### ISSUE TITLE
Option#orNull can't be used from java

### ISSUE THREAD

**Issue by scabug** [scala/bug#10006]
Scala options are a pain to use in java, but they would be much more pleasant if you could orNull them.  As it is today, they blow up with things like:

```scala
error] class AllOf implements RoutePredicate {
                       [error] blahblaaablhablah.java:24: method orNull in class scala.Option<A> cannot be applied to given types;
                       [error]   required: scala.Predef.$less$colon$less<scala.runtime.Null$,A1>
                       [error]   found: no arguments
                       [error]   reason: cannot infer type-variable(s) A1
                       [error]     (actual and formal argument lists differ in length)
                       [error]     String sanitizedPath = opt.orNull();
                       [error] Compile failed at Oct 24, 2016 1:38:55 PM [0.221s]

               compile(blabhlahblahblahbl/predicates:predicates) failed: Zinc compile failed.
```

**Comment by SethTisue** [comment]
it's not clear to me if this is even actionable (I suspect it is not, but I could easily be wrong)

I'm going to close the ticket, but we can reopen if someone can propose a solution plan. otherwise it's too open-ended for scala/bug

**Comment by Jasper-M** [comment]
`scala-java8-compat` contains a conversion between `Option` and `Optional`. That's really the best you can do here, I think...

**Comment by NthPortal** [comment]
The purpose of the signature for `Option.orNull` is to prevent you from attempting to make non-nullable types (e.g. `Int`) `null` (I believe). You can still use `Option.getOrElse(null)` from Java though.
