### ISSUE TITLE
Pattern matching tuples fails to produce exhaustivity warning

### ISSUE THREAD

**Issue by scabug** [scala/bug#10019]
This feels like a bug?

Compare:

```scala
object Bug {
  sealed case class Foo(e: Option[Int])

  def loop(t: Foo): Nothing = t match {
    case Foo(Some(_)) => ???
  }
}
/*
match may not be exhaustive.
[warn] It would fail on the following input: Foo(None)
[warn]   def loop(t: Foo): Nothing = t match {
[warn]                               ^
*/
```

to this, which is also not exhaustive but produces no warning:

```scala
object Bug {
  sealed case class Foo(e: Option[Int])

  def loop(s: Foo, t: Foo): Nothing = (s,t) match {
    case (Foo(Some(_)), _) => ???
  }
}
```

I know `Tuple2` isn't sealed, but that doesn't seem to explain it (problem occurs even using a custom sealed replacement for `Tuple2`, plus the stdlib tuples participate successfully in match exhaustivity checks in some other contexts).

Any ideas?

**Comment by SethTisue** [comment]
@aklosslp that looks like #5365 to me

**Comment by aklosslp** [comment]
Yep I agree.

**Comment by dwijnand** [comment]
> I know `Tuple2` isn't sealed

It's `final` which is even better!  So that should not matter.

**Comment by dwijnand** [comment]
> But this code issues no warnings:
> 
> ```scala
> def foo(t1: List[T], t2: List[T]) = (t1, t2) match {
>   case (Nil, Nil) => ()
>   case (List(_), List(_)) => ()
> }
> ```
> 
> even though there are still missing cases.

Btw, that's because that's using `List#unapplySeq`, which is #9232 (and specifically mentions `List`).  It's particularly bad because `::`'s `toString` returns `List(_)` instead of `_ :: _`.

(I'm going to consider this issue specific to tuples.)

**Comment by dwijnand** [comment]
> I found this surprising too:
> 
> ```scala
> def foo(t1: List[T], t2: List[T]) = (t1, t2) match {
>   case (Nil, Nil) => ()
> }
> ```
> 
> This code issues a warning:
> 
> ```scala
> [warn] It would fail on the following inputs: (List(_), List(_)), (List(_), Nil), (Nil, List(_))}
> ```
> 
> But this code issues no warnings:
> 
> ```scala
> def foo(t1: List[T], t2: List[T]) = (t1, t2) match {
>   case (Nil, Nil) => ()
>   case (List(_), List(_)) => ()
> }
> ```
> 
> even though there are still missing cases.

Relevant commentary in the pattern matcher:

```
      // special-case: interpret pattern `List()` as `Nil`
      // TODO: make it more general List(1, 2) => 1 :: 2 :: Nil  -- not sure this is a good idea...
      private val rewriteListPattern: PartialFunction[TreeMaker, Prop] = {
        case p @ ExtractorTreeMaker(_, _, testedBinder)
          if testedBinder.tpe.typeSymbol == ListClass && p.checkedLength == Some(0) =>
            uniqueEqualityProp(binderToUniqueTree(p.prevBinder), unique(Ident(NilModule) setType NilModule.tpe))
      }
```

😄

I'm going to leave out this part, as, as I said, it's more generally covered by #9232.

**Comment by dwijnand** [comment]
Fixed in https://github.com/scala/scala/pull/9147.
