### ISSUE TITLE
Improve REPL display of methods

### ISSUE THREAD

**Issue by scabug** [scala/bug#10023]
The creation of  a method in the REPL like e.g. 

```scala
def foo(in: Int): String = ???
```

will result in an output like 

```scala
foo: (in: Int)String
```

which is almost (but not quite!) valid Scala syntax and therefore rather confusing.

Instead the output should
- valid scala syntax
- and maybe a helpful message that and what happened.

**Comment by SethTisue** [comment]
let's consolidate under #10024
