### ISSUE TITLE
Improve REPL display

### ISSUE THREAD

**Issue by scabug** [scala/bug#10024]
The current REPL output for definitions is very confusing because it is almost, but not quite valid Scala and also inconsistent.

Some examples:

```scala
scala> case class Foo()
defined class Foo
```

```scala
scala> trait Bar
defined trait Bar
```

```scala
scala> type Qux = Nothing
defined type alias Qux
```

```scala
scala> val a = 1
a: Int = 1
```

```scala
scala> var b = 1
b: Int = 1
```

The Scala REPL's response should be more consistent reporting about definitions.
Possible solutions
- no output in the success case (as does the Python REPL)
- display the type definition (as it is currently the case but without "defined" )
- display the type definition as valid Scala
- ...

**Comment by eed3si9n** [comment]
This and related REPL display issues might be good first issue if it were defined clearly on what's expected at the end.

For example, this issue says "no output in the success case (as does the Python REPL)" as possible solution while #7960 says it would be better to include `val` or `val`:

```
scala> var x = 5
var x: Int = 5
```

**Comment by SethTisue** [comment]
> no output in the success case (as does the Python REPL)

I agree with #7960. I think it's valuable to show the types, and it's valuable to show the computed value, too:

```
scala> val x = 2 + 2
x: Int = 4
```

**Comment by SethTisue** [comment]
closed #7960 and #10023, consolidating here.

**Comment by SethTisue** [comment]
note that anyone doing nontrivial REPL work should target 2.13, since the REPL code changed around between 2.12 and 2.13 so merging changes forward is extra work we'd rather not do.

**Comment by df3n5** [comment]
Hi,

I'm willing to pick this up, what exactly is the desired outcome? Do we want nothing in the case of a type definition, and to keep var and val definitions the same? Something like this:
```scala
scala> case class Foo()
scala> val (x, y) = (42, 17)
x: Int = 42
y: Int = 17
```

**Comment by SethTisue** [comment]
> I'm willing to pick this up

awesome!

> what exactly is the desired outcome

this is all open-ended and open to debate. these tickets were opened by interested individuals with opinions, they aren't the outcome of any process.

if something is easy to tweak you might just go ahead and we can bikeshed it after, if something looks like bunch of work then you might check first whether people think it's a good idea

re: "nothing in the case of a type definition", sounds good to me

re: "keep var and val definitions the same", #7960 (which is now consolidated here) proposes adding `val` or `var` to bring it closer to being legal Scala that's printed

**Comment by df3n5** [comment]
Cool, I'll have a go at changing it to what I suggested above and come back here for feedback once it is ready or I reach a stumbling block.

**Comment by df3n5** [comment]
@psilospore No, I have no time for contributions at the moment. Good luck with it!

**Comment by SethTisue** [comment]
also in this area: #11416

**Comment by bishabosha** [comment]
I'm currently working on this now, with the following choices:

**`val`/`var`**
```scala
scala> lazy val x = ""
lazy val x: String = <lazy>

scala> var mut = 0
var mut: Int = 0

scala> mut = 1
// mutated mut
```

**`def`/`macro`**
```scala
scala> def foo = ""
def foo: String = <method>

scala> def foo[T: Numeric, A: Numeric](x: T): String = x.toString
def foo[T, A](x: T)(implicit evidence$1: Numeric[T], evidence$2: Numeric[A]): String = <method>

scala> def m(x: => Int): Int = macro ???
// defined term macro m(x: => Int): Int
```

**definitions**
```scala
scala> object A
// defined object A

scala> trait B
// defined trait B

scala> class C
// defined class C
```
