### ISSUE TITLE
Accept leading semi for line comment

### ISSUE THREAD

**Issue by scabug** [scala/bug#10105]
Weary of endless github wars over comment formatting? Wouldn't it be nice if Scala recovered the semicolon, which is on the brink of extinction, for line comments? Only if it is the leading non-whitespace.

```scala
  // boring
  val x = 42

  /** Annoying sparkles in my eyes.
    * With the weird indentation.
    */
  val y = 17

  ; exciting! punctuated equilibrium in language evolution
  ; I could go on and on about how it doesn't look like Java.
  def z = ???

  ; I space them qua separators
  for (v <- vs ; w <- ws if v < w) yield (v, w)
```

**Comment by som-snytt** [comment]
This effort has been superseded by Commentless Scala, which removes support for all comments, in favor of the commentator interpolator. SIP # is TBD, but the feature is tentatively scheduled for 2.14.
