### ISSUE TITLE
Support templating (replating)

### ISSUE THREAD

**Issue by scabug** [scala/bug#10111]
Tools (REPLs) should be able to submit snippets for "wrapping" and compilation.

The wrapping should be customizable as a custom templating phase.

It should be possible for the same custom template to be used with various tools, such as distro REPL and Ammonite.

**Comment by som-snytt** [comment]
Not actionable. This was before the great repl schism. But scala-cli is asking the same questions about snippets again, so it would have been nice. As with Almond Joy and Mounds, sometimes you feel like a nut and you want a particular (candy) wrapper.
