### ISSUE TITLE
Fix sbt interface

### ISSUE THREAD

**Issue by scabug** [scala/bug#10110]
The interface with sbt is stale and rife with comments about compatibility with ancient versions of scala.

sbt needs a simple hook for postInit actions.

**Comment by som-snytt** [comment]
Also align reporting and configuration (such as `-Xmaxerrs`).

**Comment by SethTisue** [comment]
I suggest we not keep this open unless someone can clearly state what ought to be fixed and _why_ it ought to be fixed?

**Comment by dwijnand** [comment]
I'm not breaking any new ground, but just to lay it out: as a tool (sbt) that supports multiple previously released versions of Scala, it can only use the APIs that are available for that version (as we're not inclined to releasing new minor releases of, say, 2.10).

Perhaps there are still APIs in the 2.12 and 2.13 trees that sbt doesn't used (having migrated to better newer ones) so those could now go.  But my impression is it's only a number of lines, at most the odd class and/or odd file.  Not something that, IMO, is worth dropping in a minor version (e.g 2.13.5) and force ("break") some other tool that hadn't yet migrated.
