### ISSUE TITLE
'recursive value needs type' when using string interpolation linter and "suspicious" definition

### ISSUE THREAD

**Issue by scabug** [scala/bug#10125]
Here is code that compiles fine without linter and fails when linter is enabled:

```scala
object Foo {
  implicit class HasIr(s: String) {
    def ir: Int = 1234
  }

  val bar = "$bar".ir
}
```

When adding `scalacOptions += "-Xlint"`, the compilation fails as follows:

```scala
[error] /home/hhrutz/Documents/temp/interp_bug/src/main/scala/foo/Foo.scala:8: recursive value bar needs type
[error]   val bar = "$bar".ir
[error]             ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

Obviously the linter doesn't get to warn me about possible missing string interpolation (the dollar is intended in my case and not an interpolator), but then gets stuck assuming that `$bar` is interpolated `bar`.

**Comment by som-snytt** [comment]
```
@Value("${myProperty}")
var myProperty: String = _
```
