### ISSUE TITLE
Make PartiallyOrdered a universal trait

### ISSUE THREAD

**Issue by scabug** [scala/bug#10128]
[`PartiallyOrdered` is a non-universal trait](https://github.com/scala/scala/blob/v2.12.1/src/library/scala/math/PartiallyOrdered.scala#L19), though it seems like it could be made one "for free".

I ran into this while trying to make a value-class that extends `PartiallyOrdered`.

**Comment by atiqsayyed** [comment]
I wanna pick this one, is there anything that i should know apart form obvious comments above??..

**Comment by SethTisue** [comment]
I suspect a fix would need to target 2.13.x because of binary compatibility
