### ISSUE TITLE
TreeMap.zipWithIndex loses the TreeMap's custom ordering

### ISSUE THREAD

**Issue by scabug** [scala/bug#10146]
When one uses zipWithIndex on a TreeMap, and the latter was created using a non-default ordering, the resulting map again receives the default ordering (coming from the implicit parameter).

The result is something unexpected, from the point of view of the end user: the map's ordering is suddenly lost. An artificial example from REPL which illustrates the issue.

```
scala> val reversedIntOrdering = implicitly[Ordering[Int]].reverse
reversedIntOrdering: scala.math.Ordering[Int] = scala.math.Ordering$$anon$4@2e38d44e

scala> val treeMap = TreeMap(2 -> "a", 3 -> "b", 4 -> "c", 5 -> "d")(reversedIntOrdering)
treeMap: scala.collection.immutable.TreeMap[Int,String] = Map(5 -> d, 4 -> c, 3 -> b, 2 -> a)

scala> treeMap.zipWithIndex.foreach(println)
((2,a),3)
((3,b),2)
((4,c),1)
((5,d),0)
```

What is even funnier, if the map loses its TreeMap type, the result is "regular" again:

```
scala> val anyMap: Map[Int, String] = treeMap
anyMap: Map[Int,String] = Map(5 -> d, 4 -> c, 3 -> b, 2 -> a)

scala> anyMap.zipWithIndex.foreach(println)
((5,d),0)
((4,c),1)
((3,b),2)
((2,a),3)
```

**Comment by magnolia-k** [comment]
In Scala 2.13.0

```scala
Welcome to Scala 2.13.0 (OpenJDK 64-Bit Server VM, Java 12.0.1).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.immutable.TreeMap
import scala.collection.immutable.TreeMap

scala> val reversedIntOrdering = implicitly[Ordering[Int]].reverse
reversedIntOrdering: scala.math.Ordering[Int] = scala.math.Ordering$Reverse@3bf3e060

scala> val treeMap = TreeMap(2 -> "a", 3 -> "b", 4 -> "c", 5 -> "d")(reversedIntOrdering)
treeMap: scala.collection.immutable.TreeMap[Int,String] = TreeMap(5 -> d, 4 -> c, 3 -> b, 2 -> a)

scala> treeMap.zipWithIndex.foreach(println)
((5,d),0)
((4,c),1)
((3,b),2)
((2,a),3)
```

**Comment by Jasper-M** [comment]
I don't see how the map could keep its non-default ordering, since the type of the key changes.
Note that in 2.13 the result of `zipWithIndex` is an `Iterable` and not a `TreeMap`.

**Comment by magnolia-k** [comment]
@Jasper-M 
I'm sorry, but I didn't understand what the comment meant.
Do you claim that you can't reach the reason for this behavior in Scala 2.13.0?

**Comment by SethTisue** [comment]
I'm also puzzled by Jasper-M's remark — if we're returning an `Iterable` now, then surely we could have it be ordered any way we want, including order-preserving? @scala/collections

**Comment by SethTisue** [comment]
Jasper's comment references 2.13.

In any case, the 2.13 ordering is as desired, so we should close this, I think. @som-snytt but feel free to open a new ticket with your new, somewhat different case

**Comment by som-snytt** [comment]
OK. I thought the fix would be similar for sorted things, but the map case requires defining that the result keeps iteration order.

I read or misread the comment as "impossible in 2.12, but note in 2.13 the signature changed". But neither here nor there.

Neither hair nor Nair. (Saving that for later.)
