### ISSUE TITLE
AssertionError should be considered fatal

### ISSUE THREAD

**Issue by scabug** [scala/bug#10166]
`AssertionError` s, being outside the list of fatal errors defined for `NonFatal`, are caught by code matching on `NonFatal` and with the `Try` construct - making it easy for failed assertions to be inappropriately handled or silently discarded where they should be considered fatal application failures and fail loudly to inform the developer/tester that a program assumption/assertion has been broken and requires remediation.

**Comment by Ichoran** [comment]
As I commented on the PR, I think `AssertionError` is misnamed.  It is used for things like bounds checks, which makes it no different conceptually (in many cases, anyway) from an `ArrayIndexOutOfBoundsError`.  Also, switching it now will probably break a bunch of code that relied on catching assertions.

**Comment by SethTisue** [comment]
PR: https://github.com/scala/scala/pull/6320

**Comment by viktorklang** [comment]
Is there enough information to be able to say that "all" AssertionErrors are fatal?

**Comment by SethTisue** [comment]
@viktorklang tbh I don't really understand why any `Error` would be considered `NonFatal`. the JVM already has the `Error` vs non-`Error` distinction, I've never been especially clear on why `NonFatal` adds an additional level of classification.

**Comment by SethTisue** [comment]
is there a canonical example (or two or three) of an `Error` that you consider to be definitely `NonFatal`?

**Comment by NthPortal** [comment]
for `AssertionError` in particular, yes - see [this comment](https://github.com/scala/scala/pull/6320#issuecomment-367811151)

**Comment by NthPortal** [comment]
most of the discussion for this seems to have happened at scala/scala#6320 (don't know why)

**Comment by viktorklang** [comment]
@SethTisue «An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch. » - https://docs.oracle.com/javase/8/docs/api/java/lang/Error.html

The problem is that there are quite a few unreasonable applications out there, and since Error is extendable it is impossible to say that all Errors are fatal.

[ThreadDeath](https://docs.oracle.com/javase/8/docs/api/java/lang/ThreadDeath.html), for instance, is a NonFatal Error.

**Comment by NthPortal** [comment]
to be fair, `ThreadDeath` is deprecated(ish)

**Comment by viktorklang** [comment]
@NthPortal To be fair, I only checked JavaSE ;)

**Comment by lrytz** [comment]
It's a datapoint a bit far fetched, but IntelliJ shows `AssertionError` and `OutOfMemoryError` differently (red and orange). I don't know how they make the distinction.

<img width="463" alt="image" src="https://user-images.githubusercontent.com/119636/36562801-5c2d4526-1818-11e8-8226-6d1db3027375.png">

@Ichoran sorry to nit-pick, but it's `ArrayIndexOutOfBoundsException` not `-Error`.

In my understanding, the errors that are excluded in `NonFatal` are things that an application really should not try to recover from, so my tendency is to keep `AssertionError` non-fatal.

**Comment by NthPortal** [comment]
@lrytz I think that's just because `AssertionError` is usually thrown for test failure

... which is another reason it should stay non-fatal, as a good testing harness shouldn't catch fatals (although it could specifically go out of its way to catch `AssertionError` and not other fatals)

**Comment by NthPortal** [comment]
Interestingly, I get a different icon for OOM (using scalatest)

![image](https://user-images.githubusercontent.com/7505383/36564112-3b589ba8-17ea-11e8-91d0-e8b4c3efff3b.png)

(`AssertionError`, `IllegalStateException`, and `OutOfMemoryError` respectively)

**Comment by SethTisue** [comment]
looks like this is not-a-bug/wontfix

perhaps there's room for a new PR that improves the Scaladoc for `NonFatal`, though.

**Comment by SethTisue** [comment]
quoth @Ichoran on Gitter:

> "The usage of AssertionError as generated by assert is governed by practical considerations of what works rather than first principles; and as people have likely come up with different conventions that work in practice, any change is likely to be breaking. Since the lack of convention extends into usage in Java (which we cannot substantively affect), it is also not practical to develop first principles. So leaving it alone is likely the best we can manage for now."
