### ISSUE TITLE
Enter current Scala version (2.12.1) into next Debian stable (Stretch)

### ISSUE THREAD

**Issue by scabug** [scala/bug#10172]
The next Debian version, Stretch, is becoming a stable release soon, with hard freeze happening [in the next days](https://wiki.debian.org/DebianStretch). Scala is still at 2.11.8: https://packages.debian.org/sid/scala

As I understand the problem with submitting 2.12.1 is that it requires sbt to build. I think a zero-dependencies variant of building the Scala package is to simply include Paul Philips' "sbt" shell script which takes care of getting the right version of sbt when trying to build.

**Comment by SethTisue** [comment]
duplicates #9299
