### ISSUE TITLE
InnerClass entry should added to class file for references in Java Generic Signatures

### ISSUE THREAD

**Issue by scabug** [scala/bug#10180]
Related to #9937, in which the same bug in Kotlin trips up scalac.

```
$ cat sandbox/test.scala && scalac sandbox/test.scala
class C {
  class D
}

abstract class E { def foo: Option[C#D] }

$ javap -cp . -v E | tail -n 30
  #25 = Utf8               ScalaSig
{
  public abstract scala.Option<C$D> foo();
    descriptor: ()Lscala/Option;
    flags: ACC_PUBLIC, ACC_ABSTRACT
    Signature: #18                          // ()Lscala/Option<LC$D;>;

  public E();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #14                 // Method java/lang/Object."<init>":()V
         4: return
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   LE;
      LineNumberTable:
        line 5: 0
}
SourceFile: "test.scala"
RuntimeVisibleAnnotations:
  0: #6(#7=s#8)
Error: unknown attribute
  ScalaInlineInfo: length = 0xE
   01 00 00 02 00 0B 00 0C 00 00 09 00 0A 00
Error: unknown attribute
  ScalaSig: length = 0x3
   05 00 00
```

Compare with Java:

```
$ cat sandbox/Test.java && javac -d . sandbox/Test.java
class C { class D {} }
abstract class E { abstract java.util.List<C.D> foo(); }

$ javap -cp . -v E | tail -n 5
    Signature: #14                          // ()Ljava/util/List<LC$D;>;
}
SourceFile: "Test.java"
InnerClasses:
     #12= #11 of #20; //D=class C$D of class C

```

**Comment by lrytz** [comment]
[`akka.persistence.AbstractPersistentActorWithAtLeastOnceDelivery`](https://github.com/akka/akka/blob/v2.5.2/akka-persistence/src/main/scala/akka/persistence/AtLeastOnceDelivery.scala#L449) inherits [`private var unconfirmed = immutable.SortedMap.empty[Long, Delivery]`](https://github.com/akka/akka/blob/v2.5.2/akka-persistence/src/main/scala/akka/persistence/AtLeastOnceDelivery.scala#L232) where `Delivery` is an inner class, the attribute is missing. See https://github.com/scala/bug/issues/10341.

**Comment by lrytz** [comment]
Fix in https://github.com/scala/scala/pull/5925. Created a new ticket https://github.com/scala/bug/issues/10348 for the fact that the signature is `()Lscala/Option<LC$D;>;`, while it should be `()Lscala/Option<LC;.LD;>;`

**Comment by lrytz** [comment]
Oh, javac's signature is actually also `()Ljava/util/List<LC$D;>;`, so maybe there's no issue there.

**Comment by lrytz** [comment]
Earlier PR: https://github.com/scala/scala/pull/5690
