### ISSUE TITLE
SeqView violated rules for java.lang.Object.equals

### ISSUE THREAD

**Issue by scabug** [scala/bug#10201]
In [JavaDoc for Object.equals](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html) 

> It is reflexive: for any non-null reference value `x`, `x.equals\(x\)` should return `true`.

However, SeqView does not conform the rule:

```scala
Welcome to Scala 2.12.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_102).
Type in expressions for evaluation. Or try :help.

scala> val v = Seq(0.0, 1.0).view.map{ d => d + math.random }
v: scala.collection.SeqView[Double,Seq[_]] = SeqViewM(...)

scala> v == v
res0: Boolean = false
```

**Comment by szeiger** [comment]
Fixed in 2.13.x for 2.13.0-M4. Views are compared by identity in the new collection library.
