### ISSUE TITLE
Incorrect output in toHexString applied to Byte and Short values

### ISSUE THREAD

**Issue by scabug** [scala/bug#10216]
This is my very first issue submission to Scala, so I apologize in advance for any mistakes I might have made in filling out the different fields.

Calling `toHexString` method on numeric types other than Int will produce unexpected output. I believe that `toHexString` is not implemented in `Byte` and `Short` and an implicit conversion to `Int` is happening.

```scala
scala> -1.toByte.toHexString
res2: String = ffffffff
// should be "ff"

scala> -1.toShort.toHexString
res3: String = ffffffff
// should be "ffff"

scala> -1.toHexString
res4: String = ffffffff
// is correct

scala> -1.toLong.toHexString
res5: String = ffffffffffffffff
// is correct
```

**Comment by atiqsayyed** [comment]
@SethTisue I'm confused after going through the discussions, is it concluded that the toHexString function would be deprecated??

**Comment by Ichoran** [comment]
I'm not convinced deprecation is a better solution than making it work properly for every numeric type, like we do with min and max and so on.

**Comment by atiqsayyed** [comment]
@Ichoran it makes sense not to deprecate it rather find a proper solution for it

**Comment by som-snytt** [comment]
`toBinaryString` and `toOctalString` show the same behavior. Hence the sense of whack-a-mole in the previous discussion.

**Comment by Ichoran** [comment]
All the moles need to be whacked.  There aren't that many of them.  You don't need to pave everything over with concrete to solve the problem.

**Comment by niebloomj** [comment]
What is the conclusion? Deprecating toHexString or creating the richness for the other types?

**Comment by niebloomj** [comment]
@Ichoran

**Comment by som-snytt** [comment]
In every generation, one is chosen to whack the moles. Endowed with extraordinary skill and patience, a whacker will rise after some years to find the moles and then whack them, and the moles will fall.

**Comment by niebloomj** [comment]
lol i just want a first issue to work on haha

**Comment by martijnhoekstra** [comment]
Then just maybe, you are the chosen one. Only by whacking the moles we can
be sure.

**Comment by niebloomj** [comment]
Can someone assign this to me so that there isn't duplicated work? Thank you. The moles will be whacked.

**Comment by NthPortal** [comment]
Please consider this ticket assigned to you. GitHub only allows assigning to organisation members, but if someone else looks at this ticket they will see your comment.

**Comment by NthPortal** [comment]
```scala
scala> -1.toBinaryString
res0: String = 11111111111111111111111111111111

scala> -1.toByte.toBinaryString
res1: String = 11111111111111111111111111111111
```

@nogurenn yes

**Comment by som-snytt** [comment]
Sorry I missed the updated conversation. I gave this a nudge.

Maybe the test could be further improved as an exercise? Normally you would expect a junit test, but I left it as partest because of possible issues around widening or implicit selection, it's better to test the compiler being built.

**Comment by som-snytt** [comment]
Forgot to add that the fix is not binary compatible. Luckily 2.14 milestone is due by end of the year.

**Comment by som-snytt** [comment]
Not only is this out of scope for Scala 2, the PR was never merged at `scala-library-next`.
