### ISSUE TITLE
HTML generated by Scaladoc should embed all necessary font files

### ISSUE THREAD

**Issue by scabug** [scala/bug#10235]
Scaladoc-generated HTML now uses the Open Sans font for its body text. However, the default lib/index.css bundles and embeds only the regular weight of Open Sans, omitting the bold weight, and italic variants. Consequently, bold/strong styling in HTML is not displayed correctly. For example, the headings in the online API documentation on the following page are barely distinguishable from normal text (at least, when viewed in Chrome), since the proper bold-weight of the Open Sans font is not available:

    [http://www.scala-lang.org/api/2.12.1/]

Scaladoc-generated HTML should bundle and embed all relevant variants of the fonts that it uses.

**Comment by Lacaranian** [comment]
I'll take a look at this one, if that's all right.
