### ISSUE TITLE
Type equality wrong for reified path dependent types

### ISSUE THREAD

**Issue by Jasper-M** [scala/bug#10254]
```
scala> import scala.reflect.runtime.universe._
import scala.reflect.runtime.universe._

scala> val a = new {type T = Int}
a: AnyRef{type T = Int} = $anon$1@26e22aaa

scala> weakTypeOf[a.T] =:= typeOf[Int]
res4: Boolean = false

scala> weakTypeOf[a.T] <:< typeOf[Int]
res5: Boolean = true
```

But if `a.T` is strictly a subtype of `Int`, how come the following works?

```
scala> val int: Int = 42
int: Int = 42

scala> val b: a.T = int
b: a.T = 42
```

In other words:  `(weakTypeOf[a.T] =:= typeOf[Int]) == false` is lying. Or am I missing something?

**Comment by SethTisue** [comment]
I'm not an expert in this area, but since nobody else has responded in all this time, I think we should err on the side of assuming this is intended behavior of `WeakTypeTag` that it does not resolve the path-dependent type (`a.T`) into a concrete type `Int`.
