### ISSUE TITLE
Eliminate LaTeX-style quotations from compiler output

### ISSUE THREAD

**Issue by lrytz** [scala/bug#10253]
Some compiler messages use LaTeX-style quotations, for example:

```scala
scala> object T {
     |   def x = 0
     |   locally {
     |     import T.x
     |     def x = 1
     |   }
     | }
<console>:15: warning: imported `x' is permanently hidden by definition of method x
           import T.x
                    ^
defined object T
```

As you can see, this upsets GitHub's Scala syntax highlighter. What a convincing reason to change a programming language!

**Comment by som-snytt** [comment]
The reporter can detect the orphan back-tick and fix the trailing single quote (to paired single quotes).

**Comment by thestuckster** [comment]
Hey, I'd like to look into this as my first contribution. Can you give any more information?

**Comment by som-snytt** [comment]
@thestuckster one way to get unstuck is to list the unbalanced latex strings:
```
$ grep \` $(find src -name "*.scala") | grep \" | grep \'
```
Then change the trailing single quote to back quote, or maybe conversely.

**Comment by thestuckster** [comment]
I have opened a PR here: https://github.com/scala/scala/pull/6397
Please let me know if something is amiss

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/6418 seems abandoned. someone else want to pick this one up...?

**Comment by Jasper-M** [comment]
Does this ticket extend to things like scaladoc comments as well?

Cause right now, opening e.g. Parsers.scala in my usual editor is pure horror:
<img width="599" alt="screen shot 2018-11-06 at 14 58 19" src="https://user-images.githubusercontent.com/3708353/48069235-419ea600-e1d5-11e8-8191-671f3db153d6.png">

It's probably more an issue of the syntax highlighter, but anyway...

**Comment by SethTisue** [comment]
> Does this ticket extend to things like scaladoc comments as well?

sure, feel free to broaden it if you're feeling ambitious.

we'd be happy to receive a PR that addresses either category, or both.

**Comment by SethTisue** [comment]
note that any PR on this should target 2.13.x, since merging it forward from 2.12.x would be annoying
