### ISSUE TITLE
Scaladoc Source link are NotFound (404) for v2.12.2

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10263]
Go To
http://www.scala-lang.org/api/current/scala/collection/immutable/Queue.html

Click on Source: Queue.scala

It opens: https://github.com/scala/scala/tree/v2.12.2/src/library/scala/collection/immutable/Queue.scala#L1

v2.12.2 does not exist yet

**Comment by SethTisue** [comment]
this is a known problem and I could have sworn there's a ticket on it somewhere, but I can't seem to find it. at https://scala-ci.typesafe.com/job/scala-2.12.x-release-main/760/console we see the release-main script running release-website-update-api; the latter should be changed to be manually triggered except for nightlies (and the release steps, which we're currently copying-and-pasting from release ticket to release ticket in the scala-dev repo, updated to include the additional manual step)

**Comment by adriaanm** [comment]
usually we tag immediately with the release, but this time we're letting the staged jars age for a few days in case of regressions

**Comment by adriaanm** [comment]
I was just thinking today how we could just cut a v2.12.2 branch until we tag.

**Comment by adriaanm** [comment]
Done.
