### ISSUE TITLE
-Xlint now exposes spurious unused imports in macro exprs

### ISSUE THREAD

**Issue by nrinaudo** [scala/bug#10270]
After upgrading to 2.12.2, I've noticed that when enabling the `-Xlint` scalac option, I get warnings on unused imports, which is a new behaviour (couldn't reproduce in 2.10.x, 2.11.x or 2.12.1).

While it seems like desirable behaviour on the face of it, it breaks builds that:
* use `tut` for documentation generation
* enable `-Xlint`
* enable `-Xfatal-warnings`

The workaround is pretty simple - do not use `-Xlint`, at least in the REPL and / or in `tut`, but the fact that it comes from `-Xlint` is not obvious and took me a while to work out. I'm not suggesting rolling back the change, but maybe at the very least including it in the release notes? I failed to find any mention of it there.

**Comment by SethTisue** [comment]
@nrinaudo @som-snytt does `-Xlint -Ywarn-unused:-import` or some such incantation work?

**Comment by som-snytt** [comment]
I think it's in the release notes? Are there release notes? Yes, you can turn off all the options individually, use `-Xlint:help` for what the options are. `-Xlint:unused` enables a subset of `-Ywarn-unused`. There's an old ticket for using `-Xlint` with REPL, but it's helpful to learn about specific interactions with other tools.

**Comment by SethTisue** [comment]
> Are there release notes?

we're using GitHub for that these days: https://github.com/scala/scala/releases/tag/v2.12.2

@nrinaudo as a result, there's no way for a non-committer to send the equivalent of a pull request against the notes, but feel free to put a proposed release-notes change, with the precise wording you suggest, in a comment or issue and we'll take care of it.

> There's an old ticket for using -Xlint with REPL

#7722

**Comment by fommil** [comment]
@SethTisue nope, that doesn't work. But disabling the `unused` linter, and then re-enabling the bits you want does... as simple as this:

```scala
    // WORKAROUND https://github.com/scala/scala/pull/5402
    scalacOptions := {
      val orig = scalacOptions.value
      CrossVersion.partialVersion(scalaVersion.value) match {
        case Some((2, 12)) => orig.map {
          case "-Xlint"               => "-Xlint:-unused,_"
          case "-Ywarn-unused-import" => "-Ywarn-unused:imports,-patvars,-privates,-locals,-params,-implicits"
          case other                  => other
        }
        case _             => orig
      }
    }
```

**Comment by ochrons** [comment]
I'm experiencing the same erroneous "unused import" warnings in a few places in my Diode library:

https://github.com/suzaku-io/diode/blob/master/diode-core/shared/src/test/scala/diode/ModelRWTests.scala#L55-L56
```scala
import PartialToo._
val r5    = mr.zoom(m => PartialToo(m.c.s, m.a.i))
```
and

https://github.com/suzaku-io/diode/blob/master/diode-core/shared/src/test/scala/diode/EffectTests.scala#L41-L48

```scala
      'after - {
        import diode.Implicits._
        val now = System.currentTimeMillis()
        efA.after(100.milliseconds).map(x => s"$x$x").toFuture.map { z =>
          assert(z == "AA")
          assert(System.currentTimeMillis() - now > 80)
        }
      }
```

replacing the `import XYZ` with `implicit val xyz = XYZ` provides a workaround (or by explicitly passing the implicit parameter)

All of these worked in 2.12.1 and in 2.11.11

My scalac options are:
```scala
  scalacOptions := Seq(
    "-deprecation",
    "-encoding",
    "UTF-8",
    "-feature",
    "-unchecked",
    "-language:experimental.macros",
    "-Xfatal-warnings",
    "-Xlint",
    "-Yno-adapted-args",
    "-Ywarn-dead-code",
    "-Ywarn-numeric-widen",
    "-Ywarn-value-discard",
    "-Xfuture"
  ),
```

**Comment by stuhood** [comment]
And confusingly,
```
-Xlint:-unused,_
```
...works in concert with `-Xwarn-unused`, but:
```
-Xlint:_,-unused
```
does not.

**Comment by som-snytt** [comment]
@stuhood I fixed that under the other ticket at https://github.com/scala/scala/pull/5879

I didn't actually know that `getopt` was still one of the five hardest problems in computer science. I guess I have to read more history books.

**Comment by som-snytt** [comment]
The reporter could say why a warning was emitted. I have an alias for `scalac` which enables `-deprecation`. If it warns about a deprecation, it could say "Warnings were emitted because -deprecation is enabled." Or "Warnings were emitted because -deprecation -Ywarn-unused:fizzbot is enabled."

**Comment by dwijnand** [comment]
@som-snytt Is this a bug?

```scala
$ scala -Xlint -Xlint:-unused,_
Welcome to Scala 2.12.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.JavaConverters._
<console>:11: warning: Unused import
       import scala.collection.JavaConverters._
                                              ^
import scala.collection.JavaConverters._
```

**Comment by som-snytt** [comment]
@dwijnand https://github.com/scala/scala/pull/5879

The bug is that `-Xlint` sets the `-Ywarn-unused` settings as though they were set explicitly.

I joked on one of these threads that `getopt` is still one of the hardest problems in computer science.

My guess is that `-Xlint:-unused -Ywarn-unused` will then leave the subset of `-Xlint:unused` warnings turned off, because explicit-off trumps enable-all.

Probably the aliasing is too confusing, and there should be only `-Ywarn-unused:params,patvars`, the warnings which don't have `-Xlint` options.

**Comment by som-snytt** [comment]
I started using utest for all my light-weight testing needs.

```
import utest._

object Implicits {
  implicit class `strung out`(val s: String) {
    def greeting = s"hello, $s"
  }
}

object Testy extends TestSuite {
  //import Implicits._  // OK
  val tests = Tests {
    //import Implicits._   // unused
    * - {
      import Implicits._  // unused
      assert("world".greeting == "hello, world")
    }
  }
}
```
