### ISSUE TITLE
ETA Expansion working on function objects in member scope

### ISSUE THREAD

**Issue by YuvalItzchakov** [scala/bug#10275]
Tested Scala versions: 2.12.1, 2.11.8

The following code compiles:

```scala
object Test {
  def sum(i: Int, j: Int) = i + j

  val f = sum _
  val g = f _
}
```

While this produces a compilation error:

```scala
object Test {
  def um(): Unit = {
    def sum(i: Int, j: Int) = i + j

    val f = sum _
    val g = f _
    ()
  }
}

[error] _ must follow method; cannot follow (Int, Int) => Int
[error]     val g = f _
[error]             ^
[error] one error found
```

This seems inconsistent, expanding a function object should fail regardless of scope?

**Comment by lrytz** [comment]
Nice one..! The difference is that there's a setter **method** generated for `Test.f`, which is picked by eta-expansion:

```
scala> object T {
     |   val f = (x: Int) => x
     |   val g = f _
     | }
defined object T

scala> T.f
res6: Int => Int = T$$$Lambda$1217/1693193305@4b3ad7ca

scala> T.g
res7: () => Int => Int = T$$$Lambda$1218/447482439@6caeba36
```

**Comment by YuvalItzchakov** [comment]
Aha, interesting. I wonder how the setter method being available effects ETA expansion. Is part of the algorithm searching for one?

**Comment by lrytz** [comment]
So this is probably "not a bug", but a warning (probably under `-Xlint`) would be useful when eta-expanding a getter.

**Comment by YuvalItzchakov** [comment]
But doesn't ETA expansion work only for method -> function conversions?

**Comment by lrytz** [comment]
`Test.f` **is** a method, the field `f` is private.

```
$ scala -Xprint:typer
scala> object T { val f = (x: Int) => x }
        object T extends scala.AnyRef {
          def <init>(): T.type = {
            T.super.<init>();
            ()
          };
          private[this] val f: Int => Int = ((x: Int) => x);
          <stable> <accessor> def f: Int => Int = T.this.f
        }
```

Eta-expanding over a parameterless method gives a `Function0`

```
scala> object T { def f = 0 }
defined object T

scala> T.f _
res0: () => Int = $$Lambda$1033/368242083@34cf294c
```

**Comment by YuvalItzchakov** [comment]
Oh, I see now. Sine `f` gets has a *getter* of arity-0 basically, the expansion is performed on it. A tricky one :)

**Comment by lrytz** [comment]
> expansion of a function f to a private field with a getter an implementation detail

AFAICT that's in the language specification http://www.scala-lang.org/files/archive/spec/2.12/04-basic-declarations-and-definitions.html#variable-declarations-and-definitions

**Comment by YuvalItzchakov** [comment]
But `f` is a `val` here, not a `var`.

**Comment by lrytz** [comment]
Good point, I'd say it's an oversight.

**Comment by som-snytt** [comment]
Although my mental model is that val is a var without a setter, they also differ because of "constant value def" semantics.

Also, there are other differences between member-defining defs and locals, namely, overloading of locals is not allowed.

Maybe we need a prominent grid of these competing differences, and also a way to say in REPL which "mode" you're in. Right now, REPL defs are members, but it could be otherwise.

**Comment by som-snytt** [comment]
Deprecated, with subsequent warning knobs. https://github.com/scala/scala/pull/8836
