### ISSUE TITLE
Puzzling linter message for private var that is never updated.

### ISSUE THREAD

**Issue by tpolecat** [scala/bug#10282]
If you create a class with a private var that is never updated you get a puzzling linter warning:

```scala
scala> class A { private var x = 1; val y = x }
<console>:11: warning: private setter of x in class A is never used
       class A { private var x = 1; val y = x }
                             ^
```

Since users don't typically know that getter/setter pairs are generated it might be more useful to say something like `private var x in class A is never updated and could be a val`, or similar.

This is in 2.12.2 with `-Xlint`.

**Comment by som-snytt** [comment]
The wording is inherited from `-Ywarn-unused` in 2.12.1. The workaround is to make it `private[this]` so it doesn't warn at all. When I noticed the wording, I was too tired to bust up the tidy code.

I'm not sure that the equivalence of vars and get/setters isn't widely known, at least among Java refugees. But maybe it could say "synthetic setter `x_=` of `x`".

**Comment by tpolecat** [comment]
> I'm not sure that the equivalence of vars and get/setters isn't widely known, at least among Java refugees.

Since it's normally observed only when calling from Java it's easy to forget. For me anyway. I never think about getters and setters for fields because there's no reason to think they're there.

**Comment by som-snytt** [comment]
The browser tab just says, `Puzzling linter mess...`.

**Comment by som-snytt** [comment]
That old reference was a typo...

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6190
