### ISSUE TITLE
filter without withFilter

### ISSUE THREAD

**Issue by Blaisorblade** [scala/bug#10286]
In 2.11 filter was rewritten to withFilter, not so in 2.12. Shouldn't all collections have either both or none? http://www.scala-lang.org/api/current/scala/util/Either$$RightProjection.html (and http://www.scala-lang.org/api/current/scala/util/Either$$LeftProjection.html) don't (see also
https://github.com/scala/bug/issues/10285).

**Comment by Blaisorblade** [comment]
More generally: a guideline for this would be nice. I haven't done nearly enough research to be confident of what should happen (sorry)—but `withfilter` isn't mentioned in https://github.com/scala/scala/blob/v2.12.2/src/library/scala/util/Either.scala.

In this case (there might be more) I suspect `filter` should be deprecated/renamed (because of #10285), but "we decided to not add `withFilter` because `filter` makes no sense" doesn't sound too convincing.

**Comment by SethTisue** [comment]
not clear if there's something actionable here, or whether it's still applicable in 2.13. closing unless/until it becomes clearer
