### ISSUE TITLE
scala REPL launcher seem to have a regression since 2.11.8

### ISSUE THREAD

**Issue by hochgi** [scala/bug#10284]
@som-snytt's example from gitter:
```bash
$ ./scala-2.11.8/bin/scala -nc -i clue.sc -e 'println(greeting) ; sys.exit(0)'
hello

$ scala -nc -i clue.sc -e 'println(greeting) ; sys.exit(0)'
C:\cygwin64\tmp\scalacmd4028831356272316352.scala:1: error: not found: value greeting
println(greeting) ; sys.exit(0)
        ^
```
Also occurred on ubuntu 16.04.
The problem manifests in both 2.11.11 & 2.12.2 (didn't checked other versions)

**Comment by hochgi** [comment]
providing a workaround @som-snytt wrote on gitter channel, for anybody that may be intrested:  
> ... You can just use -I instead of -i due to scala/scala@99dad60 The difference is that -i is now a "paste" and -I is line-by-line, corresponding to :paste and :load. I'll contribute a patch to accommodate using -i x.scala -e expr.

**Comment by som-snytt** [comment]
`-I` is the old `-i` to load a file line-by-line, and `-i` now does a paste.

**Comment by som-snytt** [comment]
The help message isn't correct when it says `-e` is like entering the expression into REPL; it's actually like running it as a script, which is what it actually does.

It's a conundrum whether to take `-e` as a script (and therefore eligible to be submitted to a compiler daemon) or just spin up REPL (which is more or less equivalent for the `-nc` case).

If a script overloads a method, for example, the difference in how the snippet is embedded is detectable:

```
$ scala -I dbl.sc
Welcome to Scala 2.12.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111).
Type in expressions for evaluation. Or try :help.

scala> f("hi")
res0: String = string hi

scala> f(42)
<console>:13: error: type mismatch;
 found   : Int(42)
 required: String
       f(42)
         ^

scala> :quit

$ scala -nc -I dbl.sc -e "println(f(42))"
int 42

```
Another question is why wasn't daemonization ever realized for the interactive REPL, where quick startup is its Achilles' heel? Resident compiler bugs? The daemon could always keep a spare compiler on hand to use for instant `:reset`.

**Comment by som-snytt** [comment]
The current behavior of `-e` doesn't seem useful to me.

Is it reasonable to say that the help message is right, it should show me REPL output, maybe without the documentary `:quit`.

I'm sad when I see example code with println everywhere instead of relying on REPL facilities.

```
$ scala -nc -e "42"
C:\cygwin64\tmp\scalacmd5987127363290358611.scala:1: warning: a pure expression does nothing in statement position; multiline expressions may require enclosing parentheses
42
^

$ skala -nc -e "42"
res0: Int = 42
:quit
```

What if I want to see more than one expression? Why doesn't `-e "42 ; 17"` work? Why doesn't REPL show me every computed value that is not `Unit`?

**Comment by som-snytt** [comment]
The current runner doesn't actually respect both `-e` and a thing to run:

```
$ scala -nc hi.sc
hi there

$ scala -nc -e "println(42)" hi.sc
42

```
Is this desirable behavior:
```
$ scala -e "println(runtime.ScalaRunTime.stringOf(args))"  foo bar baz
No such file or class on classpath: foo
Array(foo, bar, baz)


```

**Comment by som-snytt** [comment]
https://github.com/scala/scala/pull/5872
