### ISSUE TITLE
Java 1.8.0_131 breaks some `super` calls inside 2.12 lambdas

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#10290]
as [reported](https://gitter.im/scala/contributors?at=5901c742c4ac989f3cb8e9bd) by @milessabin, and reproduced by myself and @dwijnand, `test/files/run/t4300.scala` (#4300) and `test/files/run/t8803.scala` (#8803) are failing now on Java 8 Update 131 with e.g.

`java.lang.IllegalAccessError: Receiver class Test$$anon$1 must be the current class or a subtype of interface A`

I haven't isolated the exact circumstances, but both tests involve `super` within lambdas

**Comment by SethTisue** [comment]
I'm running a community build. it's still running, but the first few hours so far were all green, so apparently this isn't going to cause widespread breakage (whew!). will update status here once it finishes

**Comment by SethTisue** [comment]
Update 131 release notes: http://www.oracle.com/technetwork/java/javase/8u131-relnotes-3565278.html, and the full fix list is at http://www.oracle.com/technetwork/java/javase/2col/8u131-bugfixes-3565760.html. surprisingly, I see nothing relevant in either place (nor did Miles)

**Comment by SethTisue** [comment]
```
[info] >>> The dbuild result is------------: SUCCESS (project rebuilt ok)
```

community build is all green, so it seems this won't cause widespread breakage. whew

**Comment by lrytz** [comment]
Minimized:
```
trait A {
  def f() = println("A")
}

class B extends A {
  class C {
    def c() = B.super[A].f()
  }
}

object Test {
  def main(args : Array[String]) : Unit = {
    val b = new B()
    new b.C().c()
  }
}
```

**Comment by lrytz** [comment]
It seems that check was added here: http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/rev/0b85ccd62409#l11.66

**Comment by lrytz** [comment]
We have

```
public abstract interface A {
  public static synthetic f$(LA;)V
    // parameter final synthetic  $this
   L0
    LINENUMBER 2 L0
    ALOAD 0
    INVOKESPECIAL A.f ()V
}

public class B$C {
  public c()V
   L0
    LINENUMBER 7 L0
    ALOAD 0
    INVOKESTATIC A.f$ (LA;)V
}
```

I wonder why this worked before: `B$C` doesn't conform to `A`, so passing `this` in `B$C.c` to `A.f$` should have produced a verifier error?

**Comment by lrytz** [comment]
Indeed, on the older JVMs, a slightly modified version leads to an `IncompatibleClassChangeError`:

```
trait A {
  def bar = println("A")
  def f() = bar
}
// otherwise the same as above
```

```
java.lang.IncompatibleClassChangeError: Class B$C does not implement the requested interface A
	at A.f(Test.scala:3)
	at A.f$(Test.scala:3)
	at B$C.c(Test.scala:8)
```

**Comment by lrytz** [comment]
So in a way that's good news: the code we generate was wrong and would only not crash in the most trivial cases (on old JVMs). The difference on 1.8.0_131 is only for those trivial cases.

**Comment by lrytz** [comment]
Also to note: it's a regression in 2.12, 2.11 correctly uses the `outer` when invoking `A.f`:

```
public class B$C {
  public c()V
   L0
    LINENUMBER 7 L0
    ALOAD 0
    INVOKEVIRTUAL B$C.B$C$$$outer ()LB;
    INVOKESTATIC A$class.f (LA;)V
```

**Comment by milessabin** [comment]
I'm still seeing this on 2.13.x ... is the forward port of the fix still pending?

**Comment by lrytz** [comment]
Yes, it's here: https://github.com/scala/scala/pull/5997
