### ISSUE TITLE
Undeprecate then as an identifier

### ISSUE THREAD

**Issue by Jasper-M** [scala/bug#10309]
In Scala 2.12.2:
```scala
scala> def then = "ok"
<console>:11: warning: then is a reserved word (since 2.10.0); usage as an identifier is deprecated
       def then = "ok"
           ^
then: String
```
Since [SIP-12](http://docs.scala-lang.org/sips/rejected/uncluttering-control.html) is officially rejected, I don't think it makes much sense anymore for `then` to be deprecated as an identifier.

**Comment by joroKr21** [comment]
FTR, the SIP implemented in dotty

**Comment by Jasper-M** [comment]
I know Dotty has it, but as the SIP was rejected that's a little contradictory.

**Comment by mghildiy** [comment]
Would take it. Any pointer?

**Comment by SethTisue** [comment]
this is currently under discussion at https://contributors.scala-lang.org/t/the-state-of-then/1638

**Comment by SethTisue** [comment]
I'd be very reluctant to un-deprecate in 2.12 given that `then` is presently still a keyword in Dotty

**Comment by SethTisue** [comment]
it appears `then` is here to stay in Dotty

**Comment by som-snytt** [comment]
The error message is incorrectly worded. It could say `will be a reserved word (from 3.0)`. Also, "usage as an identifier" is redundant.
```
scala> val then = 42
           ^
       warning: then is a reserved word (since 2.10.0); usage as an identifier is deprecated
val then: Int = 42
```
Reserved word:
```
scala> val then = 42
1 |val then = 42
  |    ^^^^
  |    pattern expected
```
Or: "Martin is a reserved man."

When Hamlet says, "The funeral baked meats did coldly furnish forth the marriage tables," he meant that they were "re-served."

WWJD? They don't even bother to place the caret at the reserved word.
```
goto.java:2: error: <identifier> expected
public class goto {
            ^

goneto.java:6: error: illegal start of expression
                        goto label;
                        ^
```
The spec says
> This may allow a Java compiler to produce better error messages if these C++ keywords
incorrectly appear in programs.
