### ISSUE TITLE
New command line option to generate an "args" file

### ISSUE THREAD

**Issue by dragos** [scala/bug#10302]
Reproducing a bug outside the development environment is the first thing one needs to do, and it's much more time consuming than it should be. Each tool (Sbt, Maven, Gradle, Eclipse, IntelliJ) has it's own settings format and a different way to obtain compiler settings, compiler plugins and classpath that's sent to the compiler. Partial solutions exist, for example, @retronym's [gist](https://gist.github.com/retronym/9861cf798339f1fe6da77bbd0d742f75) for Sbt.

The compiler is the ultimate source of truth and it's trivial to implement such functionality. All  tools have a simple way to add a compiler option, so the problem becomes trivial and will work in all existing tools out of the box.

Proposal: 
- add `-Xprint-args` that prints all the compiler settings to `stdout` in a format suitable for using on the command line as `@file`. Normal compiler execution continues.

I suggest a `-X` option since it's more in line with the other development options, like `-Xdev`, `-Xprint:`, `-Xshow-phases` and `-Xshow:`.

**Comment by DarkDimius** [comment]
That's an awesome idea 👍!
