### ISSUE TITLE
Method extractor without prefix doesn't type check

### ISSUE THREAD

**Issue by liufengyun** [scala/bug#10318]
The following code doesn't type check. However by writing `this.Lit` instead `Lit` in the pattern, it type checks. It happens in `2.11.8` and `2.12.2`(the only versions I checked), as well as in Dotty.

```Scala
trait Lit {
  def apply(x: Int): Lit
  def unapply(x: Lit): Option[Int]
}

class Test {
  def Lit: Lit = ???

  def foo: Unit = Lit(4) match {
    // case this.Lit(x) => x                  // it works
    case Lit(x) => x                            // <= doesn't compile
  }
}
```

**Comment by hrhino** [comment]
I vote for this being Not-A-Bug, since [the spec says](https://scala-lang.org/files/archive/spec/2.13/08-pattern-matching.html#extractor-patterns):

```
  SimplePattern   ::=  StableId ‘(’ [Patterns] ‘)’
```

and `Lit` isn't a `StableId`.

**Comment by SethTisue** [comment]
agree

**Comment by Jasper-M** [comment]
Is this a bug then?

```
case this.Lit(x) => x                  // it works
```
