### ISSUE TITLE
Multiple line expression as single line expression using :paste

### ISSUE THREAD

**Issue by Alvaroisit** [scala/bug#10319]
sbt console version 2.11.7

I run the following
:paste
val p = new Person("Dean
Wampler", 29)

Then I type Ctrl + D
and I get the following errors:
<console>:1: error: unclosed string literal
val p =new Person("Dean
                  ^
<console>:2: error: unclosed string literal
Wampler", 29)

Am I doing something wrong here or is this a bug?

Please advise,

**Comment by som-snytt** [comment]
The string spans two lines; maybe you copy/pasted from a line-wrapped window.

As usual, triple-quoted strings can be multiline.
