### ISSUE TITLE
Scaladoc define syntax clashes with string interpolation

### ISSUE THREAD

**Issue by janekdb** [scala/bug#10333]
In Scaladoc examples code block may contain interpolated strings. This result in a warning when the corresponding replacement text is not defined. If the replacement was defined replacement is unlikely to be desirable.

```
[warn] Console.scala:46: Variable RESET undefined in comment for object Console in object Console
[warn]  *          Console.err.println(s"${RESET}${YELLOW_B}${RED}${UNDERLINED}NO!${RESET}")
```

**Comment by janekdb** [comment]
Option | Comment
--- | ---
Turn off define substitution in code blocks | Attractive
Introduce new non-clashing syntax for define replacements | Attractive but introduces legacy and migration
Hide $s from the define replacement code in code blocks with escape syntax | Yuk!

**Comment by Lasering** [comment]
Related issue #9815

**Comment by som-snytt** [comment]
Duplicate.
