### ISSUE TITLE
Bytecode instability with default getters

### ISSUE THREAD

**Issue by dragos** [scala/bug#10343]
Scalac generates different bytecode depending on the order in which files are passed on the command line. Or equivalently, for a full build vs an incremental build. 

```
// Main.scala
class Main {
  Person()
}
```

```
// Person.scala
case class Person(name: String = "Joe")
```

```
$ scalac -d /tmp src/main/scala/Person.scala src/main/scala/Main.scala 
dragos@aquarius $ javap -classpath /tmp Person\$
Compiled from "Person.scala"
public final class Person$ extends scala.runtime.AbstractFunction1<java.lang.String, Person> implements scala.Serializable {
...
  public java.lang.String $lessinit$greater$default$1();
  public java.lang.String apply$default$1();
  public java.lang.Object apply(java.lang.Object);
}
dragos@aquarius $ scalac -d /tmp src/main/scala/Main.scala src/main/scala/Person.scala 
dragos@aquarius $ javap -classpath /tmp Person\$
Compiled from "Person.scala"
public final class Person$ extends scala.runtime.AbstractFunction1<java.lang.String, Person> implements scala.Serializable {
...
  public java.lang.String apply$default$1();
  public java.lang.String $lessinit$greater$default$1();
  public java.lang.Object apply(java.lang.Object);
}
```

Notice that `apply$default$1` comes first in the second run.

The difference is explained by the order in which default getters are generated: default getters are added as methods that defined them are (lazily) completed during type-checking. In the second example, `apply`  is used *before* the constructor, so the namer completes it first and adds the default getter.

This was acknowledged as an issue at some point and a later step attempts to reorder synthetic methods in `addSynthetics` to make it deterministic again. However, this fails for constructors, and probably other special names since [0a16caa5](https://github.com/scala/scala/commit/0a16caa5881b312f5cd3817fd4036436ed1d58b5). I think the root cause may be this change, and I didn't manage to find out what it was supposed to fix. AFAIK names are encoded later in the pipeline so fresh names needn't do this so early. @densh do you remember?

**Comment by densh** [comment]
@dragos I don't remember for sure, but my guess would be related to the quasiquotes' handling of fresh names. For example for situations like `q"_ + 1"` the tree is similar to `q"x$1 => x$ + 1"`. Quasiquote must detect all fresh names and consistently generate new ones at every runtime invocation of a quasiquote to avoid name clashes:
```
scala> def t = q"_ + 1"
t: reflect.runtime.universe.Function

scala> t
res0: reflect.runtime.universe.Function = ((x$1) => x$1.$plus(1))

scala> t
res1: reflect.runtime.universe.Function = ((x$2) => x$2.$plus(1))

scala> t
res2: reflect.runtime.universe.Function = ((x$3) => x$3.$plus(1))
```
