### ISSUE TITLE
Optimizer doesn't eliminate tuples in if/else branches

### ISSUE THREAD

**Issue by durban** [scala/bug#10342]
The [optimizer](http://scala-lang.org/news/2.12.0#new-optimizer) doesn't seem to eliminate tuple packing/unpacking if an `if`/`else` is also involved. (Tested with 2.12.2, with `-opt:l:method`.)

Example which works:
```scala
scala> def foo(i: Int): Boolean = {
     |   val (a, b) = (1, true)
     |   if (i > a) b else i > 0
     | }
foo: (i: Int)Boolean

scala> :javap foo
...
  public boolean foo(int);
    descriptor: (I)Z
    flags: ACC_PUBLIC
    Code:
      stack=2, locals=4, args_size=2
         0: iconst_1
         1: iconst_1
         2: istore_3
         3: istore_2
         4: iload_1
         5: iload_2
         6: if_icmple     11
         9: iload_3
        10: ireturn
        11: iload_1
        12: iconst_0
        13: if_icmple     18
        16: iconst_1
        17: ireturn
        18: iconst_0
        19: ireturn
...
```

However, if the tuple creation is in an `if`/`else`:
```scala
scala> def foo(i: Int): Boolean = {
     |   val (a, b) = if (i > 0) (1, true) else (i, false)
     |   if (i > a) b else i > 0
     | }
foo: (i: Int)Boolean

scala> :javap foo
...
  public boolean foo(int);
    descriptor: (I)Z
    flags: ACC_PUBLIC
    Code:
      stack=4, locals=5, args_size=2
         0: iload_1
         1: iconst_0
         2: if_icmple     17
         5: new           #22                 // class scala/Tuple2$mcIZ$sp
         8: dup
         9: iconst_1
        10: iconst_1
        11: invokespecial #25                 // Method scala/Tuple2$mcIZ$sp."<init>":(IZ)V
        14: goto          26
        17: new           #22                 // class scala/Tuple2$mcIZ$sp
        20: dup
        21: iload_1
        22: iconst_0
        23: invokespecial #25                 // Method scala/Tuple2$mcIZ$sp."<init>":(IZ)V
        26: astore_2
        27: aload_2
        28: invokevirtual #31                 // Method scala/Tuple2._1$mcI$sp:()I
        31: istore_3
        32: aload_2
        33: invokevirtual #35                 // Method scala/Tuple2._2$mcZ$sp:()Z
        36: istore        4
        38: iload_1
        39: iload_3
        40: if_icmple     46
        43: iload         4
        45: ireturn
        46: iload_1
        47: iconst_0
        48: if_icmple     53
        51: iconst_1
        52: ireturn
        53: iconst_0
        54: ireturn
...
```

It would be nice if this could also work. (See also #8790.)

**Comment by durban** [comment]
Seems to be fixed in 2.13.

**Comment by ira19921** [comment]
Seems to be fixed in 2.13.,какого ху....... Не надоело, заявление о хищении
данных и дальше по этапу

вс, 5 дек. 2021 г., 01:38 Daniel Urban ***@***.***>:

**Comment by ira19921** [comment]
И мошенничество

вс, 5 дек. 2021 г., 02:23 Ira 1992 ***@***.***>:

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/11779

**Comment by SethTisue** [comment]
@ira19921 there has been a problem in recent days with comments coming from your account that don't seem helpful (as far as I can tell from running the Russian-language texts through Google Translate) and may possibly be accidental. I don't know what's causing it, but in case, I'm blocking your account to make it stop. If your efforts to contribute are well-intentioned, please contact me privately at seth dot tisue at lightbend dot com and we'll try to sort it out.

**Comment by SethTisue** [comment]
> Duplicates #11779

but that one remains open? has anyone tried it on 2.13.7?

**Comment by som-snytt** [comment]
I didn't notice the other ticket's status. I asked there about it. I did check that there is a test for this flavor of the issue.
