### ISSUE TITLE
type arguments do not conform to trait Subtractable's type parameter bounds

### ISSUE THREAD

**Issue by Proximator** [scala/bug#10359]
After upgrading to Scala 2.12, I am having a weird compilation issue of this code:

`val c = Map("a" -> Set[Map[String, String]](), "b" -> Map[String, String]())`

It is throwing this exception:
`Error:(19, 7) type arguments [?,Iterable[Equals] with String with scala.collection.immutable.Map[String,String] => Any with scala.collection.generic.Subtractable[_ >: String with scala.collection.immutable.Map[String,String] <: Object, Iterable[Equals] with String with scala.collection.immutable.Map[String,String] => Any with scala.collection.generic.Subtractable[_ >: String with scala.collection.immutable.Map[String,String] <: Object, Iterable[Equals] with String with scala.collection.immutable.Map[String,String] => Any with scala.collection.generic.Subtractable[_ >: String with scala.collection.immutable.Map[String,String] <: Object, Equals]]{def seq: Iterable[Equals] with String with scala.collection.immutable.Map[String,String] => Any with scala.collection.generic.Subtractable[_ >: String with scala.collection.immutable.Map[String,String] <: Object, Equals]}]{def seq: Iterable[Equals] with String with scala.collection.immutable.Map[String,String] => Any with scala.collection.generic.Subtractable[_ >: String with scala.collection.immutable.Map[String,String] <: Object, Iterable[Equals] with String with scala.collection.immutable.Map[String,String] => Any with scala.collection.generic.Subtractable[_ >: String with scala.collection.immutable.Map[String,String] <: Object, Equals]]{def seq: Iterable[Equals] with String with scala.collection.immutable.Map[String,String] => Any with scala.collection.generic.Subtractable[_ >: String with scala.collection.immutable.Map[String,String] <: Object, Equals]}}] do not conform to trait Subtractable's type parameter bounds [A,+Repr <: scala.collection.generic.Subtractable[A,Repr]]`

**Comment by som-snytt** [comment]
Probably https://github.com/scala/bug/issues/10151

**Comment by SethTisue** [comment]
note that even in 2.11 a rather outlandish type is inferred:

```
Welcome to Scala 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_162).

scala> val c = Map("a" -> Set[Map[String, String]](), "b" -> Map[String, String]())
c: scala.collection.immutable.Map[String,scala.collection.immutable.Iterable[Equals] with String with scala.collection.immutable.Map[String,String] => Any{def seq: scala.collection.immutable.Iterable[Equals] with String with scala.collection.immutable.Map[String,String] => Any{def seq: scala.collection.immutable.Iterable[Equals] with String with scala.collection.immutable.Map[String,String] => Any{def seq: scala.collection.immutable.Iterable[Equals] with String with scala.collection.immutable.Map[String,String] => Any}}}] = Map(a -> Set(), b -> Map())
```

let's consolidate under #10151
