### ISSUE TITLE
scala.MatchError when unapplying Product2 which is not a Tuple

### ISSUE THREAD

**Issue by scf37** [scala/bug#10365]
See code example below.

If possible, please allow this behavior - I'd like be able to unapply monads/data classes to local variables w/o syntax overhead:

    case class X(a: Int, b: Int)
    val (a1, b1) = X(42, 44) //cool
    val X(a2, b2) = X(42, 44) //not cool

Code snippet to reproduce:

    def fun1(): Product2[String, Int] = new Product2[String, Int] {
      override def _1: String = "hello"
  
      override def _2: Int = 42
  
      override def canEqual(that: Any): Boolean = ???
    }
  
    def main(args: Array[String]): Unit = {
      val (a, b) = fun1()
      println(a)
      println(b)
    }

Scala 2.12.2
java version "1.8.0_112"

**Comment by lrytz** [comment]
Thanks for the report - this is a feature request though, not a bug. Please start a thread on https://contributors.scala-lang.org! It's related to https://github.com/scala/bug/issues/5898 (warn on refutable patterns in pattern valdef).
