### ISSUE TITLE
Scala Docs (CN_Version) inaccurate translation

### ISSUE THREAD

**Issue by CZiJun** [scala/bug#10367]
Dear sir:
		
	Maybe there is an inaccurate statement in the Scala docs (Simplified Chinese version)
        link:  http://docs.scala-lang.org/zh-cn/overviews/collections/views
![cn_version](https://user-images.githubusercontent.com/16524574/27112546-638ef616-50ea-11e7-9172-3dca69b19f5e.PNG)

         

      reference original doc 
      link: http://docs.scala-lang.org/overviews/collections/views
![1](https://user-images.githubusercontent.com/16524574/27112626-ddf29368-50ea-11e7-9113-a7582f043c07.PNG)

**Comment by SethTisue** [comment]
the correct place for an issue and/or pull request on this would be https://github.com/scala/scala.github.com
