### ISSUE TITLE
Inconsistent handling of +=

### ISSUE THREAD

**Issue by charpov** [scala/bug#10375]
The following code fails to compile on its last line (using 2.12.2):
```scala
trait T {
  def x: Int = 42
}
class C extends T {
  def x_=(n: Int) = ()
}

object Test {
  val c = new C
  c.x = c.x + 10
  c.x += 10
}
```
The error message states that the "receiver is not assignable", but it must be, since `c.x = c.x + 10` works.

Furthermore, this variant works:
```scala
trait T {
  def x: Int = 42
}
class C extends T {
  def x_=(n: Int) = ()
  override def x = super.x
}

object Test {
  val c = new C
  c.x = c.x + 10
  c.x += 10
}
```
The language specs say nothing about the getter being inherited or not as relevant in this situation.

**Comment by estsauver** [comment]
Hey Michel!

I dug into the spec to trying to see what was going on. I think this is the relevant part of the spec that defines this behavior: 

```
 If x is a parameterless function defined in some template, and the same template contains a setter function x_= as member, then the assignment x = e is interpreted as the invocation x_=(e) of that setter function. 
```

It looks like that would imply if x is defined only in T and the x_= method is defined in C that those aren't the same templates? 

At a minimum though, the error message is somewhat confusing, and I'm actually not that confident that's what is actually happening. I'll dive into this and see what I can find.

**Comment by charpov** [comment]
You may be right.  Do the specs define "template"?  Which section does your quote come from?

**Comment by jvican** [comment]
Yes: https://www.scala-lang.org/files/archive/spec/2.11/05-classes-and-objects.html#templates.

**Comment by charpov** [comment]
I'm withdrawing my previous comment.  The issue here is `+=`, not `=`.  The assignment `c.x = c.x + 10` (or `c.x = 42`) works, even though `x` and `x_=` are defined in separate templates.  But `+=` fails.  The relevant spec section is 6.12.4, which does not mention templates.

**Comment by som-snytt** [comment]
Fix linked. The `+=` rewrite was a bit pickier than `_=`, but didn't locate your setter.
