### ISSUE TITLE
Scala documentation's search doesn't find FunctionN and ProductN for N > 2

### ISSUE THREAD

**Issue by floating-cat** [scala/bug#10385]
For example, if I search `Function3` in Scala documentation, it [doesn't show any results](http://www.scala-lang.org/api/2.12.2/scala/index.html?search=Function3). If I search `Product`, it show [`Product`, `Product1` and `Product2`](http://www.scala-lang.org/api/2.12.2/scala/index.html?search=Product) (no Product3 and etc).

**Comment by SethTisue** [comment]
it would be valuable for someone to at least get as far as determining the cause

**Comment by ritschwumm** [comment]
grepping through http://www.scala-lang.org/api/current/index.js i do find `Product2` and `Function2`, but not `Product3` or `Function3`.

**Comment by sjrd** [comment]
`Function3` until `Function22` and `Product3` until `Product22` are specifically excluded from the docs, in order not to clutter the API. I don't exactly where in Scala's build this happens, but in Scala.js [we do something similar here](https://github.com/scala-js/scala-js/blob/06ddd281863c96183cf2037cc66bcd942bb90aed/project/Build.scala#L1067-L1084).

**Comment by JimVanHorn** [comment]
The [Tuple2 page](http://www.scala-lang.org/api/current/scala/Tuple2.html) lists 8 Value Members but if you search for any of them you won't see any Tuple finds. Search for `swap` and none of the 6 finds are Tuple or Product related. Search for `invert` and there's nothing.

**Comment by dwijnand** [comment]
I think this issue's title should be changed to correctly reflect that it's specific to Function3, Product3, etc, and not a general problem.

**Comment by NomadBlacky** [comment]
I think [this code](https://github.com/scala/scala/blob/9b6baebcd0937658bc1b0b72b4b56821575740cd/src/scaladoc/scala/tools/nsc/doc/Settings.scala#L299-L326) excludes `Tuple3` etc.
