### ISSUE TITLE
Scaladoc ignoring minus signs on negative number default values

### ISSUE THREAD

**Issue by mdimeglio** [scala/bug#10391]
In both Scala 2.11.8 and 2.12.2 (I haven't tested on other versions), scaladoc (generated using sbt doc) for methods with default values which are negative numbers doesn't contain the minus signs. 
![image001](https://user-images.githubusercontent.com/4414497/27566770-9baace5e-5b2a-11e7-9b25-f7fcd9464dd5.png)

![image002](https://user-images.githubusercontent.com/4414497/27566771-9bebbc3e-5b2a-11e7-8a57-45e3d8936690.png)

**Comment by nafg** [comment]
Is there such scaladoc online somewhere? Any idea if it's a CSS kind of issue or it's in the scaladoc logic?
