### ISSUE TITLE
Add support for tables in Scaladoc

### ISSUE THREAD

**Issue by janekdb** [scala/bug#10403]
It would be nice to have support for tables in Scaladoc.

I have started this,

| What | Where |
| --- | --- |
| Branch | https://github.com/janekdb/scala/tree/topic/2.12/scaladoc-tables |
| Project Tracking | https://github.com/janekdb/scala/projects/1 |
| Requirements | https://github.com/janekdb/scala/wiki/Scaladoc-Tables-Requirements |
| Markdown Survey | https://github.com/janekdb/scala/wiki/Table-Markdown-Survey |
---

**Comment by janekdb** [comment]
Examples of currently parsed table markdown: https://github.com/janekdb/scala/blob/topic/2.12/scaladoc-tables/test/scaladoc/resources/tables.scala

**Comment by janekdb** [comment]
Happy path table markdown is passing tests. Now for the fun part (HTML rendering).

![image](https://user-images.githubusercontent.com/1123855/28711253-dab1a49e-737e-11e7-90f6-86ade63bee37.png)

**Comment by janekdb** [comment]
So far ....

![image](https://user-images.githubusercontent.com/1123855/28748189-102deae4-74a9-11e7-8411-72e7b9e92ac4.png)

**Comment by janekdb** [comment]
Plan is to split off the CSS styling to a subsequent PR. For now just enough CSS to clearly see the table structure.

![image](https://user-images.githubusercontent.com/1123855/28965295-384b7b6e-7908-11e7-8bc3-b6f9b557fc86.png)

**Comment by janekdb** [comment]
Happy paths pretty much done.

Temporary styling,

![image](https://user-images.githubusercontent.com/1123855/29358994-04ff05d4-8275-11e7-8957-066bc13d52c4.png)

**Comment by janekdb** [comment]
Error reporting done,
```
newSource:136: warning: table rows had different cell counts: [1,2]
  /**
  ^
newSource:409: warning: unclosed table
  /**
  ^
newSource:415: warning: more than one table caption
  /**
  ^
newSource:423: warning: table caption defined after table header
  /**
  ^
newSource:431: warning: table caption defined after table cells
  /**
  ^
newSource:439: warning: more than one table header
  /**
  ^
newSource:448: warning: table header defined after table cells
  /**
  ^
newSource:456: warning: table header cell count not equal to first row cell count: header: 2, row: 1
  /**
  ^
newSource:464: warning: table rows had different cell counts: [1,3,2]
  /**
  ^
Done.
```
Some non-functional improvements then PR.

**Comment by janekdb** [comment]
Up for review: https://github.com/scala/scala/pull/6043

**Comment by m-sp** [comment]
I think this can be closed now @janekdb ?
