### ISSUE TITLE
private[this] val ctor parameters don't always have backing fields

### ISSUE THREAD

**Issue by durban** [scala/bug#10400]
If a constructor parameter is marked as `private[this] val`, and is unused in the class body, it will not have a backing field (same behavior in 2.11.11 and 2.12.2):

```scala
scala> final class MyClass(private[this] val a: AnyRef)
defined class MyClass

scala> :javap -p -c MyClass
Compiled from "<console>"
public final class $line6.$read$$iw$$iw$MyClass {
  public $line6.$read$$iw$$iw$MyClass(java.lang.Object);
    Code:
       0: aload_0
       1: invokespecial #19                 // Method java/lang/Object."<init>":()V
       4: return
}
```

On the one hand, this is somewhat understandable, since it is unused (in fact, I think this is how unused simple parameters are handled). On the other hand, the user clearly wants this as a field. (Looking at the spec, I _think_ it says that it should be a field in this case.)

Combined with, e.g., weak references, this "optimization" can cause mysterious behaviors: one may think, that there is a strong reference to an object through this field, but since the field doesn't actually exist, there is no strong reference. (For a more-or-less real world example, see https://github.com/fommil/stalagmite/issues/23.)

Workarounds:

- make it simply `private` (instead of `private[this]`)
- use it in the class body (e.g., in an unused private method)
- make it a simple parameter, and assign it to a separate `private[this] val` in the body; although, this way there will be 2 fields:

```scala:
scala> final class MyClass(val _a: AnyRef) {
     |   private[this] val a: AnyRef = _a
     | }
defined class MyClass

scala> :javap -p -c MyClass
Compiled from "<console>"
public final class MyClass {
  private final java.lang.Object _a;

  private final java.lang.Object a;

  public java.lang.Object _a();
    Code:
       0: aload_0
       1: getfield      #11                 // Field _a:Ljava/lang/Object;
       4: areturn

  public MyClass(java.lang.Object);
    Code:
       0: aload_0
       1: aload_1
       2: putfield      #11                 // Field _a:Ljava/lang/Object;
       5: aload_0
       6: invokespecial #18                 // Method java/lang/Object."<init>":()V
       9: aload_0
      10: aload_1
      11: putfield      #20                 // Field a:Ljava/lang/Object;
      14: return
}
```

**Comment by odersky** [comment]
See https://github.com/lampepfl/dotty/issues/8579#issuecomment-602092696

**Comment by som-snytt** [comment]
Closing as not a hookah-smoking caterpillar (as it appears in the issue label).

The workaround doesn't require double-vals:
```
class C(@deprecatedName("c") c0: Int) { @annotation.unused private[this] val c = c0 }
```
The workaround also doesn't work with doti and its ruthless efficiency. Also `private[this]` is inferred, so removing the private-within doesn't help. This works:
```
class C(@deprecatedName("c") c0: Int) { @annotation.unused private[this] def f = c ; private val c = c0 }
```
