### ISSUE TITLE
Scaladoc 2.12.2 with linter enabled errors on java sources

### ISSUE THREAD

**Issue by mrerrormessage** [scala/bug#10402]
Consider the following source:

```java
class Bar {
  public void bar() {
    baz();
  }

  private void baz() { }
}
```

When running scaladoc 2.12.1 with the `-Xlint` option enabled, this file generates no warnings. In 2.12.2, it generates the warning "private method baz in class Bar is never used". This is both incorrect and a behavior change from 2.12.1.

Another similar error I'm seeing is for java sources like:

```java
class Foo {
  private Foo() {
    throw new IllegalStateException("cannot instantiate foo!");
  }
}
```

Which displays the error: "private constructor in class Foo is never used". This error is totally correct, but a bit annoying as this is a common java idiom (again, this was ignored in 2.12.1).

**Comment by SethTisue** [comment]
@som-snytt perhaps this just needs a `unit.isJava` check like the one in https://github.com/scala/scala/pull/5535/files?

**Comment by SethTisue** [comment]
@som-snytt or a check to see whether we're in the middle of generating Scaladoc, as opposed to compiling? the former seems like an unsuitable time to be reporting unused warnings

**Comment by som-snytt** [comment]
Probably the `isJava` is quickest and most defensive fix.

Scaladoc analyzer knows it's doing doc, and so does sbt; it would be nicer not to be called at all.

I don't see at a glance why Scaladoc's java parser is different from scalac. The old `forScaladoc` flag isn't used anymore.
