### ISSUE TITLE
Non-deterministic compilation: cross-file optimization without -opt

### ISSUE THREAD

**Issue by dragos** [scala/bug#10423]
Scalac performs an optimization across compilation units without any `-opt` flags: it replaces outer pointers with `null` for inner classes that don't use the outer pointer. If the instantiation is in a different compilation unit, this optimization can only be done when both units are compiled together.

Here's a diff between two compilations (see below) of the *instantiating* site:

```diff
$ diff -c full-build.txrt sep-build.txrt
*** full-build.txrt     2017-07-24 09:55:06.000000000 +0200
--- sep-build.txrt      2017-07-24 09:55:20.000000000 +0200
***************
*** 8,14 ****
         7: astore_1
         8: new           #10                 // class a/Outer$Inner
        11: dup
!       12: aconst_null
        13: invokespecial #21                 // Method a/Outer$Inner."<init>":(La/Outer;)V
        16: pop
        17: return
--- 8,14 ----
         7: astore_1
         8: new           #10                 // class a/Outer$Inner
        11: dup
!       12: aload_1
        13: invokespecial #21                 // Method a/Outer$Inner."<init>":(La/Outer;)V
        16: pop
        17: return
```

The two files:

```Scala
//Outer.scala
package a

class Outer {
  final class Inner
}
```

```Scala
// UseInner.scala
package a

class UseInner {
  def foo() {
    val outer = new Outer
    new outer.Inner
  }
}
```

First compile both files together, and then only `UseInner` (passing the output of the previous compilation on the classpath):

```bash
$ scalac -d /tmp Outer.scala UseInner.scala
$ scalac -d /tmp -cp /tmp UseInner.scala
```

**Comment by lrytz** [comment]
This optimization was added in https://github.com/scala/scala/pull/5099/commits/f07019ffa56ec2dfab8ab0d9a83133005761a877

**Comment by dragos** [comment]
I think the optimization is older than that. That commit seems to extend older behavior and change constructor signatures for local classes, but the problem here is for final inner classes (constructor signature is unchanged).

**Comment by DarkDimius** [comment]
I remember that this also involves patter matching: you get different 
behavior depending on if file with outer test is compiled with inner class 
definition or not

Dotty always creates outer pointers for publicly accessible inner classes

**Comment by sjrd** [comment]
The pattern matching change caused by this "optimization" is extremely annoying, because it produces a lot of warnings. In practice one can never write `final case class`es in non-static scopes, because they're unusable for pattern matching.

**Comment by DarkDimius** [comment]
Cc @xeno-by I vaguely remember you had issues with scalameta api due to this.

**Comment by retronym** [comment]
This is a correctness bug, too. We should be able to change a member class from `final` to non-`final` without recompiling clients. My change was intended to be limited to intra-compilation unit constructor calls.
