### ISSUE TITLE
@implicitNotFound should emit a compile error when used with non-compile-time constants

### ISSUE THREAD

**Issue by hmemcpy** [scala/bug#10424]
I tried adding an `@implicitNotFound` annotation on a type, and IntelliJ was helpful enough to offer a multiline default with the `.stripMargin` trick:
```scala
@implicitNotFound(
"""Some
    |multiline
    |text
""".stripMargin)
```

Unfortunately, even though this code compiled fine, the annotation didn't work, I was not able to see the custom message.

Removing the `stripMargin` code, and turning it into a string literal solved the issue.

I believe this should be treated as a compile-time error, too easy to make this mistake.

**Comment by lrytz** [comment]
This would be best implemented by fixing https://github.com/scala/bug/issues/7041

**Comment by som-snytt** [comment]
Also https://github.com/scala/bug/issues/7411 for better and more uniform composition.

**Comment by SethTisue** [comment]
Milestoned for 2.13.6 since, as we discovered at https://github.com/scala/scala/pull/9336, we need to make compiler changes, re-STARR, and _then_ change the annotations to extend `@ConstantAnnotation`. (And although we can do additional re-STARRs between releases, we prefer not to.)
