### ISSUE TITLE
Scala compiler 2.12.2 fails where 2.11.11 succeeds

### ISSUE THREAD

**Issue by pavel-ixxus** [scala/bug#10432]
Explained and demonstrated in: https://github.com/pavel-ixxus/2.12-vs-2.11

Superficially seems similar to https://github.com/scala/bug/issues/10171 and https://github.com/wix/accord/issues/103 but the workaround suggested there hasn't worked for me.

**Comment by lrytz** [comment]
You're lucky, it's fixed in 2.12.3, which is [about to be released](https://contributors.scala-lang.org/t/upcoming-scala-releases-2-12-3-and-2-13-0-m1/955/17) (just tried it on your repo).

**Comment by lrytz** [comment]
I'm not sure which commit / PR fixed it though.. In any case, please try 2.12.3 and re-open if you still see the issue.
