### ISSUE TITLE
-Xcheckinit runtime behavior change in 2.12.3

### ISSUE THREAD

**Issue by m4dc4p** [scala/bug#10439]
2.12.3 is throwing runtime exceptions due to uniitialized fields that are not present in 2.12.2. 

The essential test is to define an object like so:

```
object Test {
  private var s: String = _
  def apply(): String = {
    if (s == null) {
      s = ""
    }
    s
  }
}
```

And then to run the following program (compiled with `"-Xcheckinit"`):

```
Test()
```

Under 2.12.2, evaulating `Test()` results in `""`.  Under 2.12.3, an `UninitializedFieldException` is thrown. Arguably, that's the right thing to do but it represents a behavior change.

Here is an SBT session proving the problem (using sbt 0.13.15 on Windows 10) :

```
$ sbt
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
...
> set scalacOptions := Seq("-Xcheckinit")
...
> set scalaVersion := "2.12.2"
...
> console
...
Welcome to Scala 2.12.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131).
...
scala> :paste
// Entering paste mode (ctrl-D to finish)

object Test {
  private var s: String = _
  def apply(): String = {
    if (s == null) {
      s = ""
    }
    s
  }
}
...
scala> Test()
res0: String = ""
scala> :q
...
> set scalaVersion := "2.12.3"
...
> console
...
Welcome to Scala 2.12.3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_131).
...
scala> :paste
// Entering paste mode (ctrl-D to finish)

object Test {
  private var s: String = _
  def apply(): String = {
    if (s == null) {
      s = ""
    }
    s
  }
}
...
scala> Test()
scala.UninitializedFieldError: Uninitialized field: <console>: 12
  at Test$.s(<console>:12)
  at Test$.apply(<console>:14)
  ... 39 elided
```

(Found jointly with https://github.com/gstro)

**Comment by lrytz** [comment]
2.12.3 adds an init check for `s`, while 2.12.2 doesn't. It looks like the 2.12.2 behavior is intended: fields initialized with `_` should be excluded according to https://github.com/scala/scala/blob/v2.12.3/src/compiler/scala/tools/nsc/transform/AccessorSynthesis.scala#L143. Something must have shaken up the flags.. 

Reminds me of https://github.com/scala/scala/pull/5966. I'll take a look tomorrow.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6024
