### ISSUE TITLE
scala ver 2.12.2 and parallel collection

### ISSUE THREAD

**Issue by fr0ster** [scala/bug#10442]
I have simple project on scala.
I use SBT for build and test my project.
In SBT console i typed next code
"(0 to 10000).par.map(_+42)"
When i use scala ver 2.11.7 that all right.
When i use scala ver 2.12.1 or 2.12.3 that command execution  don`t terminate.
I am novice in using of scala and sbt and  i don`t know where i can see more information about this problem.

Sorry for my Englash...

**Comment by som-snytt** [comment]
This issue is tracked as https://github.com/scala/scala-dev/issues/195 which links to duplicates such as https://github.com/scala/bug/issues/8119
