### ISSUE TITLE
-Ywarn-unused can't be configured to warn about unused params while ignoring unused implicit params

### ISSUE THREAD

**Issue by phearnot** [scala/bug#10447]
Consider the following snippet:

```scala
trait A

class B {
  def foo(i: Int): Int = ???
  def implicitArg()(implicit a: A) = ???
}
```
I'd like to configure scalac to complain about the unused argument `i` in method `foo`, but ignore the unused implicit argument `a` in method `implicitArg`. `-Ywarn-unused` seems to ignore `-implicits` when `params` is set:
```
~/tmp ▶ scalac -version                                                                                                              ⏎
Scala compiler version 2.12.3 -- Copyright 2002-2017, LAMP/EPFL and Lightbend, Inc.
~/tmp ▶ scalac -Ywarn-unused:params,-implicits args.scala
args.scala:4: warning: parameter value i in method foo is never used
  def foo(i: Int): Int = ???
          ^
args.scala:5: warning: parameter value a in method implicitArg is never used
  def implicitArg()(implicit a: A) = ???
                             ^
two warnings found
```

**Comment by som-snytt** [comment]
Yes, originally someone proposed warning about unused implicits, so it kept that bias. Should `params` mean all params unless `-implicits`. I guess that is workable and not confusing.

**Comment by som-snytt** [comment]
Here there are `-Ywarn-unused:explicits,implicits` where `-Ywarn-unused:params` expands to both. `-Ywarn-unused:params.-implicits` does what you'd expect.

https://github.com/scala/scala/pull/6021

**Comment by nafg** [comment]
FWIW I've had it warn about unused implicits even when they were used (implicitly)...

**Comment by som-snytt** [comment]
@nafg That wouldn't surprise me, but the anecdote doesn't help much without an example. Can you open an issue?
