### ISSUE TITLE
Scaladoc. parameter named "default" cannot be show in scaladoc.

### ISSUE THREAD

**Issue by cuzfrog** [scala/bug#10455]
```scala
/**
 *
 * @param default some-description
 */
def method(default:Int = 0) = ???
```
`default` as a parameter's name is legal, but scaladoc ignored it.

**Comment by som-snytt** [comment]
That's a good one. It's a kind of scaladoc pun.

**Comment by hrhino** [comment]
Scaladoc puns are the lowest form of docucomedy.

**Comment by atiqsayyed** [comment]
@som-snytt @SethTisue Can I help with this issue?..

**Comment by SethTisue** [comment]
sure! even just to investigate the underlying cause would be a good start.

**Comment by som-snytt** [comment]
Just getting Seth to write back is huge!

**Comment by atiqsayyed** [comment]
@som-snytt 
 Tried to generate the scala doc for following class, it works fine and i wasn't able to reproduce the issue, or i may not be looking at the exact problem
```
class ScaladocExample{
  /**
    * @param default this param is default
    */
  def method(default:Int = 0) = ???
}
```
<img width="943" alt="screen shot 2017-08-21 at 11 16 10 am" src="https://user-images.githubusercontent.com/2395804/29503469-2d7fdc0e-8662-11e7-9445-c4c50bf5ce10.png">

**Comment by som-snytt** [comment]
`default` is not in our stars.

**Comment by atiqsayyed** [comment]
@som-snytt sorry but i didn't understand. Can you please explain it briefly?..

**Comment by som-snytt** [comment]
[It's a punning quote](https://www.enotes.com/shakespeare-quotes/fault-dear-brutus-our-stars), with the stars also meaning `/** */` for extra punning goodness.

**Comment by atiqsayyed** [comment]
I wasn't able to reproduce this issue, i don't think that it's an issue.
Can someone add more details to explain this better? or how to reproduce it it it's actually a problem?

**Comment by cuzfrog** [comment]
@atiqsayyed in IDEA, the doc prompt skipped `@param default`.

**Comment by SethTisue** [comment]
@cuzfrog you're saying the problem is specific to IDEA...? if so, you'd need to report it on their tracker

**Comment by cuzfrog** [comment]
I'm sorry, Tested in scala-IDE, the prompt is right.
