### ISSUE TITLE
Non String Interpolation code treated as Interpolation code (Scala 2.12.3)

### ISSUE THREAD

**Issue by coderdiaries** [scala/bug#10456]
Noticed while working with Spring annotations:

`@Value("${myProperty}")`
 `var myProperty: String = _`
  
Compile fails with error 

> illegal cyclic reference involving variable myProperty

**Comment by hrhino** [comment]
This appears to only happen with `-Xlint:missing-interpolator`; you could try turning that off for now.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/10125 and https://github.com/scala/bug/issues/9763
