### ISSUE TITLE
Compilation failure due to `knownDirectSubclasses` and lexicographical ordering of files.

### ISSUE THREAD

**Issue by isomarcte** [scala/bug#10454]
# Overview #

Consider a type `T` with at least one sub-type and a reference to that type in another file which invokes a macro (defined in another project) that invokes `knownDirectSubclasses` against `T`. If the reference to the type `T` occurs in a file whose filename has a lexicographical ordering which occurs before the filename of the file in which the type `T` is defined, a `globalError` is raised due to `T` being observed before all sub-types have been registered with the compiler.

This is related to [SI-7046][SI-7046] which was generally thought to have been fixed in [PR 5284][PR-5284]. While that PR does list a few exceptional cases where this bug can still occur, it does not appear (to me) to list the cases documented here.

* Scala Versions
    * The error is raised on all Scala versions in the range `[2.11.9, 2.13.0-M2]`. Although it appears to still be present before `2.11.9`, but is silently ignored as the code which emits the `globalError` was only added in `2.11.9`.
* JVM Versions
    * I have tested this on OpenJDK 1.8.0_144-b01

# Details #

This bug is a bit tricky to describe well in prose, so I have created an example project here (https://github.com/isomarcte/scala-compiler-knownSubclasses-bug) which may be more directly helpful. The below is taken from the `README.md` for that project.

Here is what is happening.

Consider some `sealed` type `T` that defines all sub-classes in the companion object for the type.

```scala
sealed trait T

object T {

  final case class TImpl() extends T
}
```

Consider some type-class `F[_]` which can derive instances for certain types, assuming certain requirements for `T` are met. The validation of these requirements and the derivation code is done using a macro. This macro invokes [`knownDirectSubclasses`][knownDirectSubclasses] at some point.

```scala
trait F[T]

object F {

  def instanceImpl[T : c.WeakTypeTag](
    c: Context
  ): c.Expr[F[T]] = {
    import c.universe._
    val wtt: c.WeakTypeTag[T] = implicitly[c.WeakTypeTag[T]]

    wtt.tpe.typeSymbol.asClass.knownDirectSubclasses.toString

    reify(new F[T]{})
  }

  implicit def instance[T]: F[T] = macro instanceImpl[T]
}
```

Finally, consider a function `foo` which uses `T` and requires that `T` have an instances of `F`.

```scala
object Foo {

    def foo[T : F]: Unit = ()

    foo[T]
}
```

If the `T` is defined in a file whose filename has a lexicographical ordering which places it _after_ the file in which `foo` is defined _and_ `T` highest ranking implicit instance for `F` is the macro derived instance, then the following will occur.

* The call to [`knownDirectSubclasses`][knownDirectSubclasses] in the macro will fail to see any sub-classes of `T`
* When the compiler type-checks `T` it will raise N [`globalError` invocations][globalError], where N is the exactly equal to the number of sub-classes for `T`.

If the file in which `T` is defined has a lexicographical ordering which places it _before_ the file in which `foo` is defined, everything works great.

[SI-7046]: https://issues.scala-lang.org/browse/SI-7046 "SI-7046"

[PR-5284]: https://github.com/scala/scala/pull/5284 "Scala PR 5284"

[scodec]: https://github.com/scodec/scodec "Scodec"

[shapeless]: https://github.com/milessabin/shapeless "Shapeless"

[knownDirectSubclasses]: https://github.com/scala/scala/blob/v2.12.3/src/reflect/scala/reflect/internal/Symbols.scala#L126 "knownDirectSubclasses"

[globalError]: https://github.com/scala/scala/blob/v2.12.3/src/reflect/scala/reflect/internal/Symbols.scala#L3371 "globalError"

**Comment by isomarcte** [comment]
@milessabin I noted you added much of the code around this part of the compiler recently. I thought you might be interested in the above.

**Comment by milessabin** [comment]
I agree that the behaviour here is undesirable ... note that https://github.com/scala/scala/pull/5284 is labelled as a _partial_ fix. The error that's reported in your example is preferable to the previous behaviour (which you would see with Scala versions prior to https://github.com/scala/scala/pull/5284) which would be to compile silently with an incomplete set of subclasses.

I'd love to see a complete fix to #7046, but so far it's eluded me.

**Comment by isomarcte** [comment]
Hey @milessabin, thanks for the quick response.

I completely agree that the compiler error is much better than it silently failing to find the subtypes.

What is still surprising to me though, was that macro expansion is occurring as a result of implicit search to derive a typeclass instance, even when that instance is not actually being used. That is what https://github.com/isomarcte/scala-compiler-knownSubclasses-bug/tree/master/scodec_shapeless/src/main/scala demonstrates.

In that project I define a type which has a manually encoded `Codec` defined on the companion object. This is the implicit which is used, assuming no compilation error. The surprising part is that [this call][callMacro] will cause Scodec to attempt to derive an instance using Shapeless (thus calling `knownDirectSubclasses`) even though that instance is never used, i.e. it ranks lower at the end of implicit search. In this case the compiler error presents a problem, because we don't care that the macro can't see the subtypes because we don't want to generate an instance. Or put another way, we don't want the macro to expand.

I was only able to reproduce this with Shapeless and Scodec, which was also surprising to me. In my more minimal example if you uncomment [this line][instance], which provides a manual instance of the fake typeclass, then the macro is never expanded and thus no error is raised.

I'm sorry if this is all old news though. It is entirely possible this is an expected given the exceptions listed on https://github.com/scala/scala/pull/5284 , and the surprising nature of it to me is just a result of my ignorance on the subtleties of the interplay between implicit search and macro expansion.

[callMacro]: https://github.com/isomarcte/scala-compiler-knownSubclasses-bug/blob/master/scodec_shapeless/src/main/scala/AAA_UsesMacro.scala#L32 "callMacro"

[instance]: https://github.com/isomarcte/scala-compiler-knownSubclasses-bug/blob/master/uses_macro/src/main/scala/ADT.scala#L16 "instance"

**Comment by retronym** [comment]
One confounding factor that sometimes makes the difference between the big example that exhibits that bug and the seemingly faithful minimization that doesn't is the fact that implicit search internally orders its search by the frequency with which the candidates have been used implicitly.

https://github.com/scala/scala/blob/v2.12.3/src/compiler/scala/tools/nsc/typechecker/Implicits.scala#L924

**Comment by retronym** [comment]
I've identified a way to make these particular tests work.

https://github.com/retronym/scala/tree/ticket/10454

The code added in #5284 only forces typechecking of the subclass of `ADT` if the enclosing `ModuleDef` has a lazy type. I debugged the new test case with

```
-classpath
/Users/jz/code/scala-compiler-knownSubclasses-bug/macro/target/scala-2.12/classes:/Users/jz/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.3.jar:/Users/jz/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.3.jar
/Users/jz/code/scala-compiler-knownSubclasses-bug/uses_macro/src/main/scala/AAA_UsesMacro.scala
/Users/jz/code/scala-compiler-knownSubclasses-bug/uses_macro/src/main/scala/ADT.scala
```

And noticed that the tree for `object ADT`-s symbol has a `ModuleTypeRef(moduleClassSym)` as its info, not a type completer.

So my patch descends into each of `moduleClassSym.rawInfo.decls`.

@milessabin Do you care to take a deeper look a this?

**Comment by milessabin** [comment]
@isomarcte all your examples compile post https://github.com/scala/scala/pull/6029.

**Comment by isomarcte** [comment]
@milessabin @retronym Thank you so much! I am very impressed at how quickly you guys sorted that.

**Comment by retronym** [comment]
@isomarcte Could you please [try](https://stackoverflow.com/questions/40622878/how-do-i-tell-sbt-to-use-a-nightly-build-of-scala-2-11-2-12-or-2-13/40622879#40622879) the next nightly build in your project to see if the fix works in the large?
