### ISSUE TITLE
scala.sys.process doesn't provide a way to use non-default file encoding

### ISSUE THREAD

**Issue by retronym** [scala/bug#10461]
This appears to have been the root cause of the Windows partest failure, as diagnosed by @hrhino 

`InputStreamReader` has overloaded constructors that accept an explicit encoding, we should probably thread in an implicit `Codec` as we do in `scala.io` to let the user choose something other than `file.encoding`.

```
  def processFully(processLine: String => Unit): InputStream => Unit = in => {
    val reader = new BufferedReader(new InputStreamReader(in))
    try processLinesFully(processLine)(reader.readLine)
    finally reader.close()
  }

```

**Comment by retronym** [comment]
We're planning to spin `scala.sys.process` out to a module in Scala 2.13.x, that might also be a good time for this sort of renovation.

**Comment by retronym** [comment]
Incidentally, I came across https://github.com/brettwooldridge/NuProcess recently which is a alternative to `ProcessBuilder` that doesn't require dedicated threads for stream handling of each spawned process.

Furthermore, when we spend some time in the API and implementation of `sys.process`, we should also take the opportunity to take advantage of / expose the methods in `ProcessBuilder` and `Process` that were added in Java 1.7/1.8.

  - `Process.waitFor` now accepts a timeout
  - `Process.destroyForcibly` added
  - Input stream redirection support (including inheriting from parent process)

Java 9 will add a few more features: http://www.baeldung.com/java-9-process-api

Some of the improvements in the Java library erode the value of our wrapper, so we might well just recommend direct use of the Java API.

**Comment by SethTisue** [comment]
in 2.13, scala.sys will become its own module, at which point this could be addressed if someone cares to. closing since scala.sys issues will no longer be tracked here in scala/bug. I've made a "module:scala.sys" label so we can find relevant issues once the module has its own repo

**Comment by som-snytt** [comment]
The issue duplicates https://github.com/scala/bug/issues/8464 but maybe leave open as an enhancement.

**Comment by SethTisue** [comment]
nah
