### ISSUE TITLE
-Ystatistics implementation is not threadsafe

### ISSUE THREAD

**Issue by jvican** [scala/bug#10460]
Turning `_enabled` into a compile-time constant with:
```patch
diff --git a/src/reflect/scala/reflect/internal/util/Statistics.scala b/src/reflect/scala/reflect/internal/util/Statistics.scala
index 81500e0792..9f96135fc5 100644
--- a/src/reflect/scala/reflect/internal/util/Statistics.scala
+++ b/src/reflect/scala/reflect/internal/util/Statistics.scala
@@ -254,7 +254,7 @@ quant)
     }
   }
 
-  private final val _enabled = false
+  private final val _enabled = true
   private val qs = new mutable.HashMap[String, Quantity]
```
  
creates the following error: https://scala-ci.typesafe.com/view/scala-bench/job/bootstrap-benchmark/258/console.
  
From looking at the code, it looks like this line is the responsible:
```scala
      val startByType = if (Statistics.canEnable) Statistics.pushTimer(byTypeStack, byTypeNanos(tree.getClass)) else null
```
  
where `byTypeNanos` at some point returns null for `tree.getClass`, causing `pushTimer` not to push the timer and `popTimer` in `finally if (Statistics.canEnable) Statistics.popTimer(byTypeStack, startByType)` to fail because the invariant that a timer must be pushed before we pop it is violated.
  
This is as far as I have got since I cannot investigate deeper.
  
This happened [when playing around with the statistics](https://github.com/scala/scala/pull/6034).

**Comment by lrytz** [comment]
Maybe a bug in the inliner? Assigning to me to investigate.

**Comment by jvican** [comment]
I've thought about that, but I've tried to see the generated code for this snippet of code concretely and I didn't see anything weird (but double check just in case).

**Comment by jvican** [comment]
I think this cannot be an inliner bug because it also fails when it's not a constant (though this time it fails in a different place): https://github.com/scalacenter/scala/commit/f9a7fab61389293e2509b4d2446f63c309d7be3d -> https://scala-ci.typesafe.com/view/scala-bench/job/bootstrap-benchmark/265/console.
  
This must  be an error of the statistics infrastructure, IMO. It's revealing a bug that hasn't been catched because statistics are always turned off.

**Comment by retronym** [comment]
This appears to be a simple race condition in statistics.

SBT compiles independent sub-projects in parallel using different instances of `Global` from a single classloader. So there will be a single instance of `TypersStats.byTypeStack` shared between these places.

For the same reason, exposing `-Ystatistics` as a compiler setting is rather misleading.

Any documentation we write for statistics should describe how to serialize compilation within SBT.

**Comment by jvican** [comment]
> This appears to be a simple race condition in statistics.
  
Good catch.
> SBT compiles independent sub-projects in parallel using different instances of Global from a single classloader. So there will be a single instance of TypersStats.byTypeStack shared between these places.
  
This reminds me of Iulian's request to keep all these statistics per `Global` instead of per classloader. I'll give this a try and benchmark how it affects performance.

**Comment by jvican** [comment]
I have a working prototype [here](https://github.com/scalacenter/scala/commit/08cd6c18aa290458efde61010e680636b18b48a2).
  
It builds on https://github.com/scala/scala/pull/6034, so that PR will need to be merged before.
