### ISSUE TITLE
Compiling large case class causes compiler to throw StackOverflowException.

### ISSUE THREAD

**Issue by MikeHurleySurescripts** [scala/bug#10470]
We've recently moved to Spark 2 which means we can use Scala 2.11. We were generating our own Product classes since we have records with more than 22 fields. With Scala 2.11 we were hoping to have just case classes. Everything seems to work ok except for one class that has 178 fields.

JDK: 1.8 u141
Problem scala versions: 2.11.8 (Spark 2) and 2.11.11 (experiment)
Successful scala version: 2.12.3 (experiment)

Workaround: Continue generating Product classes

[bugexample.zip](https://github.com/scala/bug/files/1229028/bugexample.zip)

**Comment by SethTisue** [comment]
`scalac bugexample.scala` fails, but `scalac -J-Xss16m bugexample.scala` succeeds

**Comment by MikeHurleySurescripts** [comment]
Thanks @SethTisue. Once I figured out how to set that via gradle my build now works.

Here's the gradle snippet I added (gradle 3.3):
```
compileScala {
        options.forkOptions.jvmArgs += "-Xss16m"
}
```

**Comment by vilinski** [comment]
Just to be clear, is it "by design" or "won't fix" or why is it closed? The 2.12.6 compiles big case classes still with "-Xss" option only.

**Comment by SethTisue** [comment]
it's considered normal that some kinds of unusual Scala code may require extra stack to compile.

it's also considered normal that the exact point at which the default stack size becomes insufficient may change from time to time, including in a minor release.

**Comment by mljohns89** [comment]
What's the default for Xss?

**Comment by SethTisue** [comment]
Please use https://users.scala-lang.org or other sources (https://scala-lang.org/community has suggestions) for questions about JVM configuration, build tool configuration, etc.
