### ISSUE TITLE
Repl customize splash prompt

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#10472]
Folks want to customize the look of the repl.

It's currently possible to set `shell.welcome` in compiler.properties or `-Dscala.repl.welcome`.

This mechanism could be made easier. Also, another point of customization is the prompt for the splash loop that reads only the first line of input. That would allow showing a logo or special instructions just once, after the standard banner.

[Discussion.](https://users.scala-lang.org/t/printing-text-before-repl-prompt/1574/5?u=som-snytt)

**Comment by SethTisue** [comment]
@som-snytt oh wait... should we close this?

**Comment by som-snytt** [comment]
I guess the moment for customizing the first prompt has passed.

The PR doesn't emphasize that this was for Spark, which outputs a fat banner.
```
$ scala

     ________ ___   / /  ___  
    / __/ __// _ | / /  / _ | 
  __\ \/ /__/ __ |/ /__/ __ | 
 /____/\___/_/ |_/____/_/ | | 
                          |/  version 2.12.4

scala> :quit
$ type -a scala
scala is aliased to `JAVA_HOME=$JAVA8_HOME $SCALA_HOME/bin/scala -Dscala.repl.welcome=banner'
```

**Comment by SethTisue** [comment]
> Spark, which outputs a fat banner

phat!
