### ISSUE TITLE
Scala 2.13.0-M2 regression: Scala ScriptEngine can no longer be loaded

### ISSUE THREAD

**Issue by peter-gergely-horvath** [scala/bug#10486]
The following call used to work with Scala 2.12.3:
`
ScriptEngine scriptEngine = new ScriptEngineManager().getEngineByName("scala");
`

Once Maven dependency versions are updated to 2.13.0-M2, the code above stops working, `getEngineByName` returns null

The following Maven dependencies are used: **Please note: only the dependency versions have been changed, the ScriptEngine works with the same dependencies if version is set to 2.12.3**
```
<dependency>
    <groupId>org.scala-lang</groupId>
    <artifactId>scala-library</artifactId>
    <version>2.13.0-M2</version>
</dependency>

<dependency>
    <groupId>org.scala-lang</groupId>
    <artifactId>scala-compiler</artifactId>
    <version>2.13.0-M2</version>
</dependency>
```

**Comment by som-snytt** [comment]
Thanks. Looks like the package name changed in the refactor, to `interpreter.shell`.

https://github.com/scala/scala/blob/v2.13.0-M2/build.sbt#L445
