### ISSUE TITLE
Nullary method inherits non-nullary arity from override

### ISSUE THREAD

**Issue by olafurpg** [scala/bug#10480]
```scala
// a.scala
trait A {
  def nonNullary(): String
}
object B extends A {
  override def nonNullary = ""
  nonNullary() // OK

  def nullary = ""
  nullary() // error: not enough arguments for method apply: (index: Int)Char in class StringOps.
}
```

I expected `nonNullary()` to report an error like the `nullary()` call. `scalap b` shows that `B.nonNullary` inherits the signature of `A.nonNullary`

```scala
// scalap b
object B extends A {
  override def nonNullary(): java.lang.String = { /* compiled code */ }
  def nullary: java.lang.String = { /* compiled code */ }
}
```
The same applies for nullary Scala methods that override a 0-arg Java method, including `.toString`.

Context: I'm implementing a scalafix rewrite that inserts explicit `()` for non-nullary methods. See  https://github.com/scalacenter/scalafix/issues/204#issuecomment-324376166 . The problem I'm facing is that I'd like the rewrite to not trigger for methods like `B.nonNullary`.

Related: https://github.com/lampepfl/dotty/pull/2716

**Comment by som-snytt** [comment]
I remember [reading](http://scala-lang.org/files/archive/spec/2.12/05-classes-and-objects.html#overriding):

> A special rule concerns parameterless methods. If a parameterless method defined as def f: T = ... or def f = ... overrides a method of type ()T′ which has an empty parameter list, then f is also assumed to have an empty parameter list.

Which is why `toString` has a parameter list even when you omit it, apart from empty application.

**Comment by olafurpg** [comment]
Interesting @som-snytt "nullary" did not yield relevant hits when I looked at the spec.

Let me refine my expected behavior then: I expect `nonNullary()` to compile but the `B.nonNullary` symbol to contain information whether method was defined as nullary or not. Conceretly, I would like to be able to distinguish from the scala signature which one of `B.overridesNonNullary` and `B.isNonNullary` is defined as parameterless

```scala
trait A {
  def overridesNonNullary(): String
}
object B extends A {
  override def overridesNonNullary = ""
  def isNonNullary() = ???
}
```

The motivation for this change is to prevent false positives for this scalafix rewrite: https://github.com/scalacenter/scalafix/issues/204

**Comment by som-snytt** [comment]
```
Welcome to Scala 2.13.8 (OpenJDK 64-Bit Server VM, Java 18.0.2.1).
Type in expressions for evaluation. Or try :help.

scala> trait T { def nilary(): String }
trait T

scala> object X extends T { def nilary = "X" ; override def toString = nilary }
                                                                       ^
       warning: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method nilary,
       or remove the empty argument list from its definition (Java-defined methods are exempt).
       In Scala 3, an unapplied method like this will be eta-expanded into a function.
                                ^
       warning: method without a parameter list overrides a method with a single empty one
object X

scala> :replay -Xsource:3
replay> trait T { def nilary(): String }
trait T

replay> object X extends T { def nilary = "X" ; override def toString = nilary }
        object X extends T { def nilary = "X" ; override def toString = nilary }
                                 ^
On line 2: error: method without a parameter list overrides a method with a single empty one
        object X extends T { def nilary = "X" ; override def toString = nilary }
                                                                        ^
On line 2: warning: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method nilary,
        or remove the empty argument list from its definition (Java-defined methods are exempt).
        In Scala 3, an unapplied method like this will be eta-expanded into a function.


scala>
```
