### ISSUE TITLE
Loading Scala ScriptEngine unexpectedly changes / fails to reset Thread ContextClassLoader

### ISSUE THREAD

**Issue by peter-gergely-horvath** [scala/bug#10485]
Loading a Scala 2.12.3 `ScriptEngine` changes Context `ClassLoader` on the current Thread, and fails to restore the original one. The dangling `ClassLoader` pollutes the Thread's context `ClassLoader`, which might cause _major_ issues within the application later on. (E.g. imagine the thread is a worker of a larger pool, used to service long running requests, not specific to Scala)

**Please see attached Maven project that reliably reproduces this error:** [testcase.zip](https://github.com/scala/bug/files/1259991/testcase.zip)
 See `testcase/src/test/java/scalabugreport/ScalaScriptEngineTest.java`in the project ZIP: the test case demonstrates the expected behaviour vs the behaviour exposed by Scala `ScriptEngine`. All other `ScriptEngine` implementations tested (JavaScript/Nashorn, Groovy, Python/Jython, and Ruby/JRuby) correctly clean up after being loaded.

Only the test case `testScalaScriptEngine` fails with errors similar to this:
`
java.lang.AssertionError: Thread ContextClassLoader should not change when loading the 
ScriptEngine. expected [sun.misc.Launcher$AppClassLoader@18b4aac2] but found [scala.reflect.internal.util.ScalaClassLoader$URLClassLoader@24f2608b]
Expected :sun.misc.Launcher$AppClassLoader@18b4aac2
Actual   :scala.reflect.internal.util.ScalaClassLoader$URLClassLoader@24f2608b
`

Test case: (see attached ZIP above for the whole Maven project)
    
    import org.testng.Assert;
    import org.testng.annotations.Test;
    
    import javax.script.ScriptEngine;
    import javax.script.ScriptEngineManager;
    
    public class ScalaScriptEngineTest {
    
        @Test
        public void testJavaScriptScriptEngine() {
            testScriptEngine("JavaScript");
        }
    
        @Test
        public void testGroovyScriptEngine() {
            testScriptEngine("Groovy");
        }
    
        @Test
        public void testJythonScriptEngine() {
            testScriptEngine("jython");
        }
    
        @Test
        public void testJrubyScriptEngine() {
            testScriptEngine("jruby");
        }
    
        @Test
        public void testScalaScriptEngine() {
            testScriptEngine("scala");
        }
    
    
        public void testScriptEngine(String engineName) {
    
            ClassLoader expected = Thread.currentThread().getContextClassLoader();
    
            ScriptEngineManager scriptEngineManager = new ScriptEngineManager();
            ScriptEngine scriptEngine = scriptEngineManager.getEngineByName(engineName);
            if (scriptEngine == null) {
                throw new IllegalStateException("Could not load ScriptEngine: " + engineName);
            }
    
            ClassLoader actualAfterLoadingScriptEngine = Thread.currentThread().getContextClassLoader();
    
            Assert.assertEquals(actualAfterLoadingScriptEngine, expected,
                    "Thread ContextClassLoader should not change when loading the ScriptEngine.");
    
        }
    
    }

**Comment by som-snytt** [comment]
Thanks. This issue is https://github.com/scala/bug/issues/8521 which has a fix https://github.com/scala/scala/pull/5657 in the long queue.

**Comment by peter-gergely-horvath** [comment]
To be honest I don't agree with marking this as duplicate of [#8521](https://github.com/scala/bug/issues/8521), because:
1.) Unlike  [#8521](https://github.com/scala/bug/issues/8521), the class loader setting is corrupted **without calling any script**, solely by acquiring the  `ScriptEngine` instance. See the sample code: there is no eval / interpret call made!  
2.) This is a different API, which should also be separately tested. The fact it is backed by `IMain` is a low level implementation detail.

**Comment by som-snytt** [comment]
That's a fair point. The test case in the other PR, [here](https://github.com/som-snytt/scala/blob/38e8986e6f713211b25bf17106596daba4a231eb/test/junit/scala/tools/nsc/interpreter/ScriptedTest.scala#L102), uses the script engine to eval. I'm not sure that PR will ever trickle in anyway.

Generally the interpreter does some initialization to warm up the compiler and create some context before the user submits a job.

Here's a probe for this case:

```
$ ~/scala-2.12.2/bin/scala
Welcome to Scala 2.12.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111).
Type in expressions for evaluation. Or try :help.

scala> import javax.script._
import javax.script._

scala> :pa
// Entering paste mode (ctrl-D to finish)

val r = new Runnable() {
override def run() = {
  println(Thread.currentThread.getContextClassLoader)
  val scriptEngineManager = new ScriptEngineManager()
  val se = scriptEngineManager.getEngineByName("scala")
  println(se)
  println(Thread.currentThread.getContextClassLoader)
}}

// Exiting paste mode, now interpreting.

r: Runnable = $anon$1@7d070ef5

scala> val t = new Thread(r) { override def setContextClassLoader(cl: ClassLoader) = ??? }
t: Thread{def setContextClassLoader(cl: ClassLoader): Nothing} = Thread[Thread-2,5,main]

scala> t.start
scala.tools.nsc.interpreter.IMain$TranslatingClassLoader@5b69fd74

scala> Exception in thread "Thread-2" scala.NotImplementedError: an implementation is missing
	at scala.Predef$.$qmark$qmark$qmark(Predef.scala:284)
	at $line5.$read$$iw$$iw$$iw$$iw$$anon$1.setContextClassLoader(<console>:15)
	at $line5.$read$$iw$$iw$$iw$$iw$$anon$1.setContextClassLoader(<console>:15)
	at scala.reflect.internal.util.ScalaClassLoader$.setContext(ScalaClassLoader.scala:122)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:33)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:30)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:33)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:565)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:592)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:562)
	at scala.tools.nsc.interpreter.Scripted.$anonfun$new$1(Scripted.scala:115)
	at scala.tools.nsc.interpreter.IMain.beQuietDuring(IMain.scala:209)
	at scala.tools.nsc.interpreter.Scripted.<init>(Scripted.scala:114)
	at scala.tools.nsc.interpreter.Scripted$.apply(Scripted.scala:309)
	at scala.tools.nsc.interpreter.Scripted$Factory.getScriptEngine(Scripted.scala:302)
	at javax.script.ScriptEngineManager.getEngineByName(ScriptEngineManager.java:238)
	at $line4.$read$$iw$$iw$$iw$$iw$$anon$1.run(<pastie>:18)
	at java.lang.Thread.run(Thread.java:745)
```
So the culprit is [here](https://github.com/scala/scala/blob/v2.12.2/src/repl/scala/tools/nsc/interpreter/Scripted.scala#L115).

On 2.12.3, there's a different bug which I've filed separately [here](https://github.com/scala/bug/issues/10488).
