### ISSUE TITLE
Inconsistent InnerClass attribute in delayed init body

### ISSUE THREAD

**Issue by retronym** [scala/bug#10487]
```
⚡ scala
Welcome to Scala 2.12.3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_112).
Type in expressions for evaluation. Or try :help.

scala> :paste -raw
// Entering paste mode (ctrl-D to finish)

package p1; object A extends App { println("here") }

// Exiting paste mode, now interpreting.


scala> val cls = Class.forName("p1.A$delayedInit$body")
cls: Class[_] = class p1.A$delayedInit$body

scala> cls.getEnclosingClass
java.lang.IncompatibleClassChangeError: p1.A and p1.A$delayedInit$body disagree on InnerClasses attribute
  at java.lang.Class.getDeclaringClass0(Native Method)
  at java.lang.Class.getDeclaringClass(Class.java:1235)
  at java.lang.Class.getEnclosingClass(Class.java:1277)
  ... 29 elided
```

**Comment by retronym** [comment]
The module class has:

```
SourceFile: "a.scala"
InnerClasses:
     public static final #12= #9 of #11; //delayedInit$body=class p1/A$delayedInit$body of class p1/A
Error: unknown attribute
```

But there is no corresponding entry in `A$delayedInit$body.class`.

**Comment by shelajev** [comment]
Hi, we hit a similar issue while trying to compile scala or akka apps to native images with GraalVM. 
For example, the [akka-quickstart-scala](https://developer.lightbend.com/start/?group=akka&project=akka-quickstart-scala) uses the
`object Main extends App {` main class, and we hit the problem as described in [graal#370](https://github.com/oracle/graal/issues/370). 

Currently it can be worked around by using the Object + main function syntax as described in [graal#384](https://github.com/oracle/graal/issues/384), but it's quite inconvenient that it doesn't work out of the box. 

I'm not sure I have the understanding of the scala compiler necessary to try fixing it myself. But if I can provide any additional information I'd be happy to, I'd like to fix this issue. Thank you!

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6788
