### ISSUE TITLE
Documentation is flooded with unresolved markup ("$" signs especially)

### ISSUE THREAD

**Issue by Leu-Gim** [scala/bug#10482]
E.g. http://scala-lang.org/files/archive/spec/2.12/03-types.html#existential-types

Texts are rendered like
```
An existential type has the form $T$ forSome { $Q$ } where $Q$ ...
```
or
```
Let $t_1[\mathit{tps}_1] >: L_1 <: U_1 , \ldots , t_n[\mathit{tps}_n] >: L_n <: U_n$ be the types declared in $Q$ ...
```
The same in both other specs (2.11, 2.13) and throughout all their content. Hard to read.

**Comment by Leu-Gim** [comment]
Turns out the mark-up is resolve at client side. Works depending on browser.

**Comment by hrhino** [comment]
That's LaTeX-style markup being rendered by [MathJax](https://www.mathjax.org/) (motto: "Beautiful math in all browsers" deemed slightly incorrect). Do you have Javascript disabled in the browser it doesn't work in?

And maybe we should have a plaintext version of the spec, so people don't have to look at the plainTeX one if they don't want to use javascript.

**Comment by Leu-Gim** [comment]
Thanks for response, no, JavaScript was enabled. Plaintext version would ve superb! PDF, etc yet of an option.

**Comment by Leu-Gim** [comment]
The cause was an ad-blocker, cdnjs.cloudflare.com was blocked by it.
