### ISSUE TITLE
All threads in global execution context hang

### ISSUE THREAD

**Issue by avkonst** [scala/bug#10484]
This is randomly happening behavior, which stops our entire system in runtime. I managed to create a reproducer.

**Scenario:**
stage1 - run 600 parallel tasks on global execution context with blocking closure inside
stage2 - run 100 parallel tasks on global execution context without blocking closure inside

**Observed behaviors (I observe one or the other, the second is a partial case of the first and most frequently observed):**
1. stage1 is completed by 'scala.concurrent.context.maxExtraThreads + scala.concurrent.context.maxThreads' threads in parallel, stage2 is completed by 1 thread (i.e. all tasks executed by 1 thread, all threads except one from the global context are in WAIT state)
2. stage1 is completed by 'scala.concurrent.context.maxExtraThreads + scala.concurrent.context.maxThreads' threads in parallel, stage2 hangs without completing any tasks (all threads from the global context are in WAIT state)

**Expected behavior:**
stage1 is completed by 'scala.concurrent.context.maxExtraThreads + scala.concurrent.context.maxThreads' threads in parallel, stage2 is completed by 'scala.concurrent.context.maxThreads' (4 in my case) threads in parallel

**Environment**
Scala version: 2.12.1
Java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Reproducer**
```scala
import java.util.Calendar
import java.util.concurrent.{Executors, ForkJoinPool}

import scala.concurrent.duration.Duration
import scala.concurrent.{Await, Future}

object AsyncTest extends App {

  start()

  def start(): Unit = {

    //System.setProperty("scala.concurrent.context.maxThreads", "3")
    implicit val ec = scala.concurrent.ExecutionContext.Implicits.global

    //implicit val ec = scala.concurrent.ExecutionContext.fromExecutor(null)

    //implicit val ec = scala.concurrent.ExecutionContext.fromExecutorService(Executors.newSingleThreadExecutor)

    //implicit val ec = scala.concurrent.ExecutionContext.fromExecutor(Executors.newWorkStealingPool(2))

    val blockingTasks = 600
    val paralleleTasks = 100

    def stage1 = {
      val futures = Vector.range(1, blockingTasks + 1).map { i =>
        Future {
          val sleepTime = 2000
          scala.concurrent.blocking {
            Thread.sleep(sleepTime)
          }

          val today = Calendar.getInstance().getTime()
          println(Thread.currentThread().getName + " Future: " + i + " - sleep was: " + sleepTime + " - " + today)
          1;
        }
      }

      val all = Future.sequence(futures)
      println("waiting on " + Thread.currentThread().getName)
      Await.result(all, Duration("100s"))
      println("finished waiting on " + Thread.currentThread().getName)
    }

    def stage2 = {
      val futures2 = Vector.range(1, paralleleTasks + 1).map { i =>
        Future {
          val sleepTime = 2000
          Thread.sleep(sleepTime)

          val today = Calendar.getInstance().getTime()
          println(Thread.currentThread().getName + " Future 2: " + i + " - sleep was: " + sleepTime + " - " + today)
          1
        }
      }

      val all2 = Future.sequence(futures2)
      println("waiting on " + Thread.currentThread().getName)
      Await.result(all2, Duration("1000s"))
      println("finished waiting on " + Thread.currentThread().getName)
    }

    stage1
    stage2
  }
}
```

**Comment by avkonst** [comment]
More experiments shows that the bug is reproducible when blockingTasks >= 260 (which is scala.concurrent.context.maxExtraThreads + scala.concurrent.context.maxThreads for my environment)

**Comment by lrytz** [comment]
cc @viktorklang

**Comment by viktorklang** [comment]
Thanks @lrytz. I'm currently on vacation, but I've started a conversation with Prof. Lea, as to specced behavior in the case the FJTF returns null in the non-vompensating worker case.

**Comment by viktorklang** [comment]
@avkonst In the mean time, you can set the system property "scala.concurrent.context.maxExtraThreads" to 1024 (or higher).

I'm looking into the possibility of having the DefaultThreadPool only limit the number of Extra Threads created, instead of having a total maximum threads.

**Comment by avkonst** [comment]
Thanks, I applied a semaphore before invoking blocking or Await to fix it. It causes event loop executor threads to hang for short period of time, but it is very rare side effect which I can live with for the moment, and it does not cause the whole system to hang up.

**Comment by viktorklang** [comment]
@avkonst Have a look at this: https://github.com/scala/scala/pull/6055/files

**Comment by SethTisue** [comment]
@viktorklang where does this stand — was it fixed by https://github.com/scala/scala/pull/6529 ?

**Comment by viktorklang** [comment]
@SethTisue It's my belief that it solved the problem.
