### ISSUE TITLE
Regression: Function in static annotation doesn't compile

### ISSUE THREAD

**Issue by KarelCemus** [scala/bug#10497]
I believe this is a regression issue because the code compiles and works with Scala 2.11 but doesn't compile with 2.12.3

The following example code doesn't make sense but is a very simplified real use case.

```
import scala.annotation._

class baz(out: Foo=>Int, in: (Foo, Int)=>Unit) extends StaticAnnotation

class Foo {
  @baz(out = _.value, in = _.value=_) var value: Int = 5
}
```

Compiler reports:

```
[error] /.../test.scala:6:16: illegal cyclic reference involving variable value
[error]   @baz(out = _.value, in = _.value=_) var value: Int = 5
[error]                ^
[error] /.../test.scala:6:30: illegal cyclic reference involving variable value
[error]   @baz(out = _.value, in = _.value=_) var value: Int = 5
[error]                              ^
[error] /.../test.scala:6:36: not found: value x$3
[error]   @baz(out = _.value, in = _.value=_) var value: Int = 5
[error]                                    ^
[error] three errors found

```

**Comment by KarelCemus** [comment]
Hi @lrytz, is there any progress on this regression issue, please? It prevents me from upgrading to Scala 2.12. Or is there any easy workaround?

**Comment by lrytz** [comment]
Hi @KarelCemus, I haven't found a workaround unfortuantely.. I don't have time currenlty to dig into it, I assigned a milestone and hope to come back to it.

**Comment by adriaanm** [comment]
The cycle is caused by calling `filterAccessorAnnots` while completing the accessor / field.
