### ISSUE TITLE
Issue on Getting Started page

### ISSUE THREAD

**Issue by cfjedimaster** [scala/bug#10499]
I'm learning Scala and going through the Getting Started page here (https://www.scala-lang.org/documentation/getting-started-sbt-track/getting-started-with-scala-and-sbt-on-the-command-line.html). 

Step 1 under "Running the project" says to "cd into hello-world." and then run sbt. However, doing so will throw an error saying no main class was defined.

If I CD'ed into hello-world-template (which is where the new folder was created, not hello-world), and *then* CDed into project, sbt ran as expected.

**Comment by SethTisue** [comment]
thanks for the report! we track issues with the scala-lang.org website over at scala/scala-lang, so I've relocated this to https://github.com/scala/scala-lang/issues/747
