### ISSUE TITLE
scalac generates setters for final fields

### ISSUE THREAD

**Issue by scf37** [scala/bug#10515]
I have several trait that define vals:

```
trait A {
  val a = ...
  val b = ...
}
```

and I have object that extends that trait:
```
object TestModule2 extends A
```

And that's what I see after decompiling TestModule2$.class:
```
public final class TestModule2$
implements A,
B,
C,
D {
    public static TestModule2$ MODULE$;
    private final Dsl.Rule dl_horizontal;
....
    @Override
    public Dsl.Rule dl_horizontal() {
        return this.dl_horizontal;
    }
....
    @Override
    public void me$scf37$finecss$D$_setter_$dl_horizontal_$eq(Dsl.Rule x$1) {
        this.dl_horizontal = x$1;
    }
```

Definitely not critical but I have about 650 vals there and half of 160Kb .class file is pointless setters.

scalaVersion := "2.12.3"
java version "1.8.0_112"

**Comment by hrhino** [comment]
Those are not actually useless setters: interfaces (on the JVM) can't have fields, so the backing field for the `val` needs to be mixed in to the implementing object, and the _trait_ (not the object) calls those setters to set the backing fields during initialization. 

If you make `A` a class it will get the fields in `A` itself and not need the trait setter.
