### ISSUE TITLE
SAM and Subtyping causes AbstractMethodError

### ISSUE THREAD

**Issue by ikempf** [scala/bug#10512]
The following fails on 2.12.3
This seems to be related to SAM, subtyping, implicit resolution and ad-hoc polymorphism.

```scala
trait JsonEncoder[A] {
  def encode(value: A): JsonValue
}

trait JsonObjectEncoder[A] extends JsonEncoder[A] {
  def encode(value: A): JsonObject
}

object JsonEncoderInstances {

  implicit val stringEncoder: JsonEncoder[String] =
    JsonString.apply

  implicit val intEncoder: JsonEncoder[Int] =
    i => JsonNumber(i)

  implicit def listEncoder[A](implicit encoder: JsonEncoder[A]): JsonObjectEncoder[List[A]] =
    l => JsonObject(l.zipWithIndex.map {
      case (a, index) => index.toString -> encoder.encode(a)
    })

}
```
```scala
// Following fails with java.lang.AbstractMethodError: com.ikempf.sandbox.sam_subtyping_bug.JsonEncoderInstances$$$Lambda$142/1556995360.encode(Ljava/lang/Object;)Lcom/ikempf/sandbox/sam_subtyping_bug/JsonValue;
implicitly[JsonEncoder[List[String]]].encode(List("a","b"))
```

The bug dissapears under following conditions 
- I do not use the SAM syntax for the `listEncoder[A]` (non parameterized types do not cause seem to cause the exception)
- I return a `JsonEncoder[List[A]]` instead of a `JsonObjectEncoder[List[A]]`
- I resolve a `implicit[JsonObjectEncoder[List[String]]]` instead of a `implicit[JsonEncoder[List[String]]]`
- I do not use implicit resolution and directly use `listEncoder[String].encode(List("a","b"))`

This is an edge case that fails at runtime but it seems to me that it should compile and run just fine.
Here is a [sample repo](https://github.com/ikempf/scala-sam-subtyping-bug) that reproduces the bug.

### Environnment
Scala: 2.12.3
Java: 1.8.0_102
JVM: HotSpot 25.102-b14

**Comment by hrhino** [comment]
Turns out you don't the implicits at all:

```scala
trait JV; trait JO extends JV
trait JE {
  def enc(a: Any): JV
}
trait JOE extends JE {
  def enc(a: Any): JO
}
object Test extends App {
  val one: JOE = (a: Any) => null
  val two: JE = one
  two.enc(12)
}
```

gives

```
java.lang.AbstractMethodError: Test$$$Lambda$144/708049632.enc(Ljava/lang/Object;)LJV;
	at Test$.delayedEndpoint$Test$1(exn.scala:16)
	at Test$delayedInit$body.apply(exn.scala:11)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1(App.scala:76)
```

because we're not giving our lambda the right bridges:

```
BootstrapMethods:
  0: #88 invokestatic java/lang/invoke/LambdaMetafactory.altMetafactory:(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;[Ljava/lang/Object;)Ljava/lang/invoke/CallSite;
    Method arguments:
      #89 (Ljava/lang/Object;)LJO;
      #92 invokestatic Boom$.$anonfun$one$1:(Ljava/lang/Object;)LJO;
      #89 (Ljava/lang/Object;)LJO;
      #93 2
      #94 0
```

I'm sure I've seen this or one of its twins before, though.

**Comment by ikempf** [comment]
I think you are reffering to [10477](https://github.com/scala/bug/issues/10477)
I first thought it was a duplicate (it may be ?) but in my case the bug only arises when using SAM.
Also when I do not use implicit resolution the issue does not manifest (I'll add this to my inital post)
