### ISSUE TITLE
Misleading error messages when calling empty argument method without parentheses

### ISSUE THREAD

**Issue by scalasolist** [scala/bug#10517]
Programmer should match number of parentheses in declaration of a method and its invocation. It is a general rule. But no one could eliminate mistakes completely. It would be good if compiler could accurately tell programmer what goes wrong.

Example containing mistakes:

    class Res[A]
    def mk1[X] = new Res[X]
    def mk2[Y]() = new Res[Y]
  
    val use1 : Res[Int] = mk1 // ok
    val use2 : Res[Int] = mk1() // error
    val use3 : Res[Int] = mk2  // error
    val use4 : Res[Int] = mk2[Int] // ok
    val use5 : Res[Int] = mk2() // ok

And the corresponding compiler output:

    PolymorphicEmpty.scala:7: error: test.package.Res[X] does not take parameters
      val use2 : Res[Int] = mk1() // error
                               ^
    PolymorphicEmpty.scala:8: error: polymorphic expression cannot be instantiated to expected type;
     found   : [Y]()test.package.Res[Y]
     required: test.package.Res[Int]
      val use3 : Res[Int] = mk2  // error
                            ^
    two errors found

The first error is described accurately. The second is the trap. I had personally fell for it. I had a much more complicated case and get polymorphic expression error frequently, so I spend large time to revise many part of my program in terms of handling types before I noticed that I forgot to remove extra parenthesis from the method declaration.

It would be great to either blame programmer for omitting parentheses explicitly, or to solve type inference neatly

-----------------------

    scalac -version
    Scala compiler version 2.11.8-20160304-000000-1706a37eb8

    java -version
    java version "1.8.0_144"
    Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
    Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

**Comment by SethTisue** [comment]
https://github.com/lampepfl/dotty/issues/2571

**Comment by SethTisue** [comment]
my guess is that a backport of the Dotty changes to Scala 2 would be accepted if it targeted 2.14

**Comment by som-snytt** [comment]
```
       warning: Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method mk2,
       or remove the empty argument list from its definition (Java-defined methods are exempt).
       In Scala 3, an unapplied method like this will be eta-expanded into a function.
```
