### ISSUE TITLE
compile mistake for void 

### ISSUE THREAD

**Issue by johnyannj** [scala/bug#10516]
jdk8:
one java interface:
`public interface IntefaceA{
 default void remove() {
        throw new UnsupportedOperationException("remove");
    }
}`

and one scala calass:
`class ClassB extends IntefaceA {
 overide remove() {throw UnsupportedOperationException}
}`

then make a new Java class

`public class ClassC extend ClassB{
}`

we will compile failed. because the the return type of classB in class file is "Nothing", not void....

**Comment by som-snytt** [comment]
There is an issue not to infer `Nothing` in override.

https://github.com/scala/bug/issues/7212

Similarly frequent with `Option`: https://github.com/scala/bug/issues/7873

The Scala method in the sample shouldn't be procedure syntax a/k/a `Unit`, which works.
