### ISSUE TITLE
StackOverflowError using Iterator ++ on 2.11.11

### ISSUE THREAD

**Issue by tksfz** [scala/bug#10525]
```
def iter(n: Int): Iterator[Int] = if (n <= 0) Iterator.empty else { Iterator.single(n) ++ iter(n - 1) }
iter(100000).foreach(print)
```

gets a StackOverflowError for me on Scala 2.11.11. But it works on Scala 2.12.2. Using `Stream.#::` works on both.

I think this is meant to work (that Iterator is meant to be stack-safe) given that `++` takes a by-name argument.

**Comment by som-snytt** [comment]
Duplicates #9623

**Comment by tksfz** [comment]
Awesome, apologies for the duplicate and thank you. I found that issue earlier but didn't notice the bit about not being on 2.11. (On the JIRA it has a Fix Version mentioning 2.11)

**Comment by SethTisue** [comment]
JIRA is just archival now, but I updated #9623 to have the right milestone

**Comment by som-snytt** [comment]
Sorry it didn't add the duplicates comment. I'm on a tablet.
