### ISSUE TITLE
Type inference issue in 2.12.4 nightly build

### ISSUE THREAD

**Issue by gkossakowski** [scala/bug#10535]
I'm testing building some code at Stripe with Scala 2.12.4 nightly (http://www.scala-lang.org/files/archive/nightly/2.12.x/scala-2.12.4-bin-c1c9c7c.tgz) and I get spurious warnings about type inference in very simple cases. E.g.:

```scala
sealed abstract class Environment
final case object Dev extends Environment
final case object Prod extends Environment
```

```scala
val env = if (sys.props("env") == "prod") (Prod: Environment) else (Dev: Environment)
```

gives this error:

```
warning: a type was inferred to be `Product with Serializable with com.stripe.....Environment`; this may indicate a programming error
  val env = if (sys.props("env") == "prod") Prod else Dev
```

**Comment by gkossakowski** [comment]
I'm a bit surprised by this error, I'd assume some basic tests would catch it.

**Comment by adriaanm** [comment]
Overzealous PR reversion submitted. Will refine for 2.12.5

**Comment by adriaanm** [comment]
Thanks for testing and reporting!!

**Comment by som-snytt** [comment]
It was noticed by the community build, as remarked on the reverted PR.

Everything moving so **quickly** this week -- No time to **react** -- Must -- commit! *commit!*

Please imagine that in the thought bubbles of a superhero comic.

To be fair, one really must be overzealous about `Product with Serializable`.

**Comment by adriaanm** [comment]
My comment was written in a rush -- I wish I had picked a better adjective, because I do appreciate the work on improving our lint checks, but I do think we need to refine this before we can ship it. -Xfatal-warnings is enabled in a lot of builds.

**Comment by gkossakowski** [comment]
Thanks for the swift response. I'll give a nightly build another whirl this afternoon.
