### ISSUE TITLE
AnyRefMap does not work on certain keys

### ISSUE THREAD

**Issue by hartleys** [scala/bug#10540]
Certain specific keys cannot be stored in AnyRefMaps.

For example: for the string "K00278:18:H7C2NBBXX:7:1111:7791:21465" (which is a read name from a DNA sequencer):

     val x = scala.collection.mutable.AnyRefMap[String,String]();
          #x: scala.collection.mutable.AnyRefMap[String,String] = Map()
     x("K00278:18:H7C2NBBXX:7:1111:7791:21465")= "foobar";
     x.size
          #res19: Int = 1
     x.keySet.size
          #res20: Int = 1

Despite listing a size of 1, the mapped value isn't actually accessible, and the key doesn't actually appear in the keyset:

     x.keySet.toList.size
          #res21: Int = 0
     x.get("K00278:18:H7C2NBBXX:7:1111:7791:21465")
          #res22: Option[String] = None
     x.keySet
          #res23: scala.collection.Set[String] = Set()
     x.toString
          #res24: String = Map()

This bug appears to be caused by a flaw in the code for AnyRefMap. It uses a hash function:

    private def hashOf(key: K): Int = {
        if (key eq null) 0x41081989
        else {
          val h = key.hashCode
          // Part of the MurmurHash3 32 bit finalizer
          val i = (h ^ (h >>> 16)) * 0x85EBCA6B
          val j = (i ^ (i >>> 13))
          if (j==0) 0x41081989 else j & 0x7FFFFFFF
        }
      }

When you use this on that particular read name:

     hashOf("K00278:18:H7C2NBBXX:7:1111:7791:21465")
          #res27: Int = 0

It checks for j==0, but doesn't check for j==0x80000000. So maybe just change it to:

          if (j==0 || j == 0x80000000) 0x41081989 else j & 0x7FFFFFFF

or maybe:

          if ((j & 0x7FFFFFFF)==0) 0x41081989 else j & 0x7FFFFFFF

or better yet, maybe replace the previous line with:

          val j = (i ^ (i >>> 13)) & 0x7FFFFFFF

Or maybe something slightly different? I don't know what the performance impact of these changes would be.

**Comment by SethTisue** [comment]
oh wow, really good catch.

@Ichoran, your dept?

**Comment by hartleys** [comment]
Heh, thanks. Until around 1pm today I was pretty sure that I was going insane.

**Comment by Ichoran** [comment]
Yeah, my department and my fault because I wrote that function.  Sorry for the trouble!

**Comment by Ichoran** [comment]
I'll submit a PR to fix this when I get home tonight.

**Comment by Ichoran** [comment]
`"JK1C=H"` is a string of shortest length with the offending hashcode.  It's -2105619938 (also attainable with `(-2105619938).asInstanceOf[AnyRef]`).

**Comment by Ichoran** [comment]
`"JK1C=H"` is a string of shortest length with the offending hashcode.  It's -2105619938 (also attainable with `(-2105619938).asInstanceOf[AnyRef]`).

**Comment by Ichoran** [comment]
https://github.com/scala/scala/pull/6117 (using the last of the fixes suggested by @hartleys)
