### ISSUE TITLE
classloader error when updating local jar

### ISSUE THREAD

**Issue by mpollmeier** [scala/bug#10541]
Note: At first sight you might think this is a sbt bug, but please keep reading. I guess that any similar build system would be affected in the same way for this very typical workflow: keeping sbt running while updating one of the project's snapshot dependencies.

## steps to reproduce
1. `git clone https://github.com/mpollmeier/sbt-publishlocal-bug.git`
1. open two terminals, one in library, one in service
1. in library: `sbt publishLocal`
1. in service: start sbt, run `compile` (everything compiles fine), keep sbt open
1. in library: change anything, e.g. `echo "object A" >> src/main/scala/Library.scala`
1. in library: `sbt publishLocal`
1. in service: run `compile` again

## Result
Fails to load the jar, with different error messages, depending on god knows why. These ones I've seen so far:

```
[error] error while loading Library, invalid stored block lengths

[error] error while loading Library, ZIP_Read: error reading zip file

[error] error while loading Library, class file '/home/mp/.ivy2/local/sbttest/library_2.12/0.1-SNAPSHOT/jars/library_2.12.jar(Library.class)' is broken
[error] (class java.lang.ArrayIndexOutOfBoundsException/627)

error while loading Library, read error
[error] /home/mp/tmp/sbt-publishlocal-bug/service/src/main/scala/Service.scala:3: Library does not have a constructor
```

followed by:
```
[error] /home/mp/tmp/sbt-publishlocal-bug/service/src/main/scala/Service.scala:3:11: Library does not have a constructor
[error]   println(new Library().foo)
[error]           ^
[error] two errors found
```

I was able to trace it down to this scala commit: https://github.com/scala/scala/commit/6cb50acfb5ee4df342e83d8505116d4607 which introduces `VirtualDirectoryFlatClassPath`. 

Here's the original issue I filed with sbt: https://github.com/sbt/sbt/issues/3584
I was hoping sbt could provide a workaround, e.g. by catching this error and reloading the classloader in that case, but didn't get any feedback so far.

**Comment by mpollmeier** [comment]
Update: this isn't a problem for sbt any more since 1.1.0-RC1 - jar loading seems to work differently now with sbt-server. This might still be a problem for other build systems, not sure though.

**Comment by halfmatthalfcat** [comment]
Ran into this today on `1.3.9`. Restarting/republishing to local fixed it.
