### ISSUE TITLE
NoSuchMethodError during initialization of adapted function

### ISSUE THREAD

**Issue by pbaun** [scala/bug#10554]
I have following macro:
```
import scala.language.experimental.macros
import scala.reflect.macros.blackbox

trait Example

object Example {
  def apply[T](f: Any => T): Example = macro applyImpl

  def applyImpl(c: blackbox.Context)(f: c.Tree): c.Expr[Example] = {
    import c.universe._
    val functionName = TermName(c.freshName())
    c.Expr[Example] {
      q"""
        new Example {
          val $functionName = $f
        }
      """
    }
  }
}
```
The following will throw NoSuchMethodError during initialisation of instance of generated class
```
scala> Example(_ => true)
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: .$anonfun$res3$1$adapted(Ljava/lang/Object;)Ljava/lang/Object;
  ... 38 elided
Caused by: java.lang.NoSuchMethodError: .$anonfun$res3$1$adapted(Ljava/lang/Object;)Ljava/lang/Object;
  at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
  at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
  at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987)
  at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390)
  at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746)
  at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
  ... 38 more
```
It works the same way with any primitive type and affects Scala 2.12.x. It doesn't throws exception on Scala 2.11 or with referential type. 
```
scala> Example(_ => "")
res0: example.Example = $anon$1@3b2b4a1a
```
Demo project: https://github.com/pbaun/macro-bug

Possibly it's a duplicate of #10054

**Comment by som-snytt** [comment]
It's not possible to push the incoming arg down into the anonymous class without repairing symbol ownership.

In this case, delambdafy wants to adapt the function and puts the adapter implementation on the anon class, but attempts to invoke it on `Main`, where other lambda bodies reside, because that's where the lambda started out and are lambdalifted. You want the lambda mechanisms on the anon class instead.

An easy fix is to leave the arg in its original context:
```
c.Expr[Example](q"{ val $functionName = $f ; new Example { val g = $functionName }}")
```

**Comment by som-snytt** [comment]
Other workarounds: `-Ydelambdafy:inline` or avoid lambdas of non-specialized types.
