### ISSUE TITLE
val with lazy behavior

### ISSUE THREAD

**Issue by fmeriaux** [scala/bug#10560]
Hello !

I noticed that in a class with a `val` it behaves like` lazy` as soon as a function is called during its initialization.

In the repository below, I have a `case class` that initializes a value by transforming a map via a 'resolve' function that returns an exception.

But the exception is not returned, unless attempting to access the value (behavior similar to the lazy).

Why this behavior? Is this a bug? If not, is there a way to force evaluation properly? I found nothing in my research.

Repository : 
https://github.com/fmeriaux/scala-val

**Comment by sjrd** [comment]
It's not the `val`, it's `mapValues`. [`mapValues`](https://www.scala-lang.org/api/current/scala/collection/Map.html#mapValues[W](f:V=%3EW):scala.collection.Map[K,W]) returns a view without eagerly copying the values. Your `resolve` functions is only called when you try and access the corresponding element.

**Comment by fmeriaux** [comment]
I thought about this, but I have not seen a .force method that you can usually find on views. Is there another way to force execution correctly ?

**Comment by hrhino** [comment]
You can (usually) use [`transform`](https://www.scala-lang.org/api/current/scala/collection/immutable/Map.html#transform[W,That](f:(K,V)=>W)(implicitbf:scala.collection.generic.CanBuildFrom[This,(K,W),That]):That), which is eager:

```scala
  /* effectively: def transform[W](f: (K, V) => W): Map[K, W] = { */
  def transform[W, That](f: (K, V) => W)(implicit bf: CanBuildFrom[This, (K, W), That]): That = {
    val b = bf(repr)
    for ((key, value) <- this) b += ((key, f(key, value)))
    b.result()
  }
```

**Comment by fmeriaux** [comment]
Effectively.. ! Thank you :)

I close this issue, thank you again for responding quickly.
