### ISSUE TITLE
Custom ClassLoader fails as a macro class loader in 2.12

### ISSUE THREAD

**Issue by ochrons** [scala/bug#10562]
When providing a custom class loader to Scala compiler Analyzer, it throws a `scala.NotImplementedError: an implementation is missing` when attempting to close the loader. This is due to `???` in `MacroRuntimes.scala`:

```scala
  private lazy val defaultMacroClassloaderCache = {
    def attemptClose(loader: ClassLoader): Unit = loader match {
      case u: URLClassLoader => debuglog("Closing macro runtime classloader"); u.close()
      case afcl: AbstractFileClassLoader => attemptClose(afcl.getParent)
      case _ => ???
    }
    perRunCaches.newGeneric(findMacroClassLoader, attemptClose _)
  }
```

ScalaFiddle provides a special "in-memory" class loader which failed the match above. The workaround is to "fake" it as a `URLClassLoader`.

This issue is not present in scalac 2.11

**Comment by som-snytt** [comment]
The questionable question marks were removed in https://github.com/scala/scala/pull/7366 in 2.13.
