### ISSUE TITLE
scala 2.12.4 access to java inner abstract class protected = not found

### ISSUE THREAD

**Issue by fkowal** [scala/bug#10568]
hello

when switching scala 2.12.3 -> 2.12.4
i encoundered a problem with accessing protected static method of an inner class
https://gist.github.com/fkowal/33369c5315d6bb2b14caf2bb6387b888#file-converter-java
```java
public interface Converter {
    abstract class FactoryFactory {

        protected static String getString() { // the problem is with accessing this method
            return "string";
        }
    }
}
```

i've prepared a gist illustrating the problem
https://gist.github.com/fkowal/33369c5315d6bb2b14caf2bb6387b888

**Comment by hrhino** [comment]
Yikes. I hope this has nothing to do with scala/scala#6058.

**Comment by SethTisue** [comment]
in the meantime (2.12.5 won't be out until March 2018 or so), is there a suggested workaround?

**Comment by hrhino** [comment]
Not an official one, but what I would do:
```java
package example;

import com.example.*;

abstract class ConverterFactoryFactoryAdapter extends Converter.FactoryFactory {
    public static String getString() {
        return Converter.FactoryFactory.getString();
    }
}
```
which lets you do
```scala
package example

import com.example.Converter
import com.example.Converter.FactoryFactory

class FactoryImpl extends FactoryFactory {
  import ConverterFactoryFactoryAdapter._
  def method(): Unit = {
    val s = getString()
  }
}
```

My apologies for breaking this.

**Comment by er1c** [comment]
@hrhino is this being worked on for `2.12.5` or are we stuck with this issue? thanks!

**Comment by hrhino** [comment]
On January 11, 2018 4:14:26 PM EST, Eric Peters <notifications@github.com> wrote:
>@hrhino is this being worked on for `2.12.5` or are we stuck with this
>issue? thanks!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/scala/bug/issues/10568#issuecomment-357063384

Thanks for the poke. I'll make a PR tomorrow and do my best to push it into 2.12.5.

**Comment by er1c** [comment]
@hrhino thank you!
