### ISSUE TITLE
assignment to tuple is not typechecked

### ISSUE THREAD

**Issue by happyser** [scala/bug#10574]
scala 2.11.8 (doesn't work in scala 2.12.4 either)

Following code compiles and fails on tuple assignment

   def tupleIssue() = {

    val (d: Long, justCreated: Boolean) = {

      if (false) {
        (true)
      } else {
        (None, false)
      }
    }
  }

**Comment by martijnhoekstra** [comment]
The if expression evaluates to Any, which just leaves us with https://github.com/scala/bug/issues/5898 - which makes this a duplicate I think?

**Comment by SethTisue** [comment]
duplicate of #5898
