### ISSUE TITLE
2.12.4 regression: 'params' cannot be negated, it enables other arguments

### ISSUE THREAD

**Issue by marconilanna** [scala/bug#10572]
This used to work in 2.12.3, but doesn't in 2.12.4 anymore:

```
$ scalac -Ywarn-unused:_ -Ywarn-unused:-params
scalac error: 'params' cannot be negated, it enables other arguments
```

**Comment by marconilanna** [comment]
Maybe it is related to https://github.com/scala/scala/commit/97ed2f4398bc6e910462133e9e3e0eb378455ae7? @som-snytt

**Comment by som-snytt** [comment]
Yes, that's the way it works now. You'd need to `-Ywarn-unused:-explicits,-implicits`.

Or `-Xlint:unused -Ywarn-unused:patvars,-implicits`.

**Comment by marconilanna** [comment]
@som-snytt Thank you for the pointer.

Given it is a build breaking change that is not mentioned in the [release notes](https://github.com/scala/scala/releases/tag/v2.12.4), may I suggest we add a quick line about it to the 2.12.4 release notes before someone else runs into the same problem?

Even after reading `scalac -Ywarn-macros:help` and `scalac -Xlint:help`, it wasn't obvious from the description that "`-Ywarn-unused:params` is an expanding option that enables both".

ccing @adriaanm

**Comment by SethTisue** [comment]
@som-snytt if you suggest a wording I'll add it to the release notes.

**Comment by som-snytt** [comment]
"`-Ywarn-unused:params` is now an expanding option that enables `-Ywarn-unused:implicits` for unused implicit parameters and `-Ywarn-unused:explicits` for other parameters. Those two options can be enabled independently of each other."

The help text for `params` could also say `enables...`.

**Comment by marconilanna** [comment]
> The help text for params could also say enables....

https://github.com/scala/scala/pull/6152 :-)
