### ISSUE TITLE
Compiling for a jdk8 while on jdk9

### ISSUE THREAD

**Issue by 2m** [scala/bug#10575]
When releasing the latest Akka version with jdk9 support, we bumped into an issue where due to the changes in jdk9 the code compiled with jdk9 failed to run on jdk8 (changes were made in `java.nio.ByteBuffer` and the corresponding [Akka ticket](https://github.com/akka/akka/issues/23755)).

While compiling Java code we can use the `--release` flag on `javac` to compile against an older jdk API. However there is no such flag on `scalac`.

**Comment by adriaanm** [comment]
cross-ref: https://github.com/scala/scala-dev/issues/139#issuecomment-321530343

**Comment by SethTisue** [comment]
@retronym is this fully resolved by https://github.com/scala/scala/pull/6362?

**Comment by SethTisue** [comment]
I'll assume so. we can open new tickets if there are unresolved aspects
