### ISSUE TITLE
AnyVal case class with Nothing member crashes compiler

### ISSUE THREAD

**Issue by puffnfresh** [scala/bug#10570]
The following code worked in scalac 2.11.8 but crashes the compiler under 2.12.2:

```scala
case class Void(underlying: Nothing) extends AnyVal
```

The problem is that scalac tries to generate a null somewhere and use it for the default value.

> Cannot emit primitive conversion from Lscala/runtime/Null$; to Lscala/runtime/Nothing$;

**Comment by hrhino** [comment]
This is a duplicate of #9240 and also #10361, and should work in 2.12.3 (following scala/scala#5938).

**Comment by puffnfresh** [comment]
I confirm this works under 2.12.4, thank you :heart:
