### ISSUE TITLE
Repl :type defines type alias instead of printing signature

### ISSUE THREAD

**Issue by fxk8y** [scala/bug#10586]
Using :type on some expression involving the declaration of a type alias works for simple aliases but declaring upper bounded types leads to interpretation instead of showing the types signature.
I also tried it with other types than structural ones(as shown below) and can confirm that the behavior is not related to the type declaration's type.

    Welcome to Scala 2.12.2 (OpenJDK 64-Bit Server VM, Java 1.8.0_131).
    Type in expressions for evaluation. Or try :help.
    
    scala> :type type T = { def t: String }
    AnyRef{def t: String}
    
    scala> :type -v  type T = { def t: String }
    // Type signature
    AnyRef{def t: String}
    
    // Internal Type structure
    RefinedType(
      parents = List(
        AliasTypeRef(
          Alias(type AnyRef = Object)
          normalize = TypeRef(TypeSymbol(class Object extends Any))
        )
      )
      decls = List(method t)
    )
    
    scala> :type -v type T <: { def t: String }
    defined type alias T
    
    scala> :type type T <: { def t: String }
    defined type alias T
    
    scala> :type -v  type T = { def t: String }
    // Type signature
    AnyRef{def t: String}
    
    // Internal Type structure
    RefinedType(
      parents = List(
        AliasTypeRef(
          Alias(type AnyRef = Object)
          normalize = TypeRef(TypeSymbol(class Object extends Any))
        )
      )
      decls = List(method t)
    )
    
    scala> :type -v  type T <: { def t: String }
    defined type alias T
    
    scala> def callt(t: T) = t.t
    <console>:12: warning: reflective access of structural type member method t should be enabled
    by making the implicit value scala.language.reflectiveCalls visible.
    This can be achieved by adding the import clause 'import scala.language.reflectiveCalls'
    or by setting the compiler option -language:reflectiveCalls.
    See the Scaladoc for value scala.language.reflectiveCalls for a discussion
    why the feature should be explicitly enabled.
           def callt(t: T) = t.t
                               ^
    callt: (t: T)String

As you can see at the end the defined type alias is real and usable but shouldn't be according to the manual.

    :type [-v] <expr>        display the type of an expression without evaluating it

**Comment by som-snytt** [comment]
The report has it backward. The textual repl just tries to interpret the expression text albeit lazily and see what gets defined. Definitions are simply interpreted. A concrete class is allowed to have an abstract type member, but repl doesn't see it as definition for import. The `:type` command just runs the interpreter as a fall-back, which is why `defined type alias` is printed, but the symbol is not actually available. It's not useful anyway.

```
$ scala
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

scala> $intp.definedSymbolList
res0: List[$intp.memberHandlers.intp.global.Symbol] = List(value $intp)

scala> $intp.symbolOfLine("type T = { def t: String }")
res1: $intp.global.Symbol = type T

scala> $intp.definedSymbolList
res2: List[$intp.memberHandlers.intp.global.Symbol] = List(value $intp, value res0, type T, value res1)

scala> type U = { def u: String }
defined type alias U

scala> $intp.definedSymbolList
res3: List[$intp.memberHandlers.intp.global.Symbol] = List(value $intp, value res0, type T, value res1, value res2, type U)

scala> def f(t: T, u: U) = ???
f: (t: T, u: U)Nothing

scala> type V <: { def v: String }
defined type alias V

scala> $intp.definedSymbolList
res4: List[$intp.memberHandlers.intp.global.Symbol] = List(value $intp, value res0, type T, value res1, value res2, type U, value res3, method f)

scala> def g(v: V) = ???
<console>:11: error: not found: type V
       def g(v: V) = ???
                ^

scala> 

```
