### ISSUE TITLE
Possible bug in bytecode emitted for methods that return an inner class where the parent has a type parameter

### ISSUE THREAD

**Issue by jroper** [scala/bug#10581]
This could either be a scalac bug, or an IntelliJ bug, I don't have the necessary knowledge of bytecode and the JLS to determine which.

If I have a Java parent class with a type parameter, an Inner class, and a method that returns that inner class:

```java
abstract class Parent<A> {
  class Inner {}
  Inner newInner() {
    return new Inner();
  }
}
```

And then I write class that extends it and invokes the method:

```java
class Child extends Parent<String> {
  Child() {
    Inner inner = newInner();
  }
}
```

This all works with no problems, javac compiles it fine, and IntelliJ type checks it with no problems.  However, if I rewrite `Parent` in Scala:

```java
abstract class Parent[A] {
  class Inner
  def newInner: Inner = new Inner
}
```

Then IntelliJ highlights an unchecked warning when you try to assign the result of `newInner` to an `Inner`. It appears that in the Java version, IntelliJ considers the return type of `newInner` to be `Parent<String>.Inner`, while in the Scala version, it considers the return type to be `Parent.Inner`.

Looking at javap, the signatures disagree with this, so maybe it's an IntelliJ bug, but then other IntelliJ behaviour leads me to believe that when compiling Java code, IntelliJ doesn't treat Scala classes any differently to Java classes, and I've verified that this behaviour happens when the Scala code is in a different compilation unit, so perhaps there is something different that scalac is emitting, perhaps a non spec conformance that javac happens to accept.

**Comment by jroper** [comment]
I've also raised this bug on IntelliJ:

https://youtrack.jetbrains.com/issue/SCL-12838

**Comment by lrytz** [comment]
I can reproduce in IntelliJ, but not on the command line. Passing `-Xlint:unchecked` to javac doesn't give any warning. I also checked the bytecode, it looks the same and correct. So I'm closing this.
