### ISSUE TITLE
-Xlint:unused false positive with private class in companion object

### ISSUE THREAD

**Issue by ruippeixotog** [scala/bug#10583]
The following code, when compiled with `-Xlint`, yields a warning:

```scala
import Container._

class Container {
  println(classOf[MyClass])
}

object Container {
  private class MyClass
}
```

```
[warn] Main.scala:8: private class MyClass in object Container is never used
[warn]   private class MyClass
[warn]                 ^
[warn] one warning found
```

In real world projects, this is happening to me because I'm using Java libraries and I need to pass a `Class` to be instantiated by reflection.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/9058
