### ISSUE TITLE
Seemingly bad class file with 2.12.4

### ISSUE THREAD

**Issue by countfloyd** [scala/bug#10594]
Compiled my project with 2.12.4 and when attempting to run it, I get this exception. Works fine with 2.12.3.

```
java.lang.ClassFormatError: StackMapTable format error: access beyond the end of attribute
	at com.stanfordcomputing.datumo.master.actors.MasterDatabaseActor$.$anonfun$props$1(MasterDatabaseActor.scala:31)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)
	at akka.actor.Props.newActor(Props.scala:213)
	at akka.actor.ActorCell.newActor(ActorCell.scala:563)
	at akka.actor.ActorCell.create(ActorCell.scala:589)
	at akka.actor.dungeon.FaultHandling.finishCreate(FaultHandling.scala:136)
	at akka.actor.dungeon.FaultHandling.faultCreate(FaultHandling.scala:130)
	at akka.actor.dungeon.FaultHandling.faultCreate$(FaultHandling.scala:120)
	at akka.actor.ActorCell.faultCreate(ActorCell.scala:370)
	at akka.actor.dungeon.FaultHandling.faultRecreate(FaultHandling.scala:59)
	at akka.actor.dungeon.FaultHandling.faultRecreate$(FaultHandling.scala:55)
	at akka.actor.ActorCell.faultRecreate(ActorCell.scala:370)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:465)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by jrudolph** [comment]
Can you post sources or the compiled class file?

**Comment by countfloyd** [comment]
Won't let me post .class or .scala files. I don't know if this will work but I renamed 3 MasterDatabaseActor class files as png.

![masterdatabaseactor](https://user-images.githubusercontent.com/286256/32616663-1b7e8a7a-c530-11e7-8a54-b32fc6381a0a.png)
![masterdatabaseactor](https://user-images.githubusercontent.com/286256/32616664-1b9f0188-c530-11e7-8aca-e0bf82d57397.png)
![masterdatabaseactor anonfun receive 1](https://user-images.githubusercontent.com/286256/32616666-1c158a6a-c530-11e7-823d-2a4ddb8f1e0e.png)

**Comment by SethTisue** [comment]
you can attach a `.zip` and put any file type inside

**Comment by countfloyd** [comment]
Oh, DUH. Here you go.
[classes.zip](https://github.com/scala/bug/files/1458720/classes.zip)

**Comment by lrytz** [comment]
@countfloyd it seems the bad stack map frame is emitted for the body of method `$anonfun$createInitialData$4`, which is the body of lambda defined in method createInitialData. The method is really large, according to the line number table it seems to span lines 83-808 in source code. `javap` fails to decode the `StackMapTable` attribute and gives

```
Error: java.lang.reflect.InvocationTargetException
        StackMapTable: length = 0x11
         00 05 FB 05 5E 42 07 00 04 FF FB 96 42 42 07 00
         04
```

So that's probably where the bug is.

I tried a few things but didn't manage to reproduce / understand the bug so far; is it possible for you to share the source code?

Most likely the bug is caused by our upgrade to asm 5.2 (Scala 2.12.3 used asm 5.1). In the release notes of 5.2 (https://projects.ow2.org/bin/view/asm/asm-5-2-is-out)

> #317630 Frames are re-calculated for Large Methods

**Comment by countfloyd** [comment]
Yes, that is a huge method. Should probably break it up a bit. Can I e-mail you the source file or otherwise post it so it's not public?

**Comment by countfloyd** [comment]
I broke up the method into smaller ones and the problem went away. Thanks for the tip.

**Comment by lrytz** [comment]
It would be great if you could e-mail me the source file (lukas.rytz@gmail.com).

**Comment by lrytz** [comment]
@countfloyd thanks for the source file (by email). I just managed to reproduce the issue locally by compilation from source, will dig into the causes later.

**Comment by lrytz** [comment]
"minimization" here: https://gist.github.com/lrytz/500adf9271d0c198994bbf79d62a1d16

**Comment by lrytz** [comment]
2.11.12 and 2.10.7 are also affected, also when running on Java 6.

**Comment by lrytz** [comment]
It seems to be a bug only in our ASM fork, not in the upstream. I used `ASMifier` to get a java source file that generates the classfile: https://gist.github.com/lrytz/59a9e2e27698d5e716d4caa1b9447cdf

I can reproduce the error when using `scala-asm-5.2.0-scala-2`

```
➜  sandbox git:(2.12.x) ✗ javac -cp /Users/luc/.ivy2/cache/org.scala-lang.modules/scala-asm/bundles/scala-asm-5.2.0-scala-2.jar CDump.java
➜  sandbox git:(2.12.x) ✗ java -cp /Users/luc/.ivy2/cache/org.scala-lang.modules/scala-asm/bundles/scala-asm-5.2.0-scala-2.jar:. CDump
➜  sandbox git:(2.12.x) ✗ scala -nc -e 'new C'
java.lang.ClassFormatError: StackMapTable format error: access beyond the end of attribute
```

But not when using stock ASM 5.2

```
➜  sandbox git:(2.12.x) ✗ javac -cp ~/Downloads/asm-5.2.jar CDump.java
➜  sandbox git:(2.12.x) ✗ java -cp ~/Downloads/asm-5.2.jar:. CDump
➜  sandbox git:(2.12.x) ✗ scala -nc -e 'new C'
➜  sandbox git:(2.12.x) ✗
```

**Comment by lrytz** [comment]
So the bug was introduced by the backport commit https://github.com/scala/scala-asm/commit/7b59db10a6c3eb58ca7f06b166d4d7600ba297f1, the first in https://github.com/scala/scala-asm/pull/3. I guess pushing that change in isolation onto asm 5.2 broke some assumptions (introduced by a different commit that was not backported). I think the best way to move forward is to upgrade to ASM 6 and avoid investing the time to actually debug the issue in detail.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6180
