### ISSUE TITLE
About AST token matching issue

### ISSUE THREAD

**Issue by HyejeanMOON** [scala/bug#10607]
Hi,

@adriaanm 

I want to create a plugin about build Control Flow Graph for Scala. 
In token matching step, I have some troubles, and do not understand this bug was happened  is Scala Compiler reason or my program. 
Could you tell me how to solve this problem. 
Thanks.

### The problem :
The plugin traverse AST token of target file, when matching "**If(cond,thenp,elsep)**" token, "**cond**","**thenp**" and "**elsep**" will be operating twice. Similarly, when matching "**while**" , same bug was happened. Like as below.

[https://drive.google.com/open?id=1lpz9SOcs2yK8DeDvoLszaaBIbQSYvO6e](url)
(There is a picture of CFG in google drive)
After ifExit_15,  **cond**, **thenp** and **elsep**  are operated again.

### The target file source code:

`

        package hello

        object ifTest{

         var v2=0
         var v4 = 0

         println("hello")

         if(v2 >= 100 && v4 <= 0) {
             val v1 = 11

         }else{
              println("hello false")
             val v3=33
         }

        }

`

### My source code(partial):
`

       val traverser(tree:Tree):Unit = new Traverser{

          override def traverse(tree: Tree):Unit={

          case i @ If(cond, thenp, elsep) =>

          // ifEntry -> condNode -> whenTrue -> Block -> ifExit
          //                      -> whenFalse -> Block -> ifExit

          val entryNode = "ifEntry" + "_" + UniqueIDs.UniqueIDsAdd     // node declaration
          Drawing(entryNode) // build graph

          val condString = decomposeBranches(cond)   // recognize "&&", "||", "!" from cond

          val condNode = "cond" + condString + "_" + UniqueIDs.UniqueIDsAdd
          Drawing(condNode)

          val exitNode = "ifExit" + "_" + UniqueIDs.UniqueIDsAdd       

          val whenTrue = "whenTrue" + "_" + UniqueIDs.UniqueIDsAdd
          Drawing(whenTrue)  

          for(t <- thenp){
               traverse(t)
          }
          
          Drawing(exitNode)

          lastNode = condNode

          val whenFalse = "whenFalse" + "_" + UniqueIDs.UniqueIDsAdd
          Drawing(whenFalse)

         for(e <- elsep){
               traverse(e)
         }

         Drawing(exitNode)
          
   
         }
     }
          

`

**Comment by SethTisue** [comment]
http://scala-lang.org/community/ has guidance on where to ask questions
