### ISSUE TITLE
Undesired implicit class shadowing in scala 2.12.3/2.12.4

### ISSUE THREAD

**Issue by fokot** [scala/bug#10606]
When I import implicit class with name and in the same scope I have field with same name, implicit conversion is not found.
```scala
object works {

  object bcrypt {
    implicit class Password(p: String) {
      def bcrypt = s"BCRYTPED_$p"
    }
  }

  import bcrypt._

  val PasswordString = ""

  val v = "PASSWORD".bcrypt
}

object fails { //same as `works`, but added value called `PasswordString` renamed to `Password`

  object bcrypt {
    implicit class Password(p: String) {
      def bcrypt = s"BCRYTPED_$p"
    }
  }

  import bcrypt._

  val Password = ""

  val v = "PASSWORD".bcrypt
}

object works_2 { //same as `fails`, but `Password` implicit class moved directly to the scope with `Password` field

  implicit class Password(p: String) {
    def bcrypt = s"BCRYTPED_$p"
  }

  val Password = ""

  val v = "PASSWORD".bcrypt
}
```

**Comment by fokot** [comment]
Maybe also other scala versions are affected I tested only these two

**Comment by ritschwumm** [comment]
i'm afraid this works as designed

**Comment by fokot** [comment]
I do not agree @ritschwumm. If this would be a function called `Password` than yes it should be hidden in this scope by `val Password`. But this is an implicit class. I know that it generates `implicit def Password` method. But now it is a class and type definition is not hidden. Type definition can be hidden only by another type not by a value. Thats why you have never problem distinguish between class and companion object.

**Comment by Jasper-M** [comment]
@fokot it is indeed the implicit def that gets shadowed, but that is what you need for an implicit conversion. So @ritschwumm is right.

**Comment by som-snytt** [comment]
https://docs.scala-lang.org/sips/implicit-classes.html

An implicit class is desugared into a class and implicit method pairing, where the implicit method mimics the constructor of the class.

The generated implicit method will have the same name as the implicit class. This allows importing the implicit conversion using the name of the class, as one expects from other implicit definitions.
