### ISSUE TITLE
2.12.4 regression: the compiler fails to reject unstable paths in types

### ISSUE THREAD

**Issue by sjrd** [scala/bug#10619]
With 2.12.3, and any other published version of Scala (incl. 2.11.12 and 2.13.0-M2):
```scala
$ ~/opt/scala-2.12.3/bin/scala
Welcome to Scala 2.12.3 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_40).
Type in expressions for evaluation. Or try :help.

scala> class Outer { class Inner }
defined class Outer

scala> def newOuter = new Outer
newOuter: Outer

scala> identity[newOuter.Inner] _
<console>:13: error: stable identifier required, but newOuter found.
       identity[newOuter.Inner] _
                ^

scala> val x: newOuter.Inner = ???
<console>:12: error: stable identifier required, but newOuter found.
       val x: newOuter.Inner = ???
```
which is the correct behavior.

With 2.12.4:
```scala
$ ~/opt/scala-2.12.4/bin/scala
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_40).
Type in expressions for evaluation. Or try :help.

scala> class Outer { class Inner }
defined class Outer

scala> def newOuter = new Outer
newOuter: Outer

scala> identity[newOuter.Inner] _
res0: Outer#Inner => Outer#Inner = $$Lambda$1060/2027587999@e7b265e

scala> val x: newOuter.Inner = ???
scala.NotImplementedError: an implementation is missing
  at scala.Predef$.$qmark$qmark$qmark(Predef.scala:284)
  ... 29 elided
```
which is bogus.

**Comment by milessabin** [comment]
FWIW, the approach taken in https://github.com/scala/scala/pull/5999 (creating a synthetic stabilizing val in circumstances similar to this) could be generalized to make the behaviour you're seeing here safe.

**Comment by sjrd** [comment]
I don't think you can, because there is no reasonable place to put your synthetic stable `val`. Let's take the statement
```scala
val f = Predef.identity[newOuter.Inner] _
```
Where you define the `val fresh = newOuter`? You certainly cannot declare as
```scala
val f = Predef.identity[{
  val fresh = newOuter
  fresh
}.Inner] _
```
So then, where? Are you going to use
```scala
val f = {
  val fresh = newOuter
  Predef
}.identity[fresh.Inner] _
```
Of course not, since `fresh.Inner` is not in the scope of `val fresh`. What then?

In general, there is no reasonable place to put a synthetic `val` that would make the behavior "safe".

And in fact, I don't *want* the behavior to be safe. I want it not to compile. I really shouldn't be using unstable path in type position, period.

**Comment by milessabin** [comment]
@sjrd you would hoist the stabilizing val out of the application,

```
val f = {
val fresh = newOuter
Predef.identity[fresh.Inner] _
}
```
`f` is useless of course, because it can't be applied, but it's not clear to me that that would be any more problematic than other cases where scoping makes escaping terms unusable.

**Comment by sjrd** [comment]
What if the receiver of my application (here `Predef`) has side-effects, and what I hoist is not pure (`newOuter`)? Still broken.

And what if it's in one of the zillions other places that types can appear, for example `val x: ATypeHere = ...` or `(expr: ATypeHere)`?

**Comment by Atry** [comment]
> What if the receiver of my application (here Predef) has side-effects, and what I hoist is not pure (newOuter)? Still broken.
`fresh` should be `lazy`, similar to https://github.com/lampepfl/dotty/pull/1993/files#diff-f37a8539e78b357dd6f5b90b83f842f1R261 . Thus no side effect will be performed.
``` scala
val f = {
  lazy val fresh = newOuter
  Predef.identity[fresh.Inner] _
}
```

> And what if it's in one of the zillions other places that types can appear, for example val x: ATypeHere = ... or (expr: ATypeHere)?
As long as there is an owner for the definition.

**Comment by Atry** [comment]
The 2.12.4 behavior is similar to `Foo[Bar]##Baz` syntax in https://github.com/ThoughtWorksInc/implicit-dependent-type . Really cool!

**Comment by sjrd** [comment]
No this is not "really cool". I don't *want* this to compile. [The spec](https://www.scala-lang.org/files/archive/spec/2.11/03-types.html) (section 3.1) doesn't want this code to compile. One doesn't simply put unstable paths in types! There's a good reason for this to be prohibited by the spec: because side effects in a type would be undefined behavior.

This is a *bug*, not a feature: the compiler used to be compliant with the spec, and isn't anymore.

If you want to change the spec, this has to go through a SIP. Until that change goes through the SIP process and is accepted, this is a bug.

**Comment by milessabin** [comment]
Whilst I understand your concerns wrt this specific issue, the broader question of introducing stabilizing vals is a perfectly reasonable one. And yes, maybe it does need a SIP.

Note that there are a number of other contexts in which synthetic vals are introduced (default arguments, right associative operator applications) which we currently treat as unproblematic. I appreciate that this is a bug, which is probably causing you grief right now, but please don't throw the baby out with the bathwater.

**Comment by sjrd** [comment]
There might have been a misunderstanding. All my comments here only apply to this specific issue. I am not questioning synthetic vals in general, nor even stabilization in general.

The core problem I have with this specific issue is that the suggestions to "make it work" are about moving a *path* from a *type* position (with no evaluation order even being *defined*) and putting it in a term position, which means inventing an evaluation order for it. That is really problematic.

I have also clarified my position on the linked PR https://github.com/scala/scala/pull/5999#issuecomment-348142647

**Comment by Atry** [comment]
IIRC, in the expression `foo.Bar`, `foo` is always a term position, no matter `Bar` is a type or not.

**Comment by Atry** [comment]
I thought the side effects in `foo` is orthogonal to stability, since Scala before 2.12.4 had allowed `foo` to be a `lazy val` that contains side effects already.

@sjrd FYI if your concern if side effects.

**Comment by sjrd** [comment]
> IIRC, in the expression foo.Bar, foo is always a term position, no matter Bar is a type or not.

Nope, if `foo.bar` is in type position, then `foo` is in *path* position, not arbitrary *term* position.

`lazy val`s in paths are broken. This has been discovered to lead to unsoundness in the language. Let's not use their existence as a precedent.

**Comment by Atry** [comment]
>then `foo` is in path position,

which can be expanded to arbitrary terms by a `selectDynamic` macro 😄

**Comment by Atry** [comment]
> This has been discovered to lead to unsoundness in the language. 

What effects soundness is the purity, not stability, considering Idris allows determining types from function calls.

**Comment by sjrd** [comment]
> which can be expanded to arbitrary terms by a selectDynamic macro

If you believe that because a macro (or compiler plugin) can technically do it, it is good language design, then I must stop arguing with you now. Otherwise we will both spend an eternity trying to convince each other of things that we find unacceptable.

**Comment by Atry** [comment]
There isn't a **path position** concept in the typer. That's why `selectDynamic` tricks can type check, even it breaks stability.

As you said, the stability concept introduced in SLS has been proven unsound due to side effects in `lazy val`.

`selectDynamic` do not ruin soundness. It's the side effects who break soundness, which is orthogonal to stability.

In brief:

 * Stability never works as its design purpose.
 * Stability can be workaround by `selectDynamic`.

**Comment by Atry** [comment]
> `lazy val`s in paths are broken. This has been discovered to lead to unsoundness in the language. Let's not use their existence as a precedent.


So does `js.native`. Are you going to turn `val foo: Foo = js.native` to an unstable expression?

**Comment by sjrd** [comment]
> So does js.native. Are you going to turn val foo: Foo = js.native to an unstable expression?

Er, what? The compiler prevents you from using `js.native` in any position where it would be part of the evaluation order. Including in lazy vals.

**Comment by Atry** [comment]
I thought I made an mistake about the soundness. It's `null` and `throw` make a path-dependent type unsound, not side effects, nor stability.

**Comment by sjrd** [comment]
Non-termination too.

**Comment by Atry** [comment]
If soundness is irrelevant to stability, what's the problem of removing the stable identifier restriction?

**Comment by sjrd** [comment]
The current stable identifier restriction is a pretty good approximation of the required guarantees. It can only be fooled by `null` and `lazy val`s, the latter not being admitted in dotty anymore IIRC. Removing that restriction opens the door to many more cases of unsoundess.

In addition, there is still the problem of arbitrary side effects being expressible in the context of a path position, which does not define an evaluation order.

**Comment by Atry** [comment]
Could give me an example in Dotty that breaks soundness when using `lazy val` without `throw`, `null` or `asInstanceOf`?

**Comment by Atry** [comment]
If I understand correctly:

1. The current Scala 2 is unsound in some mix-in types, no matter the prefix is `object`, `val`, `lazy val` or `def`(if allowed).
2. Dotty should be sound when avoiding `throw`, `null` or `asInstanceOf`, no matter the prefix is `object`, `val`, `lazy val` or `def`(if allowed).

**Comment by sjrd** [comment]
I don't have a link right now for the `lazy val` unsoundness, but it involves non-termination.

**Comment by sjrd** [comment]
https://github.com/lampepfl/dotty/issues/50#issuecomment-177341557

Replace the `???` in the `lazy val` by a non-terminating term, and you get the same problem: https://scastie.scala-lang.org/sjrd/w0lGqwvcT5yIdxfdHW9wJw

**Comment by Atry** [comment]
Yes. But it's still irrelevant to stability.  

The unsoundness is due to non-termination, and the similar problem can be seen without `lazy`.
https://scastie.scala-lang.org/rTT86qkFSK6ea8Ky2TOB1A

**Comment by Atry** [comment]
Non-lazy `val` is even worse than `lazy val` because non-lazy `val` never throws the`StackOverflowError` for non-terminated recursive function.

**Comment by Atry** [comment]
@milessabin What's the definition of "clearly unsound"?

**Comment by Atry** [comment]
Could you make a `ClassCastException` from the usage of unstable prefix?

**Comment by SethTisue** [comment]
is this truly a blocker for 2.12.5?

**Comment by lrytz** [comment]
I think it's bad enough to be a blocker.

**Comment by SethTisue** [comment]
PR: scala/scala#6359
