### ISSUE TITLE
-Ywarn-unused:locals false positives

### ISSUE THREAD

**Issue by alexknvl** [scala/bug#10623]
```scala
sealed trait Is[A, B] { ab =>
  def subst[F[_]](fa: F[A]): F[B]
  final def flip: B Is A = {
    type f[a] = a Is A
    subst[f](refl)
  }
}
def refl[A]: A Is A = ???
```

The compiler (2.12.4) complains that (with `-Xfatal-warnings` and `-Ywarn-unused:locals`)
```scala
[error] Is.scala:93:10: local type f is never used
[error]     type f[a] = a === A
```

**Comment by som-snytt** [comment]
It was discounting the reference because `f` aliases the enclosing trait.

The book-keeping is still in terms of `tree.tpe` and the `isUnusedType` check was already using `typeSymbolDirect`.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6190
