### ISSUE TITLE
Explicitly typed constant not really a constant?

### ISSUE THREAD

**Issue by jcranky** [scala/bug#10626]
This works:

```scala
class X {
  @SuppressWarnings(Array(test.msg))
  val bla: String = "asdf"
}

object test {
  final val msg = "bla"
}
```

But this fails:

```scala
class X {
  @SuppressWarnings(Array(test.msg))
  val bla: String = "asdf"
}

object test {
  final val msg: String = "bla"
}
```

The error is:

```console
/tmp/test.scala:3: error: annotation argument needs to be a constant; found: test.msg
  @SuppressWarnings(Array(test.msg))
                               ^
one error found
```

**Comment by jcranky** [comment]
I tested this on scala `2.11.1`, `2.12.1` and `2.12.4`.

**Comment by Jasper-M** [comment]
This is as specified in the paragraph about [constant value definitions](https://www.scala-lang.org/files/archive/spec/2.12/04-basic-declarations-and-definitions.html#value-declarations-and-definitions).

**Comment by jcranky** [comment]
@Jasper-M thanks, I was not aware of that. I have to say though that it is _very_ confusing. Why _no type annotation may be given_ ? Is there a rationale behind that, or is it just arbitrary?

**Comment by jcranky** [comment]
Ah, the singleton type! Now it makes sense to me, thanks!

**Comment by martijnhoekstra** [comment]
@jcranky I *think* https://github.com/scala/bug/issues/7542 is the canonical ticket, but I'm not sure.

**Comment by jcranky** [comment]
@martijnhoekstra ha, yes that is it, thanks! And this sentence really resonates with me:

> that there can be no type annotation, a requirement which seems utterly arbitrary to someone not versed in the implementation

**Comment by nmarasoiu** [comment]
Hi, can the value be computed like System.getProperty("a")? given that System is a final class and getProperty a static method?

**Comment by hrhino** [comment]
@nmarasoiu no, because the value of `System.getProperty("a")` isn't known at compile time, and constant values must be constant as of compile time.
