### ISSUE TITLE
Font contrast issue for "Filter All Members"

### ISSUE THREAD

**Issue by wenyangfu** [scala/bug#10634]
This issue was previously mentioned here: https://github.com/scala/docs.scala-lang/issues/937

While browsing API docs for [Scala 2.12.4](http://www.scala-lang.org/files/archive/api/2.12.4/scala/), I noticed that the font contrast for "filter all members" could use some adjustment; it was very difficult to read the words due to faint font coloring. Personally, I think other users would be confused by the purpose of this box (as I was initially).

I've highlighted the element in question with a blue box:
![scaladocs-filter-font-contrast](https://user-images.githubusercontent.com/6570181/33387964-3e4bd444-d4f4-11e7-9a69-71813f1a22c7.png)

I believe this affects all docs for Scala 2.12.x.

**Comment by ashawley** [comment]
The relevant HTML is:

```html
<input id='mbrsel-input' placeholder='Filter all members' type='text' accesskey='/'/>
```

Seems it will take adding a new entry with the `::placeholder` selector.  Perhaps, it should be applied on `#memberfilter > .input > input`.

There's a good chance this selector doesn't work across browsers, so it may require jamming in vendor-specific CSS.

https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder

Alternatively, one could change the background color of `#mbrsel` to something less contrasting that browsers can better automatically infer the placeholder color.

**Comment by nogurenn** [comment]
Hi, new guy here looking for first issues. Just pinging to ask if this could be closed by one of the primary contributors? Seems like the fix was already merged last year.

**Comment by ashawley** [comment]
I agree.  The contrast is better.

https://www.scala-lang.org/api/2.12.9/scala/
