### ISSUE TITLE
False positive for never used warning

### ISSUE THREAD

**Issue by fmeriaux** [scala/bug#10630]
Hello,

Since scala 2.12.4, this warning is logged : 

```
Warning:(223, 31) parameter value definitions in method reads is never used
  implicit def reads(implicit definitions: Definitions): Reads[ArrayProperty] = Json.reads[ArrayProperty]
```

Play json provided macros to create json formatters. The macro uses the implicit to create the instance, but the compiler does not detect it.

```scala
case class ArrayProperty(/* some attributes ... */)(implicit definitions: Definitions = Map.empty)
object ArrayProperty {
    implicit def reads(implicit definitions: Definitions): Reads[ArrayProperty] = Json.reads[ArrayProperty]
}
```

To my knowledge, there is no way of mutating this warning specifically...

**Comment by som-snytt** [comment]
If the variable is used in expanded code, use `-Ywarn-macros:after`. If the implicit is not used, use `-Ywarn-macros:none` to turn off linting for macros.

**Comment by fmeriaux** [comment]
Thank you.

It works, I close the issue.
