### ISSUE TITLE
Add canonical URL tag to scala API doc pages

### ISSUE THREAD

**Issue by lajnakjjfn** [scala/bug#10640]
https://publicobject.com/2017/02/14/canonical-urls-for-javadocs/ reminded me that the described issue seems to also be present for the docs at http://www.scala-lang.org/api.

The issue being, when e.g. searching for 'scala bigint', Google [shows](https://www.google.com/search?q=scala+bigint) links for the 2.7.4 and 2.12.0 API docs, but not for the 'current' version.

Would it make sense to insert canonical URL tags in the future API doc pages on scala-lang.org/api, or even retroactively in the existing versions?

**Comment by SethTisue** [comment]
yes, I believe a pull request that added this would be welcome

but, it isn't obvious to me without doing a little research if this should be a change to the Scaladoc tool, or a change to https://github.com/scala/scala-dist, or what

applying the change retroactively would require running a script on the machine that serves scala-lang.org, but we could certainly do that too — if the pull request included such a script, which had been tested first locally, that would be super-awesome

**Comment by mslinn** [comment]
Please consider this an actionable request for supporting the Scala-related educational community.

Most of the 1402 Scaladoc links in our 2 Scala courses broke with the Scala 2.13 release. The URLs changed. A canonical URL would have prevented that, and might also provide a universally accepted shortening method so no bazillion-character-long URLs would be generated.

Yes, I wrote a script to generate SQL commands to update the transcript database. I also have to go through the Adobe Premiere Pro lecture projects for all 110 lectures. This is going to take a very, very long time.

**Comment by Jasper-M** [comment]
> Most of the Scaladoc links in our 2 Scala courses broke with the Scala 2.13 release (~350 links in 110 lectures) because the URLs for method-level docs changed. This was not a problem for previous Scala releases. Canonical URLs would have prevented that

I'm not sure how you would maintain this across different Scala version (except manually for each class and method). The reason the urls changed is that classes changed packages and methods changed signatures.

Also note that although this issue is closed because scaladoc _supports_ setting a canonical url, I don't think that the scaladoc of the standard library already contains canonical urls.

**Comment by mslinn** [comment]
I don't think I did a good job of explaining myself. 

 * The autogenerated URLs are unwieldy, so a standard algorithm for shortening them would help
 * Several different URL generation mechanisms have been used over the years. I'm asking for a stable mechanism, which I called "canonical" per the [link I provided](https://yoast.com/rel-canonical/).
