### ISSUE TITLE
cryptic "double definition" error while instantiate a trait

### ISSUE THREAD

**Issue by doofin** [scala/bug#10654]
while experimenting with autowire library(https://github.com/lihaoyi/autowire) ,
scalac reports 
`
[error] /home/d/work/scalajs-spa-tutorial/server/src/main/scala/controllers/Application.scala:52: double definition:
[error] override def write(r: Object,implicit evidence$2: Object): Object at line 52 and
[error] override def write(r: Object,implicit evidence$2: Object): Object at line 52
[error] have same type
[error]       new autowire.Server[ByteBuffer, Pickler, Pickler] {
[error]           ^
[error] one error found

`
for the following code 
```scala
  def autowireGet[AutoWireApiT](api:AutoWireApiT,reqPath:String,reqBodyBytes:ByteString): Future[ByteBuffer] ={
    new autowire.Server[ByteBuffer, Pickler, Pickler] {
      override def read[R: Pickler](p: ByteBuffer) = Unpickle[R].fromBytes(p)
      override def write[R: Pickler](r: R) = Pickle.intoBytes(r)
    }.route[AutoWireApiT](api)(
      autowire.Core.Request(
        reqPath.split("/"),
        Unpickle[Map[String, ByteBuffer]].fromBytes(reqBodyBytes.asByteBuffer))
    )
  }


//relevant traits:
trait Server[PickleType, Reader[_], Writer[_]] extends Serializers[PickleType, Reader, Writer] {
  type Request = Core.Request[PickleType]
  type Router = Core.Router[PickleType]
  /**
   * A macro that generates a `Router` PartialFunction which will dispatch incoming
   * [[Requests]] to the relevant method on [[Trait]]
   */
  def route[Trait](target: Trait): Router = macro Macros.routeMacro[Trait, PickleType]

}


trait Serializers[PickleType, Reader[_], Writer[_]] {
  def read[Result: Reader](p: PickleType): Result
  def write[Result: Writer](r: Result): PickleType
}
```

sbt.version=0.13.15
scala version  = "2.11.11"

**Comment by Jasper-M** [comment]
Are you sure this is not an issue with autowire? Or with the way you are trying to use autowire?

**Comment by Jasper-M** [comment]
I can't reproduce this.

**Comment by SethTisue** [comment]
@doofin we can reopen if you can boil it down to a [MCVE](https://stackoverflow.com/help/mcve). in general, scala/bug is where you come once you've become done due diligence and have become reasonably certain you have found a previously unreported bug in Scala. it's where bug reporting ends, not where it starts.
