### ISSUE TITLE
Question: annotation argument needs to be a constant

### ISSUE THREAD

**Issue by nmarasoiu** [scala/bug#10651]
Hi,
In this snippet,
```
@SwaggerDefinition(...authorizationUrl = SecurityConstants.authorizationUrl)
```
and given that
```
final object SecurityConstants {
  final val authorizationUrl: String =..
}
```
(only one of the two finals should be ok, but still)
I was expecting/hoping that this would compile with 2.12.3 but it is however giving 
"annotation argument needs to be a constant; found: SecurityConstants.authorizationUrl
[error]         authorizationUrl = SecurityConstants.authorizationUrl,"

Also calling Java static method System.getenv("a") in annotation brings the same error, that is 
```
@SwaggerDefinition(...authorizationUrl = System.getenv("a"))
```
Please help,
Nicu M

**Comment by lrytz** [comment]
This issue tracker is only to report bugs, questions can be asked on the forum (https://users.scala-lang.org/) or on StackOverflow.
