### ISSUE TITLE
Binding precedence not respected for enclosing package in unit

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#10662]
Even after #2458 the implementation still won't respect `p.X`, as it only looks for the first definition from enclosing scopes. The reference should be ambiguous because `p.q.X` is defined elsewhere.

```
package p {

  class X {
    override def toString() = "p.X"
  }

  package q {
    //import p.X  // "permanently hidden"
    object Test extends App {
      println(new X)
    }
  }
}
```
and in a different compilation unit:
```
package p.q

class X { 
  override def toString() = "p.q.X"
} 
// similarly for package object q { type X = other }
```

**Comment by SethTisue** [comment]
@som-snytt is https://github.com/scala/scala/pull/7609 something you plan to return to, or is this up for grabs?

**Comment by som-snytt** [comment]
I'll give it another shot. Thanks, I'd forgotten about this one, which was the final nail in spec chapter 2. I'd say it's up for grabs like the bouquet at a wedding, but does anyone really want to get tied down to a total leftover no one understands or cares about? Also, "A foreign definition induces ambiguity" is my other political joke.
