### ISSUE TITLE
vals in an Enumeration referencing a Value changes the Enumeration

### ISSUE THREAD

**Issue by rjsvaljean** [scala/bug#10664]
When I have an Enumeration with a value in the Enumeration object that's an alias for one of the values in the Enumeration (here `Cab` is an alias for `Aab`)

```
object Xab extends Enumeration {
  type Xab = Value
  val Aab, Bab = Value
  val Cab = Aab
}
```

`Xab.values` gives me `Xab.ValueSet(Cab, Bab)` instead of what I'd expect `Xab.ValueSet(Aab, Bab)`

It seems to have started breaking in **2.12.0-M2** (is still broken in **2.12.4**). Scala **2.11.6** does the right thing.

A coupe of other observations:
- it works correctly with scala 2.12.0-M2 if all of the variables names are just one character. So, if I use `X`, `A` and `B` (removing the `...ab` suffixes in all the names) , `.values` gives be `X.ValueSet(A, B)`
- making `Cab` a `def` fixes the issue

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/5462

**Comment by som-snytt** [comment]
It turns out you can get either result on either version, comment on linked ticket.
