### ISSUE TITLE
use of custom unapply breaks exhaustivity checking

### ISSUE THREAD

**Issue by fommil** [scala/bug#10660]
In 2.12.4 the following code (correctly) warns on compile due to exhaustivity checking

```scala
sealed abstract class Maybe[A]
final case class Empty[A]() extends Maybe[A]
final case class Just[A](a: A) extends Maybe[A]

Just(1) {
  case Just(2) => true
  case Empty() => true
}
```

but the following, with an alternative encoding of `Empty` (#10659) compiles without warning

```scala
  final case object Empty extends Maybe[Nothing] {
    def apply[A](): Maybe[A] = this.asInstanceOf[Maybe[A]]
    def unapply[A](e: Maybe[A]): Boolean = this == e
  }
```

Guessing, it looks like the presence of the "custom" `unapply` causes the more aggressive checkers not to trigger. Perhaps the presence of the custom unapply should only disable the aggressive checking around the `Empty`, not around the entire ADT `Maybe`.

// @xuwei-k

**Comment by sjrd** [comment]
Well of course it breaks exhaustivity checking, because the match might indeed not be exhaustive, if you replace the *body* of your `unapply` by `false`. The compiler has no way to inspect the body of your `unapply` to make a decision about exhaustivity.

**Comment by fommil** [comment]
Then it is broken in two ways. The one I care about is that it no longer warns that Just is not covered.

**Comment by sjrd** [comment]
Replace the body of your `unapply` by `true` and now `Just` is covered.

**Comment by fommil** [comment]
But that is then broken.

The custom extractor is against Maybe, so perhaps there is no way to fix this.

**Comment by sjrd** [comment]
> But that is then broken.

*You* know that. The compiler has no idea.

**Comment by fommil** [comment]
yes, but that's just further evidence that the compiler should be *more* cautious, not less. It's almost like the exhaustiveness checker is assuming that Boolean unapply is returning true.

**Comment by TomasMikula** [comment]
So you would like a warning every time the compiler cannot prove exhaustiveness (as opposed to when it can prove non-exhaustiveness)?

**Comment by fommil** [comment]
That would be pretty good, yes! Effectively forcing pattern matches only for destructuring. I'm aware the motivating example is therefore excluded.

**Comment by SethTisue** [comment]
I'd love to have an annotation that fails compilation on non-exhaustive matches (somewhat like `@tailrec`). I looked for an existing ticket on that but failed, anyone know of one?

**Comment by fommil** [comment]
I did the same search when I wanted to close this as a dupe, and realised this is the closest we have. But my ticket search foo is pretty bad.

**Comment by fommil** [comment]
I added a custom unapply to the scalaz IList, looking like this

```scala
  object :: {
    def unapply[A](xs: ICons[A]): Option[(A, IList[A])] = xs match {
      case ICons(head, tail) => Some(head -> tail)
    }
  }
```

*even though* the input type is `ICons`, it still disables the exhaustivity checker for `INil`

in addition, the definition of an `unapplySeq` also breaks exhaustivity checking, e.g.

```scala
  def unapplySeq[A](ilist: IList[A]): Option[Seq[A]] = Some(ilist.toList)
```

It is debatable what should and shouldn't disable the matcher. But I feel it shouldn't happen silently (there is a scalafix request for this).

**Comment by durban** [comment]
@SethTisue See https://github.com/scala/scala/pull/5617.

**Comment by LPTK** [comment]
In addition to this, it would be very nice if the exhaustive checker could special-case extractors that return `Some[T]` or the `true` literal type, and assume that these extractors can never fail.

Conceptually, the `unapply` shown by @fommil above should really be:

```scala
    def unapply[A](xs: ICons[A]): Some[(A, IList[A])] = xs match {
      case ICons(head, tail) => Some(head -> tail)
    }
```

It compiles, but neither Dotty nor Scalac leverage the additional knowledge. This would address @sjrd's remark that the compiler currently has no clue whether an extractor is fallible or not, although that is arguably an important semantic distinction. Would also probably help with https://github.com/lampepfl/dotty/issues/2575.

Perhaps that should be a separate ticket.

**Comment by smarter** [comment]
> It compiles, but neither Dotty nor Scalac leverage the additional knowledge.

They both do in some situations, for example in:
```scala
sealed trait Base
case class One() extends Base
object Foo {
  def unapply(x: Base): Option[Int] =
    Some(0)
}

object Test {
  def test(x: Base) =
    x match {
      case Foo(a) => a
    }
}
```
You get a "match may not be exhaustive" warning for Dotty, if `Option[Int]` is replaced by `Some[Int]`, the warning goes away.

**Comment by LPTK** [comment]
@smarter you're right, they seem to do the right thing for `Some`-returning extractors!, though Dotty has [some weird rough edges](https://scastie.scala-lang.org/yrtkGWgeR066M0rZZjxwMQ). However, Dotty doesn't seem to like extractors with return type `true` (see the same link).

**Comment by smarter** [comment]
@LPTK Feel free to open issues for any problem you encounter, it helps!

**Comment by TomasMikula** [comment]
@LPTK The Scala issue for `Some`-returning extractors is #10502.

**Comment by LPTK** [comment]
@jcracknell maybe we should open another issue for that. It does seem a little surprising, and I think emitting a warning for this would be a good idea.
