### ISSUE TITLE
Should `trait Foo <: Bar` syntax compile?

### ISSUE THREAD

**Issue by Atry** [scala/bug#10678]
```
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_152).
Type in expressions for evaluation. Or try :help.

scala> trait Foo
defined trait Foo

scala> trait Bar <: Foo
defined trait Bar
```

https://www.scala-lang.org/files/archive/spec/2.12/05-classes-and-objects.html#traits

> ```
> TmplDef          ::=  ‘trait’ TraitDef
> TraitDef         ::=  id [TypeParamClause] TraitTemplateOpt
> TraitTemplateOpt ::=  ‘extends’ TraitTemplate | [[‘extends’] TemplateBody]
> ```

**Comment by som-snytt** [comment]
I remember hearing from old-timers that it was a synonym for `extends`.

The production is still enshrined in the code if not the spec:

```
     *  TraitTemplateOpt ::= TraitExtends TraitTemplate | [[`extends'] TemplateBody] | `<:' TemplateBody
     *  TraitExtends     ::= `extends' | `<:'
```

It obeys the rule of "optional `extends`":

```
scala> trait Bar <: {
     | def bar = 42
     | }
defined trait Bar
```

I'm going to hurry up and use it before we lose it.

**Comment by propensive** [comment]
I vote to spoil the party and deprecate it asap. It doesn't work in Dotty, FWIW.

**Comment by som-snytt** [comment]
OMG @propensive as party pooper. I fell asleep without figuring out if there was a moment when they intended to deprecate but it somehow fell through the cracks. I did see that it's not in the spec conversion to markdown.

Deprecation is warranted, because the tide of history is against symbolical things, but not without noting the beautiful symmetry with
```
type Bar <: something
```
It expresses an intuition about what is a trait. People still ask should I use trait or class, and usually the answer is merely pragmatic.

**Comment by Atry** [comment]
Another party pooper here: [Inheritance is not subtyping](https://dl.acm.org/citation.cfm?id=96721)

**Comment by propensive** [comment]
@som-snytt I wonder if the syntax originated from a virtual class ("virtual" as in "virtual method") experiment around 2007 which never worked. There was a paper, which I can no longer find, called something like "Scala Tribes". I quite liked the idea at the time, much as I also liked the Cake Pattern, which is no coincidence.

**Comment by milessabin** [comment]
It was definitely part of one of the virtual class experiments.

**Comment by som-snytt** [comment]
Yes, that's right. I was just about to send a PR. So surreal that it's 2 a.m. and two of my heroes chime in. Are you sitting at a cafe somewhere?

For the record, everyone likes cake.

**Comment by Atry** [comment]
I created a [Factory](https://javadoc.io/page/com.thoughtworks.feature/factory_2.12/latest/com/thoughtworks/feature/Factory.html) type class, which dynamically creates abstract types, simulated the behavior of virtual class.

**Comment by Atry** [comment]
I think one day we can bring virtual class back by some simple untyped transformers, with the help of the DOT calculus.

However, Scala2 seems not possible to support virtual class correctly, due to https://github.com/scala/bug/issues/10665 and other typer issues.

**Comment by SethTisue** [comment]
nice catch @Atry! and thanks @som-snytt for the fix
