### ISSUE TITLE
"illegal cyclic reference involving type" regression in 2.13.0-M2

### ISSUE THREAD

**Issue by soronpo** [scala/bug#10676]
```scala
trait Impl[T]
object Impl {
  implicit def impl[T] : Impl[T] = new Impl[T] {}
}

type Alias = Impl[shapeless.Witness.`1`.T]
implicit def foo(implicit alias : Alias) : Unit ={} //illegal cyclic reference involving type Alias
```
Tried several Scalac versions:
:x: 2.11.12
:white_check_mark: 2.12.4
:x: 2.13.0-M2

The following code variations get rid of the error:
```scala
//not using type alias
implicit def foo(implicit alias : Impl[shapeless.Witness.`1`.T]) : Unit ={} 
```
```scala
//definition not implicit
def foo(implicit alias : Alias) : Unit ={} 
```
```scala
//not using a singleton type
type Alias = Impl[Int]
implicit def foo(implicit alias : Alias) : Unit ={}
```

**Comment by milessabin** [comment]
Can you reproduce this without shapeless's `Witness`?

**Comment by soronpo** [comment]
>Can you reproduce this without shapeless's Witness?

I did not manage to find a way . I tried typelevel scala with a literal-type, and everything was OK.

**Comment by soronpo** [comment]
I checked this now for 2.13.0-M3, and it's somehow fixed :open_mouth: 
So I'm closing.
