### ISSUE TITLE
Element 1 not accessible in Bitset2

### ISSUE THREAD

**Issue by aaggarwal35** [scala/bug#10677]
In BitSet2 definition (Scala 2.11.12, but true for [newer versions](https://github.com/scala/scala/blob/07d61ecf134dbba143531f5a1bd3c1289c437296/src/library/scala/collection/immutable/BitSet.scala#L124) as well):

```
package scala
package collection
package immutable

...
object BitSet {
..
  class BitSet2(val elems0: Long, elems1: Long) extends BitSet {
...
}
```

`elems1` is not exposed. All other elements (including `BitSet1` and `BitSetN`) are available.

To be consistent, `elems1` should also be marked as `val`.

**Comment by hrhino** [comment]
I would think that the `BitSet` subclasses aren't really public API; it makes more sense that they would be private. Do you have a use case for getting the raw `Long`s?

On the other hand, the new collections [also have this same code](https://github.com/scala/collection-strawman/blob/master/collections/src/main/scala/strawman/collection/immutable/BitSet.scala#L116), so maybe it's worth bringing up over there. It's not possible to add the `val` for binary compatibility reasons in 2.12.x, so 2.13 would be the chance to go one way or the other.

**Comment by aaggarwal35** [comment]
There are other ways to access the data (`toList`, `iterator`). My suggestion was mostly to ensure consistent API.

I agree that those subclasses are mostly an implementation detail and might be better off being hidden.
