### ISSUE TITLE
polymorphic expression cannot be instantiated to expected type

### ISSUE THREAD

**Issue by mfolnovic** [scala/bug#10688]
Hello,

I've already asked on Gitter about this, and got a solution/hint for how to fix this... I'm reporting this because in case this is also a bug in scalac.

I have: https://scastie.scala-lang.org/NpVJKdeDQviL2Az5Kbpwnw

As you can see, `method2` and `method3` compiles but `method1` doesn't, even though `method3` is just `store expression in value` and `return that value`.

Also, this fully compiles: https://scastie.scala-lang.org/HJ7vEk0nQFq7mYdAzP2HNw
(I've just changed `Node[Info]` to `Node[+Info]`)

Sorry if this is known bug / duplicate.

**Comment by SethTisue** [comment]
although we appreciate the report, the way this repo works is:

if you're not sure whether something is a bug, please start by posting to users.scala-lang.org (or contributors.scala-lang.org if sufficiently confident)

open a ticket here on scala/bug once you've become reasonably certain 1) it's a bug and 2) isn't a duplicate
