### ISSUE TITLE
Order of TypeVar constraints affects unification

### ISSUE THREAD

**Issue by joroKr21** [scala/bug#10686]
Contrived example, but situations like that _can_ arise during implicit search and they make the difference between success and failure:
```scala
def foo[A](implicit ev: (Int, String) =:= (Int, A)): (Int, A) = null
def bar[A](implicit ev: (Int, A) =:= (Int, String)): (Int, A) = null
foo // nope
bar // ok
```
The cause for this?
```scala
scala> val wild = appliedType(typeOf[(_,_)].typeConstructor, IntTpe, WildcardType)
wild: $r.intp.global.Type = (Int, ?)

scala> lub(wild :: typeOf[(Int, String)] :: Nil)
res2: $r.intp.global.Type = (Int, ?)

scala> lub(typeOf[(Int, String)] :: wild :: Nil)
res3: $r.intp.global.Type = (Int, String)
```
It doesn't look right to me. What if `TypeVar` constraints were not added in reverse order?

**Comment by retronym** [comment]
The reminds me a bit of https://github.com/scala/bug/issues/8740#issuecomment-292432768.

I think your fix for this bug is promising. I wonder, can we push this into `lub`/`glb` itself, so that they never return `?` when a non-wildcard is part of list of types?

**Comment by joroKr21** [comment]
I wonder the same thing, but I don't know where to add the check for `?` `lub` and `glb` are a lot more complicated than I imagined.

**Comment by retronym** [comment]
Does something like this work?

```diff
diff --git a/src/reflect/scala/reflect/internal/tpe/GlbLubs.scala b/src/reflect/scala/reflect/internal/tpe/GlbLubs.scala
index 814e1640e0..95a35d15e8 100644
--- a/src/reflect/scala/reflect/internal/tpe/GlbLubs.scala
+++ b/src/reflect/scala/reflect/internal/tpe/GlbLubs.scala
@@ -283,6 +283,7 @@ private[internal] trait GlbLubs {
     def lub0(ts0: List[Type]): Type = elimSub(ts0, depth) match {
       case List() => NothingTpe
       case List(t) => t
+      case WildcardType :: ts => lub(ts)
       case ts @ PolyType(tparams, _) :: _ =>
         val tparams1 = map2(tparams, matchingBounds(ts, tparams).transpose)((tparam, bounds) =>
           tparam.cloneSymbol.setInfo(glb(bounds, depth)))
@@ -421,6 +422,7 @@ private[internal] trait GlbLubs {
   def glb(ts: List[Type]): Type = elimSuper(ts) match {
     case List() => AnyTpe
     case List(t) => t
+    case WildcardType :: ts => lub(ts)
     case ts0 =>
       if (StatisticsStatics.areSomeColdStatsEnabled) statistics.incCounter(lubCount)
       val start = if (StatisticsStatics.areSomeColdStatsEnabled) statistics.pushTimer(typeOpsStack, lubNanos) else null
```

**Comment by joroKr21** [comment]
No, I don't think that will work. I looked at it closer and AFAICT the problem appears in `elimSub`/`elimSuper`. Besides, the wildcard can be buried in a composite type. The abstraction that leaks is that for any type `T` both `T <: ?` and `? <: T`. Which means that top-level wildcards don't make it as constraints but they can hop on the train of a more complex type like `(Int, ?)`.

**Comment by joroKr21** [comment]
Dotty doesn't seem to have this problem
