### ISSUE TITLE
List item is changed to null

### ISSUE THREAD

**Issue by MartinMajor** [scala/bug#10687]
Hello,

code itself is pretty self-explanatory:

```scala
sealed abstract class State(name: String, optional: String = "hello")

object State {
  case object Closed extends State("closed")
  case object Open extends State("open")
  case object Ended extends State("ended")

  val values = List(Closed, Open, Ended)
}

val x = State.Open
println(State.values) // writes "List(Closed, null, Ended)" instead of "List(Closed, Open, Ended)"
```

When State contains optional argument then `values` List changes item that is accessed first to `null`.

When I remove `optional` argument or does not access `State.Open`, output is as expected.

I'm using: `Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_121)`

**Comment by hrhino** [comment]
That's fun. When you access `State.Open`, you're initializing `Open`, which calls the `State` constructor, but needs to access the argument's default. That's stored in the `State` companion, which gets initialized, and (as part of that) calculates `values`.

As a workaround, you can make `values` a `lazy val`.

**Comment by Jasper-M** [comment]
I would think the correct behavior would be that `State` always gets initialized first when something in `State` gets accessed, whether that's an object, a val, a lazy val or a def.

Conceptually the above should behave the same (other than the exact text being printed) as the following, but it doesn't:

```
sealed abstract class State(name: String, optional: String = "hello")

object State {
  lazy val Closed = new State("closed"){}
  lazy val Open = new State("open"){}
  lazy val Ended = new State("ended"){}

  val values = List(Closed, Open, Ended)
}

val x = State.Open
println(State.values)
```

**Comment by hrhino** [comment]
On January 10, 2018 7:13:03 AM PST, Jasper Moeys <notifications@github.com> wrote:
>I would think the correct behavior would be that `State` always gets
>initialized first when something in `State` gets accessed, whether
>that's an object, a val, a lazy val or a def.
>
>Conceptually the above should behave the same (other than the exact
>text being printed) as the following, but it doesn't:
>
>```
>sealed abstract class State(name: String, optional: String = "hello")
>
>object State {
>  lazy val Closed = new State("closed"){}
>  lazy val Open = new State("open"){}
>  lazy val Ended = new State("ended"){}
>
>  val values = List(Closed, Open, Ended)
>}
>
>val x = State.Open
>println(State.values)
>```
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/scala/bug/issues/10687#issuecomment-356631549

Indeed. I wonder if this is an overzealous `isExprSafeToInline` or something.

Or, more spookily, to spec.

**Comment by som-snytt** [comment]
Pretty sure this exactly duplicates https://github.com/scala/bug/issues/5366
