### ISSUE TITLE
Array literals should be constant expressions

### ISSUE THREAD

**Issue by Jasper-M** [scala/bug#10698]
According to [the spec](https://www.scala-lang.org/files/archive/spec/2.13/06-expressions.html#constant-expressions) the following should be a constant value definition:
```scala
scala> final val a = Array(1, 2, 3)
a: Array[Int] = Array(1, 2, 3)
```
But it's not. So either the spec or the implementation needs to be fixed.

@retronym seems to have noticed the same [8 years ago](https://stackoverflow.com/questions/2448373/how-do-i-specify-a-static-array-in-a-scala-2-8-annotation/2449066#2449066).

**Comment by som-snytt** [comment]
https://github.com/scala/bug/issues/9690

**Comment by Jasper-M** [comment]
Oh snap.

**Comment by SethTisue** [comment]
I added a ticket link to the SO question so the trail won’t go cold there for future explorers.
