### ISSUE TITLE
2.12.3 with -Xcheckinit throws UninitializedFieldException when field is in base trait

### ISSUE THREAD

**Issue by purawskis** [scala/bug#10692]
Similar runtime behavior change to issue #10439
Using following test case one gets `UninitializedFieldException` with scala 2.12.3 and 2.12.4 when evaluating `Test()` but `""` with scala 2.12.2.
Because of this it is impossible to use `ActorLogging` with `-Xcheckinit` (see https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/Actor.scala#L312)

```
trait TestBase {
  private var s: String = _
  def apply(): String = {
    if (s == null) {
      s = ""
    }
    s
  }
}

object Test extends TestBase
```

**Comment by hrhino** [comment]
It seems that the only difference between this and the [existent, passing test case](https://github.com/scala/scala/blob/2.13.x/test/files/run/t10439.scala) is that the field is in a trait.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6267
