### ISSUE TITLE
Quasiquote documentation mentions SingletonType when it should mention SingletonTypeTree

### ISSUE THREAD

**Issue by lukaseder** [scala/bug#10707]
On: https://docs.scala-lang.org/overviews/quasiquotes/syntax-summary.html

There's a typo:

![image](https://user-images.githubusercontent.com/734593/35745185-ab7c236c-0842-11e8-865e-b429df41760d.png)

It says `SingletonType` when it should say `SingletonTypeTree`

**Comment by SethTisue** [comment]
would you like to submit a pull request on this over at https://github.com/scala/docs.scala-lang/pulls ...?

**Comment by lukaseder** [comment]
Sure, will do on Monday

Am Freitag, 2. Februar 2018 schrieb Seth Tisue :

**Comment by lukaseder** [comment]
Done: https://github.com/scala/docs.scala-lang/pull/1015
