### ISSUE TITLE
let's deprecate view bounds by default (not just under -Xfuture)

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#10719]
https://github.com/scala/scala/pull/2909 deprecated view bounds under `-Xfuture`, but nobody ever came back and removed the `if (settings.future)` check in `Parsers.scala`.  as far as I know, that was just an oversight

there is a question of whether this change should target 2.12 or 2.13. I suggest we target 2.12.5 for the deprecation, and then actually remove it from the language in 2.13.

**Comment by SethTisue** [comment]
someone want to tackle this...?

**Comment by SethTisue** [comment]
anyone interested in tackling this might also like to tackle the slightly broader https://github.com/scala/scala-dev/issues/471 and other pieces of https://github.com/scala/scala-dev/issues/430

**Comment by som-snytt** [comment]
If no one has created a local branch yet, I'll take a crack at it. I need a good first issue of the night. Some folks are already a few issues in, so I'm just catching up. I'm looking forward to never mixing up view bounds and views as in implicits broadly construed.

**Comment by eed3si9n** [comment]
I didn't see a PR yet on this, so I took it.

**Comment by SethTisue** [comment]
> I suggest we target 2.12.5 for the deprecation, and then actually remove it from the language in 2.13.

we went with a slower timetable: deprecated in 2.13, slated for removal in 2.14.
