### ISSUE TITLE
Spec: clicking on changelog doesn't work

### ISSUE THREAD

**Issue by Blaisorblade** [scala/bug#10728]
Sorry to say, but go to https://www.scala-lang.org/files/archive/spec/2.12/, try clicking on changelog, it doesn't work, even though there is a link to Changelog (at least in Chrome). Workaround: click on some other chapter and then click changelog.

Probably relevant: right clicking on "Changelog" and clicking inspect brings me to `<h4 id="authors-and-contributors">Authors and Contributors</h4>`, which has an upper margin on `-32` and a `padding-top` of `32`; inspector tools reveal most of changelog is covered by the padding, and the ~one pixel of the "Changelog" link not covered by padding does work as a link.

**Comment by SethTisue** [comment]
PR https://github.com/scala/scala/pull/6337

**Comment by SethTisue** [comment]
GitHub got overly excited auto-closing this ticket because of Jorge's commit, but scala/scala#6337 is in fact merged now.
