### ISSUE TITLE
Make scala-library et all include Automatic-Module-Names

### ISSUE THREAD

**Issue by ktoso** [scala/bug#10734]
The `Automatic-Module-Name` http://openjdk.java.net/projects/jigsaw/spec/issues/#AutomaticModuleNames allows an artifact (JAR), to include this property in its MANIFEST.MF in order to inform the Java 9 module system of it's "module name", even though the jar is NOT a module yet (does not have module-info) it can be seen by the module system as-if-it-was.

I strongly recommend picking the module name explicitly, and not deriving it simply from filename.
Example names would be `scala.library` etc.

Here's a snippet from Akka how we do it, which should be easy to adopt in the Scala build:

Helper: 

```scala
package akka

import sbt.{Def, _}
import sbt.Keys._

/**
 * Helper to set Automatic-Module-Name in projects.
 *
 * !! DO NOT BE TEMPTED INTO AUTOMATICALLY DERIVING THE NAMES FROM PROJECT NAMES !!
 *
 * The names carry a lot of implications and DO NOT have to always align 1:1 with the group ids or package names,
 * though there should be of course a strong relationship between them.
 */
object AutomaticModuleName  {
  private val AutomaticModuleName = "Automatic-Module-Name"

  def settings(name: String): Seq[Def.Setting[Task[Seq[PackageOption]]]] = Seq(
    packageOptions in (Compile, packageBin) += Package.ManifestAttributes(AutomaticModuleName → name)
  )
}
```

Usage:

```
lazy val persistence = akkaModule("akka-persistence")
   ...
  .settings(AutomaticModuleName.settings("akka.persistence"))
```

With the stdlib having such stable names, even before "becoming modules" this allows user of Scala and other libraries to progress towards becoming JDK9 modules already.

**Comment by ktoso** [comment]
I can also propose a PR if you'd prefer that, let me know

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6395
