### ISSUE TITLE
Enumeration is not thread-safe

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#10747]
Various aspects of `Enumeration` are not thread-safe (as of [this commit](https://github.com/scala/scala/blob/90ffe626ecd7b888794740f4b4b143d4728d8232/src/library/scala/Enumeration.scala)):

1. `Enumeration.values` does not use the double-check idiom, and thus may be initialized multiple times. Though the results of the initializations should be equivalent, they may be different `ValueSet`s.
  It is possible that the method is intended to behave like `String.hashCode()`, in that multiple initialization is acceptable; if so, this is not an issue.
2. Access to `vsetDefined` is not properly synchronized, allowing a `Value` to be left out of `vset`, as in the following sequence:
   1. [thread 1] `vset` is built and assigned ([here](https://github.com/scala/scala/blob/90ffe626ecd7b888794740f4b4b143d4728d8232/src/library/scala/Enumeration.scala#L108))
   2. [thread 2] `vsetDefined` is set to `false` in `Val`'s constructor ([here](https://github.com/scala/scala/blob/90ffe626ecd7b888794740f4b4b143d4728d8232/src/library/scala/Enumeration.scala#L239))
   3. [thread 1] `vsetDefined` is set back to `true` in the body of `values` ([here](https://github.com/scala/scala/blob/90ffe626ecd7b888794740f4b4b143d4728d8232/src/library/scala/Enumeration.scala#L109)), without adding the new `Value` to `vset`
3. The IDs and names of `Enumeration` values are stored in `mutable.Map`s which are not thread-safe. Consequently, if `Value`s are added to an `Enumeration` after construction, it is (theoretically) possible to:
   1. view the `Enumeration` in an inconsistent state (e.g. only be able to access some of the `Value`s added, not necessarily consistent with the order they were added)
   2. create multiple values with the same ID, without failing the assertion in `Val`'s constructor; which `Value` actually ends up in the `Map` is non-deterministic
   3. other things as well?

**Comment by NthPortal** [comment]
It's also not obvious to me why it isn't just a (`@volatile`) `lazy val`, since Scala has language-level support for lazy initialization.

**Comment by NthPortal** [comment]
Updated description to cover more general thread-safety problems with `Enumeration`

**Comment by NthPortal** [comment]
I'm not really sure what to do about this. Problems 1 and 2 are easy to fix (in fact, I have already written the code), but problem 3 is quite difficult to fix. I can't think of a way to prevent adding values to the `Enumeration` after construction (perhaps that's even a valid use case? I don't know). At minimum, we could document that adding values to an `Enumeration` after construction is not thread-safe, but that doesn't feel like enough.

**Comment by SethTisue** [comment]
you've looked into this more closely than I have, but my general feeling about `Enumeration` is that it's fine to just document limitations that aren't easily fixed. I don't think `Enumeration` is in very wide use (not by experts anyway; lots of resources caution against it), and won't be needed anymore in Dotty which has very appealing seeming `enum` support (http://dotty.epfl.ch/blog/2018/03/05/seventh-dotty-milestone-release.html#enum-simplification-4003)

**Comment by SethTisue** [comment]
P.S. I'm surprised to even learn that it's possible to add more values later. it seems to go against the whole concept of an enumeration

**Comment by NthPortal** [comment]
You and me both.

The problem is, it's entirely implemented in the library, without help from the compiler (AFAICT). Values are added by calling one of the `Value` methods, during the object's construction. And because the parent constructor gets called first, there's no way to set a flag to prevent `Value` from being invoked after construction.

**Comment by som-snytt** [comment]
The normal idiom, `object X extends Enumeration`, is thread-safe by virtue of construction during class loading.

**Comment by som-snytt** [comment]
I was going to say there should be a test to demonstrate what is supposed to be fixed. Maybe I made that comment on a different issue with a race condition.

I'm not sure this class is worth fixing. I think it's OK to document that it has one well-defined use case and you exceed that use case at your peril.

The error with `values` is that the flag `vsetDefined` is volatile but `vset` is not. A thread can construct vset and publish the fact but other threads don't see the vset. OK, that's what you're fixing.

I'm still not sure this class is worth fixing, but this improvement LGTM.

**Comment by NthPortal** [comment]
> I was going to say there should be a test to demonstrate what is supposed to be fixed.

I would love to do that, if I knew how xD

One of the issues with `values` is that it *may* return two different but equivalent instances (assuming you don't add values after construction). I don't think this is a *huge* problem, but given that the fix overlaps with fixing other problems caused by adding values after construction, I thought I might as well.

**Comment by NthPortal** [comment]
@som-snytt rereading your comment, I don't believe you're correct.

`write(vset, ValueSet.newBuilder ++= vmap.values).result())` happens before `write(vsetDefined, true)` AND
`write(vsetDefined, true)` happens before `read(vsetDefined): true` AND
`read(vsetDefined): true` happens before `read(vset): ?`

Thus, a second thread sees the publication of `vset`, even without `vset` being volatile, due to `vsetDefined` being volatile.

The issue lies with the lack of the double-check idiom, the use of which prevents `read(vsetDefined): false` from happening after `write(vset, ValueSet.newBuilder ++= vmap.values).result())` but before `write(vsetDefined, true)`.

**Comment by SethTisue** [comment]
to make a long story short for anyone interested, this is now just a documentation issue. we can document the thread-unsafely and leave it at that

there is some further discussion on https://github.com/scala/scala/pull/6471 which was closed with being merged
