### ISSUE TITLE
UNIX bin scripts don't work for paths with spaces, again

### ISSUE THREAD

**Issue by argv-minus-one** [scala/bug#10756]
Scala version: 2.12.4
Environment: Debian sid on Linux

In the launcher scripts (`scala`, `scalac`, etc), the `findScalaHome` function doesn't completely quote the path to the script. As a result, if the script is in (or is symlinked from) a path with spaces in it, it'll fail:

	$ scala -version
	/home/x/Shell Commands/scala: line 16: cd: too many arguments
	Error: Could not find or load main class scala.tools.nsc.MainGenericRunner

The problem is indeed on line 16 of the scripts, which reads:

    local dir="$( cd -P $(dirname "$source") && cd -P $(dirname "$linked") && pwd )"

The `$(dirname …)`s need to be quoted, as in:

    local dir="$( cd -P "$(dirname "$source")" && cd -P "$(dirname "$linked")" && pwd )"

**Comment by som-snytt** [comment]
I wonder when scala center will have a full-time hire just to fix shell quoting in the scripts.

It would be great if they hired Paul Phillips just for scripting and to come up with a better name for `import PartialFunction.{cond => when}`. Because I always think `condiment`.

Actually they should team up Paul and Li Haoyi. That would be a usability powerhouse, not to mention the great project names they'd come up with.

```
$ PATH="ugly path"/bin:$PATH scalac -version
Scala compiler version 2.13.0-M3 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.
$ "ugly path/bin/scalac" -version
Scala compiler version 2.13.0-M3 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.
$ cd "ugly path2/bin"
$ pwd
/Users/andrew/ugly path2/bin
$ ls -l sc
lrwxr-xr-x  1 andrew  staff  6 Mar  1 21:24 sc -> scalac
$ ./sc -version
Scala compiler version 2.13.0-M3 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.
```

I hesitate to say it works for me on macos. It also works with extra quotes. I'll try again on different machines later.

Probably propensive will say he's on the script quoting committee and has a macro `path["/Users/andrew/ugly path"]` that handles the issue at compile time. It will be called `spaceless`.

**Comment by hrhino** [comment]
https://github.com/scala/scala/pull/6387

**Comment by df3n5** [comment]
I have made a Pull Request for this and tested it locally. It there a way to write automated tests for this part of the code?

**Comment by som-snytt** [comment]
Following up on my previous comment, repro:
```
$ tar xfz ../scala-2.12.4.tgz 
$ mv scala-2.12.4 "my scala"
$ ln -s "my scala"/bin/scala sc
$ ./sc
./sc: line 16: cd: my: No such file or directory
Error: Could not find or load main class scala.tools.nsc.MainGenericRunner
$ vi ./sc
$ ./sc
./sc: line 19: cd: ./my scala/bin
/home/amarki/tmp/my scala/bin/..: No such file or directory
Error: Could not find or load main class scala.tools.nsc.MainGenericRunner
```

The edit worked for me on my MacOS but not on Ubuntu. Maybe there's a relevant difference in my bash config, but I can't chase that at the moment.

**Comment by df3n5** [comment]
Apologies, this was a typo on my part. My updated fix for this is working now on Fedora Linux and MacOS, you can test it like so (starting with a fresh checkout of scala git repo):

```
#!/bin/bash
set -e
mkdir -p build
rm -vrf build/pack
sbt dist/mkPack

pushd build/pack
cp -rvf bin/ bad\ bin
mkdir -v bad\ linked\ bin
ln -sv `pwd`/bad\ bin/scala `pwd`/bad\ linked\ bin/scala\ link
bad\ linked\ bin/scala\ link -e 'val e = 123; println(s"e is : ${e}")'
popd
```

**Comment by SethTisue** [comment]
> It there a way to write automated tests for this part of the code?

it's possible to test this kind of thing in https://github.com/scala/scala-dist-smoketest . I don't think it's possible to test in scala/scala.

thank you @argv-minus-one for the report and @df3n5 for the fix!
