### ISSUE TITLE
Nonsensical floating-point Ranges are allowed

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#10759]
Most `Range`s involving `NaN`, `PositiveInfinity` and `NegativeInfinity` are allowed, despite being nonsensical.

- `Range`s where either bound or the step is `NaN` are empty
- `Range`s where one bound is infinite and the other is finite:
   - are empty if the step is away from the end bound
   - throw a cryptic exception if the step is toward the end bound (see the end for details)
- `Range`s where both bounds are finite, but the step is infinite:
   - are empty if the step is away from the end bound
   - throw a cryptic exception if the step is toward the end bound (see the end for details)
- `Range`s from one infinity to the other:
   - are empty if the step is away from the end bound
   - throw a cryptic exception if the step is toward the end bound (see the end for details)
- `Range`s where both bounds are `PositiveInfinity` or `NegativeInfinity` have a single element (`PositiveInfinity` or `NegativeInfinity` respectively), regardless of step

This probably shouldn't be allowed, as it almost certainly isn't what you want to do. Additionally, where it already throws an exception, it should throw a more helpful one.

----------------

The following exception is thrown when attempting to create a variety of ranges involving infinity:

```
scala> PositiveInfinity to 2.0 by -1.0
java.lang.NumberFormatException
  at java.math.BigDecimal.<init>(BigDecimal.java:494)
  at java.math.BigDecimal.<init>(BigDecimal.java:824)
  at scala.math.BigDecimal$.decimal(BigDecimal.scala:51)
  at scala.math.BigDecimal$.apply(BigDecimal.scala:248)
```

----------------

Scala 2.12.4

**Comment by NthPortal** [comment]
I'm going to wait until collection-strawman is merged into scala to work on this, as the code is split across the two repositories

- `Range` and `NumericRange` are in strawman
- `FractionalProxy`, `RichFloat` and `RichDouble` are in scala

**Comment by Ichoran** [comment]
Is it possible to drop numeric ranges that pretend to be for `Float` and `Double`?  These are just bad news due to numeric imprecision.  If you say something like `0.1 to 0.7 by (0.1 + 0.2)` you would _think_ you would have three steps, but you either won't, or you will but other code will be randomly and incomprehensibly inaccurate (because you rounded things enough to make the above work).

Normally I don't like breaking changes, but in the case where there is no way to do the right thing except by not actually using the type that is stated, I think the better thing to do is remove the feature.

**Comment by SethTisue** [comment]
@Ichoran see https://github.com/scala/collection-strawman/pull/489 — I think it's orthogonal to this ticket, this isn't the place to discuss it

**Comment by Ichoran** [comment]
@SethTisue - It's not orthogonal because there will be no behavior to fix via this PR if my recommendation is taken.  But I'm happy to discuss it over there instead of here.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6468
