### ISSUE TITLE
repl colon command completion can be surprising

### ISSUE THREAD

**Issue by hrhino** [scala/bug#10757]
Can't really give a repl transcript, but imagine that when I type `<TAB>` I've pushed the same-named key.

```scala
scala> :sett<TAB>
/* gives you...  */
scala> :settings
/* with no trailing space, so type `-Xprint:pars` there and you'll get an error */

scala> :settings -Ydeb<TAB>
/* gives you... */
scala> :settings -Ydebug // yay!

scala> :set -Ydeb<TAB>
/* gives you... */
scala> :set -Ysettings
```

**Comment by som-snytt** [comment]
You're supposed to read the warnings on the little instruction sheet which comes in the package which you're not supposed to ever throw away. Then you're supposed to do it like on the second line.

**Comment by som-snytt** [comment]
It's surprising that it works at all.

I increased the featureful goodness of command completion only. I think I understand how it's supposed to work.

**Comment by SethTisue** [comment]
PR: scala/scala#6373
