### ISSUE TITLE
-Ywarn-value-discard does not warn on this.type

### ISSUE THREAD

**Issue by exoego** [scala/bug#10761]
* scalac version 2.12.4

I expected the following code to be warned regarding returned value discard.

```scala
import scala.collection.mutable

class Bar {
  def + (other: Bar): this.type = this
}

class Foo {
  private val storage: mutable.Map[String, String] = mutable.Map()

  def put(key: String, value: String): Unit = storage += key -> value

  def useBar(): Unit = {
    val a = new Bar
    val b = new Bar
    a + b
  }
}
```

But I got no warnings.

It seems that scalac does not warn on discarded non-Unit value, if a return type of function is `this.type`.

**Comment by exoego** [comment]
@som-snytt 
Thank you for explaining.  That makes sense.

As a scala user, I think it would be helpful if such reason is explained in help messages in `scalac -Y`.
So I open a pull request to update description of the option.
https://github.com/scala/scala/pull/6394

**Comment by SethTisue** [comment]
let's document this as part of https://github.com/scala/docs.scala-lang/issues/1058
