### ISSUE TITLE
CaseClass2Map Problem

### ISSUE THREAD

**Issue by ababup1192** [scala/bug#10777]
# Overview
I have discovered this problem when trying to get the key-value pairs ```Map [String, Any]``` from *case class* with “lazy val”.
It got the key ```lang.Class#getFields``` and values ```Product#productIterator```, in result zipped anf mapped as ```Tuple#toMap```.
The reason behind is that when lazy val fields exist, they are recognized as Field types, but in Java they are effectively translated as methods, so we can not get the values properly. 
In addition, it worked properly in 2.11.x. 
But in 2.12.x, the case class contains the lazy val field so that the order of argements in ```java.lang.Class # getFields``` is different from the order of the argements of the case class that result in the arguments shifted and did not get the proper result. 
```scala
object CaseClass2MapSimulator extends CaseClass2Map with App
case class Foo(x: Int, bar: Bar) {
  lazy val z = 2
}
case class Bar(y: Int)
trait CaseClass2Map {
  private def convert(product: Product): Map[String, Any] = {
    println(product.getClass.getDeclaredFields.map(_.getName).toList)
    // case 2.11.12 => List(x, bar, z, bitmap$0)
    // case 2.12.4  => List(z, x, bar, bitmap$0)
    product.getClass.getDeclaredFields
      .map(_.getName)
      .zip(product.productIterator.toList).toMap
  }
  println(convert(Foo(1, Bar(3))))
  // case 2.11.12 => Map(x -> 1, bar -> Bar(3))
  // case 2.12.4  => Map(z -> 1, x -> Bar(3))
}
```
# Solution
We solved this problem by extracting all methods with ```java.lang.Class # getMethods```, filtering extra methods, invoking and retrieving values to form pairs.
```scala
object Product2Map {
  private[this] val excludeMethodNames = Seq(
    "canEqual",
    "unapply",
    "hashCode",
    "productElement",
    "productIterator",
    "productArity",
    "productPrefix",
    "wait",
    "toString",
    "getClass",
    "notify",
    "notifyAll"
  )
  private def extractFieldMethods(clazz: Class[_]): Array[Method] = {
    clazz.getMethods().filterNot { m => excludeMethodNames.contains(m.getName) }
      .filterNot { m => m.getName.indexOf("$") >= 0 }
      .filterNot { m => m.getReturnType.toString == "void" } // we don't want side effects in rendering
      .filterNot { m => (m.getModifiers & Modifier.PUBLIC) == 0 }
      .filter { m => m.getGenericParameterTypes.length == 0 }
  }
  def convert(product: Product): Map[String, Any] = extractFieldMethods(product.getClass)
    .map(m => (m.getName -> m.invoke(product))).toMap
}
```
# Questions
- Is it intended to change the order arguments in 2.12.x? or it is just a mistake?
- Is there any simple solutions in Scala? For example using Scala’s reflection (Universe, Mirror etc.) rather than Java?

**Comment by NthPortal** [comment]
To quote [the javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getFields--):

> The elements in the returned array are not sorted and are not in any particular order.

Whether or not the compiler changed the field declaration order, you should not be relying on `getDeclaredFields` to give them to you in that order anyway. You're lucky it worked up until now.

**Comment by ababup1192** [comment]
@NthPortal 
I understood in this case. May I present the correct solution?

**Comment by SethTisue** [comment]
* `getFields` itself does not guarantee ordering, as @NthPortal points out
* but also, this stuff is extremely liable to change between Scala major versions, and is even subject to change (though it's less likely) between Scala minor versions

**Comment by alexknvl** [comment]
As a workaround consider using `shapeless`:
https://github.com/milessabin/shapeless
https://github.com/milessabin/shapeless/blob/master/examples/src/main/scala/shapeless/examples/labelledgeneric.scala

The only limitation is that types have to be known at compile-time.
