### ISSUE TITLE
Eta-expansion misses synthetic apply in an explicit object

### ISSUE THREAD

**Issue by gkossakowski** [scala/bug#10780]
This compiles:

```scala
case class Foo(i: Int)
Option(1).map(Foo)
```

and this compiles:

```scala
case class Foo(i: Int)
object Foo
Option(1).map(Foo.apply)
```

but this doesn't:

```scala
case class Foo(i: Int)
object Foo
Option(1).map(Foo)
```

It looks like eta-expansion fails to pick up a synthetic apply in an object that itself is not synthetic. Perhaps some subtle typechecking ordering issue?
Tested on Scala 2.12.4

cc @travisbrown

**Comment by Jasper-M** [comment]
Isn't this https://github.com/scala/bug/issues/3664 ?

**Comment by gkossakowski** [comment]
I think it's different but maybe related. The second example shows that `apply` method is there but it's not picked up by eta-expansion.

**Comment by Jasper-M** [comment]
It shows that `apply` is there but object `Foo` doesn't extend `Int => Foo`.

**Comment by lrytz** [comment]
Eta expansion works on methods, it doesn't add an `apply` to values. This is expected.
```
scala> object T { def apply(x: Int) = 0 }
defined object T

scala> def f: Int => Int = T
<console>:12: error: type mismatch;
 found   : T.type
 required: Int => Int
       def f: Int => Int = T
                           ^

scala> def f: Int => Int = T _
<console>:12: error: _ must follow method; cannot follow T.type
       def f: Int => Int = T _
                           ^

scala> def f: Int => Int = T.apply
f: Int => Int
```

**Comment by gkossakowski** [comment]
Thanks for the response.
What's the mechanism behind the first example compiling?

**Comment by SethTisue** [comment]
Synthetic case class companion objects extend `FunctionN`

**Comment by gkossakowski** [comment]
Ah, fair. Thanks!
