### ISSUE TITLE
Infinite loop in scala compiler after updating pom to use 2.12.5

### ISSUE THREAD

**Issue by Brassrat** [scala/bug#10799]
I am running MAC OS Sierra - 10.12.8
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home
JAVA_OPTS='-Xms512m -Xmx4096m'
SCALA_HOME=/usr/local/bin/scala
SCALA_VERSION=2.12.5
type -p scala => /usr/local/Cellar/scala/2.12.5/libexec/bin/scala

If i update my maven pom to use 2.12.5 libraries the compiler goes into an infinite loop ... the last couple of iterations are shown below.
If i switch back to 2.12.4 everything compiles and works. 
Not sure which of the 10 files is causing the problem
mvn -X doesn't provide much additional information

Intellij does not have a problem, itself 

 --- scala-maven-plugin:3.3.2:testCompile (scala-test-compile)
proj/src/test/scala:-1: info: compiling
[INFO] Compiling 10 source files to proj/target/test-classes at 1521726217998
[ERROR] error: java.lang.StackOverflowError
[INFO] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1651)
[INFO] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:107)
[INFO] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1366)
[INFO] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1357)
[INFO] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
[INFO] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
[INFO] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[INFO] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1808)
[INFO] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:107)
[INFO] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1368)
[INFO] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1357)
[INFO] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
[INFO] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
[INFO] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
[INFO] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:1808)
[INFO] 	at scala.tools.nsc.typechecker.RefChecks$RefCheckTransformer.transform(RefChecks.scala:107)
[INFO] 	at scala.reflect.internal.Trees.itransform(Trees.scala:1366)
[INFO] 	at scala.reflect.internal.Trees.itransform$(Trees.scala:1357)
[INFO] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
[INFO] 	at scala.reflect.internal.SymbolTable.itransform(SymbolTable.scala:18)
[INFO] 	at scala.reflect.api.Trees$Transformer.transform(Trees.scala:2555)
...

**Comment by hrhino** [comment]
Can you share the code that causes this? Preferably minimized to a small file that can be used to reproduce it. ([Here](https://gcc.gnu.org/bugs/minimize.html) is some advice on how to do that.) As it is this doesn't give any idea as to why this may be happening.

**Comment by hrhino** [comment]
Thanks! but... I can compile that in the 2.12.5 repl.

```scala
Welcome to Scala 2.12.5 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_161).
Type in expressions for evaluation. Or try :help.

scala> :pa
// Entering paste mode (ctrl-D to finish)

def e() = {
val q = "|" // """
val xyzzy = s"$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q,$q"
}

// Exiting paste mode, now interpreting.

e: ()Unit
```

It's possible that you need to increase your stack size (using [`-Xss`](https://stackoverflow.com/questions/4967885/jvm-option-xss-what-does-it-do-exactly)). It's also possible that you have a compiler option which matters (visible by `show scalacOptions` in sbt).

**Comment by Brassrat** [comment]
I am not using sbt.
I am using maven and/or idea.

I have not specified any scala options – using out-of-the-box maven scala plugin.
a stack size issue would result in what appears to be an infinite loop if the required recursion depth is really large (or each frame is really large) and the compiler runs out of stack before it has fully recursed. I guess this could be happening. 

i was compiling the example within the build of my application - so obviously the state of the compiler, etc. would come into play. I can't send you the entire application and don't really have the time to try to figure out what is causing this behavior if i have to start pulling it apart.

I worked around the issue by breaking the single string into multiple strings with + in-between.
(e.g., s”$q$q”  => s”$q” + s”$q”). So the resulting string itself is not an issue, size-wise.

 **Note also, I should put in a bug report on the following: 
  s”\”xyzzy\”:\”${vbl}\””
does not compile for me (either 2.12.4 or 2.12.5)**
