### ISSUE TITLE
As java10 has been released,  does scala support java10 now?

### ISSUE THREAD

**Issue by hefeiyun** [scala/bug#10798]
As java10 has been released,  does scala support java10 now?   THANKS

**Comment by martijnhoekstra** [comment]
scala/bug is not intended for questions, but for bug reports. For questions like these, consider posting on https://users.scala-lang.org/ instead.

**Comment by adriaanm** [comment]
In short, we only officially support LTS releases of Java, with best effort support for the intermediate 6-month ones. We'll be updating this page with more info/more detailed policy: http://docs.scala-lang.org/overviews/jdk-compatibility/overview.html
