### ISSUE TITLE
Easier for Language Server users to report red squigglies

### ISSUE THREAD

**Issue by fommil** [scala/bug#10797]
One of the absolutely most infuriating parts of writing ensime is receiving reports like "it doesn't work" or "it is all red" but users don't post any code / projects... just the exception dump. I already know what the exception looks like, thanks.

This frustration led me and @rorygraves to create https://github.com/ensime/pcplod to make it easier for macro and plugin authors to check that their code won't break the PC, but it can also be used by any developer on any project to reproduce red squigglies *in their project*.

The uptake has been zero.

It would be good if the entire workflow for reporting bugs was revisited... with the recent interest in LSPs you can be guaranteed that the number of users of the scalac interactive compiler is going to increase dramatically and there is no infrastructure or docs that seem to be suitable for users, despite our best efforts.

(As a slight tangent, I've noticed that most PC bugs tend to manifest as misaligned semantic highlighting, pcplod does not allow asserting on this but it would be a simple addition)

An acceptance criteria is that @tpolecat can finally show us some code that "doesn't work" for him.

**Comment by tpolecat** [comment]
You have stated with great pride that ENSIME is just for you and you don't care about users, so you should be overjoyed that I choose not to use it. Leave me alone.
