### ISSUE TITLE
Allow compiler plugins after namer but before typer

### ISSUE THREAD

**Issue by fommil** [scala/bug#10794]
Many compiler plugins would benefit from naming, but do not need typing, e.g. #10793 and https://gitlab.com/fommil/scalaz-deriving/blob/master/deriving-plugin/src/main/scala/scalaz/plugins/deriving/AnnotationPlugin.scala

Both of the above examples are part of my recommendations to the LSP-WG. If this ticket cannot be resolved, various nasty upstream workarounds will be necessary.

**Comment by hrhino** [comment]
So my understanding of this is that a full phase between them doesn't make sense: the namer phase's traversal only goes as far as top-level declarations, and then the typer phase goes through the trees, forcing infos which cause more naming to allow more typing, and so on. You don't even get annotations on top-level symbols until their info is completed IIRC.

There are `AnalyzerPlugin`s which allow for some of this. (This is how paradise annotation macros work: you can sneak an expansion in the window between the `ClassDef` being inspected and its body being inspected.) There's some scaladoc for the API, but you need to be familiar/familiarize yourself with how typechecking works inside scalac to really understand what can/can't be done. It could certainly be documented better, but I don't know how right now.

**Comment by xeno-by** [comment]
`AnalyzerPlugin` is only part of the story in paradise. There is also something called `MacroPlugin`, which is also essential: https://github.com/scalamacros/paradise/blob/2.12.5/plugin/src/main/scala/org/scalamacros/paradise/typechecker/AnalyzerPlugins.scala#L31-L56.

**Comment by hrhino** [comment]
Right, that too. Thanks. `MacroPlugin` is a bit less likely to be useful in these situations since all of those operations are going to get "stolen" by paradise, and make a hypothetical other plugin incompatible. `pluginsEnterStats` is the only one IIRC which can be implemented by multiple `MacroPlugin`s.
