### ISSUE TITLE
No unreachable code warning in try-catch.

### ISSUE THREAD

**Issue by alexknvl** [scala/bug#10806]
Found by @hepin1989.

```scala
try { 1 } catch { 
  case _: Exception ⇒ println("Something went wrong")
  case ex: IllegalArgumentException ⇒ println(ex.getMessage)
}
```
Doesn't print a warning.

```scala
(new IllegalArgumentException()) match { 
  case _: Exception ⇒ println("Something went wrong")
  case ex: IllegalArgumentException ⇒ println(ex.getMessage)
}
```
Does.

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/37879976-d3904150-30b3-11e8-8476-761389dd3950.png)

**Comment by hepin1989** [comment]
![image](https://user-images.githubusercontent.com/501740/37880011-787394f6-30b4-11e8-8ea0-d7333d8bf01a.png)

**Comment by hepin1989** [comment]
https://youtrack.jetbrains.com/issue/SCL-13551

**Comment by SethTisue** [comment]
@hepin1989 I appreciate your helpfulness here, but a small bit of advice: with code, it's always better to use text instead of screenshots (unless the issue you're demonstrating is actually a GUI issue). screenshots of code are less helpful than they could be, for two reasons, 1) they aren't searchable, 2) they aren't copy-and-pastable

**Comment by SethTisue** [comment]
interesting bug — why should `catch` be different from an ordinary pattern match? puzzling.

**Comment by SethTisue** [comment]
(I'm not quiiiiiite optimistic enough to slap "good first issue" on it...)

**Comment by hepin1989** [comment]
@SethTisue There are code samples up there, so I took a screenshot of its current behavior.

**Comment by som-snytt** [comment]
@hepin1989 it's not a big deal in this case. :) Just makes it easier for others to cut/paste and try it. I'll take a look at this issue. Those checks look arbitrarily applied to me, so I'd like to understand the method in the madness. I was going to look earlier, but my daughter is going to "science camp" tomorrow for a few days. She'd do better with three days in the woods reading poetry, which is more my line. Now she's packed and playing "Another day of sun" on flute.

**Comment by som-snytt** [comment]
[Workaround](https://github.com/scala/scala/pull/6483/files#diff-c489f26a7c2477de426dd9541ce8f97dR9) is to add something besides a trivial or type test. Maybe using `NonFatal` would be an example of a useful workaround.
