### ISSUE TITLE
Don't suggest that users `import scala.concurrent.ExecutionContext.Implicits.global`

### ISSUE THREAD

**Issue by DavidGregory084** [scala/bug#10808]
I'd like to suggest that references to the global `ExecutionContext` are removed from the `@implicitNotFound` annotation for `ExecutionContext`.

I regularly discover imports for the global execution context in inexperienced devs' code, as the compiler tells them that they can import this to make their code compile.

It seems to me that suggesting something that silently alters concurrent programs' behaviour causes quite a lot of mischief compared to the relatively small convenience of getting your code to compile without really understanding what is happening. :smile:

**Comment by viktorklang** [comment]
One *possible* solution would be to amend the `implicitNotFound` not to mention the global EC, and then @deprecate `ExecutionContext.Implicits`.

**Comment by DavidGregory084** [comment]
I have just addressed the wording for now, but if there is general support for the idea of deprecating `ExecutionContext.Implicits` I would be happy to do that as well

**Comment by Jasper-M** [comment]
> @deprecate ExecutionContext.Implicits

Wouldn't that be kind of overkill? How would you suggest everyone using `Implicits.global` to rewrite their code?

**Comment by Ichoran** [comment]
This clobbers the discoverability of getting a running Future.  This is a big step backwards in usability.

**Comment by DavidGregory084** [comment]
> Error messages should do as much as possible to help a programmer produce working code. This change does exactly the opposite: makes it even harder to produce working code. I appreciate that there are many cases where you need to care intimately about the execution context you are using, but it doesn't follow that the error message has to be unhelpful about where to find execution contexts and/or which one(s) might be a good first try.
> This clobbers the discoverability of getting a running Future. This is a big step backwards in usability.

How about if we change the error message to suggest adding an `implicit val ec: ExecutionContext = ExecutionContext.global? It would be helpful in the sense that at least it's more explicit than an import.

If a developer imports this they magically shift every computation in any call-site downstream of the file that has the import onto a different thread pool.

For web development at least, this is the wrong thing to do nearly all of the time, but the fact that the suggestion comes from the compiler lends it a false legitimacy.

**Comment by DavidGregory084** [comment]
Alternatively, we could make the error message more verbose (and helpful), but I wasn't sure if there was typically a limit on how verbose `@implicitNotFound`  messages should be

**Comment by DavidGregory084** [comment]
I think in most cases whichever framework is used will take care of passing along the EC to the parts of the application that the developer has written themselves, and typically the EC is instantiated at the very top level of the application. 

You might want to make sure that your application reuses an existing thread pool if the framework you are using already provides one for your use or you may want to make sure that thread local "stuff" like the slf4j MDC (usually used for for storing request info and similar things) and distributed tracing spans get propagated by a custom EC.

IMO my ideal would be something like:
```
Cannot find an implicit ExecutionContext. You might pass
an (implicit ec: ExecutionContext) parameter to your method.

The ExecutionContext is used to configure how and on which
thread pools Futures will run so the specific ExecutionContext
that is selected is important.

If your application does not define an ExecutionContext elsewhere, 
consider using Scala's global ExecutionContext by defining
the following:

implicit val ec: ExecutionContext = ExecutionContext.global
```

**Comment by SethTisue** [comment]
nicely written.

fwiw, like Rex, I think including the global import is really helpful when you're getting started and/or when you're playing in the REPL. in the REPL, I think I've personally copy-and-pasted from this message 100+ times, easy

**Comment by DavidGregory084** [comment]
Yes, I think you're right, but I think we can land on something that makes things easy for beginners and discourages industrial users from shooting themselves in the foot. :)

**Comment by ritschwumm** [comment]
what about industrial beginners shooting their colleagues in the foot?

**Comment by Ichoran** [comment]
I like the comment!  I'd just shorten the code `implicit val ec = ExecutionContext.global`

**Comment by DavidGregory084** [comment]
:+1: although I tend to add type ascription to implicit definitions out of habit now as I was under the impression they would become mandatory in Dotty

**Comment by sjrd** [comment]
Only for fields. Not for local `val`s.

**Comment by hepin1989** [comment]
Maybe there should have a `detail` and a `concise` once for messages:), which we could switch on and off with compiler option?

**Comment by Jasper-M** [comment]
I really don't see what's so much better about `implicit val ec = ExecutionContext.global` than `import ExecutionContext.Implicits.global`.

**Comment by viktorklang** [comment]
@Jasper-M The benefit is that imports can go top-level while val declarations can't. So there's less risk of something at the top of the file incurring problems in a localized area.

**Comment by viktorklang** [comment]
@Jasper-M It also reduces the API surface area. And I think we should also consider whether `global` should delegate to `FJP.commonPool()` or not.

**Comment by Jasper-M** [comment]
> The benefit is that imports can go top-level while val declarations can't. So there's less risk of something at the top of the file incurring problems in a localized area.

Sure, but I guess people who are inclined to shoot themselves in the foot with a top-level import are also likely to put that implicit val on the class or object level. Which, when following the "best practices" of 1 class or object per file, is as good as top-level.

**Comment by viktorklang** [comment]
@Jasper-M Given the usual number of imports vs members, I'd think the member or local val much easier to spot.

**Comment by DavidGregory084** [comment]
@Jasper-M yeah, as Viktor says my motivation is that I think it's much easier to spot in code review, especially in a new file or if the reviewers aren't used to looking for imports that might change behaviour

**Comment by nafg** [comment]
Can someone motivate this more? What is (necessarily) wrong with using the global EC?

How about a more conservative change: a slight modification to the wording that makes it more clear that the global EC _may_ be what you want, but has XXX downside

**Comment by DavidGregory084** [comment]
@nafg there isn't anything wrong with using the global EC in and of itself, but suggesting to use it in a compilation error is pretty poor as the minute that you add the import it clobbers any existing EC all the way down your callstack, and it's quite hard to spot in a review unless you are looking for it.
So far we have come to the conclusion that we should revise the wording to deemphasise the global EC a bit and we're iterating on the wording on the PR. :)

**Comment by som-snytt** [comment]
This is, in part, a tooling issue. Advice can differ depending on environment. The REPL could automatically supply an EC, for instance. There's currently a hacky difference in the advice how to re-run a compilation with compiler args depending on if you're in the REPL. So messaging can be tool-dependent.

If the compilation environment/IDE tracks importable implicit ECs, it can suggest did you want EC1 or EC2?

I remember my fastest version of partest had one EC for ingesting tests and a second for running them, for example.

Yesterday I wrote a tool at work, I needed to spawn one DB query in a future while the main thread works on another. The so-called global EC is very convenient for my day-to-day. Often my needs are not very sophisticated, as I think Ichoran said.

I'd suggest renaming `global` to its actual purpose as a minimum viable EC, appropriate for the available context. Maybe how macros have `whitebox.Context` and I almost wrote `shitebox`, there could be paths `synchronous.Context`, `platform.Context` scaled to the CPUs, etc.

**Comment by stephennancekivell** [comment]
Maybe you could suggest how to create one newcomers arent completely lost.

```
Cannot find an implicit ExecutionContext. You might pass
an (implicit ec: ExecutionContext) parameter to your method.

...

implicit val context: ExecutionContex = ExecutionContext.fromExecutor(Executors.newFixedThreadPool(3))

or

implicit val ec: ExecutionContext = ExecutionContext.global

```

**Comment by viktorklang** [comment]
@stephennancekivell It's not that simple though—because now you need to explain how lifecycle management should be done for the pool which was just created.

**Comment by martin-g** [comment]
What about adding a link in the error message to a documentation where the user can read more about this topic ?
Some projects do this.

**Comment by viktorklang** [comment]
@martin-g Do you have a link to an example of an @implicitNotFound annotation referring to ScalaDoc?

**Comment by martin-g** [comment]
To ScalaDoc - no. But I believe Play Framework points to their site documentation.

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/6470

**Comment by som-snytt** [comment]
The beginner's issue can be solved with `-Yimports:Something` or similar, instead of making them paste code.
