### ISSUE TITLE
Rename & deprecate `eq` and `ne`

### ISSUE THREAD

**Issue by argv-minus-one** [scala/bug#10809]
As has been discussed before in #3754, the method names `eq` and `ne` (on `AnyRef`) are confusing and misleading. The names suggest that they are some sort of equality comparison, when in fact they test whether two references are to the same object.

Now that Scalafix exists, and a major overhaul of the language is on the way, is it still “not realistic” to rename them?

**Comment by smarter** [comment]
I don't think scalafix should become an excuse to rename everything in the language, this way lies madness.

**Comment by argv-minus-one** [comment]
Why, what else do you think people are going to want renamed?

**Comment by Ichoran** [comment]
Replacing a weird but nominally readable name with a non-obvious symbolic operator sounds like a step backwards to me.  Yes, there's something to learn with `eq` and `ne`, but most of the difficulty comes from needing to understand what reference equality is.

**Comment by argv-minus-one** [comment]
Fair enough. I've removed that part of my initial post.

**Comment by NthPortal** [comment]
> The names suggest that they are some sort of equality comparison, when in fact they test whether two references are to the same object.

That *is* an equality comparison; in fact, it is the *default* equality comparison.

--------

#3754 claims that

> it is not a word, unlike every other non-symbolic method name in Scala

however, this is not the case - see `scala.math.Ordering` and `scala.math.Ordered`.

**Comment by SethTisue** [comment]
@argv-minus-one scala/bug is for bugs, please start discussions like this on https://contributors.scala-lang.org instead

**Comment by som-snytt** [comment]
I'd like a tool so that when I switch back to Java for my day job, I can use `eq` and `==` with Scala semantics.

`scalac -better-javac` should just delegate to `javac` after running some `javafix` rules.
