### ISSUE TITLE
-Xsource:2.11 should disallow trailing commas under Scala 2.12?

### ISSUE THREAD

**Issue by Sciss** [scala/bug#10818]
This

```scala
List(
  1,
  2,
  3,
)
```

is valid in Scala 2.12. If I cross-build with 2.11 as another target, I think I should be able to disallow this using

    scalacOptions += "-Xsource:2.11"

but the above still compiles under Scala 2.12

**Comment by som-snytt** [comment]
This is a `good weird issue` if there were a label for that. I haven't seen that `-source` respects syntax evolution backwardly; usually the effort is to deprecate then disallow. I wonder if a `scalafix` rule could enforce that a syntax change respects all of past, present and future versions.

I was just writing my first sbt plugin to auto-filter `scalacOptions` for the current scala version, and this is an obvious candidate I hadn't considered.

**Comment by SethTisue** [comment]
> I haven't seen that -source respects syntax evolution backwardly

I'm not sure if there's precedent, either. before using `-Xsource:2.11` in a build of my own, I think I'd have to do a careful audit for what else changes as a result

**Comment by SethTisue** [comment]
in general, my impression is that `-Xsource` (and its sisters `-Xfuture` and `-Xexperimental`) are intended for testing, experimentation, and during migration, and not so much as some kind of general cross-building facility. but then actually I don't know why would we would support backwards `-Xsource`, as opposed to forward `-Xsource`, at all

**Comment by som-snytt** [comment]
@SethTisue I think this is settled. https://github.com/scala/bug/issues/8361 except for the backwards part.

Frankly, I can't imagine disallowing trailing comma under any regime. That would only spur tickets to "backport trailing comma."

It's "trailing comma" singular because you only get one.

**Comment by dwijnand** [comment]
I think this should be closed.  We're not going to add 2.11 source support to 2.13.
