### ISSUE TITLE
Scope of @ in pattern

### ISSUE THREAD

**Issue by hvesalai** [scala/bug#10821]
## code

```
case class Foo(i: Int)

def one(f: List[Foo]): Option[Foo] = f match {
  case h @ Foo(1) :: t => Some(h)
  case _ => None
}
```

## problem

Does not compile. Results in compiler error:

```
error: type mismatch;
 found   : immutable.this.$colon$colon[Foo]
 required: Foo
    case h @ Foo(1) :: t => Some(h)
                                 ^
```

## expectation

`h @` would capture `Foo(1)`, not `::`

## notes

This compiles, but the parenthesis are unnecessary noise.

```
def thisCompilesButIsUgly(f: List[Foo]): Option[Foo] = f match {
  case (h @ Foo(1)) :: t => Some(h)
  case _ => None
}
```

Play around with the code at https://scalafiddle.io/sf/mPH6JwH/1

**Comment by Jasper-M** [comment]
Have you reason to assume it's a bug? I suspect (__but have not checked__) this is just the official precedence rules at work.

**Comment by hvesalai** [comment]
Indeed it is not a bug in the compiler, but in the language specification. The relevant rules from the language are :

```
 1  Pattern         ::=  Pattern1 { ‘|’ Pattern1 }
 2  Pattern1        ::=  varid ‘:’ TypePat
 3                    |  ‘_’ ‘:’ TypePat
 4                    |  Pattern2
 5  Pattern2        ::=  varid [‘@’ Pattern3]
 6                    |  Pattern3
 7  Pattern3        ::=  SimplePattern
 8                    |  SimplePattern {id [nl] SimplePattern}
 9  SimplePattern   ::=  ‘_’
10                    |  varid
11                    |  Literal
12                    |  StableId
13                    |  StableId ‘(’ [Patterns] ‘)’
14                    |  StableId ‘(’ [Patterns ‘,’] [varid ‘@’] ‘_’ ‘*’ ‘)’
15                    |  ‘(’ [Patterns] ‘)’
16                    |  XmlPattern
17  Patterns        ::=  Pattern {‘,’ Patterns}
```

Which means Pattern(a @  b :: c) is generated using the following steps:

```
Pattern(a @ b :: c)
1: Pattern1(a @ b :: c)
4: Pattern2(a @ b :: c)
5: varid(a) @ Pattern3(b :: c)
8: varid(a) @ SimplePattern(b) id(::) SimplePattern(c)
10: varid(a) @ varid(b) id(::) SimplePattern(c)
10: varid(a) @ varid(b) id(::) varid(c)
```

(and hence parsed in the reverse order).

So then I need to propose a change to the language?

**Comment by Jasper-M** [comment]
Probably, but I'm not sure if such a proposal would stand a chance. Unless I'm missing something this is just a matter of preference and if you change the rules existing code will probably break. But by all means try if it's important to you.

**Comment by som-snytt** [comment]
You propose `@ SimplePattern` instead of `@ Pattern3`?

It's a little complicating because you don't know immediately if an id is infix or a varid.

`n match { case x @ Bisto Basco dookie @ Dizzy => }`

`case ::(h @ X, t) =>` is a workaround.

It's tricky because we expect operator precedence even though `@` is not an operator, the way we expect `match` to work as an infix op.

**Comment by hvesalai** [comment]
@som-snytt In your example I would have expected `x @ Bistro` to be a unit, not `x @ (Bistro Basco dookie @ Dizzy)`

**Comment by som-snytt** [comment]
I asked on gitter if Dotty would accept this ticket there.

The codebase tends to use extra parens for `case x @ (P :: rest)`.

Example where required parens are missing: https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/transform/CleanUp.scala#L344

**Comment by som-snytt** [comment]
Sadly, closing as "not planned".
