### ISSUE TITLE
Regex - checking if a string matches is cumbersome

### ISSUE THREAD

**Issue by dhoepelman** [scala/bug#10827]
Checking if a string matches a regex is a common operation, but not directly available on Scala's `Regex`.

Current ways are fairly cumbersome:
```
val r = """\d+""".r

// Java API
r.pattern.matcher("123").matches()

// Extractor
"123" match {
  case r() => true
  case _ => false
}
```

A `matches` method feels natural and elegant:
```
r.matches("123")

// or infix
r matches "123"
```

[I've submitted a PR for this](https://github.com/scala/scala/pull/6521)

**Comment by som-snytt** [comment]
I suggest proposing this when regex support is spun out to a module. Maybe that module will opt for a very simple API and other libs will offer the full enchilada (as is already true).

A previous generation struggled to produce the current API, and the code comment says the main goal was extract and replace. To perform a match and discard the match info is probably not desirable. (Filtering on the predicate is almost the same as flatMap on extracted value.)

For the newbie case, there is `String::matches`.

This is trivial to support as an extension method:

```
scala> import scala.util.matching._
import scala.util.matching._

scala> implicit class m(val r: Regex) extends AnyVal {
     | def matches(s: String): Boolean = r.pattern.matcher(s).matches
     | }
defined class m

scala> raw"hello\.world".r matches "hello.world"
res0: Boolean = true

scala> raw"hello\.world".r matches "hello,world"
res1: Boolean = false
```

Also `"^hello$".r findFirstIn "hello, world"`.

The unanchored case is the same as `findFirstIn("").nonEmpty`. Changing the semantics of `matches` would probably be confusing.

**Comment by dhoepelman** [comment]
I agree that it's trivial as an extension method. I have seen that or a utility method in all of the scala projects I've encountered that use `Regex` (sometimes incorrectly defined). That's why I think it should be there by default.

More broadly speaking a regex is used either as a predicate or to extract data. `scala.util.matching.Regex` does a good job of scalafying Java's `Pattern` for extraction, but ignores the predicate use-case. In my experience the predicate use-case is more common so I picked an uncontroversial/useful predicate method to PR.

I was not aware of a desire to move regex to a separate module (did a quick search in contributors, bugtracker and sip meeting minutes before creating the issue), is there any previous public discussion about this?

> For the newbie case, there is String::matches.

It's unfortunate that they are pushed in that direction, as this can have pretty bad performance due to recompilation on every call.

**Comment by NthPortal** [comment]
Oops, misclicked

**Comment by som-snytt** [comment]
I don't mean to sound dogmatic on this question, just to say that maybe `if (r.matches(s)) something()` is an anti-pattern. With no `else`, you are side-effecting, and otherwise the `match` expression suffices. I defer to the previous art on this. Anti-patterns are common, so that is not a justification. The obvious use case is `strings filter r.matches` as opposed to `strings flatMap r.findFirstIn(_)`.

**Comment by NthPortal** [comment]
@som-snytt it's also quite useful if you're implementing a match/filter interface such as `java.io.FilenameFilter`

**Comment by ritschwumm** [comment]
i've yet to see a (non-trivial) project where i ddidn't have to implement this as an extension method sooner or later... interestingly, more often than not for use in an expression equivalent to this:
`if (re matches s) Some(s) else None`

**Comment by dhoepelman** [comment]
@som-snytt `matches` is not the smell here, it's `if` without else and the side-effect. Discussing that is a bit irrelevant.
Like you and @NthPortal mentioned there are plenty of legitimate use-cases, especially when used as a predicate.

**Comment by som-snytt** [comment]
Previous duplicate https://github.com/scala/bug/issues/4354 didn't get much attention compared to other efforts back then.

**Comment by lrytz** [comment]
+1 from me for adding it
