### ISSUE TITLE
Compiler broken with def clone.

### ISSUE THREAD

**Issue by djx314** [scala/bug#10829]
Here's the pr https://github.com/djx314/poi-collection/pull/1
Here's the scala 2.11.12's test https://travis-ci.org/djx314/poi-collection/jobs/366847915
And the 2.12.5 https://travis-ci.org/djx314/poi-collection/jobs/366847916

It seem's that when call the `def clone` the compiler will boom!
And remove all the clone method then the test case pass in my local machine.

**Comment by hepin1989** [comment]
refs https://github.com/scala/bug/issues/10501

**Comment by djx314** [comment]
Clone this since it's the same of https://github.com/scala/bug/issues/10501
