### ISSUE TITLE
List(1,2,3,4).contains("hello") compiles

### ISSUE THREAD

**Issue by pjrt** [scala/bug#10831]
This seems to be an issue in the inference of types since the following also compiles:

```scala
trait K[A] { def f[A1 >: A](a2: A1): Boolean = false } 
val x = new K[Int]{} 
x.f("Hello") // compiles
x.f[String]("Hello") // does not
```

When `[A1 >: A]` is used in a function though, it works as expected:

```scala
def f[A, A1 >: A](a: A)(a1: A1): Unit = () 
f(1)("hello") // does not compile
```

So it seems `[A1 >: A]` is unsafe when used in methods where `A` is defined at the trait/class level.

**Comment by edmundnoble** [comment]
`List(1, 2, 3, 4).contains("hello")` works for the same reason `List(None).contains(Some(1))` works.

It's not "unsafe" exactly; there's no runtime failure here. It's just that `Int <: Any` and `String <: Any`. So `Any` is inferred, because that's the most specific solution here.

In your later example, there is no actual `A1 >: A` being inferred; after the first parameter list `(1)`, the compiler infers `A1 == A`, and the `a1: A1` is really `a1: Int`, which doesn't work. You can see that this happens if you try to call `f(None)(Some(1))`, despite `Option[Nothing] <: Option[Int]`.

**Comment by pjrt** [comment]
> It's not "unsafe" exactly; there's no runtime failure here.

I disagree there. Though `false` isn't a "runtime error" (ie: an exception), it it is an error (that check will never return true). Type systems are meant to prevent these kinds of issues.

**Comment by hrhino** [comment]
> Type systems are meant to prevent these kinds of issues.

Right. Scala's inference isn't directly to blame here, though; the method signature `[A1 >: A](a1: A1): Boolean` is morally equivalent to `(a1: Any): Boolean`, which is arguably a library design bug.

**Comment by edmundnoble** [comment]
@pjrt I'm on your side here. I think the fact that this compiles is annoying and error-prone. The problem however is not possible to fix while keeping collection types covariant. In order for a `List[Int]` to also be a `List[Any]` at the same time, the methods have to be callable in the same way. If you want to avoid this, at the cost of some manual widening of types/type ascriptions, scalaz still has an `IList` (invariant list) type which doesn't have this issue. I don't believe that will change in the stdlib.

**Comment by eed3si9n** [comment]
I wrote https://contributors.scala-lang.org/t/type-safe-contains/2334

**Comment by lrytz** [comment]
`-Xlint:infer-any` warns about it (not on Scala 3 though)

```scala
$> scala -S 2.13 -Xlint
Welcome to Scala 2.13.17 (OpenJDK 64-Bit Server VM, Java 25).
Type in expressions for evaluation. Or try :help.

scala> List(1,2,3,4).contains("hello")
                     ^
       warning: a type was inferred to be `Any`; this may indicate a programming error.
val res0: Boolean = false
```

**Comment by SethTisue** [comment]
on Scala 3 it infers a union type

**Comment by lrytz** [comment]
https://github.com/scala/scala3/pull/24258
