### ISSUE TITLE
Discuss renaming ImmutableArray

### ISSUE THREAD

**Issue by lrytz** [scala/bug#10836]
We could call it `immutable.ArraySeq` (suggested by @szeiger). Reasons:
  - We might have a real immutable array in the future using opaque types
  - It makes sense to call it a Seq

**Comment by lrytz** [comment]
I think ArraySeq is a good name, it sounds like a Seq backed by an array ("has an array"). ImmutableArray sounds like "is an array", which it would be.

**Comment by odersky** [comment]
I agree. Let's keep `ImmutableArray` for the opaque wrapper for `Array`.

**Comment by szeiger** [comment]
We had `scala.collection.mutable.ArraySeq` which has been subsumed by `scala.collection.mutable.WrappedArray`. We could call it `scala.collection.mutable.ArraySeq` instead and rename `ImmutableArray` to `scala.collection.immutable.ArraySeq`. This would gives us a nice symmetry that shows that they are essentially the same (except for the pretend immutability).

**Comment by odersky** [comment]
That looks like a good plan of action.
