### ISSUE TITLE
Scaladoc underline markdown not styled with underline

### ISSUE THREAD

**Issue by janekdb** [scala/bug#10861]
When underline markdown is used in Scaladoc 2.12.x the text does not have an underline. The HTML is as expected. It's as if the CSS has turned off the underlining.

# Example
```
/**
 * '''bold''', ''italic'', `monospace`.
 *
 * ^superscript^, ,,subscript,,
 *
 * __underline__^①^.
 */
object UnderlineBug
```

![image](https://user-images.githubusercontent.com/1123855/39572533-fe03bac4-4ebe-11e8-836a-2e2c0f0c1cc2.png)

**u** tags are present,

![image](https://user-images.githubusercontent.com/1123855/39572593-46a0c18c-4ebf-11e8-9a00-4165b1c6eb6d.png)

**Comment by Jasper-M** [comment]
> It's as if the CSS has turned off the underlining.

[It looks like it.](https://github.com/scala/scala/blob/v2.13.0-M4-pre-20d3c21/src/scaladoc/scala/tools/nsc/doc/html/resource/lib/index.css#L108) My CSS is a bit rusty, but an extra `u { text-decoration: underline; }` might do the trick.

**Comment by SethTisue** [comment]
thanks Janek for the catch, and thanks Jasper for the fix!
