### ISSUE TITLE
Should in-place collection updates retain key element identities?

### ISSUE THREAD

**Issue by szeiger** [scala/bug#10860]
Should operations like `mapInPlace` and `flatMapInPlace` on mutable collections obey the general rules laid out it https://github.com/scala/bug/issues/10415#issuecomment-368047800, in particular should they retain existing key elements rather than replacing them with equal but not identical elements returned by the mapping function?

While looking at https://github.com/scala/scala/pull/6546 I was wondering what the original motivation for the current implementation with `toAdd` and `toRemove` was. The most straight-forward way to implement `mapInPlace` and `flatMapInPlace` is to collect the results, clear the collection, and copy the results back.

I assume they were written differently in order to follow this rule:
> Key element identities already in the source collection (i.e. the receiver of a method call) must always be preferred over new key elements which are equal but have different identities

The current implementations of `mapInPlace` don't and the current implementations of `flatMapInPlace` look like they were designed to but are broken.

I'm on the fence about the interpretation of my own rules in this case. On one hand, retaining key elements would make these in-place updates consistent with other in-place updates like `addOne`, on the other hand these are *mapping* methods so it makes sense that the result of the mapping operation is used (as in `map` and `flatMap`).

**Comment by ritschwumm** [comment]
at first glance i'd say keys are (immutable) _values_, and as such should not even have any other identity than the value themselves, and relying on reference equality in any way is just wrong.

except maybe as an implementation detail safely hidden inside the collection itself where you can  assume the same reference always points to the same value for performance reasons.

**Comment by szeiger** [comment]
Also pinging @mkeskells and @Ichoran who may have opinions on this.

**Comment by Ichoran** [comment]
I don't have any strong opinion, mostly because `map(k) = v` and `map += (k, v)` suggest different behaviors, yet are supposed to be identical.

I do think that `Set` and `Map` should follow the same rule.

**Comment by NthPortal** [comment]
While I think it's a decent idea to have the library behave consistently, I'm not convinced that this behaviour should be specified. FWIW, Java specifies keeping the old one (for [`Set`](https://docs.oracle.com/javase/8/docs/api/java/util/Set.html#add-E-); I can't find it for `Map`).

**Comment by szeiger** [comment]
I'm closing this ticket because the issue is addressed by the rules in https://github.com/scala/bug/issues/10415. I've come to the conclusion that the right answer to my original question is "no", mapping operations should not retain any memory of the source collection but only use the data produced by the mapping operation.
