### ISSUE TITLE
Small doc error in macro Context typecheck method

### ISSUE THREAD

**Issue by McBrainy** [scala/bug#10864]
For the `scala.reflect.macros.blackbox.Context` class [typecheck method][blackbox-context], the doc says the default for the `mode` param is `EXPRmode`, but the in-doc signature says `TERMmode`. As far as I can tell, `EXPRmode` doesn't exist (anymore?).

This appears in both the [blackbox][blackbox-context] and [whitebox][whitebox-context] docs.

[blackbox-context]: https://www.scala-lang.org/api/2.12.0/scala-reflect/scala/reflect/macros/blackbox/Context.html#typecheck(tree:Typers.this.Tree,mode:Typers.this.TypecheckMode,pt:Typers.this.Type,silent:Boolean,withImplicitViewsDisabled:Boolean,withMacrosDisabled:Boolean):Typers.this.Tree
[whitebox-context]: https://www.scala-lang.org/api/2.12.0/scala-reflect/scala/reflect/macros/whitebox/Context.html#typecheck(tree:Typers.this.Tree,mode:Typers.this.TypecheckMode,pt:Typers.this.Type,silent:Boolean,withImplicitViewsDisabled:Boolean,withMacrosDisabled:Boolean):Typers.this.Tree

**Comment by hrhino** [comment]
Nice catch! Internally, what the macro API calls `TERMmode` is in fact `EXPRmode`, so that's probably how the typo got introduced. (I don't know and can't figure out why it's different in the API layer.)

Would you like to make a pull request to scala/scala correcting it?

**Comment by heathermiller** [comment]
Yes! A PR would be most welcome!

@xeno-by, please jump in and let us know if there's anything we should be aware of about these APIs that we're overlooking?

**Comment by kamilduda** [comment]
Hey, I'd like to look into this as my first contribution :smiley:

**Comment by hrhino** [comment]
Thanks! (you don't need to ask 😉)

Feel free to swing by [scala/contributors](https://gitter.im/scala/contributors) if you have any questions, or just ask here!

**Comment by kamilduda** [comment]
Ready for review: scala/scala#6613

**Comment by kamilduda** [comment]
Retargeted to `2.12.x` branch

**Comment by SethTisue** [comment]
@kamilduda I've sent you an invite to https://github.com/orgs/scala/teams/contributors/members, if you reply here and tell me you accepted it, I'll assign this ticket to you, for the record

**Comment by kamilduda** [comment]
@SethTisue thanks! And sure, I accept it
