### ISSUE TITLE
http://www-dev.scala-lang.org/ is ranking in search

### ISSUE THREAD

**Issue by asarver** [scala/bug#10862]
Sorry if this is already known (or intended), but http://www-dev.scala-lang.org/ is ranking in google search, and some of the content on the page is a year out of date.

Wanted to bring to someone's attention in case this was a dev environment or something that shouldn't be showing up when someone searches "scala". :)

**Comment by SethTisue** [comment]
yes, it's an old testbed.

@fsalvi is this on one of the machines you manage...?

**Comment by SethTisue** [comment]
@asarver THANK YOU for calling our attention to this.

**Comment by fsalvi** [comment]
I added a redirect to the main website. It should disappear soon from search engines...

**Comment by asarver** [comment]
When will the redirect go in? The link is still accessible for me

**Comment by Jasper-M** [comment]
You might have to do a hard refresh (bypass the cache) to see it.

**Comment by asarver** [comment]
yup, good call. Thanks!
