### ISSUE TITLE
LinkedHashMap.keySet loses iteration order when manipulated

### ISSUE THREAD

**Issue by eleaar** [scala/bug#10884]
This is a follow up to: https://github.com/scala/bug/issues/4954, but I'm creating a new issue for better visibility as the problem is still (again?) present in scala 2.12.6.

The iteration order of `LinkedHashMap.keySet` breaks when the set is manipulated. Here is an example of a failing test:

```
"LinkedHashSet" must {
   // OK
    "maintain insertion iteration order when transformed" in {
      // given
      val set = mutable.LinkedHashSet(1, 2, 3, 4, 5)

      // when
      val result = set diff Set(1, 2)

      // then
      result.toSeq must contain theSameElementsInOrderAs Seq(3, 4, 5)
    }
  }

  "LinkedHashMap KeySet" must {
   // KO
    "maintain insertion iteration order when transformed" in {
      // given
      val set = mutable.LinkedHashMap(1 -> 1, 2 -> 2, 3 -> 3, 4 -> 4, 5 -> 5).keySet

      // when
      val result = set diff Set(1, 2)

      // then
      result.toSeq must contain theSameElementsInOrderAs Seq(3, 4, 5)
    }
  }
```

I think the culprit is `scala.collection.mutable.LinkedHashMap#DefaultKeySet`, which do not redefine the `+` and `-` operators of its superclass `scala.collection.MapLike#DefaultKeySet`.
In the parent implementation, an immutable copy is created on first modification, and the copy no longer preserves iteration order:
```
def + (elem: K): Set[K] = (Set[K]() ++ this + elem).asInstanceOf[Set[K]] // !!! concrete overrides abstract problem
def - (elem: K): Set[K] = (Set[K]() ++ this - elem).asInstanceOf[Set[K]] // !!! concrete overrides abstract problem
```

This is different from the behaviour of `mutable.LinkedHashSet` (inherited from `mutable.SetLike`) which creates an iteration-order preserving copy on not-in-place mutations, such as those implied by `diff`.

**Comment by SethTisue** [comment]
Does the problem still exist in Scala 2.13.0-M4? (Which just hit Maven Central minutes ago.)

**Comment by eleaar** [comment]
The problem still exists in `2.13.0-M3`, but no longer exists in `2.13.0-M4`.

I see there is a `LinkedHashSet#LinkedKeySet` class in `2.13.0-M4` which does precisely what it should. 

Great work guys! Technically, this may be a new record in bug resolution time :D

**Comment by SethTisue** [comment]
I'm going to close the ticket since it's fixed in M4, but regardless, we're still accepting bugfixes for the 2.12.x series. (Whether this particular bug is actually even fixable for 2.12.x in a sufficiently safe and binary compatible manner, I don't know offhand.)
