### ISSUE TITLE
Error message for Java "package is not a value" is incorrect in 2.12.6

### ISSUE THREAD

**Issue by lihaoyi** [scala/bug#10888]
2.12.4

```scala
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> java.lang
<console>:12: error: package java.lang is not a value
       java.lang
            ^
```
2.12.6

```scala
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> java.lang
<console>:12: error: Java class java.lang is not a value
       java.lang
            ^
```

`java.lang` is not a java class, but a package: the 2.12.4 error message was correct and the 2.12.6 error message is incorrect, making this a regression.

Notably, this broke the Ammonite test suite during the upgrade to 2.12.6 (https://github.com/lihaoyi/Ammonite/commit/2be97144fb8404059873c4d1c2de7ebd716c5753#diff-a269801311108bc1ce234cce52a424b3R17). I can work around it in the Ammonite test suite, but since it's a regression it should probably be fixed upstream anyway

**Comment by lihaoyi** [comment]
This appears to be caused by https://github.com/scala/scala/commit/55da02d3c5b381e47cabd1acaffe489d4305748b#diff-05c273d837c49f8b6278b19592a541beR756, @hrhino

**Comment by hrhino** [comment]
Good ol' Ammonite, keeping us honest. First it gives the REPL some friendly competition, now it's vetting our errors and warnings. I hope we don't get to the point where, after a green community build run, I have to ask Seth "okay Seth, pretty please kick off an Ammonite build?". I just finished reading up on dbuild for self-sufficiency purposes; guess it's time to read up on Mill, too.

**Comment by som-snytt** [comment]
You'll have to read up on Grinder, the Mill-based community build.
