### ISSUE TITLE
Command invoked with sys.process behaves differently than when invoked in shell (both bash and fish)

### ISSUE THREAD

**Issue by SongWithoutWords** [scala/bug#10897]
I encountered this issue when trying to invoke `emacs --eval '(ediff "file1" "file2")'`, from Scala in order to diff failed test results against the expected result.

The issue can be reproed using the following minimal example:

```scala
~> scala
Welcome to Scala 2.12.6 (OpenJDK 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> import sys.process._
import sys.process._

scala> """emacsclient --eval '(+ 4 5)'""".!

*ERROR*: End of file during parsingres0: Int = 1

scala> :quit
~> emacsclient --eval '(+ 4 5)'
9
```

**Comment by SongWithoutWords** [comment]
The message `*ERROR*: End of file during parsing` from Emacs indicates that there is an unmatched opening parenthesis, so it's almost as if the command line is modified in some way before it is invoked.

**Comment by SongWithoutWords** [comment]
This issue occurs also with `Process("emacsclient --eval '(+ 4 5)'").!!` and `Process("emacsclient --eval '(+ 4 5)'").lines`, and in both sbt builds and the scala interpreter.

**Comment by SethTisue** [comment]
no shell is involved with `sys.process.!`, by design. that means shell-specific concepts like quoting don't apply. to separate arguments, do e.g. `Seq("emacsclient", "--eval", "(+ 4 5)").!`. the same is true of the underlying Java API

**Comment by SongWithoutWords** [comment]
thank you @SethTisue , works like a charm
