### ISSUE TITLE
Access interpolated expression text in interpolated strings

### ISSUE THREAD

**Issue by etorreborre** [scala/bug#10890]
In [specs2](https://github.com/etorreborre/specs2/blob/master/core/shared/src/main/scala/org/specs2/specification/create/S2StringContext.scala#L203) we use string interpolation to "inject" tests to execute inside an interpolated string. When those tests are so expressive that the preceding text is redundant, we use the expression text as [a description of the test itself](https://etorreborre.github.io/specs2/guide/SPECS2-4.2.0/org.specs2.guide.AutoExamples.html#in-an-acceptance-specification):
```scala
class SeqSpecification extends Specification { def is = s2"""
  updateLast modifies the last element of a Seq
  ${ Seq(1).updateLast(_ + 1)     must_== Seq(2)     }
  ${ Seq(1, 2).updateLast(_ + 1)  must_== Seq(1, 3)  }
  ${ Seq[Int]().updateLast(_ + 1) must_== Seq[Int]() }
"""
}
```

At the moment this is implemented using `-Yrangepos` but this option sometimes has to be deactivated (because of some compiler bugs) and will not be present in Scala 3. So it would be nice to extends the `StringContext` to include the "parts" and the "expressions"
```
case class StringContext(parts: Seq[String], expressions: Seq[String])
```
So that in principle it would be almost possible to reconstitute the original interpolated string.

**Comment by hrhino** [comment]
> will not be present in Scala 3

I think that's not true; Dotty's positions are all range right now.

**Comment by etorreborre** [comment]
@hrhino sorry for the misunderstanding. In any case it would be nice if those strings were accessible directly rather than doing the pos searching I'm doing [here](https://github.com/etorreborre/specs2/blob/master/core/shared/src/main/scala/org/specs2/specification/create/S2Macro.scala#L14).

Regarding `-Yrangepos` issues, I don't remember having them directly on the `s2` macro but I remember other people reporting it in [other macros](https://github.com/typesafehub/scalalogging/issues/38) so they had to deactivate the option for specs2.

**Comment by etorreborre** [comment]
Closing this old issue now.

**Comment by SethTisue** [comment]
`-Yrangepos` is now on by default in Scala 2.

changing `StringContext` is permanently out of scope for Scala 2, but someone could request this at https://github.com/lampepfl/dotty-feature-requests/ , for possible action after Scala 3 leaves the Scala 2 standard library behind
