### ISSUE TITLE
Collections are missing scan equivalent of reduce (Haskell's scanl1)

### ISSUE THREAD

**Issue by klaeufer** [scala/bug#10898]
This is a variant of `scanLeft` that has no starting value argument, requiring the collection to be nonempty.

```
def scanLeft1[A](op: (A, A) => A): Seq[A] = this.tail.scanLeft(xs.head)(op)
Seq(1, 2, 3).scanLeft(_ + _) == Seq(1, 3, 6)
```

It would apply to finite and infinite collections. 

Whether `scanLeft1` is the best name is subject to further discussion.

Applies up to 2.13.x as far as I can tell.

**Comment by som-snytt** [comment]
My attempt as an overload in 2.13 seems to fail:

https://github.com/scala/scala/pull/6677

**Comment by Wogan** [comment]
This looks similar to `combine` from `SemiGroup`; maybe that name makes sense.

**Comment by som-snytt** [comment]
@Wogan Thanks for looking. You raised my hopes and then dashed them. :)

I may propose calling it `somSnytt`, which is the same length as `scanLeft` with the same initial and final letter. That ought to drum up further responses both pro and con, probably con.

**Comment by som-snytt** [comment]
That's because [nobody cares](https://contributors.scala-lang.org/t/which-operations-should-be-included-in-the-new-collections/1106/80).

**Comment by palanga** [comment]
@som-snytt I do care
