### ISSUE TITLE
change Either subclasses type parameters?

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#10895]
We can delete some `asInstanceOf` if change type parameters of `scala.util.Left` and `scala.util.Right`.

```diff
  */
-final case class Left[+A, +B](value: A) extends Either[A, B] {
+final case class Left[+A](value: A) extends Either[A, Nothing] {
   def isLeft  = true
   def isRight = false
 }
@@ -432,7 +432,7 @@ final case class Left[+A, +B](value: A) extends Either[A, B] {
  *  @author <a href="mailto:research@workingmouse.com">Tony Morris</a>, Workingmouse
  *  @version 1.0, 11/10/2008
  */
-final case class Right[+A, +B](value: B) extends Either[A, B] {
+final case class Right[+B](value: B) extends Either[Nothing, B] {
   def isLeft  = false
   def isRight = true
```

```diff
   def map[B1](f: B => B1): Either[A, B1] = this match {
     case Right(b) => Right(f(b))
-    case _        => this.asInstanceOf[Either[A, B1]]
+    case l@Left(_) => l
   }
 ```

Are there any advantages the current definition?

https://github.com/xuwei-k/scala-1/commit/01c6b85a3f38a71b0f08fef7859f969380341f86

**Comment by SethTisue** [comment]
related: https://github.com/scala/scala/pull/6329

**Comment by eed3si9n** [comment]
If we are considering source compatibility breakages, what do you guys think about hiding `Left` and `Right` as types and leave in `object Right` whose `apply` returns `Either[Nothing, B]`? This would be analogous to `def ::` returning `List[A]` and being able to pattern match using `::`.
Thankfully there are no methods specific to `Left` or `Right`.

**Comment by dwijnand** [comment]
What am I not understanding? AFAICT `Right.apply` switching from returning `Right` to `Either` is a source compatibility breakage.

**Comment by SethTisue** [comment]
I'm going to close this as design discussions should happen on https://contributors.scala-lang.org, scala/bug is for bugs. there is no bug here.

**Comment by dwijnand** [comment]
I've bootstrapped the conversation on the forums: https://contributors.scala-lang.org/t/change-either-subclasses-type-parameters/1918.
