### ISSUE TITLE
Multiple statements in the REPL should evaluate toString in the same order

### ISSUE THREAD

**Issue by dwijnand** [scala/bug#10893]
The outputs of this should be the same:

```scala
scala> final class Counter(var i: Int = 0) { def next() = { i += 1; i }; def countItUp() = { next(); () }; override def toString = { next(); "" + i } }
defined class Counter

scala> val c = new Counter(); c.countItUp(); c.next()
c: Counter = 3
res14: Int = 2

scala> val c = new Counter(); c.countItUp()
c: Counter = 2

scala> c.next()
res16: Int = 3
```

This is a generalisation of the original `Iterator` issue reported in #10892, and stems from the same Gitter conversation: https://gitter.im/scala/contributors?at=5b02b656e0b50c2d05dca187

**Comment by SethTisue** [comment]
I'm fine with the existing behavior, as discussed on Gitter. It seems normal to me that `toString` only gets called at the end when all the bindings are being printed.

But I'd also be fine with an implementation that interleaves evaluation and printing, too. that would make e.g. `val x = 1; while(true) { }` print `val x: Int = 1` before hanging, which seems nice.

**Comment by hrhino** [comment]
[Gitter link](https://gitter.im/scala/contributors?at=5b02b656e0b50c2d05dca187), for posterity.

**Comment by dwijnand** [comment]
I'm ambivalent on whether `val x: Int = 1` should print or not, just that its RHS `toString` is evaluated at the right time.

So generalising I think the following property should be true:

* multiple statements on the same line, i.e `a; b; c`,
* should mean the same thing as on multiple-lines, i.e `a\nb\nc`,
* and viceversa.

**Comment by dwijnand** [comment]
and by `toString` there I mean "string output" (to account for the actual use of `replStringOf`).

**Comment by dwijnand** [comment]
@adriaanm given your recent 2.13 REPL ventures, (1) WDYT of this ticket? and (2) do you think you could mentor on how to go about fixing this for 2.13.0-M5?

**Comment by som-snytt** [comment]
@dwijnand What you're looking for here:
```
scala> :help
All commands can be abbreviated, e.g., :he instead of :help.
:completions <string>    output completions for the given string
:edit <id>|<line>        edit history
:help [command]          print this summary or command-specific help
:history [num]           show the history (optional num is commands to show)
:h? <string>             search the history
:imports [name name ...] show import history, identifying sources of names
:implicits [-v]          show the implicits in scope
:javap <path|class>      disassemble a file or class name
:line <id>|<line>        place line(s) at the end of history
:load <path>             interpret lines in a file
:paste [-raw] [path]     enter paste mode or paste a file
:power                   enable power user mode
:quit                    exit the interpreter
:replay [options]        reset the repl and replay all previous commands
:require <path>          add a jar to the classpath
:reset [options]         reset the repl to its initial state, forgetting all session entries
:save <path>             save replayable session to a file
:sh <command line>       run a shell command (result is implicitly => List[String])
:settings <options>      update compiler options, if possible; see reset
:silent                  disable/enable automatic printing of results
:type [-v] <expr>        display the type of an expression without evaluating it
:kind [-v] <type>        display the kind of a type. see also :help kind
:warnings                show the suppressed warnings from the most recent line which had any

scala> final class Counter(var i: Int = 0) { def next() = { i += 1; i }; def countItUp() = { next(); () }; override def toString = { next(); "" + i } }
defined class Counter

scala> :silent

scala> val c = new Counter(); c.countItUp(); val first = c.next()

scala> val c = new Counter(); c.countItUp()

scala> :silent

scala> c.next
res4: Int = 2

scala> first
res5: Int = 2

```
Probably the `silent` command itself needn't actually operate silently. It's a little creepy.

**Comment by som-snytt** [comment]
Maybe the feedback is behind a flag because it means "batch mode" rather than "my toString is side-effecting."
```
$ scala -Dscala.repl.info

     ________ ___   / /  ___  
    / __/ __// _ | / /  / _ | 
  __\ \/ /__/ __ |/ /__/ __ | 
 /____/\___/_/ |_/____/_/ | | 
                          |/  version 2.12.6
[info] started at Mon May 21 14:06:44 PDT 2018

scala 2.12.6> :silent
Result printing is off.
```

**Comment by dwijnand** [comment]
I'd like the evaluation of toString to happen at the right time, but I don't want to lose results printing.

**Comment by adriaanm** [comment]
Happy to help, but this is not going to be a quick fix. The result printing code is pretty convoluted. Would be nice to clean it up though!

**Comment by som-snytt** [comment]
I took a look a week ago. My idea was to rewrite user code to:
```
val c = new C
val ires13 = print(c)
c.f()
val res14 = c.next()
val ires15 = print(res14)
```
The `eval` object has the form:
```
lazy val result = $line3.$read.$iw.$iw.res14
lazy val print = print(c) + print(res14)
```
the only change would be to use the intermediate print results:
```
lazy val print = ires13 + ires15
```

The annoying part is that the ancient REPL is not amenable to rewriting. I could revive a PR from a few years ago to operate on trees instead. 

The additional trick would be not to force those ires values when not running as REPL, for programmatic usage. I think that's why those members are lazy.

I just noticed that the PR went through so you don't see `eval` cruft under `-Xprint:typer` unless you `-Dscala.repl.debug`. That's nice.

**Comment by som-snytt** [comment]
Power asserts in Groovy suffer the same problem with respect to side effects. The intro docs mention it. In REPL, you know you're going to need these intermediate representations. Aside from side-effecting `toString`, there's no downside. It would be nice if there were a uniform way to capture state cheaply, but maybe that's called serialization.

**Comment by som-snytt** [comment]
Worth adding that the REPL output doesn't actually make much sense:
```
scala> val c = new C
val c: C = C@2a504ea7
```
It is not "something you can paste into the REPL". If I want the REPL to expand inferred types, like automatic print/show mode, then it could redraw
```
scala> val c: C = new C()
C@2a504ea7
```
or possibly with caret, similar to errors
```
scala> val c: C = new C()
           ^ C@2a504ea7
```
