### ISSUE TITLE
Iterator#hasNext should be documented

### ISSUE THREAD

**Issue by dwijnand** [scala/bug#10894]
There's detail in the class docs (v2.13.0-M4) about `Iterator#hasNext`, but nothing on the method itself. Should there by at the very minimum a reference?

**Comment by dyuval** [comment]
@dwijnand did you had in mind something like this: 
  /**  Returns true if there is a next element available. */
  def hasNext: Boolean

**Comment by dwijnand** [comment]
I would say that and also a reference to the further information available in the class docs.
