### ISSUE TITLE
`def collect(pf: PartialFunction)` implemented in term of `isDefinedAt` and `apply`

### ISSUE THREAD

**Issue by allanrenucci** [scala/bug#10901]
The following implementations of `collect` are implemented in term of `isDefinedAt` and `apply` which will cause double evaluation of pattern matchers and guards:
- [x] `AnyRefMap`
- [x] `Try`
- [x] `LongMap`
- [x] `StrictOptimizedIterableOps`
- [x] `SortedSet`
- [x] `SortedMap`
- [x] `collection.Map`
- [x] `Iterator`
- [x] `Iterable`

**Comment by Jasper-M** [comment]
What's the alternative?

**Comment by szeiger** [comment]
We already use `applyOrElse` in `ArrayOps` but it's questionable as an optimization. I just ran some benchmarks for a similar implementation in `Iterable.collect`. Depending on the PF and the percentage of matches it can be faster but it can also be considerably slower. For simple PFs such as
```
    val res = testObject.collect1 {
      case i if i < size => 1
    }
```
the naive implementation is *always* faster, even when matching 100% (i.e. the guard is always evaluated twice). When only 10% of the elements are matched, the naive implementation is a full 30% faster than the one with `applyOrElse`:

```scala
  def collect2[B](pf: PartialFunction[A, B]): CC[B] = flatMap { a =>
    var matched = true
    def d(x: A): B = {
      matched = false
      null.asInstanceOf[B]
    }
    val v = pf.applyOrElse(a, d)
    if(matched) new View.Single(v)
    else View.Empty
  }
```

**Comment by allanrenucci** [comment]
I believe the performance loss comes from boxing `var matched`.

Have you tried `collect` implemented as
```scala
def collect[B](pf: PartialFunction[A, B]): CC[B] = flatMap { a =>
  val v = pf.applyOrElse(a, checkFallback[B])
  if (!fallbackOccurred(v)) new View.Single(v)
  else View.Empty
}
```

`checkFallback` and `fallbackOccurred` are currently private to `PartialFunction`, but we could either make it private to the collection or create a similar marker object for `Iterable`.

**Comment by szeiger** [comment]
The performance of the "fallback" version is the same as the one with the flag. Here are some numbers from the simple PF above:
```
[info] Benchmark                  (size)  Mode  Cnt      Score     Error  Units
[info] CollectBenchmark.collect1     100  avgt   40  11844.599 ±  54.192  ns/op
[info] CollectBenchmark.collect1    1000  avgt   40  22455.749 ±  82.692  ns/op
[info] CollectBenchmark.collect2     100  avgt   40  16470.658 ± 581.862  ns/op
[info] CollectBenchmark.collect2    1000  avgt   40  23519.922 ± 320.782  ns/op
[info] CollectBenchmark.collect3     100  avgt   40  16100.244 ± 119.509  ns/op
[info] CollectBenchmark.collect3    1000  avgt   40  23972.883 ± 830.894  ns/op
```
1 = naive (current impl), 2 = flag, 3 = fallback. The size of the initial buffer is always 1000, the "size" parameters determines how many of those 1000 are collected.

**Comment by martijnhoekstra** [comment]
Do you have the harness gistable @szeiger? I wonder what the "pretty" implementation `flatmap(a => pf.andThen(b => View.Single(v)).applyOrElse(a, View.Empty))` does in terms of performance.

**Comment by szeiger** [comment]
`enableOptimizer`, then `bench/jmh:run scala.collection.CollectBenchmark` in https://github.com/scala/scala/compare/2.13.x...szeiger:issue/10901-wip

**Comment by allanrenucci** [comment]
I tried three other implementations of collect:
```scala
def collect4[B](pf: PartialFunction[A, B]): CC[B] = {
  val marker = new Object{}
  val fallback = ((x: A) => marker).asInstanceOf[Function[A, B]]
  flatMap { a =>
    val v = pf.applyOrElse(a, fallback)
    if (marker eq v.asInstanceOf[AnyRef]) View.Empty
    else new View.Single(v)
  }
}

def collect5[B](pf: PartialFunction[A, B]): CC[B] = {
  val marker = new Object{}
  flatMap { a =>
    val v = pf.applyOrElse(a, ((x: A) => marker).asInstanceOf[Function[A, B]])
    if (marker eq v.asInstanceOf[AnyRef]) View.Empty
    else new View.Single(v)
  }
}

def collect6[B](pf: PartialFunction[A, B]): CC[B] = {
  flatMap { a =>
    val marker = new Object{}
    val v = pf.applyOrElse(a, ((x: A) => marker).asInstanceOf[Function[A, B]])
    if (marker eq v.asInstanceOf[AnyRef]) View.Empty
    else new View.Single(v)
  }
}
```
Here is the benchmark results:
```
CollectBenchmark.collect1     100  avgt   40   5881.805 ± 118.819  ns/op
CollectBenchmark.collect1    1000  avgt   40  18657.741 ± 320.144  ns/op
CollectBenchmark.collect2     100  avgt   40   8543.085 ± 304.188  ns/op
CollectBenchmark.collect2    1000  avgt   40  18208.450 ± 310.302  ns/op
CollectBenchmark.collect3     100  avgt   40   8345.246 ± 154.708  ns/op
CollectBenchmark.collect3    1000  avgt   40  17054.773 ± 226.218  ns/op
CollectBenchmark.collect4     100  avgt   40   7952.027 ± 109.386  ns/op
CollectBenchmark.collect4    1000  avgt   40  16965.747 ± 327.751  ns/op
CollectBenchmark.collect5     100  avgt   40   7012.025 ± 101.616  ns/op
CollectBenchmark.collect5    1000  avgt   40  17222.528 ± 318.504  ns/op
CollectBenchmark.collect6     100  avgt   40   7732.255 ± 123.136  ns/op
CollectBenchmark.collect6    1000  avgt   40  18383.640 ± 298.732  ns/op
```
If we were to implement `collect` in term of `applyOrElse`, `collect5` seems to be the best compromise.

Also I changed the benchmark to collect on a `List` instead of an `ArraySeq`.

**Comment by viktorklang** [comment]
@allanrenucci Why do you need to allocate a new marker for each invocation?

**Comment by viktorklang** [comment]
@allanrenucci Collect2 is this:

```scala
  def collect2[B](pf: PartialFunction[A, B]): CC[B] = flatMap { a =>
    var matched = true
    def d(x: A): B = {
      matched = false
      null.asInstanceOf[B]
    }
    val v = pf.applyOrElse(a, d)
    if(matched) new View.Single(v)
    else View.Empty
  }
```

**Comment by allanrenucci** [comment]
My bad, I meant `collect3`:
```scala
def collect3[B](pf: PartialFunction[A, B]): CC[B] =
  flatMap { a =>
    val v = pf.applyOrElse(a, Iterable.checkFallback[B])
    if (!Iterable.fallbackOccurred(v)) new View.Single(v)
    else View.Empty
  }
```

**Comment by viktorklang** [comment]
@allanrenucci Are `checkFallback` and `fallbackOccurred` @inline and/or final?

**Comment by Ichoran** [comment]
If we're concerned about efficiency, why is this implemented in terms of `flatMap` with an extra wrapper?

Also, I generally find self-returning functions faster than closures that return a different marker when using `applyOrElse`:

```scala
val loop = new Function1[Any, AnyRef]{ def apply(a: Any) = this }
. . .
pf.applyOrElse(x, loop)
```

Before optimization, this makes sense, as you only have one formal allocation instead of two.

**Comment by szeiger** [comment]
`flatMap` is the best you can do in `Iterable`. We have more efficient implementations in subclasses. I benchmarked the most inefficient case as a baseline. On more specialized implementations the performance differences of PF handling should be even larger.

**Comment by Ichoran** [comment]
@szeiger - If that were true, then `filter` would also have to defer to `flatMap`, which it doesn't.

**Comment by szeiger** [comment]
I suppose we could add `View.Collect` as a potentially more efficient backing operation.

**Comment by szeiger** [comment]
I can confirm Allan's results. Using a separate marker object is measurably faster than a self-returning functions. But there is no need to allocate it inside of `collect`. Reusing a global instance is just as fast. My latest results show this:
```
[info] Benchmark                  (size)  Mode  Cnt      Score     Error  Units
[info] CollectBenchmark.collect1     100  avgt   40  11933.688 ± 123.867  ns/op
[info] CollectBenchmark.collect1    1000  avgt   40  21033.375 ± 172.246  ns/op
[info] CollectBenchmark.collect3     100  avgt   40  14094.684 ± 219.073  ns/op
[info] CollectBenchmark.collect3    1000  avgt   40  20559.268 ± 161.540  ns/op
[info] CollectBenchmark.collect4     100  avgt   40  15566.985 ± 134.621  ns/op
[info] CollectBenchmark.collect4    1000  avgt   40  20511.994 ± 203.303  ns/op
[info] CollectBenchmark.collect5     100  avgt   40  14103.956 ± 165.178  ns/op
[info] CollectBenchmark.collect5    1000  avgt   40  20866.314 ± 236.182  ns/op
```
1 = naive, 3 = global marker, 4 = global self-returning function, 5 = same as allan's 5

It also shows that we're already faster than the naive version when keeping all results but the 10% case is still quite a bit slower. I'll prepare a PR based on my latest version with some further optimizations via `View.Collect`.

**Comment by szeiger** [comment]
Another interesting option:
```scala
  def collect1[B](pf: PartialFunction[A, B]): CC[B] = { // from StrictOptimizedIterableOps
    val t = collectThrowable
    val b = iterableFactory.newBuilder[B]
    val it = iterator
    while (it.hasNext) {
      val elem = it.next()
      try b += pf.applyOrElse[A, B](elem, ((x: A) => throw t))
      catch { case ignored if ignored eq t => }
    }
    b.result()
  }
```
Throwing an exception in the non-matching case is only 5% slower for the size=100 test (90% non-matching) but 25% faster for size=1000 (100% matching).

**Comment by szeiger** [comment]
I spoke too soon. I didn't compile the library with optimizations for that test. Using an Exception is a bit slower in both cases when the optimizer is enabled.

**Comment by viktorklang** [comment]
@szeiger Where do you toggle that setting?
