### ISSUE TITLE
Add `--` operator on s.c.i.Set

### ISSUE THREAD

**Issue by julienrf** [scala/bug#10900]
`collection.Set[A]` has a deprecated `--` operation that takes as parameter another `Set[A]`. In 2.12 this operation was not deprecated and took a `TraversableOnce` as parameter.

But then immutable `Set` does not provide a non-deprecated `--` operation. FTR, this operator does exist in `s.c.i.Map`.

I think we should add the following operations to `s.c.i.SetOps[A]`:

~~~ scala
def removeAll(values: IterableOnce[A]): C = values.iterator.foldLeft(coll)(_ - _)
@`inline` final def -- (values: IterableOnce[A]): C = removeAll(values)
~~~

**Comment by szeiger** [comment]
Why did we create this asymmetry in the first place? `Set` supports set difference with `diff` (`&-`) and exclusion of single elements with `excl` (`-`) whereas `Map` supports removal of elements with `removeAll` (`--`) and `remove` (`-`). Having different names for these operators makes sense but sharing the symbolic operators for some of them less so. Should we rename `&-` back to `--`?

**Comment by julienrf** [comment]
`&~` is different than `--` because the former takes a `Set` whereas the latter takes an `IterableOnce`. Both `&~` and `--` exists in 2.12. Maybe we should keep both of them?
