### ISSUE TITLE
A case of `this`

### ISSUE THREAD

**Issue by viktorklang** [scala/bug#10912]
Scala Version 2.12:

I has made a mistake—I, naïvely I might add—expected the following to work:

~~~scala
class F {
  def f = (this:AnyRef) match {
    case `this` => println("success")
  }
}
~~~

But it yields:

~~~
<console>:13: error: not found: value this
            case `this` => println("success")
~~~

-Xprint:parser says:

~~~scala
class F extends scala.AnyRef {
          def <init>() = {
            super.<init>();
            ()
          };
          def f = (this: AnyRef) match {
            case ``this`` => println("success") // NOTICE THE DUPLICATED BACKTICKS
          }
        }
~~~

If *this* should not be legal to match against, then I think the error message should be more informative, and in the case this is indeed a bug, what would the consequence(s) be of fixing it?

**Comment by hrhino** [comment]
I think the only plausible bug here is that `case this => ...` doesn't compile.

The duplicated backticks are probably "just" #10685.

It's problematic that backticks mean both "treat this as an identifier even though it doesn't follow the normal lexical rules for identifiers" _and_ "treat this lowercase identifier as an identifier pattern even though it would syntactically be a variable pattern". Plausibly a new syntax for the latter could be introduced. But here Scala just wants a value in scope named `TermName("this")`, which isn't `this`.

**Comment by hrhino** [comment]
Kinda like [this](https://scalafiddle.io/sf/if2LV0N/0):

```scala
object F {
  val `true` = false
  def f = (false: Boolean) match {
    case `true` => println("success")
  }
}

F.f // success
```

**Comment by viktorklang** [comment]
The following works though:

```
class F {
  def f: Unit = (this: AnyRef) match {
    case _: this.type => println("success")
  }
}
```

**Comment by hrhino** [comment]
Right, it's a type pattern and `this.type` is a perfectly cromulent type.

**Comment by viktorklang** [comment]
@hrhino I still think it should be possible to match against the value of that type. :)

**Comment by hrhino** [comment]
Yep. As I mentioned, I'm pretty sure the bug is that `case this =>` should be accepted. I'm not sure if the spec grammar means that "this" qualifies as a `StableId`, which it would need to be to justify that syntax without a spec change, but it seems correct to me.

The other place that `StableId` shows up (other than `Path`) is imports, but that leaves a lot to be desired:

```scala
scala> :pa -raw
// Entering paste mode (ctrl-D to finish)

object A {
  val x = 1
  val y = {
    import this.{x => z}
    z
  }
}

// Exiting paste mode, now interpreting.

<pastie>:4: error: identifier expected but '{' found.
    import this.{x => z}
                ^
<pastie>:5: error: identifier expected.
    z
^
There were compilation errors!
```

```scala
scala> :pa -raw
// Entering paste mode (ctrl-D to finish)

object B {
  val x = 1
  val y = {
    val x = 2
    {
      import this.x
      x
    }
  }
}

// Exiting paste mode, now interpreting.

<pastie>:7: error: '.' expected.
      x
^
There were compilation errors!

**Comment by dwijnand** [comment]
> It's problematic that backticks mean both "treat this as an identifier even though it doesn't follow the normal lexical rules for identifiers" _and_ "treat this lowercase identifier as an identifier pattern even though it would syntactically be a variable pattern". Plausibly a new syntax for the latter could be introduced. But here Scala just wants a value in scope named `TermName("this")`, which isn't `this`.

I was thinking what about making keywords that are values (e.g `true` or `this`, as opposed to, say, `private`, `val`) be un-backtickable. Then you avoid weird things like "re-defining" `true` or `this. WDYT?

**Comment by viktorklang** [comment]
Apparently I never give up! 😂
-- 
Cheers,
√

**Comment by hrhino** [comment]
That's the spirit!
