### ISSUE TITLE
Make viewness of mapValues / filterKeys more obvious

### ISSUE THREAD

**Issue by lrytz** [scala/bug#10919]
@Ichoran suggests to rename them to `mappedValueView` / `filteredKeyView` (https://github.com/scala/bug/issues/4776#issuecomment-394183317).

For naming, I think `mapValuesView` / `filterKeysView` would be more consistent, as the strict methods are called `map` / `filter` (not `mapped` / `filtered`).

"Alternatively, return a value class with a single method, `view`, that gives out the view"

**Comment by smarter** [comment]
Having a strict version of these methods would be great too.

**Comment by lrytz** [comment]
In principle the operations should be strict on strict collections, and lazy on views, like other operations. We probably cannot just change the semantics though..

**Comment by szeiger** [comment]
Let's deprecate the operations on `MapOps` now and undeprecate them on `MapView` so that you get the desired semantics with `.view.mapValues` and `.view.filterKeys`. Maybe we can make the versions on `Map` strict in 2.14 after a deprecation cycle without removing them first? Otherwise this will have to wait until Scala 3.1.

**Comment by lrytz** [comment]
This sounds good, but it's annoying if you want a strict `mapValues` (without deprecation warning): you have to write `.view.mapValues(f).toMap`. We could add `mapValuesStrict`? But it's also not great to add a method only to deprecate it in the next release...

**Comment by szeiger** [comment]
Well, it's already better than 2.12 where there's no obvious way at all to make the result strict.

**Comment by joshlemer** [comment]
@szeiger do we still want to deprecate MapOps#mapValues?

**Comment by szeiger** [comment]
After rereading this thread it still looks like a sensible option to me. I'm undecided whether the replacement should be a dedicated `mapValuesView` method or `.view.mapValues`.

**Comment by julienrf** [comment]
Introducing `mapValuesStrict` or `mapValuesView` would look quite bad, imho.

**Comment by SethTisue** [comment]
@joshlemer once you've accepted the invitation to https://github.com/orgs/scala/teams/contributors , comment here and I'll assign this ticket to you.

**Comment by joshlemer** [comment]
@SethTisue I accepted it

**Comment by SethTisue** [comment]
👍 thanks for all the good scala/scala PRs lately, much appreciated!

**Comment by SethTisue** [comment]
> it's annoying if you want a strict mapValues (without deprecation warning): you have to write .view.mapValues(f).toMap

And also note that by going through `.view` like that you lose the original collection type, `toMap` will only be right if the original type was `immutable.Map`

fwiw, `transform` exists as a strict, collection-type-preserving alternative:

```
scala 2.13.1> collection.immutable.SortedMap(1 -> "foo")
res7: scala.collection.immutable.SortedMap[Int,String] = TreeMap(1 -> foo)

scala 2.13.1> res4.transform((_, v) => v.length)
res8: scala.collection.immutable.SortedMap[Int,Int] = TreeMap(1 -> 3)
```

thx @OlegYch for the reminder
