### ISSUE TITLE
Avoid splash reader

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#10929]
Maybe Spark doesn't want a splash reader.

Maybe they want to initialize synchronously, output the result of some init code, and only then let the user return from their coffee break to start inputting amazing code.

Let's just resuscitate `-Yrepl-sync` for this purpose.

**Comment by SethTisue** [comment]
@som-snytt I don't understand the thinking here

**Comment by som-snytt** [comment]
Closing this as obsolete because the refactored REPL (work underway) requires the backend (compiler) is initialized concurrently with the frontend (line reader), so a special "splash reader" (like a splash screen except it read a line of text so user could start typing) is no longer required. This description is partly aspirational.
