### ISSUE TITLE
scalac produces inconsistent output on Mac with case-insensitive FS in case of a name clash

### ISSUE THREAD

**Issue by pshirshov** [scala/bug#10926]
`scalac` silently overwrites it's own output producing an inconsistent set of classfiles in situation when it works on a case-insensitive filesystem (like MacOS with default settings) and you have a name conflict in your source files, like:

1. You have a package object and defined a class named `Package`
2. You have two classes with the same name in different cases, like `Test` and `test`

In case (2) `scalac` produces a good warning:

```
Warning:(7, 7) Generated class c1.test differs only in case from c1.Test.
  Such classes will overwrite one another on case-insensitive filesystems.
``` 

Though case (1) is completely missed. The problem is obscure and not so easy to track.

**Comment by pshirshov** [comment]
This case is a bit different. Though, anyway, why these two tickets were closed?

**Comment by som-snytt** [comment]
Currently warns, per linked test.
