### ISSUE TITLE
Nil.startsWith(Nil, 1) return true but Array().startsWith(Array(), 1) return false in latest Scala 2.13

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#10931]
build.sbt

```scala
resolvers += "scala-pr" at "https://scala-ci.typesafe.com/artifactory/scala-integration/"

scalaVersion := "2.13.0-pre-2b49d71" // latest 2018-06-05
```

### latest Scala 2.13

```
Welcome to Scala 2.13.0-pre-2b49d71 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> Nil.startsWith(Nil, 1)
res0: Boolean = true

scala> Array[Int]().startsWith(Array[Int](), 1)
res1: Boolean = false
```

### Scala 2.13.0-M4

```
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> Nil.startsWith(Nil, 1)
res0: Boolean = true

scala> Array[Int]().startsWith(Array[Int](), 1)
res1: Boolean = false
```

### Scala 2.12.6

```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> Nil.startsWith(Nil, 1)
res0: Boolean = true

scala> Array[Int]().startsWith(Array[Int](), 1)
res1: Boolean = true
```

**Comment by julienrf** [comment]
Our custom implementation in `ArrayOps` is not consistent with the implementation in `SeqOps`. Also I’ve noticed that this operation is not on `StringOps`. We should probably add it as well for the sake of consistency.

**Comment by szeiger** [comment]
It's pointless in `StringOps` because `java.lang.String` has it's own `startsWith` method.

**Comment by szeiger** [comment]
I'm wondering if the original implementation was intentional or accidental. Does it make sense to say that a collection contains an empty collection at an out-of-bounds index?

**Comment by lrytz** [comment]
`Nil` is not defined at index `0`, but `Nil.startsWith(Nil, 0)` is true. So it seems to make sense if `Nil.startsWith(Nil, x)` is true for any x.
