### ISSUE TITLE
inappropriate mutable.MultiMap#toString in Scala 2.13.0-M4

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#10932]
```scala
package example

import collection.mutable.{ HashMap, MultiMap, Set }

object MultiMapToStringExample {
  def main(args: Array[String]): Unit = {
    val x = new HashMap[Int, Set[String]] with MultiMap[Int, String]
    x.addBinding(1, "a")
    println(x)
  }
}
```

```
>; ++ 2.13.0-M4!; run
[info] Running example.MultiMapToStringExample 
MultiMapToStringExample(1 -> HashSet(a))
```

```
>; ++ 2.12.6!; run
[info] Running example.MultiMapToStringExample 
Map(1 -> Set(a))
```

I think we should override [`def className: String`](https://github.com/scala/scala/blob/v2.13.0-M4/src/library/scala/collection/Iterable.scala#L183-L260)

**Comment by szeiger** [comment]
Taking another look at those definitions, except for `View` all of them are in concrete collection implementations. If we add them to abstract traits like `Map` (which is the case in 2.12) this calls into question the need for the generic implementation in `Iterable`. We could simply set it to `Iterable` there, add overrides in `Map`, `Set` and `Seq` and require all collection implementations to override it if they want something more specific. The current situation where some collection types get a more or less good default and others don't is rather unsatisfactory.

**Comment by lrytz** [comment]
Sounds good to me.
