### ISSUE TITLE
Add updateWith/updatedWith operation to Map collections

### ISSUE THREAD

**Issue by julienrf** [scala/bug#10949]
I think it would be interesting to add an `updatedWith` operation to `immutable.Map`:

~~~ scala
def updatedWith[V1 >: V](key: K)(f: PartialFunction[Option[V], Option[V1]]): Map[K, V1]
~~~

This operation has been implemented in scala-collection-contrib, for reference: https://github.com/scala/scala-collection-contrib/blob/master/src/main/scala/scala/collection/decorators/ImmutableMapDecorator.scala#L7-L26

Similarly, we should have an `updateWith` operation in `mutable.Map`:

~~~ scala
def updateWith(key: K)(f: PartialFunction[Option[V], Option[V]]): Option[V]
~~~

This operation was also implemented in scala-collection-contrib: https://github.com/scala/scala-collection-contrib/blob/master/src/main/scala/scala/collection/decorators/MutableMapDecorator.scala#L7-L26

**Comment by Ichoran** [comment]
That is a pretty hairy signature.  Can it just be `Option[V] => Option[V]` or `PartialFunction[V => V]`?  I understand how this is more general, but I worry that it is general to the point of obtuseness.

**Comment by julienrf** [comment]
I can understand that this is a scary signature. The goal is to not require users to be exhaustive when they call it.

**Comment by Ichoran** [comment]
When exhaustiveness is a simple `case x => x` away, I am not sure the extra-complicated signature is worth it.

You can implement a lot of stuff in terms of `flatMap`, but we provide `filter` and `map` anyway.

**Comment by martijnhoekstra** [comment]
shouldn't it be `def updatedWith[V1](key: K)(f: PartialFunction[Option[V], Option[V1]]): Map[K, V1]`? (or a non-partial variation I'm more partial to)?

**Comment by julienrf** [comment]
@martijnhoekstra Yes, I updated the issue description with the correct type signature.

**Comment by julienrf** [comment]
Let’s keep it in collection-contrib for now.

**Comment by Ichoran** [comment]
We should still have a proper efficient `updateWith(k, f: V => V): Boolean` at least for mutable maps where slotting the new item in the same hole is vastly faster than doing two lookups.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/11185
