### ISSUE TITLE
Some types in collections still need to be made Serializable

### ISSUE THREAD

**Issue by lrytz** [scala/bug#10945]
For example `Partition` (https://github.com/scala/scala/blob/4b5694deb00a66475ccb1b096b139c8004c55c7d/src/library/scala/collection/View.scala#L146-L147)

**Comment by som-snytt** [comment]
I patched the three warnings in `View` at https://github.com/scala/scala/pull/6806/commits

**Comment by alejopa** [comment]
How can I find out which collections need to be made Serializable?

**Comment by szeiger** [comment]
`Partition` has been fixed

**Comment by szeiger** [comment]
`Partition` shouldn't have required serialization in the first place (it was only used as a temporary placeholder). Since the serialization tests are passing and there are no known missing classes I'm closing this ticket.
