### ISSUE TITLE
Re-consider where to define *InPlace in the hierarchy

### ISSUE THREAD

**Issue by lrytz** [scala/bug#10947]
Continuing the discussion from https://github.com/scala/scala/pull/6793

**Comment by lrytz** [comment]
@NthPortal  says:

> I am (in principle) open to the idea of a `maybe<Op>InPlace` family of methods that default to not being done in place, but will (best effort) be done in place if it's equally or more efficient.

This would lead to the anti-pattern of putting a mutable collection into a `var`, so I agree it's not a very nice API.

Could we could factor the `InPlace` methdos out (as abstract methods only) into a trait to mix into concrete collection types and maybe `mutable.IndexedSeqOps`? Or are the requirements different for `map/flatMap/filter/...`, so it doesn't make sense to put them together?

**Comment by NthPortal** [comment]
> This would lead to the anti-pattern of putting a mutable collection into a `var`

Good point. I was thinking more from the perspective of chaining ops (e.g. `seq.maybeSortInPlace.apply(3)`), which of course is much less common for mutable collections.

I retract my comment.

**Comment by erikerlandson** [comment]
This seems like it might be a good use case for type classes.  Define a type class `NLogNSortable`, or some such. Provide implicit conversion.

That, or `implicit class`, which would be nicer from a library user perspective.

**Comment by erikerlandson** [comment]
Just in general, making all the collections hierarchies lighter weight, and moving more functionality to `implicit class` and/or type-classes, seems like it might help resolve some thorny design conflicts that naturally arise out of trying to do things with complex hierarchies.

**Comment by NthPortal** [comment]
@erikerlandson one of the problems with using typeclasses for this is that all of the `<op>InPlace` implementations tend to require access to the private state of the class, which may not be available to the typeclass

**Comment by NthPortal** [comment]
@julienrf I don't think scala/scala#6910 fixes this. I'm still concerned about the definition of `mapInPlace` on `mutable.Seq` without a default implementation, because

- it is a non-trivial barrier to implementing your own collection
- there may not be a sensible implementation for some (any?) linear `mutable.Seq` types

In particular, looking at the default implementation of `mutable.SeqLike.transform` in 2.12 (which basically seems to have been renamed to `mapInPlace`), its default implementation is *incredibly* inefficient (O(n<sup>2</sup>)) for linear types.

```scala
  def transform(f: A => A): this.type = {
    var i = 0
    this foreach { el =>
      this(i) = f(el)
      i += 1
    }
    this
  }
```

I'm not convinced that it can be done any better than this in some cases, which means it shouldn't be defined there.

**Comment by julienrf** [comment]
That’s a good point, we should probably define it only on `mutable.IndexedSeq` (which has an efficient implementation). What do you think?

**Comment by Ichoran** [comment]
@julienrf - FYI I had been thinking the same thing but I think I forgot to express it.

**Comment by NthPortal** [comment]
... thank you for closing this when I fast-forwarded my fork to upstream, GitHub

**Comment by julienrf** [comment]
That being said, our current implementation in `ListBuffer`, `UnrolledBuffer` and `JListWrappor` are all `O(n)`. I could keep these implementations but still move the definition of `mapInPlace` from `mutable.SeqOps` to `mutable.IndexedSeqOps`, though.

**Comment by Ichoran** [comment]
I think we'd better move to `IndexedSeqOps`, then.
