### ISSUE TITLE
SortedSet/SortedMap operations do not default to the collection's Ordering

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#10942]
`SortedSet`/`SortedMap` operations do not default to the collection's `Ordering`. Instead, they will use whatever implicit `Ordering` happens to be in scope.

While it is *possible* to use the collection's `Ordering` (as demonstrated below), it is not obvious how to do it, or that it needs to be done. Additionally, it is difficult to impossible if the collection does not first get assigned to a variable.

I opine that the default behaviour ought to be to use the collection's `Ordering`, assuming it fits the resulting collection's type.

----------------

```scala
Welcome to Scala 2.13.0-20180613-212940-3cf8f79 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_171).
Type in expressions for evaluation. Or try :help.

scala> val set = SortedSet(1, 2, 3)(Ordering.Int.reverse)
set: scala.collection.immutable.SortedSet[Int] = TreeSet(3, 2, 1)

scala> set map { _ + 1 }
res4: scala.collection.immutable.SortedSet[Int] = TreeSet(2, 3, 4)

scala> set.max
res5: Int = 3

scala> set.max(set.ordering)
res8: Int = 1

scala> set.map(_ + 1)(set.ordering)
res9: scala.collection.immutable.SortedSet[Int] = TreeSet(4, 3, 2)
```

**Comment by julienrf** [comment]
This is because `map` can change the type of elements, so it has to take an implicit `Ordering` for the new type of elements.

We could try to add an overload of `map` for the case of endofunctions. (And we would have to do the same for `collect` and `flatMap`)

**Comment by NthPortal** [comment]
I don't think having operations the behave like this is possible (due to how overload resolution works), so I'm going to close it. If someone else has ideas, feel free to reopen
