### ISSUE TITLE
Check that strict operation implementations are only in `StrictOptimizedXxxOps` traits

### ISSUE THREAD

**Issue by julienrf** [scala/bug#10940]
The `XxxOps` traits (such is `IterableOps`) should be safe to extend by non-strict collection types. Therefore they should only contain view-based operation implementations. This is not currently always the case, for instance @smarter made me realized that [this override](https://github.com/scala/scala/blob/c5da7a0331e6549402253fb46053f1b0172ecac1/src/library/scala/collection/immutable/Set.scala#L48-L53) should be moved to a `StrictOptimizedSetOps` trait instead of being in `SetOps`.

**Comment by smarter** [comment]
Related: make sure that the StrictOptimizedXOps are mixed in everywhere they need to be, e.g. shouldn't BitSet extend `StrictOptimizedSortedSetOps` ?

**Comment by julienrf** [comment]
Yes. In the case of `BitSet` I’ve fixed it in scala/scala#6776
