### ISSUE TITLE
Using a Java annotation as a ClassfileAnnotation leads to problems

### ISSUE THREAD

**Issue by hrhino** [scala/bug#10958]
This one's mostly for fun, because why would you do such a thing?

```scala
hhoughton:tmp hhoughton$ scala-launch 2.12.6
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_161).
Type in expressions for evaluation. Or try :help.

scala> @Deprecated class Foo
defined class Foo

scala> val ann = classOf[Foo].getAnnotation(classOf[Deprecated])
ann: Deprecated = @java.lang.Deprecated()

scala> ann: annotation.ClassfileAnnotation
java.lang.AssertionError: assertion failed:
  Cannot emit primitive conversion from Ljava/lang/Deprecated; to Lscala/annotation/ClassfileAnnotation; - <console>
     while compiling: <console>
        during phase: jvm
```

_not_ a `ClassCastException`, as you may have thought!

I'm not sure what can be done about this; patching parents of a class to add superclasses that just aren't there at runtime is inviting runtime crashers at the very least.

**Comment by lrytz** [comment]
This is an endless source of bugs, see https://github.com/scala/bug/issues/9400. We should stop modifying java annotations (flags, parents, etc) and trying to work around the inconsistencies in later phases.

**Comment by hrhino** [comment]
ah, I think this is a duplicate of #9644, which I somehow didn't find.
