### ISSUE TITLE
[2.13.0-M4] Implement missing methods for Iterator

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10961]
* [ ] `def aggregate[B](z: ⇒ B)(seqop: (B, A) ⇒ B, combop: (B, B) ⇒ B): B`
* [ ] `def copyToArray(xs: Array[A]): Unit`
* [ ] `def corresponds[B](that: GenTraversableOnce[B])(p: (A, B) ⇒ Boolean): Boolean`
* [ ] `def hasDefiniteSize: Boolean`
* [ ] `def isTraversableAgain: Boolean`
* [ ] `def padTo(len: Int, elem: A): Iterator[A]`
* [ ] `def partition(p: (A) ⇒ Boolean): (Iterator[A], Iterator[A])`
* [ ] `def toTraversable: Traversable[A]`

**Comment by julienrf** [comment]
These operations were available in 2.12, we should add them back.

**Comment by julienrf** [comment]
Note that there is a `padTo` implementation for `Iterator` in `View.PadTo`.

**Comment by julienrf** [comment]
I’m not sure `scanRight` makes much sense in `Iterator` but we should at least provide a deprecated implementation.

**Comment by gmethvin** [comment]
I'm planning to submit a PR for this.

It looks like `toTraversable` is implemented in `IterableOnceExtensionMethods`, so it would already be usable on `Iterator`.

I agree `scanRight` doesn't make sense at all on `Iterator`. I think we should deprecate and suggest using some kind of `Iterable`, though I'm not sure how prescriptive we should be there about what to use. We could suggest a direct replacement like `ArrayBuffer.from(iterator).scanRight`.

**Comment by gmethvin** [comment]
It looks like we already have `def copyToArray[B >: A](xs: Array[B], start: Int = 0)` which would be source compatible with previous usages of `def copyToArray[B >: A](xs: Array[B]): Unit`.

**Comment by MasseGuillaume** [comment]
@gmethvin it's not source compatible: https://github.com/scala/bug/issues/10973#issuecomment-402646937

**Comment by gmethvin** [comment]
Ah, I missed that case. Thanks for the explanation. I'll remove the default parameter then and stick with the method overloading.
