### ISSUE TITLE
scan operation in Iterable should be deprecated, fold should be added (and deprecated)

### ISSUE THREAD

**Issue by julienrf** [scala/bug#10962]
These operations are equivalent to `scanLeft` and `foldLeft`, respectively, on sequential collections. Since the new collections are only sequential, I see no reason to keep those operations. The current state is that we have a non-deprecated `scan` and no `fold`. Both should be present and deprecated.

**Comment by Prithvirajbilla** [comment]
Hi, I'd like to pick this. Let me know if some one is already working on this. This will be first one for me. Thanks.

**Comment by Prithvirajbilla** [comment]
IterableOnce already has a fold method. so added deprecated annotation to it. 
https://github.com/Prithvirajbilla/scala/commit/14d96f3f66fc6257ea2a76689df0eda84d912223 This should address the issue.

**Comment by NthPortal** [comment]
@Prithvirajbilla If no one else has said here that they're working on it (and it's not assigned to anyone), you can assume no one else has started working on it, and claim it with a comment (as you have done). Thanks for picking this up!

**Comment by Prithvirajbilla** [comment]
@NthPortal thanks for telling me what the proper etiquette is.

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/7719 undid the deprecations
