### ISSUE TITLE
ListSet.toList ordering

### ISSUE THREAD

**Issue by invadergir** [scala/bug#10963]
Hi, 

I'm trying to sort out what the actual behavior of ListSet.toList should be.  The documentation for the [current 2.12 version](https://www.scala-lang.org/api/2.12.6/scala/collection/immutable/ListSet.html) says 

> Elements are stored internally in reversed insertion order, which means the newest element is at the head of the list.

I've seen different things.  What is the expected behavior?  Is the code or the documentation wrong?

In Scala 2.12.6: 
```
$ scala
Welcome to Scala 2.12.6 (OpenJDK 64-Bit Server VM, Java 1.8.0_171).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.immutable._
import scala.collection.immutable._

scala> val l = ListSet(0) + 1  + 2
l: scala.collection.immutable.ListSet[Int] = ListSet(0, 1, 2)

scala> l.toList
res0: List[Int] = List(0, 1, 2)

scala> val l2 = ListSet(0, 1, 2)
l2: scala.collection.immutable.ListSet[Int] = ListSet(0, 1, 2)

scala> l2.toList
res1: List[Int] = List(0, 1, 2)
```

For comparison, 2.11 works as the documentation would imply:
```
$ scala
Welcome to Scala 2.11.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_171).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.immutable._
import scala.collection.immutable._

scala> val l = ListSet(0) + 1  + 2
l: scala.collection.immutable.ListSet[Int] = ListSet(2, 1, 0)

scala> l.toList
res0: List[Int] = List(2, 1, 0)

scala> val l2 = ListSet(0, 1, 2)
l2: scala.collection.immutable.ListSet[Int] = ListSet(2, 1, 0)

scala> l2.toList
res1: List[Int] = List(2, 1, 0)
```

Cheers

**Comment by SethTisue** [comment]
please search the bug tracker for other issues involving `ListSet`

(and/or try it in Scala 2.13.0-M4, which has a revamped collections library)

**Comment by invadergir** [comment]
I don't think it's a duplicate of https://github.com/scala/bug/issues/10005, which I saw.  I think the docs  need updating to reflect the new behavior.  That link does answer my first question, however.

**Comment by SethTisue** [comment]
if the docs and the behavior are out of sync in 2.13.0-M4, we should have an open ticket on that.

if the docs and the behavior are out of sync in 2.12.x only, then we'd certainly welcome a 2.12.x pull request correcting that

**Comment by Jasper-M** [comment]
I think both the docs and the code are correct in sync. The docs specifically say:

> List set iterators and traversal methods visit elements in the order whey were first inserted.

Elements are indeed stored *internally* in reverse insertion order, but this only affects performance, not behavior. Perhaps you *could* say that public documentation talking about implementation details causes confusion, and they should just list the performance characteristics without explanation?
