### ISSUE TITLE
Scaladoc contains unexpanded macros

### ISSUE THREAD

**Issue by Jasper-M** [scala/bug#10969]
See for instance https://www.scala-lang.org/api/2.13.0-M4/scala/collection/IterableOnceOps.html or https://www.scala-lang.org/api/2.13.0-M4/scala/collection/immutable/List.html. It's full of `$coll` and `$willNotTerminateInf` etc. It looks like it's primarily the new collections that are affected, because e.g. the `Option` scaladoc looks ok.
Related issue: #9785

**Comment by chrisphelps** [comment]
Related: https://github.com/scala/collection-strawman/issues/510

**Comment by SethTisue** [comment]
@chrisphelps if you comment here after accepting my invite to https://github.com/orgs/scala/teams/contributors, I'll credit you with the ticket

**Comment by chrisphelps** [comment]
@SethTisue joined. Thanks!
