### ISSUE TITLE
optimize ArrayOps slice

### ISSUE THREAD

**Issue by isaacl** [scala/bug#10966]
Can we adjust ArrayOps to use `java.util.Arrays.copyOfRange`?

```scala
private[this] val ar = (1 to 100) map { _.toString } toArray

@Benchmark
def take10 = ar.take(10)

@Benchmark
def take10New = if (ar.length > 10) java.util.Arrays.copyOf(ar, 10) else ar
```

```
Benchmark      Score   Error  Units
take10        25.649 ± 0.518  ns/op
take10New      9.872 ± 0.290  ns/op
```

The discrepancy even worse when the array doesn't need to be reduced, still `25ns` for take, but only `3ns` for my custom method.

**Comment by Ichoran** [comment]
Part of the contract of `take` is that you get a new collection, so you can't shortcut it when the array is already shorter than 10.  (You can shortcut it for `ArraySeq`.)

But we should use `java.util.Arrays.copyOf` where we can.  (Keep in mind that the methods are overloaded on `Arrays`, so depending on context you may have the overhead of dispatch to the correct method.)

**Comment by isaacl** [comment]
> Part of the contract of take is that you get a new collection
I didn't see that documented. Do we have to keep that contract?

vector docs currently say, for example:
> a vector consisting only of the first n elements of this vector, or else the whole vector, if it has less than n elements.

**Comment by Ichoran** [comment]
Yes, for mutable collections you have to keep the contract that you get a fresh copy.  Otherwise whether or not modifications affect the original is unpredictable.  (The contract may be implicit, but it's true for all operations that do not explicitly work in place.)

**Comment by isaacl** [comment]
So I have this function:

```scala
def smallList[T](arr: Array[T]): List[T] =
  arr.take(n).toList
```

Is this the most efficient way to copy up to X items to a new list?

**Comment by isaacl** [comment]
> Keep in mind that the methods are overloaded on Arrays, so depending on context you may have the overhead of dispatch to the correct method.

We can probably use scala's Array.copy https://github.com/scala/scala/blob/2.13.x/src/library/scala/Array.scala#L124

**Comment by Ichoran** [comment]
@isaacl - Doubtful.  It's probably faster to
```
var l = List.empty[T]
var i = math.min(n, arr.length) - 1
while (i >= 0) { l = arr(i) :: l; i += 1 }
l
```

**Comment by Jasper-M** [comment]
I would hope that `arr.iterator.take(n).toList` is a good compromise.

**Comment by NthPortal** [comment]
or `arr.view.take(n).toList`

**Comment by isaacl** [comment]
I notice that `xs.length` almost always gets converted to ScalaRunTime.array_length, which does an instance lookup check.  In fact, even if I adjust an ArrayOps method to:

```scala
(xs: Array[_]) match {
  case x: Array[AnyRef]     => { val len = x.length;  .... }
```
the `x.length` call gets converted to `array_length`. Why is this?

**Comment by Jasper-M** [comment]
To return to the core of this issue: isn't this optimization already done in 2.13.x? https://github.com/scala/scala/blob/v2.13.0-M4/src/library/scala/collection/ArrayOps.scala#L237-L258

**Comment by isaacl** [comment]
yes, it does already use copyOfRange.  I was using this bug for general slice perf.

**Comment by isaacl** [comment]
@szeiger I wonder if we could speed up `slice`/`take`/`fold` by having a ConcreteArrayOps class which Arrays with known type can use instead of having to go through type switching at runtime.

**Comment by isaacl** [comment]
> I think that's how it used to work in 2.12.x.

Indeed. It appears that change simply never got moved to 2.13.x. I couldn't find any clear reason with git sleuthing.

**Comment by Jasper-M** [comment]
I just realized, `ArrayOps` is a value class. In 2.12 those specialized subclasses were also value classes, but that was completely useless since value classes still box when you call an inherited method on them. If you want to have. You would have to redefine all inherited members in every specialized subclass if you want to avoid the extra boxing.

**Comment by Ichoran** [comment]
@Jasper-M - Yes, that's absolutely right!  It's still probably worth doing, if someone is willing to keep it all straight.

**Comment by som-snytt** [comment]
The linked ticket is closed and this ticket is speculative.
