### ISSUE TITLE
Buffer misses appendAll and append

### ISSUE THREAD

**Issue by julienrf** [scala/bug#10970]
In 2.12, `Buffer` has `append` and `appendAll`. These methods do not exist in 2.13. `Buffer` does have `append` but its type signature is different. We should match the previous type signatures and deprecate them in favor of `addAll`.

**Comment by Prithvirajbilla** [comment]
I'd like to pick this up. thanks.

**Comment by julienrf** [comment]
Thank *you*, go ahead!

**Comment by julienrf** [comment]
After thinking more about this one I think it’s fine to have `append` and `appendAll` (non-deprecated) in `Buffer`, for symmetry with `prepend` and `prependAll`.

So, we should do the following:

- add `append` and `appendAll`, and make `addOne` and `addAll` final aliases to these methods,
- add deprecated variadic versions of `append` and `prepend`. We should suggest users to use `appendAll` and `prependAll` instead. We could also add variadic overloads of `appendAll` and `prependAll`.
