### ISSUE TITLE
[2.13.0-M4] missing classes in collection.generic

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10978]
```
    (removed)
      Sizing
      SliceInterval

    (moved to scala.collection.mutable)
      Clearable
      Subtractable
      Growable
      Shrinkable
```

**Comment by julienrf** [comment]
I think we should just document that `Sizing` and `SliceInterval` do not exist anymore.

For those that have been moved to the `collection.mutable` package, my opinion is that that package suits them better, so I would just add deprecated aliases to them.

**Comment by Prithvirajbilla** [comment]
There is no `Subtractable` class  in scala.collection.mutable

And also can some one give me pointers for which file to edit to document  that `Sizing` and `SliceInterval` do not exist anymore.

**Comment by MasseGuillaume** [comment]
https://static.javadoc.io/org.scala-lang/scala-library/2.12.6/scala/collection/generic/Subtractable.html

It looks like Subtractable is now implemented correctly in `SetOps`, `MapOps`, etc. We should keep it for compatibility in generic.

**Comment by julienrf** [comment]
We could add `Subtractable` back (without using it) and deprecate it, indeed.
