### ISSUE TITLE
[2.13.0-M4] avoid using default parameters

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10973]
Some operations like SeqOps now uses default parameter. This is a breaking change if you use eta-expension.

before

```scala
def indexOf[B >: A](elem: B): Int
def indexOf[B >: A](elem: B, from: Int): Int
```

now

```scala
def indexOf[B >: A](elem: B, from: Int = 0): Int
```

```scala
class Example {
  def scala212(a: Int): Int = a
  def scala212(a: Int, b: Int): Int = 1

  def scala213(a: Int, b: Int = 1): Int = a

  def useSite(f: Int => Int): Int = f(42)

  useSite(scala212 _)
// Ok


  useSite(scala213 _)
// found   : (Int, Int) => Int
// required: Int => Int
//         useSite(scala213 _)
//                 ^

}
```

This apply to at least:

SeqOps
* [ ] `indexOf`
* [ ] `indexOfSlice`
* [ ] `indexWhere`
* [ ] `lastIndexOf`
* [ ] `lastIndexOfSlice`
* [ ] `lastIndexWhere`

**Comment by lrytz** [comment]
i think this is a breaking change we're willing to accept, so a documentation issue.

**Comment by MasseGuillaume** [comment]
If you add another default parameter (in future) you break the code at call site once again.

```scala
class Example2 {
  // lib
  def indexOf(a: Int, b: Int = 0, c: Int = 0): Unit = println("scala214")

  // user
  def callSite(f: (Int, Int) => Unit): Unit = f(42, 0)
  callSite(indexOf _)
//type mismatch;
//        found   : (Int, Int, Int) => Unit
//        required: (Int, Int) => Unit

}
new Example
```

If you add another method, it's compatible:

```scala
class Example1 {
  // lib
  def indexOf(a: Int): Unit = println("scala212")
  def indexOf(a: Int, b: Int): Unit = println("scala213")
  def indexOf(a: Int, b: Int, c: Int): Unit = println("scala214")
  
  // user
  def callSite(f: (Int, Int) => Unit): Unit = f(42, 0)
  callSite(indexOf _)
}
new Example1
```

**Comment by olafurpg** [comment]
This breaking change can be avoided with minimal effort and the 2.12 design has the benefit of playing nicer with eta expansion. By keeping the old design you also avoid the need to document the breaking change altogether. I think it would be great to preserve the 2.12 API.

**Comment by MasseGuillaume** [comment]
another breaking pattern found in Akka:

```scala
trait Scala212 {
  def m(a: Int): Unit = println("m1")
  def m(a: Int, b: Int): Unit = println("m2")
  def m(a: Int, b: Int, c: Int): Unit = println("m3")
}

trait Scala212Usage extends Scala212 {
  override def m(a: Int): Unit = println("override m1")
  override def m(a: Int, b: Int): Unit = println("override m2")
  override def m(a: Int, b: Int, c: Int): Unit = println("override m3") 
}


trait Scala213 {
  def m(a: Int, b: Int = 0, c: Int = 0): Unit = ()
}

trait Scala213Usage extends Scala213 {
  override def m(a: Int): Unit = println("override m1")
  override def m(a: Int, b: Int): Unit = println("override m2")
// error: method m overrides nothing
//         override def m(a: Int): Unit = println("override m1")
//                      ^
  override def m(a: Int, b: Int, c: Int): Unit = println("override m3") 
// error: method m overrides nothing
//         override def m(a: Int, b: Int): Unit = println("override m2")
//                      ^
}
```

**Comment by MasseGuillaume** [comment]
Here is annother one:

https://github.com/akka/akka/blob/59040fadadacda5354e0af73a44237096ab23774/akka-actor/src/main/scala/akka/util/ByteIterator.scala#L446-L448

```
missing parameter type for expanded function ((x$27: <error>) => x$27.$eq$eq(elem))
missing parameter type for expanded function ((x$28: <error>) => x$28.$eq$eq(elem))
```


```scala
trait Buffer[+A] {
  def indexOf[B >: A](elem: B, from: Int = 0): Int = 42
  def indexWhere(p: (A) ⇒ Boolean, from: Int = 0): Int = 42
}

abstract class ByteIterator extends Buffer[Byte] {
  override def indexWhere(p: Byte ⇒ Boolean): Int = 1
  def indexOf(elem: Byte): Int = indexWhere { _ == elem }
  override def indexOf[B >: Byte](elem: B): Int = indexWhere { _ == elem }
}
```

**Comment by szeiger** [comment]
Should be easy enough to avoid by going back to the overloaded methods. In the long term it would be nicer if we could make eta-expansion smarter to deal with default parameters automatically.

**Comment by szeiger** [comment]
Unfortunately cases such as https://github.com/scala/bug/issues/10973#issuecomment-404166638 were enabled by not making all but the most flexible implementation of a method `final`. Overriding of methods with default parameters in general is a bit awkward because you have to repeat all parameters with the same default values.

I'm less concerned about the call sites. Instead of eta-expanding you can always write the lambda manually, thus avoiding the need to deal with any of the default values. This is also resilient against future changes to the defaults or the number of parameters.
