### ISSUE TITLE
[2.13.0-M4] missing method Searching.SearchImpl.search

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10977]

**Comment by julienrf** [comment]
It is [here](https://static.javadoc.io/org.scala-lang/scala-library/2.13.0-M4/scala/collection/Searching$.html#search[Repr,A](coll:Repr)(implicitfr:scala.collection.generic.IsSeqLike[Repr]):scala.collection.Searching.SearchImpl[Repr,fr.A]). Or is it somehow incompatible?
