### ISSUE TITLE
[2.13.0-M4] Renaming parameters

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10971]
Some parameter renames make sense:

`ArraySeq.update`: idx => index

Some renames are inconsistent:

`ArrayBuffer.remove`: `n => idx` (should be `index` to be consistent with above)

Some renames are worst:

`ArrayBuffer`: `initialSize => initSize`
`SortedMapFactory.apply`: `ord` => `arg0` (this is one is at least consistent with `EvidenceIterableFactory`)

Let's try to be consistent. We should also use `@deprecatedName('oldName)` if there is a clear improvement.

**Comment by julienrf** [comment]
To clarify on the actions that should be done: we should always use the same names as in 2.12, except when the new names are clearer. In such cases, we should add the `@deprecatedName('oldName)` annotation to not break the source compatibility.

**Comment by MasseGuillaume** [comment]
related: https://github.com/scala/bug/issues/10991

**Comment by Prithvirajbilla** [comment]
I'd like to pick this up. thanks

**Comment by Prithvirajbilla** [comment]
> SortedMapFactory.apply: ord => arg0 (this is one is at least consistent with EvidenceIterableFactory)

I couldn't find this rename in SortedMapFactory(https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/Factory.scala#L661)

**Comment by MasseGuillaume** [comment]
@Prithvirajbilla the compiler will desugar

```scala
def apply[K : Ordering, V](elems: (K, V)*): CC[K, V] = from(elems)
```

into

```scala
def apply[K, V](elems: (K, V)*)(implicit arg0: Ordering[K]): CC[K, V] = from(elems)
```

you can write the following

```scala
def apply[K, V](elems: (K, V)*)(implicit ordering: Ordering[K]): CC[K, V] = from(elems)
```

**Comment by Prithvirajbilla** [comment]
okay. thanks. 

What do you recommend that we do here? 

Is it changing the `apply` function on SortedMapFactory back to have an implicit parameter as argument  and also change the `EvidenceIterableFactory` to also have an implicit parameter as argument. (for consistency)

Also note that we can't use `@deprecatedName` for implicit parameters.

**Comment by MasseGuillaume** [comment]
> What do you recommend that we do here?

seems like `EvidenceIterableFactory` is for `ClassTag` and `Ordering`. It's not worth to keep the old name since you would need to duplicate some code to keep the parameter name.

> Also note that we can't use @deprecatedName for implicit parameters.

seems to work there (Scala 2.12.4)

```scala
scala> def f(@deprecatedName('aa) a: Int)(implicit @deprecatedName('bb) b: Int): Int = b
f: (a: Int)(implicit b: Int)Int

scala> f(aa = 1)(bb = 2)
<console>:13: warning: the parameter name aa is deprecated: use a instead
       f(aa = 1)(bb = 2)
            ^
<console>:13: warning: the parameter name bb is deprecated: use b instead
       f(aa = 1)(bb = 2)
                    ^
res0: Int = 2

```

**Comment by Prithvirajbilla** [comment]
regarding the @deprecatedName for implicit parameters. It works. My bad. sorry.

I guess it is just my Intellij showing red in this case. 

Thanks.
