### ISSUE TITLE
[2.13.0-M4] missing method canEqual

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10976]
from `IterableLike`

**Comment by julienrf** [comment]
Indeed this is a breaking change that we should document: equality is not anymore defined at the level of `Iterable`, but it is defined in each branch: `Set`, `Map`, `Seq`.

**Comment by julienrf** [comment]
I’ve added a point about that in the FAQ: https://github.com/scala/collection-strawman/wiki/FAQ#what-are-the-breaking-changes
