### ISSUE TITLE
util.control.Breaks / break() appears to allow breaking outside breakable{} scope

### ISSUE THREAD

**Issue by PeterAJansen** [scala/bug#10983]
Hi there,

I tracked down a bug today in some code that ended up being an errant break() in a function X without a breakable {} structure, but that was called by function Y with a breakable structure -- and the break in X was breaking out of the breakable {} in Y, beyond it's scope.  

Below is a distilled example -- I would expect the break() in check() to throw an error for being outside a breakable {} scope, or to break out of (i.e. return from) the check() function, but it successfully compiles and breaks out of the breakable{} in the count() function.

It's possible that this is known or even planned behavior, but if so that seems unusual to me. 

```
import scala.util.control.Breaks._

object bugtest {

  def count(num:Int): Unit = {
    breakable {
      for (i <- 0 until num) {
        println("num: " + i)
        check(i)
      }
    }
  }

  def check(num:Int): Unit = {
    if (num >= 5) {
      println ("breaking...")
      break()     //## Break outside of a breakable {}
    }
  }

  def main(args:Array[String]): Unit = {
    count(10)
  }
  
}

```
Output: 

```
num: 0
num: 1
num: 2
num: 3
num: 4
num: 5
breaking...
```

My expectations are that this would either: 
- Not compile, or
- return from the check() function, and have the loop in count() continue iterating until it hits 10. 

thanks,
Peter

**Comment by martijnhoekstra** [comment]
Thanks for the report.

The doc at https://www.scala-lang.org/api/current/scala/util/control/Breaks$.html#break():Nothing doesn't give me any reason to think your expectations should hold. I can't see anything directly actionable here, so I'm closing this report.

Further discussion about the (desired) semantics of the break method could go on https://users.scala-lang.org or https://contributors.scala-lang.org

**Comment by SethTisue** [comment]
improvements to the Scaladoc in this area would be welcome
