### ISSUE TITLE
[2.13.0-M4] missing method on Array

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10985]
```scala
def deep(): collection.IndexedSeq[Any]
```

**Comment by julienrf** [comment]
@lrytz Do you know if there was a reason to not have it in `Array` anymore? I see that you added it to partest tools only.

**Comment by lrytz** [comment]
It's a hacky ugly testing utility to print values in (nested) arrays. If you feel strongly about it, we can add it deprecated.

**Comment by MasseGuillaume** [comment]
Yes I think we should leave it: https://github.com/scalatest/scalatest/pull/1383
