### ISSUE TITLE
[2.13.0-M4] missing method on mutable.HashMap

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10988]
```scala
def mapResult[NewTo](f: (HashMap[A, B]) ⇒ NewTo): Builder[(A, B), NewTo]
```

**Comment by julienrf** [comment]
This is because `mutable.HashMap` is not anymore a `Builder` of itself. Also, the `result()` method is missing.

Should we make `mutable.HashMap` a builder of itself again?

**Comment by julienrf** [comment]
You can see how this has been done in `ArrayBuffer`

**Comment by szeiger** [comment]
`s.c.m.SetLike` and `s.c.m.MapLike` used to extend `Builder` in 2.12.x. We should probably keep it this way.
