### ISSUE TITLE
[2.13.0-M4] missing method on mutable.PriorityQueue

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10989]
```scala
def orderedCompanion: PriorityQueue.type
```

**Comment by julienrf** [comment]
BTW, I just noticed that we forgot to override the `iterableFactory` member. We should override it to return `PriorityQueue` (the companion object), remove the overrides of `fromSpecificIterable` and `newSpecificBuilder`, and finally add a deprecated `orderedCompanion` alias to `iterableFactory`.

**Comment by gmethvin** [comment]
@julienrf That won't quite work, because the `PriorityQueue` companion is not an `IterableFactory` but a `SortedIterableFactory`. We could do something similar to `TreeSet` and add a `sortedIterableFactory` method though.

**Comment by julienrf** [comment]
Good point. Let’s forget about my previous comment then and just add a deprecated `orderedCompanion` that aliases to `PriorityQueue`.

**Comment by gmethvin** [comment]
OK I'll submit a PR to add the method. It looks like the only place we need to add it is in `PriorityQueue` since no other collections used `GenericOrderedTraversableTemplate`.
