### ISSUE TITLE
[2.13.0-M4] missing method on immutable.TreeMap

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10980]
`def compare(k0: A, k1: A): Int`

**Comment by julienrf** [comment]
I don’t know if it’s worth keeping non-deprecated, the implementation simply delegates to `ordering.compare`.

**Comment by julienrf** [comment]
If we add it, it should be added to `SortedOps` so that it is also available to `TreeSet` (as in 2.12).
