### ISSUE TITLE
[2.13.0-M4] missing classes on scala.collection.mutable

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10987]
* [ ] `ArrayStack`
* [ ] `FlatHashTable`
* [ ] `HashTable` (now private, implementation details)
* [ ] `History`
* [ ] `LazyBuilder`
* [ ] `LinearSeq`
* [ ] `LinkedEntry` (removed, Class for the linked hash map entry, used internally.)
* [ ] `MapBuilder`
* [ ] `MutableList`
* [ ] `Publisher`
* [ ] `ResizableArray`
* [ ] `RevertibleHistory`
* [ ] `SetBuilder`
* [ ] `StackBuilder`
* [ ] `Subscriber`
* [ ] `Undoable`
* [ ] `WrappedArray`
* [ ] `WrappedArrayBuilder`

**Comment by julienrf** [comment]
I think we should just document that in the FAQ (for now).

**Comment by julienrf** [comment]
I’ve added this list of unsupported types to the FAQ: https://github.com/scala/collection-strawman/wiki/FAQ#what-are-the-breaking-changes

I suggest to close this issue for now. We can see later if we should invest in a better compatibility layer for these removed classes.

**Comment by erikerlandson** [comment]
I am running into lack of `MapBuilder` on https://github.com/non/spire/pull/759

**Comment by SethTisue** [comment]
> I am running into lack of `MapBuilder` on [non/spire#759](https://github.com/non/spire/pull/759)

`Map.newBuilder` should cross-compile. (but perhaps you're in some special situation?)
