### ISSUE TITLE
[2.13.0-M4] missing method on SetOps, MapOps

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10984]
missing methods from SetLike

```scala
def +(elem1: Int, elem2: Int, elems: Int*): This
def -(elem1: Int, elem2: Int, elems: Int*): This

Set(1) + (1, 2)
Set(1) - (1, 2)
```
missing methods from MapLike

```scala
def +[B1 >: B](elem1: (A, B1), elem2: (A, B1), elems: (A, B1)*): This
def -(elem1: Int, elem2: Int, elems: Int*): This

Map(1 -> 2) + (3 -> 4, 5 -> 6)
Map(1 -> 2) - (1, 3, 4)
```

**Comment by julienrf** [comment]
These [methods](https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/Set.scala#L164-L165) [are](https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/Set.scala#L185-L186) [all](https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/Map.scala#L54-L55) [available](https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/Map.scala#L294-L295).

**Comment by MasseGuillaume** [comment]
Maybe it's a bug in the repl ?

```scala
Set(1, 1) + (1, 2)
                       ^
       error: too many arguments (2) for method +: (elem: Int)scala.collection.immutable.Set[Int]
```

**Comment by MasseGuillaume** [comment]
Sorry I tested this on 2.13.0-M4, not master.
