### ISSUE TITLE
Scaladoc: add protected to visibility

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10999]
In the filtered search there are only two options for visibility: Public, All.

I think we should have

* Public
* Protected
* Private
* All / None

Public, Protected, Private should toggle (on/off)

All, None should clear the above

**Comment by som-snytt** [comment]
Relatedly, https://github.com/scala/bug/issues/3807

**Comment by Prithvirajbilla** [comment]
This looks interesting. I'd like to take a look at this.

 I agree with option for visibility of `Protected` functions. 

But don't think option for visibility of `private ` functions is useful, given we can't use those private functions. I can't think of a good purpose for them.

**Comment by som-snytt** [comment]
My Java friend (I have one friend, and he happens to use only Java and only Eclipse) doesn't download javadoc. He only hovers in the IDE to view it. I don't understand that behavior.

I always download Javadoc and Scaladoc; it is a separate representation, for me, from what any IDE might report. It is the golden representation. I have a jetty that serves various docs including java and scaladoc.

My idea was that Scaladoc should show doc for all the locals and privates just as if they were lifted to an enclosing scope. Why not? I want to know how they work, and if there's any doc that offers further explanatory notes. Obviously doc on privates has a shorter life span than public API as such. I just want a nice way to view comments that my predecessors have left behind like bread crumbs.

This is so obvious to me.

OTOH, my Java friend doesn't even use Javadoc as such. So maybe we're barking up the wrong tree so to speak, and doc comments on trees is a waste of time.

**Comment by MasseGuillaume** [comment]
@som-snytt I don't use an IDE but I use scaladoc every day. I use javadoc.io to fetch what I want: https://javadoc.io/doc/com.typesafe.akka/akka-http_2.12/10.1.3

There is also [dash](https://kapeli.com/dash) to aggregate documentation.

**Comment by SethTisue** [comment]
there is also now skepticism at https://github.com/scala/scala/pull/8183 about whether including private members is desirable

**Comment by som-snytt** [comment]
Someone [noticed](https://github.com/scala/docs.scala-lang/issues/1627) that `stringPrefix` isn't in the scaladoc any more. Since implementing a custom collection is easy now, probably we need to be aware of it and its replacement.
