### ISSUE TITLE
[2.13.0-M4]  scala.sys.process.ProcessBuilder scaladocs refers to deprecated method lineStream

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10993]
https://static.javadoc.io/org.scala-lang/scala-library/2.13.0-M4/scala/sys/process/ProcessBuilder.html

we should replace all occurrences of `*Stream` to `lazy*`

**Comment by julienrf** [comment]
I think this has been fixed in https://github.com/scala/scala/commit/b504fe4c40a5857cf8fe6b7c4aba778c4a4e0ae6
