### ISSUE TITLE
Set Intersect (&) not "left sided"

### ISSUE THREAD

**Issue by INRIX-Cory-Bradshaw** [scala/bug#10997]
When using sets to find the intersection between case classes with two parenthesis the results are not the items from the left operand found in the right operand, but a mix. The test below creates two sets looking for diffs/intersects based on the first parameter list (a Long). Each set has items with the same second parameter set to make spotting where the returned items came from easier.

Result:
Intersect returns items mixed from both left and right side operands, whereas a more correct result can be obtained from using a mix of filter/contains to enforce that all objects are gotten from a single (known) set.

### Example Case class for this test:

    case class IdWithFrcAndLength(persistId: Long)(val frc: Int, val length:Double, val id:Long)

### Test setup:
    val id1=Set(IdWithFrcAndLength(1)(2,3.0,4),
      IdWithFrcAndLength(2)(2,3.0,4),
      IdWithFrcAndLength(3)(2,3.0,4),
      IdWithFrcAndLength(4)(2,3.0,4),
      IdWithFrcAndLength(5)(2,3.0,4))
    val id2=Set(IdWithFrcAndLength(1)(3,54.0,5),
      IdWithFrcAndLength(2)(3,54.0,5),
      IdWithFrcAndLength(3)(3,54.0,5),
      IdWithFrcAndLength(6)(3,54.0,5),
      IdWithFrcAndLength(7)(3,54.0,5),
      IdWithFrcAndLength(8)(3,54.0,5))

### Testing Diffs (this works fine)

    test("Verify Set Diff") {

      val diff = id1--id2
      val diff2 = id2--id1

      assert(diff.size===2)
      assert(diff2.size===3)
      //Neither diff should have 1,2,3, as they are common
      assert(!diff.exists(_.persistId===1))
      assert(!diff.exists(_.persistId===2))
      assert(!diff.exists(_.persistId===3))
      assert(!diff2.exists(_.persistId===1))
      assert(!diff2.exists(_.persistId===2))
      assert(!diff2.exists(_.persistId===3))

      assert(diff.exists(_.persistId===4))
      assert(diff.exists(_.persistId===5))

      assert(diff2.exists(_.persistId===6))
      assert(diff2.exists(_.persistId===7))
      assert(diff2.exists(_.persistId===8))

      //Verify the Diffs collect from the left side
      assert(diff.forall(_.id===4))
      assert(diff2.forall(_.id===5))
    }

### Testing Intersection (this fails)
    test("Verify Set Intersection"){
      val intersect = id1 & id2
      assert(intersect.size==3)
      assert(intersect.exists(_.persistId===1))
      assert(intersect.exists(_.persistId===2))
      assert(intersect.exists(_.persistId===3))

      //Verify if we are collecting from the left or right.
      assert(intersect.head.id===4)
      assert(intersect.forall(_.id==4))
    }

### Testing Filter/contains (this gives what i would expect intersection to return)
    test("Verify Set Intersection"){
      val intersect = id1 & id2
      assert(intersect.size==3)
      assert(intersect.exists(_.persistId===1))
      assert(intersect.exists(_.persistId===2))
      assert(intersect.exists(_.persistId===3))

      //Verify if we are collecting from the left or right.
      assert(intersect.head.id===4)
      assert(intersect.forall(_.id==4))
    }

**Comment by som-snytt** [comment]
You're asking for `xs & ys` to work the same as `xs filter ys`. Why not just use `filter`?

**Comment by INRIX-Cory-Bradshaw** [comment]
I ended up using filter, but this seemed like an inconsistency with the set operations (hence opening the ticket), as the other operations seem to return items from the left operand. I am wondering if this behavior between scala versions, only because we had comments in the code mentioning keeping a specific set on the left of the operator so its items get returned, but this could have also been a bad assumption by the original developer.

**Comment by som-snytt** [comment]
Your example gives the result you expect in 2.13. In 2.12, `intersect` is defined as `filter`, but overridden in `HashSet` with comments suggesting the behavior is intended:
```
          // the other set
          // We do this check first since even if the result is of size 1 since
          // it is preferable to return the existing set for better structural sharing
          that

        // when that is a leaf, we can switch to the simpler Tree/Leaf implementation
        // it is OK to swap the arguments because intersect is symmetric
        // (we can't do this in case of diff, which is not symmetric)
```
I'm not a doctor or a lawyer or a collections expert, but I play one on tv.

**Comment by INRIX-Cory-Bradshaw** [comment]
Interesting, I'm not sure what the underlying set implementation is being used. I am taking a Java collection .asScala.map(transform).toSet . I am using scala 2.12.2.

This can be closed if this is a known behavior, I just thought it was at odds with the other behaviors seen in the set operations. (I guess symmetric operations is the term I am looking to describe what I was expecting)

**Comment by som-snytt** [comment]
I also noticed that the behavior changes for `set.par`, and that the overview doc doesn't seem to mention . Probably commutativity is assumed. But there are other cases where equality is defined one way but folks want one element to be preferred over another that is equal to it. Then the useful question is, why do you prefer that element, if they are otherwise equal?
