### ISSUE TITLE
[2.13.0-M4] missing method on mutable.SortedMap

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#10990]
```scala
def updated[B1 >: B](key: A, value: B1): SortedMap[A, B1]
```

**Comment by julienrf** [comment]
Indeed, and `mutable.Map` doesn’t have it either. It’s reported [here](https://github.com/scala/collection-strawman/wiki/FAQ#what-are-the-breaking-changes) but we should provide a deprecated implementation (in `mutable.MapOps`).

**Comment by szeiger** [comment]
Only the special cases `AnyRefMap` and `LongMap` have these methods at the moment.
