### ISSUE TITLE
[2.13.0-M4] missing methods newBuilder from HasNewBuilder

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#11000]
```scala
protected[this] def newBuilder: Builder[A, Repr]
```

**Comment by julienrf** [comment]
I think we don’t have this `HasNewBuilder` trait anymore, right?

**Comment by MasseGuillaume** [comment]
@julienrf correct, in 2.12 if you extend let's say `collection.Seq` you would get `newBuilder`.

https://static.javadoc.io/org.scala-lang/scala-library/2.12.6/scala/collection/Seq.html

select all in the visibility

**Comment by julienrf** [comment]
I think you can implement it as follows (in `IterableOps`, `ArrayOps` and `StringOps`):

~~~ scala
@deprecated("Use newSpecificBuilder instead", "2.13.0")
@deprecatedOverriding("Override newSpecificBuilder instead", "2.13.0")
@inline protected[this] def newBuilder: Builder[A, C] = newSpecificBuilder
~~~

**Comment by MasseGuillaume** [comment]
`StringOps` is` final`, it's not necessary anymore since we don't have `StringLike`. ibid for ArrayOps.

**Comment by szeiger** [comment]
Closing because there doesn't appear to be a useful way forward (see discussion on https://github.com/scala/scala-dev/issues/532)
