### ISSUE TITLE
[2.13.0-M4] new method mutable.Set.get not so useful

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#11001]
[`mutable.SetOps.get`](https://static.javadoc.io/org.scala-lang/scala-library/2.13.0-M4/scala/collection/mutable/SetOps.html#get(elem:A):Option[A])

```scala
def get(elem: A): Option[A]
```
I don't think this method  should be added. At least not abstract, since it can be defined as

```scala
def get(elem: A): Option[A] = if (contains(elem)) Some(elem) else None
```

It's not consistent with the [`immutable.SetOps`](https://static.javadoc.io/org.scala-lang/scala-library/2.13.0-M4/scala/collection/immutable/SetOps.html)

**Comment by gmethvin** [comment]
`get` is documented to return a *reference to the contained element* equal to `elem`, so it would not be sufficient to return the argument.

The question is whether it is sufficiently useful to have a method that works like that. I can think of ways someone might use a reference to the contained element, but they all involve doing unusual things with `equals` and/or mutating data structures inside the set.

There is also a comment from @szeiger about this on `JSetWrapper`:

```scala
//TODO Should Set.get be supported? There is no efficient way to return the canonical element from a Java Set
def get(elem: A): Option[A] = if(underlying.contains(elem)) Some(elem) else None
```

I think we should remove the method.
