### ISSUE TITLE
[2.13.0-M4] WrappedArray make has a different signature in ArraySeq

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#11007]
2.12

[`def make[T](x: AnyRef): WrappedArray[T]`](https://static.javadoc.io/org.scala-lang/scala-library/2.12.6/scala/collection/mutable/WrappedArray$.html#make[T](x:AnyRef):scala.collection.mutable.WrappedArray[T])

2.13

[`def make[T](x: Array[T]): ArraySeq[T]`](https://static.javadoc.io/org.scala-lang/scala-library/2.13.0-M4/scala/collection/mutable/ArraySeq$.html#make[T](x:Array[T]):scala.collection.mutable.ArraySeq[T])

**Comment by lrytz** [comment]
WrappedArray was renamed to ArraySeq in 2.13, so I think this is an intended change.

**Comment by MasseGuillaume** [comment]
@lrytz correct there is a depreciation method for this scala.colletion.mutable package object.

```
@deprecated("Use ArraySeq instead of WrappedArray; it can represent both, boxed and unboxed arrays", "2.13.0")
type WrappedArray[X] = ArraySeq[X]
```

However since the signature is different, this is not an exact replacement. You cannot use `ArraySeq` instead of `WrappedArray`. We should deprecate the 2.12 signature and find a different name for the 2.13 signature.

**Comment by julienrf** [comment]
@MasseGuillaume Although the signature says `AnyRef`, the method was actually defined only on Arrays, so there should be no breakage at use site.

**Comment by MasseGuillaume** [comment]
counter example: https://github.com/scala/scala/blob/cf4fb702b17d4b9e9784e5660bc14e708c136f60/src/library/scala/collection/mutable/ArrayLike.scala#L39-L46

**Comment by julienrf** [comment]
@MasseGuillaume Do you think we can close this issue?
