### ISSUE TITLE
A method for automatic resource management should be included in stdlib

### ISSUE THREAD

**Issue by kmizu** [scala/bug#11003]
In Java (7 or later), the following code, closing `br` after `try` statement is executed, is legal:

```java
try (BufferedReader br = new BufferedReader(new FileReader(path))) {
    return br.readLine();
}
```

Also in Scala. since such an expression is very useful, many Scala programmers reinvent their own expressions such as:

```scala
def using[A <: { def close() }, B](resource: A)(block: A => B): B = try {
  block(resource)
} finally {
  resource.close()
}
using(new BufferedReader(new FileReader(path))){br =>
  br.readLine()
}
```

I think that such a method should be included in stdlib (e.g. `scala.io`) to avoid code duplication.

**Comment by NthPortal** [comment]
try-with-resources is actually more complicated than that. I believe it is basically equivalent to

```scala
def tryWithResources[A <: java.lang.AutoCloseable](resource: A)(body: A => B): B = {
  try {
    val res = body(resource)
    resource.close()
    res
  } catch {
    case e: Exception =>
      try resource.close()
      catch {
        case other: Exception =>
          e.addSuppressed(other)
          throw e
      }
  }
}
```

I don't know off the top of my head what it does for multiple resources, but I imagine it's even more complicated.

**Comment by Ichoran** [comment]
@NthPortal - This complication is exactly why it should be provided.  Everyone needs it, approximately, but it's kind of tricky to get right.  (FWIW I wouldn't use quite the implementation you gave, but the point that you need to handle exceptions in many different places is a good one.)

**Comment by NthPortal** [comment]
@Ichoran I wouldn't use that implementation either - I'd probably take into account `scala.util.control.NonFatal`. However, as best I can tell, the implementation I gave is what Java compiles/desugars a `try`-with-resources (with a single resource) to.

**Comment by ritschwumm** [comment]
i've implemented this a couple of times now, i think it should go into the standard library. preferrably with a typeclass instead of using AutoCloseable, though: there's quite a few resources in java.* that do not implement Autclosable or Closable but still would profit from this construct

**Comment by gmethvin** [comment]
I agree, this seems like a missing feature in Scala. If we add this it should probably be typeclass-based. It would also be nice to have a convenient syntax for handling multiple resources.

**Comment by NthPortal** [comment]
@ritschwumm good idea. with an implicit declared in scope automatically for `AutoClosable`.

I might take a look at this

**Comment by NthPortal** [comment]
relevant: scala/scala#6347

**Comment by NthPortal** [comment]
I went with `Resource`, but I'm open to bikeshedding

**Comment by NthPortal** [comment]
> It would also be nice to have a convenient syntax for handling multiple resources.

@gmethvin I think you will probably have to live with nesting (which isn't too much more verbose than Java's `try`-with-resources)

**Comment by SethTisue** [comment]
feedback/review on scala/scala#6907 is welcome
