### ISSUE TITLE
[2.13.0-M4] length made final without deprecatedOverride

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#11014]
We should add a `@deprecatedOverride` first then mark them as final (in 2.14).

```scala
def length: Int
```

* [ ] `collection.Iterator`

**Comment by som-snytt** [comment]
Required on sealed classes?

TIL `Iterator.length`.

**Comment by Prithvirajbilla** [comment]
`length` method in  concurrent.duration.InfiniteDuration is marked as `final`. https://github.com/scala/scala/blob/2.13.x/src/library/scala/concurrent/duration/Duration.scala#L214 But I wouldn't drop `final` for this one.

**Comment by NthPortal** [comment]
why does `lengthCompare` need to be final? I would think that it specifically *shouldn't* be final, so that you can overload it for optimisation

**Comment by julienrf** [comment]
`lengthCompare` is `final` on the `List` override only. This is not a problem because `List` is `sealed` (and also was in 2.12, so there is no breakage here). I’ve updated the PR description.

**Comment by julienrf** [comment]
The problem with making it *only* `@deprecatedOverriding` is that this may lead to inconsistent definitions for `length` and `size`.

My preference is to keep it `final`: this would ensure that collection implementations are correct, although this can break existing collection implementations that used to override it.

**Comment by julienrf** [comment]
After reading again the issue description I think it was mostly wrong: it’s fine to have a `final` `length` on `List` and `Range` because these are `sealed` types. The only remaining case is on `Iterator`, where `length` is defined as an alias to `size` and it makes sense to keep it `final` for the reason I explained in my previous comment. Therefore I think we can safely close that issue. Sorry @Prithvirajbilla for the time you spent on it…

**Comment by MasseGuillaume** [comment]
@julienrf We should reopen this issue for `Iterator`. The `@deprecatedOverriding` should mention the concern about size and length.

https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/util/ByteIterator.scala#L42

**Comment by sjrd** [comment]
Deprecations must only be used when the previous meaning can be preserved, although it is not recommended anymore. If overriding `length` does not change `size` as well anymore, then we are not preserving the previous meaning of overriding `length`. That means that a deprecation is not strong enough. It must be a hard compile error.

**Comment by sjrd** [comment]
You have to anyway, because you have to override `size` in 2.13 to preserve the correct behavior.
