### ISSUE TITLE
[2.13.0-M4] stringPrefix should not be final (yet)

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#11011]
Let's add a `@deprecatedOverriding` first.

```scala
def className: String = ...
@deprecatedOverriding("override className instead", "2.13.0")
@`inline` def stringPrefix: String = className
```

**Comment by Prithvirajbilla** [comment]
I'd like to pick this up.  Thanks.

**Comment by Prithvirajbilla** [comment]
Are you referring to `stringPrefix` method in `scala.collection.Set`?  or something else.  clarification need.  Thanks

**Comment by SethTisue** [comment]
it's on `Iterable`, and then gets overridden in `Set` and other collections

**Comment by MasseGuillaume** [comment]
Yep, this is fixed on the latest branch, thanks.

**Comment by SethTisue** [comment]
@Prithvirajbilla thanks for investigating!
