### ISSUE TITLE
@deprecated on the constructor of an annotation class does not result in any warning when using the annotation

### ISSUE THREAD

**Issue by smarter** [scala/bug#11012]
The warning does appear when instantiating the annotation class by hand using `new`:
```scala
scala> @deprecated("class", "") class Foo @deprecated("constructor", "") extends scala.annotation.StaticAnnotation
defined class Foo

scala> new Foo
       ^
       warning: constructor Foo in class Foo is deprecated: constructor
           ^
       warning: class Foo is deprecated: class
res0: Foo = Foo@3b95a6db

scala> @Foo class Bar
                  ^
       warning: class Foo is deprecated: class
defined class Bar
```

**Comment by SethTisue** [comment]
(potential "good first issue", that is, for someone wanting to get into the compiler code a little)

**Comment by som-snytt** [comment]
This would have been a good first issue, but I've been jonesing to get into the compiler code a little.

Getting the caret at the right spot would also make a good first issue.

https://github.com/scala/scala/pull/7001
