### ISSUE TITLE
"".toArray[Any] throw ClassCastException

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#11028]
## 2.13.x

[latest 2.13.x `6ff29f9` 2018-07-17](https://github.com/scala/scala/tree/6ff29f967f84cfe77cf1ff15e9ea343abde586be)

```
Welcome to Scala 2.13.0-pre-6ff29f9 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> "".toArray[Any]
java.lang.ClassCastException: [C cannot be cast to [Ljava.lang.Object;
  ... 38 elided
```

https://github.com/scala/scala/blob/6ff29f967f84cfe77cf1ff15e9ea343abde586be/src/library/scala/collection/StringOps.scala#L855-L856

https://github.com/scala/scala/blob/6ff29f967f84cfe77cf1ff15e9ea343abde586be/src/library/scala/collection/StringOps.scala#L146

We can just remove type parameter because `StringOps` is a simple value class, not collection.

```diff
-  def toArray[B >: Char : ClassTag]: Array[B] =
-    s.toCharArray.asInstanceOf[Array[B]]
+  def toArray: Array[B] =
+    s.toCharArray
```

or copy array if parameter is not `ClassTag[Char]`?

```diff
-  def toArray[B >: Char : ClassTag]: Array[B] =
-    s.toCharArray.asInstanceOf[Array[B]]
+  def toArray[B >: Char : ClassTag]: Array[B] = {
+    val chars = s.toCharArray
+    if (implicitly[ClassTag[B]] == implicitly[ClassTag[Char]]) {
+      chars
+    } else {
+      // copy array
+    }
+  }
```

## 2.12.x

```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> "".toArray[Any]
java.lang.ClassCastException: [C cannot be cast to [Ljava.lang.Object;
```

- https://github.com/scala/scala/blob/v2.12.6/src/library/scala/collection/immutable/StringLike.scala#L329-L330
- https://github.com/scala/scala/blob/v2.12.6/src/library/scala/collection/immutable/StringLike.scala#L43

`StringOps` extends `StringLike`. It is a **covariant** collection. Should we copy array?

**Comment by NthPortal** [comment]
should be fixed by scala/scala#6878

**Comment by NthPortal** [comment]
@dwijnand why not M5?

**Comment by dwijnand** [comment]
Didn't mean anything by it. From your comment Seth labelled it M5. Seeing as the comment was erroneous I was just reverting that.

**Comment by NthPortal** [comment]
okay 👍
