### ISSUE TITLE
No-op copyToArray throws exception in Array, ArrayDeque, Queue, ArrayStack

### ISSUE THREAD

**Issue by Ichoran** [scala/bug#11048]
The standard behavior is not to throw an exception, even if you index outside the target, as long as you're not doing anything.  (In fact, even if you are doing anything, you don't throw an exception--you just don't do it.)

Array and the ArrayDeque inheritance hierarchy all throw an exception instead, even on a no-op (zero length copied).

```
Welcome to Scala 2.13.0-20180731-142616-329c477 (OpenJDK 64-Bit Server VM, Java 1.8.0_171).
Type in expressions for evaluation. Or try :help.

scala> val target = Array[Int]()
target: Array[Int] = Array()

scala> List(1, 2).copyToArray(target, 1, 0)
res0: target.type = Array()

scala> Array(1, 2).copyToArray(target, 1, 0)
java.lang.ArrayIndexOutOfBoundsException
  at java.lang.System.arraycopy(Native Method)
  at scala.Array$.copy(Array.scala:110)
  at scala.collection.ArrayOps$.copyToArray$extension(ArrayOps.scala:1267)
  ... 43 elided

scala> collection.mutable.ArrayDeque(1, 2).copyToArray(target, 1, 0)
java.lang.IndexOutOfBoundsException: 1
  at scala.collection.mutable.ArrayDeque.requireBounds(ArrayDeque.scala:494)
  at scala.collection.mutable.ArrayDeque.copySliceToArray(ArrayDeque.scala:454)
  at scala.collection.mutable.ArrayDeque.copyToArray(ArrayDeque.scala:438)
  ... 43 elided
```

**Comment by joshlemer** [comment]
@Ichoran this is fixed in https://github.com/scala/scala/pull/6926 
I have added test cases for the above [here](https://github.com/scala/scala/pull/6926/files#diff-df9ae63268f46a69b9be9e73273d2a72R104) and [here](https://github.com/scala/scala/pull/6926/files#diff-e8dfab7b4912f3840540ac42592063ddR69)
