### ISSUE TITLE
Queue and ArrayStack patchInPlace in the wrong place

### ISSUE THREAD

**Issue by Ichoran** [scala/bug#11046]
Version 2.13.0-20180731-142616-329c477

```scala
scala> import collection.mutable.Queue
import collection.mutable.Queue

scala> val expected = List(0, 1).patch(1, List(2), 0)
expected: List[Int] = List(0, 2, 1)

scala> val inplace = Queue(0, 1).patchInPlace(1, Queue(2), 0)
inplace: scala.collection.mutable.Queue[Int] = Queue(0, 1, 2)
```

Possible fix: rename the method `patchInWrongPlace`

**Comment by Ichoran** [comment]
Note--this affects `insertAll` also.

**Comment by szeiger** [comment]
It appears to be the other way around actually: `ArrayDeque#insertAll` inserts at the wrong position and this also affects `patchInPlace`.
