### ISSUE TITLE
Vector::head throws UnsupportedOperationException instead of NoSuchElementException

### ISSUE THREAD

**Issue by asoltysik** [scala/bug#11059]
### Expected behaviour:
`Vector::head` should throw `NoSuchElementException` as mentioned in docs and similar to `List` and other collections.
https://www.scala-lang.org/api/2.12.6/scala/collection/immutable/Vector.html#head:A

### Current behaviour:

`Vector::head` throws `UnsupportedOperationException`

### Reproduction:
```scala
Vector.empty[Int].head 
/*
java.lang.UnsupportedOperationException: empty.head
  scala.collection.immutable.Vector.head(Vector.scala:185)
*/
```

**Comment by veera83372** [comment]
Can I pick this one?

**Comment by asoltysik** [comment]
I'm not working on this so I'd say go ahead

śr., 8.08.2018, 21:42 użytkownik veera venky <notifications@github.com>
napisał:
