### ISSUE TITLE
Iterator.empty has different return type

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#11052]
in Scala 2.12

```scala
val empty: Iterator[Nothing]
```

in Scala 2.13

https://github.com/scala/scala/blob/be5ba0541bdf3a0e4d1de8df806d6f6294236d3c/src/library/scala/collection/Iterator.scala#L890

```scala
@`inline` final def empty[T]: Iterator[T] = _empty
```

It's used in akka for example to generate an Exception

https://github.com/akka/akka/blob/59040fadadacda5354e0af73a44237096ab23774/akka-actor/src/main/scala/akka/util/ByteIterator.scala#L36

This is the error you get:

```scala
def next(): Byte = {
  if (!hasNext) Iterator.empty.next
  else ???
}
```

```
polymorphic expression cannot be instantiated to expected type;
 found   : [T]()T
 required: Byte
```

**Comment by ritschwumm** [comment]
lol @akka

**Comment by som-snytt** [comment]
So an `Iterator[Nothing].next()` is guaranteed to throw, and it wouldn't be necessary to provide a branch for the `if else`, though I always see it written as `if else`.

Someone should also remind akka to use parens for `next()`.

IIRC, when Popeye laughs, he says "akka, akka, akka" over and over.

There must a pun forthcoming with `Iterator.empty` and `Humpty Dumpty`. Possibly involving `thread dump`?

**Comment by julienrf** [comment]
Workaround: `Iterator.empty[Nothing].next()`?

**Comment by MasseGuillaume** [comment]
@som-snytt This is not cross-compatible. In scala <= 2.12, you would get this error:

```scala
scala> Iterator[Nothing].next()
<console>:12: error: missing argument list for method apply in object Iterator
Unapplied methods are only converted to functions when a function type is expected.
You can make this conversion explicit by writing `apply _` or `apply(_)` instead of `apply`.
       Iterator[Nothing].next()
               ^
```

**Comment by viktorklang** [comment]
@MasseGuillaume You could possibly use: [akka.util.Collections.EmptyImmutableSeq.iterator.next()](https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/util/Collections.scala#L15)

**Comment by MasseGuillaume** [comment]
@viktorklang will do, However, this bug is about cross-compatibility. We should avoid breaking code. Even more, if there is no easy cross-compatible workaround.

**Comment by viktorklang** [comment]
@MasseGuillaume I understand. I was only offering a cross-compilable alternative in the mean time.

**Comment by MasseGuillaume** [comment]
This works in 2.12 and 2.13:

```scala
Iterator[Nothing]().next
```

**Comment by viktorklang** [comment]
@MasseGuillaume Except that you are now allocating empty iterators.

scala> Iterator[Nothing]() eq Iterator[Nothing]()
res1: Boolean = false

**Comment by julienrf** [comment]
@MasseGuillaume `(Iterator.empty: Iterator[Nothing]).next()`

**Comment by joshlemer** [comment]
Why not just `Iterator.empty.next()`? This works in 2.12 and 2.13

**Comment by NthPortal** [comment]
I was confused about that as well

**Comment by MasseGuillaume** [comment]
@joshlemer @NthPortal read the first comment again: 
https://github.com/scala/bug/issues/11052#issue-347056469

This does not compile:

```
def next(): Byte = {
  if (!hasNext) Iterator.empty.next
  else ???
}
//polymorphic expression cannot be instantiated to expected type;
// found   : [T]()T
// required: Byte
```

**Comment by szeiger** [comment]
This appears to be a limitation of type inference. The compiler can infer the correct type in the polymorphic version (`Iterator.empty.next(): Byte`) or insert the missing empty parameter list (`Iterator.empty.next: Byte` in 2.12) but not both combined.

Our standard `IterableFactory` requires `def empty[A]`. Not being able to extend `IterableFactory` in the `Iterator` companion object would be a high price to pay. It would also be inconsistent with other similar cases where switching from `Nothing` to `[A]A` was preferred for covariant types to improve type inference in expressions such as `xs.fold(empty[Int])(...))`.

The recommended solution is to add the missing parentheses, as pointed out by @joshlemer. I'm tentatively moving this ticket to 2.14. Dotty's type inferencer can already deal with this situation.
