### ISSUE TITLE
Cannot use varargs from Java

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#11057]
```scala
// build.sbt
scalaVersion := "2.13.0-M4"
```

```scala
// src/main/scala/C.scala
object VarArgs {
  @annotation.varargs
  def call(args: Int*): Int = args.size
}
```

```java
// src/main/java/VarArgsUsage.java
public class VarArgsUsage {
  public void usage() {
    VarArgs.call(1, 2, 3);
  }
}
```

```
[error] /home/gui/scala213/test/junit/java/VarArgsUsage.java:4: method call in class VarArgs cannot be applied to given types;
[error]   required: scala.collection.immutable.Seq<java.lang.Object>
[error]   found: int,int,int
[error]   reason: actual and formal argument lists differ in length
[error]     VarArgs.call(1, 2, 3);
```

javap result from 2.13.X

```java
public final class VarArgs {
  public static int call(scala.collection.immutable.Seq<java.lang.Object>);
}
```

javap result from 2.12.X

```java
public final class VarArgs {
  public static int call(int...);
  public static int call(scala.collection.Seq<java.lang.Object>);
}
```

**Comment by MasseGuillaume** [comment]
It looks like `@annotation.varargs` is broken in 2.13.X.

**Comment by lrytz** [comment]
I'll take a look tomorrow.

**Comment by MasseGuillaume** [comment]
The partest for varargs is here: https://github.com/scala/scala/blob/2.13.x/test/files/jvm/t8786-sig.scala

However, this does not illustrate the situation correctly. I created a test harness to prove this:

You can take a look at this commit in 2.13.x:
https://github.com/MasseGuillaume/scala/commit/04035f9dfb881627cb7834680431b97ef68c7c04

And this commit in 2.12.x:
https://github.com/MasseGuillaume/scala/commit/34fe1bcd4db7c6353316618243563efcda6adc9c

The test in 2.12 pass as expected.

**Comment by lrytz** [comment]
Most likely caused by https://github.com/scala/scala/pull/6531

**Comment by MasseGuillaume** [comment]
@lrytz can you assign this bug to me? I would love to solve this.

**Comment by lrytz** [comment]
@MasseGuillaume sorry I just saw your comment now, after submitting the PR...
