### ISSUE TITLE
Inconsistency in naming of methods in SeqViews/IndexedSeqView

### ISSUE THREAD

**Issue by joshlemer** [scala/bug#11066]
### In IndexedSeqView

we have the following methods:

* `def reverse: IndexedSeqView[A]`
* `def reversed: Iterable[A]`

* `def prepended[B >: A](elem: B): IndexedSeqView[B]`
* `def prependedAll[B >: A](prefix: Iterable[B]): View[B]`

* `def appended[B >: A](elem: B): View[B]`
* `def appendedAll[B >: A](suffix: Iterable[B]): View[B]`

1. Should `prepended`, `prependedAll`, `appended` and `appendedAll` return `IndexedSeqView`s or `View`s? Should probably be consistent

2. Should `reverse` and `reversed` be switched so that all the past tense methods return views? or Should the other methods become present tense?

**Comment by julienrf** [comment]
Note that `reversed` is non-public. We have different return types for `appended` and `appendedAll` (respectively, `prepended` and `prependedAll`) because we need to know the size of the resulting collection to be able to return an `IndexedView`. In the case of `appendedAll` and `prependedAll`, we don’t know it in general (we may know it only if `knownSize` is greater than -1).

**Comment by joshlemer** [comment]
@julienrf Maybe `appended` could be made to return IndexedSeqView, to match `prepended`

**Comment by SethTisue** [comment]
marked as "blocker" since it would really be preferable for M5 to have final names for things

**Comment by joshlemer** [comment]
In my opinion 'appended' should return IndexedSeqView and that is the most important issue, and in fact PR #7048 depends on that

**Comment by julienrf** [comment]
Yes I think `appended` should return an `IndexedSeqView`. I thought it was already the case, actually. That’s probably an oversight :-/

**Comment by szeiger** [comment]
The others could be overloaded to return an `IndexedSeqView` if the RHS is also of that type.

**Comment by szeiger** [comment]
As Julien mentioned, `reversed` is `protected`, the public method is called `reverse`, which is consistent with immutable collections.

All of `appended`, `appendedAll`, `prepended` and `prependedAll` come from `SeqOps` and are implemented there using the basic `View.*` implementations. `SeqView` and `IndexedSeqView` selectively override `prependedAll`.

I'll add overrides for `appended` and overloaded `appendAll` and `prependAll` versions.
