### ISSUE TITLE
MemberDef range position should wrap annotations

### ISSUE THREAD

**Issue by lrytz** [scala/bug#11060]
```
$> cat Test.scala
@deprecated("", "")
class C
$> scalac Test.scala -Yrangepos -Xprint:typer -Xprint-pos
[[syntax trees at end of                     typer]] // Test.scala
[20:27]package [20:20]<empty> {
  [20:27]@deprecated([12:14]"", [16:18]"") class C extends [27:27][27]scala.AnyRef {
    [27]def <init>(): [27]C = [27]{
      [27][27][27]C.super.<init>();
      [27]()
    }
  }
}
```

The range position for the `ClassDef` is `[20:27]`, so it doesn't include the annotation. This causes completions in the annotation to fail in 2.13 (2.12 uses some different mechanism it seems), the [call to `wrappingTree`](https://github.com/scala/scala/blob/47b422400eb389fdbd704ed885efb23839d64374/src/repl/scala/tools/nsc/interpreter/PresentationCompilation.scala#L41) returns a range that doesn't include the annotation.

This was worked around in https://github.com/scala/scala/commit/63f788bfb86c89a9d383bfa7f5619d928dd359d2, but that fix is inefficient. It should not be necessary to descend into all the children all `trees`. The method was optimized in 2.12.x (https://github.com/scala/scala/commit/49bb79f3f2e03a7ad2abf41378f714ada11cc423#diff-6da1db51682701fbfb6d168ce11dd438L40). Bringing that improvement forward breaks completion in 2.13.

**Comment by lrytz** [comment]
I think this can be fixed in RC1, @SethTisue @adriaanm agree?

**Comment by adriaanm** [comment]
agree, but could we keep the correct but slow version in M5, deferring the optimization to RC1?

**Comment by SethTisue** [comment]
@lrytz want to sneak that in, or shall we just postpone to RC1?

**Comment by mkeskells** [comment]
> Bringing that improvement forward breaks completion in 2.13.
@lrytz what is the break in 2.13

**Comment by adriaanm** [comment]
completion inside an annotation doesn't work in the repl

**Comment by adriaanm** [comment]
`@deprecated(message = "".<TAB>) class C` // TAB does nothing
