### ISSUE TITLE
Add lazyZip to ArrayOps and StringOps

### ISSUE THREAD

**Issue by julienrf** [scala/bug#11063]
The `lazyZip` operation is currently only available on `Iterable`. To use it on an `Array` or a `String` you have to first convert them to iterables. The `lazyZip` operation should be available on `Array` and `String` without requiring this conversion.

**Comment by szeiger** [comment]
A more generally applicable definition would be to put `toLazyZipOps` into `Predef` and make use of `IsIterableLike`. I was going to make the argument that it is unnecessary overhead for `Array` and `String` because they are strict but actually that doesn't even matter. `LazyZipOps` forces its argument, there are no by-name tricks to prevent that, so why does it exist in the first place? Shouldn't `lazyZip` be defined as a method directly on `Iterable`?

**Comment by julienrf** [comment]
> Shouldn't lazyZip be defined as a method directly on Iterable?

The problem is that you would then be able to chain `lazyZip` too many times. Consider the following expressions:

~~~ scala
def example(xs: List[Int]): Unit = {
  (xs lazyZip xs): LazyZip2[Int, Int, List[Int]]
  // `LazyZipN` types are special lazy collection types
  // We can go up to LazyZip4
  (xs lazyZip xs lazyZip xs lazyZip xs): LazyZip4[Int, Int, Int, Int, List[Int]]
  // After that, you get a compilation error
  xs lazyZip xs lazyZip xs lazyZip xs lazyZip xs
  // error: method lazyZip is not a member of LazyZip4
}
~~~

However, note that there is an implicit conversion from `LazyZipN[E1, E2, ...]` to `Iterable[(E1, E2, …)]`. If `lazyZip` was defined as a method on `Iterable`, it would become possible to call `lazyZip` on a `LazyZip4` instance:

~~~ scala
(xs lazyZip xs lazyZip xs lazyZip xs lazyZip xs): LazyZip2[(Int, Int, Int, Int), Int, List[(Int, Int, Int, Int)]]
// We would get a LazyZip*2* instance instead of an expected LazyZip5 (which does not exist)
~~~

In order to make it impossible to call `lazyZip` on a `LazyZip4` instance, the `lazyZip` method is available via an implicit conversion from `Iterable`. As a consequence, it is possible to call it on an `Iterable` instance, but not on something that *can be converted* into an `Iterable` (such as a `LazyZip4` instance).

**Comment by julienrf** [comment]
> A more generally applicable definition would be to put toLazyZipOps into Predef and make use of IsIterableLike

Yes, that’s a good suggestion!
