### ISSUE TITLE
HashMap.merged for new CHAMP-based HashMap

### ISSUE THREAD

**Issue by szeiger** [scala/bug#11077]
This method needs to be optimized in the same way as it was in the old HashMap implementation.

**Comment by mkeskells** [comment]
@szeiger  is someone working on this now, if not I can pick his up

**Comment by lrytz** [comment]
@mkeskells pretty sure it's up for grabs, @szeiger is away for the next two weeks.

**Comment by adriaanm** [comment]
pinging a few candidates for fixing this: @mkeskells, @joshlemer, or perhaps @retronym?

**Comment by joshlemer** [comment]
✋

**Comment by SethTisue** [comment]
@joshlemer is this a blocker for RC1, or can I move it to the 2.13.1 milestone?
