### ISSUE TITLE
Random.nextBytes should return Array[Byte] and not Unit

### ISSUE THREAD

**Issue by Lasering** [scala/bug#11072]
Every method on the Random object returns the random value except `nextBytes` which expects the output array as argument. This makes its use very clunky compared to the other methods.

There should exist a method:

```scala
class Random(val self: java.util.Random) extends AnyRef with Serializable {
  def nextBytes(dim: Int): Array[Byte] = {
    val bytes = Array.ofDim[Byte](dim)
    Random.nextBytes(bytes)
    bytes
  }
}
```

As in practice we want to specify the size of the array.

I can make a PR if the idea is accepted.

**Comment by viktorklang** [comment]
How about:

```scala
  def nextBytes(into: Array[Byte]): Array[Byte] = {
    Random.nextBytes(into)
    into
  }
```

**Comment by martijnhoekstra** [comment]
IMO that's a worst of both worlds @viktorklang 

Returning `Unit` makes it obvious that the method works by mutating the argument as a side-effect.

In your example, you still have to initialize the Array yourself, and the advantage is getting back the filled array that you already have created anyway. Especialy with `tap` merged, `Array.ofDim[Byte](dim).tap(nextBytes)` offers the same functionality as you would have if you returned the array.

I'd prefer adding an overload that takes a length and returns an Array, if that's at all needed (I have no idea how often people require a single array of random bytes vs looping with a buffer, which the current method is optimized for)

**Comment by viktorklang** [comment]
@martijnhoekstra `array.tap(nextBytes)` would be nice, yes.
