### ISSUE TITLE
VectorMap#equals violate transitive law

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#11080]
https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#equals-java.lang.Object-

> It is transitive: for any non-null reference values x, y, and z, if x.equals(y) returns true and y.equals(z) returns true, then x.equals(z) should return true.

https://github.com/scala/scala/blob/c6fc4e717490402ff2502737df3e36f331cbd9d7/src/library/scala/collection/immutable/VectorMap.scala#L107

```
Welcome to Scala 2.13.0-pre-ca5a07d (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.immutable.VectorMap
import scala.collection.immutable.VectorMap

scala> val x = VectorMap(1 -> 2, 3 -> 4)
x: scala.collection.immutable.VectorMap[Int,Int] = VectorMap(1 -> 2, 3 -> 4)

scala> val y = Map(1 -> 2, 3 -> 4)
y: scala.collection.immutable.Map[Int,Int] = Map(1 -> 2, 3 -> 4)

scala> val z = VectorMap(3 -> 4, 1 -> 2)
z: scala.collection.immutable.VectorMap[Int,Int] = VectorMap(3 -> 4, 1 -> 2)

scala> x == y
res0: Boolean = true

scala> y == z
res1: Boolean = true

scala> x == z
res2: Boolean = false
```

**Comment by mdedetrich** [comment]
Thanks for spotting the bug, bit annoying since it effects performance
