### ISSUE TITLE
The mutable collection's factory method 'empty[T]' should have parenthesis

### ISSUE THREAD

**Issue by kmizu** [scala/bug#11096]
For example,  an instance of `scala.collection.mutable.Buffer` can be created via:

```scala
val buffer = scala.collection.mutable.Buffer.empty[Int]
```

Since this method returns a different buffer for each call, it has side effect.  Then, this method should be called as the followings:

```scala
val buffer = scala.collection.mutable.Buffer.empty[Int]()
```

However, since `empty[T]` method is declared as 'no parentheses'  method, it cannot be done.  I think it should be fixed.  How do you think about it?

**Comment by lrytz** [comment]
We discussed this at https://github.com/scala/collection-strawman/issues/520. Please re-open if you think that it needs further discussion.
