### ISSUE TITLE
False positive "parameter value is never used" warning

### ISSUE THREAD

**Issue by LMnet** [scala/bug#11099]
I updated my application from scala 2.11.12 to 2.12.6 and I got 2 new false positive warnings.

The first one: 
```scala
import pureconfig.ConfigConvert

case class MySet[A](set: Set[A])

implicit def mySetConvert[A](implicit valueConvert: ConfigConvert[A]): ConfigConvert[MySet[A]] =
  ConfigConvert[Set[A]].xmap(
    MySet.apply,
    _.set
  )
```

With the code above I got this warning:
```
parameter value valueConvert in method mySetConvert is never used
implicit def mySetConvert[A](implicit valueConvert: ConfigConvert[A]): ConfigConvert[MySet[A]] =
```

If I delete `valueConvert` I got this error:
```
could not find implicit value for parameter conv: pureconfig.ConfigConvert[Set[A]]
ConfigConvert[Set[A]].xmap(
             ^
```

The second one:
```scala
import pureconfig._
import scala.util.Success

trait TestTrait
case class TestClass() extends TestTrait

def load = {
  implicit val convert: ConfigConvert[TestTrait] = {
    ConfigConvert.viaNonEmptyStringTry[TestTrait](_ => Success(TestClass()), x => x.toString)
  }

  loadConfig[Map[String, TestTrait]]
}
```

With the code above I got this warning:
```
local val convert in method loadProjectsGeometriesConfig is never used
implicit val convert: ConfigConvert[TestTrait] = {
             ^
```

If I delete `convert` I got this error:
```
could not find implicit value for parameter reader: pureconfig.Derivation[pureconfig.ConfigReader[Map[String,ru.dgis.casino.advisor.welder.ScalaBug2.TestTrait]]]
loadConfig[Map[String, TestTrait]]
          ^
```

Both issues are somehow related to the pureconfig library (I'm using the latest 0.9.1 version), which uses shapeless generic derivation. With Scala 2.11 I got no warnings.

**Comment by SethTisue** [comment]
relevant? https://github.com/scala/scala/pull/5876  /cc @som-snytt

**Comment by som-snytt** [comment]
Yes, that's the one. For some use cases, it's currently necessary to disable linting macros (`none`):
```
$ scalam -Ywarn-macros:help
Usage: -Ywarn-macros:<mode> where <mode> choices are none, before, after, both (default: before).
  none    Do not inspect expansions or their original trees when generating unused symbol warnings.
  before  Only inspect unexpanded user-written code for unused symbols.
  after   Only inspect expanded trees when generating unused symbol warnings.
  both    Inspect both user-written code and expanded trees when generating unused symbol warnings.
```

**Comment by LMnet** [comment]
I scanned a lot of discussions but didn't find this flag. `-Ywarn-macros:after` fixed the issue, thanks. 

But anyway, it looks a bit like a "secret knowledge". How to find this flag, if you do not know about its existence?

**Comment by som-snytt** [comment]
The search box on the docs page works for `options`: https://docs.scala-lang.org/overviews/compiler-options/index.html

**Comment by LMnet** [comment]
Scala 3 is still very far from the current moment. Maybe it would be helpful if warning message will contain info about this flag.

**Comment by som-snytt** [comment]
Good idea. Somewhere there is a note for the warning to say whether it was pre- or post-expansion; it would be natural to mention the flag, too.

**Comment by philwalk** [comment]
I'm trying to migrate to 2.13.0, and I'm getting the same false positive, but unrelated to macros (afaik):

```
stats.scala:189:33: parameter value yy in method convolve is never used
[warn]  def convolve(xx: Seq[Double], yy: Seq[Double]) = {
          crossCorrelate(xx.toArray, yy.reverse.toArray)
        }
```
I wouldn't think that it would matter, but I confirmed that method crossCorrelate uses both xx and yy, in case there might be some transitive thing happening.
