### ISSUE TITLE
Add method View#peek

### ISSUE THREAD

**Issue by joshlemer** [scala/bug#11098]
`View`s could have a method `peek` which would allow the injection of a side-effecting function (or indeed, breakpoint) in the middle of the view's pipeline. Inspired by [Java 8 Stream#peek method](https://docs.oracle.com/javase/8/docs/api/?java/util/stream/Stream.html). The signature would be something like:

```scala
def peek[U](f: A => U): View[A] = new View.Peek(this, f)
```

and its usage would be like

```scala
     View("one", "two", "three", "four")
         .filter(_.length > 3)
         .peek(e => println("Filtered value: " + e))
         .map(_.toUpperCase)
         .peek(e => println("Mapped value: " + e))
         .to(Seq)
```

**Comment by NthPortal** [comment]
I would like to suggest that this be widened to all collections. It is trivial to implement (`.map(a => { f(a); a })`), but also a common enough thing to want (for debugging or logging) that it's worth not needing to write repeatedly, IMO.

**Comment by joshlemer** [comment]
Should probably be implemented as `foreach(f); this` for strict collections, so that a new one is not built

**Comment by SethTisue** [comment]
We have `tap` now. This is the same, but for collections. Can the naming can be aligned somehow? `tapEach` or something? 🤔
