### ISSUE TITLE
Problems with ControlThrowable

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#11116]
`scala.util.control.ControlThrowable` is "[a] marker trait indicating that the Throwable it is mixed into is intended for flow control." ([docs](https://www.scala-lang.org/api/current/scala/util/control/ControlThrowable.html)). One of its key features is that it extends `scala.util.control.NoStackTrace`, and thus (unless disabled) does not incur the significant construction cost of filling in the stack trace; it accomplishes this by overriding `fillInStackTrace()` to do nothing.

In some cases, such as `scala.runtime.NonLocalReturnControl`, `ControlThrowable` is used for single-use exceptions. In others, such as the exception used by an instance of `scala.util.control.Breaks`, it is a cached exception.

Java 1.7 (the advent of try-with-resources) added an `addSuppressed` method, used for adding suppressed exceptions in try-with-resource blocks. It also added constructors for each of `Throwable`, `Error`, `Exception` and `RuntimeException` with a parameter to disable suppressed exceptions for a particular subclass (as well as one to disable stack traces). However, unlike `fillInStackTrace()`, `addSuppressed` is final, so it cannot be overridden by a mixin trait to disable suppression, like `fillInStackTrace()` can.

For cached `ControlThrowable` instances, it would be desirable to disable suppressed exceptions as well as stack traces, so that exceptions are not leaked (i.e. kept as references) by being added as suppressed to a cached instance. Additionally, the suppression information becomes somewhat confusing once `addSuppressed` is called multiple times in different contexts.

Is there a way we can improve `ControlThrowable` to disable suppressed exceptions as well? Because it is a mixin trait, it cannot call one of `Throwable`'s constructors. Is there a workable deprecation and/or migration path to it being a non-mixin class? Should it be deprecated in favour of a new class which can disable suppressed exceptions?

It is worth noting that `ControlThrowable` is treated specially by various parts of the stdlib (such as being a [fatal exception](https://www.scala-lang.org/api/current/scala/util/control/NonFatal$.html)). Consequently, it is insufficient to just say that users should just ignore `ControlThrowable` and disable suppressed exceptions via `Throwable`'s constructor, because their exception class will then not receive the special treatment of `ControlThrowable`s from the stdlib. Any solution involving new classes must receive the same privileged treatment as `ControlThrowable`.

**Comment by NthPortal** [comment]
cc @viktorklang

**Comment by NthPortal** [comment]
For reference, this came up when working on `scala.util.Using`, which (like try-with-resources) suppresses exceptions.

**Comment by adriaanm** [comment]
Fixed by scala/scala#7413
