### ISSUE TITLE
patchInPlace has absurd semantics when `from + replaced > length`

### ISSUE THREAD

**Issue by sjrd** [scala/bug#11114]
I couldn't find any written down Scaladoc for `patchInPlace`, so it is difficult to argue it's a *bug*, but I'll try. Here is a transcript:
```scala
Welcome to Scala 2.13.0-pre-53c4be1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_60).
Type in expressions for evaluation. Or try :help.

scala> val buf = scala.collection.mutable.ArrayBuffer(1, 2, 3, 4, 5)
buf: scala.collection.mutable.ArrayBuffer[Int] = ArrayBuffer(1, 2, 3, 4, 5)

scala> buf.patchInPlace(3, List(10, 11), 4)
java.lang.IndexOutOfBoundsException: 7
  at scala.collection.mutable.ArrayBuffer.checkWithinBounds(ArrayBuffer.scala:54)
  at scala.collection.mutable.ArrayBuffer.remove(ArrayBuffer.scala:142)
  at scala.collection.mutable.IndexedBuffer.patchInPlace(Buffer.scala:202)
  at scala.collection.mutable.IndexedBuffer.patchInPlace$(Buffer.scala:192)
  at scala.collection.mutable.ArrayBuffer.patchInPlace(ArrayBuffer.scala:26)
  ... 40 elided

scala> buf.patchInPlace(3, List(10, 11), 10)
java.lang.IndexOutOfBoundsException: 8
  at scala.collection.mutable.ArrayBuffer.checkWithinBounds(ArrayBuffer.scala:54)
  at scala.collection.mutable.ArrayBuffer.remove(ArrayBuffer.scala:142)
  at scala.collection.mutable.IndexedBuffer.patchInPlace(Buffer.scala:202)
  at scala.collection.mutable.IndexedBuffer.patchInPlace$(Buffer.scala:192)
  at scala.collection.mutable.ArrayBuffer.patchInPlace(ArrayBuffer.scala:26)
  ... 40 elided

scala> buf.patchInPlace(0, List(10, 11), 10)
res2: buf.type = ArrayBuffer(10, 11)
```
As you can see in the very last (successful) call, `replaced` was truncated to `buf.length`, and because `from = 0`, the call succeeds. But in the other two calls, `replaced` being truncated to `buf.length` does not help, because `from > 0` and hence `from + truncatedLength` is still too big.

It's completely inconsistent. I believe `replaced` should either
* never be truncated (hence the last call would also throw), or
* be truncated to `length - clampedFrom` (note that `from` itself is clamped within `0 <= clampedFrom <= length`, so `replaced` should be truncated wrt. to the clamped `from`, not the original one)

**Comment by NthPortal** [comment]
I would assume that it should have the same semantics as `patch` (I agree that it still needs to be documented), except that it modifies the underlying collection. Thus, the two that throw an exception ought to return `resN: buf.type = ArrayBuffer(1, 2, 3, 10, 11)`

**Comment by Ichoran** [comment]
I have a (failing) collections-laws test for `patchInPlace` that insists that it behave identically to `patch`.  If someone who wants to fix `patchInPlace` can get collections-laws running and keep modifying `patchInPlace` until it passes, that would be great.  I wasn't able to submit a full set of bug reports because the presumption in collections-laws is that bugs are rare, and so testing stops once one bug is found.

I don't think semantics other than those of `patch` are defensible for `patchInPlace`.  Taking a different argument to enable better performance is okay, though, I think.  You at least need `Iterable` not `IterableOnce` in order to know how much space to clear out for the patch.

**Comment by joshlemer** [comment]
>Taking a different argument to enable better performance is okay, though   

Why not pattern match to optimize the `Seq` case, otherwise falling back to slower version?

**Comment by Ichoran** [comment]
@joshlemer - Because in practice I think you wouldn't use `patchInPlace` unless it was higher-efficiency, and I think it's unlikely to be higher-efficiency unless the implementation for iterators was converting to an array, and that's trivial to do with the `Iterable` version.
