### ISSUE TITLE
reconsider removal of -Yno-adapted-args in 2.13

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#11110]
I'm confused why `-Yno-adapted-args` got the axe (in https://github.com/scala/scala/pull/6505, under the umbrella of 
https://github.com/scala/scala-dev/issues/430)

might this have been overzealous? `-Yno-adapted-args` is both widely used and useful IMO

and it only causes "language fragmentation" in the sense that it makes some code — code that has been producing compiler warnings since Scala 2.11 (EDIT: under `-Xlint`, that is, not by default) — give a hard error instead of a warning

if we were to get rid of argument adaptation entirely, as I expect to happen in Scala 2.14 and/or Scala 3, then it will make sense to remove the flag at that time. but I don't see that it makes sense to remove now

**Comment by Jasper-M** [comment]
> and it only causes "language fragmentation" in the sense that it makes some code — code that has been producing compiler warnings since Scala 2.11 — give a hard error instead of a warning

There doesn't seem to be a warning without the flag, though.

**Comment by hrhino** [comment]
You need to use `-Ywarn-adapted-args` for the warning, which apparently made the cut, so that and `-Xfatal-warnings` have a similar effect in conjunction.

That said, I always turn on `-Yno-adapted-args` in my project, and I'll be sad to see it go. (Isn't there talk of removing it completely in Dotty?)

**Comment by dwijnand** [comment]
Duplicate of https://github.com/scala/scala-dev/issues/496, I'd say.

**Comment by SethTisue** [comment]
> (Isn't there talk of removing it completely in Dotty?)

yes, this "feature" is on its slow way out of existence.

> You need to use -Ywarn-adapted-args for the warning

ah, right, thanks for the correction. note that this warning has been part of `-Xlint` since 2.11, though, so it hasn't been *only* behind that one obscure flag.

> Duplicate of scala/scala-dev#496, I'd say.

I see your point, but that one's targeted for 2.13.1. I opened this ticket specifically to ask what we're going to do for 2.13.0-RC1/2.13.0.

**Comment by dwijnand** [comment]
I think that one should target RC1.

**Comment by adriaanm** [comment]
For migration to dotty, we can adjust adaption use -Xsource. Since we're out of time for RC1, re-scheduling for 2.13.1. If someone manages to fix this for the RC1, that's fine too, but we won't hold up the RCs for this.

**Comment by SethTisue** [comment]
@szeiger's Scala Days talk has a slide on this. from https://downloads.lightbend.com/website/scaladays/2018/ny/slides/migrating-to-scala-2-13.pdf

<img width="504" alt="screen shot 2019-03-05 at 7 29 26 pm" src="https://user-images.githubusercontent.com/161079/53854154-25412900-3f7d-11e9-8996-7f839e88c700.png">

**Comment by szeiger** [comment]
@adriaanm Does it even make sense to revert this in 2.13.1 (or later) now that 2.13.0 shipped without the option?

**Comment by adriaanm** [comment]
As useful as this is, I don't want to regress on our policy, nor remove the pressure to actually implement the migration under -Xsource. For now, the warning + fatal warning will have to suffice.

**Comment by szeiger** [comment]
I don't follow. Are you proposing that certain source levels enable or disable the warnings automatically? If so, which ones?

**Comment by adriaanm** [comment]
No, I wasn't thinking of the warnings. They are still available, right? I'm referring to the change to the adapt logic that actually prevented the insertion of `()` or tupling of args. 

A "future" (i.e. 2.14 or 3.0) source level will implement (a refinement of) the policy implemented by `-Yno-adapt-args`, and I feel we should focus our energy on getting that done.

We're talking about not inserting `()` (except for java-defined methods) and not auto-tupling args (except for, erm, what were the conditions again? I guess only for cases where a Tuple was expected or where we know only a single argument is allowed, e.g. infix methods).

**Comment by szeiger** [comment]
So you're saying we should not restore `-Yno-adapt-args` on principle? Judging by the changes in https://github.com/scala/scala/pull/6505 it should only take a few lines of code to get it back. Or maybe there were more changes in the meantime that would make this infeasible?

**Comment by adriaanm** [comment]
You're right, it would not be a lot of work to bring back, but then there's less incentive to switch to the -Xsource mechanism, which provides a more coherent upgrade-prep experience.

**Comment by eed3si9n** [comment]
There's apparently a single use case where auto-tupling is useful, so I suggested in https://contributors.scala-lang.org/t/lets-drop-auto-tupling/1799/14?u=eed3si9n that we create an opt-in marker called `scala.reflect.ParamList[_]`:

```scala
def foo[A](params: A): Unit = println(params.toString)
def bar[A: ParamList](params: A): Unit = println(params.toString)
```

so 

```scala
foo(1, "hello", Option(3)) // won't compile
bar(1, "hello", Option(3)) // prints (1, "hello", Option(3))
```

**Comment by szeiger** [comment]
While we're still considering things, I'm rescheduling this for 2.13.2.

**Comment by SethTisue** [comment]
given that we still have `-Ywarn-adapted-args`, and now that we have [configurable warnings](https://github.com/scala/scala/pull/8373), I think this qualifies as fixed

**Comment by yanns** [comment]
I also wanted to have something like `-Yno-adapted-args` in scala 2.13.

> given that we still have ` -Ywarn-adapted-args`
For me it does not work:
```
[error] bad option: '-Ywarn-adapted-args'
```

The new configurable warning convention does not work:
```
[error] bad option: '-Wadapted-args'
```

I could use `-Xlint:adapted-args`

**Comment by SethTisue** [comment]
> I could use `-Xlint:adapted-args`

right. thank you for the correction

but note also that it's included in `-Xlint`'s defaults, so it doesn't normally need to be individually enabled:

```
Welcome to Scala 2.13.2-bin-a789d81 (OpenJDK 64-Bit Server VM, Java 1.8.0_242).
scala> println(1, 2)
(1,2)
scala> :replay -Xlint
replay> println(1, 2)
               ^
        warning: adapted the argument list to the expected 2-tuple: add additional parens instead
                signature: Predef.println(x: Any): Unit
          given arguments: 1, 2
         after adaptation: Predef.println((1, 2): (Int, Int))
(1,2)
```

as for the turning the warning into an error, `-Werror` will turn all warnings into errors, and the incantation for turning just this particular warning into an error is `-Wconf:cat=lint-adapted-args:e`:

```
scala> :reset -Xlint -Wconf:cat=lint-adapted-args:e
Resetting interpreter state.
Forgetting all expression results and named terms: $intp

scala> println(1,2)
              ^
       error: adapted the argument list to the expected 2-tuple: add additional parens instead
               signature: Predef.println(x: Any): Unit
         given arguments: 1, 2
        after adaptation: Predef.println((1, 2): (Int, Int))
```

**Comment by SethTisue** [comment]
> [error] bad option: '-Wadapted-args'

by the way, it isn't clear to me why some things are `-W` flags and other things are under `-Xlint` instead. @som-snytt is there some rule there?

**Comment by som-snytt** [comment]
Warnings that are not noisy and also "recommended" can be promoted to lint.

E.g., `-Wunused:params` is not enabled by `-Xlint:unused` (as a very refined case).

`-Wdead-code` has false positives, so is not linted.

The borderline promotable warnings IMHO are numeric-widen and value-discard.
