### ISSUE TITLE
Array iterator reduced performance from 2.12.6 to 2.13.0-M4

### ISSUE THREAD

**Issue by shawjef3** [scala/bug#11118]
As part of another investigation I found that 2.13.0-M4's iterator over arrays is around 7% slower than 2.12's, although I didn't account for any overhead from JMH's [Blackhole](http://hg.openjdk.java.net/code-tools/jmh/file/3769055ad883/jmh-core/src/main/java/org/openjdk/jmh/infra/Blackhole.java#l377), if any.

Please see [my results](https://docs.google.com/spreadsheets/d/1L1z4N5wUP7iZG0pz0Gh9rW4ZJWNQgoFiUA-cCtr3dvw), and [the code repository](https://github.com/shawjef3/TakeUntilThreshold/tree/557ae18b614bb11d91f58fddb4e76a4b7ffdd995), focusing on [the array benchmark](https://github.com/shawjef3/TakeUntilThreshold/blob/557ae18b614bb11d91f58fddb4e76a4b7ffdd995/benchmarks/src/main/scala/me/jeffshaw/takeuntil/IteratorBenchmarks.scala#L92) and [its super class](https://github.com/shawjef3/TakeUntilThreshold/blob/557ae18b614bb11d91f58fddb4e76a4b7ffdd995/benchmarks/src/main/scala/me/jeffshaw/takeuntil/IteratorBenchmarks.scala#L59).

**Comment by shawjef3** [comment]
[2.13.0-M5 implementation](https://github.com/scala/scala/blob/612e9374f5731d2b22c02c8c3793c990273a8cb7/src/library/scala/collection/ArrayOps.scala#L107)

[2.12.6 implementation](https://github.com/scala/scala/blob/v2.12.6/src/library/scala/collection/IndexedSeqLike.scala#L52)

**Comment by szeiger** [comment]
I have no reason to believe why the new implementation should be slower but I can confirm your results using a pared down version of your project that contains nothing but a modified version of ArrayIteratorBenchmarks. To make it easier to find the source of the problem and allow quick iterations I added a simplified version of ArrayOps from 2.13.x. This is on 2.12.6 with the regular implementation against the new ArrayOps:

```
[info] Benchmark                                    (valueCount)   Mode  Cnt        Score       Error  Units
[info] ArrayIteratorBenchmarks.newArrayOpsIterator           100  thrpt    5  1425642.945 ± 56207.053  ops/s
[info] ArrayIteratorBenchmarks.newArrayOpsIterator         10000  thrpt    5    14392.692 ±   909.480  ops/s
[info] ArrayIteratorBenchmarks.newArrayOpsIterator       1000000  thrpt    5      127.421 ±     2.481  ops/s
[info] ArrayIteratorBenchmarks.newArrayOpsIterator      10000000  thrpt    5       12.663 ±     0.199  ops/s
[info] ArrayIteratorBenchmarks.scalaIterator                 100  thrpt    5  1391580.352 ± 16841.489  ops/s
[info] ArrayIteratorBenchmarks.scalaIterator               10000  thrpt    5    14259.630 ±   508.920  ops/s
[info] ArrayIteratorBenchmarks.scalaIterator             1000000  thrpt    5      155.889 ±     1.982  ops/s
[info] ArrayIteratorBenchmarks.scalaIterator            10000000  thrpt    5       15.478 ±     0.719  ops/s
```

For small array sizes (including quite large values of "small") the new implementation is slightly faster but for very large sizes it is clearly worse.

**Comment by hrhino** [comment]
Could it be that the 2.12 version caches the array's length? Since the array's type argument is unbounded, calls to `.length` need to go through the `array_length` runtime method.

**Comment by szeiger** [comment]
It looks like the main difference is specialization of `apply`. Even though 2.12 has to box into `ArrayOps.ofInt` and its `apply` method will never be called externally, internal code such as the `Iterator` implementation benefits from the specialization. Manually specializing it (like we already did for some other `ArrayOps` methods in 2.13) brings the performance numbers much closer. I'm still seeing some inconsistencies depending on size though, so I'll dome some further experiments.

**Comment by szeiger** [comment]
Add specialization (`@specialized` + manual dispatch for the constructor is sufficient; I didn't see any improvements from manual specialization) and cache `length` and now it's consistently faster than in 2.12.6:

```
[info] Benchmark                                    (valueCount)   Mode  Cnt        Score       Error  Units
[info] ArrayIteratorBenchmarks.newArrayOpsIterator           100  thrpt    5  1570470.835 ± 56216.265  ops/s
[info] ArrayIteratorBenchmarks.newArrayOpsIterator         10000  thrpt    5    17663.422 ±   388.210  ops/s
[info] ArrayIteratorBenchmarks.newArrayOpsIterator       1000000  thrpt    5      184.145 ±     6.529  ops/s
[info] ArrayIteratorBenchmarks.newArrayOpsIterator      10000000  thrpt    5       18.134 ±     0.469  ops/s
[info] ArrayIteratorBenchmarks.scalaIterator                 100  thrpt    5  1393337.091 ± 47127.285  ops/s
[info] ArrayIteratorBenchmarks.scalaIterator               10000  thrpt    5    14407.301 ±   542.851  ops/s
[info] ArrayIteratorBenchmarks.scalaIterator             1000000  thrpt    5      159.706 ±     6.602  ops/s
[info] ArrayIteratorBenchmarks.scalaIterator            10000000  thrpt    5       15.745 ±     0.591  ops/s
```

**Comment by shawjef3** [comment]
@szeiger Great job!
