### ISSUE TITLE
Unintuitive, arguably broken inliner behavior

### ISSUE THREAD

**Issue by edmundnoble** [scala/bug#11121]
I expect that a method marked `@inline`, when called from code with `-opt-inline-from` set correctly, will be inlined. However, I was surprised to discover that this is not only not the case, but there wasn't even a warning triggered.

See here: https://github.com/scala/scala/blob/1e904d75450373d7845eb7452d940e52d955b27d/src/compiler/scala/tools/nsc/backend/jvm/opt/InlinerHeuristics.scala#L180

This code indicates to me that actually, marking a method as `@inline` does *nothing* to ensure it is inlined. The only thing it does is change the error message if it can't be inlined; but the error message is only ever emitted if the call-site is already marked inline.

The only way to have a method inlined is to mark the call-site as `@inline`, which contradicts the documentation (https://www.scala-lang.org/api/current/scala/inline.html).

Edit: There's another issue with the documentation: the `t3` definition is never inlined, unless using `-Yopt-inline-heuristics:everything`, in which case even the methods marked `@noinline` are inlined (which I verified experimentally and by looking at the same code).

I verified this in practice using a project of mine, in which adding definition-site `@inline` did nothing but call-site `@inline` worked.

Another odd quirk I noticed before I got it working is that only `final` methods are inlined, *even on `object`s*. This is bizarre considering that the only usage of `final` in `object` that I know of is to use `final val` for constant literal folding, and again there's no documentation of this.

I'm not sure if at this point the definition-site `@inline` can actually be fixed without breaking a lot of code at runtime, but documenting this and (perhaps?) removing the `final` restriction for methods on objects would be helpful.

Edit: To be clear, this is on Scala 2.12.4.

**Comment by hrhino** [comment]
Regarding the final defs in `object`s: we don't mark your method `ACC_FINAL` unless you actually say `final`, even though methods of static modules are effectively final:

```
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_161).
Type in expressions for evaluation. Or try :help.

scala> :pa -raw
// Entering paste mode (ctrl-D to finish)

object Fnord { def hodge = 2 ; final def podge = 3 }

// Exiting paste mode, now interpreting.


scala> :javap -c Fnord$
Compiled from "<pastie>"
public final class Fnord$ {
  public static Fnord$ MODULE$;

  public static {};
    Code:
       0: new           #2                  // class Fnord$
       3: invokespecial #12                 // Method "<init>":()V
       6: return

  public int hodge();
    Code:
       0: iconst_2
       1: ireturn

  public final int podge();
    Code:
       0: iconst_3
       1: ireturn
}
```

I recall someone saying there was a reason for keeping it this way. The optimizer doesn't know that much about the symbols from the rest of the compiler; I'm not sure if the information (whether it's in a static module) is easy to get from there.

**Comment by hrhino** [comment]
More responsively:

That block of code is (in your project, one hopes) switching on `-opt-inline-heuristics` being the `"default"`, in which case the decision is [this line](https://github.com/scala/scala/blob/1e904d75450373d7845eb7452d940e52d955b27d/src/compiler/scala/tools/nsc/backend/jvm/opt/InlinerHeuristics.scala#L218):

```scala
if (!callsite.isNoInlineAnnotated && (callsite.isInlineAnnotated || shouldInlineHO)) requestIfCanInline(callsite, reason)
```

`callsite.isInlineAnnotated` is a bit of a bad name, because it [actually checks](https://github.com/scala/scala/blob/1e904d75450373d7845eb7452d940e52d955b27d/src/compiler/scala/tools/nsc/backend/jvm/opt/CallGraph.scala#L369-L370) whether either the callsite _or_ the callee are thus annotated:

```scala
    // an annotation at the callsite takes precedence over an annotation at the definition site
    def isInlineAnnotated = annotatedInline || (callee.get.annotatedInline && !annotatedNoInline)
```

and from there we go into `requestIfCanInline`, which concerns itself with more specifics about whether inlining is even possible.

**Comment by edmundnoble** [comment]
I guess the problem is actually in `requestIfCanInline`, but I don't see why call-site inline works here when definition-site doesn't. Nor why `final` is required.

**Comment by hrhino** [comment]
Right. Assuming this is testz-related, if you can point me to methods that aren't inlining as expected, I'll take a look. This doesn't sound correct.

**Comment by edmundnoble** [comment]
Sure, mark any of the `test` methods in `*Suite` as `@inline` and it won't be inlined into `Main$`. Use this branch: https://github.com/edmundnoble/testz/tree/factor

**Comment by lrytz** [comment]
> I verified this in practice using a project of mine, in which adding definition-site @inline did nothing but call-site @inline worked.

I'd need a reproducer for that. This is pretty basic functionality of the inliner, and there's a large number of tests that would fail if your observation was generally true.

I see in your project you're using `-opt-inline-from:<sources>`, which can show surprising behavior with sbt's incremental compilation.



> only final methods are inlined, even on objects.

This is also not true in general, so there must be something else going on. Can you show how to reproduce?


```
➜  sandbox git:(pr7035) cat Test.scala
object A {
  @inline def f = 0
}

class C {
  def t1 = A.f
}

➜  sandbox git:(pr7035) scalac12 -opt:l:inline '-opt-inline-from:**' Test.scala
➜  sandbox git:(pr7035) cfr-decompiler C.class


    public int t1() {
        if (A$.MODULE$ == null) {
            throw null;
        }
        return 0;
    }

```

Please re-open when providing the examples.

**Comment by edmundnoble** [comment]
What I was seeing appears to be entirely artifacts of the incremental compiler; is that documented anywhere? As well, the edit I made still applies:

> Edit: There's another issue with the documentation: the t3 definition is never inlined, unless using -Yopt-inline-heuristics:everything, in which case even the methods marked @noinline are inlined (which I verified experimentally and by looking at the same code).

**Comment by lrytz** [comment]
> artifacts of the incremental compiler; is that documented anywhere?

Yeah, there's not enough documentation about what the optimizer does and how it works. I'm currnetly working on some improvements to the optimizer for 2.13, and it's also on my list to write down some details about its internals. I really hope to get to that.



> the t3 definition is never inlined

I can't follow the reference, where's t3 defined / used?
