### ISSUE TITLE
Update documentation for LazyList

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#11131]
Update scaladocs for `LazyList`, following up on scala/collection-strawman#367, scala/scala#7000, #11307, scala/scala#7558, and probably others.

---------

A non-exhaustive list of things to document:

- [x] which methods preserve laziness, and to what degree

**Comment by NthPortal** [comment]
I would love it if someone else volunteered to take this on - I would like to focus on ensuring that `LazyList` is properly lazy.

**Comment by NthPortal** [comment]
It would be really nice to have this done by final release. I guess I'll grab it for now and try to get it done, unless anyone else pipes up.

**Comment by NthPortal** [comment]
Reopening for some followup to scala/scala#7842

**Comment by SethTisue** [comment]
scala/scala#7842 was merged. @NthPortal feel free to reopen if you actively intend to address this sometime in the next month or two. otherwise, let's leave it closed, there are lots of things in stdlib that ideally would have better Scaladoc

**Comment by NthPortal** [comment]
@SethTisue I have no idea what the intended followup was, so I'm gonna leave it closed
