### ISSUE TITLE
Range API is weird

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#11138]
The API for `Range` allows you to call `by (x: Int)` on a `Range` to change the step, which is great. It allows you to say `1 to 10 by 2`, and get all of the odd numbers from 1 to 10.

However, it also allows you to do silly things like `1 to 10 by 1 by 4 by 7 by 2`, which is just ridiculous and it really shouldn't.

Ideally, there should be two types of `Range`: one with and one without a step, with `by(step: Int)` only defined on the one without a step. This would also allow you to use `Range` in APIs where you only want to allow a step of `1`, but still want to allow `Range`s for convenience.

**Comment by martijnhoekstra** [comment]
It seems kind of useful to be able to receive a range and then be able to set a step. `1 to 10 by 1 by 4 by 7 by 2` is IMO ridiculous in that there is no reason to do that (directly) not that you could if you wanted to.

Making ranges only allow you to change the range if the range was 1 (at compile time) makes no sense to me.

**Comment by szeiger** [comment]
I doubt it's worth the added complexity of having two separate types.
