### ISSUE TITLE
Raw string literals are not properly highlighted in code blocks in Scaladocs

### ISSUE THREAD

**Issue by Atry** [scala/bug#11144]
<img width="1085" alt="2018-09-13 09 34 55" src="https://user-images.githubusercontent.com/601530/45461973-64ae5b80-b738-11e8-91e5-85b36bf83193.png">

The single quoted `" Doe"` should be considered as a part of the enclosing raw string literal instead of code.

* [The Scaladoc link](https://static.javadoc.io/com.thoughtworks.dsl/dsl_2.12/1.0.0-RC19/com/thoughtworks/dsl/keywords/NullSafe.html)
* [The source code](https://github.com/ThoughtWorksInc/Dsl.scala/blob/v1.0.0-RC19/keywords-NullSafe/src/main/scala/com/thoughtworks/dsl/keywords/NullSafe.scala#L85)

**Comment by xuwei-k** [comment]
- https://github.com/scala/scala/blob/v2.13.0-M5/src/scaladoc/scala/tools/nsc/doc/html/SyntaxHigh.scala#L147-L164
- https://github.com/scala/scala/blob/v2.13.0-M5/src/scaladoc/scala/tools/nsc/doc/html/SyntaxHigh.scala#L252-L254
