### ISSUE TITLE
Include/explain iterator laziness in documentation

### ISSUE THREAD

**Issue by ksilin** [scala/bug#11145]
The [documentation of `Iterator#map`](https://www.scala-lang.org/api/current/scala/collection/Iterator.html#map[B](f:A=%3EB):Iterator[B]) explains the lazy nature correctly, once you know about iterator laziness already. However, the implications for side-effecting applications of `map` can surprise developers new to Scala (as it did surprise me)

An aside on the implications of laziness in the [Iterator overview docs](https://docs.scala-lang.org/overviews/collections/iterators.html#) would be very helpful.

**Comment by SethTisue** [comment]
note that scala/bug is normally used for issues actionable in the scala/scala repo, but this issue is actionable over at https://github.com/scala/docs.scala-lang

**Comment by ksilin** [comment]
Ah, I see. Thanks for pointing me in the right direction.  Closing in favor of https://github.com/scala/docs.scala-lang/issues/1145
