### ISSUE TITLE
Bind an object to ILoop

### ISSUE THREAD

**Issue by bes1002t** [scala/bug#11150]
I'm using the scala.tools.nsc.interpreter.ILoop to run REPL in my command line script. I saw that it is possible to bind an object to a IMain instance, but I can't find a way to do that with an ILoop instance.

I just wanna pass my tool context to the REPL instance so the user does not have to care about a login mechanism. If he starts my tool he is already logged in and could retrieve objects from the backend. So is there a way to bind a object to an ILoop instance? If not I would call this a bug because IMain provides this feature.

**Comment by som-snytt** [comment]
Use the `javax.script` API to create a context for a scripted REPL. It's not obvious how you want to use the context: have the REPL run some init code? You're starting the REPL programmatically? Or you just want to pass some credentials via system properties? I'd suggest taking this up on gitter.

I don't think 2.13+ REPL will have a different mechanism for storing arbitrary context, but it should be easier to customize the REPL to add your own. That's what I do for in-house tools. Also, probably fixed in Ammonite.

This just occurred to me:
```
scala> import javax.script._,scala.tools.nsc._,interpreter._
import javax.script._
import scala.tools.nsc._
import interpreter._

scala> val scripted = Scripted()
scripted: scala.tools.nsc.interpreter.Scripted = scala.tools.nsc.interpreter.Scripted@2078bf0a

scala> val b = scripted.createBindings
b: javax.script.Bindings = javax.script.SimpleBindings@18c0f025

scala> b.put("name","Fred")
res0: Object = null

scala> scripted.setBindings(b, javax.script.ScriptContext.GLOBAL_SCOPE)

scala> val repl = new ILoop
repl: scala.tools.nsc.interpreter.ILoop = scala.tools.nsc.interpreter.ILoop@643fed50

scala> val ss = new GenericRunnerSettings(println)
ss: scala.tools.nsc.GenericRunnerSettings =
Settings {
  -d = .
}

scala> repl.chooseReader(ss)
res2: scala.tools.nsc.interpreter.InteractiveReader = scala.tools.nsc.interpreter.jline.InteractiveReader@14ea3ecf

scala> repl.in = res2
repl.in: scala.tools.nsc.interpreter.InteractiveReader = scala.tools.nsc.interpreter.jline.InteractiveReader@14ea3ecf

scala> repl.intp = scripted.intp
repl.intp: scala.tools.nsc.interpreter.IMain = scala.tools.nsc.interpreter.Scripted$$anon$2@7f8586f9

scala> repl.getClass.getDeclaredFields.filter(_.getName.toString.contains("Fut"))
res6: Array[java.lang.reflect.Field] = Array(private scala.concurrent.Future scala.tools.nsc.interpreter.ILoop.globalFuture)

scala> res6.head.setAccessible(true)

scala> res6.head.set(repl, concurrent.Future.successful(true))

scala> repl.loop()

scala> 42
res0: Int = 42

scala> s"$name"
res1: String = Fred

scala> :q
res10: repl.LineResults.LineResult = ERR

scala> 
```
