### ISSUE TITLE
Multiple versions of Scala detected when importing from maven scala-compiler 2.11.12

### ISSUE THREAD

**Issue by adri242** [scala/bug#11176]
Given this dependency import from maven inside a pom.xml:
```
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-compiler</artifactId>
            <version>2.11.12</version>
        </dependency>
```
warning shown below is displayed:
```
[WARNING]  Expected all dependencies to require Scala version: 2.11.12
[WARNING]  org.scala-lang:scala-compiler:2.11.12 requires scala version: 2.11.12
[WARNING]  org.scala-lang.modules:scala-xml_2.11:1.0.5 requires scala version: 2.11.7
[WARNING] Multiple versions of scala libraries detected!
```
seems like the own dependency from scala-compile **2.11.12** is importing module scala-xml which requires scala version **2.11.7**

I know this is not an updated version of Scala but I require it to use **Apache Spark**

**Comment by SethTisue** [comment]
closing because as of Scala 2.13, there is no longer a dependency from scala-compiler to scala-xml

**Comment by SethTisue** [comment]
see also https://github.com/scala/scala-xml/issues/195 /cc @ashawley

**Comment by hrhino** [comment]
Also, 2.11.12 and 2.11.7 should be binary compatible, so the differing scala versions won't cause errors.

**Comment by ashawley** [comment]
I'm not a Maven user, myself, but the warning makes sense.  

Funny how sbt didn't ever complain about this, but I'm not an sbt expert either, so I'm sure there's some explanation.

I'll try to find some time to tinker with Maven and add something to the FAQ on the scala-xml Wiki.

**Comment by ashawley** [comment]
The warnings will go away if you use a newer version of scala-maven-plugin correctly.

The sample Maven project for scala-modules is improved:

https://github.com/scala/scala-module-dependency-sample/
