### ISSUE TITLE
Unused warning occurred even if the variable was used

### ISSUE THREAD

**Issue by tkrs** [scala/bug#11175]
Given the following code:

```scala
object Hello {
  for {
    a <- Option(1)
    b <- Option(2) if a == 1
  } yield a + b
}
```

Compiling with `-Ywarn-unused:params` on **2.12.7** gives the following warning:

```
[warn] /Users/tkrs/code/github.com/tkrs/hello/src/main/scala/Hello.scala:7:5: parameter value b in value$anonfun is never used
[warn]     b <- Option(2) if a == 1
[warn]     ^
[warn] one warning found
```

However, no warning occurred on **2.12.6**.

**Comment by som-snytt** [comment]
Thanks, I'm already taking a look, sigh. Someone brought up another issue, not sure if it's a ticket, but my response was that the current approach will remain brittle, short of a rewrite.

**Comment by som-snytt** [comment]
It snags the filtering expression:

```
Replaying: for (x <- Option(1); y <- Option(2) if x > 1) yield x + y
[[syntax trees at end of                    parser]] // <console>
        val res2 = Option(1).flatMap(((x) => Option(2).withFilter(((y) => x.$greater(1))).map(((y) => x.$plus(y)))))
```

The related umbrella issue https://github.com/scala/bug/issues/10287 is still open.

**Comment by manuchadha1979** [comment]
Hi

In which release this issue has been or is planned to be resolved?

regards

**Comment by dwijnand** [comment]
@manuchadha1979 this is currently targeting the 2.13.1 milestone, but it looks like no one has picked up fixing it yet.

**Comment by manuchadha1979** [comment]
Thanks. Would the current work around be either not to use the compiler option or not to use use the `for` comprehension?

**Comment by dwijnand** [comment]
It's your choice.

An alternative to not using the compiler option or not using the for comprehension is this:

```diff
 object Hello {
   for {
     a <- Option(1)
     b <- Option(2) if a == 1
+    useB = b // WORKAROUND scala/bug#11175 -Ywarn-unused:params false positive
   } yield a + b
 }
```

**Comment by som-snytt** [comment]
Modulo side-effects:
```
$ scala -Wunused:params

     ________ ___   / /  ___
    / __/ __// _ | / /  / _ |
  __\ \/ /__/ __ |/ /__/ __ |
 /____/\___/_/ |_/____/_/ | |
                          |/  version 2.13.0

scala> for (x <- Option(1); y <- Option(2) if x > 1) yield x + y
                            ^
       warning: parameter value y in anonymous function is never used
res0: Option[Int] = None

scala> for (x <- Option(1) if x > 1; y <- Option(2)) yield x + y
res1: Option[Int] = None
```

**Comment by joan38** [comment]
> It's your choice.
> 
> An alternative to not using the compiler option or not using the for comprehension is this:
> 
> ```diff
>  object Hello {
>    for {
>      a <- Option(1)
>      b <- Option(2) if a == 1
> +    useB = b // WORKAROUND scala/bug#11175 -Ywarn-unused:params false positive
>    } yield a + b
>  }
> ```

I used a `_` instead:
```
_ = b // Workaround scala/bug#11175 -Ywarn-unused:params false positive
```

**Comment by som-snytt** [comment]
Apologies to the 22 thumbs-up voters, who probably meant thumbs-down.

The technology was pushed to its limit.

Is it a coincidence that it topped out at 22, or does github use a Tuple?

**Comment by SethTisue** [comment]
consolidating here: #11175, #11400, #12018

**Comment by SethTisue** [comment]
consolidating at https://github.com/scala/bug/issues/10287
