### ISSUE TITLE
mutable ArraySeq cannot sort

### ISSUE THREAD

**Issue by Ichoran** [scala/bug#11187]
```
Welcome to Scala 2.13.0-20181002-132957-0036e7a (OpenJDK 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> val a = collection.mutable.ArraySeq(2, 1)
a: scala.collection.mutable.ArraySeq[Int] = ArraySeq(2, 1)

scala> a.sorted
java.lang.ClassCastException: [I cannot be cast to [Ljava.lang.Object;
  at scala.collection.mutable.ArraySeq.sorted(ArraySeq.scala:82)
  ... 41 elided
```

**Comment by Ichoran** [comment]
Note--the other sorts all have problems too (`sortWith`, `sortInPlaceBy`, etc.).  Hopefully it's just one mistake.  With some, only `ArraySeq` comes up in collections-laws; in others, `WrappedArray` also is affected.

**Comment by szeiger** [comment]
Keeping open because https://github.com/scala/scala/pull/7317 only tests `sorted`. The other methods could still be affected. We should also try to fix the compiler bug that causes this issue in the first place.
