### ISSUE TITLE
immutable maps have a dangerous remove method

### ISSUE THREAD

**Issue by Ichoran** [scala/bug#11189]
Immutable maps have a new method called `remove` that is dangerous when combined with mutable maps which have a side-effecting `remove`.  If you get your map type wrong, you will silently fail to modify your map with no error.

```
Welcome to Scala 2.13.0-20181002-132957-0036e7a (OpenJDK 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> val m = Map(3 -> "wish")
m: scala.collection.immutable.Map[Int,String] = Map(3 -> wish)

scala> m.remove(3)
res0: scala.collection.immutable.Map[Int,String] = Map()

scala> val mm = collection.mutable.Map(3 -> "wish")
mm: scala.collection.mutable.Map[Int,String] = HashMap(3 -> wish)

scala> mm.remove(3)
res1: Option[String] = Some(wish)

scala> mm
res2: scala.collection.mutable.Map[Int,String] = HashMap()
```

Immutable maps cannot have a `remove` method since the mutable map return value will often be ignored and hence the different return types cannot be used to catch the error.

**Comment by yhpark** [comment]
@exoego you mean add alias `removed`?

**Comment by exoego** [comment]
@yhpark Ah, yes.

**Comment by szeiger** [comment]
No need to deprecate, the method didn't exist yet in 2.12.

**Comment by szeiger** [comment]
There's also `removeAll` which needs to be renamed to `removedAll`. This method is also found in `immutable.Set` (where the remove-single-item method is called `excl`).

**Comment by Ichoran** [comment]
It follows the form of other methods (past tense is immutable), but I agree that it's clunky.  I wasn't able to think of a better alternative.

**Comment by som-snytt** [comment]
I apologize again for stripping the paint off the bike shed.

**Comment by szeiger** [comment]
I expect the names will be mostly used for implementing collections. Users will continue to use `-`. The difference in the new collections is that all symbolic methods also have a proper alphabetic name.
