### ISSUE TITLE
Partest kind-relative paths

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11184]
The basedir in `test` is the `test` dir. Either the basedir should be the root dir, or partest must strip leading `test/` from the path. It would be even better if we could specify `pos/A.scala` and just have it do the right thing. This business about where paths are relative to has plagued partest since its command-line days.

```
sbt:root> partest test/files/pos/A.scala
[info] Updating library...
[snip]
[info] Done compiling.
Discarding 1 invalid test paths
Partest version:     2.13.0-20181001-143853-7c8b36f
Compiler under test: $baseDir/compiler
Scala version is:    Scala compiler version 2.13.0-20181001-143853-7c8b36f -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.
[snip]
Selected 0 tests drawn from 

[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[success] Total time: 181 s, completed Oct 1, 2018 9:07:00 AM
```

**Comment by som-snytt** [comment]
Also, why didn't they ever make `[snip]` a logging level?

If you're outputting html, everything suppressed under snip could have a roll-up `[+]`icon to expand it.

**Comment by SethTisue** [comment]
is this fixed by https://github.com/scala/scala/pull/7298 ?

**Comment by som-snytt** [comment]
Since the fix was pre-existing, I was going to leave this open for the `partest pos/A.scala` feature. Typing `test/files` has gotten so old.

**Comment by som-snytt** [comment]
I guess there was a previous issue with basedir, which explains (and forgives) hrhino's confused expression. I don't remember that part, but I still want to type `partest pos/A<tab>` and benefit from autocomplete. That is so obvious to me. Maybe even just `A<tab>` completing for all kinds? Faster than `--grep`.

**Comment by dwijnand** [comment]
> but I still want to type `partest pos/A<tab>` and benefit from autocomplete. That is so obvious to me. Maybe even just `A<tab>` completing for all kinds? Faster than `--grep`.

Note scala/scala#9224 doesn't do that part (exercise for the reader? 😄)
