### ISSUE TITLE
Consider exhaustivity in match optimization, and turn last case into default

### ISSUE THREAD

**Issue by adriaanm** [scala/bug#11191]
The checks implied by the last case in an exhaustive match are useless, and could be elided.

Consider the simple example from https://gist.github.com/szegedi/477b8030d1bfab33cc6d44a78d9396f4, but it applies generally:

```
b match {
  case true  => 10
  case false => 11
}
```

is compiled to

```
if (b) 10
else if (!b) 11
else throw new MatchError(b)
```

We do a lot better on the equivalent:
```
b match {
  case true  => 10
  case _ => 11
}
```

exhaustiveness should be enough to conclude that `case false` (or any last case in an exhaustive match) could be replace by `case _`

**Comment by adriaanm** [comment]
The right spot to implement would be in `optimizeCases`. We currently don't do any DCE -- this would be a good start.

**Comment by sjrd** [comment]
What about `null`?

**Comment by szegedi** [comment]
`null` is not an issue. Scalac compiles `Boolean` to primitive JVM `boolean` type.

`case _` indeed produces better code, but feels like a workaround and still causes the weird `iconst_1; iload b; if_icmpne addr` sequence whereas it should compile identically to an if/else expression: `iload b; ifne addr`

**Comment by sjrd** [comment]
> Scalac compiles Boolean to primitive JVM boolean type.

Yeah I know ;) I was talking about match on non-primitive data types. Because honestly, the *only* primitive data type you can reasonably *exhaustively* match on is `Boolean`, and most of the time we use `if` for that purpose ;) If this issue is to have any impact, it must also be considering exhaustivity on sealed hierarchies. And for those, `null` is an issue.

**Comment by joroKr21** [comment]
I think I'd rather get a NPE any day of the week and reap the benefits of irrefutable pattern matching including (possibly) destructuring in for-comprehensions without `filter` but alas...

**Comment by dwijnand** [comment]
> If this issue is to have any impact, it must also be considering exhaustivity on sealed hierarchies. And for those, `null` is an issue.

Not just `null`.  In the face of separate compilation, what was exhaustive before could be inexhaustive later (e.g introducing a new leaf class to a sealed hierarchy) so this change would make whichever was the last `case` you define catch any new classes!

So I see 3 solutions here:
1. do it just for `Boolean`, which I think isn't worth it
2. do it but when a user opts-in to it (like `@switch`)
3. do it for sealed classes, but then add a way for sealed class definitions to _opt-out_ (cf https://github.com/lightbend/migration-manager/issues/200)

**Comment by viktorklang** [comment]
I don't think it works for @switch, since it will have to operate on Ints.

**Comment by szegedi** [comment]
> do it just for Boolean, which I think isn't worth it

It'd be totally worth to me as a user of the feature. In some situations `case true`/`case false` just feels like a better expression of intent, e.g. any operation on a monad encapsulating a boolean value can be expressed without having to bind the argument:
```
someBoolM map { 
  case true => …
  case false =>
}
```
but I'm reluctant to use it as I know it doesn't produce the best bytecode it could. I can get the best results with `case _`, but honestly it looks uglier. What I'm saying is I'd be all for having a special-case in the compiler for boolean. (But I'm also aware that talk is cheap and it's not me who's rolling up their sleeves to make it happen.)

**Comment by dwijnand** [comment]
I like pattern matching boolean too, but (just to qualify my statement a bit more) I think it's not worth it in terms of how much code I presume it would require in the compiler.

**Comment by adriaanm** [comment]
Agreed with dwijnand. Given the few cases (🙄) in which this would apply, I don't think it's worth complicating the pattern matcher. If someone submits an elegant implementation, I would be happy to have this improved.

**Comment by dwijnand** [comment]
An elegant implementation that does what?

Any sum type but `Boolean` can change its definition and that change can be in a separate compilation so this is only safe for:

* all pattern matching on `Boolean`, and
* any pattern matching on a sealed sum type within the same compilation unit of said type

Neither of which are worth it.

Anything else is unsafe as the default behaviour, so it would have to be some kind of opt-in annotation (or similar) by the user.  Is that what you had in mind?

**Comment by adriaanm** [comment]
I meant the stuff you think isn’t worth it :-) 

opt-ins shouldn’t affect code gen semantically. 

Given that, closing until someone motivated reopens.

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/8369 was abandoned, but could be picked up again by somebody
