### ISSUE TITLE
s String interpolator with "multi-line" String literal allows escape sequences

### ISSUE THREAD

**Issue by eed3si9n** [scala/bug#11197]
## steps

Scala 2.12.7

```scala
object Test extends App {
  def strict(s: String): Unit = println("strict : " + s)
  def byName(s: => String): Unit = println("by name: " + s)

  strict("""\t non-s multi-line""")
  byName("""\t non-s multi-line""")
  strict(s"""\t s multi-line""")
  byName(s"""\t s multi-line""")
}
```

## problem

```
[info] Running foo.Test
strict : \t non-s multi-line
by name: \t non-s multi-line
strict : 	 s multi-line
by name: \t s multi-line
```

## expectation

I'd expect "multi-line" triple-quoted s String interpolator to not allow escape sequence.

```
[info] Running foo.Test
strict : \t non-s multi-line
by name: \t non-s multi-line
strict : \t s multi-line
by name: \t s multi-line
```

## note

https://github.com/scala/bug/issues/11196 fixes it for by-name case by accident.

**Comment by som-snytt** [comment]
That is a common expectation, but the s-interpolator is [defined to process escapes](https://scala-lang.org/files/archive/api/2.12.7/scala/StringContext.html#s(args:Any*):String).

An interpolator doesn't ordinarily know what punctuation was used.

**Comment by Jasper-M** [comment]
I don't understand how this is possible...

```
scala> s"""\t s multi-line"""
res8: String = "	 s multi-line"

scala> (() => s"""\t s multi-line""")()
res9: String = \t s multi-line
```

**Comment by lrytz** [comment]
Something in UnCurry.

```
scala> s"""\t s multi-line"""
...
[[syntax trees at end of                 refchecks]] // <console>
...
        private[this] val res1: String = "\t s multi-line";
...
[[syntax trees at end of                   uncurry]] // <console>
...
        private[this] val res1: String = "\t s multi-line";
```

vs

```
scala> (() => s"""\t s multi-line""")()
...
[[syntax trees at end of                 refchecks]] // <console>
...
        private[this] val res2: String = (() => "\t s multi-line").apply();
...
[[syntax trees at end of                   uncurry]] // <console>
...
        private[this] val res2: String = {
  final <artifact> def $anonfun$res2(): String = "\\t s multi-line";
  (() => $anonfun$res2())
}.apply();
```

**Comment by lrytz** [comment]
So it's in `Typer.typed`. The rhs tree of the method is a `Literal("""\t s multi-line""")`, but it's type is a `ConstantType(String("\\t s multi-line"))`. The call to adapt creates a new literal with the escaped backslash:
![image](https://user-images.githubusercontent.com/119636/46791131-c0bccd80-cd40-11e8-9f5e-d6406097f999.png)

**Comment by lrytz** [comment]
I'll leave it at that for now :-) It's an issue with the initial type checking of the tree generated by the parser, which pretty-prints as `(() => StringContext("\\t s multi-line").s())()`

**Comment by som-snytt** [comment]
Duplicates scala/bug#11196

The expected change in behavior is SIP territory. or SipHash, or SipHack.
