### ISSUE TITLE
both method get(ActorSystem) in Cluster and method get(ActorSystem) in Cluster match

### ISSUE THREAD

**Issue by oryjk** [scala/bug#11198]
my env  jdk 11, scala 2.12.7 and akka 2.5.17, when gradle build,  an error occur:<p>
<b>both method get(ActorSystem) in Cluster and method get(ActorSystem) in Cluster match</b><p>
jdk8 is ok

**Comment by eed3si9n** [comment]
Could you post the snippet that you're trying to compile?

**Comment by oryjk** [comment]
@eed3si9n 
![image](https://user-images.githubusercontent.com/6252789/46723371-4477ab00-ccaa-11e8-8940-8914e21154eb.png)

**Comment by oryjk** [comment]
package com;

import akka.actor.AbstractActor;
import akka.cluster.Cluster;

public class snippet extends AbstractActor {

@eed3si9n 
    private Cluster cluster = Cluster.get(getContext().getSystem());

    @Override
    public Receive createReceive() {
        return receiveBuilder().match(String.class, message -> {
            System.out.println(cluster);
        }).build();
    }
}

**Comment by SethTisue** [comment]
how exactly would I reproduce the problem on my own computer? I got as far as trying `javac -classpath /Users/tisue/.ivy2/cache/com.typesafe.akka/akka-actor_2.12/jars/akka-actor_2.12-2.5.16.jar snippet.java`, but that isn't enough, I need some Akka Cluster JAR too, it looks like. this isn't actionable unless you provide compiled

it's certainly *possible* that once someone gets to the bottom of this, it'll turn out that some Scala bug responsible. or maybe it's an Akka issue, or a Java issue, who knows? right now this doesn't qualify as bug report against Scala, it looks like more of a support request involving multiple technologies and multiple libraries. I'm sorry but we can't accept those here. I wish you luck in getting to the bottom of this.

**Comment by SethTisue** [comment]
heh, it is a Scala bug! looks like a duplicate of https://github.com/scala/bug/issues/11061

**Comment by SethTisue** [comment]
looks very similar to https://github.com/scala/bug/issues/11061, which was supposed to be fixed in 2.12.7, maybe some form of it isn't fixed?

also, that issue illustrates what I mean by "complete, specific instructions for reproducing"

**Comment by oryjk** [comment]
hi @SethTisue， there is full code and reproducing this the problem,<b>
 https://github.com/oryjk/scala_build_with_jdk11.git

**Comment by johanandren** [comment]
I wrote in the Akka ticket as well, but FYI the problem is that the used Akka version was compiled with 2.12.6 so the Akka classfiles contains the error even if your project uses Scala 2.12.7 where the bug has been fixed.

**Comment by oryjk** [comment]
link to https://github.com/akka/akka/issues/25777

**Comment by SethTisue** [comment]
thanks Johan, glad we could get this sorted out
