### ISSUE TITLE
s String interpolator takes backslash literally when used with by-name parameter

### ISSUE THREAD

**Issue by eed3si9n** [scala/bug#11196]
This was originally reported to sbt as "sbt logger does super weird stuff with string context without interpolation" - https://github.com/sbt/sbt/issues/4371

## steps

```scala
package foo

object Test extends App {
  def strict(s: String): Unit = println("strict: " + s)
  def byName(s: => String): Unit = println("by name: " + s)

  strict(s"\tdo homework")
  byName(s"\tdo homework")
}
```

## problem

From sbt:

```
> ++2.12.5!
> run
[info] Running foo.Test
strict: 	do homework
by name: \tdo homework
```

## expectation

```
> ++2.12.4!
> run
[info] Running foo.Test
strict: 	do homework
by name: 	do homework
```

## notes

Ref https://github.com/scala/scala/pull/6093

**Comment by dwijnand** [comment]
Where is the s String interpolator in the steps?

**Comment by som-snytt** [comment]
I took a swing. TIL `FoldableConstantType`.

**Comment by SethTisue** [comment]
and https://github.com/scala/scala/pull/7335

**Comment by som-snytt** [comment]
I'm sad when @SethTisue doesn't happy face my "take a swig" comment. Oh, never mind, it turns out I can happy face my own comment, how perverse is that? But now I'm happy.
