### ISSUE TITLE
Exhaustivity checking gives up with unapply

### ISSUE THREAD

**Issue by skilldrick** [scala/bug#11208]
It looks like the compiler stops trying to check for exhaustivity when it encounters an unapply:

```
object TestCase {
  class Object(val str: String) {}

  object Object {
    def apply(str: String) = new Object(str)

    def unapply(obj: Object): Option[String] =
      Some(obj.str)
  }

  sealed trait Trait

  case class A(obj: Object) extends Trait
  case class B(obj: Object) extends Trait

}

object Test {
  import TestCase._

  val a: Trait = A(Object("foo"))

  // Compiles
  // Note: if `Object` is a case class, this option also fails compilation
  a match {
    case B(Object(str)) => str
  }

  // Fails compilation with "match may not be exhaustive"
  a match {
    case B(obj) => obj.str
  }
}
```

I understand that the typechecker can't know if `unapply` will match, it should be able to see that 

```
  a match {
    case B(Object(str)) => str
  }
```

is not exhaustive.

Scala version: 2.11.11

**Comment by smarter** [comment]
In this particular case, you can let the compiler know that your unapply will always match by using Some in the result type:
```scala
    def unapply(obj: Object): Some[String] =
      Some(obj.str)
```
In general, there's many open issues with the exhaustiveness checker in Scala, and it's unlikely that they will be fixed before Scala 3 with its rewritten exhaustiveness checker is released.

**Comment by skilldrick** [comment]
Oh wow, the `Some` return type fixes it! Thanks for the response.
