### ISSUE TITLE
Type parameter bound check regression in Scala 2.13.0-M5

### ISSUE THREAD

**Issue by xerial** [scala/bug#11202]
When checking Java's type parameter bound, Scala 2.13.0-M5 shows this kind of error:
```
[error] /Users/leo/work/git/airframe/airframe-jmx/src/main/scala/wvlet/airframe/jmx/JMXMBean.scala:79:26: inferred type arguments [javax.management.JMX] do not conform to method getAnnotation's type parameter bounds [A <: java.lang.annotation.Annotation]
[error]     val description = cl.getAnnotation(classOf[JMX]) match {
[error]                          ^
[error] /Users/leo/work/git/airframe/airframe-jmx/src/main/scala/wvlet/airframe/jmx/JMXMBean.scala:79:47: type mismatch;
[error]  found   : Class[javax.management.JMX](classOf[javax.management.JMX])
[error]  required: Class[A]
```
https://github.com/wvlet/airframe/blob/5ca3143788b4768fb3ea3096138c759764c29e40/airframe-jmx/src/main/scala/wvlet/airframe/jmx/JMXMBean.scala#L79

`JMX` in the above error is a Java annotation definition like this:
https://github.com/wvlet/airframe/blob/083f50ad452bab07a6c9f4bb436bb245e78a2e2d/airframe-jmx/src/main/scala/wvlet/airframe/jmx/JMX.java#L24

`Class.getAnnotation` in JDK (Class.java) uses the following definition:
```java
    public <A extends Annotation> A getAnnotation(Class<A> annotationClass) {
        Objects.requireNonNull(annotationClass);

        return (A) annotationData().annotations.get(annotationClass);
    }
```

In this example:
- JMX is a Java annotation 
- When calling Class.getAnnotation(classOf[JMX]) shows the above error in Scala 2.13.0-M5, even though JMX should be an extension of Java's Annotation.
- This error didn't happen in Scala 2.13.0-M4 or prior.

== (update)
I've found the above error is referencing different type (javax.management.JMX), but my expectation was resolving wvlet.airframe.jmx.JMX.

It seems the import order might have been changed since Scala 2.13.0-M5.

**Comment by xerial** [comment]
Let me close the issue. It seems this is not the type bound check error, rather the import order precedence has changed since Scala 2.13.0-M5

**Comment by SethTisue** [comment]
sounds like https://github.com/scala/scala/pull/6589
