### ISSUE TITLE
About Java static code block

### ISSUE THREAD

**Issue by Charele** [scala/bug#11221]
Hi, I meet a question,some Java code, I need rewrite them by Scala,
But I find can't complete if Java code with static code block.

For example: Java
class xxx {
	static {		
		System.out.println("xxx class static code block exec!!!");		
	}	
}

I can write a Scala class xxx,but where I put that println statement???

**Comment by hrhino** [comment]
The `static` members of a Java class roughly correspond to members of an `object` in Scala. Statements in an `object` are run as part of its initialisation, and are roughly equivalent to a `static { ... }` block in Java. So your code roughly corresponds to:

```scala
object xxx {
  println("...")
}
```

That said, this is a bug tracker, not a place to ask for help. These sorts of questions are better asked on [StackOverflow](https://stackoverflow.com) or [gitter](https://gitter.im/scala/scala).

**Comment by Charele** [comment]
How do you do!
Are you sure you understand my question really?

My test:
class xxx 
object xxx {
  println("??????")
}
object test111 extends App {
  
  println("begin...")
  new xxx
  new xxx
  println("byebye!")
}

The result is:
begin...
byebye!
