### ISSUE TITLE
Unreachable code false positive while pattern matching on a sealed trait extending another sealed trait

### ISSUE THREAD

**Issue by MouslihAbdelhakim** [scala/bug#11229]
compiling the below code throws a  `warning: unreachable code
       case _:AB => false`

```scala
sealed trait A
sealed trait AB extends A
sealed trait AA extends A
def f(a: A): Boolean = a match {
     case _:AA => true
     case _:AB => false
}
```
while testing the function show that both branches are reachable.

```scala
scala> f(new AB{} )
res0: Boolean = false

scala> f(new AA{} )
res1: Boolean = true
```

This behavior is reproducible on 2.11 and 2.12, and only if all traits are `sealed`

**Comment by coreyoconnor** [comment]
I was able to reproduce this on 2.13.0.

**Comment by dwijnand** [comment]
Looking at this again, I think the REPL behaviour is wrong, I described it more on https://github.com/lampepfl/dotty/issues/10145.

**Comment by dwijnand** [comment]
I don't think this is worth spending time on.  The code is unreachable until you bypass the sealedness in the REPL.
