### ISSUE TITLE
Incorrect unboxing of java primitives

### ISSUE THREAD

**Issue by simpadjo** [scala/bug#11236]
```
 val boxed: java.lang.Integer = null
 val unboxed : Int = boxed
 println(unboxed)
```
Prints `0` in scala 2.12.4, 2.12.7
Throws `NullPointerException` in 2.12.0 as expected.

**Comment by lrytz** [comment]
This is actually a feature, and it was fixed. Possibly in https://github.com/scala/scala/pull/5176.
