### ISSUE TITLE
REPL redefinition of classes does not propagate (even on def's, not just val's)

### ISSUE THREAD

**Issue by Akrome** [scala/bug#11231]
Putting this in repl:

`class Wrapped {
  def fruit = "Apple"
}`
`class Wrapper {
  def wrapped = new Wrapped()
}`
`class Wrapped {
  def fruit = "Banana"
}`
`val w = new Wrapper()`
`w.wrapped.fruit`

I would expect the output to be "Banana", but I get "Apple".

I understand that it's probably due to the fact that the bytecode for Wrapper still points to the "old" bytecode for Wrapped. This seems confirmed by the fact that doing:

Putting this in repl:

`class Wrapped {
  def fruit = "Apple"
}`
`class Wrapper {
  def wrapped = new Wrapped()
}`
`class Wrapped {
  def fruit = "Banana"
}`
`class Wrapper {
  def wrapped = new Wrapped()
}`
`val w = new Wrapper()`
`w.wrapped.fruit`

Actually yield "Banana" as expected. Is this intended? Is there an option or flag to enable that allows redefinition to happen at the classloader level (or something equally magical) so that if I redefine a class then it's redefined everywhere?

**Comment by SethTisue** [comment]
What looks like redefinition here isn't, it's merely shadowing. The REPL is just a series of nested scopes, growing ever deeper.

We'd need http://openjdk.java.net/jeps/159. There's JRebel, but it's commercial.

Note that in general we prefer that questions like this go on https://users.scala-lang.org (or https://contributors.scala-lang.org, if you are seriously considering making the change yourself), scala/bug is for bugs you're already reasonably certain are actual bugs.

**Comment by som-snytt** [comment]
To say more, each line gets its own package, and `Wrapper` is compiled against the preceding line.

On the value level, my preferred repl models each line as a function in its dependencies from history. When you evaluate the line, you pick up variables scoped from history.

I haven't tried this, but you could do the same thing at type level, where a dependency results in recompilation. That's helpful in interactive mode, but would hurt performance in batch mode, such as when running a script.

Maybe batch mode could issue a warning when recompilation is required.
