### ISSUE TITLE
Rename transformValues in AnyRefMap/LongMap

### ISSUE THREAD

**Issue by lrytz** [scala/bug#11244]
The method names should be `somethingInPlace`

**Comment by szeiger** [comment]
We already have this:
```scala
  @deprecated("Use mapValuesInPlace instead", "2.13.0")
  @inline final def transform(f: (K, V) => V): this.type = mapValuesInPlace(f)
```
I think it's misnamed. This should be `mapInPlace` and `transformValues` should be `mapValuesInPlace`.

**Comment by julienrf** [comment]
It’s not really a `mapInPlace` because the return type of the function is `V`, not `(K, V)`.

**Comment by szeiger** [comment]
On second thought `mapValuesInPlace` *produces* only values but takes keys and values like other `map` methods. So maybe `transformValues` should be `transformValuesInPlace`.
