### ISSUE TITLE
Introduce `scala.control` package?

### ISSUE THREAD

**Issue by He-Pin** [scala/bug#11250]
Then migrate some classes in `scala.util.control` to `scala.control` and unleash the potential modulation of `scala.util`.

**Comment by hepin1989** [comment]
Like `scala.util.control.NonFatal` then wil be `scala.control.NonFatal`

**Comment by NthPortal** [comment]
@som-snytt I believe `scala.runtime` is only for the runtime implementation generated by the compiler - it is not considered a stable, public API.

**Comment by som-snytt** [comment]
@NthPortal I was thinking of `NonLocalReturnControl`, but now I see it's already in `runtime`.

**Comment by som-snytt** [comment]
"Out of scope for Scala 2."
