### ISSUE TITLE
Future's Flatmap is not stacksafe

### ISSUE THREAD

**Issue by hepin1989** [scala/bug#11256]
```
@RunWith(classOf[JUnit4])
class Stacksafe {

  @Test
  def testFib(): Unit = {
    implicit val ex: ExecutionContext = new ExecutionContext {
      override def execute(runnable: Runnable): Unit = runnable.run()
      override def reportFailure(cause: Throwable): Unit = cause.printStackTrace()
    }

    def fib(n: Int, a: Long = 0, b: Long = 1): Future[Long] =
      Future(a + b).flatMap { b2 =>
        if (n > 0)
          fib(n - 1, b, b2)
        else
          Future(b2)
      }

    val future = fib(1000)
    println(Await.result(future,Duration.Inf))
  }
}
```
It's ok with 100,but not 1000

**Comment by hepin1989** [comment]
https://github.com/scala/bug/issues/6932

**Comment by viktorklang** [comment]
This is not a bug. Your Execution context is not stack safe.

**Comment by viktorklang** [comment]
Think of ExecutionContext as the Interpreter, where the "next actions" enter through `execute` and execution of the Runnable can lead to more calls to `execute`. Therefor it is the responsibility of the implementor of ExecutionContext to make sure that it is stack safe / reentrant.

**Comment by hepin1989** [comment]
@viktorklang I try this because of `Task` or `IO` claims they are, so I take a try. I think to fix this will change so much, may not worth it.

**Comment by hepin1989** [comment]
> This is not a bug. Your Execution context is not stack safe.
Seems it's `by design`:)

**Comment by hepin1989** [comment]
thanks, I was expecting it will be safe in any way.

**Comment by hepin1989** [comment]
@viktorklang So,now anyone want to make it safe then will need to take care of the `Batchable`:)

**Comment by viktorklang** [comment]
@hepin1989 Not necessarily :) Most thread pools are stack safe by definition since they add new Runnables to a queue. (just like the BatchingExecutor does).

**Comment by hepin1989** [comment]
@viktorklang But I do expect even I call `runnable.run` directly, it works too.

**Comment by viktorklang** [comment]
@hepin1989 

>A general purpose ExecutionContext must be asynchronous in executing any Runnable that is passed into its execute-method. A special purpose ExecutionContext may be synchronous but must only be passed to code that is explicitly safe to be run using a synchronously executing ExecutionContext.
--https://www.scala-lang.org/api/current/scala/concurrent/ExecutionContext.html
