### ISSUE TITLE
Pattern matching unaware of user-defined unapply

### ISSUE THREAD

**Issue by dwijnand** [scala/bug#11252]
As of https://github.com/scala/scala/pull/5816, which shipped in Scala 2.12.2, it's possible for users to define their own `apply` and `unapply` methods in case companions.

However, it looks like the pattern matcher isn't aware of this:

```scala
Welcome to Scala 2.12.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_144).
Type in expressions for evaluation. Or try :help.

scala> :pa
// Entering paste mode (ctrl-D to finish)

final case class Ttl(duration: Int, other: Boolean)

object Ttl {
  def apply(duration: Int) = new Ttl(duration, false)

  def unapply(x: Ttl): Option[Int] = if (x eq null) None else Some(x.duration)
}

// Exiting paste mode, now interpreting.

defined class Ttl
defined object Ttl

scala> Ttl(1) match { case Ttl(y) => println(y) }
<console>:13: error: wrong number of arguments for pattern Ttl(duration: Int,other: Boolean)
       Ttl(1) match { case Ttl(y) => println(y) }
                              ^

scala> Ttl.unapply(Ttl(1))
res1: Option[Int] = Some(1)
```

The context is being able to evolve a class but retain binary compatibility-in the real code (akka/akka) the class is `abstract` (and `sealed`) so there's no `copy` method either, as it isn't bincompat safe.

**Comment by ashwinbhaskar** [comment]
@adriaanm Can you help me out by telling which class I need to touch to fix this?

**Comment by dwijnand** [comment]
The wrong number of arguments errors comes from https://github.com/scala/scala/blob/v2.12.7/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L5234.

**Comment by adriaanm** [comment]
Actually, compiling with `scalac -Xprompt` points at (for 2.13.0-M5):

https://github.com/scala/scala/blob/v2.13.0-M5/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L3409

```
	at scala.tools.nsc.typechecker.Typers$Typer.tryNamesDefaults$1(Typers.scala:3409)
	at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3499)
	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4728)
	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4737)
```

**Comment by adriaanm** [comment]
I didn't have time to dig deeper, but this at least seems to fix the problem where it occurs. There are a lot of assumptions that case classes don't actually have unapply's, so maybe recovering from that wrong assumption is the best we can do...

```
            else if (mode.inPatternMode) {
              // we may have an unapply we haven't tried yet, as we went straight to the constructor in normalTypedApply
              // by setting pt to the type of the class
              tree match {
                case Apply(origFun, _) =>
                  val funTyped = typed(origFun, mode)
                  funTyped.tpe match {
                    case HasUnapply(unapply) => doTypedUnapply(tree, fun0, funTyped, args, mode, pt)
                    case _ => duplErrorTree(WrongNumberOfArgsError(tree, fun)) // #2064
                  }
                case _ => duplErrorTree(WrongNumberOfArgsError(tree, fun)) // #2064
              }
            }
```

**Comment by ashwinbhaskar** [comment]
@adriaanm Your solution works! I am a newbie in 'contributing to scala'. I have good experience in scala but I am not able to make out what this class Tree does. How do I get about making myself familiar with the flow. Is there any documentation that you can point me to.

**Comment by adriaanm** [comment]
To learn more about the Scala compiler data structures, I recommend the dotty videos. They are more recent but the concepts are mostly the same. http://dotty.epfl.ch/docs/resources/talks.html#deep-dive-with-dotty  (A long time ago, we also recorded similar videos on scalac: https://www.scala-lang.org/old/node/598.html)

**Comment by dwijnand** [comment]
Tweet that. 😄

**Comment by adriaanm** [comment]
Go for it, I won't have twitter access until I get home ;-)

**Comment by dwijnand** [comment]
All yours, @ashwinbhaskar! (The Scala Team is busy finishing the last tasks for 2.13.0-RC1.)

**Comment by som-snytt** [comment]
I can't tell if @dwijnand was saying, "Go ahead and tweet the links to the talks!" or "Go ahead and work on the bug!"

The fix seems to run into the [autotupling in patterns question](https://github.com/scala/bug/issues/6675) which was supposed to be laid to rest in 2.12 but there's no time like the present.

For the negative case of smooshing two args into one, "wrong number of args" error is accommodated as a warning, oh sorry it crushes (not smushes) the args of the synthetic apply, [here](https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/transform/patmat/PatternExpansion.scala#L229).

For the uncrushable case, the third test failure with a constant arg, the message is arguably degraded.

Otherwise, totally crushing it!

What did Adriaan say when he unwrapped a nice watch under the tree?  "There's no present like the time!"

**Comment by SethTisue** [comment]
@ashwinbhaskar do you plan to make a second stab at this, or is it up for grabs again?

**Comment by ashwinbhaskar** [comment]
@SethTisue : It is up for grabs:)

**Comment by retronym** [comment]
@dwijnand Here's how to correct the assumption that a non-overloaded unapply method of a case companion must be the synthetic one

```diff
--- a/src/compiler/scala/tools/nsc/typechecker/PatternTypers.scala
+++ b/src/compiler/scala/tools/nsc/typechecker/PatternTypers.scala
@@ -93,7 +93,7 @@ trait PatternTypers {
       // Dueling test cases: pos/overloaded-unapply.scala, run/case-class-23.scala, pos/t5022.scala
       // A case class with 23+ params has no unapply method.
       // A case class constructor may be overloaded with unapply methods in the companion.
-      if (canElide && caseClass.isCase && !member.isOverloaded)
+      if (canElide && caseClass.isCase && !member.isOverloaded && member.isCaseApplyOrUnapply)
         logResult(s"convertToCaseConstructor($fun, $caseClass, pt=$pt)")(convertToCaseConstructor(fun, caseClass, pt))
       else if (!reallyExists(member))
         CaseClassConstructorError(fun, s"${fun.symbol} is not a case class, nor does it have an unapply/unapplySeq member")
```

The example in above compiles to;

```
 object Client extends scala.AnyRef {
    def <init>(): Client.type = {
      Client.super.<init>();
      ()
    };
    {
      case <synthetic> val x1: Ttl = Ttl.apply(1);
      case5(){
        <synthetic> val o7: Option[Int] = Ttl.unapply(x1);
        if (o7.isEmpty.unary_!)
          {
            val y: Int = o7.get;
            matchEnd4(scala.Predef.println(y))
          }
        else
          case6()
      };
      case6(){
        matchEnd4(throw new MatchError(x1))
      };
      matchEnd4(x: Unit){
        x
      }
    }
  }
}
```
