### ISSUE TITLE
Move `scala.util.Try` and `scala.util.Either` to `scala` package. 

### ISSUE THREAD

**Issue by He-Pin** [scala/bug#11268]
#### Problem

Currently, these standard types are not top level and live in `scala.util.*` package. They should live in the top level.

#### Perposal

Move `scala.util.Try` and `scala.util.Either` to `scala` package,and annotation type alias in `scala.util`'s package object to keep code compile,until we decide what's next move.

**Comment by hepin1989** [comment]
Also refs :https://github.com/scala/scala-dev/issues/323

**Comment by dwijnand** [comment]
> They should live in the top level.

Why?

Note that `Either` is already aliased in the `scala` package object (and `Try` isn't).

**Comment by hepin1989** [comment]
@dwijnand I first came out with this idea and there is some discussion in https://github.com/scala/scala/pull/5677 too.

>scala.util (Try and Either move to the scala package)

I think these common types live in `scala.util` seems a little wired and especially there are many other not that much common sibling types live there.

**Comment by hepin1989** [comment]
BTW, there is `https://github.com/vavr-io/vavr/tree/master/vavr/src/main/java/io/vavr/control` which mostly alias with scala's type layout, cc @danieldietrich .

**Comment by som-snytt** [comment]
I think you mean `scala.util.chaining._`. I feel like I'm not living as well as I ought.

Now there is `-Yimports:scala.util,scala.util.chaining` which at least takes the sting out of REPL sessions.

**Comment by SethTisue** [comment]
perhaps we could have made a different decision here initially, but I don't see good cost/benefit in changing it now
