### ISSUE TITLE
The Generated Anyvals,such as`Int`,`Long`,'s `+(s:String)` method should start with a new line.

### ISSUE THREAD

**Issue by hepin1989** [scala/bug#11267]
#### Problem:

Currently, the lark of a new line in `GenerateAnyVals` make the methods hard to find.

https://github.com/scala/scala/blob/1d46b3bd979e0ac30c37c2e763d78309eeae86ec/src/library/scala/Int.scala#L49

![image](https://user-images.githubusercontent.com/501740/48907699-302aee80-eea3-11e8-849d-56b5659d7795.png)

#### Expectation:

The methods start with a new line to keep consistency.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/7448
