### ISSUE TITLE
Change to bash launcher script to support newlines in JAVA_OPT settings

### ISSUE THREAD

**Issue by philwalk** [scala/bug#11261]
The feature I'm requesting is a one line insertion in bin/scala that would permit a use case that is currently not supported.   The problem and solution are described on this StackOverflow page: 

[how-to-pass-line-separator-to-the-jvm-via-bash-variable-java-opts](https://stackoverflow.com/questions/53343645/how-to-pass-line-separator-to-the-jvm-via-bash-variable-java-opts-with-no-interp)

The change would permit the use of encoded newlines within command line arguments.   It consists of the insertion of the following line immediately prior to the  call to execCommand, near the bottom of the script:

`IFS=' '`

Here's the new line following by the existing code that it's immediately prior to:

```
IFS=' '
execCommand \
  "${JAVACMD:=java}" \
  $JAVA_OPTS \
  "${java_args[@]}" \
  "${classpath_args[@]}" \
  -Dscala.home="$SCALA_HOME" \
  $OVERRIDE_USEJAVACP \
  $WINDOWS_OPT \
   scala.tools.nsc.MainGenericRunner  "$@"
```
The effect is to define the IFS (Internal Field Separator) as one or more spaces, but to disallow newlines to be treated as spaces.     This supports use cases of property settings with included newlines.   The use case of immediate interest for me is that I'd like to be able to append to JAVA_OPTS like this:

`JAVA_OPTS="$JAVA_OPTS "-Dline.separator=$'\n'`

Currently, my only recourse is to edit the distributed scala bash script after installation.
Thanks for your consideration!

**Comment by som-snytt** [comment]
I took advantage of the occasion to reread the bash manual and submit a PR.

Normally, it's hard to create a JAVA_OPTS with an embedded newline, but less hard with a tab, so I kept tab as a separator.

The other temptation is not to support this use case, since `-J-Dline.separator` works, and perhaps deprecate `JAVA_OPTS`, or to specify that only normal bash word splitting is supported.

OTOH, the change is simple, and although there must be unintended consequences, I don't see any at the moment.

**Comment by philwalk** [comment]
I'm not able to get the -J-Dline.separator to work.   Here's my test
script, and what it prints normally (without the -J-Dline.separator):
```

#!/usr/bin/env scala
val bytes = sys.props("line.separator").map { _.toInt }.mkString(" ")
printf("line.separator bytes: %s\n",bytes)

```

`line.separator bytes: 13 10`

Here's what I'm passing to the scala launcher script:

`-J-Dline.separator=$'\n'`

With this version of the script, I have a different problem:

```

#!/bin/bash
  IFS=' '
  source `which scala` -J-Dline.separator=$'\n' "$@"
!#
val bytes = sys.props("line.separator").map { _.toInt }.mkString(" ")
printf("line.separator bytes: %s\n",bytes)

```

Here's the result:

`No such file or class on classpath:`

If there's a way to get this script to work without any changes to
bin/scala, we can close this, but I haven't found it yet.

Also, if someone documents a working solution to my question on
StackOverflow, I'll give them credit.

Phil

**Comment by philwalk** [comment]
I'm not able to get the -J-Dline.separator to work, at least not with a newline value.
Here's my test script, and what it prints normally (without the -J-Dline.separator):

```
#!/usr/bin/env scala
val bytes = sys.props("line.separator").map { _.toInt }.mkString(" ")
printf("line.separator bytes: %s\n",bytes)
```

`line.separator bytes: 13 10`

Here's what I'm passing to the scala launcher script:
…

`-J-Dline.separator=$'\n'`

With this version of the script, I have a different problem:

```
#!/bin/bash
  IFS=' '
  source `which scala` -J-Dline.separator=$'\n' "$@"
!#
val bytes = sys.props("line.separator").map { _.toInt }.mkString(" ")
printf("line.separator bytes: %s\n",bytes)

```

Here's the result:

`No such file or class on classpath:
`
If there's a way to get this script to work without any changes to
bin/scala, we can close this, but I haven't found it yet.

Also, if someone documents a working solution to my question on
StackOverflow, I'll give them credit.

Phil

**Comment by som-snytt** [comment]
I'd have to look at `#!` interaction. What I verified:

```
snips $ cat helloworld.sc 
println("hello")
println("world")
snips $ scalam -J-Dline.separator=$'\r'$'\n' helloworld.sc  > hw.out
snips $ hexdump -C hw.out
00000000  68 65 6c 6c 6f 0d 0a 77  6f 72 6c 64 0d 0a        |hello..world..|
0000000e
snips $ echo $JAVA_OPTS

snips $ export JAVA_OPTS=-Dline.separator=$'\r'$'\n'
snips $ scalam helloworld.sc  > hw.out
snips $ hexdump -C hw.out
00000000  68 65 6c 6c 6f 0d 77 6f  72 6c 64 0d              |hello.world.|
0000000c
snips $ vi ~/scala-2.13.0-M5/bin/scala
snips $ scalam helloworld.sc  > hw.out
snips $ hexdump -C hw.out
00000000  68 65 6c 6c 6f 0d 0a 77  6f 72 6c 64 0d 0a        |hello..world..|
0000000e
```

**Comment by philwalk** [comment]
Tom,
Thanks for the feedback.  A few questions:
what is `scalam`?   that might be relevant.
Also, is your environment cygwin?   I assume you're testing with a Windows JVM (otherwise, it's not relevant to this issue).
In your examples, you're specifying Carriage Return and Linefeed, which is the default anyway (on Windows JVM), although you second example seems to show a problem (the linefeed is being discarded, no surprise there).
What happens when you specify only a newline?

**Comment by som-snytt** [comment]
To follow up, the example on mac or linux shows correct usage of `-J`, then the `-D` getting stripped in latest milestone, then after editing IFS, `-D` works as intended.

**Comment by philwalk** [comment]
Thanks for this!
I verified the fix in a Windows 10, cygwin64 bash shell, scala 2.12.8, jvm 1.8.0_191 environment.
BTW, I have success using -D but not -J (not sure why, but it doesn't matter to me at this point anyway).

**Comment by philwalk** [comment]
Unfortunately, this is not quite fixed yet.   I have been using '-savecompiled' which can mask the problem by creating a compiled jar file, which then hides the problem in subsequent tests.

Here's my test script, which I named `lineSeparator.sc`:

```
#!/usr/bin/env scala
val bytes = sys.props("line.separator").map { _.toInt }.mkString(" ")
printf("line.separator bytes: %s\n",bytes)
```
If I call my script like this, I can see the java command line call to `MainGenericRunner`:

`SCALA_RUNNER_DEBUG=1 ./lineSeparator.sc`

I experimentally edited the java command line to see what might be causing the problem. 
The following two command lines differ slightly, one works, the other fails.

This fails:

```
java \
  -Dline.separator=$'\n' \
  -classpath 'C:/opt/SCALA-~1.7/lib/jline-2.14.6.jar;C:/opt/SCALA-~1.7/lib/scala-compiler.jar;C:/opt/SCALA-~1.7/lib/scala-library.jar;C:/opt/SCALA-~1.7/lib/scalap-2.12.7.jar;C:/opt/SCALA-~1.7/lib/scala-parser-combinators_2.12-1.0.7.jar;C:/opt/SCALA-~1.7/lib/scala-reflect.jar;C:/opt/SCALA-~1.7/lib/scala-swing_2.12-2.0.3.jar;C:/opt/SCALA-~1.7/lib/scala-xml_2.12-1.0.6.jar' \
  -Dscala.usejavacp=true \
  scala.tools.nsc.MainGenericRunner \
  -J-Dline.separator=$'\n' \
  lineSeparatorBytes.sc
```

This works:

```
java \
  -Dline.separator=$'\n' \
  -classpath 'C:/opt/SCALA-~1.7/lib/jline-2.14.6.jar;C:/opt/SCALA-~1.7/lib/scala-compiler.jar;C:/opt/SCALA-~1.7/lib/scala-library.jar;C:/opt/SCALA-~1.7/lib/scalap-2.12.7.jar;C:/opt/SCALA-~1.7/lib/scala-parser-combinators_2.12-1.0.7.jar;C:/opt/SCALA-~1.7/lib/scala-reflect.jar;C:/opt/SCALA-~1.7/lib/scala-swing_2.12-2.0.3.jar;C:/opt/SCALA-~1.7/lib/scala-xml_2.12-1.0.6.jar' \
  -Dscala.usejavacp=true \
  scala.tools.nsc.MainGenericRunner \
  lineSeparatorBytes.sc
```

The only difference between the two is that I removed the 2nd-to-last parameter:

`  -J-Dline.separator=$'\n' \`

**Comment by som-snytt** [comment]
Traditionally, the script runner kicks of a compilation server in the background. The `-J` option is collected to be passed through to that resident compiler aka `fsc`. The arrangement is fraught with peril, and I only ever used `-nc` for "no compile daemon". Offhand, I'm not sure how setting line.separator on the daemon would make difference. If I attempt to think about it right now, I will nod off at my desk, so I'll defer it till later. You might experiment with `-nc`, however; it became the default in recent versions.

Here is my quick trial in which I don't use `-nc`, I have no idea what it just did:

```
$ scala -Dline.separator=$'\r' seenl.sc 
  -target:<target>                     Target platform for object files. All JVM 1.5 - 1.7 targets are deprecated. Choices: (jvm-1.5,jvm-1.6,jvm-1.7,jvm-1.8), de                                         deprecated: In 2.12, -optimise enables -opt:l:inline -opt-inline-from:**. Check -opt:help for using the Scala 2.12 optim
```
as opposed to
```
$ scala -Dline.separator=$'\r' -nc seenl.sc 
line.separator bytes: 13
```

**Comment by philwalk** [comment]
That fixed it, I think ...  this invocation now works for me:

`scala -J-Dline.separator=$'\n' -nc lineSeparatorBytes.sc`

it produces this output:

`line.separator bytes: 10`

Thanks for looking into this!
