### ISSUE TITLE
s.c.m.{HashMap,HashSet} methods addAll, removeAll could avoid hashing if argument is s.c.i.HashMap/HashSet

### ISSUE THREAD

**Issue by joshlemer** [scala/bug#11265]
Currently, `scala.collection.mutable.{HashMap,HashSet}` rehash all elements of the argument collection when calling `addAll` or `subtractAll`. This could be optimized in the case where the argument is a `scala.collection.immutable.{HashMap,HashSet}`, because those collections actually keep the hashes of all their keys.

**Comment by gmarti** [comment]
Looked at it but we cannot reuse the hash from `immutable.HashMap` in `mutable.HashMap`
They both use some algorithm to improve the hash by shifting bits but they are different
`immutable.HashMap` improve hash with `scala.collection.Hashing.improve`
`mutable.HashMap` improve hash in a local `computeHash` method

And also to avoid problems, hash should be typed so we avoid dangerous change that will break hashing when reusing them

I'll look at the feasibility with HashSet

**Comment by joshlemer** [comment]
@gmarti actually there's a PR open for this that I made here https://github.com/scala/scala/pull/7520

It does the trick of translating between the two different "improved hash" types, by taking advantage of the two facts:
* mutable HashSets and HashMaps improve their hashes in a way that is reversible (improve(improve(hash) == hash)

* immutable HashSets and HashMaps store their original hashes, so those can be used when interacting with mutable counterparts
