### ISSUE TITLE
Some annotations like `native`,`specialized`,throws`,`volatile` etc should be marked with final

### ISSUE THREAD

**Issue by hepin1989** [scala/bug#11266]
#### Problem:

I saw some of the annotations are marked as `final`, such as `tailrec` and some not, such as `native`,`specialized`,`throws` etc. From a user perspective, these give you a wonder should I extends them? So I think that's a good idea to mark them `final` for consistency and clarification.

#### Expectation:

These annotations are marked as `final`.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/7449
