### ISSUE TITLE
Add cycle detection to LazyList.distinct/LazyList.distinctBy

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#11270]
Add cycle detection to `LazyList.distinct` and `LazyList.distinctBy`, so that when called on cyclic `LazyList`s, they still terminate.

**Comment by ashwinbhaskar** [comment]
@NthPortal can I take this up?

**Comment by NthPortal** [comment]
@ashwinbhaskar go for it!

**Comment by ashwinbhaskar** [comment]
@NthPortal thank you:)

**Comment by ashwinbhaskar** [comment]
@NthPortal Wanted to understand if I have got the definition of cyclic lazy list right. Is this a cyclic lazy list?

> 0 #:: 1 #:: fibs.zip(fibs.tail).map{ n => n._1}

**Comment by ashwinbhaskar** [comment]
@NthPortal Wanted understand if I have got the definition of cyclic lazy list correct? Is this a cyclic lazy list ?

> val altNumbers: LazyList[Int] = 0 #:: 1 #:: altNumbers.zip(altNumbers.tail).map{ n => n._1}

**Comment by NthPortal** [comment]
A cyclic `LazyList` has itself as its eventual tail (rather than the result of calling a method like `map` on itself). Calling `force` on such a `LazyList` will terminate (unlike the example you gave), and after being evaluated, its `toString` method displays the end of it as `...`.

```scala
scala> val ring: LazyList[Int] = 1 #:: 2 #:: 3 #:: ring
ring: LazyList[Int] = LazyList(?)

scala> ring.force
res0: ring.type = LazyList(1, 2, 3, ...)

scala> ring.take(10).force
res1: scala.collection.immutable.LazyList[Int] = LazyList(1, 2, 3, 1, 2, 3, 1, 2, 3, 1)
```

**Comment by ashwinbhaskar** [comment]
@NthPortal Thank you for the clarification. I have added cycle detection to distinctBy (overriding distinct is not required as it internally calls distinctBy). But I am afraid that detecting cycle would require us to traverse the list and it might not be lazy anymore. https://github.com/scala/scala/pull/7568

**Comment by ashwinbhaskar** [comment]
@NthPortal No problem:). I understood a good deal about the LazyList during the process. Though, it would be interesting to see how it could be done while still keeping the laziness. Any pointers ? I could work on it if you could show me the way:)

**Comment by NthPortal** [comment]
@ashwinbhaskar I don't know what pointers I could give without actually coding it, sorry

**Comment by ashwinbhaskar** [comment]
@NthPortal no issues:)

**Comment by SethTisue** [comment]
doing cycle detection seems rather above-and-beyond-the-call-of-duty to me?

**Comment by NthPortal** [comment]
perhaps, yeah.

it also has the disadvantage of either evaluating twice as many elements as it needs to by scouting ahead, or holding onto (leaking memory of) half as many elements as have been traversed, so it's not clear that it's worth it for the uncommon situation of calling `distinct(By)` on a cyclic `LazyList`.

**Comment by Ichoran** [comment]
Haven't looked at the implementation, but `distinct` on `LazyList` has a particularly easy way to detect cycles: you do the two-element thing _only_ starting when you hit a duplicate, and you drop it all as soon as you hit something new.  If it actually is a cycle, you'll detect it in n+3m time, where n is the non-cyclical part and m is the cyclical part; and if it's not a cycle, you have only a little extra work in cases where the list is not badly degenerate.

**Comment by NthPortal** [comment]
@Ichoran thanks! I hadn't thought of those optimisations! Just curious - would you tend to prefer scouting ahead or lagging behind?

**Comment by ashwinbhaskar** [comment]
@Ichoran By "two-element" thing do you mean 2 iterators (one fast and one slow)?

**Comment by Ichoran** [comment]
@ashwinbhaskar - Yes, that's what I mean.

@NthPortal - You add something that lags behind; you always want to have the fast-moving place be the one that is calculating what is distinct because then once you reach the end you are done and just drop everything else.

**Comment by SethTisue** [comment]
> doing cycle detection here seems rather above-and-beyond-the-call-of-duty to me?

after scala/scala#7568 my feeling that we just shouldn't go here is growing.

**Comment by NthPortal** [comment]
closing due to discussion on scala/scala#7692
