### ISSUE TITLE
flatMap iterator does not clean up its cur field before obtaining its next value

### ISSUE THREAD

**Issue by szhem** [scala/bug#11272]
### Scala Version
2.11.x-2.12.x
### Motivation
In case of `flatMap`ping multiple resource-consuming iterators it may be necessary twice as much memory as for the single element to iterate over them. 
Consider the following synthetic example
```scala
val iter = Iterator(128*1024*1024, 128*1024*1024).flatMap(new Array[Byte](_))
while(iter.hasNext) {
  iter.next()
}
```
Running it with `-Xmx196m` jvm argument produces OutOfMemoryError
```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
   ...
```
In case of the modification proposed below no OutOfMemoryError happens and the corresponding snippet completes successfully.

The real-world issue of not cleaning up `cur` field early is described in this [message](https://github.com/apache/spark/pull/23083#discussion_r) of this [apache spark pull request](https://github.com/apache/spark/pull/23083).

### Possible solution
Clean up `cur` field before fetching its next value.
*Old implementation:*
```scala
def flatMap[B](f: A => GenTraversableOnce[B]): Iterator[B] = new AbstractIterator[B] {
  private var cur: Iterator[B] = empty
  private def nextCur() { cur = f(self.next()).toIterator }
  def hasNext: Boolean = {
    // Equivalent to cur.hasNext || self.hasNext && { nextCur(); hasNext }
    // but slightly shorter bytecode (better JVM inlining!)
    while (!cur.hasNext) {
      if (!self.hasNext) return false
      nextCur()
    }
    true
  }
  def next(): B = (if (hasNext) cur else empty).next()
}
```
*New implementation:*
```scala
def flatMap[B](f: A => GenTraversableOnce[B]): Iterator[B] = new AbstractIterator[B] {
  private var cur: Iterator[B] = empty
  private def nextCur() { cur = f(self.next()).toIterator }
  def hasNext: Boolean = {
    // Equivalent to cur.hasNext || self.hasNext && { nextCur(); hasNext }
    // but slightly shorter bytecode (better JVM inlining!)
    while (!cur.hasNext) {
      cur = empty
      if (!self.hasNext) return false
      nextCur()
    }
    true
  }
  def next(): B = (if (hasNext) cur else empty).next()
}
```
Note: `cur` is assigned to `empty` in the very beginning of while loop within `hasNext` method
1. to prevent JIT optimizations at runtime in case of doing the same thing in the `nextCur` method, e.g.
    ```scala
    private def nextCur() { 
      cur = empty
      cur = f(self.next()).toIterator 
    }
    ```
2. to clean up the very last `cur` element in case there are no more elements in it.

**Comment by som-snytt** [comment]
Thanks for the diagnosis. The PR includes a test for reachability.

**Comment by szhem** [comment]
@som-snytt Don't you think that Java's JIT can decide to "optimize" the code and just replace ...
```scala
while (!myCurrent.hasNext && self.hasNext) {
  myCurrent = null   // clear the stale reference before advancing
  myCurrent = f(self.next()).iterator
}
```
... with ...
```scala
while (!myCurrent.hasNext && self.hasNext) {
  myCurrent = f(self.next()).iterator
}
... at runtime?
```

**Comment by SethTisue** [comment]
(I responded to @szhem's question on the PR.)
