### ISSUE TITLE
Future `fallbackTo` should use a call-by-name parameter.

### ISSUE THREAD

**Issue by WayneWang12** [scala/bug#11280]
`fallbackTo` method in `Future` is as below:
```scala
  def fallbackTo[U >: T](that: Future[U]): Future[U] =
    if (this eq that) this
    else {
      implicit val ec = internalExecutor
      transformWith {
        t =>
          if (t.isInstanceOf[Success[T]]) this
          else that transform { tt => if (tt.isInstanceOf[Success[U]]) tt else t }
      }
    }
```

However, I think parameter `that` should be a call-by-name parameter that we can use this method to write recover strategy more easily.

Eric Meijer mentioned this method in the coursera course Principles of Reactive Programming. And he also list it as `def fallbackTo[U >: T](that: => Future[U]): Future[U]`.

**Comment by viktorklang** [comment]
Thanks @WayneWang12, have you considered the implications of this proposal?

**Comment by Jasper-M** [comment]
I think it makes sense for both methods (with different names) to be available.

**Comment by WayneWang12** [comment]
Actually I notice it a long time ago. I've learned scala through several courses, Pricinples of Reactive Programming is one of the best. 

Eric Meijer taught me the usage of `fallbackTo` and I remembered it. But in reallity it's not the same. 
 I think this proposal can at least reduce the misunderstand caused by Eric's course:) (just joking).

Say that I have code like:
```scala
    val t = Future.successful(1)
    t.fallbackTo(Future {
      println("this isn't supposed to be printed")
      5
    })
```
As the name implies that future in `fallbackTo` is a remdy strategy which is supposed to execute when the previous future fails. But the `println` will run neverthless. It's not the same.

**Comment by viktorklang** [comment]
@WayneWang12 No, `recover` / `recoverWith` is intended to be executed when the previous Future fails. `fallbackTo` is for the use case where you already have 2 Futures.

**Comment by WayneWang12** [comment]
It looks a little strange to me... Maybe due to the language barrier, I don't know the meaning of `fallbackTo` now...

I'm confused. Why do I need `fallbackTo` if I already have two futures? Say that I'm looking to a key-value in cache, if not found, it falls back to a query to database. That make sense to me. 

So `fallbackTo` can not be used in this senario?

**Comment by WayneWang12** [comment]
OK. I think I have to comment on every Eric Meijer's course video to tell people `fallbackTo` is not the same as he described...

**Comment by Normal** [comment]
still confusing though
