### ISSUE TITLE
More liberal Ordering.ordered

### ISSUE THREAD

**Issue by alexeyr** [scala/bug#11284]
The Java standard library includes some types which extend `Comparable<SomeSuperType>` (e.g. `LocalDate` or `java.sql.Date`). The signature of `Ordering.ordered` could be modified to

      implicit def ordered[A](implicit arg0: (A) ⇒ Comparable[_ >: A]): Ordering[A] 

in order to handle these types. I don't think it would break existing code defining its own orderings.

**Comment by Jasper-M** [comment]
My past self [agrees](https://stackoverflow.com/questions/38059191/how-make-implicit-ordered-on-java-time-localdate/46811621#46811621) with you. Can't recall anymore whether I found a reason for not trying to get this in after all. Or if I was just too lazy.

**Comment by NthPortal** [comment]
@alexeyr I assume that's supposed to be `Comparable[_ >: A]`?
