### ISSUE TITLE
ListMap and VectorMap builders should leverage mutation in building internal data structures

### ISSUE THREAD

**Issue by joshlemer** [scala/bug#11296]
Currently, `ListMap` and `VectorMap` builders build by performing immutable updates to the underlying `List`s, `Map`s, and `Vector`s. Just like is done with most other collections, mutation should be leveraged inside the Builders to improve performance.

The implementation of `ListMap#updated` (comments mine) which is used by the builder:
```scala
    override def updated[V2 >: V1](k: K, v: V2): ListMap[K, V2] = {
      val m = this - k // this may involve a total rebuilding of the List
      new m.Node[V2](k, v)
    }
```

Implementation of `VectorMap#updated` (comments mine) which is used by the builder:
```scala
  def updated[V1 >: V](key: K, value: V1): VectorMap[K, V1] = {
    underlying.get(key) match { // (1)
      case Some(oldIndexWithValue) =>
        new VectorMap(fields,
          underlying.updated(key, (oldIndexWithValue._1, value))) // (2) can we mutably update here? 
      case None =>
        new VectorMap(
          fields :+ key, // and here? 
          underlying.updated(key, (fields.length, value))) // and here? 
    }
  }
```

The VectorMap builder would need some special `private[collection]` methods added to `MapBuilder` and `VectorBuilder` to facilitate VectorMapBuilder:

* `VectorBuilder#updateAt(index: Int, elem: A): this.type` this will allow in-place updates to elements at a specific index (at line (2) above)
* `MapBuilder#get(key: K): Option[V]` this should return the value currently associated with `key` (for use at line (1) above)

**Comment by SethTisue** [comment]
@joshlemer where do we stand here: should the ticket still be open, and if so is it an RC1 blocker?

**Comment by joshlemer** [comment]
Done, finished @SethTisue
