### ISSUE TITLE
REPL does not kill to end of word or Word in vi-mode; leaves the last letter

### ISSUE THREAD

**Issue by jamesblau** [scala/bug#11292]
I've only noticed this in the scala REPL, and I reproduced it in a clean Ubuntu 18.04.1 AMD64 install in a Virtualbox VM to check that it wasn't something weird with my config. Vi-mode works as expected in bash and in other REPLs I've tried, such as Python's. I make a lot of typos because of this, so I finally thought I'd make an issue.

To reproduce:

- Start with clean OS if desired
- `echo set editing-mode vi > .inputrc`
- `scala` to open REPL
- type: `ab<Esc>0de`

Result:

- The 'a' is deleted, but not the 'b'

Expected result:

- The entire word 'ab' is cleared to the end, leaving the line blank

The same is found for 'dE', 'ce', and 'cE'; 'db' and so on work as expected, as do 'e' and 'E' when used on their own as movements rather than to kill or replace an entire word.

**Comment by jamesblau** [comment]
OK, thanks. I guess JLine2 is no longer under active development ("JLine 2.x development has come to an end", last commit July 16) so I guess I'll try to find a way to see if JLine3 has the same bug, and if not I'll just sit tight.

**Comment by jamesblau** [comment]
For anyone else running into this: I couldn't figure out how to set vi-mode in the JLine3 demo, but I did finally go to the audacious step of reading the rlwrap man page, and realized there is a `-a` setting to give control to rlwrap despite JLine's protestations. So the workaround is `rlwrap -a scala`.

**Comment by SethTisue** [comment]
if you're using rlwrap, you'll want to run with `-Xnojline`

the disadvantage of rlwrap is that you lose tab completion, which is a pretty big loss
