### ISSUE TITLE
Make LazyList.newBuilder return a builder which doesn't evaluate elements

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#11299]
Currently, `LazyList.newBuilder` returns a builder mapped from `ArrayBuffer.newBuilder`, which means that all elements are evaluated before the `LazyList` is built; arguably, this is counterproductive and not a useful builder. It should be replaced by a builder that lazily evaluates collections added using `addAll`.

**Comment by julienrf** [comment]
We could indeed introduce a builder like we used to have in 2.12, whose `++=` method doesn’t evaluate its appended elements (see implementation [here](https://github.com/scala/scala/blob/2.12.x/src/library/scala/collection/mutable/LazyBuilder.scala)). That being said, I’m not sure it is worth it. Builders are eager by nature, this “lazy” builder is actually lazy only if you use its `++=` operation, but not its `+=` operation, which I find confusing.

A workaround is to use a `var` initialized to an empty `LazyList`:

~~~ scala
var b = LazyList.empty[Int]
b ++= LazyList.from(0).take(10)
~~~

What do you think?

**Comment by NthPortal** [comment]
@julienrf The only issue with that is that it keeps rebuilding the prefix of the list every time you append to it. You can probably manage something similar using `stateFromCollConcatSuffix` (possibly soon to be `stateFromIteratorConcatSuffix`), where the suffix is lazily evaluated to either be the next element(s) appended or empty if you call `result()`

**Comment by julienrf** [comment]
What do you mean by ”rebuilding”?

**Comment by NthPortal** [comment]
Just like `List`, appending to the end is `O(n)` and requires building a new `LazyList` containing all its elements and then whatever you're appending. It's still done lazily, but that actually kinda makes it worse, because you can blow the stack when you evaluate elements if you append too many things.

**Comment by julienrf** [comment]
Yeah, but this “rebuilding” is lazy so it is not `O(n)`. That being said, you’re right that concatenating `m` `LazyList`s introduces `m` levels of indirections, whereas the `LazyBuilder` thing doesn’t.
