### ISSUE TITLE
Determine how lazy LazyList should be

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#11307]
## Background

(quoted from #11105)

> Currently, `LazyList` has two forms of laziness:
> 
> 1. laziness in determining whether or not it is empty (and by extension, how many elements it has)
> 2. independent laziness of elements - that is, evaluating a subsequent `head` or `tail` of the `LazyList` does not cause the evaluation of previous `head`s.

Form 1 is one of the primary reasons for the creation of `LazyList`, is generally maintained throughout operations on it, and I think is is generally agreed to be of very high value.

Form 2 is less obviously valuable. Historically, it exists because the original implementation of `LazyList` had a strict state (empty or cons), and lazy `head` and `tail` (like `Stream`, but with a lazy `head` as well); when the design of `LazyList` was changed to have a lazy state and strict `tail` (because lazy `tail` doesn't add anything once the state is lazy), the lazy `head` was still kept.

During various discussions on various issues, it has been noted that the fact that `LazyList`'s supports form 2 of laziness

- makes some implementations more complex (though not overly so)
- often adds no value, because the `LazyList` is created in a fashion (e.g. from an `Iterator`) that does not have form 2 of laziness
- is subverted by many common operations (such as `filter`, `dropWhile`) which by their nature must evaluate elements sequentially in order to determine the next element

This yields the question (quoted from @sjrd at https://github.com/scala/scala/pull/6880#issuecomment-402390591):

> As added food for thought: I wonder whether it is still useful that the *head* be lazy. Are there use cases where one already knows that the lazy list is non-empty, but doesn't know yet what its `head` will be (and cannot synchronously compute it)? My experience from programming in Oz (where this lazier `LazyList` is basically *the* base data type used *everywhere*--and optimized by the VM) doesn't support any such use case. [...]

(see also https://github.com/scala/bug/issues/11089#issuecomment-413982889)

## Issue and Investigation Areas

Should `LazyList` support form 2 of laziness by having a lazy `head`? There are a few points to think about in this regard:

1. How significant is the *implementation* cost of supporting form 2 of laziness? Keeping in mind that the implementation supporting form 2 of laziness already exists, but must be maintained.
2. How significant is the *performance* cost of having a lazy `head`?
3. Are there use cases where, despite the fact that the creation of the `LazyList` does not support form 2 of laziness, the fact that some methods (such as `map`) support form 2 of laziness is valuable because it allows performing independently lazy expensive operations?
4. Are there use cases for which form 2 of laziness is valuable in the creation of the `LazyList` (in contrast to what is discussed in the previous question)? I and several others have yet to come up with one.

I think that if we cannot come up any compelling use cases for form 2 of laziness, taking into account how frequently it is not present anyway, then `LazyList` should be changed to have a strict `head` and not support form 2 of laziness. I say this despite the fact that I have invested significant effort into writing comprehensive tests which ensure that all methods which can preserve/support form 2 of laziness do so. Once 2.13 is out, it will be difficult to change `LazyList`'s behaviour even in subsequent releases of Scala because it would be a significant change in semantics (much like the way `Stream` cannot be a deprecated type alias for `LazyList`).

## Consensus

Form 2 of laziness should be removed, and `head` made strict.

--------

~~I don't know if this issue actually needs to be resolved by 2.13.0-RC1, but it definitely needs to be resolved by the final release of 2.13.0, and it would probably be better to resolve it at least a few release candidates beforehand.~~

**Comment by NthPortal** [comment]
Regarding point 1: I am happy to maintain `LazyList` for the foreseeable future, but that's obviously not a guarantee forever

**Comment by lrytz** [comment]
Thank you very much for writing this up! The design definitely needs to be finalized before RC1, which is scheduled for end of January.

It sounds to me like going for a strict `head` is a better choice for the standard library. The goal of the standard library is to find the "right" balance between simplicity, productivity, performance. Since we're not aware of a good use case for a lazy `head` right now, we should go for the simpler solution. If the need shows up, people can implement that collection outside the standard library, and if that really takes off we'll reconsider.

**Comment by texasbruce** [comment]
It would be inconsistent with other collection types. If you want lazy head, you can use `take(1)`

**Comment by NthPortal** [comment]
@texasbruce I don't understand what you mean - how does that give you form 2 of laziness with a strict `head`?

**Comment by texasbruce** [comment]
It's inconsistent because it implements `Iterable` of which head method returns the element type. If you wanna strip the trait out, then you gonna have a lot of methods to implement, and causes compatibility for existing code base that passes LazyList as Iterable.

As @lrytz mentioned, I don't see a use case for *mandatory* lazy implementation of head because as I mentioned you can always use` take(1)`. I am curious to see any trouble of the non lazy head causes

**Comment by NthPortal** [comment]
I am not suggesting that calling `head` somehow does not evaluate the element. I am saying that calling `tail.head` does not cause the evaluation of `head`

**Comment by texasbruce** [comment]
Oh sorry misunderstood. But how can it be implemented?

**Comment by NthPortal** [comment]
@texasbruce it is already implemented (see scala/scala#7355)

**Comment by texasbruce** [comment]
Thanks for the info

**Comment by sjrd** [comment]
I believe my opinion on this question is already clear to anyone who's read my various comments in the various issues, but I'll state it unambiguously here.

I think `LazyList` should *not* have a lazy `head`.

A lazy head clearly has more overhead and a higher implementation complexity, and as was mentioned we don't have any use case.

**Comment by NthPortal** [comment]
I believe I have come up with a use case (point 3).

You have a text file, and you read the lines into a `LazyList` (which does not have form 2 of laziness). You then perform an expensive analysis on each line of the file (via `map`).

```scala
val lines: LazyList[String] = ???
val analysed = lines.map(doExpensiveAnalysis)
```

However, the result of the analysis may tell you that the following `n` lines are of little value to you (for whatever reason), so you want to drop them. With a lazy `head`, you can do a simple `filter` and avoid the expensive analysis for the lines you are skipping.

```scala
var skip = 0
val filtered = analysed.filter { elem =>
  if (skip > 0) {
    skip -= 1
	false
  } else {
    skip = elem.skipCount
	true
  }
}
```

Without a lazy `head`, it is more difficult and less clear to avoid the analysis.

```scala
var skip = 0
val filtered = lines.flatMap { line =>
  if (skip > 0) {
    skip -= 1
    Nil
  } else {
    val elem = doExpensiveAnalysis(line)
	skip = elem.skipCount
	elem :: Nil
  }
}
```

If `doExpensiveAnalysis` is not its own method, the code becomes even less clear as the filtering (done via `flatMap`) and analysis are now mingled together.

Or perhaps you would like to do something with the last analysed line in the file matching some predicate, and then proceed to perform other operations (perhaps like the one above) starting from the front of the `LazyList`.

```scala
// side note: why isn't there a `findLast`?
val lastMatchingIdx = analysed.lastIndexWhere(somePredicate)
val lastMatching = analysed(lastMatchingIdx)
```

Without a lazy `head`, doing that search would require analysing *all* lines, whereas with a lazy `head`, it might analyse only a single line (if the predicate is true for the last line). It still needs to *read* all the lines, but it doesn't need to perform the expensive analysis for all of them.

**Comment by odersky** [comment]
I also tend to make `head` strict. It seems to be simpler conceptually.

**Comment by shawjef3** [comment]
I've run into a scenario where I wanted `head` to be lazy. Sometimes I want to use `Iterator` as control structure rather than a collection, where I get to accumulate results if I like. I use `Stream` (<= Scala 2.12) to lazily run each iteration and get the result. In these cases, when I call `Iterator#toStream`, I don't want the `Iterator` to execute until I explicitly start walking the `Stream`.

**Comment by NthPortal** [comment]
@joroKr21 no, but that introduces another layer of indirection (and boxing and dependent load); if it's a strong use case, we should have it not require extra boxing and indirection.

**Comment by NthPortal** [comment]
Requesting input from others who have been involved with `LazyList` design and/or bugs and may have input on this question.

pinging @hrhino @julienrf @szeiger @SethTisue @paulp.

I am currently leaning the same way as the current rough consensus, to make `head` strict and remove "form 2" of laziness.

**Comment by OlegYch** [comment]
i often hear people complaining about Stream head being strict, and then some people started pointing out that it's fixed in LazyList
does this suggest to revert to Stream behavior?

**Comment by sjrd** [comment]
No it doesn't. When people complain about the head being strict in `Stream`, they are in fact referring to form 1 of laziness, and that one we keep.

**Comment by szeiger** [comment]
Given the high complexity of the new implementation I also agree with forcing elements when their existence has been determined. It would also resolve the problems with `IterableFactory.fill` (which doesn't really make sense for `LazyList` if the elements are not evaluated in order) and with `Iterator` not being lazy enough as a basic abstraction.

**Comment by SethTisue** [comment]
I'm fine with dropping form 2. It turned out to be a bigger can of worms that any of us anticipated.

**Comment by SethTisue** [comment]
@NthPortal also I think there's now sufficient consensus that you can go forward with this.

**Comment by Atry** [comment]
`LazyList[A]` is essentially a `() => LazyList.State[A]`, and `Deferrer[A]` is essentially a `() => LazyList[A]`, therefore, `Deferrer[A]` is essentially a `() => () => LazyList.State[A]`. Does `Deferrer` really necessary?

**Comment by Jasper-M** [comment]
Looks like `Deferrer` was added as a workaround for a bug with right-associative operators: https://github.com/scala/collection-strawman/issues/127
But that issue also seems to have been fixed in the compiler: https://github.com/scala/scala/pull/5969

**Comment by NthPortal** [comment]
you need `Deferrer` to allow defining recursive or circular `LazyList`s. this is what happens if `#::` and `#:::` are defined on `LazyList`:

```scala
scala> lazy val ones: LazyList[Int] = 1 #:: ones
ones: LazyList[Int] = <lazy>

scala> ones.head
java.lang.StackOverflowError
  at .ones(<console>:1)
  at .ones$lzycompute(<console>:1)
  at .ones(<console>:1)
  at .ones$lzycompute(<console>:1)

scala> lazy val nats: LazyList[Int] = 1 #:: nats.map(_ + 1)
nats: LazyList[Int] = <lazy>

scala> nats.head
java.lang.StackOverflowError
  at .nats$lzycompute(<console>:1)
  at .nats(<console>:1)
  at .nats$lzycompute(<console>:1)
  at .nats(<console>:1)
```

**Comment by szeiger** [comment]
see https://github.com/scala/scala/pull/7990 for a way that could potentially eliminate `Deferrer`

**Comment by NthPortal** [comment]
@szeiger I'm not completely following how it can eliminate `Deferrer`. `Deferrer` is currently used/required to avoid initializing the base `LazyList` in recursively-defined instances; how can dropping the reference to `this` get around that?

**Comment by szeiger** [comment]
Oh, right, you need both operands to be lazy. I wonder if extension methods could be used. The current documentation doesn't mention it.

**Comment by NthPortal** [comment]
if I understand correctly, `Deferrer` is essentially an extension method over a by-name value
