### ISSUE TITLE
Scaladoc creates invisible dead link for `Permalink`

### ISSUE THREAD

**Issue by ennru** [scala/bug#11300]
We noticed lots of dead links in our generated documentation and traced them to be generated by scaladoc.

These links are not actually visible to the user, but Google's analysis sees lots of dead links and downgrades the credibility of the documentation.

Scaladoc generates dead links in sections like
```
<span class="permalink">
      <a href="../scala/index.html#annotation" title="Permalink">
        <i class="material-icons"></i>
      </a>
```
on page [scala.collection](https://www.scala-lang.org/api/2.12.8/scala/collection/index.html).

Without the `scala` part that link would be correct.

Scala version 2.12.8

**Comment by ennru** [comment]
Running a [Dead Link Checker](https://www.deadlinkchecker.com/website-dead-link-checker.asp) on [Scala 2.12.7 APIs](https://www.scala-lang.org/api/2.12.7/index.html) gives

![bild](https://user-images.githubusercontent.com/458526/50080466-6df20d00-01ec-11e9-9350-cdf227e2996f.png)

**Comment by hamednourhani** [comment]
Hi @SethTisue & @ennru 
shall i work on it?

**Comment by dwijnand** [comment]
Go for it, @hamednourhani, it's all yours.

**Comment by ennru** [comment]
You're most welcome. 
I digged around a bit. For some level the permalinks get based on the wrong level of package, but I didn't manage to understand why that is. And it is not obvious to where the same logic applies.

**Comment by OberstK** [comment]
@hamednourhani Are you still working on that?
@ennru Is this still an issue? Looking at the scala doc 2.12.8 [here](https://www.scala-lang.org/api/2.12.8/scala/collection/index.html) I can not reproduce the dead link issue. The Dead Link Checker also only returns two results

**Comment by eed3si9n** [comment]
Here's a single `li` element for `scala.annotation` package:

```html
<li name="scala.annotation" visbl="pub" class="indented2 " data-isabs="false" fullComment="yes" group="Ungrouped">
 <a id="annotation"></a><a id="annotation:annotation"></a>
  <span class="permalink">
  <a href="../scala/index.html#annotation" title="Permalink">
  <i class="material-icons"></i>
  </a>
  </span>
  <span class="modifier_kind">
  <span class="modifier"></span>
  <span class="kind">package</span>
  </span>
  <span class="symbol">
  <a title="" href="../annotation/index.html"><span class="name">annotation</span></a>
  </span>
    
  <div class="fullcomment"><dl class="attributes block"> <dt>Definition Classes</dt><dd><a href="../index.html" class="extype" name="scala">scala</a></dd></dl></div>
  </li>
```

The dead link is `<a href="../scala/index.html#annotation" title="Permalink">`. The dead link is repeated as `"../scala/index.html#beans"` but it does not show up in the Dead Link Checker probably because they all point to `../scala/index.html`.

**Comment by eed3si9n** [comment]
Here's my PR for this - https://github.com/scala/scala/pull/7906
