### ISSUE TITLE
Regression? Map .withDefaultValue refines return type in 2.13, not in 2.12

### ISSUE THREAD

**Issue by Sciss** [scala/bug#11314]
Ok in Scala 2.12:

    var m = Map("foo" -> "bar").withDefaultValue("baz")
    m += "a" -> "b"

fails in 2.13.0-M5:

```
Error:(442, 7) value += is not a member of scala.collection.immutable.Map.WithDefault[String,String]
  Expression does not convert to assignment because:
    type mismatch;
     found   : scala.collection.immutable.Map[String,String]
     required: scala.collection.immutable.Map.WithDefault[String,String]
    expansion: m = m.+("a".$minus$greater("b"))
    m += "a" -> "b"
```

It doesn't seem to make sense to me to expose the return type `WithDefaultValue`?

**Comment by julienrf** [comment]
Related: #11017

**Comment by julienrf** [comment]
I think I understood the problem: although the `updated` method has a refined `Map.WithDefault` return type, its **symbolic alias**, the `+` operator, doesn’t: it still returns a `Map`, hence the compilation error.

The solution consists in overriding the `+` alias to also refine its return type.
