### ISSUE TITLE
I can't unimport names under scala package object

### ISSUE THREAD

**Issue by eed3si9n** [scala/bug#11317]
## steps

I want to mask `scala.Seq`.

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

object Foo {
  import scala.{ Seq => _, _ }
  val xs = Seq(1, 2, 3)
}

// Exiting paste mode, now interpreting.

defined object Foo

scala> Foo.xs
res1: Seq[Int] = List(1, 2, 3)
```

## problem

The name `Seq` is still available within `object Foo { ... }`.

## expectation

The code does not compile.

**Comment by Jasper-M** [comment]
It's generally not possible to unimport something after it has already been imported:
```scala
scala> def foo = {
     |   import scala.util._
     |   import scala.util.{Try => _, _}
     |   Try(1/0)
     | }
foo: scala.util.Try[Int]
```

**Comment by eed3si9n** [comment]
> It's generally not possible to unimport something after it has already been imported

Trying to tie this back to the spec.

[2](https://www.scala-lang.org/files/archive/spec/2.12/02-identifiers-names-and-scopes.html) says:

> A binding in some inner scope _shadows_ bindings of lower precedence in the same scope as well as bindings of the same or lower precedence in outer scopes. 

I guess in my example, the unqualified `Seq` would not be bound in `object Foo` scope, so it would try the outer scope of that and finds `import scala._` in there.
