### ISSUE TITLE
Un-final @deprecated (and friends)

### ISSUE THREAD

**Issue by dwijnand** [scala/bug#11311]
https://github.com/scala/scala/pull/7449 makes a number of annotations insta-`final`.  Backing @fommil's concern I suggest we un-final them and mark them `@deprecatedInheritance` for 2.13 (and possibly backport) and `final` in 2.14.

Maybe some of the more niche ones can be on the fast track of insta-final, but I also don't see there being any urgency.

**Comment by dwijnand** [comment]
Thank you @hepin1989 for volunteering to fix this.

**Comment by hepin1989** [comment]
@dwijnand I think only `deprecated` is need to be un-final for now. At least in Java you could not extend any of `@interface`.

**Comment by hepin1989** [comment]
Another thing is, is this kind of thing supported in Scala ?
![image](https://user-images.githubusercontent.com/501740/50001686-96a1b900-ffd8-11e8-9a8b-6cc5a4b6e330.png)

**Comment by hepin1989** [comment]
Another thing is what we really needed here and there is not extends the `@deprecated` but `suppressWarnings`.
like 
```scala
class suppressWarnings(suppressed:Array[String]) extends scala.annotation.StaticAnnotation
```
and then 
```
class unused extends suppressWarnings(suppressed = Array("unused"))
```

**Comment by hepin1989** [comment]
As both Akka and Scalaz are going to make use of think kind of thing for temporarily suspending the warning, so there is kind of needs for a dedicated design around this need instead of overloading the `deprecated` more.
