### ISSUE TITLE
Scaladocs on AnyRef.wait/synchronized missing

### ISSUE THREAD

**Issue by lrytz** [scala/bug#11310]
https://www.scala-lang.org/api/2.13.0-M5/scala/AnyRef.html#wait():Unit has no Scaladoc, the doc comment from https://github.com/scala/scala/blob/v2.13.0-M5/src/library-aux/scala/AnyRef.scala#L115-L120 is not emitted. Same for `synchronized`.

For methods that *do* have scaladocs, the parameter names from library-aux are not used.

Reported at https://contributors.scala-lang.org/t/scaladocs-about-liburary-aux-is-broken/2582

**Comment by rajcspsg** [comment]
Hi @SethTisue @lrytz 

Shall I work on this issue?

**Comment by SethTisue** [comment]
yes, please do!

**Comment by SethTisue** [comment]
note that this is not a simple matter of adding or updating a doc comment; the doc comment already exists, but it doesn't end up in the finished Scaladoc. it isn't clear why; you'll need to investigate. (that's why the ticket is tagged "Scaladoc tool" rather than just "doc"). note that `AnyRef.scala` is special because `AnyRef` is a compiler fiction

**Comment by Jasper-M** [comment]
Some things I noticed:
- In [Definitions.scala](https://github.com/scala/scala/blob/2.13.x/src/reflect/scala/reflect/internal/Definitions.scala) there seem to be no definitions for `wait` (yet the compiler does know those methods from `java.lang.Object`), and the definition of `synchronized` doesn't seem to match the type signature in the source file. So there seems to be a connection between missing definitions and missing scaladoc.
- The definitions in Definitions.scala are generated with synthetic names (`x$1`, `x$2`) which don't match the descriptive names in the source file, but don't match the synthetic names in the scaladoc either (`arg0`, `arg1`). That does explain the (un)named arguments at compile time though. Isn't there a separate issue for that?

**Comment by Jasper-M** [comment]
And I said something similar in this overlapping issue #6684.

**Comment by eed3si9n** [comment]
I have a PR for `AnyRef#wait` fix. I didn't look into `synchronized` - https://github.com/scala/scala/pull/9045

**Comment by SethTisue** [comment]
Eugene's PR is now merged. Somebody want to look into `synchronized` next?

**Comment by eed3si9n** [comment]
I'll do it - https://github.com/scala/scala/pull/9050

**Comment by som-snytt** [comment]
I literally just came here from browsing https://contributors.scala-lang.org/t/scaladocs-about-liburary-aux-is-broken/2582/2

I can't tell if the PR fixes parameter names, for scaladoc and completion purposes. And named arg purposes.

**Comment by eed3si9n** [comment]
scala/scala#9050 should pull up the Scaladoc comments from AnyRef.scala, but I don't think it will fix the parameter names.

**Comment by SethTisue** [comment]
> the parameter names from library-aux are not used

is it worth keeping this ticket open over this one remaining part?

**Comment by SethTisue** [comment]
> is it worth keeping this ticket open over this one remaining part?

Answering my own question: nah, we don't generally keep open tickets for “would be nice” documentation improvements.
