### ISSUE TITLE
incorrect drop implementation on RangeIterator

### ISSUE THREAD

**Issue by julienrf** [scala/bug#11328]
~~~ scala
// scala 2.12
(0 until 0).endsWith(List(-4, -3, -2, -1)) // false
~~~

~~~ scala
// scala 2.13
(0 until 0).endsWith(List(-4, -3, -2, -1)) // true
~~~

**Comment by som-snytt** [comment]
I'm blinking my eyes and shaking my head, and now I'm going to use the spray bottle of cleaner on my eyeglasses.

**Comment by NthPortal** [comment]
The problem boils down to the following:

```scala
scala> (0 until 0).iterator.drop(-4).toList
res0: List[Int] = List(-4, -3, -2, -1)
```

**Comment by SethTisue** [comment]
@rpmcdougall I'll assign you the ticket if you accept my invite to https://github.com/orgs/scala/teams/contributors and then reply here

**Comment by rpmcdougall** [comment]
I accepted your invites, thanks!
