### ISSUE TITLE
Compiler messes up with Pattern matching inside partial function

### ISSUE THREAD

**Issue by MDIB** [scala/bug#11325]
Hey, I don't know if that's a bug or if you guys are aware but I found it interesting to report anyways.

The scala compiler messes up pattern matching when I try to use it inside a partial function (which is required to be able to map over a Map deconstructing key and value ) 

The following code:

```scala
sealed trait Something

case class Example(inside: String) extends Something

object AnotherOne extends Something

val myMap: Map[String,Something] = Map("a" -> new Example("bla"),
                                       "b" -> new Example("blo"))

myMap.map{case (k,v) => (k -> v match {
  case Example(str) => str
})}
```

Throws me the error:

```
 error: constructor cannot be instantiated to expected type;
 found   : Example
 required: (String, Something)
  case Example(str) =>
       ^
```

Which is totally unexpected (at least for me) as it is very clear that pattern matching `case Example(str)` refers to `v` not the partial function :sadapanda:

Let me know what I can do to follow up with more useful information.

Thanks a lot!

**Comment by hrhino** [comment]
I think it's just matching against `k -> v`, no?

**Comment by MDIB** [comment]
lol if I put another parenthesis around (k -> v) it works interesting, thanks!

**Comment by hrhino** [comment]
Yup! If you're not sure if something is a bug, you can also ask around on [gitter](https://gitter.im/scala/scala) or [discourse](https://users.scala-lang.org/) or stackoverflow to possibly get a faster answer.
