### ISSUE TITLE
operator Referencial Transparency

### ISSUE THREAD

**Issue by yinshurman** [scala/bug#11320]
I know operator apply in scala is a syntax sugar of method call,but I think it breaks the  referencial transparency principle as I understand,eg:

`import scala.collection.mutable.Map `
`val a=Map.empty[String,Int]`
`val b=("key",10)`
`a += b                   //which is ok`
`a += ("key",10)    //which get a type mismatch error  ` 
`a+=(("key",10))    //which is ok again,but I think it breaks the referencial transparency principle`
    

 I guess internally `a += ("key",10) ` is translate to `a.+=("key",10)`so that the literal ("key",10) is now  understood as arguments rather than a tuple,may be that is why `a += (("key",10))` works well.
but I really don't appreciate that way,beacause it breaks down the referencial transparency as well as  human intuition,any way,it is ugly and weird I think.
any way,i hope scala to be better and  better.

**Comment by lrytz** [comment]
This issue tracker is for bugs, for discussions about the language we have discourse (https://users.scala-lang.org), gitter (https://gitter.im/scala/scala). The issue here is also discussed here: https://github.com/scala/scala-dev/issues/503
