### ISSUE TITLE
scalac -Xprompt terminates before taking any input from user

### ISSUE THREAD

**Issue by ashwinbhaskar** [scala/bug#11332]
`scalac  -Xprompt sandbox/UnapplyTest.scala`

gives

```
sandbox/UnapplyTest.scala:6: error: wrong number of arguments for pattern Ttl(duration: Int, et: Boolean)
    case Ttl(duration) => println(duration)
            ^

a)bort, s)tack, r)esume: 
a)bort, s)tack, r)esume: one error found
[error] Nonzero exit code returned from runner: 1
[error] (compiler / Compile / runMain) Nonzero exit code returned from runner: 1

```

**Comment by som-snytt** [comment]
The report is about the sbt task, where it's not obvious that there's hope of reading from the console.
```
sbt:root> scalac -Xprompt sandbox/nope.scala
[info] Done packaging.
[info] Running (fork) scala.tools.nsc.Main -usejavacp -Xprompt sandbox/nope.scala
```
There are still rough edges from the command line due to the new reporters.

**Comment by som-snytt** [comment]
For the rough edges, https://github.com/scala/scala/pull/7601

**Comment by som-snytt** [comment]
For the sbt task, you can add
```
   fork in run := true,
+  connectInput in run := true,
```
Probably they won't want to do that by default just for this marginal feature.

**Comment by som-snytt** [comment]
Or https://github.com/scala/scala/pull/7617/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR154
