### ISSUE TITLE
WrappedArray[Byte].hashCode() method works differently from List[Char].hashCode() and violates equals/hashCode contract in Scala 2.12

### ISSUE THREAD

**Issue by smishmash** [scala/bug#11330]
https://github.com/scala/bug/issues/10690 addresses this problem for scala 2.13 in development. However the problem exists for scala 2.12 as well. Would you consider back-porting the fix to 2.12?

**Comment by smishmash** [comment]
PR is here: https://github.com/scala/scala/pull/7607#issue-242509725

It has a failure that I don't understand.

**Comment by smishmash** [comment]
@som-snytt thank you for the pointer. I have updated the PR and all tests pass.

**Comment by hrhino** [comment]
scala/scala#7607 has been merged for 2.12.9
