### ISSUE TITLE
scaladoc 2.12 does not show SVG icon for type alias

### ISSUE THREAD

**Issue by Atry** [scala/bug#11335]
For example:

Given a type alias that has a `@template` annotation
https://github.com/ThoughtWorksInc/DeepLearning.scala/blob/afe4cee4070a4433a72b7ef5711b3bb4af1e9a58/CumulativeLayer/src/main/scala/com/thoughtworks/deeplearning/CumulativeLayer.scala#L170

Scaladoc create pages for it

https://static.javadoc.io/com.thoughtworks.deeplearning/unidoc_2.12/1.0.0/com/thoughtworks/deeplearning/CumulativeLayer$Output.html

There should be an icon at the up left corner.

**Comment by Philippus** [comment]
duplicate of #10382 ?

**Comment by Atry** [comment]
Yes. It's a duplicate.
