### ISSUE TITLE
package-private method should not be overridable outside of the package

### ISSUE THREAD

**Issue by TomasMikula** [scala/bug#11339]
This compiles, even though `filterImpl` is declared `private[scala]` in [`TraversableLike`](https://github.com/scala/scala/blob/44971d104f4364a0ddaa4f05afc4cc61ee39cdf7/src/library/scala/collection/TraversableLike.scala#L245).

```scala
abstract class MyIterable[A] extends Iterable[A] {
  override def filterImpl(p: A => Boolean, isFlipped: Boolean): MyIterable[A] = ???
}
```

Another problem is that I cannot have a (private) method of the same name and arguments as a package-private method without overriding the package-private method:

```scala
abstract class MyIterable[A] extends Iterable[A] {
  private def filterImpl(p: A => Boolean, isFlipped: Boolean): MyIterable[A] = ???
}
```

```
error: overriding method filterImpl in trait TraversableLike of type (p: A => Boolean, isFlipped: Boolean)Iterable[A];
 method filterImpl has weaker access privileges; it should not be private
         private def filterImpl(p: A => Boolean, isFlipped: Boolean): MyIterable[A] = ???
```

**Comment by som-snytt** [comment]
The spec language in 5.2.1 "private" was changed in 2015 to clarify:

> Class-private or object-private members may not be abstract, and may not have protected or override modifiers. They are not inherited by subclasses and they may not override definitions in parent classes.

issue 9321 at https://github.com/scala/scala/commit/99fcdf758e5b52f77a138bc777692dd2461e0a9c

There is also a mention in Scala 3 that they might just get rid of qualified private. Pun on "busted down to private".
