### ISSUE TITLE
an unexpected type representation reached the compiler backend while compiling

### ISSUE THREAD

**Issue by oskin1** [scala/bug#11334]
I experienced the following compiler errors:
```
[error] Error while emitting Funnel.scala
[error] ErasedValueType(class Sink, Array[Byte]) (of class scala.reflect.internal.Types$UniqueErasedValueType)
[error] Error while emitting Funnel.scala
[error] assertion failed: ClassBType.info not yet assigned: Lcom/github/oskin1/scakoo/Funnel$;
```
along with this message:
`an unexpected type representation reached the compiler backend while compiling Funnel.scala: ErasedValueType(class Sink, Array[Byte]). If possible, please file a bug on https://github.com/scala/bug/issues`

Here is the branch containing the project at the error state -- https://github.com/oskin1/CuckooScala/tree/scalac-bug/src/main/scala/com/github/oskin1/scakoo

I found out that it is possible to avoid this error by removing inheritance of `Sink` from `AnyVal`.

It also compiles well if I remove one implicit from `Funnel` object:
```
// Does not compiles
object Funnel {

  implicit val byteArrayFunnel: Funnel[Array[Byte]] = { a: Array[Byte] =>
    Sink.fromByteArray(a)
  }

  implicit val stringFunnel: Funnel[String] = { s: String =>
    Sink.fromString(s, StandardCharsets.UTF_8)
  }

  implicit val intFunnel: Funnel[Int] = { i: Int =>
    Sink.fromInt(i)
  }

}
```
=>
```
// Compiles well
object Funnel {

  implicit val byteArrayFunnel: Funnel[Array[Byte]] = { a: Array[Byte] =>
    Sink.fromByteArray(a)
  }

  implicit val stringFunnel: Funnel[String] = { s: String =>
    Sink.fromString(s, StandardCharsets.UTF_8)
  }

}
```

It seems to be very strange behavior.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/10600

Also works to add a dummy method:
```
trait Funnel[A] { self =>

  /** Convert a value to [[Sink]].
    */
  def apply(value: A): Sink

  def fommil(): Int = 42

}
```
