### ISSUE TITLE
Poor expansion of type hierarchy sections in scaladoc

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#11348]
The 'Linear Supertypes', 'Known Subclasses' and 'Type Hierarchy' sections only expand/hide if you click on the text, not if you click anywhere else in the panel/div which has the hover animation.

**Comment by hamednourhani** [comment]
> The 'Linear Supertypes', 'Known Subclasses' and 'Type Hierarchy' sections only expand/hide if you click on the text, not if you click anywhere else in the panel/div which has the hover animation.

Hi i have test it on chrome and firefox . I think actions do well when you click across white panel/dev. what is your browser/os version?

**Comment by NthPortal** [comment]
This appears to be a 2.13 issue. I had assumed given that it exists on 2.13 that it existed on 2.12 as well, but I was mistaken.

See for reference: [here](https://scala-lang.org/files/archive/api/2.13.0-M5/scala/collection/immutable/Seq.html) and [here](https://static.javadoc.io/org.scala-lang/scala-library/2.13.0-M5-6e0cba7/scala/collection/immutable/Seq.html).

I am using Windows and a recent version of Chrome (`Version 71.0.3578.98 (Official Build) (64-bit)` as of right now, but probably not when I opened this issue), but I highly doubt it matters.
