### ISSUE TITLE
Make `-Ywarn-unused:params` sensitive to usages in extending classes

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11343]
Tweaks to linting params as noted by @lrytz on community build.
```
$ skala -Xlint -Ywarn-unused
Welcome to Scala 2.12.2-20170406-193519-6614931 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111).
Type in expressions for evaluation. Or try :help.

scala> def f(x: Int)(y: Int = 1) = x + y
<console>:11: warning: parameter value x in method f$default$2 is never used
       def f(x: Int)(y: Int = 1) = x + y
             ^
f: (x: Int)(y: Int)Int

scala> :pa
// Entering paste mode (ctrl-D to finish)

class C { def f(x: Int, y: Int) = y }
class D extends C { override def f(x: Int, y: Int) = x + y }

// Exiting paste mode, now interpreting.

<pastie>:11: warning: parameter value x in method f is never used
       class C { def f(x: Int, y: Int) = y }
                       ^
defined class C
defined class D
```

**Comment by SethTisue** [comment]
@som-snytt should this stay open? I transferred it from scala-dev

**Comment by som-snytt** [comment]
The second case still warns. The improvement is to (optionally) warn only for sealed or final classes, if param is used in no override. Don't warn (optionally) for abstract classes.

**Comment by som-snytt** [comment]
Relatedly, unused ctor of "effectively sealed" (sealed/private) class does not warn. Under the rubric of things to notice about such classes.

**Comment by SethTisue** [comment]
> The second case still warns

I would not consider that a bug. The parameter is in fact unused. Scala 3 also warns in this case.

> The improvement is to (optionally) warn only for sealed or final classes, if param is used in no override

I doubt this level of ambition is desirable.

There aren't other places in unused analysis where you do this kind of inter-class analysis.... are there?

**Comment by som-snytt** [comment]
The sentiment at one point (maybe Jason said something) was that warning for unused params would be too noisy to be useful.

I would like all the unused warnings to be lints, just because remembering which are enabled by `-Xlint` is an encumbrance. That is possible if they work well with some heuristics (which can be turned off).

**Comment by SethTisue** [comment]
Hmm. Maybe in Scala 3 I'll conclude that `-Wunused:all` casts too wide a net and I should enable the categories individually.

**Comment by som-snytt** [comment]
Currently, an override is absolved (for unused param) because you can't change the signature you inherit.

Closing because not inclined to convince Seth (by plying him with beers). The nowarn and WConf facilities obviate too much cleverness.

Probably the other heuristics to mitigate warnings should be removed, except for simple "RHS is ???".
