### ISSUE TITLE
deprecate scala.Immutable for 2.13

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#11353]
https://www.scala-lang.org/api/2.12.8/scala/Immutable.html

I wasn't even aware this trait existed until https://stackoverflow.com/questions/54139628/why-i-can-update-state-of-an-object-extend-immutable-trait-in-scala

the trait is no longer used by the 2.13 collections, and I strongly suspect it wasn't consistently applied even in 2.8–2.12

**Comment by SethTisue** [comment]
volunteer?

**Comment by satansk** [comment]
@SethTisue I'll try it. 

By the way, can we just remove its source code or annotate it with `@deperated`?

**Comment by satansk** [comment]
Get it!

**Comment by som-snytt** [comment]
Maybe just deprecate on 2.12.x.

**Comment by SethTisue** [comment]
It's too late for a 2.12 deprecation, IMO — 2.13.0 will almost certainly come out before 2.12.9. It's fine, there's no big rush to get rid of this.

**Comment by satansk** [comment]
And I just checked 2.13, it has been removed from 2.13.x.

**Comment by SethTisue** [comment]
gah, how'd I manage to get that wrong? 😳

okay, thanks for checking

**Comment by sinh-idnow** [comment]
Thank you @SethTisue

**Comment by Jasper-M** [comment]
If it's gone in 2.13, shouldn't it be deprecated in 2.12 to be completely correct?

**Comment by som-snytt** [comment]
@Jasper-M although I am always completely correct, see my previous comment, the real issue is whether @SethTisue gets enough thank-yous, and I think clearly he does not. Also, see Seth's time-traveling comment, where the version timeline doesn't coincide with the release timeline. For those who don't read sci-fi, you can't go back in time and meet yourself, such as by deprecating the very API you are attempting to use. That would mean time could never move forward, only laterally. Scala 3 got around the paradox by calling itself "Dotty".

**Comment by Jasper-M** [comment]
I saw, and probably nobody cares/has heard about this trait, but on the other hand people also went to trouble of adding deprecated versions of all the Gen* and *Like stuff. I guess deprecating it back in the future is still better than pretending it never existed.

**Comment by NthPortal** [comment]
Since it appears to only have been used for collections (and AFAICT, everything extends it by way of `scala.collection.immutable.Traversable`), could it be made a deprecated alias of `scala.collection.immutable.Iterable[_]`?

**Comment by Jasper-M** [comment]
https://github.com/scala/scala/pull/6883

Apparently it was already decided that this could be deleted... So probably best to just leave this closed.

**Comment by SethTisue** [comment]
LOL, apparently I'll forget again in 6 months, and again...

**Comment by SethTisue** [comment]
if anyone feels strongly enough that we ought to do the deprecation in 2.12.9, I think a PR on that would be accepted
