### ISSUE TITLE
Make StringContext.{f,raw} into macros in 2.13

### ISSUE THREAD

**Issue by retronym** [scala/bug#11366]
Followup work from https://github.com/scala/scala/pull/6093

We couldn't do this in 2.12 due to the source incompatibility, but we might be willing to break this for 2.13.

If we do, we, need to:

  - [x] factor the code in refchecks into something we can share with `FastTrack`'s use of `scala.tools.reflect.FormatInterpolator`.
  - [x] after the subsequent restarr, replace `StringContext.{s,f}` with fast tracked macros.

The benefit of a macro over an intrinsic is that we avoid divergence between the intrinsified and regular behaviour. Currently, the intrinsic defers the the regular behaviour when the tree shapes are non-standard, e.g. a manual call to `StringContext.s` with non-literal arguments for `parts`. The `f` interpolator, which is already a macro, just emits a compile error for that case.

**Comment by adriaanm** [comment]
I lost track of this one because I was focussed on the bug tracker. Will see if we can still get this into RC1 since we can't do this in a .1 release.

**Comment by SethTisue** [comment]
next steps: re-STARR, then a followup to scala/scala#7678 that actually makes the changeover to macros

**Comment by SethTisue** [comment]
@retronym re-STARRing is complete, so this is unblocked. (and, you're no doubt aware, time is running short for RC1)

**Comment by adriaanm** [comment]
This one is on my plate
