### ISSUE TITLE
Should we deprecate Seq#lengthCompare and Seq#lengthIs?

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#11388]
Should we deprecate `Seq#lengthCompare` and `Seq#lengthIs` in favour of `Iterable#sizeCompare` and `Iterable#sizeIs`? It doesn't seem necessary to have both, and the `size` variants are higher up in the hierarchy. I believe this came up in Gitter at some point, though I don't recall when.

Potentially the `length` variants could be outright removed, though it seems better to have a deprecation cycle.

**Comment by NthPortal** [comment]
Deprecating the `length` variants would also mean that `lengthIs` is being added in 2.13 in a deprecated state. On the one hand, I think it's important for discoverability, since people are used using `lengthCompare`; on the other hand, we're telling people to switch to the `size` variants, so why would you ever use `lengthIs`?

**Comment by som-snytt** [comment]
If a deprecated method is marked inline, is there a best practice for emitting a deprecation warning only if inlining fails or is not enabled by whatever the optimizer option is? Note that Scala deprecations don't include a horizon like Java's `forRemoval`.

**Comment by joshlemer** [comment]
I reckon only having `size` variants should be enough.

**Comment by som-snytt** [comment]
I propose `forRemoval` https://github.com/scala/scala/pull/7714 but I didn't establish a convention for forwarding methods. I was considering ways (short of scalafix) to make migration due to rename trivial, including avoiding warnings.

**Comment by NthPortal** [comment]
anyone else have any thoughts on this? should I (or someone else) make a PR to remove the `length` variants?

**Comment by NthPortal** [comment]
Note: deprecating `lengthCompare` requires making it a final alias of `sizeCompare`, which in turn requires a scalafix migration to change existing implementations. Currently, `sizeCompare` is a final alias of `lengthCompare` on `Seq`.

**Comment by NthPortal** [comment]
Currently, name-based pattern matching uses `lengthCompare` and not `sizeCompare`. In order to deprecate `lengthCompare` on `Seq`, I think we would need to support `sizeCompare` for name-based pattern matching and deprecate `lengthCompare` for pattern matching, for consistency reasons.

Unlike `Seq#lengthCompare`, which is a well-defined symbol and fairly easy to replace using Scalafix, `lengthCompare` for pattern matching can be defined on arbitrary classes, and it's impossible to tell if a class with a `lengthCompare` method means to have it for pattern matching or for its own purposes. Thus, it is nigh impossible to automatically migrate name-based pattern matching away from `lengthCompare`.

For this reason, I think we need to keep `lengthCompare`/`lengthIs` on `Seq` for consistency, unless and until someone spearheads the change to pattern matching rules.

cc @julienrf @szeiger

**Comment by julienrf** [comment]
> Unlike `Seq#lengthCompare`, which is a well-defined symbol and fairly easy to replace using Scalafix, `lengthCompare` for pattern matching can be defined on arbitrary classes, and it's impossible to tell if a class with a `lengthCompare` method means to have it for pattern matching or for its own purposes. Thus, it is nigh impossible to automatically migrate name-based pattern matching away from `lengthCompare`.

Do we know any users relying on that?

I’m in favor of keeping only `size` variants, if it’s not too late to apply that change.

**Comment by lrytz** [comment]
Name-based pattern matching uses `lengthCompare` if available, and `length` otherwise. I think it would be a bit weird to change it to use `sizeCompare` and `length`, so we'd have to go all the way and use `sizeCompare` and `size` in name-based pattern matching. Not sure if that's a good idea, we're in pattern sequences (`unapplySeq`), so `length` seems more apropriate.

But should we really remove `lengthCompare` / `lengthIs`? Given that `Seq` adds `length, it seems more consistent to also add these two aliases.

**Comment by lrytz** [comment]
We discussed this issue on a team meeting and decided to keep the `size*` and `length*` methods.

To summarize, we have
  * `IterableOnceOps.size`
  * `IterableOps.sizeCompare(otherSize: Int)`
  * `IterableOps.sizeCompare(that: Iterable[_])`
  * `final IterableOps.sizeIs`
On `Seq`
  * `SeqOps.length` (`size` becomes a final alias)
  * `SeqOps.lengthCompare(len: Int)` (`sizeCompare` becomes a final alias)
  * `final SeqOps.lengthIs`

It seems to me that the `SeqOps.sizeCompare(that: Iterable[_])` overlaod is missing - is that right?

**Comment by Ichoran** [comment]
The overload should be `SeqOps.lengthCompare(that: Seq[_])` for symmetry.  Otherwise `that` doesn't necessarily have a length (as we define it).

**Comment by lrytz** [comment]
@Nth could you add this to https://github.com/scala/scala/pull/7805?

**Comment by som-snytt** [comment]
So to summarize, size matters and length also matters.

**Comment by NthPortal** [comment]
@lrytz the problem is, as @Ichoran noted, `Iterable` doesn't have a length, so it would need to be `SeqOps.lengthCompare(that: Seq[_])`. I'm concerned that having different parameter types will lead to confusion, and potentially people mistakenly thinking `sizeCompare` only takes a `Seq` as well. Additionally, unlike the other operations, it must be an alias (or forward, more precisely) of the `size*` variant, because it cannot accept all arguments to its `size*` variant. With that in mind, do we still want to add that `lengthCompare` variant?

**Comment by lrytz** [comment]
Would it be really that inconsistent to have `lengthCompare(that: Iterable[_])`, or is it only a "cosmetic" question?

**Comment by szeiger** [comment]
I think `lengthCompare(that: Iterable[_])` would be fine. As long as the LHS has a `length` it makes sense to compare it to the `size` of some other collection.

**Comment by Ichoran** [comment]
It wouldn't be _that_ inconsistent but the asymmetry is a bit odd.  (`a lengthCompare b` works, but `b lengthCompare a` doesn't, even though both have finite sizes.)  I think that's a worse problem than the suggestion that maybe people won't realize you can call `sizeCompare` with a non-`Seq` `Iterable` argument.  (Neither problem is very serious.)

**Comment by NthPortal** [comment]
should the aliasing be in the other direction for `lengthCompare(Iterable)`?

**Comment by Ichoran** [comment]
You mean the implementation is `-that.sizeCompare(this)` instead of `this.sizeCompare(that)`?  I don't think it should matter to anything.  Isn't the underlying implementation symmetric?

**Comment by NthPortal** [comment]
I mean

```scala
final def lengthCompare(that: Iterable[_]): Int = sizeCompare(that)
```

as opposed to

```scala
override final def sizeCompare(that: Iterable[_]): Int = lengthCompare(that)
def lengthCompare(that: Iterable[_]): Int = super.sizeCompare(that)
```

**Comment by Ichoran** [comment]
Oh, yeah, if we're not insisting both have `length`, `lengthCompare` should defer to `sizeCompare`

**Comment by som-snytt** [comment]
Despite the PR title, I'm not sure how you can "clean up length/size comparisons", they will always be an off-color product of patriarchal culture.
