### ISSUE TITLE
Immutable BitSet presents wrong values to filter

### ISSUE THREAD

**Issue by Ichoran** [scala/bug#11380]
```
Welcome to Scala 2.13.0-20190123-001909-5888c7d (OpenJDK 64-Bit Server VM, Java 1.8.0_191).
Type in expressions for evaluation. Or try :help.

scala> val x = collection.immutable.BitSet(125)
x: scala.collection.immutable.BitSet = BitSet(125)

scala> x.filter{ xi => println(xi); true }
61
```

Filter seems to be presenting the upper 64 bits as if they were the lower ones?  (61 + 64 = 125)

**Comment by diesalbla** [comment]
This seems to affect only the special `Bitset` subclass for two words (from 0 to 127 elements). Using a larger number seems to work fine: 
```
scala> val b = BitSet(125, 63, 65, 5, 129)
b: scala.collection.immutable.BitSet = BitSet(5, 63, 65, 125, 129)

scala> b.filter{ xi => print(s"$xi, "); true } ; println("")
129, 65, 125, 5, 63
```
Although, in the second case, I am curious as to why does it go in that order.

**Comment by mghildiy** [comment]
In my Intellij project, build.sbt has latest scala:

`scalaVersion := "2.13.0-M5"`

Following code:
`val bitSet = collection.immutable.BitSet(125)`
`bitSet.filter{ xi => println(xi); true }`

prints 125.

**Comment by Jasper-M** [comment]
It's caused by a more recent change: scala/scala#7486
