### ISSUE TITLE
2.13 Stream.append (deprecated) has changed semantics

### ISSUE THREAD

**Issue by jrudolph** [scala/bug#11392]
Before the `Stream.append`'s parameter was by-name, now it's not any more leading to issues.

https://github.com/scala/scala/blob/8a52aa19703004f0eb22d72a1efc82617924db32/src/library/scala/collection/immutable/Stream.scala#L74-L75

If it's deprecated anyway, it would make sense to keep the semantics close to what it was before. That will also help with cross-compiling.

**Comment by julienrf** [comment]
Indeed, I don’t know why we changed this. It’s probably an oversight. We should just make it take a by-name parameter instead (it delegates to `lazyAppendedAll`, which does take a by-name parameter).

**Comment by WellingR** [comment]
I am having a look at this, as it seems fairly easy to do
