### ISSUE TITLE
Integrate scala-java8-compat in the standard library ?

### ISSUE THREAD

**Issue by smarter** [scala/bug#11408]
I don't really get why https://github.com/scala/scala-java8-compat is still a separate library now that Scala is Java 8+ only. As more and more Java libraries (including the JDK itself) start taking advantages of Java 8 Optional/streams/..., using them from Scala becomes increasingly more cumbersome.

A built-in conversion between Option and Optional would be especially useful, it's not a big implementation cost, and it means that people won't reimplement it over and over and over again:
https://github.com/sbt/util/blob/develop/internal/util-logging/src/main/scala/sbt/util/InterfaceUtil.scala, https://github.com/scalacenter/bloop/blob/master/frontend/src/main/scala/bloop/util/JavaCompat.scala, https://github.com/superpixelhq/jdot/blob/master/src/main/scala/com/superpixel/jdot/util/ScalaConverters.scala, https://github.com/proglang/jgs/blob/master/GradualConstraints/Tests/src/test/java/de/unifreiburg/cs/proglang/jgs/util/Interop.scala, https://github.com/thaytharma/dc18-webauthnapplication/blob/master/webauthn-server-core/src/main/scala/com/yubico/scala/util/JavaConverters.scala, https://github.com/beatmadsen/xcs-main/blob/master/src/main/scala/com/madsen/util/JavaConversions.scala, https://github.com/atomist-attic/artifact-source/blob/master/src/main/scala/com/atomist/util/Utils.scala, [etc](https://github.com/search?l=Scala&q=java.util.optional&type=Code)

**Comment by SethTisue** [comment]
related: https://github.com/scala/scala-java8-compat/issues/113

**Comment by Ichoran** [comment]
I've been working only on the integrated version, not on the separate repository.

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/7458
