### ISSUE TITLE
Mark all the generated methods with an annotation

### ISSUE THREAD

**Issue by szhem** [scala/bug#11407]
Introduce a runtime annotation inserted on all the generated methods by scalac.

It will help to distinguish user-written methods and compiler-generated methods from each other that can be useful for code analysis tools e.g. code coverage ones.

For example, [jacoco](https://github.com/jacoco/jacoco) uses bytecode instrumentation to analyze code coverage (so that theoretically any language that runs on top of jvm can benefit from it) and such an annotation available at runtime can be pretty useful to exclude compiler-generated methods and fields from the coverage reports.

**Comment by hrhino** [comment]
Shouldn't we be marking synthetic methods as `ACC_SYNTHETIC` anyways? Does JaCoCo ignore that flag?

**Comment by szhem** [comment]
JaCoCo is pretty flexible and can be extended to support it, but care should be taken when marking generated methods with `ACC_SYNTHETIC`.

[Here are some details](https://fosdem.org/2019/schedule/event/kotlin_code_coverage_bytecode/)
Consider java8 lambda expression (18:36 on the timeline)
<img src="https://user-images.githubusercontent.com/1523889/53048796-a4772d00-34a6-11e9-846a-2e1f3dc1c08d.png" width="300">
... that is translated into `invokedynamic` instruction (18:56 on the timeline)
<img src="https://user-images.githubusercontent.com/1523889/53048903-e56f4180-34a6-11e9-95a9-988b2923164a.png" width="300">
... that calls generated synthetic method `lambda$fun$0` (19:12 on the timeline)
<img src="https://user-images.githubusercontent.com/1523889/53048984-164f7680-34a7-11e9-876e-420b0560f6a0.png" width="300">
... that in its order has `ACC_SYNTHETIC` flag set and contains instructions of the user provided code.

So in case of simple exclusion of the `ACC_SYNTHETIC` methods (19:53 on the timeline) coverage report will not include user-provided code
<img src="https://user-images.githubusercontent.com/1523889/53049169-8827c000-34a7-11e9-8ccc-1137f5559869.png" width="300">.

On the other hand in case of preserving synthetic method and a little bit of "hacking" the tools shows 100% coverage (20:24 on the timeline)
<img src="https://user-images.githubusercontent.com/1523889/53049799-eb662200-34a8-11e9-81b0-c25cb15f7fcd.png" width="600">.

Generally speaking `ACC_SYNTHETIC` is fine for compiler-generated code that does not include instructions of user-provided code (e.g. case classes, mix-ins, auto-generated accessors, etc.)

**Comment by Godin** [comment]
@hrhino @szhem while JaCoCo ignores all methods with attribute `synthetic` except ones whose name starts with `lambda$` (because they represent bodies of lambda expression),

IMO you can't mark generated `equals`, `hashCode` etc in `case class`es as `synthetic`, because then they won't be accessible from Java - here is example to back these words:

`javap -v -p Example.class`
```
{
  public Example();
    descriptor: ()V
    flags: ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #8                  // Method java/lang/Object."<init>":()V
         4: return

  public static void add();
    descriptor: ()V
    flags: ACC_PUBLIC, ACC_STATIC, ACC_SYNTHETIC
    Code:
      stack=2, locals=2, args_size=0
         0: return
}
```

attempt to compile `Test.java`

```
class Test {
  void test1() {
    new Example();
  }

  void test2() {
    new Example().add();
  }
}
```

results in

```
$ javac -cp . Test.java
Test.java:7: error: cannot find symbol
    new Example().add();
                 ^
  symbol:   method add()
  location: class Example
1 error
```

----

For the reference this ticket is triggered by the following discussion started by @szhem in JaCoCo Mailing List - https://groups.google.com/d/msg/jacoco/npl9SUL8_WA/jzoprA4pAwAJ

**Comment by som-snytt** [comment]
Typical question https://discord.com/channels/632150470000902164/632628489719382036/1095854194931540008

> is there a way to distinguish trait-generated forwarders from actual user-defined methods, at the JVM bytecode level? It seems that they don't set the SYNTHETIC flag, and don't seem to have any annotations

Not sure if @SethTisue intended to close. Maybe his close button is broken. This ticket renders as green open for me.

**Comment by SethTisue** [comment]
second time I've done that this week 🤷
