### ISSUE TITLE
surprising behavior for a val implementing an abstract def

### ISSUE THREAD

**Issue by dsilvasc** [scala/bug#11401]
I just ran into this in production where wiring dependencies with abstract members yielded unexpected null pointer exceptions:

```scala
Welcome to Scala 2.12.8 (GraalVM 1.0.0-rc10, Java 1.8.0_192).
Type in expressions for evaluation. Or try :help.

scala> abstract class FooModule {
     |   def role: String
     |   val serviceClient = s"service client for $role" // or in reality, new Client(role, region, etc)
     | }
defined class FooModule

scala> new FooModule { val role = "bob" }.serviceClient
res0: String = service client for null

scala> new FooModule { final val role = "bob" }.serviceClient
res1: String = service client for bob

scala> new FooModule { lazy val role = "bob" }.serviceClient
res2: String = service client for bob

scala> new FooModule { final lazy val role = "bob" }.serviceClient
res3: String = service client for bob

scala> new FooModule { final val role: String = "bob" }.serviceClient
res4: String = service client for null
```

Will scala 2.13, 2.14 or 3.x change the behavior of abstract members implemented as vals?  Otherwise, is there a way for the compiler to prohibit the definition of `val serviceClient` from referencing abstract members like `role`?

**Comment by dsilvasc** [comment]
Looks like this is similar to https://github.com/scala/bug/issues/8517 -- the difference here is that I'd prefer if the compiler rejected programs like this and forced me to write `lazy val serviceClient` to catch the issue during development instead of runtime.

**Comment by smarter** [comment]
> Will scala 2.13, 2.14 or 3.x change the behavior of abstract members implemented as vals?

No, but for Scala 3 we're working on an analysis to warn in all cases when you use uninitialized values (in Scala 2 there's `-Xcheckinit` to throw an exception on uninitialized access, although I'm not sure how thorough this is).

Another way to avoid the problem would be to use a constructor parameter:
```scala
scala>  abstract class FooModule(val role: String) { val serviceClient = s"service client for $role" }
defined class FooModule
scala> (new FooModule("bob") {}).serviceClient
res2: String = service client for bob
```

This isn't possible for traits yet but will be in the future: https://docs.scala-lang.org/sips/trait-parameters.html

**Comment by smarter** [comment]
See also https://contributors.scala-lang.org/t/lets-fix-scalas-initialization-order-when-overloading-values/2809, I think we can close this issue since there's nothing immediately actionable here.

**Comment by dsilvasc** [comment]
Thanks for the pointers.  Constructor args are probably the simplest way to avoid issues here, and I hadn't considered early initializers either:

```scala
scala> (new { val role = "bob" } with FooModule).serviceClient
res7: String = service client for bob
```

**Comment by dsilvasc** [comment]
Looking forward to @liufengyun's compiler warnings work.

**Comment by smarter** [comment]
Please don't use early initializers, they're going away: https://contributors.scala-lang.org/t/proposal-to-remove-early-initializers-from-the-language/2144 :)

**Comment by dsilvasc** [comment]
FYI, FindBugs catches this:

```
$ findbugs-3.0.1/bin/fb analyze -longBugCodes /tmp/b
H C UR_UNINIT_READ_CALLED_FROM_SUPER_CONSTRUCTOR UR: role isn't initialized in Bar.role() when invoked from constructor for superclass  At test.scala:[line 7]
```

**Comment by dsilvasc** [comment]
FindBugs and SpotBugs don't catch the issue when you use traits instead of classes though:

```scala
trait Foo {
  def x: String
  val y = s"x: $x"
}

trait Bar extends Foo {
  val x: String = "bob"
}

object Bar extends Bar
```

No complaints from FindBugs/SpotBugs on that one.  FindBugs has been abandoned, and SpotBugs doesn't catch the initialization issue in the resulting bytecode, which when decompiled by fernflower into java looks something like

```java
public interface Foo {
   void Foo$_setter_$y_$eq(final String x$1);

   String x();
   String y();

   static void $init$(final Foo $this) {
      $this.Foo$_setter_$y_$eq((new StringBuilder(3)).append("x: ").append($this.x()).toString());
   }
}

public interface Bar extends Foo {
   void Bar$_setter_$x_$eq(final String x$1);

   String x();

   static void $init$(final Bar $this) {
      $this.Bar$_setter_$x_$eq("bob");
   }
}

public final class Bar$ implements Bar {
   public static Bar$ MODULE$;
   private final String x;
   private final String y;

   static {
      new Bar$();
   }

   public String x() {
      return this.x;
   }

   public void Bar$_setter_$x_$eq(final String x$1) {
      this.x = x$1;
   }

   public String y() {
      return this.y;
   }

   public void Foo$_setter_$y_$eq(final String x$1) {
      this.y = x$1;
   }

   private Bar$() {
      MODULE$ = this;
      Foo.$init$(this);
      Bar.$init$(this);
   }
}
```

**Comment by dsilvasc** [comment]
Suggested the example with traits as something SpotBugs might want to catch: https://github.com/spotbugs/spotbugs/issues/879
