### ISSUE TITLE
Optimize ListBuffer

### ISSUE THREAD

**Issue by lrytz** [scala/bug#11409]
```
scala> val b = collection.mutable.ListBuffer.empty[String] += "a"
b: scala.collection.mutable.ListBuffer[String] = ListBuffer(a)

scala> b.update(0, "a1")

scala> b
res2: scala.collection.mutable.ListBuffer[String] = ListBuffer(a1)

scala> b += "b"
res3: b.type = ListBuffer(a1)
```

The `last0` field of `ListBuffer` is not updated.

**Comment by SethTisue** [comment]
@lrytz @julienrf @szeiger @joshlemer @NthPortal somebody want to pick this up for RC1?

**Comment by SethTisue** [comment]
also interested in views on whether this is an RC1 blocker or not

**Comment by NthPortal** [comment]
Is this an optimisation issue? It kinda seems like a bug.

If I am correct that it is a bug, I think it's a blocker for RC1; otherwise, since it doesn't seem to affect any method that isn't already defined (thus making it a binary-compatible change), I'd consider it not a blocker.

@SethTisue I can't pick this up, sorry. I am at especially low capacity of late.

**Comment by Jasper-M** [comment]
AFAICT the bug described in the report is fixed:

```
Welcome to Scala 2.13.0-pre-f1c1d62 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_152).
Type in expressions for evaluation. Or try :help.

scala> val b = collection.mutable.ListBuffer.empty[String] += "a"
b: scala.collection.mutable.ListBuffer[String] = ListBuffer(a)

scala> b.update(0, "a1")

scala> b
res1: scala.collection.mutable.ListBuffer[String] = ListBuffer(a1)

scala> b += "b"
res2: b.type = ListBuffer(a1, b)
```

But apparently the intent of the ticket changed to optimizing the fix?

**Comment by SethTisue** [comment]
> apparently the intent of the ticket changed to optimizing the fix?

@szeiger do you recall why you changed the ticket name to "optimize"?

it looks like we ought to just close this, perhaps after adding the test from https://github.com/julienrf/scala/commit/c105f12900bec6e6a8eea80e9b50fd78ea037bb4

**Comment by szeiger** [comment]
`setNext` is very inefficient because it has to traverse the entire tail. I'm currently trying to figure out how this was fixed in the first place. All the obvious methods are unchanged.

**Comment by szeiger** [comment]
Ah, this was fixed even *before* https://github.com/julienrf/scala/commit/c105f12900bec6e6a8eea80e9b50fd78ea037bb4 which is confusingly located in a branch named `fix-listbuffer`. There's more room for optimization in the other methods that call `setNext`.
