### ISSUE TITLE
Method type syntax in errors & warnings doesn't have colon for the return type

### ISSUE THREAD

**Issue by psilospore** [scala/bug#11416]
This error seems like it should be:
```
 error: ambiguous reference to overloaded definition,
18-both method apply in object Foo2 of type (z: String)Base[T]
19-and  method apply in object Foo2 of type (a: Int)Base[T]
```
had colons before the return type like this?
```
 error: ambiguous reference to overloaded definition,
18-both method apply in object Foo2 of type (z: String): Base[T]
19-and  method apply in object Foo2 of type (a: Int): Base[T]
```
Not sure if this is standard so it might not be a bug. But if it is valid I don't mind picking this up.

**Comment by hrhino** [comment]
That's the long-running way that scalac prints `MethodType`s, and matches the way that I usually mistype methods signatures the first time around. It's probably inspired by Java's descriptors (of the form `(I)LBase;` in the above example).

I think it makes sense to print these sorts of things in as close to real Scala code as can be done, though.

**Comment by som-snytt** [comment]
This is how the types are represented in the spec.

There was another PR or ticket to have REPL print everything in Scala syntax. It would be handy if there were a compiler flag to pick a pretty printing option.

**Comment by SethTisue** [comment]
> There was another PR or ticket to have REPL print everything in Scala syntax

you're probably thinking of https://github.com/scala/bug/issues/10024
