### ISSUE TITLE
Different compilation times when referring to an object by variable vs creating it inline

### ISSUE THREAD

**Issue by anatoliykmetyuk** [scala/bug#11413]
Consider the following source:

```scala
trait A
trait F[X]

trait Foo {
  type V
  def ===[X](implicit ev: V =:= X) = ev
}

trait Weird {
  import Types._

  type X = F23

  val foo = new Foo { type V = X }

  foo.===[X]  // Compilation time: 3 seconds
  // new Foo { type V = X }.===[X]  // Compilation time: 16 seconds
}

object Types {
  type F1  = F[A  ]
  type F2  = F[F1 ]
  type F3  = F[F2 ]
  type F4  = F[F3 ]
  type F5  = F[F4 ]
  type F6  = F[F5 ]
  type F7  = F[F6 ]
  type F8  = F[F7 ]
  type F9  = F[F8 ]
  type F10 = F[F9 ]
  type F11 = F[F10]
  type F12 = F[F11]
  type F13 = F[F12]
  type F14 = F[F13]
  type F15 = F[F14]
  type F16 = F[F15]
  type F17 = F[F16]
  type F18 = F[F17]
  type F19 = F[F18]
  type F20 = F[F19]
  type F21 = F[F20]
  type F22 = F[F21]
  type F23 = F[F22]
  type F24 = F[F23]
  type F25 = F[F24]
}
```

In it, consider the two lines:

```scala
  foo.===[X]  // Compilation time: 3 seconds
  // new Foo { type V = X }.===[X]  // Compilation time: 16 seconds
```

If you have the first one uncommented and the second one commented, the compilation time of the source file is ~3 seconds. If you have the second one uncommented and the first one commented, the compilation time goes up to 16 seconds.

Precisely, if you save the file with the name `Weird.scala`, here are the steps to reproduce:

```bash
MacBook-Pro-Anatolii:weird anatolii$ scalac -version
Scala compiler version 2.12.8 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.
MacBook-Pro-Anatolii:weird anatolii$ # First line uncommented
MacBook-Pro-Anatolii:weird anatolii$ time scalac Weird.scala

real	0m4.238s
user	0m8.946s
sys	0m0.480s
MacBook-Pro-Anatolii:weird anatolii$ # Second line uncommented
MacBook-Pro-Anatolii:weird anatolii$ time scalac Weird.scala

real	0m15.686s
user	0m21.433s
sys	0m0.449s
```

The time seems to be growing, maybe non-linearly, with X in the case of the second line and remains unchanged in the case of the first line. E.g. for `type X = F25`, the time goes up to ~110 seconds for the second line and remains ~3 seconds for the first line:

```bash
MacBook-Pro-Anatolii:weird anatolii$ time scalac Weird.scala  # Second line for X = F25

real	1m53.302s
user	1m55.549s
sys	0m1.277s
MacBook-Pro-Anatolii:weird anatolii$ time scalac Weird.scala  # First line for X = F25

real	0m3.568s
user	0m8.598s
sys	0m0.358s
```

The access to the path-dependent type from the member method that uses the `=:=` implicit seems to be important: when you remove any of these components, the issue won't reproduce. Also, the issue won't reproduce if you refer to the nested type as `F[F[F...` as opposed to `F25`.

Scalac and JVM versions:

```bash
MacBook-Pro-Anatolii:weird anatolii$ scalac -version
Scala compiler version 2.12.8 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.
MacBook-Pro-Anatolii:weird anatolii$ java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

What's going on here?

**Comment by SethTisue** [comment]
is it also reproducible in Scala 2.13.0-M5-1775dba (a recent nightly build, available from Maven Central)?

**Comment by anatoliykmetyuk** [comment]
Nope, I can't reproduce it on Scala 2.13.0-M5-1775dba.

**Comment by SethTisue** [comment]
very nice minimization job, by the way!

@retronym should this be added to our tests or benchmarks somehow?
