### ISSUE TITLE
Deprecations in 2.12 based on latest 2.13 collections

### ISSUE THREAD

**Issue by adriaanm** [scala/bug#11411]
After 2.13.0-M4 we should have the complete picture of what should be deprecated in 2.12 to aid in the transition to the new collections.

**Comment by SethTisue** [comment]
I'm wondering if we should just close this, on the assumption that we'd probably have noticed any missing deprecations by now

**Comment by eed3si9n** [comment]
https://docs.scala-lang.org/overviews/core/collections-migration-213.html can be used as an entry point into figuring out what was removed in 2.13 etc.

In terms of "aid in the transition to the new collections", maybe we could deprecate things like `/:`. - https://github.com/scala/scala/blob/v2.12.9/src/library/scala/collection/TraversableOnce.scala#L154

2.13 removed a bunch of classes and traits, but I'm not sure if those are commonly hit. For example, `ArrayStack` was removed. On 2.12.9 ArrayStack isn't deprecated https://github.com/scala/scala/blob/v2.12.9/src/library/scala/collection/mutable/ArrayStack.scala.

**Comment by eed3si9n** [comment]
Here's foldLeft - https://github.com/scala/scala/pull/8317

**Comment by eed3si9n** [comment]
Fixed in scala/scala#8317
Please reopen if there are further specific todos.
