### ISSUE TITLE
Scala implicit def not found if it is named toString

### ISSUE THREAD

**Issue by pathikrit** [scala/bug#11422]
**Compiles**
```scala
object Foo {
  implicit def asString(i: Int): String = i.toString      
  def foo(x: String) = println(x)
}    
import Foo._
foo(23)
```

**Fails to Compile**
```scala
object Foo {
  implicit def toString(i: Int): String = i.toString      
  def foo(x: String) = println(x)
}
import Foo._
foo(23)    
```

Error:
```
error: type mismatch;
found   : scala.this.Int(23)
required: String
  foo(23)
```

**Comment by som-snytt** [comment]
What version fails to compile the sample? Please include the phase of the moon. It works for me, but a bug in implicit shadowing, which is facing mandatory retirement age, seemed probable enough. Implicit shadowing should have stopped driving years ago.

**Comment by pathikrit** [comment]
@som-snytt : Check this out - https://scalafiddle.io/sf/E6tE3dW/0

**Comment by som-snytt** [comment]
The `import` is relevant. `-Xlog-implicits` explains:
```
t11422.scala:13: <toString: error> is not a valid implicit value for Int(23) => String because:
reference to toString is ambiguous;
it is both defined in class Object and imported subsequently by
import Foo._
```
The implicit must be accessible without a prefix, and inherited definitions have higher binding precedence than imports. An explicit `toString(23)` fails for the same reason. I apologize for having maligned the implicit shadower without cause.

**Comment by pathikrit** [comment]
Isn't this still a bug? And, this compiles fine:

```
trait Foo {
  def asString: String = "hello"
}

object Bar extends Foo {
  implicit def asString(i: Int): String = i.toString
}

import Bar._
def foo(x: String) = x

foo(23)
```

**Comment by som-snytt** [comment]
More like:
```
import language._

object Foo {
  implicit def toString(i: Int): String = i.toString
  def foo(x: String) = println(x)
  def f() = foo(23)  // OK
}

object Bar {
  implicit def asString(i: Int): String = i.toString
  def bar(x: String) = println(x)
}

object Main {
  def asString() = toString()
  def main(args: Array[String]) = println {
    import Bar._
    bar(23)        // neither
    import Foo._
    toString(23)   // nope
    foo(23)        // nope
  }
}
```
It's expected behavior per the previous comment. `toString` and `asString` are imported in the block, but defined in enclosing scope: the import cannot shadow the definition, so the name is ambiguous.
