### ISSUE TITLE
HTML in string literal in examples of Scaladoc does not properly escaped

### ISSUE THREAD

**Issue by Atry** [scala/bug#11424]
```
/** Some scaladoc that contains string literal of HTML
  * {{{
  * val button = "<button>My Button</button>" 
  * }}}
  */
class HtmlDoc
```

```
$ scaladoc -version
Scaladoc version 2.12.8 -- Copyright 2002-2018, LAMP/EPFL and Lightbend, Inc.
```

```
$ scaladoc HtmlDoc.scala 
model contains 2 documentable templates
```
<img width="1552" alt="2019-03-08 00 07 06" src="https://user-images.githubusercontent.com/601530/53970788-73e5f300-4136-11e9-8827-2b6d3bb2596c.png">

**Comment by OberstK** [comment]
I had a look into this and could trace down why this is happening. I will open a PR for a fix, but there is some need for discussion if I missed inter-dependencies with other behavior around the rendering of code within a comment. I hope someone else can bring in more insight

**Comment by Atry** [comment]
Hi @SethTisue , could you reopen this issue because this bug seems still unfixed to me in Scala 2.13.1.

Given the following comments in the source file:
```
  * @example XHTML literals with text attributes
  * {{{
  * @html
  * val myDiv = <div class="my-class" tabindex="42"></div>
  * myDiv.value.nodeName should be("DIV")
  * myDiv.value.className should be("my-class")
  * myDiv.value.tabIndex should be(42)
  * }}}
  *
  * Nested XHTML literals with interpolation:
  *
  * {{{
  * @html
  * val myDiv2 = <div style="color: red;" tabIndex={99999} title="my title" class={"my-class"}><div>text</div><span style={"color: blue;"} tabIndex={99}></span><div innerHTML={"html"}></div><div></div>{myDiv.bind}</div>
  * myDiv2.watch()
  * myDiv2.value.outerHTML should be("""<div style="color: red;" tabindex="99999" title="my title" class="my-class"><div>text</div><span style="color: blue;" tabindex="99"></span><div>html</div><div></div><div class="my-class" tabindex="42"></div></div>""")
  * }}}
```

It renders to:

```
@html
val myDiv =


myDiv.value.nodeName should be("DIV")
myDiv.value.className should be("my-class")
myDiv.value.tabIndex should be(42)
Nested XHTML literals with interpolation:

@html
val myDiv2 =



text<span style={"color: blue;"} tabIndex={99}></span>



{myDiv.bind}
myDiv2.watch()
myDiv2.value.outerHTML should be("""



text" tabindex="99">

html



""")
```

* Source code: https://github.com/GlasslabGames/html.scala/blob/75887b53ef55d341453cbaf4c0110ca4b24d4576/html/src/main/scala/org/lrng/binding/html.scala#L711
* Generated Scaladoc: https://javadoc.io/static/org.lrng.binding/html_sjs0.6_2.12/1.0.2+34-75887b53/org/lrng/binding/html.html

**Comment by SethTisue** [comment]
`CommentFactoryBase.scala` has:

```
  private val SafeTags =
    new Regex("""((&\w+;)|(&#\d+;)|(</?(abbr|acronym|address|area|a|bdo|big|blockquote|br|button|b|caption|cite|code|col|colgroup|dd|del|dfn|em|fieldset|form|hr|img|input|ins|i|kbd|label|legend|link|map|object|optgroup|option|param|pre|q|samp|select|small|span|strong|sub|sup|table|tbody|td|textarea|tfoot|th|thead|tr|tt|var)( [^>]*)?/?>))""")
```

thus, I suspect the different behavior you're seeing in your new example is simply because `div` isn't on the safe list, whereas `button` is. if so, this is a different bug. (and I don't know what the right design here is — I don't think I understand the intent behind the current code)
