### ISSUE TITLE
 Scala Classloader with java.lang.ClassLoader.registerAsParallelCapable

### ISSUE THREAD

**Issue by ajithme** [scala/bug#11429]
Currently i have a custom classloader ``abc.MyClassLoader``which extends ``java.net.URLClassLoader#URLClassLoader``, and i want to enable my custom classloader as parallel capable. To do this i need to call a static method from my custom classloader ``java.lang.ClassLoader#registerAsParallelCapable``

In java custom classloader this would be as straightforward as having registration done in a static block, but currently i see that for scala i need to do this is a companion object and not in my custom class, but it will not take affect as inside ``java.lang.ClassLoader#registerAsParallelCapable`` the class name is registered via its name which is got by ``Reflection.getCallerClass()`` which will give companion class name ``abc.MyClassLoader$`` instead of actual class  ``abc.MyClassLoader`` thus failing to enforce parallel capability for classloader

Linking original issues via which the problem was found:
https://issues.apache.org/jira/browse/SPARK-26961

**Comment by ajithme** [comment]
cc @SethTisue @szeiger @Ichoran

**Comment by som-snytt** [comment]
You need [SIP-30](https://docs.scala-lang.org/sips/static-members.html) which is in dotty but not yet Scala 2? The annotation requests the member as a static member of the companion class. It looks like it works.
```
dotty $ cat sandbox/C.scala

import java.net._

class C extends URLClassLoader(new Array[URL](0))
object C { @annotation.static val x = { ClassLoader.registerAsParallelCapable(); () } }
dotty $ ./bin/dotc sandbox/C.scala
dotty $ javap -private -verbose C.class
[snip]
  private static {};
    descriptor: ()V
    flags: ACC_PRIVATE, ACC_STATIC
    Code:
      stack=1, locals=0, args_size=0
         0: invokestatic  #25                 // Method java/lang/ClassLoader.registerAsParallelCapable:()Z
         3: pop
         4: getstatic     #30                 // Field scala/runtime/BoxedUnit.UNIT:Lscala/runtime/BoxedUnit;
         7: putstatic     #32                 // Field x:Lscala/runtime/BoxedUnit;
        10: return
```

**Comment by ajithme** [comment]
@som-snytt Thanks for explanation. Unfortunately i cannot upgrade to higher scala version now. So i suppose moving my classloader implementation to java is the only option.?

**Comment by som-snytt** [comment]
I haven't experimented, and maybe there is a better technique. You could write a minimal shim in Java that delegates to code in Scala. I see the mechanism requires superclasses to be registered, so extending the Scala class is not an option.

**Comment by hrhino** [comment]
Yeah, this is a pretty horrid API. I've seen this done, and the safest way is probably
```scala
// MyLoader.scala
sealed abstract class MyLoader { ... }
object MyLoader {
  def apply(): MyLoader = new MyLoader0
}
```
```java
// MyLoader0.java
/* package-private */ final class MyLoader0 extends MyLoader {
  static { registerAsParallelCapable(); }
}
```

which isn't nice but works.

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/9450

**Comment by ajithme** [comment]
Linking original issues via which the problem was found:
https://issues.apache.org/jira/browse/SPARK-26961

**Comment by som-snytt** [comment]
https://github.com/scala/scala/pull/9475
