### ISSUE TITLE
Error if not an annotation

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11428]
Consider this example:
```
import annotation.switch

class switch {
  def test(x: Int) = (x: @switch) match {
    case 1 | 2 | 3 => ()
  }
}
```
Dotty reports:
```
-- [E007] Type Mismatch Error: tests/allan/Test.scala:4:25 ---------------------
4 |  def test(x: Int) = (x: @switch) match {
  |                         ^^^^^^^
  |                         found:    switch
  |                         required: scala.annotation.Annotation
  |                         
one error found
```
And scalac
```
tests/allan/Test.scala:1: warning: imported `switch` is permanently hidden by definition of class switch
import annotation.switch
                  ^
one warning found
```
I would say an error is warranted. One guess is that it was lost under https://github.com/scala/scala/pull/1901.

Description copied from https://github.com/lampepfl/dotty/issues/3617.

**Comment by som-snytt** [comment]
Related PR for related issue https://github.com/scala/scala/pull/7546

**Comment by psilospore** [comment]
We can probably close this. I have this covered in https://github.com/scala/scala/pull/7546/files#diff-b351be41bee21402ad433b314b590272 now.

**Comment by som-snytt** [comment]
Thanks, @psilospore
