### ISSUE TITLE
Scalafix rewrite(s) for 2.12->2.13 non-collection library changes

### ISSUE THREAD

**Issue by dwijnand** [scala/bug#11430]
(Related scala/scala-dev#327 which seems to be about language changes in 2.13)

There are a number of changes in the standard library, to the point I think 2.13 should ship with a Scalafix rewrite for them.

In particular, I'm thinking of https://github.com/scala/scala/pull/5830 (which is a re-submission of https://github.com/scala/scala/pull/5677) which ~deprecated a number of things and suggests these replacements~:

(2019-05-09 edit: No, it didn't.  The original PR did, the re-submission just removed the already-deprecated code.)

> To compensate for the associated deprecations in your own code:
> 
> * `compat.Platform.EOL` --> add `import java.lang.System.{lineSeparator => EOL}`
> * `compat.Platform.currentTime` --> add `import java.lang.System.{currentTimeMillis => currentTime}`
> * `compat.Platform.arraycopy` --> add `import java.lang.System.arraycopy`
> * `sys.error` --> `throw new RuntimeException` (or subclass)
> * `sys.exit` --> `System.exit`
> * `sys.props` --> `System.getProperties().asScala` (with `import scala.collection.JavaConverters._`)
> * `sys.env` --> `System.getenv().asScala`
> * `sys.runtime` --> `Runtime.getRuntime`
> * `sys.addShutdownHook` --> `Runtime.getRuntime.addShutdownHook(new Thread(() => ...))`
> * `Console.BOLD` --> `AnsiColor.BOLD` (with `import scala.io.AnsiColor`)
> * `Console.readLine` --> `Console.in.readLine()`
> * `concurrent.Lock` --> `java.util.concurrent.locks.ReentrantLock` (lock/unlock)

I argue that deprecations in the standard library affect the entire ecosystem, so the release should come with a (or multiple) rewrites.  Not because the migration is hard, but because it's so vastly impacting.  I would expect it to be much easier than the collection rewrites.

I optimistically target 2.13.0-RC1 🙂

**Comment by dwijnand** [comment]
I've implemented these in https://github.com/dwijnand/scala-rewrites.

@olafurpg any chance I could get you (and/or anyone else with Scalafix expertise) to review it?

If the Scala maintainers like it I was thinking I could transfer the repo to the scala org so it can be an official part of the 2.13.0 release.

**Comment by olafurpg** [comment]
@dwijnand I'm happy to review, where is the best place to leave comments?

For example, matching against `Term.Select` below
https://github.com/dwijnand/scala-rewrites/blob/ab9e425e4499fc13d3b3451ce6393c05e3541f08/rewrites/src/main/scala/fix/Scala_2_13.scala#L141
will make the rewrite do nothing when colors are referenced as plain identifiers `BLACK` from a wildcard `import Console._`.

**Comment by dwijnand** [comment]
@olafurpg 1-n issues and/or 1-n PRs to the repo, if that works for you.

Good point about Term.Name.  I handle that for EOL, but not everywhere.  I'll do that.

**Comment by dwijnand** [comment]
Updated the ticket: The PR that landed _didn't_ add all those deprecations.  The original PR did, but the re-submission just removed the already-deprecated code.

I'm continuing to progress in the scala-rewrites repo.

**Comment by dwijnand** [comment]
Closing in favour of progress being made and tracked in https://github.com/scala/scala-rewrites.
