### ISSUE TITLE
parser issue with `var` and `_`: default-value syntax and placeholder syntax collide

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#11437]
as reported at https://stackoverflow.com/questions/55182423/weird-behavior-of-anonymous-function-with-placeholder :

```
val adder: Int => Int = _ + 3 // Works fine
var adder: Int => Int = (_ + 3) // Works fine
var adder: Int => Int = _ + 3 // Error
```

The error is "error: ';' expected but identifier found.", pointing to the `+`.

@travisbrown writes on SO:

> The problem you're seeing seems to be that an underscore immediately following the = in a var definition is interpreted as this special default initial value, and the alternative use as a placeholder in a function is not considered. This behavior seems to me like it must be a bug

Dotty has the same issue.

**Comment by SethTisue** [comment]
(As with any "good first issue", there is a possibility that it's actually hard to fix. Discovering that, and recording why here on the ticket, would be a nice contribution regardless.)

**Comment by som-snytt** [comment]
That was a good first issue of the day.

**Comment by SethTisue** [comment]
> That was a good first issue of the day.

Som Snytt eats good first issues for breakfast, as they say.

**Comment by som-snytt** [comment]
@SethTisue thanks for mentioning the doti status. I still think we need a `f--d in doti` label.

I came across it because I thought you had created an issue for default var init.
