### ISSUE TITLE
"-target:jvm-1.8" doesn't work and scalac produces code with class file version 55.0 while 52.0 is expected

### ISSUE THREAD

**Issue by plokhotnyuk** [scala/bug#11441]
Prerequisites:
- Installed JDK 8 in `/usr/lib/jvm/jdk1.8.0`
- Installed JDK 11 in `/usr/lib/jvm/jdk-11`
- Installed SBT and git tools

Steps to reproduce:
1. Clone `jsoniter-scala` repo:
```sh
git clone https://github.com/plokhotnyuk/jsoniter-scala.git
```
2. Enter to the cloned directory and checkout for the specific commit:
```sh
cd jsoniter-scala
git checkout  0191472aab4e06e64f9aa086dfdeff89ab682713
```
3. Compile and run benchmarks with JDK 11:
```sh
sbt -java-home /usr/lib/jvm/jdk-11 'jsoniter-scala-benchmark/jmh:run TwitterAPIBenchmark.readJsoniterScala'
```
4. Compile and run benchmarks with JDK 8:
```sh
sbt -java-home /usr/lib/jvm/jdk1.8.0 'jsoniter-scala-benchmark/jmh:run TwitterAPIBenchmark.readJsoniterScala'
```
5. Get the following error instead expected running of benchmarks:
```
[error] (jsoniter-scala-benchmark / Jmh / generateJmhSourcesAndResources) java.lang.UnsupportedClassVersionError: com/jsoniter/output/JsoniterJavaSerializer has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```

W/A for my case is to use JDK 8 for compilation and JDK 11 for running of benchmarks:
```
sbt -java-home /usr/lib/jvm/jdk1.8.0 'jsoniter-scala-benchmark/jmh:run -jvm /usr/lib/jvm/jdk-11/bin TwitterAPIBenchmark.readJsoniterScala'
```

But in general case when JDK 11 is a default Java it can lead for publishing (or releasing) of library which can run on JDK 11 only...

**Comment by michelou** [comment]
Try the following before running sbt with a different JDK version (eg. JDK 8 -> JDK 11 in your case) :
```
> rm -rf ~/.sbt
```

**Comment by plokhotnyuk** [comment]
@michelou it doesn't resolve the subject issue

**Comment by adriaanm** [comment]
I doubt this is a scalac bug. Is the problematic bytecode generated by javac or scalac? If it's javac, this is the wrong tracker for this issue. If it's somehow an sbt issue, that's over at https://github.com/sbt/sbt/issues

**Comment by plokhotnyuk** [comment]
@adriaanm Thanks for the hint! It affects only java classes.
