### ISSUE TITLE
Stream `find` leaks

### ISSUE THREAD

**Issue by OlegYch** [scala/bug#11443]
using 2.13.0-M5-1775dba (published on 16-Feb-2019)

this throws OOME
```
//  type S[A] = Stream[A]
//  val S = Stream
  type S[A] = LazyList[A]
  val S = LazyList

  S.iterate(1)(_ + 1).find(_ => false)
```

this correctly runs forever:
```
    @annotation.tailrec def find[A](s: S[A])(p: A => Boolean): Option[A] = {
      s.headOption match {
        case Some(x) if p(x) => Some(x)
        case None => None
        case _ => find(s.tail)(p)
      }
    }
    find(S.iterate(1)(_ + 1))(_ => false)   
```

perhaps `find` should be overriden in the same way `Stream#foreach` is?

--------

Status: `LazyList` is fixed; `Stream` still needs to be

**Comment by NthPortal** [comment]
If I'm not mistaken, since `find` returns `Option[A]`, this fix is binary compatible?

**Comment by OlegYch** [comment]
@NthPortal i suspect adding tailrec breaks bincompat, though can't be sure

i've found a couple other functions with the same problem though - collect and collectFirst
(though collect is only broken in LazyList)

**Comment by OlegYch** [comment]
ie with -Xmx50m
```
Stream.iterate(1)(_ + 1).collect{ case i if i > 10000000 => i }.headOption //works
LazyList.iterate(1)(_ + 1).collect{ case i if i > 10000000 => i }.headOption //fails with OOME
Stream.iterate(1)(_ + 1).collectFirst{ case i if i > 10000000 => i } //fails with OOME
LazyList.iterate(1)(_ + 1).collectFirst{ case i if i > 10000000 => i } //fails with OOME
```

**Comment by smarter** [comment]
Making a method tailrec doesn't break binary-compatibility.

**Comment by NthPortal** [comment]
The concern was whether or not adding an override (since the method is not currently defined in `LazyList`) is binary compatible

**Comment by SethTisue** [comment]
> The concern was whether or not adding an override (since the method is not currently defined in `LazyList`) is binary compatible

it appears so: https://github.com/lightbend/migration-manager/commit/e607d192074215f4bf6f9b3e58644866582bf856

but also, it's reallllllly really time to enable MiMa now on the 2.13.x branch, I am making a note to myself to finally do that this week

**Comment by SethTisue** [comment]
as an exercise, I verified the bincompat as follows. the change is clearly backwards compatible, the question is whether it's forward compatible, that is, whether code compiled when the override is present still works if the override is removed

given

```
trait A {
  def foo = 2
}

class B extends A {
  override def foo = 3
}
```

compiling `(new B).foo` gives

```
      10: invokevirtual #72                 // Method B.foo:()I
```

note the reference to `B.foo`. if we change `B` to just `class B extends A` with no override, recompile B, and then re-rerun the existing bytecode for `(new B).foo` without regenerating it, there is no linkage error and `2` is returned as expected

 a useful reference on these issues is https://docs.oracle.com/javase/specs/jls/se8/html/jls-13.html , which states:

```
here is a list of some important binary compatible changes that the Java programming language supports: [..] Moving a method upward in the class hierarchy
```

which is what is happening here when considering the forward-compat side.

anyway, all this is surely old hat, but I just wanted to go over it again for myself

**Comment by smarter** [comment]
Yeah adding/removing an override in a class is fine I think, I'm not so sure that this also the case when doing the same in a trait given the complicated encoding used.

**Comment by SethTisue** [comment]
as we were just discussing on Gitter, it's pretty awesome that the reason the `@tailrec` version can run forever is that the generated bytecode overwrites `this` before looping:

```
      19: invokevirtual #474                // Method tail:()Lscala/collection/immutable/LazyList;
  ...
      24: astore_0
      25: goto          0
```

**Comment by SethTisue** [comment]
@NthPortal are you interested in addressing `collect` and `collectFirst` as well in your PR?

**Comment by NthPortal** [comment]
@SethTisue yeah, I can try to do that

**Comment by NthPortal** [comment]
should we have a tailrec implementation in `LinearSeqOps` instead? (the tailrec could be a private or static method)

**Comment by NthPortal** [comment]
a few things I've discovered:

1) `collect` was already tail-recursive, but still OOMed
2) `filter` appears to OOM as well
3) both of these are despite the fact that they pass the GC tests in `LazyListTest`

**Comment by OlegYch** [comment]
yep i confirm filter has regressed as well (compared to Stream)
both filter and collect in LazyStream are implemented via private tailrec method, but they are themselves not tail recursive
perhaps moving that function to an object will do the trick, this is what Stream.collect seems to be doing

**Comment by NthPortal** [comment]
the question is though, why don't the `*_allows_GC` tests catch that it's not actually being collected?

I will certainly look into moving the methods to the companion, though I'm concerned there are other methods for which this is a problem that we haven't caught. It's not clear to me why some tail-recursive methods work fine (such as my new implementation of `find`) and some don't. And until/unless we can get a reliable fix to the `*_allows_GC` tests, it's difficult to check what works and what doesn't.

**Comment by NthPortal** [comment]
Update: the reason the `*_allows_GC` tests did not catch the problem with `filter` is because they only checked the case of retaining all values, not of dropping all values.

**Comment by NthPortal** [comment]
moving `collectTrampoline` and `collectState` to the companion had no effect

in class:

```scala
  // removing @inline makes no difference, I've checked
  @inline private def collectTrampoline[B](pf: PartialFunction[A, B]): LazyList[B] =
    newLL(collectState(pf))

  @tailrec
  private def collectState[B](pf: PartialFunction[A, B]): State[B] =
    if (isEmpty) State.Empty
    else {
      val marker = Statics.pfMarker
      val res = pf.applyOrElse(head, ((_: A) => marker).asInstanceOf[A => B])
      if (res.asInstanceOf[AnyRef] eq marker) tail.collectState(pf)
      else sCons(res, tail.collectTrampoline(pf))
    }
```

in companion:

```scala
  private def collectTrampoline[A, B](ll: LazyList[A], pf: PartialFunction[A, B]): LazyList[B] =
    newLL(collectState(ll, pf))

  @tailrec
  private def collectState[A, B](ll: LazyList[A], pf: PartialFunction[A, B]): State[B] =
    if (ll.isEmpty) State.Empty
    else {
      val marker = Statics.pfMarker
      val res = pf.applyOrElse(ll.head, ((_: A) => marker).asInstanceOf[A => B])
      if (res.asInstanceOf[AnyRef] eq marker) collectState(ll.tail, pf)
      else sCons(res, collectTrampoline(ll.tail, pf))
    }
```

anyone have any idea where the reference to the beginning of the `LazyList` is being held onto in either method pair? I'm out of ideas

**Comment by OlegYch** [comment]
@NthPortal have you tried testing Stream with this framework? these fail for me:
```
  @Test
  def filter_all_out_foreach_allows_GC(): Unit = {
    assertStreamOpAllowsGC(_.filter(_ => false).foreach(_), _ => ())
  }

  @Test
  def collect_all_out_foreach_allows_GC(): Unit = {
    assertStreamOpAllowsGC(_.collect{case -1 => 1}.foreach(_), _ => ())
  }
```
perhaps *allowsGC* helpers are not what they seem

**Comment by OlegYch** [comment]
oh, they need for at least some values to be retained to have a chance to force gc

**Comment by OlegYch** [comment]
any idea why this fails?
```
assertStreamOpAllowsGC((ll, check) => ll.collect({ case i if { check(i); false } => i }), _ => ())
```

**Comment by OlegYch** [comment]
this doesn't
```
assertStreamOpAllowsGC((ll, check) => ll.collect{case i if i > 100 => 1}.foreach(check), _ => ())
```

**Comment by OlegYch** [comment]
hm, one reason might be that Stream.collect doesn't actually drop head reference, but Stream is less memory intensive than LazyStream

**Comment by NthPortal** [comment]
my best guess as to the source of the leak is that `newLL(=> X)` (an alias for `new LazyList(() => X)`) captures the start of the `LazyList` in a closure, and that closure doesn't stop being referenced until the next `State` is resolved. *if* that is the case:
- there are a lot of method implementations in `LazyList` that need to be changed
- the implementations cannot use tail recursion
- the implementations need to either:
  - use `var`s and `while` loops (so that the closure captures the `var` as an `ObjectRef`, which will not hold on to the start of the `LazyList`)
  - use `LazyList.from(iterator.<op>)`

**Comment by OlegYch** [comment]
hm i'm having trouble with Stream tests on current 2.13 branch and on v2.13.0-RC1 tag

Stream methods like filter and collect fail there while they don't on a separate project using 2.13.0-RC1

can someone tell me what's the difference between https://github.com/OlegYch/sbt-zinc-559/tree/scala-11443 and https://github.com/OlegYch/scala/tree/scala-11443

**Comment by NthPortal** [comment]
@OlegYch I took a look and am just as mystified as you are

**Comment by OlegYch** [comment]
well good news is that this kind of ad-hoc tests work for LazyList with latest changes
no idea why Stream fails

**Comment by OlegYch** [comment]
does it fail for you @NthPortal ?

**Comment by NthPortal** [comment]
@OlegYch I only looked at the code; I did not run it. I am (un?)fortunately in the middle of two major life changes atm, so I don't have a ton of time right now. I'll see how soon I can take a look.

Honestly, `Stream` is in a sorry state right now. It never really got un-abstracted when `LazyList` split, so it is currently made up of an abstraction over only itself, which is quite messy.

**Comment by OlegYch** [comment]
it is quite easy to reproduce, just add `javaOptions in Test := Seq("-Xmx10M"),` in junit project and run
```
object StreamFilterTest extends App {
  val str = Stream.iterate(1)(_ + 1).filter(_ > 10000000).headOption
  println(str)
}
```
i'm guessing it's some kind of difference in scalac options used during publishing

**Comment by OlegYch** [comment]
i mean, it should behave the same using 2.13.0-RC1 tag and binary, right?

**Comment by SethTisue** [comment]
local builds aren't bootstrapped, published builds (including the builds published on https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/ for as-yet-unmerged PRs) are, that's a possible way for differences to creep in.

(sorry I don't have time today to take a closer look at whether that might be relevant here)

**Comment by smarter** [comment]
> published builds (including the builds published on https://scala-ci.typesafe.com/artifactory/scala-pr-validation-snapshots/ for as-yet-unmerged PRs)

That doesn't seem to be true based on what I've seen: https://github.com/scala/scala/pull/7980#issuecomment-483379251

**Comment by SethTisue** [comment]
@smarter open a scala-dev ticket and let's discuss?

**Comment by NthPortal** [comment]
unassigning myself for `Stream` (I'll re-assign if I eventually take a look at it)

**Comment by szeiger** [comment]
`Stream.filter` is trivial to fix. `Stream.collect` uses the same implementation as in 2.12, complete with all the comments explaining that it doesn't OOM, but it doesn't actually work. Neither in 2.12 nor in 2.13 is the head collected when it loops.
