### ISSUE TITLE
Invalid constant in default value when an object created before constant definition

### ISSUE THREAD

**Issue by alexnivanov** [scala/bug#11444]
Good day!

This piece of code illustrate the issue I found:

```
object SomeType {
  val BEFORE = SomeType()
  val DEFAULT_VALUE = 1
  val AFTER = SomeType()
}

case class SomeType(value: Int = SomeType.DEFAULT_VALUE)

object Runner {

  def main(args: Array[String]) {
    println(s"Object created before val initialization: ${SomeType.BEFORE}")
    println(s"Object created after val initialization: ${SomeType.AFTER}")
  }

}
```

produces output:

```
Object created before val initialization: SomeType(0)
Object created after val initialization: SomeType(1)
```

So, in declaration we have the same default value for both objects, but the actual result depends on declaration order!

Eventually, we get 0 when Int constant is not yet defined, but there are *no compilation warnings* whatsoever, so it can produce some confusing and hard to find issues in production :(

**Comment by SethTisue** [comment]
https://docs.scala-lang.org/tutorials/FAQ/initialization-order.html

(the doc page shouldn't be so specific about the problem being nulls; as you've observed, you get the default value for the type, for reference types that's `null`, for `Int` it's `0`)

**Comment by SethTisue** [comment]
ticket of record is #399

**Comment by alexnivanov** [comment]
@SethTisue thanks for the clarification, this is a really complex issue...
