### ISSUE TITLE
Stack, Queue, and ArrayDeque return an empty window when empty

### ISSUE THREAD

**Issue by Ichoran** [scala/bug#11440]
The standard behavior of `sliding` is to be under-full if the collection length is less than the window length but _not to return anything_ if the collection is empty.

The collections above return an empty collection instead.

```
Welcome to Scala 2.13.0-20190319-203750-5e547be (OpenJDK 64-Bit Server VM, Java 1.8.0_191).
Type in expressions for evaluation. Or try :help.

scala> Vector.empty[Int].sliding(1).size
res0: Int = 0

scala> collection.mutable.ArrayDeque.empty[Int].sliding(1).size
res1: Int = 1

scala> collection.mutable.Queue.empty[Int].sliding(1).size
res2: Int = 1

scala> collection.mutable.ArrayStack.empty[Int].sliding(1).size
                          ^
       warning: value ArrayStack in package mutable is deprecated (since 2.13.0): Use Stack instead of ArrayStack; it now uses an array-based implementation
res3: Int = 1

scala> collection.mutable.Stack.empty[Int].sliding(1).size
res4: Int = 1

scala> collection.mutable.Stack.empty[Int].sliding(1).foreach(println)
Stack()
```

**Comment by Ichoran** [comment]
Note the previous bug (and fix) at https://github.com/scala/bug/issues/11047

**Comment by gi114** [comment]
In Scala 2.12.1 there was no issue so we can see what has changed

**Comment by SethTisue** [comment]
can we have a volunteer to attempt a fix?

I've tentatively put it on the 2.13.1 milestone on the assumption that a fix wouldn't involve breaking bidcompat

**Comment by gi114** [comment]
Hi, 

I am looking at the sliding function for the first time and it is clear what it does, though i would like to clarify what happens in the case that the starting collection length > 0, like length = 3, and the window size parameter is > length, like 4. Would the return value always be the collection of size length = 3? so would it be unchanged as far as the window size is > length?

In case the initial collection is empty, applying any sliding window parameter (needs +ve) should result in an collection size = 0 and nothing printed. Is that correct? 

I would like to understand the details so I can give it a try!

Thanks for your help

**Comment by Ichoran** [comment]
Yes, your statements are all correct.

Note that there are other peculiar behaviors regarding moving by sliding more than one; they are as far as I know correct, so you should try to leave those intact.

For instance, this is weird but "correct" behavior:

```scala
scala> (1 to 8).sliding(5, 2).foreach(println)
Vector(1, 2, 3, 4, 5)
Vector(3, 4, 5, 6, 7)
Vector(5, 6, 7, 8)
```

(The principle is "stop once you have returned the last element", not "keep going until your start point runs off the end of the source collection" or "stop once the end of the window falls off the end of the source collection.)
