### ISSUE TITLE
Inconsistency in Scala's map for 0.0 and -0.0 as keys

### ISSUE THREAD

**Issue by Yotamho** [scala/bug#11447]
Even though `0.0D` and `-0.0D` has different `.hashCode()` return values, and are treated in Java as different values in a `HashMap`s, the following inconsistency occurs in Scala (2.12.8, JVM: 10.0.2):

    scala> Map(-0.0D->2, 0.0D->1)
    res0: scala.collection.immutable.Map[Double,Int] = Map(-0.0 -> 1)

**Comment by eed3si9n** [comment]
I am guessing that this is related to cooperative equality (https://contributors.scala-lang.org/t/can-we-get-rid-of-cooperative-equality/1131) and weak conformance.
See also https://github.com/scala/bug/issues/10773

**Comment by som-snytt** [comment]
My guess is
```
scala> val x = 0D
x: Double = 0.0

scala> val y = -0D
y: Double = -0.0

scala> x == y
res0: Boolean = true

scala> x.equals(y)
res1: Boolean = false

scala> runtime.BoxesRunTime.equals(x,y)
res2: Boolean = true
```
where the last test is trying to be too smart. The Javadoc for boxed `Double.equals` tweaks the zero case: "This definition allows hash tables to operate properly."

**Comment by Ichoran** [comment]
This isn't a bug.  Scala harmonizes hash code values for everything that is equal, including 0.  If your variant of zero happens to be -0.0, it prints out strange but everything works.

```
scala> Map(2.5 -> "two and a half", 3f -> "three")
res33: scala.collection.immutable.Map[AnyVal,String] = Map(2.5 -> two and a half, 3.0 -> three)

scala> res33(2.5)
res34: String = two and a half

scala> res33(3)
res35: String = three

scala> res33(2.5f)
res36: String = two and a half

scala> res33(3f)
res37: String = three
```

Note that the positive and negative zeros have a hash code of 0, just like `Int` zero:

```
scala> 0.##
res38: Int = 0

scala> 0.0.##
res39: Int = 0

scala> (-0.0).##
res40: Int = 0
```

**Comment by Ichoran** [comment]
Aside: use `.##` not `.hashCode` to get your hash codes to agree with `==` equality.
