### ISSUE TITLE
method resolution fails when overloaded method taking a parent type is overridden

### ISSUE THREAD

**Issue by shawjef3** [scala/bug#11456]
This fails for Scala 2.10, 2.11 and 2.12. I have not tried 2.13 or Dotty. To hit the bug, `Y` must extend `X`, `f(X)` must be overridden, but `f(Y)` must not be overridden. The override order bug carries to child types.

```scala
class X
class Y extends X

class Parent {
  def f(x: X): Unit = ???
  def f(x: Y): Unit = ???
}

class ChildOverridesX extends Parent {
  override def f(x: X): Unit = ???
}

class DoubleChildOverridesX extends ChildOverridesX

class ChildOverridesY extends Parent {
  override def f(x: Y): Unit = ???
}

class DoubleChildOverridesY extends ChildOverridesY

class ChildOverridesBoth extends Parent {
  override def f(x: X): Unit = ???
  override def f(x: Y): Unit = ???
}

class DoubleChildOverridesBoth extends ChildOverridesBoth

object Usage {
  val x: X = ???
  val y: Y = ???

  // compiles
  (null: Parent).f(x)
  // compiles
  (null: ChildOverridesX).f(x)
  // compiles
  (null: ChildOverridesY).f(x)
  // compiles
  (null: ChildOverridesBoth).f(x)
  // compiles
  (null: Parent).f(y)
  // does not compile
  (null: ChildOverridesX).f(y)
  // compiles
  (null: ChildOverridesY).f(y)
  // compiles
  (null: ChildOverridesBoth).f(y)

  // compiles
  (null: DoubleChildOverridesX).f(x)
  // compiles
  (null: DoubleChildOverridesY).f(x)
  // compiles
  (null: DoubleChildOverridesBoth).f(x)
  // does not compile
  (null: DoubleChildOverridesX).f(y)
  // compiles
  (null: DoubleChildOverridesY).f(y)
  // compiles
  (null: DoubleChildOverridesBoth).f(y)
}
```

**Comment by shawjef3** [comment]
I have commits to add this file to the test suite for 2.10.x through 2.13.x.

https://github.com/shawjef3/scala/commit/b42cf5f187558b4ed0214104784b2f73d21b18c0
https://github.com/shawjef3/scala/commit/e7c344fbec8fa961ef6628a850ef85184862cb4a
https://github.com/shawjef3/scala/commit/98c674432cb58386c2d3dc84e865a8b896c599d6
https://github.com/shawjef3/scala/commit/3d35daa775ee7d4bc7194fffc998d2111dfc8c26

**Comment by shawjef3** [comment]
@retronym the README suggests I ping you.

**Comment by shawjef3** [comment]
This thread describes how I ran into this and developed the above code. Originally I found this problem when calling Java methods. https://users.scala-lang.org/t/how-to-disambiguate-java-overloads-taking-long-and-object/4250

**Comment by diesalbla** [comment]
It also fails on the current head of the `2.13.x` branch. 
```Scala
// Exiting paste mode, now interpreting.
         (null: ChildOverridesX).f(y)
                                 ^
On line 43: error: ambiguous reference to overloaded definition,
       both method f in class ChildOverridesX of type (x: X)Unit
       and  method f in class Parent of type (x: Y)Unit
       match argument types (Y)
         (null: DoubleChildOverridesX).f(y)
                                       ^
On line 56: error: ambiguous reference to overloaded definition,
       both method f in class ChildOverridesX of type (x: X)Unit
       and  method f in class Parent of type (x: Y)Unit
       match argument types (Y)
```

**Comment by som-snytt** [comment]
This is as specified. Via gitter:

First of all, they say overloading is evil. To make it less evil, Scala says you can reason about an overloaded f without referring to the application itself, the use site. Given an overloaded f, it scores the two fs for which is "more specific." That means taking a more specific parameter, or being defined in a subclass. Usually, subclassing means imposing more specific constraints. If the two fs score the same, then you can't choose between them, so the overload is ambiguous.

There is a previous ticket about how java overloading differs from scala.

Therefore I'll close as a gesture of support for the team trying to resolve tickets for the next release.

Those who gave a thumbs-up should feel free to comment their dispute.

**Comment by shawjef3** [comment]
@som-snytt Can you link the previous ticket? I don't understand why overriding an overload should create an ambiguity where previously there was none. The types don't change.

**Comment by shawjef3** [comment]
Just to be clear, leaving this behavior as-is means that there is code someone can write in Java that they can't in Scala. Not just difficult, but actually impossible, because certain method calls are not possible.

**Comment by shawjef3** [comment]
I created a fix for this. https://github.com/shawjef3/scala/commit/06d828a111dc5e5506892cb02fc7d8454ebad52f

**Comment by som-snytt** [comment]
Changing the way overload resolution works is possible, but you'd want to start with a thread on the forum https://contributors.scala-lang.org/

"There are as many paths to overload resolution as there are Scala programmers. There are many algorithms for implicit resolution as there are genders of Scala programmers." -- old Scala saying.

**Comment by shawjef3** [comment]
You got it. https://contributors.scala-lang.org/t/proposal-make-overload-resolution-bind-more-closely-for-matching-types/2998

**Comment by shawjef3** [comment]
tarsa on the scala-lang forums gave me an easier solution. Keep this closed.
