### ISSUE TITLE
Create collection.SeqMap trait which immutable, mutable SeqMap extend

### ISSUE THREAD

**Issue by joshlemer** [scala/bug#11458]
Currently there are totally unrelated `mutable.SeqMap` and `immutable.SeqMap` traits, but there is no `collection.SeqMap` trait that these two both extend, they both just extend their respective `mutable.Map` and `immutable.Map`. This seems like it was probably an oversight, since every other analogous collection `Foo` that exists in mutable/immutable forms has a `collection.Foo` trait that it extends. The closest analogues would be `collection.SortedMap` (because it's beneath the main collection type (`Map`) but still not a concrete implementation). Or also `collection.LinearSeq` and `collection.IndexedSeq`. 

So far as I can tell, `collection.SeqMap` is the only one missing.

**Comment by Philippus** [comment]
@SethTisue @lrytz Should the milestone for this one be set to `2.13.0-RC1`?
