### ISSUE TITLE
BinaryTreeStepper misses a step

### ISSUE THREAD

**Issue by Ichoran** [scala/bug#11451]
Current behavior:

```scala
scala> collection.immutable.TreeSet.from(Array(-1, 48, 111, 115, 0, 116, 5399))
res0: scala.collection.immutable.TreeSet[Int] = TreeSet(-1, 0, 48, 111, 115, 116, 5399)

scala> val s = res0.stepper; while (s.hasStep) println(s.nextStep)
-1
48
111
115
116
5399
```

(Note the missing `0`!)

The culprit is in `BinaryTreeStepper.scala`: in the private `initialize` method the two lines

```scala
      val unrolled = unroll(root)
      myCurrent = if (unrolled eq root) detach(root) else unrolled
```

should be replaced with the single line

```scala
      myCurrent = detach(unroll(root))
```

I will do it myself but I'm out of time to submit a PR right now.  If nobody else gets to it by tomorrow, I'll do it.

**Comment by SethTisue** [comment]
tentatively marking as blocker and assigning @lrytz

**Comment by Ichoran** [comment]
Still didn't get to it.  Surely will over the weekend if nobody else gets it first.

**Comment by Ichoran** [comment]
Luckily someone else did first :)
