### ISSUE TITLE
problem with erased generics in Java and overriding

### ISSUE THREAD

**Issue by adriaanm** [scala/bug#11469]
looks like matching in refchecks is broken?

**Comment by SethTisue** [comment]
@adriaanm 2.13.1 milestone okay?

**Comment by retronym** [comment]
Not sure if related, but in https://github.com/scala/bug/issues/10418#issuecomment-336354579 I noted that the way we unify `Object` and `Any` in `matchesType` when a Java defined method is involved is too shallow and doesn't deal with class type parameters.

**Comment by SethTisue** [comment]
example workaround: https://github.com/scalacommunitybuild/jackson-module-scala/commit/b23140ec2b990ee8dead7c77f8c49e5b49998e49  fyi @pjfanning

**Comment by lrytz** [comment]
same / similar / related (?) issue:

```
$> cat Test.java
import java.util.Optional;

public class Test {
  public abstract static class A<T> {
    public void m(Optional<? extends T> a) { }
  }
  public abstract static class B extends A<Object> {
    @Override
    public void m(Optional<?> a) { }
  }
}
$> javac Test.java
$> cat A.scala
class A {
  new Test.B() { }
}
$> qsc A.scala
A.scala:2: error: name clash between inherited members:
def m(x$1: java.util.Optional[_ <: Object]): Unit in class A and
def m(x$1: java.util.Optional[_]): Unit in class B
have same type after erasure: (x$1: java.util.Optional)Unit
  new Test.B() { }
      ^
one error found
```

**Comment by adriaanm** [comment]
We can probably make refchecks a bit smarter/more forgiving in 2.13.x.

**Comment by lrytz** [comment]
some classes cannot be subclassed in scala then..

**Comment by adriaanm** [comment]
So far we've found workarounds, right? We should fix this in 2.13.x, but until then I think it's important we book the progress we've made with refchecks. We could exclude java pairs until we have a better fix, but that seems sketchy.

Here's the same thing in code, but I'm reluctant to even submit the PR for that https://github.com/adriaanm/scala/tree/t11469

**Comment by adriaanm** [comment]
To be clear, this stuff compiled before because we didn't check those pairs at all.

**Comment by lrytz** [comment]
It can be quite annoying I'd say, as there are Java classes that just cannot be extended anymore in Scala. Also adding another Java class in between (`C extends B` in the example https://github.com/scala/bug/issues/11469#issuecomment-488662447) doesn't help, `C` cannot be subclassed in Scala either. Let's say you need to subclass `B` and also mix in some Scala trait, it can get quite complicated to do it in Java :) An example is the abstract class `java.security.Provider`, it doesn't seem overly exotic wanting to create a subclass of that in Scala.

**Comment by adriaanm** [comment]
I can't think of a better way to fix this than https://github.com/scala/scala/pull/7966. It looks like a good & feasible fix, but it's going to take some time to get that production ready...

**Comment by adriaanm** [comment]
I've been playing around with hackier solutions, but the only thing that comes to mind is to exclude pairs that involve a java type. It's kind of stunning that we (apparently) never looked at those before, because otherwise we would have seen these bugs sooner.

**Comment by adriaanm** [comment]
Since there's no easy workaround, and we'd rather fix this in an RC than in a minor release (where we don't do RC cycles because we shouldn't do risky things anymore), we're going to block RC2 on a (proper) fix for this.

**Comment by pjfanning** [comment]
@adriaanm @SethTisue I tried out this change with jackson-module-scala but a large number of tests are failing - tests that check JSON serialisation support for types like Option[Long]

jackson-module-scala works with scala 2.13.0-RC1 after using the compilation workaround (https://github.com/scalacommunitybuild/jackson-module-scala/commit/b23140ec2b990ee8dead7c77f8c49e5b49998e49)

Would either of you have any ideas what's up?

https://travis-ci.org/FasterXML/jackson-module-scala/jobs/535323388
https://github.com/FasterXML/jackson-module-scala/pull/413

**Comment by adriaanm** [comment]
Yes, that's fixed by the last commit of https://github.com/scalacommunitybuild/jackson-module-scala/tree/community-build-2.13 (https://github.com/scalacommunitybuild/jackson-module-scala/commit/ffcdaa102a6226f8828d6bad249dcd40d2c5bc28)
