### ISSUE TITLE
rounding Issue

### ISSUE THREAD

**Issue by desbond** [scala/bug#11463]
def convertMoney(amount: Double): String = {
    (math floor amount * 100).toInt.toString()
  }

println(convertMoney(36.91))  gives 3690
println(convertMoney(36.92)) gives 3692
println(convertMoney(36.81))  gives 3681
Scala v 2.12.8

**Comment by plokhotnyuk** [comment]
It looks more like Java issue:
```
scala> java.lang.Math.floor(36.91 * 100)
res0: Double = 3690.0
```

**Comment by desbond** [comment]
def convertMoney(amount: Double): String = {
    (scala.math floor amount * 100).toInt.toString()
  }
println(convertMoney(36.91))

This gives the same result

**Comment by plokhotnyuk** [comment]
It even more like IEEE-754 issue:
```
scala> java.lang.Double.doubleToRawLongBits(3691.0).toBinaryString
res0: String = 100000010101100110101100000000000000000000000000000000000000000

scala> java.lang.Double.doubleToRawLongBits(36.91 * 100).toBinaryString
res1: String = 100000010101100110101011111111111111111111111111111111111111111
```

**Comment by SethTisue** [comment]
as @plokhotnyuk indicates, this is already working exactly as it should

**Comment by plokhotnyuk** [comment]
@desbond have you tried to use string formatting instead? does it work for you?
```
scala> "%.0f".format(36.91 * 100)
res0: String = 3691

scala> "%.0f".format(36.92 * 100)
res1: String = 3692

scala> "%.0f".format(36.81 * 100)
res2: String = 3681
```

**Comment by desbond** [comment]
@plokhotnyuk Yes I have worked around the problem. I just thought it was strange behaviour and was worth reporting.

Thanks for your quick responses

Des

**Comment by eed3si9n** [comment]
If you don't want to lose pennies during business transactions, consider https://www.scala-lang.org/api/2.12.8/scala/math/BigDecimal.html
