### ISSUE TITLE
Curried functions not working in repl

### ISSUE THREAD

**Issue by ashwinbhaskar** [scala/bug#11472]
This does not compile in repl

```
def func(x: Int)(y :Int)(z : Int) : Int = x + y + z

  val a = func(1)
```

It gives the error
```
error: missing argument list for method func
       Unapplied methods are only converted to functions when a function type is expected.
       You can make this conversion explicit by writing `func _` or `func(_)(_)(_)` instead of `func`.
```

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org for questions

**Comment by ashwinbhaskar** [comment]
@SethTisue I created  this as an issue. Isn't it a valid bug? I posted it on users.scala-lang after you told. And it seems like it works in dotty repl but not in 2.13.

**Comment by SethTisue** [comment]
the language is working as designed, there is no bug. the Dotty change is a design change, not a bug fix.

as https://github.com/scala/bug/blob/master/README.md says,

> To keep this tracker focused, we ask that feature requests and discussion of potential language changes take place in the language design category on our contributors forum.

**Comment by ashwinbhaskar** [comment]
@SethTisue Okay. Got it.
