### ISSUE TITLE
ClassCastException (ArraySeq) when pattern-matching on varargs case class

### ISSUE THREAD

**Issue by cheeseng** [scala/bug#11476]
We encounter a weird ClassCastException when running our tests in ScalaTest for org.scalactic.Every, that looks like this: 

```
[error] (run-main-0) java.lang.ClassCastException: scala.collection.immutable.ArraySeq$ofInt cannot be cast to com.test.Every
[error] java.lang.ClassCastException: scala.collection.immutable.ArraySeq$ofInt cannot be cast to com.test.Every
[error] 	at com.test.TestMain$.main(TestMain.scala:7)
[error] 	at com.test.TestMain.main(TestMain.scala)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] 	at java.lang.reflect.Method.invoke(Method.java:498)
[error] Nonzero exit code: 1
[error] (Compile / run) Nonzero exit code: 1
```

I tried to minimize the problem but not quite successful, the best I can do is to include the source of Every as com.test.Every, in the attached zip (a sbt project), you can reproduce the problem by running: 

```
> sbt run
```

If you change the scala version to 2.12.8, it works without problem.

[test-bug.zip](https://github.com/scala/bug/files/3054790/test-bug.zip)

**Comment by Jasper-M** [comment]
This is ... interesting.

```
scala> case class Foo(a: Int*) { def lengthCompare(i: Int) = 1 }
defined class Foo

scala> Foo(1) match { case Foo(a) => a }
java.lang.ClassCastException: scala.collection.immutable.ArraySeq$ofInt cannot be cast to Foo
  ... 36 elided
```

**Comment by eed3si9n** [comment]
@Jasper-M Nice minimization.

**Comment by SethTisue** [comment]
culprit guess, is it https://github.com/scala/scala/pull/7068?

**Comment by SethTisue** [comment]
culprit guess, is it https://github.com/scala/scala/pull/7068?

note that this isn't an RC1 regression; it was broken in M5 too

**Comment by SethTisue** [comment]
@adriaanm suspects https://github.com/scala/scala/pull/7068/files#diff-352de7f9c77a7e21df6940d6a1bcdc7eR574

**Comment by SethTisue** [comment]
@cheeseng is this hard to work around in your codebase? wondering how much of a 2.13 blocker it is

**Comment by adriaanm** [comment]
Well,  “suspect” is too strong right now. Maybe the PR was just in the
wrong place at the wrong time :-)

**Comment by cheeseng** [comment]
@SethTisue Not really a blocker, we just want to understand the reason behind tests failing under 2.13, and this is one of them.
