### ISSUE TITLE
Empty Vararg Yield ArraySeq(()) in 2.13.0-RC1

### ISSUE THREAD

**Issue by cheeseng** [scala/bug#11475]
For the following code: 

```
class MyList {
  def containsOnly(elements: Any*): Unit = {
    println("elements: " + elements)
  }
}
val a = new MyList
a containsOnly ()
```

In 2.12.8, it prints: 

```
elements: List()
```

an empty, however, in 2.13.0-RC1, it prints: 

```
elements: ArraySeq(())
```

which is an ArraySeq that contains a single element ().  Is this expected in 2.13?

Thanks.

**Comment by SethTisue** [comment]
`a containsOnly ()` means `a.containsOnly(())` now, see https://github.com/scala/scala/pull/7684

**Comment by cheeseng** [comment]
@SethTisue I see, thanks for your explanation and link, and sorry for the noise made.

**Comment by SethTisue** [comment]
@cheeseng no worries! you will be far from the only person puzzled and surprised by this

**Comment by som-snytt** [comment]
If there were `-Yunit-value-discard` to adapt `x f ()` to zero-arg `x.f()`, the varargs case would still be problematic for generic (or `Any`) parameters, in that the expression is not an error.
