### ISSUE TITLE
Implementation and spec about Null's supertypes are out of sync

### ISSUE THREAD

**Issue by Jasper-M** [scala/bug#11479]
The only thing the spec has to say about `Null`, in paragraph `3.5.2 Conformance`, is:

> For every class type `T` such that `T <: scala.AnyRef` one has `scala.Null <: T`.

But the implementation says:

```
scala> trait Foo extends Any
defined trait Foo

scala> val foo: Foo = null
foo: Foo = null

scala> implicitly[Null <:< Foo]
res4: Null <:< Foo = generalized constraint
```

**Comment by sjrd** [comment]
The spec is wrong and the implementation is correct.

There is no choice, because if you declare a `class Bar extends AnyRef with Foo`, then you can construct a transitive chain of conformance from `Null` up to `Foo`:
```scala
$ scala
Welcome to Scala 2.12.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_191).
Type in expressions for evaluation. Or try :help.

scala> trait Foo extends Any
defined trait Foo

scala> class Bar extends AnyRef with Foo
defined class Bar

scala> implicitly[Null <:< Bar]
res0: Null <:< Bar = <function1>

scala> implicitly[Bar <:< Foo]
res1: Bar <:< Foo = <function1>

scala> implicitly[Null <:< Foo]
res2: Null <:< Foo = <function1>
```
The only correct answer is Yes, `Null <: Foo`, because we have `Null <: Bar` and `Bar <: Foo`.

**Comment by SethTisue** [comment]
"The change is reflected in my local copy of the spec" — https://github.com/scala/scala/commit/01494243503b1597f0d5597c6c4414a42473c064

looks like the change never made it to the repo

**Comment by Jasper-M** [comment]
Also might be worth updating the `Null` scaladoc:

>Null is - together with scala.Nothing - at the bottom of the Scala type hierarchy.
>
>Null is a subtype of all reference types; its only instance is the null reference. Since Null is not a subtype of value types, null is not a member of any such type. For instance, it is not possible to assign null to a variable of type scala.Int. 

It's not strictly incorrect, but it gives the impression that _only_ reference types are supertypes of `Null`.
