### ISSUE TITLE
Override `stepper` in more collection types

### ISSUE THREAD

**Issue by lrytz** [scala/bug#11483]
(source: https://github.com/scala/scala-java8-compat/issues/113)

Check if there are more collections that would from a `stepper` override (with an existing or new stepper implementation). From the top of my head:
  - mutable/immutable ArraySeq, ArrayBuffer
  - mutable LinkedHashMap/LinkedHashSet (cannot use XTableStepper because that doesn't yield the elements in insertion order)
  - ArrayDeque
  - VectorMap

**Comment by lrytz** [comment]
To allow doing that in a minor release, it might make sense to add some overrides of `stepper` in 2.13.0 without actually providing a more efficient Stepper (yet). @Ichoran, what do you think?

**Comment by Ichoran** [comment]
@lrytz - `LinkedHashX` are linked lists when following insertion order.  There's no point overriding them.

`VectorMap` can be overridden.  The existing Vector stepper should work fine mapped, but we don't have a mapped stepper any longer.

`ArraySeq` and `ArrayBuffer` can just use the stepper for arrays.

`ArrayDeque` has a (slightly) more complicated indexing scheme and will need a new (slightly modified) stepper.

So I'm not sure the overrides are enough given that we need new stepper classes also.  I guess we could use anonymous subclasses whose type isn't observable.

**Comment by lrytz** [comment]
We can declare new steppers `private[collection]`, as the types don't leak out to the `stepper` signature.
