### ISSUE TITLE
Scala 2.13.0-RC1 - method without `override` modifier rejected when overridden both earlier and later in trait linearisation

### ISSUE THREAD

**Issue by Sciss** [scala/bug#11495]
I think this is a bug:

```scala
trait Basic {
  def numFrames: Long
}

trait Readable extends Basic {
  def numFrames: Long = ??? // doesn't matter for bug report
}
    
trait Writable extends Basic {
  override final def numFrames: Long = ??? // doesn't matter for bug report
}

trait Bidi extends Readable with Writable  // writable beats readable
  
trait WritableFileLike extends Writable

trait BidiFileLike extends WritableFileLike with Bidi // compiles up to 2.13.0-M5, not RC1
```

Note that in the linearisation order, `Writable` is last and thus should "eliminate" its first occurrence in `WritableFileLike`, which I guess triggers the error in 2.13.0-RC1:

```
[error] final override def numFrames: Long (defined in trait Writable)
[error]   with def numFrames: Long (defined in trait Readable)
[error] trait BidiFileLike extends WritableFileLike with Bidi
[error]       ^
```

**Comment by smarter** [comment]
> Note that in the linearisation order, Writable is last and thus should "eliminate" its first occurrence in WritableFileLike

No, for linearization order the first occurence is the important one, see https://www.scala-lang.org/files/archive/spec/2.12/05-classes-and-objects.html#class-linearization. I think 2.13.0-RC1 is doing the right thing.

**Comment by Sciss** [comment]
I can actually remove the `final` qualifier, the problem stays.

**Comment by hrhino** [comment]
Isn't this the opposite of #11136? (Not that I'm biased...)

**Comment by som-snytt** [comment]
[The PR](https://github.com/scala/scala/pull/7439) to the earlier ticket is explanatory (though it also has a long tail of follow-up).

What do you call a duplicate ticket that is the opposite? A mirror ticket?

I'm not sure which ticket I admire more for their creative variants of `IO`-related trait names.

**Comment by Sciss** [comment]
I don't understand - is this resolved?

**Comment by som-snytt** [comment]
@Sciss See smarter's comment -- the current behavior is correct, the old behavior was wrong, and was always wrong. Now I have to check my "stackable traits" answer on stackoverflow from 2012.
