### ISSUE TITLE
Remove insta-deprecated scala.jdk.CollectionConverters.Ops

### ISSUE THREAD

**Issue by dwijnand** [scala/bug#11500]
Backstory: https://github.com/scala/scala/pull/7987#pullrequestreview-230151899

**Comment by SethTisue** [comment]
@dwijnand (should be RC3?)

**Comment by lrytz** [comment]
ah yes!

**Comment by dwijnand** [comment]
Fixed in https://github.com/scala/scala/pull/8107.
