### ISSUE TITLE
Steam empty/head check consumes from stream

### ISSUE THREAD

**Issue by withinboredom** [scala/bug#11508]
So, this may or may not be a bug. However, there's some inconsistent behavior that may be worth reporting.

The following snippet of code demonstrates the issue:

```scala
case class Source(max: Int) {
  var number: Int = 0

  def stream: Stream[Int] = {
    number += 1
    if (number <= max)
      Stream.cons(number, stream)
    else
      Stream.empty
  }

  def process(st: => Stream[Int]) = {
    if (st.nonEmpty) {
      val (some, tail) = st.span(_ < max / 2)

      if (some.nonEmpty) {
        some.foreach(i => println(s"some: $i"))
      }

      tail.foreach(i => println(s"tail: $i"))
    }
  }
}

def st = 1 #:: 2 #:: 3 #:: Stream.empty

val x = Source(10)
x.process(x.stream)
x.process(st)
```

It gives the following output:

```
$ scala test.scala
some: 2 # skipped 1
some: 3
some: 4
tail: 5
tail: 6
tail: 7
tail: 8
tail: 9
tail: 10
some: 1 # Did not skip 1
some: 2
some: 3
```

If you run it, you may notice that `process` takes an anonymous function `=> Stream[Int]` which seems to be the culprit causing `nonEmpty` and other head checks to consume from the stream, if and only if it's a dynamic stream. ie, one that isn't hard coded. Discovering this was fun because integration tests were failing but unit tests were passing in our project.

This is present in 2.11.12 and 2.12.8.

**Comment by SethTisue** [comment]
`process` as written is just incorrect code. it seems to be written under the assumption that `=>` has `lazy val` semantics (evaluated at most once), but that isn't how by-name parameters work, the parameter is freshly evaluated every time it is referenced

we ask that you use https://users.scala-lang.org for questions, and only come here to the bug tracker once you've confirmed that there is actually a new, previously unreported bug in Scala

**Comment by withinboredom** [comment]
> is just incorrect code

Yes this is a contrived example.

> to be written under the assumption that => has lazy val semantics

or when you don't want to hold a reference to the the stream head when processing infinitely. ;)

> the parameter is freshly evaluated every time it is referenced.

That's what I figured, it was worth reporting the inconsistency so that others may come across it instead of digging through hundreds of lines of code trying to find missing values that only appear in prod-like environments.
