### ISSUE TITLE
mutable.MultiMap cannot be used as documented without warnings

### ISSUE THREAD

**Issue by raboof** [scala/bug#11504]
The [mutable.MultiMap docs](https://www.scala-lang.org/api/2.13.0-RC1/scala/collection/mutable/MultiMap.html) suggest `val mm = new HashMap[Int, Set[String]] with MultiMap[Int, String]`, but `HashMap` is marked `@deprecatedInheritance("HashMap wil be made final; use .withDefault for the common use case of computing a default value", "2.13.0")`.

**Comment by lrytz** [comment]
Should `MultiMap` be deprecated? @szeiger / @julienrf

**Comment by julienrf** [comment]
Probably, but we should provide a proper replacement.

**Comment by lrytz** [comment]
Would it be enought to point people to scala-collection-contrib? Is it planned to release that module?

**Comment by julienrf** [comment]
We need to make this repository “releasable”, and then to find someone who wants to take the responsibility of pushing git tags to cut releases.

**Comment by szeiger** [comment]
We could provide a factory method that gives you a `MultiMap` for a `HashMap` typed as `Map with MultiMap`. It could still be implemented as a wrapper (similar to `MultiDict`) when HashMap is made final.

But I would prefer to deprecate `MultiMap` instead. I'm not sure we should point to `MultiDict` as a recommended replacement at this point. After all, if we were sufficiently confident that the API is good and can be kept stable we should have added it to the standard library. We could recommend a simple `Map` as a replacement (and point to `MultiDict` as another option). After all, `MultiMap` does not add much functionality on top of `Map`.

**Comment by szeiger** [comment]
The PR targets 2.13.1. Since deprecation is the most likely solution (and the current implementation works fine, albeit with a deprecation warning) I'm rescheduling this to 2.13.1.
