### ISSUE TITLE
can‘t compile project

### ISSUE THREAD

**Issue by cjdxhjj** [scala/bug#11501]
my project have some module,some module write by java to share with others.for example domain layer, client layer,other module write by scala,for example dao,bussiness,web layer,bussiness layer dependines on dao,web layer dependines on core,i use gradle and idea,my dao can build success,but bussiness layer compile error with the following message
nx-search\search-web\src\main\scala\com\nxin\search\server\conf\AppConf.scala:9: object conjuction is not a member of package com.nxin.search
the line is import com.nxin.search.conjuction.PigEarQueryHandler, this class write by scala. in lower layer.because can't import namespace, so it cause many more not found: type error,i search google for a long time,find only one method.
sourceSets.main.scala.srcDir "src/main/java"
sourceSets.main.java.srcDirs = []
sourceSets.test.scala.srcDir "src/test/java"
sourceSets.test.java.srcDirs = []

or sourceSets {
    main {
        scala {
            srcDirs = ['src/main/java', 'src/main/scala']
        }
        java {
            srcDirs = []
        }
    }
    test {
        scala {
            srcDirs = ['src/test/java', 'src/test/scala']
        }
        java {
            srcDirs = []
        }
    }
}

but it not work any all.
my jdk is jdk 11.3,scala is 2.12.8, gradle version is 5.4,what can i do it? i also try to reinstall the ide   
scala plugin, it also not work,i tried compile using cmd,it also failed.

**Comment by lrytz** [comment]
Please only report bugs here. https://docs.scala-lang.org/getting-started.html, for questions https://users.scala-lang.org/
