### ISSUE TITLE
Weird? inferred result type in repl

### ISSUE THREAD

**Issue by xavierguihot** [scala/bug#11506]
While playing with a custom flatten function on the repl:

```scala
def flatten[T](list: List[Any]): List[T] =
  list.flatMap {
    case x: T => List(x)
    case sub: List[Any] => flatten[T](sub)
  }
```

I'm seeing this (note the result type):

```scala
scala > val a = flatten[String](List(List(1), List(List(2), 3), 4))
a: List[String] = List(List(1), List(List(2), 3), 4)
```

Even if I specify this type (`String` or whatever else), I wouldn't expect to see the type of `a` as `List[String]` which is clearly in conflict with the actual value of `a`.

I'm noticing the same display on 2.12 and the latest nightly 2.13.

PS: This is not about writing the function, but about the way the result is displayed in the repl.

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org for questions

**Comment by xavierguihot** [comment]
Feels like an issue though
