### ISSUE TITLE
Unit.box and Unit.unbox can no longer be called without a warning

### ISSUE THREAD

**Issue by raboof** [scala/bug#11503]
Because the `Unit` object now has a ``@scala.annotation.compileTimeOnly("`Unit` companion object is not allowed in source; instead, use `()` for the unit value")``

Should box/unbox utilities be moved somewhere else?

**Comment by sjrd** [comment]
There is no need to call those methods, ever. You can always replace `Unit.box(x)` by `x: Any` and `Unit.unbox(x)` by `{ x ; () }`.

**Comment by Jasper-M** [comment]
> There is no need to call those methods, ever.

If that is the case, wouldn't those methods be better off in `scala.runtime`? [insert Captain Hindsight meme]

**Comment by sjrd** [comment]
Yes, they probably should have been there all along.

**Comment by raboof** [comment]
> There is no need to call those methods, ever. You can always replace Unit.box(x) by x: Any and Unit.unbox(x) by { x ; () }.

Perhaps deprecate them with that recommendation?

**Comment by som-snytt** [comment]
Either you're invoking the methods reflectively on an `AnyValCompanion`, or you know statically to use `runtime.BoxedUnit`. I guess the cast on unboxing can fail, so it's more verbose now; value discard is not equivalent. If the purpose of the boxing methods is Java interop, then it makes sense that `Unit.box` is not (easily) available, though you can always `runtime.BoxedUnit.UNIT`.

I think they would need a use case to support "manual unit boxing support."

**Comment by som-snytt** [comment]
A deprecation is probably trumped by the error. There's another issue to say please show me warnings under `-Xfatal-warnings` aka `-Werror` even when erroring. But at least the scaladoc would help.

**Comment by Jasper-M** [comment]
The signature of `box` from Java's point of view is `public scala.runtime.BoxedUnit box(scala.runtime.BoxedUnit)` so I don't think it's gonna do much for interop.
