### ISSUE TITLE
MapView has silly `toString`

### ISSUE THREAD

**Issue by joshlemer** [scala/bug#11515]
```scala
scala> Seq(1).view
res0: scala.collection.SeqView[Int] = View(?)

scala> Array(1).view
res3: scala.collection.IndexedSeqView[Int] = View(?)

scala> Set(1).view
res1: scala.collection.View[Int] = View(?)

scala> Map(1 -> 1).view
res2: scala.collection.MapView[Int,Int] = <function1>


```

**Comment by joshlemer** [comment]
Arguably, `SeqView` should also toString as `SeqView(?)`

**Comment by SethTisue** [comment]
for backwards compatibility, let's preserve the old behavior under `.toSillyString`

**Comment by joshlemer** [comment]
![](https://i.imgflip.com/300hwm.jpg)

**Comment by eed3si9n** [comment]
I don't know if we should keep the `?` thing. Scala 2.12.x says `...`, and that seems fine to me.

```scala
Welcome to Scala 2.12.8 (OpenJDK 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> Seq(1).view
res0: scala.collection.SeqView[Int,Seq[Int]] = SeqView(...)

scala> Array(1).view
res1: scala.collection.mutable.IndexedSeqView[Int,Array[Int]] = SeqView(...)

scala> Seq(1).view
res2: scala.collection.SeqView[Int,Seq[Int]] = SeqView(...)

scala> Map(1 -> 1).view
res3: scala.collection.IterableView[(Int, Int),scala.collection.immutable.Map[Int,Int]] = IterableView(...)
```

**Comment by NthPortal** [comment]
`?` is at least consistent with `LazyList` though

**Comment by som-snytt** [comment]
I would have expected `???`.

**Comment by eed3si9n** [comment]
With [Kind Projector](https://github.com/typelevel/kind-projector), `?` means something as part of a type, so unless there's a strong reason to do so I think we should avoid it appearing as a term.

**Comment by som-snytt** [comment]
Apologies, my joke was that `...` with three dots should be three `?`. Sorry to be lame. It's an occupational hazard. In my defen[sc]e, there was that Daniel Spiewakism today https://gitter.im/scala/scala?at=5ccb36d14b4cb471d9974a5d where types vs terms is shot to pieces via java interop.

**Comment by eed3si9n** [comment]
Also recently someone told me that `?` also means WildcardType. https://github.com/scala/scala/blob/v2.13.0-RC1/src/reflect/scala/reflect/internal/Types.scala#L1132-L1138

**Comment by julienrf** [comment]
`...` is currently used by `LazyList` to model cyclic lists. If we replace `?` with `...` here, we should apply the same change in `LazyList` and find a replacement for `...`.

**Comment by NthPortal** [comment]
to me, `?` indicates an unknown - we don't know the contents of the view (or `LazyList`); `...` does not give that same indication to me, and even slightly indicates that there are some non-zero number of elements (which is not necessarily the case).

**Comment by eed3si9n** [comment]
The plot thickens :)

### Scala 2.12.8

```scala
scala> Stream(1)
res0: scala.collection.immutable.Stream[Int] = Stream(1, ?)

scala> import scala.concurrent.ExecutionContext.Implicits._
import scala.concurrent.ExecutionContext.Implicits._

scala> scala.concurrent.Future { 1 }
res1: scala.concurrent.Future[Int] = Future(<not completed>)
```

### Scala 2.13.x branch

```scala
scala> LazyList(1)
res0: scala.collection.immutable.LazyList[Int] = LazyList(?)

scala> import scala.concurrent.ExecutionContext.Implicits._
import scala.concurrent.ExecutionContext.Implicits._

scala> scala.concurrent.Future { 1 }
res1: scala.concurrent.Future[Int] = Future(<not completed>)
```

Whatever the REPL prints, I think it should be clear to relatively new learners to what it means, and whether it can be used by re-pasting the expression back into the REPL. From that perspective maybe `?` and `...` are equally cryptic, and something like `Future(<not completed>)`, similar to `<function1>` would be better?

**Comment by julienrf** [comment]
Do you mean `View(<not computed>)` and `LazyList(<not computed>)`?

**Comment by eed3si9n** [comment]
Yes. `<some description>` is both clear in terms of what it means, and doesn't look like a Scala symbol someone needs to look up.

**Comment by NthPortal** [comment]
should certain very particular views (e.g. `StringView`) print their contents instead of `<not computed>`?

**Comment by eed3si9n** [comment]
@NthPortal 

> should certain very particular views (e.g. `StringView`) print their contents instead of `<not computed>`?

If you can copy-paste it back and it works, I think it's fine to print the contents.

**Comment by NthPortal** [comment]
should we also change `toString` for cyclic `LazyList`s and `Stream`s? perhaps `<cycle>` or `<cyclic>`?

**Comment by joshlemer** [comment]
Still a little bit silly
```scala
scala> MapView(1 -> 2)
res0: scala.collection.MapView[Int,Int] = View(<not computed>)

```

**Comment by som-snytt** [comment]
Frost has `Road(<not taken>)`. It turns out that the Monty Python meme gets better with age.

**Comment by NthPortal** [comment]
I thought I fixed it!

**Comment by NthPortal** [comment]
how important is this to get into 2.13.0?

**Comment by dwijnand** [comment]
Not enough to trigger an RC3, IMO.

**Comment by dwijnand** [comment]
... but I'll add it so it can part of RC3 if RC3 is released.
