### ISSUE TITLE
Value class falls back to allocation

### ISSUE THREAD

**Issue by unoexperto** [scala/bug#11526]
Guys, could you please share your thoughts on why compiler produces code that allocates instances of `SomeTraitLocalString` if I remove line with `override` ? Is there way to fix it ?

Tested with Scala 2.12.8 and 2.13-RC1 (following conversation at [gitter](https://gitter.im/scala/scala?at=5cd842a9f52a2375161d71b0))

```
trait OptionExtensionTrait[L, R] extends Any {

  protected def value: Option[R]

  def newFunction: Either[Option[L], R] = ???
}

object main {
  implicit class SomeTraitLocalString[R](protected val value: Option[R]) extends AnyVal with OptionExtensionTrait[String, R] {
    override def newFunction = super.newFunction
  }

  def main(args: Array[String]): Unit = {

    Some(1).newFunction
    Some(2).newFunction
  }
}
```

Decompiled code

```
main.SomeTraitLocalString$.MODULE$.newFunction$extension(this.SomeTraitLocalString((Option<R>)new Some((Object)BoxesRunTime.boxToInteger((int)1))));
```

vs. 

```
new main.SomeTraitLocalString<R>(this.SomeTraitLocalString((Option<R>)new Some((Object)BoxesRunTime.boxToInteger((int)1)))).newFunction();
```

**Comment by NthPortal** [comment]
If a value class extends a trait, it must allocate an instance in order to invoke a method on the trait, which is what happens when you don't have the override. However, adding the override generates a static extension method which gets invoked instead - not because its an override, but because it's a method in a value class. If you upcast to `OptionExtensionTrait` and call the method (i.e. `(Some(1): OptionExtensionTrait[String, Int]).newFunction`) it will also allocate an instance, because you're invoking a method on a trait.

**Comment by unoexperto** [comment]
@NthPortal Thank you for the explanation. It makes sense now. Could you suggest how I can overcome this? Perhaps I can automagically generate `SomeTraitLocalString` with macros of something like that ?

**Comment by NthPortal** [comment]
don't worry though - it's not actually inconsistent. it allocates even with the static invocation ;)

```scala
public final <R> scala.util.Either<scala.Option<java.lang.String>, R> newFunction$extension(scala.Option<R>);
    Code:
       0: new           #14                 // class $line4/$read$$iw$$iw$SomeTraitLocalString
       3: dup
       4: aload_1
       5: invokespecial #30                 // Method $line4/$read$$iw$$iw$SomeTraitLocalString."<init>":(Lscala/Option;)V
       8: invokevirtual #34                 // Method $line4/$read$$iw$$iw$SomeTraitLocalString.$line4$$read$$iw$$iw$SomeTraitLocalString$$super$newFunction:()Lscala/util/Either;
      11: areturn
```

**Comment by unoexperto** [comment]
@NthPortal Touche! :)
