### ISSUE TITLE
"ClassBType.info not yet assigned" error with Scala 2.13.0-RC1 

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#11524]
- https://travis-ci.org/xuwei-k/scalaz/jobs/530543436#L4947
- https://github.com/xuwei-k/scalaz/commit/2201a647b81100df72ff74ab1d150e005339adf6

```
[error] Error while emitting CofreeTest.scala
[error] <error> (of class scala.reflect.internal.Types$ErrorType$)
[error] Error while emitting CofreeTest.scala
[error] assertion failed: ClassBType.info not yet assigned: Lscalaz/CofreeTest$LazyDefns$1$1;
[warn] 402 warnings found
[error] two errors found
[error] (testsJVM / Test / compileIncremental) Compilation failed
```

**Comment by lrytz** [comment]
Can reproduce locally

**Comment by lrytz** [comment]
This seems to be an interaction with https://github.com/scala/scala/pull/6050.

I just attached the debugger to the 2.13.0-RC1 compiler when running. Here's the tree that reaches the backend. Note the `error` type, which is causing the warning https://github.com/scala/scala/blob/v2.13.0-RC1/src/compiler/scala/tools/nsc/backend/jvm/BTypesFromSymbols.scala#L185.

```
object CofreeTest extends Object {
  final <static> <artifact> def $anonfun$new$1(lazyDefns$1$1: scalaz.CofreeTest$LazyDefns$1$1): scalaz.Order = lazyDefns$1$1.<rec$1: error>();
  def <init>(): scalaz.CofreeTest.type = {
    CofreeTest.super.<init>();
    scala.Predef.implicitly({
      final <synthetic> val lazyDefns$1: scalaz.CofreeTest$LazyDefns$1$1 = new scalaz.CofreeTest$LazyDefns$1$1();
      scalaz.this.Cofree.cofreeOrder(scalaz.std.anyVal.intInstance().$asInstanceOf[scalaz.Order](), {
        $anonfun(lazyDefns$1)
      })
    });
    ()
  }
}
```

The by-name implicit is https://github.com/xuwei-k/scalaz/blob/2201a647b81100df72ff74ab1d150e005339adf6/core/src/main/scala-2.13+/scalaz/CofreeInstancesVersionSpecific.scala#L14

To reproduce
  - check out https://github.com/xuwei-k/scalaz/tree/2201a647b81100df72ff74ab1d150e005339adf6 (at this revision)
  - run `sbt`, then `++2.13.0-RC1`, then `rootJVM/test:compile`

A minimization would be helpful.. But @milessabin maybe you can take a look anyway?

**Comment by milessabin** [comment]
I'll try and find time in the next day or two. @xuwei-k a minimization would be _really_ helpful.

**Comment by joroKr21** [comment]
Another instance in kittens: #11591

**Comment by milessabin** [comment]
Continuing this on #11591.

**Comment by milessabin** [comment]
#11591 fixed in https://github.com/scala/scala/pull/8201.

@xuwei-k it'd be great if you could confirm that this also fixes your issue ... most likely it will turn the compiler crash into vanilla implicit resolution failure.

**Comment by xuwei-k** [comment]
confirmed! thanks!
