### ISSUE TITLE
Scaladoc: Predef, deprecated annotation of implicit class `any2stringadd` not shown

### ISSUE THREAD

**Issue by Sciss** [scala/bug#11527]
The docs don't show deprecation:

https://www.scala-lang.org/api/2.13.0-RC1/scala/Predef$$any2stringadd.html

Although it's annotated that way in the source code: https://github.com/scala/scala/blob/v2.13.0-RC1/src/library/scala/Predef.scala#L377-L380

(perhaps related to #11393 ?)

**Comment by adriaanm** [comment]
I assume this is because it's meta-annotated with `@companionMethod`.
