### ISSUE TITLE
`try ()` does not compile

### ISSUE THREAD

**Issue by SrTobi** [scala/bug#11532]
When trying to compile the expression (Scala Version: 2.12.8)
```
try ()
```

the following error message is given:
```
illegal start of simple expression
try ()
     ^
```

Same goes for all tuples in a try (i.e. `try (1, 2)`)

According to the specification this should work:
```
Expr1 ::=  ‘try’ (‘{’ Block ‘}’ | Expr) [‘catch’ ‘{’ CaseClauses ‘}’] [‘finally’ Expr]
                                  ~~~~
```
https://www.scala-lang.org/files/archive/spec/2.12/06-expressions.html#try-expressions

**Comment by SrTobi** [comment]
the match in https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/ast/parser/Parsers.scala#L1518 seems to be the problem

**Comment by SrTobi** [comment]
also note that `try () => ()` doesn't work either.

**Comment by dwijnand** [comment]
I think that makes sense, you need

```scala
scala> try (() => ())
<console>:12: warning: A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.
       try (() => ())
       ^
res0: () => Unit = $$Lambda$1073/204568533@76f856a8
```

**Comment by SrTobi** [comment]
Well... either way, the specification is weird regarding `try`.

Why have `‘try’ (‘{’ Block ‘}’ | Expr)` and not just `try Expr` (like `finally`, `if`, etc...)?

This is even ambiguous, because `Expr` already contains `BlockExpr` (`Expr` > `PostfixExpr` > `InfixExpr` > `PrefixExpr` > `SimpleExpr` > `BlockExpr`)

Yes, `try () => ()` doesn't make much sense, but I think consistency is more desirable here.
And `try (someCall(), someOtherCallThatMayThrow()) finally { println("gc!!!") }` makes definitively sense.

**Comment by adriaanm** [comment]
Thanks for narrowing it down -- that match does indeed look fishy to me. `try (1, 2)` should parse afaict. I think the grammar for `try` reflects how it evolved: originally, you couldn't just pass an expression in. This was added in a7ea09750252edb05465232db0ee2e4ed8ac4039, and I guess no one noticed that was wrong until today :-)

**Comment by dwijnand** [comment]
```scala
scala> try (1, 2)
<console>:1: error: ')' expected but ',' found.
       try (1, 2)
             ^
```

**Comment by dwijnand** [comment]
The story here is similar to the story of infix methods with multiple arguments (which Scala 3 is addressing).

The workarounds are clarifying parentheses:

```scala
scala> try (())
<console>:12: warning: A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.
       try (())
       ^

scala> try ((1, 2))
<console>:12: warning: A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.
       try ((1, 2))
       ^
res5: (Int, Int) = (1,2)
```

**Comment by SrTobi** [comment]
ok thx for clarifying...I was just reworking our parser for `try` in Intellij, which was not any less wrong :smile:, and I thought I'd miss something.

**Comment by som-snytt** [comment]
There is a PR https://github.com/scala/scala/pull/4400 and duplicate https://github.com/scala/bug/issues/5887

**Comment by som-snytt** [comment]
```
$ skala

     ________ ___   / /  ___  
    / __/ __// _ | / /  / _ | 
  __\ \/ /__/ __ |/ /__/ __ | 
 /____/\___/_/ |_/____/_/ | | 
                          |/  version 2.12.6-20180410-164619-76b53db

scala> try ()
<console>:12: warning: A try without a catch or finally is equivalent to putting its body in a block; no exceptions are handled.
       try ()
       ^
```

**Comment by som-snytt** [comment]
Relatedly, I had forgotten about "name-based catch", which is also addressed in that PR:

```
scala 2.13.0-RC1> try 42 catch 22
                               ^
                  error: value isDefinedAt is not a member of Int

scala 2.13.0-RC1> :pa
// Entering paste mode (ctrl-D to finish)

try 42 catch new {
  def isDefinedAt(x: Any) = false
  def apply(x: Any) = ()
}

// Exiting paste mode, now interpreting.


try 42 catch new {
             ^
<pastie>:1: warning: reflective access of structural type member method isDefinedAt should be enabled
by making the implicit value scala.language.reflectiveCalls visible.
This can be achieved by adding the import clause 'import scala.language.reflectiveCalls'
or by setting the compiler option -language:reflectiveCalls.
See the Scaladoc for value scala.language.reflectiveCalls for a discussion
why the feature should be explicitly enabled.

try 42 catch new {
             ^
<pastie>:1: warning: reflective access of structural type member method apply should be enabled
by making the implicit value scala.language.reflectiveCalls visible.
res1: AnyVal = 42
```
