### ISSUE TITLE
Spark Sql is showing blank output on perform join  

### ISSUE THREAD

**Issue by harshit-net** [scala/bug#11539]
on read a file from excel and then assign it to a temp variable  , and when i run a  sql query on that  
 using spark sql ,it shows the empty result.So Please help me .
Thanks in advance.

**Comment by hrhino** [comment]
Hi @harshit-net!

This is the bug tracker for Scala, the language, not Spark, the tool written in Scala. Not many people here know that much about Spark.

I recommend you visit https://gitter.im/spark-scala/Lobby or try the user@spark.apache.com mailing list (http://apache-spark-user-list.1001560.n3.nabble.com/), and if it's a bug, file a ticket on the [Spark JIRA](https://issues.apache.org/jira/browse/SPARK).

Thanks!
