### ISSUE TITLE
shutdown hooks nondeterministic on windows?

### ISSUE THREAD

**Issue by adriaanm** [scala/bug#11536]
From https://scala-ci.typesafe.com/job/scala-2.13.x-integrate-windows/976/consoleFull

```
!!  733 - run/shutdownhooks.scala                   [output differs][duration 5.87s]
% diff Y:\jenkins\workspace\scala-2.13.x-integrate-windows\test\files\run\shutdownhooks.check Y:\jenkins\workspace\scala-2.13.x-integrate-windows\test\files\run\shutdownhooks-run.log--- shutdownhooks.check
+++ shutdownhooks-run.log
@@ -1,3 +1,3 @@
 Fooblitzky!
-main#shutdown.
 Test#shutdown.
+main#shutdown.
##### Log file 'Y:\jenkins\workspace\scala-2.13.x-integrate-windows\test\files\run\shutdownhooks-run.log' from failed test #####

Fooblitzky!
Test#shutdown.
main#shutdown.
```

**Comment by lrytz** [comment]
https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#addShutdownHook-java.lang.Thread- says

>  When the virtual machine begins its shutdown sequence it will start all registered shutdown hooks in some unspecified order and let them run concurrently

I think we just need to give the test a bit more slack in timing (https://github.com/scala/scala/blob/2.13.x/test/files/run/shutdownhooks.scala#L3)

**Comment by som-snytt** [comment]
Maybe it's easier to delete all that code. It's like having a thin Scala wrapper around `finalize`.
