### ISSUE TITLE
Scalac report a deprecation warning inconsistently between var and def

### ISSUE THREAD

**Issue by exoego** [scala/bug#11538]
Scalac report a warning on `@deprecated(...) var` if its type contains deprecated type.

```scala
@deprecated("Non-standard", "0.1")
class StreatmEvent {}

class RTCPeerConnection {
  @deprecated("Non-standard", "0.1")
  var onaddstream: js.Function1[StreatmEvent, _] = js.native
}
```

However, inconsitently, scalac does not report a warning on `@deprecated(...) def` that uses deprecated type.

```scala
@deprecated("Non-standard", "0.1")
class StreatmEvent {}

class RTCPeerConnection {
  @deprecated("Non-standard", "0.1")
  def onaddstream: js.Function1[StreatmEvent , _] = js.native

  @deprecated("Non-standard", "0.1")
  def onaddstream_= (handler: js.Function1[StreatmEvent , _]): Unit = js.native
}
```

For me working on https://github.com/scala-js/scala-js-dom/pull/367, no warnings on member already marked as `@deprecated` is preferrable.
But it may depends on use case.

cc: @sjrd https://github.com/scala-js/scala-js-dom/pull/367#discussion_r284596013

**Comment by som-snytt** [comment]
The annotation isn't winding up on the field. (Same issue with `val`.)

I looked at how it's done and went blind. Annotations from trees have to be attached to symbols. Possibly they are rethinking the mechanism https://github.com/scala/bug/issues/10459 I ran out of morning coffee before I saw why getters and setters work but not the field sym.

**Comment by dwijnand** [comment]
Fixed with https://github.com/scala/scala/pull/8122
