### ISSUE TITLE
join two excel sheets in play framework using sparksql shows empty result.

### ISSUE THREAD

**Issue by harshit-net** [scala/bug#11544]
I am using playframework 2.7,spark 2.4.0,sbt 1.2.8 and scala 2.11

here is my code:
   var file_name1 ="excel1.xlsx" 
      var file_name2 ="excel2.xlsx"       

     
     
     var df1 =Spark.sqlContext.read
    .format("com.crealytics.spark.excel")
    .option("sheetName", "sheet1") // Required
    .option("useHeader", "true") // Required
    .option("treatEmptyValuesAsNulls", "false") // Optional, default: true
    .option("inferSchema", true) // Optional, default: false
    .option("addColorColumns", "false") // Optional, default: false
    .option("timestampFormat", "MM-dd-yyyy HH:mm:ss")
     .load(file_name1)
     .limit(10)
  
   var df2 =Spark.sqlContext.read
    .format("com.crealytics.spark.excel")
    .option("sheetName", "sheet1") // Required
    .option("useHeader", "true") // Required
    .option("treatEmptyValuesAsNulls", "false") // Optional, default: true
    .option("inferSchema", true) // Optional, default: false
    .option("addColorColumns", "false") // Optional, default: false
    .option("timestampFormat", "MM-dd-yyyy HH:mm:ss") // Optional, default: yyyy-mm-dd hh:mm:ss[.fffffffff]
     .load(file_name2)
     .limit(10)
     
    df1.registerTempTable("temp1")
   df2.registerTempTable("temp2")
  
  val df= sqlContext.sql("select * from temp1 inner join temp2 on temp1.a==temp2.a")
     df.show()

**Comment by Jasper-M** [comment]
I don't think this is a bug and definitely not a Scala bug.

**Comment by lrytz** [comment]
Yes, please ask questions on mailing lists.

**Comment by harshit-net** [comment]
but when i run the same code in spark shell it works fine but not in playframework

**Comment by lrytz** [comment]
@harshit-net please read this https://github.com/scala/bug#what-belongs-here

We might have to block your account from the Scala organization if you don't follow the procedures, we tried to explain you [3 times now](https://github.com/scala/bug/issues?q=is%3Aissue+author%3Aharshit-net).
