### ISSUE TITLE
sbt command `scala` fails loading jars

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/bug#11540]
running `scala` in the sbt shell on 2.13.x results in 

> [info] Running (fork) scala.tools.nsc.MainGenericRunner -usejavacp
> Welcome to Scala 2.13.0-20190517-092235-a26aeb7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_201).
> Type in expressions for evaluation. Or try :help.
> 
> scala> error: error while loading ScalaSignature, class file 'C:\Users\marti\AppData\Local\Temp\sbt_db56a33b\target\4e97baec\scala-library.jar(scala/reflect/ScalaSignature.class)' is broken
> (class java.lang.IllegalArgumentException/null)
>                           ^
>        error: object $eval is not a member of package $line1

Can anyone reproduce? If not, how do I start scala in debug mode?

**Comment by SethTisue** [comment]
works for me

**Comment by dwijnand** [comment]
Same.

Try `clean`ing?

**Comment by martijnhoekstra** [comment]
my bad
