### ISSUE TITLE
spark sql query in playframework shows empty result

### ISSUE THREAD

**Issue by harshit-net** [scala/bug#11543]
when i run a Group By query in spark-shell it shows me perfect result but when i run my code with same query using spark sql in playframework with same spark version it shows me empty result, similar issue with Join operation only cross join operation works in playframework with sbt but other joins shows empty result. Please help me in this. Thanks in advance . I am using spark 2.4.0 and play framework 2.7, sbt 1.2.8,scala 2.11.8

**Comment by lrytz** [comment]
This issue tracker is for bugs in Scala. You can ask your question on a mailing list.

**Comment by SethTisue** [comment]
see https://scala-lang.org/community
