### ISSUE TITLE
Java higher-order methods inconsistently require type annotations 

### ISSUE THREAD

**Issue by joshlemer** [scala/bug#11558]
This works:
```scala
scala> import java.util.stream.Stream
import java.util.stream.Stream

scala> Stream.of(1,2,3).map(_ + 1)
res20: java.util.stream.Stream[?0] = java.util.stream.ReferencePipeline$3@27014faf
```

But then, you'd think that this should work:

```scala
scala> Stream.of(1,2,3).map(_.toString)
                              ^
       error: type mismatch;
        found   : Int => String
        required: java.util.function.Function[_ >: Int, _]

```

It can be made to work only by including the map type param:
```scala
scala> Stream.of(1,2,3).map[String](_.toString)
res22: java.util.stream.Stream[String] = java.util.stream.ReferencePipeline$3@7e7daeac
```

This would hopefully work because it does actually work in java:

```java
Stream.of(1,2,3).map(i -> i.toString());
```

**Comment by SethTisue** [comment]
reminiscent of https://github.com/scala/scala-dev/issues/184 , is it the same?

**Comment by dwijnand** [comment]
I guess the inconsistency is that `+` exists on Int, but `.toString` is on `Object` and `Function` isn't contravariant.

**Comment by joshlemer** [comment]
@dwijnand no that's not the issue, it happens whenever the return-type of the function differs from the input type. 

@SethTisue this does seem to be related or the same issue, yes.

**Comment by adriaanm** [comment]
I've been looking at this. Fertile ground for bug fixin'! Already found an issue introduced by https://github.com/scala/scala/pull/6492, but no full fix for this issue yet.

**Comment by som-snytt** [comment]
Seen on SO by someone "stuck" on 2.12, and not in the Valentine's Day sense of "stuck on you."
