### ISSUE TITLE
crash in lambdalift, perhaps interaction with extension method receiver stabilizer

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/bug#11556]
A port of twitter-util to 2.13.0-RCx crashes with

```
java.lang.IllegalArgumentException: Could not find proxy for val rw: com.twitter.io.Pipe in List(value rw, method $anonfun$new$15, value <local PipeTest>, class PipeTest, package io, package twitter, package com, package <root>) (currentOwner= value stabilizer$2 )
[error]         at scala.tools.nsc.transform.LambdaLift$LambdaLifter.searchIn$1(LambdaLift.scala:318)
```

@lrytz suggests reporting even unminimized at https://contributors.scala-lang.org/t/experience-of-migrating-to-2-13-x/3367/7?u=martijnhoekstra.

The full stack trace is at https://gist.github.com/martijnhoekstra/4fe3bd2fbeefceb3b29ee1366aac5c89

You can reproduce with the following branch:

https://github.com/martijnhoekstra/util/tree/bynamecrash

sbt project util-core/test on 2.13.0-RC3 will reproduce the issue. The offending file is util-core/src/test/scala/com/twitter/io/PipeTest.scala

The last commit in that branch (https://github.com/martijnhoekstra/util/commit/5e2e4fb2910f5991101df7da386a3355a5d6b1c5) undoes a workaround that prevents the issue, which could help debugging the issue.

**Comment by lrytz** [comment]
I corrected myself in the post on contributors: the `stabilizer$2` value is due to https://github.com/scala/scala/pull/5999, not by-name implicits.

**Comment by adriaanm** [comment]
Sounds like an issue with the owner chain. Maybe (random guess) an interaction with macros from the test framework?

**Comment by som-snytt** [comment]
Thanks for the hint, my PR for stabilizers has a similar crasher.

**Comment by soronpo** [comment]
I've hit this error today. When trying to minimize it, I made my way into a macro I build. I've noticed it only gave the crash when I returned a tree. So I `c.untypecheck()` that tree and voila, the bug was gone.

**Comment by SethTisue** [comment]
@martijnhoekstra wdyt, shall we close this? is it plausible that your original report stemmed from a problem in a macro?

**Comment by martijnhoekstra** [comment]
A problem in a macro sounds at least plausible. At this point I don't think anybody is looking to minimize this particular case and proof it one way or another, so closing sounds fine to me.
