### ISSUE TITLE
na.drop not work

### ISSUE THREAD

**Issue by wqh17101** [scala/bug#11555]
Hi there

```
val t1=Seq(("a","1"),("b","2")).toDF("id","value")
val t2=Seq(("a","3"),("c","2")).toDF("id","value2")
t1.join(t2,Array("id"),"left").show()
```
![image](https://user-images.githubusercontent.com/26429138/58848152-0c4d2e80-86b8-11e9-8392-46b08bab5695.png)
```
t1.join(t2,Array("id"),"left").na.drop().show()
```
![image](https://user-images.githubusercontent.com/26429138/58848165-1707c380-86b8-11e9-90e9-7858bbb35f61.png)
```
def countMatch(s:String,pattern:String):Int={
    s.sliding(pattern.length).count(_==pattern)
  }

val counterWord = udf((s:String)=>{
	keywordSeq.map(x=>(x,Util.countMatch(s,x))).filter(_._2!=0)
})
```
when i run 
```
t1.join(t2,Array("id"),"left").na.drop().withColumn("counter",counterWord(col("value2"))).withColumn("size",size($"counter")).filter($"size" === 1).show()

```
i got a java null exception

but when i run 
```
t1.join(t2,Array("id"),"left").na.drop().withColumn("counter",counterWord(col("value2"))).withColumn("size",size($"counter")).persist().filter($"size" === 1).show()
```
it worked.

i wander know why i can get the right answer when i use persist(). it seems that without persist(), the code run in the wrong order.

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org for questions

**Comment by wqh17101** [comment]
@SethTisue i dont know how to new the issue. What i can do for now is just watching?
![image](https://user-images.githubusercontent.com/26429138/58853596-6f958b80-86cd-11e9-8369-369b444237d5.png)

**Comment by SethTisue** [comment]
You need to click "Log In" first before you can post. You can log in with your GitHub identity.

**Comment by wqh17101** [comment]
@SethTisue the icon on the right means that i have already log in

**Comment by wqh17101** [comment]
@SethTisue oh, it is funny, it seems like that there is a system for trust level.
![image](https://user-images.githubusercontent.com/26429138/58855197-09f7ce00-86d2-11e9-83f3-71321421b5e4.png)

**Comment by lrytz** [comment]
yes, your post was in the review queue. you should be able to post from now on.

**Comment by wqh17101** [comment]
I see it .Thank you for all your help . @SethTisue @lrytz
