### ISSUE TITLE
intermittent scala.collection.immutable.ImmutableChampHashMapProperties failure

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#11557]
spotted at https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/8732/consoleFull :

```
[error] Failed: Total 923, Failed 1, Errors 0, Passed 922
[error] Failed tests:
[error] 	scala.collection.immutable.ImmutableChampHashMapProperties
```

I don't see any details about the error in the log, but I'm in a bit of rush right now, could somebody look into it...? maybe crank up the number of repetitions locally and see if you can provoke the failure?

**Comment by Philippus** [comment]
https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/8732/:
`scala.collection.immutable.ImmutableChampHashMapProperties.merged(right) { select right } is the same as left concat right`

https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/8729/:
`scala.collection.immutable.ImmutableChampHashMapProperties.merged(right) { select left } is the same as right concat left`

**Comment by NthPortal** [comment]
I was poking into this and discovered the unrelated #11559

**Comment by NthPortal** [comment]
the two failures @Philippus linked both claim that `HashMap("" -> "").merged(HashMap("" -> ""))` fails, which is very odd

**Comment by lrytz** [comment]
It seems this didn't happen again. Was it the phase of the moon? Maybe a race condition with tests executing in parallel?

The output of the two jenkins runs linked above doesn't give an example that fails the test in question...
  - https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/8732/testReport/scala.collection.immutable/ImmutableChampHashMapProperties/merged_right____select_right___is_the_same_as_left_concat_right/
  - https://scala-ci.typesafe.com/job/scala-2.13.x-validate-main/8729/testReport/junit/scala.collection.immutable/ImmutableChampHashMapProperties/merged_right____select_left___is_the_same_as_right_concat_left/

Should we close this ticket?

**Comment by SethTisue** [comment]
> maybe crank up the number of repetitions locally and see if you can provoke the failure?

I tried `scalacheck/testOnly *ImmutableChamp* -- -minSuccessfulTests 100000`, and it passed (elapsed time: about 9 minutes)

> It seems this didn't happen again

I haven't seen it again either

\</dueDiligence>

**Comment by Philippus** [comment]
Maybe use `propertyWithSeed` instead of `property` for easier reproducibility.

**Comment by SethTisue** [comment]
https://github.com/rickynils/scalacheck/issues/400, sigh (not that I've submitted a fix...)
