### ISSUE TITLE
Increment problem

### ISSUE THREAD

**Issue by picreed** [scala/bug#11552]
```scala
object Main {
  def main(args: Array[String]): Unit = {
    var x = 0
    while (1<2){
      println(x)
      x = x+970
    }
  }
}
```

the following code produces negative numbers after several seconds of compilation

**Comment by NthPortal** [comment]
This is not a bug. When the result of a mathematical operation exceeds `Int.MaxValue` (on the JVM), the value overflows to a negative value (specifically, `Int.MaxValue + 1 == Int.MinValue`).

**Comment by picreed** [comment]
Thanks I'll remove the issue
