### ISSUE TITLE
String interpolator macro crashes REPL

### ISSUE THREAD

**Issue by retronym** [scala/bug#11564]
```
$  printf "val x = \"\"; s\"\$x\"\nval s\"\$y\" = \"\"\nval x = \"\"; s\"\$x\"\n"| scala-launch 2.13.0
Welcome to Scala 2.13.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_172).
Type in expressions for evaluation. Or try :help.

scala> val x = ""; s"$x"
x: String = ""
res0: String = ""

scala> val s"$y" = ""
y: String = ""

scala> val x = ""; s"$x"
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:632)
	at scala.None$.get(Option.scala:631)
```

I notice that the fast track map, at least in the `Run` that crashes, has an overloaded symbol for `StringContext_s`.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/65551/59418246-01398300-8dc9-11e9-925b-834e8edc5eb7.png">

That's due to the addition of `object s` (an unapply extractor) in `StringContext` in 2.13. But I'm not sure why `getMemberMethod` isn't filtering that out in:

```scala
lazy val StringContext_s = getMemberMethod(StringContextClass, nme.s).filter(_.isMethod)
```

**Comment by som-snytt** [comment]
Thanks for the find, @lihaoyi. Oh my, there's already a PR, @retronym. You'd think this combination of features would have been tried; I'll muse on that and report, if there's anything to say.

**Comment by retronym** [comment]
The report was filed in person which expedited things somewhat.

**Comment by som-snytt** [comment]
I saw the gitter as I fell asleep. Dale's reply omitted the shrug emoji:
```
Yeah it's a macro. ¯\_(ツ)_/¯
```

**Comment by lihaoyi** [comment]
My workaround in Ammonite to just throw away the compiler every command when running under 2.13.0

- https://github.com/lihaoyi/Ammonite/pull/972/commits/7b83eb0ed12797912556ac53f4e03243f3961197

Costs me a few 10s of ms of performance, but no big deal. The bandaid automatically turn itself off once 2.13.1 rolls around
