### ISSUE TITLE
Calling BoxesRunTime.boxToBoolean for Function1 with specialized return type

### ISSUE THREAD

**Issue by vladmlch** [scala/bug#11561]
Recently I profiled my production project and observed that `BoxesRunTime.boxToBoolean` is in top N hot methods. Diving deep I created test-case which shows that specialization on return type does not work on scala version (2.11, 2.12, 2.13). Here is a code:

    object BoxTest {
    
      def main(args: Array[String]): Unit = {
        {
          val f: String => Boolean = _.length == math.random()
          List("1", "2").filter(f)
        }
    
        {
          List("1", "2").filter(_.length == math.random())
        }
    
        {
          customF(_.hashCode() == math.random())
          customF2(_.hashCode() == math.random())
        }
      }
    
      def customF(f: Any => Boolean) = println(f(math.random()))
      def customF2(f: Function1[Any, Boolean]) = println(f(math.random()))
    }

Which is compiled to 

    import scala.Function1;
    import scala.reflect.ScalaSignature;
    
    @ScalaSignature(
       bytes = "\u0006\u0005m:QAB\u0004\t\u0002)1Q\u0001D\u0004\t\u00025AQ\u0001F\u0001\u0005\u0002UAQAF\u0001\u0005\u0002]AQaK\u0001\u0005\u00021BQ\u0001O\u0001\u0005\u0002e\nqAQ8y)\u0016\u001cHOC\u0001\t\u0003\u0015!Xm\u001d;t\u0007\u0001\u0001\"aC\u0001\u000e\u0003\u001d\u0011qAQ8y)\u0016\u001cHo\u0005\u0002\u0002\u001dA\u0011qBE\u0007\u0002!)\t\u0011#A\u0003tG\u0006d\u0017-\u0003\u0002\u0014!\t1\u0011I\\=SK\u001a\fa\u0001P5oSRtD#\u0001\u0006\u0002\t5\f\u0017N\u001c\u000b\u00031m\u0001\"aD\r\n\u0005i\u0001\"\u0001B+oSRDQ\u0001H\u0002A\u0002u\tA!\u0019:hgB\u0019qB\b\u0011\n\u0005}\u0001\"!B!se\u0006L\bCA\u0011)\u001d\t\u0011c\u0005\u0005\u0002$!5\tAE\u0003\u0002&\u0013\u00051AH]8pizJ!a\n\t\u0002\rA\u0013X\rZ3g\u0013\tI#F\u0001\u0004TiJLgn\u001a\u0006\u0003OA\tqaY;ti>lg\t\u0006\u0002\u0019[!)a\u0006\u0002a\u0001_\u0005\ta\r\u0005\u0003\u0010aI*\u0014BA\u0019\u0011\u0005%1UO\\2uS>t\u0017\u0007\u0005\u0002\u0010g%\u0011A\u0007\u0005\u0002\u0004\u0003:L\bCA\b7\u0013\t9\u0004CA\u0004C_>dW-\u00198\u0002\u0011\r,8\u000f^8n\rJ\"\"\u0001\u0007\u001e\t\u000b9*\u0001\u0019A\u0018"
    )
    public final class BoxTest {
       public static void customF2(final Function1 f) {
          BoxTest$.MODULE$.customF2(var0);
       }
    
       public static void customF(final Function1 f) {
          BoxTest$.MODULE$.customF(var0);
       }
    
       public static void main(final String[] args) {
          BoxTest$.MODULE$.main(var0);
       }
    }
    
            //decompiled from BoxTest$.class
    package tests;
    
    import java.lang.invoke.SerializedLambda;
    import scala.Function1;
    import scala.collection.immutable.List;
    import scala.collection.immutable..colon.colon;
    import scala.collection.immutable.Nil.;
    import scala.runtime.BoxesRunTime;
    
    public final class BoxTest$ {
       public static final BoxTest$ MODULE$ = new BoxTest$();
    
       public void main(final String[] args) {
          Function1 f = (x$1) -> {
             return BoxesRunTime.boxToBoolean($anonfun$main$1(x$1));
          };
          ((List)(new colon("1", new colon("2", .MODULE$)))).filter(f);
          ((List)(new colon("1", new colon("2", .MODULE$)))).filter((x$2) -> {
             return BoxesRunTime.boxToBoolean($anonfun$main$2(x$2));
          });
          this.customF((x$3) -> {
             return BoxesRunTime.boxToBoolean($anonfun$main$3(x$3));
          });
          this.customF2((x$4) -> {
             return BoxesRunTime.boxToBoolean($anonfun$main$4(x$4));
          });
       }
    
       public void customF(final Function1 f) {
          scala.Predef..MODULE$.println(f.apply(BoxesRunTime.boxToDouble(scala.math.package..MODULE$.random())));
       }
    
       public void customF2(final Function1 f) {
          scala.Predef..MODULE$.println(f.apply(BoxesRunTime.boxToDouble(scala.math.package..MODULE$.random())));
       }
    
       // $FF: synthetic method
       public static final boolean $anonfun$main$1(final String x$1) {
          return (double)x$1.length() == scala.math.package..MODULE$.random();
       }
    
       // $FF: synthetic method
       public static final boolean $anonfun$main$2(final String x$2) {
          return (double)x$2.length() == scala.math.package..MODULE$.random();
       }
    
       // $FF: synthetic method
       public static final boolean $anonfun$main$3(final Object x$3) {
          return (double)x$3.hashCode() == scala.math.package..MODULE$.random();
       }
    
       // $FF: synthetic method
       public static final boolean $anonfun$main$4(final Object x$4) {
          return (double)x$4.hashCode() == scala.math.package..MODULE$.random();
       }
    
       private BoxTest$() {
       }
    
       // $FF: synthetic method
       private static Object $deserializeLambda$(SerializedLambda var0) {
          return Class.lambdaDeserialize<invokedynamic>(var0);
       }
    }

version scala 2.13-RC3, but similar (or the same) is generated on 2.11 and 2.12.

Could someone clarify is this expected behavior or should it be fixed?

**Comment by joroKr21** [comment]
I think that's a known limitation of `@specialized`. If one or more of the specialized type parameters are instantiated to non-specialized types then none of them are. I find this (admittedly old) article a quite helpful resource: http://aleksandar-prokopec.com/2013/11/03/specialization-quirks.html. Maybe not all gotchas apply nowadays but looks like this one does.

**Comment by profic** [comment]
Got it, thanks @joroKr21
