### ISSUE TITLE
Please update spec links and advisements to 2.13

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11566]
The future is now.

**Comment by SethTisue** [comment]
three PRs and counting. wonder what else I'm missing.

**Comment by som-snytt** [comment]
Beautiful! Is it supposed to have a red banner announcing, THE FUTURE IS NOW?

Clicking around, I see the "Scala 2.13" button links to the change log, which says:

> Trailing commas in expression, argument, type or pattern sequences are no longer supported.

It's just one of those things. Trailing commas are literally my favorite feature. Even after I recently discovered the sbt plugin that lets you omit all commas. Was it a big secret? Or maybe they decided it was too hard to explain trailing commas or no commas.

**Comment by SethTisue** [comment]
"I am reasonably sure that a pull request removing the antiquated change log would be accepted,” he intoned a neutral voice, staring into the middle distance
