### ISSUE TITLE
compileTimeOnly annotation does not work in dead code

### ISSUE THREAD

**Issue by scf37** [scala/bug#11563]
This one compiles in 2.13.0:

```scala
@compileTimeOnly def fun(f: () => Unit): Unit = ???
if (false) fun(() => Unit)
```

But that one fails:

```scala
@compileTimeOnly def fun(f: () => Unit): Unit = ???
fun(() => Unit)
```

Expected: both samples should not compile
Actual: first one compiles

Scala: 2.12.8, 2.13.0

**Comment by Jasper-M** [comment]
Does dead code removal run by default? In the end if it's dead code it kind of *is* compile time only 😛

**Comment by som-snytt** [comment]
Yes, that is what the annotation means.

The Java spec on "Unreachable statements" goes to some lengths to explain why unreachability for `if` statements is defined as it is, which is, to enable the `if (false)` idiom.

I might slap `compileTimeOnly` on my `debuggerem` method to ensure that usages were properly wrapped in `if (ProjectConstants.Debuggering)`, where the flag is set false before releasing to QA. Possibly my method was also marked `elidable`, but that requires a build flag to work, and I don't trust the person running the build.

For comparison:
```
scala 2.13.0> if (false) List(1) size
                                 ^
              error: postfix operator size needs to be enabled
              by making the implicit value scala.language.postfixOps visible.
              This can be achieved by adding the import clause 'import scala.language.postfixOps'
              or by setting the compiler option -language:postfixOps.
              See the Scaladoc for value scala.language.postfixOps for a discussion
              why the feature needs to be explicitly enabled.

scala 2.13.0> Unit
              ^
              error: `Unit` companion object is not allowed in source; instead, use `()` for the unit value

scala 2.13.0> if (false) Unit
res2: Any = ()
```

**Comment by som-snytt** [comment]
"Once we have untyped macros, there won't be any necessity in having the @compileTimeOnly annotation."

**Comment by som-snytt** [comment]
Also, this doesn't work as one might hope, as cto is checked before eliding the RHS:
```
  @elidable(5) def f = g
  @compileTimeOnly("No gee!") def g = 42
```
