### ISSUE TITLE
App.main is not safe when using in multiple threads

### ISSUE THREAD

**Issue by zsxwing** [scala/bug#11576]
When an object extends `App`, its `val` fields are no longer immutable. They can be changed when the `main` method is called.

Test codes:

```
package foo
  
object Foo extends App {
  val o = new Object
  println("before sleeping: " + System.identityHashCode(o))
  Thread.sleep(1000)
  println("after sleeping: " + System.identityHashCode(o))
}
```
Save the above codes into `Foo.scala` and run `bin/scala -i Foo.scala`. Then run `for(_ <- 0 until 20) { new Thread(){override def run(): Unit = { foo.Foo.main(Array[String]()) }}.start()}` and we will see `Foo.o` will be changed when the `main` method is called.

```
bin/scala -i Foo.scala

scala> for(_ <- 0 until 20) { new Thread(){override def run(): Unit = { foo.Foo.main(Array[String]()) }}.start()}
before sleeping: 468999564
before sleeping: 1307011118
before sleeping: 576840873
before sleeping: 161905467
before sleeping: 1851738528
before sleeping: 1609246765
before sleeping: 1963522280
before sleeping: 599879316
before sleeping: 1485984579
before sleeping: 1485984579
before sleeping: 613807594
before sleeping: 809681270
before sleeping: 809681270
before sleeping: 1888925102
before sleeping: 507593600
before sleeping: 676610477
before sleeping: 4193694
before sleeping: 1775559751
before sleeping: 1471569059
before sleeping: 1512438079

scala> after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
after sleeping: 809681270
```

**Comment by zsxwing** [comment]
cc @jiangxb1987

**Comment by som-snytt** [comment]
This probably falls under the caveat on App that fields are not initially initialized and the deprecation of DelayedInit that its semantics are surprising.

But it is worth saying that the successor implementation of App shouldn't change the semantics of val.

**Comment by szeiger** [comment]
Related: https://github.com/scala/bug/issues/11412 (fields are even final in bytecode which is not allowed but not caught by the bytecode verifier; this can lead to very surprising side-effects)

**Comment by zsxwing** [comment]
@szeiger Yep. Sounds related. But your fix in #8067 doesn't fix the issue in this ticket. Right?

**Comment by szeiger** [comment]
Right, this issue shows a fundamental problem with the `DelayedIinit` design. It allows you to pretend that you have final vals but gives you an explicit way to run the initializer more than once. This could be fixed for `App` (either with the current `DelayedIinit`-based implementation or a future one with dedicated compiler support) by CASing a flag at the beginning of `main` and throwing an exception if it is called more than once.

In the long run I'd prefer to see `App` replaced by top-level functions (using an annotation or some explicit evidence to make them eligible as `main` methods). This would solve the problem at the design level: If you don't pretend to have a singleton in the first place then you don't have to prevent multiple initializations.

**Comment by Jasper-M** [comment]
@szeiger 
> this can lead to very surprising side-effects

Could https://github.com/scala/bug/issues/11412 be such a side-effect?

**Comment by SethTisue** [comment]
This isn't going to improve in Scala 2 (`App` is what it is, `DelayedInit` is what it is). Hence, closing the ticket — this is working as designed, it's just a questionable design.

Scala 3 uses a different design, along the lines @szeiger describes.
