### ISSUE TITLE
[java-interop] Compilation error "incompatible type in overriding" when inheriting from a Java subclass with different field type to parent class (regression in 2.13)

### ISSUE THREAD

**Issue by hughsimpson** [scala/bug#11575]
Minimal to reproduce:

```java
public class Base {
    long[] counts;
}

public class Cover extends Base {
    int[] counts;
}
```

Extending in Scala:
```scala
class LocalImpl extends Cover
```

throws `incompatible type in overriding` in 2.13.0 (compiles for 2.10.7, 2.11.12, 2.12.7)

**Comment by SethTisue** [comment]
Nicely minimized.

At first I thought this might be an access thing, but it's not, it's a method-vs-field thing. Make the fields public, javac still accepts it. But make the fields into methods, and javac of course says `counts() in Cover cannot override counts() in Base`, regardless of whether they're public-access or default-access.

I'm a bit appalled that this is even legal Java...

@adriaanm I assume this relates to your refchecks changes?

**Comment by adriaanm** [comment]
Yeah, looks like another victim of the stricter refchecks in https://github.com/scala/scala/pull/7439.
Looks like we need to add a few exemptions in the logic for when we're dealing with Java pairs

**Comment by hughsimpson** [comment]
For posterity, the workaround in my case was to use a delegate pattern and not subclass directly. cf https://github.com/kamon-io/Kamon/commit/4ca896d93ae088a4dc34ff79b4cb56b620730945
