### ISSUE TITLE
scala-library.jar grew a lot from 2.13.0-M5 to 2.13.0-RC1

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#11577]
we should understand what happened here:

```
3.9M    scala-2.13.0-M5/lib/scala-library.jar
5.3M    scala-2.13.0-RC1/lib/scala-library.jar
```

it isn't just that the scala-java8-compat merge landed; everything got bigger:

<img width="512" alt="Screen Shot 2019-06-19 at 7 23 57 AM" src="https://user-images.githubusercontent.com/161079/59739012-97572880-9263-11e9-9509-0972f107a684.png">

I've added "check jar size" to the release steps, but as @dwijnand suggests, it would be better if we also had some check on this as part of PR validation

**Comment by adriaanm** [comment]
I'm going to start by comparing some sha close to M5 compiled with itself and compiled with RC1 (for a sha that compiles with both)

**Comment by adriaanm** [comment]
I had to cherry-pick a few commits onto v2.13.0-M5 for it compile under RC1, but the good news is that the scala-library jar sizes are very close when compiled by either compiler. So, it's unlikely a bug in standard codegen. Maybe the inliner got more aggressive?

**Comment by adriaanm** [comment]
```
$ g log v2.13.0-M5.. --oneline    
21e5f85 (HEAD) Use a java static to throw IndexOutOfBoundsException
fbe3651 Use proxy-based serialization for modules
2eb20e8 Change Predef.$conforms type from A <:< A to A => A
c3b8c55 Move <:<, =:=, DummyImplicits out of Predef

$ sbt -Dstarr.version=2.13.0-RC1 clean publishLocal

$ ls -l ~/scala/scala-2.13.0-M5/lib/scala-library.jar /Users/adriaan/.ivy2/local/org.scala-lang/scala-library/2.13.0-pre-21e5f85/jars/scala-library.jar    

```

**Comment by adriaanm** [comment]
Enabling the optimizer doesn't affect the jar size much:

```
ls -l /Users/adriaan/.ivy2/local/org.scala-lang/scala-library/2.13.0-pre-21e5f85/jars/scala-library.jar
-rw-r--r--  1 adriaan  staff  4031551 Jun 19 11:47 /Users/adriaan/.ivy2/local/org.scala-lang/scala-library/2.13.0-pre-21e5f85/jars/scala-library.jar
```

**Comment by adriaanm** [comment]
Looks like it was just the growth due to scala/scala#7458. Scala-library went from 4476282 to 5514612 between scala/scala@dc11644 and scala/scala@a2eebb4 compiling both with 2.13.0-RC1 (one small patch needed for the latter: `g co a864ae0  /Users/adriaan/git/scala/src/library/scala/collection/convert/Accumulator.scala`)

**Comment by adriaanm** [comment]
Since scala-reflect didn't budge, I think we can also take that as a datapoint in favor of the assumption that it's not codegen

**Comment by SethTisue** [comment]
seven months of everbody furiously coding on the new collections, then.

some additional history here:

```
5.0M	scala-2.12.8/lib/scala-library.jar
4.1M	scala-2.13.0-M1/lib/scala-library.jar
4.1M	scala-2.13.0-M3/lib/scala-library.jar
3.8M	scala-2.13.0-M4/lib/scala-library.jar
3.9M	scala-2.13.0-M5/lib/scala-library.jar
5.3M	scala-2.13.0-RC1/lib/scala-library.jar
5.4M	scala-2.13.0/lib/scala-library.jar
```

note that we ended up only around 8% over the 2.12 number

this is worth doing the diligence on, but I think we could close it now

**Comment by SethTisue** [comment]
or maybe close this one and make a new ticket for the backstop, but on the 2.12.9 milestone, we'd want it there too

**Comment by lrytz** [comment]
It would be interesting to check if https://github.com/scala/scala/pull/7133 had any effect.
