### ISSUE TITLE
Set().map() Information Loss = Dangerous Behavior

### ISSUE THREAD

**Issue by IDoCodingStuffs** [scala/bug#11580]
```
val elements = Set(1,2,3)
val weights = Map(1 -> 1.0, 2 -> 1.0, 3 -> 1.0)
val values = Map(1 -> 0.2, 2 -> 0.6, 3 -> 0.4)
 
val wSum = elements.map(element=>
        weights(element) * values(element))
      .sum

wSum == 1.2 //True
```

Looks good so far

```
val elements = Set(1,2,3)
val weights = Map(1 -> 1.0, 2 -> 1.0, 3 -> 1.0)
val values = Map(1 -> 0.5, 2 -> 0.5, 3 -> 0.5)
 
val wSum = elements.map(element=>
        weights(element) * values(element))
      .sum

wSum == 1.5 //False, wSum = 0.5
```

Making elements a Seq fixes this since the result of the .map will be a Vector(3) instead of Set(1)

**Comment by IDoCodingStuffs** [comment]
Also dibs on the PR

**Comment by IDoCodingStuffs** [comment]
Before someone else beats me to it, yes this is dangerous behavior. How does Java represent keysets for maps? (HInt: read it again)

**Comment by ashawley** [comment]
There seems to be a bug in your example.

```
scala> val elements = Set(1,2,3,4)
elements: scala.collection.immutable.Set[Int] = Set(1, 2, 3, 4)

scala> val weights = Map(1 -> 1.0, 2 -> 1.0, 3 -> 1.0)
weights: scala.collection.immutable.Map[Int,Double] = Map(1 -> 1.0, 2 -> 1.0, 3 -> 1.0)

scala> val values = Map(1 -> 0.2, 2 -> 0.6, 3 -> 0.4)
values: scala.collection.immutable.Map[Int,Double] = Map(1 -> 0.2, 2 -> 0.6, 3 -> 0.4)

scala> elements.map { element =>
     |   weights(element) * values(element)
     | }.sum
java.util.NoSuchElementException: key not found: 4
```

**Comment by ashawley** [comment]
It is confusing, but mapping over a `Set` returns a `Set`.  That's the way it is.  I'm not sure there's a way to make it "safer" without irreperably changing the definition of `Set` or `map`.  Here's a simpler example:

```
scala> Set(1,2,3,4).toSeq.map(_ => 1).sum
res1: Int = 4

scala> Set(1,2,3,4).map(_ => 1).sum
res2: Int = 1
```

**Comment by IDoCodingStuffs** [comment]
That 4 is not supposed to be there, fixed.

Set behavior is completely correct here but the solution here is .map() should not return a set by default, it simply does not make sense. For a function x -> y where x is from a Set same y can be mapped from different x values. Returning a Set does not make mathematical sense then, so that behavior must change

**Comment by IDoCodingStuffs** [comment]
And in practice my example on top is the intuitive weighted sum. Which I can guarantee is used in some form in some analytics engine out there that it also utilizes Java HashMaps from some legacy code. And it returns wronger weighted averages the more mods the distribution has because it is downright dropping data points. See where this is going?

**Comment by ashawley** [comment]
You'd need to share a minimal version of your `java.util.HashMap` code, but I'm sure there's a difference.

I don't know a lot about the Java 8 collections, but I predict all the collections have to be converted to an `Iterator` or a `Stream` to map over them, and that's the reason why this problem doesn't occur in Java.  The Scala collections library predates the Java 8 collections by a number of years.

**Comment by IDoCodingStuffs** [comment]
```
//Imagine this part is from an imported Java legacy parser, written as Scala for convenience
import java.util._
val elements = new HashMap[Int, Array[BigDecimal]]{
  put(1, Array(BigDecimal(1.0), BigDecimal(0.5)))
  put(2, Array(BigDecimal(1.0), BigDecimal(0.5)))
  put(3, Array(BigDecimal(1.0), BigDecimal(0.5)))
}
//Hypothetical application importing the above
import scala.jdk.CollectionConverters._

val wSum = elements.keySet.asScala.map(element=>
        elements.get(element)(0) * elements.get(element)(1))
      .sum

wSum == BigDecimal(1.5) //False
```

**Comment by SethTisue** [comment]
This is working as designed. It's always been this way — at least since Scala 2.7 (2008), anyway, that's the oldest version I have on my laptop. We kept this aspect of the design in the Scala 2.13 collections redesign.

If you want a different result type, convert the collection first, or go through `.iterator` (any Scala version) or `.view` (works well beginning on Scala 2.13) and ask for the collection type you want at the end.

```
scala 2.13.0> Set(1,2,3).map(_ / 2)
res3: scala.collection.immutable.Set[Int] = Set(0, 1)

scala 2.13.0> Set(1,2,3).view.map(_ / 2).to(List)
res4: Seq[Int] = List(0, 1, 1)
```

**Comment by eed3si9n** [comment]
> This is working as designed. 

I agree.

`Set#map` returning a `Set` is one of core principles of Scala collections that's been around, and documented widely.

**Comment by IDoCodingStuffs** [comment]
Any reference to the justification for that core principle? Besides "that's the way it's been" that is, I do not see why map should discard duplicate values under any circumstances

**Comment by eed3si9n** [comment]
> Any reference to the justification for that core principle?

Since you mentioned "Returning a Set does not make mathematical sense", are you familiar with Functor law (http://eed3si9n.com/herding-cats/Functor.html)?  The underlying principle of `map` is a functor, a transformation of `F[A]` to `F[B]` while preserving the structure of `F`.

In terms of the design intent, I think you should be able to find some reference in

- 'Programming in Scala'
- https://docs.scala-lang.org/overviews/collections/introduction.html
- https://docs.scala-lang.org/overviews/core/architecture-of-scala-collections.html

See for example https://docs.scala-lang.org/overviews/collections/overview.html#an-overview-of-the-collections-api

> All collections support the API provided by `Traversable`, but specialize types wherever this makes sense. For instance the map method in class `Traversable` returns another `Traversable` as its result. But this result type is overridden in subclasses. For instance, calling `map` on a `List` yields again a `List`, calling it on a `Set` yields again a `Set` and so on.

**Comment by ashawley** [comment]
Good find, Eugene.  I was going to suggest documentation improvements, but I guess you found it is mentioned on the "_Collections Overview_".   Maybe a word of warning should be added to the [Sets](https://docs.scala-lang.org/overviews/collections/sets.html) page?  It fails to mention `map`, and it may be good to emphasize the functor situation which may trip some folks up with `Set`.

**Comment by IDoCodingStuffs** [comment]
I'd say documentation definitely calls for a specific mention of this case if consensus is towards no implementation changes. See Haskell documentation for Data.Set#map for instance:

https://downloads.haskell.org/~ghc/6.4.1/docs/html/libraries/base/Data-Set.html#7

![image](https://user-images.githubusercontent.com/43346404/59809069-fdc46100-92cc-11e9-9a34-c6aa8d5bc79b.png)

Still, I am not convinced this should be just left alone in the code, maybe a warning during compile if nothing else

**Comment by SethTisue** [comment]
documentation improvements :+1: yes please

I do not think this merits a compiler warning. I appreciate you taking the time to tackle making the linked PR, but I will oppose merging it.

lots of reading on whether sets qualify as functors at https://stackoverflow.com/questions/19177125/sets-functors-and-eq-confusion

if you want to have a design discussion about this, you'd get a broader audience on https://contributors.scala-lang.org than here in the bug tracker. in general, that's where we have more open-ended discussions.

**Comment by ashawley** [comment]
I tinkered in Java a bit, and this would probably be a closer equivalent of mapping over a `Set`:

```java
Map<Integer,double[]> elements = new java.util.HashMap() {{
  put(1, new double[]{1.0, 0.5});
  put(2, new double[]{1.0, 0.5});
  put(3, new double[]{1.0, 0.5});
}};

double sum = elements.keySet().stream()
  .map(k -> elements.get(k)[0] * elements.get(k)[1])
  .collect(Collectors.summingDouble(Double::doubleValue));
```

The point to emphasize is that [Set](https://docs.oracle.com/javase/8/docs/api/java/util/Set.html) in Java doesn't have a `map`.   It needs to converted to a `Stream`, first.  Java didn't use the functor pattern in its collections.  There could be an argument for or against it, especially for a case like this, but it is different.  

Documentation would be beneficial.  Just like how dividing by zero is mathematically well-defined, a programming language or library still still need to mention what happens (e.g. throws exception or returns `NaN`).

**Comment by joshlemer** [comment]
@IDoCodingStuffs Leaving aside how to get from here to there (from current state of api to ideal state), I strongly agree with the spirit of this issue. 

The behaviour of `Set#map` is quite strange on its own, but especially as an implementation of the `Iterable` interface, I think the difference in behaviour between Set's map and that of other Iterables makes it very questionable what is the use-case of `Iterable#map` at all? If you have an `Iterable[T]` and you call `map` on it, you actually do not know if it is deduplicating or not. I cannot think of a situation in which I would like to map each element of an `Iterable[T]` to something, but then I don't actually care if the output is deduplicated or not. 

```scala
def foo(it: Iterable[Int]): Iterable[Int] = it.map(_ / 3)

foo(List(1,2)) // List(0, 0)
foo(Set(1, 2)) // Set(0)
```

The situation is even more bizarre when you look at Map, which can completely change its behaviour based on if you know it is a Map at compile time:

```scala
scala> Map(1 -> 1, 2 -> 1).map(_.swap)
res14: scala.collection.immutable.Map[Int,Int] = Map(1 -> 2)

scala> (Map(1 -> 1, 2 -> 1): Iterable[(Int, Int)]).map(_.swap)
res15: Iterable[(Int, Int)] = List((1,1), (1,2))
```

I think in an ideal world, and maybe something we can shoot for long term, is a situation where Sets and Maps return `Iterable`s from their map methods, and Seq's continue as they do today, refining their `map` output to return `Seq`: 

```scala
scala> Map(1 -> 1, 2 -> 1).map(_.swap)
res14: Iterable[(Int, Int)] = List((1,1), (1,2))
scala> (Map(1 -> 1, 2 -> 1): Iterable[(Int, Int)]).map(_.swap)
res15: Iterable[(Int, Int)] = List((1,1), (1,2))

scala> Set(1,2).map(_ / 3)
res18: scala.collection.immutable.Iterable[Int] = List(0, 0)

scala> Seq(1,2).map(_ / 3)
res19: Seq[Int] = List(0, 0)
```

**Comment by joshlemer** [comment]
(all the above goes equally for `flatMap`, `collect`)

**Comment by IDoCodingStuffs** [comment]
Created a topic at
https://contributors.scala-lang.org/t/set-map-deduping-and-possibly-unsafe-behavior/3436

Also pasted your comment verbatim on there @joshlemer. A design change, if agreed on, should follow along those lines
