### ISSUE TITLE
Wrong exit code for scala script in 2.13.0

### ISSUE THREAD

**Issue by flomebul** [scala/bug#11581]
With the following code in a file "ProgOne.scala"

//ThisIsABug
val bug = 1 / 0
println(s"bug = $bug")

The process "scala -howtorun:script ProgOne.scala" raise an exception (java.lang.ArithmeticException: / by zero), but the exit code returned is 0inside of not 0

**Comment by SethTisue** [comment]
If someone decides to tackle this, you'll want to check both the unix and the windows runners.

**Comment by som-snytt** [comment]
I broke it, so I fixed it. I'll try to set up a test when I fully awake.

**Comment by SethTisue** [comment]
Oh, I didn't realize that it was a regression. I'll update the metadata accordingly.
