### ISSUE TITLE
Hard-coded “scalac” in Partest suiteRunner.verbose is misleading

### ISSUE THREAD

**Issue by FlashSheridan** [scala/bug#11585]
The hard-coded “scalac” in the message from suiteRunner.verbose (code below) is misleading; what the function does immediately after the message seems quite different from calling `scalac`, though I don’t understand yet what it _is_ doing.  I would suggest changing “scalac” to “compiling.”

`suiteRunner.verbose(s"% scalac ${ sources.map(_.testIdent).mkString(space) }${ if (suiteRunner.debug) " -d " + outDir else ""}")`

### Motivation:
I’m testing a compiler for a blockchain language based on Scala (http://axoni.com/axlang), and would like to run Partest against our compiler.  As a first step, I tried to compile with my system `scalac`, by changing `compilerUnderTest` and the `"compiler"` case in `findArtifact()` in partest/scala/tools/partest/nest/FileManager.scala.
      This made the output from Partest for “Compiler under test:” and “baseDir:” suggest that I had succeeded, but if I moved the system compiler away, the results were unaffected. (See https://contributors.scala-lang.org/t/using-partest-with-a-different-compiler/3379 for details, which has gone unanswered.)

**Comment by hrhino** [comment]
I responded on the linked thread. Sorry it took a scala/bug issue for someone to notice.

I'm going to close this as "out of scope"; the discourse is probably the better place to have this discussion.
