### ISSUE TITLE
Unexpected mkString behaviour on Array[Char] in 2.13.0

### ISSUE THREAD

**Issue by plim** [scala/bug#11583]
In scala version 2.13.0, calling `mkString` on an `Array[Char]` with a separator that isn't an empty string returns unexpected results. 

Done in console:
```
scala> val a1 = Array('1', '2', '3', '4', '5', '6', '7')
a1: Array[Char] = Array(1, 2, 3, 4, 5, 6, 7)

scala> val res1 = a1.mkString(" ")
res1: String = 1 2 3 5

scala> val res2 = a1.mkString("")
res2: String = 1234567
```

**Comment by som-snytt** [comment]
Workaround:
```
scala> val xs = Array('1', '2', '3', '4', '5', '6', '7')
xs: Array[Char] = Array(1, 2, 3, 4, 5, 6, 7)

scala> xs.iterator.mkString(" ")
res0: String = 1 2 3 4 5 6 7
```
I thought it was going to be a Monday crossword, but now I must go chauffeur the child.

**Comment by NthPortal** [comment]
that's super weird

**Comment by NthPortal** [comment]
why is 4 missing??

**Comment by NthPortal** [comment]
override def addString(sb: StringBuilder, start: String, sep: String, end: String): StringBuilder = {
      val jsb = sb.underlying
      if (start.length != 0) jsb.append(start)
      val len = array.length
      if (len != 0) {
        if (sep.isEmpty) jsb.append(array)
        else {
          jsb.ensureCapacity(jsb.length + len + end.length + (len - 1) * sep.length)
          jsb.append(array(0))
          var i = 1
          while (i < len) {
            jsb.append(sep)
            jsb.append(array(i))
            i += i // <<<--- this should be += 1
          }
        }
      }
      if (end.length != 0) jsb.append(end)
      sb
    }

**Comment by SethTisue** [comment]
@Ichoran opportunity to add coverage in scala-collection-laws?

**Comment by som-snytt** [comment]
A good use case for `0d1` or `i"1"` as a declaration of intent.

With off-by-one perils at every turn, public enemy number one (`1`) could be better addressed.

`i.inc` and `i.dec` seems like obvious syntax.

Also, with this ticket, we can now speak of off-by-`i - 1` bugs.

**Comment by Ichoran** [comment]
@SethTisue - I didn't write collection-laws to abstract over element type very easily.  I think for custom array implementations a standard unit test framework would be better.
