### ISSUE TITLE
Single-line docs disappear when permalinked

### ISSUE THREAD

**Issue by szeiger** [scala/bug#11586]
Single-line comments such as https://github.com/sbt/sbt-sdlc/blob/4b27e22299fe873ded8d451fe6d3ac3995a55ab7/src/sbt-test/sdlc/simple/src/main/scala/com/example/Main.scala#L4 cannot be toggle-expanded in scaladoc 2.12+ sites. They always show the single overview line.

When using the permalink to such a method (`com/example/Main.html#foo(x:Int):Int` in this case) this line disappears entirely, leaving only the signature. Clicking on it does not toggle the line. The only way to get it back is to remove the link fragment.

Tested with Scaladoc 2.12.8 and 2.13.0.

**Comment by lrytz** [comment]
Fixed in https://github.com/scala/scala/pull/8256
