### ISSUE TITLE
Map.values.map is not strict in Scala 2.13

### ISSUE THREAD

**Issue by ijuma** [scala/bug#11589]
I am not sure if this is intentional, but I didn't see any mention of it in the migration notes. `mutable.Map.values.map` is not strict in 2.13 which can cause side-effects to be executed multiple times when compared to 2.12 and older.

A simple example follows with 2.12.8 and then 2.13.0:

> Welcome to Scala 2.12.8 (OpenJDK 64-Bit Server VM, Java 11.0.2).
> Type in expressions for evaluation. Or try :help.
> scala> scala.collection.mutable.Map(1 -> "1", 2 -> "2")
> res0: scala.collection.mutable.Map[Int,String] = Map(2 -> 2, 1 -> 1)
> 
> scala> var iterationCounter = 0
> iterationCounter: Int = 0
> 
> scala> res0.values.map { v => iterationCounter += 1; v }
> res1: Iterable[String] = List(2, 1)
> 
> scala> res1.toSeq
> res2: Seq[String] = List(2, 1)
> 
> scala> iterationCounter
> res3: Int = 2
> 
> scala> res1.toSeq
> res4: Seq[String] = List(2, 1)
> 
> scala> iterationCounter
> res5: Int = 2

scala> scala.collection.mutable.Map(1 -> "1", 2 -> "2")
res0: scala.collection.mutable.Map[Int,String] = HashMap(1 -> 1, 2 -> 2)

> Welcome to Scala 2.13.0 (OpenJDK 64-Bit Server VM, Java 11.0.2).
> Type in expressions for evaluation. Or try :help.
> 
> scala> var iterationCounter = 0
> iterationCounter: Int = 0
> 
> scala> res0.values.map { v => iterationCounter += 1; v }
> res1: Iterable[String] = View(<not computed>)
> 
> scala> res1.toSeq
> res2: Seq[String] = List(1, 2)
> 
> scala> iterationCounter
> res3: Int = 2
> 
> scala> res1.toSeq
> res4: Seq[String] = List(1, 2)
> 
> scala> iterationCounter
> res5: Int = 4

**Comment by NthPortal** [comment]
is there a reason for `Map#values` not returning `View` rather than `Iterable`?

**Comment by julienrf** [comment]
Not that I know. It should return a strict Iterable
