### ISSUE TITLE
Non-Iterators have iterator reuse warnings in scaladoc

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/bug#11595]
For example, the documentation of `Vector#map` has

> Note
> Reuse: After calling this method, one should discard the iterator it was called on, and use only the iterator that was returned. Using the old iterator is undefined, subject to change, and may result in changes to the new iterator as well.

at https://scala-lang.org/files/archive/api/2.13.0/scala/collection/immutable/Vector.html#map[B](f:A=%3EB):CC[B]

**Comment by Philippus** [comment]
sounds similar to https://github.com/scala/scala/pull/8007
