### ISSUE TITLE
TreeSet min is not O(logn) in Scala 2.12

### ISSUE THREAD

**Issue by LFilips** [scala/bug#11598]
The TreeSet min implementation is not O(logn) as stated in the performance chart: https://docs.scala-lang.org/overviews/collections/performance-characteristics.html

The TreeSet min function is using the default min from TraversableOnce and that is O(n), it should be overridden and use the .firstKey method instead that is O(logn).

You can reproduce the comparison between List() and TreeSet()min time with this class: https://github.com/LFilips/jhm-test/blob/master/src/main/scala/com/filipponi/jmh/CalculateMin.scala using jmh. To run this use: ./runBench.sh CalculateMin.

This are the result on my machine:
```
[info] Benchmark                            Mode  Cnt        Score        Error  Units
[info] CalculateMin.listMin                 avgt   10  1022412.455 ± 292576.347  ns/op
[info] CalculateMin.treeSetMin              avgt   10  2987347.801 ± 392704.380  ns/op
[info] CalculateMin.treeSetMinWithFirstKey  avgt   10       11.695 ±      0.062  ns/op
```

I'm using java:
```
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
```

**Comment by plokhotnyuk** [comment]
It can happen that TreeSet is ordered by different function than default one, so it cannot be easily fixed by overriding of `min`.

At least, it should be clearly defined in ScalaDocs and in the performance section of the documentation site that `firstKey` should be used for `O(log(n))`, not `min`.

**Comment by NthPortal** [comment]
@LFilips `scala.collection.SortedSet` defines `min` to check if you're using the same (or reverse) `Ordering` as is used to define the set; if so, it shortcuts to `head` (or `last`).
If that's not happening, it's definitely a bug.

**Comment by NthPortal** [comment]
it's worth adding a footnote that `min` is only `O(log n)` if using the same `Ordering` as the set/map (or the reverse)

**Comment by xuwei-k** [comment]
I think Scala 2.12.8 `immutable.TreeSet#min` use `TraversableOnce` implementation. 😢 

https://github.com/scala/scala/blob/v2.12.8/src/library/scala/collection/TraversableOnce.scala#L223-L228


```
Welcome to Scala 2.12.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_201).
Type in expressions for evaluation. Or try :help.

scala> {val z = (1 to 10000000).to[scala.collection.immutable.TreeSet] ; val s = System.nanoTime ; val x = z.min ; println(System.nanoTime - s) ; x }
108943811
res0: Int = 1
```

```
Welcome to Scala 2.13.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_201).
Type in expressions for evaluation. Or try :help.

scala> {val z = (1 to 10000000).to(scala.collection.immutable.TreeSet) ; val s = System.nanoTime ; val x = z.min ; println(System.nanoTime - s) ; x }
44361
res0: Int = 1
```

**Comment by LFilips** [comment]
@NthPortal i've missed the fact that was related to a specific scala version 😄 (I was using scala 2.12.8). As @xuwei-k said defaults to the traversableOnce implementation.
Can you explain this sentence "it's worth adding a footnote that min is only O(log n) if using the same Ordering as the set/map (or the reverse)"?
Looking at the snipped that you've sent if the ordering is the same gets the head, otherwise the tail (if is a redBlackTree i can imagine going on the leftmost leaf or the rightmost leaf?) Can you give me an example of the situation when you can use a different ordering?

**Comment by NthPortal** [comment]
@LFilips `TreeSet(1, 2, 3).min(Integer.compare)` uses an `Ordering` which is not the same or the reverse of the one used to build the `TreeSet`

**Comment by xuwei-k** [comment]
https://github.com/scala/scala/pull/8204
