### ISSUE TITLE
jQuery vulnerability in scala-lang.org

### ISSUE THREAD

**Issue by exoego** [scala/bug#11594]
White working on #11567 (vulnerability in ScalaDoc), I found HTML templates for scala-lang.org also uses [jQuery.js 2.1.3 that is considered vulnerable](https://snyk.io/test/npm/jquery/2.1.3).

Use-site
https://github.com/scala/scala/blob/a37e40399b65554241ee0f4276a915b3d0f723f9/spec/_layouts/toc.yml#L9

I suggest to migrate to jQuery 3 (as planed so in #11567).

**Comment by eed3si9n** [comment]
Here's my PR - https://github.com/scala/scala/pull/8250

**Comment by exoego** [comment]
Closing since addressed in https://github.com/scala/scala/pull/8250
