### ISSUE TITLE
Scala 2.12 -> 2.13 regression in implicit precedence

### ISSUE THREAD

**Issue by oxbowlakes** [scala/bug#11596]
The following code compiles under scala 2.12.8 but not under scala 2.13.0 (it fails with ambiguous implicit warnings)
```
package object foo {
  import scala.language.higherKinds
  class Functor[X[_]]
  trait Monad[F[_]] extends Functor[F]

  class OptionT[M[_], A]
  trait OptionTInstances2 {
    implicit def optionTMonad[M[_]]: Monad[({ type l[a] = OptionT[M, a] })#l] = ???
  }

  trait OptionTInstances1 extends OptionTInstances2 {
    implicit def optionTFunctor[M[_]]: Functor[({ type l[a] = OptionT[M, a] })#l] = ???
  }

  object OptionT extends OptionTInstances1

  object Main extends App {
    implicitly[Functor[({type l[a] = OptionT[Option, a]})#l]]
  }
}
```

**Comment by som-snytt** [comment]
I see 2.12 doesn't even look at the monad implicit, so it may have progressed with fixes to "implicit shadowing" (just a guess) or maybe pruning strategy.

I'm actually not able to view the spec right now, for some internet reason. That's a reason to finally get a PDF version again. I know someone worked on that recently. (Edit: it loaded after several minutes. Cloudflare?)

If both methods are in scope, ordinary static overload resolution applies. IIRC "defined in a subclass" is a tie-breaker?

Just to add, it was an opportunity to compare option names:
```
~/scala-2.12.8/bin/scalac -Xdev -Ydebug -Ytyper-debug -Xprint:typer owbox.scala
scalac -Xdev -Vimplicits -Vdebug -Vtyper -Vprint:typer owbox.scala
```
I do like how the `V`s align. `V` means I'm asking for more info, hopefully without changing behavior (although forcing typechecking can side effect).

Also apologies to oxbowlakes for mistyping owbox. From the crossword, I recently learned ["sin bin"](https://en.wikipedia.org/wiki/Penalty_box), so for issues I hereby propose "ow box".

**Comment by joroKr21** [comment]
That's intentional. See scala/scala#6123 and scala/scala#6441

There is a natural prioritization because `Monad extends Functor`. Placing the functor instance in a subclass evens the odds so to speak. The solution is to swap places when you want to cross compile or just remove the boilerplate for 2.13.+

**Comment by som-snytt** [comment]
Thanks @joroKr21 ! "Aha!"

**Comment by xuwei-k** [comment]
https://github.com/scala/bug/issues/11068

**Comment by som-snytt** [comment]
@xuwei-k "Ach! Akka!"
