### ISSUE TITLE
Compiler allows to assign invalid values to literal type variables

### ISSUE THREAD

**Issue by plokhotnyuk** [scala/bug#11602]
```
$ /opt/scala-2.13.0/bin/scala
Welcome to Scala 2.13.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_212).
Type in expressions for evaluation. Or try :help.

scala> var x: true = true
x: true = true

scala> x = false
           ^
       error: type mismatch;
        found   : Boolean(false)
        required: true

scala> x = null.asInstanceOf[true]
mutated x

scala> x
res0: Boolean = false
```

**Comment by dwijnand** [comment]
I seem to remember from a SIP meeting maybe a year ago(?) that, basically, once you use `asInstanceOf` you're taking over from the compiler, so you can't then blame the compiler for unsoundness.

**Comment by lrytz** [comment]
There's also

```
scala> class C { val x: 1 = x }
                            ^
       warning: value x in class C does nothing other than call itself recursively
defined class C

scala> (new C).x
res0: Int = 0
```

See https://github.com/scala/scala/pull/5310#issuecomment-346876424 for prior discussion.

**Comment by plokhotnyuk** [comment]
But:
```
scala> x.isInstanceOf[true]
res1: Boolean = true

scala> x.isInstanceOf[false]
res2: Boolean = false
```

**Comment by plokhotnyuk** [comment]
@lrytz Why it was closed so fast? 

Current implementation doesn't follow the SIP-23, where it is stated: 
```
(1: Any).isInstanceOf[1]           // result is true
(1: Any).asInstanceOf[1]           // result is 1: 1
(1: Any).asInstanceOf[2]           // ClassCastException
```

But in the Scala 2.13.0 REPL:
```
scala> (1: Any).asInstanceOf[2]
res0: Int = 1
```

**Comment by dwijnand** [comment]
Well, those two things should definitely match, you're right.

However, I think it's probably the SIP document that should be updated.  (Btw, it's likely what I remembered was from the SIP meeting on literal types... 😄)

@milessabin could you confirm that, please?  Also, could you update the document?  Otherwise, I could give it a shot and seek your review.

**Comment by milessabin** [comment]
Yes, the decision was that the SIP document should be updated.

**Comment by sjrd** [comment]
Yes, your assessment is correct, @dwijnand. `asInstanceOf[A]` is defined as "dear compiler, *believe me*, this is an `A`; please accept that, and insert in the generated code just enough code for the underlying runtime to not give a `ValidationError`".

`isInstanceOf` provides way more guarantees. It is *stronger* than `asInstanceOf`.

You have a guarantee that *if* `x.isInstanceOf[A]` returns true, *then* `x.asInstanceOf[A]` succeeds. But not the other way around.

**Comment by milessabin** [comment]
@dwijnand happy to review if you want to take a stab at updating the document.

**Comment by dwijnand** [comment]
https://github.com/scala/docs.scala-lang/pull/1418
