### ISSUE TITLE
2.13.0: ArrayStoreException in Vector.updated

### ISSUE THREAD

**Issue by rjmac** [scala/bug#11600]
This may be an instance of #7268 as it does not happen if the vector is not constructed via `Vector.apply`, but this particular manifestation is new in 2.13:
```scala
abstract class Base
class Derived1 extends Base
class Derived2 extends Base
val x = Vector(new Derived1)
x.updated(0, new Derived2) // exception in Vector.updateAt
```
If it matters, the JVM is openjdk 1.8.0_212

**Comment by NthPortal** [comment]
I believe the offending line is https://github.com/scala/scala/blob/26f34d022b9fc6af4a7231fd6bfc2e88a783de6d/src/library/scala/collection/immutable/Vector.scala#L33

it checks `isInstanceOf[Array[AnyRef]]`, but forgets that `Array`s are covariant at the JVM level. probably need a `getClass` check or something?

**Comment by SethTisue** [comment]
#11600 should be fixed at the same time as this one
