### ISSUE TITLE
2.13.0: mutable.HashSet.addAll processes parameter twice

### ISSUE THREAD

**Issue by miteshaghera** [scala/bug#11601]
`addAll` method of `mutable.HashSet` will process parameter twice if it's not a `mutable.HashSet` or `immutable.HashSet`. It potentially can cause duplicate elements in collection. 

Please refer following testing code.

    import java.util
    import scala.jdk.CollectionConverters._

    object HashSet {
      def main(args: Array[String]): Unit = {
        val jhs = new util.HashSet[Obj]()
        jhs.add(new Obj("A"))
        jhs.add(new Obj("B"))
        val shs = jhs.asScala.map(x => new Obj2(x.f))
        println("java set: " + jhs.size)
        println("scala set: " + shs.size)
      }
    }

    class Obj(val f:String) {
    }

    class Obj2(val f:String) {
    }

It will not cause a problem if proper `hashCode` and `equals` are present in `Obj2`.

**Comment by sjrd** [comment]
Indeed. This line is redundant and causes the issue. It shouldn't be there:
https://github.com/scala/scala/blob/e89bdde12d43cb80dfab75d203e3d34a65587014/src/library/scala/collection/mutable/HashSet.scala#L102

**Comment by som-snytt** [comment]
This report is partially duplicated by https://github.com/scala/bug/issues/11976 the fix for which fixes the reported example and the indirect test, but not the direct test. (I had to reproduce it for a different issue.)
