### ISSUE TITLE
Type-inference issue with HKT-members

### ISSUE THREAD

**Issue by ryan-williams** [scala/bug#11619]
[scalafiddle](https://scalafiddle.io/sf/8J50apv/3); repros in 2.12.8 and 2.13.0.

```scala
sealed trait A[+T]
 case class A1[+T](t: T) extends A[T]

sealed trait            B[+T] { type AA[+U] <: A[U] }
type Aux[+_A[+U], +T] = B[ T] { type AA[+U] = _A[U] } 

val b: Aux[A1, Int] = ???
(   b: Aux[A1, Int]): Aux[A, Int]
    b               : Aux[A, Int]  // 🚫
```

```
ScalaFiddle.scala:9: error: type mismatch;
 found   : ScalaFiddle.this.B[scala.this.Int]{type AA[+U] = ScalaFiddle.this.A1[U]}
 required: ScalaFiddle.this.Aux[ScalaFiddle.this.A,scala.this.Int]
    (which expands to)  ScalaFiddle.this.B[scala.this.Int]{type AA[+U] = ScalaFiddle.this.A[U]}
      b               : Aux[A, Int]  // 🚫
      ^
```

Redundantly casting `b: Aux[A1, Int]` is required for the subsequent cast to `Aux[A, Int]` to compile.

Changing the `Aux` alias to use `<:` instead of `=` lets it compile:

```scala
type Aux[+_A[+U], +T] = B[ T] { type AA[+U] <: _A[U] } 
```

Seems like the first way should work, though.

**Comment by joroKr21** [comment]
If we comment out the last line we get this:
```scala
type Aux[+_A[+U], +T] = B[ T] { type AA[+U] = _A[U] }
     ^
<pastie>:5: error: covariant type _A occurs in invariant position in type [+_A[+U], +T]B[T]{type +AA[+U] = _A[U]} of type Aux
```

I'm not sure if type comparison should work if the variance is not right.
I guess the real issue is that variance checks come after typechecking and so the true error is hidden.
But I don't think we can do anything about that.

**Comment by ryan-williams** [comment]
Interesting, the failing line I annotated was masking a different failure. 

It seems like this whole issue is a red herring then, so I'll close; please re-open if there's still something here I'm missing.

Thanks @joroKr21!
