### ISSUE TITLE
No compiling error when code is not tailrec

### ISSUE THREAD

**Issue by He-Pin** [scala/bug#11612]
```scala
import scala.annotation.tailrec

object Test  extends App {

  println(methodA(1,false))

  @tailrec
  def methodA(input: Int,condition:Boolean): Int = {
    if (condition)
      methodA(input + 2, condition)
    else
      methodB(input + 2, condition)
  }

  @tailrec
  def methodB(input: Int,condition:Boolean): Int = {
    if (condition)
      methodB(input + 3, condition)
    else
      methodA(input + 3, condition)
  }
}
```
should not compile

**Comment by NthPortal** [comment]
`@tailrec` only requires that there exists at least one call to itself, and that all calls to itself are in tail position

**Comment by som-snytt** [comment]
That's a good one. Is there something useful to lint, short of analyzing the world? Often the terminating case is something simple like `Nil` or `0`, but maybe that is too simple.

I was going to try something out, but got distracted by other things that made no sense to me.

**Comment by SethTisue** [comment]
I think this is working as designed and the possibility of improving it seems rather speculative to me.

**Comment by som-snytt** [comment]
Score another one for codetriage.
