### ISSUE TITLE
[2.13.0] parallel collections rely upon missing classes/traits at runtime

### ISSUE THREAD

**Issue by gilreathjw** [scala/bug#11616]
When attempting to perform arbitrary operations at runtime with a ParRange, I get multiple runtime errors:

```
Error:(29, 27) Symbol 'type scala.collection.generic.GenericTraversableTemplate' is missing from the classpath.
This symbol is required by 'trait scala.collection.generic.GenericParTemplate'.
Make sure that type GenericTraversableTemplate is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
A full rebuild may help if 'GenericParTemplate.class' was compiled against an incompatible version of scala.collection.generic.
    ParRange(0, Width, 1, true).foreach(x => {
```

Also missing are:

'type scala.collection.GenIterableLike'
'type scala.collection.Parallel'
'type scala.collection.GenSeqLike'
'type scala.Immutable'

I am using 2.13.0 for both the language and the module in Gradle:

compile "org.scala-lang:scala-library:2.13.0"
compile "org.scala-lang.modules:scala-parallel-collections_2.13.0-M2:1.0.2"

I dive into more detail on this issue here:

https://stackoverflow.com/questions/56923286/type-scala-collection-generic-generictraversabletemplate-is-missing-from-the-c

**Comment by Jasper-M** [comment]
The `scala-parallel-collections` you are using is compiled against 2.13.0-M2. That's not binary compatible with 2.13.0.

**Comment by NthPortal** [comment]
it should work if you use `compile "org.scala-lang.modules:scala-parallel-collections_2.13:0.2.0"` instead
