### ISSUE TITLE
Warn if implicit underscore is no-op

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11618]
Please warn on:
```
implicit val _ = 42
implicitly[Int]
```

Normally, an extractor pattern would either fail or implicit is available.

```
scala> object X { def unapply(s: String) = Option(s.tail) }
defined object X

scala> val X(s) = "hello"
s: String = ello

scala> val X(_) = "hello"

scala> implicit val X(_) = "hello"

scala> implicitly[String]
                 ^
       error: could not find implicit value for parameter e: String
```
https://github.com/scala/bug/issues/10384

**Comment by som-snytt** [comment]
Oh wait, I meant to say: warn if implicit doesn't actually introduce a binding. Sorry, this isn't my day job.

**Comment by SethTisue** [comment]
This came up today — I was talking to a user who was upgrading some code from 2.12 to 2.13 and hit this. I agree that a compiler warning would be desirable here.

(The 2.13.0 release notes don't mention the change that caused it; I'm going to fix that right now.)

**Comment by som-snytt** [comment]
I didn't remember how this works, so as a refresher, the spec says that if there is one bound variable, you wind up with:
```
val x = e match { case p(x) => x }
```
Otherwise, the vars are stuck in a tupleN:
```
val xy$1 = e match { case p(x, y) => (x, y) }
val x = xy$1._1
val y = xy$1_2
```
For no vars, the result of the match is the unit value.

The modifier is only applied to the vars.

However, `C` really gets a field with a `BoxedUnit`:
```
class C { implicit val Some(_) = Option(("hi",42)) }
```
That is per spec, but probably not per expected. That's how it always worked for patterns, which now includes plain underscore.

**Comment by som-snytt** [comment]
I was looking for a good first issue. I got one, and she's a pretty good kid.

**Comment by som-snytt** [comment]
One could also warn about introducing multiple implicits of the same type? Except maybe they are shadowed at the use site:
```
implicit val P(x: T, y: T) = e
locally {
  def x = ???
  implicitly[T]  // OK
}
```
