### ISSUE TITLE
JAR for parallel collections in 2.13.0 does not work in REPL via :require

### ISSUE THREAD

**Issue by dbdahl** [scala/bug#11622]
In the Scala 2.13.0 REPL, adding the parallel collections JAR file via ":require" does not work, e.g.,

> % scala
> 
> Welcome to Scala 2.13.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_201).
> Type in expressions for evaluation. Or try :help.
>                                                          
> scala> :require scala-parallel-collections_2.13-0.2.0.jar        
> Added '/home/dahl/tmp/scala-parallel-collections_2.13-0.2.0.jar' to classpath.
>                                                        
> scala> import scala.collection.parallel.immutable
>                                ^
>        error: object parallel is not a member of package collection
> 
> scala> 

It does, however, work when the JAR is added as a command line argument.

> % scala -cp scala-parallel-collections_2.13-0.2.0.jar 
> 
> Welcome to Scala 2.13.0 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_201).
> Type in expressions for evaluation. Or try :help.
> 
> scala> import scala.collection.parallel.immutable
> import scala.collection.parallel.immutable
> 
> scala> 
> 

In my context, I am embedding the REPL in my application.  The user needs to have the ability to added arbitrary JAR files (e.g., the parallel collections library, as above).  I hope here is a good solution for this bug.  Thanks!

**Comment by som-snytt** [comment]
As a footnote, file completion doesn't work for `require`.

Perhaps related phenomenon:
```
$ scala

     ________ ___   / /  ___
    / __/ __// _ | / /  / _ |
  __\ \/ /__/ __ |/ /__/ __ |
 /____/\___/_/ |_/____/_/ | |
                          |/  version 2.13.0

scala> <foo/>
       ^
       error: To compile XML syntax, the scala.xml package must be on the classpath.
       Please see https://github.com/scala/scala-xml for details.

scala> :require scala-xml_2.13-1.2.0.jar
Added '/home/amarki/snips/scala-xml_2.13-1.2.0.jar' to classpath.

scala> <foo/>
       ^
       error: To compile XML syntax, the scala.xml package must be on the classpath.
       Please see https://github.com/scala/scala-xml for details.

scala> :quit
$ scala

     ________ ___   / /  ___
    / __/ __// _ | / /  / _ |
  __\ \/ /__/ __ |/ /__/ __ |
 /____/\___/_/ |_/____/_/ | |
                          |/  version 2.13.0

scala> :require scala-xml_2.13-1.2.0.jar
Added '/home/amarki/snips/scala-xml_2.13-1.2.0.jar' to classpath.

scala> <foo/>
res0: scala.xml.Elem = <foo/>

```

Just to confirm:
```
$ scala -cp scala-parallel-collections_2.13-0.2.0.jar

     ________ ___   / /  ___
    / __/ __// _ | / /  / _ |
  __\ \/ /__/ __ |/ /__/ __ |
 /____/\___/_/ |_/____/_/ | |
                          |/  version 2.13.0

scala> scala.collection.parallel.availableProcessors
res0: Int = 12

scala> :quit
$ scala

     ________ ___   / /  ___
    / __/ __// _ | / /  / _ |
  __\ \/ /__/ __ |/ /__/ __ |
 /____/\___/_/ |_/____/_/ | |
                          |/  version 2.13.0

scala> :require scala-parallel-collections_2.13-0.2.0.jar
Added '/home/amarki/snips/scala-parallel-collections_2.13-0.2.0.jar' to classpath.

scala> scala.collection.parallel.availableProcessors
                        ^
       error: object parallel is not a member of package collection

```
`--verbose` reports
```
scala> :require scala-parallel-collections_2.13-0.2.0.jar
[classpath updated on entries [ZipArchiveClassPath(/home/amarki/snips/scala-parallel-collections_2.13-0.2.0.jar,None)]]
[could not invalidate system packages: scala.collection]
Added '/home/amarki/snips/scala-parallel-collections_2.13-0.2.0.jar' to classpath.
```

**Comment by BattlestarSC** [comment]
I'm having the same issue with just an SBT build. 
`libraryDependencies += "org.scala-lang.modules" %% "scala-parallel-collections" % "0.2.0"`
and upon compile, with `import scala.collection.parallel.CollectionConverters._` 
Intellij reports that `object parallel is not a member of package collection` and cites that import line

**Comment by SethTisue** [comment]
@BattlestarSC I'm not able to reproduce the problem:

```
% cd issue-11622   
% echo 'libraryDependencies += "org.scala-lang.modules" %% "scala-parallel-collections" % "0.2.0"
' > build.sbt
% echo 'scalaVersion := "2.13.1"' >> build.sbt                                                   
% sbt
...
sbt:issue-11622> console
[info] Starting scala interpreter...
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 1.8.0_242).
Type in expressions for evaluation. Or try :help.

scala> import scala.collection.parallel.CollectionConverters._
import scala.collection.parallel.CollectionConverters._

scala> 
```

**Comment by BattlestarSC** [comment]
Would it be relevant that I was using a Scala worksheet? Otherwise, yes, I'd say its likely Intellij, and therefor unrelated

**Comment by SethTisue** [comment]
Likely relevant. It wouldn't surprise me if IntelliJ's worksheet support uses some of the same code the REPL uses.

Additional confirmation would be if IntelliJ is logging the same “could not invalidate system packages: scala.collection" message somewhere.

**Comment by som-snytt** [comment]
The REPL feature intentionally does not reload `scala` packages. In particular, parallel-collections includes classes in `scala.collection` and subpackages.

The workaround is
```
:replay -cp scala-parallel-collections_2.13-1.0.4.jar
```
