### ISSUE TITLE
StringLike gone, but vestiges remain

### ISSUE THREAD

**Issue by mslinn** [scala/bug#11623]
Searching through the Scala source, I see a few references to `StringLike`, but the `scala.collection.immutable.StringLike` trait is no more. Looks like it got subsumed into `scala.collection.StringOps`.
```
$ git grep StringLike
spec/01-lexical-syntax.md:> [scala.collection.immutable.StringLike](http://www.scala-lang.org/api/current/#scala.collection.immutable.StringLike). spec/01-lexical-syntax.md:> `StringLike`, the method is applicable to all strings.
test/files/pos/overloaded_ho_fun.scala:class StringLike(xs: String) {
test/files/pos/overloaded_ho_fun.scala:  val sl = new StringLike("a")
test/junit/scala/collection/immutable/StringLikeTest.scala:class StringLikeTest {
```

**Comment by som-snytt** [comment]
The spec example should be removed, as it's just an example of the library and not syntax.

Maybe it could stay in the late chapter on the library, but probably not even that; that chapter is for more fundamental library concepts and it is probably also out of date again.
