### ISSUE TITLE
List.toIterable method change behavior in Scala 2.13

### ISSUE THREAD

**Issue by FabioPinheiro** [scala/bug#11638]
I think the List method toIterable have the wrong type in Scala 2.13
It return a List instead of a Iterable
https://www.scala-lang.org/api/current/scala/collection/immutable/List.html#toIterable:Iterable.this.type

```
Welcome to Scala 2.12.8-20190113-111201-unknown (OpenJDK 64-Bit Server VM, Java 1.8.0_222).
scala> List(1,2,3).toIterable
res0: Iterable[Int] = List(1, 2, 3)
```

```
Welcome to Scala 2.13.0-20190613-143643-unknown (OpenJDK 64-Bit Server VM, Java 1.8.0_222).
scala> List(1,2,3).toIterable
res0: List[Int] = List(1, 2, 3)
```

```
Starting dotty (0.12.0-1) REPL...
scala> List(1,2,3).toIterable                                                                                         
val res0: Iterable[Int] = List(1, 2, 3)
```

**Comment by julienrf** [comment]
Is it really a problem?

**Comment by dwijnand** [comment]
A List is an Iterable.  So I also don't see why it returning List presents a problem.

**Comment by FabioPinheiro** [comment]
Yes but the type return by the toIterable should be a Iterable
Yes List is a Iterable and is still correct but I think the compiler cannot infer in certain conditions.

I asked the question also on gitter https://gitter.im/scala/scala?at=5d2f3cb0eab6cd7763861909
And after some discussion I will replaced toIterable for `to(Iterable)` intended of forcing the type

**Comment by dwijnand** [comment]
> but I think the compiler cannot infer in certain conditions

I think we would need better clarification on what you mean here, in order to agree that the current behaviour is problematic.

**Comment by FabioPinheiro** [comment]
So everything seems right. But from the migration guide I was not expecting this behavior change. https://docs.scala-lang.org/overviews/core/collections-migration-213.html

The following example is where my confusion started:
```
import cats.data._, cats.implicits._ //cats "org.typelevel" %% "cats-core" % "2.0.0-M4"
import scala.concurrent.ExecutionContext.Implicits.global

import scala.concurrent.Future

object Test extends App {
  val ret = for{
    a <- EitherT[Future, Iterable[Int], Int](Future(Left(Iterable(1,2,3))))
    //b <- IorT.fromIor[Future](Ior.Left(List(1,2,3)): Ior[List[Int], Int]).toEither.leftMap(_.to(Iterable))
    // this is ok

    b <- IorT.fromIor[Future](Ior.Left(List(1,2,3)): Ior[List[Int], Int]).toEither.leftMap(_.toIterable)
    // This does not compile:
    //  [error] /home/fabio/workspace/scala213test/src/main/scala/Test.scala:8:7: type mismatch;
    //  [error]  found   : Int => cats.data.EitherT[scala.concurrent.Future,List[Int],Int]
    //  [error]  required: Int => cats.data.EitherT[scala.concurrent.Future,Iterable[Int],Int]
    //  [error]     a <- EitherT[Future, Iterable[Int], Int](Future(Left(Iterable(1,2,3))))
    //  [error]       ^
    //  [error] one error found

  } yield b
}
```
When I read the error I see that I have a `List[_]` and I need a `Iterable[_]`.
List[A] implements also a Iterable[A]. So I thought that this was that the compiler fail to infer the correct type for `b`.
So calling toIterable makes sense from the documentation. In the List documentation I see on the method toIterable "return This collection as an Iterable[A]. ..."
This fix the problem for 2.12. But Scala 2.13 have a different behavior from the others Scala  versions including dotty

I always get a bit confused about covariant/invariant/contravariant. @dwijnand maybe you can clarify me something.
Is this directly related with covariant/invariant/contravariant of the type mathematically speaking?
I mean in the perfect world the compiler should be able to infer to type of `b` with the Iterable because it needs for the out side flapMap of `a`.
Or is because of `List[Int] <: Iterable[Int], but class EitherT is invariant in type A.`?

**Comment by dwijnand** [comment]
> is because of `List[Int] <: Iterable[Int], but class EitherT is invariant in type A.`?

That's right!

Rather than `leftMap(_.toIterable)` and `leftMap(_.to(Iterable))` I suggest you simply `leftMap(_: Iterable[Int])`

**Comment by FabioPinheiro** [comment]
Like also to mention @tpolecat suggestion `.leftWiden[Iterable[Int]]` 
`def leftWiden[A, B, AA >: A](fab: F[A, B]): F[AA, B] = fab.asInstanceOf[F[AA, B]]`
Seems to be a limitation on the EitherT of cats: https://github.com/typelevel/cats/issues/2310

I still not 100% convinced about the documentation (the part about the return)
https://www.scala-lang.org/api/current/scala/collection/immutable/List.html#toIterable:Iterable.this.type

I'm going to go to close this ticket. 
Thanks for all the help.

**Comment by dwijnand** [comment]
TIL `leftWiden`, looks like it exists for these exact situations.

If you have any suggestions for how to fix the docs, then I'd be happy to take them - perhaps there's a better way to explain the intended behaviour.

**Comment by Jasper-M** [comment]
Why does this method even exist / is this method not deprecated? It only exists on `Iterable` and returns itself by definition.

**Comment by julienrf** [comment]
I’m surprised it is not defined in `IterableOnceOps`, which contains operations shared by both `Iterator` and `Iterable`. Maybe @szeiger knows why?

**Comment by Jasper-M** [comment]
Actually it's specifically defined as a deprecated extension method for `IterableOnce`.

**Comment by julienrf** [comment]
That one is expected, `IterableOnce` does not extend `IterableOnceOps`.

**Comment by szeiger** [comment]
As @Jasper-M commented, having `toIterable` on `Iterable` doesn't make sense, `IterableOnce` doesn't get any of these methods in 2.13 and `IterableOnceOps` is a utility for sharing common code between `Iterable` and Iterator`. The only place where the method still makes sense is on `Iterator`.
