### ISSUE TITLE
Spurious unused warnings on implicit not found

### ISSUE THREAD

**Issue by nrinaudo** [scala/bug#11643]
# Steps to reproduce

Have a build configured as follows:
```scala
scalaVersion := "2.12.8"
scalacOptions ++= List("-Xfatal-warnings", "-Ywarn-unused:params")
```

And a source file:
```scala
object Main {
  def foo(implicit i: Int): Int = i
  def bar(i: Int): Int = i + foo
}
```

# Expected behaviour
Compilation fails with:
```
[error] /path/src/main/scala/Test.scala:3:30: could not find implicit value for parameter i: Int
[error]   def bar(i: Int): Int = i + foo
[error]                              ^
[error] one error found
```
# Observed behaviour
Compilation fails with:
```
[error] /path/src/main/scala/Test.scala:3:30: could not find implicit value for parameter i: Int
[error]   def bar(i: Int): Int = i + foo
[error]                              ^
[error] /path/src/main/scala/Test.scala:3:11: parameter value i in method bar is never used
[error]   def bar(i: Int): Int = i + foo
[error]           ^
[error] two errors found
```

That second error seems spurious - `i` *is* used.

# Notes
This example is minimised, but I've seen up to 20 spurious errors for 1 missing implicit - not a showstopper, but it's certainly painful to sort through the noise to find the interesting error message.

**Comment by som-snytt** [comment]
The diagnostic would halt at an erroneous tree. Now it continues to inspect the tree, but doesn't register new definitions; it only looks for new usages.

**Comment by som-snytt** [comment]
> it's certainly painful to sort through the noise to find the interesting error message.

The alternative fix would be just to make the other error messages more interesting.

:tada: `/path/src/main/scala/Test.scala:3:30: could not find implicit value for parameter i: Int`
