### ISSUE TITLE
false positive "unreachable code" in pattern match

### ISSUE THREAD

**Issue by msiegenthaler** [scala/bug#11649]
The following code gives 
```
[warn]       unreachable code
[warn]       L9:  case Box() => Left(1)
```

when compiled with scala 2.12.8

```scala
sealed trait Command { type Err }
final case class Kick() extends Command { type Err = String }
final case class Box() extends Command { type Err = Int }
def handle[E](cmd: Command {type Err = E}): Either[E, Unit] = cmd match {
  case Kick() => Left("a")
  case Box() => Left(1)
}
```

The code works as expected, covering both cases, but the compiler emits the false warning. Might be related to #10251, but I'm not sure and the code is a bit simpler, so it might help you tracking it down.

**Comment by SethTisue** [comment]
same in 2.13.0

**Comment by nrinaudo** [comment]
Isn't that a duplicate of #11457 ?
