### ISSUE TITLE
-Xsource:2.14 produces warning for value classes which are wrapping case classes in Scala 2.13.0

### ISSUE THREAD

**Issue by crow-fff** [scala/bug#11657]
The following code produces a warning with `-Xsource:2.14` (and `-deprecation`) enabled for the following code:

```scala
case class Bar(x: Int)
class Foo(val bar: Bar) extends AnyVal
```

The warning is:

> Auto-application to `()` is deprecated. Supply the empty argument list `()` explicitly to invoke method hashCode, or remove the empty argument list from its definition (Java-defined methods are exempt). In Scala 3, an unapplied method like this will be eta-expanded into a function. class Foo(val bar: Bar) extends AnyVal

Seems like the inspection is called on the compiler generated code for AnyVal (and only when the contained value type is some case class) instead of the original one.

**Comment by som-snytt** [comment]
This has a fix at https://github.com/scala/scala/pull/8010

There is no issue mentioned there, and I don't remember where it came up, probably gitter.

**Comment by crow-fff** [comment]
I have another point too. Why are all those checks called on the generated code?
Is there any way to move them before this phase?
I'm not familiar with the compiler codebase, but if you give me some directions, I can try to figure out how to do it.

**Comment by som-snytt** [comment]
The spurious warning was due to normal typechecking of synthetic code that is generated by the compiler. I think it falls under, What's good for the goose is good for the gander. Consider macros, which are typechecked both before and after expansion.

**Comment by crow-fff** [comment]
> What's good for the goose is good for the gander.

The usage of macros is controlled by user, while a compiler's synthetic code appears out of regular language constructs, and I don't understand why a user should see warnings about this code if there are any.

**Comment by eed3si9n** [comment]
I'm on team goose-gander as well.

I think nice that the typechecking or whatever the feature is following the same logic for synthetically generated code. Of course, from the language user's point of view, it's _not nice_ that there's a warning at all, but if there were magical situation where some generated code skipped through the safety rules, I think it would be in a different level of not-niceness when things fail.

We can't always predict these feature interactions, but here we are with two fix PRs.
