### ISSUE TITLE
Scala 2.13 Iterator .take() method converts dropped values into null

### ISSUE THREAD

**Issue by Bloznelis** [scala/bug#11658]
```
val it = Iterator(1,2,3,4,5)
val slice = it.take(2).toVector

slice: scala.collection.immutable.Vector[Int] = Vector(1, 2, null, null, null)
```
This is problematic i.e. for calling `.size` afterwards
```
val it = Iterator(1,2,3,4,5)
val sliceSize = it.take(2).size

sliceSize: Int = 5
```

**Comment by eed3si9n** [comment]
@Bloznelis Thanks for the report! This looks like a bug.

**Comment by Jasper-M** [comment]
In the same vein:

```
scala> Iterator(1,2,3,4,5).take(2).toBuffer
java.util.NoSuchElementException: next on empty iterator
  at scala.collection.Iterator$$anon$19.next(Iterator.scala:893)
  at scala.collection.Iterator$$anon$19.next(Iterator.scala:891)
  at scala.collection.IndexedSeqView$IndexedSeqViewIterator.next(IndexedSeqView.scala:61)
  at scala.collection.mutable.ArrayBuffer$.from(ArrayBuffer.scala:264)
  at scala.collection.mutable.ArrayBuffer$.from(ArrayBuffer.scala:255)
  at scala.collection.SeqFactory$Delegate.from(Factory.scala:307)
  at scala.collection.IterableOnceOps.toBuffer(IterableOnce.scala:1276)
  at scala.collection.IterableOnceOps.toBuffer$(IterableOnce.scala:1276)
  at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1196)
  ... 36 elided
```

**Comment by Jasper-M** [comment]
I'll take this one.

**Comment by szeiger** [comment]
```
scala> collection.immutable.ArraySeq(1,2,3,4,5).view.iterator.take(2).knownSize
res12: Int = 5

scala> collection.immutable.ArraySeq(1,2,3,4,5).view.iterator.getClass.getName
res13: String = scala.collection.IndexedSeqView$IndexedSeqViewIterator
```

So `IndexedSeqViewIterator` is the culprit. Maybe even worse than the bug in `IndexedSeqViewIterator`: Why are we using it at all for `ArraySeq` when we have all the nice, efficient, specialized implementations in `ArrayOps.ArrayIterator`? All specialized `ArraySeq` implementations should override `iterator` to create the correct `ArrayIterator`.

**Comment by Jasper-M** [comment]
> Why are we using it at all for ArraySeq when we have all the nice, efficient, specialized implementations in ArrayOps.ArrayIterator? All specialized ArraySeq implementations should override iterator to create the correct ArrayIterator.

I think that this optimization would require changing the location and/or visibility of `ArrayIterator` which is likely to be binary incompatible.

**Comment by szeiger** [comment]
Making the classes package-private should be OK. It's no different than adding new package-private features like in https://github.com/scala/scala/pull/8269#issuecomment-517272349

**Comment by Jasper-M** [comment]
> Making the classes package-private should be OK. It's no different than adding new package-private features like in scala/scala#8269 (comment)

On second thought you could just call `unsafeArray.iterator` I guess.

**Comment by Jasper-M** [comment]
I suggest making a separate issue for the optimization part. I think there's some more things that can be done here, such as implementing `knownSize` in `ArrayIterator` and `SliceIterator`.

**Comment by szeiger** [comment]
Going through `ArrayOps.iterator` makes the type-check at runtime even though `ArraySeq` is specialized so you already know the type. (Still much better than the current IndexedSeqView implementation I suppose).

`ArrayIterator` not defining `knownSize` looks like another oversight.

Then there's the matter of `stepper` where a specialized implementation is even more important `Iterator` always has to box, you only get the more efficient array operations that don't have to go through `ScalaRunTime`, but `Stepper` can give you unboxed access.

**Comment by szeiger** [comment]
Fixed by https://github.com/scala/scala/pull/8299
