### ISSUE TITLE
Problem detecting java varargs

### ISSUE THREAD

**Issue by OopsieWoopsie** [scala/bug#11652]
When trying to pass a varargs parameter to a Java class Scala IDE says:
> type mismatch; found : Seq[String] required: String

```java
public class Test {

    public static void test(String... args) {
    }
}
```

```scala
object Foo {

  def bar(args: String*): Unit = {
    Test.test(args) // < error
  }
}
```

**Using:**
Scala IDE 4.7.0 (4.7.0-vfinal-2017-09-29T14:34:02Z-Typesafe)
The Scala version of the IDE is 2.12.3

**Comment by lrytz** [comment]
Hi, plesae use https://users.scala-lang.org/ to ask questions. Thanks!

**Comment by OopsieWoopsie** [comment]
Sorry but this is not a question, I know what I'm doing.
