### ISSUE TITLE
Missing Java links in API docs for Scala 

### ISSUE THREAD

**Issue by ashawley** [scala/bug#11655]
For example, the link to "Java Streams" on this page:

https://www.scala-lang.org/api/2.13.0/scala/jdk/StreamConverters$.html

Should link to the documentation for `java.util.stream.Stream`.

Building Scala, there are a bunch of warnings when running `doc`:

```
[warn] src/library/scala/jdk/StreamConverters.scala:17:1: Could not find any member to link for "java.util.stream.Stream".
[warn] /** This object provides extension methods to create [[java.util.stream.Stream Java Streams]] that
[warn] ^
```

This could be fixed by adding some setting to sbt, see https://github.com/scala/scala-xml/pull/146

Scaladoc doesn't do the best job with generating links to entries of Javadoc, but it does ok most of the time.

**Comment by SethTisue** [comment]
perhaps we ought to be using https://github.com/ThoughtWorksInc/sbt-api-mappings ?

**Comment by ashawley** [comment]
Yes, that would also work.  That plug-in was originally meant to help with tricky situations linking to popular Scala libraries and to Scala itself, but later added Javadoc support, as well.  I don't think Scala will have any Scala dependencies to cross-reference.

I've added just the lightweight solution in https://github.com/scala/scala/pull/8284.
