### ISSUE TITLE
False positive on local var never updated.

### ISSUE THREAD

**Issue by kamilkloch** [scala/bug#11678]
Scala 2.12.9.
The following code
```scala
test("...") {
  var ts = new collection.mutable.ArrayBuffer[Long]
  val b = build {ts += a.now.toEpochMillis; a.prev}
  [...]
  assert(ts.isEmpty)
  ts.clear()
  [...]
  assert(ts === Seq(3L, 2L, 1L))
}
```
gives
```
local var ts in value <local TestSeriesBuild> is never updated: consider using immutable val
```

**Comment by hrhino** [comment]
Where's it updated? Presumably the contents of the buffer get changed, but the warning is being able to replace `var ts = ...` with `val ts = ...`; is there a reason you can't do that?

**Comment by kamilkloch** [comment]
@hrhino My bad, thanks for pointing it out. `val` works fine with `ArrayBuffer`. Thanks.

**Comment by hrhino** [comment]
No problem!
