### ISSUE TITLE
"error during expansion of this match (this is a scalac bug)" error since Scala 2.13

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#11692]
How to reproduce

```
git clone https://github.com/scalaz/scalaz-deriving.git --branch maybe-scala-compiler-bug
cd scalaz-deriving
sbt compile
```

- https://github.com/scalaz/scalaz-deriving/commit/36946459b2fbe7c6a3819484fd8d37fe0c29a6be

build log

```
[error] /home/travis/build/scalaz/scalaz-deriving/scalaz-deriving/src/main/scala/scalaz/Deriving.scala:106:35: error during expansion of this match (this is a scalac bug).
[error] The underlying error was: type mismatch;
[error]  found   : x4._1.type (with underlying type <unapply-selector>.T)
[error]  required: x1.T
[error]       (g(z1), g(z2)).zip(tcs).all {
[error]                                   ^
[error] one error found
[error] (deriving / Compile / compileIncremental) Compilation failed
```

- https://travis-ci.org/scalaz/scalaz-deriving/builds/573382149
- https://travis-ci.org/scalaz/scalaz-deriving/jobs/573382151#L1911-L1918

![travis-ci](https://user-images.githubusercontent.com/389787/63223632-be928d80-c1f3-11e9-8d94-edc53858231d.png)

compile success with Scala 2.12.8, 2.12.9 but fail with Scala 2.13.0.

(avoid `/~\.unapply` when support Scala 2.13 😢  https://github.com/scalaz/scalaz-deriving/commit/2b88b2965d2a6e3256ad67bfd70b5173f462de98#diff-da428bb5fa409a907cd8911128e9610aR106 )

**Comment by lrytz** [comment]
Is `unapplySeq` involved? https://github.com/scala/bug/issues/11102

**Comment by xuwei-k** [comment]
https://github.com/scalaz/scalaz-deriving/blob/36946459b2fbe7c6a3819484fd8d37fe0c29a6be/scalaz-deriving-base/src/main/scala/scalaz/APair.scala#L29

not `unnapplySeq` but `unapply` (with dependent type)

**Comment by lrytz** [comment]
Thanks, @xuwei-k. Did you already try to minimize it into a small self-contained source file?
