### ISSUE TITLE
Error package process DSL

### ISSUE THREAD

**Issue by gustavotemple** [scala/bug#11694]
None of these following [commands](https://www.scala-lang.org/api/current/scala/sys/process/index.html) work:

 ```scala
import sys.process._

val awk1 = "route" #| Seq("awk", "'{print $2}'")
println(awk1.!!) // Failed

val awk2 = "route" #| Seq("awk", "\'{print $2}\'")
println(awk2.!!) // Failed

val awk3 = "route" #| Seq("awk", "'{print", "$2}'")
println(awk3.!!) // Failed

val awk4 = "route" #| Seq("awk", "\'{print", "$2}\'")
println(awk4.!!) // Failed
```

And they seem ok after read this:
https://stackoverflow.com/q/21247653

**Comment by SethTisue** [comment]
is there an error message, unexpected behavior, or what?

what version of Scala are you using?

what are you claiming is in the bug in sys.process, exactly?

**Comment by gustavotemple** [comment]
Hi @SethTisue,

Sorry, I don't know where exactly is the bug, but in some way the `awk` doesn't work: 
```
scala> println(awk.!!) 
awk: cmd. line:1: '{print $2}'
awk: cmd. line:1: ^ invalid char ''' in expression
```

And I followed correctly the DSL:
https://www.scala-lang.org/api/current/scala/sys/process/index.html

My scala version:
```
scala -version
Scala code runner version 2.11.12 -- Copyright 2002-2017, LAMP/EPFL
```

**Comment by Jasper-M** [comment]
You don't need the `'`.

```
scala> ("echo foo bar" #| Seq("awk", "{print $2}")).!!
res14: String =
"bar
"
```

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org for questions
