### ISSUE TITLE
[2.13 regression] Usage of `toSeq` in some collection methods lead to unnecessary copies

### ISSUE THREAD

**Issue by smarter** [scala/bug#11708]
For example, in `indexOfSlice`:
https://github.com/scala/scala/blob/c78d75c817f86053d80d7854e8326a38a538f6cd/src/library/scala/collection/Seq.scala#L437
`toSeq` will copy anything that isn't an immutable Seq, in particular this affects Array which get implicitly wrapped into an `mutable.ArraySeq`:
```scala
Array(1, 2, 3).indexOfSlice(List(2, 3), 0)
```
With big enough collections, this copy can have a sizeable impact on runtime performance, e.g. I noticed Dotty spending a lot of time in https://github.com/lampepfl/dotty/blob/a14180f4801519d2f0b91b739929c80dc0618cc8/compiler/src/dotty/tools/dotc/ast/Trees.scala#L370

**Comment by szeiger** [comment]
The only cases I found are directly in `collection.Seq`: The aforementioned `indexOfSlice` plus its sibling `lastIndexOfSlice`, as well as potentially `CombinationsItr` and `PermutationsItr`.

This is another case where more correct type bounds would help (as attempted for `CC` in https://github.com/scala/scala/pull/7504 but we need `C` here), at least for one of the `toSeq` uses. The others should be straight-forward.
