### ISSUE TITLE
More LazyList methods’ Scaladoc should have non-termination warnings

### ISSUE THREAD

**Issue by mahesh2492** [scala/bug#11718]
I was playing with LazyList. So I just created a list and filtered out all elements which are less than 10.

  val lazyList = LazyList.from(1)
  val result = lazyList.count(_ < 10)
  println("result" + result)

There is no response from lazylist.

**Comment by martijnhoekstra** [comment]
There used to be a warning in the documentation that aggregates over
infinite sequences cant terminate. Maybe the bug is that the warning is
gone? Or am I looking in the wrong place?

**Comment by mahesh2492** [comment]
@martijnhoekstra I was checking only 10 numbers. It must work.

**Comment by martijnhoekstra** [comment]
The list doesn't know all further numbers are all >10, but discussing that
is more something for users.scala-lang.org

**Comment by som-snytt** [comment]
Unfortunately, it's not that smart.

It seems you were checking for nine numbers:

```
scala> LazyList.from(1).takeWhile(_ < 10).size
res0: Int = 9
```

Sample "may not terminate" caveat for [`Iterator.forall`](https://www.scala-lang.org/api/current/scala/collection/Iterator.html#forall(p:A=%3EBoolean):Boolean), where you must click the doc to expand it and see the hint. The warning is not applied liberally; it might be easier to annotate what is guaranteed to terminate.
