### ISSUE TITLE
Macros using type members in their signature won't compile

### ISSUE THREAD

**Issue by blackmamo** [scala/bug#11728]
Macros that attempt to use type members in their definitions fail to compile. The compiler seems unable to unify the member type in the macro def and macro impl.

```scala 
import scala.reflect.macros.whitebox.Context

trait A[T] {
  type ListType = List[T]
}

object MacrosPlus {
  // This works fine
  implicit def a[T <: A[_]]:T#ListType = macro aImpl[T]
  def aImpl[T <: A[_] : c.WeakTypeTag](c: Context): c.Expr[T#ListType] = {
    import c.universe._

    c.Expr[T#ListType](q""" ??? """)
  }
}
```

**Comment by blackmamo** [comment]
```
Error:(9, 48) macro implementation has incompatible shape:
 required: (c: scala.reflect.macros.whitebox.Context): c.Expr[List[_$1]]
 or      : (c: scala.reflect.macros.whitebox.Context): c.Tree
 found   : (c: scala.reflect.macros.whitebox.Context): c.Expr[List[_$2]]
type mismatch for return type: c.Expr[List[_$2]] does not conform to c.Expr[List[_$1]]
  implicit def a[T <: A[_]]:T#ListType = macro aImpl[T]
```

**Comment by joroKr21** [comment]
Have you tried the second suggesion (returning `c.Tree`)?

**Comment by blackmamo** [comment]
The Tree form is problematic for me in my full use case because I need to accept the macros arguments as trees as well, and I prefer types

I have actually realised there is an obvious work around:

```scala
import scala.reflect.macros.whitebox.Context

trait A[T] {
  type ListType = List[T]
}

object MacrosPlus {
  def a[T <: A[_]]:T#ListType = a[T#ListType, T] // I can use this overload as the user
  def a[LT, T <: A[LT]]:LT = macro aImpl[LT, T] // The compiler will use this version with the macro
  def aImpl[LT, T <: A[LT] : c.WeakTypeTag](c: Context): c.Expr[LT] = { // and it will match this definition
    import c.universe._

    c.Expr[LT](q""" ??? """)
  }
}
```

**Comment by blackmamo** [comment]
May have spoken too soon, that isn't working. I am pursuing it more as it will hopefully help me understand why those types won't unify

**Comment by blackmamo** [comment]
I think I understand now, member types depend on an instance, and I dont have one here to resolve it. I don't think this is a bug.

It would be nice to have a way to access the type parameters without having to repeat yourself.

Is there a different technique/ hack I could use?

**Comment by joroKr21** [comment]
Note that `c.Expr` doesn't provide any type safety, you can trivially construct one given a `c.Tree` and declare any type you want.

**Comment by SethTisue** [comment]
closing since this seems to have ended up as Q&A rather than a bug report. we can reopen if it becomes clear there's a bug involved
