### ISSUE TITLE
outer class inaccessible during initialization of inner class in Scala 2.13.0

### ISSUE THREAD

**Issue by joschua-fink** [scala/bug#11736]
```scala
trait Foo {
  trait Bar {
    println(Foo.this)
  }
}

abstract class Foo1 extends Foo

object Foo2 extends Foo1 {
  new Bar {}
}

Foo2
```

In Scala 2.13.0 the example above unexpectely prints `null`. Making `Foo1` a trait or `Foo2` something else than an object solves the issue. The example works as expected in Scala 2.12.10.

**Comment by som-snytt** [comment]
Probably related to https://github.com/scala/scala/pull/7270 from last fall, in RC1.

I don't do the crossword any more so maybe I'll find time to finally understand the conversations on that ticket.

**Comment by SethTisue** [comment]
@retronym @lrytz interested in looking into this?

**Comment by som-snytt** [comment]
There is an elaborate before-and-after or he-said-she-said test at https://github.com/scala/scala/pull/8425 where retronym will say it blows the complexity budget.

**Comment by lrytz** [comment]
The problem is that the first statement in `object Foo2` is a `new`. The implementation fails to tell this apart from the super call, and puts it in the wrong place. The following works correctly (added a `println`):

```
trait Foo {
  trait Bar {
    println(Foo.this)
  }
}

abstract class Foo1 extends Foo

object Foo2 extends Foo1 {
  println("statement after the super call")
  new Bar {}
}

Foo2
```

Fix in https://github.com/scala/scala/pull/8431.
