### ISSUE TITLE
scala.collection.mutable.Map.mapValuesInPlace ignores some entries (2.13)

### ISSUE THREAD

**Issue by m2ym** [scala/bug#11737]
`mapValuesInPlace` in `scala.collection.mutable.Map` is expected to affect all of its entries, but in a specific situation, some are not affected.

The following expression is the minimum reproducible code I found:

```scala
scala.collection.mutable
  .Map(
    0 -> 1,
    1 -> 1,
    2 -> 1,
    3 -> 1,
    4 -> 1,
    5 -> 1,
    6 -> 1,
    7 -> 1,
    8 -> 1,
    9 -> 1,
    241 -> 1
  )
  .mapValuesInPlace((_, _) => -1)
  .forall(_._2 == -1)
```

This expression should evaluate to `true` (in my understanding), but `false` actually.

Removing the `241` entry makes the expression work well as expected.

Log:

```
$ sbt scala
[snip]
Welcome to Scala 2.13.1-20190912-130256-a3791d4 (OpenJDK 64-Bit Server VM, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.

scala> scala.collection.mutable.Map(0 -> 1, 1 -> 1, 2 -> 1, 3 -> 1, 4 -> 1, 5 -> 1, 6 -> 1, 7 -> 1, 8 -> 1, 9 -> 1, 241 -> 1).mapValuesInPlace((_, _) => -1).forall(_._2 == -1)
res0: Boolean = false

scala> scala.collection.mutable.Map(0 -> 1, 1 -> 1, 2 -> 1, 3 -> 1, 4 -> 1, 5 -> 1, 6 -> 1, 7 -> 1, 8 -> 1, 9 -> 1).mapValuesInPlace((_, _) => -1).forall(_._2 == -1)
res1: Boolean = true
```

**Comment by SethTisue** [comment]
@lrytz wdyt, is this worth holding up 2.13.1 over, or should we let it slide to 2.13.2?

I lean towards letting it slide, because:

* the method didn't exist in ≤2.12
* waiting for a fix (and then for the community build to re-run) would cause days of delays
* we already waited rather a long time for 2.13.1 and it already has fixes for many more significant bugs than this

**Comment by lrytz** [comment]
> the method didn't exist in ≤2.12

It did, it was just named `transform`. The buggy implementation was inherited from 2.12, but (probably by luck) 2.12 is not affected.

I'm in favor of putting this in 2.13.1.

**Comment by lrytz** [comment]
@m2ym thank you for the small self-contained report!
