### ISSUE TITLE
scalap 2.13.x regression with constructor parameters

### ISSUE THREAD

**Issue by Shadowfiend** [scala/bug#11747]
While trying to make lift-json tests pass in Scala 2.13, I discovered a difference in the behavior of scalap between Scala 2.12 and 2.13. In particular, the constructor `MethodSignature` of a class has `children` for its parameters in Scala 2.12, but seems to lack these children in Scala 2.13.

I've created a minimal reproduction at https://github.com/Shadowfiend/scala-2-13-scalap-primitive-parameter-detection . While I'm running the example above on OpenJDK 11.0.2, the related test failure is playing out on OpenJDK 8, 11, and 12.

For simplicity, here is the test code:

```scala
case class Test(name: String)

class Booyan(base: Int)
class Booyak(base: String)
class Booyap(base: java.lang.Object)

object Test extends App {
  printClass(classOf[Booyan])
  printClass(classOf[Booyak])
  printClass(classOf[Booyap])

  def printClass(clazz: Class[_]) = {
    println(
      ScalaSigParser
        .parse(clazz)
        .get
        .symbols
        .collect {
          case initSymbol: MethodSymbol if initSymbol.name == "<init>" =>
            initSymbol.name + ": " + initSymbol.children
        }
        .mkString(" - ", "\n - ", "")
    )
  }
}
```

And here is the output on 2.12.9 vs 2.13.1:

```
# 2.12.9
 - <init>: List(MethodSymbol(base, owner=2, flags=2000, info=15 ,None))
 - <init>: List(MethodSymbol(base, owner=2, flags=2000, info=15 ,None))
 - <init>: List(MethodSymbol(base, owner=2, flags=2000, info=15 ,None))
# 2.13.1
 - <init>: List()
 - <init>: List()
 - <init>: List()
```

**Comment by som-snytt** [comment]
The exclusion was at https://github.com/scala/scala/commit/31b71066e5cb087601d74cd7d607cb1227b33a7c#diff-c1f505a8fcff1819b9db82e7c2dff3f2R30

**Comment by Shadowfiend** [comment]
If this is intentional, I should be able to update our code accordingly. In fact I'll probably do that anyway to get things out the door.

I'll say though, it's weird to filter `children` on anything other than what the parent is… Without a lot of context on my end, it feels like pickling should use a purpose-added variant instead and `children` should preserve its original behavior.

**Comment by lrytz** [comment]
Yeah, the change seems to be intended. I guess in scalap, `sym.children` means "member symbols defined within `sym`". The `ScalaSigPrinter` does `for (child <- symbol.children) printSymbol(level + 1, child)`, so parameters should not be in there.
