### ISSUE TITLE
Source.fromResource("some_file") throws NPE instead of FileNotFound exception 

### ISSUE THREAD

**Issue by vasiliybondarenko** [scala/bug#11743]
`Source.fromResource("some_file")` throws NPE instead of FileNotFound exception for non existent files. 
`Source.fromFile("some_file")` throws `FileNotFoundException` in that case

**Comment by som-snytt** [comment]
A resource need not be a `file` resource. A workaround would be of the form:
```
Option(ClassLoader.getSystemResource("junk")).map(io.Source.fromURL(_))
```
I think `Source` is acknowledged to be convenient but not fully realized. It has a `report` facility that might be developed further.

**Comment by nogurenn** [comment]
@som-snytt What would be the desired change for this?

**Comment by eed3si9n** [comment]
https://github.com/scala/scala/blob/2480754c33cff3bbd98f0ca268638254ea67e2d8/src/library/scala/io/Source.scala#L178-L179

```scala
  def fromResource(resource: String, classLoader: ClassLoader = Thread.currentThread().getContextClassLoader())(implicit codec: Codec): BufferedSource =
    fromInputStream(classLoader.getResourceAsStream(resource))
```

maybe it should be


```scala
  def fromResource(resource: String, classLoader: ClassLoader = Thread.currentThread().getContextClassLoader())(implicit codec: Codec): BufferedSource =
    Option(classLoader.getResourceAsStream(resource)) match {
      case Some(in) => fromInputStream(in)
      case None     => throw new IllegalArgumentException(s"resource '$resource' was not found")
    }
```
