### ISSUE TITLE
Yet more errors in code execution order

### ISSUE THREAD

**Issue by soronpo** [scala/bug#11756]
This is a following bug to #11397 
Indeed that bug was fixed, but as it turns out the general problem was not fixed. Here is a minimized code that throws an exception when the problem exists.

```scala
trait MyAny {
  type TSomething
  type This <: MyAny
}

class MyBool extends MyAny {
  type TSomething = DummyImplicit
  type This = MyBool
}

object Test extends App {
  val i = new MyBool
  var call = 0
  var callList : List[Int] = List()

  final class MyMatch[MV <: MyAny](val matchVal : MV)  {
    def myCase[MC](pattern : Boolean)(block : => Unit)(
      implicit patternBld : matchVal.TSomething
    ) : MyMatch[MV] = {
      call -= 1
      block
      this
    }
  }

  def myMatch[MV <: MyAny](matchValue : MV) : MyMatch[matchValue.This] = {
    callList = callList :+ call
    call += 1
    new MyMatch[matchValue.This](matchValue.asInstanceOf[matchValue.This])
  }

  myMatch(i)
    .myCase(true) {
      myMatch(i)
        .myCase(true) {

        }
    }
    .myCase(true) {
      myMatch(i)
        .myCase(true) {

        }
    }
  
  assert(callList == List(0, 0, -1))
}
```

**Comment by retronym** [comment]
The by-name argument of `myCase` is not taken into account.

Rewriting these as explicit `Function0` fixes the scope at which the stabilizers are inserted and avoids the assertion error:

```scala
trait MyAny {
  type TSomething
  type This <: MyAny
}

class MyBool extends MyAny {
  type TSomething = DummyImplicit
  type This = MyBool
}

object Test extends App {
  val i = new MyBool
  var call = 0
  var callList : List[Int] = List()

  final class MyMatch[MV <: MyAny](val matchVal : MV)  {
    def myCase[MC](pattern : Boolean)(block : () => Unit)(
      implicit patternBld : matchVal.TSomething
    ) : MyMatch[MV] = {
      call -= 1
      block()
      this
    }
  }

  def myMatch[MV <: MyAny](matchValue : MV) : MyMatch[matchValue.This] = {
    callList = callList :+ call
    call += 1
    new MyMatch[matchValue.This](matchValue.asInstanceOf[matchValue.This])
  }

  myMatch(i)
    .myCase(true) { () =>
      myMatch(i)
        .myCase(true) { () =>

        }
    }
    .myCase(true) { () =>
      myMatch(i)
        .myCase(true) { () =>

        }
    }
  
  assert(callList == List(0, 0, -1))
}
```

This is the part of the logic that needs to be nuanced:
https://github.com/scala/scala/blob/f755dc5e3435dc67a505147eb46374d2260da71c/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L5202

My gut feel is that we should consider a slight change to the implementation. Rather looking at the input (untyped) trees in enclosing contexts to exactly determine where the belong, maybe we should just record that there are pending stabilizers due for insertion, but wait until actually typechecking the outer tree before trying to figure out the appropriate insertion context.

**Comment by som-snytt** [comment]
I'll take a look today, as I have a related PR where I also said improve by deferring the insert. I'll update here if I don't make progress.

**Comment by SethTisue** [comment]
this seems like a desirable fix to me, but not actually a blocker for 2.13.2. I've tentatively re-targeted for 2.13.3 and removed the "blocker" label

**Comment by soronpo** [comment]
I don't understand the policy of treating a regression as a non-blocker.

**Comment by SethTisue** [comment]
I don't agree — not at all — that every regression is necessarily a release blocker.

at some point, the value of releasing what we have on the 2.13.x branch as 2.13.2 — including regression fixes as well as other improvements — exceeds the value of delaying the release to get one more fix in

**Comment by soronpo** [comment]
IMO, an issue that causes user code that migrates from 2.12.x to 2.13.x to silently break is very very bad.
