### ISSUE TITLE
Loading multiple csv files with wildcards

### ISSUE THREAD

**Issue by mukhan41** [scala/bug#11757]
hi I have a folder which contain 24 csv files having unique pattern. for example name is hyper01.csv till hyper24.csv I want to load files from 08 to 22 using wildcards. please suggest
currently using .load(s"s3a://${sys.env("S3_BUCKET_NAME")}/Input_1_CSV/CSV_2018-02-{2[1-5]}/{r[08,22]}")

**Comment by soronpo** [comment]
The issue tracker is not meant for such questions. Please refer to either stackoverflow, https://users.scala-lang.org/ or the scala/scala gitter room.
