### ISSUE TITLE
scala.reflect.io.ZipArchive#ensureDir infinitely recurses in some cases in 2.13.1

### ISSUE THREAD

**Issue by mjadczak** [scala/bug#11754]
It looks like this class was modified in 2.13.1 to use a "path" representation for entries always, instead of going back and forth between "dotted" and "path" representations (see scala/scala#8356). The `ensureDir` function depends on having a "root" entry already in the `dirs` map which is passed in - otherwise, it will never terminate, as the `dirName` function which it calls has a fixed point at `"/"`.

With the "path" representation, the root is always `"/"`, whereas it seems to have been `""` in some cases previously. This means that every time we will call this `ensureDir` functions, we need to make sure that we pass it a map already containing an entry for `"/"`. [There seems to have already been an effort](https://github.com/scala/scala/commit/0c7170b2abc696c55ec596cd715b3454db02e344#diff-a1226d4dc1d8e8e5d47949335b81a607R189) to fix some of these cases. Unfortunately, not all were caught.

In our case, we are reflectively compiling scala code at runtime, and are getting a `StackOverflowError` in this method when resolving one package (`javax.swing`). I have traced this to [this line](https://github.com/scala/scala/blob/59dec6114da327a1c79e3cc1571f4173ecb6e829/src/reflect/scala/reflect/io/ZipArchive.scala#L325), which I believe should use `"/"` as the key, instead of `""`. I think there is a similar bug at line 250 in that file, in `URLZipArchive`.

**Comment by som-snytt** [comment]
I'll take a look, since the problem is already diagnosed and my daughter's middle school band is playing soon at the high school football game.

**Comment by michelou** [comment]
I read (where `root = new DirEntry("/")`):
```
Line 190 : dirs.put("/", root)
Line 250 : dirs.put("", root)
Line 325 : dirs.put("", root)
```

**Comment by butlermh** [comment]
I think this bug affects Scala 2.12.10 as well?

I am encountering Stackoverflow error when trying to use Scalate 1.9.5 on Scala 2.12.10?

Exception in thread “main” java.lang.StackOverflowError
at scala.reflect.io.ZipArchive$.splitPath(ZipArchive.scala:62)
at scala.reflect.io.ZipArchive$.scala$reflect$io$ZipArchive$$dirName(ZipArchive.scala:58)
at scala.reflect.io.ZipArchive.ensureDir(ZipArchive.scala:114)
at scala.reflect.io.ZipArchive.ensureDir(ZipArchive.scala:114)
at scala.reflect.io.ZipArchive.ensureDir(ZipArchive.scala:114)
at scala.reflect.io.ZipArchive.ensureDir(ZipArchive.scala:114)
at scala.reflect.io.ZipArchive.ensureDir(ZipArchive.scala:114)
etc

Looking at the [code](https://github.com/scala/scala/commits/2.13.x/src/reflect/scala/reflect/io/ZipArchive.scala) this [patch](https://github.com/scala/scala/pull/8447) wasn’t applied to 2.12.10 branch?

**Comment by SethTisue** [comment]
@butlermh it looks like it certainly _could_ be the same problem, but we'd have to establish that for sure. Som's PR (https://github.com/scala/scala/pull/8447) includes test coverage, so a possible first step would be to backport the tests and see if they fail or not.

@som-snytt: @mjadczak's original report implied the problem was 2.13-only; do you agree?

**Comment by som-snytt** [comment]
There are actually two retronyms, existing on parallel planes which are time-shifted such that one retronym makes changes on 2.12 and the other retronym makes changes on 2.13, not necessarily in that order.

**Comment by rjolly** [comment]
I confirm 2.12.10 is impacted as well, it breaks the scripting engine.
`jrunscript -classpath lib\scala-compiler-2.12.9.jar;lib\scala-reflect-2.12.9.jar;lib\scala-library-2.12.9.jar -Djava.class.path=lib\scala-library-2.12.9.jar -l scala
scala> "hello world"
hello world
scala>

jrunscript -classpath lib\scala-compiler-2.12.10.jar;lib\scala-reflect-2.12.10.jar;lib\scala-library-2.12.10.jar -Djava.class.path=lib\scala-library-2.12.10.jar -l scala
Exception in thread "main" java.lang.StackOverflowError
        at scala.reflect.io.ZipArchive$.scala$reflect$io$ZipArchive$$dirName(ZipArchive.scala:58)
        at scala.reflect.io.ZipArchive.ensureDir(ZipArchive.scala:114)
        at scala.reflect.io.ZipArchive.ensureDir(ZipArchive.scala:114)
`

**Comment by victorhearnyeates** [comment]
I'm still seeing this in 2.13.3 when we add a `-Dlog4j2.debug` option

**Comment by SethTisue** [comment]
@victorhearnyeates (that's intriguing, but not actionable without details on how to reproduce it)

**Comment by SethTisue** [comment]
2.12 backport merged for 2.12.13: https://github.com/scala/scala/pull/9230

**Comment by jdimeo** [comment]
Eagerly awaiting this for 2.12! It's breaking our code which uses the compiler to provide a DSL

**Comment by SethTisue** [comment]
@jdimeo you might like to [test a nightly build](https://stackoverflow.com/questions/40622878/how-do-i-tell-sbt-to-use-a-nightly-build-of-scala-2-12-or-2-13) to make sure the fix fixes it for you

2.12.13 itself will be along before too much longer; see https://contributors.scala-lang.org/t/coming-soon-scala-2-12-13/4546

**Comment by jdimeo** [comment]
@SethTisue - thank you - the nightly build got me unstuck on my build error.
