### ISSUE TITLE
Pattern matching LazyList

### ISSUE THREAD

**Issue by charpov** [scala/bug#11750]
This is a feature request.  With the switch from `Stream` to `LazyList`, I have lost the possibility of pattern matching on `Empty`.  I find myself writing things like:

```scala
val LazyNil = LazyList.empty

def getAt[A](s: LazyList[A], i: Int): A = (s, i) match {
  case (LazyNil, _) => throw new NoSuchElementException("getAt(empty)")
  case (h #:: _, 0) => h
  case (_ #:: t, _) => getAt(t, i - 1)
}
```
Is there a good reason the `empty_` value from `LazyList` is not public?  If not, could it be changed into a public `Empty` at some point?

**Comment by SethTisue** [comment]
thread: https://users.scala-lang.org/t/pattern-matching-lazylist/5105/3

**Comment by SethTisue** [comment]
conclusion: just match on `LazyList()`

**Comment by charpov** [comment]
> conclusion: just match on `LazyList()`

OK, but never got the answer as to why the existing `empty_` field cannot be public and act as a `Nil`.

**Comment by SethTisue** [comment]
the name is taken; we already expose `LazyList.empty[T]`, which is a `def` (it must be, it takes a type parameter)

the situation is the same with other collection types as well, which don't support this kind of matching either, and for the same reason:

```
scala 2.13.4> Nil match { case List.empty => "yes" }
                                    ^
              error: stable identifier required, but scala.`package`.List.empty found.
```
