### ISSUE TITLE
Warn on any deprecated option option

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11759]
The language option should trigger deprecation, similarly for lint or optimizer options that may go out of fashion.
```
$ scalac -optimize -language:higherKinds -d /tmp -Xlint nodep.scala
warning: -optimize is deprecated: Since 2.12, enables -opt:l:inline -opt-inline-from:**. See -opt:help.
nodep.scala:2: warning: Unused import
import scala.language.higherKinds
                      ^
nodep.scala:6: warning: method f in object nope is deprecated:
class C { def c = nope.f }
                       ^
three warnings found
```

**Comment by som-snytt** [comment]
Nobody cares about command line options, even if they are modeled in the language.

**Comment by SethTisue** [comment]
@som-snytt maybe I don't care, but I can't tell because I actually don't understand what the issue was here. unless you're completely confident this is unimportant. Would you mind explaining it?

**Comment by som-snytt** [comment]
There is no way to deprecate "choices" for a command line option, such as `-language:higherKinds`, other such choices subject to deprecation such as `-Xlint` and `-opt` choices. No is clamoring for it, nor clambering for it.

**Comment by SethTisue** [comment]
Okay — although improvement here would be welcome, I don't think we need an open ticket around.
