### ISSUE TITLE
Diverging implicit expansion in Scala 2.13

### ISSUE THREAD

**Issue by lihaoyi** [scala/bug#11768]
The following code compiles in Scala 2.12.10, fails with a diverging implicit error in Scala 2.13.0:

```scala
object A {
  trait B[T]
  implicit def c[T <: Singleton]: B[T] = ???
  implicit def d[T1: B, T2: B]: B[Tuple2[T1, T2]] = ???
  implicit def e[T: B]: B[Option[T]] = ???

  implicit def f[C[_] <: Iterable[_], T](implicit r: B[T]): B[C[T]] = ???
}
object G{
  class H[T: A.B, V: A.B](t: Option[(V, T)]){
    implicitly[A.B[Option[(V, T)]]]
  }
  def h[T: A.B, V: A.B](t: Option[(V, T)]){
    implicitly[A.B[Option[(V, T)]]]
  }
}
```

`class H` is what fails to compile, even though `def h` compiles just fine. 

As far as I can tell this is a minimal repro. Removing `def f` also is sufficient to make everything (including `class H`) compile. Converting the `Tuple2` to a `Seq` also makes things compile.

This is a regression and causes spurious compile errors when trying to use uPickle with Scala 2.13

**Comment by joroKr21** [comment]
It also fails on 2.12 if we enable `-Ypartial-unification`.
I'm not sure yet why it causes divergence but at some point the implicit search matches `f[[+T](V, T), T]`, i.e. it unifies `C[_]` with `(V, T)`.

**Comment by joroKr21** [comment]
More minimization:
```scala
  trait B[T]
  object B extends {
    implicit def d[T1: B, T2: B]: B[(T1, T2)] = ???
    implicit def f[C[x] <: Iterable[x], T: B]: B[C[T]] = ???
  }

  object G {
    class H[T : B, V : B] {
      implicitly[B[((V, T), T)]]
    }
  }
```

Why would being inside a class matter?

**Comment by joroKr21** [comment]
> Why would being inside a class matter?

Here: https://github.com/scala/scala/blob/19b05850dc835e0e504d635def4de5ab9781da13/src/compiler/scala/tools/nsc/typechecker/Implicits.scala#L515-L521

Inside a method, `T` and `V` are skolems (not type parameters).
But inside a class they are type parameters.
So when we have open implicits for `B[V]` and `B[(V, T)]` and we want to check if one dominates the other they are stripped to `B[?]` and B[(?, ?)]`, which are `=:=` by the nature of wildcards and we conclude that one dominates and hence there is divergence.

We need to summon help here. I don't know why the class constructor type parameters are not sckolemized or why we need to strip them in `dominates`.

**Comment by joroKr21** [comment]
CC @milessabin

**Comment by joroKr21** [comment]
It's definitely a bug, but weird that we notice it just now. Feels like I have been using `-Ypartial-unification` since forever.

**Comment by jbracker** [comment]
@Jasper-M But it should not fail, right? Or am I missing something?

**Comment by Jasper-M** [comment]
> But it should not fail, right? Or am I missing something?

Ideally not, but I suspect it's a known limitation of the divergence checking algorithm.

Though the strange thing is, it works as-is in Dotty, it works if you use `shapeless.Lazy` in Scala 2, but it still doesn't work with by-name implicits in 2.13...

**Comment by joroKr21** [comment]
Well it works if we use `def Test` instead of `class Test` so it's the same problem as the OP.

**Comment by joroKr21** [comment]
The underlying problem uncovered by `-Ypartial-unification` is older and affects more versions of the compiler: found #10080
