### ISSUE TITLE
Least upper bound in List.foreach[U](f: A => U)

### ISSUE THREAD

**Issue by kamilkloch** [scala/bug#11769]
Not sure if this is a bug or an expected behavior. 
Scala 2.12. The following code
```scala
val mapBuilder = Map.newBuilder[String, String]
val setBuilder = Set.newBuilder[String]

List(Option("")).foreach {
  case Some(_) => mapBuilder += "" -> ""
  case None => setBuilder += ""
}
```
does not compile - compiler fails to infer the least upper bound of the two builders (the `U` in `foreach[U](f: A => U)`): 
```
type arguments [String,Iterable[java.io.Serializable] with String => Any with scala.collection.generic.Subtractable[String,Equals]] do not conform to trait Subtractable's type parameter bounds [A,+Repr <: scala.collection.generic.Subtractable[A,Repr]]
```

Annotating the `foreach` with `Any` resolves the problem:
```scala
List(Option("")).foreach[Any] {
...
```
Is this an expected behavior?

**Comment by som-snytt** [comment]
Scrolling right on the error text, guessing https://github.com/scala/bug/issues/10151

The example compiles on 2.13 because of new collections and presumably not improved inference.
