### ISSUE TITLE
synthetic methods for default parameter value are generated with wrong index for the first parameter

### ISSUE THREAD

**Issue by unkarjedy** [scala/bug#11793]
consider the example:
```scala
object LocalMethodsWithSameName1 {
  def main(args: Array[String]) {
    def foo(i: Int = 1, u: Int = 10, v: Long = 50) = {
      def foo(j: Int = 2) = 200 + j
      100 + i + u + v
    }
    ""
    def other() {
      def foo(i: Int = 3) = 300 + i
      ""
    }
    def third() {
      def foo(i: Int = 4) = 400 + i
      ""
    }
    foo()
    other()
    third()
  }
}
```

decompiled version for: [2_12_7.txt](https://github.com/scala/bug/files/3818465/2_12_7.txt)
decompiled version for: [2_12_8.txt](https://github.com/scala/bug/files/3818466/2_12_8.txt)

Compare generated classes. Note that for the first default argument the index in the synthetic method is generated incorrectly:

![image](https://user-images.githubusercontent.com/3989292/68370642-061f1a80-014e-11ea-8eb8-5fe415abd06d.png)

this causes some IntelliJ debugger evaluator issues

related issue in IntelliJ:
https://youtrack.jetbrains.com/issue/SCL-16528#focus=streamItem-27-3779068.0-0

**Comment by lrytz** [comment]
That's an interesting one :-)

It's not a bug though. Using the defaults works correctly. It's just lambdalift that adds another `$n` when lifting methods up. You can look at the output when compiling with `-Vprint:_`.

The spec says that the first default of `foo` is `foo$default$1`, which is true when it's created. If `foo` is local, it gets lifted as `foo$1`, and the default gets lifted as `foo$default$1$1` (not `foo$1$default$1`), but that's just an implementation detail / binary encoding question.

**Comment by unkarjedy** [comment]
I understand that strictly it isn't a bug but a cosmetic issue. 

IUUC if the generated "lifted indices" were random and the runtime worked it wouldn't be a bug as well.  (which is how it currently looks like for >2.12.8)

Yes, that`s an implementation detail which complicates debugging support.
Still not quite clear why the same local function should get different "lifted index" for different parameters:
> $n when lifting methods up

**Comment by unkarjedy** [comment]
even more complicated example
after adding more default parameters: (testing on 2.13.1)
```scala
object LocalMethodsWithSameName {

  def main(args: Array[String]) {
    def bar(i: Int = 1, u: Int = 10, v: Long = 100) = ()

    def foo(i: Int = 1, u: Int = 10, v: Long = 100) = {
      def foo(j: Int = 2) = 200 + j
      1000 + i + u + v
    }
    ""
    def other() {
      def foo(i: Int = 3, u: Int = 30, v: Long = 300) = 3000 + i
      ""
    }
    def third() {
      def foo(i: Int = 4, u: Int = 40, v: Long = 400) = 4000 + i
      ""
    }
    foo()
    other()
    third()
  }
}
```
the output:
```scala
Warning:scalac: package <empty> {
  object LocalMethodsWithSameName extends Object {
    def main(args: Array[String]): Unit = {
      "";
      LocalMethodsWithSameName.this.foo$1(LocalMethodsWithSameName.this.foo$default$1$2(), LocalMethodsWithSameName.this.foo$default$2$1(), LocalMethodsWithSameName.this.foo$default$3$1());
      LocalMethodsWithSameName.this.other$1();
      LocalMethodsWithSameName.this.third$1()
    };
    final <static> private[this] def bar$1(i: Int, u: Int, v: Long): Unit = ();
    final <synthetic> <static> private[this] def bar$default$1$1(): Int = 1;
    final <synthetic> <static> private[this] def bar$default$2$1(): Int = 10;
    final <synthetic> <static> private[this] def bar$default$3$1(): Long = 100L;
    final <static> private[this] def foo$2(j: Int): Int = 200.+(j);
    final <synthetic> <static> private[this] def foo$default$1$1(): Int = 2;
    final <static> private[this] def foo$1(i: Int, u: Int, v: Long): Long = 1000.+(i).+(u).+(v);
    final <synthetic> <static> private[this] def foo$default$1$2(): Int = 1;
    final <synthetic> <static> private[this] def foo$default$2$1(): Int = 10;
    final <synthetic> <static> private[this] def foo$default$3$1(): Long = 100L;
    final <static> private[this] def foo$3(i: Int, u: Int, v: Long): Int = 3000.+(i);
    final <synthetic> <static> private[this] def foo$default$1$3(): Int = 3;
    final <synthetic> <static> private[this] def foo$default$2$2(): Int = 30;
    final <synthetic> <static> private[this] def foo$default$3$2(): Long = 300L;
    final <static> private[this] def other$1(): Unit = {
      "";
      ()
    };
    final <static> private[this] def foo$4(i: Int, u: Int, v: Long): Int = 4000.+(i);
    final <synthetic> <static> private[this] def foo$default$1$4(): Int = 4;
    final <synthetic> <static> private[this] def foo$default$2$3(): Int = 40;
    final <synthetic> <static> private[this] def foo$default$3$3(): Long = 400L;
    final <static> private[this] def third$1(): Unit = {
      "";
      ()
    };
    def <init>(): LocalMethodsWithSameName.type = {
      LocalMethodsWithSameName.super.<init>();
      ()
    }
  }
}
```

we can see that for `bar`, `foo$1`, `foo$2`, `foo$3` the logic for the indices construction is not transparent

**Comment by lrytz** [comment]
> not quite clear why the same local function should get different "lifted index" for different parameters

To lambdalift, these are all just plain methods. `foo` is a method that needs to be lifted, `foo$default$1` as well, lambdalift doesn't (need to) know that the two methods are related.

This could be changed of course, a PR is welcome if there's a convincing reason.

The change in 2.12.8 is likely due to https://github.com/scala/scala/pull/7203.

**Comment by unkarjedy** [comment]
thanks for tips and link!
