### ISSUE TITLE
Scala 2.13.0 OpenJdk 13: REPL crashes with RuntimeException: /packages cannot be represented as URI

### ISSUE THREAD

**Issue by sqd** [scala/bug#11794]
```
[I] ~ java -version
openjdk version "13.0.1" 2019-10-15
OpenJDK Runtime Environment (build 13.0.1+9)
OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode)
[I] ~ scala
Welcome to Scala 2.13.0-20190613-143643-unknown (OpenJDK 64-Bit Server VM, Java 13.0.1).
Type in expressions for evaluation. Or try :help.

scala> 1
java.io.IOError: java.lang.RuntimeException: /packages cannot be represented as URI
	at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
	at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:216)
	at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:63)
	at scala.collection.StrictOptimizedIterableOps.strictOptimizedFlatMap(StrictOptimizedIterableOps.scala:118)
	at scala.collection.StrictOptimizedIterableOps.strictOptimizedFlatMap$(StrictOptimizedIterableOps.scala:115)
	at scala.collection.immutable.Vector.strictOptimizedFlatMap(Vector.scala:113)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:106)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:105)
	at scala.collection.immutable.Vector.flatMap(Vector.scala:113)
	at scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:63)
	at scala.tools.nsc.interpreter.IMain.compilerClasspath(IMain.scala:93)
	at scala.tools.nsc.interpreter.IMain.makeClassLoader(IMain.scala:352)
	at scala.tools.nsc.interpreter.IMain.ensureClassLoader(IMain.scala:275)
	at scala.tools.nsc.interpreter.IMain.classLoader(IMain.scala:278)
	at scala.tools.nsc.interpreter.IMain.runtimeMirror$lzycompute(IMain.scala:168)
	at scala.tools.nsc.interpreter.IMain.runtimeMirror(IMain.scala:168)
	at scala.tools.nsc.interpreter.IMain.$anonfun$getModuleIfDefined$1(IMain.scala:177)
	at scala.tools.nsc.interpreter.IMain.noFatal(IMain.scala:170)
	at scala.tools.nsc.interpreter.IMain.getModuleIfDefined(IMain.scala:177)
	at scala.tools.nsc.interpreter.IMain.readRootPath(IMain.scala:289)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.resolvePathToSymbol(IMain.scala:662)
	at scala.tools.nsc.interpreter.IMain$Request.resultSymbol$lzycompute(IMain.scala:919)
	at scala.tools.nsc.interpreter.IMain$Request.resultSymbol(IMain.scala:918)
	at scala.tools.nsc.interpreter.IMain$Request.$anonfun$typeMap$1(IMain.scala:930)
	at scala.reflect.internal.util.Collections.$anonfun$mapFrom$1(Collections.scala:220)
	at scala.collection.immutable.List.map(List.scala:222)
	at scala.reflect.internal.util.Collections.mapFrom(Collections.scala:220)
	at scala.reflect.internal.util.Collections.mapFrom$(Collections.scala:219)
	at scala.reflect.internal.SymbolTable.mapFrom(SymbolTable.scala:28)
	at scala.tools.nsc.interpreter.IMain$Request.typeMap(IMain.scala:930)
	at scala.tools.nsc.interpreter.IMain$Request.typeOf$lzycompute(IMain.scala:935)
	at scala.tools.nsc.interpreter.IMain$Request.typeOf(IMain.scala:935)
	at scala.tools.nsc.interpreter.IMain$Request.compile(IMain.scala:897)
	at scala.tools.nsc.interpreter.IMain.$anonfun$compile$1(IMain.scala:493)
	at scala.tools.nsc.interpreter.IMain.$anonfun$compile$1$adapted(IMain.scala:493)
	at scala.util.Either.filterOrElse(Either.scala:400)
	at scala.tools.nsc.interpreter.IMain.compile(IMain.scala:493)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:487)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:470)
	at scala.tools.nsc.interpreter.shell.ILoop.interpretStartingWith(ILoop.scala:930)
	at scala.tools.nsc.interpreter.shell.ILoop.command(ILoop.scala:787)
	at scala.tools.nsc.interpreter.shell.ILoop.processLine(ILoop.scala:462)
	at scala.tools.nsc.interpreter.shell.ILoop.loop(ILoop.scala:485)
	at scala.tools.nsc.interpreter.shell.ILoop.run(ILoop.scala:1019)
	at scala.tools.nsc.MainGenericRunner.runTarget$1(MainGenericRunner.scala:87)
	at scala.tools.nsc.MainGenericRunner.run$1(MainGenericRunner.scala:91)
	at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:102)
	at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:107)
	at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)
Caused by: java.lang.RuntimeException: /packages cannot be represented as URI
	... 49 more

That entry seems to have slain the compiler.  Shall I replay
your session? I can re-run each line except the last one.
[y/n]
Abandoning crashed session.

scala> :quit

```

**Comment by sqd** [comment]
Fixed by using the 2.13.1 binary from scala-lang.org as describe [here](https://github.com/scala/bug/issues/11762#issuecomment-538905917)

But I'm using openjdk 13, so this could be a bug with 2.13.0 instead of with jdk version?

**Comment by SethTisue** [comment]
as per https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html

**Comment by yonghaoy** [comment]
I am still having the issue with Scala 2.13.1, JDK 13 and sbt 1.3.8:


: java.lang.RuntimeException: /packages cannot be represented as URI
[error]         at java.base/jdk.internal.jrtfs.JrtPath.toUri(JrtPath.java:176)
[error]         at scala.tools.nsc.classpath.JrtClassPath.asURLs(DirectoryClassPath.scala:204)
[error]         at scala.tools.nsc.classpath.AggregateClassPath.$anonfun$asURLs$1(AggregateClassPath.scala:55)
[error]         at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:240)
[error]         at scala.collection.Iterator.foreach(Iterator.scala:937)
[error]         at scala.collection.Iterator.foreach$(Iterator.scala:937)
[error]         at scala.collection.AbstractIterator.foreach(Iterator.scala:1425)
[error]         at scala.collection.IterableLike.foreach(IterableLike.scala:70)
[error]         at scala.collection.IterableLike.foreach$(IterableLike.scala:69)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error]         at scala.collection.TraversableLike.flatMap(TraversableLike.scala:240)
[error]         at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:237)
[error]         at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error]         at scala.tools.nsc.classpath.AggregateClassPath.asURLs(AggregateClassPath.scala:55)
[error]         at scala.tools.nsc.typechecker.Macros.findMacroClassLoader(Macros.scala:66)
[error]         at scala.tools.nsc.typechecker.Macros.findMacroClassLoader$(Macros.scala:65)
[error]         at scala.tools.nsc.Global$$anon$1.findMacroClassLoader(Global.scala:469)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$defaultMacroClassloaderCache$2(MacroRuntimes.scala:56)
[error]         at scala.reflect.internal.SymbolTable$perRunCaches$$anon$1.apply(SymbolTable.scala:457)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader(MacroRuntimes.scala:58)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.defaultMacroClassloader$(MacroRuntimes.scala:58)
[error]         at scala.tools.nsc.Global$$anon$1.defaultMacroClassloader(Global.scala:469)
[error]         at scala.reflect.macros.runtime.MacroRuntimes$MacroRuntimeResolver.resolveRuntime(MacroRuntimes.scala:76)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.$anonfun$standardMacroRuntime$3(MacroRuntimes.scala:38)
[error]         at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:206)
[error]         at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:203)
[error]         at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:80)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime(MacroRuntimes.scala:38)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.standardMacroRuntime$(MacroRuntimes.scala:31)
[error]         at scala.tools.nsc.Global$$anon$1.standardMacroRuntime(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:448)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$14.default(AnalyzerPlugins.scala:445)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime(AnalyzerPlugins.scala:445)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroRuntime$(AnalyzerPlugins.scala:445)
[error]         at scala.tools.nsc.Global$$anon$1.pluginsMacroRuntime(Global.scala:469)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime(MacroRuntimes.scala:25)
[error]         at scala.reflect.macros.runtime.MacroRuntimes.macroRuntime$(MacroRuntimes.scala:25)
[error]         at scala.tools.nsc.Global$$anon$1.macroRuntime(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.$anonfun$expand$1(Macros.scala:619)
[error]         at scala.tools.nsc.Global.withInfoLevel(Global.scala:219)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.expand(Macros.scala:613)
[error]         at scala.tools.nsc.typechecker.Macros$MacroExpander.apply(Macros.scala:600)
[error]         at scala.tools.nsc.typechecker.Macros.standardMacroExpand(Macros.scala:764)
[error]         at scala.tools.nsc.typechecker.Macros.standardMacroExpand$(Macros.scala:762)
[error]         at scala.tools.nsc.Global$$anon$1.standardMacroExpand(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:432)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins$$anon$12.default(AnalyzerPlugins.scala:429)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.invoke(AnalyzerPlugins.scala:401)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand(AnalyzerPlugins.scala:429)
[error]         at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsMacroExpand$(AnalyzerPlugins.scala:429)
[error]         at scala.tools.nsc.Global$$anon$1.pluginsMacroExpand(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.Macros.macroExpand(Macros.scala:757)
[error]         at scala.tools.nsc.typechecker.Macros.macroExpand$(Macros.scala:757)
[error]         at scala.tools.nsc.Global$$anon$1.macroExpand(Global.scala:469)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.vanillaAdapt$1(Typers.scala:1163)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1223)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5631)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:881)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:471)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1219)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5631)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3280)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:471)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:3670)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$33(Typers.scala:3678)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3678)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3689)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4767)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4776)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5571)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedArg$1(Typers.scala:3280)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:471)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedArgToPoly$1(Typers.scala:3670)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$doTypedApply$33(Typers.scala:3678)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3678)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3689)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4767)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4776)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5571)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:5692)
[error]         at scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1079)
[error]         at scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1629)
[error]         at scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1798)
[error]         at scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1763)
[error]         at scala.tools.nsc.typechecker.Namers$Namer$ValTypeCompleter.completeImpl(Namers.scala:910)
[error]         at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:1960)
[error]         at scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:1958)
[error]         at scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:1953)
[error]         at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1530)
[error]         at scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1678)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5240)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1999)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1868)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5538)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5681)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3264)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3264)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5247)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5540)
[error]         at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5617)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:106)
[error]         at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
[error]         at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:96)
[error]         at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1467)
[error]         at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1451)
[error]         at scala.tools.nsc.Global$Run.compileSources(Global.scala:1444)
[error]         at scala.tools.nsc.Global$Run.compile(Global.scala:1567)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
[error]         at xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
[error]         at xsbt.CompilerInterface.run(CompilerInterface.scala:31)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[error]         at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
[error]         at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
[error]         at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
[error]         at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
[error]         at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
[error]         at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
[error]         at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
[error]         at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
[error]         at sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
[error]         at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
[error]         at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
[error]         at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1544)
[error]         at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1518)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by SethTisue** [comment]
@yonghaoy I see you also reported this at https://github.com/sbt/sbt/issues/5093 . let's discuss there, not here — at least, unless we're able to establish that it's actually a Scala bug
