### ISSUE TITLE
s.c.SeqMap should override its toString

### ISSUE THREAD

**Issue by joshlemer** [scala/bug#11809]
`SeqMap`'s `toString` currently prints something like `Map(1 -> 2)`, however the convention in the collections is that abstract collections show their name in their `toString`. For example, see `IndexedSeq(1,2,3)`. So instead of `Map(1 -> 2)`, it should be `SeqMap(1 -> 2)`. This affects all three of `scala.collection.SeqMap`, `scala.collection.immutable.SeqMap`, `scala.colllection.mutable.SeqMap`.

Reproducing:

```scala
scala> new collection.SeqMap[Int, Int] { def -(k: Int) = ???; def -(k: Int, k2: Int, ks: Int*) = ???; def get(k: Int) = ???; def iterator = Iterator(1 -> 2) }
res12: scala.collection.SeqMap[Int,Int]{def -(k: Int): Nothing; def -(k: Int, k2: Int, ks: Int*): Nothing; def get(k: Int): Nothing} = Map(1 -> 2)
```

```scala
scala> import scala.collection.immutable._
import scala.collection.immutable._

scala> :paste
// Entering paste mode (ctrl-D to finish)

  new SeqMap[Int, String] {
    override def removed(key: Int): SeqMap[Int, String] = ???
    override def updated[V1 >: String](key: Int, value: V1): SeqMap[Int, V1] = ???
    override def get(key: Int): Option[String] = ???
    override def iterator: Iterator[(Int, String)] = Iterator(1 -> "hi")
  }

// Exiting paste mode, now interpreting.

res14: scala.collection.immutable.SeqMap[Int,String] = Map(1 -> hi)
```

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

  new collection.mutable.SeqMap[Int, String] {
    override def subtractOne(elem: Int): this.type = ???
    override def get(key: Int): Option[String] = ???
    override def iterator: Iterator[(Int, String)] = Iterator(1 -> "hi")
    override def addOne(elem: (Int, String)): this.type = ???
  }

// Exiting paste mode, now interpreting.

res15: scala.collection.mutable.SeqMap[Int,String] = Map(1 -> hi)

```

**Comment by Jasper-M** [comment]
This doesn't really seem to be a problem in practice?

```
scala> scala.collection.immutable.SeqMap(1 -> 2)
res4: scala.collection.immutable.SeqMap[Int,Int] = VectorMap(1 -> 2)

scala> scala.collection.SeqMap(1 -> 2)
res5: scala.collection.immutable.SeqMap[Int,Int] = VectorMap(1 -> 2)

scala> scala.collection.mutable.SeqMap(1 -> 2)
res6: scala.collection.mutable.SeqMap[Int,Int] = LinkedHashMap(1 -> 2)
```

Looks like it's the case for the whole collections library that `className` only gets overridden in the leaf/implementation classes.

**Comment by joshlemer** [comment]
@Jasper-M It's not true of `IndexedSeq` or `SortedMap` or `SortedSet` or `LinearSeq` though. `SeqMap` stands out.

**Comment by Jasper-M** [comment]
Oh ok I see it now. I was confused because those traits appear to override the deprecated `stringPrefix` instead of `className`. The relevant commit says 

> All user-extensible classes override `stringPrefix` instead of
`className` for compatibility with 2.12.

I don't really understand that reasoning, but I'm probably missing something.
