### ISSUE TITLE
ConcatIterator can lose its tail after merging another ConcatIterator

### ISSUE THREAD

**Issue by altomch** [scala/bug#11807]
Tail for next concatenations can be detached after `Iterator ++ ConcatIterator`:
```
scala> var initIt = Array(1).iterator                
scala> val concatIt = Array(2).iterator ++ Array(3).iterator
scala> var it = initIt ++ concatIt                           // (1)

scala> it.next()
res0: Int = 1
scala> it.hasNext                                            // (2)
res1: Boolean = true

scala> it = it ++ Array(4).iterator                          // (3)
scala> it.next()
res2: Int = 2
scala> it.next()
res3: Int = 3

scala> it.hasNext                                            // (4)
res4: Boolean = false
```
(1) `concatIt` is assigned to `tail` and `last` [link](https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/Iterator.scala#L1177)
(2) `merge` method is called, it unwraps the tail (`concatIt`), but `last` field still contains wrapped  object [link](https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/Iterator.scala#L1151)
(3) other Iterator concatenated to current, but it connects to tail of the `last` field which is already detached from iteration in (2) [link](https://github.com/scala/scala/blob/2.13.x/src/library/scala/collection/Iterator.scala#L1180)
As a result we have `false` in (4)

This behavior was introduced in [#5033](https://github.com/scala/scala/pull/5033)

Scala v2.12.10, v2.13.1 
Java 1.8.0_212

**Comment by dwijnand** [comment]
(@altomch I tweaked the script so it didn't error in the REPL.  Have a look and tweak it if my change was wrong.)

**Comment by altomch** [comment]
> (@altomch I tweaked the script so it didn't error in the REPL. Have a look and tweak it if my change was wrong.)

thank you, it was my "copy-pasting" mistake

**Comment by som-snytt** [comment]
I'll PR this as a lunchtime exercise. Actually, it's almost a happy hour exercise at this point.

**Comment by som-snytt** [comment]
@altomch Thanks for the explanation. This was like those math problems where you cheat and look at the answer in the back of the book, then it's still too subtle so you have to work it out with a pencil.
