### ISSUE TITLE
Scaladoc member link only gets me in the neighborhood, then I use streetview to find my destination

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11805]
I wanted to link to the Scaladoc for `PartialFunction.applyOrElse`.

https://www.scala-lang.org/api/current/scala/PartialFunction.html#applyOrElse[A1%3C:A,B1%3E:B](x:A1,default:A1=%3EB1):B1

My firefox on Windows winds up at `orElse` instead of `applyOrElse`. The microsoft browser is at `andThen`. On MacOS, safari shows `compose`, firefox `orElse`. Edit: when refreshed, the safari window is scrolled to `orElse`. and firefox, on refresh, scrolls to `compose`.

In the `compose` case, possibly the floating header with the search box exactly covers the `applyOrElse`, similar to hrhino.

I'm willing to believe that this is a practical joke punning on the method names which has gone over my head.

**Comment by hrhino** [comment]
Works for me:

![20191117_095853](https://user-images.githubusercontent.com/28076058/69009139-aa5c4a80-0920-11ea-8118-f426764de0ce.jpg)

I think that method's just a bit shy.

**Comment by SethTisue** [comment]
I have long been plagued by this (in Safari)

**Comment by som-snytt** [comment]
Thank-you @SethTisue for the validation @hrhino 

Also I always wondered who uses safari besides my mother when she was alive.

**Comment by eed3si9n** [comment]
If header is hiding something, it doesn't happen uniformly.

### steps

1. Open https://www.scala-lang.org/api/current/scala/PartialFunction.html (Scala 2.13.1 atm) using Chrome 79 on macOS.
2. Scroll down to `def andThen[C](k: PartialFunction[B, C]): PartialFunction[A, C]`, right-click on the link icon, and open a new tab.
3. Repeat right-click, new-tab for `applyOrElse[A1<:A,B1>:B](x:A1,default:A1=>B1):B1`.
4. Repeat right-click, new-tab for `unlift:PartialFunction[A,B]`

#### (Chrome, new-tab) andThen[C](k: PartialFunction[B, C]): PartialFunction[A, C]

<img width="1017" alt="andThen" src="https://user-images.githubusercontent.com/184683/74589872-4dcc0280-4fd7-11ea-9ce7-132cebe7bfd9.png">

#### (Chrome, new-tab) applyOrElse[A1<:A,B1>:B](x:A1,default:A1=>B1):B1

<img width="1011" alt="applyOrElse" src="https://user-images.githubusercontent.com/184683/74589893-7ce27400-4fd7-11ea-956c-75d9a7034a25.png">

#### (Chrome, new-tab) unlift:PartialFunction[A,B]

<img width="1021" alt="unlift" src="https://user-images.githubusercontent.com/184683/74589907-a9968b80-4fd7-11ea-9a73-a720827e21bf.png">

### notes

I'm guessing that this has something to do with `<` and `>`?

**Comment by hrhino** [comment]
I got here via GitHub notifications, and what do you know?

![20200215_135844](https://user-images.githubusercontent.com/28076058/74593594-cabca380-4ffa-11ea-8ab3-673e5da56574.jpg)

**Comment by eed3si9n** [comment]
@zerosum sent a PR for this from ScalaMatsuri 2020 hackathon - https://github.com/scala/scala/pull/9252

**Comment by SethTisue** [comment]
@zerosum if you comment here, we'll assign you the ticket (for credit/glory)

**Comment by zerosum** [comment]
@SethTisue ❤️
