### ISSUE TITLE
-Xpluginsdir Setting Appears Nonfunctional Starting with 2.12.9

### ISSUE THREAD

**Issue by dccorona** [scala/bug#11802]
It appears that this commit (originally for 2.13, but backported to 2.12 starting from 2.12.9) breaks (intentionally or otherwise) the `-Xpluginsdir` setting:

https://github.com/scala/scala/commit/bec58990dda5be70ab34b152537e0f8d102084ee

Specifically, it appears that the method `Plugin.loadAllFrom` completely ignores the `dirs` argument, which is where the value of `-Xpluginsdir` is passed when searching for plugins.

I have confirmed this against the binary distribution of 2.12.9, 2.12.10, and 2.13.1 (2.12.8 works) using [kind-projector](https://github.com/typelevel/kind-projector)

From within the extracted binary distribution for any of the above versions:

```
bin/scalac -Xpluginsdir path/to/directory/containing/kindprojector/jar -Xplugin-list
```

For `2.12.9+`, the above spits out nothing. But on `2.12.8-`, it outputs:

```
kind-projector - Expand type lambda syntax
```

But this works on `2.12.9+`:

```
bin/scalac -Xplugin:path/to/directory/containing/kindprojector/jar/kind-projector.jar -Xplugin-list
```

Was the intent to deprecate this compiler option? If so, what is supposed to be the alternative to build tools that want to avoid referencing each compiler plugin JAR explicitly?

**Comment by SethTisue** [comment]
paging @retronym

**Comment by som-snytt** [comment]
I'll take a look. FSR it never got a partest.

**Comment by som-snytt** [comment]
Looks like it's broken.
```
$ cat test/files/run/t11802-pluginsdir-run.log
error: Missing required plugin: ploogin
```

**Comment by som-snytt** [comment]
I had the mistaken idea that the pluginsdir could hold an exploded archive, i.e., that it would detect and use `myplugins/scalac-plugin.xml`.

The behavior re-implemented here is that each jar or zip in pluginsdir is like `-Xplugin:myplugins/file.jar` except that archives that don't supply a plugin are silently ignored. (Presumably such a dir may be a build output dir with other artifacts in it.)

**Comment by dccorona** [comment]
Thanks for adding this back. Will this commit be backported to 2.12.x?

**Comment by som-snytt** [comment]
There are two associated PRs, for each of 2.12.x and 2.13.x. I neglected to mark one `no-merge`.
