### ISSUE TITLE
With `-release 8` in JDK 11 some classes are not found

### ISSUE THREAD

**Issue by jrudolph** [scala/bug#11814]
```
> scala -release 8 -e "println(sun.misc.Unsafe.getUnsafe)"

/tmp/scalacmd476803211499913445.scala:1: error: not found: value sun
println(sun.misc.Unsafe.getUnsafe)
        ^
one error found
```

It seems related to #11679 where the suggestion was to add the JDK 8 `rt.jar` to the compilation class path instead of using `-release 8`. That's what we did in akka but it led to other issues, so we'd rather like to use `-release 8` instead (https://github.com/akka/akka/issues/27079).

**Comment by lrytz** [comment]
Workaround ideas:

1) use reflection, like we do in the standard library (https://github.com/scala/scala/blob/2.13.x/src/library/scala/runtime/Statics.java#L151-L188)

2) you could have a module (or an external dependency) that defines the parts of the API that you use in akka, and mark it `% "provided"`

```
package sun.misc;
public final class Unsafe {
  public static Unsafe getUnsafe() { throw new RuntimeException(); }
  ...
}
```

**Comment by jrudolph** [comment]
It seems just accessing it from java files just seems to work so a shim in front of Unsafe might also just be fine as long as the types are not exported so they end up in scala.

>     1. use reflection, like we do in the standard library ([scala/scala:src/library/scala/runtime/Statics.java@`2.13.x`#L151-L188](https://github.com/scala/scala/blob/2.13.x/src/library/scala/runtime/Statics.java#L151-L188) [](/scala/scala/blob/HEAD@{2019-11-28T12:50:00Z}/src/library/scala/runtime/Statics.java#L151-L188)

I guess, the reflection overhead is better using `MethodHandles` than going through `invoke` reflection? Otherwise, I guess it might be prohibitive for our use cases where the Unsafe usage is in the high-performance internals.

**Comment by lrytz** [comment]
> reflection overhead is better using `MethodHandles` than going through `invoke` reflection?

That's the promise - @retronym says on https://github.com/scala/scala/pull/6425 "We use method handle based reflection to achieve this. This has zero runtime overhead in the manner used."

**Comment by jrudolph** [comment]
Thanks for the confirmation, @lrytz. That might then indeed be a way forward and might also allow an incremental path to use `VarHandles` with supporting JDKs.

**Comment by jrudolph** [comment]
> It seems just accessing it from java files just seems to work so a shim in front of Unsafe might also just be fine as long as the types are not exported so they end up in scala.

As @raboof pointed out, `javac` seems to have exactly same issue, so I was wrong about that workaround above. Compiling an equivalent Java file with a JDK 11 `javac --release 8` fails with a similar issue (see also [8214165](https://bugs.openjdk.java.net/browse/JDK-8214165)).

We can close this now but thanks for the additional workaround pointers.
