### ISSUE TITLE
Accommodate BlockContext for locking

### ISSUE THREAD

**Issue by leventov** [scala/bug#11829]
I think it would be nice if Scala supported `blocking {}`-style operations with Locks.

For example:
```scala
val myLock: ReentrantLock

withLock(myLock) {
  ...
}
```

Where withLock is a Scala library function along the lines of:
```scala
def withLock[T](lock: Lock)(thunk: () => T): T = {
  BlockContext.current.lock(lock)
  try {
    thunk
  } finally {
    lock.unlock()
  }
}
```

`BlockContext.lock()` is a new function which is `lock.lock()` in the default BlockingContext, and uses [`ManagedLocker`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ForkJoinPool.ManagedBlocker.html) from the Javadoc of `ManagedBlocker` in FP-related `BlockContext` in `ExecutionContextImpl`.

**Comment by SethTisue** [comment]
It's better to make a proposal like this on https://contributors.scala-lang.org

**Comment by SethTisue** [comment]
https://contributors.scala-lang.org/t/accommodate-blockcontext-for-locking/3884
