### ISSUE TITLE
segmentLength is confusing

### ISSUE THREAD

**Issue by Jasper-M** [scala/bug#11821]
The scaladoc of `segmentLength` says

> Computes length of longest segment whose elements all satisfy some predicate.
>
> __returns__ the length of the longest segment of this sequence such that every element of the segment satisfies the predicate `p`.

From reading the name of the method and this explanation, which of these is true?

```
"yxxyyxxxyy".segmentLength(_ == 'x') == 0

"yxxyyxxxyy".segmentLength(_ == 'x') == 3
```

Maybe I'm crazy but I would think the second one. However, it's the first.

Same thing for the overload with a `from` parameter.

**Comment by SethTisue** [comment]
a pull request bringing the documentation in line with reality would be welcome.

it used to be called `prefixLength`. @szeiger do you know why it changed? (in your commit scala/scala@3993526a8140e779b488ad3adf4f288dbef2586f)

**Comment by ganchurin** [comment]
@SethTisue May I take this one?

**Comment by SethTisue** [comment]
go for it!

**Comment by ganchurin** [comment]
Opened a pull request. Please take a look when you have time.
