### ISSUE TITLE
Issue for issue templates

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11831]
Scala 2 almost got an issue template via [One small nudge for a bug, a giant time-saver for us.](https://github.com/eed3si9n/bug/commit/6e59729666ae50cfb2dfd0d54457385d0670667e)

Since dotty will bring the fancy templates we envy, and probably more guidance will be required for posting Scala 2 bugs during and after the transition, perhaps we could install issue templates now.

For example, library enhancements could receive the 3.2 milestone. The template could ask for the result in dotty, or just a checkbox for Fixed in dotty?

Now that there is an issue for issue templates, someone may step up and contribute.

**Comment by SethTisue** [comment]
@eed3si9n is on Team Issue Template. you two can bond over it

I think any templates should be kept short & sweet, and I think the Dotty ones are good examples of that

**Comment by eed3si9n** [comment]
Dotty uses GitHub's new Choose UI - https://github.com/lampepfl/dotty/issues/new/choose
I do that on sbt as well - https://github.com/sbt/sbt/issues/new/choose

If @SethTisue would be on board with Team Issue Template if we adopted Dotty's template (sans feature request and syntax highlight reports), I'd be happy to do so.

Would that convince @lrytz?

**Comment by som-snytt** [comment]
We propose the template eschew `"Description"` or `minimized code` for:

## I contrived a fairly trivial example to illustrate my point as follows:

https://stackoverflow.com/questions/59596386/protected-method-that-takes-an-abstract-super-class-instance-and-the-access-to/59596881#comment105358506_59596386

**Comment by lrytz** [comment]
I see value in reporters having to select "🐛 Bug report", and provide other categories like "question" or "feature request" where the template would say "please don't open an issue here, instead go there".

The issue template for bugs itself, I personally still consider it unnecessary overhead.

**Comment by som-snytt** [comment]
The bug report option could just redirect them to the dotty getting started page.

**Comment by som-snytt** [comment]
Take [a gander](https://github.com/lampepfl/dotty/issues/7934) (scroll down).

**Comment by eed3si9n** [comment]
Exhibit https://github.com/scala/bug/issues/11891

> For Example this is the input Data, where I need relation tree like below output :

> (large JSON)

**Comment by eed3si9n** [comment]
Here's another PR for this - https://github.com/scala/bug/pull/11893
