### ISSUE TITLE
traits and self-type cause java.lang.AbstractMethodError 

### ISSUE THREAD

**Issue by dieu** [scala/bug#11833]
Hello,

I have a simple code which throws an error on 2.12.x+ but work perfectly fine on dotty. 

```
abstract class Base[T] {
  type Type = T
  
  def methodOp(arg: Type): Unit = {
    this match {
      case m: Base[T] with Mark =>
        m.method(arg.asInstanceOf[m.Type]) throw java.lang.AbstractMethodError Apps$.method(Ljava/lang/Object;)V
      case _ =>
      
    }
  }
}

trait Mark { this: Base[_] => 
  def method(arg: Type): Unit
}

object Apps extends Base[Int] with Mark {
  override def method(arg: Apps.Type): Unit = {
    println(arg)
  }
}
```

https://scastie.scala-lang.org/ndlr1yZiSyiuORdjAvULmw

works with dotty:

https://scastie.scala-lang.org/nG7jh4zpRKWB9P20WuoXZw

Is it possible to work around this error?

**Comment by som-snytt** [comment]
I don't see any workaround on https://github.com/scala/bug/issues/8681

**Comment by eed3si9n** [comment]
Looks like we can close this. Also in general questions should be on Scala Users or Stackoverflow - https://www.scala-lang.org/community/

**Comment by dieu** [comment]
@som-snytt  @eed3si9n 

JFYI: We found a workaround to force the scala compiler to generated the bridge method.

```
def method[T <: Type](arg: T): Unit  
```

https://scastie.scala-lang.org/dih0xBjORWa65k901ekT6w
