### ISSUE TITLE
REPL loses multicolumn alignment with non-ascii

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11834]
Tabulation in REPL doesn't seem to compute the display width of non-ascii characters correctly.

From sample autocomplete of `:load` showing files in two columns:

```
second                                    connect                                     
𝔘𝔫𝔦𝔠𝔬𝔡𝔢                            catty.scala                                 
t2.out                                    door.scala 
```

**Comment by SethTisue** [comment]
not sure whether "good first issue"

**Comment by som-snytt** [comment]
"Good first issue on doti."

**Comment by steven-barnes** [comment]
I have taken this as my First Issue, and have fixed it by counting code points instead of characters. This will not work for strings that use Unicode combining characters. Is this acceptable, or do I need to handle combining characters?

**Comment by SethTisue** [comment]
I think a PR would be accepted even if it didn't handle combining characters. You can choose your ambition level on this.

**Comment by som-snytt** [comment]
I vaguely remember opening this issue, but I can't believe it was only a couple of weeks ago, it feels like last year!

The example was on my Mac. I just pasted it on my Ubuntu, where it looks terrible. It has weird internal spacing so it does fill seven spaces.

I wonder if there is a jline3 way to get the display width of strings.

I asked the French guy on his way out to lunch and he just looked at me funny. He insists on all diacritics, all the time, but I guess he doesn't i18n.

**Comment by steven-barnes** [comment]
Using BreakIterator was easier than I thought, so it handles combining characters. PR is here: https://github.com/scala/scala/pull/8631

Let me know if I did anything wrong

**Comment by martijnhoekstra** [comment]
I'm pleasantly surprised this was doable :+1:

**Comment by som-snytt** [comment]
I'm pleasantly surprised someone did it!
