### ISSUE TITLE
Scala signature package has wrong version expected 5.0 found 5.2 in package class

### ISSUE THREAD

**Issue by ahamedfo** [scala/bug#11847]
Error:scalac: error while loading package, class file 'C:\Users\ahafo\.ivy2\cache\org.scala-lang\scala-library\jars\scala-library-2.13.0.jar(scala/collection/mutable/package.class)' is broken
(class java.lang.RuntimeException/error reading Scala signature of package.class: Scala signature package has wrong version
 expected: 5.0
 found: 5.2 in package.class)

**Comment by ahamedfo** [comment]
Im not really sure why one of my prior files no longer works I have seen others ask this question but am unsure of the answer.

**Comment by ashawley** [comment]
This sounds like a plea for help, and not a bug report.  For getting help with using Scala, see the resources on the community page:

https://scala-lang.org/community/

Or the `CONTRIBUTING` file in this repo:

https://github.com/scala/bug/blob/master/CONTRIBUTING.md

**Comment by som-snytt** [comment]
This is due to using a pre-2.13 compiler with the 2.13 library on the class path.

When this question is posted to gitter, mention your build set-up.

This can happen by supplying `-toolcp` or a stale `CLASSPATH` in the environment.
