### ISSUE TITLE
Them's the breaks

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11842]
aka You break it, you bought it.

`breakable` is no longer a darling, but it is still underdocumented and undeprecated.

Witness https://stackoverflow.com/questions/59543974/scala-break-inner-loop

**Comment by SethTisue** [comment]
Ma Bell sends you a whopping bill / With eighteen phone calls to Brazil!

**Comment by som-snytt** [comment]
Oh man, I deserve a break tonight.

Somebody say all right!

**Comment by som-snytt** [comment]
>  underdocumented and undeprecated

and underappreciated!

**Comment by steven-barnes** [comment]
I am a bit confused here... The answer to the Stackoverflow question is pretty obvious. So you want more documentation for Breaks? Does it need to be deprecated?

**Comment by som-snytt** [comment]
Anyone who addresses this may re-use my punning mnemonic: "breakable is not a break label."

Probably if the current minimalist documentation seems sufficient to you, this is not a good second issue for you.

**Comment by SethTisue** [comment]
@som-snytt I don't think we should leave this issue open unless either 1) you're planning on tackling it yourself, in which case let's assign it to you, or 2) you can be more specific about what's under-documented. I don't think scala/bug is a good place for a bunch of left-open-indefinitely "X should be documented better" tickets, surely there are a great may such Xs

**Comment by som-snytt** [comment]
I guess I bought it.

**Comment by som-snytt** [comment]
@SethTisue I had to say that `break` relies on "empty application". Then I wondered why does `break` have parens? DYK it was originally `def break { throw up }` until paulp added the "side-effecting" lint and also added parens. The funny thing is that `def f: Nothing = ???` doesn't warn. We could have left it parenless as the Good Lord intended.
