### ISSUE TITLE
Tab completion for aliased constructors in REPL

### ISSUE THREAD

**Issue by Jasper-M** [scala/bug#11846]
```
scala> class Foo(i: Int) { def this(s: String) = this(s.toInt) }
defined class Foo

scala> new Foo
   def <init>(i: Int): Foo   def <init>(s: String): Foo

scala> type Bar = Foo
defined type alias Bar

scala> new Bar
   type Bar = Bar
```

`type Bar = Bar` very informative by the way. Perhaps fix the tab completion for type aliases in general while we're at it...

In constructor position I would just expect `def <init>(i: Int): Foo   def <init>(s: String): Foo` though.

**Comment by SethTisue** [comment]
Note that Metals uses the REPL's tab-completion code, so I would expect this to benefit Metals as well.

**Comment by Jasper-M** [comment]
In case that wasn't clear, this also affects tab completion on things like `new String` since `String` is an alias.

**Comment by jxnu-liguobin** [comment]
Hi @SethTisue. I'm going to see this.  Is it expensive to solve this issue or will the change be great? Does this mean that for repl, the alias is ignored?

**Comment by SethTisue** [comment]
> Is it expensive to solve this issue or will the change be great?

I don't know. I think there's a good chance it will be easy, but I can't be sure.

> Does this mean that for repl, the alias is ignored?

Not sure what you mean?

**Comment by jxnu-liguobin** [comment]
I hope no one wants to show ` type bar = bar` 😅

**Comment by jxnu-liguobin** [comment]
> Not sure what you mean?

I hope no one wants to show ` type bar = bar` 😅
