### ISSUE TITLE
Scala 2.13.1 regression: Crash on lazy vals initialised from class parameters 

### ISSUE THREAD

**Issue by TJC** [scala/bug#11855]
## Description

Regression when upgrading from Scala 2.12.10 to 2.13.1:
'lazy vals' cause java.lang.IllegalAccessError if they are initialised with a class parameter.

```scala
class LazyConstructors(thingCons: (String) => MyThing) {
  lazy val thing: MyThing = thingCons("foo")
  def callMe = thing.toString
}
```

```
java.lang.IllegalAccessError: Update to non-static final field example.LazyConstructors.thingCons attempted from a different method (thing$lzycompute) than the initializer method <init> .
```

### Workaround

In the above code, making this change results in the code no longer crashing -- just defining the class parameter as a `val`

```scala
class LazyConstructors(val thingCons: (String) => MyThing)
```

## Environment:

- Scala 2.13.1
- OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
- sbt 1.3.7

## Runnable code demonstrating issue

https://github.com/TJC/scala-2.13-lazy-val-issue

Check out the repo, _ensure you have JDK 11_, and then run `sbt test`

**Comment by TJC** [comment]
Looks like this is a duplicate of #11781

**Comment by som-snytt** [comment]
Did that fix not merge forward?

**Comment by som-snytt** [comment]
The fix just missed the previous forward merge by a couple of days.

**Comment by TJC** [comment]
Ah, oh no!
But it'll definitely be coming along in 2.13.2 then? That's good to know.

**Comment by dwijnand** [comment]
Yep.
