### ISSUE TITLE
Local shadowing doesn't work in Scala 2.13

### ISSUE THREAD

**Issue by andreaTP** [scala/bug#11861]
Locally defined names are not hiding imported ones.

e.g.: in a project define an `object` in two separate packages:
```scala
package example.pkg

object Lib {
  val answer = "NOT expected"
}
```
and:
```scala
package example

object Lib {
  val answer = "NOT expected"
}
```
invoke `Lib.answer` in the `example` package while importing `example.pkg.Lib` such as:
```scala
package example

import example.pkg.Lib

object Main extends App {
  println(Lib.answer)
}
```
we have:
 - Scala up to 2.12 -> emit a warning: `imported Lib' is permanently hidden by definition of object Lib in package example` and pick up the implementation in the `example` package
 - Scala 2.13.0 and 2.13.1 -> do not emit the warning and pick up the implementation of `Lib` in package `example.pkg`

I created a full repro here:
https://github.com/andreaTP/repro_scala213_shadowing
running `repro.sh` shows the bug.

It is my understanding that this is indeed a bug and not a desired behavior since the code emitting the warning is still there:
https://github.com/scala/scala/blob/eb1ea8b367f9b240afc0b16184396fa3bbf7e37c/src/compiler/scala/tools/nsc/typechecker/Namers.scala#L555

**Comment by som-snytt** [comment]
The old behavior was not [per spec](https://scala-lang.org/files/archive/spec/2.13/02-identifiers-names-and-scopes.html).

It matters if the definition is in the current compilation unit (file) or defined elsewhere.

The warning is shown in [a test](https://github.com/scala/scala/blob/2.13.x/test/files/neg/permanent-blindness.scala).

**Comment by andreaTP** [comment]
Thanks for the explanation!
