### ISSUE TITLE
Undefined behavior of implicit shadowing in scalac

### ISSUE THREAD

**Issue by v-gerasimov** [scala/bug#11860]
```scala
trait Writer[A] {
  def write(value: A): String
}

object Writer {
  implicit val stringWriter: Writer[String] = new Writer[String] {
    override def write(value: String): String = value
  }
}

object Foo {
  implicit val string2foo: Writer[String] = new Writer[String] {
    override def write(value: String): String = "foo"
  }
}

object A extends  App {
  import Foo._

  implicit class WriterOps[A](value: A) {
    def toWrappedString(implicit w: Writer[A]): String = w.write(value)
  }

 //object Foo has the implicit with the same name
  implicit val string2foo: Writer[String] = new Writer[String] {
    override def write(value: String): String = "foo"
  }

  val foo = "Hello".toWrappedString
  println(foo) //prints "foo"
  println("Hello".toWrappedString) //prints "Hello"
}
```

Scala is 2.12.10 and 2.13.1.

**Comment by Jasper-M** [comment]
Doesn't seem to be related to the order of the code. The difference seems to be in whether the expression `"Hello".toWrappedString` has an expected type or not.

```
val a: Any = "Hello".toWrappedString
println(a) //prints "Hello"

val b = "Hello".toWrappedString
println(b) //prints "foo"

val c: String = "Hello".toWrappedString
println(c) //prints "Hello"

val d = "Hello".toWrappedString
println(d) //still prints "foo"
```

And if you put the code in a def instead of an object it always prints `foo`.

**Comment by dwijnand** [comment]
So just importing `Foo._` brings `string2foo: Writer[String]` into scope, so it should always be used for all strings.  When you then introduce a shadowing binding `string2foo: Writer[String]` then normally that replaces the previous implicit (not ambiguous).  However here it seems that:

* that is the behaviour when the type is inferred
* that's not the behaviour there's an expected `Any` or `String` type

🤔

**Comment by dwijnand** [comment]
So it seems when type inference is involved then the shadowing happens ("as intended"?), but when it's not, then they're ambiguous so the non-foo instance wins (because its in the implicit scope)?

**Comment by som-snytt** [comment]
No one mentioned that doti prefers `Foo.string2Foo` for both cases, which is self-consistent but makes the least sense to me, from what little I know about doti.
```
➜  snips dotc t11860.scala
➜  snips dotr A
foo
foo
```

**Comment by Jasper-M** [comment]
It's not really a `delayedinit` problem. The same thing happens with regular objects. Or with classes.
```
object RegularObject {
  import Foo._
  implicit val string2foo: Writer[String] = _ => "foo"

  val a: String = "Hello".toWrappedString // Hello
  val b = "Hello".toWrappedString // foo
}
```

It's more an instance variable vs local variable thing.

**Comment by som-snytt** [comment]
In coding, we should say, "Foo me once, shame on you, etc."

**Comment by dwijnand** [comment]
... foo me twice, you're bar'd?

**Comment by Jasper-M** [comment]
Could it be related to the stuff that's happening in scala/scala#8441? Something weird about the implicit scope in the constructor body?

**Comment by dwijnand** [comment]
Perhaps.  But I just ran my test script with the HEAD of 2.13.x and it behaves the same.

**Comment by Jasper-M** [comment]
Yeah doesn't seem to be exactly the same thing. It's more like how Trump and Brexit are related. Not the same thing but similar underlying cause.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/9208

See comments from 2016.

**Comment by dwijnand** [comment]
Duplicate of #9208

**Comment by som-snytt** [comment]
Added as a test to the linked PR.
