### ISSUE TITLE
Scala documentation template unfriendly for non-mouse users

### ISSUE THREAD

**Issue by cfraizer** [scala/bug#11878]
Since the days of NCSA Mosaic, every major graphical browser has, drawing on the venerable tradition of `more`, used `<SPACE>` to indicate "scroll forward one page". This is built-in behavior, not something that requires script.

Every page of Scala API documentation, when initially loaded, eats those keypresses and ignores them. To scroll through Scala documentation, one must use the mouse to click in the body of the page, after which `<SPACE>` (and `<SHIFT+SPACE>`) work as expected.

This is not an obvious "keyboard focus" issue. That is, `document.activeElement` is the `<BODY>` element both *before* and *after* clicking on the page. (When focus is in an `<INPUT>` element, of course, that field should take the `SPACE` characters. When that happens, `document.activeElement` refers to the `<INPUT>` element itself.)

Why do I care? I have "shaky hands" because of a medical condition. It means my mouse clicks often don't land where I intend, so I tend not to use the darned thing. 

Verified that this occurs with both Chrome and Firefox with the documentation page [Array](https://www.scala-lang.org/api/current/scala/Array.html). It actually happens (unsurprisingly) on every Scala API page.

My amateurish attempts to figure out what is eating those keyboard events just left me confused, but I would be happy to help if someone could offer advice.  (The path leads through minimized jquery code.)

**Comment by Prithvirajbilla** [comment]
This issue is happening because of how the content is located /positioned on the dom. (currently using `absolute ` position).

I went ahead and removed position css attribute for element `div#content-scroll-container` . And everything is working as expected. 

Attached screenshot.

![Spacebar_Issue](https://user-images.githubusercontent.com/1584221/74596690-9bb92880-5020-11ea-8ea5-00c85cc5505c.PNG)

**Comment by SethTisue** [comment]
Sounds good! (Though I don't know anything about front-end stuff...)

Care to PR it...?

**Comment by Prithvirajbilla** [comment]
yes. I will make a PR.

**Comment by cfraizer** [comment]
Thank you @Prithvirajbilla.
