### ISSUE TITLE
optimizer command line flags cleanup

### ISSUE THREAD

**Issue by lrytz** [scala/bug#11873]
Split out of https://github.com/scala/bug/issues/11746#issuecomment-534015696

  - ~make `-opt:_` work~ done in https://github.com/scala/scala/pull/8454
  - `opt:inline` and `-opt:l:inline` could be confusing, we should probably rename `l:inline`
  - update https://www.lightbend.com/blog/scala-inliner-optimizer to mention the `-V` flags

**Comment by som-snytt** [comment]
I'll take an initial swipe at this. I've always wanted to learn the optimizer options. The biggest problem for me isn't the spelling of optimizer but the common prefix opt. That's bad optics, ha.

Thanks for the blog link, I wondered why I couldn't find it again: it's not the scala blog, it's the proprietary blog.

I guess knowing how the optimizer options work is a competitive advantage.

**Comment by som-snytt** [comment]
I think I was considering:
```
-opt:none  (was -opt:l:none)
X-opt           (was -opt:l:default)
X-opt:no-inline (was -opt:l:method)
-opt:default      (was -opt:l:default)
-opt          (was -opt:l:method)
-opt:inline:**  (was -opt:l:inline -opt-inline-from:**)
```
or similar. Would anyone want inline without method? It's like car packages, you upgrade to get a feature, but you don't delete features.

**Comment by lrytz** [comment]
- Agree to drop the `l:` in principle, but `-opt:inline` would change from only enabiling the inliner to enable all optimizations. Is that fine? Do we need to keep the possibility to select the inliner specifically?
- I like the `opt:inline:**` idea - would it accept only `**` or all of the patterns of `-opt-inline-from`?
- Plain `-opt`, I'm not sure. I find `opt:method` quite clear, or alternatively `opt:local`.
- Not sure what you mean by `X-opt`

**Comment by som-snytt** [comment]
The X meant a rejected form.

I coded the `-opt:inline:thing` parsing.

Oh, maybe `opt:local`. I couldn't think of a good name, but it felt like a good `-opt`, what we want to upgrade from the minimal to.

On upgrading, I think the car option package analogy is apt, but maybe you can disable a la carte. I haven't tried that yet.

**Comment by som-snytt** [comment]
Also, sorry to deprecate the `-opt:l:` for `-opt:lukas` syntax.

**Comment by dwijnand** [comment]
@som-snytt still interested in this?

**Comment by som-snytt** [comment]
This makes me nostalgic for pre-pandemic days when it seemed like we had all the time in the world.

**Comment by SethTisue** [comment]
@som-snytt did the PR fix all of the todos in the issue description, or just some of them?

**Comment by som-snytt** [comment]
I don't mind either updating the old blog (if someone shows me where the source is) or creating a new overview page.

That is the last mile.

**Comment by SethTisue** [comment]
oh, I forgot that the blog post is on Lightbend's site, rather than a Scala site.

at the time (2018), there was something of a push to call attention to Lightbend's role in Scala development, but I think that aspect of the blog post's purpose is now fulfilled, and it would now really be better to have it live on a Scala site going forward

So: if you want to make a new overview page on docs.scala-lang.org, that would be amaaaaazing and much appreciated. After it was merged, I or Lukas would take care of updating the blog post to include a notice at the top redirecting readers to the new page.

here's the source: https://gist.github.com/SethTisue/055d02ec81e7a0f8033c5ab9348bd817

**Comment by som-snytt** [comment]
The associated doc PR at https://github.com/scala/docs.scala-lang/pull/2336 which I'd already forgotten if I'd written it. I also forget that doc PRs go on that other repo.

**Comment by SethTisue** [comment]
https://github.com/lightbend/techhub-blog/pull/102
