### ISSUE TITLE
Support for traits with context bounds

### ISSUE THREAD

**Issue by shea-engagio** [scala/bug#11876]
Hey all, this is an oldie but a goodie. When defining traits, you aren't able to put a context bound on the type parameter so that you can enforce that the type paramater has a Manifest. We all know _why_ this is the case, ostensibly. Traits are not allowed to have paramaters. However, implicit context bounds where we reach a gray area.

The compiler doesn't support this clearly, but intentions to include it have been mentioned all the way back in [2011](https://www.scala-lang.org/old/node/11696). How is progress on this? Is there a project started?

**Comment by SethTisue** [comment]
please ask on https://contributors.scala-lang.org — the bug tracker is for bugs, not for questions
