### ISSUE TITLE
2.13.1 scalac StackOverflowError when annotation argument references the annottee

### ISSUE THREAD

**Issue by dbarvitsky** [scala/bug#11870]
Consider the example:
```scala

class Invariant(condition: Unit => Boolean) extends scala.annotation.StaticAnnotation
abstract class Demo {
  @Invariant( _ => x.length == 3 )
  def x: String = "foo"
}
```

This code results in the `java.lang.StackOverflowError` through `scala.reflect.internal.AnnotationInfos$LazyAnnotationInfo.forcedInfo$lzycompute(AnnotationInfos.scala:158)` ([scalac-SOE-stack.txt](https://github.com/scala/bug/files/4129572/scalac-SOE-stack.txt) has the full stack trace if you need it). As far as I can tell, the stack trace is different from those encountered in #7449, #1632, #1667 and #10421. Increasing the stack `-Xss128m` just makes the SOE stack trace longer, so it looks like cyclic init.

Some pointers to help narrow the problem.

1. The annotation argument does not have to be a lambda. The following snippet yields the same SOE: 
```scala
class Annot(arg: Any) extends scala.annotation.StaticAnnotation
abstract class Demo {
  @Annot(x)
  def x: String = "foo"
}
```

2. The following example compiles fine.
```scala
class Annot(arg: Any) extends scala.annotation.StaticAnnotation
abstract class Demo {
  @Annot(y)
  def x: String = "foo"
  def y: String = "bar"
}
```

3. However, if you put the annotation on the second field as well, there is the SOE again
```scala
class Annot(arg: Any) extends scala.annotation.StaticAnnotation
abstract class Demo {
  @Annot(y)
  def x: String = "foo"

 @Annot(x)
  def y: String = "bar"
}
```

4. Finally, the code below causes SOE even when the annotations are different.
```scala
class Annot1(arg: Any) extends scala.annotation.StaticAnnotation
class Annot2(arg: Any) extends scala.annotation.StaticAnnotation
abstract class Demo {
  @Annot1(y)
  def x: String = "foo"

  @Annot2(x)
  def y: String = "bar"
}
```

Thank you!

**Comment by hrhino** [comment]
I'm going to tentatively point the finger at scala/scala#8338 here (without bisecting) because that seems to be the reason we're looking to inspect the annotations of `x` at all (to see if it's `@uncheckedStable`).

It's a tricky one: can we perhaps make `AnnotationInfo`s a little bit less lazy (so that we do know their type symbol during `annotSig` even if we don't know their type nor args)?

**Comment by lrytz** [comment]
I didn't realize this is a regression

**Comment by SethTisue** [comment]
@changvvb if you comment here, I think GitHub will allow me to assign you the issue

**Comment by changvvb** [comment]
Ok, I'm here.

**Comment by lrytz** [comment]
original fix reverted in https://github.com/scala/scala/pull/9069
