### ISSUE TITLE
Scala REPL assigning to `res<n>` throwing error only the first time

### ISSUE THREAD

**Issue by code-shoily** [scala/bug#11877]
Hello, I just started learning Scala today, while playing around with the REPL, I assigned `val res5 = 42` when `res5` was supposed to be result number. After that, as I tried to do a `"Answer " + res5` it threw an error first and on following usage it didn't. I am not sure if it's a bug or if there's an explanation behind it but figured I should report this. I am attaching a screenshot of it.

<img width="632" alt="Screen Shot 2020-02-01 at 9 13 52 PM" src="https://user-images.githubusercontent.com/5702155/73601910-d195e180-4537-11ea-94fa-7b10b6a6f93e.png">

```
scala> x
res28: Int = 20

scala> val res29 = 0
res29: Int = 0

scala> "Zero " + res29
                 ^
       error: recursive value res29 needs type

scala> "Zero " + res29
res30: String = Zero 0

scala>
```

**Comment by yawaramin** [comment]
Able to reproduce:

```
scala
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> 1
res0: Int = 1

scala> val res1 = 42
res1: Int = 42

scala> "Life " + res1
                 ^
       error: recursive value res1 needs type

scala> "Life " + res1
res2: String = Life 42
```

**Comment by som-snytt** [comment]
You can use `scala -Dscala.repl.debug` to show how your code snippets are wrapped. It doesn't try to be clever when assigning results to `resN`, it just bumps a counter.

The one place it's a bit clever is when you paste a transcript which uses results:

```
scala> 42
res0: Int = 42

scala> res0 + 1
res1: Int = 43

scala> scala> 42

// Detected repl transcript. Paste more, or ctrl-D to finish.

res0: Int = 42

scala> res0 + 1
res1: Int = 43
// Replaying 2 commands from transcript.

scala> val res0 = { 42 }
res0: Int = 42

scala> res0 + 1
res2: Int = 43
```

**Comment by yawaramin** [comment]
Thanks for the tip. I see what's happening now. As you said, it just bumps a counter. When we explicitly assign `res1`, the counter is still at 0 because the REPL doesn't bump it when the expression is explicitly assigned. So when we evaluate the next expression, it bumps it to 1 and ends up with:

    val res1 = "Life ".+(res1)

And that triggers:

    error: recursive value res1 needs type

When we evaluate the next expression it bumps the counter to 2 and ends up with:

    val res2 = " ".+(res1)

Which is not recursive and thus works.

**Comment by code-shoily** [comment]
That explains the error message. Thanks @som-snytt and @yawaramin

**Comment by dwijnand** [comment]
@som-snytt Do you think it's viable to fail this faster?  I'm thinking either make `val res29 = 0` illegal as it's using REPL "reserved" res*, or fast-fail `"Zero " + res29` given `res29` isn't defined.

**Comment by som-snytt** [comment]
It would be more user-friendly to warn than to confuse.

**Comment by unkarjedy** [comment]
Has anyone already tried to implement the warning / fail-fast / anything else?
I've just faced the same issue and was quite confused:

![image](https://user-images.githubusercontent.com/3989292/117269767-3e95d680-ae61-11eb-8af1-b28d6da195ad.png)
