### ISSUE TITLE
Overload resolution fails with vararg

### ISSUE THREAD

**Issue by tkrs** [scala/bug#11879]
Given the following code:

```scala
object A {
  val ok: OK = ???
  ok.f("ok")
  ok.f("ok", "ok")

  val ng: NG = ???
  ng.f("ng")
  ng.f("ok", "ok")

  val foo: Foo = ???
  foo.f("ok")
  foo.f("ok", "ok")
}

trait OK {
  def f(a: String): Unit
  def f(a: String*): Unit
}

trait X0 {
  def f(a: String): Unit
}
trait NG extends X0 {
  def f(a: String*): Unit
}
class Foo extends NG {
  def f(a: String): Unit = ???
  def f(a: String*): Unit = ???
}
```

Compiling with 2.13.1 gives the following error:

```
[error] /home/tkrs/work/scala/overloads/src/main/scala/A.scala:7:6: ambiguous reference to overloaded definition,
[error] both method f in trait NG of type (a: String*)Unit
[error] and  method f in trait X0 of type (a: String)Unit
[error] match argument types (String)
[error]   ng.f("ng")
[error]      ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Feb 6, 2020, 4:25:55 AM
```

If it is overloaded of the method defined in `super-trait?`, as with `trait NG`, the compilation will fail. However, there is no problem if it is defined in the same trait, as with `trait OK`.

**Comment by som-snytt** [comment]
`f(String)` is more specific than `f(String*)`, but `f(String*)` is defined in a subclass, which evens the score. More at SLS 6.26.3 https://www.scala-lang.org/files/archive/spec/2.13/06-expressions.html

A workaround is to prefer `f(String, String, String*)` for two or more.

**Comment by Jasper-M** [comment]
> f(String*) is defined in a subclass, which evens the score.

I still don't understand this logic. If I have a value of type `NG` I shouldn't care where which method comes from, or which method is overridden where.

**Comment by som-snytt** [comment]
Stipulating that overloading is evil, if by default you select the member that is most germane to the type (the one that is defined there), you can always upcast to select the other one.
```
scala> class C { def f(i: Int) = "x"*i } ; class D extends C { def f(s: String) = s*3 }
defined class C
defined class D

scala> val d = new D
d: D = D@659f226a

scala> d.f _
res0: String => String = $$Lambda$841/0x00000008005e0040@30aec673

scala> (d: C).f _
res1: Int => String = $$Lambda$852/0x00000008005e6040@2aea717c
```
