### ISSUE TITLE
import annotation._ is a drag for Seth

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11888]
Subj.

Don't repackage, just set `-Yimports` to include it.

Also, `import util.chaining._` is a drag.

**Comment by SethTisue** [comment]
I wonder if @odersky, or somebody, remembers if there was a design justification originally for this.

In case the subject line of the ticket isn't clear enough for somebody, this is about how come I have to write e.g. `@annotation.tailrec`, or do `import annotation._` before I can `@tailrec`. It's always annoyed me and I've always wondered about it, but perhaps there some justification for it that I'm not aware of.

**Comment by som-snytt** [comment]
The linked PR seeks justice for REPL. ✊ 

I don't actually know why the fist looks like Bart Simpson. Even with my computer glasses on, I'm having trouble counting the fingers.

**Comment by lrytz** [comment]
Adding a few type aliases to Predef would be binary compatible.

**Comment by odersky** [comment]
I think it was pretty much random. We cannot put all annotations in `scala` or `Predef`, that would pollute top-level namespaces too much. So some annotations ended up in `scala` and some in `scala.annotation`. 

I have a proposal to fix this at the root, rather than fiddling with some individual annotations: https://github.com/lampepfl/dotty/issues/8419

**Comment by som-snytt** [comment]
My crazed proposal would be on `@foo` if name lookup fails always try `annotation.foo`. That is stronger than the dotty proposal but also more uniform. `@foo` always implies `@annotation.foo` however that binds.

In any case, progress will be on Scala 3.

**Comment by odersky** [comment]
I think we should do this for Scala 3. I.e. when resolving an annotation we should also look in scala.annotations without requiring an explicit import. 

Maybe someone wants to open a SIP? I would be very supportive of that.
