### ISSUE TITLE
Strange error message when trying to override a val and calling super on the overriden val (2.13.1)

### ISSUE THREAD

**Issue by joostheijkoop** [scala/bug#11906]
## reproduction steps

use scala 2.13.1 or https://scalafiddle.io/sf/bSB8JgJ/3 (though in scala fiddle the `<none>` is left off) and try to compile this:

```scala
class Test {
  lazy val test: Seq[String] = Seq.empty
}

class Test2 extends Test {
  override val test: Seq[String] = super.test
}
```

## problem

The message is not very helpful and seems incomplete:

```
error: super may not be used on <none>
    override val test: Seq[String] = super.test
```

The `lazy` property seems to trigger the least informative message.

## expectation

a more informative complete error message, that explains what is and is not allowed like:
`super may not be used with a class' value members like Test#test, it is only allowed to be used with a method or a type`

**Comment by som-snytt** [comment]
Regressed in 2.12.0, perhaps because of fields?

Quick PR for lazy, which is an accessor without an accessed; and also augment the explanation.

doti is still terse.
