### ISSUE TITLE
SerialVersionUID on a trait does nothing and therefore should be disallowed

### ISSUE THREAD

**Issue by smarter** [scala/bug#11901]
## reproduction steps

```scala
@SerialVersionUID(1L)
trait T
```

## problem

This compiles, but the annotation doesn't actually do anything (and it can't do anything since we can't add a static field to an interface)

## expectation

This should emit an error, like https://github.com/lampepfl/dotty/pull/8429

**Comment by chuchao333** [comment]
I am going to work on this one, will try to get a PR up soon. Thanks

**Comment by som-snytt** [comment]
For your consideration:

```
$ scala -Xlint
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 11.0.3).
Type in expressions for evaluation. Or try :help.

scala> @SerialVersionUID(1L)
     | trait T
       trait T
             ^
On line 2: warning: @SerialVersionUID has no effect on traits
defined trait T
```
I acknowledge that smarter folks like smarter don't use linters.

**Comment by som-snytt** [comment]
Also, shout out to whoever made that sweet bug report template. @eed3si9n

**Comment by smarter** [comment]
Ah, it's hidden behind a lint flag, weird. I guess that's intentional so this can be closed.

**Comment by som-snytt** [comment]
Maybe duplicate of "use -Xlint -Werror by default".

**Comment by SethTisue** [comment]
excellent warriors use xlint werror

**Comment by som-snytt** [comment]
I will pay for that t-shirt, it doesn't even have to be a Scala Spree freebie.

Maybe on the back it could pun on "worrier".

**Comment by som-snytt** [comment]
The behavior https://github.com/scala/scala/pull/6174

The flag https://github.com/scala/scala/pull/6886

It looks like the flag was introduced to reduce noise? There is minimal discussion about whether the lint flag reduces effectiveness.

Maybe just making it an error is more effective.

**Comment by dwijnand** [comment]
> I will pay for that t-shirt, it doesn't even have to be a Scala Spree freebie.

I'm painting it on my Wall.
