### ISSUE TITLE
Trailing commas in function bodies and constructors

### ISSUE THREAD

**Issue by poslegm** [scala/bug#11900]
Hello! Scala compiler allows trailing comma in the lambda body, function body and constructors. Is it bug or correct behavior? Looks a little weird.

In a [SIP-27](https://docs.scala-lang.org/sips/trailing-commas.html) I've read:

> Following Dr. Martin Odersky’s suggestion, the proposal is that trailing commas are only supported in comma-separated elements that are enclosed by parentheses, square brackets or curly braces (), ], and }, respectively).

Is function bodies comma-separated elements?

## reproduction steps

```scala
List(1, 2, 3).map {
  a => a + 1,
}

class A() {
  println("a"),
}

def b() = {
  println("b"),
}

new A()
b()
```

## problem

Code compiles

## expectation

Code doesn't compile

Related https://github.com/scalameta/scalafmt/issues/1410#issuecomment-593132277

**Comment by som-snytt** [comment]
I just noticed this, too, and also consulted the docs and commit. The implementation is just in the scanner: COMMA, NL, RBRACE will ignore the COMMA. That is as opposed to emitting an IGNORABLE_COMMA which the parser could selectively ignore.

There was a recent fix for `type T,` which is tricky to observe in Scala 2, but Scala 3 still accepts a top-level `type T,` at EOF. (PR forthcoming.)

**Comment by som-snytt** [comment]
Quick acknowledgement of @dwijnand test case:
```
def f: (
  Int,
  String,
)
```
which I think will happen never, even in the universe where the monkeys type out the complete works of Shakespeare AND Borges's story about Pierre Menard AND Menard's complete works.

**Comment by neko-kai** [comment]
@som-snytt ur wrong that's my code

**Comment by som-snytt** [comment]
@neko-kai kudos to you! or neko-kai-kudos.

**Comment by OlegYch** [comment]
i claim that code as well

**Comment by Jasper-M** [comment]
It was my code

**Comment by SethTisue** [comment]
*I'm* Spartacus!

**Comment by som-snytt** [comment]
Now I'm not sure if I'm in the universe where the monkeys type comments responding to what the monkeys typed in the other universe.
