### ISSUE TITLE
Incorrect deprecation message: "Octal escape literals are deprecated, use ... instead"

### ISSUE THREAD

**Issue by MasseGuillaume** [scala/bug#11912]
## reproduction steps

compile the following:

```scala
println("\033c".hashCode())
```

## obtained

`\u001b`

```bash
Octal escape literals are deprecated, use \u001b instead.
[warn]       println("\033c".hashCode())
[warn]                ^
[warn] one warning found
```

## expectation

it should be `\u001bc`

```bash
Octal escape literals are deprecated, use \u001bc instead.
[warn]       println("\033c".hashCode())
[warn]                ^
[warn] one warning found

```

Scala 2.13.1
https://scastie.scala-lang.org/9hvZnukeQEisQ7aUrA56Hw

**Comment by som-snytt** [comment]
The recommendation specifies the character instead of repeating the whole text.
```
scala> "\012c".length
        ^
       error: octal escape literals are unsupported: use \n instead
```
If the question is how long is the patch, it should do the doti and `^^^^`.

**Comment by som-snytt** [comment]
BTW, on a branch somewhere I started looking at ranged carets. Maybe I'll get back to it.
