### ISSUE TITLE
IMain.valueOfTerm returns obsolete values in Scala 2.13

### ISSUE THREAD

**Issue by Sciss** [scala/bug#11915]
## reproduction steps

I created [a repository to reproduce](https://github.com/Sciss/ScalaIssue11915). Compare the output of `sbt ++2.12.11 run`:

```
[info] res0: Int = 1234
[info] res0: Int = 5678
[info] run1: 1234, run2: 5678
```

with the output of `sbt ++2.13.1 run`:

```
[info] res0: Int = 1234
[info] res0: Int = 5678
[info] run1: 1234, run2: 1234
```

## problem

So while the reporter prints the correct values, getting them from user code via `valueOfTerm` is broken under Scala 2.13.

The invocation at hand is

```scala
trait Base {
  _: IMain =>

  def test(): Unit = {
    val run1 = eval("1234")
    val run2 = eval("5678")
    println(s"run1: $run1, run2: $run2")
  }

  def eval(source: String): Any = {
    reset()
    val res: Results.Result = interpret(source)

    res match {
      case Results.Success =>
        val n = mostRecentVar
        valueOfTerm(n).getOrElse(sys.error(s"No value for term $n"))

      case Results.Error      => sys.error("failed")
      case Results.Incomplete => sys.error("incomplete")
    }
  }
}
```

Going into the implementation of `valueOfTerm`, one finds that under 2.12, a fresh `SynchronizedSymbol` is seen for the two subsequent `res0`, whereas under 2.13, the same symbol is returned twice, and consequently the same (old) value is returned in the second run.

**Comment by Sciss** [comment]
In the meantime, if there is any workaround for Scala 2.13, that would be great. Greating a fresh `IMain` for each `eval` means several hundres of milliseconds slowdown. the `reset()` call is essential because each call to `eval` must be isolated from the others.

**Comment by dwijnand** [comment]
@som-snytt/@SethTisue do either of you want to take this?  I wouldn't want to clash with your JLine or other in-flight/in-mind REPL changes.  If it's disconnected enough, let me know and I'll have a crack at this one.

**Comment by som-snytt** [comment]
I started looking. I'll continue looking a bit more, albeit supine. So nice to have a sample repo.

I assume it's the caching of classloaders and/or classpaths. I can update before I sign out, in case you want to prioritize it today.

**Comment by dwijnand** [comment]
No rush.  Pingback when you have an answer.

**Comment by Sciss** [comment]
So I found the issue basically. It's that `reset()` calls `resetClassLoader()` but this has no effect for `valueOfTerm` because it refers to `lazy val runtimeMirror = ru.runtimeMirror(classLoader)`.

if I "hack" [valueOfTerm](https://github.com/scala/scala/blob/39d3b3a93cd3cf01303ba9aba487b742943d8e57/src/repl/scala/tools/nsc/interpreter/IMain.scala#L1018) to insert a new `runtimeMirror`, the problem disappears:

```scala
  def valueOfTerm(id: String): Option[Any] = exitingTyper {
    def value(fullName: String) = {
      val runtimeMirror = ru.runtimeMirror(classLoader)  // shadow with fresh
      import runtimeMirror.universe.{Symbol, InstanceMirror, TermName}
```

**Comment by som-snytt** [comment]
Yes, I also just noticed that. :)
