### ISSUE TITLE
private[this] subverts override accessibility check

### ISSUE THREAD

**Issue by lrytz** [scala/bug#11913]
```scala
scala> class C { def f = 0 }
defined class C

scala> class D extends C { private[this] def f = 1 }
defined class D

scala> (new D).f
java.lang.IllegalAccessError: tried to access method D.f()I from class
  ... 28 elided
```

Should not compile. See the discussion at https://github.com/scala/scala/pull/8810#issuecomment-601053015

See also https://github.com/scala/bug/issues/11881

**Comment by dwijnand** [comment]
Keep for 2.13.4, or push to 2.13.5 or Backlog?

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/9334
