### ISSUE TITLE
inconsistent logic when override self type method

### ISSUE THREAD

**Issue by ohze** [scala/bug#11924]
## reproduction steps

+ pk1/A.scala
```scala
package pk1
class A {
  protected def f(): Unit = print("A")
}
```
+ Main.scala
```scala
import pk1.A

trait B { self: A =>
  override def f(): Unit = {
    print("B")
    self.f()
  }
}
class C extends A with B
object Main {
  def main(args: Array[String]): Unit = {
    new C().f()
  }
}
```

## problem
+ The code above run successfully
```
[info] running Main 
BA[success]...
```
+ But when remove the `protected` modifier from `A.f` =>
```scala
[info] running Main 
BBB...//many Bs
[error] java.lang.StackOverflowError
...
[error] 	at scala.Predef$.print(Predef.scala:385)
[error] 	at B.f(Main.scala:5)
[error] 	at B.f$(Main.scala:4)
[error] 	at C.f(Main.scala:9)
[error] 	at B.f(Main.scala:6)
[error] 	at B.f$(Main.scala:4)
[error] 	at C.f(Main.scala:9)
...
```
+ similar (StackOverflowError) if we move `A` from `pkg1` to default package (same package as B)
## expectation
IDK :)

**Comment by ohze** [comment]
Note: The above code is simplified from akka's:
[DockerBindDnsService.atStartup](https://github.com/akka/akka/blob/v2.6.4/akka-actor-tests/src/test/scala/akka/io/dns/DockerBindDnsService.scala#L27) override [AkkaSpec.atStartup](https://github.com/akka/akka/blob/v2.6.4/akka-testkit/src/test/scala/akka/testkit/AkkaSpec.scala#L135)

**Comment by lrytz** [comment]
I cannot reproduce this, I get the infinite recursion with both 2.12.11 and 2.13.1.

The infinite recursion seems to be the correct behavior, `(self: A).f()` is a virtual call.

**Comment by Jasper-M** [comment]
When I run this in the REPL I see the same as reported by ohze

```
scala> class A {
     |   protected def f(): Unit = print("A")
     | }
class A

scala> trait B { self: A =>
     |   override def f(): Unit = {
     |     print("B")
     |     self.f()
     |   }
     | }
     | class C extends A with B
     | object Main {
     |   def main(args: Array[String]): Unit = {
     |     new C().f()
     |   }
     | }
trait B
class C
object Main

scala> Main.main(Array())
BA
```

**Comment by lrytz** [comment]
Wow, i omitted the `package` declaration in `A`, and that makes a difference

```
   // access flags 0x1
   public default f()V
     GETSTATIC scala/Predef$.MODULE$ : Lscala/Predef$;
     LDC "B"
     INVOKEVIRTUAL scala/Predef$.print (Ljava/lang/Object;)V
     ALOAD 0
-    INVOKEINTERFACE B.B$$super$f ()V
+    CHECKCAST A
+    INVOKEVIRTUAL A.f ()V
     RETURN
```
