### ISSUE TITLE
Accessing some properties of the broken Symbol causes a forced error in macro deployment.

### ISSUE THREAD

**Issue by giiita** [scala/bug#11928]
## reproduction steps / problem

There are some classes in the library that have an IMPORT that cannot be resolved.
For example, [org.scalatest.tools.Framework](https://github.com/scalatest/scalatest/blob/3.1.x/scalatest/src/main/scala/org/scalatest/tools/Framework.scala#L29) in ScalaTest.

If I add scalatest as a dependent library, it will be added to the test classpath, but this import will not be resolved in the normal test classpath.
There is no SBT module in the test classpath.

```scala
import sbt.testing.{Event => SbtEvent, Framework => SbtFramework, Runner => SbtRunner, Status => SbtStatus, _}
```

Now, I want the macro to scan for classes under a specific package arrangement to find classes that have a specific function.

```scala
def collectXxx(targets: List[c.Symbol]) {
  targets.filter { x =>
    {
      x.isModule || (
        x.isClass &&
          !x.isAbstract &&
          x.asClass.primaryConstructor.isMethod
    } && x.typeSignature.baseClasses.contains(XxxTag.typeSymbol)
  }
}
```

This will filter to symbols that are object / class and inherit from Xxx.
This will work in most cases, but if there is a class in targets that cannot be compiled as is, such as scalatest, the compiler error cannot be avoided.
The moment baseClasses is accessed, the macro deployment status is set to global error.

```
[error] <macro>:1:26: Symbol 'type sbt.testing.Framework' is missing from the classpath.
[error] This symbol is required by 'class org.scalatest.tools.Framework'.
[error] Make sure that type Framework is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'Framework.class' was compiled against an incompatible version of sbt.testing.
[error] type `fresh$macro$612` = org.scalatest.tools.Framework
[error]                          ^

```

If you look at the stack trace in debug mode, I was setting global_error when I accessed each property of [StubClassSymbol](https://github.com/scala/scala/blob/75912fef4b330ee9d42415ecc72bd7eaab11dc02/src/reflect/scala/reflect/internal/Symbols.scala#L3596).

```
java.lang.Throwable
	at scala.reflect.internal.Symbols$StubSymbol.fail(Symbols.scala:3552)
	at scala.reflect.internal.Symbols$StubSymbol.info(Symbols.scala:3563)
	at scala.reflect.internal.Symbols$StubSymbol.info$(Symbols.scala:3563)
	at scala.reflect.internal.Symbols$StubClassSymbol.info(Symbols.scala:3567)
  | => cat scala.reflect.internal.Symbols$StubClassSymbol.info(Symbols.scala:3567)
	at scala.reflect.internal.Types$TypeRef.baseClasses(Types.scala:2593)
	at scala.reflect.internal.Types.computeBaseClasses(Types.scala:1703)
	at scala.reflect.internal.Types.computeBaseClasses$(Types.scala:1680)
	at scala.reflect.internal.SymbolTable.computeBaseClasses(SymbolTable.scala:28)
	at scala.reflect.internal.Types.$anonfun$defineBaseClassesOfCompoundType$2(Types.scala:1781)
	at scala.reflect.internal.Types$CompoundType.memo(Types.scala:1651)
	at scala.reflect.internal.Types.defineBaseClassesOfCompoundType(Types.scala:1781)
	at scala.reflect.internal.Types.defineBaseClassesOfCompoundType$(Types.scala:1773)
	at scala.reflect.internal.SymbolTable.defineBaseClassesOfCompoundType(SymbolTable.scala:28)
	at scala.reflect.internal.Types$CompoundType.baseClasses(Types.scala:1634)
	at refuel.internal.AutoDIExtractor.$anonfun$recursivePackageExplore$3(AutoDIExtractor.scala:119)
```

I thought of a way to get around this.
Perhaps when the import fails to resolve, that TypeSymbol becomes a StubClassSymbol.
So I parsed the structure of the Symbol that went into error and added a condition to filter it if a StubClassSymbol was found. And this one has worked.

```scala
!x.typeSignature.asInstanceOf[ClassInfoTypeApi].parents.exists { pr =>
  pr.typeSymbol.isClass && 
  pr.typeSymbol.asClass.isInstanceOf[scala.reflect.internal.Symbols#StubClassSymbol]
}
```
But I think this is really pushy.

## expectation

I need a way to check the validity of Symbol without a forced macro expansion error.
If the symbol is non-compileable, as in typecheck, for example, it responds with a StubSymbol.

```scala
// If the class can be referenced without any problems, it is returned
// as is. StubSymbol is returned if anything is wrong.
c.brokencheck(sym)
```

**Comment by SethTisue** [comment]
what is the Scala bug here?

**Comment by giiita** [comment]
It's unnatural for macro expansion to result in an error that cannot be supplemented while processing continues. But the solution may be enhancement. Should I post it as an enhancement?

**Comment by SethTisue** [comment]
It seems like a question to me and not a bug report, which is what scala/bug is for.
