### ISSUE TITLE
raw-interpolator escapes backslashes in REPL

### ISSUE THREAD

**Issue by eed3si9n** [scala/bug#11922]
## reproduction steps

```scala
Welcome to Scala 2.13.2-pre-bc1cad4 (OpenJDK 64-Bit Server VM, Java 1.8.0_232).

scala> raw"\n".toArray
```

## problem

```scala
scala> raw"\n".toArray
val res0: Array[Char] = Array(n)
```

## expectation

```scala
scala> raw"\n".toArray
res0: Array[Char] = Array(\, n)
```

**Comment by retronym** [comment]
Looks like a bug in our JLine3 integration.

**Comment by retronym** [comment]
I've submitted a fix.

**Comment by retronym** [comment]
FTR, here's the part of JLine's line reader that we need to skip: https://github.com/jline/jline3/blob/7093b8ece24646955be00592ff3a8da17bb28e5d/reader/src/main/java/org/jline/reader/impl/LineReaderImpl.java#L1104-L1119
