### ISSUE TITLE
Shapeless master broken with night scalac 2.13.2

### ISSUE THREAD

**Issue by joroKr21** [scala/bug#11923]
Example job: https://travis-ci.org/github/milessabin/shapeless-test-scala-nightly/jobs/667507411

## reproduction steps

Clone https://github.com/milessabin/shapeless-test-scala-nightly
`./run.sh`

## problem

Tests fail with `IncompatibleClassChangeError`:
```scala
[error] Test shapeless.TestEnum.testEnum4 failed: java.lang.IncompatibleClassChangeError: Expected non-static field shapeless.EnumDefns4$EnumVal$.shapeless$EnumDefns4$EnumVal$$BarA, took 0.005 sec
[error]     at shapeless.TestEnum.$anonfun$testEnum4$1(generic.scala:1167)
[error]     at shapeless.Generic$$anon$1.to(generic.scala:163)
[error]     at shapeless.TestEnum.testEnum4(generic.scala:1168)
[error]     ...
```

## expectation

Tests should pass as they do in the community build or on shapeless master with Scala 2.13.1

**Comment by lrytz** [comment]
Hmm, for me 2.12.11 looks the same as 2.13.1

```
Welcome to Scala 2.12.11 (Java HotSpot(TM) 64-Bit GraalVM EE 19.2.1, Java 1.8.0_231).
Type in expressions for evaluation. Or try :help.

scala> :power
Power mode enabled. :phase is at typer.
import scala.tools.nsc._, intp.global._, definitions._
Try :help or completions for vals._ and power._

scala> :pa
// Entering paste mode (ctrl-D to finish)

trait Foo
object Foo {
  val x = new Foo { }
}

val x = typeOf[Foo.type].member(TermName("x"))
singleType(typeOf[Foo.type], x)

// Exiting paste mode, now interpreting.

defined trait Foo
defined object Foo
x: $r.intp.global.Symbol = value x
res0: $r.intp.global.Type = Foo.<refinement>.type
```

Is it a question of type printing?
```
scala> res0.asInstanceOf[SingleType].sym
res2: $r.intp.global.Symbol = value x

scala> res0.asInstanceOf[SingleType].pre
res3: $r.intp.global.Type = Foo.type
```
Or what's the bug?

**Comment by joroKr21** [comment]
Hmm, sorry for the false alarm, it looks like a type printing bug indeed.

**Comment by joroKr21** [comment]
Shapeless is still broken though 😄 We get:
```scala
[error] Test shapeless.TestEnum.testEnum4 failed: java.lang.IncompatibleClassChangeError: Expected non-static field shapeless.EnumDefns4$EnumVal$.shapeless$EnumDefns4$EnumVal$$BarA, took 0.005 sec

[error]     at shapeless.TestEnum.$anonfun$testEnum4$1(generic.scala:1167)

[error]     at shapeless.Generic$$anon$1.to(generic.scala:163)

[error]     at shapeless.TestEnum.testEnum4(generic.scala:1168)

[error]     ...
```

So I'm not sure what to do.

**Comment by milessabin** [comment]
Nb. this is with last couple of scalac nightlies and shapeless master, so it isn't something which would be picked up by either the community build (which uses shapeless 2.3.3) or by normal shapeless PR validation (which use 2.13.1).

**Comment by milessabin** [comment]
`IncompatibleClassChangeError` seems very odd. Some kind of incremental/separate compilation issue?

**Comment by lrytz** [comment]
@joroKr21 can you clarify which exact Scala versions you're comparing? To me, 2.12.11, 2.13.1 and current 2.13.x all look the same.

**Comment by milessabin** [comment]
The error [here](https://travis-ci.org/github/milessabin/shapeless-test-scala-nightly/jobs/667047489#L987) is,

scala: 2.13.2-bin-bc1cad4
shapeless: f291bcc20dbd61142c0f406c511a3d9f15efc2c6 (which is current master)

We don't see it with 2.13.1.

**Comment by lrytz** [comment]
OK, thanks. So we need to diagnose / minimize. The code in the description here behaves the same on 2.13.1 and 2.13.2-bin-bc1cad4, so that doesn't seem to be related.

**Comment by joroKr21** [comment]
Yes sorry the code in the description is what I suspected as the reason for the failure but I was completely off. I will amend the issue and make it specifically about shapeless.

**Comment by joroKr21** [comment]
milessabin/shapeless#994 should fix the issue but we have to wait for the next nightly.

The problem is that we were referencing the fields in the object instead of their getters. However the fields don't exist in the bytecode, they are converted to static fields. It looks like there are no checks against this so it passed through all the way to the generated bytecode.

**Comment by milessabin** [comment]
The latest nightly was [green](https://travis-ci.org/github/milessabin/shapeless-test-scala-nightly/builds/667934458).
