### ISSUE TITLE
False positive for -Wself-implicit (with lazy implicit value)

### ISSUE THREAD

**Issue by agboom** [scala/bug#11939]
## reproduction steps

When using Scalacheck while `-Wself-implicit` is enabled, I ran into a warning that I did not expect.

```scala
import org.scalacheck.Arbitrary.{arbitrary, _}
import org.scalacheck.Gen._
import org.scalacheck._

object Check {

  val finite: Gen[Float] =
    arbitrary[Float].suchThat(n => !n.isInfinite && !n.isNaN)
}
```

For a live demo see: https://scastie.scala-lang.org/WwQ0rFDkTl6jEDvXgOnH2w

## problem

```
Implicit resolves to enclosing lazy value arbFloat
```

## expectation

No warning

I'm not sure whether it is related to the fact that the resolving implicit is a lazy value, but it is part of this example.

This issue is related, but was closed, so I assumed that the cause is different: https://github.com/scala/bug/issues/11813

**Comment by som-snytt** [comment]
The related issue is fixed for upcoming 2.13.2 (not current release 2.13.1).

I can't tell by looking (or remembering) if it's the same problem.

`import org.scalacheck.Arbitrary.{arbitrary, _}` is to resolve a conflict with another wildcard import?

**Comment by hrhino** [comment]
It's the same problem, what with `NoSymbol` being everyone's transowner.

Why not to 2.12.x?

**Comment by som-snytt** [comment]
For the same reason you don't get a 212 number in NY any more?

We're going to wind up with too many semi-rhetorical questions?

**Comment by hrhino** [comment]
My bad, it wasn't supposed to be. scala/scala#8881 just because...

I'll be sure to treasure my (212) number like the rarity it apparently is.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/11813

I almost wrote Duplicatest. I verified the fix with the example.
