### ISSUE TITLE
LazyList#lazyAppendedAll argument evaluate twice

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#11931]
## reproduction steps

```
Welcome to Scala 2.13.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_201).
Type in expressions for evaluation. Or try :help.

scala> LazyList(1).lazyAppendedAll({println("a"); Seq(2)}).toList
a
a
res0: List[Int] = List(1, 2)
```

```
Welcome to Scala 2.13.2-bin-ca30256 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_201).
Type in expressions for evaluation. Or try :help.

scala> LazyList(1).lazyAppendedAll({println("a"); Seq(2)}).toList
a
a
val res0: List[Int] = List(1, 2)
```

## problem

`print` the `"a"` twice

## expectation

only once print `"a"`

## note 

🤔 

https://github.com/scala/scala/blob/ca30256251d78ca9be8e60208e5d1c74e9292806/src/library/scala/collection/immutable/LazyList.scala#L347-L355

```diff
  def lazyAppendedAll[B >: A](suffix: => collection.IterableOnce[B]): LazyList[B] =
    newLL {
      if (isEmpty) suffix match {
        case lazyList: LazyList[B]       => lazyList.state // don't recompute the LazyList
        case coll if coll.knownSize == 0 => State.Empty
-       case _                           => stateFromIterator(suffix.iterator)
+       case coll                        => stateFromIterator(coll.iterator)
      }
      else sCons(head, tail lazyAppendedAll suffix)
    }
```

**Comment by SethTisue** [comment]
@NthPortal do you have time/inclination to take a look?

**Comment by NthPortal** [comment]
I think @xuwei-k has nailed the source of the problem and the solution (thanks for doing all the hard work!). I'll throw up a PR later today hopefully

**Comment by NthPortal** [comment]
(relatedly, would it make sense to list me as a code owner for `*LazyList*` files, to make it more likely that I get automatically assigned/pinged?)

**Comment by SethTisue** [comment]
> would it make sense to list me as a code owner for *LazyList* files

hmm, I don't have any experience with that GitHub feature. Seems like it couldn't hurt, happy to give it a try. I worry that such metadata would tend to fall out of date, but I worry about everything :-)

related: how about adding an entry for yourself in the scala/scala README.md? that's another place something like this can be listed

**Comment by NthPortal** [comment]
nit: I don't think this is a a regression, as it doesn't seem like it was ever correct in a release

**Comment by SethTisue** [comment]
yeah. fwiw, we sometimes use scala/scala-dev for tickets like this (bugs that only exist in yet-to-be-released versions, that are expected to be fixed before release). but we're not even especially consistent about that ourselves
