### ISSUE TITLE
Scala doesn't complain about implicit ambiguity 

### ISSUE THREAD

**Issue by RoniFinTech** [scala/bug#11948]
## reproduction steps

```scala
trait SomeTrait {
implicit val defaultParam: SomeCaseClass = SomeCaseClass()

def someFunc(x: Int)(implicit someCaseClass: SomeCaseClass) ={
// do something
}
}

class SomeClass extends SomeTrait {
implicit val someOtherParam: SomeCaseClass = SomeCaseClass()
someFunc(4)  // someOtherParam is picked as the implicit
}
```

## problem

The problem is that the compiler doesn't complain about ambiguous implicit of the same type. Why is that?

## expectation
error ambiguous implicits.

**Comment by lrytz** [comment]
https://stackoverflow.com/questions/8623055/scala-implicit-parameter-resolution-precedence

https://www.scala-lang.org/files/archive/spec/2.13/07-implicits.html#implicit-parameters

> If there are several eligible arguments which match the implicit parameter's type, a most specific one will be chosen using the rules of static overloading resolution.

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org for questions
