### ISSUE TITLE
For-comp with no yield synthesises a .map call

### ISSUE THREAD

**Issue by japgolly** [scala/bug#11951]
## reproduction steps

Desugar the following:

```scala
for {x <- List(1); y = 1} ()
```

## problem

It effectively desugars to:

```scala
List(1).map { x => val y = 1; (x, y) }.foreach { case (x, y) => () }
```

## expectation

Because there's no `yield`, I expect all `.flatMap` and `.map` calls to be `.foreach` instead. It should desugar to:

```scala
List(1).foreach { x => val y = 1; () }
```

**Comment by Jasper-M** [comment]
Isn't that more or less the general issue that assignments (`y=1`) in for comprehensions incur an extra `map` call?

**Comment by joroKr21** [comment]
You need https://github.com/oleg-py/better-monadic-for

**Comment by martijnhoekstra** [comment]
specced at https://scala-lang.org/files/archive/spec/2.13/06-expressions.html#for-comprehensions-and-for-loops to everyones chagrin as 

> A generator `p <- e` followed by a value definition `p′ = e′ `is translated to the following generator of pairs of values, where `x` and `x′` are fresh names:
> 
> `(p, p′) <- for (x@p <- e) yield { val x′@p′ = e′; (x, x′) }`
> 

https://contributors.scala-lang.org/t/pre-sip-improve-for-comprehensions-functionality/3509/52 is the canonical contributors thread.

**Comment by dwijnand** [comment]
Perhaps https://github.com/lampepfl/dotty/issues/2573 is the canonical epic.

**Comment by SethTisue** [comment]
unlikely to progress in Scala 2. Scala 3 is a different story

**Comment by SethTisue** [comment]
(if it ever were to progress in Scala 2, it would be because it happened in Scala 3 first)
