### ISSUE TITLE
scala.collection.mutable.StringBuilder is missing underlying API append(s, offset, len)

### ISSUE THREAD

**Issue by ryanberckmans** [scala/bug#11958]
[scala.collection.mutable.StringBuilder](https://www.scala-lang.org/api/2.13.2/scala/collection/mutable/StringBuilder.html) has no API to append a substring, unlike the underlying java.lang.StringBuilder's [API to do so](https://docs.oracle.com/javase/8/docs/api/java/lang/StringBuilder.html#append-java.lang.CharSequence-int-int-).

**Comment by lrytz** [comment]
@ryanberckmans hi, this issue tracker is for bugs. Please use https://users.scala-lang.org for discussion.

**Comment by ryanberckmans** [comment]
thanks https://users.scala-lang.org/t/add-scala-collection-mutable-stringbuilder-charsequence-start-end/5963
