### ISSUE TITLE
"-Woctal-literal" does not work in 2.13.2

### ISSUE THREAD

**Issue by ikempf** [scala/bug#11950]
In Scala 2.13.2 the `-Woctal-literal` is giving false positives. This did not happen in 2.13.1.
This issue affects `integer` and `hex` literals.

## reproduction steps
Minimal program: 
```scala
val a = 0    // Warn
val b = 0xAF // Ok
val c = 0x0F // Warn
```
Compile using:
```
scalac -deprecation -Woctal-literal Main.scala
```

## problem

```scala
Main.scala:4: warning: Decimal integer literals should not have a leading zero. (Octal syntax is obsolete.)
  val a = 0    // Warn
          ^
Main.scala:6: warning: Decimal integer literals should not have a leading zero. (Octal syntax is obsolete.)
  val c = 0x0F // Warn
          ^
2 warnings
```

## expectation
The integer value `0` should not be considered as "having a leading zero".
IMO hex litterals should still allow leading zeros as writing `0x1A 0x07` is more natural and widespread than `0x1A 0x7`.

**Comment by NthPortal** [comment]
@som-snytt

**Comment by som-snytt** [comment]
"How is that possible?"

**Comment by NthPortal** [comment]
this has already come up several times, and 2.13.2 has barely been out. is it worth pushing out 2.13.3 sooner rather than later just to fix this?

**Comment by som-snytt** [comment]
Workaround is `-Woctal-literal -Wconf:msg=Octal:s` or more refined filtering.

Maybe scala center will release a scalafix that turns `val x = 0` into `var x: Int = _` or `1-1`.

**Comment by SethTisue** [comment]
> is it worth pushing out 2.13.3 sooner rather than later just to fix this? 

I don't think so given that 1) most people aren't using `-Woctal-literal` in the first place, 2) the problem is highly googleable, 3) the workaround is easy

But note also that the 7-month delay between 2.13.1 and 2.13.2 was highly unusual. We expect to build 2.13.3 in 2–3 months.

> Workaround is -Woctal-literal -Wconf:msg=Octal:s or more refined filtering

Is there any reason to do it this way rather than to just omit `-Woctal-literal`?

**Comment by som-snytt** [comment]
> Is there any reason to do it this way rather than to just omit -Woctal-literal?

For example, it warns on `0`, `007`, `0x007`. The spurious warnings can be selected by source file.

`'-Wconf:msg=Octal&src=octal.scala:s'`

where the extra single quotes are for shell escaping. The warnings have an empty "site", so that is not useful for selection.
