### ISSUE TITLE
Scala 2.13.2 REPL doesn't show input in Windows 10 CMD and PowerShell.

### ISSUE THREAD

**Issue by counter2015** [scala/bug#11959]
## reproduction steps
Environment
-  Windows10 Family Version 1909
- Scala 2.13.2

## problem
In 2.13.2, input cannot be echoed to the screen
![1](https://user-images.githubusercontent.com/13608862/80378407-32cb1800-88cf-11ea-8b0d-da7ec48bc523.gif)

However, in 2.13.1 it works
![GIF1](https://user-images.githubusercontent.com/13608862/80378869-e3391c00-88cf-11ea-86cb-7c9d5166a492.gif)

## expectation
Input should be echoed.

**Comment by SethTisue** [comment]
well, this is odd — we did several rounds of testing on Windows before release (https://github.com/scala/scala-dev/issues/679) and didn't get any other reports of this, either before or after release

@martijnhoekstra you're not able to reproduce this, I assume? any idea what might be different in the environment that would cause different behavior?

@counter2015 is the behavior the same under Cygwin, PowerShell, etc? or is this unique to vanilla CMD?

**Comment by SethTisue** [comment]
@counter2015 I assume that `-Xjline:off` makes the problem go away? (while also losing editing niceties, naturally)

**Comment by counter2015** [comment]
> @counter2015 I assume that `-Xjline:off` makes the problem go away? (while also losing editing niceties, naturally)

Yes, it works.

**Comment by counter2015** [comment]
> well, this is odd — we did several rounds of testing on Windows before release ([scala/scala-dev#679](https://github.com/scala/scala-dev/issues/679)) and didn't get any other reports of this, either before or after release
> 
> @martijnhoekstra you're not able to reproduce this, I assume? any idea what might be different in the environment that would cause different behavior?
> 
> @counter2015 is the behavior the same under Cygwin, PowerShell, etc? or is this unique to vanilla CMD?
> 
> @alexarchambault forgive me for randomly roping you in (or trying to), but is this a behavior you've seen in any of your testing?

REPL works well under Cygwin while Powershell has the same behavior of no output.

**Comment by martijnhoekstra** [comment]
> @martijnhoekstra you're not able to reproduce this, I assume? any idea what might be different in the environment that would cause different behavior?

No, works for me in CMD and MSYS. I know there is a situation where I don't get anything echoed, but I forget what it is exactly. Something more or less exotic to the point where I never bothered reporting (the `scala` sbt task in the scala/scala repo on the 2.13.x branch on CMD?)

**Comment by counter2015** [comment]
> > @martijnhoekstra you're not able to reproduce this, I assume? any idea what might be different in the environment that would cause different behavior?
> 
> No, works for me in CMD and MSYS. I know there is a situation where I don't get anything echoed, but I forget what it is exactly. Something more or less exotic to the point where I never bothered reporting (the `scala` sbt task in the scala/scala repo on the 2.13.x branch on CMD?)
> 
> I also tried the zip archive in case it was somehow different, but that works too.
> 
> @counter2015 how did you install scala?

I just download from https://downloads.lightbend.com/scala/2.13.2/scala-2.13.2.zip 
unzip it and run. It can't echo and "enter" key doesn't work in CMD and PowerShell.

**Comment by michelou** [comment]
Scala 2.13.2 REPL works fine for me too.

**Comment by martijnhoekstra** [comment]
> > > @martijnhoekstra you're not able to reproduce this, I assume? any idea what might be different in the environment that would cause different behavior?
> > 
> > 
> > No, works for me in CMD and MSYS. I know there is a situation where I don't get anything echoed, but I forget what it is exactly. Something more or less exotic to the point where I never bothered reporting (the `scala` sbt task in the scala/scala repo on the 2.13.x branch on CMD?)
> > I also tried the zip archive in case it was somehow different, but that works too.
> > @counter2015 how did you install scala?
> 
> I just download from https://downloads.lightbend.com/scala/2.13.2/scala-2.13.2.zip
> unzip it and run. It can't echo and "enter" key doesn't work in CMD and PowerShell.

That's so weird -- that's exactly what I did and it works for me. Maybe something weird with platform encoding? I wouldn't know where to begin trying to reproduce this.

**Comment by counter2015** [comment]
I have no idea, it seems difficult to reproduce.
Just now I install 2.13.2 REPL in Windows 8, it works fine.

**Comment by counter2015** [comment]
It seems that this problem is caused by other reason and hard to reproduce.

I will close it since no one can replicate the problem, if someone can reproduce it, I wiil reopen the issue.
