### ISSUE TITLE
Nonlocal return in lambda induces fruitless specialization

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11965]
## reproduction steps

(with `-Xlint`)

```scala
Welcome to Scala 2.13.3-20200428-221111-73961e8 (OpenJDK 64-Bit Server VM, Java 11.0.7).
Type in expressions for evaluation. Or try :help.

scala> def f(): Int = (1 to 10).map { i => i }.sum
def f(): Int

scala> def f(): Int = (1 to 10).map { i => return 0 ; i }.sum
                                           ^
       warning: return statement uses an exception to pass control to the caller of the enclosing named method f
warning: Fruitless specialization of Unit in parameter position. Consider using `@specialized(Specializable.Arg)` instead.
def f(): Int
```

## problem

```scala
warning: Fruitless specialization of Unit in parameter position. Consider using `@specialized(Specializable.Arg)` instead.
```

## expectation

Or is it fruity?

I don't need advice I can't act on. This is the coronavirus test of lints. Since I can't do anything about it, I'm not sure I want to know.

**Comment by inkytonik** [comment]
I'm seeing this warning too when moving Kiama to 2.13.2. sbt reports the fruitless warning with no coordinate information, so I can't even try to avoid it. And warnings are errors for us...

**Comment by lrytz** [comment]
Using `scala -Xlint -Wconf:any:wv`, you see

```scala
scala> def f(): Int = (1 to 10).map { i => return 0 ; i }.sum
                                           ^
       warning: [lint-nonlocal-return @ f] return statement uses an exception to pass control to the caller of the enclosing named method f
warning: [lint-unit-specialization @ scala.runtime.NonLocalReturnControl.<init>] Fruitless specialization of Unit in parameter position. Consider using `@specialized(Specializable.Arg)` instead.
def f(): Int
```

So you can work around it with `scala -Xlint:_,-unit-special`, or even `scala -Xlint '-Wconf:cat=lint-unit-specialization&site=.*NonLocalReturnControl.<init>:s'`

The warning site is wrong, should be `f` of course, not `NonLocalReturnControl.<init>`.

**Comment by SethTisue** [comment]
another report, though it doesn't involve nonlocal return: https://users.scala-lang.org/t/help-to-understands-fruitless-specialization-warning/5968

**Comment by som-snytt** [comment]
Today I plan to leave a little extra time today to finish reading `-Wconf:help`.

I see I left a comment to remove specialization on Unit from `NonLocalReturnControl` later, it breaks binary compat.

But it's erroneously warning on the instance creation, an innocent `new`.
