### ISSUE TITLE
Unused temporary for lonely vararg in named args rewrite

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#11964]
## reproduction steps

```scala
object t7 {
  def f(a: Int, b: String*) = "first"
}
object Test extends App {
  println(t7.f(1))
  println(t7.f(a = 19))
  println(t7.f(a = 28, b = "sl19"))
  println(t7.f(b = "sl19", a = 28))
}
```

## problem

```scala
$ scalac -Xlint unused-fresh.scala
unused-fresh.scala:8: warning: local val x$1 in value <local Test> is never used
  println(t7.f(b = "sl19", a = 28))
                   ^
one warning found
```
where
```
      scala.Predef.println({
        <artifact> val x$1: Seq = scala.collection.immutable.Seq.apply(scala.runtime.ScalaRunTime.wrapRefArray(Array[String]{"sl19"}.$asInstanceOf[Array[Object]]())).$asInstanceOf[Seq]();
        <artifact> val x$2: Int(28) = 28;
        t7.f(28, scala.runtime.ScalaRunTime.wrapRefArray(Array[String]{"sl19"}.$asInstanceOf[Array[Object]]()))
      });
```

## expectation

Less cruft.

**Comment by dwijnand** [comment]
Weird.  I kind of expected `b = "sl19"` to not compile.  Were you expecting it to?  Does the spec say anything about that?

Also, why isn't `x$2` similarly unused?

**Comment by som-snytt** [comment]
Guessing that `x$2` is not used because it's a constant, and not flagged unused for same reason. Non-constant expr is used.

The way to avoid disappointment is not to have expectations.

I did recently see a behavioral difference in Scala 3, that you can't name a sequence arg out-of-order, though the issue was deemed too low-priority to track at https://github.com/lampepfl/dotty/issues/10220.

Pushing expectations:
```
scala> def f(a: Int, b: String*) = "first"
def f(a: Int, b: String*): String

scala> f(b = "x", a = 42)
val res0: String = first

scala> f(b = "x", b = "y", a = 42)   // not beyond the pale
                    ^
       error: parameter 'b' is already specified at parameter position 1

scala> f(b = "x"::"y"::Nil:_*, a = 42)   // not in dotty you don't
val res2: String = first

scala>
```

**Comment by dwijnand** [comment]
It's an Xlint unused concern, no?

**Comment by som-snytt** [comment]
I removed lint label because it's an extra allocation.

I was just checking the byte code, which creates a list `x :: Nil` for the temporary, then allocates an array that is wrapped for the arg.

**Comment by dwijnand** [comment]
Ah, I see your reasoning now.  Yeah, silly macro, leaving cruft around.

**Comment by dwijnand** [comment]
Another version, where even a simple usage of the varargs emits the warning:

## reproduction steps

using Scala 2.13.3

```scala
object Hmm {
  def zxc(b: Int*)(implicit x: Int = 3) = "" + b + x
  zxc(4)
}
```

## problem

```
> scalac -Xlint as.scala
as.scala:3: warning: local val x$1 in value <local Hmm> is never used
  zxc(4)
      ^
1 warning
```

**Comment by SethTisue** [comment]
The creation of the unused `ArraySeq` is a (small) performance issue, not just a warnings/linting issue.

**Comment by SethTisue** [comment]
> it's an extra allocation

added "performance" label to note that, and "help wanted" too, the extra `ArraySeq` is 🤦‍♂️

**Comment by retronym** [comment]
I ran into this one as well. Minimized to:

```scala
cat sandbox/test.scala && scalac --scala-version 2.13.6 -Werror -Xlint:unused -d /tmp -Xprint:typer sandbox/test.scala
class Test {

   def foo(a: Any, b: Any = null, c: Any = null)(cs: String*) = ???
   foo("", c = "")("X")
}
sandbox/test.scala:4: warning: local val x$4 in value <local Test> is never used
   foo("", c = "")("X")
                   ^
[[syntax trees at end of                     typer]] // test.scala
package <empty> {
  class Test extends scala.AnyRef {
    def <init>(): Test = {
      Test.super.<init>();
      ()
    };
    def foo(a: Any, b: Any = null, c: Any = null)(cs: String*): Nothing = scala.Predef.???;
    <synthetic> def foo$default$2: Any = null;
    <synthetic> def foo$default$3: Any = null;
    {
      <artifact> val x$1: String("") = "";
      <artifact> val x$2: String("") = "";
      <artifact> val x$3: Any = Test.this.foo$default$2;
      <artifact> val x$4: Seq[String("X")] @scala.reflect.internal.annotations.uncheckedBounds = scala.collection.immutable.Seq.apply[String]("X");
      Test.this.foo("", x$3, "")("X")
    }
  }
}

error: No warnings can be incurred under -Werror.
1 warning
1 error
```

**Comment by som-snytt** [comment]
I see I guessed correctly last year.

It affects a single constant arg to varargs because the apply gets one more typecheck where it is constfolded (and then rewrapped).

The linter ignores the unused temps which are constant-typed, but sees that the non-const varargs temp is now unused.

I'll try to PR a quickie. Then maybe the names-default rewrite can follow right-associative rewrite to where there is a canonical typecheck followed by rewriting for evaluation order.
