### ISSUE TITLE
Triple quoted strings and raw interpolated strings swallow trailing backslash and emit spurious warning

### ISSUE THREAD

**Issue by japgolly** [scala/bug#11966]
## reproduction steps

```scala
"""\/ \/ /\"""
```

## problem

```scala
scala> """\/ \/ /\"""
                ^
       warning: Unicode escapes in triple quoted strings are deprecated, use the literal character instead
```

## expectation

Silence from scalac. I'm not using a unicode escape.

**Comment by SethTisue** [comment]
2.13.2 regression. @martijnhoekstra want to take a look...?

**Comment by martijnhoekstra** [comment]
darn.

**Comment by martijnhoekstra** [comment]
The spurious error is the least problematic part of the bug.

```
scala> """\/ \/ /\"""
                ^
       warning: Unicode escapes in triple quoted strings are deprecated, use the literal character instead
val res0: String = \/ \/ /

```

**Comment by martijnhoekstra** [comment]
When a string or raw interpolator ends with a backslash, that backslash is swallowed if there are additional backslashes in the string, at least 5 positions before the end.
