### ISSUE TITLE
mutable.PriorityQueue does not override Iterable.isTraversableAgain

### ISSUE THREAD

**Issue by thewilly** [scala/bug#11961]
## reproduction steps
It is very simple to reproduce, just create an empty priority queue and chech the status of the `isTraversableAgain` flag. Will print that it is tru but it should not.

```scala
private val compilerStages = new PriorityQueue[String]()
println(compilerStages.isTraversableAgain) // Prints true
```

## problem
Most of the time you traverse a PriorityQueue as follows:
```scala
val pq = new new PriorityQueue[String]()

while(pq.isTraversableAgain) {
  println(pq.dequeue)
}
```
This will generate an exception because the priority queue is empty but the isTraversableAgain flag is true, when it should not. And the same applies if the PriorityQueue is not empty, at the end of the loop execution the queue will be empty and the isTraversableAgain will be still true.

## expectation
The class `mutable.PriorityQueue` should override the `Iterable.isTraversableAgain` value and only be true when there are more elements in the queue, as otherwise you will end with a wonderfull exception when trying to traverse over it and it is empty.

The `isTraversableAgain` flag should be true when the size of the queue is more than 1. That way when you are traversing with only 1 left element in the queue you already know that the queu is not traversable again.

A possible solution for this would be...
```scala
private class ResizableArrayAccess[A0] extends ArrayBuffer[A0] {
  ...
  override def isTraversableAgain: Boolean = this.size > 1
  ...
}
```

This is similar to a `hasNext` method from aany LinkedList.
> If you find that this make sense I can make a PR with the changes and some tests for it.

**Comment by Jasper-M** [comment]
`isTraversableAgain` is not similar to `hasNext`. The doc for `isTraversableAgain` says the following.

> Tests whether this iterable collection can be repeatedly traversed. Always true for Iterables and false for Iterators unless overridden.

**Comment by thewilly** [comment]
Okay then can be closed 😁, sorry.
