### ISSUE TITLE
Subtype information getting lost

### ISSUE THREAD

**Issue by bbonanno** [scala/bug#11972]
Hi there, I recenctly got this bug mockito/mockito-scala/issues/229 reported and after some digging it seems to be caused by what I think it may be a bug in the compiler.

## reproduction steps
In the following scenario, the inheritance information is not present on the compiled Class (Tested in both 2.12.11 and 2.13.2)

```scala
abstract class Abstract
trait TraitExtendsAbstract extends Abstract

println(classOf[TraitExtendsAbstract].getSuperclass)
println(classOf[Abstract].isAssignableFrom(classOf[TraitExtendsAbstract]))
```

## problem

Running that code will print

```scala
null
false
```

## expectation

It should print

```scala
class Abstract
true
```

## extra details

If I run the following code it would actually print the expected result

```scala
val anInstance: TraitExtendsAbstract = new TraitExtendsAbstract {}

println(anInstance.getClass.getSuperclass)
println(classOf[Abstract].isAssignableFrom(anInstance.getClass.getSuperclass))
```

**Comment by sjrd** [comment]
That is unfortunately unavoidable. On the JVM, an interface cannot extend any class but `Object`. So if you look at Java reflection, which only uses the JVM type system, and not the Scala type system, you have no way of telling that the trait initially extended a class.

**Comment by bbonanno** [comment]
@SethTisue Fair enough, many thanks for your answer!
