### ISSUE TITLE
Not found Type WithFilter while upgrading to scala 2.12

### ISSUE THREAD

**Issue by lokanathnayak** [scala/bug#11977]
HI,

Recently I have upgraded the play to 2.6 and scala to 2.12. Below code was working fine with previous version, but now its trowing compilation error in upgraded version.

object Global extends WithFilters {

override def doFilter(next: EssentialAction): EssentialAction = {
    Filters(super.doFilter(next), CustomOverridingFilter)
  }

override def onError(request: RequestHeader, throwable: Throwable) = {
    //Some code here
    super.onError(request, throwable)
  }

  override def onStart(app: Application) = {
    //Some code here
    super.onStart(app)
  }

  override def onStop(app: Application) = {
    //Some Code Here
  }
}

-------------------------------------------------
object CustomOverridingFilterextends Filter {

  override def apply(nextFilter: (RequestHeader) => Future[Result])
                    (requestHeader: RequestHeader): Future[Result] = {
					//Some Code Here
  }
}

-------------------------------------------------------------
Getting Compilation error as below:
 not found: type WithFilters
  value doFilter is not a member of AnyRef
  value onStart is not a member of AnyRef
  
-------------------------------------------
Play : 2.6
Scala: 2.12

Can someone please help me

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org for questions

**Comment by SethTisue** [comment]
https://stackoverflow.com/questions/61617423/play-migration-to-2-6-and-scala-2-12-compilation-issue-while-using-withfilter
