### ISSUE TITLE
False positive for -Wunused:privates under "-Xsource:3"

### ISSUE THREAD

**Issue by Lasering** [scala/bug#11980]
## Reproduction steps
https://scastie.scala-lang.org/lhejtNgFRtSxx0UXQiD2SA

Inlined:
```scala
object Domain {
  def id(id: String): Domain = Domain(Some(id), None)
  def name(name: String): Domain = Domain(None, Some(name))

  def apply(id: String, name: String): Domain = Domain(Some(id), Some(name))
}

case class Domain private (id: Option[String], name: Option[String])
```
`build.sbt` using scala 2.13.2
```scala
scalacOptions ++= Seq(
  "-Xsource:3",
  "-Werror",
  "-Wunused:privates",
)
```
## Problem
```
[error] /(...)/Domain.scala:16:28: private default argument in class Domain is never used
[error] case class Domain private (id: Option[String], name: Option[String])
[error]                            ^
[error]  /(...)/Domain.scala:16:48: private default argument in class Domain is never used
[error] case class Domain private (id: Option[String], name: Option[String])
[error]                                                ^
```

## Expectation
The case class Domain has no default arguments, so no warning/error should be emitted.

**Comment by Jasper-M** [comment]
I think it's about the default arguments of the `copy` method. 
I wonder what the solution should be. Don't warn for (some?) generated code? Or retract the private `copy` method if it's not used?

**Comment by som-snytt** [comment]
Yes, the diff of `-Vprint` is that `private` is propagated:
```
<     case <synthetic> def apply(id: Option[String], name: Option[String]): Domain = new Domain(id, name);
---
>     case <synthetic> private def apply(id: Option[String], name: Option[String]): Domain = new Domain(id, name);
27,29c27,29
<     <synthetic> def copy(id: Option[String] = id, name: Option[String] = name): Domain = new Domain(id, name);
<     <synthetic> def copy$default$1: Option[String] = Domain.this.id;
<     <synthetic> def copy$default$2: Option[String] = Domain.this.name;
---
>     <synthetic> private def copy(id: Option[String] = id, name: Option[String] = name): Domain = new Domain(id, name);
>     <synthetic> private def copy$default$1: Option[String] = Domain.this.id;
>     <synthetic> private def copy$default$2: Option[String] = Domain.this.name;
```
There was a similar ticket which I can't find ATM; I thought it avoids warning about synthetics, but it seems likely I'm mistaken.

**Comment by Jasper-M** [comment]
> There was a similar ticket which I can't find ATM; I thought it avoids warning about synthetics, but it seems likely I'm mistaken.

I seem to remember disabling warnings for synthetics being rejected where the argument was something about eating your own dogfood. But I own neither a dog nor dogfood so I'm not sure.

**Comment by dwijnand** [comment]
> I wonder what the solution should be. Don't warn for (some?) generated code? Or retract the private `copy` method if it's not used?

There is a precedent that unused private code is dropped.  The case I know is private constructors are dropped if they're not accessed from the companion object (so the "private constructors" were actually public in bytecode).  However, the reason I know is because it caused spurious MiMa errors, as I wanted to keep the public bytecode (I ended up changing the strategy higher up, avoid the problem).  So I'm not sure if it's a precedent to follow or not. 🙂

**Comment by som-snytt** [comment]
Related https://github.com/scala/bug/issues/7707

I see the fix was very narrow: `rescindPrivateConstructorDefault`
