### ISSUE TITLE
tailrec doesn't mind recursive calls to supertypes in branches.

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/bug#11989]
## reproduction steps

using Scala 2.13.2,

```scala
import scala.annotation.tailrec

abstract class Base[A] {
  def raise(state: Container): Unit
}

final case class Container(other: Base[_])

final class Derived[A] extends Base[A] {
  @tailrec final def raise(state: Container): Unit =
    if (!(state eq null)) raise(state) else state.other.raise(state)
}
```

## problem

should not compile (but does).

the recursive call `state.other.raise(state)` can't be re-written, as it is a call to a super type. 

Scalac knows this, and replacing the body of `raise` with just `state.other.raise(state)` informs you of it with `could not optimize @tailrec annotated method raise: it contains a recursive call targeting a supertype`, but if the call is made from a branch, then it accepts the annotation.

Dotty rejects the annotation.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/11442 but I'll retain the test.
