### ISSUE TITLE
scala distinct 0.0 and -0.0 behavior is wrong

### ISSUE THREAD

**Issue by WeichenXu123** [scala/bug#11994]
## reproduction steps

using Scala (2.12),

```scala
scala> 0.0.##
res1: Int = 0

scala> (-0.0).##
res3: Int = 0

scala> 0.0.hashCode
res4: Int = 0

scala> -0.0.hashCode
res5: Int = -2147483648

scala> 0.0 == -0.0
res6: Boolean = true
```
This break the contract "between equals() and hashCode() If two objects are equal, then they must have the same hash code."

This leads to non-determinist distinct array results when array includes 0.0 and -0.0:
~~~scala
import scala.util.Random
val rng = new Random(3)

val a1 = Array.tabulate(200)(_=>rng.nextDouble * 2.0 - 1.0) ++ Array.fill(20)(0.0) ++ Array.fill(20)(-0.0)
a1.distinct.sorted.foreach(x => print(x.toString + "\n"))
~~~

will get output
```
...
-0.009292684662246975
-0.0033280686465135823
-0.0
0.0
0.0022219556032221366
0.02217419561977274
...
```
But `Array(0.0, -0.0).distinct` will get result `Array(0.0)`

## problem

0.0 and -0.0 hashCode is different but they're equal, this break the contract "between equals() and hashCode() If two objects are equal, then they must have the same hash code."

**Comment by sjrd** [comment]
This is correct. `hashCode` must be consistent with `equals`, not `==`. You'll see that `0.0.equals(-0.0)` is *false*, so having different `hashCode`s is correct.

`##` is the one that needs to be consistent with `==`, and you showed yourself that the `##`es are equal.
