### ISSUE TITLE
Missing Unused Expression Warning

### ISSUE THREAD

**Issue by jamesward** [scala/bug#11998]
## reproduction steps

using Scala 2.13.2,

```scala
val isAThing = {
  "blah" == "asdf" &&
  "foo" == "bar"
  "baz" == "baz"
}
```

With these compiler options:
```
  "-unchecked",
  "-deprecation",
  "-explaintypes",
  "-feature",
  "-Wconf:any:error",
  "-Wdead-code",
  "-Wunused",
  "-Wvalue-discard",
```

## problem

The compiler does not catch that the first two expressions are unused.

**Comment by som-snytt** [comment]
This isn't under a flag. It doesn't do anything with `Object#equals`.
```
scala> def f = { 1 + 1 ; 2 }
                   ^
       warning: a pure expression does nothing in statement position; multiline expressions might require enclosing parentheses
def f: Int

scala> def f = { 1 == 1 ; 2 }
                   ^
       warning: a pure expression does nothing in statement position; multiline expressions might require enclosing parentheses
def f: Int

scala> def f = { "" == "" ; 2 }
def f: Int
```
Here, "pure" means "looks like a constant", IIRC. It could special case equals for String, or string equality for constants could be constant-folded, etc.

The heuristic could be improved, and maybe add a strict option that would be more like detecting value discard.

`-Wunused` only means a symbol that was introduced but not referenced. (For imports, a selector was never used to look up a symbol.)

**Comment by SethTisue** [comment]
shouldn't `-Wvalue-discard` be catching it though?

**Comment by som-snytt** [comment]
`-Wvalue-discard` warns that [value discard conversion](https://scala-lang.org/files/archive/spec/2.13/06-expressions.html#value-conversions) was applied. That's not in the middle of a block, in "statement position", but only at the end, in "result position", when `Unit` is expected.

> The heuristic could be improved, and maybe add a strict option that would be more like detecting value discard.

**Comment by SethTisue** [comment]
PR https://github.com/scala/scala/pull/9893

**Comment by som-snytt** [comment]
`-Wnonunit-statement` in the linked PR
