### ISSUE TITLE
repl ignores input if lines following line comments

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/bug#11991]
## reproduction steps

2.13.2

```scala
scala> :paste
// Entering paste mode (ctrl-D to finish)

// This is a comment
val x = 1
val y = 2

// Exiting paste mode, now interpreting.

scala> x
       ^
       error: not found: value x
```

## problem

the repl doesn't find x (or y).

It has to start with a comment, after that, we're fine:
```
scala> :paste
// Entering paste mode (ctrl-D to finish)

val y = 2

// This is a comment, but x below is fine
val x = 1


// Exiting paste mode, now interpreting.

val y: Int = 2
val x: Int = 1
```

**Comment by martijnhoekstra** [comment]
Taken from https://users.scala-lang.org/t/comments-in-scala-repl-paste-mode/6014  reported originally by @njsand

**Comment by SethTisue** [comment]
Nice catch! Definitely a blocker for 2.13.3. I'll dig into it and figure out what's going on.

**Comment by SethTisue** [comment]
@som-snytt this regressed in scala/scala@0e6426dddb16a2d18d698f7019a6a7c2593445db — do you have time to look into it...?

**Comment by som-snytt** [comment]
@SethTisue could you move your "no good deed" joke from its original location and paste it here? This was when I had the dry cough and a couple of days before I was in bed with fever, so I don't remember anything from that week or really anything before that. "I assume it was the virus," or maybe the flu "which is just about as bad as corona."

My other joke for this ticket was, "Everyone ignores my input after I make a comment, I got used to it."

I'll take a look. To paraphrase another famous aphorism, the linked commit seems to be: "Move `reporter.reset` until it compiles."

**Comment by SethTisue** [comment]
@som-snytt want me to take this one? I consider it critical for 2.13.3

**Comment by som-snytt** [comment]
I must have rubbernecked it.

Inbox-style notifications were working so well for me, too. I'll take a look right now, before I'm allowed outside for some exercise on the asphalt.

**Comment by som-snytt** [comment]
Paste will probe for a package statement by re-parsing. REPL always leaked the error if the actual code was not top-level; it mattered once REPL started reporting parser errors.

Line comments are skipped by the scanner; not sure yet what difference is with leading line comment. The package probe should probably use `parseStatsOrPackage`?
