### ISSUE TITLE
Exception when compiling..... scala.reflect.internal.Symbols$Symbol.hasFlag(Symbols.scala:751)

### ISSUE THREAD

**Issue by rhande-mdsol** [scala/bug#11993]
Compile the code in Travis CI, and it inconsistently fails  with this error.

[0m[[0m[31merror[0m] [0m[0mnull[0m
[0m[[0m[31merror[0m] [0m[0mscala.reflect.internal.Symbols$Symbol.hasFlag(Symbols.scala:751)[0m
[0m[[0m[31merror[0m] [0m[0mscala.reflect.internal.HasFlags.isMutable(HasFlags.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0mscala.reflect.internal.HasFlags.isMutable$(HasFlags.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0mscala.reflect.internal.Symbols$Symbol.isMutable(Symbols.scala:226)[0m
[0m[[0m[31merror[0m] [0m[0mscala.reflect.internal.Symbols$Symbol.isStable(Symbols.scala:958)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4798)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4885)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5680)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:796)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:721)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:796)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4855)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:713)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4857)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4885)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5680)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:796)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:721)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:796)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4855)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:713)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4857)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4885)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5680)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:796)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:721)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:796)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4855)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:713)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4857)[0m
[0m[[0m[31merror[0m] [0m[0mscala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4885)[0m

and after this, during the packaging of the Jar, the same error recurs with the StackOverflow error.

[0m[[0m[31merror[0m] [0m[0mjava.lang.StackOverflowError[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.reflect.internal.Symbols$Symbol.hasFlag(Symbols.scala:751)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.reflect.internal.HasFlags.isMutable(HasFlags.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.reflect.internal.HasFlags.isMutable$(HasFlags.scala:120)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.reflect.internal.Symbols$Symbol.isMutable(Symbols.scala:226)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.reflect.internal.Symbols$Symbol.isStable(Symbols.scala:958)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4798)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4885)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5680)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:796)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.transform.Erasure$Eraser.adaptMember(Erasure.scala:721)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:796)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5726)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$38(Typers.scala:4855)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:713)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:4857)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:4885)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5680)[0m
[0m[[0m[31merror[0m] [0m[0m	at scala.tools.nsc.transform.Erasure$Eraser.typed1(Erasure.scala:796)[0m
The travis.yml details  are as follows.

scala:
  **- 2.12.7**
jdk:
  **- openjdk8**

**Comment by SethTisue** [comment]
> Compile the code in Travis CI 

compile what code, exactly? how would I reproduce the problem on my own computer (or my own Travis-CI job)?

also: is the problem reproducible in Scala 2.12.11? and is it reproducible in 2.13.2?

**Comment by lrytz** [comment]
Closing for now, @rhande-mdsol re-open if you can provide more information.
