### ISSUE TITLE
`class Stream.Cons` and `object Stream.cons` are clashing with each other

### ISSUE THREAD

**Issue by sjrd** [scala/bug#11997]
In `object Stream`, there is a [`class Cons`](https://github.com/scala/scala/blob/b91a1445fc00b92e886c927988a4f0525fcfb7cc/src/library/scala/collection/immutable/Stream.scala#L380) and an [`object cons`](https://github.com/scala/scala/blob/b91a1445fc00b92e886c927988a4f0525fcfb7cc/src/library/scala/collection/immutable/Stream.scala#L424).

This *happens* not to cause any issue on the JVM, even on Windows. That's because `Stream$cons$` being a nested `object`, scalac does not generate static forwarders for it in `Stream$cons`. However Scala.js generates more static forwarders, to be able to correctly define static methods in nested static classes of JDK APIs.

This basically prevents from building Scala.js 1.x with 2.13.x on Windows.

I don't know what to do about this, given the binary compat guarantees. 😰

**Comment by joroKr21** [comment]
Running on Mac, I do see linking errors when building OSS projects that upgraded to Scala.js 1.x
I haven't investigated but this could be the reason.

**Comment by dwijnand** [comment]
> with 2.13.x

Same with 2.12.x, right?  Seeing as it's the same: https://github.com/scala/scala/blob/v2.12.11/src/library/scala/collection/immutable/Stream.scala#L1149-L1163

**Comment by sjrd** [comment]
I've never observed the issue with 2.12.x. And our build uses 2.12.x by default, so I'm *constantly* building on 2.12.x.

I guess this is because in 2.12.x, `object cons` comes *before* `class Cons`. So when we compile `object cons`, we generate `Stream$cons$.class` and `Stream$cons.class`. And then when we arrive at `class Cons`, we overwrite `Stream$cons.class` with the one for `Cons`. We lose the static forwarders for `Stream$cons$`, but we never observe that, because it's not a JDK class.

If my analysis is correct, we could work around the issue by swapping the order of the definitions in the 2.13.x source!

**Comment by dwijnand** [comment]
Fixed in scala/scala#9035.
