### ISSUE TITLE
[2.13 regression] Scala 2.13 miscompiles Spark: it forgets to emit a field leading to a NoSuchFieldError at runtime

### ISSUE THREAD

**Issue by smarter** [scala/bug#12002]
## reproduction steps

This is using Scala 2.13.2 (Scala 2.13.{0, 1} had a bug preventing Spark from compiling) and a fork of Spark to get it to compile with 2.13 (see [SPARK-25075](https://issues.apache.org/jira/browse/SPARK-25075?focusedCommentId=17096870&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17096870)):
```shell
git clone https://github.com/smarter/spark/ -b scala-2.13-miscompile
cd spark
sbt core/compile
```

## problem

The class `HighlyCompressedMapStatus` has a field `numNonEmptyBlocks`: https://github.com/smarter/spark/blob/ecfee82fda5f0403024ff64f16bc767b8d1e3e3d/core/src/main/scala/org/apache/spark/scheduler/MapStatus.scala#L165
This field is only used in the constructor of the class: https://github.com/smarter/spark/blob/ecfee82fda5f0403024ff64f16bc767b8d1e3e3d/core/src/main/scala/org/apache/spark/scheduler/MapStatus.scala#L174
... but scalac doesn't emit any field for it, even though it emits a getfield call for its usage in the constructor:
```shell
$ javap -p -v core/target/scala-2.13/classes/org/apache/spark/scheduler/HighlyCompressedMapStatus.class|grep numNonEmptyBlocks
  #304 = Utf8               numNonEmptyBlocks
  #306 = NameAndType        #304:#118     // numNonEmptyBlocks:I
  #307 = Fieldref           #2.#306       // org/apache/spark/scheduler/HighlyCompressedMapStatus.numNonEmptyBlocks:I
        65: getfield      #307                // Field numNonEmptyBlocks:I
            0      95     2 numNonEmptyBlocks   I
      numNonEmptyBlocks              final
```
If I add a `private def foo: Int = numNonEmptyBlocks` to the class, then the field does show up:
```shell
$ javap -p -v core/target/scala-2.13/classes/org/apache/spark/scheduler/HighlyCompressedMapStatus.class|grep numNonEmptyBlocks
   #20 = Utf8               numNonEmptyBlocks
   #50 = NameAndType        #20:#21       // numNonEmptyBlocks:I
   #51 = Fieldref           #2.#50        // org/apache/spark/scheduler/HighlyCompressedMapStatus.numNonEmptyBlocks:I
  private int numNonEmptyBlocks;
         1: getfield      #51                 // Field numNonEmptyBlocks:I
         7: putfield      #51                 // Field numNonEmptyBlocks:I
        70: getfield      #51                 // Field numNonEmptyBlocks:I
            0     100     2 numNonEmptyBlocks   I
      numNonEmptyBlocks              final
```

**Comment by Jasper-M** [comment]
Shouldn't it `iload_2` the constructor parameter instead of `getfield`?

**Comment by smarter** [comment]
That would also work yeah, that seems to be the pattern used for accessing constructor arguments normally.

**Comment by Jasper-M** [comment]
By the way this is embarrassingly simply to reproduce:

```
scala> class Foo(private[this] var a: Int) { val theA = a }
class Foo

scala> new Foo(0)
java.lang.NoSuchFieldError: a
  ... 41 elided
```

**Comment by smarter** [comment]
Looks like this regressed between 2.13.1 and 2.13.2

**Comment by Jasper-M** [comment]
> Looks like this regressed between 2.13.1 and 2.13.2

I can reproduce in 2.13.0 already.

Scala 2.12.11
```
scala> class Foo(private[this] var a: Int) { a }
defined class Foo

scala> :javap -c Foo
Compiled from "<console>"
public class $line2.$read$$iw$$iw$Foo {
  public $line2.$read$$iw$$iw$Foo(int);
    Code:
       0: aload_0
       1: invokespecial #19                 // Method java/lang/Object."<init>":()V
       4: iload_1
       5: pop
       6: return
}

scala> new Foo(0)
res0: Foo = Foo@17f039e6
```

Scala 2.13.0
```
scala> class Foo(private[this] var a: Int) { a }
defined class Foo

scala> :javap -c Foo
Compiled from "<console>"
public class $line2.$read$$iw$$iw$Foo {
  public $line2.$read$$iw$$iw$Foo(int);
    Code:
       0: aload_0
       1: invokespecial #19                 // Method java/lang/Object."<init>":()V
       4: aload_0
       5: getfield      #22                 // Field a:I
       8: pop
       9: return
}

scala> new Foo(0)
java.lang.NoSuchFieldError: a
  ... 37 elided
```

**Comment by smarter** [comment]
Oops, yes, I didn't test it right.

**Comment by smarter** [comment]
Looks like it actuall regressed between M5 and RC1.

**Comment by som-snytt** [comment]
It looks for usages in secondary constructors, so a workaround is:
```
scala> class C(private[this] var c: String) {
     | def this(x: String, dummy: Null) = { this(x) ; c }
     | c = "hello"
     | }
class C

scala> new C("world")
val res0: C = C@49e2b3c5
```

**Comment by som-snytt** [comment]
I'll take a shot in a bit, by letting it elide the field but adding a local to the constructor.

**Comment by Jasper-M** [comment]
I'm confused. This still crashes. Now also in 2.12.12: #12096

**Comment by som-snytt** [comment]
The fix detects assignment to the field only. It should detect more.

**Comment by lrytz** [comment]
@Jasper-M what example still crashes?

In `class Foo(private[this] var a: Int) { a }` there is no field generated in any of the versions 2.12.11, 2.12.12, 2.13.2, 2.13.2. The compiler eliminates `private[this]` fields that are only accessed in the constructor. It doesn't consider the possibility that the field could be accessed reflectively.

`class Foo(private var a: Int) { a }` gets a field in all of the above versions.

The fix in https://github.com/scala/scala/pull/9005 ensures that a field is generated if there's an assignment to it in the constructor (`class Foo(private[this] var a: Int) { a = 2 }`). This got [backported to 2.12.12](https://github.com/scala/scala/pull/9006), together with a fix for https://github.com/scala/bug/issues/12003 (which is the same as https://github.com/scala/bug/issues/6880 that was fixed in 2.13.0, I guess?)

**Comment by Jasper-M** [comment]
@lrytz 
```
Welcome to Scala 2.13.3.
Type in expressions for evaluation. Or try :help.

scala> class Foo(private[this] var a: Int) { a }
class Foo

scala> new Foo(1)
java.lang.NoSuchFieldError: a
  ... 41 elided
```

**Comment by lrytz** [comment]
Oh, I see 🙁

There were two bugs, and we fixed one, and backported the other bug back to 2.12.12.

**Comment by dongjoon-hyun** [comment]
Thank you!

**Comment by som-snytt** [comment]
Sorry @Jasper-M that your example didn't make it into the test. I think I said on the PR that it was a baby step toward correctness, but two baby steps forward, one baby step back.

I don't have bandwidth even to refresh my memory about the change, but I did expect a follow-up at some point.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/9143
