### ISSUE TITLE
-Ywarn-unused:patvars false positive

### ISSUE THREAD

**Issue by oscar-broman** [scala/bug#12000]
## reproduction steps

Scala 2.13.2

```scala
scala -Ywarn-unused:patvars
scala> for (k @ (a, _) <- Option((0, 0)) if a == 0) yield k

warning: pattern var k in value $anonfun is never used: use a wildcard `_` or suppress this warning with `k@_`
```

## problem

`k` is used and the code won't compile without it. The warning appears to happen due to `withFilter` not using `k`.

**Comment by SethTisue** [comment]
looks like one that @som-snytt will want to 👀

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/11400
Duplicates https://github.com/scala/bug/issues/10287
