### ISSUE TITLE
Regression using Scala 2.13.2 with quill macro.

### ISSUE THREAD

**Issue by ajozwik** [scala/bug#12005]
## reproduction steps

Regression using Scala compiler 2.13.2

```
git clone --branch 2.13.2 https://github.com/ajozwik/quill-generic.git 
cd quill-generic
sbt -Dmacro.scala.version=2.13 ";project quill-jdbc-macro;test:compile;"
```

## problem
Up to scala 2.13.1 (and scala 2.12.11)  the code using [getquill](https://github.com/getquill/quill) with scala macro compiled without any problem.

For scala 2.13.2 - the java.lang.StackOverflowError without clear error occurs:

```
[error] java.lang.StackOverflowError
[error] scala.reflect.internal.Symbols$Symbol.isPrimaryConstructor(Symbols.scala:951)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:1122)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitssImpl(Contexts.scala:1145)
[error] scala.tools.nsc.typechecker.Contexts$Context.withOuter$1(Contexts.scala:1124)
[error] scala.tools.nsc.typechecker.Contexts$Context.implicitssImpl(Contexts.scala:1145)
.....
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.bestImplicit(Implicits.scala:1717)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit1(Implicits.scala:113)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit(Implicits.scala:92)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicit$(Implicits.scala:89)
[error] scala.tools.nsc.Global$$anon$5.inferImplicit(Global.scala:482)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicitFor(Implicits.scala:47)
[error] scala.tools.nsc.typechecker.Implicits.inferImplicitFor$(Implicits.scala:46)
[error] scala.tools.nsc.Global$$anon$5.inferImplicitFor(Global.scala:482)
[error] scala.tools.nsc.typechecker.Typers$Typer.applyImplicitArgs(Typers.scala:272)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adapt$1(Typers.scala:888)
[error] scala.tools.nsc.typechecker.Typers$Typer.adaptToImplicitMethod$1(Typers.scala:492)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1305)
[error] scala.tools.nsc.typechecker.Typers$Typer.adapt(Typers.scala:1302)
[error] scala.tools.nsc.typechecker.Implicits$ImplicitSearch.typedImplicit1(Implicits.scala:875)
.....

```

**Comment by SethTisue** [comment]
have you called this to the attention of the Quill developers? it's certainly possible that this is a regression in Scala, but the first hypothesis that has to be ruled out is that the macro is faulty

**Comment by ajozwik** [comment]
The code with macro has been written by myself.

I simplified code. The problem is when `AbstractSaleRepository` (which is trait)  is compiled. And only if I set scalaVersion to "2.13.2". With all "2.12.x" and "2.13.0", "2.13.1" compiles without any problem.
This class AbstractSaleRepository - use what I called `CompositeKey` - case class with at least two fields. For any other implementation - when I use case class extends AnyVal  - compiles with 2.13.2 without problem. 

I use there 
```
final case class SaleId(fk1: ProductId, fk2: PersonId) extends Embedded with CompositeKey2[ProductId, PersonId]
final case class ProductId(value: Long) extends AnyVal
final case class PersonId(value: Int) extends AnyVal
```

If I change directly to primitives
```
final case class SaleId(fk1: Long, fk2: Int) extends Embedded with CompositeKey2[Long, Int]
```
code compiles.

So the clue is - if I use embedded type - compilation fails. The rule with AnyVal is missing.

**Comment by SethTisue** [comment]
A possible next step would be to use `git bisect` identify the particular Scala PR when the behavior changed. That usually makes it easy to see what's going wrong. We merged [272 pull requests](https://github.com/scala/scala/pulls?page=3&q=is%3Aclosed+milestone%3A2.13.2) for 2.13.2, so that's 9 bisect steps.

**Comment by ajozwik** [comment]
I just search from https://scala-ci.typesafe.com/artifactory/scala-integration/org/scala-lang/scala-compiler/ commits.
Last correct was
2.13.2-bin-be9e4d2/     12-Feb-2020 21:06 

First incorrect is:
```
2.13.2-bin-9643055/     13-Feb-2020 09:18 
```

**Comment by joroKr21** [comment]
Trying to debug but it seems quill is not published for 2.13?

**Comment by ajozwik** [comment]
Not all modules, that I use -Dmacro.scala.version=2.13 to build. I copied solution from quill configuration.

**Comment by joroKr21** [comment]
One easy thing you could check is if you write the code that the macro generates by hand - does it cause the same problem?

**Comment by joroKr21** [comment]
@ajozwik @SethTisue there is another PR in 2.13.2 that touches the lines where the stack trace is looping: #8441

**Comment by ajozwik** [comment]
> One easy thing you could check is if you write the code that the macro generates by hand - does it cause the same problem?

Yes, without my macro the problem is the same. Look on branch 2.13.2_no_own_macro


```
git clone --branch 2.13.2_no_own_macro https://github.com/ajozwik/quill-generic.git 
cd quill-generic
sbt -Dmacro.scala.version=2.13 ";project quill-jdbc-macro;test:compile;"
```

**Comment by ajozwik** [comment]
> One easy thing you could check is if you write the code that the macro generates by hand - does it cause the same problem?
I create own implementation on branch: 2.13.2_no_own_macro - and it compiles.
If you change in `SaleRepositoryWithoutMacro` `JdbcContext[D, N] with DateQuotes` to `JdbcContextDateQuotes[D, N]` - than you receive StackOverflowError.

**Comment by joroKr21** [comment]
Yeah that's quite complicated. I narrowed it down to a weird broken invariant that the code assumes: `x =:= y => allSymbols(x) == allSymbols(y)` but that is not true in this case.

**Comment by joroKr21** [comment]
@ajozwik I have minimized it this far:
```scala
trait DateQuotes[I <: SqlIdiom, N <: NamingStrategy] extends Context[I, N] {
  implicit val instantEncoder: MappedEncoding[Date, Instant] = MappedEncoding[Date, Instant](_.toInstant)
  implicit val instantDecoder: MappedEncoding[Instant, Date] = MappedEncoding[Instant, Date](Date.from)
}

object DateQuotes {
  type Context[I <: SqlIdiom, N <: NamingStrategy] = JdbcContextBase[I, N] with DateQuotes[I, N]
}

trait WithJdbcContext[I <: SqlIdiom, N <: NamingStrategy] {
  protected val context: DateQuotes.Context[I, N]
}

trait AbstractSaleRepository[I <: SqlIdiom, N <: NamingStrategy] extends WithJdbcContext[I, N] {
  import context._
  implicitly[Encoder[Date]]
}
```

But I don't know Quill well. Do you think you can minimize it to remove the dependency on Quill? That would be the basis for fixing this and adding a test.

**Comment by joroKr21** [comment]
I managed to minimize it:
```scala
class A
class B
class MappedEncoding[I, O]

trait Encoding {
  type Encoder[T]
  implicit def mappedEncoder[I, O](implicit mapped: MappedEncoding[I, O], encoder: Encoder[O]): Encoder[I]
  implicit def mappedDecoder[I, O](implicit mapped: MappedEncoding[I, O], decoder: Encoder[I]): Encoder[O]
}

trait Tag[T]
object Tag {
  type Context[T] = Encoding with Tag[T]
}

trait WithContext[T] {
  protected val context: Tag.Context[T]
  implicit val encoder: MappedEncoding[A, B]
  implicit val decoder: MappedEncoding[B, A]
}

trait AbstractSaleRepository[T] extends WithContext[T] {
  import context._
  implicitly[Encoder[A]]
}
```

**Comment by ajozwik** [comment]
+1
Thank you, I confirm - https://github.com/scala/scala/pull/9009 solves this problem.

**Comment by SethTisue** [comment]
(let's keep the ticket open until scala/scala#9009 is actually merged)
