### ISSUE TITLE
False warning “@nowarn annotation does not suppress any warnings” reported by scaladoc

### ISSUE THREAD

**Issue by julienrf** [scala/bug#12007]
## reproduction steps

using Scala 2.13.2,

```scala
import scala.annotation.nowarn

trait Module {
  final class Inner

  @nowarn("cat=unchecked")
  def f(x: Any): Unit =
    x match {
      case _: Inner =>  ()
      case _ => ()
    }
}
```

## problem

Without the `@nowarn` annotation, the compiler produces the following warning:

~~~ text
[warn] The outer reference in this type test cannot be checked at run time.
[warn]       case _: Inner =>  ()
[warn]             ^
~~~

With the `@nowarn` annotation, that warning is suppressed but generating the API documentation produces the following warning:

~~~ text
[warn] @nowarn annotation does not suppress any warnings
[warn]   @nowarn("cat=unchecked")
[warn]    ^
~~~

Running scaladoc should not produce this warning.

Workaround: add `-nowarn` to the scaladoc options:

~~~ scala
Compile / doc / scalacOptions += "-nowarn"
~~~

**Comment by bplommer** [comment]
This bug exists in Scala 2.12.13 - I've opened a PR to backport the fix.
