### ISSUE TITLE
Dotty (in Scastie) producing "Expected a toplevel definition" error...

### ISSUE THREAD

**Issue by chaotic3quilibrium** [scala/bug#12017]
## reproduction steps

using Scala (2.12.11, 2.13.2, Dotty - within Scastie),

```scala
val sA = Some(1, 2)
val sB = Some((1, 2))

println(sA)
println(sB)
println(sA == sB)
```

## problem

The above compiles and runs successfully with Scastie using 2.12.11 and 2.13.2. Selecting Dotty in Scastie causes it to fail with an error. The error is displayed underneath the line of code, `println(sB)`. And the error appears as a red X followed by this message, "Expected a toplevel definition".

Here are the three Scastie links which should take you right to each of the instances I used.
 - 2.12.11 - https://scastie.scala-lang.org/TMWWqjHKQwixWRYfxAgiRg
 - 2.13.2  - https://scastie.scala-lang.org/atcjDFu3SpaTjg4zNWhh0w
 - Dotty   - https://scastie.scala-lang.org/1iHb91ZGT3aDa1rj6wtDsg

**Comment by SethTisue** [comment]
This is the Scala 2 bug tracker. Please report Dotty bugs at https://github.com/lampepfl/dotty. Though, I gave this one a quick try in the Dotty 0.24.0-RC1 REPL, and didn't get an error so perhaps this is actually a Scastie bug? In which case https://github.com/scalacenter/scastie/issues would be the place for it

**Comment by Jasper-M** [comment]
Scastie worksheet mode is disabled for Dotty. It's a limitation.
