### ISSUE TITLE
Resource leak: Sources not closed

### ISSUE THREAD

**Issue by rethab** [scala/bug#12016]
There are several places in this repo where `Source.fromFile` is used without closing the source thereafter. While this is likely not a problem in the productive sources (see output below), this has in the past led to issues with running tests on windows.

Note that this issue was originally reported by @michelou in the dotty repo https://github.com/lampepfl/dotty/issues/8358 and @smarter found that this repo has the same issues.

## Occurences
_note that I excluded `Using` here because it is actually used in one place_
```
[rethab:~/dev/scala] 2.13.x ± λ git grep "Source.fromFile" *.scala | grep -v Using
project/GenerateFunctionConverters.scala:    val x = scala.io.Source.fromFile(f)
src/library/scala/concurrent/package.scala: *   val source = scala.io.Source.fromFile("/etc/dictionaries-common/words")
src/partest/scala/tools/partest/nest/FileManager.scala:    compareContents(io.Source.fromFile(original).getLines.toSeq, io.Source.fromFile(revised).getLines.toSeq, original.getName, revised.getName)
test/benchmarks/src/main/scala/scala/collection/immutable/GenerateVectorBenchmark2Charts.scala:    Source.fromFile(file, "UTF8").getLines().drop(1).map { s =>
test/files/jvm/t2104.scala:    g(Source.fromFile(f))
test/files/run/t4671.scala:val s = scala.io.Source.fromFile(o.file)
test/files/run/t4671.scala:val s = scala.io.Source.fromFile(o.file)
test/files/run/t6240-universe-code-gen.scala:  val actual = scala.io.Source.fromFile(actualFile)
test/files/specialized/fft.scala:    val f = io.Source.fromFile(inputFileName)
```

**Comment by som-snytt** [comment]
https://github.com/scala/bug/issues/7244 and relatedly https://github.com/scala/scala/pull/8887

**Comment by som-snytt** [comment]
The PR reduces some usages. There are old tickets along similar lines, including the API is unexpected or hard to use, please at least update the docs. Now just `Files.readString` or `reflect.io.Path("f").toFile.slurp()`.
