### ISSUE TITLE
Scaladoc: Some parameter names in ArrayOps and StringOps are wrong

### ISSUE THREAD

**Issue by ganchurin** [scala/bug#12010]
The following methods in Scala 2.13.x have scaladoc with parameter names which differ from actual names:
* `scala.collection.ArrayOps#filterNot` (scaladoc: `pred`, actual: `p`)
* `scala.collection.ArrayOps#indexWhere` (scaladoc: `p`, actual: `f`)
* `scala.collection.ArrayOps#find` (scaladoc: `p`, actual: `f`)
* `scala.collection.ArrayOps#exists` (scaladoc: `p`, actual: `f`)
* `scala.collection.ArrayOps#forall` (scaladoc: `p`, actual: `f`)
* `scala.collection.StringOps#forall` (scaladoc: `p`, actual: `f`)

**Comment by ganchurin** [comment]
I'd like to fix it.

**Comment by SethTisue** [comment]
PR: https://github.com/scala/scala/pull/8996
