### ISSUE TITLE
Scaladoc web links don't expand function description when signature contains `>`

### ISSUE THREAD

**Issue by xavierguihot** [scala/bug#12029]
When opening a link to the scaladoc for any function containing `>` in its signature, the description is not expanded.

For instance, when opening:

    https://www.scala-lang.org/api/2.13.x/scala/collection/StringOps.html#forall(f:Char=>Boolean):Boolean

the description is not expanded:

![image](https://user-images.githubusercontent.com/17266051/83915043-c61b2700-a772-11ea-9e7a-22f20bfa9a13.png)

Whereas when opening:

    https://www.scala-lang.org/api/2.13.x/scala/collection/StringOps.html#grouped(size:Int):Iterator[String]

which doesn't contain a `>` character in its signature, the description is correctly expanded:

![image](https://user-images.githubusercontent.com/17266051/83915186-0a0e2c00-a773-11ea-9c62-55510506835c.png)

**Comment by jmcrawford45** [comment]
👋 first time contributor here; I'm happy to pick this one up. From some cursory tests, I believe this is particular to how documentation is generated for params with a `@deprecatedName`. For example, https://www.scala-lang.org/api/2.13.x/scala/collection/StringOps.html#fold[A1%3E:Char](z:A1)(op:(A1,A1)=%3EA1):A1 contains the param descriptions, while https://www.scala-lang.org/api/2.13.x/scala/collection/ArrayOps.html#indexWhere(f:A=%3EBoolean,from:Int):Int is only missing the documentation for the first parameter annotated with `@deprecatedName`.

**Comment by jmcrawford45** [comment]
Interestingly enough, I cannot replicate this behavior locally through `scaladoc src/library/scala/collection/StringOps.scala` (version 2.13.2) or `sbt doc`

**Comment by jmcrawford45** [comment]
@SethTisue is there any additional scaladoc environment information I'm not aware of here that you think would help in reproducing this locally?

**Comment by SethTisue** [comment]
ha, I was just looking at this ticket a few minutes ago myself. I'm too busy today and tomorrow to dig into it, but I should have time to look at it later this week, unless somebody else gets to it first

**Comment by Jasper-M** [comment]
> https://www.scala-lang.org/api/2.13.x/scala/collection/StringOps.html#fold[A1%3E:Char](z:A1)(op:(A1,A1)=%3EA1):A1

Couldn't _this_ be the cause? `<` and `>` are urlencoded.

**Comment by xavierguihot** [comment]
The doc also doesn't expand when I use `https://www.scala-lang.org/api/2.13.x/scala/collection/StringOps.html#forall(f:Char=>Boolean):Boolean`

**Comment by Jasper-M** [comment]
Your browser automatically encodes those characters. Mine does at least.

**Comment by forketyfork** [comment]
This was only reproducible in Chrome and Firefox, but not in Safari, since all browsers except Safari return `window.location.href` as url-encoded. This value was used to lookup the anchor, which failed in those browsers. I've prepared a PR to fix this.
Now navigation should also work when the link is initially url-encoded.
