### ISSUE TITLE
Add support to reference a parameter name from scaladoc

### ISSUE THREAD

**Issue by robstoll** [scala/bug#12033]
As far as I know the current recommendation to refer to parameter names is using `{@code ...}`.
IMO it would be beneficial if one can refer to a parameter (or a type parameter) using an own syntax.
For instance, could be `[(param)]` and `[{tparam}]` or `{@parameref }` and `{@tparamref }`

This way, I assume, IDEs would pick it up and include it in renamings. Certain IDEs support replacement of a text within scaladoc but if you use something like `expected` as parameter name, you end up checking each suggestion as it could also be wrong. An own syntax would help here as well.

Thoughts?

**Comment by dwijnand** [comment]
There very little activity around the Scaladoc tool these days, so this might get more traction if someone were to propose it to the team working on https://github.com/lampepfl/scala3doc.

**Comment by robstoll** [comment]
I guess this will be fixed in scala3 if they still use dokka under the hood as there is a way in Kotlin and as far as I remember it was said, that it is also able to distinguish params and type params

**Comment by som-snytt** [comment]
Heads up, closing as out of scope for Scaladoc 2.

**Comment by robstoll** [comment]
Fair enough, I hope it will be improved in scala 3 (although no longer based on dokka)
