### ISSUE TITLE
REPL: Add quotation marks to Char and String values

### ISSUE THREAD

**Issue by maseev** [scala/bug#12030]
## reproduction steps

- Start a Scala REPL instance
- Copy & paste the attached code snippet below 

using Scala (2.13.1),

```scala
    List(1, 2, 3)
    List('1', '2', '3')
    List("1, 2", "3")
```
Expected result:
```scala
    res0: List[Int] = List(1, 2, 3)
    res1: List[Char] = List('1', '2', '3')
    res2: List[String] = List("1, 2", "3")
```
Actual result:
```scala
    res0: List[Int] = List(1, 2, 3)
    res1: List[Char] = List(1, 2, 3)
    res2: List[String] = List(1, 2, 3)
```
## problem

Scala's REPL doesn't add quotation marks to `Char` and `String` values. Because of that, it makes quite difficult to distinguish values inside a collection, for example.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/8603 which has a PR.
