### ISSUE TITLE
Deprecated `Map.++:` uses wrong order (2.13.0 regression)

### ISSUE THREAD

**Issue by lrytz** [scala/bug#12054]
## reproduction steps

2.12.11

```scala
scala> ListMap(2 -> "b") ++: ListMap(1 -> "a")
res0: scala.collection.immutable.ListMap[Int,String] = ListMap(2 -> b, 1 -> a)
```

2.13.0, 2.13.2

```scala
scala> ListMap(2 -> "b") ++: ListMap(1 -> "a")
                         ^
       warning: method ++: in trait MapOps is deprecated (since 2.13.0): Use ++ instead of ++: for collections of type Iterable
val res0: scala.collection.immutable.ListMap[Int,String] = ListMap(1 -> a, 2 -> b)
```

Discovered when forward-porting new tests from https://github.com/scala/scala/pull/9074 to 2.13. A fix is in https://github.com/scala/scala/pull/9084.

**Comment by SethTisue** [comment]
Note that the actual fix is in the merge commit for scala/scala#9084: https://github.com/scala/scala/commit/d23424cd3aa17f7ad95b81018c70ceed2566962b
