### ISSUE TITLE
scalac -Xlint:-multiarg-infix does not suppress multiarg-infix linting as expected

### ISSUE THREAD

**Issue by jeffrey-aguilera** [scala/bug#12058]
Expect to be able to disable this linter, as it flags common idioms used by Slick.

**Comment by lrytz** [comment]
That looks like an oversight... For operator method definitions the warning is [guarded by the `Xlint` flag](https://github.com/scala/scala/blob/5f634880d4a1ca50006e3035ffb2a86f08766ed1/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L2409-L2412), but [not for callsites](https://github.com/scala/scala/blob/5f634880d4a1ca50006e3035ffb2a86f08766ed1/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L5080-L5081).

What works though: `-Wconf:cat=lint-multiarg-infix:s`.

**Comment by som-snytt** [comment]
It might have been intentional because the application syntax was up for deprecation, not defining an operator-named method with multiple parameters. However, lint was deemed friendlier than outright deprecation, so I also expected the lint flag here.
