### ISSUE TITLE
Symbolic method name require whitespace before colon

### ISSUE THREAD

**Issue by eed3si9n** [scala/bug#12056]
## reproduction steps

using Scala 2.13.3-pre-12f1c41

```scala
scala> def !: Int = 1
              ^
       error: '=' expected but identifier found.
```

## problem

I'm not sure what `'=' expected` means here but if I add a whitespace in between

```scala
scala> def ! : Int = 1
def $bang: Int
```

the definition goes through. This leads me to think that the parser is somehow bunching up `!:` together. I expect no whitespace to be needed between `!` and `:` as I don't have to fore `def a`:

```scala
scala> def a: Int = 1
def a: Int
```

## notes

Here's a variant of this with `unary_!`:

```scala
scala> class Foo { def unary_!: Foo = this }
                                ^
       error: '=' expected but identifier found.
                                           ^
       error: illegal start of simple expression
```

**Comment by SethTisue** [comment]
`!:` is a legal identifier:

```
scala> def !: : Int = 1
def !:: Int

scala> !:                                                                                                               
val res0: Int = 1
```

**Comment by joroKr21** [comment]
You're defining a right-associative bang 😄

**Comment by eed3si9n** [comment]
https://scala-lang.org/files/archive/spec/2.13/01-lexical-syntax.html says:

> As usual, the longest match rule applies.

so it will try to parse both `a:` or `!:` looking for an identifier. `a:` is not a legal identifier but as Seth pointed out `!:` is legal, so the parser would keep chugging along.

```scala
scala> def !: : Int = 1
def !:: Int
``` 

The tree printer prints out without the whitespace, which I tried to fix in https://github.com/scala/scala/pull/9085/commits/fb8dd8839b7c2e530f9386e1552e5fde54a60c4d

**Comment by dwijnand** [comment]
I feel like the status quo isn't benefiting anyone.  Couldn't we find a rule to make the cases like `def unary_!: Foo` work as expected, forcing all those millions (/s) of library authors defining `!:` terms to escape them like

```scala
def `!:` : Int = 1
```

?

**Comment by Jasper-M** [comment]
Where do you draw the line?
```
def +: Int = 1 // +
def ::: Int = 1 // :: ?
def :: Int = 1 // error ?
```

**Comment by dwijnand** [comment]
IMO: if a space would've made it legal, it's legal.  I.e. the space is optional, and backticks are used for funky names (rather than a space).

**Comment by sjrd** [comment]
> IMO: if a space would've made it legal, it's legal. I.e. the space is optional, and backticks are used for funky names (rather than a space).

If we take this criteria ad absurdum, we have to admit that the following should be legal:
```scala
sealedabstract classFoo
```
Spaces are important in general. I don't think they are any less important here.

**Comment by eed3si9n** [comment]
The space between reserved words `sealed` and `abstract` are never optional, but when defining a function like

```scala
def a: Int = 1
```

the space between the function name and `:` is not only optional, it would be discouraged in the most prevalent style.

From the lexical analysis perspective, it's more about "the longest match rule" and [SLS 1.1](https://scala-lang.org/files/archive/spec/2.13/01-lexical-syntax.html#identifiers):

> There are 3 ways to form an identifier.
> 1. First, an identifier can start with a letter, followed by an arbitrary sequence of letters and digits. This may be followed by underscore `_` characters and another string composed of either letters and digits or of operator characters.
> 2. Second, an identifier can start with an operator character followed by an arbitrary sequence of operator characters. The preceding two forms are called plain identifiers.
> 3. Finally, an identifier may also be formed by an arbitrary string between back-quotes (host systems may impose some restrictions on which strings are legal for identifiers). The identifier then is composed of all characters excluding the backquotes themselves.

When the parser fails with `'=' expected but identifier found`, I wonder if it can backtrack its steps and say maybe "longest match" went too far. Or "look-ahead" a single token and when it finds an identifier, and lift `:` out?

@Jasper-M 

```scala
def +: Int = 1 // +
def ::: Int = 1 // :: ?
def :: Int = 1 // error ?
```

I'd say whatever unambiguous would be ok.
