### ISSUE TITLE
Add scaladoc to scala.collection.MapFactory

### ISSUE THREAD

**Issue by er1c** [scala/bug#12065]
https://www.scala-lang.org/files/archive/api/2.13.3/scala/collection/MapFactory.html

2.12 has documentation: https://www.scala-lang.org/files/archive/api/2.12.11/scala/collection/generic/MapFactory.html

2.13:
![image](https://user-images.githubusercontent.com/64685/86057258-b4e0d580-ba13-11ea-827e-63708cbaaab7.png)

2.12:
![image](https://user-images.githubusercontent.com/64685/86057292-c924d280-ba13-11ea-8d98-3389b1e2836f.png)

**Comment by eed3si9n** [comment]
Hi @seratch-san has sent a PR as part of ScalaMatsuri hackathon. could either of you review this plz?  https://github.com/scala/scala/pull/9251

**Comment by dwijnand** [comment]
@seratch if you reply I can assign you this fix! 😄

**Comment by seratch** [comment]
@dwijnand Hey, I'm glad to see the PR has been merged!
