### ISSUE TITLE
Add scaladoc description to scala.Array.from

### ISSUE THREAD

**Issue by er1c** [scala/bug#12064]
https://www.scala-lang.org/files/archive/api/2.13.3/scala/Array$.html#from[A](it:IterableOnce[A])(implicitevidence$3:scala.reflect.ClassTag[A]):Array[A]

When scanning through the scaladocs, there is a glaring omission.

![image](https://user-images.githubusercontent.com/64685/86056442-5109dd00-ba12-11ea-877f-dabe06309669.png)

**Comment by som-snytt** [comment]
https://en.wikipedia.org/wiki/Doublemint

**Comment by SethTisue** [comment]
@chaitanyav if you comment here, I can assign you the ticket (for credit/glory)

**Comment by chaitanyav** [comment]
@SethTisue @som-snytt Thank you.
