### ISSUE TITLE
`scala.Some` got deserialized into `Some(null)` if deserialized by using another scala version

### ISSUE THREAD

**Issue by andyglow** [scala/bug#12063]
## reproduction steps
1. setup compilation against version A (2.11)
2. prepare test data (Some, None, case class with option fields)
3. serialize (bucket A)
4. setup compilation against version B (2.12)
5. serialize (bucket B)
6. setup compilation against version A (2.11)
7. deserialize both buckets and compare with expectations
8. setup compilation against version B (2.12)
9. deserialize both buckets and compare with expectations

Here is the snippet
https://scastie.scala-lang.org/andyglow/WwmjFhJbT1aMBuRDcI89ug

## problem

If the instance of `scala.Some` got serialized with Scala 2.11 and then got deserialized with Scala 2.12 it turns into `Some(null)`. The value got lost. This works in both ways scala `2.11 -> 2.12` as well as scala `2.12 -> 2.11`

**Comment by SethTisue** [comment]
We don't offer that level of serialization compatibility — not even always between minor versions, certainly not between major versions like 2.11 vs 2.12. So this is not a bug, it's working as designed.

On the other hand:

* I don't think we have properly documented what is or isn't guaranteed
* Perhaps we could or should do more to make it fail fast more of the time 

The main prior discussion on that that I know of is https://github.com/scala/scala-dev/issues/237
