### ISSUE TITLE
mutable.HashMap#growTable is broken

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#12076]
`mutable.HashMap#growTable` is broken (it does not handle integer overflow, computes a threshold value but never uses it). `growTable` is called with `length * 2` (see https://github.com/scala/scala/pull/9101#discussion_r450029320), and without overflow checks, something will go wrong. Unfortunately, it's difficult to say what the actual failure mode is, as creating a `HashMap` that big uses a tremendous amount of memory, and I cannot do it on my system.

**Comment by Ichoran** [comment]
Note that hash tables have sizes which are powers of two, and therefore have a max size of `1 << 30`.  So only a hash table that is already the max size has the chance to overflow.

**Comment by SethTisue** [comment]
@NthPortal explains why scala/scala#9124 only partially addressed this, here: https://github.com/scala/scala/pull/9124#discussion_r460823808

**Comment by Ichoran** [comment]
@SethTisue - I think that's just a mistake and the code is fine.  `threshold` is used all over the place to determine when to grow again.  You don't use it again inside `growTable` because you are already growing and you know you've made enough space (or you've failed).

**Comment by NthPortal** [comment]
@Ichoran you're correct - I misread the code

**Comment by NthPortal** [comment]
Fixed by scala/scala#9124

**Comment by SethTisue** [comment]
@RadoBuransky if you comment here, I'll assign you the ticket (for credit/glory)

**Comment by RadoBuransky** [comment]
Thanks @SethTisue
