### ISSUE TITLE
Range.BigDecimal illegitim IllegalArgumentException (more than Int.MaxValue ) when end and inc are really small

### ISSUE THREAD

**Issue by strokyl** [scala/bug#12073]
## reproduction steps

using Scala (2.13.1),

```scala
object RangeBug extends App {
  val start = BigDecimal(-2E-34)
  val inc = BigDecimal(1E-34)
  val end = BigDecimal(1E-64)
  println(List.unfold(start){ prec =>
    Option.when(prec < end)(prec -> (prec + inc))
  })

  //this one fail
  println(Range.BigDecimal(start, end, inc).toList)
}

```

## Range.BigDecimal throws java.lang.IllegalArgumentException: More than Int.MaxValue elements

In this case, we can see constructing the range using List.unfold that this range only contain three elements:
```
List(-2.0E-34, -1.0E-34, 0E-35)
```
Therefore there is no reason for the Range.BigDecimal to fail.

**Comment by SethTisue** [comment]
@cahilltr if you comment here, then I can assign you the ticket (merely for credit/glory)

**Comment by cahilltr** [comment]
@SethTisue , please and thank you!
