### ISSUE TITLE
Lints should respect `-Wmacros`

### ISSUE THREAD

**Issue by neko-kai** [scala/bug#12072]
## reproduction steps

using Scala `2.13.3`:

Scastie showing the warning: https://scastie.scala-lang.org/r3Fnc5YcSzeA91CKs06EtQ

```scala
// libraryDependencies += "com.github.alexarchambault" %% "scalacheck-shapeless_1.14" % "1.2.5"

import org.scalacheck.Arbitrary

final case class X(s: String)
object X {
  implicit val arb: Arbitrary[X] = org.scalacheck.derive.MkArbitrary[X].arbitrary
}
```

## problem

Getting a warning:

```
Block result was adapted via implicit conversion (method apply) taking a by-name parameter
```

But the warning applies to the code generated by `shapeless.Lazy` macro, not user-written code. This makes it mandatory to disable the `-Xlint:byname-implicit` due to the massive amount of false positives whenever implicit derivation is used.

**Comment by som-snytt** [comment]
`-Wunused` consults `-Wmacros`, and it looks like `-Xlint:missing-interpolator` attempts to avoid reporting on macro expansion. Maybe typer could just tell reporter not to report warnings.

**Comment by SethTisue** [comment]
fyi @milessabin

**Comment by milessabin** [comment]
I'd seen this and assumed the linter rule was trigger happy and disabled it.

There's nothing I can do here because the structure is essential to the encoding of `Lazy`. It's a shame this wasn't picked up in the community build.

**Comment by diesalbla** [comment]
The error message was introduced by https://github.com/scala/scala/pull/8590

**Comment by SethTisue** [comment]
volunteer to attempt to improve the situation?

**Comment by lrytz** [comment]
Maybe we can find a secret handshake to sidestep the warning? It would also be good not to warn if the method call is written by the user, not synthesized by the compiler:

```scala
scala> implicit def f(x: => Int): Int = x
warning: 1 feature warning; for details, enable `:setting -feature` or `:replay -feature`
def f(x: => Int): Int

scala> { println("hi"); f(1) }
                         ^
       warning: Block result was adapted via implicit conversion (method f) taking a by-name parameter
hi
val res0: Int = 1
```

Alternatively, the shapeless macro could add a `: @nowarn("cat=lint-byname-implicit")` ascription.

```scala
scala> { println("hi"); f(1) } : @annotation.nowarn("cat=lint-byname-implicit")
hi
```

**Comment by alexklibisz** [comment]
If anyone else is trying to figure out how to suppress just this one type of lint warning:

```
-Xlint:-byname-implicit
```
