### ISSUE TITLE
Deprecated type members hidden when using scaladoc groups

### ISSUE THREAD

**Issue by Jasper-M** [scala/bug#12079]
```
/** @groupname main Main */
class C {
  /** skala dok
    * @group main
    */
  def m = 0

  /** skala dok */
  @deprecated
  def a = 0

  /** skala dok */
  class A

  /** skala dok */
  @deprecated
  class B
}
```

After compiling with `scaladoc -groups`, the scaladoc for `C` shows `m`, `a` and `A`, but `B` is hidden.

<img width="470" alt="image" src="https://user-images.githubusercontent.com/119636/87412353-3b2b1900-c5c9-11ea-9475-66dd2b165af3.png">

When clicking on "Alphabetic", the class `B` shows up.

This affects `Predef.any2stringadd` in the 2.13 scaladocs.

**Comment by lrytz** [comment]
Changed the description into a self-contained example (and added some labels 😉)

**Comment by lrytz** [comment]
@RadoBuransky if you feel like it, post a comment here, so that we can assign this ticket to you for credit.

**Comment by RadoBuransky** [comment]
@lrytz Yeah!
