### ISSUE TITLE
type arguments [_$1] do not conform when multi cases

### ISSUE THREAD

**Issue by changvvb** [scala/bug#12087]
## reproduction steps

using Scala (2.12.12),

```scala
object Test {
  trait A[T <: A[T]]
  trait B[T <: B[T]] extends A[T]

  val s: Seq[A[_]] = Seq.empty

  s.foreach {
    case b: B[_]  ⇒ ()
    case b: B[_]  ⇒ ()
  }
}
```

## problem
type arguments [_$1] do not conform to trait A's type parameter bounds [T <: Playground.Test.A[T]]

but it works if there is only one case with type `B[_]`
```scala
s.foreach {
  case b: B[_]  ⇒ Unit
}
```

**Comment by martijnhoekstra** [comment]
It's true though -- after the first case didn't match, the compiler can infer the value is not `B[T <: B[T]]` for some type T, so no satisfiable type signature for the second `B[_]` exists. Whether that error conveys that information in a reasonable way is a different question.

**Comment by changvvb** [comment]
Because of the type erasure, I think it should only check the type constructor B. And the type B[_] can also  be used as variable type. By the way, the codes in reproduction steps can be compiled successfully in 2.13

**Comment by SethTisue** [comment]
(offhand, I don't know what 2.13 change might have caused this to progress)
