### ISSUE TITLE
Case class's copy method create strange status instance.

### ISSUE THREAD

**Issue by oldbig** [scala/bug#12090]
## reproduction steps

using Scala (2.12.6, 2.12.8, 2.12.10),

```scala
object BugDemo {
  def main(args: Array[String]): Unit = {
    val foo = Bug("foo")
    println(s"foo's length should be 10: $foo")

    foo.setLengthTo100()
    println(s"foo's length should be 100: $foo")

    val bar = foo.copy(name = "bar")
    println(s"foo's length should still be 100: $foo")

    // bar should have the same length as foo, the value should be 100.
    println(s"copied instance bar's length should be 100: $bar")
  }
}

case class Bug(name: String) {
  //default length is 10
  var length:Int = 10

  def setLengthTo100(): Unit = length = 100

  override def toString: String = s"name: $name, length: $length"
}
```

## problem

This is a `suspected bug`.
The bar.length should be the same as foo's length, because we just copy it and supply name value, did nothing for length.

Here is the short video of **explain the reason**: [youtube link](https://youtu.be/HyKPqS1f9zs)

Good practice: case class should not have var fields.

**Comment by julienrf** [comment]
This is expected: `copy` only copies the case class constructor fields. Most probably, a case class is not the right tool for your use case?

**Comment by oldbig** [comment]
> This is expected: `copy` only copies the case class constructor fields. Most probably, a case class is not the right tool for your use case?

Thank your @julienrf 

This is a simplified use case that not the real code in my project.
A case class is fine for me, it just confused me a little time for I found bar lost foo's length. At last, I reset value like follow, although looks strange, it is better than other's way, and this type of usage not spread everywhere, just one place.
```
var bar = foo.copy(name="bar")
bar.length = foo.length
```
`copy only copies the case class constructor fields.`  please have a look this code, the length is constructor field now:
```
object BugDemo {
  def main(args: Array[String]): Unit = {
    val foo = Bug("foo", 3)
    println(s"foo's length should be 10: $foo")

    foo.setLengthTo100()
    println(s"foo's length should be 100: $foo")

    val bar = foo.copy(name = "bar")
    println(s"foo's length should still be 100: $foo")

    // bar should have the same length as foo, the value should be 100.
    println(s"copied instance bar's length should be 100: $bar")
  }
}

case class Bug(name: String,var length: Int) {
  //the if expression will be included in constructor.
  if(name.length < 20) {
    length = 10
  }

  def setLengthTo100(): Unit = length = 100

  override def toString: String = s"name: $name, length: $length"
}
```
So no matter the field is constructor parameter or not, if `modification var field code` be compiled to the constructor will cause this situation.

**Comment by julienrf** [comment]
Here you change the value of `length` in the constructor body, so it is reset to 10. The default implementation of copy is this one:

~~~
def copy(name: String = this.name, length: Int = this.length): Bug =
  new Bug(name, length)
~~~

So, the class constructor is called, which causes the `length` field to be reset to 10 (even though the value 100 was passed to the constructor).

> At last, I reset value like follow, although looks strange, it is better than other's way, and this type of usage not spread everywhere, just one place.

Alternatively, you can override the `copy` method to do whatever you want it to do.

**Comment by lrytz** [comment]
Thanks @julienrf for the explanations. Since everything workes as expected here, please continue this discussion on https://users.scala-lang.org.

**Comment by oldbig** [comment]
Hi @julienrf 
Exactly, this is just what I say in the video, it compiles to the same code as `new Bug(name, length)`.
And override copy method is a very good solution to avoid caller forget call reset code, I found copy function not allowed to have `override` modifier.
The copy method may be made programmers think that is a `shallow copy`, copy will keep original status except for pass parameters. what about adding this description about the copy method implementation to one documentation (I am not sure whether there already exists), maybe this documentation is fine:
[case-classes](https://docs.scala-lang.org/overviews/scala-book/case-classes.html)
So summary: copy is not `shallow copy` it is just an implicit way to call a constructor.
Ok thank your @julienrf 
I think this can be closed.
