### ISSUE TITLE
Constructors handles private[this] var

### ISSUE THREAD

**Issue by wangyum** [scala/bug#12096]
## reproduction steps

// TODO

## problem

[This test](https://github.com/apache/spark/blob/1c714befd882ebb3d561d7b660c85a2c48b0802c/core/src/test/scala/org/apache/spark/serializer/KryoSerializerSuite.scala#L341-L360) will fail:
```
[info] org.apache.spark.serializer.KryoSerializerSuite *** ABORTED *** (324 milliseconds)
[info]   java.lang.NoSuchFieldError: numNonEmptyBlocks
[info]   at org.apache.spark.scheduler.HighlyCompressedMapStatus.<init>(MapStatus.scala:174)
```

It works if [we remove](https://github.com/apache/spark/blob/ba0456223482b13540fbe62bb212bb9be50619be/core/src/main/scala/org/apache/spark/scheduler/MapStatus.scala#L163-L170) `private[this] var`:
```diff
diff --git a/core/src/main/scala/org/apache/spark/scheduler/MapStatus.scala b/core/src/main/scala/org/apache/spark/scheduler/MapStatus.scala
index 7f8893ff3b..5ae45ea0bd 100644
--- a/core/src/main/scala/org/apache/spark/scheduler/MapStatus.scala
+++ b/core/src/main/scala/org/apache/spark/scheduler/MapStatus.scala
@@ -162,7 +162,7 @@ private[spark] class CompressedMapStatus(
  */
 private[spark] class HighlyCompressedMapStatus private (
     private[this] var loc: BlockManagerId,
-    private[this] var numNonEmptyBlocks: Int,
+     var numNonEmptyBlocks: Int,
     private[this] var emptyBlocks: RoaringBitmap,
     private[this] var avgSize: Long,
     private[this] var hugeBlockSizes: scala.collection.Map[Int, Byte],

```

**Comment by wangyum** [comment]
It should be fixed by https://github.com/scala/scala/pull/9006. But it seems Scala 2.12.12 still has this issue.

**Comment by Jasper-M** [comment]
This actually regressed in 2.12.12.

**Comment by dongjoon-hyun** [comment]
cc @srowen

**Comment by dongjoon-hyun** [comment]
From Spark side, we did workaround first, https://issues.apache.org/jira/browse/SPARK-32436.

**Comment by SethTisue** [comment]
@som-snytt , @retronym

**Comment by Jasper-M** [comment]
I still don't understand the purpose of the field in that Spark code though. It seems to be unused except for checking its own precondition.

**Comment by srowen** [comment]
I agree - @dongjoon-hyun we could rewrite that code to simply not try to treat this as a member and save a few bytes. 
If the fundamental issue is that scala is correctly recognizing that this isn't needed as a member and so that's why it's not actually serialized or something, then maybe this isn't a scala issue per se. You all would know better whether this might generalize into other non trivial cases.

**Comment by som-snytt** [comment]
The latest fix was to retain the field if the constructor assigns to it. But now I see the long code comment that says it intended to omit fields only for non-vars. Either I didn't read that comment or I tripped over the double negative.

**Comment by dongjoon-hyun** [comment]
@Jasper-M and @srowen . If you are interested, I'll give more context about that.
On the same PR I gave you, the first commit is about removing it. I tried that idea. I also thought it's unused like you guys.

- https://github.com/apache/spark/pull/29231/commits/9753676f423d2df2e6ac4824520d323094d5d328

There was a relevant UT failure. So, I decided to keep the same behavior like Scala 2.12.10 and older.

**Comment by dongjoon-hyun** [comment]
BTW, one more thing, the field is not externalized at all. So, removal doesn't save a few bytes.

**Comment by lrytz** [comment]
Cross-linking my comment from the other ticket: https://github.com/scala/bug/issues/12002#issuecomment-664919990

**Comment by dwijnand** [comment]
Looking quickly I think this is fixed by backporting https://github.com/scala/scala/pull/9226

**Comment by dongjoon-hyun** [comment]
Yep. It was fixed quickly but not released yet.
