### ISSUE TITLE
How can I use "mvn scala:doc" to make the latest version of scaladoc with new style? Why the scaladoc I make is with old style.

### ISSUE THREAD

**Issue by Wang-Zhihui** [scala/bug#12094]
How can I use "mvn scala:doc" to make the latest version of scaladoc with new style?
Like this: https://www.scala-lang.org/files/archive/api/current/index.html

Why the scaladoc I make is with old style.
Like this: https://www.scala-lang.org/api/2.10.3/#package

**Comment by SethTisue** [comment]
Maven support is over in https://github.com/davidB/scala-maven-plugin

**Comment by SethTisue** [comment]
https://github.com/davidB/scala-maven-plugin/issues/413
