### ISSUE TITLE
Implicit BuildFrom Not In Scope With Exclusive Range

### ISSUE THREAD

**Issue by adamgfraser** [scala/bug#12105]
## reproduction steps

Using Scala 2.13.3,

```scala
import scala.concurrent._
import scala.concurrent.ExecutionContext.global
  
implicit val ec = global
  
Future.traverse(1 until 10)(a => Future.unit)
// Cannot construct a collection of type scala.collection.immutable.AbstractSeq[Unit] with elements of type Unit based on a collection of type scala.collection.immutable.AbstractSeq[Int].
```

## problem

There is no implicit `CanBuildFrom` in scope here when the range is exclusive, even though there is when the range is inclusive. I would expect we should be able to build something here, especially when we can in seemingly the same situation if we just do `1 to 10` instead of `1 until 10`.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/11875 and others. "Fixed in dotty." Workaround is to provide type args or use `Range.inclusive`.
