### ISSUE TITLE
Array.min in 2.12.12 vs 2.13.3

### ISSUE THREAD

**Issue by kamilkloch** [scala/bug#12107]
Scala 2.12.12:
```scala
> println(Array(2.0, 1.0, Double.NaN).min)
NaN
```

Scala 2.13.3:
```scala
> println(Array(2.0, 1.0, Double.NaN).min)
1.0
```

Which one is correct? ;)

**Comment by Jasper-M** [comment]
There's some history on this topic https://github.com/scala/bug/issues/11844

**Comment by eed3si9n** [comment]
https://github.com/scala/scala/pull/8721 is the PR that came out of it and it should summarize the situation.

**Comment by NthPortal** [comment]
```scala
Welcome to Scala 2.12.12 (OpenJDK 64-Bit Server VM, Java 1.8.0_265).
Type in expressions for evaluation. Or try :help.

scala> Array(2.0, 1.0, Double.NaN, 3.0).min
res0: Double = 3.0
```

2.13.3 is the one that's correct (or at the very least more correct). I don't believe we can backport a fix (though I could be mistaken)

**Comment by eed3si9n** [comment]
`Array(2.0, 1.0, Double.NaN, 3.0).min` sounds like a clear bug in Scala 2.12.12, which I think we could backport a fix to return `NaN`.

However, in the original example, I would argue that _both_ are "correct" in the sense that they work as intended.

Scala 2.12.12 conforms to IEEE 754 floating point semantics, like `java.lang.Math.min(1.0, Double.NaN)` returning `NaN`.

Scala 2.13.3 on the other hand conforms to total ordering like `java.lang.Double.compare` being able to sort an array of Double.
