### ISSUE TITLE
Unsound cast on numeric literals via patmat

### ISSUE THREAD

**Issue by dwijnand** [scala/bug#12119]
using Scala 2.13.3,

```scala
scala> (1.0: Any) match { case x : 1 => x }
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
  at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:99)
```

Spin out from #11938, see 2nd half of https://github.com/scala/scala/pull/8874 for an attempt at fixing it.

**Comment by eed3si9n** [comment]
I guess throwing a MatchError _would_ make sense, and in practice you're probably right. But if I'm being a stickler about the specification, [3.2.2](https://scala-lang.org/files/archive/spec/2.13/03-types.html#literal-types) says

> At run time, an expression `e` is considered to have literal type `lit` if `e == lit`.

Thanks (no thanks) to cooperative equality, `1.0 == 1` evaluates as `true`. This should mean that the `(1.0: Any)` _should_ pass the typed pattern test `x: 1`. This is clearly repeated in section [8.2](https://scala-lang.org/files/archive/spec/2.13/08-pattern-matching.html#type-patterns):

> - A literal type _lit_. This type pattern matches only the value denoted by the literal _lit_ (the `==` method is used to compare the matched value to _lit_).

Given that `(1.0: Any) == 1`, `x` would be bound to `(1.0: Any)` under cooperative equality and the 2.13 spec.

**Comment by som-snytt** [comment]
That 3.2.2 should say `lit == e`.

This is unfortunate:
```
scala> val x: () = ()
val x: Unit = ()

scala> x match { case u: () => () }
                          ^
       error: identifier expected but ')' found.
```

Miles mentioned the non-pattern usage at some point as unintended leakage; I guess the pattern case is the intended exclusion in 3.2.2. The empty tuple pattern `()` is covered by 8.1.8 as someone mentioned on a recent ticket (apropos of how infix `x y ()` is parsed).

**Comment by som-snytt** [comment]
We need a label `should not compile that way`.

**Comment by dwijnand** [comment]
Part of the reason I descoped (for myself) this part of the original issue was because the battle rages on in July 2020 on this: https://github.com/lampepfl/dotty/issues/9359 (and I was looking for less untested waters).
