### ISSUE TITLE
scala compiler warns when matching against enums with a deprecated value

### ISSUE THREAD

**Issue by dsilvasc** [scala/bug#12114]
## reproduction steps

Using java 8,

```java
// ExampleEnum.java

public enum ExampleEnum {
    FIRST,
    @Deprecated
    SECOND,
    THIRD
}
```

using Scala 2.12,

```scala
package example

object EnumConsumer extends App {
  def consume(e: ExampleEnum): String =
    e match {
      case ExampleEnum.FIRST => "first"
      case ExampleEnum.SECOND => "second"
      case ExampleEnum.THIRD => "third"
    }

  for (e <- ExampleEnum.values()) {
    println(consume(e))
  }
}
```

## problem
Compile with fatal warnings, and the compiler rejects the code above:

```
EnumConsumer.scala:7: Java enum SECOND in Java enum ExampleEnum is deprecated: see corresponding Javadoc for more information.
one error found
```

If you comment out the line it complains about, then the compiler rejects the code with:

```
EnumConsumer.scala:5: match may not be exhaustive.
It would fail on the following input: SECOND
one error found
```

Switching to if/else doesn't help either:

```scala
  def consume(e: ExampleEnum): String =
    if (e == ExampleEnum.FIRST) "first"
    else if (e == ExampleEnum.SECOND) "second"
    else "third"
```

```
EnumConsumer.scala:6: Java enum SECOND in Java enum ExampleEnum is deprecated: see corresponding Javadoc for more information.
one error found
```

It would be reasonable for the scala compiler to warn about producing the enum value, since the deprecation annotation discourages creating the value.  It's still necessary to handle the value passed in by others though, and it's still necessary to include it in the match for it to be exhaustive.

The compiler shouldn't warn about matching deprecated enum values.

**Comment by dwijnand** [comment]
The downside of doing this is that when, eventually, the enum case _is_ deleted that code will go straight from compiling without any warnings to not compiling at all, which isn't how deprecation cycles normally go.  Not sure if that makes the proposed changed a bad idea or not, or what else to do...

**Comment by eed3si9n** [comment]
I'd suggesting using nowarn (https://www.scala-lang.org/api/2.13.3/scala/annotation/nowarn.html) or https://github.com/ghik/silencer in this situation. It's case by case how much library wants to handle legacy values.

**Comment by SethTisue** [comment]
Yeah, I don't see a need to change anything here. Both warnings (the deprecation one and the exhaustive-match one) seem correct to me.

Another way of evading the warnings: `case _ => ...`

**Comment by dsilvasc** [comment]
It's not really a choice whether to handle legacy values or not though.  Suppose you write some state to disk, serialized as protocol buffers.  The protobuf schema contains an [enum](https://developers.google.com/protocol-buffers/docs/proto3#enum), and your data on disk now contains those values.

Then you deprecate an enum value in the protobuf schema, to signal that new data shouldn't be written with that value.  Your code still needs to handle that value, because it still exists on disk for pre-existing data.

Once all writers and all data have been migrated, then you can remove the value from the schema.

Replace disk with network and it's the same situation for services needing to handle remote payloads from external sources who haven't migrated (both requests from old clients and responses from old upstream services).

**Comment by dwijnand** [comment]
Seems like in your case, the choice is made for you: you must continue to handle the enum - and then, of course, don't want to see noise about it.  But in other situations, with other enums, users might want to choose to migrate off of the deprecated enum.  So I'm feeling stronger that suppressing the warning in pattern matching isn't universally correct.

Does suppressing the warning with `@nowarn` or `-Wconf` or `@silent` (on older versions) not work for you?

**Comment by dsilvasc** [comment]
Thanks for the pointer to `@silent` for 2.12 (we're pending a couple of deps before we can go to 2.13).  I can suppress the warning, but I was just having a hard time seeing where it would be the value consumer's fault that the value inhabits the enum type and therefore must be handled to avoid a runtime MatchError.

**Comment by joroKr21** [comment]
But that is true for anything deprecated. You must continue using it until you can migrate away. That is the whole point of deprecation cycles, to give you time.

**Comment by SethTisue** [comment]
In addition to the arguments already made, I would add:

The rule is simple: if you mention a deprecated thing, you get a deprecation warning. (Which you are free to suppress.)

The value of keeping the rule dead simple (easy to understand, easy to implement correctly) exceeds the value of adding narrow, difficult-to-characterize exceptions.

**Comment by dwijnand** [comment]
> I was just having a hard time seeing where it would be the value consumer's fault that the value inhabits the enum type and therefore must be handled to avoid a runtime MatchError.

The example in my head was something like

```java
/**
  * @Deprecated Notifying users via SMS is a deprecated practice.
  */
enum Notify {
  None,
  @Deprecated SendSms,
  Tweet
}
```

and the Scala user would change their code

```scala
   notifications.foreach {
-    case SendSms => sendSms(data)
     case Tweet   => tweet(data)
     case _       =>
   }
```

**Comment by dsilvasc** [comment]
I see.  There's a risk with that approach: when you add Email to Notify, the compiler will not remind/require you anymore to handle `case Email`, because of the `case _`.

**Comment by dwijnand** [comment]
Yeah, I'm a big exhaustivity fan so I wouldn't do it that way either.

But I'd be making my own choice to keep a reference to a deprecated piece of API and suppressing the warning, while another user might be perfectly happy to drop the reference making their code ready for the removal.  Without the warning the second user wouldn't get the prompt to make the change.

Add that to Seth's KISS reason, and I think this is the right choice.

**Comment by dsilvasc** [comment]
Makes sense.  Thanks everyone for your consideration 👍
