### ISSUE TITLE
collection.Set and immutable.Set's removeAll/-- operator is too expensive

### ISSUE THREAD

**Issue by texasbruce** [scala/bug#12120]
## reproduction steps

using Scala 2.13.x,

```scala
  def removedAll(that: IterableOnce[A]): C = that.iterator.foldLeft[C](coll)(_ - _)

  override final def -- (that: IterableOnce[A]): C = removedAll(that)
```

## problem

When removing a collection of items from the Set, it will perform a `foldLeft` on the immutable `coll` (as shown above), which essentially creates N-1 intermediate collections (N = size of that) in the while loop in the `foldLeft` method, which are then discarded right away and adding GC pressure.

Possible solutions can be either an old-fashioned `while` loop and adding each element to a mutable Set, or a `View.Filter`

**Comment by NthPortal** [comment]
it's a balancing act. as it currently is, for small values of `that`, the current implementation is quite efficient. for values of `that` approaching the size (and the same values as) `this`, it becomes less efficient, and your implementation would probably be more efficient. it is also worth noting that regardless of the size of `that`, if none of its elements are in `this`, the current implementation remains quite efficient (`-`/`removed` typically return `this` if `this` does not contain the element). your proposed implementation imposes a fixed cost proportional to the size of `this`, which may not be justified in many (perhaps most?) cases.

**Comment by SethTisue** [comment]
perhaps it's better to leave `--` alone and let people use `filterNot`+`contains` if they expect workloads that would be more efficient that way?

**Comment by NthPortal** [comment]
another alternative: if `that` is a `Set`, consider using `diff`

**Comment by texasbruce** [comment]
> it's a balancing act. as it currently is, for small values of `that`, the current implementation is quite efficient. for values of `that` approaching the size (and the same values as) `this`, it becomes less efficient, and your implementation would probably be more efficient. it is also worth noting that regardless of the size of `that`, if none of its elements are in `this`, the current implementation remains quite efficient (`-`/`removed` typically return `this` if `this` does not contain the element). your proposed implementation imposes a fixed cost proportional to the size of `this`, which may not be justified in many (perhaps most?) cases.

We can optimze based on `that` size and how many elements intersect.

Space wise,
For intersection N = 0, current impl creates no extra collection, my propsal creates 2 extra collection (1 builder/mutable, 1 end result), or 1 View + 1 Result (we can check isEmpty/Iterator.hasNext)
For intersection N = 1, current impl creates 1 extra collection, my proposal stays the same.
For intersection N >= 2, curr creates N extra collections, my proposal stays the same.

I don't think we should make assumption what most cases are, but I don't think sets intersection <= 1 cover most cases.


> another alternative: if `that` is a `Set`, consider using `diff`

It's another pointer here. For `Set`, `diff` and `removeAll` behave the same. We should probably merge the implementation.

**Comment by NthPortal** [comment]
> For intersection N = 1, current impl creates 1 extra collection

you cannot compare creating a new collection when adding/removing a single element to rebuilding the entire collection. due to structural sharing, the cost of adding a single element is cheap for most implementations (O(1) or O(log n)); however, the cost of rebuilding the entire collection is high (O(n)). Most implementations (including the default ones) are specially designed, optimised collections that have high degrees of structural sharing and require minimal rebuilding when adding or removing elements.

> It's another pointer here. For `Set`, `diff` and `removeAll` behave the same.

They do not. `diff` builds up from an empty collection. perhaps it ought to use a builder rather than `+`, but that's a separate argument.

**Comment by texasbruce** [comment]
> you cannot compare creating a new collection when adding/removing a single element to rebuilding the entire collection. due to structural sharing, the cost of adding a single element is cheap for most implementations (O(1) or O(log n))

Can you elaborate on `structural sharing` for `Set`? AFAIK Set uses `HashSet` as underlying collection, which in turn uses `Array` for content and hashes. Each mutation will trigger `arraycopy` method and rebuild a whole array.

**Comment by SethTisue** [comment]
> Can you elaborate on structural sharing for Set? 

https://github.com/scala/scala/commit/d5ae93e1b35fac4002cfbffff9ec741356549e08
