### ISSUE TITLE
Overriding implict def without explicit implicit keyword causes implict to be removed

### ISSUE THREAD

**Issue by texasbruce** [scala/bug#12123]
## reproduction steps

using Scala 2.13.x,

```scala
trait FooT {
  implicit def s: String
  def print()(implicit s: String) = println(s)
  
}

class Foo extends FooT {
  override def s = "Foo"
  // override implict def s = "Foo" // Require explicit implicit to work

  print()
}

new Foo
```

It gives error:

    could not find implicit value for parameter s: String

## problem

Overriding implict def without explicit implicit keyword causes implict to be removed.

In a subclass, implicit should be maintained if it is implicit in parent class no matter whether implicit keyword is provided in the subclass.

**Comment by som-snytt** [comment]
Overriding without `implicit` is the Scala 2 idiom for "disabling" an implicit in lexical scope. (The shadowing def doesn't have to be an override.)

Therefore, I think this proposal would not be entertained.

Scala 3 has different rules for implicit resolution and there is no shadowing of implicit definitions.

**Comment by texasbruce** [comment]
@som-snytt it seems counterintuitive. Subclasses should inherit parent class'es characteristics IMO. But it's up for debates I guess

**Comment by som-snytt** [comment]
Yes, there are a few aspects of implicit look-up that were deemed less than optimal. Hopefully the mechanisms in Scala 3 will feel intuitive and ergonomic.

**Comment by SethTisue** [comment]
I agree that changing this is out of scope for Scala 2.
