### ISSUE TITLE
scala.reflect.internal.Types$TypeRef.computeHashCode(Types.scala:2416) NPE

### ISSUE THREAD

**Issue by TeXSatz** [scala/bug#12122]
## reproduction steps
Using 
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment Corretto-11.0.8.10.1 (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.8.10.1 (build 11.0.8+10-LTS, mixed mode)
or the Java from sbt: 14.0.1
under MacOS 10.15.6
with sbt 1.3.13 and Scala 2.13.3

[scala-bug.zip](https://github.com/scala/bug/files/5095627/scala-bug.zip)

  sbt compile

of the attached sbt project
(with a commented version that works)
reports

## problem

[info] Compiling 1 Scala source to .../scala-bug/target/scala-2.13/classes ...
[error] ## Exception when compiling 1 sources to .../scala-bug/target/scala-2.13/classes
[error] java.lang.NullPointerException
[error] scala.reflect.internal.Types$TypeRef.computeHashCode(Types.scala:2416)
[error] scala.reflect.internal.Types$UniqueType.<init>(Types.scala:1084)
[error] scala.reflect.internal.Types$TypeRef.<init>(Types.scala:2359)
[error] scala.reflect.internal.Types$ArgsTypeRef.<init>(Types.scala:2109)
[error] scala.reflect.internal.Types$ClassArgsTypeRef.<init>(Types.scala:2730)
[error] scala.reflect.internal.Types$TypeRef$.apply(Types.scala:2754)
[error] scala.reflect.internal.Types.copyTypeRef(Types.scala:4089)
[error] scala.reflect.internal.Types.copyTypeRef$(Types.scala:4081)
[error] scala.reflect.internal.SymbolTable.copyTypeRef(SymbolTable.scala:28)
[error] scala.reflect.internal.Types.appliedType(Types.scala:4158)
[error] scala.reflect.internal.Types.appliedType$(Types.scala:4143)
[error] scala.reflect.internal.SymbolTable.appliedType(SymbolTable.scala:28)
[error] scala.reflect.internal.Types.appliedType(Types.scala:4176)
[error] scala.reflect.internal.Types.appliedType$(Types.scala:4175)
[error] scala.reflect.internal.SymbolTable.appliedType(SymbolTable.scala:28)
[error] scala.reflect.internal.Definitions$DefinitionsClass$VarArityClass.specificType(Definitions.scala:623)
[error] scala.reflect.internal.Definitions$DefinitionsClass.functionType(Definitions.scala:641)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedFunctionUndoingEtaExpansion$5(Typers.scala:3150)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedFunctionUndoingEtaExpansion(Typers.scala:73)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedFunction(Typers.scala:3044)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typed1$105(Typers.scala:5857)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedFunction$1(Typers.scala:492)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedOutsidePatternMode$1(Typers.scala:5894)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5926)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedArg(Typers.scala:3415)
[error] scala.tools.nsc.typechecker.Typers$Typer.handlePolymorphicCall$1(Typers.scala:3811)
[error] scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3830)
[error] scala.tools.nsc.typechecker.Typers$Typer.tryNamesDefaults$1(Typers.scala:3651)
[error] scala.tools.nsc.typechecker.Typers$Typer.doTypedApply(Typers.scala:3726)
[error] scala.tools.nsc.typechecker.Typers$Typer.normalTypedApply$1(Typers.scala:5051)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedApply$1(Typers.scala:5060)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5916)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
[error] scala.tools.nsc.typechecker.Typers$Typer.computeType(Typers.scala:6062)
[error] scala.tools.nsc.typechecker.Namers$Namer.assignTypeToTree(Namers.scala:1128)
[error] scala.tools.nsc.typechecker.Namers$Namer.valDefSig(Namers.scala:1740)
[error] scala.tools.nsc.typechecker.Namers$Namer.memberSig(Namers.scala:1914)
[error] scala.tools.nsc.typechecker.Namers$Namer.typeSig(Namers.scala:1878)
[error] scala.tools.nsc.typechecker.Namers$Namer$ValTypeCompleter.completeImpl(Namers.scala:945)
[error] scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete(Namers.scala:2062)
[error] scala.tools.nsc.typechecker.Namers$LockingTypeCompleter.complete$(Namers.scala:2060)
[error] scala.tools.nsc.typechecker.Namers$TypeCompleterBase.complete(Namers.scala:2055)
[error] scala.reflect.internal.Symbols$Symbol.completeInfo(Symbols.scala:1546)
[error] scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1518)
[error] scala.reflect.internal.Symbols$Symbol.initialize(Symbols.scala:1707)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5573)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6051)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:2058)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedModuleDef(Typers.scala:1934)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5883)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:6051)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$8(Typers.scala:3397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3397)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5582)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5885)
[error] scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5973)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:117)
[error] scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
[error] scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.run(Analyzer.scala:105)
[error] scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1515)
[error] scala.tools.nsc.Global$Run.compileUnits(Global.scala:1499)
[error] scala.tools.nsc.Global$Run.compileSources(Global.scala:1491)
[error] scala.tools.nsc.Global$Run.compile(Global.scala:1626)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:153)
[error] xsbt.CachedCompiler0.run(CompilerInterface.scala:125)
[error] xsbt.CompilerInterface.run(CompilerInterface.scala:39)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error] java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error] java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error] java.base/java.lang.reflect.Method.invoke(Method.java:564)
[error] sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:248)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:122)
[error] sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:95)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:91)
[error] scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
[error] sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:186)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
[error] sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3$adapted(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:215)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:77)
[error] sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:146)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error] sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error] scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] sbt.Execute.work(Execute.scala:290)
[error] sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] java.base/java.lang.Thread.run(Thread.java:832)
...
sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:343)
[error] 	at sbt.internal.inc.Incremental$.doCompile(Incremental.scala:120)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:100)
[error] 	at sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:180)
[error] 	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:98)
[error] 	at sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:102)
[error] 	at sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:155)
[error] 	at sbt.internal.inc.Incremental$.compile(Incremental.scala:92)
[error] 	at sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:75)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:348)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:301)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:168)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:248)
[error] 	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:74)
[error] 	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1765)
[error] 	at sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1738)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[error] 	at java.base/java.lang.Thread.run(Thread.java:832)
[error] (Compile / compileIncremental) java.lang.NullPointerException

**Comment by som-snytt** [comment]
This is due to improved parameter type inference introduced in 2.12.8 and 2.13, where only some parameters in a function literal have ascribed types.

Note that in the attached sample, the "extra" ascription is not necessary:
```
(replyTo: ActorRef[StreamAck], element) => StreamMsg(replyTo, element)
```
In the sample that works, the unascribed type is inferred from the expected type and not from the application in the function body.
