### ISSUE TITLE
java annotation Array constants have to be specified using the `Array(...)` factory method 2.13.3

### ISSUE THREAD

**Issue by stephennancekivell** [scala/bug#12133]
I have some java classes that have annotations that are now crashing after upgrading to 2.13.3

## reproduction steps

Using Scala 2.13.3, but its a java file.

```java
@Entity
@Table(name = "portal", uniqueConstraints = @UniqueConstraint(columnNames = {"account_id_fk", "name"}))
...
```

## problem
```
Array constants have to be specified using the `Array(...)` factory method
@Table(name = "portal", uniqueConstraints = @UniqueConstraint(columnNames = {"account_id_fk", "name"}))
```
I expect this to compile like it did in 2.13.2.

If I try the suggestion it doesnt work, just say the next line is illegal eg, `illegal start of type declaration`
```java
@Entity
@Table(name = "portal", uniqueConstraints = @UniqueConstraint(columnNames = Array("account_id_fk", "name")))
...
```

This seems like it might be related to https://github.com/scala/scala/pull/8781

edit: I should mention these annotations are from javax.persistence

Thanks

**Comment by SethTisue** [comment]
@dwijnand ?

**Comment by stephennancekivell** [comment]
Hi @dwijnand Im still getting the same error in a recent 2.13.4 snapshot.

I see your fix has been merged into 2.12 but I'm not familiar with how it should get into the 2.13 branch. How should that happen.

I've put together a minimal reproduction here https://github.com/stephennancekivell/scala-12133

Thanks
![image](https://user-images.githubusercontent.com/727013/93282378-a388b780-f811-11ea-907c-99eeb6c259bd.png)

**Comment by som-snytt** [comment]
@stephennancekivell there is a "merge forward" PR in flight https://github.com/scala/scala/pull/9206

**Comment by stephennancekivell** [comment]
Oh, thanks for explaining @som-snytt, that makes sense.
