### ISSUE TITLE
Pattern matching cannot deduce generic type when the generic type given in the extractor parameter

### ISSUE THREAD

**Issue by texasbruce** [scala/bug#12147]
## reproduction steps

using Scala 2.13.x,

```scala
scala> case class Foo[T](foo: T)
class Foo

scala> def doFooInt(foo: Foo[Int]) = ()
def doFooInt(foo: Foo[Int]): Unit

scala> def doMessage(x: Any) = x match { case f@Foo(_: Int) => doFooInt(f) }
                                                                        ^
       error: type mismatch;
        found   : Foo[Any]
        required: Foo[Int]
       Note: Any >: Int, but class Foo is invariant in type T.
       You may wish to define T as -T instead. (SLS 4.5)
```

## problem

When pattern matching `f@Foo(_: Int)`, compiler should be able to deduce the type of `f` to be `Foo[Int]` instead of `Foo[Any]` because it is already provided in the pattern.

Currently it needs to be manually casted like

```scala
case f@Foo(_: Int) => doFooInt(f.asInstanceOf[Foo[Int]])
```

**Comment by martijnhoekstra** [comment]
This shouldn't compile, the example is unsound.

**Comment by martijnhoekstra** [comment]
making this compile would allow this unsound behaviour:

```
case class Foo[T](element: T) {
  var otherElement: T = element
}

def doFooInt(foo: Foo[Int]) = {
  println(foo.otherElement + foo.element)
}
val foo = new Foo[Any](1)
foo.otherElement = "foo"

def doMessage(x: Any) = x match {
  case f@Foo(_: Int) => doFooInt(f)
}

doMessage(foo)

```

**Comment by dwijnand** [comment]
As an invariant `Foo[T]`, I agree.  But should it work as a covariant `Foo[+T]`?  How do you construct an unsound example for a covariant type?

**Comment by martijnhoekstra** [comment]
```
class Foo[+T](val elementOne: T, val elementTwo: T)
object Foo {
  def unapply[T](f: Foo[T]) = Some(f.elementOne)
}

def doFooInt(foo: Foo[Int]) = {
  foo.elementOne + foo.elementTwo
}
val foo = new Foo(1, "foo")

def doMessage(x: Any) = x match {
  case f@Foo(_: Int) => doFooInt(f)
}

doMessage(foo)


```

**Comment by dwijnand** [comment]
Nice, thanks.  I guess that restricts us to fixing it for the synthetic unapplies only.

**Comment by dwijnand** [comment]
It's required that `case f@Foo(_: Int, _) => doFooInt(f)` infers `T=Any` not `T=Int`.

**Comment by som-snytt** [comment]
Extractor pattern is different from constructor pattern, just to clarify terms. Constructor of a case class is the normal thing.

**Comment by martijnhoekstra** [comment]
```
case class Foo[+T](element: T) {
  def otherElement: T = element
}

class MoreThanFoo(i: Int) extends Foo[Any](i) {
  override val otherElement: Any = "no"
}

def doFooInt(foo: Foo[Int]) = {
  println(foo.otherElement + foo.element)
}

def doMessage(x: Any) = x match {
  case f@Foo(_: Int) => doFooInt(f)
}

doMessage(new MoreThanFoo(1))
```

**Comment by dwijnand** [comment]
OK, nice.  I guess "yes, but only if it's covariant, final, and using the synthetic unapply" is too much.

I'm happy to close this.

**Comment by texasbruce** [comment]
What would be a good practice in this case? Do we have any better solution than manual casting?

**Comment by texasbruce** [comment]
> 
> 
> ```
> class Foo[+T](val elementOne: T, val elementTwo: T)
> object Foo {
>   def unapply[T](f: Foo[T]) = Some(f.elementOne)
> }
> 
> def doFooInt(foo: Foo[Int]) = {
>   foo.elementOne + foo.elementTwo
> }
> val foo = new Foo(1, "foo")
> 
> def doMessage(x: Any) = x match {
>   case f@Foo(_: Int) => doFooInt(f)
> }
> 
> doMessage(foo)
> ```

How about strictly for case class only?

**Comment by martijnhoekstra** [comment]
case Foo(a: Int) => doFooInt(Foo(a))

**Comment by texasbruce** [comment]
> 
> ```
> case Foo(a: Int) => doFooInt(Foo(a))
> ```

That wouldn't work for classes with var members which value could be changed. And it is creating unnecessary objects that can pressure GC.

**Comment by texasbruce** [comment]
Can we allow providing the type parameter to extractor? e.g.

    case f@Foo[Int](_: Int) => doFooInt(f)

This is basically just like explicitly providing the type parameter to unapply method.

**Comment by martijnhoekstra** [comment]
The cast is your only way out of this match I'm afraid. Be careful though, since the cast is just as unsound as the match. I'm afraid we're veering a bit far off topic from bug reporting though.

**Comment by texasbruce** [comment]
> 
> 
> The cast is your only way out of this match I'm afraid. Be careful though, since the cast is just as unsound as the match. I'm afraid we're veering a bit far off topic from bug reporting though.

Do you think my previous post of providing the type parameter is a valid proposal? If so, we can close this issue and I'll open a feature request

**Comment by dwijnand** [comment]
Your type parameter example (type argument actually) is just as hazardous as Martijn's `MoreThanFoo` example (https://github.com/scala/bug/issues/12147#issuecomment-690216999).

If matching `Foo[Int]`s is a common occurrence in different patterns in your codebase, you might want to consider writing a custom extractor that does `case f@Foo(_: Int) => f.asInstanceOf[Foo[Int]]`, having proven to yourself (and remain responsible for upholding) that that's a sound cast.

**Comment by texasbruce** [comment]
> 
> 
> Your type parameter example (type argument actually) is just as hazardous as Martijn's `MoreThanFoo` example ([#12147 (comment)](https://github.com/scala/bug/issues/12147#issuecomment-690216999)).
> 
> If matching `Foo[Int]`s is a common occurrence in different patterns in your codebase, you might want to consider writing a custom extractor that does `case f@Foo(_: Int) => f.asInstanceOf[Foo[Int]]`, having proven to yourself (and remain responsible for upholding) that that's a sound cast.

If that is the only invalid scenario, we can still make `final case class` behave this way right? IMHO case classes should be final either way

**Comment by NthPortal** [comment]
> Can we allow providing the type parameter to extractor?

only sound if you have evidence (i.e. `ClassTag`); otherwise the type is unchecked at runtime

**Comment by dwijnand** [comment]
> If that is the only invalid scenario, we can still make `final case class` behave this way right? IMHO case classes should be final either way

Yeah, as I said earlier "only if it's covariant, final, and using the synthetic unapply", but that's too many if's, IMO.
