### ISSUE TITLE
Implicit conversion from Java BigDecimal to Scala BigDecimal NPEs on null input

### ISSUE THREAD

**Issue by krmoore2010** [scala/bug#12146]
I have a piece of code that converts the data in a SQL query to a string or null using a function:-

```scala
  def dataToString(resultSet: ResultSet, metaData: ResultSetMetaData, index: Int): String = {
    metaData.getColumnClassName(index) match {
      case "java.lang.Integer" => resultSet.getInt(index).toString
      case "java.sql.Timestamp" => fmtTimestampAsDate(resultSet.getTimestamp(index))
      case "java.lang.String" => resultSet.getString(index)
      case "java.math.BigDecimal" =>
        val v = resultSet.getBigDecimal(index)
        println(v)
        fmtMoney(v)
      case x@_ =>
        println(s"UN-HANDLED TYPE: $x")  //add new types as  needed
        resultSet.getObject(index).toString
    }
  }

 def fmtMoney(money: BigDecimal): String = {
      if (money == null) {
        null
      } else {
        val df = new DecimalFormat("###0.00")
        df.format(money)
      }
    }
```

However, this code doesn't work as expected because 

I've seen a bug report where it says this shouldn't handle null but in this instance, I'm not sure. This code blows up with:-
Exception in thread "main" java.lang.IllegalArgumentException: null value for BigDecimal

The return from resultSet.getBigDecimal(index) is null I would expect v to null and not promoted to  a BigDecimal 

if write fmtMoney(null)  this works as expected.

I'm not sure promotion from null to  BigDecimal should occur which is the opposite of an earlier reported bug on this.

Ken

**Comment by SethTisue** [comment]
most of this code doesn't seem relevant to the issue — can you reduce it to an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) so we can evaluate it?

**Comment by SethTisue** [comment]
> which is the opposite of an earlier reported bug on this

link?

**Comment by krmoore2010** [comment]
Hi,

This code illustrates it:-

object Test extends App {
  //this return java.math.BigDecimal or null so implicit conversion is required to scala BigDecimal
  def funcReturningBigDecimalOrNull(returnNull: Boolean): java.math.BigDecimal = if (returnNull) null else new java.math.BigDecimal("0.00")

  def methodWithBigDecimalParameter(bd: BigDecimal): String = {
    if (bd == null) null else bd.toString()
  }

  val v = funcReturningBigDecimalOrNull(true)  //v is assigned null
  println(v) //this prints null
  methodWithBigDecimalParameter(v)  //this call fails there is an implicit conversion implicit def javaBigDecimal2bigDecimal(x: BigDec): BigDecimal = apply(x) happening on a null value
}


The java library I’m using returns a java.math.BigDecimal so I’ve done the same in scala.


Ken

**Comment by krmoore2010** [comment]
https://github.com/scala/bug/issues?q=is%3Aissue+javaBigDecimal2bigDecimal+is%3Aclosed

Link to a closed bug report

**Comment by krmoore2010** [comment]
The question is should it attempt to convert the null to BigDecimal or leave it as null?

**Comment by SethTisue** [comment]
Is this actually specific to `BigDecimal`, or is it just a question/report about how implicit conversions work?

**Comment by krmoore2010** [comment]
Also methodWithBigDecimalParameter(null) works as expected.

**Comment by krmoore2010** [comment]
its why  does  v:java.math.BigDecimal = null behave differently in   function(v)  to  function(null)  it's not what I would expect.
should the implicit be:-

implicit def javaBigDecimal2bigDecimal(x: BigDec): BigDecimal = if (x == null) null else apply(x)

**Comment by SethTisue** [comment]
thanks, this is clear now.

previous discussions in this area: https://github.com/scala/bug/issues/9176, https://github.com/scala/bug/issues/10638

**Comment by SethTisue** [comment]
the MCVE here is simply:

```scala
scala 2.13.3> (null: java.math.BigDecimal): BigDecimal
java.lang.IllegalArgumentException: null value for BigDecimal
  ... 35 elided
```

**Comment by dwijnand** [comment]
@cahilltr ping back, so I can assign you

**Comment by cahilltr** [comment]
Thanks @dwijnand

**Comment by krmoore2010** [comment]
Hi thanks for fixing that I was also trying to make a more general point that no implicit conversion should be done on a null not just the BigDecimal case. Because it's not possible to know the type of null. I wondered if this should be handled by the complier and not just by using an if  statement in the conversion function. It would need to generate a runtime check for null though.

**Comment by SethTisue** [comment]
@krmoore2010 you might try starting a thread in https://contributors.scala-lang.org about it, since what you're suggesting is a design change that would also require a spec change. I'm not sure if this has been discussed before.

**Comment by SethTisue** [comment]
I think https://github.com/scala/bug/issues/9176 is our ticket on the more general considerations here.
