### ISSUE TITLE
Tailrec call as lambda is not recognised

### ISSUE THREAD

**Issue by ye-yu** [scala/bug#12153]
I am converting a loop into a tailrec function as such:

```scala
@tailrec
final def repeat(intConsumer: Int => Unit, count: Int, start: Int = 0): Unit = {
    val next = () => if (start < count) repeat(intConsumer, count, start + 1)
    intConsumer(start)
    next()
}
```

However, it seems that the scala compiler does not recognise that the call to `next()` is recursive. Scala can compile the following code despite having the same objective:

```scala
@tailrec
final def repeat(intConsumer: Int => Unit, count: Int, start: Int = 0): Unit = {
    intConsumer(start)
    if (start < count) repeat(intConsumer, count, start + 1)
}
```

My objective is to simplify the recursive call as lambda in case I have a complex loop like:

```scala
@tailrec
final def repeat(..., count: Int, start: Int = 0): Unit = {
    val next = () => if (start < count) repeat(..., count, start + 1)
   // long codes
    if (conditionIsNotMet) {
        next()
        return
    }
   // another long codes
    if (anotherConditionIsNotMet) {
        next()
        return
    }
   // another long codes
    next() // finish process
}
```

Currently, this is not possible because the compile will return the error of:
> could not optimize @tailrec annotated method repeat: it contains a recursive call not in tail position

Otherwise, feel free to inform if this is not a good case for a tailrec function. Thank you.

**Comment by dwijnand** [comment]
I think it's outside of the budget intended for `@tailrec` to be able to recognise those code shapes as being tail recursive (sadly!).  So, while there's nothing erroneous in this issue, I think closing it would better reflect the reality that it isn't going to be addressed.

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org for questions
