### ISSUE TITLE
Unbreak 2.13.x's DeterminismTest testReferenceToInnerClassMadeNonPrivate

### ISSUE THREAD

**Issue by dwijnand** [scala/bug#12156]
If https://github.com/scala/scala/pull/9206 is merged, `scala.tools.nsc.DeterminismTest.testReferenceToInnerClassMadeNonPrivate` needs to be un-`@Ignore`'d and fixed.

**Comment by retronym** [comment]
`git bisect` tells me that the behaviour of `exitingTyper(sym.isPrivate)` for inner class symbols that have `notPRIVATE` set

```
import scala.reflect.internal.Flags._; Predef.assert(exitingTyper(NoSymbol.newTermSymbol(nme.EMPTY).setFlag(PRIVATE | notPRIVATE).isPrivate))
```

broke in:

7ad3a2e0335af2de43f8f727dacf7e238bc7cf71 "Move the patmat phase after superaccessors"

**Comment by retronym** [comment]
Oh of course, it should be `enteringPhase`.
