### ISSUE TITLE
Compiling Scala code optimized makes bytecode bind to "hidden" classes which creates ABI compatibility issues

### ISSUE THREAD

**Issue by mrange** [scala/bug#12162]
Hi.

At work we recently ran into and issue when we upgraded from `org.scala-lang:scala-library:2.12.10` to `org.scala-lang:scala-library:2.12.12` in one of our components.

[embeddedkafka](https://mvnrepository.com/artifact/io.github.embeddedkafka/embedded-kafka_2.12/2.5.0) start failing with no class def found error: 

```
  Cause: java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$7
  at kafka.api.ApiVersion$.orderingByVersion(ApiVersion.scala:45)
  at kafka.api.ApiVersion.compare(ApiVersion.scala:139)
  at kafka.api.ApiVersion.compare$(ApiVersion.scala:138)
```

As this is minor version upgrade of scala lib this was surprising to us.

I took a look at the [kafka code](https://github.com/apache/kafka/blob/57de67db22eb373f92ec5dd449d317ed2bc8b8d1/core/src/main/scala/kafka/api/ApiVersion.scala#L45) and believe this code could be the issue:
```scala
implicit def orderingByVersion[A <: ApiVersion]: Ordering[A] = Ordering.by(_.id) // Line 45
```

I tried reproducing this locally but was unsuccessful until applying `-optimize` flag.

## reproduction steps

using Scala 2.12.10 (with -optimize),

```scala
package abi_test

object ApiVersion {
  implicit def orderingByVersion[A <: ApiVersion]: Ordering[A] = Ordering.by(_.id)
}

case class ApiVersion(id: Int)

object Program {
  def main(args: Array[String]): Unit = {
    val x = ApiVersion(1)
    val y = ApiVersion(2)
    val z = ApiVersion.orderingByVersion.compare(x, y)
    println(s"Hello world: $z")
  }
}
```

## problem

When analyzing the bytecode of the optimized build we find this for the `implicit val`

```
public <A extends abi_test.ApiVersion> scala.math.Ordering<A> orderingByVersion();
    Code:
       0: getstatic     #34                 // Field scala/package$.MODULE$:Lscala/package$;
       3: invokevirtual #38                 // Method scala/package$.Ordering:()Lscala/math/Ordering$;
       6: invokedynamic #59,  0             // InvokeDynamic #0:apply:()Lscala/Function1;
      11: getstatic     #62                 // Field scala/math/Ordering$Int$.MODULE$:Lscala/math/Ordering$Int$;
      14: astore_2
      15: astore_1
      16: ifnonnull     21
      19: aconst_null
      20: athrow
      21: new           #14                 // class scala/math/Ordering$$anon$7
      24: dup
      25: aload_2
      26: aload_1
      27: invokespecial #65                 // Method scala/math/Ordering$$anon$7."<init>":(Lscala/math/Ordering;Lscala/Function1;)V
      30: areturn
```

The problem starts here: `21: new           #14                 // class scala/math/Ordering$$anon$7`

`Ordering$$anon$7` is a hidden class and it turns out that in `2.12.12` this class is gone (possible renamed to `Ordering$$anon$5`). When JVM looks for `Ordering$$anon$7` it doesn't find it and crashes.

In an non-optimized build it looks like this:

```
public <A extends abi_test.ApiVersion> scala.math.Ordering<A> orderingByVersion();
    Code:
       0: getstatic     #32                 // Field scala/package$.MODULE$:Lscala/package$;
       3: invokevirtual #36                 // Method scala/package$.Ordering:()Lscala/math/Ordering$;
       6: invokedynamic #57,  0             // InvokeDynamic #0:apply:()Lscala/Function1;
      11: getstatic     #60                 // Field scala/math/Ordering$Int$.MODULE$:Lscala/math/Ordering$Int$;
      14: invokevirtual #66                 // Method scala/math/Ordering$.by:(Lscala/Function1;Lscala/math/Ordering;)Lscala/math/Ordering;
      17: areturn
```

To my untrained eye this doesn't involve any hidden symbols and works for `2.12.12` as well.

To us it it means that we are kind of stuck on `2.12.10` for now when we use `embeddedkafka` is it transitively depends on `kafka` which seems compiled with `optimize` flag (the bytecode is very similar).

## musings

This might well be intended behavior but it seems to me that if we use optimized builds or use dependencies (transitively) that uses optimized builds we need to be very careful when picking the scala library version.

As the code most likely is API compatible a possible mitigation for us would be to build our own versions of embedded kafka and kafka without the optimize flag but that is time I would rather spend on something else.

I am very grateful for any ideas on mitigations or if I messed up somehow.

PS. I did search github issues but didn't find something that described this issue. Ofc if it is a duplicate please close it.

**Comment by lrytz** [comment]
This is a known limitation when using the optimizer. It's unfortunate you did not come across any information about it. If you have suggestions where we can put additional links (doc sites, scala site, compiler help output, ...) to build awareness, that is very welcome.

https://www.lightbend.com/blog/scala-inliner-optimizer

**Comment by mrange** [comment]
Thanks, I will consult the documentation you linked.
