### ISSUE TITLE
Error in repl

### ISSUE THREAD

**Issue by Robson96** [scala/bug#12160]
## reproduction steps

using Scala 2.13.3

```scala
scala> object Data {
     | val constant =  "value"
       val constant =  "value"
                      ^
On line 2: error: illegal character '\u00a0'

```

## problem
error in space character

**Comment by som-snytt** [comment]
Whitespace is defined narrowly at https://scala-lang.org/files/archive/spec/2.13/01-lexical-syntax.html and does not include NBSP.
