### ISSUE TITLE
ArrayBuffer incorrectly reports the upper bound in IndexOutOfBoundsException

### ISSUE THREAD

**Issue by oseppala** [scala/bug#12176]
## reproduction steps

using Scala 2.13 and above

```scala
scala> val buf = scala.collection.mutable.ArrayBuffer(1,2,3)
scala> buf(3)
java.lang.IndexOutOfBoundsException: 4 is out of bounds (min 0, max 2)
```

## problem

When requesting for an out of bounds index in an ArrayList, the error report shows an index one higher than what was requested.

The bug was introduced in https://github.com/scala/scala/commit/7e1ed8c01637711f81f868323533f0c963a50330
which made the exception messages more readable. The code is shown below:

```scala
 @inline private def checkWithinBounds(lo: Int, hi: Int) = {
    if (lo < 0) throw new IndexOutOfBoundsException(s"$lo is out of bounds (min 0, max ${size0-1})")
    if (hi > size0) throw new IndexOutOfBoundsException(s"$hi is out of bounds (min 0, max ${size0 - 1})")
  }

  def apply(n: Int): A = {
    checkWithinBounds(n, n + 1)
    array(n).asInstanceOf[A]
  }
```

When `apply` is called with an index `n`, the method calculates two bounds to be checked by `checkWithinBounds`. the parameter `hi` gets a value one higher that the requested value, `lo` is the value as-is. 

The bug is that when checking the upper bound, `hi` (which is the correct value + 1) is shown as the requested value. Using `lo` would give the correct result, but could lead to a regression bug later depending on how checkWithinBounds is called.

**Comment by dwijnand** [comment]
@mshibuya if you reply I can assign you this fix 😄
