### ISSUE TITLE
REPL replay caret is misaligned with replay prompt

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12178]
## reproduction steps

using Scala (add version here),

```scala
scala 2.13.3> scala> f"${0}%%%%%d"

// Detected repl transcript. Paste more, or ctrl-D to finish.

val res13: String = %%0

// Replaying 1 commands from transcript.

scala> f"${0}%%%%%d"
                        ^
              error: conversions must follow a splice; use %% for literal %, %n for newline


scala 2.13.3> f"${0}%%%%%d"
                        ^
              error: conversions must follow a splice; use %% for literal %, %n for newline
```

## problem

The transcript of the replayed transcript should look normal, with caret pointing at the error.

I expected a special `replay>` prompt, as happens with `:replay` command, or maybe `paste>`.

Error reporting has to factor in the current prompt of whatever width.

This may seem like niche behavior, but cut/pasting example snippets is job Nr 1 in REPL. Some work has gone into getting everything to line up, so by the sunk cost fallacy, we should sink more.

**Comment by SethTisue** [comment]
I confess to neglecting the transcript-pasting feature during the JLine 3 upgrade process.

**Comment by som-snytt** [comment]
The old way was also a bit funky, in that the echoed text doesn't align with anything before it.
```
scala 2.12.12> scala> f"${0}%%%%%d"

// Detected repl transcript. Paste more, or ctrl-D to finish.

// Replaying 1 commands from transcript.

scala> f"${0}%%%%%d"
<console>:12: error: conversions must follow a splice; use %% for literal %, %n for newline
               f"${0}%%%%%d"
                         ^
```

**Comment by som-snytt** [comment]
It would be nice if repl display worked uniformly irrespective of source context, but no one uses replay anyway.
