### ISSUE TITLE
Duration.apply(String) does not parse large values correctly.

### ISSUE THREAD

**Issue by jbracker** [scala/bug#12180]
## reproduction steps

using Scala (2.12.7). But as far as I can see this will also happen in Scala 2.13.x

```scala
scala> println(Duration("-7036832630452943 microseconds"))
-7036832630452942848 nanoseconds
```

## problem

I encountered this during some of my ScalaCheck tests. I would expect the parse function to work precisely and not approximate a near nanosecond.

The reason for this is the "weird" way that `Duration.apply` was written:
```scala
def apply(s: String): Duration = {
    val s1: String = s filterNot (_.isWhitespace)
    s1 match {
      case "Inf" | "PlusInf" | "+Inf" | "Duration.Inf" => Inf
      case "MinusInf" | "-Inf" | "Duration.MinusInf"   => MinusInf
      case "Duration.Undefined"                        => Undefined
      case _                                           =>
        val unitName = s1.reverse.takeWhile(_.isLetter).reverse
        timeUnit get unitName match {
          case Some(unit) =>
            val valueStr = s1 dropRight unitName.length
            val valueD = JDouble.parseDouble(valueStr)
            if (valueD >= -maxPreciseDouble && valueD <= maxPreciseDouble) Duration(valueD, unit)
            else Duration(JLong.parseLong(valueStr), unit)
          case _          => throw new NumberFormatException("format error " + s)
        }
    }
  }
```
Why first try parsing a Double and then a Long? Is this done for performance? I'd suggest
```scala
def apply(s: String): Duration = {
    val s1: String = s filterNot (_.isWhitespace)
    s1 match {
      case "Inf" | "PlusInf" | "+Inf" | "Duration.Inf" => Inf
      case "MinusInf" | "-Inf" | "Duration.MinusInf"   => MinusInf
      case "Duration.Undefined"                        => Undefined
      case _                                           =>
        val unitName = s1.reverse.takeWhile(_.isLetter).reverse
        timeUnit get unitName match {
          case Some(unit) =>
            val valueStr = s1 dropRight unitName.length
            Duration(JLong.parseLong(valueStr), unit)
          case _          => throw new NumberFormatException("format error " + s)
        }
    }
  }
```
to fix the issue.

**Comment by NthPortal** [comment]
also happens in 2.12.12 and 2.13.3

**Comment by NthPortal** [comment]
my only guess as to why it parses it as a `Double` is that we allow fractional values (assuming that's even true). I'm not sure the parsing is even specified anywhere

**Comment by jbracker** [comment]
I did not think about fractional values. That makes sense.

I think to detect a fractional value it should check if the `String` contains a period "." and decide to parse a `Long` or a `Double` depending on that.

**Comment by jbracker** [comment]
The documentation states:

> Parse String into Duration.  Format is `"<length><unit>"`

But it does not specify what length can actually be. So I guess that should also be clarified.

**Comment by NthPortal** [comment]
the relevant commit for this bug seems to be 9da135880d0b78b440f4ce62dd8b7dc156571d71

**Comment by NthPortal** [comment]
my guess is that the constants used are wrong? but that's only a guess.

we actually have parsing methods that don't throw now though, so we ought to be able to fix it easily anyway doing something like `StringParsers.parseLong(valueStr).getOrElse(JDouble.parseDouble(valueStr))`

**Comment by SethTisue** [comment]
@philippus if you comment here, I'll assign you the ticket

**Comment by jbracker** [comment]
First of all: @Philippus Thanks for the pull request and the quick work!

BUT: I'd be careful with that:
```scala
import java.lang.{Double => JDouble}
// This is what we want:
println(JDouble.parseDouble("1.4")) // 1.4

// This is ok, I guess? But it does not seem very clean to allow this:
println(JDouble.parseDouble("1.4d")) // 1.4
println(JDouble.parseDouble("1.4e-10")) // 1.4E-10

// This we definitely don't want (IMHO):
println(JDouble.parseDouble("Infinity")) // Infinity
println(JDouble.parseDouble("-Infinity")) // -Infinity
println(JDouble.parseDouble("NaN")) // NaN
```

We should clearly state what is allowed syntax for this, document it as part of the ScalaDoc (missing in the pull request) and then take care of implementing it.

**Comment by Philippus** [comment]
I think we're ok there, as the parsed output will still go into the `Duration.apply` and yield a `NumberFormatException` as before for most cases.
`Duration.apply("Infinity days")` for example will give `java.lang.NumberFormatException: format error Infinity days`.
`Duration.apply("1.4e-10 days")` will turn into "0 days", but that is the same behavior as before as well.

**Comment by SethTisue** [comment]
@jbracker a followup PR with improved Scaladoc would be welcome. (We don't usually keep open tickets on minor doc improvements.)
