### ISSUE TITLE
scala.reflect.macros.Context.typecheck fails in case of custom type aliases

### ISSUE THREAD

**Issue by myazinn** [scala/bug#12181]
## reproduction steps

using Scala 2.13.3,

```scala
// macro implementation
import scala.annotation.{StaticAnnotation, compileTimeOnly}
import scala.language.experimental.macros
import scala.reflect.macros.whitebox

@compileTimeOnly("msg")
class dummy[A] extends StaticAnnotation {
  def macroTransform(annottees: Any*): Any = macro dummyMacro.impl
}

object dummyMacro {

  def impl(c: whitebox.Context)(annottees: c.universe.Tree*): c.universe.Tree = {

    import c.universe._

    annottees.headOption.collect {
      case m: ModuleDef => m.impl.body.collectFirst {
        case DefDef(_, TermName("foo"), _, _, tree: Tree, _) =>
          // fails in case of custom type alias
          c.typecheck(tree, c.TYPEmode)
      }
    }

    annottees.head
  }
}

// example of use
@dummy
object MacroTest {
  type NotFound[A] = List[A]
  def foo: List[Unit] = Nil // compiles
  // def foo: NotFound[Unit] = Nil // compilation error
}

```

## problem

During the macro transformation (it doesn't matter whether it is whitebox or blackbox), the `typecheck` method throws an exception if the return type of the `foo` method is a type alias defined in the same object.
At the same time, this `typecheck` method works fine in case of built-in aliases (such as List) or if I use an alias from another object with explicit object name. If I import it, the compilation will fail.

```scala
object TypeKeeper {
  type NotFound[A] = List[A]
}

@dummy
object MacroTest {
  def foo: TypeKeeper.NotFound[Unit] = Nil // compiles
  //  import TypeKeeper.NotFound
  // def foo: NotFound[Unit] = Nil // compilation error
}
```
I've faced this issue during the investigation of this bug https://github.com/zio/zio/issues/4099. It seems that the problem described in that bug applies not only to zio macros, but to all scala macros.

**Comment by joroKr21** [comment]
Probably it applies only to macro annotations. There is a chicken / egg problem here. The only reason to use macro annotations (as opposed to regular macros) is to add definitions. Which means that in general the code will not typecheck until we add those definitions (i.e. expand the macro annotation). But at the same time you want to typecheck the very object you have annotated before expanding the annotation. So I guess that's undefined behaviour and you shouldn't be doing that.

**Comment by som-snytt** [comment]
I'm not an angry user, in the sense of using in anger, but I was curious what the overview says.

> Macro annotations bring textual abstraction to the level of definitions. 

and

> In the spirit of Scala macros, macro annotations are as untyped as possible to stay flexible and as typed as possible to remain useful. On the one hand, macro annottees are untyped, so that we can change their signatures (e.g. lists of class members). But on the other hand, the thing about all flavors of Scala macros is integration with the typechecker, and macro annotations are not an exceptions. During expansion we can have all the type information that’s possible to have (e.g. we can reflect against the surrounding program or perform type checks / implicit lookups in the enclosing context).

**Comment by myazinn** [comment]
@som-snytt @joroKr21 
Thank you for your answers. As I understand it, the described behavior is not really a bug and I should close the issue, right?

**Comment by som-snytt** [comment]
Yes, this can be closed. A bug report is useful as documentation, of course.

**Comment by joroKr21** [comment]
The workaround is usually to define two macros - one blackbox and one macro annotation. The annotation just forwards to the blackbox.
