### ISSUE TITLE
Custom extractor causes wrong type to be inferred in different match block

### ISSUE THREAD

**Issue by dthoma** [scala/bug#12194]
## reproduction steps

using Scala 2.13.3 on JDK 14

```scala
object Main {

  trait Trait[A]

  class CaseA extends Trait[Int]

  class CaseB extends Trait[Boolean]

  object Pattern {
    def unapply(fa: CaseB): Option[CaseB] = None
  }

  def foo[A](t: Trait[A]) = {
    def bar(f: Trait[A]): Unit = {}

    t match {
      case Pattern(_) =>
    }

    t match {
      case a: CaseA => bar(new CaseA)
    }
  }

}

```
## problem

Both match-blocks compile fine on their own, with both blocks compilation fails with:
```
Foo.scala:21:28: type mismatch;
  found   : Main.CaseA
  required: Main.Trait[A]
```

In the second one, the type parameter `A` shoud be inferred to be `Int`, which allows a new instance of `CaseA` to be passed to bar. This works fine if the first match block is removed.

However adding the first match block breaks that. A completely different block should of course not have any effect on local inferrence at all.

The issue does not happen if instead of the extractor a type-test for `CaseB` is used or `unapply` expects `Trait[_]`, `Any` or `CaseA`. Also it is important that `CaseA` and `CaseB` extend `Trait[A]` with different type arguments. It seems that the local inferrence of the first influences the second match.

**Comment by martijnhoekstra** [comment]
Related to https://github.com/scala/bug/issues/12182 ?

**Comment by dwijnand** [comment]
Perhaps... not sure.

**Comment by joroKr21** [comment]
Isn't that just a GADT limitation?

**Comment by dthoma** [comment]
> Isn't that just a GADT limitation?
How can that be a limitation if both match blocks compile on their own?
Shouldn't this kind of behaviour be local to each match block?

**Comment by dthoma** [comment]
I now also managed to cause a ClassCastException. I assume it is down to the same problem, so I am adding it here:

```scala
object Main {

  trait Trait[A] {
  }

  class CaseA extends Trait[Boolean]
  
  case class CaseB[A](value: A) extends Trait[A]

  object Pattern {
    def unapply(fa: CaseA): Option[CaseA] = None
  }

  def foo[A](t: Trait[A]) = {
    def bar(f: Trait[A]): Unit = {}

    // remove this match block and everything works
    t match {
      case Pattern(_) =>
      case _ =>
    }
    
    t match {
      case CaseB(value) => // line 24
        println(value)
      case _ =>
    }
  }

 
  def main(args: Array[String]): Unit = {
    foo(CaseB(true)) // this works
    foo(CaseB(5)) // this causes a class cast exception in line 24
  }
}

```

**Comment by joroKr21** [comment]
Sounds like a mutability problem. At least there is a commend 😬 
https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/typechecker/Infer.scala#L1198-L1201
