### ISSUE TITLE
Various suggested changes for Tasty Reader

### ISSUE THREAD

**Issue by bishabosha** [scala/bug#12197]
## reproduction steps

using Scala `2.13.4-bin-8891679`,

The following list are a number of changes that should happen to how we understand definitions from Scala 3.

## Immediate Action

These should probably be blockers for 2.13.4

- [x] block opaque types
  - currently they are treated as simple type aliases. This means their API and an validation they assume at the definition are basically void.
  - they can be reintroduced properly if they are kept opaque but are correctly erased, with all the correct warnings with respect to overload collision etc.
- [x] block context function types
  - currently these fail at compile time due to using a synthetic classes `scala.ContextFunction(\d+)` that are not on the classpath
  - they also have some pretty magic rules for erasure
- [x] block refinements to `scala.PolyFunction`
  - these fail at runtime due to magic erasure that rewires from `scala.PolyFunction` to the standard function types
- [x] block methods with `@scala.annotation.static`
  - these fail at runtime because dotty moves the runtime location and call semantics of these methods
- [x] block definitions with `@scala.annotation.alpha` annotation
  - these fail at runtime because dotty changes the binary name of these method
- [x] block generic tuple types
  - these fail at runtime because dotty has magic erasure
- [x] block large function types
  - these fail at runtime because dotty has magic erasure
- [x] handle java defined annotations
  - dotty treats these as having an `<init>` method which is incorrect and fails at compiletime because the correct overload can not be found
  - we should probably escape resolving constructors of annotation types

- [x] support tasty changes in Scala `3.0.0-M1`
- [x] block trait parameters for top level traits in a package
  - this apparently has different behaviour than if the trait is nested in an object

## Gradual Changes later

the following would need to be investigated case by case
- [x] re-enable opaque types
- [ ] re-enable `@static` and `@alpha`
- [ ] large function types
- [ ] generic tuple types
  - probably useless as their API is exclusively `inline` defs
- [ ] erasure of polymorphic function types
- [x] consume values of types that extend traits with parameters

## Unknown

- Merge top level definitions into package scope
  - will need to ensure that the correct wrapper object is maintained in backend

**Comment by bishabosha** [comment]
I am currently working on all of the immediate suggested changes

**Comment by lrytz** [comment]
2.13.4 is scheduled for end of October. That said, I think anything that's ready can be merged pretty quickly as the tasty reader is new and not yet used by anyone in production.

**Comment by lrytz** [comment]
@bishabosha keep this open with https://github.com/scala/scala/pull/9271 merged?

**Comment by bishabosha** [comment]
I think so just because of the extra points not yet done

**Comment by lrytz** [comment]
OK, changed the milestone to 2.13.5, assuming you're OK with the current state for 2.13.4.

**Comment by bishabosha** [comment]
Yes I believe that is ok

**Comment by SethTisue** [comment]
@bishabosha I'm re-milestoning to 2.13.6, but let us know if that's not right

**Comment by bishabosha** [comment]
@SethTisue Perhaps this issue should be closed, there was a discussion that concluded that special support for Scala 3 should only come with user demand.
