### ISSUE TITLE
java.lang.NoSuchFieldError when mix Scala and Java types

### ISSUE THREAD

**Issue by REASY** [scala/bug#12195]
## reproduction steps

using Scala (2.13.3 and Scala 2.12.12, SBT 1.4.1)
Minimal reproducible example: https://github.com/REASY/scala-compiler-bug

## problem
There is a small app https://github.com/REASY/scala-compiler-bug/blob/main/src/main/scala/example/Example.scala#L7 which suppose to print 
```
example.scala.Document.getMember(foo)
```
but instead it fails on runtime with the error `java.lang.NoSuchFieldError: document`:
```
$ sbt ";clean;cleanFiles;runMain example.Example"
[info] welcome to sbt 1.4.1 (Oracle Corporation Java 1.8.0_261)
[info] loading global plugins from C:\Users\User\.sbt\1.0\plugins
[info] loading settings for project scala-compiler-bug-build from plugins.sbt ...
[info] loading project definition from C:\Users\User\AppData\Local\Temp\scala-compiler-bug\project
[info] loading settings for project root from build.sbt ...
[info] set current project to compiler-bug (in build file:/C:/Users/User/AppData/Local/Temp/scala-compiler-bug/)
[success] Total time: 0 s, completed Oct 20, 2020 7:19:17 PM
[success] Total time: 0 s, completed Oct 20, 2020 7:19:18 PM
[info] compiling 2 Scala sources and 2 Java sources to C:\Users\User\AppData\Local\Temp\scala-compiler-bug\target\scala-2.13\classes ...
[info] done compiling
[info] running example.Example
[error] (run-main-0) java.lang.NoSuchFieldError: document
[error] java.lang.NoSuchFieldError: document
[error]         at example.Example$.main(Example.scala:9)
[error]         at example.Example.main(Example.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error] stack trace is suppressed; run 'last Compile / bgRunMain' for the full output
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 2 s, completed Oct 20, 2020 7:19:20 PM
```
![image](https://user-images.githubusercontent.com/5107562/96585032-3a60fc00-1309-11eb-850a-6d9ee325e236.png)

There is Java type [Window](https://github.com/REASY/scala-compiler-bug/blob/main/src/main/java/example/java/Window.java#L8) which has a public field `document` with Scala type [Document](https://github.com/REASY/scala-compiler-bug/blob/main/src/main/scala/example/scala/Document.scala). `Window` class is instantiated and accessed in runnable class https://github.com/REASY/scala-compiler-bug/blob/main/src/main/scala/example/Example.scala
```scala
package example

import example.java.Window

// To run via SBT use in shell: `sbt "runMain example.Example"`
object Example {
  def main(args: Array[String]): Unit = {
    val wnd = new Window()
    val res = wnd.document.getMember("foo").toString
    println(res)
  }
}
```

## Investigation
If I look to the generated bytecode using `javap` I can see that `example.java.Window` is looking as expected, `document` field's type is correct:
```
scala> :javap -c example.java.Window
Compiled from "Window.java"
public class example.java.Window {
  public final example.scala.Document document;

  public example.java.Window();
    Code:
       0: aload_0
       1: invokespecial #1                  // Method java/lang/Object."<init>":()V
       4: aload_0
       5: new           #2                  // class example/scala/Document
       8: dup
       9: invokespecial #3                  // Method example/scala/Document."<init>":()V
      12: putfield      #4                  // Field document:Lexample/scala/Document;
      15: return
}
```
On the other hand, the accessed type of document in `example.Example$.main` method is wrong, it is `example/java/Document` instead of `example/scala/Document`:
```
scala> :javap -c example.Example$
Compiled from "Example.scala"
public final class example.Example$ {
  public static final example.Example$ MODULE$;

  public static {};
    Code:
       0: new           #2                  // class example/Example$
       3: dup
       4: invokespecial #12                 // Method "<init>":()V
       7: putstatic     #14                 // Field MODULE$:Lexample/Example$;
      10: return

  public void main(java.lang.String[]);
    Code:
       0: new           #19                 // class example/java/Window
       3: dup
       4: invokespecial #20                 // Method example/java/Window."<init>":()V
       7: astore_2
       8: aload_2
       9: getfield      #24                 // Field example/java/Window.document:Lexample/java/Document;
      12: ldc           #26                 // String foo
      14: invokevirtual #32                 // Method example/java/Document.getMember:(Ljava/lang/String;)Ljava/lang/Object;
      17: invokevirtual #36                 // Method java/lang/Object.toString:()Ljava/lang/String;
      20: astore_3
      21: getstatic     #41                 // Field scala/Predef$.MODULE$:Lscala/Predef$;
      24: aload_3
      25: invokevirtual #45                 // Method scala/Predef$.println:(Ljava/lang/Object;)V
      28: return
}
```
![image](https://user-images.githubusercontent.com/5107562/96586686-8745d200-130b-11eb-9ffc-6fc4e2d83013.png)

**Comment by dwijnand** [comment]
> On the other hand, the accessed type of document in `example.Example$.main` method is wrong, it is `example/java/Document` instead of `example/scala/Document`:

```scala
package example.java;

import example.scala.Document;

// If you remove this line it will work ¯\_(ツ)_/¯
import java.util.function.Supplier;

public class Window {
    public final Document document = new Document();
}
```

I don't it is: the import doesn't have any effect because it's shadowed by the `Document` class in the java package (this is a change that came in 2.13).

**Comment by REASY** [comment]
Hello, @dwijnand. Thanks for the feedback. 

Here if I remove the commented lines (https://github.com/REASY/scala-compiler-bug/blob/main/src/main/java/example/java/Window.java#L5-L6):
![image](https://user-images.githubusercontent.com/5107562/96594015-5ae28380-1314-11eb-9683-c089f4202407.png)
As you can the type output states that the type is `example.scala.Document`:
```
$ sbt ";clean;cleanFiles;runMain example.Example"
[info] welcome to sbt 1.4.1 (Oracle Corporation Java 1.8.0_261)
[info] loading global plugins from C:\Users\User\.sbt\1.0\plugins
[info] loading settings for project compiler-bug-build from plugins.sbt ...
[info] loading project definition from C:\repos\compiler-bug\project
[info] loading settings for project root from build.sbt ...
[info] set current project to compiler-bug (in build file:/C:/repos/compiler-bug/)
[success] Total time: 0 s, completed Oct 20, 2020 8:36:22 PM
[success] Total time: 0 s, completed Oct 20, 2020 8:36:22 PM
[info] compiling 2 Scala sources and 2 Java sources to C:\repos\compiler-bug\target\scala-2.13\classes ...
[info] done compiling
[info] running example.Example
example.scala.Document.getMember(foo)
[success] Total time: 3 s, completed Oct 20, 2020 8:36:25 PM
```

Also If I use full class name instead of import it also works:
```
$ sbt ";clean;cleanFiles;runMain example.Example"
[info] welcome to sbt 1.4.1 (Oracle Corporation Java 1.8.0_261)
[info] loading global plugins from C:\Users\User\.sbt\1.0\plugins
[info] loading settings for project compiler-bug-build from plugins.sbt ...
[info] loading project definition from C:\repos\compiler-bug\project
[info] loading settings for project root from build.sbt ...
[info] set current project to compiler-bug (in build file:/C:/repos/compiler-bug/)
[success] Total time: 0 s, completed Oct 20, 2020 8:42:02 PM
[success] Total time: 0 s, completed Oct 20, 2020 8:42:02 PM
[info] compiling 2 Scala sources and 2 Java sources to C:\repos\compiler-bug\target\scala-2.13\classes ...
[info] done compiling
[info] running example.Example
example.scala.Document.getMember(foo)
[success] Total time: 3 s, completed Oct 20, 2020 8:42:05 PM
```
![image](https://user-images.githubusercontent.com/5107562/96594425-c9274600-1314-11eb-829c-b3bbf124092e.png)

**Comment by som-snytt** [comment]
To be clear, for my benefit, the `import example.scala.Document` shadows `example.java.Document` in both Java and Scala.

That has always been specified in Scala, but the behavior was broken until 2.13 or so.

(I think dwijnand said the opposite.)

So IIUC Scala is picking the wrong thing in mixed compilation. The "delete the other import" behavior makes it sound like a java parser problem; I think the import logic for symbol lookup has something Java specific, but I'd have to look.

Just for practice, I'll try it in Dotty.

**Comment by som-snytt** [comment]
TIL sbt compiler bridge has finite backward compatibility.
```
[info] Non-compiled module 'compiler-bridge_2.12' for Scala 2.12.0. Compiling...
/tmp/sbt_1d91b260/scala/ZincCompat.scala:19: error: type PlainNioFile is not a member of package scala.reflect.io
  type PlainNioFile = scala.reflect.io.PlainNioFile
```

**Comment by som-snytt** [comment]
It's nothing subtle, it's just a bug in Java lookups, where it short-circuits on the irrelevant import.

**Comment by REASY** [comment]
Thanks, @som-snytt for the investigation. Could you, please, explain a bit more why there is something wrong in Java lookups. If we look to the the generated class `example.java.Window` bytecode, the type is correct. Is it somehow related to the internal phrases of Scala compiler (we have Java class referencing Scala class)

**Comment by som-snytt** [comment]
Yes, this is scalac parsing Java source and not handling imports in Java source correctly.

Since the bug is many years old, it suggests that mixed compilation with co-dependence is rare. Or possibly interop boundaries usually consist of thin shims, without the usual prologue of imports?
