### ISSUE TITLE
pass-by-name parameter need space to be recoginized

### ISSUE THREAD

**Issue by VuNguyenLong** [scala/bug#12193]
## reproduction steps

using Scala 2.13.3, run with java 14.0.1

'''def foo(b:Boolean, x:=>Int, y:=>Int) = if(b) x else y
'''
expected to return a function that have 2 pass-by-name parameters x and y

## problem
above code return "error: ':' expected but identifier found."

just work fine if add 2 space after ':'
''' def foo(b:Boolean, x: =>Int, y: =>Int) = if(b) x else y
'''

i think there should be a bug around here.

**Comment by som-snytt** [comment]
That's just how it parses (or lexes). See ["long match rules applies"](https://scala-lang.org/files/archive/spec/2.13/01-lexical-syntax.html).

Sample required space around colon:

https://github.com/scala/scala/blob/v2.13.3/src/library/scala/Boolean.scala#L34

There's probably an odder example than:
```
def f(b: Boolean, :=> : => Int) = if(b) :=> else 42
```
