### ISSUE TITLE
Incorrect unification of bounds of higher type members leads to kind mismatch

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12192]
## reproduction steps

using Scala 2.13.3,

```scala

	trait Expr[X, E] {
		def applyTo[F[A >: E <: E]] :Expr[X, F[E]]
	}

	trait Functor[F, A <: U, U] {
		type Apply[+X <: U]
		type Super[+X >: A <: U] >: F
	}

	trait Implicit[X, Y] {
		type S >: Y
		val expr :Expr[X, S]
	}

	def test[F, A <: U, U, X](fun :Functor[F, A, U], x :Implicit[X, A] { type S >: A <: U }) = {
		x.expr.applyTo[({ type E[B >: A <: U] = fun.Super[B] })#E] //works
		x.expr.applyTo[fun.Super] //type mismatch
       }
```

## problem
Should compile; the indirection is using an identity functor.

I suspect it might be a duplicate of #12142; @joroKr21 ?

**Comment by joroKr21** [comment]
Yes, that compiles on 2.13.x - do you think it's worth adding another test?

**Comment by noresttherein** [comment]
I do not know the internals and what did you actually use as the test, but this is much simpler than my previous report, so it might just as well replace the old one? Certainly I'd rather debug this than the other one!

**Comment by joroKr21** [comment]
I basically pasted it in the REPL. If you clone the scala project and start `sbt` you can then run a `scala` command inside.
The test itself is in a file `t12142.scala`
