### ISSUE TITLE
clarify spec wording on SAM

### ISSUE THREAD

**Issue by adriaanm** [scala/bug#12204]
https://github.com/scala/scala/blob/2.12.x/spec/06-expressions.md#sam-conversion
- [ ] what compiles to INDY / anon subclass (versus: what is even a SAM?)
- [ ] restriction on constructors

https://groups.google.com/d/msg/scala-internals/lv4sTGorDLU/onfydhVpBAAJ

**Comment by SethTisue** [comment]
@adriaanm the description probably isn't clear enough to be actionable by anyone but you. can you either provide an actionable description, or just close the ticket?

**Comment by som-snytt** [comment]
I see the sample from the mailing list is the next issue, https://github.com/scala/bug/issues/12205

Now we can benefit from Scala 3's more opinionated opinion. (Although sometimes Scala 3 just shrugs.)

There was a lot of construction dust (also in the spec). Oh, pun on "constructor"!

> if class C defines a constructor, it must be accessible and must define exactly one, empty, argument list;

Should just say the primary ctor must have `()`. If no params are specified, "empty parameter section is assumed" says the spec.

**Comment by adriaanm** [comment]
Pardon my construction dust & vague description. Looking at the spec, I think there's a fair amount of detail around the requirements. I probably wouldn't spec the details of what can be compiled using INDY vs an anonymous subclass (platform specific). So, I'm going to close this one.
