### ISSUE TITLE
Register allocation on local variable slots

### ISSUE THREAD

**Issue by retronym** [scala/bug#12203]
Currently, scalac always uses a fresh local variable slot for each local, even if their scope doesn't overlap.

``` scala
def f = {
  if (...) {
    val a = 0
    ...
  } else {
    val b = ""
    ..
  }
}
```

`a` and `b` could use the same local variable slot, which would make the method's frame smaller.

**Comment by lrytz** [comment]
One caveat here is that, if I remember correctly, some local optimizations (copy prop? eliminateStaleStoresAndRewriteSomeIntrinsics? i'm not sure, but JUnit tests would tell) profit from the fact that every local variable has its own slot.

It's also not obvious how much of a benefit this would be, given that the JVM performs register allocation.

Note that unused slots (that can exist after removing unused code) are eliminated (`compactLocalVariables`).

So I think we can close this.
