### ISSUE TITLE
Scala 2.12.8 trait method not found error in intellij

### ISSUE THREAD

**Issue by AjitTK** [scala/bug#12200]
## Version

Scala (2.12.8)

## problem
I unable to execute my code in scala version 2.12.8 because during execution in IDE intellij at a runtime it throws error of method not found. Where as method is present in trait and I am using that method from base class refrence. There is no compile time error or warning.

(explain how the above behavior isn't what you expected)
Bese class can able to access trait method and method should load by jvm during runtime.

**Comment by SethTisue** [comment]
In order for this to be appropriate for scala/bug, the problem must be reproducible outside of IntelliJ, and must be reproducible in Scala 2.13.3.
