### ISSUE TITLE
Private methods and members not showing up in scaladoc

### ISSUE THREAD

**Issue by IowU** [scala/bug#12217]
Hello,
I was trying to generate some scaladoc using ```sbt doc```, but I noticed that private members and methods don't show up. I tried adding the ```scalacOptions in (Compile, doc) += "-private" ``` in my **build.sbt** but nothing changed. Is there a way to make them appear? Same result when I tried using ```scaladoc <file_path> ```.

**Comment by SethTisue** [comment]
I did a test and `-private` does cause private members to be documented when they wouldn't otherwise, but it doesn't make them visible by default; you still have to ask see them in UI:

<img width="1017" alt="Screen Shot 2020-11-05 at 11 09 34 AM" src="https://user-images.githubusercontent.com/161079/98285502-79bd5880-1f57-11eb-8d6b-5499e730b544.png">

**Comment by SethTisue** [comment]
closely related: https://github.com/scala/bug/issues/12083

**Comment by SethTisue** [comment]
this is probably working-as-designed, but perhaps the design should be changed, idk.

**Comment by SethTisue** [comment]
let's consolidate under #12083 since it's basically the same thing.

**Comment by unkarjedy** [comment]
@SethTisue  Do you think there is any chance to include it into 2.12?
Want to use it a lot in SBT plugin docs and it fails to publish it on the doc stage with error "Could not find any member to link for"

**Comment by lrytz** [comment]
@unkarjedy I'm not sure your comment relates to this ticket - this ticket is about usability of the generated scaladoc html.

**Comment by unkarjedy** [comment]
@lrytz Yes. 
In Scala 2.13 you can add the `-private` option and it will allow you referencing the package private methods.
Without the option it will generate the warning that I just mentioned.
In Scala 2.12 the `-private` option is not recognised.

# Example
```scala
package example

/**
 *  - [[Other.fooPublic]]
 *  - [[Other.fooPackagePrivate]]
 */
object Main {
  def main(args: Array[String]): Unit = {
    (1 to 5).map(println)

    for (i <- 1 to 5) {
      println(s"i = $i")
    }
  }
}

class Other {
  def fooPublic: String = ???
  private def fooPrivate: String = ???
  private[example] def fooPackagePrivate: String = ???
}
```

## Scala 2.13.16 
### Without extra options
```
[IJ]doc
[info] Main Scala API documentation to /Users/dmitrii.naumenko/Desktop/dev/tc-config/untitled3/target/scala-2.13/api...
[warn] /Users/dmitrii.naumenko/Desktop/dev/tc-config/untitled3/src/main/scala/example/Main.scala:3:1: Could not find any member to link for "Other.fooPackagePrivate".
[warn] /**
[warn] ^
[warn] one warning found
[info] Main Scala API documentation successful.
[success] Total time: 0 s, completed 23 Sept 2025, 11:51:49
```

<img width="286" height="178" alt="Image" src="https://github.com/user-attachments/assets/d25c1b85-7105-4d7c-866d-757654ea75d4" />

### With `Compile / doc / scalacOptions += "-private"` option
```
[IJ]doc
[info] Main Scala API documentation to /Users/dmitrii.naumenko/Desktop/dev/tc-config/untitled3/target/scala-2.13/api...
[info] Main Scala API documentation successful.
[success] Total time: 0 s, completed 23 Sept 2025, 11:52:26
```

<img width="271" height="180" alt="Image" src="https://github.com/user-attachments/assets/5163defb-22ea-4896-8e38-d85a781512dd" />

## Scala 2.12.20
### Without extra options
Same as in Scala 2.13

### With `Compile / doc / scalacOptions += "-private"` option
```
[IJ]doc
[info] Main Scala API documentation to /Users/dmitrii.naumenko/Desktop/dev/tc-config/untitled3/target/scala-2.12/api...
[error] bad option: '-private'
```

**Comment by lrytz** [comment]
I see! https://github.com/scala/scala/pull/8183 might be pretty straightforward to backport, but I don't know if there were any follow-ups related to it.

We will probably do another 2.12 release in the coming weeks for JDK 25 support. There's no concrete date yet though, code compiled with 2.12.20 works fine on JDK 25 and also the compiler works fine on Java 25 as long as you're not using the optimizer.
