### ISSUE TITLE
Overload resolution may be (inappropriately) order-dependent in the presence of bounded type parameters

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12212]
using Scala 2.13.3,

```scala
trait Low[X]
trait Lower[V, X] extends Low[X]
trait Res[V]
trait High[L[X] <: Low[X]]
trait HighRes[L[X] <: Lower[V, X], V] extends Res[V]

trait Mid[X, Y]

def m[L[X] <: Lower[V, X], V](high :High[L]) :HighRes[L, V] = ???

def m[X, Y](mid :Mid[X, Y]) :Res[Y] = ???

def ok[L[X] <: Lower[V, X], V](high :High[L]) :HighRes[L, V] =
    m(high)

def wtf[L[X] <: Lower[V, X], V](high :High[L]) :HighRes[L, V] =
    m[L, V](high)
```
## problem

```
C:\slang\src\test\scala\Playground.scala:51
kinds of the type arguments (L,V) do not conform to the expected kinds of the type parameters (type X,type Y).
L's type parameters do not match type X's expected parameters:
type L has 1 type parameter, but type X has 0
        m[L, V](high)
```

I admit I do not fully understand overload resolution rules - maybe it is all according to SLS. If so, it is extremely unfortunate, as in slightly more complex scenarios (for example involving PDTs), the inferer will fail, leaving no way of picking the correct overload.

**Comment by martijnhoekstra** [comment]
The behaviour is order-dependent. It compiles with 

```
def m[X, Y](mid :Mid[X, Y]) :Res[Y] = ???
def m[L[X] <: Lower[V, X], V](high :High[L]) :HighRes[L, V] = ???
```

**Comment by noresttherein** [comment]
Seriously? The algorithm described in SLS is quite clearly order independent. I would like to get a better understanding about how things really work so I can solve such issues in the future.
Is it even a bug, or intended behaviour?

**Comment by martijnhoekstra** [comment]
The algorithm described in SLS is quite clearly order independent and this behaviour isn't, so this is a bug. Seriously.

**Comment by noresttherein** [comment]
Apologies, I didn't want to appear snarky. I was just completely baffled by this case (and similar) and perhaps somewhat annoyed in that I couldn't find a reliable generic workaround, unlike with other bugs and language limitations. As I stated in the description, I wasn't even sure if this is a bug, SLS is outdated or I simply do not understand it.

**Comment by martijnhoekstra** [comment]
It is quite baffling, I'll give you that.

**Comment by som-snytt** [comment]
I have no recollection of this pre-pandemic issue:

https://github.com/scala/bug/issues/11907

The symptom is different, but FSR I suggested that parameter type inference (since 2.13?) might be involved.

There are a bunch of issues with overloading and type params. An older issue with explicit type arg and inference: https://github.com/scala/bug/issues/10074

It would be nice if paths in issue text didn't start with "porn". Maybe the user is "Paul Orn" and it's perfectly innocent, but it's a distraction.

**Comment by noresttherein** [comment]
Sorry? (Not sure if I should be). Worked for big corpo most of my career, I like to keep invigilating admins on their toes.

**Comment by SethTisue** [comment]
Re: the pathname issue, this kind of thing is simply not welcome in our issue tracker. As per https://www.scala-lang.org/conduct/ , discussing it further on this ticket isn't welcome, either. Feel free to contact me or any of the other moderators about it privately.

**Comment by noresttherein** [comment]
Can't say I see rule in the link that would in any way apply, but considering reporting bugs take time and I don't think a single one of mine got fixed It's really easy to comply.

**Comment by dwijnand** [comment]
Here's one success story: https://github.com/scala/bug/issues/12142!  I wish I could resolve more (or even any!) of the issues you reported...

I thought it was funny at first, but I think the joke is tired now so I'm in favour of it stopping.  Nothing against porn, just that it's not a subject for here.

**Comment by joroKr21** [comment]
Overloading resolution does a bounds check but not a kinds check. I wonder if that is intentional 🤔
