### ISSUE TITLE
AbstractMethodError or IllegalAccessError exception calling member of a specialized class in another module

### ISSUE THREAD

**Issue by OndrejSpanel** [scala/bug#12222]
## reproduction steps

using Scala 2.13.3,  2.12.2, 2.11.12 or 2.10.7 (other versions not tested)

Clone https://github.com/OndrejSpanel/SpecRepro or use the files as below:

Buffer.scala:

```scala
trait ABuffer[@specialized(Float)T] {
  def count: Int
}

class Buffer[@specialized(Float) T](array_par: Array[T]) extends ABuffer[T] {
  var array: Array[T] = array_par

  var count: Int = 0
}

class Float32Buffer(array_par: Array[Float]) extends Buffer[Float](array_par)
```

Main.scala:

```scala
object Main extends App {

  val vertices = Array[Float]()

  val attribute = new Float32Buffer(vertices)
  println(attribute.count)

}
```

build.sbt:

```
name := "SpecRepro"

val commonSettings = Seq(scalaVersion := "2.13.3")

lazy val root = (project in file(".")).settings(commonSettings)

lazy val examples = (project in file("examples")).dependsOn(root).settings(commonSettings)

```

## problem

When running Main, an exception `java.lang.AbstractMethodError` is thrown.

## Notes

This is extracted from a real-life problem, where the module `root` is in fact a library used in a different sbt project.

- the issue cannot be seen if both sources are located in the same SBT module
- the issue goes away if you change `var count` to `def count`
- the issue goes away if you change `var array` to `var array: Array[T] = _`
- the issue goes away if you remove any of the two `@specialized` annotations
- if you change `var count` to `val count`, an exception `java.lang.IllegalAccessError` si thrown instead

I was unable to reproduce the issue with Dotty 0.27.0-RC1

**Comment by SethTisue** [comment]
> I was unable to reproduce the issue with Dotty 0.27.0-RC1

Dotty simply ignores `@specialized`

**Comment by OndrejSpanel** [comment]
It seems the issue was already described in http://aleksandar-prokopec.com/2013/11/03/specialization-quirks.html:

> Specialization in 2.10 has a problem of specializing constructors in some cases

With explanation and a workaround:

> I won’t get into why the above fails the way it fails - suffices to say that the specialization creates specialized fields in the specialized variants of the class and does not properly rewire the bridges for the field accessor methods in the constructor body correctly. Here is the pattern to solve the above issues - create a method `init `in which you initialize the troublesome fields:

**Comment by joroKr21** [comment]
Looks like the names are mangled for some reason:
```scala
scala> typeOf[Buffer[_]].decls.toList.map(_.name)
val res0: List[$r.intp.global.Symbol#NameType] = List(array_par, <init>, array, array_$eq, array , Buffer$$count, Buffer$$count_$eq, Buffer$$count )
```
