### ISSUE TITLE
Compiler bug when using Array deconstructor.

### ISSUE THREAD

**Issue by crakjie** [scala/bug#12225]
## reproduction steps

using Scala 2.13.3, sbt 1.4.1 

The following lines is making a compiler error while making a incremental compilation.
A `clean; compile;` is a work around. 

```scala
val Array(address, port) = str.split(":")
```

Another workaround is just using the Array apply to extract value by index.

## problem
This appear while doing a incremental compilation only.

Partial error ouput for SOE.
```
[error] ## Exception when compiling 366 sources to target/scala-2.13/classes
[error] scala.reflect.internal.FatalError: 
[error]   EmptyScope.enter
[error]         during phase: globalPhase=erasure, enteringPhase=posterasure
[error]      library version: version 2.13.3
[error]     compiler version: version 2.13.3
[error] 
[error]   last tree to typer: TypeTree(trait Seq)
[error]             tree tpe: Seq
[error]               symbol: abstract trait Seq in package immutable
[error]    symbol definition: abstract trait Seq extends Iterable with Seq with SeqOps with IterableFactoryDefaults (a ClassSymbol)
[error]       symbol package: scala.collection.immutable
[error]        symbol owners: trait Seq
[error]            call site: method build in object Modules in package components
```

The output : 
https://gist.github.com/crakjie/b50df6d68b0852cc3a67369c94022616/64f69e3aacb9fe4e75276c4299fdf857a34ea06c

A details output of the error with -Ydebug : 
https://gist.github.com/crakjie/b50df6d68b0852cc3a67369c94022616

The syntax in the context :
https://gist.github.com/crakjie/0ff9fb06eb4773e0e16914cc09dc95d0

## expecting behaviour 
Either working every time either refusing the syntax.

**Comment by dwijnand** [comment]
What version of sbt are you using?  And can you detail the steps required to induce the incremental bug, please?

**Comment by crakjie** [comment]
@dwijnand 1.4.1 but I think I already had the problem with 1.3.x

**Comment by dwijnand** [comment]
OK, thanks.  How about the reproduction steps?  With the incremental compiler you need to compile it once, change something and compile it again, so it would be necessary to understand what needs to happen to cause this.

**Comment by smarter** [comment]
I think the biggest clue here is the assertion that triggers under -Ydebug:
```scala
	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:170)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.assertClassNotArray(BTypesFromSymbols.scala:220)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.assertClassNotArrayNotPrimitive(BTypesFromSymbols.scala:224)
	at scala.tools.nsc.backend.jvm.BTypesFromSymbols.classBTypeFromSymbol(BTypesFromSymbols.scala:96)
```
Somehow, writing `val Array(address, port) = str.split(":")` means that we end up trying to access `scala.Array` incorrectly at the backend (I guess that means the symbol for scala.Array doesn't get erased as it should and survives until the backend somehow).

**Comment by smarter** [comment]
Actually I can trigger this easily:
```scala
object Test {
  def foo(arr: Array[Int]): Unit = {
    val Array(x, y) = arr
  }
}
```
When compiling with `scalac -Ydebug` this explodes in the same place, because we keep a reference to Array.UnapplySeqWrapper, this is an inner class of the companion object scala.Array (which should survive), but somehow we end up trying to load the companion class scala.Array in the backend (which isn't supposed to exist at that point I think since we erase Arrays). A backend expert should take a look at that.

**Comment by lrytz** [comment]
It looks to me like there are two unrealate issues. Turning on `-Ydebug` when compiling `val Array(x, y) = arr` indeed triggers an assertion error in the backend, but the fix here is to remove/weaken the assertion, the backend does the right thing.

The reason for the assertion is that we don't usually emit references to `scala.Array` in code, but there's an exception for the Java InnerClass table which contains these entries

```
  // access flags 0x19
  public final static INNERCLASS scala/Array$UnapplySeqWrapper scala/Array UnapplySeqWrapper
  // access flags 0x9
  public static INNERCLASS scala/Array$UnapplySeqWrapper$ scala/Array UnapplySeqWrapper$
```

Now the original crash reported by @crakjie is in erasure and seems unrelated. The stack trace from his gist:

```
[error] scala.reflect.internal.Reporting.abort(Reporting.scala:69)
[error] scala.reflect.internal.Reporting.abort$(Reporting.scala:65)
[error] scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:28)
[error] scala.reflect.internal.Scopes$EmptyScope$.enterEntry(Scopes.scala:533)
[error] scala.reflect.internal.Scopes$Scope.enter(Scopes.scala:157)
[error] scala.reflect.internal.Symbols$Symbol.setInfoAndEnter(Symbols.scala:1593)
[error] scala.tools.nsc.typechecker.Implicits.memberWildcardType(Implicits.scala:348)
[error] scala.tools.nsc.typechecker.Implicits.memberWildcardType$(Implicits.scala:342)
[error] scala.tools.nsc.transform.Erasure.memberWildcardType(Erasure.scala:23)
...
[error] scala.tools.nsc.typechecker.Implicits$HasMember$.apply(Implicits.scala:359)
[error] scala.tools.nsc.typechecker.Typers$Typer.$anonfun$adaptToMemberWithArgs$6(Typers.scala:1394)
[error] scala.tools.nsc.typechecker.Typers$Typer.silent(Typers.scala:720)
[error] scala.tools.nsc.typechecker.Typers$Typer.adaptToMemberWithArgs(Typers.scala:1394)
[error] scala.tools.nsc.typechecker.Typers$Typer.typedSelect$1(Typers.scala:5324)
...
[error] scala.tools.nsc.transform.Erasure$ErasureTransformer.transform(Erasure.scala:1378)
[error] scala.tools.nsc.ast.Trees$Transformer.transformUnit(Trees.scala:162)
...
[error] xsbt.CompilerBridge.run(CompilerBridge.scala:39)
...
[error] sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:157)
```

@crakjie could you provide an example project and steps for reproducing the issue?

**Comment by smarter** [comment]
> Now the original crash reported by @crakjie is in erasure and seems unrelated.

It is related but it's not clear to me how, without -Ydebug-error in the output we have:
> exception when typing com.the_ica.rafale.syntax.<ConfigOps: error>.getCalculatorServers$extension

ConfigOps (from https://gist.github.com/crakjie/0ff9fb06eb4773e0e16914cc09dc95d0) is the file which defines `val Array(...) = ...`, and @crakjie confirmed that removing these destructors made the problem go away.

**Comment by lrytz** [comment]
I don't understand how they are related. Your example compiles fine (and to correct bytecode) under `-Ydebug` if I remove the backend assertion (https://github.com/scala/scala/blob/39148e4ec34a5c53443dd1b25ceec2308cd097fe/src/compiler/scala/tools/nsc/backend/jvm/BTypesFromSymbols.scala#L96), and it doesn't cause a crash in erasure.

I'm not doubting that it's the array deconstructor that causes @crakjie's issue, I'm just saying that your example doesn't seem to be a minimization of it.

**Comment by smarter** [comment]
Well to get to the bottom of it we'd need to know where the `<ConfigOps: error>` thing comes from, that's what I hoped `-Ydebug` would provide, but perhaps the existing assertion is masking the real error cause.

**Comment by crakjie** [comment]
Another Hint. While in my case compilation was working fine after removed the `val Array(x, y) = arr` a colegue told me he still have an error without exactly the same error message (nothing referencing trait Seq) but he manage to compile after removed the `private` modifier of the object  ConfigOps found in the very same file https://gist.github.com/crakjie/0ff9fb06eb4773e0e16914cc09dc95d0#file-gistfile1-txt-L61 . 

Not sure it's related but in may case I was using sbt 1.4.1 when he was still using 1.3.9

**Comment by SethTisue** [comment]
Lukas, you self-assigned here but then haven't come back to it. Do you want to stay assigned, or un-assign? If you unassign, want to sketch out how you'd imagined proceeding?

**Comment by SethTisue** [comment]
Also I think we determined there are two bugs here. Maybe this ticket should stay as being about the incremental compilation problem, but open a new ticket about the back end problem?

**Comment by som-snytt** [comment]
IIUC this fixed the assertion under `-Vdebug` but they did not determine the cause of the incremental compilation failure in erasure.
