### ISSUE TITLE
Suppress "Unused import" warnings when error present

### ISSUE THREAD

**Issue by dwijnand** [scala/bug#12234]
When a file is in this state:

```
[error] /d/scala/test/junit/scala/tools/nsc/backend/jvm/IndyLambdaTest.scala:12:10: stable identifier required, but IndyLambdaTest.this.compiler found.
[error]   import compiler._
[error]          ^
[error] /d/scala/test/junit/scala/tools/nsc/backend/jvm/IndyLambdaTest.scala:16:20: not found: value compileAsmMethods
[error]       val method = compileAsmMethods(s"""def f = $code """).find(_.name == "f").get
[error]                    ^
```

I think it would be better not to also emit:

```
[warn] /d/scala/test/junit/scala/tools/nsc/backend/jvm/IndyLambdaTest.scala:6:39: Unused import
[warn] import scala.jdk.CollectionConverters._
[warn]                                       ^
[warn] /d/scala/test/junit/scala/tools/nsc/backend/jvm/IndyLambdaTest.scala:7:24: Unused import
[warn] import scala.tools.asm.Handle
[warn]                        ^
[warn] /d/scala/test/junit/scala/tools/nsc/backend/jvm/IndyLambdaTest.scala:8:29: Unused import
[warn] import scala.tools.asm.tree.InvokeDynamicInsnNode
[warn]                             ^
[warn] /d/scala/test/junit/scala/tools/nsc/backend/jvm/IndyLambdaTest.scala:12:19: Unused import
[warn]   import compiler._
[warn]                   ^
```

The legitimacy of those warnings is going to dubious, in this situation, so I'm thinking best avoid emitting them?

It's particularly annoying when you're here:

```
[warn] 99 warnings found
[error] 100 errors found
```

... 99 unused imports aren't what I'm looking for...

**Comment by som-snytt** [comment]
Unfortunately, you don't know which badly formed import caused the error.

Ideally, there's an error and you think, But I imported X! and you can see why you didn't.

I could use extra help on naming, similar to dotty help on implicits. Where is a name bound from, and what bindings does it shadow, etc?

So an error on import doesn't mean warnings on imports are spurious.

There's also `-Xmaxwarns`, `-Xmaxerrs`, which I have used occasionally to avoid avalanches.

**Comment by dwijnand** [comment]
In this case it wasn't an import causing error at all.

But I thought I remembered a "hasError" or similar API and I'm wondering if it were better if unused imports warnings were conditional on that.  Maybe it means introducing some kind of "warning if no error" indicator?

**Comment by dwijnand** [comment]
`-Xmaxwarns` is a bit too static, I want no/less warnings if I'm flooded with errors.  Also, speaking of maxerrs, it would be nice to know that it's in play, something like "100 errors found (of 4855)".  I might've given up on my experiment a lot sooner if I'd known how many type errors it introduced.

**Comment by dwijnand** [comment]
I understood your point better now.  I almost want something like "log level" for unused import, where I give up the rare unused `import cats.instances._` warning when I'm getting a compile error for not import cats.syntax.  Something like `-Vunused-imports:fine` rather than `-Vunused-imports:finest`.

We'd probably want to look at how true it is that the unused import warning does indeed come up and be useful, if someone were to PR this.  But I'm happy to close this.
