### ISSUE TITLE
Can't take advantange of covariance of trait T[+A[_<:B[X], _], X] when extending it: self type error.

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12242]
## reproduction steps

using Scala 2.13.4,

```scala
	trait Box[T]

	trait Adapter[B <: Box[T], T]

	trait SpecialAdapter[B <: Box[T], T] extends Adapter[B, T]

	trait Mixin[+A[B <: Box[S], X], S]

	trait Super[T] extends Mixin[Adapter, T]

	trait Sub[T] extends Super[T] with Mixin[SpecialAdapter, T]
```

## problem
```
illegal inheritance;
 self-type Playground.Sub[T] does not conform to Playground.Mixin[Playground.SpecialAdapter,T]'s selftype Playground.Mixin[Playground.SpecialAdapter,T]
	trait Sub[T] extends Super[T] with Mixin[SpecialAdapter, T]
```

Apparently all type parameters matter: I can't remove any without the error going away.  Crucial here is also the bound `<: Box[S]` in the type parameter of `Mixin`; removing it, or substituting it with `<: Box[_]` compiles.

**Comment by dwijnand** [comment]
I `SpecialAdapter` necessary?  Can't guess why it would be necessary instead of just using `Adapter`.

**Comment by joroKr21** [comment]
Shouldn't this be:
```diff
+ trait Mixin[+A[B <: Box[X], X], S]
- trait Mixin[+A[B <: Box[S], X], S]
```

Actually I think neither should work:
```scala
trait Super[T] extends Mixin[Adapter, T]
trait Sub[T] extends Super[T] with Mixin[SpecialAdapter, T]
```

but it seems that there are missing kind checks: #2067

**Comment by joroKr21** [comment]
As expected Scala 3 rejects `Mixin[Adapter, T]`
