### ISSUE TITLE
"match may not be exhaustive" warning for Enumeration

### ISSUE THREAD

**Issue by flomebul** [scala/bug#12244]
## reproduction steps

using Scala 2.13.4

```scala
  object Kind extends Enumeration {
    val Tiny, Small, Large = Value
  }

  def maxLo(kind: Kind.Value): Int =
    kind match {
      case Kind.Tiny  => 1
      case Kind.Small => 2
      case Kind.Large => 6
    }
```

## problem

```
ProgFoor.scala:9: warning: match may not be exhaustive.
It would fail on the following input: (x: bugs.ProgFoor.package.Kind.Value forSome x not in (Large, Small, Tiny))
    kind match {
    ^
```
I expect no warning while exhaustivity is quite an evidence.

**Comment by som-snytt** [comment]
Contrary evidence:
```
object Kind extends Enumeration {
  val Tiny, Small, Large = Value
  Value(100, "Huge")
}

class C {
  val Other = Kind.withName("Huge")
  def maxLo(kind: Kind.Value): Int =
    kind match {
      case Kind.Tiny  => 1
      case Kind.Small => 2
      case Kind.Large => 6
      case Other      => ???
    }
}

object Test extends App {
  val c = new C
  println(c.maxLo(Kind.Small))
  println(c.maxLo(c.Other))
}
```

**Comment by NthPortal** [comment]
an even better example:

```scala
object Kind extends Enumeration {
  val Tiny, Small, Large = Value
  def addValueAfterInit(name: String): Value = Value(name)
}
```

oops (please don't ever do this. please)

**Comment by NthPortal** [comment]
I'm going to say that this is not a bug, but rather a(n unfixable) design flaw of `Enumeration`. Scala 3's enums should be significantly better and should not have this problem

**Comment by SethTisue** [comment]
maybe it's time formally deprecate `scala.Enumeration`?

**Comment by NthPortal** [comment]
maybe? I feel like, despite its many shortcomings, it is concise, so we shouldn't deprecate it until its replacement (in Scala 3) is here.

on the other hand, it has many, many shortcomings

**Comment by flomebul** [comment]
Ok, understood : I'm wrong. Thanks.

**Comment by martijnhoekstra** [comment]
It's an understandable mistake. It ought to be exhaustive, and that it's not should come to the surprise of most people who made reasonable assumptions about Enumeration. Thanks for the report, it's good to have it on file!

**Comment by som-snytt** [comment]
The pattern described by Bloch and implemented for example as a logging Level includes dynamic extension, so let's not expect apples to be oranges.

OK, just checked, it is possible to get a `java.util.Enumeration` from a `scala.Enumeration`.
```
scala> scala.math.BigDecimal.RoundingMode.values.iterator.asJavaEnumeration
val res7: java.util.Enumeration[math.BigDecimal.RoundingMode.Value] = IteratorWrapper(<iterator>)
```

**Comment by NthPortal** [comment]
@flomebul you *should* be right, but sadly, `Enumeration`
