### ISSUE TITLE
Vector.unapplySeq is refutable

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/bug#12240]
## reproduction steps

using Scala 2.13.4

```scala
scala> Vector(1) match {
  case Vector(_ @ _*) => ???
}
```

## problem

> match may not be exhaustive.
> It would fail on the following input: `Vector1()`

The match is totally exhaustive. Unfortunately, scalac doesn't know. `Vector.unapplySeq` seems to be using name-based pattern matching to return a `SeqFactory.UnapplySeqWrapper`. But name-based pattern matching can't AFAIK provide irrefutable patterns, so the pattern ends up refutable, and the warning (with the somewhat odd counterexample) is emitted.

**Comment by martijnhoekstra** [comment]
reported at https://gitter.im/scala/scala?at=5fbbebf6ba69631c7496aaee by @mrdziuban

**Comment by mrdziuban** [comment]
If/when this is fixed, I would hope that a match statement like this would also be considered exhaustive

```scala
Vector("test") match {
  case Vector() => "empty"
  case Vector(_) => "one"
  case Vector(_, _, _*) => "two or more"
}
```

which seems like a good alternative to using `+:` like [my original question in gitter](https://gitter.im/scala/scala?at=5fbbe682ba69631c74969eed) which can't prove complementary exhaustiveness between `Vector()` and `+:`, e.g.

```scala
Vector("test") match {
  case Vector() => "empty"
  case _ +: Vector() => "one"
  case _ +: _ +: _ => "two or more"
}
```

**Comment by dwijnand** [comment]
I wonder if changing `UnapplySeqWrapper` to have `def isEmpty: false.type = false` fixes this?  Hopefully then two obviously exhaustive cases would be.
