### ISSUE TITLE
Supershell blanches partest exes (Xs)

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12256]
## reproduction steps

building Scala 2.13.5,

```plain
sbt> testAll
# starting 44 tests in presentation
..............XX............................
```

## problem

The X's start out red but immediately turn white.

Dotty says https://github.com/lampepfl/dotty/blob/M2/project/Build.scala#L193

**Comment by dwijnand** [comment]
Isn't this an sbt supershell issue, rather than a scala build issue?  I don't mind losing the red all together.  I think the supershell is useful handy and worth keeping.

**Comment by som-snytt** [comment]
I always run `sbt -Dsbt.supershell=false`.

**Comment by SethTisue** [comment]
anytime I feel myself missing the red X's, I just watch an episode or two of Family Feud to refuel:

<img width="370" alt="Screen Shot 2020-12-04 at 11 11 17 AM" src="https://user-images.githubusercontent.com/161079/101204765-94035880-3621-11eb-8768-b62b9c471766.png">

**Comment by som-snytt** [comment]
`partest --effeXXX`
