### ISSUE TITLE
`true` is not an irrefutable extractor type

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/bug#12254]
In fact, it's not an extractor type at all:

```scala
object Test {
  sealed trait Foo
  final class Bar extends Foo

  object Bar {
    def unapply(o: Bar) : true = true
  }

  def f(foo: Foo) = foo match {
    case Bar() => println("Bar")
  }
}

Test.scala:10: error: The result type of an unapply method must contain a member `get` to be used as an extractor pattern, no such member exists in true
    case Bar() => println("Bar")
         ^
1 error
```

_Originally posted by @robby-phd in https://github.com/scala/bug/issues/12232#issuecomment-735774442_

**Comment by Jasper-M** [comment]
I guess a case could be made that `: true` extractors should be rejected because they're useless.

**Comment by martijnhoekstra** [comment]
Not as useless as `: false` extractors!

Anyway, @robby-phd may want to weigh in on the use case they're looking to facilitate.

**Comment by dwijnand** [comment]
I assume you say they're useless because we have guards.  But I don't think they're useless when you consider the nesting property pattern matching brings.  Something like

```scala
case Apply(NonNullary(), List(NonEmptyToString(arg))) => ...
```

reads nicer, IMHO, than

```scala
case Apply(meth, List(arg)) if nonNullary(meth) && nonEmptyToString(arg) => ...
```

**Comment by Jasper-M** [comment]
Using an extractor statically known to return `true` is like `if (true) foo else bar`. Or am I not seeing something? Useless may be too strong, but not actually useful either I guess. Anyway I'm all for consistency so not really arguing that it shouldn't work.

**Comment by dwijnand** [comment]
Hmm, yeah, my example is bad.  But one thing that it would still bring is that the input type of the extractor is pre-requisite, but then why `case Foo(IsString())` when you can just `Foo(_: String)`?  🤔   Maybe under more complex types it's handy?  `case Foo(IsCollection())` rather than `case Foo(_: GenTraversableOnceOps[_, _, _ <: AnyRef])`... 🤡

**Comment by Jasper-M** [comment]
Good point. That does make is kind of useful.

**Comment by robby-phd** [comment]
Yes, it's handy for complex types (and good for consistency).
