### ISSUE TITLE
Scala Grammar

### ISSUE THREAD

**Issue by Gameonlp** [scala/bug#12260]
The grammar documentation here: https://www.scala-lang.org/files/archive/spec/2.13/13-syntax-summary.html does not match the accepted language of the compiler.

The compiler accepts '+', '~' and '|' as derivations of `id` which are part of the Unicode class Sm. These symbols should not be derivable for `id`, as they neither get matched by `upper`, `lower`, nor get matched by `opchar`.

Using compiler built on commit d45a673aae01df75f41c825a56d8d1a4532897e8.

**Comment by eed3si9n** [comment]
> ```
> opchar           ::=  // printableChar not matched by (whiteSpace | upper | lower |
>                       // letter | digit | paren | delim | Unicode_Sm | Unicode_So)
> ```

I agree this is a bug. Unicode Sm is [Symbol-Math](https://unicode.org/charts/script/chart_Symbol-Math.html), which includes `+` etc, so saying that Unicode Sm is _not an opchar_ seems wrong.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/9947

Note it's more clear in the chapter text.

**Comment by som-snytt** [comment]
oh sorry jinx, @eed3si9n or maybe we should say "hi-jinx" to combine the greetings.

**Comment by magnolia-k** [comment]
https://github.com/scala/scala/pull/9243

This issue has been closed as a duplicate(#9243), but the original issue was to remove `opchar` and was inconclusive about Unicode_Sm.

As the target character is between ¥u0020 and ¥u007F, I think that the Unicode specification can be removed.

**Comment by magnolia-k** [comment]
The following statement would be consistent with the implementation.

```
opchar ::=  printableChar not matched by (whiteSpace | upper | lower | letter | digit | paren | delim)

```

**Comment by som-snytt** [comment]
The test is https://github.com/scala/scala/blob/v2.13.6/src/reflect/scala/reflect/internal/Chars.scala#L85

```
def isSpecial(c: Char) = {
  val chtp = Character.getType(c)
  chtp == Character.MATH_SYMBOL.toInt || chtp == Character.OTHER_SYMBOL.toInt
}
```

**Comment by som-snytt** [comment]
For example, back when you could use unicode in source text,

```
Welcome to Scala 2.12.13 (OpenJDK 64-Bit Server VM, Java 16.0.1).
Type in expressions for evaluation. Or try :help.

scala> def \u2250 = 42
$u2250: Int
```
now I must go cut and paste...
```
Welcome to Scala 2.13.6 (OpenJDK 64-Bit Server VM, Java 16.0.1).
Type in expressions for evaluation. Or try :help.

scala> def ≐ = 42
def $u2250: Int

scala>
```
Oh, is this re-opened to move the RPAREN left? it should say "some printables | some symbols".

**Comment by som-snytt** [comment]
Somewhere I commented that the chapter text is correct:
```
Operator characters. These consist of all printable ASCII characters (\u0020 - \u007E) that are in none of the sets above, mathematical symbols (Sm) and other symbols (So).
```
https://github.com/scala/scala/blame/2.13.x/spec/01-lexical-syntax.md#L29

**Comment by magnolia-k** [comment]
I understand perfectly.

I will rework the description PR to add Unicode instead of excluding it.

**Comment by magnolia-k** [comment]
https://github.com/scala/scala/pull/9666
