### ISSUE TITLE
JLine 3: Support camel-cased, acronym-style completion as previously

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#12267]
for example, previously `System.rFOE` would complete to `System.runFinalizersOnExit`, but it doesn't anymore

**Comment by retronym** [comment]
Assigning myself because this is a pet feature of mine that I'd like to have back. I might tinker with the upstream contribution to JLine. I'll post my status here if/when I actively start working on this, feel free to work-steal the back, Seth, if you want to work on it yourself.

**Comment by retronym** [comment]
Started the upstream PR: https://github.com/jline/jline3/pull/626

**Comment by retronym** [comment]
I have a [WIP PR]https://github.com/retronym/scala/pull/110) that integrates the new JLine. So far so good. There are a few points to tidy up before I submit.

**Comment by som-snytt** [comment]
Shouldn't the title refer to "retronym-style completion"?

**Comment by SethTisue** [comment]
I went ahead and PRed the JLine upgrade separately: https://github.com/scala/scala/pull/9467 , as I think we'll want it regardless and now's a good time to be testing it

**Comment by retronym** [comment]
I'm quite happy with the state of my work in https://github.com/retronym/scala/pull/110. See the PR description for the fixes and new features. @som-snytt @SethTisue would you like to give it a spin and see if you can spot any bugs or UI improvement ideas?

**Comment by som-snytt** [comment]
Now I'm having second thoughts. The newspaper reports

>The district's arts department has decided to change its name, "VAPA" (visual and performing arts) to "SFUSD Arts Department" because they say "acronyms are a symptom of white supremacy culture,"

I would have said VAPA is too close to vapid and vaping.

The acronym for "SFUSD Arts Department" is SAD.

**Comment by SethTisue** [comment]
PR: https://github.com/scala/scala/pull/9656
