### ISSUE TITLE
REPL: broken highlighting

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12276]
## reproduction steps

using Scala 2.13.4,

```scala
scala> val decoderOut = java.nio.CharBuffer.allocate(5)
val decoderOut: java.nio.CharBuffer = ?????

scala> val decoderOut = java.nio.CharBuffer.allocate(6)
val ?[1m?[34mdecoderOut?[0m: ?[1m?[32mjava.nio.CharBuffer?[0m = ??????
```

## problem

Highlighting is broken.

**Comment by som-snytt** [comment]
Noticed at https://github.com/lampepfl/dotty/issues/10715

**Comment by SethTisue** [comment]
`allocate` fills in null characters, so it's equivalent to e.g. `Seq.fill(6)('\u0000').mkString`

I am having trouble resisting looking into this little puzzle

**Comment by griggt** [comment]
>```     if (binaryChars > 5) // more than one can count while holding a hamburger```

Should I even ask?  :zany_face: :

https://github.com/scala/scala/blob/cb345bf2501a9395762e5b5c5cc3f46371829aa3/src/repl/scala/tools/nsc/interpreter/Naming.scala#L31-L37

**Comment by som-snytt** [comment]
The filtering feature goes back a decade, to when displaying arbitrary data would put the terminal in a bad state. It's been a while since I've had to `stty sane` without any echo. The limit 5 probably represents "more than a couple of color/reset control sequence pairs."

It makes more sense to not filter structured output such as `val x =` but to take the `replStringOf` output and pipe it through hexdump if it contains non-printable chars. I was too lazy to do that in the PR. However, the test does do hexdump formatting.
