### ISSUE TITLE
REPL: display of method signatures should indicate when a method is deprecated

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#12279]
```
scala 2.13.4> "foo".pr<TAB>
prefixLength( (deprecated)   prepended(                   prependedAll(                product(
```

so far so good, but now:

```scala> "foobar".prefixLength<TAB>
final def prefixLength(p: Char => Boolean): Int
```

this should also have a `(deprecated)` after it, IMO

**Comment by jxnu-liguobin** [comment]
Hi, How to participate in solving this problem? and where is the code files? @SethTisue

**Comment by SethTisue** [comment]
@jxnu-liguobin Welcome! I have a video and slide deck called “You Are a Scala Contributor” ([link](https://slideslive.com/38908767/you-are-a-scala-contributor)) that has some general advice on working on Scala. `README.md` and `CONTRIBUTING.md` in the scala/scala repo have a lot of helpful information.

The code for the user interface aspects of the REPL are in `src/repl-frontend`. For display of method signatures, `interpreter/jline/Reader.scala` has code in `Completion#complete`:

```scala
      // the presence of the empty string here is a signal that the symbol
      // is already complete and so instead of completing, we want to show
      // the user the method signature. ...
```

I've answered fairly briefly, but I will keep answering if you keep asking.

(Help is also available at https://gitter.im/scala/contributors. Tickets and pull requests are usually the best places to ask about the technical specifics of a problem; Gitter can be better for questions about build issues, the contribution process, etc.)

**Comment by SethTisue** [comment]
```
scala 2.13.4> "foo".pr<TAB>
prefixLength( (deprecated)   prepended(                   prependedAll(                product(
```

Note that the PR that added the "(deprecated)" display in this other part of the REPL UI is https://github.com/scala/scala/pull/8905 — that shows where the information about whether a method is deprecated is available.

**Comment by jxnu-liguobin** [comment]
@SethTisue Expect result is ```final def prefixLength(p: Char => Boolean): Int (deprecated)``` ?

**Comment by SethTisue** [comment]
yeah

**Comment by jxnu-liguobin** [comment]
@SethTisue I submitted a draft pr.(It's not clear how to write tests for println)
