### ISSUE TITLE
Try(null).toOption

### ISSUE THREAD

**Issue by kiranbayram** [scala/bug#12288]
## reproduction steps

using Scala (2.13.3),

```scala
scala> scala.util.Try(null).toOption
res5: Option[Null] = Some(null)
```

## problem

Sorry if i'm asking a stupid question but wouldn't it be better if the statement above returns `None` instead of `Some(null)`.

**Comment by som-snytt** [comment]
The doc says "Returns None if this is a Failure or a Some containing the value if this is a Success."

https://www.scala-lang.org/api/current/scala/util/Try.html#toOption:Option[T]

**Comment by kiranbayram** [comment]
Thanks for the explanation. Should i close the ticket or do you do it?

**Comment by som-snytt** [comment]
OK I'll close if you're happy, I'm happy.

**Comment by SethTisue** [comment]
(please use https://users.scala-lang.org for questions)

**Comment by som-snytt** [comment]
I also submitted a question as an issue at the other repo because my elvis example is broken in dotty.
