### ISSUE TITLE
unicode escape sequence for backslash symbol (`\u005c') is treated differently since 2.13.2

### ISSUE THREAD

**Issue by unkarjedy** [scala/bug#12293]
## reproduction steps

Since 2.13.2 Unicode escape sequence for backslash (`\u005c`) is treated as an escaped backslash `\\` at a source level.
In 2.12.12 & 2.11.12 it's treated as single `\` at a source level (except `raw` interpolated string literals and non-interpolated multiline string literals)

I couldn't find any related ticket, PR or discussion.
Is it as designed or a regression?

```scala
"\u005c\u005c"
"""\u005c\u005c"""
s"\u005c\u005c"
s"""\u005c\u005c"""
raw"\u005c\u005c"
raw"""\u005c\u005c"""
```

![image](https://user-images.githubusercontent.com/3989292/102899227-a849b100-447b-11eb-8f66-dc21be8894bc.png)

![image](https://user-images.githubusercontent.com/3989292/102899259-b4357300-447b-11eb-8f45-9df9fe8c8f82.png)

**Comment by unkarjedy** [comment]
@martijnhoekstra could this change https://github.com/scala/bug/issues/11966 somehow lead to this?

**Comment by martijnhoekstra** [comment]
This is https://github.com/scala/scala/pull/8282, listed in the release notes of 2.13.2 at https://github.com/scala/scala/releases/tag/v2.13.2: Unicode escapes are now ordinary escape sequences (not processed early) (#8282), and indeed as intended.

Instead of "\u005c\u005c", use "\\". Insteaf of, for example, "\u005ct", use "\\t". Are there any other issues you're running in to with that?

**Comment by unkarjedy** [comment]
Oh, sorry, that was so dum from me... 
I've checked 2.13.4 notes, but after I discovered that the issue appeared in 2.13.2 I didn't recheck it's release notes

>That was, at least by me, seen as an improvement

I also think this is an improvement. Less "WTF" cases. (though technically it is a regression)

>Are there any other issues I'm not thinking of that you're running in to?

No, I am fixing various edge cases with string literals in IntelliJ Scala Plugin (in different subsystems), and I noticed this difference.
Wanted to ensure which is the expected behaviour. Sorry for bothering.

**Comment by martijnhoekstra** [comment]
This will definitely cut down on your sting literal edgecases.

**Comment by som-snytt** [comment]
Death, where is thy sting? or string?

**Comment by unkarjedy** [comment]
@martijnhoekstra
Not sure whether to create a new issue..
Is this expected that the output for the input:
```scala
scala.util.Properties.versionString

"""\"""
"""\\"""
"""\\\"""
"""\u0025"""
"""\\u0025"""
"""\\\u0025"""
"""\\\\u0025"""
```
will be
![image](https://user-images.githubusercontent.com/3989292/104605772-fa06e500-568f-11eb-940f-2b22d8766c81.png)

I understand why it works so, but it looks like a bug to me.
I would expect output to be:
```
val res1: String = \
val res2: String = \\
val res3: String = \\\
val res4: String = %
val res5: String = \%
val res6: String = \\%
val res7: String = \\\%
```
WDYT?

**Comment by martijnhoekstra** [comment]
That would totally make sense. The PR mentions it

> That last condition is really weird since the backslash itself isn't escaped or anything, but it's a carryover of how the scanner used to determine whether to process the escape or not.

There is also a comment in the source where it happens:

>  If a backslash is followed by one or more `u` characters and there is
    an odd number of backslashes immediately preceding the `u`, processing
    the escape is attempted and an invalid escape is an error.
    The odd backslashes rule is, well, odd, but is grandfathered in from
    pre-2.13.2 times, when this same rule existed in the scanner, and was also
    odd. Since escape handling here is for backwards compatibility only, that
    backwards compatibility is also retained.

**Comment by som-snytt** [comment]
The odd rule is inherited from Java, JLS 3.3. Also multiple uu. That has to do with round-tripping to ASCII.

**Comment by unkarjedy** [comment]
Ok, guess we will just leave with it until everyone migrates to Scala 3 with removed Unicode escapes in raw literals.

No questions regarding `\uuu0025`, cause AFAIR it existed for ages in Scala and was inherited from Java.
