### ISSUE TITLE
scala.util.Random.alphanumeric throws an exception using Scala 2.13.4 and Eclipse OpenJ9 VM

### ISSUE THREAD

**Issue by lvitaly** [scala/bug#12291]
## reproduction steps

using Scala 2.13.4 and Eclipse OpenJ9 VM, Java 11.0.9 (jdk-11.0.9_11_openj9-0.23.0),

```scala
[info] Starting scala interpreter...
Welcome to Scala 2.13.4 (Eclipse OpenJ9 VM, Java 11.0.9).
Type in expressions for evaluation. Or try :help.

scala> scala.util.Random.alphanumeric
java.lang.IllegalAccessError: Class 'scala.util.Random' no access to: class 'scala.collection.immutable.LazyList$State'
  at java.base/java.lang.invoke.MethodHandle.sendResolveMethodHandle(MethodHandle.java:1248)
  at java.base/java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method)
  at java.base/java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:1068)
  at scala.util.Random.alphanumeric(Random.scala:252)
  ... 37 elided
Caused by: java.lang.IllegalAccessException: Class 'scala.util.Random' no access to: class 'scala.collection.immutable.LazyList$State'
  at java.base/java.lang.invoke.MethodHandles$Lookup.checkClassAccess(MethodHandles.java:501)
  at java.base/java.lang.invoke.MethodHandles$Lookup.accessCheckArgRetTypes(MethodHandles.java:790)
  at java.base/java.lang.invoke.MethodHandle.sendResolveMethodHandle(MethodHandle.java:1222)
  ... 40 more
```

## problem

works just fine using Scala 2.13.3 and Eclipse OpenJ9 VM, Java 11.0.9 (jdk-11.0.9_11_openj9-0.23.0)

```scala
[info] Starting scala interpreter...
Welcome to Scala 2.13.3 (Eclipse OpenJ9 VM, Java 11.0.9).
Type in expressions for evaluation. Or try :help.

scala> scala.util.Random.alphanumeric
val res0: scala.collection.immutable.LazyList[Char] = LazyList(<not computed>)
```

**Comment by lrytz** [comment]
Comparing the classfiles `scala/util/Random.class` and `LazyList$State.class` between 2.13.3 and 2.13.4, the only difference is the InnerClass enry:

```diff
-  // access flags 0x609
-  public static abstract INNERCLASS scala/collection/immutable/LazyList$State scala/collection/immutable/LazyList State
+  // access flags 0x60A
+  private static abstract INNERCLASS scala/collection/immutable/LazyList$State scala/collection/immutable/LazyList State
```

This change is due to https://github.com/scala/scala/pull/9131 (cc @retronym).

The InnerClass table is supposed to express source-level properties, so marking the inner class `private` is correct. The [VM spec says](https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.7.6)

> The value of the inner_class_access_flags item is a mask of flags used to denote access permissions to and properties of class or interface C as declared in the source code from which this class file was compiled. It is used by a compiler to recover the original information when source code is not available.

So I believe it's a bug in OpenJ9 that the flag in the InnerClass table affects runtime semantics. The classfile for `LazyList$State` is public, `0x601` is `ACC_PUBLIC | ACC_INTERFACE | ACC_ABSTRACT`.

```
// access flags 0x601
public abstract interface scala/collection/immutable/LazyList$State
```

**Comment by pshipton** [comment]
Does Hotspot have the same behavior?

**Comment by SethTisue** [comment]
Closing because this was actually an OpenJ9 bug, which it appears is now fixed.
