### ISSUE TITLE
It is possible to set a parameter name to a method parameter that is illegal in Java

### ISSUE THREAD

**Issue by magnolia-k** [scala/bug#12306]
## reproduction steps

using Scala 2.13.4,

```scala
scala> case class Person(`user.id`: String)
class Person

scala> classOf[Person].getConstructors.head.getParameters.map(_.getName)
java.lang.reflect.MalformedParametersException: Invalid parameter name "user.id"
  at java.base/java.lang.reflect.Executable.verifyParameters(Executable.java:392)
  at java.base/java.lang.reflect.Executable.privateGetParameters(Executable.java:422)
  at java.base/java.lang.reflect.Executable.getParameters(Executable.java:363)
  ... 32 elided

scala> val p = Person(`user.id` = "ID1")
val p: Person = Person(ID1)
```

## problem

Parameter names containing dots are reasonable in Scala, but not in Java.

The method name of the accessor generated from the parameter is converted to an appropriate method name in Java and stored in the bytecode, but the parameter name is stored as is.

When the parameter name is accessed via Java reflection, an exception will be thrown due to the presence of invalid characters.

However, the accessor method works properly.

This check has been introduced in the following Java commit.

https://github.com/openjdk/jdk/commit/367fa5ac0ee697dd6afb71fe7f860d7719199146

---

It might be more appropriate to warn about the behavior of Scala 2, when defining methods.

**Comment by som-snytt** [comment]
It appears to be inadvertent, as usually the name is encoded:

```
  public int f(int);
    descriptor: (I)I
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=2, args_size=2
         0: iload_1
         1: ireturn
      LineNumberTable:
        line 1: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       2     0  this   L$line4/$read$$iw;
            0       2     1 user$u002Eid   I
    MethodParameters:
      Name                           Flags
      user.id                        final
```
You can use the encoded name from Scala, too, which is not obvious:
```
scala> C(user$u002Eid = 42)
val res1: C = C(42)
```

**Comment by martijnhoekstra** [comment]
If I read paragraph 4.2.2 from the JVM spec correctly, this is indeed illegal:

> 4.2.2 Unqualified Names
> Names of methods, fields, local variables, and formal parameters are stored as
unqualified names. An unqualified name must contain at least one Unicode code
point and must not contain any of the ASCII characters . ; [ / (that is, period or
semicolon or left square bracket or forward slash).

**Comment by som-snytt** [comment]
The long discussion to hone the PR doesn't mention the name itself, and it uses `name.decoded`.

https://github.com/scala/scala/pull/4735/files

**Comment by som-snytt** [comment]
It's worth adding that Scala spec says "host systems may impose restrictions on legal strings" in backticks, but I don't think breaking Java interop as shown was intended.

**Comment by SethTisue** [comment]
nice catch — thanks for the report. (and thanks, @som-snytt, for the prompt fix.)
