### ISSUE TITLE
Global.askLoadedTyped no longer reports warnings

### ISSUE THREAD

**Issue by tgodzik** [scala/bug#12308]
## reproduction steps

using Scala 2.12.13 and 2.13.x

```scala
  def toTextDocument(
      global: Global,
      code: String,
      filename: String,
      timeout: Long,
      options: List[String]
  ): s.TextDocument = {
    val unit = addCompilationUnit(global, code, filename)
    global.typeCheck(unit)
    // reload seems to be necessary before askLoadedType.
    ask[Unit](r => global.askReload(unit.source :: Nil, r)).get
    val compiledTree =
      ask[compiler.Tree](r => global.askLoadedTyped(unit.source, r))
        .get(timeout)
    val tree = compiledTree match {
      case Some(Left(t)) => t
      case Some(Right(ex)) => throw ex
      case None => throw new IllegalArgumentException("Presentation compiler timed out")
    }
    lazy val semanticdbOps: SemanticdbOps {
      val global: global.type
    } = new SemanticdbOps {
      val global: global.type = compiler
    }
    semanticdbOps.config =
      SemanticdbConfig.parse(options, _ => (), global.reporter, SemanticdbConfig.default)
    import semanticdbOps._
    unit.body = tree
    val document = unit.asInstanceOf[semanticdbOps.global.CompilationUnit].toTextDocument
    document
  }
```

## problem

We use ` compiler.askLoadedTyped` to interactively construct semanticdb file to be used for example in scalafix. When we enable `-Ywarn-unused:imports` until 2.12.12 it used to report the warnings right away with it. However, this no longer works in 2.12.13 and as it also turns out in 2.13.x also.

I think this might have something to do with the recent `-Wconf` changes as running `global.compileSources` does report them (though we don't get a fully typed tree or at least I was unable to obtain it.).

Is there a way to force the warnings to be reported straight away? @lrytz any idea how I can work around it? Basically I need the fully typed tree and  warnings reported. I will try to work around it but any help would be appreciated.

**Comment by tgodzik** [comment]
Trying something like:
```scala
    val unit = addCompilationUnit(compiler, code, filename)
    val run = new compiler.Run
    // run.compileSources(List(unit.source))
    run.compileUnits(List(unit), run.parserPhase)
```

doesn't give as a full tree - it's missing imports

**Comment by tgodzik** [comment]
Seems like `compiler.runReporting.reportSuspendedMessages()` is the answer here.

**Comment by SethTisue** [comment]
@lrytz (this comes out of the Gitter discussion I mentioned to you)

**Comment by dwijnand** [comment]
Looks like using that has worked for scalameta: https://github.com/scalameta/scalameta/pull/2216.

**Comment by lrytz** [comment]
> Seems like `compiler.runReporting.reportSuspendedMessages()` is the answer here.

👍 

The typer phase's `run` [method invokes `reportSuspendedMessages`](https://github.com/scala/scala/blob/cb345bf2501a9395762e5b5c5cc3f46371829aa3/src/compiler/scala/tools/nsc/typechecker/Analyzer.scala#L100-L113), however the call `interactiveGlobal.typeCheck` only calls `typerPhase.apply`, so we never get to `reportSuspendedMessages`.

We might have to fix the implementation of suspended warninigs. It seems the interactive `Global` can run the `typerPhase` multiple times without creating a new `Run`. Calling `reportSuspendedMessages` will set `runReporting.suppressionsComplete = true`, so a subsequent `interactiveGlobal.typeCheck` that uses the same `Run` will probably not handle `@nowarn` correctly, i.e., warnings that should be silenced would get reported.

We should handle the suspension of warnings per compilation unit instead, and report suspended warnings at the end of `typerPhase.apply`.
