### ISSUE TITLE
Scala 2.13 spec doc format error.

### ISSUE THREAD

**Issue by counter2015** [scala/bug#12302]
Comparing 2.12 doc and 2.13 doc.

## 2.12

https://www.scala-lang.org/files/archive/spec/2.12/08-pattern-matching.html
![image](https://user-images.githubusercontent.com/13608862/104265754-418f4480-54c9-11eb-81be-1811e9a58459.png)

## 2.13
https://www.scala-lang.org/files/archive/spec/2.13/08-pattern-matching.html
![image](https://user-images.githubusercontent.com/13608862/104265945-a0ed5480-54c9-11eb-966c-e65007dda224.png)

## Problems

The source of two pages:
- 2.12 https://github.com/scala/scala/blob/2.12.x/spec/08-pattern-matching.md
- 2.13 https://github.com/scala/scala/blob/2.13.x/spec/08-pattern-matching.md

I guess that the  `≥` symbol should use `$\geq 2$` instead of `´\geq 2´`

I didn't check every page, this problem may occur in other pages too.

BTW, the thing `1 and 3` is rendered as `I and 3` makes me confused.

**Comment by forketyfork** [comment]
I can't reproduce, the text by the 2.13 link looks fine for me. The delimiter was purposefully changed from `$` to `´` with a matching rendering configuration update, so this shouldn't be the cause. But I believe the math rendering library was also recently changed from MathJax to KaTeX, so this could be a browser incompatibility issue. Which browser do you use, and are there any errors in the browser console when you open the page for 2.13?

**Comment by counter2015** [comment]
@forketyfork you're right. It is because network problem, I can't get `https://code.jquery.com/jquery-3.5.1.min.js`.

Thanks!
