### ISSUE TITLE
Pattern matching incompatible type does not result compiler error

### ISSUE THREAD

**Issue by texasbruce** [scala/bug#12304]
## reproduction steps

using Scala 2.13.2,

```scala
scala> class Foo
class Foo

scala> val m: Map[String, Map[String, Foo]] = Map("outer" -> Map("inner" -> new Foo))
val m: Map[String,Map[String,Foo]] = Map(outer -> Map(inner -> Foo@28bd5015))

scala> m.collect { case (_, foo: Foo) => "This should be type error" }
val res1: scala.collection.immutable.Iterable[String] = List()

```

## problem

In the example when I tried to match Map as a Foo, it should result in compiler error because they are incompatible non-covariant types and should result a compiler error.

**Comment by texasbruce** [comment]
Compiler warning generated here:

```scala
scala> class Foo
class Foo

scala> class Bar
class Bar

scala> val m = Map(1 -> new Foo)
val m: scala.collection.immutable.Map[Int,Foo] = Map(1 -> Foo@646e6d07)

scala> m.collect { case (_, bar: Bar) =>}
                                 ^
       warning: fruitless type test: a value of type Foo cannot also be a Bar
val res1: scala.collection.immutable.Iterable[Unit] = List()

```

**Comment by dwijnand** [comment]
@retronym was looking at this recently: https://github.com/scala/scala/pull/9372.

**Comment by SethTisue** [comment]
It's unclear whether Jason might return to that PR, so interested contributors shouldn't hesitate to step forward.

**Comment by jxnu-liguobin** [comment]
I want to know about it, why https://github.com/retronym/scala/pull/109/files was closed?

**Comment by SethTisue** [comment]
The best way to attract Jason's attention would be to resubmit it (as a draft) — presumably there will be test failures we can take a look at.

**Comment by SethTisue** [comment]
@jxnu-liguobin has resurrected Jason's PR at https://github.com/scala/scala/pull/9706

**Comment by SethTisue** [comment]
Dale realized just now that this isn't a bug, in either Scala 2 or 3. `class Foo` isn't final, and `Map` is an unsealed trait, so somebody can `class Bar extends Foo with Map[...]`. The compiler is right not to warn.

However, Jason's PR has some related test cases that _are_ broken. I'll open a new ticket with those shortly.

**Comment by SethTisue** [comment]
> I'll open a new ticket with those shortly.

https://github.com/scala/bug/issues/12438
