### ISSUE TITLE
Scaladoc incorrectly fails on some constants it thinks are unused

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#12303]
## reproduction steps

using Scala 2.13.x, [2.12.2, 2.12.12],

File `Test.scala`:

```scala
import scala.annotation.implicitNotFound

object Test {
  private final val one   = "foo"
  private final val two   = "foo" + "bar"
  private final val three = "foo" + "bar" + "baz"
  private final val four  = "foo" + "bar" + "baz" + " oh no"

  @implicitNotFound(one)   trait One
  @implicitNotFound(two)   trait Two
  @implicitNotFound(three) trait Three
  @implicitNotFound(four)  trait Four
}
```

For 2.13:

```
$ scaladoc -Xlint -Werror Test.scala
Test.scala:6: warning: private val three in object Test is never used
  private final val three = "foo" + "bar" + "baz"
                    ^
Test.scala:7: warning: private val four in object Test is never used
  private final val four  = "foo" + "bar" + "baz" + " oh no"
                    ^
error: No warnings can be incurred under -Werror.
2 warnings
```

For 2.12.2 through 2.12.12:

```
$ scaladoc -Xlint -Xfatal-warnings Test.scala
Test.scala:6: warning: private val three in object Test is never used
  private final val three = "foo" + "bar" + "baz"
                    ^
Test.scala:7: warning: private val four in object Test is never used
  private final val four  = "foo" + "bar" + "baz" + " oh no"
                    ^
error: No warnings can be incurred under -Xfatal-warnings.
model contains 6 documentable templates
two warnings found
one error found
```

## problem

- the values *are* used
- it only happens when the constant is defined by more than one string concatenation
- it's checked by scaladoc at all, when it really shouldn't be

**Comment by NthPortal** [comment]
based on my testing, it appears to have been introduced between 2.12.1 and 2.12.2

**Comment by som-snytt** [comment]
I vaguely recall something about with 2 or more operators, the expression is not constant-folded so that the field is not eliminated. All are inlined. There would be an existing ticket about it.

**Comment by NthPortal** [comment]
they may be related, but these errors only occur with linting and fatal warnings

**Comment by SethTisue** [comment]
Perhaps the details around the interaction with constant folding are a distraction here, and Scaladoc runs simply shouldn't be doing unused checks at all — just a missing `settings.isScaladoc` check?

**Comment by NthPortal** [comment]
I'm still baffled by why it only fails in 2.13 when `-feature` is set though

**Comment by som-snytt** [comment]
I do not see that -feature is required.
```
➜  snips scaladoc -d /tmp -Xlint t12303.scala
t12303.scala:6: warning: private val three in object Test is never used
  private final val three = "foo" + "bar" + "baz"
                    ^
t12303.scala:7: warning: private val four in object Test is never used
  private final val four  = "foo" + "bar" + "baz" + " oh no"
                    ^
2 warnings
➜  snips scaladoc -version
Scaladoc version 2.13.4 -- Copyright 2002-2020, LAMP/EPFL and Lightbend, Inc.
```

**Comment by som-snytt** [comment]
I don't think compiler diagnostics should be scaladoc-aware, but I could see `ScaladocSettings` turning irrelevant settings into no-ops (or whatever state is desirable).

**Comment by NthPortal** [comment]
that's weird. I could swear I needed it
