### ISSUE TITLE
REPL: a List/Seq with the last comma in different lines have different appearance

### ISSUE THREAD

**Issue by imx7** [scala/bug#12310]
scala> val a=List("a",    "b",    "c",    "d",    "e",
     | )
a: List[String] = List(a, b, c, d, e)

scala> val a=List("a",    "b",    "c",    "d",    "e",)
<console>:1: error: illegal start of simple expression
       val a=List("a",    "b",    "c",    "d",    "e",)

**Comment by imx7** [comment]
val a=List("a", "b", "c", "d", "e",
)
it works well in REPL,but got an error in Intellij IDEA

**Comment by som-snytt** [comment]
It's defined to work just for the multiline case.

https://scala-lang.org/files/archive/spec/2.13/01-lexical-syntax.html#trailing-commas-in-multi-line-expressions

It's not clear to me if the issue is that REPL doesn't print the val in trailing-comma format, as entered.

**Comment by SethTisue** [comment]
I don't know why you're seeing something different in IntelliJ, but note that IntelliJ uses their own compiler, sometimes there are discrepancies.
