### ISSUE TITLE
Wrong "SEP" used in scala / scalac / scalap / scaladoc shell script in cygwin environment

### ISSUE THREAD

**Issue by flomebul** [scala/bug#12318]
## reproduction steps

using Scala 2.13.4,

```
scala -toolcp lib/jansi-2.1.1.jar
```

## problem

At line 162 of the scrupt, the jar file is added in the "TOOL_CLASSPATH" with a ":", not with a ";", but the "TOOL_CLASSPATH" is already converted to windows path at this line.

**Comment by som-snytt** [comment]
i.e., `cygpath` conversion should happen last. Looks like it has always been broken.

**Comment by som-snytt** [comment]
I thought I might try and tackle this one.
