### ISSUE TITLE
"@nowarn annotation does not suppress any warnings" makes cross building difficult

### ISSUE THREAD

**Issue by eed3si9n** [scala/bug#12313]
## reproduction steps

Using Scala 2.13.4, call some method that is deprecated using `@nowarn`.

```scala
scala> def foo = Map(1 -> 1).mapValues(_ + 1)
                             ^
       warning: method mapValues in trait MapOps is deprecated (since 2.13.0): Use .view.mapValues(f). A future version will include a strict version of this method (for now, .view.mapValues(f).toMap).
def foo: scala.collection.MapView[Int,Int]

scala> import scala.annotation.nowarn
import scala.annotation.nowarn

scala> @nowarn def foo = Map(1 -> 1).mapValues(_ + 1)
def foo: scala.collection.MapView[Int,Int]
```

Now try to cross build this using Scala 2.12.13:

```scala
scala> @nowarn def foo = Map(1 -> 1).mapValues(_ + 1)
<console>:11: warning: @nowarn annotation does not suppress any warnings
@nowarn def foo = Map(1 -> 1).mapValues(_ + 1)
 ^
error: No warnings can be incurred under -Xfatal-warnings.
```

## problem

The problem is that it warns about the fact that `@nowarn` doesn't suppress anything in Scala 2.12.x.

## expectation

It should ignore seemingly frivolous `@nowarn`s because it could be for cross building.

**Comment by ghik** [comment]
I think it can be turned off with `-Wconf:unused-nowarn:s`

**Comment by som-snytt** [comment]
For completeness, `-Wunused:-nowarn` or `-Ywarn-unused:-nowarn`

**Comment by eed3si9n** [comment]
Thanks guys. I'll close this issue.

**Comment by jatcwang** [comment]
Another option is to use https://github.com/typelevel/scalac-compat to control which Scala version `@nowarn` will apply
