### ISSUE TITLE
Performance improvement for immutable Set creation

### ISSUE THREAD

**Issue by texasbruce** [scala/bug#12319]
This is a feature request. I tried to add this to the contributor forum but the forum doesn't have a category for collection library enhancement so I added it here.

## problem

For specializations of immutable Set (Set1, Set2, Set3, Set4), currently there is no way to create instance of them directly, but only through from method and builder pattern, and it creates quite a few unnecessary temporary objects. For a call like Set(1,2,3,4), it creates `ArraySeq` for varargs, then `SetBuilder`, then it goes from `Set1` -> `Set2` -> `Set3` -> `Set4` -> `HashSetBuilder` if size is more than 4 and copy all the elements to new builder -> result). 

We can improve this by adding size compare to `Set.from` method and test if knownSize is 1,2,3,4 and create the specialization class directly. And also we can change the access of the SetN classes to public instead of private right now.

E.g.

```
  def from[E](it: collection.IterableOnce[E]): Set[E] =
    it match {
      case _: SortedSet[E]         => (newBuilder[E] ++= it).result()
      case _ if it.knownSize == 0  => empty[E]
      case _ if it.knownSize == 1  => new Set1(it.iterator.next)
      //... etc.
      case s: Set[E]               => s
      case _                       => (newBuilder[E] ++= it).result()
    }
```

We can also add a convenience method `Set.single` similar to `Iterable.single` to create a single item Set without any overhead of varargs. Another possible thing we can do is to make SetN class constructors public instead of private right now so users can call them directly to make the best decisions.

**Comment by SethTisue** [comment]
at https://contributors.scala-lang.org/categories there was a "Scala Core" category which was IMO poorly named. I've renamed it to "Scala Standard Library"

**Comment by SethTisue** [comment]
related: https://github.com/scala/scala/pull/8790

**Comment by SethTisue** [comment]
also related: https://github.com/scala/scala-library-next/issues/42

(but I'm going to lock the issue to discourage further discussion. if I see a contributors thread start, I'll link to it from here.)
