### ISSUE TITLE
scala.runtime.BoxesRunTime.java unboxing issue

### ISSUE THREAD

**Issue by pjfanning** [scala/bug#12327]
## reproduction steps

The commented out assertion in https://github.com/FasterXML/jackson-module-scala/blob/master/src/test/scala/com/fasterxml/jackson/module/scala/deser/ParamWithDashNameDeserializerTest.scala#L49 fails with all Scala versions I've tested with.

Fails with (when assertion is uncommented)
```
[info] - should support param names with dashes *** FAILED ***
[info]   java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
[info]   at scala.runtime.BoxesRunTime.unboxToLong(BoxesRunTime.java:103)
[info]   at scala.runtime.java8.JFunction1$mcJJ$sp.apply(JFunction1$mcJJ$sp.scala:17)
[info]   at scala.Option.map(Option.scala:242)
[info]   at com.fasterxml.jackson.module.scala.deser.ParamWithDashNameDeserializerTest.useOptionLong(ParamWithDashNameDeserializerTest.scala:22)
```

## problem

Jackson relies on Java reflection and has issues because of type erasure. In the test above, there is an attempt to deserialize JSON to a Class that has a variable of type Option[Long] but Jackson passes a java.lang.Integer instead. The test passes if a larger number is used (a number greater than Max Int).

BoxesRunTime could cast to java.lang.Number instead of to a specific class like Long or Integer. See https://docs.oracle.com/javase/8/docs/api/java/lang/Number.html

```
    public static long unboxToLong(Object l) {
        return l == null ? 0 : ((java.lang.Long)l).longValue();
    }
```

Could be rewritten as
```
    public static long unboxToLong(Object l) {
        return l == null ? 0 : ((java.lang.Number)l).longValue();
    }
```

If this change is ok, I could do a Scala 2.13 PR.

**Comment by SethTisue** [comment]
I don't understand why this would or should be considered Scala's bug and not Jackson's?

**Comment by pjfanning** [comment]
@SethTisue thanks for having a look.

Jackson is based around Java reflection and when taking `{"value-long":251}` and deserializing it to Option[AnyRef] - it treats the 251 as an int. The fact that the class is really Option[Long] is lost because of type erasure. Calling `map` on the Option[Long] then fails when the unboxing in BoxesRunTime happens.
I'm not sure if Jackson can really be fixed.

In the test case, a small tweak to BoxesRunTime would probably fix at least the use case in the test case in the description. Casting to java.lang.Number in BoxesRunTime doesn't change its behaviour fundamentally and makes it a bit more tolerant.

Feel free to close this if you think BoxesRunTime should not be changed.

**Comment by sjrd** [comment]
This change would have major, unpredictable consequences in terms of performance for all existing code everywhere. Even if we wanted to, we'd need a very thorough experimental analysis of that impact, and I don't expect anyone to be willing to do that.

This is not a Scala bug. It's definitely a bug or at least a limitation of Jackson.

**Comment by som-snytt** [comment]
The next test "(annotated case)" is incorrectly commented out.

Possibly, finicky unboxing helps to find bugs in boxing, so that may be another reason to resist the change.

**Comment by pjfanning** [comment]
Thanks everyone for your time. I'll close this.

**Comment by robert-blankenship** [comment]
(Sorry, I know this is a Scala ticket and an old one at that but I couldn't find anywhere else to discuss it).

@pjfanning Did you ever create a ticket with Jackson?

This looks like a bug to me. Say you are trying to deserialize this:
```
case class MyJsonObj(myJsonField: Option[Long])
```

If `myJsonField` fits into an Int, you will get an exception trying to deserialize the JSON. The solution appears to be this:

```
case class MyJsonObj(
  @JsonDeserialize(contentAs=classOf[java.lang.Long])
  myJsonField: Option[Long]
)
```

But the solution is just weird and clunky... And to make matters worse, the exception is runtime when you access the field `obj.myJsonField`. An `Int` should be an `Int` and a `Long` should be a `Long`. Something about it feels prematurely optimized and opaque. I would prefer it the other way where I pass in some annotation to magically squeeze the JSON into the smallest type.

Does it behave the same way when dealing with `Short` or `Byte`?

**Comment by pjfanning** [comment]
@robert-blankenship there is no solution known for this issue - it is documented at https://github.com/FasterXML/jackson-module-scala/wiki/FAQ#deserializing-optionint-seqint-and-other-primitive-challenges and affects all primitives, including Short and Byte

**Comment by hanishi** [comment]
When spray‑json deserializes a JSON number into a case class field of type Long (or Option[Long]), if the number fits within the Int range, it is represented as a java.lang.Integer. Later, when Scala’s unboxing mechanism (via BoxesRunTime.unboxToLong) attempts to convert that value to a Long, it fails with a ClassCastException. This issue did not occur under JDK 8, but newer versions enforce stricter type conversions. If the number is large enough, spray‑json produces a java.lang.Long, and the conversion succeeds.

**Comment by hanishi** [comment]
Could our distributed setup—where the case class is deserialized on one JVM and then transmitted to a shard entity in a Pekko cluster as a message—exacerbate the issue? This might explain why the error doesn’t occur in a local unit test but appears in the cluster environment.

**Comment by sjrd** [comment]
@hanishi Please ask questions on https://users.scala-lang.org/
This bug tracker is for bug reports only.
Thank you for your understanding.

**Comment by hanishi** [comment]
@sjrd 
Thank you for the pointer. I’ll try to rephrase the issue as a question and post it on the Scala Users forum to seek further clarification. 
We’ve observed the same behavior in our distributed environment—specifically when a case class is deserialized on one JVM and then transmitted to a shard entity in our Pekko cluster, the ClassCastException occurs. If this isn’t considered a bug, then what exactly is it? Is it an inherent limitation or a design choice in how Scala’s numeric unboxing works (especially with newer JDKs), or is there another explanation we should be aware of?

**Comment by hanishi** [comment]
On second thought, Jackson CBOR Serializable is handling the serialization. Maybe that's why. Sorry for all of the above.
