### ISSUE TITLE
Class annotated with @throws produces invalid Bytecode (invalid class type signature in classfile)

### ISSUE THREAD

**Issue by jbracker** [scala/bug#12324]
## reproduction steps

Using Scala 2.13.3 and Java 11.

Compile the following class into a class-file:

```scala
@throws(classOf[IllegalArgumentException])
class ScalaClass[T](someList: List[T]) {
   throw new IllegalArgumentException("Boom!")
}
```

## problem

The generated classfile/bytecode contains a type signature for `ScalaClass`. This type signature contains a _ThrowsSignature_ although these are only permitted as part of _MethodSignature_: 
https://docs.oracle.com/javase/specs/jvms/se15/html/jvms-4.html#jvms-4.7.9.1

This issue was discovered while working with ClassGraph to do bytecode analysis:
https://github.com/classgraph/classgraph/issues/495#issuecomment-768105884
You can read up on the details from the linked comment onwards.

At first we thought the type signature parser of ClassGraph was missing something, but we're confident that the bytecode generated by Scala is invalid. Later on in that issue you can see that `javac` even rejects the classfile generated by Scala due to it being invalid:
https://github.com/classgraph/classgraph/issues/495#issuecomment-768307245

Attached is a minimal Scala/Maven project that produces the said invalid classfile for the class mentioned above:
[ClassGraphMinimalExample.zip](https://github.com/scala/bug/files/5881407/ClassGraphMinimalExample.zip)

**Comment by SethTisue** [comment]
I assume your intent here that the `@throws` annotation would apply to the constructor? If so, I believe the syntax for that is `class C @throws ...`, as per https://riptutorial.com/scala/example/13168/annotating-the-main-constructor

Regardless, it's still a bug that the compiler accepts the form you tried

**Comment by jbracker** [comment]
> I assume your intent here that the `@throws` annotation would apply to the constructor?

Yes, that is the intention. The throws annotation is supposed to annotate the constructor.

> If so, I believe the syntax for that is `class C @throws ...`, as per https://riptutorial.com/scala/example/13168/annotating-the-main-constructor . Give that a try?

I will keep that in mind.

**Comment by som-snytt** [comment]
Confirmed the correct syntax, and that it works using a checked exception, i.e., javac errors if the exception is not declared.

**Comment by som-snytt** [comment]
Worth adding that `@throws[Exception]` looks more modern.
```
class C @throws[Exception] (c: Int)
```
