### ISSUE TITLE
Can't alias top level package

### ISSUE THREAD

**Issue by BalmungSan** [scala/bug#12329]
## Reproduction steps

Using Scala `2.13.4`, and assuming some top-level package `test`, then:

```scala
// Neither of these work:

import {test => t}

import _root_.{test => t}
```

## Problem

It feels arbitrary that this doesn't work for a top-level package when it works for any nested package.
Also, according to @Jasper-M this works in **Scala 3**.

Context of this bug in [SO](https://stackoverflow.com/questions/65993117/qualified-imports-if-possible-with-aliasing).

**Comment by dwijnand** [comment]
> Also, according to @Jasper-M this works in **Scala 3**.

"this" being `import _root_.{test => t}` works in Dotty.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/9125
