### ISSUE TITLE
automatic eta-expansion should work for SAM expected type and function with single empty parameter clauses (2.13) 

### ISSUE THREAD

**Issue by unkarjedy** [scala/bug#12335]
## reproduction steps

using Scala (2.13.4 (or 2.12.13),

### Example
```scala
scala.util.Properties.versionString

abstract class Sam00 { def foo(): Int }
abstract class Sam1 { def foo(s: String): Int }

def foo00(): Int = 1
def foo1(s: String): Int = 1
val a: Sam00     = foo00
val a: () => Int = foo00

val a: Sam1          = foo1
val a: String => Int = foo1
```

### Problem
I would expect automatic eta-expansion work the same way for SAM expected type and Function expected type for functions with empty parameters.
This is also taking into account that it works OK for functions with non-empty parameters.

![image](https://user-images.githubusercontent.com/3989292/107499820-7c5aca00-6ba6-11eb-9ef6-92910058c0b3.png)

**Comment by som-snytt** [comment]
This behavior is as intended for 2.13, but was to be relaxed for 2.14 [sic]

https://github.com/scala/scala/commit/45201171aef3b33fb49955ef94ee085a275ecdbb

> it could be an accidental SAM

Why isn't "accidental SAM" a meme?

**Comment by SethTisue** [comment]
![pancho096](https://user-images.githubusercontent.com/161079/107574148-35b7a080-6ba3-11eb-9a34-df2760b920f7.jpg)

**Comment by dwijnand** [comment]
This is in line with Scala 3, where these are also type mismatch errors.

**Comment by unkarjedy** [comment]
Ok, will try it this way :D
https://github.com/lampepfl/dotty/issues/11414
