### ISSUE TITLE
eta-expansion with SAM expected type with empty parameters (Runnable) doesn't work for some functions

### ISSUE THREAD

**Issue by unkarjedy** [scala/bug#12334]
## reproduction steps

using Scala (2.12.13 and 2.11.12+experimental flag),

```scala
scala.util.Properties.versionString

def f1: () => Unit = () => println()
def f2(): () => Unit = () => println()
def f3: Unit = println()
def f4(): Unit = println()
def f5(): Unit = println()

f1 _
f2 _
f3 _
f4 _
f5 _

val a1: Runnable = f1
val a2: Runnable = f2
val a3: Runnable = f3
val a4: Runnable = f4
val a5: Runnable = f5

val b1: Runnable = f1 _
val b2: Runnable = f2 _
val b3: Runnable = f3 _
val b4: Runnable = f4 _
val b5: Runnable = f5 _
```

#### 2.11.12 (experimental):
1. type of `f1 _` and `f2 _` is `() => () => Unit`.
`f1 _` is eta-expanded to Runnable but `f2 _` is not
2. type of `f4 _` and `f5 _` is `() => Unit`, 
 but still it can't eta-expand `() => Unit` to Runnable
![image](https://user-images.githubusercontent.com/3989292/107366406-2d9e2900-6aef-11eb-9c22-16a85f0e0b2f.png)

#### 2.12.13
~ the same as 1. for 2.11
but for `f4 _` and `f5 _` the error messages writes that found type `Unit`, not `() => Unit`
![image](https://user-images.githubusercontent.com/3989292/107366652-72c25b00-6aef-11eb-9141-a60d5fd7f154.png)

#### 2.13.4 
Everything works fine
![image](https://user-images.githubusercontent.com/3989292/107366729-840b6780-6aef-11eb-997c-4bc9e3674467.png)

**Comment by unkarjedy** [comment]
for scala 2.11 might be related https://github.com/scala/bug/issues/12334

**Comment by SethTisue** [comment]
closing since “everything works fine” in 2.13.4
