### ISSUE TITLE
2.11 (experimental): explicit eta-expansion with Java SAM expected type produces error, while automatic eta-expansion works 

### ISSUE THREAD

**Issue by unkarjedy** [scala/bug#12333]
## reproduction steps

using Scala 2.11.12 with `-Xexperimental` flag

```scala
def f(x: Int): Unit = println()
val autoEtaJava     : java.util.function.Function[Int, Unit] = f
val explicitEtaJava : java.util.function.Function[Int, Unit] = f _
val autoEtaScala    : Function[Int, Unit] = f
val explicitEtaScala: Function[Int, Unit] = f _
```

## problem
Auto eta-expansion works fine at line `val autoEtaJava     : java.util.function.Function[Int, Unit] = f`
I would expect explicit eta-expansion also work for Java expected SAM as it works for Scala expected SAM.

![image](https://user-images.githubusercontent.com/3989292/107344222-4567b400-6ad3-11eb-8172-8670f2b5c4a3.png)

**Comment by unkarjedy** [comment]
The original example I played around with:
```scala
def f0 = (x: Int) => println()
def f1: Int => Unit = (x) => println()
def f2(): Int => Unit = (x) => println()
def f3(x: Int) = println()
def f4(x: Int): Unit = println()

type JF[A, B] = java.util.function.Function[A, B]
val a1: JF[Int, Unit] = f0
val a1: JF[Int, Unit] = f1
val a2: JF[Int, Unit] = f2
val a3: JF[Int, Unit] = f3
val a4: JF[Int, Unit] = f4

val b1: JF[Int, Unit] = f0 _
val b1: JF[Int, Unit] = f1 _
val b2: JF[Int, Unit] = f2 _
val b3: JF[Int, Unit] = f3 _
val b4: JF[Int, Unit] = f4 _

val c1: Function[Int, Unit] = f0
val c1: Function[Int, Unit] = f1
val c2: Function[Int, Unit] = f2
val c3: Function[Int, Unit] = f3
val c4: Function[Int, Unit] = f4

val d1: Function[Int, Unit] = f0 _
val d1: Function[Int, Unit] = f1 _
val d2: Function[Int, Unit] = f2 _
val d3: Function[Int, Unit] = f3 _
val d4: Function[Int, Unit] = f4 _
```

![image](https://user-images.githubusercontent.com/3989292/107344584-ac856880-6ad3-11eb-91ca-f5ad27d754c1.png)

**Comment by SethTisue** [comment]
is the problem reproducible on Scala 2.13.4?

**Comment by unkarjedy** [comment]
Nope, it's a problem of 2.11 only, 2.12.13, 2.13.4 works fine

**Comment by SethTisue** [comment]
Okay. We don't mind such reports (since someone may find them useful as documentation, and the tickets can be used to discuss workarounds), but we don't leave them open, either.

**Comment by unkarjedy** [comment]
Just for the record, explicit eta-expansion also doesn't work in 2.12.13 when trying eta-expand method with single empty parameters clause (see `val a: C0 = foo00 _`) to Scala SAM class.
(works fin in 2.13.4)
```scala
abstract class C0 {
  def foo(): Long
}
abstract class C1  {
  def foo(s: String): Long
}

def foo0: Int = 1
def foo00(): Int = 1
def foo1(s: String): Int = 1

val a: C0 = foo0
val a: C0 = foo0 _

val a: C0 = foo00
val a: C0 = foo00 _

val a: C1 = foo1
val a: C1 = foo1 _

val a: () => Long = foo0
val a: () => Long = foo0 _
val a: () => Long = foo00
val a: () => Long = foo00 _
```

#### 2.12.13
![image](https://user-images.githubusercontent.com/3989292/107498068-5f24fc00-6ba4-11eb-82f0-579eccbf43ad.png)

#### 2.13.4
![image](https://user-images.githubusercontent.com/3989292/107498592-0e61d300-6ba5-11eb-9454-c4c634599b4e.png)
