### ISSUE TITLE
Can't invoke `VarHandle.setVolatile` from Scala

### ISSUE THREAD

**Issue by szegedi** [scala/bug#12348]
## reproduction steps

using Scala 2.13.3 on Java 11.0.10,

```scala
scala> val a = new Array[Object](1)
val a: Array[Object] = Array(null)

scala> val h = java.lang.invoke.MethodHandles.arrayElementVarHandle(a.getClass)
val h: java.lang.invoke.VarHandle = java.lang.invoke.VarHandleObjects$Array@47148f3f

scala> h.setVolatile(a, 0, "foo")
java.lang.NoSuchMethodError: VarHandle.setVolatile(Object[],int,String)Object
  at java.base/java.lang.invoke.MethodHandleNatives.newNoSuchMethodErrorOnVarHandle(MethodHandleNatives.java:576)
  at java.base/java.lang.invoke.MethodHandleNatives.varHandleOperationLinkerMethod(MethodHandleNatives.java:529)
  at java.base/java.lang.invoke.MethodHandleNatives.linkMethodImpl(MethodHandleNatives.java:462)
  at java.base/java.lang.invoke.MethodHandleNatives.linkMethod(MethodHandleNatives.java:450)
  ... 32 elided
```

## problem

I would expect this to succeed without the exception. 

If the code containing these steps is compiled with scalac , it can be seen that it emits the call to `setVolatile` with wrong return type `Object` instead of `void`:
```
invokevirtual java/lang/invoke/VarHandle.setVolatile:([Ljava/lang/Object;ILjava/lang/String;)Ljava/lang/Object;
pop
 ```

Since `VarHandle.setVolatile` is declared to return `void`, scalac is emitting wrong return type, it should emit `void`:
```
invokevirtual java/lang/invoke/VarHandle.setVolatile:([Ljava/lang/Object;ILjava/lang/String;)V
 ```

**Comment by szegedi** [comment]
I found a workaround: defining the `setVolatile` call in a `def` of its own explicitly declared to return `Unit` gets the compiler to do the right thing, so this works:
```scala
val a = new Array[Object](1)
val h = java.lang.invoke.MethodHandles.arrayElementVarHandle(a.getClass)
def sv: Unit = h.setVolatile(a, 0, "foo")
sv
```
Doesn't make the bug invalid though. I suspect there's a general issue with how calls to signature-polymorphic methods are compiled.

**Comment by JornVernee** [comment]
Relevant JLS: https://docs.oracle.com/javase/specs/jls/se11/html/jls-15.html#jls-15.12.3-400-B

```
The compile-time parameter types and compile-time result are determined as follows:
    ...
    If the compile-time declaration for the method invocation is a signature polymorphic method, then:
        ...
        The compile-time result is determined as follows:

            If the signature polymorphic method is either void or has a return type other than Object, the compile-time result is the result of the invocation type of the compile-time declaration (§15.12.2.6).
            ...
```

**Comment by Jasper-M** [comment]
The behavior does seem to be in line with the Scala spec: https://www.scala-lang.org/files/archive/spec/2.13/06-expressions.html#signature-polymorphic-methods 
Those extra rules seem to be specific for Java 9 and up, which probably explains why Scala is not 100% up to date here.

Looks like the compiler was [updated](https://github.com/scala/scala/commit/1ff714b83795bff6604ef39604511ed896a49eea) to recognize `VarHandle` signature polymorphic methods, but not [everywhere](https://github.com/scala/scala/blob/ce93562218f4148ba749940924dc2650aca6cf9f/src/compiler/scala/tools/nsc/backend/jvm/opt/ByteCodeRepository.scala#L167) and not with the new typing rules.

**Comment by lrytz** [comment]
The spec has changed, it used to be

>  The compile-time result is determined as follows:
>     If the method invocation expression is an expression statement, the compile-time result is void.

now it's

>  The compile-time result is determined as follows:
>     If the signature polymorphic method is either void or has a return type other than Object, the compile-time result is the result of the invocation type of the compile-time declaration (§15.12.2.6).
>     Otherwise, if the method invocation expression is an expression statement, the compile-time result is void.

something like this should work:

https://github.com/scala/scala/compare/2.13.x...lrytz:t12348 

@Jasper-M you're right that the code in the backend is way out of date, I need to look at that as well.
