### ISSUE TITLE
TypeTag implicit incorrectly marked as unused

### ISSUE THREAD

**Issue by koterpillar** [scala/bug#12356]
## reproduction steps

using Scala 2.13.5 with `-Wunused`:

```scala
import scala.reflect.runtime.universe._

object foo {
  case class Wrap[A](value: A)

  def withTag[A: TypeTag]: Unit = ()

  // new in 2.13.5, incorrect:
  // warning: parameter value evidence$2 in method withTagWrap1 is never used
  def withTagWrap1[A: TypeTag]: Unit = withTag[Wrap[A]]

  // this is expected:
  // error: No TypeTag available for blah.foo.Wrap[A]
  def withTagWrap2[A]: Unit = withTag[Wrap[A]]
}
```

## problem

The `TypeTag[A]` context bound in `withTagWrap1` is used (to derive `TypeTag[Wrap[A]]`) and should not be reported as unused.

The same code works in Scala 2.13.4.

Possibly related to https://github.com/scala/scala/pull/9346.

**Comment by som-snytt** [comment]
It won't warn with `-Wmacros:after`. Use `-Xprint:typer` to see the expansion.

Use `-Vmacro-lite` to see
```
performing macro expansion scala.reflect.api.`package`.materializeTypeTag[foo.Wrap[A]]
```

It's possible to disable `-Wunused:-synthetics` or use `-Xlint:unused` for less fuss, or use `-Wconf` to limit warnings.

Thanks for the report. Probably at this point, the interaction with macros will not be further improved.

**Comment by NthPortal** [comment]
@som-snytt why would it have to do with `-Wmacros:after`? there are no macros here

**Comment by Jasper-M** [comment]
@NthPortal There's an implicit `TypeTag[A]` in scope, but a (intrinsic) macro is required to generate the `TypeTag[Wrap[A]]`.
