### ISSUE TITLE
2.13.5 reports false positive unused evidence for some implicits

### ISSUE THREAD

**Issue by arixmkii** [scala/bug#12355]
## reproduction steps

Example in scastie - compilation will fail (because fatal warnings are on)
https://scastie.scala-lang.org/xzO1YZ7yR5OSmE1uyMzrrw

using Scala 2.13.5,

```scala
import pureconfig.ConfigReader
import pureconfig.generic.semiauto._

final case class SomeConfig[C](optVal: Option[C])

implicit def configReader[C : ConfigReader] = deriveReader[SomeConfig[C]] // this will fail to compile
```

## problem

The code compiled just fine with 2.13.4 and it is impossible to compile this with fatal warnings enabled w/o adding `@nowarn` annotation, what in turn causes issues for 2.12 series cross-compilation, because it reports warning that the annotation suppresses nothing.

**Comment by som-snytt** [comment]
Probably try `-Wmacros:after` to check only after macros are expanded.

**Comment by arixmkii** [comment]
It helped for 2.13.5! Was not aware of this option and it seems that the name changed between 2.12 and 2.13 series. Will do the reading.
@som-snytt Thank you a lot! I guess this ticket can be safely closed now. Should I close it myself or would maintainers do the honors?
