### ISSUE TITLE
"LocalVariableTable" attribute generation inconsistency

### ISSUE THREAD

**Issue by Maccimo** [scala/bug#12362]
## reproduction steps

Consider following example:

```scala
class TestScala {

	def foo(value: String) = {
		bar(value);
	}

	def bar(value: String) = {
		println(value);
	}

}

object TestScala {

	def baz(value: String) = {
		xyz(value);
	}

	def xyz(value: String) = {
		println(value);
	}

}
```

Scalac version: `Scala compiler version 2.13.5 -- Copyright 2002-2020, LAMP/EPFL and Lightbend, Inc.`

## problem

Class file produced by scalac will contain both `MethodParameters` and `LocalVariableTable` attributes for methods `foo()` and `bar()` but only `MethodParameters` attribute for methods `baz()` and `xyz()`.

In contrast, functionally equal class written in Java and compiled with `javac -g -parameters` will contain both `MethodParameters` and `LocalVariableTable` attributes for all four methods. Tested with javac from Oracle JDK 8 and Open JDK 17.

```java
public class TestJava {

	public void foo(String value) {
		bar(value);
	}

	public void bar(String value) {
		System.out.println(value);
	}

	public static void baz(String value) {
		xyz(value);
	}

	public static void xyz(String value) {
		System.out.println(value);
	}

}
```

**Comment by lrytz** [comment]
The static methods `baz` and `xyz` in `TestScala.class` are compiler-generated forwarders for Java interopability. The actual implementations of `baz` and `xyz` are in the "module class" `TestScala$.class`, and these have the `MethodParameters` and `LocalVariableTable` attributes.

Since the static forwarders don't have any local variables besides the parameters, the local variable table would not add any information. But maybe it's useful for some tools - how did you end up looking at this?

I think a patch would be accepted, probably here: https://github.com/scala/scala/blob/8a2cf63ee5bad8c8c054f76464de0e10226516a0/src/compiler/scala/tools/nsc/backend/jvm/BCodeHelpers.scala#L791 (`mirrorMethod.visitLocalVariable`)

**Comment by Maccimo** [comment]
How I discovered this:

IntelliJ IDEA has a nice feature: While debugging application they can decompile class if there is either no available sources or no debug information in the class (`-g:none` compiler switch) and let you step through code and examine variables values. This is useful in some cases.

This feature works pretty well for java code but not good enough with classes produced with Scala. Absence of "LocalVariableTable" impact both decompiler and variables list in the debugger.

Here is how it looks like during debug session:

![image](https://user-images.githubusercontent.com/1935894/111809480-14567c80-88e6-11eb-97ab-9c607f0db472.png)

This, of course, can be addressed with patches in IDEA's debugger and decompiler but other IDEs can rely on same assumptions too.

<hr>

I do a quick check how javac act in similar cases and here is the results:

## Covariant return type:

```java
public class Base {

	public Object doSomething(String value) {
		return value;
	}

}
```

```java
public class Descendant extends Base {

	@Override
	public String doSomething(String value) {
		return value;
	}

}
```

Bridge method contains both `LocalVariableTable` and `MethodParameters`:

```java
  public java.lang.Object doSomething(java.lang.String);
    descriptor: (Ljava/lang/String;)Ljava/lang/Object;
    flags: (0x1041) ACC_PUBLIC, ACC_BRIDGE, ACC_SYNTHETIC
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: aload_1
         2: invokevirtual #2                  // Method doSomething:(Ljava/lang/String;)Ljava/lang/String;
         5: areturn
      LineNumberTable:
        line 1: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       6     0  this   LDescendant;
    MethodParameters:
      Name                           Flags
      value                          synthetic
```

## Call to private method from inner class:

```java
public class Outer {

	private void foo(String value) {
		System.out.println(value);
	}

	public class Inner {

		public void bar(String value) {
			foo(value);
		}

	}

}
```

Accessor method has no `MethodParameters` attribute, but still contains `LocalVariableTable` attribute:

```java
  static void access$000(Outer, java.lang.String);
    descriptor: (LOuter;Ljava/lang/String;)V
    flags: (0x1008) ACC_STATIC, ACC_SYNTHETIC
    Code:
      stack=2, locals=2, args_size=2
         0: aload_0
         1: aload_1
         2: invokespecial #1                  // Method foo:(Ljava/lang/String;)V
         5: return
      LineNumberTable:
        line 1: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       6     0    x0   LOuter;
            0       6     1    x1   Ljava/lang/String;
```

**Comment by jxnu-liguobin** [comment]
> Since the static forwarders don't have any local variables besides the parameters, the local variable table would not add any information. But maybe it's useful for some tools - how did you end up looking at this?

Since the generated forwarding method does not have any local variables, then `LocalVariableTable` is empty?
I don't quite understand that, Can you explain? thanks.

**Comment by lrytz** [comment]
Parameters (including `this` for instance methods) are also local variables; https://docs.oracle.com/javase/specs/jvms/se16/html/jvms-2.html#jvms-2.6.1

**Comment by jxnu-liguobin** [comment]
The calculation of `Label` seems to be in its subclass` BCodeSkelBuilder# locals`? It's not clear how to calculate this in the parent class`BCodeHelpers`. I need to extract it upward or maybe have a simpler method?
