### ISSUE TITLE
Unicode character displays as '?' in 2.13.5 REPL

### ISSUE THREAD

**Issue by jonathon-bell** [scala/bug#12360]
## reproduction steps

using Scala 2.13.5,

```scala
scala> "φ"
val res0: String = ?
```

## problem
This appears to be a regression from recent versions: 

using either Scala 2.13.3 or 2.13.4:

```scala
scala> "φ"
val res0: String = φ
```

**Comment by SethTisue** [comment]
fixed by https://github.com/scala/scala/pull/9537

**Comment by jonathon-bell** [comment]
Thanks!
