### ISSUE TITLE
scala3 integration: illegal cyclic inheritance involving object

### ISSUE THREAD

**Issue by eodlgim** [scala/bug#12369]
## reproduction steps

using Scala (2.13.5+, 3.0.0-x),

Test.scala
```scala
package test

sealed trait A

object A {
  sealed trait B
  case object First extends A with B
  case object Second extends A with B
}
```

Main.scala

```scala
import test.A

object Main extends App {
}
```

build.sbt
```scala
lazy val root = project.in(file(".")).aggregate(project3, project213)

lazy val project3 = project.in(file("pr3")).settings(Seq(scalaVersion := "3.0.0-RC1"))

lazy val project213 = project.in(file("pr213")).dependsOn(project3).settings(Seq(
  resolvers += "scala-integration" at "https://scala-ci.typesafe.com/artifactory/scala-integration/",
  scalaVersion := "2.13.6-bin-fd69ef8",
  scalacOptions ++= (if (isDotty.value) Seq.empty else Seq("-Ytasty-reader"))
))
```

## problem

Doesn't compile when module with version 2.13x depends on module with 3.0.0x, but compiles when both modules have are the same versions.

**Comment by SethTisue** [comment]
@bishabosha bat signal

**Comment by bishabosha** [comment]
on first look this appears to be due to forcing annotations early on top level symbol `A` to look for sealed children

**Comment by SethTisue** [comment]
@bishabosha should we milestone this 2.13.7, or Backlog? (do you intend to return to it sometime soon-ish?)

also I'm wondering why you mention annotations — how are annotations in play here?

**Comment by dwijnand** [comment]
Using sealed traits in Scala 3 is probably quite unusual with `enum` available, as is having a second sealed parent.  But outside of that it's fairly vanilla and a shame that this doesn't work.

**Comment by bishabosha** [comment]
> @bishabosha should we milestone this 2.13.7, or Backlog? (do you intend to return to it sometime soon-ish?)
> 
> also I'm wondering why you mention annotations — how are annotations in play here?

I should work on this in the next week.

The comment I made about annotations is that TASTy encodes the sealed children of a class by attaching `scala.annotation.internal.Child[Foo]` annotations which reference the child. The issue is how to discover all the children so that pattern match exhaustivity checking is correct, but without forcing too much and making the cycle observed here.
