### ISSUE TITLE
Function overloading with inheritance gives ambiguous reference error

### ISSUE THREAD

**Issue by gagandeepkalra** [scala/bug#12368]
## reproduction steps

using Scala (2.12.13, 2.13.5, 3.0.0-RC2),

```scala
  trait First
  object First extends First

  trait Second extends First
  object Second extends Second

  // case 1: this works 
  trait A {
    def abc(i: Second): Second = {
      println("inside Second")
      i
    }

    def abc(i: First): First = {
      println("inside First")
      i
    }
  }

  trait Z extends A {
  }
  // end

  // case 2: this doesn't
  trait A {
    def abc(i: Second): Second = {
      println("inside Second")
      i
    }
  }

  trait Z extends A {
    def abc(i: First): First = {
      println("inside First")
      i
    }
  }
  // end

  // case 3: but this works
  trait A {
    def abc(i: First): First = {
      println("inside First")
      i
    }
  }

  trait Z extends A {
    def abc(i: Second): Second = {
      println("inside Second")
      i
    }
  }
  // end

  def main(args: Array[String]): Unit = {
    val z = new Z {}

    println(z.abc(First))
    println(z.abc(Second)) // case 2: ambiguity error here
  }
```

## problem

Function overloading works with inheritance relationship but it won't work with trait mixin, only when the mixin version has the subclass overload. 

The fact that case 3 works, not sure if case 2 is a bug or case 3 or neither?

My guess is it's related to mixin order, but I still couldn't find specification for this behaviour. 

Error:
ambiguous reference to overloaded definition,
[error] both method abc in trait Z of type (i: Temp.First)Temp.First
[error] and  method abc in trait A of type (i: Temp.Second)Temp.Second
[error] match argument types (Temp.Second.type) and expected result type Any
[error]     println(z.abc(Second))

**Comment by som-snytt** [comment]
This is [as specified](https://scala-lang.org/files/archive/spec/2.13/06-expressions.html#overloading-resolution), see the definition of "relative weight", where the choice of overload depends on both the signature and where it is defined.

If the method that is not selected in case 1 is moved to the subclass, its "score" is bumped up, as in case 2, and it becomes ambiguous.

I didn't understand these words: "Function overloading works with inheritance relationship but it won't work with trait mixin, only when the mixin version has the subclass overload." But let's not mince words.

You might want to ask on gitter or the users forum.

**Comment by gagandeepkalra** [comment]
> This is [as specified](https://scala-lang.org/files/archive/spec/2.13/06-expressions.html#overloading-resolution), see the definition of "relative weight", where the choice of overload depends on both the signature and where it is defined.
> 
> If the method that is not selected in case 1 is moved to the subclass, its "score" is bumped up, as in case 2, and it becomes ambiguous.
> 

This makes sense, I understand the spec now. Thankyou.
