### ISSUE TITLE
bintray.com going away

### ISSUE THREAD

**Issue by MikeEngUSA** [scala/bug#12372]
Apologies for raising this as a bug here; however, since both `https://repo.typesafe.com/` and `https://repo.scala-sbt.org/` (and possibly others) redirect to `https://dl.bintray.com/`, I'm hoping that someone _Scala_-related can address this...

It seems that _JFrog_ are closing down their `dl.bintray.com` facility, according to this _[blog post](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter)_ as of May 1st this year.

To remind everyone that they are doing this, they've [scheduled a _brown-out_ of their repository services](https://status.bintray.com) today (April 12th), from 6 am - 2 pm PT.

As a consequence, if you don't have a particular cached artifact, none of your _SBT_ builds can succeed at the current time.

Is anyone else aware of this? Are there plans to move to other repositories before May 1st?

**Comment by SethTisue** [comment]
see https://github.com/sbt/sbt/issues/6294

note that there will be a second brownout April 26

**Comment by MikeEngUSA** [comment]
@SethTisue Thanks for the update. I missed that one... Is there any open issue that you're aware of for changes to the _Lightbend_ / _Typesafe_ repo?

**Comment by SethTisue** [comment]
> Is there any open issue that you're aware of for changes to the Lightbend / Typesafe repo

just as the Scala Center is in the process of securing new hosting for repo.scala-sbt.org, Lightbend IT is in the process of securing new hosting for repo.lightbend.com and repo.typesafe.com; they expect to be done before May 1 (perhaps before April 26? I don't know), and those resolvers will continue functioning for users as before, via updated redirects

(and if your employer is a Lightbend customer, please don't hesitate to open a support case with any questions or concerns)
