### ISSUE TITLE
Opaque type from Scala 3 module  is missing from the classpath in test scope of dependent scala 2 module

### ISSUE THREAD

**Issue by jyuricle** [scala/bug#12399]
I'm migrating the multimodule project to Scala 3. I started with the shared module, the 2 others modules depend on it. Everything works fine, but when I run tests on one of 2.13 modules, I get an error about opaque type missing in classpath.

## reproduction steps
using Scala (2.13.6 & 3.0.0)

The example to reproduce the error: (here 2.13.6 module `a` depends on 3.0.0 module `common`):

`build.sbt`:
```scala
lazy val root = (project in file("."))
  .aggregate(a, common)

lazy val common = project.in(file("common"))
  .settings(scalaVersion := "3.0.0")

lazy val a = project.in(file("a"))
  .dependsOn(common)
  .settings(scalaVersion := "2.13.6")
  .settings(scalacOptions += "-Ytasty-reader")
  .settings(libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.9")

```

Module `common` contains one single package object:
```scala
package object example {
  opaque type Offset = Long
  object Offset:
    def apply(o: Long): Offset = o
}

```

Module `a` contains one single file:
```scala
package a

import example.Offset

final case class A(off: Offset)

object Main extends App {
  println("Running in Scala 2: " + A(Offset(10)))
}
```

The actual test in module `a`:
```scala
package example

import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec
import example.Offset
import a.A

class Test1 extends AnyWordSpec with Matchers {

  "test1" should {

    "test scala 3" when {

      "using it inside scala 2" in {
        A(Offset(10)) shouldBe A(Offset(10))
      }
    }
  }
}

```

When running `Test / compile` I get the following error: 
```
[error] /Users/yurii.krat/test/scala3/a/src/test/scala/example/Test1.scala:15:9: Symbol 'type example.package.Offset' is missing from the classpath.
[error] This symbol is required by 'object a.A'.
[error] Make sure that type Offset is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'A.class' was compiled against an incompatible version of example.package.
[error]         A(Offset(10)) shouldBe A(Offset(10))
[error]         ^
[error] one error found
[error] (a / Test / compileIncremental) Compilation failed

```

## problem
I'm wondering why in everything is fine when running the actual code, but compile error in `Test` scope. 

Btw, wrapping opaque type in usual plain object instead of package object fixes the issue.

**Comment by dwijnand** [comment]
@bishabosha this might end up being a zinc bug, but could you do a first pass to see if there's something on the tasty reader side, please?

**Comment by bishabosha** [comment]
If I define `Offset` in an object nested within the package object then it works fine.
```scala
```

If I run with `-Ydebug-tasty` it seems if `Offset` is defined in a package object then the package object is discovered in namer, but 
so it seems package objects should be forced earlier?

**Comment by bishabosha** [comment]
If I define `Offset` in an object nested within the package object then there is no error:
```scala
package example {
  object Defs {
    opaque type Offset = Long
    object Offset:
      def apply(o: Long): Offset = o
  }
}
```

If I run with `-Ydebug-tasty` it seems that with the original code, `package object example` is unpickled from TASTy in namer (and its definitions are not forced, and so `Offset` is forced in typer), but with the rewrite above everything is unpickled in typer.

So it seems package object definitions should be forced as soon as they are unpickled?

**Comment by dwijnand** [comment]
Actually looking at it again, "symbol not found" and package objects makes me think this is whatever #10306 / https://github.com/sbt/sbt/issues/3187 / https://github.com/sbt/zinc/issues/690 is...
