### ISSUE TITLE
Missing `type test cannot be checked at runtime` warning

### ISSUE THREAD

**Issue by japgolly** [scala/bug#12408]
## reproduction steps

using Scala 2.13.6

```scala
sealed trait Action[Page]
case class Renderer[Page, Props]() extends Action[Page]
sealed trait Redirect[Page] extends Action[Page]

final class RouterLogic[Page, Props] {

  def hmm1(a: Action[Page]): Int =
    a match {
      case r: Renderer[Page, Props] => 1
      case _                        => 2
    }

  def hmm2(a: Action[Page]): Int =
    a match {
      case r: Redirect[Page] => 2
      case _                 => 1
    }
}
```

## problem

Expected warning:

```
[warn] 9 |      case r: Renderer[Page, Props] => 1
[warn]   |           ^^^^^^^^^^^^^^^^^^^^^^^^
[warn]   |      the type test for Renderer[Page, Props] cannot be checked at runtime
[warn] one warning found
```

The above warning is correctly emitted in Scala 3.

https://github.com/lampepfl/dotty/issues/12691

**Comment by lrytz** [comment]
👍  the collections implementation has a lot of this, check for "cannot be checked at runtime" in a recent build log: https://travis-ci.com/github/scala/scala/jobs/510365011

**Comment by SethTisue** [comment]
minimized:

```
class Renderer[T]
class Test[T](a: Any) {
  a match {
    case r: Renderer[T] => ; case _ =>
  }
}
```

note that `T` must be a type parameter on the enclosing class; the warning is emitted if the type parameter is on an enclosing method

**Comment by SethTisue** [comment]
Would a volunteer like to look into this? The minimization is pretty simple, it isn't super-obscure.

**Comment by SethTisue** [comment]
> the collections implementation has a lot of this

that would also be great for a volunteer to investigate; I opened scala/scala-dev#775 on it

**Comment by som-snytt** [comment]
In fact, I was taking a look because I was interested in learning about Checkable with its copious commentary. I wonder if I will make progress.

**Comment by jxnu-liguobin** [comment]
Hi, Where should I start?  

> minimizing further, we get:
> 
> ```scala
> class Renderer[T]
> class Test[T](a: Any) {
>   a match {
>     case r: Renderer[T] =>
>   }
> }
> ```
> 
> note that `T` must be a type parameter on the enclosing class; the warning is emitted if the type parameter is on an enclosing method

Besides, I don't understand what this minimum means?

**Comment by som-snytt** [comment]
@jxnu-liguobin there is a pr someone will walk it over the goal line or push the putt into the cup whatever the sport metaphor.

It is indeed hard to start if you don't get the minimal example.

**Comment by som-snytt** [comment]
That was just a month ago but feels like something that began before the great pandemic.
