### ISSUE TITLE
Cannot inherit java interface that covariantly overrides a method with Array return type

### ISSUE THREAD

**Issue by SrTobi** [scala/bug#12407]
## reproduction steps

using Scala 2.13.6,

Java:
```java
public interface A {
    A[] getArray();
}

public interface B extends A {
    @Override
    B[] getArray();
}
```

Scala:
```scala
trait Test extends B
```

## problem

When compiling the scala code the compiler gives:
```
incompatible type in overriding
def getArray(): Array[A] (defined in trait A)
  with def getArray(): Array[B] (defined in trait B);
 found   : (): Array[B]
 required: (): Array[A]
trait Test extends B
```

This makes it impossible to inherit `B`.

**Comment by joroKr21** [comment]
Hmm an interesting philosophical question is whether we should support bug compatibility with Java

**Comment by SrTobi** [comment]
Well, this basically stops us from upgrading our application to `Scala 2.13.6`. A type system should help you avoid bugs, and not prevent you from developing your application altogether (because we cannot change those interfaces and we cannot avoid them either).

**Comment by joroKr21** [comment]
> Well, this basically stops us from upgrading our application to Scala 2.13.6

Do you mean that it's a regression (it worked before)?

**Comment by lrytz** [comment]
I'll take a look, this is quite certainly related to https://github.com/scala/scala/pull/9629

**Comment by SrTobi** [comment]
> > Well, this basically stops us from upgrading our application to Scala 2.13.6
> 
> Do you mean that it's a regression (it worked before)?

yeah it works in `2.13.5`
