### ISSUE TITLE
productElementName includes extra names

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12402]
## reproduction steps

using Scala 2 with its built-in versioned prompt,

```scala
scala 2.13.6> case class C[A: Ordering](a: A)
class C

scala 2.13.6> C(42)
val res1: C[Int] = C(42)

scala 2.13.6> C(42).productArity
val res4: Int = 1

scala 2.13.6> C(42).productElementNames
val res8: Iterator[String] = <iterator>

scala 2.13.6> .toList
val res9: List[String] = List(a)

scala 2.13.6> C(42).productElementName
override def productElementName(x$1: Int): String
scala 2.13.6> C(42).productElementName(0)
val res11: String = a

scala 2.13.6> C(42).productElementName(1)
val res12: String = evidence$1
```

## problem

The case class should not report a name for non-product element members.

**Comment by VladKopanev** [comment]
Hi! I would like to contribute the fix for that. Could you please give me a clue where I need to put my tests? Also, I would like to know if there is a test code that I can use as a base for this issue and how do I run tests against the new version?

**Comment by som-snytt** [comment]
@VladKopanev That would be great. There is a [nearby PR](https://github.com/scala/scala/pull/8885/files) which also touches SyntheticMethods. The test would be a new test in `test/files/run`. It could be just an App that prints the method result or uses regular `assert`. In `sbt`, `partest run/mytest` compiles and runs it. The project readme describes it a bit.
