### ISSUE TITLE
Undocumented ordering change in List.groupBy between 2.12.12 and 2.12.13

### ISSUE THREAD

**Issue by kubukoz** [scala/bug#12410]
## reproduction steps

using Scala 2.12.13 or 2.12.14:

```scala
scala> List(1, 2, 3).groupBy(identity).foreach(println)
(1,List(1))
(2,List(2))
(3,List(3))
```

## problem

In 2.12.12 and below:

```scala
scala> List(1, 2, 3).groupBy(identity).foreach(println)
(2,List(2))
(1,List(1))
(3,List(3))
```

While both results seem correct because maps after `groupBy` are identical (according to `equals`), the change in ordering is visible when you convert back to an ordering-sensitive data structure, such as a list (or if you do `.foreach`). This may break code that relies on the old ordering.

**Comment by SethTisue** [comment]
a next step here might be to bisect the Scala version to see which scala/scala PR is responsible

but also, @scala/collections does this ring a bell for anybody?

**Comment by som-snytt** [comment]
It rang a bell but this wasn't das Ding https://github.com/scala/bug/issues/11276 get it, ding.

**Comment by dwijnand** [comment]
https://github.com/scala/scala/pull/8948? (https://github.com/scala/scala/pull/9376 is also possible, but tiny)

**Comment by som-snytt** [comment]
This is a good one https://github.com/scala/bug/issues/4558 where the problem is
```
scala> Seq(1,2,3).view.groupBy(identity)
java.lang.StackOverflowError
```
and the expectation is
```
scala> Seq(1,2,3).groupBy(identity)
res3: scala.collection.immutable.Map[Int,Seq[Int]] = Map(3 -> List(3), 1 -> List(1), 2 -> List(2))
```

**Comment by retronym** [comment]
This did come up for discussion. We considered adding a backwards compatiblity mode with a system property.

But we considered that that 2.12.12 ordering was not the same as the the input collection (ie, we didn't use a `LinkedHashMap` internally) it seemed like we were within our rights to change the undefined behaviour here to achieve better performance.

**Comment by retronym** [comment]
I have added a compatibility note to the release notes.

```

The internal implementation of `groupBy` has been [optimized](https://github.com/scala/scala/pull/8948) to reduce allocations. This can result in different ordering elements if you iterate the resulting `Map`. The ordering of the returned map is not specified behaviour and should not be relied upon, for ordering sensitive use cases consider building a `LinkedHashMap` or `TreeMap` instead.
```

**Comment by dwijnand** [comment]
Obligatory https://xkcd.com/1172/
