### ISSUE TITLE
Fruitless type test warning in incremental build but not in clean build

### ISSUE THREAD

**Issue by danarmak** [scala/bug#12414]
## reproduction steps

Using either Scala 2.12.14 or 2.13.6, and two source files:

```
Classes.scala
===========
package testwarning

sealed trait Trait1
sealed trait Trait2

class Class1 extends Trait1
// No class extends Trait1 with Trait2

Tester.scala
=========
package testwarning

object Tester {
  def test(x: Trait1): String = x match {
    case y: Trait2 => "Also Trait2"
    case _ => "Only Trait1"
  }
}
```

I expect to get the warning: 
```
[warn] /home/danarmak/test/scala-testwarning-repro/src/main/scala/testwarning/Tester.scala:6:13: fruitless type test: a value of type testwarning.Trait1 cannot also be a testwarning.Trait2
[warn]     case y: Trait2 => "Also Trait2"
[warn]             ^
```

Running `sbt clean compile` produces no warning. But if I then change `Tester.scala` (e.g. add some whitespace) and run `sbt compile` (incrementally), I get the warning. I believe the same happens with the warning "match may not be exhaustive".

Because the reproduction requires two source files, I also uploaded it [here](https://github.com/danarmak/scala-testwarning-repro) with the necessary sbt project.

## problem

Incremental compilation and clean / full compilation should produce the same result. And if they don't, then a clean build should be the 'correct' one. 

This is interfering with fatal-warnings on my CI, because the CI's clean build doesn't catch the actual warnings. This has also caused a `@nowarn annotation does not suppress any warnings` error on the CI.

**Comment by eed3si9n** [comment]
Thanks for the report!

To supplement this, I don't think this is an incremental compilation (as in Zinc) per se, but a separate compilation, which is scalac's ability to compile `Tester.scala` together with precompiled `*.class` or `*.jar` files:

```
$ mkdir classes
$ scalac Classes.scala -d classes
$ ls classes/testwarning
Class1.class  Trait1.class  Trait2.class
$ scalac Tester.scala -cp classes
Tester.scala:5: warning: fruitless type test: a value of type testwarning.Trait1 cannot also be a testwarning.Trait2
    case y: Trait2 => "Also Trait2"
            ^
one warning found
```

What this indicates is that the type (or some other) information pickled into `Trait2.class` file has the correct information, but it's confused when `*.scala` is compiled directly.

**Comment by som-snytt** [comment]
There is a todo comment
```
     *  TODO: the last two conditions of the last possibility (that the symbols are not of
     *  classes being compiled in the current run) are because this currently runs too early,
     *  and .children returns Nil for sealed classes because their children will not be
     *  populated until typer.  It was too difficult to move things around for the moment,
     *  so I will consult with moors about the optimal time to be doing this.
```
It may be past the optimal time to consult with moors.

**Comment by eed3si9n** [comment]
@som-snytt I was gonna say "Qu'ils mangent de la RefCheck" but clearly your PR is better.

**Comment by som-snytt** [comment]
I took a swing at just pushing the check out to the "extra work units" after typer.

This is after macros expand; I see there is a difference between children and direct known subclasses.

**Comment by som-snytt** [comment]
This is just typer.

**Comment by danarmak** [comment]
Could you please list which warnings are affected by this?

**Comment by som-snytt** [comment]
The linked PR is just for the "fruitless test" at typer in the example.  An "exhaustive" check would be a different issue in patmat.
