### ISSUE TITLE
Overload with varargs behave Inconsistently with Java

### ISSUE THREAD

**Issue by YulawOne** [scala/bug#12429]
## reproduction steps

using Scala 2.13.6, try to compile

#### Java
```java

import java.util.Arrays;

public class Overload {
    static class A {
        public String doSmth(String id) {
            return id;
        }
    }

    static class B extends A {
        public String doSmth(String id, Integer... vararg) {
            return id + Arrays.toString(vararg);
        }
    }

    public static void main(String[] args) {
        var b = new B();
        b.doSmth("a"); // compiles and overload works as expected 
        b.doSmth("b", 1); 
    }
}
```

#### Scala
```scala

object Overload {
  class A {
    def doSmth(id: String): String = id
  }

  class B extends A {
    def doSmth(id: String, vararg: Int*): String = id + vararg.mkString(",")
  }

  def main(args: Array[String]): Unit = {
    val b = new B
    b.doSmth("a")
    b.doSmth("b", 1)
  }
}

// Overload.scala:14:7: ambiguous reference to overloaded definition,
// [error] both method doSmth in class B of type (id: String, vararg: Int*): String
// [error] and  method doSmth in class A of type (id: String): String
// [error] match argument types (String)
// [error]     b.doSmth("a")
// [error]       ^
// [error] one error found
```

## problem

in the line `b.doSmth("a")` an ancestor method should be resolved without issues based on overload priority, similar to Java. However, Scala compiler fails to resolve overload.

## workaround

Add dummy override to B:
```scala
object Overload {
  class A {
    def doSmth(id: String): String = id
  }

  class B extends A {
    override def doSmth(id: String): String = super.doSmth(id) // dummy override
    def doSmth(id: String, vararg: Int*): String = id + vararg.mkString(",")
  }

  def main(args: Array[String]): Unit = {
    val b = new B
    b.doSmth("a")
    b.doSmth("b", 1)
  }
}
```

**Comment by som-snytt** [comment]
This is as specified.

**Comment by SethTisue** [comment]
https://scala-lang.org/files/archive/spec/2.13/06-expressions.html#overloading-resolution ?

**Comment by som-snytt** [comment]
"Relative weight" expresses that if I add an overload in a subclass, I intend for it to be preferred, so if the version from the superclass is "more specific", then my intentions are ambiguous and so is the overload.

I can't find the previous ticket which is less clear-cut than this case. (Because all search is terrible.)

**Comment by YulawOne** [comment]
I need to read the spec, so I don't have expertise from formal stand point, but from observational point the method in subclass is "more specific" rather superclass, as it has fewer arguments and it matches entirely, while the method in superclass has additional varargs, that makes "less specific". Is my reasoning wrong?
