### ISSUE TITLE
Newline syntax issue with some symbolic names (???)

### ISSUE THREAD

**Issue by Sciss** [scala/bug#12428]
## reproduction steps

The following causes issues with the usage line of `???`:

```scala
def bla(b: Boolean): Int = {
  println("Here")
  ???
  if (b) 1 else 0
}
```

## problem

in 3.0.0, this causes a compiler error `expression expected but if found`.

https://scastie.scala-lang.org/Ri9DgwTZTcCAP4bcwFEqqQ

while it works fine in 2.13:

https://scastie.scala-lang.org/joPxrIh9ReivLLpr4DU0Pg

**Comment by Sciss** [comment]
variant:

```scala
def updateChild(dt: Long): Unit = {
    if (dt != 0L) ???!
    println("removeChild")
  }
```

**Comment by som-snytt** [comment]
It is taken as infix in Scala 3: `println("Here").???(null)`. `-source 3.0-migration` warns.

The difference with Scala 2 `-Xsource:3` is that the test for the (second) operand is that it look like a simple expression, whereas Scala 3 accepts any expression including `if`.

Scala 2 makes a best effort at tracking Scala 3, but Scala 3 also checks indentation, for example.

I'll close this here, but you could open a ticket over at dotty if you feel strongly that `if` should never be considered for infix.

The second case is more interesting; perhaps turning off quiet syntax works for you.

**Comment by som-snytt** [comment]
The option is `-old-syntax` and actually it doesn't help; it reaches for infix and then complains that you didn't say `then`.

**Comment by som-snytt** [comment]
Maybe the dotty ticket should be to request an alias for `???`. I may have suggested `wtf` in the past.
