### ISSUE TITLE
illegal cyclic reference involving class Object

### ISSUE THREAD

**Issue by Honglun** [scala/bug#12421]
## reproduction steps

using Scala (2.12.10, 2.12.11, 2.12.12, 2.12.13),

```scala
import java.util.concurrent.Executors

import scala.concurrent.{ExecutionContext, Future}
import scala.tools.nsc.GenericRunnerSettings
import scala.tools.nsc.interpreter.ILoop


class TestSacalaExecutor{
  protected implicit val executor = ExecutionContext.fromExecutorService(Executors.newFixedThreadPool(10))
  var loop: ILoop = _

  def initLoop() = {
    loop = new ILoop()
    val settings = new GenericRunnerSettings((msg: Any) => {print(msg)})
    settings.processArguments(
      List("-Yrepl-class-based",
      "-Yrepl-outdir", "D:\\tmp\\repl-65299201-e525-4aae-8d6f-ee80201fc045",
      "-classpath",
      ""  ),
      true)
    settings.usejavacp.value = true
    settings.embeddedDefaults(Thread.currentThread().getContextClassLoader())
     Future {
       loop.process(settings)
       println("spark repl has been finished, now stop it.")
     }
  }
}

object TestSacalaExecutor {

  def main(args: Array[String]): Unit = {
    val executor = new TestSacalaExecutor
    executor.initLoop()
    watiTime(executor.loop.intp != null, 10000)
    println(executor.loop.intp.classLoader)
  }

  def watiTime(f : => Boolean, timeout: Long){
    val start = System.currentTimeMillis()
    while(!f){
      val spendTime = System.currentTimeMillis() - start
      println(s"wait -> $spendTime")
      if(spendTime > timeout){
        throw new RuntimeException("timeout")
      }
    }
  }
}

```

## problem
Calling the method 'watiTime' will cause the error: 'scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving class Object'.  Scala-2.11.8 doesn't have this problem.

**Comment by som-snytt** [comment]
The compiler is not thread-safe, so in general you can't construct `ILoop` on one thread and use it in another. This is a known limitation. I don't know off-hand what makes it less thread-safe for the example, or if it is a different change in initialization that caused the change in behavior.

**Comment by Honglun** [comment]
The root cause is not thread-safe, If it is, it should be `NullPointerException`. And I change the code `val loop: ILoop = new ILoop()`, the same error will still appear.

**Comment by som-snytt** [comment]
wrap `initLoop` in the future and await it, and it works as expected.
```
def initLoop = Future { /* run iloop */ }
...
Await.result(executor.initLoop(), Inf)
```

**Comment by Honglun** [comment]
'Await.result' doesn't meet my needs. And  I don't think my code has any syntactic problems. Java and Scala-2.11.8 doesn't have this problem. Please analyze the cause of the error in method 'waitTime', instead of changing my code.

**Comment by Honglun** [comment]
@som-snytt Why is it closed? I don't think you understand what I mean. The purpose of the method 'waitTime' is not to wait for the future to complete.  The future process is always running until we kill it. I use 'waitTime' to determine if the loop has been initialized. The point is that Java and Scala-2.11.8 doesn't have this problem.

**Comment by SethTisue** [comment]
> The compiler is not thread-safe, so in general you can't construct ILoop on one thread and use it in another. This is a known limitation

This is the heart of the matter and it's why the issue was closed.

If your code happened to work in 2.11, well, that was just luck.

The point of Som's suggestion involving `Await.result` isn't that you must use `Await.result` in particular... don't use it if you don't want to. But then you'll need to find some other way to comply with the constraint that `ILoop` expects to run on the same thread it was created on. That constraint is the crux here.
