### ISSUE TITLE
Wrong "unused nowarn" warnings when there are errors

### ISSUE THREAD

**Issue by lrytz** [scala/bug#12433]
```scala
import annotation.nowarn
object T {
  @deprecated def f = 1
  def t1 = /
  @nowarn def t2 = f
}
```

Compiling this with `-Wunused:nowarn` gives an incorrect warning:

```
Test.scala:4: error: not found: value /
  def t1 = /
           ^
Test.scala:5: warning: @nowarn annotation does not suppress any warnings
  @nowarn def t2 = f
   ^
1 warning
1 error
```

The reason is that the error is reported during typer, which makes the compiler skip later phases. So refchecks doesn't run and the `@nowarn` annotation doesn't silence the deprecation warning.

**Comment by som-snytt** [comment]
Early termination typically results in cascading errors, in general.

But it seems to me there are other open tickets around "refchecks didn't run yet". I'll update this comment if I rediscover them.
