### ISSUE TITLE
s.c.c.TrieMap#isEmpty is potentially wildly inefficient

### ISSUE THREAD

**Issue by NthPortal** [scala/bug#12445]
`s.c.c.TrieMap#isEmpty` will compute `size` if it is not already cached, which is O(n) and potentially very expensive

**Comment by SethTisue** [comment]
Does bincompat allow addressing it in 2.13.x?

**Comment by NthPortal** [comment]
should do - the signature isn't polymorphic, and it's also already overridden/implemented in `TrieMap`

**Comment by NthPortal** [comment]
the simple solution is to implement it as `sizeIs == 0`; however, there may also be a way to check if it's cached first, use that if possible, and if not use `sizeIs == 0` or similar.

(thank you so much past me for implementing `sizeIs`)
