### ISSUE TITLE
implicit object is not available for implicit resolution

### ISSUE THREAD

**Issue by myazinn** [scala/bug#12440]
## reproduction steps

using Scala 2.13.6,

```scala
trait Companion[T]

abstract class Service[T: Companion]

object Foo {
  // can't find required implicit
  class Impl extends Service[String]

  implicit object Impl extends Companion[String]
}
```

## problem
I'm expecting the above code to compile but it doesn't. If I (1) add dummy line that calls for this implicit value too, or (2) change the definition order, or (3) change `implicit object` to `implicit lazy val` then the code compiles fine
1.
```scala
trait Companion[T]

abstract class Service[T: Companion]

object Foo {
  def unused: Any = implicitly[Impl.type]
  
  class Impl extends Service[String]

  implicit object Impl extends Companion[String]
}
```
2.
```scala
trait Companion[T]

abstract class Service[T: Companion]

object Foo {
  implicit object Impl extends Companion[String]
  
  class Impl extends Service[String]
}
```
3.
```scala
trait Companion[T]

abstract class Service[T: Companion]

object Foo {  
  class Impl extends Service[String]

  implicit lazy val Impl: Companion[String] = ???
}
```
I'm really surprized that (1) fixes this issue. Intuitively it should not affect implicit resolution of existing code at all.

Initially I've faced this issue on Scala 2.12.14 which has exactly the same behavior in this case. Also, if I compile this code in Scala 3 then it works fine. Maybe you will find it useful.

**Comment by som-snytt** [comment]
https://github.com/scala/bug/issues/11751
helpfully links to
https://github.com/scala/bug/issues/8697

Note that in 3, explicit type was added.

**Comment by myazinn** [comment]
@som-snytt 
Got it, thanks.
Sorry for creating duplicate ticket, I couldn't find these tickets myself
