### ISSUE TITLE
Incorrect filterInPlace behavior in TrieMap

### ISSUE THREAD

**Issue by charpov** [scala/bug#12443]
## reproduction steps
Method `filterInPlace` is not reimplemented in `TrieMap` and relies instead on the `MapOps` implementation. This implementation does not work on a concurrent map because it uses the code:
```scala
if (!p(k, v)) {
    this -= k
}
```
This could remove a value other than `v`, added concurrently, that does satisfy the predicate.

The bug could be demonstrated with the following code, using Scala 3.0.1:

```scala
val exec = Executors.newCachedThreadPool()

def slowPositive(x: Int): Boolean =
   SECONDS.sleep(2)
   x > 0

val map = TrieMap("K" -> 0)

exec.execute(() => map.filterInPlace((_, v) => slowPositive(v)))

exec.execute { () =>
   SECONDS.sleep(1)
   map += "K" -> 1
}

exec.shutdown()
exec.awaitTermination(10, SECONDS)

assert(map.get("K").contains(1)) // should be true
```
The pair `("K",1)` cannot be removed by filtering positive values and should be present in the map at the end.

## remedy

The quickest solution would be to replace `-=` with `remove(k,v)` in `MapOps`, but this would have an unnecessary performance cost on all the non-concurrent maps.  The next quickest is to copy the implementation of `filterInPlace` from `MapOps` into `TrieMap` and replace `-=` with `remove(k,v)` there.  But this code copies the entire map into an array in order to avoid `ConcurrentModificationException`.  This is overkill in a concurrent map that, presumably, can handle modifications during iterations.  So, the best approach is probably to rewrite the method directly in terms of the `TrieMap` implementation.  It looks like using `iterator` and `remove(k,v)` should work, but may not be the best approach.  There's nothing trickier than non-blocking concurrent code!  Whoever wrote `TrieMap` would know best.

**Comment by SethTisue** [comment]
@scala/collections agree with Michel's assessment?

**Comment by NthPortal** [comment]
I agree that this is an issue, since the removal does not reflect a state the map was ever in. however, I don't think `remove(K,V)` is the solution. I think it's going to need an implementation that uses the map's internals

**Comment by NthPortal** [comment]
I'm also going to strongly disagree that this is a good first issue 😉

**Comment by charpov** [comment]
> I don't think `remove(K,V)` is the solution.

Because it's incorrect, or because of performance? 

```scala
      val iter = this.iterator
      while iter.hasNext do
         val (k, v) = iter.next()
         if !pred(k, v) then this.remove(k, v)
      this
```
This may not be optimal (in particular, it needs to hash every key), but it's better than the current broken behavior.
(Apologies for the Scala 3 code; that's how my environment is set up right now.)

**Comment by NthPortal** [comment]
performance, sorry. I'm fairly sure we can avoid checking full equality (at the very least we can optimise it to `eq` instead of doing a full `equals`)

**Comment by charpov** [comment]
`remove(k,v)` is based on `eq`, not `equals`.  I'm more concerned about re-hashing.  Note that the current `filterInPlace` not only re-hashes, but copies the entire map into an array, so this would not be worse.

**Comment by NthPortal** [comment]
oh, my mistake. regardless. a bespoke implementation can be optimised

**Comment by som-snytt** [comment]
We need a label for "good Nth issue"

**Comment by NthPortal** [comment]
> This may not be optimal (in particular, it needs to hash every key)

after doing some digging, I've discovered that the iterator doesn't expose a way to iterate over the entries with hash codes, so it looks like your implementation is about as good as it's going to get without major implementation changes (that I'm not currently comfortable making myself) @charpov

**Comment by charpov** [comment]
I suspect there might be a way to traverse the trie (the order doesn't matter) and use a CAS on each node to filter out values, but that would require a deep understanding of the structure, which I don't have.

BTW, I'm surprised that `isEmpty` relies on `size`, which looks costly and complex. Contrary to what the comments say, `clear` seems to be implemented as a CAS on a root pointer, not via iteration.  Isn't there a way to look at this pointer to test emptiness?

**Comment by NthPortal** [comment]
already on it ;) #12445

**Comment by NthPortal** [comment]
> `remove(k,v)` is based on `eq`, not `equals`

after doing some digging, this is not the case

**Comment by charpov** [comment]
My bad.  I was looking at line 332, but I must have read `==` with my Java brain.
I suppose it makes sense: If users want pointer comparison, they can always (or often) define `equals` accordingly. It's harder the other way around.  Java maps do the same thing. It'd be nice to be able to do a (referenced-based) CAS on a node directly instead, if that is possible.

**Comment by charpov** [comment]
BTW, the wrapped concurrent map (`JConcurrentMapWrapper`) does not reimplement `filterInPlace` and suffers from the same bug.

**Comment by NthPortal** [comment]
dah. I'll have to move the fix up the hierarchy I guess

**Comment by charpov** [comment]
You can probably place the code I suggested inside `concurrent.Map`.
