### ISSUE TITLE
Pure binding in a for-comprehension that shadows an implicit generates a misleading error

### ISSUE THREAD

**Issue by slice** [scala/bug#12455]
## reproduction steps

using Scala 2.13.6,

```scala
class Foo(implicit baz: Int) {
  def task: Either[Unit, Unit] = for {
    _ <- Right("...")

    incremented = Bar.incrementedImplicit

    // ...
    // ...
    // ...

    baz = 123
  } yield ()
}

object Bar {
  def incrementedImplicit(implicit quux: Int): Int = quux + 1
}
```

## problem

If you have a pure binding in a for-comprehension with the same name as an implicit that's used in the same for-comprehension, the compiler will emit a confusing error:

```
test.scala:5: error: could not find implicit value for parameter quux: Int
    incremented = Bar.incrementedImplicit
                      ^
```

The `Bar.incrementedImplicit` call needs an implicit `Int` in scope. Naturally, one would expect the one from the implicit parameter list from the class definition to be used. But if you have a pure binding with the same name as one from an enclosing scope (here, `baz`), the compiler seems to get confused (or at least, emit a confusing error).

Removing the `baz = 123` line or renaming the variable makes the error go away. If you use the value of `incremented` in the shadowing pure binding, you get an even more misleading error message:

```
test.scala:11: error: recursive value incremented needs type
    baz = incremented + 123
    ^
test.scala:5: error: could not find implicit value for parameter quux: Int
    incremented = Bar.incrementedImplicit
                      ^
```

**Comment by som-snytt** [comment]
The shadowing is just how Scala 2 works; Scala 3 works differently.

```
class Foo(implicit baz: Int) {
  locally {
    val incremented = Bar.incrementedImplicit
    val baz = incremented + 123
  }
}

object Bar {
  def incrementedImplicit(implicit quux: Int): Int = quux + 1
}
```
The word "recursive" in the error message is just an approximation for a cyclic error in type completion. Apparently because `baz` is forced during implicit search. If it's the shadowing check that does that, perhaps forcing the type is unnecessary, since all you need is the name for that.

Either writing `val baz: Int` or removing the dependency fixes the cyclic error.
```
  locally {
    val incremented = Bar.incrementedImplicit
    val baz = 0
    val bar = incremented + 123
  }
```

**Comment by slice** [comment]
> The shadowing is just how Scala 2 works; Scala 3 works differently.

Ah... understood. Should this issue be closed then?

**Comment by som-snytt** [comment]
I agree the word "recursive" is misleading, but it's kind of "best-effort". Also possibly the extra message could be improved (eliminated); it's also confusing (or revealing) that the messages are printed "out of order". But probably it is not worth the effort at this point.

**Comment by slice** [comment]
Thanks for the clarification!
