### ISSUE TITLE
Collection optimizations have changed the behavior ++ with view. in scala 2.12.11

### ISSUE THREAD

**Issue by spangaer** [scala/bug#12454]
## reproduction steps

https://github.com/spangaer/scala-2.12.11-mergeview-change

`./reproduce`

## problem

In Scala versions 2.12.[3,10] and 2.13.6 any mapping operation on a view that is merged is invoked only once.

In Scala versions. 2.12.[11,14] the first element of the view is iterated twice.

https://github.com/scala/scala/blob/v2.12.14/src/library/scala/collection/immutable/HashMap.scala#L180

The first time, the `.isEmpty` check on line 184.
The second time in the `.foreach` on line 191.

If the mapping operation has side effects (e.g. creating an Akka actor), the change breaks down pretty badly.

## workaround

Replacing the `.view` with `.iterator`

## related

https://github.com/scala/bug/issues/12047

## code

```scala
import scala.collection.immutable

object Main {

  def main(args: Array[String]) {

    val scalaVersion = util.Properties.versionString

    println("\n")
    println(scalaVersion)

    val map = immutable.HashMap(1 -> 1, 2 -> 2)

    val set = Set(3, 4)

    map ++ set.view
      .map { i =>
        try {
          println(s"  index: $i")
          Some(i -> i)
        } catch {
          case _: Exception =>
            None
        }
      }
      .collect { case Some(s) =>
        s
      }

    println("\n")
  }

}
```

## output

```
version 2.12.3
  index: 3
  index: 4

version 2.12.10
  index: 3
  index: 4

version 2.12.11
  index: 3
  index: 3
  index: 4

version 2.12.14
  index: 3
  index: 3
  index: 4

version 2.13.6
  index: 3
  index: 4
```

**Comment by lrytz** [comment]
I don't think this is a bug.

I think `if (that.isEmpty) ... else ... that.foreach` where `that: GenTraversableOnce` is a correct optimization. The method `GenTraversableOnce.isEmpty` has a comment

> Implementations in subclasses that are not repeatedly traversable must take care not to consume any elements when `isEmpty` is called

which says that it's OK to call `isEmpty` and then still traverse the `GenTraversableOnce`.

The view `val sv = Set(1).view.map(x => {println(x); x}).filter(_ > 0)` *can* be traversed repeatedly - it just recomputes the elements (and re-executes side-effects), but that's not breaking any guarantees.

I think think of a `View` as a collection that's implemented over an "iterator factory", see the [`View.fromIteratorProvider` method](https://github.com/scala/scala/blob/v2.13.6/src/library/scala/collection/View.scala#L58-L60). So a view "has the right" to create and use an iterator as often as needed.

In 2.13.6:

```scala
scala> val sv = Set(1).view.map(x => {println(x); x}).collect(x => x)
val sv: scala.collection.View[Int] = View(<not computed>)

scala> sv.isEmpty
1
val res4: Boolean = false

scala> sv.isEmpty
1
val res5: Boolean = false
```

**Comment by SethTisue** [comment]
@scala/collections

**Comment by NthPortal** [comment]
I'm going to agree with Lukas here—this is not a bug.

by definition, a view (re)computes its elements as needed, generally each time they are accessed. as such, a view is *not* the correct type to use for creating actors. consider creating a concrete collection and calling `foreach` on it, or, as you noted, using an iterator

**Comment by spangaer** [comment]
While I don't disagree on these statements.
- A behavioral change like this probably doesn't belong in an incremental version (not asking for a revert, just flagging)
- I find it particularly bothering that 2.13.6 does not have the behavioral change. If it was just prep for 2.13.x and get on with our lives, I'd see the sense.

I had refactored the problem code already, but given this I'm a bit scared to proceed with the version update.

**Comment by NthPortal** [comment]
I suspect the reason is that 2.13 tends to use `knownSize` in those situations rather than `isEmpty`, and `knownSize` typically returns `-1` in situations where `isEmpty` would have to potentially evaluate an element.

**Comment by NthPortal** [comment]
honestly, I think it's mostly chance. a lot of the collections were re-implemented significantly, and `HashMap` was completely re-implemented, as it uses the new CHAMP implementation

**Comment by spangaer** [comment]
But why does, what I understood to be a back-port, cause a behavioral change in `2.12.11+` and and not in `2.13.x`?

**Comment by NthPortal** [comment]
for what I can tell, the change to that method that added an `isEmpty` call happened in scala/scala#8466, which was not a backport and has the following in its description:

> Note - for 2.12 only
> We can duplicate the functionality to 2.13, but I think it is with a seperate PR as 2.13 collections are differently structured

it would seem that if that work was done to add similar functionality in 2.13, the 2.12 PR was not linked to it.

**Comment by spangaer** [comment]
Fair enough. Looking at the timings, when all of this was happening, 2.13 was still sort of "maturing". Hence the 2.12 target.

I know I'm grossly late with following comment: not this "issue", but the collection rework is a pretty fundamental overhaul for an incremental update of "the current stable".

**Comment by SethTisue** [comment]
> the collection rework is a pretty fundamental overhaul for an incremental update of "the current stable"

Scala versions are epoch.major.minor, not major.minor.patch. The collections overhaul in 2.13 (released 2019) was the first such overhaul since 2.8 (released 2010).

**Comment by spangaer** [comment]
I'm referring to the rework of the HashMap etc, that led to this "issue". So the 2.12.[11 -> 14] rework, not the 2.13 one 😉.

**Comment by SethTisue** [comment]
Ah, okay.

Some additional context: in 2.12.x: `.view` is a buggy, misbegotten footgun. This bug tracker is full of `.view` bugs stretching back to the 2.8 overhaul. So I understand that you're unhappy that something involving `.view` changed in 2.12.x point release, but please know that no one should be using `.view` at all in 2.{8-12} as its behavior, depending on what collection you're using and what operations you're performing on it, is.... unpredictable.

`.view` works fine in 2.13.

**Comment by spangaer** [comment]
Some irony that it probably started entering our code base given it's conceptual virtues when reading about the 2.13 collections refactor. But understood.

I'll probably stick with 2.12.10 to keep what works working (this one's fixed, but there's bound to be others), we should jump to 2.13 not too far in the future anyway.

**Comment by SethTisue** [comment]
(That sounds plausible, but I'll just add that most uses of `.view` in the wild can be replaced with `.iterator` and it doesn't matter, since people are typically doing `foo.view.op(...).op(...).toBar` or similar and it's immaterial whether the type along the way is `View` or `Iterator`. Exceptions exist, naturally.)
