### ISSUE TITLE
Could not retrieve sbt 1.5.5

### ISSUE THREAD

**Issue by Klaider** [scala/bug#12462]
## reproduction steps

using SBT 1.5.5,

```sh
sbt new scala/scala.g8
```

## problem

The command terminates with errors, of which the last one is

```
[error] [launcher] could not retrieve sbt 1.5.5
```

Full log:

```
[info] [launcher] getting org.scala-sbt sbt 1.5.5  (this may take some time)...
[error] [launcher] xsbt.boot.internal.shaded.coursier.error.ResolutionError$CantDownloadModule: Error downloading org.scala-sbt:sbt:1.5.5
  not found: C:\Users\hando\.ivy2\local\org.scala-sbt\sbt\1.5.5\ivys\ivy.xml
  download error: Caught javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty (java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty) while downloading https://repo1.maven.org/maven2/org/scala-sbt/sbt/1.5.5/sbt-1.5.5.pom
  download error: Caught javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty (java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty) while downloading https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt/1.5.5/sbt-1.5.5.pom
  download error: Caught javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty (java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty) while downloading https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt/1.5.5/sbt-1.5.5.pom
  download error: Caught javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty (java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty) while downloading https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt/1.5.5/ivys/ivy.xml
  download error: Caught javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty (java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty) while downloading https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt/1.5.5/ivys/ivy.xml
[error] [launcher] could not retrieve sbt 1.5.5
```

**Comment by Jasper-M** [comment]
Doesn't look like an issue with Scala itself. And quite possibly a local issue on your system.

**Comment by Klaider** [comment]
@Jasper-M So where else could I report this issue? And I installed SBT directly, so I think it's not the host environment.

**Comment by SethTisue** [comment]
https://github.com/sbt/sbt/issues if you become convinced, with evidence, that there is actually a bug in sbt, but I agree with Jasper that it's likely something in your environment and is probably not Scala-specific and probably not even sbt-specific either

so for now I think you should treat this as "I need help with sbt" rather than "there is a bug in sbt I need to report". try googling the error message for possible causes, and/or see https://www.scala-sbt.org/support.html

**Comment by charJe** [comment]
@Klaider Were you ever able to solve this _issue_? I'm having the the same problem.

**Comment by Klaider** [comment]
@charJe I haven't tried any further, but maybe you can ask about this bug in [github.com/sbt/sbt](https://github.com/sbt/sbt/issues) as SethTisue said.

**Comment by Cathysshelter** [comment]
> @Klaider Were you ever able to solve this _issue_? I'm having the the same problem.

Were you ever able to solve this issue? I'm having the the same problem.

**Comment by charJe** [comment]
I was able to solve it be reinstalling Java, but only installing through intellij worked.

**Comment by som-snytt** [comment]
Although this is not a support forum, no one asked what version of Java and OS and whether the client is behind a corporate firewall.

The error "the trustAnchors parameter must be non-empty" is an easy google, though possibly challenging to repair.

In the modern era (2022), someone would likely suggest trying `scala-cli` or `coursier` as a sanity check.

**Comment by Cathysshelter** [comment]
> @Klaider Were you ever able to solve this _issue_? I'm having the the same problem.

I have solved this problem. I use openjdk8, and I replace its 'cacerts' file to openjdk11's 'cacerts' file.

**Comment by som-snytt** [comment]
In the past, I've had to fix `cacerts` on every upgrade. I hoped for better visibility and tooling.
