### ISSUE TITLE
Error upgrading to Scala 2.13.6

### ISSUE THREAD

**Issue by Braj-Bhushan** [scala/bug#12468]
I am trying to migrate to Scala - 2.13.6 and Akka - 2.6.16 with akka-actor_2.13 version 2.6.16.

**Code**

```scala
import akka.http.scaladsl.model.ContentType
import akka.http.scaladsl.model.HttpCharsets.UTF-8
import akka.http.scaladsl.model.MediaTypes.{application/json, application/xml}

object MyPayloadType extends Enumeration {

val XML,
JSON = Value

def getMyPayloadType(contentType: Value): ContentType.NonBinary = contentType match {

case XML => ContentType(`application/xml`, `UTF-8`)

case JSON => ContentType(`application/json`)
}
}
```

**Above code gives the following compilation error.**
"Symbol 'type Scala.collection.IndexedSeqOptimized' is missing from the classpath.
This symbol is required by 'class akka.util.ByteString'

Please suggest to resolve above.

**Comment by eed3si9n** [comment]
Googling for this error brings up https://github.com/akka/akka/issues/27243. Are you sure it's using `_2.13` artifacts?

**Comment by dwijnand** [comment]
> Please suggest to resolve above.

Please use https://users.scala-lang.org/ or https://stackoverflow.com/tags/scala for problem resolution questions.  There are also chat options, see https://www.scala-lang.org/community/.
