### ISSUE TITLE
scalac cannot parse records that implement interfaces

### ISSUE THREAD

**Issue by s5bug** [scala/bug#12474]
## reproduction steps

using Scala 2.13.6, Java 17

_`sealed` and `permits` commented out due to #12159_
```java
public /* sealed */ interface Nat /* permits Nat.Zero, Nat.Succ */ {
    public static final record Zero() implements Nat {}
    public static final record Succ(Nat pred) implements Nat {}
}
```

## problem

```
`;` expected but `implements` found.
    public static final record Zero() implements Nat {}
```

The error message is confusing as well, as
```java
public static final record Zero();
```
does not work, but
```java
public static final record Zero() {}
```
does.

**Comment by dwijnand** [comment]
@harpocrates fyi, if you feel like looking at this

**Comment by som-snytt** [comment]
I added a test, but this always worked. `record` support arrived in 2.13.7 which was merged that summer but released Nov 1, after this ticket.
