### ISSUE TITLE
All error messages for "needs to be abstract" errors should give method stubs

### ISSUE THREAD

**Issue by jphmrst** [scala/bug#12487]
Currently the `class XXX needs to be abstract, since def YYY: ... is not defined` error messages give stub methods with `???` bodies when there are two or more missing methods, but do not offer these stub methods when there is a single missing method.  It would be nice to offer stub methods in the case of a single missing method as well.

**Comment by som-snytt** [comment]
Perhaps also include the comment for where the members come from.

Or "Missing implementations for 2 members from `trait T`" etc.

```
scala> trait T { def f: Int }
trait T

scala> class C extends T
             ^
       error: class C needs to be abstract. Missing implementation for:
         def f: Int // inherited from trait T

scala> trait T { def f: Int; def g: String }
trait T

scala> class C extends T
             ^
       error: class C needs to be abstract.
       Missing implementations for 2 members. Stub implementations follow:
         def f: Int = ???
         def g: String = ???
```
Also eliminate the verbiage about "Stub implementations". Extra words may have been useful when it was a cool new error messaging feature.

**Comment by jphmrst** [comment]
> Also eliminate the verbiage about "Stub implementations". Extra words may have been useful when it was a cool new error messaging feature.

Well...that's the opposite that this ticket requests ;-) .  I find them useful, and would love to see them in all missing-method cases.

**Comment by som-snytt** [comment]
@jphmrst I just meant those two words, I agree with what you ask. I'll try a quickie PR!

**Comment by som-snytt** [comment]
more sample flaws

```
scala> trait T { var v: Int ; def f: Int }
trait T

scala> class C extends T
             ^
       error: class C needs to be abstract.
       Missing implementations for 2 members. Stub implementations follow:
         def f: Int = ???
         def v_=(x$1: Int): Unit = ???
```

**Comment by jphmrst** [comment]
> Edit: I see the reason for the difference is that there are verbose explanations provided only if there is only one missing method. Otherwise, it is too verbose. The assumption is that for multiple missing, you know what you're doing and didn't implement an interface. But it's easy to imagine `f` and `g` are missing for head-scratching reasons and you'd like extra help.

I just don't see the "additional verbosity" of _either_ the `//` comments locating the abstract declarations' locations, _or_ the `= ???` of the stubs, to be all that verbose.  The latter is easy to just ignore if it's just the hint you're after; if you're after the stubs, then you're going to edit the part with the `//` comments anyway.  It seems like a false economy to not show them both every time.

**Comment by jxnu-liguobin** [comment]
This issue has been received? I can create a pr.


> Maybe offer to emit that advice under `-verbose`

 Should we do it?

**Comment by som-snytt** [comment]
The draft PR breaks a case, but demonstrates always showing all the info, in a regular format.

The verbose "diagnostic" is always emitted as a line comment.
