### ISSUE TITLE
Regression in Scala 2.13.7 - cannot use wildcard for F-bounded type when using OptManifest

### ISSUE THREAD

**Issue by Sciss** [scala/bug#12481]
## reproduction steps

using Scala 2.13.6 (and all before), the following works ( https://scastie.scala-lang.org/NkHsooECRGqIgttwtvkgMg )

```scala
trait Txn[T <: Txn[T]]

trait Universe[T <: Txn[T]]

object Ref {
  def apply[A](init: A)(implicit om: OptManifest[A]): Ref[A] = ???
}
trait Ref[A]

trait Handler {
  def all: Ref[Vector[Universe[_]]] = Ref(Vector.empty)   // here
}
```

In Scala 2.13.7, the marked line produces an error

```
type arguments [_$1] do not conform to trait Universe's type parameter bounds [T <: Txn[T]]
      def all: Ref[Vector[Universe[_]]] = Ref(Vector.empty)
```

This is somehow caused by the `OptManifest` argument to the `Ref` constructor. If I remove that implicit argument, it compiles again.

**Comment by Sciss** [comment]
Note that I can write in this case `def all: Ref[Vector[Universe[_]]] = Ref(Vector.empty)(NoManifest)` as a work-around, since the class manifest is not strictly needed here.

**Comment by som-snytt** [comment]
I guess it involves https://github.com/scala/scala/pull/9776 and not wildcard representation. An extra check is introduced.

**Comment by SethTisue** [comment]
attn @lrytz

**Comment by som-snytt** [comment]
I'll let lrytz say if it is simply correct, which I guess it is.

test at https://github.com/scala/scala/pull/9802

**Comment by lrytz** [comment]
Thank you @som-snytt - I think you're right

```
  def m1[T <: Txn[T]] = optManifest[Universe[T]] // ok
  def m2 = optManifest[Universe[_]] // type arguments [_$2] do not conform to trait Universe's type parameter bounds [T <: Txn[T]]
```

**Comment by lrytz** [comment]
Though i'm not all that sure how wildcards are working / supposed to work. `def t: Universe[_] = ???` is ok. Writing out the code after `-Vprint:typer` explicitly type checks.

```
def t: Ref[Vector[Universe[_]]] = Ref.apply[Vector[Universe[_]]](scala.Vector.empty[Nothing])(scala.reflect.ClassManifestFactory.classType[Vector[Universe[_]]](classOf[scala.collection.immutable.Vector[_]], scala.reflect.ClassManifestFactory.classType[Universe[_]](classOf[Universe[_]], scala.reflect.NoManifest)))
```

**Comment by Jasper-M** [comment]
Works in Scala 3, by the way. But their wildcards are generally better at ignoring stuff, as demonstrated in the possibly somewhat related #8039.

**Comment by som-snytt** [comment]
Yes, I noticed that dotty is nicer with special wildcard name handling. I expected to need some name-based extraction somewhere. But per Lukas's comment, I tried to induce explicit failure, but it was something else leaking when summoning the manifest, which is not merely implicit but "internal" or "magical". Also, paulp's "rocket science" dig is motivational, I don't remember why it didn't come up on the underscore ticket.

BTW both PRs landed about the same time, which is why I assumed the underscore ticket was causative. I didn't actually bisect.

**Comment by joroKr21** [comment]
The main code path where `checkTypeRef` is used takes care of converting existential types to wildcards:
https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/typechecker/RefChecks.scala#L1758-L1780

**Comment by joroKr21** [comment]
TIL that this doesn't complain 🤔 
```scala
  trait Foo[A <: Int]
  class bar[A] extends StaticAnnotation
  @bar[Foo[String]]
  val x = 42
```

**Comment by joroKr21** [comment]
Also this:
```scala
  trait Foo[A <: Int]
  trait Bar[A, B]
  val x: Bar[Foo[String] @uncheckedBounds, Foo[String]] = null
```

**Comment by SethTisue** [comment]
(leaving it on the 2.13.8 milestone, no _released_ version of 2.12 had the bug)
