### ISSUE TITLE
supplementary characters from Unicode_So category are not parsed in operator identifier

### ISSUE THREAD

**Issue by unkarjedy** [scala/bug#12482]
Scala 2.13.7

https://www.scala-lang.org/files/archive/spec/2.13/13-syntax-summary.html
```
opchar           ::=  ‘!’ | ‘#’ | ‘%’ | ‘&’ | ‘*’ | ‘+’ | ‘-’ | ‘/’ | ‘:’ |
                      ‘<’ | ‘=’ | ‘>’ | ‘?’ | ‘@’ | ‘\’ | ‘^’ | ‘|’ | ‘~’
                      and any character in Unicode categories Sm or So
```

Supplementary unicode characters `\u1F300..\u1F5FF` are also included by  Unicode So category.
See `java.lang.Character.UnicodeBlock#MISCELLANEOUS_SYMBOLS_AND_PICTOGRAPHS`
But they are not parsed in `2.13.7`
```scala
class Suppl {
  def ☀ = 42
  def 𐐀 = 42
  def 🌂 = 42
  def 🌀 = 42
}
```

```
error: illegal character '\ud83c\udf02'
error: illegal character '\ud83c\udf00'
```

Whether spec or implementation should be patched.

relates to:
https://github.com/scala/scala/pull/9687
https://github.com/scala/bug/issues/1406

**Comment by som-snytt** [comment]
Thanks for the report! I will follow up.
