### ISSUE TITLE
Cannot put annotation on package object

### ISSUE THREAD

**Issue by adampauls** [scala/bug#12496]
## reproduction steps

using Scala 2.13.7

```scala
@scala.annotation.nowarn
package object pack
```

## problem

Fails to compile with 
```
expected start of definition
```

I am trying to silence deprecation warning on package object inheritance while we migrate to Scala 3. The annotation location parses fine if the `package` keyword is removed. Perhaps I'm supposed to put the annotation somewhere else, but I couldn't figure out where.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/3115 where the annotation of interest was deprecation.

`-Wconf` may suffice. `cat=deprecation` with `msg=...`. It's a parser warning, so there is no `site=p`, alas.
