### ISSUE TITLE
Spurious unused patvar warning when used pattern is a type pattern in a `for` 

### ISSUE THREAD

**Issue by martijnhoekstra** [scala/bug#12497]
## reproduction steps

using Scala 2,

```scala
for {
  (_, _) <- Option(1 -> 2)
  (c: Int, _) = 3 -> 4
} {
  println(c)
}
```

under -Wunused:patvar

> pattern var c in value $anonfun is never used: use a wildcard `_` or suppress this warning with `c@_`

## problem

`c` is used, but reported as unused

**Comment by dwijnand** [comment]
In the desugaring there will be extra patterns which end up being unused.  It's unfortunate.  I'll let @som-snytt close as duplicate if this is documented somewhere already.

**Comment by SethTisue** [comment]
#10287 ?

**Comment by som-snytt** [comment]
Thanks @SethTisue I couldn't find it and then got distracted looking at old tickets.

**Comment by dwijnand** [comment]
Duplicate of #10287
