### ISSUE TITLE
Symbol documentation is misleading

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12507]
## reproduction steps

Noticed at https://github.com/lampepfl/dotty/issues/14028

using Scala 2.13.7,

```scala
scala> :doc Symbol
No such command ':doc'.  Type :help for help.

scala> :spec Symbol
No such command ':spec'.  Type :help for help.
```

but if there were such a command, it would offer deprecated advice about `Symbol` literals.

The `spec` command would show the incorrectly specified or implemented innards of `Symbol`, which is not a case class.

## problem

It's nicer when docs align with reality. It's unusual to collide with a language change in the standard library docs.

**Comment by som-snytt** [comment]
```
scala> 'abc
       ^
       warning: symbol literal is deprecated; use Symbol("abc") instead
val res6: Symbol = Symbol(abc)

scala> def f: 'abc = 'abc
              ^
       error: stable identifier required, but scala.Symbol("abc").type found.
                     ^
       warning: symbol literal is deprecated; use Symbol("abc") instead
```
Perhaps that was never in a release, but spec was not rejiggered after sip-23.

Also, why isn't there a hip whiskey called sip-23?

**Comment by ira19921** [comment]
Что надо от меня

пт, 3 дек. 2021 г., 14:30 som-snytt ***@***.***>:
