### ISSUE TITLE
Scala pattern case with type parameterlization compile failed

### ISSUE THREAD

**Issue by yikf** [scala/bug#12504]
## reproduction steps

Scala version: scala 2.12

```scala
class A[T]

class B extended A[Integer]

class C[T] extended A[T]

def foo(input: A[T]): Unit = {
   input match {
     case b: B => // this will compile fail, require type parameterlization
     case c: C[Integer] => // will compile successful
     case _ => // do nothing
  }
}
```

## problem
As mentioned above:
The input maybe is B's instance, But we case B without type parameterlization will compile failed.

Any one could help me?

**Comment by lrytz** [comment]
This place is for bug reports, please ask questions on https://users.scala-lang.org/ or https://discord.com/invite/scala

**Comment by yikf** [comment]
> This place is for bug reports, please ask questions on https://users.scala-lang.org/ or https://discord.com/invite/scala

Sorry, Thanks guy~
