### ISSUE TITLE
Compilation failing after upgrading to 2.12 from 2.11 for covariance

### ISSUE THREAD

**Issue by rahul-narayana** [scala/bug#12503]
## reproduction steps

using Scala (2.12.15),

When compiling the following code

```scala
type Dish[A] = List[A]

sealed trait Order[+A] {
  val items: Dish[A]
}
```
It gives the following error ```covariant type A occurs in invariant position in type => com.example.Catalog.Dish[A] of value items```

## problem

I am migrating a legacy project from 2.11 to 2.12. The same works fine when I compile in scala 2.11. Apologise if I have missed something. I couldn't find anything in the release notes regarding the same

**Comment by lrytz** [comment]
`type Dish[+A] = List[A]` works. https://users.scala-lang.org is the recommended place to ask questions like this
