### ISSUE TITLE
Backport compiler option "-Ydebug-error" from scala 3

### ISSUE THREAD

**Issue by tribbloid** [scala/bug#12505]
This is a very important option when working with a fast-moving compiler or unstable compiler plugin. Yet it is missing in scala 2 for a very long time. (The option "-Yissue-debug" only covers a very small subsection of errors that can be handled by "-Ydebug-error")

To me it looks like a low-hanging fruit, time to bring it up to be on par with Scala 3.

**Comment by lrytz** [comment]
I'm closing this ticket because this issue tracker is for bugs. This doesn't mean I disagree with the idea; but we are not collecting feature requests / ideas here.

**Comment by ira19921** [comment]
Спасибо

чт, 2 дек. 2021 г., 10:34 Lukas Rytz ***@***.***>:

**Comment by tribbloid** [comment]
@lrytz thanks a lot, I'll take it as a yes, will submit a PR shortly

**Comment by ira19921** [comment]
👌

четверг, 2 декабря 2021 г. пользователь Peng Cheng ***@***.***>
написал:

**Comment by som-snytt** [comment]
Fixed in https://github.com/scala/scala/pull/9824
