### ISSUE TITLE
-Xlint:nowarn as suggested by Scala 2.12 docs is reported as an error by Scalac in 2.12.15

### ISSUE THREAD

**Issue by jackkoenig** [scala/bug#12516]
I get [error] 'nowarn' is not a valid choice for '-Xlint' using -Xlint:nowarn as suggested by the Scala 2.12 API docs: https://www.scala-lang.org/api/2.12.15/scala/annotation/nowarn.html yet Scala compilation completes successfully. It shows up briefly in Scastie as well: https://scastie.scala-lang.org/u4WGadkdSi6Uoy4PghHkgA

## reproduction steps

using Scala (2.12.15),

Using `scalacOption` `-Xlint:nowarn` as suggested by the API docs (https://www.scala-lang.org/api/2.12.15/scala/annotation/nowarn.html)

You can see this in Scastie but have to change things (so it recompiles) and then look fast because compilation messages go away pretty quickly: https://scastie.scala-lang.org/u4WGadkdSi6Uoy4PghHkgA

## problem

This gives the following "error":

```
[error] 'nowarn' is not a valid choice for '-Xlint'
```

Notably compilation still succeeds, but the message is red and looks scary 🙂

**Comment by som-snytt** [comment]
The typo was fixed in https://github.com/scala/scala/commit/41e24110967c2b1b768759f6539cfd2f25073ba4 which should be backported.
