### ISSUE TITLE
Custom created object is child of both AnyVal and AnyRef

### ISSUE THREAD

**Issue by guruprasathb** [scala/bug#12522]
## reproduction steps

using Scala (3.x),

class Demo
val d = new Demo
d.isInstanceOf[Any]
-> true

d.isInstanceOf[AnyRef]
-> true

d.isInstanceOf[AnyVal]
-> true

## problem

How could an object be child of both AnyVal and AnyRef

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org for questions
