### ISSUE TITLE
Scala Serialization Incompatibility between 2.11.8 and 2.12.0 Onwards

### ISSUE THREAD

**Issue by ak-2021** [scala/bug#12526]
## PROBLEM
In Scala 2.11.8, EmptySet object in Set.scala defined inside package scala.collection.immutable was missing SerialVersionUID and was later added in Scala 2.12.0 and onwards as a result of which it causes deserialization issue because of the mismatch of the SerialVersionUID and throws InvalidClassException. The data that were persisted with 2.11.8 are not getting deserialized and hence I am unable to retrieve the existing data with scala 2.12.0 and higher versions. 

How can we fix this issue with serialization incompatibility? 

The difference in SerialVersionUID is causing deserialization issue. Would request your inputs on how to fix this issue. 

Thanks

**Comment by ak-2021** [comment]
Hello @adriaanm @retronym @lrytz Please provide some suggestions on how to fix the serialization incompatibilities between the Scala versions 2.11.8 and 2.12.0 & onwards. Any inputs would be really appreciated. 

Thanks

**Comment by som-snytt** [comment]
They might be either asleep or at happy hour.

The 2.12 annotation is at https://github.com/scala/scala/commit/759b0daaf448f08f3233ee5fdaa3bc29f0732dfc

where it looks like an incidental change.

The unrelated 2.13 annotation is at https://github.com/scala/scala/commit/18081fe2e8b3ec89d437674905e85eb0042294f3

In the past, I have handled this sort of migration by reading with the old code, and writing with the new code.

Probably you will get better help on discord or the forum, where there are more eyeballs.

I'm not sure there is an "actionable" bug, but it's nice to have a ticket about the issue.

**Comment by SethTisue** [comment]
Scala 2 major versions aren't serialization compatibility with each other; end of story.

I don't know if anyone has come up with some kind of mitigation or way to translate; you might ask on https://users.scala-lang.org
