### ISSUE TITLE
Nested singleton objects have a public constructor

### ISSUE THREAD

**Issue by kjh618** [scala/bug#12525]
# Reproduction Steps

Scala 2.13.8, AdoptOpenJDK 11

```scala
object Ok

object Bad1 {
  object Bad2
}

classOf[Ok.type].getConstructor().newInstance() // (1)
classOf[Bad1.Bad2.type].getConstructor().newInstance() // (2)
```

# Problem

(1) fails correctly with `java.lang.NoSuchMethodException` at `getConstructor()` since the constructor of `Ok` is private, but (2) succeeds without throwing any exceptions. This makes it possible to create a new instance of a singleton with reflection or macros.

Looking at the decompiled Java code (using Intellij IDEA), it seems `Bad2` does not mark its constructor as private.

```java
public final class Ok$ {
   public static final Ok$ MODULE$ = new Ok$();

   private Ok$() {
   }
}
```

```java
public final class Bad1 {
   public static class Bad2$ {
      public static final Bad1.Bad2$ MODULE$ = new Bad1.Bad2$();
   }
}
```

Is there any particular reason why nested objects does not have a private constructor? Even though it's still not possible to create a new instance of such objects without reflection/macros, I think the behavior should be consistent with non-nested objects.

**Comment by kjh618** [comment]
Btw, the same thing happens in Scala 3.1.1 as well.

**Comment by lrytz** [comment]
Without thinking about it too deeply, I guess it could be done for statically nested objects, but not for objects nested within a class (`class A { object B }`) where there's an instance of `B` for each outer `a: A`. So you can easily create multiple `B`'s for the same outer `a: A` here too. A partial fix for the static version only seems not worth it.

Also it's a change in the binary encoding, so there's always a risk for accidental breakages (Scala 2.13.x and 3.x remain binary compatible).

**Comment by kjh618** [comment]
Since only `A` calls the constructor of the inner object `B`, `B`'s constructor can be private as well. So it's possible to fix both cases.

Though I understand the point about binary compatibility. It's not a major issue, so prioritizing compatibility is perfectly fine.

**Comment by SethTisue** [comment]
> Since only A calls the constructor of the inner object B, B's constructor can be private as well

Can it? Bytecode has no concept of inner classes; in byte code, all classes are top-level.

Javac uses a rather elaborate trick to handle this, as explained at https://stackoverflow.com/questions/2883181/why-is-an-anonymous-inner-class-containing-nothing-generated-from-this-code

I doubt that introducing something that elaborate into Scala 2 is viable at this stage in its history. (I haven't thought through whether it would even be binary compatible.)

**Comment by kjh618** [comment]
Huh, good to know.

I tried the example in the link above in Scala 2, and it seems that the Scala compiler just makes everything public in the bytecode, even if `PrivateInnerClass` is marked `private`. I guess doing it this way is also fine, since the Java's way (extra class + dummy parameter) can be bypassed with reflection anyway.
