### ISSUE TITLE
Compiler crash on assertion failed:  cannot invokespecial ____, the interface is not a direct parent

### ISSUE THREAD

**Issue by jerrypeng** [scala/bug#12523]
## reproduction steps

The error can be reproduced with the following interfaces and classes:

`A.java`
```java
public interface A {
    default int foo() {
        return 0;
    }
}
```

`B.java`
```java
public interface B extends A {
    int bar();
}
```

`C.scala`
```scala
class C extends B {

  override def bar(): Int = {
    return 0
  }

  override def foo(): Int = {
    val f: () => Int = super.foo; f()
  }
}

object Test {
  def main(args: Array[String]): Unit = {
   var c = new C()
   c.foo()
  }
}
```

The compiler will generate the following error:

```
scalac: Error while emitting C.scala
assertion failed: 
  cannot invokespecial A.foo, the interface is not a direct parent.
     while compiling: /Users/jerry.peng/workspace/scala-test/src/C.scala
        during phase: jvm
     library version: version 2.12.15
    compiler version: version 2.12.15
  reconstructed args: -classpath /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/lib/tools.jar:/Users/jerry.peng/workspace/runtime/scala-test/out/production/scala-test:/Users/jerry.peng/.m2/repository/org/scala-lang/scala-reflect/2.12.15/scala-reflect-2.12.15.jar:/Users/jerry.peng/.m2/repository/org/scala-lang/scala-library/2.12.15/scala-library-2.12.15.jar -Xprint:jvm

  last tree to typer: Ident(f)
       tree position: line 10 of /Users/jerry.peng/workspace/scala-test/src/C.scala
            tree tpe: Function0
              symbol: value f
   symbol definition: val f: Function0 (a TermSymbol)
      symbol package: <empty>
       symbol owners: value f -> method foo -> class C
           call site: constructor Test in object Test in package <empty>

== Source file context for tree position ==

     7   }
     8 
     9   override def foo(): Int = {
    10     val f: () => Int = super.foo; f()
    11 //    val f: Int = C.super.foo(); f
    12   }
    13 }

```

**using Scala 2.12.15**

**using javac 1.8.0_292**

## problem

The code is valid and should be able to be compiled successfully.  Looking at the code generation from scalac compiler I see the issue if probably because of 

```
<superaccessor> <artifact> private def super$foo(): Int = C.super.foo()
```

calling 

```java
 C.super.foo()
```

is not valid in Java.  The code has to explicitly reference parent class to invoke the method i.e. `B.super.foo()`.

**Comment by rednaxelafx** [comment]
Adding a comment here: using a pure Java example:
```java
import java.util.function.*;

interface A {
    default int foo() {
        return 0;
    }
}

interface B extends A {
    int bar();
}

public class Foo implements B {
  @Override
  public int foo() {
    IntSupplier func = B.super::foo;
    return func.getAsInt();
  }

  @Override
  public int bar() { return 42; }
}
```
This code compiles fine with JDK8's javac, and the bytecode emitted for the lambda capture function is:
```
  private int lambda$foo$0();
    descriptor: ()I
    flags: ACC_PRIVATE, ACC_SYNTHETIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #4                  // InterfaceMethod B.foo:()I
         4: ireturn
      LineNumberTable:
        line 16: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   LFoo;
```
Note that it's calling `invokespecial InterfaceMethod B.foo:()I` instead of `invokespecial InterfaceMethod A.foo:()I`.

Also note that in Java if the example is changed to `A.super::foo`, then javac complains with:
```
Foo.java:16: error: not an enclosing class: A
    IntSupplier func = A.super::foo;
                        ^
1 error
```

**Comment by lrytz** [comment]
Thanks for the self-contained code. 2.13.8 has the same issue.

**Comment by SethTisue** [comment]
As shown by the pos test in Lukas's PR, the workaround is to declare `C` as `extends B with A` instead of just `extends B`.

**Comment by SethTisue** [comment]
Another workaround is to write `super[B].foo` instead of `foo.super`. I didn't remember that this syntax existed until I consulted https://scala-lang.org/files/archive/spec/2.13/06-expressions.html; it's called a "static super reference".

It's confusing that the Scala equivalent of `B.super::foo` is `super.foo[B]` rather than the `B.super.foo` one might have expected; `B.super.foo` exists as syntax, but has a different purpose — it's for getting to an outer class from an inner one.

**Comment by SethTisue** [comment]
@jerrypeng @rednaxelafx I've approved the linked PR, but perhaps you'd like to take a look as well before it's merged.

**Comment by lrytz** [comment]
> one workaround is to declare `C` as `extends B with A` instead of just `extends B`

that only works after the PR, because the compiler has logic to remove interfaces that it considers redundant :)

**Comment by snuyanzin** [comment]
@lrytz we faced it in 2.12.20 as well
I wonder if it is possible to backport fix to 2.12.x?

**Comment by SethTisue** [comment]
@snuyanzin Scala 2.12 is in minimal-maintenance mode these days which means we're highly risk-averse there and highly reluctant to merge anything that isn't a critical fix. we certainly aren't tackling non-critical backports ourselves. I hope the `super[B].foo` workaround works in your case?

**Comment by snuyanzin** [comment]
my issue is between Apache Flink and Apache Calcite
some parts of Apache Flink work with scala 2.12 and extends Apache Calcite(pure in java) interfaces/classes, since some new version new interfaces in Apache Calcite appeared and it triggered the issue...
The only work around for now I see: rewrite several classes in Apache Flink to java... (upgrade to scala 2.13 looks much more painful for now since it will touch a way more classes...)
