### ISSUE TITLE
Allow -Wconf to match "unused" details

### ISSUE THREAD

**Issue by Daenyth** [scala/bug#12551]
I'm trying to maintain a crossbuilding codebase, and in scala 2.13 the `scala.collection.compat` imports are of course marked as unused.

I tried this to silence those:
```
-Wconf:msg=scala.collection.compat:is
-Wconf:cat=unused&origin=scala.collection.compat:is
```

But neither `msg` nor `origin` seem to work to match on the error. It would be good if there would be a way to match on this

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/12326 which was just fixed in https://github.com/scala/scala/pull/9939

This use case prompted the original ticket.

**Comment by SethTisue** [comment]
@som-snytt Yay! But also, I think you could improve the PR description of scala/scala#9939 could be improved to use this an example. I've added the "release notes" label to that PR — it's more significant that I had originally realized.

**Comment by SethTisue** [comment]
@Daenyth if you want to test this in a nightly build of 2.13.9, see https://stackoverflow.com/a/40622879/86485
