### ISSUE TITLE
Iterator behavior different in Scala 2.13.8 and Scala 3.1.1

### ISSUE THREAD

**Issue by JD557** [scala/bug#12552]
## Reproduction steps

Unfortunately, I couldn't minimize this bug, but I can point to some relevant commits:

On https://github.com/JD557/minart/pull/185/commits/5cf7dc85e387e7e338e1f0ebc9e339dd1d5d7c71, running `sbt +2.13.8 imageJVM/test` will fail, while `sbt +3.1.1 imageJVM/test` will succeed. [Simply reimplementing some operations to use next/hasNext](https://github.com/JD557/minart/pull/185/commits/8ee862f2274ef49a6316618ae1011b0c2c381fb6) fixed the problem.

Scala version: 2.13.8 and 3.1.1 (not sure which one has the "bug")

## Problem

It appears that (sometimes) on 2.13.8 calling `take(n).toArray` multiple times can return an empty array (similar to what happens on `Vector.iterator`).
OTOH, on 3.1.1, calling `take(n).toArray` multiple times seems to work as `List.iterator`, and will just keep on iterating.

I understand that "calling `take(n).toArray` multiple times" is undefined behavior, but since the stdlib is the same, I expected the code to have the same undefined behavior on both compiler versions

**Comment by som-snytt** [comment]
Scala 3 uses the Scala 2 standard library but can lag, so it won't necessarily see the [latest fixes](https://github.com/scala/scala/releases/tag/v2.13.8).

The rule not to reuse iterators is hard and fast. Changing which API you reuse because the implementation behavior is different is also wrong.

**Comment by SethTisue** [comment]
Oh good call, that does seem a possible cause — 3.1.1 uses the 2.13.6 standard library. (The 2.13.8 upgrade [has been merged](https://github.com/lampepfl/dotty/pull/14258) but it's not clear to me yet if it will make a 3.1.x release or be held for 3.2.)

A lot of collections changes landed in 2.13.7 (and a few more in 2.13.8).

@JD557 Can you try it with 2.13.6 and let us know?

**Comment by SethTisue** [comment]
> it's not clear to me yet if it will make a 3.1.x release or be held for 3.2

duh... it'll be in 3.1.2. I should have checked this:

```
Welcome to Scala 3.1.2-RC2 (17.0.2, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
                                                                                                    
scala> util.Properties.versionString
val res0: String = version 2.13.8
```

**Comment by JD557** [comment]
Indeed, 2.13.6 passes the tests.

Closing this then.
Thanks for the help, this was driving me crazy.
