### ISSUE TITLE
Even hello world example is not working

### ISSUE THREAD

**Issue by pepe78** [scala/bug#12558]
Scala does not seem to work properly

pepe@pepe-MS-7C90:~$ scala -version
Scala code runner version 2.11.12 -- Copyright 2002-2017, LAMP/EPFL

pepe@pepe-MS-7C90:~/code/pepe78/python-performance$ scalac main.scala 
pepe@pepe-MS-7C90:~/code/pepe78/python-performance$ scala main
error: Compile server encountered fatal condition: javax/tools/DiagnosticListener

Code:
  object HelloWorld {
    def main(args: Array[String]) {
      println("Hello, world!")
    }
  }

pepe@pepe-MS-7C90:~$ java --version
openjdk 17.0.2 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17.0.2+8-Ubuntu-120.04, mixed mode, sharing)

![scala](https://user-images.githubusercontent.com/27255946/158655378-3cdf0406-6d5f-4299-9e7f-f8dde8403b8d.png)

OS: Ubuntu 20.04.4 LTS x86_64
Kernel: 5.13.0-35-generic

**Comment by som-snytt** [comment]
That is an ancient version of scala, and the reported error is with the compile server. `scala -help` says
```
When running a script or using -e, an already running compilation daemon
(fsc) is used, or a new one started on demand.  The -nc option can be
used to prevent this.
```
Also, on the JVM, the "main class" is used as an entry point:
```
scala -nc HelloWorld
```
I think the command was
```
fsc -shutdown
```
to terminate your compile server.
```
➜  fsc -shutdown
[Compile server exited]
```
The compile server is an old feature, and at some point, `-nc` became the default behavior.

**Comment by som-snytt** [comment]
The community forums for questions are listed at https://scala-lang.org/community/

I see that 2.11.12 does not run on JDK 17
```
➜  scala hh.scala
error: Compile server encountered fatal condition: javax/tools/ToolProvider
java.lang.NoClassDefFoundError: javax/tools/ToolProvider
```
There is a list of supported versions somewhere.

**Comment by pepe78** [comment]
this actually worked:

pepe@pepe-MS-7C90:~/code/pepe78/python-performance$ scala -nc main.scala
Hello, world!

**Comment by SethTisue** [comment]
Note that `-nc` (aka `-nocompdaemon`) is the default on Scala 2.13.0 and newer.

**Comment by pepe78** [comment]
> Note that `-nc` (aka `-nocompdaemon`) is the default on Scala 2.13.0 and newer.

Note that 'sudo apt install scala' installs 2.11.12

I just went for default

**Comment by SethTisue** [comment]
yeah, that's a sad situation — see https://github.com/scala/bug/issues/9299
