### ISSUE TITLE
Incorrect title in Pom Fix for Scala Reflect

### ISSUE THREAD

**Issue by SvenssonWeb** [scala/bug#12555]
## Reproduction steps

When looking at the following artifact page:
https://mvnrepository.com/artifact/org.scala-lang/scala-reflect

The title is Scala Compiler instead of Scala Reflect

## Problem

Caused by incorrect information in fixPom configuration:
https://github.com/scala/scala/blob/d26ea6430a79118b7b25f43951f6428c4b1ea00c/build.sbt#L427-L429

**Comment by SvenssonWeb** [comment]
Thanks, I'll try to formulate one. 
Given that it has been like this for a few years I started to wonder if it was a conscious decision.

**Comment by SethTisue** [comment]
We expect to build 2.12.6 in a few weeks. I'll start a release thread on https://contributors.scala-lang.org soon.

Thank you for the report and the fix!
