### ISSUE TITLE
Regression with "Source.drop" in library 2.13.8

### ISSUE THREAD

**Issue by flomebul** [scala/bug#12559]
## Reproduction steps

Scala version: 2.13.8
```scala
import scala.io.Source

val source = Source.fromString("Ceci est une chaîne.")

println(s"pos = ${source.pos}")
assert(source.pos == 0)

source.drop(5)

println(s"pos = ${source.pos}")
assert(source.pos == 2048 + 5)
```

## Problem

The line `source.drop(5)` has no effect: `source.pos` remain equal to `0`.

**Comment by SethTisue** [comment]
all methods on iterators invalidate the iterator — after `val source2 = source.drop(5)`, you're only supposed to use `source2` after that, `source`'s behavior is undefined

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org for questions — most unexpected behaviors aren't actually bugs.

**Comment by som-snytt** [comment]
I know I'm supposed to ask in the chat room, but what does `pos` do? There is no doc.
```
scala> val s = io.Source.fromString("abcdefghij")
val s: scala.io.Source = <iterator>

scala> s.pos
val res0: Int = 0

scala> s.next()
val res1: Char = a

scala> s.pos
val res2: Int = 2049
```
I guess the doc is on `Positioner`: "position of last character returned by next"

**Comment by som-snytt** [comment]
The default positioner says:
```
  /** Encodes a position into a single integer. */
  final def encode(line: Int, column: Int): Int = {
```
and it also promises
```
@deprecated("this class will be removed", "2.10.0")
private[scala] abstract class Position {
```
I vaguely remember that someone added some [doc](https://github.com/scala/scala/commit/5343c136e58080d72ec12a6820a0e90ac85b9a08).

**Comment by som-snytt** [comment]
To follow up that sage comment, I also noticed that the similarly ill-advised `Regex.MatchIterator` at least has a named class you can cast back to.
