### ISSUE TITLE
Bad preamble import after bumping version 2.13.6 -> 2.13.8

### ISSUE THREAD

**Issue by Denis-Savitsky** [scala/bug#12554]
## Reproduction steps

Scala version:2.13.6
Java version: 11.0.13

Not sure how to reproduce it
(didn't succeed in it)

## Problem

Bumped scala version to 2.13.8
Have in scalacOptions following:
val predef = Vector(
    "java.lang",
    "scala",
    "scala.Predef",
    "scala.util.chaining",
    "cats",
    "cats.syntax.all"
  ).mkString("-Yimports:", ",", "")
After bumping version such errors during compilation occured:
[error] bad preamble import scala.util.chaining
[error] bad preamble import cats.syntax.all
Can be solved by deleting predef from scalacOptions and manually adding necessary imports

**Comment by som-snytt** [comment]
Thanks for the report, it's actually easy to reproduce with trivial project. The failing contexts are objects inside package objects.

**Comment by som-snytt** [comment]
It's never fun to see
```
error: Error while emitting t12554.scala
null
```

**Comment by Denis-Savitsky** [comment]
> Thanks for the report, it's actually easy to reproduce with trivial project. The failing contexts are objects inside package objects. It was already broken on 2.13.7.

Okay, didn't manage to connect it with package objects as I was inundated by hundreds of such compile errors:) 
changing package objects to just object didn't help though :(

**Comment by som-snytt** [comment]
@Denis-Savitsky thanks again for using the feature. Hopefully a fix is forthcoming.
