### ISSUE TITLE
-release 8 causes java.time.Instant to have a fictitious constructor

### ISSUE THREAD

**Issue by Jasper-M** [scala/bug#12565]
## Reproduction steps

```
scalaVersion := "2.13.8"

scalacOptions ++= List("-release", "8")
```

```scala
Welcome to Scala 2.13.8 (OpenJDK 64-Bit Server VM, Java 11.0.14).
Type in expressions for evaluation. Or try :help.

scala> new java.time.Instant
java.lang.NoSuchMethodError: java.time.Instant: method 'void <init>()' not found
  ... 35 elided
```

## Problem

`java.time.Instant` doesn't have a default constructor but the compiler seems to think that it does.

**Comment by som-snytt** [comment]
This is for any earlier release, using ct.sym. (8 is sometimes a special version number. "Lucky 8".)

**Comment by som-snytt** [comment]
The condition for adding a ctor in [ClassFileParser](https://github.com/scala/scala/blame/2.13.x/src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala#L552) needs a couple of tweaks.

**Comment by som-snytt** [comment]
For some reason, there is no label for `JDK 8`.

**Comment by som-snytt** [comment]
@Jasper-M I think they just throw you "side eye".

**Comment by SethTisue** [comment]
thanks @Jasper-M for the great catch and bug report, and thanks @som-snytt for the fix 🚀

**Comment by smarter** [comment]
Same bug in Scala 3: https://github.com/lampepfl/dotty/issues/15144
