### ISSUE TITLE
Pattern guard unenables redundancy check

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12571]
## Reproduction steps

```scala
Welcome to Scala 2.13.8 (OpenJDK 64-Bit Server VM, Java 17.0.2).
Type in expressions for evaluation. Or try :help.

scala> def f(x: Int) = x match { case 42 => case 42 => }
                                                    ^
       warning: unreachable code
def f(x: Int): Unit

scala> def f(x: Int, b: Boolean) = x match { case 42 if b => case 42 if b => }
def f(x: Int, b: Boolean): Unit
```

## Problem

It could notice identical cases.

Noticed manually at https://github.com/scala/scala/blob/v2.13.8/src/compiler/scala/tools/nsc/transform/CleanUp.scala#L624

**Comment by SethTisue** [comment]
> It could notice identical cases

meh, seems outside the compiler's remit to me

**Comment by dwijnand** [comment]
The `if` can have any expression.  It happens to be just a reference to the parameter here, but I agree: I don't think we should get into studying the if expressions to start to match identical guards.
