### ISSUE TITLE
iterator.span result is confused.

### ISSUE THREAD

**Issue by sungaok** [scala/bug#12573]
## Reproduction steps

Scala version: (Is the bug only in Scala 3.x? If so, report it at https://github.com/lampepfl/dotty/issues/new/choose instead.)
2.11.12
```scala
scala> 
    val it = (1 to 10).iterator
    var n = 0
    val i=6
    val (vs, rest) = it.span { _ => n += 1; n >=3 }
    println(vs.toList.mkString(","))
    println(rest.toList.mkString(","))
when meet > only get 1,2,3,4,5,6,7,8,9,10, when I use < ,it is right ,so span predict only >

## Problem

it should be 1,2 and 3,4,5,6,7,8,9,10 .

**Comment by Ichoran** [comment]
I think you misunderstood what `span` (as opposed to `partition`) is supposed to do.  `span` cuts the collection in half.  The first half goes up to but not including the first element where the condition is false.  The second half is the rest.

So if you have a condition that is false on the first element, you get first an empty collection, and then everything else.

**Comment by som-snytt** [comment]
They finally woke Ichoran from his slumber. Why are they called iterators and not ichorators?

I benefited from the scaladoc which says you get the result of `(takewhile, dropwhile)`.

**Comment by sungaok** [comment]
if as [Ichoran] said:
that document describe"
Splits it into a pair of two iterators: one returning all elements of the prefix of it that satisfy the predicate p, the other returning all remaining elements of it." 
is too ambiguous. should you make clear that doc.

**Comment by sungaok** [comment]
so i understand these like that:
span means The first half goes up  where the condition is true, but not including the first element where the condition is false. and iterator computing, until get result don't satify predict ,and than will be the second half, it is the rest.

**Comment by som-snytt** [comment]
I think I see. You read it as: first the prefix satisfying, then the following prefix satisfying !p.

That is why the "code equivalent" worked for me. `(c.takeWhile(p), c.dropWhile(p))` assuming no side effects, so `c` is immutable.

I get "scan" and "span" mixed up because they are similar words.

**Comment by sungaok** [comment]
thanks, from result i got too confused.

**Comment by SethTisue** [comment]
@sungaok please  use https://users.scala-lang.org for questions
