### ISSUE TITLE
package-private methods ambiguate implicit conversions

### ISSUE THREAD

**Issue by armanbilge** [scala/bug#12578]
## Reproduction steps

Scala version: (Is the bug only in Scala 3.x? If so, report it at https://github.com/lampepfl/dotty/issues/new/choose instead.)

```scala
//> using scala "2.13.8"

package foo {
  package object syntax {
    implicit class BarOps1(a: Any) {
      def bar(x: Int): String = ???
    }

    implicit class BarOps2(a: Any) {
      private[syntax] def bar(x: Int): String = ???
    }
  }
}

import foo.syntax._

object Main {
  def main(args: Array[String]): Unit = {
    val a = new Object
    a.bar(42)
  }
}

```

## Problem

```
[error] ./bug.scala:20:5: type mismatch;
[error]  found   : a.type (with underlying type Object)
[error]  required: ?{def bar(x$1: ? >: Int(42)): ?}
[error] Note that implicit conversions are not applicable because they are ambiguous:
[error]  both method BarOps1 in package syntax of type (a: Any): foo.syntax.package.BarOps1
[error]  and method BarOps2 in package syntax of type (a: Any): foo.syntax.package.BarOps2
[error]  are possible conversion functions from a.type to ?{def bar(x$1: ? >: Int(42)): ?}
[error]     a.bar(42)
[error]     ^
[error] ./bug.scala:20:5: value bar is not a member of Object
[error]     a.bar(42)
[error]     ^^^^^
```

It's surprising that the conversion is ambiguous, since `BarOps2` should not have publicly visible methods. Note also that changing to `private` will solve the problem.

Credit to @balmungsan for identifying the issue while working on https://github.com/typelevel/cats/pull/4183.

**Comment by joroKr21** [comment]
I guess related to #6794

**Comment by armanbilge** [comment]
Ah, and is a dupe of https://github.com/scala/bug/issues/11787.

**Comment by joroKr21** [comment]
The place in Scalac is here: https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/typechecker/Typers.scala#L1373-L1393

It might be possible to improve by passing the expected type (`pt`) to `adaptToMemberWithArgs` and using `HasMethodMatching` when it's a function.
