### ISSUE TITLE
support Scala 3.2.0 in TASTy Reader

### ISSUE THREAD

**Issue by bishabosha** [scala/bug#12585]
It will have a new tasty minor version so will be rejected by nsc.

**Comment by SethTisue** [comment]
@bishabosha is there time to get this into 2.13.9? (tentative RC date is Mon May 9)

**Comment by bishabosha** [comment]
The first 3.2.0-RC1 is scheduled for May 17th, the final 3.2.0 stable could be a few months from now so perhaps it should  be released in 2.13.10?

**Comment by lrytz** [comment]
Are there any changes in tasty so far, or is it only the version number check that fails? Are any (more) changes planned or likely to happen? Are changes to tasty always breaking, or are they / could they be benign in that an old 2.13 compiler could safely work with a new tasty?

**Comment by bishabosha** [comment]
> Are there any changes in tasty so far

extension methods will have a new encoding (should not affect scala 2), there will also be a change to the way constructors can be encoded (implications for annotations). A few other things affect only bodies of methods.

> is it only the version number check that fails?

not if someone uses an annotation with the new constructor encoding.

> Are any (more) changes planned or likely to happen?

not immediately, maybe the erasure of union types. (`Int | Nothing`)

> Are changes to tasty always breaking, or are they / could they be benign in that an old 2.13 compiler could safely work with a new tasty?

some may be ok, but not when they affect either erasure, annotations, flags, or the byte format itself.

**Comment by SethTisue** [comment]
suppose we waited for 3.2.0-RC1, then released 2.13.9. would that have a reasonably good chance of being a sufficient amount of waiting?

waiting until May 17 is only a short delay, but waiting 6 more weeks after that is a considerable delay.

**Comment by SethTisue** [comment]
We discussed this at the Scala 2 team meeting yesterday, and we were all most comfortable with delaying 2.13.9 until after 3.2.0 final is out, rather than take any risks in this area.

**Comment by bishabosha** [comment]
support erasure of `Int | Nothing` https://github.com/lampepfl/dotty/pull/14971

**Comment by bishabosha** [comment]
also test against: https://github.com/lampepfl/dotty/pull/14840

**Comment by SethTisue** [comment]
@bishabosha now that 3.2.0-RC1 is out, is it time to address this?

**Comment by bishabosha** [comment]
yes I will start testing tomorrow

**Comment by bishabosha** [comment]
@SethTisue I have hit a curious case that `SpecializeTypes` phase forces every symbol in existence, which unfortunately then forces `scala.deriving.Mirror.fromProductTyped`, if some sort of enum/case-class from Scala 3 is referenced. This sets of a chain of forcing `scala.deriving.Mirror.ProductOf` which then sees the upper bounds of `MirroredElemTypes <: scala.Tuple` and tasty unpickler panics that it can't support that (due to erasure issues) - will need to rethink how to be more lazy here

**Comment by SethTisue** [comment]
@bishabosha will we need one more PR after 3.2.0 final is out? if so, we should leave the ticket open

**Comment by bishabosha** [comment]
Ok sure, I will remove the special case for `3.2.0` final

**Comment by SethTisue** [comment]
@bishabosha 3.2.0 is on Maven Central; can you submit the PR now?

**Comment by bishabosha** [comment]
Ill do that now
