### ISSUE TITLE
Bad external link in scaladoc

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12582]
## Reproduction steps

The doc for [TrieMap](https://www.scala-lang.org/api/current/scala/collection/concurrent/TrieMap.html) says look [here](https://lampwww.epfl.ch/~prokopec/ctries-snapshot.pdf) for details.

## Problem

The external link is 404. Probably scaladoc should be able to verify all external links. Probably scaladoc 3 needs the same feature.

**Comment by griggt** [comment]
Hmmm.  For me the link on the TrieMap page is `http://lampwww.epfl.ch/~prokopec/ctries-snapshot.pdf` (note `http` not `https`), which resolves just fine.  Is your browser converting the link to https?

**Comment by som-snytt** [comment]
Thanks for the heads up. I started from `https://scala-lang.org/`. (And never looked back.)

Normally if there is no https server Firefox will reluctantly if I wish to proceed with http.

even Firefox viewsource doesn't just give me plain text.
```
For details, see: <a href="[http://lampwww.epfl.ch/~prokopec/ctries-snapshot.pdf](view-source:http://lampwww.epfl.ch/~prokopec/ctries-snapshot.pdf)" target="[_blank]()">http://lampwww.epfl.ch/~prokopec/ctries-snapshot.pdf</a>
```
