### ISSUE TITLE
Scala 3 compiler bug ?

### ISSUE THREAD

**Issue by Y-P-** [scala/bug#12581]
object X {
  def bug[I](p:List[I], i: I):Unit = println(i)
  def bug[I](i: I, p:List[I]):Unit = println(i)
}
@main def test: Unit = {
  val l:List[String] = List("")
  X.bug(l, 2)
  X.bug(2, l)
}

This compiles (scala 3 using VS Code)
I believe it shouldn't : 'i' is Int, the list is List[String]. There is no way both parameter can simultaneously match either 'bug' signature.

**Comment by som-snytt** [comment]
Probably you want to use the chat or forum for questions.

This is ordinary overloading.

```
object X {
  def bug[I](p: List[I], i: I): Unit = println("x" + i)
  def bug[I](i: I, p: List[I]): Unit = println("y" + i)
}
@main def test: Unit = {
  val ss: List[String] = List("")
  X.bug(ss, 2)
  X.bug(2, ss)
}
```

**Comment by SethTisue** [comment]
also, this is the Scala 2 bug tracker, not the Scala 3 bug tracker

but yes, regardless, please use https://users.scala-lang.org for questions, or see https://www.scala-lang.org/community for other options
