### ISSUE TITLE
LinkedHashSet ordering broken in 2.13

### ISSUE THREAD

**Issue by jackkoenig** [scala/bug#12580]
## Reproduction steps

```scala
import scala.collection.mutable
val res = mutable.LinkedHashSet(1, 2, 3, 4, 5, 6) -- Set(2, 4)
println(res)
```

In Scala 2.12 you get (https://scastie.scala-lang.org/yLA5K8bYTIySDhRiwFFhTQ):
```
Set(1, 3, 5, 6)
```

In Scala 2.13 (tried 2.13.8 and 2.13.0) you get (https://scastie.scala-lang.org/jELVkBT1QDKV37m22vknRA):
```
LinkedHashSet(5, 1, 6, 3)
```

## Problem

I would expect the order to be maintained.

h/t @SethTisue for answering my questions and helping me minimize the issue.

**Comment by SethTisue** [comment]
@scala/collections agree this is a regression? and, anyone interested in attempting a fix?

**Comment by joshlemer** [comment]
Woah that is definitely a regression and should be fixed IMO.

**Comment by som-snytt** [comment]
I thought IMO meant "immediately mit optimization".

**Comment by som-snytt** [comment]
Is there even an informal contract that `xs op= ys` is equivalent to `xs op ys`.

**Comment by NthPortal** [comment]
that's... bad. we should also check `{im,}mutable.SeqMap`
