### ISSUE TITLE
Warning is not suppressed after error despite `-Wconf`

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12587]
## Reproduction steps

Scala version: 2.13.8

```scala
[error] ...scala/test/junit/scala/collection/convert/MapWrapperTest.scala:90:1: '=' expected.
[error]       def run(): Unit = {
[error] ^
[warn] ...scala/test/junit/scala/tools/nsc/async/AnnotationDrivenAsyncTest.scala:418:29: early initializers are deprecated; they will be replaced by trait parameters in 3.0, see the migration guide on avoiding var/val in traits.
[warn]         object late extends {
[warn]                             ^
[warn] one warning found
[error] one error found
```

## Problem

The warning is suppressed by configuration, but if there is an error (as shown, for example), the warning is emitted.

Now I'm not sure I didn't add suppressions because of this behavior, even though suppressions were already configured.

(It's also unfortunate that the error report is "old school", reporting on the innocent line because that is when the parser noticed it, instead of on the guilty line.)

**Comment by lrytz** [comment]
This rings a bell, I think I noticed this issue when working on the Scala 3 port, but then dropped the ball I guess...

**Comment by som-snytt** [comment]
This partest only errors, so it is more subtle.
```
// scalac: "-Wconf:cat=deprecation&msg=early initializers:s"

object X extends { val x = 42 } with Runnable {
  @volatile var done
  def run() = println(x)
}
```

**Comment by som-snytt** [comment]
Actually `build.sbt` selectively applies silencing early definitions, and it does not apply to `junit` subproject.

The test has a `nowarn`, but the error is issued by parser, so I'm guessing the warnings are flushed without seeing the inline suppression.

OK, `runFinished` says `// report suspended messages (in case the run finished before typer)`. `global` always notifies that the `run` is done. Then it `summarizeErrors`.

Normally, `typer` will `runReporting.reportSuspendedMessages(unit)` when done.

Why doesn't my partest show the reported behavior? Because the default `Wconf` is
```
private val WconfDefault = List("cat=deprecation:ws", "cat=feature:ws", "cat=optimizer:ws")
```
so the deprecation is only summarized. Does that imply that partest compilation does not summarize? No, `summarizeErrors` [sic] only summarizes warnings `if !hasErrors`. 

So why does the junit compile show the warning?

```
"-Xlint:-valpattern,_",
```

turns on deprecation and also sets `-Wconf:cat=deprecation:w`.

**Comment by som-snytt** [comment]
https://github.com/scala/bug/issues/12984
