### ISSUE TITLE
JConcurrentMapWrapper does not override default updateWith implementation

### ISSUE THREAD

**Issue by igabaydulin** [scala/bug#12586]
## Reproduction steps

Scala version: 2.13.8

Java's `ConcurrentMap#compute` default implementation and Scala's `concurrent.Map#updateWith` default implementation have the same logic and the supplied function may be invoked multiple times in both cases.

Java's `ConcurrentHashMap` extends `ConcurrentMap` and overrides `compute` implementation. It gives improved performance and guarantees that supplied function is invoked only once.

We can wrap `ConcurrentHashMap` into `concurrent.Map`

```scala
{
  import scala.jdk.CollectionConverters._
  val map: concurrent.Map[String, Int] = new ConcurrentHashMap[String, Int]().asScala
}
```

It will create an instance of `JConcurrentMapWrapper` which extends `concurrent.Map`, but it does not override `updateWith` default implementation using `compute` method of wrapped `ConcurrentHashMap`. Implementing overridden `updateWith` should be quite simple:

```scala
override def updateWith(key: K)(remappingFunction: Option[V] => Option[V]): Option[V] =
  Option(underlying.compute(key, (_: K, v: V) => remappingFunction(Option(v)).getOrElse(null.asInstanceOf[V])))
```

**Comment by SethTisue** [comment]
@scala/collections ?

**Comment by som-snytt** [comment]
I pushed that PR.

**Comment by som-snytt** [comment]
`JMapWrapperLike` was not correct for the concurrent mix-in, but it seems it should delegate for all wrapped maps. The other API that could be delegated is default value.

**Comment by SethTisue** [comment]
(There is now some discussion on the PR (scala/scala#10027) about what the right fix is.)
