### ISSUE TITLE
-Wunused:synthetics does not work on its own

### ISSUE THREAD

**Issue by gatisnolv** [scala/bug#12591]
## Reproduction steps

Scala version: 2.13.8

```scala
  object Example {
    def g[A: Context] = 1
  }
```
with **just** the compiler option
`"-Wunused:synthetics"`

## Problem

I expect the context bound to be reported as 'never used', but there is no warning.

If i also add the compiler option `"-Wunused:implicits"` (or `"-Wunused:params"` which combines both synthetics and implicits, as well as explicits), there is a warning.

I guess this follows from context bounds being "synthetic implicit parameters" (I'm just parroting [Warnings.scala](https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/settings/Warnings.scala) here), so it needs `"-Wunused:implicits"` in the current implementation as well, but I found it strange that this compiler option does not work on its own. Can we have warnings for unused synthetics without enabling warnings for unused non-synthetic (organic? (a quick joke, sorry 😄)) implicit parameters?

**Comment by SethTisue** [comment]
@som-snytt ?

**Comment by som-snytt** [comment]
I'm not sure whether the behavior was intended. `-Wunused:params,-synthetics` might have been the use case, for noise reduction.

But I think the flag check can be moved to `isWarningOnFor`; currently it filters earlier, in `isSyntheticWarnable`. Then, as requested, `-Wparams` means `explicits` (not implicit), `implicits` (not synthetic), `synthetics` (implicit). 

As always, thanks for using `-Wunused`!
