### ISSUE TITLE
Vector.prependedAll returns Vector in illegal state

### ISSUE THREAD

**Issue by ansvonwa** [scala/bug#12598]
## Reproduction steps

Scala version: 2.13.3 to 2.13.8, latest [`7952071`](https://github.com/scala/scala/tree/7952071b88a85e2502e9ecd4e8bd57040d9448f5)

```scala
val v = Vector(1 to 10000: _*)
val (pre, suf) = v.splitAt(1) // split v ...
val v2 = pre ++: suf // ...and concat again
println(s"${v(1023)} becomes ${v2(1023)} 👀") // prints "1024 becomes 1025 👀"
v2(v2.length-1) // ArrayIndexOutOfBoundsException
```

## Problem

`v2.len12` is 1023, but should be 1024 (as `v2.prefix1.length + v2.prefix2.length * WIDTH = 32 + 31 * 32 = 1024`).
This is an illegal state and yields unexpected behavior as seen above.

**Comment by som-snytt** [comment]
I took a casual look. I'll keep looking as necessary.
