### ISSUE TITLE
Compiler generates inefficient accessors for final classes

### ISSUE THREAD

**Issue by strelec** [scala/bug#12604]
## Reproduction steps

Compile this:

```scala
final class Example(val a: Int) {
  def square: Int = a * a
}
```

## Problem

Since the class is final, compiler generates something like this (java code):

```java
final class Example {
  final int a;
  int a() {
    return a;
  }
  int double {
    return a() * a();
  }
}
```

While, since a cannot be overriden, I would expect compiler to access the field directly:

```java
final class Example {
  final int a;
  int a() {
    return a;
  }
  int double {
    return a * a;
  }
}
```

I am not sure how much JVM penalizes such method indirection and whether this is worth fixing.

**Comment by som-snytt** [comment]
I was going to say `-opt`, but I had to go to great lengths to enable this simple inlining.

However, they also say that `-opt` prefers to let the JVM optimize where it can, such as in this example.
