### ISSUE TITLE
StringBuilder operations return StringBuilder instead of this.type

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12608]
## Reproduction steps

```scala
[warn] .../scala/src/compiler/scala/reflect/quasiquotes/Placeholders.scala:37:16: unused value
[warn]       sb.append(value)
[warn]                ^
```

## Problem

`-Wnonunit-statement` warns unnecessarily because `append` is not defined with result `this.type`, unlike `Growable` et al.

**Comment by SethTisue** [comment]
would fixing it be binary compatible? @scala/collections

**Comment by som-snytt** [comment]
It's such a striking difference, I wondered if there was a reason behind it. Besides the universal reason, history.

**Comment by Ichoran** [comment]
I think it would be bytecode compatible--`this.type` is just the type of the class in bytecode.

Since dependent types aren't inferred, I think it would also be backwards compatible in source (and with Scala type information) but not forwards compatible.

```scala
def whatever(sb: StringBuilder): sb.type =
  sb append "whatever"
```

would compile under the new version of the library but not under the old version.

**Comment by som-snytt** [comment]
TIL
```
scala> def f(s: String): s.type = s
def f(s: String): s.type

scala> List("x").foreach(f)
                         ^
       error: method with dependent type (s: String): s.type cannot be converted to function value

scala> List("x").foreach(f(_))

scala>
```
even if you discard the result.

**Comment by som-snytt** [comment]
`IterableOnceOps`
```
def addString(b: StringBuilder, start: String, sep: String, end: String): StringBuilder
```
should be
```
def addString(b: StringBuilder, start: String, sep: String, end: String): b.type
```
