### ISSUE TITLE
sys.process: parser for shell tokenization mishandles some quotes+escapes

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#12611]
In the sys.process context, this is a 2.13 regression; the code in question was added on 2.13.x in scala/scala#7452 (2018)

(Though the copy of the code in `CommandLineParser` has had the bug for longer; we should fix it both places.)

customer writes:

> The bug is that the parser for shell tokenization doesn't check for escape characters the first time it encounters a quote

```scala
scala 2.13.8> import sys.process._
import sys.process._

scala 2.13.8> """echo '\"hello world!\"' """.!!
val res1: String =
"\"hello world!\"
"
```

so far so good, but then:

```scala
scala 2.13.8> """echo \"hello world!\" """.!!
scala.sys.process.Parser$ParseException: Unmatched quote
  at scala.sys.process.Parser$.tokenize(Parser.scala:111)
  at scala.sys.process.ProcessCreation.apply(Process.scala:95)
```

which worked in 2.12.16.

**Comment by som-snytt** [comment]
Yes, `sys.process` was supposed to be split off. It could go into `scala.runtime`, as there is a third fork for Scala 3.

**Comment by SethTisue** [comment]
🎵 Lost my closing quote, What'll I do? `skipToDelim`, my darlin’ 🎵

**Comment by som-snytt** [comment]
One more question, why is this desirable:
```
scala> """echo \"hello world!\" """.!!
val res0: String =
"\"hello world!\"
"
```
when
```
➜  ~ echo \"hello world\"
"hello world"
```
I had to remove the bang from the string because of "event" handling which I neither use nor grok.

If the point was to mimic a shell, it should strip the backslashes, right?
