### ISSUE TITLE
Murmurhash3 Implementation Bug

### ISSUE THREAD

**Issue by mmoghad** [scala/bug#12616]
I am using Scala 2.13.7 

## Problem
The Murmurhash3 library function seems to have a bug. The output of the indexedSeqHash called on a sequence of integers returns results that are different from the original C-based implementation (https://github.com/aappleby/smhasher/blob/master/src/MurmurHash3.cpp).

I have tracked the bug to the call to finalizeHash(). Indeed, the parameter "length" here represents the number of elements in the input array of integers (1 per int), but the original C code uses the total number of bytes. For instance, if the array has a single integer, the call to finalizeHash() should pass 4 as parameter "length". 

This might be a misunderstanding from my part on what indexedSeqHash should do, but then at least the documentation should be updated to explain the its functioning and maybe reference the source of the implementation. 

With kind regards 
MM

**Comment by Ichoran** [comment]
This is not only not a bug, but an essential feature given that sequences of numbers of different storage size but the same value are equal, and therefore require the same hash value.

I guess it could be documented that this is different from C.

**Comment by SethTisue** [comment]
please use https://users.scala-lang.org for questions; come to scala/bug when you are nearly certain something is a bug (and believe you're in a position to judge that it is a bug)

**Comment by SethTisue** [comment]
we don't keep "the documentation of X could be improved" tickets open, but regardless, pull requests with documentation improvements are immensely welcome
