### ISSUE TITLE
Not recognized subtyping of implicits due to failed unification of a concrete type with an equal type member

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12610]
## Reproduction steps

Scala version: 2.13.8

```scala
	trait Subject {
		type Params
	}
	class Paramless extends Subject { type Params = Unit }
	trait Evidence[X, +R]

	implicit def paramless[X <: Subject { type Params = Unit }] :Evidence[X, Seq[Unit]] = ???
	implicit def params[X, P](implicit ev :X <:< Subject { type Params = P }) :Evidence[X, List[P]] = ???

	def evidence[X, R](x :X)(implicit ev :Evidence[X, R]) = ()

	evidence(new Paramless)
```

## Problem
```
ambiguous implicit values:
 both method paramless in object Playground of type [X <: Playground.Subject{type Params = Unit}]Playground.Evidence[X,Seq[Unit]]
 and method params in object Playground of type [X, P](implicit ev: X <:< Playground.Subject{type Params = P}): Playground.Evidence[X,List[P]]
 match expected type Playground.Evidence[Playground.Paramless,Any]
	evidence(new Paramless)
```
The type of the first implicit definition after typeApply: `Evidence[Paramless, Seq[Unit]]`.
The type of the second implicit definition: `Evidence[Paramless, List[_1.Params]] forSome { val _1 :Paramless }`
The second type is clearly a strict subtype of the first one, yet the implicit definitions are ambiguous.

**Comment by joroKr21** [comment]
This subtyping check happens before the recursive implicits are resolved and the type parameters constrained by them. Otherwise the resolution of which implicit takes priority would have to depend on the current scope and implicit resolution would have to backtrack / explore all possibilities and explode in complexity. To make it work you have to use a type bound instead of implicit evidence:

```scala
implicit def params[X <: Subject { type Params = P }, P]: Evidence[X, List[P]] = ???
```

**Comment by joroKr21** [comment]
That is to say the compiler doesn't know that `<:<` conatraints `X` to be a subtype of something - `<:<` is a user-land implicit like any other that just happens to be defined in the standard library.

**Comment by noresttherein** [comment]
@joroKr21 
The `<:<` is used to guide the inferer so it can guess properly `type Params = P`.
Scala 2 won't infer this `[X <: Subject { type Params = P }, P]` in mode without an expected type. However, adding an extra `X <:< Subject { type Params = P }` gives the compiler 'a second go' at inference: it infers type `X` as a whole first, and having that, attempts to search for an implicit value for `<:<` and is able to infer `P` in the process. It doesn't always work, sometimes smarter tricks are needed, but it works often enough and allows much more complex implicit definitions than would be possible without it.

**Comment by joroKr21** [comment]
> You mean that for the subtyping check for implicit priority only type parameters of the 'expected type' are inferred? So, in this case, the check would be between:

```scala
Evidence[Paramless, Seq[Unit]]
Evidence[Paramless, List[P]]
```

> And not P <:< Unit, so there is no subtype relation between them?

It's more like:

```scala
Evidence[X, Seq[Unit]] forSome { type X <: Subject { type Params = Unit } }
Evidence[X, List[P]] forSome { type X; type P }
```

But yes, there is no subtype relation.

> Adding the bound as you suggest changes nothing. In particular, P won't ever be inferred and this implicit will never be used unless we have a type to match List[P] against - which we don't. I think we also need to be careful here so that P is not inferred as Nothing and thus make it a subtype in this case, but I don't know the details of how this works.

I just tried and it compiled for me but I guess it still picked `paramless`. In the end if you want to prioritize such complex implicits (generic, taking type parameters and other implicit arguments) you should put the higher priority one in a subclass. Also take a look at the `Aux` pattern in Scala to fix issues with inference of type members like this one. It's heavily used in Shapeless but there should be also some articles online.

**Comment by noresttherein** [comment]
You were right, it was a typo on my part, sorry. But as we both feared, `paramless` is chosen 'incorrectly':
```
Expr[Unit](Playground.this.evidence(new Playground.this.Paramless())(Playground.this.paramless))
```
It probaby will work in Scala 3, as this is likely to the `Nothing` == 'unknown' hack.

I am aware of `Aux`, although frankly it's much ado about nothing, as inlining the `Aux` definition works just as well.
Unfortunately, it cannot be applied to my real problem, as both type parameters are input types. This is a minimized example.
Also, unfortunately, introducing precedence through implicit placement can be problematic in more complex schemes.
The two ways of introducing precedence (in a supertype of a companion object and in  a companion object of a supertype of the companion class) don't mix. If we have `X <:< Y` and their companions introduce `params/paramless` implicits for `Evidence[X, _]`/`Evidence[Y,_]`, then I can't move `paramless` to a `LowerPriorityXImplicits` and `LowerPriorityYImplicits` because it will introduce amiguity between `X.paramless` and `Y.params`, as there is no implicit precedence relation between them.

**Comment by noresttherein** [comment]
Anyway, it may be good to update the SLS with the info you provided here. It certainly clears a lot of my past head scratchers.

**Comment by SethTisue** [comment]
Closing since it doesn't sound like we have agreement there is a bug here.

(Spec improvements are always welcome, but we don't keep open tickets on would-be-nice doc improvements.)
