### ISSUE TITLE
boolean match debug 

### ISSUE THREAD

**Issue by ruhuansanmei** [scala/bug#12636]
## Reproduction steps

Scala version: 2.12.10

```scala
    true match {
      case false => println("this is false")
      case true => println("this is true")
    }

    false match {
      case false => println("this is false")
      case true => println("this is true")
    }

    "1" match {
      case "1" => println("this is 1")
      case "2" => println("this is 2")
    }
```

## Problem

![图片](https://user-images.githubusercontent.com/17924820/187055634-63b958a0-897f-4627-a450-f8a825f0e920.png)
![图片](https://user-images.githubusercontent.com/17924820/187055653-13af7e46-4264-48f9-962d-4d9a95b11b00.png)
![图片](https://user-images.githubusercontent.com/17924820/187055666-572d552e-6ee1-4720-bfd1-e2d577678e4e.png)
when i debug in IDEA, I just see there are break-point is not available， but the executed result is right.

**Comment by SethTisue** [comment]
This bug tracker is for bugs in Scala itself only. You'd need to report an IntelliJ problem in their bug tracker. See also https://scala-lang.org/community for ideas on where to ask questions.
