### ISSUE TITLE
Compiles but not run cause by error java.lang.ClassNotFoundException: java.sql.SQLException

### ISSUE THREAD

**Issue by karo06** [scala/bug#12634]
## Reproduction steps

Just migrated one project from java8 to java 11 compiles ok but when running using script command got an error ClassNotFoundException

command 
scala -nobootcp -classpath %CLASSPATH% com.myclass.MyClassBoot

Scala version: 2.11.12

## Problem

Code compiling good with JDK 8 and 11, won’t run on JDK11, shows error java.lang.ClassNotFoundException: java.sql.SQLException

**Comment by SethTisue** [comment]
Please use https://users.scala-lang.org for questions
