### ISSUE TITLE
Unstable forward reference to a function defined inside a function

### ISSUE THREAD

**Issue by tomoikey** [scala/bug#12637]
## Reproduction steps

Scala version:

**My Environment**
- Scala: 2.13.8
- Java Version: 15.0.7, 11.0.15

## Problem
```scala
  // compilation will succeed
  def noProblem: String = {
    val y: String = ""
    lazy val x = f("")

    def f(i: String): String = i
    "hello"
  }

  // compilation will fail
  def problem: String = {
    lazy val x = f("")
    val y: String = ""

    def f(i: String): String = i
    "hello"
  }
```

A compile error occurred when forward referencing a function defined inside a function.
I thought it was an evaluation order problem and tried lazy evaluation using "lazy val". When a variable is declared before the forward referenced line, the compilation succeeds. However, when a variable is declared after the forward referenced line, a compile error occurs. Is this a language specification? Or is it a bug in Scala? 
Thanks.

**Comment by som-snytt** [comment]
Yes, see the beginning of https://scala-lang.org/files/archive/spec/2.13/04-basic-declarations-and-definitions.html

`f` may rely on `y`. `def f(i: String): String = i+y`. You can make everything lazy.

Normally questions should be asked on one of the forums, where they invite discussion.

**Comment by SethTisue** [comment]
> Normally questions should be asked on one of the forums

seconded. https://users.scala-lang.org, or see https://scala-lang.org/community for other options
