### ISSUE TITLE
-Wconf src filter applies to the absolute path of sources instead of relative path

### ISSUE THREAD

**Issue by gaeljw** [scala/bug#12631]
## Reproduction steps

Scala version: 2.13.7

- Clone the repository https://github.com/gaeljw/sbt-target-issue
- Run `cd anothername/seed && sbt clean compile`, a compilation error is correctly raised to a deprecated usage
- Run `cd target/seed && sbt clean compile`, no compilation error is raised

The issue disappear when removing the scalac flag `-Wconf:src=target/.*:silent`.

## Problem

As there is a `target` in the absolute path of the second projet, it incorrectly apply the `-Wconf` filter and thus ignore all warnings.

I believe the `-Wconf` filter should apply only on the relative path of the project.

I've seen the documentation mention a `rootdir` flag but I was not able to use it, I always get _bad option_ error and not sure how it should be used anyway.

Does someone know if this is a bug and/or how to workaround it?

**Comment by som-snytt** [comment]
I had never tried `src` filter, but I usually need to read `-Wconf:help` even for config I have used before.

This works in the `target` build:
```
scalacOptions ++= Seq("-rootdir", "/home/.../sbt-target-issue/target/seed"),
```
That is, it does not suppress the warning.

It also works just to say
```
scalacOptions ++= Seq("-rootdir", "."),
```

The help says
```
   - Source file name: src=src_managed/.*
    If `-rootdir` is specified, the regex must match the canonical path relative to the
    root directory. Otherwise, the regex must match the canonical path relative to any
    path segment (`b/.*Test.scala` matches `/a/b/XTest.scala` but not `/ab/Test.scala`).
    Use unix-style paths, separated by `/`.
```
With `-rootdir` set, `target/.*` would match a relative path under `seed` that begins `target`. Otherwise, it would match any path that has a component `target`, as you discovered with a repo inside a dir named `target`.

**Comment by gaeljw** [comment]
Thanks a lot @som-snytt for your quick and very detailed answer. I will try that tomorrow morning.

2 questions if I may:
- is there any other impact of using `rootdir`?
- does it make sense at all to look at absolute path? I'm having a hard time finding a good reason for that. I'm not saying this has to be fixed but I'd like to understand the reason for this behaviour.

**Comment by som-snytt** [comment]
I just edited my answer to say the compiler doesn't know about any roots except sourcepath.

I think `-rootdir` was added just for this purpose. Worth adding that `-Wconf` works differently in Scala 3 because ... reimplemented, or perhaps to rethink these ergonomic issues.

**Comment by lrytz** [comment]
> * does it make sense at all to look at absolute path?

Without `-rootdir` the compiler has no other hint what path segments to ignore...

**Comment by gaeljw** [comment]
Just realized I didn't confirm but the solution proposed by @som-snytt works absolutely fine :ok_hand:
