### ISSUE TITLE
A public regular Java class cannot be found by the Scala compiler

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [scala/bug#12638]
## Reproduction steps

Scala version: 2.13.8

Interactive session with Ammonite 2.5.4 and Java 17:

```
$ amm
Welcome to the Ammonite Repl 2.5.4 (Scala 2.13.8 Java 17.0.4)

@ import $ivy.`io.kubernetes:client-java:16.0.0`
import $ivy.$

@ import io.kubernetes.client.openapi.models.V1JobBuilder 
cmd1.sc:51: object V1JobBuilder is not a member of package io.kubernetes.client.openapi.models
possible cause: maybe a semicolon is missing before `object V1JobBuilder`?
import io.kubernetes.client.openapi.models.V1JobBuilder
       ^
Compilation Failed
```

Scala isn't able to access a class that does exist and is public: https://github.com/kubernetes-client/java/blob/v16.0.0/fluent/src/main/java/io/kubernetes/client/openapi/models/V1JobBuilder.java, and I think it hasn't been mispelled.

## Problem

Related Ammomite issue:
https://github.com/com-lihaoyi/Ammonite/issues/1287

At first, I've believed that the problem is related to Ammonite, until I've tried SBT and found the same problem.

**Comment by SethTisue** [comment]
scala-cli command line to reproduce this is `scala-cli repl -S 2.13.8 -d "io.kubernetes:client-java:16.0.0"`

```
scala> Class.forName("io.kubernetes.client.openapi.models.V1JobBuilder")
java.lang.ClassNotFoundException: io.kubernetes.client.openapi.models.V1JobBuilder
```

I think you're mistaken and the class simply doesn't exist in the dependencies you've provided. You can verify it for yourself by inspecting the contents of the JARs — the main JAR that you've brought in, and the JARs it depends on. In this case, I see a lot of classes named `io/kubernetes/client/openapi/models/V1Job` and such in `client-java-api-16.0.0.jar`, which `client-java` depends on.
