### ISSUE TITLE
enum patmat warns not exhaustive with flag -Xlint

### ISSUE THREAD

**Issue by lucas-tubi** [scala/bug#12639]
## Reproduction steps

Scala version: `2.13.8`, latest `2.13.x` branch.

Execute the code with `scala -Xlint`:
```scala
object T extends Enumeration {
  val A = Value("a")
  val B = Value("b")
}

T.A match {
  case T.A => ()
  case T.B => ()
}
```

## Problem
It shows the warning:
```
       warning: match may not be exhaustive.
       It would fail on the following input: (x: T.Value forSome x not in (A, B))
```
Expect no warning.

**Comment by som-snytt** [comment]
The lint is `-Xlint:strict-unsealed-patmat`. `Enumeration` is not a true enum, as it can be dynamically augmented.

Use `(T.A: @unchecked) match` to suppress.

**Comment by SethTisue** [comment]
Better support for pattern matching is one of the reasons that Scala 3 replaced the old, library-only `scala.Enumeration` with a new, compiler-supported `enum` keyword. https://docs.scala-lang.org/scala3/reference/enums/enums.html

**Comment by SethTisue** [comment]
Note that this has been reported before, multiple times: https://github.com/scala/bug/issues/7206, https://github.com/scala/bug/issues/12244, https://github.com/scala/bug/issues/10680

Before opening a bug, please take the trouble to search past bug reports to see if it's a duplicate. If you aren't willing to go through that effort, you're essentially just asking a question, not filing a bug report that is useful to the project. Questions should go to https://users.scala-lang.org, not here — or see https://scala-lang.org/community for other options.

**Comment by lucas-tubi** [comment]
sorry for the overreport. thanks for the explanation.
