### ISSUE TITLE
[2.13.9] Can't reference `sun.` package classes with `-release` option

### ISSUE THREAD

**Issue by xuwei-k** [scala/bug#12643]
## Reproduction steps

```scala
class A {
  classOf[sun.misc.Unsafe]
}
```

### Java 8 without `-release` option

Success

```sh
$ java -version
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Zulu 8.62.0.19-CA-macos-aarch64) (build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (Zulu 8.62.0.19-CA-macos-aarch64) (build 25.332-b09, mixed mode)
$ scala -version
Scala code runner version 2.13.9 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.
$ scalac A.scala 
A.scala:2: warning: a pure expression does nothing in statement position; multiline expressions may require enclosing parentheses
  classOf[sun.misc.Unsafe]
         ^
1 warning
```

### Java 8 with `-release:8` option

Success

```sh
$ scalac -release:8 A.scala
A.scala:2: warning: a pure expression does nothing in statement position; multiline expressions may require enclosing parentheses
  classOf[sun.misc.Unsafe]
         ^
1 warning
```

### Java 11 without `-release` option

Success

```sh
$ java -version
openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
$ scala -version
Scala code runner version 2.13.9 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.
$ scalac A.scala           
A.scala:2: warning: a pure expression does nothing in statement position; multiline expressions may require enclosing parentheses
  classOf[sun.misc.Unsafe]
         ^
1 warning
```

### Java 11 with `-release:11` option

Success

```sh
$ java -version 
openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
$ scala -version
Scala code runner version 2.13.9 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.
$ scalac -release:11 A.scala
A.scala:2: warning: a pure expression does nothing in statement position; multiline expressions may require enclosing parentheses
  classOf[sun.misc.Unsafe]
         ^
1 warning
```

### Java 11 with `-release:8` option

Failure !?

```sh
$ java -version            
openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
$ scala -version            
Scala code runner version 2.13.9 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.
$ scalac -release:8 A.scala 
A.scala:2: error: not found: value sun
  classOf[sun.misc.Unsafe]
          ^
1 error
```

### Java 11 with `-target:jvm-1.8` option

Success

```sh
$ java -version                
openjdk version "11.0.16" 2022-07-19 LTS
OpenJDK Runtime Environment Zulu11.58+15-CA (build 11.0.16+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.58+15-CA (build 11.0.16+8-LTS, mixed mode)
$ scala -version                
Scala code runner version 2.13.9 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.
$ scalac -target:jvm-1.8 A.scala
A.scala:2: warning: a pure expression does nothing in statement position; multiline expressions may require enclosing parentheses
  classOf[sun.misc.Unsafe]
         ^
warning: 1 deprecation; re-run with -deprecation for details
2 warnings
```

**Comment by lrytz** [comment]
It's the same with Scala 2.13 and Scala 3. When using Java 11 with `-release:8`, the `ct.sym` file that's put on the classpath (instead of `rt.jar`) contains Java 8 symbols, but only the official JDK. So `sun` is missing. (That's what I remember, maybe someone has a good reference here.)

**Comment by lrytz** [comment]
> It's the same with Scala 2.13

Sorry, that didn't make sense.

**Comment by som-snytt** [comment]
Maybe the point is to undeprecate `-target`? Or is there a convenient `-classpath` idiom?

**Comment by SethTisue** [comment]
Does `javac -release` behave the same way?

**Comment by SethTisue** [comment]
> Maybe the point is to undeprecate `-target`?

Huh?

**Comment by som-snytt** [comment]
`-target` says "emit class file of version N, but I want to use arbitrary classes from the JDK and take my chances".

If that is a reasonable use case, then either undeprecate the compiler option or make it easy to put certain packages of compelling utility on the class path when using `-release`.

**Comment by lrytz** [comment]
> Does `javac -release` behave the same way?

yes, with `javac --release 8`, `sun.misc.Unsafe` is not visible

**Comment by SethTisue** [comment]
If `javac` is the same, then I think we should just close this ticket.

**Comment by SethTisue** [comment]
> make it easy to put certain packages of compelling utility on the class path when using -release

If anyone figures out what incantation is currently needed, please share!

(What do `javac` users do in this case? I did a bit of Googling for prior art but failed to find something, but maybe I didn't try hard enough.)

**Comment by He-Pin** [comment]
https://github.com/akka/akka/blob/a6863e9ed5378d52cb16f386db4e137f0a02c170/project/JdkOptions.scala#L47-L58

@SethTisue @som-snytt cc

**Comment by som-snytt** [comment]
The inliner needs actual classfiles and accommodates `-release`, maybe there could be a fallback option in the case of missing symbols (or a list of allowed symbols).

**Comment by som-snytt** [comment]
We're back in business, baby!

**Comment by He-Pin** [comment]
Rocks the Scala
