### ISSUE TITLE
Upgrading from Scala `2.13.8` -> `2.13.9` causes false positive claiming variable never used

### ISSUE THREAD

**Issue by Christewart** [scala/bug#12649]
https://github.com/bitcoin-s/bitcoin-s/actions/runs/3113227587/jobs/5047592957

The variable `processOpt` is used in the same file `NativeProcessFactory`

https://github.com/bitcoin-s/bitcoin-s/blob/2a0cb57cf187245c954f9cb952cf603d1cf06cc1/app-commons/src/main/scala/org/bitcoins/commons/util/NativeProcessFactory.scala#L14

**Comment by SethTisue** [comment]
is this different from #12646?

if it is, can you supply a  minimized test case with no external dependencies?

**Comment by som-snytt** [comment]
That looks the same. It's warning on the synthetic parameter to the setter, which is indeed unused in traits.
