### ISSUE TITLE
[2.13.9] @nowarn("cat=deprecation") no longer works if deprecation coming from Java source

### ISSUE THREAD

**Issue by mdedetrich** [scala/bug#12648]
## Reproduction steps

Scala version:  2.13.9

```scala
@deprecated("3.0") @nowarn("cat=deprecation")
val MessageFormatVersionDoc = TopicConfig.MESSAGE_FORMAT_VERSION_DOC
```

```java
public class TopicConfig {
    @Deprecated
    public static final String MESSAGE_FORMAT_VERSION_DOC = "[DEPRECATED] Specify the message format version the broker " +
        "will use to append messages to the logs. The value of this config is always assumed to be `3.0` if " +
        "`inter.broker.protocol.version` is 3.0 or higher (the actual config value is ignored). Otherwise, the value should " +
        "be a valid ApiVersion. Some examples are: 0.10.0, 1.1, 2.8, 3.0. By setting a particular message format version, the " +
        "user is certifying that all the existing messages on disk are smaller or equal than the specified version. Setting " +
        "this value incorrectly will cause consumers with older versions to break as they will receive messages with a format " +
        "that they don't understand.";
}
```

The PR that found this problem can be found at https://github.com/apache/kafka/pull/12675 and the build can be seen at https://ci-builds.apache.org/blue/organizations/jenkins/Kafka%2Fkafka-pr/detail/PR-12675/4/pipeline/12.

The failure 

## Problem

There seems to be a regression with the `@nowarn` annotation, when updating Kafka's Scala version to 2.13.9 the following error message appears

```
[2022-09-22T14:14:21.289Z] [Error] /home/jenkins/workspace/Kafka_kafka-pr_PR-12675/core/src/main/scala/kafka/log/LogConfig.scala:220:23: @nowarn annotation does not suppress any warnings

[2022-09-22T14:14:21.289Z] [Error] /home/jenkins/workspace/Kafka_kafka-pr_PR-12675/core/src/main/scala/kafka/log/LogConfig.scala:255:23: @nowarn annotation does not suppress any warnings

[2022-09-22T14:14:21.290Z] [Error] /home/jenkins/workspace/Kafka_kafka-pr_PR-12675/core/src/main/scala/kafka/server/KafkaConfig.scala:569:4: @nowarn annotation does not suppress any warnings
```

This is with no changes to the Scala source code whatsoever. I suspect this may be due to a change in handling of Java source code within scalac since the deprecated code is coming from Java.

**Comment by SethTisue** [comment]
@som-snytt does this ring any bells for you?

**Comment by som-snytt** [comment]
No, that's just the tinnitus. I'll take a look, as by coincidence I'm currently reading "Kafka on the Shore."

**Comment by danicheg** [comment]
Another case of marking `@nowarn` as redundant after updating Scala to 2.13.9:
```
/home/runner/work/mouse/mouse/shared/src/main/scala/mouse/MouseFunctions.scala:35:15: @nowarn annotation does not suppress any warnings
[error]   def ignore(@nowarn a: Any): Unit = ()
```
It's from [this](https://github.com/typelevel/mouse/actions/runs/3104153151/jobs/5028297880#step:10:33) CI run.

**Comment by som-snytt** [comment]
@danicheg That is intended, to reduce warnings for trivially-implemented methods. The previous complaint was, "This is a default implementation and will be overridden with a real implementation." Also, "it's obvious" that the parameter is unused and not shadowed in some pernicious way.

**Comment by danicheg** [comment]
> The previous complaint was, "This is a default implementation and will be overridden with a real implementation."

Ahem. I'm biased, but this take is weak :) But okay. Shouldn't that behavior be ported to 2.12 as well?

**Comment by som-snytt** [comment]
@danicheg Maybe it is an easy backport. I thought about this later in the day when someone's trivial example was
```
def f(x: Int) = ()
```
I've forgotten what was demonstrated, but you don't want to turn off warnings just to write example code.

**Comment by som-snytt** [comment]
Deprecated usages inside a deprecated element don't warn, modulo bugs. The linked PR links to the fix in 2.13.9.

So this ticket is strictly a progression and not a feature change.

**Comment by mdedetrich** [comment]
@som-snytt @lrytz I am confused regarding the fix, I just looked at the linked PRs diff and from what I can tell only tests/checks were added with no actual changes to Scala compiler?

**Comment by lrytz** [comment]
@mdedetrich what reported is not a bug, it's a progression. Whithin a scope of something deprecated (`val MessageFormatVersionDoc` in your example), the compiler doesn't issue any deprecation messages. This was always the case, https://github.com/scala/scala/pull/9960 implements a fix of this behavior, a case that was missed.

**Comment by mdedetrich** [comment]
Ah I understand, would it be possible to implement the same fix for Scala 2.12 series? Problem we have now is that the behaviour is different between Scala 2.12.x and 2.13.x which means that aside from hacky workarounds we have to disable error on warnings entirely (not desirable but of course possible)

**Comment by som-snytt** [comment]
The workaround is `-Wconf`. The scaladoc https://www.scala-lang.org/api/2.13.9/scala/annotation/nowarn.html says `cat=unused-nowarn`. Presumably `site=MyThing`.

**Comment by som-snytt** [comment]
Just to link that the behavior is in the spec at https://scala-lang.org/files/archive/spec/2.13/11-annotations.html#deprecation-annotations

> Deprecated warnings are suppressed in code that belongs itself to a definition that is labeled deprecated.

**Comment by som-snytt** [comment]
I only just noticed that the `mouse` example is for a dummy function to make value discard explicit.

The "latest" syntax ergonomix [sic] is to annotate explicitly:
```
def g(): G = ???
def f(): Unit = g(): Unit
```

**Comment by som-snytt** [comment]
`@deprecated("3.0")` sets the message, not the `since`.
