### ISSUE TITLE
[2.13.9] cannot compile call to java.net.URLDecoder.decode

### ISSUE THREAD

**Issue by yanns** [scala/bug#12654]
## Reproduction steps

Scala version: 2.3.19

```scala
scala> java.net.URLDecoder.decode("hello", java.nio.charset.StandardCharsets.UTF_8)
                                                                             ^
       error: type mismatch;
        found   : java.nio.charset.Charset
        required: String
```

## Problem

UTCDecoded.decode method exists:
```
public static String decode(String s, Charset charset) {
```

and this code is compiling with scalac 2.13.8:

```scala
scala> java.net.URLDecoder.decode("hello", java.nio.charset.StandardCharsets.UTF_8)
val res0: String = hello
```

**Comment by He-Pin** [comment]
![image](https://user-images.githubusercontent.com/501740/192205868-ef4d281d-6029-4c59-8af1-2608929ec8ec.png)

**Comment by He-Pin** [comment]
@yanns I see there is no overloading method on JDK 8.

**Comment by yanns** [comment]
@He-Pin 
You're right, it seems to have been introduced in JVM 10:
```
     * @since 10
     */
    public static String decode(String s, Charset charset) {
```

So I just need to update the JVM version to use for scalac. I'll try.

**Comment by yanns** [comment]
Good finding.
```
ThisBuild / scalacOptions ++= Seq("-release", "11")
```
fixes the issue for example.
