### ISSUE TITLE
`collection.Seq` factory doesn't preserve `collection.Seq`s

### ISSUE THREAD

**Issue by lrytz** [scala/bug#12669]
```scala
Welcome to Scala 2.13.10 (OpenJDK 64-Bit Server VM, Java 17.0.1).
Type in expressions for evaluation. Or try :help.

scala> import collection.mutable
import collection.mutable

scala> val s: collection.Seq[Int] = mutable.ArraySeq(1)
val s: scala.collection.Seq[Int] = ArraySeq(1)

scala> val es = s.to(collection.Seq)
val es: scala.collection.Seq[Int] = List(1)

scala> es eq s
val res0: Boolean = false
```

**Comment by lrytz** [comment]
Hmm, probably that's by design, `to` is can return the same instance for immutable collections, but is otherwise supposed to create a copy.

```
scala> val s = mutable.ArraySeq(1,2,3)
val s: scala.collection.mutable.ArraySeq[Int] = ArraySeq(1, 2, 3)

scala> s.to(mutable.Seq) eq s
val res1: Boolean = false
```

**Comment by som-snytt** [comment]
There is that annoying warning to use `to` to avoid aliasing. The conversion is deprecated because of the hidden copying.

**Comment by SethTisue** [comment]
Pretty sure there was a design discussion about this in not the too distant past, though I don't recall what the outcome was. I can dig for it later.

**Comment by SethTisue** [comment]
Also let's check and make sure that the Scaladoc is totally explicit on this point.
