### ISSUE TITLE
ending map function with function type

### ISSUE THREAD

**Issue by klieverse** [scala/bug#12668]
## Reproduction steps
ending a map function with a function (e.g. incrementing i)

Scala version: 2.12.16

def example() : List[Int] = {
    var i = 0
    (List.tabulate(5)(_ + 1)).map { x => 
      x + i 
      i += 1
    }
  } 

## Problem
Console message: "an unexpected type representation reached the compiler backend while compiling GUncoverLive.scala: <error>. If possible, please file a bug on https://github.com/scala/bug/issues."

**Comment by som-snytt** [comment]
The ticket does not specify the version of Scala.
```
➜  snips scalac -d /tmp t12668.scala
t12668.scala:7: error: type mismatch;
 found   : Unit
 required: Int
      i += 1
        ^
1 error
➜  snips scalac -version
Scala compiler version 2.13.10 -- Copyright 2002-2022, LAMP/EPFL and Lightbend, Inc.
```

**Comment by klieverse** [comment]
Thank you, changed it now

**Comment by som-snytt** [comment]
`-Vprint` shows 2.12 doesn't do the `+=` correctly, `i.<$plus$eq: error>(1)`

By coincidence, I was just looking at https://github.com/scala/bug/issues/9745#issuecomment-322250612 which was only partially backported to 2.12, or at least this example was not fixed.

**Comment by klieverse** [comment]
Thanks for your replies! I was not aware I was using an outdated version
