### ISSUE TITLE
unexpected coll in Iterable

### ISSUE THREAD

**Issue by flomebul** [scala/bug#12661]
## Reproduction steps

Scala version: 2.13.9

```scala
object Abug {
  def lazyMap[T, U](coll: Iterable[T], f: T => U) = new Iterable[U] {
    def iterator = coll.iterator map f
  }
}
```

## Problem

One error found by the compiler
```
type mismatch;
 found   : T => U
 required: U => U
    def iterator = coll.iterator map f
```
The error disappear if I replace `coll` by `iter` or `col`. Look like the error is strongly linked to the name of the parameter...

Same error occurre with scala version 3.2.0

**Comment by som-snytt** [comment]
I found my PR and the associated ticket.

Duplicates https://github.com/scala/bug/issues/11921
