### ISSUE TITLE
first function is not working as documented

### ISSUE THREAD

**Issue by nikeshv** [scala/bug#12672]
## Reproduction steps

Scala version: (Is the bug only in Scala 3.x? If so, report it at https://github.com/lampepfl/dotty/issues/new/choose instead.)
All versions
```
import spark.implicits._
import org.apache.spark.sql.expressions.{Window, WindowSpec}
import org.apache.spark.sql.functions._
import org.apache.spark.sql.types._
  val simpleData = Seq(("2021-01-21 00:03:24.178",  null),
    ("2021-01-21 00:03:24.336", null),
    ("2021-01-21 00:03:24.446", "1000")
  )
  val df = simpleData.toDF("dltimestamp", "speed")
val firstval: WindowSpec = 
Window.partitionBy(round(((unix_timestamp($"dltimestamp","yyyy-MM-dd HH:mm:ss.SSS") *1000) 
                                                                                   + date_format($"dltimestamp" , "SSS"))/1000)) .orderBy(asc("dltimestamp"))

val df_aggr=
df.withColumn("dltimestamp_rev",from_unixtime(round(((unix_timestamp($"dltimestamp","yyyy-MM-dd HH:mm:ss.SSS") *1000) + date_format($"dltimestamp" , "SSS"))/1000))).
withColumn("dltimestamp_original",col("dltimestamp")).
withColumn("speed",col("speed").cast(DoubleType)).
withColumn("speed_first",first("speed",ignoreNulls = true).over(firstval).cast(DoubleType)).
withColumn("rn",row_number().over(firstval)).
drop("dltimestamp").
withColumnRenamed("dltimestamp_rev","dltimestamp")
display(df_aggr)
```

## Problem
![image](https://user-images.githubusercontent.com/25953672/197530875-dd2c75fb-1c52-4e32-85a6-8aaff4a0d0e8.png)
As per the image, first 2 record is having null values for speed, but since I applied first("speed",ignoreNulls = true), it has to show the first not null value of speed, that means all the three records should have speed=1000 for column speed_first.

Explain how the above behavior isn't what you expected.
I am already passing, ignoreNulls=true to the function first, so I expect a not null column as output, unless all records are null.

**Comment by som-snytt** [comment]
With some clicking, the Spark issues can be found at https://issues.apache.org/jira/projects/SPARK/issues/SPARK-34827?filter=allopenissues

from the project page https://spark.apache.org/documentation.html
