### ISSUE TITLE
Overloading issue in 2.12.17 but fine in 2.13.10

### ISSUE THREAD

**Issue by He-Pin** [scala/bug#12688]
## Reproduction steps

2.12.17

defines:
```scala
def completeOn[T <: Throwable](implicit tag: ClassTag[T]): Repr[Out] = ???
def completeOn(pf: PartialFunction[Throwable, Boolean]): Repr[Out] = ???
```

and call side as :
```scala
  def completeOn(predicate: java.util.function.Predicate[_ >: Throwable]): javadsl.Source[Out, Mat] =
    new Source(delegate.completeOn {
      case ex: Throwable if predicate.test(ex) => true
    })
```

This works in 2.13.10 but cause a compiling error on 2.12.10.

it works if I rewrite it to:
```scala
  def completeOn(predicate: java.util.function.Predicate[_ >: Throwable]): javadsl.Flow[In, Out, Mat] = {
    val pf:PartialFunction[Throwable, Boolean] = {
      case ex: Throwable if predicate.test(ex) => true
    }
    new Flow(delegate.completeOn(pf))
  }
```

or
```scala
  def completeOn(predicate: java.util.function.Predicate[_ >: Throwable]): javadsl.Flow[In, Out, Mat] = {
    new Flow(delegate.completeOn({
      case ex: Throwable if predicate.test(ex) => true
    }: PartialFunction[Throwable, Boolean]))
  }
```
## Problem

```
missing parameter type for expanded function
[error] The argument types of an anonymous function must be fully known. (SLS 8.5)
[error] Expected type was: ?



[error]     new Flow(delegate.completeOn {
[error]                                  ^
```

refs: https://github.com/akka/akka/pull/31639

**Comment by som-snytt** [comment]
This was a feature for 2.13 https://github.com/scala/scala/commit/54714cd3392c0256e685503aa3684d85b49df728

**Comment by He-Pin** [comment]
Is there any plan to backport this? @som-snytt

**Comment by som-snytt** [comment]
I left this open just in case, and although it looks doable, I'd be surprised if there is a plan, since some time has passed.

`scala-dev` is the planning tracker, or the cemetery of lost dreams.

**Comment by SethTisue** [comment]
We don't keep open tickets just for potential backports.

It's unclear to me whether https://github.com/scala/scala/pull/7631 is a good backport candidate. Someone could submit a backport PR and see how CI likes it, and we could run the community build on it. But the interaction between type checking, type inference, and overloads is highly complex and fragile, and a lot changed in those departments between 2.12 and 2.13, so I have a hunch that a backport wouldn't ultimately be accepted even if it passed CI, on risk vs. stability grounds — 2.12.x is a branch where the value we place on stability and leaving-well-enough-alone just keeps getting higher and higher.

**Comment by som-snytt** [comment]
As usual, Seth has a more optimistic take than I could muster.
