### ISSUE TITLE
String switching and async interaction crashes compiler

### ISSUE THREAD

**Issue by lrytz** [scala/bug#12686]
`test/async/run/string-switch-async.scala`

```scala
// scalac: -Xasync

import scala.tools.partest.async.OptionAwait._
import org.junit.Assert._

object Test {
  private def testSwitch(s: String) = optionally {
    s match {
      case "" => ""
      case p =>
        value(Some(p))
        p
    }
  }
}
```

Pattern translation introduces a local for the scrutinee (`x1`) and replaces uses of `p` in the default case by `x1`. After patmat:

```scala
            case <synthetic> val x1: String = s;
            x1 match {
              case "" => ""
              case _ => {
                scala.tools.partest.async.OptionAwait.value[String](new Some[String](x1));
                x1
              }
            }
```

The `x1` variable is accessed in different async stages, and therefore transformed into a state machine field. After async:

```scala
                (stateMachine$async.this.x1: String) match {
                  case "" =>
                    ...
                  case _ =>
                    ...
                  }
```

This breaks the translation of string switches in `CleanUp`, which assumes the scrutinee AST is a `Literal` or an `Ident`: https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/transform/CleanUp.scala#L408-L412

**Comment by lrytz** [comment]
(easier to review with "Hide whitespace")

**Comment by som-snytt** [comment]
lrytz finds the best issues.

**Comment by lrytz** [comment]
it's retronym behind the scenes, of course
