### ISSUE TITLE
In a macro `c.eval` for `java.lang.Class[_]` produces `c.Type`/`Class[_]` depending on whether to define a variable

### ISSUE THREAD

**Issue by DmytroMitin** [scala/bug#12680]
## Reproduction steps

Scala version: 2.13.10

- If we define a variable `classValue` in a macro then upon expansion the macro produces `ClassCastException`

```scala
def foo(clazz: Class[_]): Unit = macro fooImpl

def fooImpl(c: blackbox.Context)(clazz: c.Tree): c.Tree = {
  import c.universe._
  val classValue = c.eval(c.Expr[Class[_]](c.untypecheck(clazz))) // HERE!!!
  q"()"
}
```
```scala
foo(classOf[String])
```
```
java.lang.ClassCastException: scala.reflect.internal.Types$ClassNoArgsTypeRef cannot be cast to java.lang.Class
```
https://scastie.scala-lang.org/DmytroMitin/RINjJfNsRNqprn9nR1ZpDQ/9 (toolbox is not used for actual reproduction, it's just for Scastie because it doesn't support multiple files/subprojects).

- If we don't define a variable then the macro expands successfully

```scala
def foo(clazz: Class[_]): Unit = macro fooImpl

def fooImpl(c: blackbox.Context)(clazz: c.Tree): c.Tree = {
  import c.universe._
  println(c.eval(c.Expr[Class[_]](c.untypecheck(clazz)))) // HERE!!!
  q"()"
}
```
```scala
foo(classOf[String]) // ()
// prints: String
```

https://scastie.scala-lang.org/DmytroMitin/RINjJfNsRNqprn9nR1ZpDQ/18

## Problem

The macro should expand successfully both times and `c.eval` should produce `Class[_]` both times.

A workaround is casting (when possible)
```scala
val classValue = c.mirror.asInstanceOf[c.universe.RuntimeMirror]
  .runtimeClass(
    c.eval(c.Expr[Type](c.untypecheck(clazz)))
  ).asInstanceOf[Class[_]
```
https://scastie.scala-lang.org/DmytroMitin/RINjJfNsRNqprn9nR1ZpDQ/33

or runtime reflection in macros
```scala
val rm = scala.reflect.runtime.currentMirror
val classValue =
  rm.runtimeClass(
    c.eval(c.Expr[rm.universe.Type](c.untypecheck(clazz)))
  ).asInstanceOf[Class[_]]
```
https://scastie.scala-lang.org/DmytroMitin/RINjJfNsRNqprn9nR1ZpDQ/32

If we remove `c.untypecheck` or replace it with `c.resetAllAttrs` (from https://github.com/scalamacros/resetallattrs) nothing changes.

If we replace existential with `Class[T]` nothing changes. 

Discovered here: https://stackoverflow.com/questions/71390113/get-annotations-from-class-in-scala-3-macros

**Comment by som-snytt** [comment]
The [example in the reflection scaladoc](https://www.scala-lang.org/api/2.13.10/scala-reflect/scala/reflect/api/Constants.html) covers special handling of constants `classOf[T]` and Java `enum`.

But they are naively unwrapped at [`eval`](https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/reflect/macros/contexts/Evals.scala#L28).

The comment:

> People are very frequently using c.eval in order to obtain underlying
values of literals. Spinning up a new compiler for that modest purpose
is a gross waste of fossil fuels.

**Comment by DmytroMitin** [comment]
@som-snytt Many thanks. So evaluating a tree of `Class[_]` (enum value) into `Type` (`Symbol`) was intended behavior. I don't know whether the behavior should change. With new implementation this stops to work for classes not existing yet during macro expansion (although previous implementation was slightly inconsistent for `classOf[String]`/`Class.forName("java.lang.String")`).
My point was that it's weird that the behavior depends on whether we define  a local variable inside a macro.
