### ISSUE TITLE
Compiler takes ages to emit errors for a simple large file

### ISSUE THREAD

**Issue by kubukoz** [scala/bug#12691]
## Reproduction steps

Scala version: 2.13.10

The file to compile will be too large in whole, but it looks like this:

```scala
class Example {
  val f1: Int
  val f2: Int
  val f3: Int
  val f4: Int
  val f5: Int
  val f6: Int
  val f7: Int
  val f8: Int
  val f9: Int
// ...
}
```

You can generate the whole thing like this:

```
//> using scala "2.13.10"
import java.nio.file.Files
import java.nio.file.Paths

object demo extends App {

  //2^16 - 14 is the max amount of fields I could fit into a Java class
  val fields = (1 until (Math.pow(2, 16).toInt - 14))
    .map { i =>
      s"  val f$i: Int"
    }
    .mkString("\n")

  val fileText = s"""class Example {
                    |$fields
                    |}""".stripMargin

  Files.writeString(Paths.get("Example.scala"), fileText)
}
```

## Problem

scalac has been compiling this file for over 10 minutes on an M1 Max machine. javac deals with a Java counterpart in around a second.

## Extra info

Profiling the compiler shows me that the worst offenders are

```
scala.reflect.internal.Symbols$Symbol.needsFlatClasses()
scala.reflect.internal.Symbols$Symbol.name()
scala.reflect.internal.tpe.FindMembers$FindMembers.membersScope()
```

Here's a flame graph:

<img width="3325" alt="image" src="https://user-images.githubusercontent.com/894884/201483763-fc1233e4-3961-4cf5-9a1d-fef6ce89ce4b.png">

And a profiler sample (20 seconds should be enough?):

[Main_2022_11_12_171812.jfr.zip](https://github.com/scala/bug/files/9995397/Main_2022_11_12_171812.jfr.zip)

**Comment by kubukoz** [comment]
Note: this only takes this long if the vals are unimplemented (as seen from the flame graph above, it's during `emitErrors`). If the class is changed into a trait, you get a failure after 5 seconds (class too large). Removing some more constants (40 instead of 14 does the trick) causes in a successful compile.

**Comment by som-snytt** [comment]
You get a nice message
```
Missing implementations for 9 members.
  val f1: Int = ???
  val f2: Int = ???
  val f3: Int = ???
  val f4: Int = ???
  val f5: Int = ???
  val f6: Int = ???
  val f7: Int = ???
  val f8: Int = ???
  val f9: Int = ???
```
If you extend `Runnable`, for example
```
t12691b.scala:2: error: class Example needs to be abstract.
Missing implementations for 10 members.
  // Members declared in Example
  val f1: Int = ???
  val f2: Int = ???
  val f3: Int = ???
  val f4: Int = ???
  val f5: Int = ???
  val f6: Int = ???
  val f7: Int = ???
  val f8: Int = ???
  val f9: Int = ???

  // Members declared in java.lang.Runnable
  def run(): Unit = ???

class Example extends Runnable {
      ^
1 error
```
Probably it should set an upper bound on the number of members to be helpful about.

If the user has a source generator, they are not depending on type diagnostic to generate their stub methods.

**Comment by som-snytt** [comment]
I notice my new profile pic has the same pose as kubukoz, but different hair style.

**Comment by som-snytt** [comment]
Sample IRL usage https://github.com/scala/scala/pull/10211/files#diff-a68f004a15151d6dee0c08425b21248fdbbf1b5efbbf8c4a99f7bd3fc10dc42cR376

Others might use an IDE to just "implement methods", but it can be helpful to see where they are declared in a complex hierarchy such as collections.
```
  trait UseIterableOps[A, CC[_], C] {
    def collect[B](pf: PartialFunction[A,B]): CC[B] = ???
    def drop(n: Int): C = ???
    def dropWhile(p: A => Boolean): C = ???
    def filter(p: A => Boolean): C = ???
    def filterNot(pred: A => Boolean): C = ???
    def flatMap[B](f: A => scala.collection.IterableOnce[B]): CC[B] = ???
    def flatten[B](implicit asIterable: A => scala.collection.IterableOnce[B]): CC[B] = ???
    def map[B](f: A => B): CC[B] = ???
    def scanLeft[B](z: B)(op: (B, A) => B): CC[B] = ???
    def slice(from: Int, until: Int): C = ???
    def span(p: A => Boolean): (C, C) = ???
    def take(n: Int): C = ???
    def takeWhile(p: A => Boolean): C = ???
    def tapEach[U](f: A => U): C = ???
    def zipWithIndex: CC[(A, Int)] = ???
  }
```

**Comment by kubukoz** [comment]
> If the user has a source generator, they are not depending on type diagnostic to generate their stub methods.

I'm not sure I agree with this: e.g. smithy4s generates interfaces that you might want to implement. They're very unlikely to be this huge, though.

Something to note: Dotty doesn't have this problem, it shows a diagnostic (with all the members! they're sorted, too) in reasonable time (a couple seconds).

**Comment by som-snytt** [comment]
That's because I didn't submit my PR to forward port Scala 2 stub generation to dotty.
