### ISSUE TITLE
false not used

### ISSUE THREAD

**Issue by shestero** [scala/bug#12701]
## Reproduction steps

Scala version: 2.13.10 (also checked 2.13.8)

```scala
    def pairOriginTarget[T](f: String => Future[T]): Future[List[T]] = Future.sequence(List(req.srcCaseId, req.targetCaseId).map(f))
    for {
      cases @ List(_, target)                    <- pairOriginTarget(gettingCase)
      List(originInstance, targetInstance)       = cases.map(_.caseInstance)
      List(originParts, targetParts)             <- pairOriginTarget(gettingParts)
      ...
```

```scala
    def pairOriginTarget[T](f: String => Future[T]): Future[List[T]] = Future.sequence(List(req.srcCaseId, req.targetCaseId).map(f))
    for {
      cases @ List(_, target)                    <- pairOriginTarget(gettingCase)
      List(originParts, targetParts)             <- pairOriginTarget(gettingParts)
      List(originInstance, targetInstance)       = cases.map(_.caseInstance)
      ...
```

## Problem

The first peace of code produce false compiler message:
pattern var cases in value $anonfun is never used: use a wildcard `_` or suppress this warning with `cases@_`
      cases @ List(_, target)                    <- pairOriginTarget(caseStaticService.getCaseWithPrinting)
The second compiles ok.
I suggest some optimization is to blame.

**Comment by som-snytt** [comment]
Just the desugaring of `for` is too complex for the linter. There is an existing ticket.

**Comment by SethTisue** [comment]
is it #10287 or is that distinct? (`local val` vs `pattern var`)

**Comment by som-snytt** [comment]
That is the duplicate.
