### ISSUE TITLE
Backport `case Some(x, y)`

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12709]
## Reproduction steps

2.13.10

```scala
Welcome to Scala 2.13.10 (OpenJDK 64-Bit Server VM, Java 19).
Type in expressions for evaluation. Or try :help.

scala> val x = Some(1,2)
val x: Some[(Int, Int)] = Some((1,2))

scala> x match { case Some(i,j) => i+j }
                          ^
       error: wrong number of arguments for pattern Some[(Int, Int)](value: (Int, Int))

scala>
```

## Problem

```scala
Welcome to Scala 3.2.1 (19, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.

scala> val x = Some(1,2)
val x: Some[(Int, Int)] = Some((1,2))

scala> x match { case Some(i,j) => i+j }
val res0: Int = 3

scala>
```

**Comment by SethTisue** [comment]
are we sure that it's intentional that Scala 3 accepts this? it looks like a gesture at backwards compatibility and something that should be phased out on the Scala 3 side rather than matched in Scala 2?

**Comment by som-snytt** [comment]
My inspiration was https://github.com/lampepfl/dotty/issues/1305

**Comment by SethTisue** [comment]
But regardless, auto-tupling is on its way out of the language, isn't it?

**Comment by som-snytt** [comment]
I think that was a red herring. Odersky says at various points that it is a "last resort." Of course, one imagines him reclining on a beach (Strand) or at a Spa.

To test the waters at either resort, I opened https://github.com/lampepfl/dotty/issues/16617 which I think has a reasonable use case, not the sort of puzzler that serves only to anger the man.

**Comment by som-snytt** [comment]
I was mistaken about what they intend.
