### ISSUE TITLE
Private class constructor is public at the bytecode level

### ISSUE THREAD

**Issue by julienrf** [scala/bug#12711]
Classes with private constructors are actually public at the bytecode level, this creates two issues:
- it can be called from Java code
- [MiMa](https://github.com/lightbend/mima) reports error if its signature changes

## Reproduction steps

```Scala
// Foo.scala
package bug

class Foo private (x: Int)

object Foo {
  def apply(x: Int) = new Foo(x)
}
```

~~~ java
// Bar.java
package bug

class Bar {
  public void bar() {
    Foo foo = new Foo(42);
  }
}
~~~

## Output

The code compiles.

## Expectation

The Java compilation should fail.

## Possible solution

In a [discussion](https://contributors.scala-lang.org/t/private-primary-constructor-vs-mima/6050/2), @smarter suggested to emit the constructor as `ACC_SYNTHETIC` to make it non-accessible from Java, and ignored by mima (see lightbend/mima#92). Note that that change would still be binary compatible with possible existing Java code that would call such constructors (but it would be source incompatible).

Related Scala 3 issue: https://github.com/lampepfl/dotty/issues/16651

**Comment by lrytz** [comment]
Marking the constructor synthetic could break other tools.

IMO this should stay as is in bytecode, it would be good to improve MiMa to understand this pattern.

**Comment by julienrf** [comment]
> Marking the constructor synthetic could break other tools.

Do you see a “good” reason to rely on this breach?

**Comment by lrytz** [comment]
I'm not saying having the constructor public is good, we should keep things private in bytecode where possible - but there are many cases where we can't. For example anything `private[x]` is public in bytecode, but MiMa knows how to handle that.

Marking something that's not synthetic as synthetic might break tools that take information from the bytecode.

**Comment by SethTisue** [comment]
I agree with Lukas. It's actually inherent and normal that we have to mark things in bytecode as public.

The callable-from-Java thing is unfortunate but it's a much bigger problem than just for constructors, so I don't think it's that helpful to fix it just for constructors, especially when the "fix" involves lying by marking actual user code as synthetic.

As for MiMa, being smarter about this is MiMa's responsibility.

**Comment by sjrd** [comment]
The IMO significant difference about constructors is that they keep their name (obviously). For other typical use cases, names are mangled with the fully qualified name of their owner and/or package, and so it's much more obvious that you're not supposed to call them even if they show up.

**Comment by sjrd** [comment]
> especially when the "fix" involves lying by marking actual user code as synthetic.

FWIW, my proposed fix was to make them JVM-package-private instead.

**Comment by lrytz** [comment]
... also, name-mangling private members that are made public is required to avoid accidental name clashes. I'm not sure if name mangling would have been introduced only to hide private definitions from Java.

**Comment by sjrd** [comment]
I see. Then I guess the least controversial way forward is indeed to change MiMa.

**Comment by julienrf** [comment]
Thank you for the discussion, I’ve followed-up by creating https://github.com/lightbend/mima/issues/738
