### ISSUE TITLE
Some StringBuilder methods do not mutate the collection

### ISSUE THREAD

**Issue by morgen-peschke** [scala/bug#12710]
## Reproduction steps

Scala versions: 
- [3.2](https://scastie.scala-lang.org/tX7DUJKTRSmWFrZ2Qz5kjg)
- [2.13](https://scastie.scala-lang.org/6g4pBTJwTpaQHaj4EmGWOA)
- [2.12](https://scastie.scala-lang.org/hIBDUQlXRV6yF8AMlAPVIg)
- [2.11](https://scastie.scala-lang.org/AJOayPHrRMOj2PzAiPIGEQ)
- [2.10](https://scastie.scala-lang.org/I6rc89rhQwC1gUIrT2QRyg)

```scala
scala> import scala.collection.mutable.StringBuilder

scala> println {
     |   val builder = new StringBuilder()
     |   builder.append("!This is a test!")
     |   builder.drop(1)
     |   builder.dropRight(1)
     |   builder.result()
     | }
!This is a test!
```

## Problem

`StringBuilder#drop` and `StringBuilder#dropRight` (and likely other methods) delegate to superclass methods that return a `View` instead of mutating the underlying collection, so they're inconsistent with the presentation of `StringBuilder` as a mutable collection.

Chaining the methods works as expected:
```scala
scala> println {
     |   new StringBuilder()
     |     .append("!This is a test!")
     |     .drop(1)
     |     .dropRight(1)
     |     .result()
     | }
This is a test
```

**Comment by som-snytt** [comment]
This seems per usual.
```
scala> import collection.mutable
import collection.mutable

scala> val buf = mutable.ArrayBuffer.empty[Int]
val buf: scala.collection.mutable.ArrayBuffer[Int] = ArrayBuffer()

scala> buf.appendAll(List(42,27,37))
val res0: buf.type = ArrayBuffer(42, 27, 37)

scala> buf.take(1)
val res1: scala.collection.mutable.ArrayBuffer[Int] = ArrayBuffer(42)

scala> buf
val res2: scala.collection.mutable.ArrayBuffer[Int] = ArrayBuffer(42, 27, 37)
```
In 2.13.9, the mutating operations on `StringBuilder` were narrowed to have result type `this.type`.

The motivation for that change was that the unused warning can ignore it. In fact,
```
➜  ~ scala -Wnonunit-statement
Welcome to Scala 2.13.10 (OpenJDK 64-Bit Server VM, Java 19).
Type in expressions for evaluation. Or try :help.

scala> println {
     | val builder = new StringBuilder()
     | builder.append("!This is a test!")
     | builder.drop(1)
     | builder.result()
     | }
       builder.drop(1)
                   ^
On line 4: warning: unused value of type StringBuilder (add `: Unit` to discard silently)
!This is a test!
```

**Comment by som-snytt** [comment]
> A collection in package scala.collection.mutable is known to have some operations that change the collection in place. So dealing with mutable collection means you need to understand which code changes which collection when.

https://docs.scala-lang.org/overviews/collections-2.13/overview.html

**Comment by morgen-peschke** [comment]
> > A collection in package scala.collection.mutable is known to have some operations that change the collection in place. So dealing with mutable collection means you need to understand which code changes which collection when.
> 
> [docs.scala-lang.org/overviews/collections-2.13/overview.html](https://docs.scala-lang.org/overviews/collections-2.13/overview.html)

Unfortunately, while the overview docs for the collections library do mention this, I couldn't find this within 3 hope of the documentation on `StringBuilder` itself. It's high-level implementation delegating most methods to a wrapped Java `StringBuilder` also _heavily_ implies that it enriches the Java `StringBuilder` in the same way that `StringOps` does Java `String`.

Punting on some of the methods and relying on the developer to memorize or peek at the implementation details of a class is certainly a reasonable strategy for reducing the maintenance burden, but the developer experience is kind of lacking - particularly for something as common as `StringBuilder`.

This behavior would be much less surprising if there were a better way to figure out which methods mutate the collection than checking the implementations. Because the immutable methods are the ones that aren't implemented by `StringBuilder`, they don't have their own scaladocs, so looking at tooltip documentation doesn't hint which methods have unexpected behavior.

**Comment by SethTisue** [comment]
@scala/collections

**Comment by som-snytt** [comment]
As a user of online docs, I sympathize with the challenges, but the summary doc says, "Caveat mutator."

The type signature indicates whether the method is side-effecting: it returns `this.type` or `Unit`.

I think they also tried to use naming conventions such as `append` vs `appended`.

Don't "peek at the implementation", look at the types, and use `-Wnonunit-statement` as a backstop.

Dottydoc aka Scaladoc 3 still has an open issue where it doesn't render `this.type` correctly, but this one looks like

![image](https://user-images.githubusercontent.com/369425/210866754-9812fdc5-a8b7-4498-a30e-d3aaa388a71a.png)

**Comment by morgen-peschke** [comment]
> As a user of online docs, I sympathize with the challenges, but the summary doc says, "Caveat mutator."

I would be 100% ok if all that came from this ticket was if the warning from the overview docs was included in the class-level scaladoc of the affected collections. The problem with the overview docs is that, by their nature, they're something you look at once every couple of major versions (and even then mostly just the diffs), so they're not usually a great place to document something like this.

> The type signature indicates whether the method is side-effecting: it returns this.type or Unit.

This would be great in theory, but I don't think this works in practice (at least in this case), because otherwise this would break and it works in all the versions listed in the initial post, which are the most recent version for each major version supported by scastie:
```scala
scala> println {
     |   new StringBuilder()
     |     .append("!This is a test!")
     |     .drop(1) // append mutates the collection, so this call should fail if mutating methods returned Unit
     |     .dropRight(1)
     |     .result()
     | }
This is a test
```

**Comment by som-snytt** [comment]
I agree with your main point.

I must nitpick that `append` returns the same `StringBuilder` and `drop` does not, and this is reflected in the method signature. There can be no disputing that fact. The comment in your example is not coherent.

![image](https://user-images.githubusercontent.com/369425/210922339-f2544b71-5e73-48d8-9122-770a20e7cb24.png)

This is the compromised Scala 3 doc:

![image](https://user-images.githubusercontent.com/369425/210922513-b82d9407-a6d0-45d8-ac92-f68af8cdb71d.png)

Scala 2 substitutes the result type for you:

![image](https://user-images.githubusercontent.com/369425/210922649-54be9fcf-3ba9-4d37-8e33-757e86ff502c.png)

In any case, the text plainly says "select", not "mutate".

I'm sure Scala 3 doc could use ideas about organizing "mutating" methods in a separate group. I know I've lodged a ticket about how grouping is handled, so I hope that is still evolving. If grouping is not appropriate, maybe an icon of some kind.

**Comment by morgen-peschke** [comment]
> I must nitpick that append returns the same StringBuilder and drop does not, and this is reflected in the method signature. There can be no disputing that fact. The comment in your example is not coherent.

It looks like I wasn't clear as I thought I was being, sorry for the confusion. The comment in the example not reflecting reality was kind of the point. A convention like returning `Unit` from mutable operations and `StringBuilder` (or `this.type`) for immutable ones is only as useful as it is consistent. In this case, it's not really consistent enough to be relied on, so we're back to memorizing which methods mutate and which do not.

**Comment by som-snytt** [comment]
I'm not sure, but possibly the misunderstanding is that `this.type` implies mutation.

`buf += element` where `+=` returns `buf.type` means it did not produce a new value but mutated the existing buf.

**Comment by morgen-peschke** [comment]
If the convention is that `this.type` implies mutation and `C` implies an immutable operation, that's a _really_ fine distinction I didn't see documented anywhere. My brain parsed "it returns this.type or Unit." as "it returns this.type (immutable) or Unit (mutable)", because `Unit` usually means "side effects here". 

It's also not a great convention because it's not something the compiler can really help with, because `C` gets widened out to `StringBuilder` at some point because `result` is a `StringBuilder` method.

**Comment by som-snytt** [comment]
Maybe there is a misunderstanding about `this.type`, which means the singleton type.

https://www.scala-lang.org/api/2.13.10/scala/collection/mutable/Growable.html#addOne(elem:A):Growable.this.type

`addOne` does not return some `Growable`, it returns exactly the instance on which the operation was invoked. If the operation does not side-effect, then it does nothing at all.

**Comment by morgen-peschke** [comment]
Fair, so it sounds like the only thing that's really needed then is updating the class-level scaladocs to give people a heads up that methods not directly implemented by `StringBuilder` are unlikely to mutate the instance.

**Comment by som-snytt** [comment]
> Unfortunately, while the overview docs for the collections library do mention this, I couldn't find this within 3 hops of the documentation on StringBuilder itself.

This symptom was because the order of annotations is somehow significant to scaladoc and it skipped the `@see` link to the overview. (Well, the destination is still difficult to navigate, but my point is that the doc at least attempted to link to something. That would get you within two hops.)

The PR corrects the overview link to `collections-2.13`.

**Comment by morgen-peschke** [comment]
@som-snytt That looks amazing! Thanks :)

**Comment by som-snytt** [comment]
As a follow-up in the distant future, the verbiage about collections conventions could be a macro and added to possibly all mutable collection classes.
