### ISSUE TITLE
For-comprehension with Option - incorrectly marked parameter as unused

### ISSUE THREAD

**Issue by kgadek** [scala/bug#12719]
## Reproduction steps

Scala version: 2.13.9 executed with `-Ywarn-unused -Werror`.

```scala
[info] Starting scala interpreter...
Welcome to Scala 2.13.9 (OpenJDK 64-Bit Server VM, Java 11.0.18).
Type in expressions for evaluation. Or try :help.

scala> for { a1 <- Some(1); a2 <- Some(0); if !(a1 > 10); res = a1 - a2 } yield res
                            ^
       warning: parameter value a2 in anonymous function is never used
error: No warnings can be incurred under -Werror.


scala> for { a2 <- Some(0); a1 <- Some(1); if !(a1 > 10); res = a1 - a2 } yield res
val res8: Option[Int] = Some(1)
```

## Problem

This looks somewhat similar to #11343. The above statement should compile without any warning. Reordering unrelated statements fixes the error.

I've been able to reproduce it on scastie: https://scastie.scala-lang.org/fY4Fp3sAQ0unBDkf1uibdg — it seems 2.13.10 is also affected

**Comment by SethTisue** [comment]
Minimizes to `for { a2 <- Some(0); if true } yield a2`

`-Vprint:parser` shows us that the `for` desugars to `Some(0).withFilter(a2 => true).map(a2 => a2)`, which of course gives the same warning.

It also gives some insight into why the warning is emitted; in `withFilter(a2 => true)`, the `a2` parameter is in fact not used.

@som-snytt this seems familiar — surely there's a ticket on this already?
