### ISSUE TITLE
Tasty Reader: handle APPLYsigpoly nodes

### ISSUE THREAD

**Issue by bishabosha** [scala/bug#12724]
Scala 3.3.0 will release with potentially `APPLYsigpoly` TASTy nodes appearing in signatures (annotations/parents of classes) so we need to test against this, and handle the nodes if they appear.

**Comment by SethTisue** [comment]
glad you thought of this because I _should_ have thought of it and didn't

**Comment by SethTisue** [comment]
@bishabosha with https://github.com/scala/scala/pull/10299 merged, this is now resolved, I think?

**Comment by bishabosha** [comment]
that's right, this should be marked as resolved
