### ISSUE TITLE
Vector(1).slice(Int.MaxValue, Int.MinValue) == Vector(1)

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12739]

**Comment by noresttherein** [comment]
Sorry, forgot to minimize it:
```scala
Vector(1).slice(0xffffff,0x800000)==Vector(1)
```

**Comment by som-snytt** [comment]
I'll have to increase the font size, but I think you over-minimized.

Anyway the fields on `Int` are true constants, so I think it's OK. However, you did neglect to say which version of the compiler you're using. It could be a bug in constant folding.
