### ISSUE TITLE
Extension methods not working for `F[Nothing]` like types.

### ISSUE THREAD

**Issue by BalmungSan** [scala/bug#12748]
## Reproduction steps

**Scala version**: `2.13.10`

```scala
trait Foo[A]

implicit class Ops[A](fooA: Foo[A]) {
  def bar: Unit = ()
}

def nothingFoo: Foo[Nothing] = new Foo[Nothing] {}

nothingFoo.bar
```

-- **Scastie**: https://scastie.scala-lang.org/OoOINh7AQxmZgBoOlp45xQ

Produces the following error:

> value bar is not a member of Playground.Foo[Nothing]

## Problem

I would expect the compiler to find the `bar` extension method, since `Foo[Nothing]` is a valid `F[A]`

> PS: This works as expected on **Scala 3**.

-----

Thanks to @armanbilge for creating the minimization!

**Comment by durban** [comment]
Yeah, this is quite old behavior: #1570, #9453 (see [this comment](https://github.com/scala/bug/issues/9453#issuecomment-292438284) in particular).

**Comment by BalmungSan** [comment]
@durban so should this one be closed as a duplicate?

**Comment by durban** [comment]
Probably yes (but I'm nobody, so... :man_shrugging:).

**Comment by som-snytt** [comment]
Scala 2 avoids `Nothing` as an inference failure, Scala 3 has different rules for inference and accommodates `Nothing`.

It would be nice to have this explained in one place. I would have to study it to explain it.

```
scala> nothingFoo.bar
                  ^
       error: value bar is not a member of Foo[Nothing]

scala> def nothingFoo[A]: Foo[A] = new Foo[A] {}
def nothingFoo[A]: Foo[A]

scala> nothingFoo.bar

scala> nothingFoo[Nothing].bar
                           ^
       error: value bar is not a member of Foo[Nothing]

scala> nothingFoo.bar // print
                                                  Ops[Nothing](nothingFoo[Nothing]).bar // : Unit
```

Thanks @durban
