### ISSUE TITLE
Package protected class cannot extend a public sealed generic class with a protected constructor

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12756]
## Reproduction steps

Scala version:  2.13.10

```scala
package test {
	sealed class Seal[X] protected (x :String) {
		protected def this() = this("")
	}
	protected[test] class Walrus extends Seal
}
```

## Problem
```
constructor Seal in class Seal cannot be accessed in package test from package test
 Access to protected constructor Seal not permitted because
 enclosing package test is not a subclass of
 class Seal in package test where target is defined
	protected[test] class Walrus extends Seal
```
A bummer because it is a useful technique for 'unsealing' a class for a class in another file.

**Comment by SethTisue** [comment]
assuming you mean `extends Seal[String]` or some such and not just `extends Seal` (because otherwise "Missing type parameter for test.Seal"), Scala 3 accept this

offhand this like something we'd be unlikely to tinker with in a Scala 2 context, but I could certainly be wrong

**Comment by som-snytt** [comment]
Adding requisite "I am the Walrus", as there doesn't seem to be a label for that.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/12379
