### ISSUE TITLE
partest of empty dir

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12769]
## Problem

An empty `pos` dir passes, an empty `run` dir crashes where
```
last test / IntegrationTest / testOnly
```
shows
```
[error] Uncaught exception when running partest: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error running .../scala/test/files/run/ZZZZ
[scroll way down]
[error] Caused by: sbt.ForkMain$ForkError: java.nio.file.NoSuchFileException: .../scala/test/files/run/ZZZZ-run.log
```

I was going to make `ZZZZ.scala` into `ZZZZ/*.scala`, changed my mind. It takes the empty dir and ignores the `ZZZZ.scala`, but really if it decides it has nothing to compile, it should fail the test instead of either passing or crashing.

Someday, when Scala 3 seeks to re-integrate partest, they'll say, "It even fails nicely on an empty test directory."

**Comment by som-snytt** [comment]
I forgot there is no `internal` label for tickets, which would otherwise go to `scala-dev`.

**Comment by SethTisue** [comment]
"build" is close enough, but I agree the scala/bug vs scala-dev thing is unclear 🤷

**Comment by som-snytt** [comment]
Thanks, I'd didn't see `build` because I was still blinded by rage. That label works nicely, as it is build-time.
