### ISSUE TITLE
LinkedHashSet.addAll does not make call to sizeHint

### ISSUE THREAD

**Issue by KisaragiEffective** [scala/bug#12760]
## Reproduction steps

Scala version: 2.13.10 ([scastie](https://scastie.scala-lang.org/xoN7MGV7SNCvdUQXOtt1qg))

```scala
import scala.collection.mutable

val random = new java.util.Random()
val randomSet: Set[Int] = (1 to 1000000).map(_ => random.nextInt()).toSet;
{
  val t = System.nanoTime()
	val hashSet: mutable.HashSet[Int] = new mutable.HashSet()
  hashSet.addAll(randomSet);
  
  println(s"${System.nanoTime() - t} ns")
};
{
  val t = System.nanoTime()
	val linkedHashSet: mutable.LinkedHashSet[Int] = new mutable.LinkedHashSet()
  linkedHashSet.addAll(randomSet);
  
  println(s"${System.nanoTime() - t} ns")  
}
```

## Problem

`scala.collection.mutable.LinkedHashSet#addAll` is not overriden, causing unnecessary multiple allocations.

In above reproduction code, LinkedHashSet is slower than HashSet about 3 times.

**Comment by SethTisue** [comment]
seems plausible. @scala/collections crew might have further insight

**Comment by liang3zy22** [comment]
The scala.collection.mutable.LinkedHashSet#addAll should cause binary compatibility issue. See the link below:
https://github.com/scala/scala/pull/10235#issuecomment-1336781619

One of the binary compatibility issue is from LinkedHashMap#addAll. I think LinkedHashSet#addAll should have same issue.

**Comment by SethTisue** [comment]
@KisaragiEffective have you tested on the current 2.13.11 nightly?

**Comment by KisaragiEffective** [comment]
@SethTisue 
No, not yet.
I don't know how to test this with latest nightly.

**Comment by KisaragiEffective** [comment]
@SethTisue I've tested with `2.13.11-bin-8269bdd`, and 5 of 5 attempts indicate LinkedHashSet is slower 2~4 times than HashSet.

**Comment by lrytz** [comment]
I didn't realize this was related to https://github.com/scala/scala/pull/10258, I'll take a look if we can include it in 2.13.11
