### ISSUE TITLE
Is There Any Downloadable Scala 3 API Doc? 

### ISSUE THREAD

**Issue by shamiul94** [scala/bug#12775]
I have found downloadable API Doc for Scala 2.10.2 [here](https://www.scala-lang.org/download/2.10.2.html#:~:text=docs%2D2.10.2.zip-,API%20docs,-33%20MB) but couldn't find any downloadable API Doc for Scala 3.2.2. Although I found the web version of the doc [here](https://www.scala-lang.org/api/3.2.2/index.html), couldn't find the downloadable version for my local usage. 
Can anyone guide me to it, please? Thanks.

**Comment by som-snytt** [comment]
I also prefer to have a local copy for when the internet is out.

At https://www.scala-lang.org/download/2.13.10.html

"Other resources" includes the doc archives:

https://downloads.lightbend.com/scala/2.13.10/scala-docs-2.13.10.txz

I haven't delved into the Scala 3 build to see if docs are packaged somewhere, but the UX is clearly different and deficient.

I only just noticed that is a lightbend URL! Thank-you, Lightbend!

There are no docs at dotty github:

https://github.com/lampepfl/dotty/releases/tag/3.2.2

**Comment by michelou** [comment]
@shamiul94 I suggest you look at the [Scala 3 example](https://github.com/michelou/wix-examples/blob/main/scala3-examples/README.md)
of my GitHub project [`wix-examples`](https://github.com/michelou/wix-examples/) where I mention in the [release notes for `scala-3.2.2.msi`](https://github.com/michelou/wix-examples/blob/main/docs/relnotes/relnotes_scala3-3.2.2.md) the source location I use for the Scala 3 API documentation you get installed when running my MSI file.

For instance (`scala-3.2.2.msi`) : 

| API | Source&nbsp;location |
|:-------|:----|
| 2.13.10 | [`scala-library-2.13.10-javadoc.jar`](https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.10/)|
| 3.2.2 | [`scala3-library_3-3.2.2-javadoc.jar`](https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.2.2/) |

**Comment by SethTisue** [comment]
This is the Scala 2 bug tracker. Please use https://users.scala-lang.org for questions
