### ISSUE TITLE
IndexedSeqOps.head = apply(0) throws IndexOutOfBoundsException, not NoSuchElementException

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12782]
## Reproduction steps

Scala version: 2.13.10

## Problem
Implementing `IndexedSeq` and not overriding `head` leads to an IOOBE being thrown, contrary to NSEE mentioned in the specification. This does not affect `Vector`, as it overrides `head`.
The same goes for `last`.

**Comment by OndrejSpanel** [comment]
Is it possible to fix this without breaking binary compatibility?

**Comment by som-snytt** [comment]
`apply` has the annotation, and this is the first time I've noticed how it is rendered:
![image](https://user-images.githubusercontent.com/369425/236257311-8bdf1ad9-acb6-4655-97e5-0966ec4a2ea9.png)

`head` has only Scaladoc.
