### ISSUE TITLE
Field named `StringContext` followed by `s""` does not compile

### ISSUE THREAD

**Issue by izzyreal** [scala/bug#12789]
## Reproduction steps

Scala version: 2.13.10

```scala
scala> class Foo { val StringContext = 42; s"" }
```

## Problem

The above code does not compile in 2.13.10 (though it compiles in 3.2.2). If you change the name of the field it compiles in 2.13.10.

**Comment by som-snytt** [comment]
It was intentional in Scala 2 that interpolation used a locally scoped identifier `StringContext`, but that behavior was changed, intentionally, in Scala 3.

**Comment by SethTisue** [comment]
> The above code does not compile in 2.13.10 

For the record, the error is `error: Int does not take parameters; signature for interpolation must be `StringContext.apply(String*)`

**Comment by izzyreal** [comment]
Thanks for the amendment @SethTisue 👍

**Comment by som-snytt** [comment]
What a nice error message from the beginning of the pandemic.
