### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by sydeptraivc** [scala/bug#12791]
Reason:
    Type double_2nd (current frame, stack[4]) is not assignable to category1 type
  Current Frame:
    bci: @9236
    flags: { }
    locals: { integer, double, double_2nd, double, double_2nd, double, double_2nd, 'net/minecraft/item/ItemStack', 'java/lang/String', 'net/minecraft/nbt/NBTTagCompound', 'net/minecraft/nbt/NBTTagList', integer }
    stack: { 'net/minecraft/network/NetworkManager', uninitialized 9231, uninitialized 9231, double, double_2nd }
## Problem

Explain how the above behavior isn't what you expected.

**Comment by som-snytt** [comment]
If a non-bogus account happens along and also wonders "how to fix this?", please use a chat forum for questions.
