### ISSUE TITLE
ListBuffer.patchInPlace does not update last0 field, leaving the buffer in a corrupted state

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12796]
## Reproduction steps

Scala version: 2.13.10

```scala
    import collection.mutable.ListBuffer
    val buffer = ListBuffer(1)
    val patch = Seq(2)
    buffer.patchInPlace(1, patch, 2)
    println(buffer.last)
```

## Problem
Prints `1`

**Comment by noresttherein** [comment]
BTW, I found this through a static analysis of my improvement to `ListBuffer`, which I hope to make public on the days, and which fixes it in one sweep, so depending on how fast you need this one to be merged, you may not need to jump onto it this very moment.

**Comment by SethTisue** [comment]
@scala/collections

**Comment by NthPortal** [comment]
uh oh. I feel like I caused this
