### ISSUE TITLE
Quill idiom for inferred implicit type with whitebox macro under `-Xsource:3`

### ISSUE THREAD

**Issue by jilen** [scala/bug#12798]
The scala `2.13.11` version requires explicit type of implicit definition.
Then it become impossible to use `whitebox macro` to return the narrowed type.

**Comment by SethTisue** [comment]
Can the macro emit `@annotation.nowarn("cat=other-implicit-type")`?

**Comment by som-snytt** [comment]
This is pre-second-coffee, but you can always write `: Any` and the whitebox macro produces a narrower type.

**Comment by SethTisue** [comment]
@som-snytt any advice we have for macro authors would be good to add to the PR description

**Comment by som-snytt** [comment]
I added a line to the PR without thinking about it, but please add a use case here if necessary.

**Comment by jilen** [comment]
> Can you give an example of what you can't do now?

The case for me is defining quill's `QueryMeta`
```scala
implicit val  personMeta = materializedQueryMeta[Person]
```
Quill will use the concrete type info later.  If specify type to `QueryMeta[Person]` it will become dynamic query.

**Comment by som-snytt** [comment]
@jilen Does that mean `implicit val personMeta: Any = materializedQueryMeta[Person]` does not work? I looked briefly at quill last year in the context of a bug related to macro and result inference, but I don't remember much about it.

**Comment by jilen** [comment]
@som-snytt Confirmed adding `: Any` gets things done. Thanks

**Comment by SethTisue** [comment]
@jilen what behavior did you expect, there?

**Comment by som-snytt** [comment]
I'll take a look today. I don't want anything to spoil Seth's Scala Days. Because really, how many Scala Days do have in this life? Every Scala Day is precious.

**Comment by SethTisue** [comment]
> I thought the type of foo should be String (returned by whitebox macro)

Ah, I had misunderstood Som's suggestion, but I understand better now.

I'm surprised to learn that that would be expected behavior. when I write `implicit val foo: Any = ...`, I would not have expected anything I could substitute for `...` to have any influence on what type `foo` gets, give that I explicitly asked for the type to be `Any`.

@som-snytt you're sure that's expected...?

I guess in Scala 3 this issue can't arise because there aren't whitebox macros...? Perhaps one possible resolution here would be to say that it's expected for `-Xsource:3` to complain when you're doing something that isn't even possible in Scala 3 at all?

perhaps @guizmaii could enlighten us on how people using Scala 3 with Quill would be expected to write this code?

**Comment by som-snytt** [comment]
@SethTisue Yes, it's fundamental to whiteboxness and also works that way in Scala 3 via `transparent inline`.

**Comment by SethTisue** [comment]
> `implicit def myimplicit: Any = macro mywhitebox`
> lets the type of myimplicit expansion get refined.

Yes, that makes a lot more sense to me.

But it doesn't seem to help OP. Their desire to have an `implicit val` with an inferred type is fundamentally at odds with the explicit-type requirement. 

> also works that way in Scala 3 via `transparent inline`

I'd like to see a spelled-out example of that; in Scala 3, can I have a `given` whose type isn't written, but comes from a `transparent inline`?

**Comment by dwijnand** [comment]
> I'd like to see a spelled-out example of that; in Scala 3, can I have a `given` whose type isn't written, but comes from a `transparent inline`?

It's written but it's also transparent: https://dotty.epfl.ch/docs/reference/contextual/givens.html#given-macros-1

**Comment by leszekgruchala** [comment]
We cannot update to 2.13.11 because of this issue and the fact we cannot add explicit types for Quill. We use `-Xsource:3` and I see `-Wconf:cat=other-implicit-type:s` is simply being ignored with that option together.

**Comment by lrytz** [comment]
Not sure if this is clear from the discussion, sorry if I'm just adding noise; the static type of an implicit whitebox macro def defines what type can be summoned:

```scala
import scala.reflect.macros.whitebox.Context
import scala.language.experimental.macros
class A
class B extends A

class FooMacroImpl(val c: Context) {
  import c.universe._
  def fooImpl: Tree = {
    q"new B()"
  }
}
object Foo {
  implicit def foo: A  = macro FooMacroImpl.fooImpl
}
```

```
scala> import Foo._
import Foo._

scala> foo
val res0: B = B@49005dc4

scala> implicitly[B]
                 ^
       error: could not find implicit value for parameter e: B

scala> implicitly[A]
val res2: A = B@a1e578f
```

**Comment by nafg** [comment]
Bottom line what do I do with scala 2.13.12?

**Comment by som-snytt** [comment]
Top line, the idiom of the title is `-Wconf:cat=scala3-migration:s` .

Sample potential dogfooding at https://github.com/scala/scala/pull/10551/files#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91R417
```
compile / scalacOptions ++= Seq("-Wconf:cat=scala3-migration&msg=elidable&site=scala.Predef:s"),
```

The wconf is `:e` by default to error, so `:s` silences it and `:w` dials it back to warning, etc.
