### ISSUE TITLE
Spurious unused warning in for comprehension (2.13.11 regression)

### ISSUE THREAD

**Issue by tgodzik** [scala/bug#12801]
## Reproduction steps

2.13.11

```scala
//> using scala "2.13.11"
//> using options "-Wunused"

class Main {
  def search2(): Iterator[Int] = {
    for {
      pkg <- Array(1).iterator
      if pkg > 1
    } yield 0
  }
}

```

## Problem

pkg is reported as unused

**Comment by SethTisue** [comment]
@som-snytt wdyt, is this a bug, or is it another dilemma like #10287?

**Comment by SethTisue** [comment]
It desugars to `foo.withFilter(pkg => ...).map(pkg => ...)` and the first `pkg` is used but the second `pkg` is not, hence the warning.

**Comment by SethTisue** [comment]
@tgodzik wait, 2.13.10 is the same

```
~/tmp/si-12801 % scala-cli compile .                                                           main
Compiling project (Scala 2.13.10, JVM)
[warn] ./S.scala:7:7
[warn] parameter value pkg in anonymous function is never used
[warn]       pkg <- Array(1).iterator
[warn]       ^^^
```

**Comment by som-snytt** [comment]
jinx.

**Comment by SethTisue** [comment]
Tomasz will make a fresh attempt to determine why he started seeing warnings after a 2.13.11 upgrade that weren't there before.
