### ISSUE TITLE
Iterator.drop susceptible to arithmetic overflow

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12822]
## Reproduction steps

Scala version: 2.13.11

```scala
println(List(1).iterator.drop(1).drop(Int.MaxValue).toList)
```

## Problem
prints
```scala
List(1)
```

**Comment by SethTisue** [comment]
@scala/collections

**Comment by yzia2000** [comment]
Yeah can see the arithmetic overflow happening with the Iterator. 
The drop function in Iterator is implemented using the SliceIterator which maintains a variable called dropping of type Int. So if we add 1 to it and then Int.MaxValue, it will overflow and cause no dropping to actually be done as highlighted.



```scala
  private[scala] final class SliceIterator[A](val underlying: Iterator[A], start: Int, limit: Int) extends AbstractIterator[A] {
    private[this] var remaining = limit
    private[this] var dropping  = start
...

    override protected def sliceIterator(from: Int, until: Int): Iterator[A] = {
      val lo = from max 0
      def adjustedBound =
        if (unbounded) -1
        else 0 max (remaining - lo)
      val rest =
        if (until < 0) adjustedBound          // respect current bound, if any
        else if (until <= lo) 0               // empty
        else if (unbounded) until - lo        // now finite
        else adjustedBound min (until - lo)   // keep lesser bound
      if (rest == 0) empty
      else {
        dropping += lo
        remaining = rest
        this
      }
    }
  }

```

Note sure how acceptable this would be to others but we could convert the dropping variable above to something of type BigInteger.

```
dropping: BigInteger
```

Maybe some other variables will need to have their type changed in a similar manner as well.

**Comment by He-Pin** [comment]
![image](https://github.com/scala/bug/assets/501740/48e178a2-790a-4885-be0f-1bdf0fe7dd28)
The problem not exits on 2.12.x

**Comment by He-Pin** [comment]
```scala
Welcome to the Ammonite Repl 2.4.0 (Scala 2.12.13 Java 1.8.0_341)
@ println(List(1).iterator.drop(1).drop(Int.MaxValue).toList)
List()


@
```
This works fine in 2.12, maybe better to run the tests against both versions. @SethTisue
