### ISSUE TITLE
Scala 2.12 incorrectly assumes invariance

### ISSUE THREAD

**Issue by j-mie6** [scala/bug#12821]
## Reproduction steps

Scala version: 2.12.18

```scala
trait InvK[F[_]]
trait InvKCo[F[+_]]

// object, class, trait all fine
// just need to be able to define `type`s
object Foo {
  // X must occur in a covariant position in A
  type A[+X] = X

  // typechecker incorrectly assumes that A's X is in an invariant position due to F not being F[+_]
  def i: InvK[A] = ???
  def j: InvKCo[A] = ???
}
```

## Problem

In Scala 2.13.11 and Scala 3.3.0, this code compiles entirely fine. In Scala 2.12 however, it reports the following errors:

> covariant type `A` appears in an invariant position in type => `InvK[Foo.A]` of method `i`
> covariant type `A` appears in an invariant position in type => `InvKCo[Foo.A]` of method `j`

Both of these are incorrectly assuming the variance is mismatched, but this is not the case, and adding a covariance annotation as in `InvKCo` does not help either.

There is a workaround, which is to use `@uncheckedVariance`.

(thanks @s5bug for the minimisation :slightly_smiling_face:)

**Comment by SethTisue** [comment]
When something is fixed in 2.13, we don't keep the ticket open. So I'm closing, but note regardless that:

* a 2.12-only ticket may have value as documentation, even closed
* a ticket might prompt someone to attempt to backport the fix to 2.12 (it doesn't _usually_, since not much non-sponsored 2.12 work is happening anymore, but you never know)

Despite our best intentions, closing a ticket is sometimes taken as a slap in the face, as we saw on e.g. #11259. I assure you that's not our intention.

**Comment by SethTisue** [comment]
Not sure what 2.13.2 PR fixed this, but the "Compiler fixes" section of https://github.com/scala/scala/releases/tag/v2.13.2 has a couple of obvious candidates

**Comment by j-mie6** [comment]
> Despite our best intentions, closing a ticket is sometimes taken as a slap in the face, as we saw on e.g. #11259. I assure you that's not our intention.

My face is positively unslapped :slight-smile:

**Comment by j-mie6** [comment]
Do I understand correctly that you verified that it fails on 2.13.1 and not 2.13.2?

In which case, I might try and backport it myself some time in the distant future

**Comment by SethTisue** [comment]
> Do I understand correctly that you verified that it fails on 2.13.1 and not 2.13.2?

yeah. scala-cli is great for this (`scala-cli -S 2.13.1`)

**Comment by j-mie6** [comment]
Awesome. I assume I can `publishLocal` a snapshot of the scala compiler or something if I wanted to test each PR in turn at some point?

**Comment by SethTisue** [comment]
Every merged PR has a corresponding nightly build, not on Maven Central, but on https://scala-ci.typesafe.com/artifactory/scala-integration/ — where scala-cli will look by default if you ask for a version number such as `scala-cli -S 2.13.2-bin-1bde691` (which is the nightly corresponding to scala/scala#8651). So it's relatively easy to `git bisect` in the scala/scala repo — you just `git bisect skip` whenever it suggests a commit other than a PR merge commit.

**Comment by j-mie6** [comment]
Ok amazing, thanks ❤️

Hopefully when I'm free of my PhD restraints I can try and hunt this down!

**Comment by som-snytt** [comment]
> PhD restraints

are you getting a PhD or a BD?

**Comment by j-mie6** [comment]
Definitely PhD @som-snytt 😛
