### ISSUE TITLE
`-Wunused:params` doesn't report on unused param in 2.13.9+

### ISSUE THREAD

**Issue by mrdziuban** [scala/bug#12838]
## Reproduction steps

Scala version: 2.13.9 and up

https://scastie.scala-lang.org/mrdziuban/P84IrKNoS8OP8Y1llFIzOw

```scala
def text(x: Int): Int = 1
```

## Problem

`x` should be reported as unused

**Comment by mrdziuban** [comment]
Thanks for the info @som-snytt!

**Comment by som-snytt** [comment]
The knob is not available yet. Closing as duplicate for that feature.
