### ISSUE TITLE
Scaladoc 2.13.11 failing on illegal URI character in file name

### ISSUE THREAD

**Issue by mdedetrich** [scala/bug#12846]
## Reproduction steps

Scala version: 2.13.11

```scala
final case class `X-Upload-Content-Type` private (contentType: ContentType)
```

Run scaladoc (i.e. `doc` in sbt) to generate Scaladoc from the above Scala code

## Problem

With the above code I get the following error

```
[error] java.net.URISyntaxException: Illegal character in path at index 143: https://github.com/apache/incubator-pekko-connectors/tree/main/google-common/src/main/scala/org/apache/pekko/stream/connectors/google/scaladsl/`X-Upload-Content-Type`.scala#L37
```

This appears to be a regression in Scala 2.13.11 as it works fine in Scala 2.13.10, see https://github.com/apache/incubator-pekko-connectors/pull/139 for more context

Complete stacktrace can be seen here https://gist.github.com/mdedetrich/43d822f08e329f98d72e8131fd807e94

**Comment by som-snytt** [comment]
The difference is not in the source but the filename, which include backticks in the project. (!)
```
scaladoc -doc-source-url "http://acme.com/€{FILE_PATH_EXT}#L€{FILE_LINE}" \`fubar\`.scala
```
errors as shown in 2.13.11.
