### ISSUE TITLE
A (non implicit) value class definition in an object clashes with an inherited nullary method

### ISSUE THREAD

**Issue by noresttherein** [scala/bug#12857]
## Reproduction steps

Scala version: (2.13.11

```scala
trait A {
	def Damn :String = ""
}

object B extends A {
	class Damn(val self :String) extends AnyVal
}
```

## Problem
```
incompatible type in overriding
def Damn: String (defined in trait A);
 found   : B.Damn.type
 required: String
	class Damn(val self :String) extends AnyVal
```
Omitting `extends AnyVal`, or, interestingly enough, adding a type parameter to method `def Damn[X] :String` fixes the issue.

**Comment by som-snytt** [comment]
[The spec](https://docs.scala-lang.org/sips/value-classes.html#step-1-extracting-methods) mandates that the value class have a companion. 

You always minimally get extensions for hashCode and equals.

The terms can be disambiguated using old-timey techniques.

It's a bug that dotty doesn't notice the error, or perhaps it's fooled by its encoding of object as lazy.

```
trait A {
  def Damn: String = "flames"
  //def Damn(implicit i: DummyImplicit): String = "flames"
}

object B extends A {
  class Damn(val self: String) extends AnyVal
}

object Test {
  def main(args: Array[String]): Unit = println {
    //new B.Damn("perdition").hashCode
    B.Damn
  }
}
```
