### ISSUE TITLE
scaladoc 2.13.12 `-doc-source-url` behavior change

### ISSUE THREAD

**Issue by armanbilge** [scala/bug#12867]
Changed in https://github.com/scala/scala/pull/10502

## Reproduction steps

```scala
// /workspace/sandbox/foo.scala
class Foo
```

```
scaladoc -doc-source-url 'http://somewhere€{FILE_PATH}.scala' /workspace/sandbox/foo.scala
```

## Problem

In 2.13.11 we get source links like:

```html
<a href="http://somewhere/workspace/sandbox/foo.scala" target="_blank">foo.scala</a>
```

In 2.13.12 we get:

```html
<a href="http://somewherefoo.scala" target="_blank">foo.scala</a>
```

h/t @Jasper-M, cc @j-mie6

**Comment by som-snytt** [comment]
Probably due to `URI` usage whack-a-mole. I don't know what `-doc-source-url` does, but I am confident there is minimal testing.

**Comment by som-snytt** [comment]
I see

![image](https://github.com/scala/bug/assets/369425/545f1cc5-8d36-469a-aef1-f7c816087a4d)

```
<a href="http://somewhere/tmp/sandbox/foo.scala" target="_blank">foo.scala</a>
```
after
```
scaladoc -d target -doc-source-url 'http://somewhere€{FILE_PATH}.scala' /tmp/sandbox/foo.scala

➜  t12867 scaladoc -version
Scaladoc version 2.13.12 -- Copyright 2002-2023, LAMP/EPFL and Lightbend, Inc.
```

**Comment by armanbilge** [comment]
I just tried again and I'm still getting the same result as above, even with `-d target`.

In case it makes a difference.
```
Linux armanbilge-sandbox-9vtqm47lh3h 6.1.44-060144-generic #202308111259 SMP PREEMPT_DYNAMIC Fri Aug 11 14:20:00 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by j-mie6** [comment]
Can confirm, I've ran the same commands as Arman and you:

`scaladoc -d target -doc-source-url 'http://somewhere€{FILE_PATH}.scala' ~/sandbox/foo.scala`

on 2.13.11 it gives the right link and on 2.13.12 it gives the wrong one, exactly as Arman described.

**Comment by som-snytt** [comment]
For some reason, I need to specify `-sourcepath /tmp` to reproduce.

**Comment by SethTisue** [comment]
I've made a note to myself to add this to the 2.13.12 release notes, as it's very easy to be affected; I just realized that our own published Scaladoc is affected. I just opened #12875 on that

we have officially been hoisted by our own petard and shot ourselves in the foot as we ate our own dogfood

**Comment by SethTisue** [comment]
added to the 2.13.12 notes:

### Scaladoc tool changes

Library authors should be aware that the behavior of `-doc-source-url` has changed, as follows:

* https://github.com/scala/bug/issues/12867

You may need to adjust your build accordingly, to avoid generating broken source links.

**Comment by armanbilge** [comment]
For reference, here's how we fixed it in sbt-typelevel.
https://github.com/typelevel/sbt-typelevel/pull/643/files#diff-0314694cc89c600666817f8d964cb769c7db8f921b9cc76686c0ee3b6f88c8aaR96-R98

```diff
- s"${info.browseUrl}/blob/${vh}€{FILE_PATH}.scala"
+ s"${info.browseUrl}/blob/${vh}/€{FILE_PATH}.scala"
```

**Comment by SethTisue** [comment]
@som-snytt if we had seen this coming, I think we would have sought to avoid inconveniencing library authors; and if we had some other reason to rush a 2.13.13 out, then that would be an opportunity to find a way for library authors not to need to change their builds

but we don't have any other reason to rush 2.13.13, so it seems this change is a fait accompli.

however, we could still consider changes in an eventual 2.13.13 release. I suspect many library authors simply won't notice that their Scaladoc has broken links in it.

Lukas is wondering if we could make both old (slashless) and new (slashful) style configs work? perhaps by inserting the slash automatically if it isn't already present? wdyt, does this make any sense?

**Comment by som-snytt** [comment]
Dotty equivalent where the "source link" is not a special scheme such as `github`:
```
~/projects/dotty/bin/scaladoc -d target -source-links:/tmp/=http://somewhere/€{FILE_PATH}.scala#€{FILE_LINE} /tmp/sandbox/C.tasty
```
The leading "sub-path" is the path prefix to relativize. The file path is always rendered with leading slash, so adding the slash as shown results in a doubled slash.

The mitigation for Scaladoc 2 will be to ensure a separator. `somewhere/€{FILE_PATH_EXT}` vs `somewhere€{FILE_PATH_EXT}` will be at the discretion of anyone who notices the difference.

Wise words from Dotty:

> We should really merge tests for source links to prevent further regressions

**Comment by som-snytt** [comment]
Confirming that Akka has always had double-slash in source links.

![image](https://github.com/scala/bug/assets/369425/2ae5b356-cf26-4eb4-90b2-48ff6ce86a81)

https://doc.akka.io/api/akka/current/akka/actor/AbstractActor.html

https://github.com/apache/incubator-pekko/blob/main/project/Doc.scala#L54

Noticed while wondering what is `"-doc-canonical-base-url"`, which was added for Akka. There are still a couple of checkboxes at

https://github.com/akka/akka.io/issues/623
