### ISSUE TITLE
2.13.12 NoSuchMethodError for scala.tools.nsc.Reporting$PerRunReporting.warning

### ISSUE THREAD

**Issue by Veyronix** [scala/bug#12869]
## Reproduction steps
- Have a library that is built on 2.13.11 and calls the `scala.tools.nsc.Reporting$PerRunReporting.warning` method.
- Have a project that uses the library and upgrade Scala in the project from 2.13.11 to 2.13.12.

## Problem
The project no longer compiles. Reason:
```
java.lang.NoSuchMethodError: 'void scala.tools.nsc.Reporting$PerRunReporting.warning(scala.reflect.internal.util.Position, java.lang.String, scala.tools.nsc.Reporting$WarningCategory, scala.reflect.internal.Symbols$Symbol)'
```

Adding a parameter with a default value to the `warning` method in Scala 2.13.12 made it not binary-compatible.
Commit which introduced the problem https://github.com/scala/scala/commit/e445819e1490c27232f6a828fb832abbc675ded0

**Comment by lrytz** [comment]
Hello, the scala compiler is not binary compatible between releases. If you have a project that depends on the Scala compiler, or on `scala.reflect.internal`, you need to fully cross-build (https://www.scala-sbt.org/1.x/docs/Cross-Build.html#Overriding+the+publishing+convention) and build / release against every Scala minor version. See also https://docs.scala-lang.org/overviews/core/binary-compatibility-of-scala-releases.html#concretely.
