### ISSUE TITLE
Upgrade to ASM 9.6 for JDK 22 support

### ISSUE THREAD

**Issue by Philippus** [scala/bug#12888]
ASM 9.6 came out a few days ago and supports the JDK 22 bytecode version, see https://asm.ow2.io/versions.html. I can create the PR's in https://github.com/scala/scala, if someone else can do the honours in https://github.com/scala/scala-asm.

**Comment by SethTisue** [comment]
will do

**Comment by SethTisue** [comment]
watching https://repo1.maven.org/maven2/org/scala-lang/modules/scala-asm/9.6.0-scala-1/

**Comment by SethTisue** [comment]
@Philippus over to you
