### ISSUE TITLE
When I declare a type  for implicit, implicitly[ClassTag[T]] ==null

### ISSUE THREAD

**Issue by laglangyue** [scala/bug#12905]
## Reproduction steps

Scala version: 2.13

```scala
import scala.reflect.ClassTag

case class File(id: String)

class Parent[T <: AnyRef: ClassTag] {

  private implicit val manifest: Manifest[T] = {
    val classTag = implicitly[ClassTag[T]]
    if (classTag == null) {
      Manifest.classType[T](classOf[AnyRef])
    } else {
      Manifest.classType[T](classTag.runtimeClass)
    }
  }

  def hello(): Array[T] = {
    println(manifest)
    Array.empty
  }
}

class Sun extends Parent[File] {

  def test(): Array[File] = {
    hello()
  }
}

object Main {
  def main(args: Array[String]): Unit = {
    new Sun().test()
  }
}
```

## Problem
Using "private implicit val manifest = {}," implicitly[ClassTag[T]] = File
```shell
File
```
Using "private implicit val manifest: Manifest[T] = {}," implicitly[ClassTag[T]] = null, unable to obtain type File.

```shell
java.lang.Object
Exception in thread "main" java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [LFile; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [LFile; is in unnamed module of loader 'app')
	at Sun.test(Test.scala:27)
	at Main$.main(Test.scala:33)
	at Main.main(Test.scala)
```

**Comment by laglangyue** [comment]
When I use implicit type declaration.

``` scala
import scala.reflect.ClassTag

case class File(id: String)

class Parent[T <: AnyRef: ClassTag] {

  private implicit val manifest: Manifest[T] = {
    val classTag = implicitly[ClassTag[T]]
    if (classTag == null) {
      Manifest.classType[T](classOf[AnyRef])
    } else {
      Manifest.classType[T](classTag.runtimeClass)
    }
  }

  def hello(): Array[T] = {
    println(manifest)
    Array.empty
  }
}

object Main {
  def main(args: Array[String]): Unit = {
    println(new Parent[String].hello())
  }
}
```
then get
```shell
java.lang.Object
[Ljava.lang.Object;@1fbc7afb
```

and using `val manifest: Manifest[T] = {}`
adn will get 
```shell
java.lang.Object
[Ljava.lang.Object;@1fbc7afb

```

**Comment by som-snytt** [comment]
`-Xlint` says
```
t12905.scala:9: warning: Implicit resolves to enclosing value manifest
    val classTag = implicitly[ClassTag[T]]
                             ^
1 warning
```

**Comment by SethTisue** [comment]
also asked at https://stackoverflow.com/questions/77478732/scala-2-13-fix-type-annotation-required-for-implicit-definition-and-cant-get , and on Discord too

@laglangyue it's inconsiderate to ask the same question in lots of places on the Internet without including crosslinks. someone could waste their time helping you in one place, even though you already got helped in another

**Comment by laglangyue** [comment]
year，sorry，get it.I has found how to resolve it，and forgot to close the issue in the other place.



发自我的iPhone


------------------ Original ------------------
From: Seth Tisue ***@***.***&gt;
Date: Wed,Nov 15,2023 2:19 AM
To: scala/bug ***@***.***&gt;
Cc: Laglangyue ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [scala/bug] When I declare a type  for implicit,implicitly[ClassTag[T]] ==null (Issue #12905)





 
also asked at https://stackoverflow.com/questions/77478732/scala-2-13-fix-type-annotation-required-for-implicit-definition-and-cant-get , and on Discord too
 
@laglangyue it's inconsiderate to ask the same question in lots of places on the Internet without including crosslinks. someone could waste their time helping you in one place, even though you already got helped in another

**Comment by laglangyue** [comment]
for `implicit val manifest: Manifest[T]` 
manifest is Manifest[Object], because of `Type Erasure`
for `implicit val manifest=`,due to type inference, I will search for the true type from ClassTag, so I closed this issue.
