### ISSUE TITLE
Upgrade REPL to use JLine 3.25.x

### ISSUE THREAD

**Issue by SethTisue** [scala/bug#12933]
https://github.com/jline/jline3/releases/tag/jline-parent-3.25.0

I'm not comfortable taking the upgrade so close to 2.13.13 release time, but let's take it for 2.13.14.

(and I should check Scala 3 too)

**Comment by lrytz** [comment]
> Merge [Jansi](https://github.com/fusesource/jansi) library into JLine by @gnodet in https://github.com/jline/jline3/pull/871

Need to check if that comes with a change to released artifacts that we have to adapt to.

**Comment by SethTisue** [comment]
3.25.1 is out: https://github.com/jline/jline3/releases/tag/jline-parent-3.25.1

But I'd still be more comfortable waiting for 2.13.14.

**Comment by SethTisue** [comment]
> Need to check if that comes with a change to released artifacts that we have to adapt to

I think not, since we're using the JLine uber-jar.

**Comment by SethTisue** [comment]
needed to fix #12957
