### ISSUE TITLE
With `-quickfix` enabled, `[rewritten by quickfix]` gets printed for every error, regardless of whether or not it was actually fixed/fixable

### ISSUE THREAD

**Issue by coreywoodfield** [scala/bug#12940]
## Reproduction steps

Scala version: 2.13.12

in Test.scala:
```scala
import foo.bar
```
Compiling with `-quickfix:any` prints
```
Test.scala:1: error: [rewritten by -quickfix] not found: object foo
import foo.bar
       ^
1 error
```
## Problem
It says the "not found: object foo" error was "rewritten by -quickfix" but it wasn't, it's not a `quickfixable` error

**Comment by SethTisue** [comment]
Nice catch — thanks for the report.
