### ISSUE TITLE
Boxed values are not checked when creating manifests

### ISSUE THREAD

**Issue by szeiger** [scala/bug#12945]
## Reproduction steps

Scala version: Reproduced in 2.13.12 and 2.12.18

```scala
val o: Option[Long] = Option[Int](42).asInstanceOf[Option[Long]]

println(o.get.getClass) // prints "long"
val l = o.get // throws ClassCastException: class java.lang.Integer cannot be cast to class java.lang.Long
```

```
      26: invokevirtual #59                 // Method o:()Lscala/Option;
      29: invokevirtual #65                 // Method scala/Option.get:()Ljava/lang/Object;
      32: getstatic     #70                 // Field scala/reflect/ClassTag$.MODULE$:Lscala/reflect/ClassTag$;
      35: invokevirtual #74                 // Method scala/reflect/ClassTag$.Long:()Lscala/reflect/ManifestFactory$LongManifest;
      38: invokevirtual #78                 // Method scala/runtime/ScalaRunTime$.anyValClass:(Ljava/lang/Object;Lscala/reflect/ClassTag;)Ljava/lang/Class;
```

## Problem

While `o.get` is actually called (and the returned value apparently stays on the stack and is not discarded before the end of the method), the value is ignored because it's not needed for the primitive ClassTag. This also prevents it from throwing a ClassCastException.

Since `getClass` is defined on `Any` one could argue that no instance check should be expected at this point. What makes this corner case confusing is the fact that it returns the wrong manifest for the instance.

**Comment by lrytz** [comment]
I'd say this can be filed away under "we can't guarantee runtime behavior when using `asInstanceOf`". It's telling the compiler "believe me, this is an `Option[Long]`", so the compiler continues assuming it's an `Option[Long]`.
