### ISSUE TITLE
Regression in scaladoc compilation when using in Scala 3 definitions

### ISSUE THREAD

**Issue by WojciechMazur** [scala/bug#12955]
## Reproduction steps

Scala version: 2.13.13
Tested with Scala 3 versions for cross compiled project: 3.3.1 and 3.3.2

[reproduction-sbt.zip](https://github.com/scala/bug/files/14372699/repro.zip)
run with `sbt "base/publishLocal; projectC/publishLocal"`

1. Define ADT in Scala 3, create a jar out of it
```scala
package testlib

enum ADT:
  case SingletonCase
  case ClassCase(x: String)
```

2. Define Scala 2 project that uses Scala 3 JAR 
```scala
package app

object Main {
  def main(args: Array[String]): Unit = {
    println(testlib.ADT.SingletonCase)
    println(testlib.ADT.ClassCase("foo"))
  }
}
```

3. Try to create documentation for Scala 2 project, (`sbt Compile/doc`)

## Problem

Compilation fails with 
```
error] stack trace is suppressed; run last projectC / Compile / doc for the full output
[error] (projectC / Compile / doc) scala.reflect.internal.Types$TypeError: Unsupported Scala 3 generic tuple type scala.Tuple in bounds of type MirroredElemTypes; found in  scala.deriving.Mirror.<refinement>.
[error] Total time: 0 s, completed Feb 22, 2024, 11:42:57 AM
```

**Comment by lrytz** [comment]
cc @bishabosha

**Comment by bishabosha** [comment]
writing here to confirm that it works in 2.13.12, so definitely something changed

**Comment by lrytz** [comment]
It's possible that the bug / behavior in the tasty reader is older but more symbols are forced in the new version of scaladoc.

**Comment by bishabosha** [comment]
I build scala 2.13 at ffc0297072ca8248daac279781d0dea5680c3a86 (the commit before any of my changes) and it works, then at the classpath changes in e6232614795da850e2c834316caa2d16b83a07ed it breaks, to confirm, I build at 6b2c4aedc7d4d7d6a629b2ade6a6c04fe864ee14 (the commit before) and it works again.

**Comment by lrytz** [comment]
Is it possible that before we didn't find all tasty files? Did [this work for `object`s](https://github.com/scala/scala/commit/e6232614795da850e2c834316caa2d16b83a07ed#diff-48440af466bc60ce77eb8afa75128abf7863f2bcba7a3153cf3adad0271df0b1L1234)?

I guess I would add a few logs of when the classfile parser / tasty reader is invoked in both before and after.

**Comment by bishabosha** [comment]
> Is it possible that before we didn't find all tasty files? Did [this work for objects](https://github.com/scala/scala/commit/e6232614795da850e2c834316caa2d16b83a07ed#diff-48440af466bc60ce77eb8afa75128abf7863f2bcba7a3153cf3adad0271df0b1L1234)?

im not sure this is the reason, i.e. the tasty attribute was always in `foo.class` for `object foo`, never `foo$.class`, so in theory the same files should be forced.

> I guess I would add a few logs of when the classfile parser / tasty reader is invoked in both before and after.

looks the only way to know for sure

**Comment by bishabosha** [comment]
adjusting for symbol ID, first diffs are pretty strange

<img width="643" alt="Screenshot 2024-02-23 at 15 02 18" src="https://github.com/scala/bug/assets/13436592/e23cb4b6-c16b-4614-84d2-d95dcea7d5d8">

**Comment by bishabosha** [comment]
Finally I have solved it.

Those were not being ignored because the `sourceFile` on the symbol was `!= null` so was assumed to be a source file in the project. I had not added the case for `".tasty"` to ignore in `associatedFile`.
