### ISSUE TITLE
Default implicit not enabled for outer object if it is not a singleton

### ISSUE THREAD

**Issue by tribbloid** [scala/bug#12952]
## Reproduction steps

Scala version: 2.13.12

```scala
object ImplicitDefaultScope {
  trait Case[T]
  object case1 {
    trait Outer {
      case class A(v: String)
      implicit def caseA: Case[A] = ???
    }
    {
      def fn(o: Outer) = {
        implicitly[Case[o.A]]
      }
    }
  }
}
```

## Problem

Compiles in Scala 3 (tested 3.4-SNAPSHOT)

Failed in Scala 2:

```
: could not find implicit value for parameter e: ai.acyclic.prover.commons.util.ImplicitDefaultScope.Case[o.A]
```

**Comment by SethTisue** [comment]
When opening a ticket in scala/bug, please don't just offer code that doesn't compile; make a case that this is a bug in Scala 2.

If you feel you don't have the time or energy for that and just want to ask your question, please use https://users.scala-lang.org instead of the bug tracker.

**Comment by SethTisue** [comment]
btw, we've recently improved the repo readme here in scala/bug to emphasize this more; see https://github.com/scala/bug/pull/12950 and the recent discussion on #12949

**Comment by som-snytt** [comment]
☑️ compiles in dotty

The implicit is available via the prefix of `o.A`, not just the prefix of `Case`. The implicit scope is the implicit scopes of all the parts.

**Comment by SethTisue** [comment]
Minimized a bit:

```
trait Case[T]
trait Outer {
  case class A(v: String)
  implicit def caseA: Case[A] = ???
}
def fn(o: Outer) =
  implicitly[Case[o.A]]
```

**Comment by SethTisue** [comment]
As an example of what I mean by citing relevant documentation before filing a bug report, is there anything relevant in https://docs.scala-lang.org/scala3/reference/changed-features/implicit-resolution.html  ...? If you looked and there isn't, say so.

**Comment by som-snytt** [comment]
☑️ `tldr;`

The important change is that packages in the prefix no longer contribute; that was lrytz's recent warning.

**Comment by SethTisue** [comment]
> that was lrytz's recent warning

I guess you mean https://github.com/scala/scala/pull/10621 ? I haven't looked closely at it, but the title implies it's specific to package prefixes, but here the prefix `o` isn't a package?

**Comment by som-snytt** [comment]
Yes, I intended to say that the significant change does not apply to this case.

**Comment by tribbloid** [comment]
@SethTisue you are right they are different. The prefix `o` is a non-singleton, non-package object.

For the others, I'll try to revise all the tickets in the past (and re-open them if necessary)

**Comment by SethTisue** [comment]
thanks. and yes, any closing of tickets is only provisional

**Comment by joroKr21** [comment]
I think the relevant difference in the spec is:
### Scala 3
> If T is a reference to an anchor of the form p.A then S also includes all term references on the path p.

### Scala2
> if T is a singleton type p.type, the parts of the type of p;

"Parts of the type of p" include e.g. `object Outer` (because `o: Outer`) but not `o.type` itself.
