### ISSUE TITLE
-Xgenerate-phase-graph is -Xdegenerate-phase-graph

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12959]
## Questions are not bug reports

Is this feature supposed to work?

## Reproduction steps

Scala version: 2.13.13

```scala
➜  scalac -Xgenerate-phase-graph pg
Phase graph of 24 components output to pg*.dot.
➜  ls -l pg*.dot
[snip] 2 Feb 26 08:10 pg-1.dot
[snip] 2 Feb 26 08:10 pg-2.dot
[snip] 2 Feb 26 08:10 pg-3.dot
[snip] 2 Feb 26 08:10 pg-4.dot
➜  snips sdk use scala 2.12.18

Using scala version 2.12.18 in this shell.
➜  scalac -Xgenerate-phase-graph pg13
Phase graph of 24 components output to pg13*.dot.
➜  ls -l pg13*.dot
[snip] 1156 Feb 26 08:11 pg13-1.dot
[snip] 1156 Feb 26 08:11 pg13-2.dot
[snip] 1156 Feb 26 08:11 pg13-3.dot
[snip] 1261 Feb 26 08:11 pg13-4.dot
```

## Problem

The dot files in 2.13 are degenerate. (Maybe only the last line is output?)

Since no one uses the compiler option, it should be removed or deprecated as not functional.

Probably the dot file output is not helpful, but `-Vphases --debug --verbose` should list the input components with their constraints, and also output the `infoTransformers` which correspond to the phases which contribute them.

(Pun on 2.13 and PG-13 is intended.)

**Comment by som-snytt** [comment]
https://github.com/scala/scala/commit/759b9795e908a0098b18abc25a88c32d625304bd
says

`Log phase levels under scalac -Xshow-phases -Ydebug -Ylog:all `

so bigger brains have trod this path before.

Logging does announce info transformers, which is almost as good as a summary.

The example from dependency graph rewrite was that async phase relied on alpha sorting.

**Comment by SethTisue** [comment]
If you (or anyone) tinkers with this, I'd suggest renaming this to be a `-Y` flag.

**Comment by som-snytt** [comment]
To increase the likelihood of a quick merge, the PR renames it `-Vphase-graph` with alias ("abbreviation") to existing name. This is a good time to do that, since no one uses the option and possibly never will. That should be the semantics of `-Z`, stuff no one uses.
