### ISSUE TITLE
Scala 2.13.13 breaks genjavadoc

### ISSUE THREAD

**Issue by mdedetrich** [scala/bug#12966]
## Reproduction steps

Scala version: 2.13.13

See https://github.com/lightbend/genjavadoc/issues/347 for details of reproduction

## Problem

The latest Scala 2.13.13 breaks genjavadoc (works fine in Scala 2.13.12). I am not sure where the core problem lies, i.e. if genjavadoc needs to be updated to handle some new behaviour or if its an actual regression in Scala 2.13.13

**Comment by som-snytt** [comment]
Guessing https://github.com/scala/scala/pull/10517 for impedance mismatch.

The stack says missing deprecationInfo?

**Comment by lrytz** [comment]
Yep, thanks! https://github.com/lightbend/genjavadoc/pull/348
