### ISSUE TITLE
dependencyTree::toFile cmd does not produces correct results

### ISSUE THREAD

**Issue by cp-endor** [scala/bug#12963]
Consider below example:
my `build.sbt` has 4 projects :
`proj-1 --> aggregates(proj2, proj3)`
`proj-2`
`proj-3`
`proj-4`

Now i want to generate dependencyTree and put result in a file eg. `sbt proj-1 / dependencyTree::toFile abc.txt`, now when I try to run this cmd on projects which aggregates sub-projects lets say `proj-1` in above example, the `dependencyTree` task will throw and error like:

> [error] (corelib / Compile / dependencyTree / toFile) Target file for dependencyTree already exists at /Users/cam/first-proj/abc.txt. Use '-f' to override

now if I use `-f` flag this error will not come but the file `abc.txt` will contain the output of any project from `proj-1`, `proj-2` or `proj-3` and it is never consistent. 

Now I have few question :
1. Is there a way I can tell `sbt` to not run the task on subprojects eg. in the above case, I want to run task only on `proj-1` and not on its aggregates `proj-2` and `proj-3`.
2. Is there any other way I can always get the consistent result in output file using `dependencyTree::toFile` ?
3. Is it a fair ask to patch the `dependencyTree` code in `sbt-dependency-graph` plugin by changing the logic in `toFIle` task, [here](https://github.com/sbt/sbt-dependency-graph/blob/master/src/main/scala/net/virtualvoid/sbt/graph/DependencyGraphSettings.scala#L205)

**Comment by som-snytt** [comment]
@cp-endor this is the bug tracker for `scalac`, not `sbt` or its projects. Probably you want to ask your question on an sbt forum such as https://discord.com/channels/632150470000902164/922600050989875282
