### ISSUE TITLE
Type mismatch with a `+` operator in an extension method of a newtype

### ISSUE THREAD

**Issue by hmemcpy** [scala/bug#12960]
Scala version: 2.13.13 (under `Xsource:3`)

The following code, under `Xsource:3` with Scala 2.13.13:

```scala
  type Point = Point.Type
  object Point {
    type Type <: Any
    def apply(x: Int): Point = x.asInstanceOf[Point]

    implicit final class MyExt(val myInt: Point) extends AnyVal {
      def +(other: Int): Point = ???
    }
  }

  val p = Point(3)
  val p2 = p + 2
```
Produces the following error:

```
type mismatch;
 found   : Int(2)
 required: String
    val p2 = p + 2
```

## Problem

The problem started after upgrading to Scala 2.13.13. We use the [scala-newtype](https://github.com/estatico/scala-newtype) library, and some of our newtypes that define a `+` operator started to fail with the error above.
The code snippet is the simplified "expanded" version of the newtype macro that also exhibits the problem:
```scala
@newtype case class Point(i: Int)
  def +(other: Int): Point
}
```

In all previous versions, this code compiled fine under Xsource:3.

**Comment by SethTisue** [comment]
As of 2.13.13, `-Xsource:3` only causes warnings to be omitted; it never (unless we missed something!) causes other behavior changes.

So it seems expected to me that if the code used to require `-Xsource:3` to compile, it might now instead require `-Xsource:3-cross`, which does enable behavior changes.

**Comment by SethTisue** [comment]
By the way, we have done our best to be clear about this in the 2.13.13 release notes as well as the PR description at https://github.com/scala/scala/pull/10573 — if you think further edits would help make the situation clearer, let us know.

**Comment by som-snytt** [comment]
I confirmed that it needs `-Xsource:3-cross`.

**Comment by hmemcpy** [comment]
Yeah, was about to update that it does work under `3-cross`. Thanks for checking!

**Comment by hmemcpy** [comment]
Sorry for the bump: Just wanted to understand why it thinks the `+` comes from `any2stringadd` now...

**Comment by som-snytt** [comment]
import is not necessary under `-Xsource:3-cross`.

https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/typechecker/Contexts.scala#L1078

**Comment by hmemcpy** [comment]
Right, sorry, I deleted my comment. We can't switch to 3-cross (yet) because of the overridden member type inference change - it causes a lot of type mismatches for us (because we omit type signatures practically everywhere) and it doesn't play nice with ZIO's contravariant R parameter (something I encountered here #12707). Unfortunately, fixing it on our side is too "expensive" in terms of changes...

Anyway, with the Xsource:3 changes I am finally able to upgrade our codebase to the latest Scala 2.13.13 without (many) additional changes, except this one (and another one having to do with infix operators beginning on a new line).

Anyway, thanks for checking, let's keep this issue closed.

**Comment by som-snytt** [comment]
We didn't mention that `-Yno-predef` also suffices for the example; or `-Yimports` to provide a custom `Predef` that omits what is undesirable and supplies what is necessary.

**Comment by lrytz** [comment]
> because we omit type signatures practically everywhere

Is there a technical reason or would everything work with explicit types?

> fixing it on our side is too "expensive" in terms of changes

With 2.13.13 you could try `-quickfix:msg=under -Xsource:3-cross, the inferred type changes` to have the compiler add the result types
