### ISSUE TITLE
Scaladoc accepts grammar errors

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12962]
## Reproduction steps

Scala version: 2.13 using `-Xsource:3-grammar`

```scala
/** A helper class to catch errors with. */
class ErrorCatcher
```

## Problem

If Scaladoc accepts faulty grammar, which can be caught with modern tooling, then we are on the road to proverbial perdition.

https://www.npr.org/2024/02/27/1233663125/grammar-preposition-sentence-rule-myth-merriam-webster-dictionary

**Comment by SethTisue** [comment]
“This is the sort of nonsense up with which I will not put.” — Winston Churchill

**Comment by som-snytt** [comment]
Closing as "not a blocker" and also "not willing to hear Miles object to my grammar nits".
