### ISSUE TITLE
Import given

### ISSUE THREAD

**Issue by som-snytt** [scala/bug#12999]
## Reproduction steps

Scala version: 2.13.14

under -Xsource:3-cross, `import ExecutionContext.Implicits.given` is ignored rather than taken as `*`.

## Problem

If cross-compiling, I don't want `*`, even if scala 2 must approximate `given`.

Also, it would probably be easy to just make `given` actually work in imports.

**Comment by SethTisue** [comment]
I don't understand why simply ignoring the import should be considered wrong?

**Comment by eed3si9n** [comment]
The semantics of `import ExecutionContext.Implicits.given` in Scala 3 is that it imports the implicits into the scope, so I guess you might consider treating it as `import ExecutionContext.Implicits._` to match the energy?

**Comment by som-snytt** [comment]
Yes, for cross compiling, I think at least take given as star; with the caveat of course that it mustn't break imports, `import x.{given, *}` must not introduce ambiguities.

If I were cross compiling, I would not want to write `Implicits.{given, *}` for dotty.

**Comment by som-snytt** [comment]
reminder
```
import-given.scala:13: error: value given is not a member of object T
  import T.given
```
and under `-Xsource:3`
```
import-given.scala:14: error: given requires a wildcard selector
  import T.{foo, given}
```
