### ISSUE TITLE
Not found: value

### ISSUE THREAD

**Issue by TDklm** [scala/bug#13012]
Hello
   I am reproducing work on [Amandroid](https://github.com/arguslab/Argus-SAF/tree/master),I encountered some errors, and I think this may be due to a version update causing a change in the method. The [code ](https://github.com/arguslab/Argus-SAF/blob/master/jawa/src/main/scala/org/argus/jawa/flow/summary/SummaryManager.scala)is as follows：
![image](https://github.com/scala/bug/assets/94581265/86784ce2-c47b-4a68-b24e-2fec69c5bda4)
error:
not found: value summary
  def getHeapSummaryPb(sig: Signature): Option[summary.HeapSummary] 
I use jdk13 scala2.13.14 IDEA2022.3.2 
If you know how to solve it, please let me know. Thank you in advance.

**Comment by som-snytt** [comment]
You're talking about
https://github.com/arguslab/Argus-SAF/blame/master/jawa/src/main/scala/org/argus/jawa/flow/summary/SummaryManager.scala#L71
which was touched at
https://github.com/arguslab/Argus-SAF/commit/8d39a020788b5fd84ff73d8154d6f585b3d24be3

If you run the build, as I just did, you'll see
```
./jawa/target/scala-2.12/src_managed/main/protos/org/argus/jawa/flow/summary/summary/HeapSummary.scala
```

**Comment by TDklm** [comment]
Thank you for your reply. I have checked that my file has been updated in the link you provided, but there are still errors. I have checked my file located in jawa/target/scala-2.12/and cannot find the src_managed folder.In fact, there is another question [above](https://github.com/arguslab/Argus-SAF/blame/master/jawa/src/main/scala/org/argus/jawa/flow/summary/SummaryManager.scala#L71) in the flowing picture
![image](https://github.com/scala/bug/assets/94581265/2fc9d46d-a0fd-4c3a-a5c4-97c1208e6fef)
I am a freshman in Scala. If you have any suggestions, I would greatly appreciate it

**Comment by SethTisue** [comment]
@TDklm please use https://users.scala-lang.org or the chat rooms for questions (or see https://scala-lang.org/community for other options such as Discord)
