### ISSUE TITLE
incorrect version in `scala.util.Properties`

### ISSUE THREAD

**Issue by m-gris** [scala/bug#13042]
## Environment
- Scala CLI version: 1.5.1
- Default Scala version: 3.5.1
- Java version: OpenJDK 11.0.22
- OS: macOS Sonoma 14.3

## Issue Description
When using Scala CLI (version 1.5.1) with Scala 3.5.1, `scala.util.Properties.versionString` reports Scala version 2.13.14, despite the REPL running Scala 3.5.1 features correctly.

## Steps to Reproduce
1. Start Scala CLI REPL:
   ```
   scala-cli repl -S 3.5.1
   ```
2. Check Scala version property:
   ```scala
   scala.util.Properties.versionString
   ```
3. Test a Scala 3-specific feature:
   ```scala
   enum Color:
     case Red, Green, Blue
   
   Color.Red
   ```

## Actual Behavior
- `scala.util.Properties.versionString` returns "version 2.13.14"
- The Scala 3 enum syntax works correctly, confirming Scala 3 is indeed running

## Expected Behavior
`scala.util.Properties.versionString` should report version 3.5.1, matching the actual Scala version in use.

## Additional Information
- The REPL welcome message correctly states "Welcome to Scala 3.5.1"
- Scala 3 syntax works as expected in the REPL
- This behavior persists even after clearing Coursier cache (`cs clean`) and updating Scala CLI

**Comment by som-snytt** [comment]
This is a FAQ. https://docs.scala-lang.org/tutorials/FAQ/index.html#i-want-scala-3-why-does-versionnumberstring-say-im-on-213

**Comment by m-gris** [comment]
Noted. Thx.
