### ISSUE TITLE
No compilation error when declaring a parameter implicit

### ISSUE THREAD

**Issue by gaeljw** [scala/bug#13049]
## Reproduction steps

Scala version: 2.13.15 (also reproduced with earlier 2.13.x versions)

Reproduction repository: https://github.com/gaeljw/scalabugimplicit

<details>

<summary>Reproduction code</summary>

```scala
package example

import scala.collection.Seq

trait DataTableOptionalEntryDefinitionBody[T] {

  def transform(entry: Map[String, Option[String]]): T

}

case class ScalaDataTableOptionalEntryTypeDetails[T](body: DataTableOptionalEntryDefinitionBody[T])

trait DataTableDsl {

  protected var registry: Seq[ScalaDataTableOptionalEntryTypeDetails[_]] = Seq.empty

  def DataTableType: DataTableTypeBody = new DataTableTypeBody()

  final class DataTableTypeBody {

    def apply[T](body: DataTableOptionalEntryDefinitionBody[T]): Unit = {
      registry = registry :+ ScalaDataTableOptionalEntryTypeDetails[T](body)
    }

  }

}

case class Hello(x: Option[String])

class HelloSpec extends munit.FunSuite with DataTableDsl {

  DataTableType { implicit entry: Map[String, Option[String]] =>
    val entryValue: Option[String] = entry("x")
    // isDefined is not a method of String, why does it even compile?
    val x = entryValue.filter(_.isDefined)
    Hello(x)
  }

  test("say hello") {
    val hello = registry.head.body.transform(Map("x" -> Some("pouet")))
    assertEquals(hello, Hello(Some("pouet")))
  }

}
```
</details>

_This is a minified example. For the record we noticed the issue in a real-world test when using [cucumber-scala](https://github.com/cucumber/cucumber-jvm-scala) library._

Run the above test case.

## Problem

The above test case fails at runtime with the following error:

```
java.util.NoSuchElementException: key not found: pouet
	at scala.collection.immutable.Map$Map1.apply(Map.scala:263)
	at example.HelloSpec.$anonfun$new$2(HelloSpec.scala:36)
	at example.HelloSpec.$anonfun$new$2$adapted(HelloSpec.scala:36)
	at scala.Option.filter(Option.scala:319)
	at example.HelloSpec.$anonfun$new$1(HelloSpec.scala:36)
	at example.HelloSpec.$anonfun$new$3(HelloSpec.scala:41)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
```

Whereas I'd expect to not even compile because of the following lines:
```scala
val entryValue: Option[String] = entry("x")
// isDefined is not a method of String, why does it even compile?
val x = entryValue.filter(_.isDefined)
```

## Additional information

If we remove the `implicit`:
```diff
- DataTableType { implicit entry: Map[String, Option[String]] =>
+ DataTableType { entry: Map[String, Option[String]] =>
```

It works as expected: the code does not compile.

**Comment by joroKr21** [comment]
`Map[String, Option[String]]` extends `String => Option[String]` which acts as an implicit conversion.
It's not a good idea to make collections implicit.

**Comment by sjrd** [comment]
This is working as designed. `Map[K, V]` extends `K => V`. When you have an `implicit K => V` in scope, you can implicitly convert a `K` to a `V`. This allows `str.isDefined` to compiled by converting `str` from `K = String` to `V = Option[String]`.

**Comment by som-snytt** [comment]
Could also add the label, "fixed in Scala 3" for language improvements.

**Comment by gaeljw** [comment]
For the record, the use of `implicit` was not desired but a mistake we lost few hours to spot 😅

Thanks a lot for the explanation and very fast answer 🙏
