### ISSUE TITLE
false positive of unused var when inside pattern match 2.13.15

### ISSUE THREAD

**Issue by Zuchos** [scala/bug#13046]
After bumping Scala to 2.13.15 with an unused warning, I'm getting a false positive warning. I extracted a synthetic case

## Reproduction steps

Scala version: 2.13.15

```scala
object Test {
  def split(): Option[(Int, Int)] = ???
  def doIt(): Option[Int] = {
    Some((1, 2)).flatMap { case (_, _) =>
      for {
        (c, d) <- split()
        e       = c + d
      } yield {
        e
      }
    }
  }
}

Test.scala:9:9: pattern var e in value $anonfun is never used
[error]         e       = c + d
[error]         
```

**Comment by Zuchos** [comment]
Ok, looks like a duplicate of https://github.com/scala/bug/issues/13041
In particular, this comment proves that the filter is not the case https://github.com/scala/bug/issues/13041#issuecomment-2377958799

**Comment by som-snytt** [comment]
Thanks, I verified the example does not warn on head.
