### ISSUE TITLE
Implicit search for Numeric[T] warns about "No implicit Ordering defined"

### ISSUE THREAD

**Issue by JD557** [scala/bug#13053]
## Reproduction steps

Scala version: 3.5.1

```scala
scala> List(Some(1), Some(2), None).sum
-- [E172] Type Error: ----------------------------------------------------------
1 |List(Some(1), Some(2), None).sum
  |                                ^
  |                             No implicit Ordering defined for Option[Int].
1 error found
```

## Problem

The error should be "No implicit **Numeric** defined for Option[Int].". The current error is quite confusing:^
- There is an `Ordering[Int]` implicit in scope
- Why would I need an `Ordering` to sum?

I believe this is caused because `Numeric[T] extends Ordering[T]` (https://github.com/scala/scala/blob/v2.13.14/src/library/scala/math/Numeric.scala#L221) and `Ordering[T]` has an implicit not found annotation https://github.com/scala/scala/blob/v2.13.14/src/library/scala/math/Ordering.scala#L72C1-L73.

A simple fix could be to just add and `@annotation.implicitNotFound(msg = "No implicit Numeric defined for ${T}.")` to `Numeric`.

**Comment by som-snytt** [comment]
This is the issue where Scala 3 does it differently (or wrong):
```
Welcome to Scala 2.13.15 (OpenJDK 64-Bit Server VM, Java 23).
Type in expressions for evaluation. Or try :help.

scala> List(Some(1), Some(2), None).sum
                                    ^
       error: could not find implicit value for parameter num: scala.math.Numeric[Option[Int]] (No implicit Ordering defined for Option[Int].)

scala>
```

**Comment by JD557** [comment]
Ah, indeed I only tested in Scala 3. The Scala 2.13 error message is much clearer.

**Comment by SethTisue** [comment]
> A simple fix could be to just add and @annotation.implicitNotFound(msg = "No implicit Numeric defined for ${T}.") to Numeric.

Or remove the one from `Ordering`? Is the one on `Ordering` actually an improvement on what the compiler would say otherwise?

**Comment by som-snytt** [comment]
We could improve what the compiler would say otherwise.

I don't know what `num` is in the example, or `e` here:

```
scala> trait T[A]
trait T

scala> implicitly[T[Int]]
                 ^
       error: could not find implicit value for parameter e: T[Int]
```
rather than
```
"Using `implicitly` requires an implicit value of type `T[Int]`, but none was found."
```
Sample message on `SortedSet`, to point out that the advice can be specific:
```
"No implicit Ordering[${B}] found to build a SortedSet[${B}]. You may want to upcast to a Set[${A}] first by calling `unsorted`."
```

**Comment by SethTisue** [comment]
Let's just remove the one on `Ordering`, then. PR: scala/scala#10913

> We could improve what the compiler would say otherwise.

indeed! (but, separate issue)
