### ISSUE TITLE
ArrayBuilder.ofUnit.addAll throws java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by dragonfly-ai** [scala/bug#13068]
## Reproduction steps

```scala
val ab = new scala.collection.mutable.ArrayBuilder.ofUnit
val aou = Array[Unit]((), (), ())
ab.addAll(aou)
```
Please consider [this relevant Scastie](https://scastie.scala-lang.org/0wALRcgfQ7eSgVL96BwaxA)

## Problem
This should add three `Unit` values to the `ArrayBuilder`, but instead it throws `UnsupportedOperationException`.  

A straight forward fix involves overriding the `addAll` method in the `ofUnit` class so that it doesn't default to the one it inherits from the `ArrayBuilder[T]` abstract class:
```scala
def addAll(xs: Array[_ <: T]): this.type = doAddAll(xs, 0, xs.length)
```
The `doAddAll` method in `ArrayBuilder` accesses the `ofUnit.elems` method which, by design, always throws `UnsupportedOperationException` because the `ofUnit` builder never actually populates array data until the invocation of its `.result()` method.

[ArrayBuilder.scala#L497](https://github.com/scala/scala/blob/301d2db99fe72b96888a7eca1fc2a1f51ebabdc0/src/library/scala/collection/mutable/ArrayBuilder.scala#L497)

Please see [prior discussion on the Scala discord](https://discord.com/channels/632150470000902164/632150470000902166/1317015802679005265).

**Comment by SethTisue** [comment]
@scala/collections
