### ISSUE TITLE
Scala 2.13.15: warn unused false positive when pattern matching on HOF parameter

### ISSUE THREAD

**Issue by PiotrBosak** [scala/bug#13061]
## Reproduction steps
https://scastie.scala-lang.org/LI6ZuhHfS3CjvYepfhJjyw
Scala version: 2.13.15 with `"-Ywarn-unused"` flag
(Is the bug only in Scala 3.x? If so, report it at [scala/scala3](https://github.com/scala/scala3/issues/new/choose) instead.)

```scala
    List(("first", "second"))
      .map { case (_, _) =>
        for {
          a <- Some("a")
          b = a // b is not used warning
        } yield b
      }
```

## Problem
When using a pattern match anonymous function in a HOF, variables assigned inside 
a for-comprehension(b = a) are reported as unused.
Same snippet in 2.13.14 works fine.

Explain how the above behavior isn't what you expected.
Do not report it as unused since it clearly is used

## Workaround
```
  List(("first", "second"))
    .map { a =>
      a match {
        case (_, _) =>
          for {
            a <- Some("a")
            b = a
          } yield b
      }
    }
```

**Comment by som-snytt** [comment]
Thanks for the report. This is fixed for 2.13.16 in https://github.com/scala/scala/pull/10870
