### ISSUE TITLE
Optimize simple for loops

### ISSUE THREAD

**Issue by scabug** [scala/bug#1338]
I would like to suggest the compiler optimize the common case of for loops, that is, 

```scala
for (var <- Range [by step])
for (var <- int to int [by step])
for (var <- int until int [by step])
```

to use while loops under the covers instead of. Currently, nested for loops using ranges/iterators are sometimes an order of magnitude slower than while loops. However, while loop constructs for iterating over arrays are very cumbersome, and the functional style (foreach) is also cumbersome and introduces a lot of function call overhead as well.

The following two matrix multipication implementations

```scala
  def matMulUsingIterators (
       a : Array[Array[Double]],
       b : Array[Array[Double]],
       c : Array[Array[Double]]) : Unit = {

    val b_j = new Array[Double](b.length)

    for (j <- 0 until b(0).length) {
        for (k <- 0 until b.length) {
            b_j(k) = b(k)(j)
        }
        for (i <- 0 until a.length) {
            val c_i = c(i)
            val a_i = a(i)
            var s = 0.0d;
            for (k <- 0 until b.length) {
                s += a_i(k) * b_j(k)
            }
            c_i(j) = s
        }
    }
  }

  def matMulUsingRanges (
       a : Array[Array[Double]],
       b : Array[Array[Double]],
       c : Array[Array[Double]]) : Unit = {

    val jRange = 0 until b(0).length;
    val kRange = 0 until b.length;
    val iRange = 0 until a.length;

    val b_j = new Array[Double](b.length)

    for (j <- jRange) {
        for (k <- kRange) {
            b_j(k) = b(k)(j)
        }
        for (i <- iRange) {
            val c_i = c(i);
            val a_i = a(i);
            var s = 0.0d;
            for (k <- kRange) {
                s += a_i(k) * b_j(k)
            }
            c_i(j) = s
        }
    }
  }
```

are much slower than the same algorithm coded with while loops:

```scala
  def matMulUsingWhileLoop (
      a : Array[Array[Double]],
      b : Array[Array[Double]],
      c : Array[Array[Double]]) : Unit = {

    val m = a.length;
    val p = b(0).length;
    val n = b.length;

    val b_j = new Array[Double](b.length);

    var i = 0; var j = 0; var k = 0;
    while (j < p) {
        k = 0
        while (k < n) {
            b_j(k) = b(k)(j);
            k += 1
        }
        i = 0
        while (i < m) {
            val c_i = c(i);
            val a_i = a(i);
            var s = 0.0d;
            k = 0;
            while (k < n) {
                s += a_i(k) * b_j(k);
                k += 1
            }
            c_i(j) = s;
            i += 1
        }
        j += 1;
    }
  }
```

but the while loop code is more complex and error prone.

(Sorry, Trac appears to remove some line breaks; I
added some explicit semis but might have missed some;
I'll try attaching actual working source code)

Running this while measuring time in nanoseconds:

```scala
Iterators   2,807,815,301ns
Ranges      2,789,958,191ns
While Loop  190,778,574ns
```

MatMul by Iterators is 14 times as slow as with while loops.

It does not appear that the Hotspot runtime profiling and optimization dramatically helps this performance problem
This performance problem can hurt adoption of Scala for many types of uses/applications.

**Comment by SethTisue** [comment]
@lrytz is this fixed in 2.13 by any chance? with the optimizer enabled, I mean?

**Comment by SethTisue** [comment]
do you agree we should now close this, as per https://github.com/scala/scala/pull/8069 ?

**Comment by ashawley** [comment]
It would seem the noise probably could have started 6 years ago back when 2.10 was released.

I copied the benchmark from https://github.com/scala/scala/pull/8069 out of the Scala project to a fresh sbt 0.13 project and ran it against 2.10.7, 2.11.12, 2.12.8 and 2.13.0.  My laptop is a little quieter than when I initially did this, so the variance is a little less with these numbers.

**2.10.7**

    Benchmark             (size)  Mode  Cnt       Score      Error  Units
    matMulUsingIterators      10  avgt   20        2.32 ±     0.06  us/op
    matMulUsingRanges         10  avgt   20        2.46 ±     0.06  us/op
    matMulUsingWhileLoop      10  avgt   20        1.17 ±     0.33  us/op
    matMulUsingIterators     100  avgt   20     1294.35 ±    26.09  us/op
    matMulUsingRanges        100  avgt   20     1547.63 ±    36.67  us/op
    matMulUsingWhileLoop     100  avgt   20     1101.28 ±    56.62  us/op
    matMulUsingIterators    1000  avgt   20  1450647.85 ± 50986.23  us/op
    matMulUsingRanges       1000  avgt   20  1609264.80 ± 37524.73  us/op
    matMulUsingWhileLoop    1000  avgt   20  1442805.40 ± 24099.38  us/op

**2.11.12**

    Benchmark             (size)  Mode  Cnt       Score      Error  Units
    matMulUsingIterators      10  avgt   20        2.35 ±     0.08  us/op
    matMulUsingRanges         10  avgt   20        2.51 ±     0.06  us/op
    matMulUsingWhileLoop      10  avgt   20        1.04 ±     0.03  us/op
    matMulUsingIterators     100  avgt   20     1297.23 ±    30.70  us/op
    matMulUsingRanges        100  avgt   20     1632.09 ±    49.61  us/op
    matMulUsingWhileLoop     100  avgt   20     1064.69 ±    25.42  us/op
    matMulUsingRanges       1000  avgt   20  1635161.15 ± 39404.86  us/op
    matMulUsingIterators    1000  avgt   20  1482990.65 ± 42431.02  us/op
    matMulUsingWhileLoop    1000  avgt   20  1438909.85 ± 20257.01  us/op

**2.12.8**

    Benchmark             (size)  Mode  Cnt       Score      Error  Units
    matMulUsingIterators      10  avgt   20        2.02 ±     0.06  us/op
    matMulUsingRanges         10  avgt   20        2.45 ±     0.06  us/op
    matMulUsingWhileLoop      10  avgt   20        0.90 ±     0.02  us/op
    matMulUsingIterators     100  avgt   20     1275.96 ±    29.09  us/op
    matMulUsingRanges        100  avgt   20     1581.64 ±    50.82  us/op
    matMulUsingWhileLoop     100  avgt   20     1081.20 ±    21.98  us/op
    matMulUsingIterators    1000  avgt   20  1465832.44 ± 29526.00  us/op
    matMulUsingRanges       1000  avgt   20  1631038.32 ± 45846.02  us/op
    matMulUsingWhileLoop    1000  avgt   20  1419277.53 ± 15006.24  us/op

**2.13.0**

    Benchmark             (size)  Mode  Cnt       Score      Error  Units
    matMulUsingIterators      10  avgt   20        6.64 ±     0.23  us/op
    matMulUsingRanges         10  avgt   20        2.98 ±     0.08  us/op
    matMulUsingWhileLoop      10  avgt   20        0.92 ±     0.02  us/op
    matMulUsingIterators     100  avgt   20     2679.84 ±    50.97  us/op
    matMulUsingRanges        100  avgt   20     2045.60 ±    46.93  us/op
    matMulUsingWhileLoop     100  avgt   20     1088.56 ±    29.83  us/op
    matMulUsingIterators    1000  avgt   20  2391493.44 ± 44324.00  us/op
    matMulUsingRanges       1000  avgt   20  2114802.81 ± 48825.73  us/op
    matMulUsingWhileLoop    1000  avgt   20  1435843.18 ± 20688.23  us/op

**Comment by Ichoran** [comment]
@SethTisue - It's not as crazily bad as in the bug report, but since it seems to have actually gotten _worse_ in 2.13 in the benchmark that @ashawley presented, and in any case it's still slow, I wouldn't make any noise.

In fact, it seems likely that there's been a ~50% performance regression in 2.13 :(

**Comment by lrytz** [comment]
> I copied the benchmark from https://github.com/scala/scala/pull/8069 out of the Scala project to a fresh sbt 0.13 project and ran it against 2.10.7, 2.11.12, 2.12.8 and 2.13.0.

@ashawley do you have that repository at hand? I'd like to reproduce your test.

I took your PR (https://github.com/scala/scala/pull/8069), rebased it on current 2.13.x, and ran `bench/jmh:run scala.ArrayBenchmark` in sbt. What I got looks pretty good (on my MacBook Pro, and in [summer heat](https://www.bbc.com/news/world-europe-48756480), jdk 1.8.0_181):

```
[info] ArrayBenchmark.matMulUsingWhileLoopBench          10  avgt   20        0.603 ±      0.022  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench          10  avgt   20        0.851 ±      0.041  us/op
[info] ArrayBenchmark.matMulUsingRangesBench             10  avgt   20        0.946 ±      0.019  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench         100  avgt   20      750.031 ±      7.678  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench         100  avgt   20      861.454 ±     26.186  us/op
[info] ArrayBenchmark.matMulUsingRangesBench            100  avgt   20     1172.940 ±     43.039  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench        1000  avgt   20  1025865.092 ±   9769.750  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench        1000  avgt   20  1141386.009 ±  44863.893  us/op
[info] ArrayBenchmark.matMulUsingRangesBench           1000  avgt   20  1202351.806 ± 112234.083  us/op
```

Note that the `bench` project in the scala/scala repo enables the inliner/optimizer (https://github.com/scala/scala/blob/v2.13.0/build.sbt#L634).

**Comment by ashawley** [comment]
Here's a repo that can run the benchmark across Scala versions: https://github.com/ashawley/bug-1338

**Comment by lrytz** [comment]
Thanks, @ashawley!

I ran the benchmark on 2.12.8 and 2.13.0, on AdoptOpenJDK 1.8.212-04, on my MacBook Pro. For me the performance is very similar, maybe with a slight advantage for 2.13

```
2.12.8

[info] ArrayBenchmark.matMulUsingWhileLoopBench          10  avgt   20        0.608 ±      0.059  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench          10  avgt   20        4.642 ±      0.090  us/op
[info] ArrayBenchmark.matMulUsingRangesBench             10  avgt   20        1.815 ±      0.203  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench         100  avgt   20      789.694 ±     35.496  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench         100  avgt   20     1665.028 ±    100.906  us/op
[info] ArrayBenchmark.matMulUsingRangesBench            100  avgt   20     1218.045 ±    104.188  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench        1000  avgt   20  1178862.700 ± 153543.215  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench        1000  avgt   20  1482162.761 ± 198875.330  us/op
[info] ArrayBenchmark.matMulUsingRangesBench           1000  avgt   20  1464256.812 ± 236343.203  us/op
```

```
2.13.0

[info] ArrayBenchmark.matMulUsingWhileLoopBench          10  avgt   20        0.555 ±      0.003  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench          10  avgt   20        4.095 ±      0.460  us/op
[info] ArrayBenchmark.matMulUsingRangesBench             10  avgt   20        1.656 ±      0.027  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench         100  avgt   20      774.364 ±     41.958  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench         100  avgt   20     1563.868 ±     36.727  us/op
[info] ArrayBenchmark.matMulUsingRangesBench            100  avgt   20     1297.571 ±    253.275  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench        1000  avgt   20  1090820.285 ±  27666.503  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench        1000  avgt   20  1552164.276 ± 220824.486  us/op
[info] ArrayBenchmark.matMulUsingRangesBench           1000  avgt   20  1168316.835 ±  21196.048  us/op
```


I also ran it on 2.13 with the optimizer enabled (`> set scalacOptions ++= Seq("-feature", "-opt:l:inline", "-opt-inline-from:**")`, which then the Iterator and RangeForeach versions perform the same as the while loop

```
2.13.0, optimized

[info] ArrayBenchmark.matMulUsingWhileLoopBench          10  avgt   20        0.579 ±     0.047  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench          10  avgt   20        0.770 ±     0.053  us/op
[info] ArrayBenchmark.matMulUsingRangesBench             10  avgt   20        0.743 ±     0.016  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench         100  avgt   20      777.171 ±    33.312  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench         100  avgt   20      900.683 ±   122.898  us/op
[info] ArrayBenchmark.matMulUsingRangesBench            100  avgt   20     1018.408 ±    39.549  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench        1000  avgt   20  1108987.279 ± 53725.845  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench        1000  avgt   20  1053506.326 ± 36964.233  us/op
[info] ArrayBenchmark.matMulUsingRangesBench           1000  avgt   20  1075920.539 ± 25893.733  us/op
```

Maybe you can give it another try? Or someone else?

Out of curiosity, I ran the 2.13 version, without the scala optimzier, on Graal EE
```
[info] ArrayBenchmark.matMulUsingWhileLoopBench          10  avgt   20        0.580 ±      0.019  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench          10  avgt   20        0.864 ±      0.014  us/op
[info] ArrayBenchmark.matMulUsingRangesBench             10  avgt   20        0.864 ±      0.022  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench         100  avgt   20      882.833 ±     53.340  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench         100  avgt   20     1004.923 ±     63.560  us/op
[info] ArrayBenchmark.matMulUsingRangesBench            100  avgt   20     1061.473 ±    136.659  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench        1000  avgt   20  1191383.633 ± 141781.733  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench        1000  avgt   20  1135731.997 ± 101049.751  us/op
[info] ArrayBenchmark.matMulUsingRangesBench           1000  avgt   20  1228080.904 ± 167866.786  us/op
```

So Graal achieves almost the same as the Scala optimizer. This brings the discussion to the VM. The original bug report is > 10 years old, I guess it measured Scala 2.7 on Java 1.5 or so. Things have improved in the meantime, the same 2.7 code might run a lot faster on a current JVM.

It's also unclear if the measurements in the orignal bug report were done after proper warm-up.

One problem with micro-benchmarks like these is that they don't test for what's called "profile pollution". In a real application, `Range.foreach` is potentially invoked a large number of times, which makes the lambda invocation in its body megamorphic. It looks like the benchmark here has enough `Range.foreach` calls. Adding a few more `Range.foreach` calls with different lambdas to the benchmark doesn't seem to affect the relative performance between the while and the foreach version, so that's a good sign.

So I'd say we can close this bug.

**Comment by ashawley** [comment]
Thanks for confirming the benchmark and sharing your insights, @lrytz.  I think this can be closed.  I also predict 2.13 is fine.  The inconsistent results it gave can be chalked up to benchmark variance, IMO.

**Comment by lrytz** [comment]
👍  Thanks for pulling on that thread, @ashawley!

**Comment by som-snytt** [comment]
I followed my bad instincts without knowing what I was doing and updated sbt and plugin:
```
sbt:for-benchmark> ++ 2.12.8 -v
[info] Setting Scala version to 2.12.8 on 0 projects.
[info] Switching Scala version on:
[info] Excluding projects:
[info]   * for-benchmark (2.11.12)
[info] Reapplying settings...
[info] Set current project to for-benchmark (in build file:/home/amarki/projects/for-benchmark/)
```

```
# 2.12.8
[info] # Run complete. Total time: 00:09:41
[info] 
[info] Benchmark                                 (loopSize)  Mode  Cnt        Score       Error  Units
[info] ArrayBenchmark.matMulUsingIteratorsBench          10  avgt   20        9.421 ±     0.621  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench         100  avgt   20     4144.742 ±    35.525  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench        1000  avgt   20  3690096.967 ± 49486.245  us/op
[info] ArrayBenchmark.matMulUsingRangesBench             10  avgt   20        3.682 ±     0.029  us/op
[info] ArrayBenchmark.matMulUsingRangesBench            100  avgt   20     3617.982 ±    53.211  us/op
[info] ArrayBenchmark.matMulUsingRangesBench           1000  avgt   20  3632637.830 ± 38451.647  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench          10  avgt   20        1.110 ±     0.050  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench         100  avgt   20     1204.156 ±    29.714  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench        1000  avgt   20  1445848.245 ± 25610.794  us/op
[success] Total time: 601 s, completed Jul 1, 2019, 11:02:00 AM

# 2.13.0
[info] # Run complete. Total time: 00:10:10
[info] 
[info] Benchmark                                 (loopSize)  Mode  Cnt        Score        Error  Units
[info] ArrayBenchmark.matMulUsingIteratorsBench          10  avgt   20        7.154 ±      0.204  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench         100  avgt   20     4301.989 ±    358.245  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench        1000  avgt   20  4097367.463 ± 270264.914  us/op
[info] ArrayBenchmark.matMulUsingRangesBench             10  avgt   20        4.455 ±      0.035  us/op
[info] ArrayBenchmark.matMulUsingRangesBench            100  avgt   20     4225.039 ±    248.789  us/op
[info] ArrayBenchmark.matMulUsingRangesBench           1000  avgt   20  4081206.540 ± 306168.149  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench          10  avgt   20        1.180 ±      0.105  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench         100  avgt   20     1184.783 ±     22.531  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench        1000  avgt   20  1562064.978 ± 114682.989  us/op
[success] Total time: 623 s, completed Jul 1, 2019, 11:36:28 AM

# 2.13.0 optimized
[info] # Run complete. Total time: 00:07:08
[info] 
[info] Benchmark                                 (loopSize)  Mode  Cnt        Score        Error  Units
[info] ArrayBenchmark.matMulUsingIteratorsBench          10  avgt   20        1.712 ±      0.113  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench         100  avgt   20     1499.381 ±     82.163  us/op
[info] ArrayBenchmark.matMulUsingIteratorsBench        1000  avgt   20  1461650.884 ±  96471.162  us/op
[info] ArrayBenchmark.matMulUsingRangesBench             10  avgt   20        1.562 ±      0.401  us/op
[info] ArrayBenchmark.matMulUsingRangesBench            100  avgt   20     1713.173 ±     15.729  us/op
[info] ArrayBenchmark.matMulUsingRangesBench           1000  avgt   20  1382271.184 ± 112008.808  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench          10  avgt   20        1.290 ±      0.082  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench         100  avgt   20     1406.527 ±     42.015  us/op
[info] ArrayBenchmark.matMulUsingWhileLoopBench        1000  avgt   20  1581735.904 ± 124449.687  us/op
[success] Total time: 438 s, completed Jul 1, 2019, 11:47:10 AM

```
