### ISSUE TITLE
Multiple assignment does not do correct typing

### ISSUE THREAD

**Issue by scabug** [scala/bug#140]
The following code should not compile:
```scala
val (is: Option[String], not: Option[String]) = ("a", "b") match {
  case ("b", _) => (Some("Dog"), None)
  case _ => (Some((1,2)), Some("Dog"))
}

is.foreach(v => println(v.length))
```
Note that 'is' is typed as an Option[String], but it is assigned either Option[String] or Option[(Int, Int)]

This leads to a runtime error.

**Comment by dwijnand** [comment]
Given @som-snytt's has shown the code block no longer compiles (still the behaviour today in 2.12.2), can't this closed now?

**Comment by SethTisue** [comment]
the soundness hole hasn't been closed:

```
scala> val (is: Option[String], not: Option[String]) = ("a", "b") match {
     |   case ("b", _) => (Option("Dog"), None)
     |   case _ => (Option((1,2)), Some("Dog"))
     | }
<console>:13: warning: non-variable type argument String in type pattern Option[String] is unchecked since it is eliminated by erasure
       val (is: Option[String], not: Option[String]) = ("a", "b") match {
                ^
is: Option[String] = Some((1,2))
```

a little more simply:

```
scala> val (is: Option[String], not) = 0 match { case 1 => (Some("foo"), 0); case _ => (Option(1), 0) }
<console>:13: warning: non-variable type argument String in type pattern Option[String] is unchecked since it is eliminated by erasure
       val (is: Option[String], not) = 0 match { case 1 => (Some("foo"), 0); case _ => (Option(1), 0) }
                ^
is: Option[String] = Some(1)
```

**Comment by SethTisue** [comment]
to be sure, we have to alter Som's code a bit:

```
scala> val (is: Option[String], not) = 0 match { case 1 => (Some("foo"), 0); case _ => (Option(1), 0) }
<console>:13: warning: non-variable type argument String in type pattern Option[String] is unchecked since it is eliminated by erasure
       val (is: Option[String], not) = 0 match { case 1 => (Some("foo"), 0); case _ => (Option(1), 0) }
                ^
is: Option[String] = Some(1)
```

but this is covered by the erasure warning; the overall pattern match is correctly typed as `(Option[Any], Int)`

**Comment by dwijnand** [comment]
```scala
is: Option[String] = Some(1)
```

😨 here be dragons

**Comment by SethTisue** [comment]
yeah that type erasure warning should probably have skulls and knives in it

**Comment by som-snytt** [comment]
Consider adding a compiler option `scalac -XYZZY` to unlock special features.

**Comment by SethTisue** [comment]
> should probably have skulls and knives in it

more seriously: perhaps we ought to break with tradition here and make the absence of `@unchecked` an error, not just a warning

**Comment by dwijnand** [comment]
> perhaps we ought to break with tradition here and make the absence of `@unchecked` an error, not just a warning

https://dotty.epfl.ch/docs/reference/changed-features/pattern-bindings.html#bindings-in-pattern-definitions 🎉 :shipit:
