### ISSUE TITLE
Scala should support Unicode supplementary characters

### ISSUE THREAD

**Issue by scabug** [scala/bug#1406]
Currently the parser only understands identifiers drawn from the basic multilingual plane.  

See https://www.oracle.com/technical-resources/articles/javase/supplementary.html for more information on how we would support this on the Java target.

**Comment by magnolia-k** [comment]
The Scala compiler uses Character.isUnicodeIdentifierPart to determine which Unicode characters can be used as identifiers. There are two versions of this function, one that takes char type as an argument and one that takes int type as an argument.

The current Scala compiler uses a function that takes char type as an argument, so it is unable to correctly determine Unicode supplementary characters.

Character.isHighSurrogate needs to be called character by character to check if the character is a high surrogate or not.
