### ISSUE TITLE
Java protected members overriding from Scala

### ISSUE THREAD

**Issue by scabug** [scala/bug#1469]
Java class
```scala
 package aaa;

 public abstract class MyJavaClass {
     abstract protected int foo();
 }
```

Scala class
```scala
 package ccc

 import aaa.MyJavaClass

 class MyScalaClass extends MyJavaClass {
     protected def foo: Int = 42
 }
```

 We cannot compile them together cause and get a compilation error
 "Error:Error:line (6)error: error overriding method foo in class MyJavaClass
 of type ()scala.this.Int;
 method foo has weaker access privileges; it should be at least
 protected[aaa]
 protected def foo: Int = 42"

But if MyJavaClass is already compiled and added to appropriate classpath we can compile our MyScalaClass without any problems.

**Comment by magnolia-k** [comment]
In recent Scala (at least 2.13, 2.12, 2.11), this code can be compiled.

**Comment by NthPortal** [comment]
thanks for verifying!
