### ISSUE TITLE
Compiler infers correct type but refuses to use it

### ISSUE THREAD

**Issue by scabug** [scala/bug#1479]
```scala
class A {
  class C
  class Inf[X<:C](x: X) 
  def f[X<:C](x: X) {}
}

object Test extends A {
  val c: C = new C
  f(c)
  new Inf(c)
}
```

gives

```scala
 inferred type arguments [Test.C] do not conform to class Inf's type parameter bounds [X <: A.this.C]
  new Inf(c)
  ^
```

When given the inferred type explicitly

```scala
new Inf[C](c)
```

it compiles. Note that the function call compiles either way.

**Comment by som-snytt** [comment]
It seems they made progress.

I didn't try to locate the progression in 2.13.0-M5. Maybe this test is redundant. Maybe this ticket could have created a pending test that would have been verified not-fixed by Jenkins, who would have noted the eventual change in status.
