### ISSUE TITLE
Change Reader.source to return Option[CharSequence]

### ISSUE THREAD

**Issue by scabug** [scala/bug#1486]
Currently, the class scala.util.parsing.input.Reader 
defines the method
```scala
def source  : java.lang.CharSequence
```
*If this is a reader over character sequences, the underlying char sequence If not, throws a !NoSuchMethodError exception.*

This feels very un-Scala-like. I suggest changing this to return Option[!CharSequence], or deprecating this
method and adding a replacement:

```scala
def charSequence : Option[java.lang.CharSequence]
```

*If this is a reader over character sequences, return Some[charSequence], else return None*

(Side note: there is a missing period in the doc string.)

**Comment by SethTisue** [comment]
if someone feels this is still an issue, open a new ticket at https://github.com/scala/scala-parser-combinators
