### ISSUE TITLE
Casts inserted when pattern matching for equality on singletons are unsound

### ISSUE THREAD

**Issue by scabug** [scala/bug#1503]
I've added a test to pending/run/castsingleton.scala:

```scala
object Test extends Application {
  case class L();
  object N extends L();

  def empty(xs : L) : Unit = xs match {
    case x@N => println(x); println(x);
  }

  empty(L())
} 
```

The problem is that the compiler inserts a cast of xs to N.type, which is unsound: The pattern match will succeed for any L, because N == L().

**Comment by SethTisue** [comment]
new PR https://github.com/scala/scala/pull/6502
