### ISSUE TITLE
Traits + clone = boom!

### ISSUE THREAD

**Issue by scabug** [scala/bug#151]
```scala
package test
object Main {
  trait Foo extends Cloneable {
    def copy : Foo = clone.asInstanceOf[Foo]
  }
  def main(args : Array[String]) : Unit = {
    Console.println("hello")
    val foo = new Foo {}
    Console.println(foo.copy)
  }
}
```

Run it and weep. All protected methods from a class that a trait extends need to be bridged, especially if the class is coming from Java.

**Comment by SethTisue** [comment]
please open a new ticket, reopening old tickets that regressed messes with milestones and such
