### ISSUE TITLE
Indicate where block begins when emitting block errors

### ISSUE THREAD

**Issue by scabug** [scala/bug#1526]
In sufficiently large source files, it is not uncommon to have a missing close } on a def. However, the compiler diagnostics for this situation are not helpful... you get two warnings, at the end of the source:
```scala
'}' expected but eof found.
block must end in result expression, not in definition	
```
Neither tells you where the block begins, which is the
crucial bit of information needed to quickly fix this.
(This problem occurs frequently because the Scala plugin
for Eclipse adds a closing } after you type "{" and " "
and sometimes you don't notice it until it is much too late.)

To fix such errors, I'm forced into trial and error 
of adding } until I can find the offending def.

Please list the line number location of the beginning
of the block.

**Comment by som-snytt** [comment]
Smart braces arrived in 2009, but regressed again by 2019:
```
snips $ scalac missing.scala
missing.scala:7: error: Missing closing brace `}` assumed here
      }
      ^
one error found
snips $ dotc missing.scala
-- Warning: missing.scala:11:0 -------------------------------------------------
11 |
   |^
   |Line is indented too far to the left, or a `}' is missing
-- [E040] Syntax Error: missing.scala:11:0 -------------------------------------
11 |
   |^
   |'}' expected, but eof found
one warning found
one error found
```
That is a 10-line file with nested functions and innermost missing right brace.
