### ISSUE TITLE
String.toInt, .toDouble should allow a default parameter

### ISSUE THREAD

**Issue by scabug** [scala/bug#16]
Aladdin: **[http://scala-webapps.epfl.ch/bugtracking/bugs/displayItem.do?id=1299 bug 1299], [http://scala-webapps.epfl.ch/bugtracking/contribs/display.do?id=773 contrib 773]**

== Code ==

```scala
object Foo {
   // this is overly verbose
   def getInt(s : String) = try {
     s.toInt
   } catch {
     case e : NumberFormatException => 0
   }

   // I'd much rather write this
   def getInt2(s : String) = s.toInt(0)
}
```

== What happened ==

n/a

== What expected ==

To be able to optionally provide a default value for string-to-primitive conversion methods, much like Option.get.

**Comment by SethTisue** [comment]
there is an active discussion on this at https://github.com/scala/collection-strawman/pull/431

**Comment by SethTisue** [comment]
has PR now, reviewers wanted: https://github.com/scala/scala/pull/6538

**Comment by SethTisue** [comment]
for fixing the last open two-digit Scala issue, @martijnhoekstra officially gets to wear a big, shiny golden crown whenever he wants.

https://github.com/scala/bug/issues?q=is%3Aopen+is%3Aissue+sort%3Acreated-asc shows 16 remaining open three-digit issues, for anyone interested in earning the right to wear an only slightly smaller and slightly less jewel-encrusted crown
