### ISSUE TITLE
getClass fails for doubly nested inner-class

### ISSUE THREAD

**Issue by scabug** [scala/bug#2034]
The following code fails with java.lang.ClassNotFoundException: TestScalaBug$$foo

workaround is to add a class foo 

may be related to bug 1572

```scala
object TestScalaBug {

  def main(args: Array[String]) {
    val fooz = new foo.foo2
    println(fooz)
  }

  object foo {
    class foo2 {
      override def toString = getClass.getSimpleName
    }
  }
    
}
```

**Comment by dwijnand** [comment]
> @retronym said:
> JDK9 has fixed this: https://bugs.openjdk.java.net/browse/JDK-8057919

It would appear that's not true:

> After https://bugs.openjdk.java.net/browse/JDK-8057919, it also "fails" in OpenJDK9.

(from: https://github.com/scala/scala-dev/issues/415#issuecomment-322935565)

**Comment by dwijnand** [comment]
Nvm, I misunderstood what was being said.

**Comment by xuwei-k** [comment]
```
$ java -version
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

$ scala
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 9.0.4).
Type in expressions for evaluation. Or try :help.

scala> object A { object B { class C } }
defined object A

scala> classOf[A.B.C].getSimpleName
res0: String = C
```

```
$ java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

$ scala
Welcome to Scala 2.12.4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_162).
Type in expressions for evaluation. Or try :help.

scala> object A { object B { class C } }
defined object A

scala> classOf[A.B.C].getSimpleName
java.lang.InternalError: Malformed class name
  at java.lang.Class.getSimpleName(Class.java:1330)
  ... 28 elided
```

**Comment by jroper** [comment]
Just to point out that the "this isn't critical because it's just pretty printing" argument is false, the implementation of `Class.isAnonymousClass` invokes `Class.getSimpleName`:

```java
    public boolean isAnonymousClass() {
        return "".equals(getSimpleName());
    }
```

I guess it's fixed in JDK9, but I don't see a rush of people upgrading.

**Comment by som-snytt** [comment]
Closing this because there is Android and there is "oh is jdk 13 available already? I mean 14?".

Perhaps closing will dissuade "pushed a commit that referenced this issue."

This issue is no longer "open to Scala" in the sense of actionable under the aegis of this project or "the Scala team", aka "team Scala", aka "team Adriaan", aka "team Flash".
