### ISSUE TITLE
scalac doesn't accept Windows notepad or wordpad files saved as UTF-8

### ISSUE THREAD

**Issue by scabug** [scala/bug#2109]
scalac doesn't accept Windows notepad or wordpad files saved as
"UTF-8" or "Unicode", even when the -encoding UTF-8 option is
used.  When the same file is saved with jEdit as UTF-8, there 
is no problem.  But notepad and wordpad are probably installed on
more computers than any other editor in the world, and this
could be a nuisance for people just trying out Scala.  This
is probably one of the dreaded BOM issues...

**Comment by SethTisue** [comment]
closing for staleness. could be reopened if someone takes an interest
