### ISSUE TITLE
bounds transitivity

### ISSUE THREAD

**Issue by scabug** [scala/bug#2173]
This (somewhat convoluted) code fails to compile

class A[+U>:Null] {
    type R[+X>:Null] = X
    type O[+X] = A[R[X]]
}

with the following error:

type arguments [A.this.R[X]] do not conform to class A's type parameter bounds [+U >: Null]

However, because type R[+X>:Null] is identical to X, it should carry X bounds and R[X] lower bound should be known to be X's lower bound, i.e. Null.

The same problem occurs with upper bounds.

**Comment by SethTisue** [comment]
doesn't compile in Dotty either ("Type argument A.this.R[X] does not conform to lower bound Null")

it's possible there's a valid bug or enhancement request here, but it would need analysis to determine what's going on. what exactly the bug or enhancement even is. we can reopen if someone provides that
