### ISSUE TITLE
Table Cell renderer bug using Nimbus and Scala

### ISSUE THREAD

**Issue by scabug** [scala/bug#2292]
Basically I have a cell renderer which extends Panel (as opposed to DefaultTableCellRenderer) and it is behaving oddly: it is not rendering the alternate row colors properly whereas an equivalent Java program behaves just fine. Please find attached the "equivalent" Scala and Java programs

**Comment by SethTisue** [comment]
if this is still a concern, open a new ticket at https://github.com/scala/scala-swing/issues
