### ISSUE TITLE
add lazy parameters

### ISSUE THREAD

**Issue by scabug** [scala/bug#240]
For now, we only have call-by-name parameters. We should allow the `lazy` modifier on parameters, for instance:

```scala
def f[a](lazy t: a) = {
 ..
}
```

The meaning should be equivalent to:

```scala
def f[a](t': => a) = {
  lazy val t: a = t'
  ..
}
```

**Comment by SethTisue** [comment]
I believe this is now out of scope for Scala 2, but there's a Scala 3 ticket: https://github.com/lampepfl/dotty-feature-requests/issues/174
