### ISSUE TITLE
Allegedly faster HashSet implementation

### ISSUE THREAD

**Issue by scabug** [scala/bug#2512]
scala.tools.nsc.util.hashSet.growTable() should set
```scala
used = 0
```
when allocating the new Array.

With the current implementation, a hashSet with 16 entries reports size 48 and has capacity 256.

With the proposed fix, it would report size 16 and have capacity 128.

Here's an example of the value of the memory saving: when attempting to compile an existing program with truck (-Xmx1312M on Win XP) I experience outOfMemoryError: Java heap space
```scala
        at scala.tools.nsc.util.HashSet.growTable(HashSet.scala:59)
        at scala.tools.nsc.util.HashSet.addEntry(HashSet.scala:42)
        at scala.tools.nsc.symtab.Types$$class.unique(Types.scala:2415)
        at scala.tools.nsc.symtab.Types$$class.mkThisType(Types.scala:2075)
```

**Comment by som-snytt** [comment]
@SethTisue the initial bug was fixed, hashes improved, no definitive reproducible demonstration of an issue with 2.13 collections. No one is crying "my small AnyRefMap is slow". Suggest closing with your friendly, Happy to re-open if someone discovers an issue.

Alternatively, transfer the issue to collections-next for dotty to inherit after the thaw.
