### ISSUE TITLE
Suggestion for improving MultiMap

### ISSUE THREAD

**Issue by scabug** [scala/bug#2608]
Consider allowing types more general than `Set` in a `MultiMap`.

The current definition is: `trait MultiMap[A, B] extends Map[A, Set[B]]`

An example usage: if a `ListBuffer` could be used in place of a `Set`, then the `MultiMap` could be used to associate  ordered, repeating values to the multimap key.

This request was raised and discussed on the scala-user mailing list:

  Subject: `MultiMap` with a `List` instead of a `Set`?

  http://old.nabble.com/MultiMap-with-a-List-instead-of-a-Set--to26199345.html

User suggestions include:
   * "I completely agree - I regularly use `MultiMap`-like functionality with `List` instead of `Set`; a generalization of it would be really useful"
   * "Could it also be generalized for any `Seq[(A, Seq[B])]`, not only a`Map` [...] it would be nice to use with a `PriorityQueue` for timeline based data such as an animation or MIDI sequence etc. -- this way events that occur at the same time can be added individually but dequeued together."

**Comment by magnolia-k** [comment]
`MultiMap` has been deprecated since Scala 2.13.0, and `MultiDict` from `scala-collection-contrib` is recommended as an alternative.

Isn't it appropriate to close this issue?
