### ISSUE TITLE
fsc only supports limited settings options?

### ISSUE THREAD

**Issue by scabug** [scala/bug#2638]
Per FastScalac.scala, only following options will be transfered to CompileClient.main0(args):

s.outdir, s.classpath, s.bootclasspath, s.extdirs, s.encoding
s.debuginfo, s.target
s.debug, s.deprecation, s.nopredefs, s.verbose, reset, shutdown
s.log

Is this a feature? or, how if I'd like to add "-make:transitive, -dependencyfile <file>" etc?

**Comment by SethTisue** [comment]
#7633
