### ISSUE TITLE
try/catch catches NonLocalReturnException

### ISSUE THREAD

**Issue by scabug** [scala/bug#2807]
Currently if I write some code like this:
```scala
for(i <- 0 to 20){
   try{
      if(isGood(i)) return i
   }catch{
      case e => {
         System.out.println("Exception occurred. Continuing")
      }
   }
}
```
Then the catch statement ends up catching the value returned by the return statement. 

This is deeply confusing...

Would there be a possible workaround for this? E.g. could we declare that, by default, a pattern for an exception does not match NonLocalReturnException?

It would at least be nice to have some prominent documentation warning users about this problem.

**Comment by SethTisue** [comment]
something in this area could be revived on https://contributors.scala-lang.org
