### ISSUE TITLE
Helpful options for running Scala scripts on read-only filesystems

### ISSUE THREAD

**Issue by scabug** [scala/bug#2943]
We are using Scala in an environment in which production code runs on a read-only filesystem.  The current Scala interpreter, when running a script with the -savecompiled option, writes the resulting jar file to the same directory as the script file.  If the directory is read-only, then the interpreter cannot save the jar and fails.

It would be helpful to have an option that would instruct the interpreter to save the compiled jar to a different directory.

It would also be helpful for the interpeter to generate the name for the compiled jar by hashing the full path of the script, so that if the -savecompiled directory is set to /tmp or c:\temp, jar files generated for scripts of the same name in different directories will not conflict.

If the hashing feature was implemented, then the -savecompiled can default to the value of the java.io.tmpdir system property.

**Comment by SethTisue** [comment]
`-savecompiled` is called `-save` these days. I'd completely forgotten it existed

**Comment by som-snytt** [comment]
The fix is to respect `-d mytarget.jar`. Not sure yet whether to prefer `tmpdir` or `~/.scalac` if `-d` is not specified.
