### ISSUE TITLE
2.8 collections: toString on ArraySeq of a primitive type reveals underlying nulls

### ISSUE THREAD

**Issue by scabug** [scala/bug#2996]
this is good:
```scala
Welcome to Scala version 2.8.0.Beta1-prerelease (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_17).
scala> new collection.mutable.GenericArray[Int](1).head
res16: Int = 0
```

but this is not so good:
```scala
scala> new collection.mutable.GenericArray[Int](1).toString
res17: String = GenericArray(null)
```

The "null" seems like an implementation detail that shouldn't leak out like this.

(Whether the Array[AnyRef] used internally by GenericArray ought to be initialized to contain a bunch of boxed integers instead of a bunch of nulls, or whether it ought to be toString's job to hide the difference, I don't know.)

**Comment by NthPortal** [comment]
This is both stale (in that the `s.c.m.ArraySeq` mentioned here is wholly unrelated to the one in 2.13) and fixed.
