### ISSUE TITLE
Appending a ListBuffer to itself causes endless loop

### ISSUE THREAD

**Issue by scabug** [scala/bug#3088]
```scala
scala> val b = new ListBuffer[Int]
scala> b += 1
scala> b ++= b
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2882)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:100)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:390)
```

If LB doesn't support self-append, then it should throw IllegalArgumentException if passed an instance of itself.  But maybe a better fix would be to look at the number of elements in the LB at the start of the append, and just append that many.

The easy "fix" is to add something to the Javadoc or assume that users will be able to diagnose the OutOfMemoryError that results, but the self-append may not be so obvious as the one in this example and could lead to a OutOfMemoryError in a production system, potentially taking the whole system down instead of just one thread.  Imagine if this happened on a web server.  If ListBuffer threw IllegalArgumentException, then just the one request would fail.  If it instead allocates all the available memory, then it will grind the CPU for a while, slowing down everything else, and potentially cause other requests that need memory to fail too.

I think that the same issue probably affects the prepend operations.

**Comment by NthPortal** [comment]
anyone know where the fix for this is? from what I can tell, it's baked into the compiler (which doesn't seem right to me)

**Comment by NthPortal** [comment]
update: it actually re-emerged at some point at or before 2.13. it just so happens that the test only checks when the `ListBuffer` has a single element, which *happens* to work because the iterator exhausts itself before returning. with more elements, it hangs
