### ISSUE TITLE
patch that adds warning for implicit methods with by-name parameters

### ISSUE THREAD

**Issue by scabug** [scala/bug#3237]
Attached is a patch that adds an option `-Ywarn-by-name`.  This option enables a warning when an implicit method has a call-by-name parameter.

It is a common mistake to assume an entire block will be passed to the implicit.  It is explicitly mentioned in the specification that implicits with call-by-name parameters are allowed, otherwise I would have suggested disallowing this entirely.

I see that the fix for the similar ticket #2688 was implemented in the parser, but it was easier for me to do it in !RefChecks.

It is only lightly tested.  If this patch is of interest, I'll add tests.

**Comment by som-snytt** [comment]
Added a lint just before the statute of limitations ran out.

**Comment by jeffrey-aguilera** [comment]
I got 275 such warnings on my source. Not sure why this is deemed a warning; but I can just mute it.
