### ISSUE TITLE
Clarify usage of Google copyright in xml sourcecode

### ISSUE THREAD

**Issue by scabug** [scala/bug#3405]
The following sourcecode contains Google copyright statements:

scala-2.8.0.RC1-sources\src\library\scala\xml\Elem.scala
Line 18:  * Copyright 2008 Google Inc. All Rights Reserved.
Line 41:  * Copyright 2008 Google Inc. All Rights Reserved.

scala-2.8.0.RC1-sources\src\library\scala\xml\MetaData.scala
Line 18:  * Copyright 2008 Google Inc. All Rights Reserved.
Line 72:  * Copyright 2008 Google Inc. All Rights Reserved.

They are from Burak Emir after he moved to Google. I'm not sure if this is just something that's been added automatically by his editor, but it would be nice to get a clarification since it's not mentioned in the Scala license.

**Comment by SethTisue** [comment]
fyi @ashawley
