### ISSUE TITLE
highlight non-exceptions & non-annotations to avoid noise when folks are looking at APIs

### ISSUE THREAD

**Issue by scabug** [scala/bug#3694]
one nice thing about javadoc when looking at a package is it manages to group exceptions and annotations together away from the main API.

right now scaladoc lumps all classes together; so if you've an API with a few core set of traits/classes its very easy to have them hidden by noise of lots of annotations or exceptions

I'd like a way to re-introduce the javadoc groupings, showing annotations and exceptions after the other main APIs.

e.g. the list of types in a package look more like this...

o c Foo
- c Bar

Annotations

c Green
c Blue

Exceptions

c BlahException
c WhatnotException

Then the real meat of an API (the core classes) are not mixed up with exceptions & annotations (of which there are often quite a lot - many of which are simple & not that interesting when browsing).

Also if you know you are choosing which annotation you should use, seeing them all grouped together in a package helps.

I'd argue that developers tend to browse annotations more regularly than exceptions. If you get an exception you are more likely to just start typing the name in the search box to find it quickly.

Extra credit if we can easily hide/show exceptions and/or annotations. 

I wonder once we start grouping classes by regular, annotation, exception - would folks ever want the 'flat' view we have now?

**Comment by SethTisue** [comment]
this is a nice suggestion. but (post JIRA -> GitHub migration), we're keeping scala/bug focused on bugs
