### ISSUE TITLE
Don't allow objects to be cloned

### ISSUE THREAD

**Issue by scabug** [scala/bug#3764]
When an "object" is placed into a package or another such object, it is assumed to be a singleton and the compiler apparently optimizes "this" references in closures within methods that object to refer to the singleton.

This assumption is incorrect when the object is clone()d, as demonstrated by this snippet:

```scala
object ObjectIdentityTest {
   def main(args: Array[String]) { new ObjectIdentityTest() }

   class Base extends Cloneable {
     override def clone() = super.clone()
     def foo = { println("  hashCode = "+this.hashCode()); true }
   }

   object A extends Base { def bar = List(1).filter(_ => foo) }

   val B = new Base { def bar = List(1).filter(_ => foo) }
}

class ObjectIdentityTest {
   import ObjectIdentityTest._

   object C extends Base { def bar = List(1).filter(_ => foo) }

   println("Original A:")
   A.foo
   A.bar

   val clonedA = A.clone().asInstanceOf[A.type]
   println("Cloned A:")
   clonedA.foo
   clonedA.bar

   println("Original B:")
   B.foo
   B.bar

   val clonedB = B.clone().asInstanceOf[B.type]
   println("Cloned B:")
   clonedB.foo
   clonedB.bar

   println("Original C:")
   C.foo
   C.bar

   val clonedC = C.clone().asInstanceOf[C.type]
   println("Cloned C:")
   clonedC.foo
   clonedC.bar
}
```

The output looks like this:

```scala
Original A:
   hashCode = 837043581
   hashCode = 837043581
Cloned A:
   hashCode = 1125883825
   hashCode = 837043581 <-- still the original A!
Original B:
   hashCode = 1251033058
   hashCode = 1251033058
Cloned B:
   hashCode = 183062162
   hashCode = 183062162
Original C:
   hashCode = 1894479961
   hashCode = 1894479961
Cloned C:
   hashCode = 1613816448
   hashCode = 1613816448
```

For B and C this is as expected but for object A, calling bar() on a
clone calls foo() on the original object.

The compiler can recognize this situation because the object in question extends java.lang.Cloneable. In this case, the object should not be assumed to be a singleton (with regards to the optimizations the compiler may perform).

**Comment by som-snytt** [comment]
Since the statute of limitations has run out, the linked PR just lints it.

Thus, the resolution of this ticket is as lrytz suggested: except it's just a lint.

Thankfully, there is no need to deprecate `scala.Cloneable`.
