### ISSUE TITLE
Provide better toString for case classes

### ISSUE THREAD

**Issue by scabug** [scala/bug#3967]
```scala
scala> case class Foo(i: Int, j: Int)
defined class Foo

scala> Foo(1,2)
res50: Foo = Foo(1,2)
```

It would have been more readable for Foo's toString to print something like:
```scala
Foo(i=1,j=2)
```

**Comment by SethTisue** [comment]
https://contributors.scala-lang.org/t/case-class-tostring-new-behavior-proposal-with-implementation/2056/44
