### ISSUE TITLE
Incorrect syntax highlighting for triple quoted strings

### ISSUE THREAD

**Issue by scabug** [scala/bug#3979]
I've attached screenshot with illustration of broken syntax highlighting.

I use Scala 2.8.0 and following scala-mode:

```scala
(defconst scala-mode-version "0.5.99.5")
(defconst scala-mode-svn-revision "$$Revision: 21917 $$") 
```

**Comment by SethTisue** [comment]
the emacs mode is no longer anywhere under scala/*, idk offhand where it lives these days
