### ISSUE TITLE
[patch] Vim: properly indent by two spaces

### ISSUE THREAD

**Issue by scabug** [scala/bug#4039]
The vim tool support only sets shiftwidth=2, but tabstop=2 is also required. Additionally, softtabstop=2 makes it easy to remove a level of indentation by pressing backspace one time, instead of two (for the two spaces).

Without this, it's unnecessarily hard to write code using the standard Scala 2 space indent.

**Comment by SethTisue** [comment]
vim support no longer lives under scala/*
