### ISSUE TITLE
scala scripts calling each other from sub-shells

### ISSUE THREAD

**Issue by scabug** [scala/bug#4099]
=== What steps will reproduce the problem (please be specific and use wikiformatting)? ===
I've got a pair of scala scripts one that calls the other like this
minimized example:

script: a
----
```scala
#!/bin/bash -v

(cd other; b)
exec scala -cp commons-email-1.2.jar "$$0" "$$@"
!#
import org.apache.commons.mail._;
```

script: other/b
----
```scala
#!/bin/bash -v

exec scala -cp commons-io-1.4.jar "$$0" "$$@"
!#
import org.apache.commons.io.FileUtils._;
```

This assumes that a is in some path like: /tmp and b is in /tmp/other and commons-email-1.2.jar and commons-io-1.4.jar are in those same paths respectively.

=== What is the expected behavior? ===

```scala
$$ a
#!/bin/bash -v
(cd other; b)
#!/bin/bash -v
exec scala -cp commons-io-1.4.jar "$$0" "$$@"
exec scala -cp commons-email-1.2.jar "$$0" "$$@"
$$
```

=== What do you see instead? ===

```scala
$$ a
#!/bin/bash -v
(cd other; b)
#!/bin/bash -v
exec scala -cp commons-io-1.4.jar "$$0" "$$@"
exec scala -cp commons-email-1.2.jar "$$0" "$$@"
/tmp/./a:7: error: value apache is not a member of package org
import org.apache.commons.mail._;
          ^
one error found
$$
```

=== Additional information ===

If I run with -verbose, it shows that the classpath is correct for 'b'
but not for 'a' when the exec is performed.  In both cases, scala
starts a new compile server instance (reason = "settings not equal").
When I change the exec line in 'a' by adding '-nocompdaemon' the error
goes away.

See below for discussion:
http://scala-programming-language.1934581.n4.nabble.com/scala-scripts-calling-each-other-is-this-a-bug-td3094846.html

=== What versions of the following are you using? ===
  - Scala: 2.8.1.final
  - Java: Java(TM) SE Runtime Environment (build 1.6.0_22-b04-307-10M3261)
  - Operating system:  MacOS 10.6

**Comment by SethTisue** [comment]
help wanted... consigning fsc to the dustbin of history

**Comment by som-snytt** [comment]
Closing in favor of future tickets about the REPL protocol and REPL server.

"fsc who?"
