### ISSUE TITLE
Views of sets do not behave like sets

### ISSUE THREAD

**Issue by scabug** [scala/bug#4116]
=== What steps will reproduce the problem (please be specific and use wikiformatting)? ===
```scala
scala> Set(1, 2, 3).view.map(_ => 1)
res7: scala.collection.IterableView[Int,Iterable[_]] = IterableViewM(...)

scala> res7.foreach(println _)
1
1
1
```

=== What is the expected behavior? ===

The result of the call to map should contain no duplicates, in this example one element.

=== What do you see instead? ===

The result contains duplicates and is the same length as the original set.

=== Additional information ===
http://thread.gmane.org/gmane.comp.lang.scala.user/34461

=== What versions of the following are you using? ===
  - Scala: 2.8.1
  - Java: Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_22
  - Operating system:  OSX 10.5

**Comment by SethTisue** [comment]
probably fixed in strawman. assigning to M4 milestone so we can check it once strawman lands

**Comment by lrytz** [comment]
This is unchanged in strawman, `Set.view` returns a plain `View`. This is expected / by design, so closing as won't-fix.
