### ISSUE TITLE
Views of maps don't behave like maps

### ISSUE THREAD

**Issue by scabug** [scala/bug#4117]
=== What steps will reproduce the problem (please be specific and use wikiformatting)? ===
```scala
scala> val m = Map("ab" -> "ab", "ac" -> "ac", "ba" -> "ba")
m: scala.collection.immutable.Map[java.lang.String,java.lang.String] = Map((ab,ab), (ac,ac), (ba,ba))

scala> m.map(t => (t._1.substring(0, 1), t._2))
res1: scala.collection.immutable.Map[java.lang.String,java.lang.String] = Map((a,ac), (b,ba))

scala> m.view.map(t => (t._1.substring(0, 1), t._2))
res2: scala.collection.IterableView[(java.lang.String, java.lang.String),Iterable[_]] = IterableViewM(...)

scala> res2.foreach(println _)
(a,ab)
(a,ac)
(b,ba)
```

=== What is the expected behavior? ===

The result of calling map on view should behave like a map, in this case it should not have duplicate keys.

=== What do you see instead? ===

Keys are duplicated.

=== Additional information ===
http://thread.gmane.org/gmane.comp.lang.scala.user/34461

=== What versions of the following are you using? ===
  - Scala: 2.8.1
  - Java: Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_22
  - Operating system:  OSX 10.5

**Comment by SethTisue** [comment]
likely fixed in strawman. assigning to M4 milestone so we can check it once strawman lands

**Comment by lrytz** [comment]
This is unchanged in strawman, calling `map` on a `MapView` produces a plain `View`.

**Comment by lrytz** [comment]
It's also expected / by design, so I'm closing this as won't-fix.
