### ISSUE TITLE
found   : T with NotNull, required: T with NotNull

### ISSUE THREAD

**Issue by scabug** [scala/bug#4169]
=== What steps will reproduce the problem (please be specific and use wikiformatting)? ===
```scala
  def convertNull[T] (ref : T) (code : => T with NotNull) : T with NotNull =
    if (ref == null) code else ref.asInstanceOf[T with NotNull]
```

=== What is the expected behavior? ===
successful compilation

=== What do you see instead? ===
{code}
<console>:6: error: type mismatch;
 found   : T with NotNull
 required: T with NotNull
           if (ref == null) code else ref.asInstanceOf[T with NotNull]
                            ^
<console>:6: error: type mismatch;
 found   : T with NotNull
 required: T with NotNull
           if (ref == null) code else ref.asInstanceOf[T with NotNull]
{code}                                                      ^

=== What versions of the following are you using? ===
  - Scala: 2.8.0, 2.8.1

**Comment by Jasper-M** [comment]
`NotNull` doesn't exist anymore, and this issue doesn't seem to be reproducible with any other type.
