### ISSUE TITLE
mutable.IndexedSeq.view.map returns collection.SeqView

### ISSUE THREAD

**Issue by scabug** [scala/bug#4190]
=== What steps will reproduce the problem (please be specific and use wikiformatting)? ===
```scala
import collection.mutable._

val x: ArrayBuffer[String] = ArrayBuffer("a", "b", "c")
val y: IndexedSeq[String] = x.view map (_ + "0")
```

This code compiles but produces a `ClassCastException` in the last line:
```scala
java.lang.ClassCastException: scala.collection.SeqViewLike$$$$anon$$3 cannot be cast to scala.collection.mutable.IndexedSeq
```

=== What is the expected behavior? ===
A compiler error or working code.

=== What versions of the following are you using? ===
  - Scala: 2.8.1

**Comment by SethTisue** [comment]
likely fixed in strawman. leaving it on M4 milestone so we can check it once strawman lands

**Comment by lrytz** [comment]
The view type herarchy is much more shallow in 2.13, which mean we lose some view functionality, but are no longer exposed to bugs like those in this ticket.
