### ISSUE TITLE
Pressing particular key does not make corresponding symbol appear in REPL mode (windows-1251)

### ISSUE THREAD

**Issue by scabug** [scala/bug#4219]
Pressing key "р" (ru_RU, windows-1251) in REPL mode does not allow to see this symbol typed. Corresponding symbol in English layout for that key ("h") as well as upper case "Р" in Russian (usung Shift or Caps Lock) are not affected.

To reproduce this issue, please run scala to get into the REPL mode (using cmd.exe or powershell.exe), switch keyboard layout to Russian and type in the following word, say, "просто". You will get "псто". 2 symbols are gone ("о" after "р" does not get typed for the first time).

Scala: 2.8.1.final[[BR]]
Java: Java 1.6.0_23[[BR]]
OS: Windows Vista[[BR]]

**Comment by SethTisue** [comment]
sounds like a JLine thing. if it's still reproducible in 2.13.2 (which upgrades our REPL to use JLine 3), say so and we'll reopen.
