### ISSUE TITLE
Improve handling of deprecated methods/classes in the REPL

### ISSUE THREAD

**Issue by scabug** [scala/bug#4229]
= problem =
When using the REPL, deprecated methods/classes can only be noticed after using them.

```scala
warning: there were 1 deprecation warnings; re-run with -deprecation for details
```

= analysis =
It would be better if deprecated methods would be recognizable in tab-completion and in usage/while typing.

= enhancement recommendation =
Options to display deprecated methods/classes more clearly could be:
 - A "strike-through effect"
 - Some coloring (related to SI-4223)
 - Some marking like appending "(d)" in the tab completion 

If that would work, it might be possible to consider dropping the "warning after usage" when running scala without "-deprecation"

**Comment by SethTisue** [comment]
as of Scala 2.13.3, deprecated methods have a "(deprecated)" after them in tab completion:

<img width="483" alt="Screen Shot 2020-12-08 at 7 57 22 PM" src="https://user-images.githubusercontent.com/161079/101581887-ab2ea700-398f-11eb-89b9-490f6f159d38.png">

**Comment by SethTisue** [comment]
Ideally, deprecated methods would be presented last, in their own group. That may yet happen under https://github.com/scala/bug/issues/12272
