### ISSUE TITLE
Add methods sumBy and productBy to TraversableOnce

### ISSUE THREAD

**Issue by scabug** [scala/bug#4276]
Since there have methods minBy and maxBy in Traversable already, and in some cases it is useful if adding sumBy and productBy to TraversableOnce.
```scala
def sumBy[B](f: A => B)(implicit num: Numeric[B]): B = {
  var sum = num.zero
  for(x <- this) sum = num.plus(sum, f(x))
  sum
}
```

**Comment by SethTisue** [comment]
what I said in 2.11. also, views work in strawman.
