### ISSUE TITLE
spec clarification on `Array` and `null`

### ISSUE THREAD

**Issue by scabug** [scala/bug#4364]
There is a comment in Arrays.scala which says:
```scala
def unapplySeq[T](x: Array[T]): Option[IndexedSeq[T]] =
  if (x == null) None else Some(x.toIndexedSeq) 
  // !!! the null check should to be necessary, but without it 2241 fails. Seems to be a bug
  // in pattern matcher.  
```
I think the comment contradicts the spec, and the behavior is correct.  The only thing the spec says about null is that typed patterns match non-null values.  In order for the code above not to NPE, we'd have to stop calling extractors when the scrutinee is null.  Since that would make it impossible to write an extractor which deals with null, it seems undesirable.

**Comment by SethTisue** [comment]
I’ve labeled as “good first issue”, on the optimistic guess that a modest spec change might be sufficient to resolve this. Might :-)

**Comment by eed3si9n** [comment]
I've sent two competing pull requests addressing this issue.

1. https://github.com/scala/scala/pull/6374 takes Paul's position, and treats `null` passing to extractor is legal, and just adds clarification to the spec that `null` handling is up to extractor authors if so desired.
2. https://github.com/scala/scala/pull/6485 takes Martin's position, and treats `null` passing to extractor as a bug, and changes SLS and the implementation such that `null` is automatically treated as no match (empty), which effectively generalizes previous ad-hoc `null`-proofings in https://github.com/scala/scala/commit/d5b02c8652d7edbdfb0b5a02570d370d3bad299f#diff-1cef0df5926a4a2b2aa56f8f32354363R376 and https://github.com/scala/scala/pull/3923.

Not sure if this still counts as modest spec change, but I am just going where the code is taking me.

**Comment by NthPortal** [comment]
Though allowing pattern matching on `null` is more flexible(-ish), I feel like it's usually not intended, and can easily cause bugs if you don't realize that you need to check for `null` in your extractor

**Comment by Philippus** [comment]
fixed in https://github.com/scala/scala/pull/6485 ?

**Comment by paulp** [comment]
You could use an annotation e.g. `@HandlesNull` on an extractor to signal the compiler that null should be passed as an argument rather than swallowed as match failure.
