### ISSUE TITLE
Allow self-names in refinement types

### ISSUE THREAD

**Issue by scabug** [scala/bug#439]
Presently, it is only possible to refer to the object itself using "this".  For symmetry and aesthetic reasons it would be useful to be able to include a self name in refinements.  Something like
```scala
X1 with ... with Xn { self => ... }
```
I am not sure yet whether it also makes sense to allow an annotation on the self name as is possible in other contexts.

For example, the following is presently allowed:
```scala
val x : { val y : this.type } = new { val y : this.type = this }
```
but the following is not
```scala
val x : { self => val y : self.type } = new { self => val y : self.type = self }
```

**Comment by SethTisue** [comment]
out of scope for Scala 2. someone could propose something for Scala 3
