### ISSUE TITLE
inferring 2+ type parameters reveals the manifest behind the curtain

### ISSUE THREAD

**Issue by scabug** [scala/bug#4401]
```scala
scala> class Bippy[T : Manifest](x: T) { def f = "abc" }
defined class Bippy

scala> implicit def mkBippy[T: Manifest](x: T): Bippy[T] = new Bippy[T](x)
mkBippy: [T](x: T)(implicit evidence$$1: Manifest[T])Bippy[T]

scala> List(1).f
res0: java.lang.String = abc

scala> Map(1 -> 1).f
res1: java.lang.String = abc

scala> List().f
res2: java.lang.String = abc

scala> Map().f
<console>:10: error: could not find implicit value for evidence parameter of type Manifest[scala.collection.immutable.Map[A,Nothing]]
       Map().f
          ^
```
But:
```scala
scala> Map()
res4: scala.collection.immutable.Map[Nothing,Nothing] = Map()

scala> Map[Nothing,Nothing]().f
res5: java.lang.String = abc

scala> Map[Int,Int]().f
res6: java.lang.String = abc

scala> Map[Bippy[String],List[Set[Int]]]().f
res7: java.lang.String = abc
```
There's no wrong answer, scalac! Infer anything you like, just infer something. (And no you can't infer [A, Nothing] scalac, that is a category error.)

**Comment by pabloazul** [comment]
As of 2.13.0, does not give the Manifest  message, but gives an error.

scala> Map().f
             ^
       error: value f is not a member of scala.collection.immutable.Map[K,Nothing]

Closing as the reported issue is no longer occurring. If anyone sees a deeper issue that should be addressed, please add a comment and reopen if you feel it should be.

**Comment by paulp** [comment]
The error message changed immaterially, but nothing about the reported behavior has changed. It still reports a nonsense type containing one uninstantiated type parameter and one instantiated type parameter. And it still fails strictly because of artifacts of the implementation which strike when there are two type parameters, but not when there is only one.

**Comment by Jasper-M** [comment]
FYI `Set().f` gives the same error as the `Map` one, so I guess this is related to variance instead of arity.

**Comment by paulp** [comment]
@Jasper-M you are right. It's actually another consequence of the compiler's devil-may-care attitude about covariant type parameters (for which it will happily infer Nothing, which can be unified away later) vs. toward invariant ones. In that case there are probably a dozen other tickets which cover the matter.

**Comment by pabloazul** [comment]
@paulp - re-opening for now then, but will close it if I come across another candidate issue to point it at for completion, or if someone else does.

**Comment by dwijnand** [comment]
Duplicate of #1570

**Comment by dwijnand** [comment]
#1570 looked like a nice and early bug about how type inference is allergic to Nothing.
