### ISSUE TITLE
Make type checker use additional information from parameter bounds

### ISSUE THREAD

**Issue by scabug** [scala/bug#4447]
```scala
scala> def g[A, B >: A] {}
g: [A,B >: A]=> Unit

scala> def f[A, B, C >: A <: B] = g[A, B]
<console>:8: error: type arguments [A,B] do not conform to method g's type parameter bounds [A,B >: A]
       def f[A, B, C >: A <: B] = g[A, B]
                                   ^
```
Since <: is transitive, C >: A <: B immediately implies that A <: B, but right now the compiler doesn't "see" it.
See also https://groups.google.com/d/topic/scala-user/YX97K0jYZ60/discussion

**Comment by SethTisue** [comment]
stale/wontfix, I guess

**Comment by milessabin** [comment]
I would expect information to be propagated from left to right, ie. _not_ from the bounds on `C` to the bounds on `B`, so I think I would be happy to wontfix this one.
