### ISSUE TITLE
Scaladoc: Better icon for annotations

### ISSUE THREAD

**Issue by scabug** [scala/bug#4489]
= problem =
It would be nice to have a distinct icon for annotations. Maybe an "a" or a different color?

= analysis =
Currently it uses the same icons as other classes and traits.

= enhancement recommendation =
It would be nice to have a different icon for annotations.
One option would be an "a", and the green/blue background color of class/trait.
Another option would be distinct background color for annotation (with the character for class/trait).

**Comment by SethTisue** [comment]
not sure if this is still an issue since the big Scaladoc redesign in 2.12

**Comment by eed3si9n** [comment]
http://www.scala-lang.org/files/archive/nightly/2.13.x/api/2.13.x/scala/annotation/tailrec.html currently shows "C."

<img width="578" alt="scala_standard_library_2_13_0-pre-81ad83d_-_scala_annotation_tailrec" src="https://user-images.githubusercontent.com/184683/38481432-c8eb8c92-3b98-11e8-9273-a04ac5ab7691.png">

**Comment by m-sp** [comment]
I'd like to pick that up.
seems that *a* is already used by [abstract types](https://github.com/scala/scala/blob/2.13.x/src/scaladoc/scala/tools/nsc/doc/html/resource/lib/abstract_type.svg)

so how about @ with a slightly lighter shade of green?

![image](https://user-images.githubusercontent.com/3969000/39596343-5162cea0-4f12-11e8-9b82-4a10b4ccaa8f.png)

**Comment by adriaanm** [comment]
Looks good! There’s plenty of potential for refining the scaladoc UI.
Improvements most welcome. For example, with my recent work on moving us to
D3-based rendering for the diagrams, I set the visuals back a bit there.
