### ISSUE TITLE
Reduce immutable Map memory use

### ISSUE THREAD

**Issue by scabug** [scala/bug#4496]
= problem =
The immutable Map has a large memory overhead. For the data I'm storing in particular, I estimate we could save a gigabyte or so of memory with a few improvements.

= analysis =
Every key-value pair is stored in a HashMap1 containing a reference to the key, the value, a hash, and the key & value stored as a pair. There is a large amount of object overhead from the HashMap1, but also from the pair.

= enhancement recommendation =
Remove the variable kv from HashMap1 and create it on the fly (easy). Finish implementing HashMap2-5 to reduce object overhead (harder) - there's already a TODO in the code for this.

**Comment by SethTisue** [comment]
closing as outdated (besides, we don't generally keep open tickets on ideas for performance improvements)

however, perhaps someone from @scala/collections would be interested in looking into whether this still applicable with the current collections

**Comment by He-Pin** [comment]
@jhartman ping , if you still instrested in
