### ISSUE TITLE
partest won't work in the binary distribution

### ISSUE THREAD

**Issue by scabug** [scala/bug#4554]
=== What steps will reproduce the problem (please be specific and use wikiformatting)? ===
```scala
  mkdir testpartest
  cd testpartest
  wget --no-check-certificate --quiet https://scala-webapps.epfl.ch/jenkins/job/scala-nightly-main/ws/scala/dists/sbaz-partest.tgz
  tar xzf sbaz-partest.tgz
  mkdir test
  cd test
  for ii in library devel test
  do
   unzip -q -o ../sbaz/scala-$$ii-[0-9]*-*.sbp
  done
  chmod u+x bin/*
  # try partest
  bin/partest --all
```

=== What is the expected behavior? ===

Tests run.

=== What do you see instead? ===

```scala
Exception in thread "main" java.lang.RuntimeException: Directory 'test' not found.
	at scala.sys.package$$.error(package.scala:27)
	at scala.tools.partest.nest.PathSettings$$$$anonfun$$testRoot$$1$$$$anonfun$$apply$$2.apply(PathSettings.scala:24)
	at scala.tools.partest.nest.PathSettings$$$$anonfun$$testRoot$$1$$$$anonfun$$apply$$2.apply(PathSettings.scala:24)
```

=== Additional information ===

This functionality has been broken for a long time. Currently it is possible to get partest to run on the binary distribution by using symbolic links and other hacks, but this should really be fixed once and for all.

=== What versions of the following are you using? ===

Current trunk.

**Comment by SethTisue** [comment]
we no longer have any ambitions of running partest any other way but through sbt

**Comment by SethTisue** [comment]
wow. I looked at hundreds of dusty tickets today, but I think this was the dustiest of them all

**Comment by som-snytt** [comment]
🤧
