### ISSUE TITLE
Classes defined in REPL have no ScalaSig annotation

### ISSUE THREAD

**Issue by scabug** [scala/bug#4567]
Classes defined in the REPL are missing ScalaSig annotation.

=== What steps will reproduce the problem? ===

In 2.8.1 REPL:
```scala
    Welcome to Scala version 2.8.1.final (Java HotSpot(TM) 64-Bit
Server VM, Java 1.6.0_24).

    scala> case class Foo(x: String)
    defined class Foo

    scala> val clazz = classOf[Foo]
    clazz: java.lang.Class[Foo] = class Foo

    scala> clazz.getAnnotations
    res1: Array[java.lang.annotation.Annotation] = Array() 
```

In 2.9.0.RC4 REPL:
```scala
    Welcome to Scala version 2.9.0.RC4 (Java HotSpot(TM) 64-Bit Server
VM, Java 1.6.0_24).

    scala> case class Foo(x: String)
    defined class Foo

    scala> val clazz = classOf[Foo]
    clazz: java.lang.Class[Foo] = class Foo

    scala> clazz.getAnnotations
    res0: Array[java.lang.annotation.Annotation] = Array() 
```

=== What is the expected behavior? ===
Compare with this example, running sbt console in the Salat project
looking at one of the Salat test model classes, which has of course
a .class file but also a ScalaSig annotation:

```scala
    scala> import com.novus.salat.test.model._
    import com.novus.salat.test.model._

    scala> val clazz = classOf[Hector]
    x: java.lang.Class[com.novus.salat.test.model.Hector] = class
com.novus.salat.test.model.Hector

    scala> clazz.getAnnotations
    res2: Array[java.lang.annotation.Annotation] =
    !A/Z:u s9 "A tC2,GN   calaSignature(bytes=   c C                Q
                    GO  
    // etc etc etc 
```

=== What do you see instead? ===

I expect that defining a class in the REPL should create a class with a ScalaSig annotation.

Failing that, extending ScalaSigParser to be able to manually derive a ScalaSig annotation on a class defined in the REPL (or anywhere) would be extremely useful.

=== Additional information ===
http://groups.google.com/group/scala-user/browse_thread/thread/484ed3e719f13fdf

=== What versions of the following are you using? ===
  - Scala: 2.8.1
  - Java: 1.6.0_24-b07
  - Operating system: Ubuntu 11.04 64-bit

**Comment by SethTisue** [comment]
stale ticket, and not really a bug per se. could be revived on https://contributors.scala-lang.org
