### ISSUE TITLE
Indicate c++ runtime dependency for scala 2.9.0 REPL

### ISSUE THREAD

**Issue by scabug** [scala/bug#4673]
The scala REPL uses jansi.dll which needs msvcr90.dll from the c++ runtime libs.
Without it there is no history nor tab-completion available in the REPL. 
I suggest to mention in the installation instructions how to verify that msvcr90.dll is available and if not how to install it from Microsoft Visual C++ 2008 SP1 Redistributable Package (x86): 
http://www.microsoft.com/downloads/en/details.aspx?FamilyID=A5C84275-3B97-4AB7-A40D-3802B2AF5FC2
The analysis of this problem was done in the scala-user group discussion "No JLineReader in REPL": 
http://groups.google.com/group/scala-user/browse_thread/thread/5df0eb293817d08a/3b04ca8fe346869c#3b04ca8fe346869c

**Comment by SethTisue** [comment]
we can reopen if someone verifies this is still a concern
