### ISSUE TITLE
REPL is not accepting numeric keyboard input (including alt key combinations)

### ISSUE THREAD

**Issue by scabug** [scala/bug#4711]
When I want to enter a unicode code (or an ascii code) with the numpad the REPL is not accepting input.
On my keyboard I have to press Fn + Alt and the 'numeric keyboard plus key' and then the hexadecimal code (the digits may be from the numeric keyboard or the normal digit keys.

The REPL is accepting paste from the clipboard so there is a work around to type it in an editor and copy/paste
it to REPL.

**Comment by SethTisue** [comment]
closing for staleness. we can reopen if someone 1) verifies that it is still an issue, and 2) verifies that it is actually actionable in scala/scala (as opposed to JLine itself)
