### ISSUE TITLE
Scala interpreter is not ignoring package statement

### ISSUE THREAD

**Issue by scabug** [scala/bug#4768]
Running as script generates an error on package statement.
The interpreter should just ignore package statement (or use it internally if it is needed)

bar.scala (attachment)

```scala
package bar

object Bar extends App {
   println("test")
}
```

```
C:\scala-2.9.0.1\examples>scala bar.scala
C:\scala-2.9.0.1\examples\bar.scala:1: error: illegal start of definition
package bar
^
one error found
```

**Comment by SethTisue** [comment]
Scala 3 accepts it.

In Scala 2, if one tries this with scala-cli, `scala-cli run` accepts it for a `.scala` file, but rejects it for an `.sc` file.
