### ISSUE TITLE
avoid per-call allocation of Manifests

### ISSUE THREAD

**Issue by scabug** [scala/bug#4814]
Requiring a Manifest parameter on a method leads to the allocation/creation of the Manifest object along with type parameters in a List (recursively) at each call site for each call. It would be much better if the manifest were cached in the class which contains the method using it, e.g. in a static field.

**Comment by SethTisue** [comment]
_some_ improvement in this area could perhaps go forward (for `ClassTag` these days not `Manifest`), but I think it would need to be preceded by discussion on https://contributors.scala-lang.org about how it should be handled
