### ISSUE TITLE
Parameter type inference: error messages could be improved

### ISSUE THREAD

**Issue by scabug** [scala/bug#4830]
{code}
Welcome to Scala version 2.9.0.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_26).
Type in expressions to have them evaluated.
Type :help for more information.

scala> "nikita ivanov" split(" ") map (_.length)
res2: Array[Int] = Array(6, 6)

scala> "nikita ivanov" split(" ") map (() => _.length)
<console>:8: error: missing parameter type for expanded function ((x$1) => x$1.length)
       "nikita ivanov" split(" ") map (() => _.length)
{code}                                             ^

How come the parameter type cannot be inferred in the second example while 1st one works fine?!?

**Comment by SethTisue** [comment]
we aren't keeping open tickets on theoretically improvable error messages. fwiw, the Scala 3 error is similar. On the possibility of improvement there, see https://www.scala-lang.org/blog/2023/10/17/feedback-wanted-error-messages.html

**Comment by som-snytt** [comment]
This is not recently improved in dotty.

It's not merely theoretically improvable. The compiler knows that there is an enclosing expression of function type, and it should tell the user that their underscore should "bind" there.
