### ISSUE TITLE
util.control.Exception.catching doesn't catch certain exceptions even if you explicitly ask it to

### ISSUE THREAD

**Issue by scabug** [scala/bug#4974]
```scala
scala> util.control.Exception.catching(classOf[InterruptedException]).withApply{x => ()} { throw new InterruptedException }
java.lang.InterruptedException
	at $anonfun$2.apply(<console>:8)
	at $anonfun$2.apply(<console>:8)
	at scala.util.control.Exception$Catch.apply(Exception.scala:88)
	at .<init>(<console>:8)
        [...]
```

Hey catching, I said CATCH!  `InterruptedException`, I said!

This is kinda sorta documented, so arguably it was just my failure to RTFM. But it does seem odd to me that if I **explicitly** say I want to catch that exception, it doesn't override the shouldRethrow stuff.

Priority: low, no doubt. Opening the ticket anyway.

**Comment by Philippus** [comment]
I don't see this as in issue, there's `catchingPromiscuously` for the desired behaviour.

**Comment by dwijnand** [comment]
Sadly Paul didn't document why he filtered those exceptions out: https://github.com/scala/scala/commit/beebad1bc4

Given:
* this isn't a very heavily used API
* the behaviour is as documented, and
* the alternate behaviour is available with another method

I think we should just leave the status quo over introducing a breaking change. Thus: closing.

**Comment by SethTisue** [comment]
yeah, this stuff is headed for a module anyway
