### ISSUE TITLE
.par shouldn't force and copy random accessible collections

### ISSUE THREAD

**Issue by scabug** [scala/bug#4984]
Copying the complete collection when calling `.par` on `IndexedSeqs` is wasteful. There are use cases where the `IndexedSeq` is backed by an external data store which may be (much) bigger than what currently fits into memory. Is there any rationale for that copying in the case of `IndexedSeqs`? Or is there just no alternative implementation yet?

**Comment by SethTisue** [comment]
please open a new ticket at https://github.com/scala/scala-parallel-collections if this is still a concern
