### ISSUE TITLE
WrappedArray missing explicit SerialVersionUID annotation

### ISSUE THREAD

**Issue by scabug** [scala/bug#5046]
SerialVersionUID is not explicitly set for WrappedArray and the subclasses of WrappedArray: ofRef, ofByte, ofShort, ofChar, etc.

I'm running into InvalidClassExceptions when deserializing an Enumeration that was serialized with a different version of scala-library:Caused by: 

```scala
java.io.InvalidClassException: scala.collection.mutable.WrappedArray$ofRef; 
local class incompatible: stream classdesc serialVersionUID = 6238838760334617323, local class serialVersionUID = 8184381945838716286
```

**Comment by xuwei-k** [comment]
https://github.com/scala/scala/blob/v2.13.0-M4/src/library/scala/collection/mutable/ArraySeq.scala#L26

`mutable.ArraySeq` ( [renamed since Scala 2.13.0-M4](https://github.com/scala/scala/blob/v2.13.0-M4/src/library/scala/collection/mutable/package.scala#L5) ) have explicit `@SerialVersionUID` annotation.

**Comment by ShaneDelmore** [comment]
I see this ticket is closed.  Is it now included in a release version of 2.12.x or 2.13.x or was it decided not to include it?

**Comment by SethTisue** [comment]
It's milestoned 2.13.0-M4, which means the fix _should_ be in 2.13.0 as well. Let us know if you find evidence to the contrary.

**Comment by ShaneDelmore** [comment]
Got it, thank you.

**Comment by dieu** [comment]
@SethTisue 2.12.x has the same issue, is it possible to backport solution to 2.12.x?

**Comment by SethTisue** [comment]
@dieu I can't think of any reason a PR with a backport wouldn't be merged

**Comment by ahummel25** [comment]
I'm seeing this in Scala 2.13.5. Is this supposed to be fixed in that version?

**Comment by dwijnand** [comment]
`mutable.WrappedArray` doesn't even exist in 2.13, so I find it difficult to believe you're seeing it in 2.13.5.

**Comment by ahummel25** [comment]
My mistake, I believe I had a mismatching spark-submit Scala version and sbt Scala version.

**Comment by hamidelmaazouz** [comment]
I get the same failure.

I am running on Spark 3.2.1 which in turn runs Scala 2.12.10. My code is also Scala 2.12.10, but I don' see where the issue is coming from or how to address it.

**Comment by SethTisue** [comment]
@hamidelmaazouz https://github.com/scala/scala/pull/9166 was merged for 2.12.14, so it's expected that you might run into this on 2.12.10

**Comment by kaaquist** [comment]
@hamidelmaazouz I know this here is an old issue. But did you manage to fix your problem? I'm facing the same thing in a spark setup where the communication between the driver and the executors "dies" because:
```text
java.io.InvalidClassException: scala.collection.mutable.WrappedArray$ofRef; local class incompatible: stream classdesc serialVersionUID = 3456489343829468865, local class serialVersionUID = 1028182004549731694
```
Can see the version of spark 3.2.1 I use is build with scala 2.12.11
```text
<<K9s-Shell>> Pod: jhub-spark/test-spark-a3ad4882bac71f15-exec-4 | Container: spark-kubernetes-executor 
root@test-spark-a3ad4882bac71f15-exec-4:/opt/spark/work-dir# cd ../bin
root@test-spark-a3ad4882bac71f15-exec-4:/opt/spark/bin# ./spark-submit --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.2.1
      /_/
                        
Using Scala version 2.12.11, OpenJDK 64-Bit Server VM, 1.8.0_144
Branch HEAD
Compiled by user hgao on 2022-01-21T00:35:52Z
Revision 4f25b3f71238a00508a356591553f2dfa89f8290
Url https://github.com/apache/spark
Type --help for more information.
```
Maybe you have some pointers to how I can fix my issue.

**Comment by kaaquist** [comment]
I can confirm that bumping the scala version from `2.12.11` -> `2.12.14` on my spark setup made the error disappear. 
```text
> docker run -it -u root --entrypoint bash bazel/third_party/spark:spark_image
root@8635b6f9ca15:/opt/spark/work-dir# cd ../bin/
root@8635b6f9ca15:/opt/spark/bin# ./spark-submit --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 3.2.1
      /_/
                        
Using Scala version 2.12.14, OpenJDK 64-Bit Server VM, 1.8.0_144
Branch HEAD
Compiled by user hgao on 2022-01-21T00:35:52Z
Revision 4f25b3f71238a00508a356591553f2dfa89f8290
Url https://github.com/apache/spark
Type --help for more information.
root@8635b6f9ca15:/opt/spark/bin# 
```

**Comment by hamidelmaazouz** [comment]
Hi @kaaquist,

Sorry for the late reply.

Indeed it's a Scala version problem. Scala AFAIK is not backwards compatible, so you need to match your scala version with the one used in Spark. So you have two solutions:

- Align your version to match that of Scala in Spark
- Build Spark yourself to match your Scala version

Best,
