### ISSUE TITLE
ArrayBuilder should expose current size as .length or .size

### ISSUE THREAD

**Issue by scabug** [scala/bug#5090]
When using an ArrayBuilder, there currently seems to be no way to get the current number of elements that it already holds, even though it tracks the element count as a private field 'size' in all implementations I could see. This forces a user that needs to know continuously how many elements were added to carry a duplicate count, wasting memory and cycles. 

The specific request is that ArrayBuilder should expose its current element count via a public .length or .size method.

**Comment by SethTisue** [comment]
has this changed in strawman?

**Comment by lrytz** [comment]
There's `ArrayBuilder.length`
