### ISSUE TITLE
Undefined, unused, and incorrect non-terminals in chapter 10 (XML) of Scala Language Specification

### ISSUE THREAD

**Issue by scabug** [scala/bug#5141]
In section 10.1:
- `CharRef` is used in the production for `AttValue`, and not defined anywhere. Should be added to the production defining nonterminals to be "as in W3C XML".
- `CharNoRef` is used in the production for `CharData` in section 10.1, and not defined anywhere. It should be replaced by `Char1`. (Aside: the XML spec uses regexps such as [^&<"] to represent character classes `CharQ` and `CharA`. It would make sense to do the same here.)
- `CombiningChar` is defined in the production "as in W3C XML", but not used anywhere.
- `XNameStart` is defined to include `BaseChar` -- which contradicts the annotation "(as in W3C XML, but without ':'" and is incorrect, since `BaseChar` includes e.g. digits, which can't start names neither in XML or in Scala. Should be either copied from http://www.w3.org/TR/REC-xml/#NT-`NameStartChar` removing the initial ":" or defined as `NameStartChar` _without_ `':'` and `NameStartChar` included to the "as in W3C XML" production.

**Comment by som-snytt** [comment]
Closing without prejudice as out of scope, since xml parsing is effectively deprecated (for removal on the horizon of Scala 3).

The omissions noted here do not seem to have hindered implementation or adoption.

Contributions should be directed to the 3.4 specification.
