### ISSUE TITLE
scala.xml.MetaData doesn't compile with -Xexperimental

### ISSUE THREAD

**Issue by scabug** [scala/bug#5144]
```scala
[scalacfork] /home/jordi/workspace/scala/src/library/scala/xml/MetaData.scala:30: error: could not optimize @tailrec annotated method concatenate: it is neither private nor final so can be overridden
[scalacfork]   def concatenate(attribs: MetaData, new_tail: MetaData): MetaData =
[scalacfork]       ^
[scalacfork] one error found
```

The compiler is correct: -Xexperimental also sets overrideObjects -- so this method is effectively overridable. The solution has to be in MetaData.scala.

**Comment by SethTisue** [comment]
closing for staleness. `-Xexperimental` is gone in 2.13

it's possible there's still an issue here, but it would need re-investigation.
