### ISSUE TITLE
Allow `string lit` identifiers in the left-hand side of cases

### ISSUE THREAD

**Issue by scabug** [scala/bug#5228]
In the section "8.1 Patterns" the spec explicitly says that variables that can be bound in a pattern match have to have the shape of "varid", i.e. that they cannot start with a capital letter, and that they cannot be surrounded with backquotes. The prior seems reasonable, because it lets the compiler distinguish variable binds and extractors, but I cannot grok the reason behind the latter.

**Comment by som-snytt** [comment]
Stopping by because of a spurious code comment.
