### ISSUE TITLE
// comments are nested in scala-mode

### ISSUE THREAD

**Issue by scabug** [scala/bug#5261]
The syntax table definition for scala-mode makes // comments "nestable". I.e. when using them on 2 consecutive lines, they extend to the line thereafter:

// comment 1
// comment 2
app.Run() // <-- this line is highlighted as a comment

Additionally, a " *" gets inserted when you open a new line.

The attached patch fixes this for me, making only /* style comments nested.

I'm using Emacs build from bzr trunk.

**Comment by SethTisue** [comment]
emacs stuff doesn't live in scala/* anymore
