### ISSUE TITLE
warn on implicit def without explicit result type

### ISSUE THREAD

**Issue by scabug** [scala/bug#5265]
The following code snipet : https://gist.github.com/1427587
does not compile.

```scala
import java.util.Date

trait TDate 

trait TT[A1,T1]

trait TTFactory[F,G] {
  def create(f: F) : TT[F,G]
  def sample: F
}

object Impls {

  // If the c1 is declared before c2, it compiles fine
  // or if the implicit's result type is specified explicitly
  implicit def c2(s: Date)/* : TT[Date, TDate] */ = c1.create(s)  

  implicit val c1 = new TTFactory[Date,TDate] {
    def create(v: Date): TT[Date,TDate] = sys.error("")
    def sample = new Date
  }
}
```

**Comment by SethTisue** [comment]
This'd be a great project for somebody.

It has increased significance lately given that Scala 3 requires the explicit result type:

```
scala> implicit def x = 3
-- Error: ----------------------------------------------------------------------
1 |implicit def x = 3
  |             ^
  |           result type of implicit definition needs to be given explicitly
1 error found
```

So I would say that `-Xlint` should warn about this by default, and `-Xsource:3` should turn that warning into error.

Is there a volunteer who would like to tackle it?

**Comment by sjrd** [comment]
To whoever would like to take this on, note that the warning should not apply to *local* definitions, i.e., those for which `sym.isLocalToBlock` is true. Such definitions are only visible after they're defined, and hence doing cause problematic cycles. Early experimentation in dotty discovered that they had to be allowed to preserve reasonable code patterns.

**Comment by som-snytt** [comment]
> This'd be a great project for somebody.

Possible typo for Som, homebody. Or is that a portmanteau?

**Comment by som-snytt** [comment]
Possible noise reduction if it accepted
```
implicit def f = foo.asInstanceOf[Bar]
implicit def g = foo: Bar
```
The first form, in particular, adds information.

The current exemption is for override in Scala 3/-Xsource:3.
