### ISSUE TITLE
avoid duplicating more than once a closure body when inlining a closure

### ISSUE THREAD

**Issue by scabug** [scala/bug#5286]
`immutable.Range.foreach()` invokes its argument's `apply()` twice. When compiling with -optimize, that leads to inlining twice "the loop body" (if it gets inlined at all, for the max size threshold might be surpassed due to the duplicate inlining). 

A formulation of `immutable.Range.foreach()` invoking its argument's `apply()` just once is: 

```
if (length > 0) {
  val sentinel = last
  var closuVar = start
  var loopCond = true
  while ( loopCond ) {
    f(closuVar)
    if(closuVar == sentinel) loopCond = false
    else closuVar += step
  }
}
```

There can be other places in the collections library that exhibit a similar pattern.

**Comment by SethTisue** [comment]
closing old back end tickets which are likely no longer applicable
