### ISSUE TITLE
Stackoverflow when compiling 19k LOC Scala file

### ISSUE THREAD

**Issue by scabug** [scala/bug#5297]
Scalaxb generates client-side stubs for WSDL SOAP webservices. The Salesforce's Enterprise WSDL (7.6K LOC) causes an explosion of the xmlprotocol.scala file to become 19K LOC. A compilation fails after 45 minutes with a stackoverflow error with high memory usage. A normal compilation takes roughly 2 minutes. 

This may be related to:
#3269

Bug rejected by Scalaxb in:
https://github.com/eed3si9n/scalaxb/issues/131

See the attachment for the compiler log, generated file, and the project's build file. A standalone example can be provided if needed.

**Comment by SethTisue** [comment]
closing for staleness. my guess is that if someone wants to improve implicit search performance (e.g. @milessabin), this won't be the motivating example.

**Comment by milessabin** [comment]
It's not main kind of example that I'm interested in, but I think it's a useful data point. Rather than closing bugs like this can't you label them as stale and leave them for posterity?

**Comment by SethTisue** [comment]
well, this is certainly debatable, but... if something is best described as a useful data point or example case for some larger issue, I'd rather that it were a comment or a link on that larger issue. we have an overwhelming number of open tickets. and despite being closed, the ticket does still exist for posterity

I'm not adamant it remain closed, but that's my case for closing it.
