### ISSUE TITLE
Piping methods on Any similar to scalaz "|>", Ruby "tap"

### ISSUE THREAD

**Issue by scabug** [scala/bug#5324]
## Introduction
The piping methods have proven to be extremely useful in other languages: `.with` - Groovy; `.tap` - Ruby. It's a known fact that a lot of people get surprised not to meet any similar feature in Scala as well as that because of that a lot of them introduce custom implicit conversions.

## Examples
Let's consider two examples of how the same purpose of outputting the following text can be achieved with and without the proposed feature:
```
Source: List(1, 2, 3, 4, 5)
Result: [2,4]
```

### Example one: with proposed methods `tap` and `convert`
```scala
Seq(1, 2, 3, 4, 5)
  .tap(it => println("Source: " + it))
  .filter(_ % 2 == 0)
  .convert(it => if (it.nonEmpty) "[" + it.mkString(",") + "]" else "")
  .tap(it => println("Result: " + it))
```
Please notice how factored, maintainable and easy on the eye the above code is

### Example two: how one has to do it currently
```scala
val tmp1 = Seq(1, 2, 3, 4, 5)
println("Source: " + tmp1)
val tmp2 = tmp1.filter(_ % 2 == 0)
val tmp3 = if (tmp2.nonEmpty) "[" + tmp2.mkString(",") + "]" else ""
println("Result: " + tmp3)
```
Notice that you have to stop and think 3 times on naming the obviously redundant intermediate variables. Also notice how unreadable, unfactored and harder to manage that code is.

## Implementation
Currently for the first example to work you'll need a following implicit conversion. You can also learn the specification of methods from there:
```scala
implicit def wrapAny[Source](source: Source) = new AnyWrapper(source)
class AnyWrapper[Source](source: Source) {
  def tap[Result](closure: Source => Result): Source = {
    closure(source)
    source
  }
  def convert[Result](closure: Source => Result): Result = {
    closure(source)
  }
}
```

## The suggestions:
1. Introduce a method with codename "convert" (or "use" or "pipe" or "pipeTo" as suggested by some) which executes a closure on the object and returns the result of that closure
2. Introduce a method with codename "tap" (or "effect" as suggested by some) which executes a closure on the object and returns the object itself
3. Not to inherit the scalaz operator-style "|>" title as it is considered disturbing by many
4. Discuss details such as names in this thread

This suggestion originates from the following discussion on StackOverflow: http://stackoverflow.com/questions/8537992/with-alternative-in-scala/8538277

**Comment by dwijnand** [comment]
Can one (such as myself) PR this? Or should it be rejected and closed?

**Comment by SethTisue** [comment]
seems like an open question whether a PR on this would ultimately succeed.

naming-wise, I like `.tap` fine... don't much care for either `convert` or `as`, but not sure what else to suggest

**Comment by eed3si9n** [comment]
Sent a PR - https://github.com/scala/scala/pull/6767

**Comment by sjrd** [comment]
Repeating what I said at https://github.com/scala/scala/pull/6767#issuecomment-396120033 :

What's the rationale for this to be in `Predef`? It could and should be explicitly imported.

There should be much stronger resistance against putting stuff in `Predef`, including pimps to `Any`.

**Comment by eed3si9n** [comment]
So it seems like people are ok with this being part of Scala library, but -1 on `scala.Prefef`.

Any suggestions on what the import would be called?

```scala
import scala.util.AnyOps
```

?

**Comment by Ichoran** [comment]
`AnyOps` seems too general.  Maybe `ChainingOps`?

**Comment by paulp** [comment]
Please, you shouldn't even be considering a name like `AnyOps` in the standard library, ever. Don't sentence thousands of people to import renaming in every file. Every implicit in the standard library should be named something like `ThisIsTheStandardLibraryAnyOps`.

**Comment by eed3si9n** [comment]
@paulp 

> Please, you shouldn't even be considering a name like `AnyOps` in the standard library, ever. Don't sentence thousands of people to import renaming in every file. Every implicit in the standard library should be named something like `ThisIsTheStandardLibraryAnyOps`.

Good point.

Maybe we should adopt the Cats naming convention and prefix the package name like `scala.util.ScalaUtilChainingOps`.

**Comment by Atry** [comment]
I wonder if we can backport this feature to https://github.com/scala/scala-collection-compat

**Comment by SethTisue** [comment]
> I wonder if we can backport this feature to https://github.com/scala/scala-collection-compat

that did happen: https://github.com/scala/scala-collection-compat/pull/320

**Comment by SethTisue** [comment]
for anyone looking to follow the discussions that have happened on this:

* https://github.com/scala/scala/pull/6767 (not merged)
* https://github.com/scala/scala/pull/7007 (merged)
* https://github.com/scala/scala/pull/7326 (not merged)

there have also been some forum threads covering the same ground:

* https://contributors.scala-lang.org/t/give-the-pipe-method-of-scala-util-chainingops-an-operator-representation/4462
* https://contributors.scala-lang.org/t/pipeline-operator/5988/15

as of 2025, the status quo is:
* `pipe` is in stdlib
* but requires an import (`import scala.util.chaining.*`)
* and does not have a symbolic alias (no `|>`)
* `tap` exists, alongside `pipe`
* collections have `tapEach`

the slight performance overhead won't be fixed in Scala 2, but the door will soon be open to fix it in Scala 3 stdlib using `inline`

**Comment by som-snytt** [comment]
The incantation for inlining only tap and pipe in Scala 2 is something like
```
//> using options -opt:inline:scala.util.ChainingOps$,scala.util.ChainingSyntax,scala.util.package$chaining$,<sources> -Yopt-inline-heuristics:everything

import scala.util.chaining._

class C {
  def f(s: String): String =
    s.pipe(x => s + s.length)
}

object Test extends App {
  val c = new C
  println {
    c.f("hello, world")
  }
}
```
The `-Y` is needed to inline the static call to the lambda method. (That may be secondary to eliminating the chaining bits.)
```
  public java.lang.String f(java.lang.String);
    descriptor: (Ljava/lang/String;)Ljava/lang/String;
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=3, locals=2, args_size=2
         0: getstatic     #22                 // Field scala/util/ChainingOps$.MODULE$:Lscala/util/ChainingOps$;
         3: pop
         4: getstatic     #25                 // Field scala/util/package$chaining$.MODULE$:Lscala/util/package$chaining$;
         7: pop
         8: new           #27                 // class java/lang/StringBuilder
        11: dup
        12: ldc           #28                 // int 0
        14: invokespecial #32                 // Method java/lang/StringBuilder."<init>":(I)V
        17: aload_1
        18: invokevirtual #36                 // Method java/lang/StringBuilder.append:(Ljava/lang/String;)Ljava/lang/StringBuilder;
        21: aload_1
        22: invokevirtual #42                 // Method java/lang/String.length:()I
        25: invokevirtual #45                 // Method java/lang/StringBuilder.append:(I)Ljava/lang/StringBuilder;
        28: invokevirtual #49                 // Method java/lang/StringBuilder.toString:()Ljava/lang/String;
        31: areturn
```
Scala 3:
https://github.com/scala/scala3/blob/main/compiler/src/dotty/tools/dotc/util/chaining.scala
