### ISSUE TITLE
Scaladoc workflow definition and implementation

### ISSUE THREAD

**Issue by scabug** [scala/bug#5363]
We need to design a workflow for searching something in scaladoc and make sure it's consistent on all platforms: Win, Linux, OSX.
We should also design a (different) workflow for mobile devices: IOS and Android should have similar scaladoc search experience.

As pointed out [here](http://groups.google.com/group/scala-user/browse_thread/thread/bcb18b71b11bd300/7624bc6d407b0d0a?lnk=gst&q=%22scaladoc+discoverability%22#7624bc6d407b0d0a), scaladoc doesn't work properly on ipad.

**Comment by SethTisue** [comment]
search was redone in Scaladoc in 2.12. please open a new ticket if this is still a concern
