### ISSUE TITLE
Scaladoc generates incorrect source links to Java source files

### ISSUE THREAD

**Issue by scabug** [scala/bug#5388]
in ModelFactory.sourceUrl, it does .stripSuffix(".scala") , so when you specify -doc-source-url when calling Scaladoc you have to add the .scala back in to the URL, except then that means any links to Java source files end up as ".java.scala" instead of just ".java"

**Comment by smarter** [comment]
This issue affects the scaladoc of scalac itself: http://www.scala-lang.org/api/2.12.4/scala-compiler/scala/tools/nsc/profile/ExternalToolHook.html points to https://github.com/scala/scala/tree/v2.12.4/src/compiler/scala/tools/nsc/profile/ExternalToolHook.java.scala#L1

**Comment by SethTisue** [comment]
scala/scala#7532 (2.13), scala/scala#7559 (2.12)

Enno thanks for fixing the bug I reported in 2012 :-)
