### ISSUE TITLE
scala 64-bit MSI

### ISSUE THREAD

**Issue by scabug** [scala/bug#5409]
The scala-dist project should generate a 64-bit MSI as well as a 32-bit MSI.  The current 32-bit MSI cannot find 64-bit installations of Java due to the registry differences between 64-bit and 32-bit software.

Annoying, but it's windows.   Time to learn the dark arts of UUIDs and CAB.

**Comment by SethTisue** [comment]
is this still an issue? if someone looks into it, finds that it is, and documents the current situation here, we can reopen

conceivably relevant: https://github.com/scala/scala-dist/pull/180 which was just merged, so won't ship until 2.13.0-M4
