### ISSUE TITLE
parameterised extractors

### ISSUE THREAD

**Issue by scabug** [scala/bug#5435]
allow extractors to take multiple argument lists

(prototype: https://github.com/adriaanm/scala-dev/commit/b67f5d4e0fbdbac29a6c82017d414e066aeedf34)
(stackoverflow question: http://stackoverflow.com/questions/2411573)

**Comment by SethTisue** [comment]
out of scope for Scala 2

**Comment by som-snytt** [comment]
That parallel universe where Adriaan fights to publish 2.14 with his complete wish list _and_ everything Paul would have done differently. An unlikely duo thrown together to restore balance to the ecosystem... before it's too late!

**Comment by SethTisue** [comment]
Seems unlikely to attract funding from the major Hollywood studios, but maybe a neighborhood theater could do a puppet-show production.
