### ISSUE TITLE
Typechecking extractors is not idempotent

### ISSUE THREAD

**Issue by scabug** [scala/bug#5465]
Pattern matching that involves extractors cannot be typechecked twice. The first typecheck distorts its structure, introducing UnApply node that wraps a synthetic SELECTOR_DUMMY ident that doesn't have a definition. If one performs resetAllAttrs, the resulting tree can no longer be typechecked.

**Comment by SethTisue** [comment]
consolidating under #5464

**Comment by SethTisue** [comment]
#8825 was in this space and was fixed by https://github.com/scala/scala/pull/6356

#12577 is also in this space
