### ISSUE TITLE
Typechecking case classes is not idempotent

### ISSUE THREAD

**Issue by scabug** [scala/bug#5467]
In the majority of cases typechecking replaces arbitrary trees that represent types with their TypeTree() equivalents that have the "tpe" fields that hold the compiled types and the "original" fields that hold the original trees with assigned symbols.

Case classes are no exception. Once plain and symless, after typechecking ValDefs have their tpts changed into TypeTrees. Thanks to originals, TypeTrees are friendly to resetAllAttrs, so everything seems to be fine. However, part of the implementation of case classes employs the violent UnTyper that erases the tpes without looking into originals. Trees that undergo such brutal treatment cannot be typechecked anymore.

Another source of non-idempotency is the whole synthetic business. Even if a case class or a case companion already have certain members, subsequent typechecking will try to add them again, resulting in conflicts and, ultimately, compilation errors.

**Comment by SethTisue** [comment]
consolidating under #5464
