### ISSUE TITLE
Meta-bug: Omitting non-ambiguous implicit conversions should be valid

### ISSUE THREAD

**Issue by scabug** [scala/bug#5592]
The language description of implicits suggests a conjecture: omitting an implicit should be valid, unless it is ambiguous or a more specific implicit would be selected; however, due to bugs in type-inference, this is not the case.
Is the conjecture intended to hold?

I would like to collect bugs affecting this issue as related to this.

**Comment by SethTisue** [comment]
stale. probably better as a discussion on https://contributors.scala-lang.org anyway, if someone is still interested
