### ISSUE TITLE
Compiler should not call System.exit

### ISSUE THREAD

**Issue by scabug** [scala/bug#5674]
...except under very specific/clear circumstances.  To do so otherwise seriously hampers interoperation with maven, sbt, osgi, any situation where we don't completely own the running jvm.

**Comment by SethTisue** [comment]
/me shudders

is there a good samaritan who wants to tackle this?

**Comment by NthPortal** [comment]
I could have a look into this.

What does `exit` get replaced with?

**Comment by SethTisue** [comment]
well, that might depend on context. in general compiler code, just throw an exception, e.g. with `Global.require`. or whatever. there is a lot of diversity in the codebase on this: `throw new IllegalArgumentException`, `throw new IllegalStateException`, `throw new FatalError`, you'll see all sorts of stuff

perhaps there will be cases where there would be room to do even better, e.g. by reporting some kind of proper compiler error? but you needn't go there unless you really feel like it, feel free to scope the issue narrowly. `System.exit` and `sys.exit` are so bad that basically anything is better. (just don't launch the proverbial missiles.)

**Comment by SethTisue** [comment]
thought: it's conceivable that one or more of the remaining calls is actually legit, like maybe in an `fsc` context? something to keep in mind, but you needn't get paranoid about it

**Comment by NthPortal** [comment]
Looking more closely at some of the uses, a lot of them are `exit(0)`, which is supposed to indicate a clean exit; this necessarily cannot be replaced with an exception indicating failure. Should there be a new `CleanExit` exception (`ControlThrowable`?), to replace `exit(0)`? Or something else? In some of these cases (e.g. `scala.tools.cmd.runAndExit`), it is not possible to merely remove the clean exit, as it actually short-circuits the code.

**Comment by NthPortal** [comment]
@SethTisue Looking more closely at some of the uses, a lot of them are `exit(0)`, which is supposed to indicate a clean exit; this necessarily cannot be replaced with an exception indicating failure. Should there be a new `CleanExit` exception (`ControlThrowable`?), to replace `exit(0)`? Or something else? In some of these cases (e.g. `scala.tools.cmd.runAndExit`), it is not possible to merely remove the clean exit, as it actually short-circuits the code.

**Comment by SethTisue** [comment]
@NthPortal sorry but I haven't had time to take a closer look at this and won't this week either. we can look at it on a case-by-case basis on the PR.

**Comment by NthPortal** [comment]
@SethTisue No worries

For all of the ones where `exit(0)` was at the end of a `main` method, I just removed it. It's really just `runAndExit` that I'm not sure how to remove
