### ISSUE TITLE
scalac warns about deprecated use of identifier "then" even if it is marked as deprecated

### ISSUE THREAD

**Issue by scabug** [scala/bug#5715]
In the following source code

```scala
    @deprecated("Use Then instead of then", "0.10.0-M2")
    def then[B : BaseTypeMapper](res: Column[B]) = Then(res)
```

scalac complains that

```scala
C:\Users\szeiger\code\scala-query\src\main\scala\scala\slick\ql\Case.scala:28: then is now a reserved word; usage as an identifier is deprecated
    def then[B : BaseTypeMapper](res: Column[B]) = Then(res)
        ^
```

This is not usually the case when using deprecated API. If the caller is also deprecated, no warning should be emitted.

**Comment by magnolia-k** [comment]
Warnings about reserved words are given in the lexical analysis stage(`src/compiler/scala/tools/nsc/ast/parser/Scanners.scala
`). Therefore, warnings are displayed in all places where they appear as identifiers.

Isn't it enough to issue warnings at the time of identifier declaration?

```scala
package example

class then

object Foo {
  val t = new then
}
```

```
[info] compiling 1 Scala source to /xxx/scala-seed-project/target/scala-2.13/classes ...
[warn] /xxx/scala-seed-project/src/main/scala/example/Hello.scala:3:7: then is a reserved word (since 2.10.0); usage as an identifier is deprecated
[warn] class then
[warn]       ^
[warn] /xxx/scala-seed-project/src/main/scala/example/Hello.scala:6:15: then is a reserved word (since 2.10.0); usage as an identifier is deprecated
[warn]   val t = new then
[warn]               ^
[warn] two warnings found
```

With the release of Scala3, reserved words have already been fixed, and reserved words other than `then` have been added.

Therefore, it would be better to remove the warning about future reserved words in the lexical analysis stage, and change it to warn against reserved words other than then, which were added in Scala3, only when declaring identifiers.

**Comment by SethTisue** [comment]
>  it would be better to remove the warning about future reserved words in the lexical analysis stage

agree; I would be in favor of merging a PR that did only that

and as a separate matter, if new warnings are added, I'd suggest putting those warnings behind `-Xsource:3`

**Comment by som-snytt** [comment]
It could be done via the much-abused "extra units of work" that run after typer.

**Comment by som-snytt** [comment]
```
new then
```
should be
```
new `then`
```
that is, if we were still using `new`.

These warnings already go through `runReporting`, so `-Wconf` works.

Normally, `Refchecks` checks deprecated usage. It could also do the name check, as an `Ident` now knows if it was backticked.

For the definition, typer could clear buffered deprecations in range of the deprecated definition.

**Comment by som-snytt** [comment]
The future keywords warning was at https://github.com/scala/scala/pull/9722.

My first take removed the current warning at scanner, added the usage warning in refchecks (check the name when the ref is checked) and the definition site warning piggy-backing on the future keywords warning in parser.

My second take piggybacks on `-Wconf`/`nowarn` to emit a `Suppression` when deprecations are seen, the equivalent of `@nowarn(cat=deprecation)` but does not trigger unused warning. (But the deprecation from scanner doesn't get site and origin for advanced `-Wconfing`.)

The hard part on first take was figuring out who was stripping the `isBackquoted` attachment. (It was the conversion to type name.)
