### ISSUE TITLE
ICode instruction invariants are missing

### ISSUE THREAD

**Issue by scabug** [scala/bug#5819]
Context for this: #5672 and discussion at https://github.com/scala/scala/pull/596

```
assert(consumed == consumedTypes.size, 
       "Someone forgot to override consumedTypes() in " +  this)
```

Also merge in Paul's ICode cleanup: https://github.com/scala/scala/commit/6e943125b3

**Comment by SethTisue** [comment]
strong hunch this is no longer applicable
