### ISSUE TITLE
Can't call no-type-parameter version of a method overloaded on type parameters

### ISSUE THREAD

**Issue by scabug** [scala/bug#5827]
In order to be able to allow DynamicProxy to accept explicit type parameters, I found that I needed to be able to override the *Dynamic methods on their type parameters. The so-called "overload hack" (i.e. having different-length implicit parameter lists that are always satisfied) allows this for cases of 1+ type parameter. However, this does not allow for a version with a zero-length type parameter list to coexist with the rest. More precisely, though you can define such a method, you cannot call it (or at least not with the regular syntax).

```scala
object O {
  def foo(x: Int) = x
  def foo[A: TypeTag](x: Int) = x + 1
  def foo[A: TypeTag, B: TypeTag](x: Int) = x + 2
}

object P {
  def bar {
    println(O.foo[Int, String](3)) // works
    println(O.foo[Int](2)) // works
    println(O.foo(1)) // error: ambiguous

  }
}
```

This happens because the typer is willing to let O.foo(1) become O.foo[Nothing](1) or O.foo[Nothing, Nothing](1). Furthermore, it does not prefer the version that the user actually wrote over the ones that it infers they may have meant. For this reason, I propose we add an extra rule for overload resolution: in cases where it would otherwise be ambiguous which method was selected, pick the one with a zero-length type parameter list. Because it only comes into play in cases where ambiguity exists (i.e. code that doesn't compile now), it shouldn't break anything.

See also: https://github.com/clhodapp/scala/commit/a28e9ef90321344a1545efeb3ec5944e546f6ee9

**Comment by SethTisue** [comment]
out of scope for Scala 2

**Comment by som-snytt** [comment]
The missing syntax is `f[](42)`.
