### ISSUE TITLE
dedicated build with GenASM emitting 1.7 classfiles

### ISSUE THREAD

**Issue by scabug** [scala/bug#5836]
Now that #5805 has been fixed it's possible to bootstrap with GenASM emitting 1.6 classfiles. Perhaps the time has come for a dedicated (nightly) build to test that functionality. 

The following minimum changes in build.xml do the trick, and also make sure the new JVM verifier is used:

```
  <property name="scalac.args" value="-target:jvm-1.6"/>

  <property name="env.ANT_OPTS" value="-Xms1536M -Xmx1536M -Xss1M -XX:MaxPermSize=192M -XX:+UseParallelGC -XX:-FailOverToOldVerifier -XX:+UseSplitVerifier -Xverify:all" />
```

The `-Xverify:all` above also serves as early warning about invalid bytecode that might have escaped testing (whether GenASM's fault or not).

It's also conceivable to have a (nightly?) build with -target:jvm-1.5-asm

TODO for @magarciaEPFL: GenASM can run faster under `-target:jvm-1.5-asm` by skipping the update of `reverseJavaName` (whose contents are needed only for 1.6 and up).

**Comment by SethTisue** [comment]
obsolete, 2.12 has the new back end
