### ISSUE TITLE
Inlined code shouldn't forget null-check on the original receiver

### ISSUE THREAD

**Issue by scabug** [scala/bug#5850]
Running the program below should result in NPE, however under `-optimize` the `println` statement is executed.

```
object Test {
  def main(args: Array[String]): Unit = {
    val r: C = null;
    r.callee()
  }
}

final class C {
  @inline final def callee() { println("callee's body has run.") }
}
```

@VladUreche, watch out for a similar situation when rewriting tail calls.

**Comment by SethTisue** [comment]
the println doesn't run in 2.12
