### ISSUE TITLE
inconsistent printing of types

### ISSUE THREAD

**Issue by scabug** [scala/bug#5941]
In my opinion some types have an inconsistent implementation of toString. Some types return only their short names. `scala.Product` for example returns "Product" instead of "scala.Product". 

```scala
scala> u.typeOf[scala.Product] 
res31: reflect.runtime.universe.Type = Product // wrong? 

scala> u.typeOf[java.lang.Object] 
res32: reflect.runtime.universe.Type = Object  // wrong? 

scala> u.typeOf[scala.Function1[_,_]] 
res33: reflect.runtime.universe.Type = scala.Function1[_, _] // correct? 
```

**Comment by retronym** [comment]
WIP: https://github.com/scala/scala/compare/2.13.x...retronym:ticket/5941?expand=1

This blocks scala/scala-partest#75, so I'm going to try to get a fix into 2.13
