### ISSUE TITLE
typer problem in scala virtualized

### ISSUE THREAD

**Issue by scabug** [scala/bug#5964]
Trying to compile LMS with virtualized M4. The branch in question is here:
https://github.com/Stivo/virtualization-lms-core/branches/delite-develop-m4

The stack trace of the compiler is at the very end of the file.

**Comment by hrhino** [comment]
Closing as Virtualized Scala is no longer part of the main repository (see scala/scala#5748).

**Comment by soronpo** [comment]
This issue was moved to scala-virtualized/scala#2
