### ISSUE TITLE
scala script runner can't find local package

### ISSUE THREAD

**Issue by scabug** [scala/bug#5978]
[~/Dropbox/AtomicScala/code]$ scala -version
Scala code runner version 2.9.2 -- Copyright 2002-2011, LAMP/EPFL

--> When script is run from command line, it can't find the package

[~/Dropbox/AtomicScala/code]$ scala Brevity6.scala 
/Users/bruceeckel/Dropbox/atomicscala/code/Brevity6.scala:2: error: object atomicscala is not a member of package com
import com.atomicscala.AtomicTest._
           ^
one error found

--> When imported to REPL it finds it.

[~/Dropbox/AtomicScala/code]$ scala
Welcome to Scala version 2.9.2 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_33).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :load Brevity6.scala
Loading Brevity6.scala...
import com.atomicscala.AtomicTest._
filterWithYield2: (v: Vector[Int])scala.collection.immutable.Vector[Int]
v: scala.collection.immutable.Vector[Int] = Vector(1, 2, 3, 5, 6, 7, 8, 10, 13, 14, 17)
Vector(1, 3, 5, 7)

Further Notes: Sometimes this problem can be temporarily fixed by rebooting, but eventually it reappears. Sometimes it can also be temporarily fixed by killing all the scala and java background processes that the interpreter starts, but again it reappears. This problem has been seen as far back as 2.8.

**Comment by som-snytt** [comment]
`-nc` became the default in 2.13.
