### ISSUE TITLE
Type.baseClasses name is misleading

### ISSUE THREAD

**Issue by scabug** [scala/bug#6002]
A simple execution of `baseClasses` indicates it return things that are not classes:

```scala
scala> reflect.runtime.universe.typeOf[String].baseClasses foreach println
class String
trait CharSequence
trait Comparable
trait Serializable
class Object
class Any
```

(as a side note, I'd rather it returned `AnyRef` than `Object`)

I understand that, since the return type is {List[Symbol]}, calling it `baseTypes` would be misleading, but `Symbol` is not a `Class` either, and `trait` is definitely something I wouldn't expect to be listed on a method called `baseClasses`.

**Comment by som-snytt** [comment]
Not only does 5.4 Traits begin: "A trait is a class...", but it adds: "Assume a trait D defines some aspect of an instance x of type C (i.e. D is a base class of C)." The nomenclature is not accidental.

Closing because open tickets make search results longer.
