### ISSUE TITLE
String interpolation needs name independence

### ISSUE THREAD

**Issue by scabug** [scala/bug#6010]
There is no way to define a string interpolation template separately from the interpolation, nor to compose multiple templates.  [Thread.](https://groups.google.com/group/scala-sips/browse_thread/thread/de7ea273874bb1d) It was suggested by Miles that
```
It'd be nice if we could get that back and write something like,

 // Inferred type should be Int => String
final val template = s"""This is string $(_:Int)."""

Then all of your examples boil down to function application and/or composition.
```
to which eugene said "Could you submit an enhancement request for that please?", a request which I am presently fielding.

**Comment by SethTisue** [comment]
interesting. could be revived as a discussion on https://contributors.scala-lang.org

**Comment by milessabin** [comment]
Leaving a pointer to [this gist](https://gist.github.com/milessabin/a69d8ffbfe9f42e65fbf) here as a reminder that we once more or less had what's being requested here.
