### ISSUE TITLE
Scaladoc: Use cases are incorrect. They should be generated automatically, by resolving the implicit members

### ISSUE THREAD

**Issue by scabug** [scala/bug#6071]
Use cases as they are implemented now are a major pain -- they don't play well with the other components in scaladoc and with all the effort we still don't get the right signatures. Thus, it should be automated -- resolve implicit parameters automatically, use the type mapping on the signature and eliminate the implicit params and use that as the usecase.

No chance to see this going into 2.10, sorry.

**Comment by SethTisue** [comment]
There have been a number of other tickets in the area of "with all the effort we still don't get the right signatures". This is now the single ticket of record on that, but anyone interested in the whole picture will want explore linked tickets.

**Comment by SethTisue** [comment]
#8887, especially, is closely related

**Comment by SethTisue** [comment]
as per https://github.com/scala/scala-dev/issues/584, 
https://github.com/scala/scala/pull/7462 deprecates `@usecase` and removes all usages of it from scala/scala, "solving" the problem for 2.13
