### ISSUE TITLE
JavaMirrors are prone to thrashing

### ISSUE THREAD

**Issue by scabug** [scala/bug#6137]
[Recent commit](https://github.com/scala/scala/commit/2eff6601dac2b19c3898e46999b0ab1523ff0c0c) has made TwoWayCache two-way weak, but [apparently](http://groups.google.com/group/scala-internals/browse_thread/thread/b2cdabbe3f6e901a) java reflection artifacts are quite aggressively garbage collected. This means that we need a different caching policy, or we'll be facing thrashing problems.

**Comment by SethTisue** [comment]
closing old reflection tickets that seem unlikely to receive attention
