### ISSUE TITLE
dead case field accessor call should be eliminated

### ISSUE THREAD

**Issue by scabug** [scala/bug#6193]
while refining my fix for #5739, I discovered case field accessors are not considered pure -- or so it seems...

shouldn't the body of `emptyMethod` be completely empty when compiled with -optimize?

```scala
case class Foo(bla: Int, blaa: String)

class Test {
  val f = Foo(1, "1")
  // when compiled with -optimize, this method's body should be empty
  // however, both calls to the accessors survive (though they are not stored in local variables)
  def emptyMethod = {
    val x = f.bla // should be considered pure and be eliminated
    val y = f.blaa
  }
}
```

**Comment by SethTisue** [comment]
@lrytz still relevant?

**Comment by lrytz** [comment]
The optimizer doesn't see through getters, so it doesn't eliminate accessor calls. But I don't think this ticket is a fit for scala/bug
