### ISSUE TITLE
_root_ should always refer to the root package

### ISSUE THREAD

**Issue by scabug** [scala/bug#6217]
I see no reason this should be allowed to happen, and a lot of reasons it shouldn't.
```scala
package foo
package _root_

object Test {
  import _root_.scala.Option
}
```
```
./a.scala:5: error: object scala is not a member of package foo._root_
  import _root_.scala.Option
                ^
one error found
```
So to be clear, that source should not compile, but it should not compile because *root* should be a reserved word.  The whole point of *root* is to know what you are importing.  Tying this into another ticket I opened recently:

```scala
// a.scala
package foo

import _root_.scala.Option

% scalac3 ./a.scala 
% mkdir -p foo/_root_
% scalac3 ./a.scala 
./a.scala:3: error: object scala is not a member of package foo._root_
import _root_.scala.Option
              ^
one error found
```

**Comment by SethTisue** [comment]
@jvican has taken an interest in this recently

**Comment by jvican** [comment]
Yes. Making `_root_` a keyword is the way to fix this issue IMO, since the word is already a standard. I'll put up a SIP about it.

**Comment by som-snytt** [comment]
The PR just enforces that `import _root_.blah.blah` means the root package always, and warns if there is a badly named symbol in scope.

Hopefully this averts enshrining `_root_` as a keyword. Because then it would sit in the front of the spec and we'd have to look at it all the time. As it is, the homely identifier can sit in the back with other miscellany, not quite as forgotten as the chapter on XML syntax, but willing on occasion to step out and perform a humble duty when needed, before returning to that quiet if lonely place under the jeers of onlookers.

**Comment by mkeskells** [comment]
Is there any reason that a package should *ever* be named `_root_`?
It seems to me that special semantics at the start of the import statement is the wrong way to go, and to do so should be illegal
i.e. 
`import _root_.foo` is always foo in the root package
`import a._root_.foo` should not compile
`package _root_` should not compile

**Comment by mkeskells** [comment]
@jvican I didn't know about that - looks good
@som-snytt - to clarify - (I hadn't realised that there was additional special casing on the special casing!) 
`import _root_.foo.bar` is always bar in the foo package
`import a._root_.foo` should not compile
`package _root_` should not compile

I wonder what havoc `val _root_ : Int = 0` would have
or `def _root_ : String`
or type aliases and generic parameters
…

Instead lets make the root, in whatever form **not a legal identifier**!

**Comment by som-snytt** [comment]
To summarize the compromise, _root_ is a soft keyword as lead element of a qualifier; a warning is emitted if it "shadows" an ordinary _root_ in scope. That covers the use case and the gotcha. Any further tightening of screws could be taken to the SIP committee.
