### ISSUE TITLE
Make internal implementation classes in scala.collections private

### ISSUE THREAD

**Issue by scabug** [scala/bug#6224]
There are several classes in scala.collection.immutable which are clearly implementation classes that should not be publicly accessible. Those include:

scala.collection.immutable.HashSet
  HashSet1  
  HashTrieSet

scala.collection.immutable.HashMap
  HashMap1  
  HashTrieMap

HashMap and HashSet should also be a sealed trait or at least have a private[immutable] constructor to prevent people from inheriting from these classes, since doing so makes no sense.

HashTrieMap is not even self-contained, but depends on its position in the hierarchy for the level. If you take a HashTrieSet from deep in a large tree and try to use it as a standalone HashSet, all hell will break loose, because the level (assumed 0 for a top-level HashTrieSet) will be inconsistent with the sorting of the entries.

In several places inside the algorithms it is assumed that a HashSet can be either a HashSet1, HashSetCollision1, HashTrieSet or empty. So making this a sealed trait would be optimal.

**Comment by SethTisue** [comment]
https://github.com/scala/collection-strawman/issues/419 aims to address this for 2.13

**Comment by szeiger** [comment]
This was addressed by the new CHAMP-based implementations in 2.13.0-M5.
