### ISSUE TITLE
ICodeReader should parse exception handlers from bytecode

### ISSUE THREAD

**Issue by scabug** [scala/bug#6228]
Candidate fix:
  https://github.com/magarciaEPFL/scala/tree/icodereader-gets-exception-handlers-2

Core functionality OK, only an interplay around error messages (affecting two tests) remains.

See also https://github.com/scala/scala/pull/1127

**Comment by SethTisue** [comment]
closing stale old backend tickets, since the backend was completely replaced in Scala 2.12. reopen if you can show this is still relevant
