### ISSUE TITLE
Use consumedTypes/producedTypes in TypeFlowAnalysis and ICodeCheckers

### ISSUE THREAD

**Issue by scabug** [scala/bug#6234]
The consumedTypes/producedTypes for icode instructions are redundantly defined in 3 separate places:
 - Opcodes.scala (consumedTypes/producedTypes)
 - ICodeCheckers.scala (for checking icode)
 - TypeFlowAnalysis.scala (for computing types on the stack at each
program point)

Since the Opcodes types are the only ones visible outside, I suggest
we use them in ICodeCheckers.scala and TypeFlowAnalysis.scala too. But
we should make such changes after the release, after chilling out
by the lake with a glass of good wine for a couple of days.

A relevant discussion on this can be found at:
https://groups.google.com/forum/?fromgroups#!topic/scala-internals/qcyTjk8euUI[1-25]

**Comment by SethTisue** [comment]
likely no longer applicable
