### ISSUE TITLE
Text encoding issues with default settings

### ISSUE THREAD

**Issue by scabug** [scala/bug#6407]
While in a perfect world “Unicode/UTF-8 everywhere” would be a sensible standard, Scala has to work well with existing code.

Because of that, text encoding/input/output is done in Unicode where possible and in the underlying platform's encoding where necessary (due to Java's heritage).

Despite that, there are several places in the standard library where a third way has been chosen: Defaulting to some outdated encodings of the ISO-8859-X family.

This should be fixed.

**Comment by SethTisue** [comment]
For the record: it appears to me that the bug part of this already got fixed at some point, and scala/scala#10004 is just an internal refactoring (with one trivial exception in `writeChromeTrace`).

**Comment by SethTisue** [comment]
> [https://github.com/scala/scala/blob/2.13.x/src/library/scala/io/Source.scala#L119](https://github.com/scala/scala/blob/2.13.x/src/library/scala/io/Source.scala?rgh-link-date=2022-04-19T16%3A07%3A03Z#L119)

😱

**Comment by som-snytt** [comment]
Too bad April is almost over. At the beginning of the month, they ought to have announced the deprecation of Scala 2 in its entirety. Deprecation messages would continue to be emitted in Scala 3 under `-source:migration-3.0`.

**Comment by SethTisue** [comment]
Honestly I think fixing `io.Source` would be fair game, even in a point release.
