### ISSUE TITLE
[scala-language] [2.10 reflection] Oddity in the toolbox interface

### ISSUE THREAD

**Issue by scabug** [scala/bug#6433]
The below REPL interaction is unidiomatic. The "problem" is that ToolBox is an implicit conversion and a type.
```scala
import scala.reflect.runtime.{universe => ru}
import scala.reflect.runtime.{currentMirror=>cm}
import scala.reflect.runtime.universe._

scala> val toolbox = cm.mkToolBox()
<console>:28: error: value mkToolBox is not a member of reflect.runtime.universe.Mirror
         val toolbox = cm.mkToolBox()
                          ^

scala> import scala.tools.reflect.ToolBox
import scala.tools.reflect.ToolBox

scala>   val toolbox = cm.mkToolBox()
toolbox: scala.tools.reflect.ToolBox[reflect.runtime.universe.type] = scala.tools.reflect.ToolBoxFactory$ToolBoxImpl@5b51c408
```
In a discussion on scala-language, Paul Phillips mentioned that the same applies to Eval and Eugene asked for this issue.
Moreover, Paul Phillips also pointed out that this idiom might now become idiomatic. Hence I've added this comment:
https://issues.scala-lang.org/browse/SI-6400?focusedCommentId=60199#comment-60199

Link to the email discussion:
https://groups.google.com/forum/?fromgroups=#!topic/scala-language/Z0Kd0jecRFE

**Comment by SethTisue** [comment]
stale ticket. let's keep scala/bug focused on bugs. anyway scala.reflect rarely changes anymore
