### ISSUE TITLE
ObservableBuffer Update message is not usable

### ISSUE THREAD

**Issue by scabug** [scala/bug#6454]
The update method updates the collection and after that it sends an `Update` message containing the new element. In my subscriber I want to get the old element so that I can handle it's removal.

In theory I could use `undo` to trigger an `Update` event for the old element, then `undo` again to set the new element back. As you can see that would get messy very quickly.

I can not think of a proposal that would not (potentially) break existing code.

**Comment by SethTisue** [comment]
`ObservableBuffer` no longer exists in 2.13
