### ISSUE TITLE
Macro cleanup: avoid having unsigma implemented as a type map

### ISSUE THREAD

**Issue by scabug** [scala/bug#6480]
Details provided here: https://github.com/scala/scala/pull/1421

**Comment by SethTisue** [comment]
scala/scala#1421 was merged by still has `object SigmaTypeMap extends TypeMap`, so I don't get what this was about, but in any case it seems unlikely that the ticket still has value. I'll err on the side of "close as fixed"

**Comment by som-snytt** [comment]
The Paulpism:

> It really pays not to write new TypeMaps unless it is absolutely necessary, because there are about 1000 ways to get them wrong. I'm 98% sure this one can be dropped.

If there are 1000 possible errors and 2% chance that it's required, then what is the probability that it is broken a decade later?
