### ISSUE TITLE
Allow named and default arguments in pattern matching

### ISSUE THREAD

**Issue by scabug** [scala/bug#6524]
Named and default arguments have been introduced in Scala 2.8, and were outlined in [SIP #1](https://docs.scala-lang.org/sips/named-and-default-arguments.html). An important scenario has been overlooked in the SIP, which is to define interaction of named and default arguments with pattern matching cases. Adding support for named arguments in pattern matching improves Scala in two ways:

(1) It increases the regularity of the language in the sense that a feature (named arguments) is applicable to more scenarios, and case class constructor calls and pattern cases are more symmetrical
(2) It brings the benefits of named arguments to a widely used feature of Scala (pattern matching): Avoiding boiler plate, and avoiding mistakes when multiple arguments of the extractor have the same type.

Example:

```scala
    case class Advance(time: Long, isSeek: Boolean, isPlaying: Boolean, added: List[Any] = Nil, removed: List[Any] = Nil)
```

An instance of this class can be conveniently created such as this:

```scala
    Advance(time=0L, isSeek=false, isPlaying=true)
```

But a pattern match is only possible like this:

```scala
    def update(u: Any) = u match {
      case Advance(time, isSeek, isPlaying, added, removed) => ...
    }
```

With a real trap like the following:

```scala
    def update(u: Any) = u match {
      case Advance(time, isPlaying, isSeek, removed, added) => ...
    }
```

Or even this, if not all arguments are used and therefore undergoing successive type checks:

```scala
    def update(u: Any) = u match {
      case Advance(isSeek, isPlaying, time, _, _) => ...
    }
```

Cf. [here](https://github.com/Sciss/SoundProcesses3/commit/fd8234992e30fd79ce309c09303af5b42e62d93e#commitcomment-1997303)

If named arguments were allowed, the following would be valid:

```scala
    def update(u: Any) = u match {
      case Advance(time = t, isSeek = false, isPlaying = true, removed = r, added = a) => ...
    }
```

Furthermore, if a "default" argument in an extractor is equated with `_`, the following would be valid:

```scala
    def update(u: Any) = u match {
      case Advance(isPlaying = true) => ...
    }
```

...and equivalent to...

```scala
    def update(u: Any) = u match {
      case Advance(time = _, isSeek = _, isPlaying = true, removed = _, added = _) => ...
    }
```

Cutting boiler plate in pattern match cases and make them more readable.

A problem I can see is where arguments are omitted but no named arguments used, such as:

```scala
    def update(u: Any) = u match {
      case Advance(time, isSeek) => ...
    }
```

In the constructor case this would be only legal if default arguments were given for `isPlaying`, `added` and `removed`, whereas in the deconstruction/extractor case it would be always legal if a default of `_` is implied for each argument. Perhaps a compromise would be to allow default arguments only where named arguments are used?

**Comment by lwouis** [comment]
What's the status of this feature?

**Comment by adriaanm** [comment]
We currently have no plans to implement this. Since this involves a language change, it would require a [SIP](https://docs.scala-lang.org/sips/sip-submission.html).

**Comment by SethTisue** [comment]
This would be a great project for somebody who wants to tackle something a bit more ambitious.

**Comment by dwijnand** [comment]
> @Sciss said:
> For referecne, here is the [scala-debate thread](http://grokbase.com/t/gg/scala-debate/12ad0n33b0/default-and-named-arguments-in-extractors). There are some valid points against this, particularly when custom extractors are used, there is no defined naming for the "arguments" (because they are the elements of the return tuple).

I haven't read the thread yet, but since 2013 two relevant things have happened:
1. Scala 3 extended custom extractors to return `Product` ("Product Match" in https://dotty.epfl.ch/docs/reference/changed-features/pattern-matching.html); and
2. we've added `productElementNames` to Product

So I think this might no longer be a blocker.

**Comment by SethTisue** [comment]
This is under discussion at https://contributors.scala-lang.org/t/pattern-matching-with-named-fields/1829

**Comment by dwijnand** [comment]
> For reference, here is the [scala-debate thread](https://groups.google.com/g/scala-debate/c/J08bI3gFzzo/m/soFPoOqQV00J).

New link (though behind http-use warning): https://grokbase.com/t/gg/scala-debate/12ad0n33b0/default-and-named-arguments-in-extractors

**Comment by SethTisue** [comment]
closing as out of scope for Scala 2 (as the Scala 3 implementation ending up depending on named tuples, and backporting that is out of scope)

**Comment by SethTisue** [comment]
but in Scala 3, as of Scala 3.5.0 there is experimental support:

```scala
Welcome to Scala 3.5.0
                                                                                                    
scala> import language.experimental.namedTuples
                                                                                                    
scala> case class Person(name: String, age: Int)
// defined case class Person
                                                                                                    
scala> Person("Alice", 52) match
     |   case Person(age = age) => age
     | 
val res0: Int = 52
```

see https://www.scala-lang.org/blog/2024/08/22/scala-3.5.0-released.html

**Comment by SethTisue** [comment]
adding the "fixed in Scala 3" despite this being experimental, as it seems highly likely to make it out of experimental
