### ISSUE TITLE
Avoid loop in getClassParts

### ISSUE THREAD

**Issue by scabug** [scala/bug#6528]
Here is the code that was being compiled: https://github.com/barneyii/zutha-lib/tree/master/src/main/scala/net/zutha/lib/collection

I tried to compile with scala 2.9.2 and that pretended to succeed when I compiled in Intellij Idea but it actually didn't finish. When I compiled with 2.9.2 using SBT it failed with a StackOverflowError.

I then tried compiling with Scala 2.10.0 M7 (later changed back to M4 with no effect) and received this error message: https://github.com/barneyii/zutha-lib/blob/master/compile-errors.txt

**Comment by SethTisue** [comment]
closing for staleness. comment/reopen if you can verify it still happens in current Scala.

**Comment by milessabin** [comment]
This is fixed, possibly as a consequence of https://github.com/scala/scala/pull/6010. I've PR a test confirming this here: https://github.com/scala/scala/pull/6367.
