### ISSUE TITLE
for macros: need something like Tree.toString that outputs originally formatted source code

### ISSUE THREAD

**Issue by scabug** [scala/bug#6540]
I needed macro assertx(x == 0) which expands to assert(x == 0, "x == 0"), but currently Tree.toString gives me "x.==(0)". 

Discussion was here: https://groups.google.com/forum/#!topic/scala-user/UoEeXL2dC4Q , you answered: "Currently we have `show` and `showRaw`. Maybe we could add an additional prettyprinter or introduce a parameters for the `show` method. "

// (Could not change issue Priority from Blocker to Minor, select box looks disabled.)

**Comment by SethTisue** [comment]
closing stale enhancement tickets, especially in dormant areas such as scala.reflect. could be revived on https://contributors.scala-lang.org

**Comment by SethTisue** [comment]
the "originally formatted source code" is probably impossible without Scala.meta anyway
