### ISSUE TITLE
DynamicVariable should support for-comprehensions

### ISSUE THREAD

**Issue by scabug** [scala/bug#6620]
More specifically, `withValue` should have an equivalent that returns an object with a `foreach`. Right now, clients have to do:

```scala
dynvar1.withValue(x) {
  dynvar2.withValue(y) {
    dynvar3.withValue(z) {
      // do something
    }
  }
}
```

This is cumbersome and hard to read and maintain when a new dynamic variable is to be added to this stack. Instead, it would be nice if they were able to do:

```scala
for {
  x <- dynvar1.using(x)
  y <- dynvar2.using(y)
  z <- dynvar3.using(z)
} {
  // do something
}
```

modulo the name for the projection method `using`.

**Comment by SethTisue** [comment]
this looks like a nice idea, offhand, but I'm going to close it since we're trying to keep scala/bug focused on bugs. perhaps a PR on this would be accepted
