### ISSUE TITLE
Compiler is confused by multiple apply()(implicit) if in the same statement

### ISSUE THREAD

**Issue by scabug** [scala/bug#6630]
Compiler does not reevaluate `apply`'s `implicit` each time `apply` is called, when the applications are in the same statement.

The compiler would be correct if `test` were a function, and the `implicit` was defined at the function definition site. In that case the `implicit` is only supposed to be evaluated in the first application to a function, where the type parameters are then fully determined.

However, this is not the case below, because the `implicit` is declared not for the function `test` but for the application function `apply`, and thus the type parameter `A` should be determined separately for each invocation of `apply`. It is proven as shown below by the fact that invoking `apply` with separate statements or even explicitly calling `.apply` more than once in the same statement does compile as expected.

The [motivating use case is for a workaround](https://issues.scala-lang.org/browse/SI-5550?focusedCommentId=60794&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-60794) to a use case that applies to [bug SI-5550](https://issues.scala-lang.org/browse/SI-5550).

```scala
class Test {
  def apply[A](v: A)(implicit d: A <:< Any) = this
}
val test = new Test

scala> test(1)
res0: Test = Test@a541e5

scala> test("")
res1: Test = Test@a541e5

scala> test(1).apply("")
res2: Test = Test@105f21c

scala> test(1)("")
error: type mismatch;
 found   : java.lang.String("")
 required: <:<[Int,Any]
       test(1)("")
               ^
```

**Comment by som-snytt** [comment]
Explicit `using` fixes the syntax, and it will also start asking for `using` for explicit implicit args.
