### ISSUE TITLE
REPL: load transitive dependencies of JARs on classpath

### ISSUE THREAD

**Issue by scabug** [scala/bug#6660]
The Scala REPL should load dependencies referenced in MANIFEST.MF files of other JARs on the classpath.

As described in https://support.typesafe.com/tickets/1585:

```
We have JAR files that contain standard META-INF/MANIFEST.MF files with the Class-Path: entry. This entry points to a number of other JARs that should be loaded transitively by the ClassLoader. Unfortunately the REPL does not load these transitive dependencies, instead dependency JARs need to be placed on the classpath explicitly one by one.

As an example let's say I have A.jar and B.jar. I also have a C.jar that has nothing else in it than a MANIFEST.MF with 'Class-Path: A.jar B.jar'. If I use

> scala -classpath A.jar;B.jar

everything is ok. I can e.g import A and import B. However, if I use

> scala -classpath C.jar

I couldn't import or use any classes from A.jar or B.jar.
```

**Comment by SethTisue** [comment]
I wonder how the Dotty REPL does on this

**Comment by lrytz** [comment]
From outside the repl, it can be done with coursier (https://github.com/dwijnand/scala-runners/issues/3), so there's some overlap here with the work discussed at https://github.com/scala/scala-dev/issues/326.

**Comment by som-snytt** [comment]
I thought this is what `--use-manifest-class-path` was for, but I guess not?

```
➜  t6660-run.obj git:(issue/6660-manifest-cp) ✗ scala --class-path y.jar:x.jar
Welcome to Scala 2.13.10 (OpenJDK 64-Bit Server VM, Java 19).
Type in expressions for evaluation. Or try :help.

scala> class C extends Y
class C

scala>
:quit
➜  t6660-run.obj git:(issue/6660-manifest-cp) ✗ scala --class-path y.jar --use-manifest-class-path
Welcome to Scala 2.13.10 (OpenJDK 64-Bit Server VM, Java 19).
Type in expressions for evaluation. Or try :help.

scala> class C extends Y
       ^
       error: Symbol 'type <empty>.X' is missing from the classpath.
       This symbol is required by 'method Y.x'.
       Make sure that type X is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
       A full rebuild may help if 'Y.class' was compiled against an incompatible version of <empty>.

scala>
:quit
```
Same result with `scalac`.

**Comment by som-snytt** [comment]
`-nobootcp -toolcp y.jar --use-manifest-class-path`
shows
```
  ZipArchiveClassPath(/home/amarki/projects/scala/build/pack/lib/scala-repl-frontend.jar,None)
  ZipArchiveClassPath(y.jar,None)
  DirectoryClassPath(.)
[snip]
  ManifestResourcesClassPath(file:/home/amarki/projects/scala/build/pack/lib/scala-repl-frontend.jar)
  ManifestResourcesClassPath(file:/home/amarki/projects/scala/test/files/run/t6660-run.obj/y.jar)
  ManifestResourcesClassPath(file:/home/amarki/projects/scala/test/files/run/t6660-run.obj/x.jar)
```
and both jars at end of `[search path for class files:`. (But not a successful compile yet.)

**Comment by som-snytt** [comment]
oh there is a fat comment
```
   * with a particularly prepared scala-library.jar. It should have all classes listed in the manifest like e.g. this entry:
   * Name: scala/Function2$mcFJD$sp.class
```
I'm not entirely sure why that is useful, as opposed to exposing the contents of the jar file. Who has a home chef to specially prepare anything?

**Comment by SethTisue** [comment]
this is now scala-cli's job

**Comment by SethTisue** [comment]
@som-snytt if you're planning something, I think Scala 3 is the appropriate first venue — though we could discuss...

**Comment by som-snytt** [comment]
@SethTisue this is why I looking at that class path stuff! The tweak to `expandManifestPath` showed the `JarRunner` only uses the class-path from the first ("main") jar, but not recursively and not for other jars on the class path. Too bad the 10-year statute of limitations has already run out on this ticket.

The use case, per the OP, is that it simplifies running local jars. `scala foo.jar` without a script to set the class path, etc. That can be nice on servers, where there is no desire to download anything from anywhere.
