### ISSUE TITLE
Tab completion for constructors in REPL

### ISSUE THREAD

**Issue by scabug** [scala/bug#6705]
Many classes - specially java ones - have multiple  constructors, which you cannot request the repl to assist you with completion, forcing you to check on its documentation to see your possibilities.

On top of it, it's an inconsistency with method completion.

**Comment by som-snytt** [comment]
Fixed by https://github.com/scala/scala/pull/7833 since 2.12.9

**Comment by Jasper-M** [comment]
To be continued at #11846.
