### ISSUE TITLE
local method invoked from closure body crashes -Ycheck:all

### ISSUE THREAD

**Issue by scabug** [scala/bug#6727]
The program below is inspired by `files/pos/z1730.scala`

```
class X[R] {

  def xx(value: () => R) = 0

  def goo2  = (new X[Int]).xx(

    {
       def poorMansMH1(): Int = 34

       @SerialVersionUID(0)
       final class AF
       extends scala.runtime.AbstractFunction0[Int]
       with Serializable {
         def apply(): Int = poorMansMH1()
       }

       new AF()
     }

  )

}
```

The program typechecks but crashes the compiler with `-Ycheck:all`

Leaving everthing as above but changing `def apply() = 34` (ie the local method "poorMansMH1" isn't invoked anywhere) compiles fine, also under `-Ycheck:all`

**Comment by SethTisue** [comment]
I'm not able to reproduce the crash under 2.12.4
