### ISSUE TITLE
Support static inheritance in Java files

### ISSUE THREAD

**Issue by scabug** [scala/bug#6735]
When parsing Java files, scalac doesn't support inheritance of statics.  For example, the following valid Java code produces a compilation error:

```java
// Foo.java
public class Foo {
  public static class Bar {}
}
```

```java
// FooBar.java
public class FooBar extends Foo {
  public Bar bar = new Bar();
}
```

**Comment by SethTisue** [comment]
I'm not able to reproduce the problem on any Scala version, not even 2.7/2.8/2.9

Based on Paul's comment, closing

**Comment by som-snytt** [comment]
Fixed by https://github.com/scala/scala/pull/7738

To test, a trivial usage
```
➜  t6735 cat barrister.scala

object Test extends App {
  println {
    new FooBar().bar
  }
}
```
Then scalac mixed
```
Using scala version 2.12.8 in this shell.
➜  t6735 scalac -d target *a
FooBar.java:3: error: not found: type Bar
        public Bar bar = new Bar();
               ^
one error found
```
