### ISSUE TITLE
Macro engine shouldn't catch fatal exceptions

### ISSUE THREAD

**Issue by scabug** [scala/bug#6748]
Problematic code: https://github.com/scala/scala/blob/6858d9a2fffd7e85144e16a5e636c2b1c95c2b3a/src/compiler/scala/tools/nsc/typechecker/Macros.scala#L783

Explanation of why it's problematic: https://github.com/scala/scala/pull/1686#issuecomment-10927638

**Comment by SethTisue** [comment]
fixed by https://github.com/scala/scala/pull/6344, I think?
