### ISSUE TITLE
Reusing a compiler instance with -Yinline causes an inconsistent state

### ISSUE THREAD

**Issue by scabug** [scala/bug#6782]
If the REPL or fsc is used with -Yinline then we end up in a state where two symbols represent the same thing and the second version isn't initialized where it's expected.  This is the root cause for the linked bugs which have more discussion on the subject.

Undoing the fix for #SI-5789 creates a simple reproducer. The test associated with that fix will cause an assertion in Mixin.scala.

**Comment by som-snytt** [comment]
The simple reproducer was lost to new traits in 2.12.
