### ISSUE TITLE
Add @since, a dual of @deprecated

### ISSUE THREAD

**Issue by scabug** [scala/bug#6802]
Add an annotation for classes/methods that signal that the annotated entity has been introduced in a minor release of Scala, and as such should not be relied on by a library that is using "2.10" as the Scala Binary Version (in SBT parlance.)

This will allow library authors to use newer compiler versions (for bug fixes, speedups, etc), without rendering their libraries unusable for users still on a previous minor release of Scala.

Include the 'Since' version in the annotation.

Raise a compiler warning if these methods are called without a compiler flag.

Indicate such methods in Scaladoc.

Update MIMA to check that we have been comprehensive in our use of the annotation in the standard library. Given the MIMA is bytecode based, we might consider making this new annotation a Java annotation with runtime retention.

Document the annotation on docs.scala-lang.org and publicise via mailing lists for Scala, SBT and other build tools.

Educate committers / reviewers about the correct use of the annotation.

Ensure that the annotations are removed and/or ignored by the warning after the next major version.

Consider overlap with the @since doc tag in Scaladoc.

**Comment by kzys** [comment]
Sorry. I messed up the milestone field accidentally.

**Comment by adriaanm** [comment]
:-) no problem

**Comment by SethTisue** [comment]
@lrytz do you see some fresh life for this idea in the context of SIP-51? (Like when we add methods that are known to break bincompat, should we put some marker like this on them?)

**Comment by som-snytt** [comment]
@SethTisue that would be a case of "The Since of the Father".

**Comment by lrytz** [comment]
Like, a technical solution to allow using compiler 2.13.17 but target 2.13.16 bin compat? Intuitively, I don't think we should do that.

**Comment by SethTisue** [comment]
Yeah... I'm not sure I had a coherent thought, here.

**Comment by som-snytt** [comment]
The pun is on "since" and "sins". It sounds even better with a slight accent. Just to settle that before closing the ticket. Is there any greater sin than breaking bincompat? The rainbow after Noah's flood was a covenant never to break bincompat again.
