### ISSUE TITLE
Too many HashEntry and DefaultEntry instances for each HashMap entry

### ISSUE THREAD

**Issue by scabug** [scala/bug#6825]
Size of mutable HashEntry, DefaultEntry, HashMap types are taking up unexpectedly large amounts of heap space.  Users on platforms with limited resources can't use these collections so long as they create so many instances for each entry.

**Comment by SethTisue** [comment]
what's the status on this in the 2.13 collections?

**Comment by szeiger** [comment]
We have a completely new `HashMap` in 2.13. We also had `AnyRefMap` for quite a while. It is based on open addressing (like the now deprecated `OpenHashMap`) so it should be a good choice for reducing heap allocations.
