### ISSUE TITLE
scala.tools.nsc.reporters.StoreReporter: `force` logic is reverted

### ISSUE THREAD

**Issue by scabug** [scala/bug#6866]
Checking for `force` parameter in scala.tools.nsc.reporters.StoreReporter is not correct
https://github.com/scala/scala/tree/v2.10.0-RC5/src/compiler/scala/tools/nsc/reporters/StoreReporter.scala#L22
there expected to be `if (force)` instead of `if (!force)`

Because of this, `echo` function does not work at all
https://github.com/scala/scala/tree/v2.10.0-RC5/src/compiler/scala/tools/nsc/reporters/Reporter.scala#L59

**Comment by SethTisue** [comment]
appears to have been fixed by https://github.com/scala/scala/pull/8338
