### ISSUE TITLE
filter out varargs star more uniformly

### ISSUE THREAD

**Issue by scabug** [scala/bug#6929]
In https://github.com/scala/scala/commit/649c2784 I modified lub not to accidentally lub its way to T* types, and included this comment:
```scala
-      existentialAbstraction(tparams, lubType)
+      // dropRepeatedParamType is a localized fix for SI-6897. We should probably
+      // integrate that transformation at a lower level in master, but lubs are
+      // the likely and maybe only spot they escape, so fixing here for 2.10.1.
+      existentialAbstraction(tparams, dropRepeatedParamType(lubType))
```

**Comment by SethTisue** [comment]
#6107 is in the same area.

@som-snytt the issue description here is vague. I'm tentatively closing on the presumption that after https://github.com/scala/scala/pull/7399, more fundamental changes in this area are unlikely in Scala 2, but we can reopen if there's dissent

**Comment by Jasper-M** [comment]
> 6107 is in the same area.

Wrong repository.
