### ISSUE TITLE
Fix parallel collection's configuration API (task support)

### ISSUE THREAD

**Issue by scabug** [scala/bug#6998]
There was a lot of debate regarding possible improvements, but it didn't make it into 2.10.

The issue basically revolves around getting rid of the mutable field in favor of an immutable approach.

Example with default configuration:

```scala
Array(1,2,3).par.map(...)
```

Current tasksupport API:

```scala
val array = Array(1,2,3).par
array.tasksupport = otherTaskSupport
array.map(...)
```

An additional issue is that this API also breaks the “flow” of operations.

The proposed improvements are along the lines of something like:

```scala
Array(1,2,3).parWith(otherTaskSupport).map(...)
```

Considering that the library has already shipped with 2.10, the current API probably needs to be deprecated before it can be removed.

Old discussion: https://groups.google.com/d/topic/scala-internals/lzxVlexkqEg/discussion

Old pull request: https://github.com/scala/scala/pull/930

**Comment by SethTisue** [comment]
please open a new ticket at https://github.com/scala/scala-parallel-collections/issues
