### ISSUE TITLE
Documentation of Context.eval not up-to-date

### ISSUE THREAD

**Issue by scabug** [scala/bug#7000]
The API documentation for scala.reflect.macros.Context.eval reads:
"... Known issues: because of #5748 trees being evaluated first need to undergo resetAllAttrs. Resetting symbols and types mutates the tree in place, therefore the conventional approach is to duplicate the tree first ..."

But according to Eugene resetAllAttrs no longer mutates the tree in place.

**Comment by Philippus** [comment]
is this issue still valid after https://github.com/scala/scala/pull/3485 ?

**Comment by eed3si9n** [comment]
I'd say it's either invalid, or won't fix. Regardless, I am going to close this for now.
