### ISSUE TITLE
misleading error when trying to instantiate AnyVal

### ISSUE THREAD

**Issue by scabug** [scala/bug#7032]
```scala
cala> new Any
<console>:30: error: class Any is abstract; cannot be instantiated
              new Any
              ^

scala> new Any{}
<console>:30: error: Any does not have a constructor
              new Any{}
                  ^

scala> new AnyVal
<console>:30: error: class AnyVal is abstract; cannot be instantiated
              new AnyVal
              ^

scala> new AnyVal{}
<console>:30: error: value class may not be a local class
              new AnyVal{}
                  ^
```

**Comment by SethTisue** [comment]
The error message could spell things out more, but I'm not sure it truly qualifies as misleading. It's a local anonymous subclass. `new AnyRef {}` is legal.

Amusingly, Scala 3 (3.3.2-RC1) gives "Value classes may not be a local class" (note the mangled grammar).

Although the error message could certainly be more explicit, we don't normally keep tickets on potentially improvable error messages open indefinitely.
