### ISSUE TITLE
Introduce ConstantAnnotation and remove ClassfileAnnotation and associated warning

### ISSUE THREAD

**Issue by scabug** [scala/bug#7041]
- remove ClassfileAnnotation (and the warning)
- introduce ConstantAnnotation do to exactly what ClassfileAnnotation does now, but without a warning
- make SerialVersionUID extend ConstantAnnotation

as discussed in https://github.com/scala/scala/pull/1924

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6143
