### ISSUE TITLE
unintentional override of a varargs method

### ISSUE THREAD

**Issue by scabug** [scala/bug#7052]
It is possible to unintentionally override a varargs method:

```scala
class A {
  def apply(xs: Int*): A = { println("called A"); this }
}

class B extends A {
  // no override keyword needed or even allowed
  def apply(xs: Seq[Int]): B = { println("called B"); this }
}

object Test {
  def main(args: Array[String]) {
    val a: A = new B
    a(1,2,3) // prints "called B"
  }
}
```

Note that the different return types are necessary, otherwise you'll get a name clash.

Also, if you mark the method in the base class as `final` it will still compile but you'll get a `VerifyError` at runtime.

**Comment by som-snytt** [comment]
Correctly rejected now, regression test in https://github.com/scala/scala/pull/9647
