### ISSUE TITLE
Scaladoc should not use strong references in maps

### ISSUE THREAD

**Issue by scabug** [scala/bug#7075]
```scala
  val cookedDocComments = mutable.HashMap[Symbol, String]()

  /** The raw doc comment map */
  val docComments = mutable.HashMap[Symbol, DocComment]()
```

in [DocComments.scala](https://github.com/scala/scala/blob/master/src/compiler/scala/tools/nsc/ast/DocComments.scala#L22).

These maps should at least be Weak (if the symbol is collected, no one would ask for its scaladoc anyway). A better solution would be to use symbol attachments (symbols get their corresponding DocComment when they are processed).

**Comment by SethTisue** [comment]
we don't generally keep open tickets for speculative possible code improvements
