### ISSUE TITLE
AbstractTypeSymbol reaches GenASM in the throws annotation of a method

### ISSUE THREAD

**Issue by scabug** [scala/bug#7122]
In `JPlainBuilder.genMethod()` the exceptions an (ICode) IMethod `m` throws are obtained via

```
  val (excs, others) = m.symbol.annotations partition (_.symbol == ThrowsClass)
```

The test added in [commit 02dd4c97](https://github.com/scala/scala/commit/02dd4c974f33d137ea353a72e27efb70928fb378) includes a source file (reproduced below)

```
class ScalaClassWithCheckedExceptions_1[E1 <: Exception] @throws[NullPointerException]("") () {
  @throws[E1]("") def bar() {}
  @throws[IllegalStateException]("") def baz(x: Int) {}
  // FIXME: SI-7066
  // @throws[E2]("") def foo[E2 <: Exception] {}
}
```

that results in an `AbstractTypeSymbol` "E1" reaching GenASM, as part of 

```
@throws[E1]("") def bar() {}
```

In terms of ASM's Textify the resulting class file includes:

```
// class version 50.0 (50)
// access flags 0x21
// signature <E1:Ljava/lang/Exception;>Ljava/lang/Object;
// declaration: ScalaClassWithCheckedExceptions_1<E1 extends java.lang.Exception>
public class ScalaClassWithCheckedExceptions_1 {

...

  public bar()V throws E1 
    RETURN
    MAXSTACK = 0
    MAXLOCALS = 1
```

Although there's no "E1" class file the bytecode verifier doesn't complain.

**Comment by SethTisue** [comment]
closing stale backend tickets; comment/reopen if you have evidence this is still applicable
