### ISSUE TITLE
java.lang.StackOverflowError during phase 'typer'

### ISSUE THREAD

**Issue by scabug** [scala/bug#7131]
The compiler crashes with a StackOverflowError during the type-checking phase.

I have attached the source file which causes the crash as well as the output messages emitted by the IDE (IntelliJ) which contains the stacktrace and the details of the error.

The offending bit appears to be the contravariance annotation on the type parameter T for the ObservableTrait. If the annotation is removed or replaced with '+' then the program just doesn't compile which I believe is the right behavior.

**Comment by diesalbla** [comment]
The code in the example no longer crashes. The compiler, as of the current development version of 2.13, no longer crashes but instead outputs the following type error:  
```
t7131.scala:27: error: type mismatch;
 found   : Iterable[U]
 required: That
 Note: implicit method convertToSimpleMappable is not applicable here because it comes after the application point and it lacks an explicit result type
        x.value.map(f)
                   ^
one error found
```

However, when checking this code in Scala 2.12.7, it gets a different error message: 
```
t7131.scala:5: error: contravariant type T occurs in covariant position in type => T of method value
  def value: T
      ^
one error found
```
