### ISSUE TITLE
Relieve compiler check for macros: outside abstract type in structural refinement

### ISSUE THREAD

**Issue by scabug** [scala/bug#7136]
I think the use of outside abstract type in structural refinement should be allowed when the refinement is passed to a type macro. From the article http://scala-programming-language.1934581.n4.nabble.com/scala-Structural-types-with-generic-type-question-td1992248.html#a1992249 , I don't see why this would apply to type macros, as long as they do not generate such code. This would allow, for instance, to write a type macro that would mix in (possibly modified) function declarations.

**Comment by SethTisue** [comment]
stale ticket. could be revived as a discussion on https://contributors.scala-lang.org (though, there isn't much interest in changing scala.reflect macros anymore)
