### ISSUE TITLE
Implicit conversion ambiguity for type and base type

### ISSUE THREAD

**Issue by scabug** [scala/bug#7138]
Should the compiler choose the least specialized implicit conversion?

```scala
object implicits {
	class Base
	class Derv extends Base
	
	implicit def intToBase(i:Int):Base = null
	implicit def intToDerv(i:Int):Derv = null


	def someFoo(cs:Base){
		println(cs)
	}

        someFoo(1) //<<-- error here
}

```

> <console>:13: error: type mismatch;
   found   : Int(1)
   required: Base
  Note that implicit conversions are not applicable because they are ambiguous:
   both method intToBase of type (i: Int)Base
   and method intToDerv of type (i: Int)Derv
   are possible conversion functions from Int(1) to Base
                SomeFoo(1)
                        ^

**Comment by som-snytt** [comment]
I might have suggested the most specific result, as for `implicitly[Base]`, but overload resolution is based on the parameter types.
