### ISSUE TITLE
Allow the creation of static methods/fields with the reflection/macro/compiler API

### ISSUE THREAD

**Issue by scabug** [scala/bug#7158]
Sometimes it is mandatory to play by the rules made somewhere else (Serialization, VM intrinsics, Android, ...) and if these rules specify that some static field/method has to exist in the class file, there is no way around it.

Introducing such a possibility in the reflection/compiler API (probably for internal use only) would solve this and would allow us to get rid of the special-cased hacks currently used in the Scala compiler, e. g. for SerialVersionUID or Android's Parceable.

Additionally, this would fix the last huge issue which currently blocks the implementation of better enums.

**Comment by SethTisue** [comment]
closing stale enhancement tickets. agree there is room for improvement here, but let's keep scala/bug (post migration from JIRA) focused on bugs
