### ISSUE TITLE
InstanceMirror and ReflectiveMirror lack a common superclass (other than AnyRef)

### ISSUE THREAD

**Issue by scabug** [scala/bug#7168]
When using reflection I have sometimes need to figure out whether I should reflect (a module for example) on a ReflectiveMirror or on an InstanceMirror like this. It would help if ReflectiveMirror and InstanceMirror had a common supertype that had the methods which are the same such as reflectModule.

Example of what I would like to achieve:
val m = if (sym.isStatic) mirror else baseInstanceMirror
m.reflectModule(…)

**Comment by SethTisue** [comment]
scala.reflect is largely dormant, this seems unlikely to progress
