### ISSUE TITLE
easier way to scan packages/modules for values of matching symbols

### ISSUE THREAD

**Issue by scabug** [scala/bug#7169]
It would be very helpful if there was an easier way to scan a package or module for matching symbols. 

A usecase could be a user that wants all values of fields of that has a matching symbol in a module (not a too uncommon scenario I think).

Example usage of this:
```scala
scan("my.package.anobject") { symbol =>
  isSymbolAString(symbol): Boolean
}: Seq[(Any, Symbol)] //Any is the value of the field
```

This will return: 
```scala
Seq(("the acutal value I was looking for", value valueIwasLookingFor))
```

If the code looks like this:
```scala
package my.package

object anobject {
  object nestedWorksAsWell { //could be nested as well
    val valueIwasLookingFor = "the acutal value I was looking for"
  }
}
```

**Comment by SethTisue** [comment]
stale ticket. let's keep scala/bug focused on bugs. anyway scala.reflect rarely changes anymore
