### ISSUE TITLE
Typer inlines constants and makes dependency analysis impossible

### ISSUE THREAD

**Issue by scabug** [scala/bug#7173]
The problem has been mentioned here:
https://groups.google.com/d/topic/scala-internals/b95Y-GbXVGA/discussion

The gist is that typer inlines compile time constants (e.g. references to static fields defined in Java) and forgets about the original tree that referred to a constant (e.g. to a field) which makes dependency analysis impossible.

According to Adriaan pattern matcher does not need constants to be inlined because it works with types. I couldn't readily find a reason why we need to inline those constants in typer so we probably should move this all the way to erasure.

I'm logging a ticket to not forget to investigate if we can do that for 2.10.2.

**Comment by retronym** [comment]
Here's another symptom of the fact that we constant fold term trees:

```
class C {
  final def foo = 1
  val s: String = {class D extends C { def foo = 2 }; ""}
}
```

`-Xprint:typer` shows `val s: String = "";`, and the invalid override of `def foo` is not flagged.

**Comment by lrytz** [comment]
See also https://github.com/scala/bug/issues/10340#issuecomment-304690644
