### ISSUE TITLE
Finally blocks are duplicated for each 'return' in a try/catch/finally

### ISSUE THREAD

**Issue by scabug** [scala/bug#7182]
Finally blocks are duplicated for every 'return' in the body of a try or catch block. It should be possible to avoid that duplication, but to do so would require an analysis of the stack state and then draining the stack or otherwise creating a situation where the stack was identical on all flows into the 'return' copy of the finally block.

This is related to #7181, except that deals with the much easier duplication on normal exit from a try or exception handler. In that case we always know the stack state must be the same because ultimately they need to flow to the same point.

Because 'return' is relatively rare in Scala and because the fix requires some care and work I'm not prioritizing this issue, just recording it for when somebody is bored.

**Comment by SethTisue** [comment]
closing stale backend tickets; comment/reopen if you have evidence this is still applicable

**Comment by lrytz** [comment]
No longer the case in 2.12, but there's a problem with the new solution https://github.com/scala/bug/issues/10183
