### ISSUE TITLE
Infer result type using type of overridden method, if any (and not using the rhs)

### ISSUE THREAD

**Issue by scabug** [scala/bug#7212]
An old email for which I never opened a ticket. It is undesirable that implementing an abstract method with an implementation like sys.error("no implementation yet") should force all subclasses to throw an exception. It is extremely unlikely anyone would want this "most specific type" to be inferred as the return type of a method for which less exceptional return type is already known (i.e. I'm not talking about def ??? which is born in the same location as the exception; I'm talking about any method for which there is an abstract or concrete implementation in a superclass.)

```
In the following, how does one define foo in class B such that:

 1) class A's foo definitions can be swapped without modifying B
 2) class C compiles

Can you? I can't.  But I should be able to.

  class A {
    def foo = new A
    // def foo = new B
  }

  class B extends A {
    override def foo = sys.error("")
  }

  class C extends B {
    override def foo = new C
  }
```

**Comment by adriaanm** [comment]
This could also be interesting to speed up compilation by using the inherited type rather than type checking the RHS. The decision point is in `assignTypeToTree`. 

Too late for 2.13, though.

**Comment by som-snytt** [comment]
It's never too late for 2.13.

"Age is just a number." Or, a major and minor version number.

**Comment by Jasper-M** [comment]
I'm not sure if I should prefer the behavior of dotty...
If you're defining public API, especially non-final, you should give an explicit return type.

**Comment by SethTisue** [comment]
I've opened a ticket suggesting the Scala 3 migration guide mention this: https://github.com/scalacenter/scala-3-migration-guide/issues/181

**Comment by SethTisue** [comment]
closing as out of scope for Scala 2

**Comment by som-snytt** [comment]
Worst possible resolution. Did I ever PR this? This is so obvious etc.

**Comment by SethTisue** [comment]
perhaps someone would like to PR it under `-Xsource:3`?

**Comment by som-snytt** [comment]
My duplicate ticket from 2013 was https://github.com/scala/bug/issues/8159 in case that inspires someone. I thought this already had a PR by lrytz or adriaanm.

**Comment by som-snytt** [comment]
I came across this again because test https://github.com/scala/scala/blob/2.13.x/test/files/neg/t2441.scala for https://github.com/scala/bug/issues/2441 is fixed in Scala 3 under this change. I had forgotten I'd just been here during pandemic.

**Comment by SethTisue** [comment]
linked PR changes the behavior, but only under `-Xsource:3`
