### ISSUE TITLE
Regression: Compiler tries implicit conversion, while corresponding implicit val is already in scope

### ISSUE THREAD

**Issue by scabug** [scala/bug#7270]
This code compiles with Scala 2.9.2
```scala
trait Im {
  type Elem[A]
  trait PArray[A]
  implicit def parrayElement[A](implicit ea: Elem[A]): Elem[PArray[A]]
  def create[A](implicit ea: Elem[A]): PArray[A]
  def test[A](implicit ea: Elem[A]) = create
}
```

It doesn't compile with Scala 2.10.0 or Scala 2.10.1

```scala
Im.scala:6: ambiguous implicit values:
[error]  both method parrayElement in trait Im of type [A](implicit ea: Im.this.Elem[A])Im.this.Elem[Im.this.PArray[A]]
[error]  and value ea of type Im.this.Elem[A]
[error]  match expected type Im.this.Elem[A]
[error]   def test[A](implicit ea: Elem[A]) = create
[error]                                       ^
```

Note that there is no need to try parrayElement here since implicit val ea: Elem[A] is already in the scope.

**Comment by som-snytt** [comment]
This is expected. "In scope" includes both the parameter and the method. The example compiles if the identifiers are the same, so that the parameter shadows the method.

This compiles in dotty because dotty considers nesting level as disambiguating.

**Comment by Jasper-M** [comment]
It also helps when you assign a type to `test`.

```
def test[A](implicit ea: Elem[A]): PArray[A] = create //works
```
