### ISSUE TITLE
Value classes lack the AnyVal parent in class files

### ISSUE THREAD

**Issue by scabug** [scala/bug#7281]
The fact that a class extends AnyVal isn't reflected in the class files generated by the compiler:

```scala
class Foo(val bar: Int) extends AnyVal
classOf[Foo].getSuperClass // class java.lang.Object
```

It's important to have a cheap and fast way to recognize value classes at runtime without depending at large, language-specific libraries.

**Comment by hrhino** [comment]
It's too late for that, too.

**Comment by SethTisue** [comment]
I wonder what the use case for "recognize value classes at runtime" even is. Judging from how little attention this ticket has attracted, maybe it's rare-to-nonexistent to want or need to do it.
