### ISSUE TITLE
Revert the deprecation of set in SyncVar

### ISSUE THREAD

**Issue by scabug** [scala/bug#7308]
For some very strange reason the set method of SyncVar has been marked for deprecation. Please remove the deprecation and do not deprecate the set method.

The set method is what makes SyncVar a var in the first place. If the SyncVar only has put, then it will effectively become a size 1 bounded queue and is no longer a variable.

SyncVar needs to act like a variable. There must be a way to set the variable twise without reading or clearing it in between.

It must support the following flow:
- Thread 1 set variable to "a"
- Thread 1 set variable to "b" (discards value "a")
- Thread 2 read variable, get value "b"
- Thread 1 set variable to "c" (discards value "b")
- Thread 1 set variable to "d" (discards value "c")
- Thread 2 read variable, get value "d"

Alternatively stop calling it a SyncVar, and rename it to BoundedQueue1

**Comment by SethTisue** [comment]
do you have a link to the PR that did the deprecation? curious about the history here

**Comment by NthPortal** [comment]
This issue needs to be resolved before scala/scala#6319 is merged, because [this commit](https://github.com/scala/scala/pull/6319/commits/691ffa7efc6fe4b3f2a1d1f5ef29564303560ffe) in that PR removes `set` and `unset`

**Comment by NthPortal** [comment]
It was deprecated in scala/scala#560, which fixed #5623

**Comment by hvesalai** [comment]
@SethTisue I must say I have no recollection about this. Furthermore I grepped SyncVar from our code and we are not using it any more, so I have no vested interest. I think everybody is using the java atomic stuff.

**Comment by lrytz** [comment]
Maybe @heathermiller has some memory of this (why were `set` and `unset` on `SyncVar` deprecated in https://github.com/scala/scala/pull/560)?

**Comment by NthPortal** [comment]
Do we just close this as `won't fix`, at this point?

**Comment by SethTisue** [comment]
I'm just about to that point... let's do one last thing, let's rub @viktorklang's lamp and see if he appears
