### ISSUE TITLE
Provide some sort of interop mechanism between Scala reflection and Java reflection

### ISSUE THREAD

**Issue by scabug** [scala/bug#7317]
(for some reason the form only lets me set priority to blocker, even though it's not even close to that)

I have some values from java.lang.reflect.* and would like to be able to use Scala reflection goodness with them. It might be nice to go the other way around, too.

For example (as explained in http://stackoverflow.com/questions/15712097/using-scala-reflection-with-java-reflection) I might have a java.lang.reflect.Method and want to determine if there are any Scala deprecation annotations attached to it. Java's reflection annotation mechanism can't see Scala annotations, so I somehow need to get a Scala Symbol out of that Method object, and doing so is difficult right now.

**Comment by SethTisue** [comment]
scala.reflect isn't really changing anymore. pull requests in this area can still be accepted, but let's keep scala/bug focused on bugs. enhancements should be discussions on https://contributors.scala-lang.org
