### ISSUE TITLE
synthetic typecreator classes have unpositioned symbols

### ISSUE THREAD

**Issue by scabug** [scala/bug#7384]
When materializing a TypeTag, the compiler generates classes like:

```scala
final class $typecreator1 extends TypeCreator {
  def <init>(): $typecreator1 = {
    $typecreator1.super.<init>();
    ()
  };
  def apply[U >: Nothing <: scala.reflect.api.Universe with Singleton]($m$untyped: scala.reflect.api.Mirror[U]): U#Type = {
    val $u: U = $m$untyped.universe;
    val $m: $u.Mirror = $m$untyped.asInstanceOf[$u.Mirror];
    $m.staticClass("com.acme.core.util.Holder").asType.toTypeConstructor
  }
}
```

The class symbol for $typecreator1 is unpositioned. This crashes SCCT.

The trees are positioned correctly.

The class symbol also lacks the SYNTHETIC flag.

**Comment by SethTisue** [comment]
This ticket is so old I don't feel like expending the effort to determine if it's still an issue. We can reopen if someone steps forward with evidence it still matters.
