### ISSUE TITLE
Resolve inherited Java static method

### ISSUE THREAD

**Issue by scabug** [scala/bug#7386]
Inherit static method from Java class is not recognized by Scala class
Here there is an small and simple example:

```scala
MyClass.java
public class MyClass extends MyClassBase {}

abstract class MyClassBase {
  public static void myStaticBaseMethod() {}
}

MyScalaClass.scala
class MyScalaClass {
  MyClassBase.myStaticBaseMethod() //compiles
  MyClass.myStaticBaseMethod() //no compiles. Wrong!!!
}
```

**Comment by SethTisue** [comment]
@lrytz do you agree this should be closed as "not a bug"? scala/scala#5606 doesn't aim to "fix" this ticket, right?

**Comment by lrytz** [comment]
Yes, I agree

**Comment by SethTisue** [comment]
> Do you think it would be feasible just to introduce an error message that can be a little bit friendlier towards those coming from Java, perhaps suggesting what the user can do

a pull request with that would be welcome, as far as I can see. (I don't think it merits an additional ticket — there are too many improvable error messages to have individual tickets for them all)
