### ISSUE TITLE
Macros fail to find annotations upon modification of the classes interface.

### ISSUE THREAD

**Issue by scabug** [scala/bug#7424]
When using a macro to find annotations the macro is unable to find the annotations on modification of the parent classes interface. The macro is run, but the annotations list of the symbol of interest is empty. However, once the file which executes these macros is recompiled, the annotations are again found.
Minimal example: https://github.com/bryce-anderson/scalaerror/

**Comment by SethTisue** [comment]
closing since a workaround exists and since scala.reflect isn't changing much anymore. comment/reopen if you disagree
