### ISSUE TITLE
TypeBoundsTree children can have NoPosition

### ISSUE THREAD

**Issue by scabug** [scala/bug#7450]
A type definition like "type D <: AnyRef" has as its lower bound type a TypeTree with a NoPosition instead of an OffsetPosition. And if the lower bound is given, the upper bound has a NoPosition as well. I think this was introduced by the recent "Simplify type bounds" commit c29405dfe1.

**Comment by SethTisue** [comment]
unclear if there's something actionable here. comment/reopen if so
