### ISSUE TITLE
compiler loses type information on lazy vals when using its API

### ISSUE THREAD

**Issue by scabug** [scala/bug#7457]
In a nightly version of Scala IDE, which is compiled against 2.10.2 or 2.11, parameterized type ascriptions on lazy vals are not highlighted anymore by semantic highlighting.

```scala
object s {
  lazy val xs: Seq[String] = ??? // Seq[String] is not highlighted
}
```

After debugging semantic highlighting it turned out that this is not a regression in the IDE but in the compiler because information to the type of xs don't reach the IDE side, thus it can't highlight anything.

**Comment by SethTisue** [comment]
please comment or reopen if this can be verified to exist in current Scala

**Comment by SethTisue** [comment]
also we'd want to determine if this is a presentation compiler bug (those live here) or a ScalaIDE bug (those live in their own tracker)
