### ISSUE TITLE
Incorrect exhaustiveness warning with tuple with Boolean values

### ISSUE THREAD

**Issue by scabug** [scala/bug#7466]
The following code gives an incorrect dead code warning:
```scala
object Test extends App {
  val Yes1 = true
  val Yes2 = true
  val No1 = false
  val No2 = false

  def test(b1: Boolean, b2: Boolean) {
    (b1, b2) match {
      case (No1, No2) => println("1")
      case (No1, Yes2) => println("2")
      case (Yes1, No2) => println("3")
      case (Yes1, Yes2) => println("4")
    }   
  }

  test(No1, Yes2)
}
```

When compiling this, I get the wraning:

```scala
[error] test.scala:14: unreachable code
[error]       case (No1, Yes2) => println("2")
```

However, when run, it does print "2", so it is clearly not dead code.

It looks like it has something to do the Booleans. If I change all the Booleans to Int's with values of 0/1, the dead code error goes away.

This same code does not produce a warning in scala 2.9.2.

**Comment by dwijnand** [comment]
Spent a good while studying this one and I can't think of a good way to fix it.  It's not false unreachable warnings anymore, it's just saying that it can't prove exhaustiveness, and gives you the  8 ways it thinks 2 booleans can fail, which is a bit dumb.
