### ISSUE TITLE
accessing a method type crashes the compiler

### ISSUE THREAD

**Issue by scabug** [scala/bug#7468]
In an interactive session:

Welcome to Scala version 2.10.1 (Java HotSpot(TM) 64-Bit Server VM, Java 1.6.0_45).

scala> import scala.reflect.runtime.{universe => ru}
import scala.reflect.runtime.{universe=>ru}

scala> val l = List(1,2,3)
l: List[Int] = List(1, 2, 3)

scala> def getTypeTag[T: ru.TypeTag](obj: T) = ru.typeTag[T]
getTypeTag: [T](obj: T)(implicit evidence$1: ru.TypeTag[T])ru.TypeTag[T]

scala> val theType = getTypeTag(l).tpe
theType: ru.Type = List[Int]

so far so good, but I was wondering about the type of tpe so I entered:
scala> :t getTypeTag(l).tpe _
****boom!**** [pasted below]
That entry seems to have slain the compiler. [...]

Strangely enough, doing it in two steps works ok:

scala> val tag = getTypeTag(l)
tag: reflect.runtime.universe.TypeTag[List[Int]] = TypeTag[List[Int]]

scala> :t tag.tpe _
() => reflect.runtime.universe.Type

********beginning of error message********

ReplGlobal.abort: no-symbol does not have an owner
error: no-symbol does not have an owner
unhandled exception while transforming <console>
error: uncaught exception during compilation: scala.reflect.internal.FatalError
scala.reflect.internal.FatalError: 
    while compiling: <console>
       during phase: superaccessors
    library version: version 2.10.1
   compiler version: version 2.10.1
 reconstructed args: 

 last tree to typer: TypeTree(trait Function0)
             symbol: trait Function0 in package scala (flags: abstract <trait>)
  symbol definition: abstract trait Function0[+R] extends AnyRef
                tpe: () => reflect.runtime.universe.Type
      symbol owners: trait Function0 -> package scala
     context owners: value $u

== Enclosing template or block ==

DefDef( // def $ires11: () => reflect.runtime.universe.Type
 <method>
 "$ires11"
 []
 Nil
 <tpt> // tree.tpe=() => reflect.runtime.universe.Type
 Function( // val $anonfun: <notype>, tree.tpe=() => reflect.runtime.universe.Type
   ()
   $line45.$read.$iw.$iw.getTypeTag[List[Int]]($line44.$read.$iw.$iw.l)({
 val $u: reflect.runtime.universe.type = scala.reflect.runtime.`package`.universe;
 val $m: $u.Mirror = scala.reflect.runtime.`package`.universe.runtimeMirror(this.getClass().getClassLoader());
 $u.TypeTag.apply[List[Int]]($m, {
   final class $typecreator1 extends TypeCreator {
     def <init>(): $typecreator1 = {
       $typecreator1.super.<init>();
       ()
     };
     def apply[U >: Nothing <: scala.reflect.api.Universe with Singleton]($m$untyped: scala.reflect.api.Mirror[U]): U#Type = {
       val $u: U = $m$untyped.universe;
       val $m: $u.Mirror = $m$untyped.asInstanceOf[$u.Mirror];
       $u.TypeRef.apply($u.ThisType.apply($m.staticPackage("scala.collection.immutable").asModule.moduleClass), $m.staticClass("scala.collection.immutable.List"), scala.collection.immutable.List.apply[$u.Type]($m.staticClass("scala.Int").asType.toTypeConstructor))
     }
   };
   new $typecreator1()
 })
})."tpe" // def tpe: TypeTags.this.Type in trait WeakTypeTag, tree.tpe=reflect.runtime.universe.Type
 )
)

== Expanded type of tree ==

TypeRef(
 TypeSymbol(abstract trait Function0[+R] extends AnyRef)
 args = List(
   AbstractTypeRef(
     pre = SingleType(
       pre = SingleType(
         pre = SingleType(
           pre = SingleType(
             pre = SingleType(
               pre = ThisType(package <root>)
               package scala
             )
             package reflect
           )
           package runtime
         )
         package runtime
       )
       value universe
     )
     AbstractType(type Type >: Null <: Types.this.TypeApi)
   )
 )
)

no-symbol does not have an owner
	at scala.reflect.internal.SymbolTable.abort(SymbolTable.scala:49)
	at scala.tools.nsc.Global.abort(Global.scala:253)
[etc.]

**Comment by SethTisue** [comment]
reopen if reproducible in current Scala

**Comment by lrytz** [comment]
no more crash in 2.12.4
