### ISSUE TITLE
Pattern matcher does not pass full type information to case body (value X is not a member of _2)

### ISSUE THREAD

**Issue by scabug** [scala/bug#7472]
In the following example, the pattern match against `FooBar` is not correctly propagated to the case body, producing a compiler error:

Preparation:

```scala
sealed trait Bar[S] {
  def system: S
}

trait Foo { def bar(): Unit }

trait FooBar extends Bar[Foo]
```

Example:

```scala
trait Test[S] {
  val bar: Bar[S]

  bar match {
    case fb: FooBar => fb.system.bar() // error
    case _ =>
  }
}
```

The error here is: "error: value bar is not a member of _2"

The following shows that the type is actually accepted by the compiler:

```scala
case fb: FooBar => (fb: FooBar).system.bar()
```

**Comment by SethTisue** [comment]
Scala 3 accepts this example because it has vastly better GADT support than Scala 2. It’s highly unlikely the situation in Scala 2 will ever improve.
