### ISSUE TITLE
Add a test/files/avian directory for Avian-specific tests and add support for it in the build system

### ISSUE THREAD

**Issue by scabug** [scala/bug#7480]
We need a directory for Avian-specific tests (and adaptions of existing tests) to effectively test Scala on Avian.

As an example, test/files/run/tailcalls.scala assumes that the runtime has no support for proper tail calls and hard-codes these assumptions into the test/check file.

At a later stage, this directory might also hold tests related to things like native value types, big array support, runtime specialization, etc.

**Comment by SethTisue** [comment]
abandoned
