### ISSUE TITLE
inliner destroys line number information

### ISSUE THREAD

**Issue by scabug** [scala/bug#7518]
In the attached screenshot, debugging Scala 2.10.2-RC1, you can see the call stack shows 

```
resetAllAttrs():37, Global {scala.tools.nsc}
adaptToImplicitMethod$1():870, Typers$Typer {scala.tools.nsc.typechecker}
```

I expect:

```
resetAllAttrs():37, Global {scala.tools.nsc}
adaptToImplicitMethod$1():881, Typers$Typer {scala.tools.nsc.typechecker}
```

Where line 881 is in the inlined lambda.

**Comment by SethTisue** [comment]
@lrytz should this stay open?

**Comment by lrytz** [comment]
yes, let's track the rest at https://github.com/scala/scala-dev/issues/3
