### ISSUE TITLE
calling scala fails on Windows machines on volumes with shortnames (3dot8names) support disabled

### ISSUE THREAD

**Issue by scabug** [scala/bug#7578]
Installed Scala from msi package
Trying to run "scala" returns an error message.
The root case seems to be: In scala.bat the ~s modifier is used, which does not work on 3dot8names-disabled volumes.

Windows does not produce any shortnames for files created on volumes that do not support shortnames (3dot8names).
To query and set the handling of 3.8 file names the utility fsutil can be used.

**Comment by Philippus** [comment]
I think this was fixed in https://github.com/scala/scala/pull/5666
