### ISSUE TITLE
→ should be deprecated

### ISSUE THREAD

**Issue by scabug** [scala/bug#7613]
From reporter¹:

```scala
val tuple = 1 -> 1 / 0.1
val tupple2 = 1 → (1 / 0.1)
```

First line compiles just fine while second one requires parentheses because, according to my understanding of SLS "6.12.3 Inﬁx Operations", '{{→}}' as '(all other special characters)' have higher precedence than '`/`', while '`->`' have lowest precedence because of first '{{\-}}'.

Martin says:

Once we specify that unicode  `→` is an alias for `->` it makes sense to rule that they have the same precedence.

¹ https://groups.google.com/d/topic/scala-language/n75hbalnoQc/discussion

**Comment by SethTisue** [comment]
closing as duplicate of https://github.com/scala/bug/issues/11210 (because the newer ticket has more discussion and inbound links)

**Comment by som-snytt** [comment]
I always feel bad that @demobox may have missed his shot at a puzzler.

**Comment by demobox** [comment]
> I always feel bad that @demobox may have missed his shot at a puzzler.

*sigh*. Although I guess from the perspective of the community overall, "N puzzlers are better than N+1 puzzlers" ;-)

Thanks for continuing to keep a keen eye out for these, @som-snytt!
