### ISSUE TITLE
ClassFormatError: Duplicate field name&signature on val in trait and subclass

### ISSUE THREAD

**Issue by scabug** [scala/bug#7645]
The compiler accepts the following code, but it fails at runtime with:

Exception in thread "main" java.lang.ClassFormatError: Duplicate field name&signature in class file Cl

```java
trait T {
  val x = 5
}

class Cl extends T {
  private[this] val x = 7
}

object Example {
  def main(args: Array[String]) {
    new Cl
  }
}
```

**Comment by som-snytt** [comment]
The OP is disallowed but the last examples are duplicates at 5252.
