### ISSUE TITLE
REPL :edit command bad interaction with certain useful editors

### ISSUE THREAD

**Issue by scabug** [scala/bug#7682]
The new `:edit` command doesn't like console editors, as foretold.

We will repair this usability deficit.

**Comment by SethTisue** [comment]
not sure what the cause is, but "good first issue" seems at least plausible. at least to figure out what's going on.

**Comment by nhiguchi** [comment]
Now, without `EDITOR`, it behaves the same as`:line`.
It freezes when I set `vim` to `EDITOR`.

If set `vim`, is it correct behavior that editable history with `vim`?

**Comment by SethTisue** [comment]
> If set vim, is it correct behavior that editable history with vim?

That's the goal, yes.

**Comment by nogurenn** [comment]
I don't see the `:edit` command in 2.12 and 2.13, so I think it's temporary until this is fixed. This is what I got.

```
$ EDITOR=""
==> java.io.IOException: Cannot run program "": error=2, No such file or directory
// says at the tail that the entry has slain the compiler (If I choose yes for replay, "Nothing to replay.")

$ EDITOR="vim"
==> 
// blank, cannot type anything, but it might actually be running and did not hang up, because....
// $ ps says
// 54175 ttys001    0:00.01 vim /var/folders/3z/vxd....
// and pressing ctrl-c in the scala console removes the vim process.

$ EDITOR="nano"
==> Error exit from nano (1), ignoring
// reaches the default case x for pr.exitCode

$ EDITOR="code" // visual studio code
==> 
    +vim
    +:ed
    +val x = 123
    +:hi
    +:ed 184-
    +:hi
    ....
    <console>:5: error: ';' expected but ':' found.
    :ed 184-
    ^
    <console>:12: error: ';' expected but ':' found.
    :ed 184-
    ^

    scala> 
// prints the stuff above, and then opens my vscode app with a blank .tmp file
// it reaches the next input (?) as seen in the last line above
// visually, it happens in that order. I ran :edit with the vscode app open already.
// I don't have proof that it does happen in that order though
```

screenshot of open vscode app after running `:ed`
<img width="636" alt="Screen Shot 2020-05-23 at 2 23 18 AM" src="https://user-images.githubusercontent.com/15997393/82698086-c01a4600-9c9c-11ea-89e0-4a73db92fae8.png">

**Comment by som-snytt** [comment]
The feature was just a quick workaround for JLine2 limitations. It allowed using gedit to edit multiple lines of history.

Closing in favor of upstream contributions to JLine3, as necessary.
