### ISSUE TITLE
Spurious "private default argument... is never used" warning with -Xlint

### ISSUE THREAD

**Issue by scabug** [scala/bug#7707]
```
object O { O() }
case class O private (x: Int = 3)
```

gives (in 2.11.0-M4)

```
warning: private default argument in object O is never used
       case class O private (x: Int = 3)
                             ^
```

but it is; it's used from the companion object.

**Comment by lrytz** [comment]
This issue is still present in 2.12.4 (and 2.12.x shortly before 2.12.5).

**Comment by som-snytt** [comment]
I don't remember why that commit didn't make it onto the slow train of warning fixes. I'll take a look during some relaxing weekend at the beach when I have nothing better to do.

**Comment by som-snytt** [comment]
This was not a relaxing weekend, but I had nothing better to do.

Note that there is no way to mark a default arg `@unused`.
