### ISSUE TITLE
scala.tools.reflect.ToolBox fails to find types in the empty package

### ISSUE THREAD

**Issue by scabug** [scala/bug#7724]
Despite a proper class path and classloader, scala.tools.reflect.ToolBox is unable to compile code that uses type defined in the empty package. It appears to be a scala visibility issue, and the workaround is to pass "-Yexpose-empty-package" to the tool box options when creating it.

**Comment by SethTisue** [comment]
given that `-Yexpose-empty-package` exists, this doesn't seem like a bug
