### ISSUE TITLE
Error parsing .class file - bad constant pool tag

### ISSUE THREAD

**Issue by scabug** [scala/bug#7772]
code:

import com.netflix.astyanax.Keyspace
import org.reflections.Reflections

class EntityManager(keyspace:Keyspace, rootpkg:String = "", create:Boolean = false)
{
   // scan package root for annotated classes
   private val reflections = new Reflections(rootpkg)

}

fails to compile with:

[warn] Class javax.annotation.Nullable not found - continuing with a stub.
[warn] Caught: java.lang.NullPointerException while parsing annotations in C:\Documents and Settings\majitel.RADIM\.ivy2\cache\org.reflections\reflections\jars\
reflections-0.9.9-RC1.jar(org/reflections/Reflections.class)
[error] error while loading Reflections, class file 'C:\Documents and Settings\majitel.RADIM\.ivy2\cache\org.reflections\reflections\jars\reflections-0.9.9-RC1.jar(org/reflections/Reflections.class)' is broken
[error] (class java.lang.RuntimeException/bad constant pool tag 10 at byte 657)
[error] C:\eclipse\workspace\play\entitymappertest\src\main\scala\em\EntityManager.scala:9: org.reflections.Reflections does not have a constructor
[error]    private val reflections = new Reflections(rootpkg)
[error]                              ^
[warn] two warnings found
[error] two errors found

i recompiled reflections library myself from sources and still getting that error.

**Comment by SethTisue** [comment]
reopen if this can be reproduced against current Scala
