### ISSUE TITLE
Explicit return causes scalac -optimize to fail

### ISSUE THREAD

**Issue by scabug** [scala/bug#7792]
Given this code:
```scala
object Return {
  def test(oi:Option[Int]):Option[String] =
    oi.map(i => return Some(i.toString))
}
```

When the `return` keyword is explicitly used and you try to compile it with `-optimize`, it causes the compiler to fail with the following message:

  `could not find init in: Return.test`

The full trace is at https://gist.github.com/dkristian/6348965 (also attached).

It compiles fine without the `-optimize` flag, and works with the flag if the method definition is changed to
```scala
  oi.map(i => i.toString)
```
Discussion started at https://groups.google.com/forum/#!topic/scala-language/WTzjZ5dpPdo

**Comment by hrhino** [comment]
Closing since it appears fixed in the new optimizer.
