### ISSUE TITLE
scala.reflect.io.AbstractFile#toByteArray

### ISSUE THREAD

**Issue by scabug** [scala/bug#7811]
I'm working on a very simple scripting engine that can "stream" (in quotes because it seems the compiler wants all the bytes up-front instead of asking for them on-demand during the compilation process) source and compile it.

As of 2.10.2, in scala.reflect.io.AbstractFile line #162, it specifies:

var rest = sizeOption.getOrElse(0)

The default value for sizeOption is None which is perfect since I don't know ahead of time in my stream what the full size is going to be.

Perhaps the buffer size of 0 in this case is intended, but it actually results in confusing behavior. If sizeOption is None, I'd expect it to instead either throw an exception (show an error) or buffer the contents of the stream until read returns -1. Instead it silently compiles nothing.

If the goal is to support an empty .scala file, then sizeOption should return Some(0), correct?

I'm able to easily work around this issue in my code, but thought I'd at least note it.

(on another note -- I wasn't able to modify the priority in the issue to something other than "Blocker")

**Comment by Philippus** [comment]
This seems to have been fixed in https://github.com/scala/scala/pull/2238/commits/3e8f8ddb2ac057ad82e1a7e37f59baff1c0e15ac

**Comment by som-snytt** [comment]
Indeed.

Contributor: now that the repl is modularized,...

Committer: The modularisation isn't done yet. We won't stop until these things are in separate github projects, with their own artifacts. We want to be able to accept and publish improvements to them independently of the compiler's schedule.

I like my old suggestion of a language import to unlock internal API. That is library and not language, but it would have been useful for "internal" macro API, which is quasi-language.
