### ISSUE TITLE
Odd stty in bin/scalac causes problems with nohup

### ISSUE THREAD

**Issue by scabug** [scala/bug#7832]
The command-line executables (scala, scalac etc.) contain some workarounds for certain terminals, using stty.  This is in conflict with nohup, which hangs if scalac is used in batch mode (tested on Mac OS X).  The problem can be easily avoided by emitting stty commands only when required -- right now it is done unconditionally for saved_stty.

**Comment by SethTisue** [comment]
comment/reopen if confirmed to happen with current Scala >= 2.13.0-M3. (JLine has been upgraded.)
