### ISSUE TITLE
Awkward macro impl shape error when path-dependent types are involved

### ISSUE THREAD

**Issue by scabug** [scala/bug#7842]
```scala
import scala.language.experimental.macros
import scala.reflect.macros.Context

object Test {
  def foo = macro impl

  def impl(c: Context) = {
    import c.universe._
    reify(Literal(Constant(42)))
  }
}
```

```scala
21:35 ~/Projects/210x/sandbox (2.10.x)$ s
Test.scala:5: error: macro implementation has wrong shape:
 required: (c: scala.reflect.macros.Context): c.Expr[c.universe.Literal]
 found   : (c: scala.reflect.macros.Context): c.Expr[c.universe.Literal]
type mismatch for return type: c.Expr[c.universe.Literal] does not conform to c.Expr[c.universe.Literal]
  def foo = macro impl
                  ^
one error found
```

**Comment by SethTisue** [comment]
Someone want to check what the situation is in 2.13.x?

**Comment by som-snytt** [comment]
Not really.
```
➜  snips scalac -d /tmp -Xlint t7842.scala
➜  snips cat t7842.scala

import scala.language.experimental.macros
import scala.reflect.macros.blackbox.Context

object Test {
  def foo: Any = macro impl

  def impl(c: Context) = {
    import c.universe._
    reify(Literal(Constant(42)))
  }
}
➜  snips scala -cp /tmp
Welcome to Scala 2.13.11 (OpenJDK 64-Bit Server VM, Java 20.0.1).
Type in expressions for evaluation. Or try :help.

scala> Test.foo
            ^
       error: Macro expansion contains free term variable c defined by impl in t7842.scala:8:12. Have you forgotten to use splice when splicing this variable into a reifee? If you have troubles tracking free term variables, consider using -Xlog-free-terms

scala>
```
The reifee is the guy in black and white with the whistle.

**Comment by eed3si9n** [comment]
This cannot be reproduced as-is in 2.13.x because you'd get an error message that prevents you from writing a weird macro that would return a `Literal(...)` tree (as opposed to `Expr[Int]`):

```
> junit/testQuick
[info] compiling 309 Scala sources and 6 Java sources to /Users/eed3si9n/work/scala-modules/scala/target/junit/test-classes ...
[error] /Users/eed3si9n/work/scala-modules/scala/test/junit/scala/MacroTest.scala:18:7: macro defs must have explicitly specified return types
[error]   def foo = macro impl
[error]       ^
[error] one error found
[error] (junit / Test / compileIncremental) Compilation failed
```

In general, I'd vote to close any other remaining macro bugs since macro was supposed to be experimental, and to some extent it has done it job now that macro has graduated to a language feature in Scala 3?

**Comment by som-snytt** [comment]
I showed the source with the required explicit type and the preferred context.

It should stay open because it compiles and fails at usage time.

Taking the advice
```
➜  snips scalac -Vfree-terms -d /tmp -Xlint t7842.scala
t7842.scala:10: free term: Ident(TermName("c")) defined by impl in t7842.scala:8:12
    reify(Literal(Constant(42)))
         ^
```

**Comment by eed3si9n** [comment]
As Eugene B wrote:

> The problem here is not that something that should work doesn't work, but rather in the fact that this something shouldn't work in principle, and we need a better error message.

Here, we have a situation where someone return a Tree inside `reify(...)`, and in 2013 the error message was "macro implementation has wrong shape." As the first line of defense we now have "macro defs must have explicitly specified return types." At this point, the user would put `def foo: Int`. Not, `def foo: Any`, so this clears the "better error message" criteria.

Even if someone did say `Any`, 

```
Have you forgotten to use splice when splicing this variable into a reifee?
```

This is the second line of defense.

**Comment by SethTisue** [comment]
>  I'd vote to close any other remaining macro bugs since macro was supposed to be experimental, and to some extent it has done it job now that macro has graduated to a language feature in Scala 3?

I did do that for quasiquote bugs a while back, but I don't think we're comfortable doing it with all macro bugs.

**Comment by SethTisue** [comment]
> This cannot be reproduced as-is in 2.13.x

closing this one based on this remark, though.

**Comment by som-snytt** [comment]
Now that scalac 2 has done its job and flushed out all the language quirks, opening a green space for new quirks in Dotty, we could close the compiler tickets and just keep the library issues, which can remain open until the library rewrite for Scala 4.0.

Also, the more tickets are left open, the less time Seth has for fishing on the Truckee.
