### ISSUE TITLE
Improve the extractor class for TypeTrees to allow pattern matching against the wrapped up tree

### ISSUE THREAD

**Issue by scabug** [scala/bug#7875]
Pattern matching against the `TypeTree` of an `Apply` node is a bit clumsy at the moment, since the extractor class for `TypeTree` s doesn't allow the programmer to match against the wrapped up tree.

Instead the programmer has to invoke the `TypeTree.original` method and match against the tree returned, i.e.

```scala
case Apply(typeTree @ TypeTree(), args) => typeTree.original match {
    case pattern => ...
}
```

Changing the `unapply` method of the `TypeTreeExtractor` class to

```scala
abstract class TypeTreeExtractor {
    def apply(): TypeTree
    def unapply(typeTree: TypeTree): Option[Tree]
}
```

would allow a more compact notion when reflecting `TypeTree` s:

```scala
case Apply(TypeTree(pattern), args) => ...
```

**Comment by SethTisue** [comment]
closing old enhancement tickets. an improvement in this area could still happen, but let's keep scala/bug focused on bugs
