### ISSUE TITLE
case class copy method shouldn't subvert private constructor

### ISSUE THREAD

**Issue by scabug** [scala/bug#7884]
```scala
case class Foo private (num: Int)

object Foo {
  def apply(x: Double): Foo = x.toInt match {
    case x if x < 0 => throw new Exception(x + " < 0")
    case x          => new Foo(x)
  }
}

object Test {
  def main(args: Array[String]): Unit = {
    val x = Foo(5d)
    println(x -> x.copy(num = -1000))
  }
}

// % scala Test
// (Foo(5),Foo(-1000))
```

**Comment by akauppi** [comment]
I made a [repo](https://github.com/akauppi/case-class-gym) to exercise and study this behavior a bit.

Had been touched by it once or twice, last year, when I wanted to have a case class that only gets created internally. Had noticed that not defining the `.apply` allowed outside creation of instances, which I thought surprising.

I agree with @scabug that "principled thing is to give the synthetic copy method the same access modifiers as the primary constructor." I would extend that to the created `.apply` feature, as well.

How to suggest this for 2.13?

**Comment by akauppi** [comment]
Have mentioned this in https://users.scala-lang.org/t/ending-the-confusion-of-private-case-class-constructor-in-scala-2-13-or-2-14/2915

**Comment by SethTisue** [comment]
> How to suggest this for 2.13?

I think a pull request on this would likely be accepted.

**Comment by akauppi** [comment]
I'll be likely to work on this in July.

**Comment by akauppi** [comment]
@SethTisue I'd be happy to make SIP, but plan to do so after I've got a PR with associated tests ready. One reason to go SIP is that (to what I've seen so far) the current behaviour doesn't seem to be clearly defined, rather it "just is". I'll see that better when making changes to Scala, and if those changes don't break existing tests, that would useful information.

**Comment by adriaanm** [comment]
The copy method is synthesized here: https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/typechecker/Unapplies.scala#L176-L233. Its signature is completed by https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/nsc/typechecker/Namers.scala#L593-L616

**Comment by SethTisue** [comment]
related: https://github.com/lampepfl/dotty/pull/5472
