### ISSUE TITLE
Pattern matching in argument lists

### ISSUE THREAD

**Issue by scabug** [scala/bug#7909]
At the moment it is not possible to use pattern matching also in arguments for function definitions as it is possible eg. in Haskell.

I would love to write function definitions like this:

def foo((l, c) : (List[Char], Char), /other arguments/) : List[Char] = /body/

for example (just for illustration, function doesn't have any deep sense):
def setAdd((l, c) : (List[Char], Char)) : List[Char] = if (l contains c) l else c :: l

useful also in anonymous function definitions.

At the moment you have to write:
def setAdd(a : (List[Char], Char)) : List[Char] = if (a._1 contains a._2) a._1 else a._2 :: a._1

**Comment by dwijnand** [comment]
A request like this (nowadays) should be discussed on the forums first, and then see if there's interest in Scala 3 (Dotty).
