### ISSUE TITLE
suppress deprecation warnings over a narrow scope

### ISSUE THREAD

**Issue by scabug** [scala/bug#7934]
Sometimes I'm forced to use a deprecated method.  I need to filter these case by case, so that the warnings remain useful generally.  I do appreciate these warnings and act on them when I can, but if my build output becomes overrun with warnings I can do nothing about, I will eventually just ignore them all.

I've open this but to clarify #1781

**Comment by omervk** [comment]
Bumping this, hopefully out of oblivion. This requires me to give up -Xfatal-warnings, which is not a Good Thing To Do.

**Comment by pshirshov** [comment]
I would propose to implement fine-granular warning settings.

So, for each warning we should choose one of 3 possible alert levels, `{IGNORE | WARN | FAIL}`.

The only problem is how to identify warnings - there is no `identifier` parameter available in compiler logging method (`c.warning(...)`, etc).

Actually we may implement two solutions (both of them may co-exist):

1. Add a "identifier" parameter into compiler to all the compiler logging methods. So we may provide identifiers like `c.warning(123456, "message"), c.warning(4567 "message")`
2. Add missing parameters based as a `hash(file:line:character)`.

At the end we would be able to do smth like `scalac -Y:warning:SC-XXXX:ignore -Y:warning:SC-XXXX:fail`

**Comment by vn971** [comment]
@omervk The "silencer" plugin works for this I must say, specifically the (dangerous) part of it that disables warnings based on a pattern: https://github.com/ghik/silencer#global-regex-based-suppression

**Comment by sourcekick** [comment]
I just had the same problems and I am wondering what to do. I need to deprecate a function in a library, but I do not want to delete the unit tests for that function.

**Comment by sourcekick** [comment]
I just have the same problems. I am using -Xfatal-warnings and I have a library in which I have to deprecate a function, but I do not want to delete the unit tests for that function.

**Comment by lrytz** [comment]
I'm looking at https://github.com/scala/scala-dev/issues/333 currently, too late for 2.13.1, but hopefully we'll get something for 2.13.2.

https://github.com/ghik/silencer was mentioned before, I can recommend you to give it a try.

**Comment by ashawley** [comment]
@sourcekick One workaround for tests that may or may not work for you, is to disable fatal warnings (or deprecations) in sbt.

```scala
scalacOptions in Test ~= (_ filterNot (_ == "-Xfatal-warnings"))
```

**Comment by SethTisue** [comment]
:squirrel: https://github.com/scala/scala/pull/8373
