### ISSUE TITLE
scala.sys.process.Process doesn't understand quoting

### ISSUE THREAD

**Issue by scabug** [scala/bug#7947]
scala.sys.process.Process doesn't understand quoting of any kind.

For example:

```scala
import scala.sys.process._
"""java -classpath "/some folder/"  Main.main""".!
```
will invoke java with 4 arguments:
 - {code}-classpath{code}
 - {code}"/some{code}
 - {code}folder/"{code}
 - {code}Main.main{code}

This will obviously fail.

Also:
```scala
// this will succeed:
"""java -classpath /tmp/  Main.main""".!
// but this will fail:
"""java -classpath "/tmp/"  Main.main""".!
// because java receives "/tmp/" including quotes
// as classpath
```

All usual shells (bash & co., cmd, cygwin, powershell) properly strip the quotes before giving them to the application.

**Comment by SethTisue** [comment]
in 2.13, scala.sys will become its own module, at which point this could be addressed if someone cares to. closing since scala.sys issues will no longer be tracked here in scala/bug. I've made a "module:scala.sys" label so we can find relevant issues once the module has its own repo

**Comment by lrytz** [comment]
I'm not sure closing is a good idea yet. When starting the new repo and importing issues, it will be hard to find those closed issues that are valid, unfixed bug reports.

**Comment by SethTisue** [comment]
(I think it's okay because the label is brand new and the number of issues is not that large.)

**Comment by som-snytt** [comment]
> in 2.13, scala.sys will become its own module

What color is that nice label? I've been thinking about "absolute pitch", which people contrast with the more common ability to name colors. But can I name colors? It's not periwinkle, which is more like "lavender's blue, dilly, dilly." What's the difference between purple and violet? From Willy Wonka: "Violet, you're turning violet!"

**Comment by propensive** [comment]
Notwithstanding its incompleteness in some other areas, I have a project called [Guillotine](https://github.com/propensive/guillotine/) which provides a `sh""` interpolator, which correctly interprets quoting. Here are [the tests](https://github.com/propensive/guillotine/blob/master/src/tests/tests.scala), if anyone is interested.

**Comment by som-snytt** [comment]
There's also https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/cmd/CommandLineParser.scala which would probably suffice.

It's nothing to lose our heads over.

**Comment by som-snytt** [comment]
Oh, I see, the guillotine isn't just for chopping up lines. It slices! It dices! It executes stuff!

**Comment by som-snytt** [comment]
Footnote, jline also has "command parsing with quoting", maybe it's improved in jline 3, maybe it's not better than the current solution, and maybe it's a better dependency after modularization.
