### ISSUE TITLE
Odd build issue in BytePickle.scala on Fedora buildsystem

### ISSUE THREAD

**Issue by scabug** [scala/bug#7955]
Copied verbatim from https://github.com/scala/scala/issues/3096

On the Fedora build system I get sometimes the following error messages when I try to build scala:

[quick.library] case Ref() => Array.concat(s, ArrayByte)
[quick.library] ^
[quick.library] /builddir/build/BUILD/scala-2.10.3/src/library/scala/io/BytePickle.scala:67: error: type mismatch;
[quick.library] found : Int(1)
[quick.library] required: Byte
[quick.library] case Def() => Array.concat(s, ArrayByte)
[quick.library] ^
[quick.library] /builddir/build/BUILD/scala-2.10.3/src/library/scala/io/BytePickle.scala:70: error: type mismatch;
[quick.library] found : Int(0)
[quick.library] required: Byte
[quick.library] if (s(0) == (0: Byte)) (Ref(), s.slice(1, s.length))
[quick.library] ^
[quick.library] /builddir/build/BUILD/scala-2.10.3/src/library/scala/io/UTF8Codec.scala:19: error: type mismatch;
[quick.library] found : Int(-17)
[quick.library] required: Byte
[quick.library] final val UNI_REPLACEMENT_BYTES = ArrayByte
[quick.library] ^
[quick.library] /builddir/build/BUILD/scala-2.10.3/src/library/scala/io/UTF8Codec.scala:19: error: type mismatch;
[quick.library] found : Int(-65)
[quick.library] required: Byte
[quick.library] final val UNI_REPLACEMENT_BYTES = ArrayByte
[quick.library] ^
[quick.library] /builddir/build/BUILD/scala-2.10.3/src/library/scala/io/UTF8Codec.scala:19: error: type mismatch;
[quick.library] found : Int(-67)
[quick.library] required: Byte
[quick.library] final val UNI_REPLACEMENT_BYTES = ArrayByte
[quick.library] ^
[quick.library] 6 errors found
BUILD FAILED
/builddir/build/BUILD/scala-2.10.3/build.xml:1108: The following error occurred while executing this line:
/builddir/build/BUILD/scala-2.10.3/build.xml:918: The following error occurred while executing this line:
/builddir/build/BUILD/scala-2.10.3/build.xml:924: The following error occurred while executing this line:
/builddir/build/BUILD/scala-2.10.3/build.xml:882: Compilation failed because of an internal compiler error; see the error output for details.
Total time: 126 minutes 22 seconds

exit 1 RPM build errors: error: Bad exit status from /var/tmp/rpm-tmp.pTkm7q (%build) Bad exit status from /var/tmp/rpm-tmp.pTkm7q (%build) Child return code was: 1 EXCEPTION: Command failed. See logs for output. # ['bash', '--login', '-c', 'rpmbuild -bb --target noarch --nodeps builddir/build/SPECS/scala.spec'] Traceback (most recent call last): File "/usr/lib/python2.7/site-packages/mockbuild/trace_decorator.py", line 70, in trace result = func(args, *kw) File "/usr/lib/python2.7/site-packages/mockbuild/util.py", line 361, in do raise mockbuild.exception.Error, ("Command failed. See logs for output.\n # %s" % (command,), child.returncode) Error: Command failed. See logs for output. # ['bash', '--login', '-c', 'rpmbuild -bb --target noarch --nodeps builddir/build/SPECS/scala.spec'] LEAVE do --> EXCEPTION RAISED
The whole build can be foind at

http://koji.fedoraproject.org/koji/buildinfo?buildID=475595

This happens not allways, so I can't give you any additional information.

**Comment by SethTisue** [comment]
this looks likely no longer relevant
