### ISSUE TITLE
REPL jline scrolls past end of history

### ISSUE THREAD

**Issue by scabug** [scala/bug#7956]
Occasionally, I find myself scrolling past the end of history.

Sorry it's not minimized reproducibly.  This could be the "entering paste mode too fast" of 2.11.

```
scala> :qInternal error in history(size 19, index 19): current()
       :qInternal error in history(size 19, index 19): current()
       :qInternal error in history(size 19, index 19): current()
       :qInternal error in history(size 19, index 19): current()
       :qInternal error in history(size 19, index 19): current()
       :q
Ignoring duplicate entry ':q'
```

**Comment by SethTisue** [comment]
closing on the assumption this is no longer a problem in 2.13.2 (and perhaps no longer a problem in earlier versions, even)
