### ISSUE TITLE
The REPL should include "val" or "var" when printing definitions

### ISSUE THREAD

**Issue by scabug** [scala/bug#7960]
When you define a value or variable in the REPL, the name, type and initial value are printed but the "val" or "var" keyword is omitted:
```
scala> var x = 5
x: Int = 5
```

This can lead to confusing values with variables. It would be better if the REPL printed the leading "val" or "var" keyword:
```
scala> var x = 5
var x: Int = 5
```

**Comment by SethTisue** [comment]
closing this once since a similar but bit broader ticket exists: #10024
