### ISSUE TITLE
Console.readLine broken after running a Process with connectInput=true

### ISSUE THREAD

**Issue by scabug** [scala/bug#7963]
```scala
// ConnectInput.scala
import scala.sys.process._
object FooApp extends App {
  "ls -l".run(true).exitValue()
  Console.readLine("Foo bar ? ")
}
```

When running this code, one needs to press enter twice in order to exit the process. This problem does not occur when using run(false) instead, so it must somehow be related to how the standard input is connected.

(still got the issue by using scala.io.ReadStdin instead of Console).

I've found a similar issue described here => http://stackoverflow.com/questions/15774987/scala-process-exits-but-doesnt-clean-up-threads/15817760#15817760

**Comment by jrudolph** [comment]
I analyzed the issue in https://github.com/sbt/sbt/issues/3737#issuecomment-365976624. We basically need a port of the fix of this old sbt issue: https://github.com/sbt/sbt/issues/327.

**Comment by jrudolph** [comment]
(Not so sure about "good first issue" and "quickfix", though ;)

**Comment by som-snytt** [comment]
I remember thinking that upgrading to the Java 7 API could happen after `sys.process` became a module. Consumers could benefit from a shorter release cycle for the module.

**Comment by SethTisue** [comment]
I do think it's a good first issue in the sense that it doesn't involve compiler internals or juggling a lot of competing concerns, it's a focused thing that can be tackled in isolation.

There are precious few open issues in scala/bug that are actually easy and quick.

**Comment by som-snytt** [comment]
@SethTisue you need a label for "good GSOC issue."

**Comment by jrudolph** [comment]
> (I do think it's a "good first issue" in the sense that it doesn't involve compiler internals or juggling a lot of competing concerns, it's a focused thing that can be tackled in isolation. There are precious few open issues in scala/bug that are actually easy and quick.)

Haha, I see, everything is relative I guess.

**Comment by SethTisue** [comment]
in 2.13, scala.sys will become its own module, at which point this could be addressed if someone cares to. closing since scala.sys issues will no longer be tracked here in scala/bug. I've made a "module:scala.sys" label so we can find relevant issues once the module has its own repo

**Comment by mshibuya** [comment]
I'll tackle on this for [OSS Hackathon@ScalaMatsuri 2019](https://scalaconfjp.doorkeeper.jp/events/91355), though I'm not sure whether I can finish...
