### ISSUE TITLE
IncompatibleClassChangeError on getDeclaringClass

### ISSUE THREAD

**Issue by scabug** [scala/bug#7994]
Executing this simple snippet of code:
```
object Test {
  def main(args: Array[String]): Unit = {
    val outter = new MyTest {
      val inner = new MyTest {
      }
    }
  }
}

class MyTest {
  println(s"${getClass.getName} - ${getClass.getDeclaringClass}")
}
```
Results in:
```
java.lang.IncompatibleClassChangeError: Test$ and Test$$anon$1$$anon$2 disagree on InnerClasses attribute
java.lang.IncompatibleClassChangeError: Test$ and Test$$anon$1$$anon$2 disagree on InnerClasses attribute
	at java.lang.Class.getDeclaringClass0(Native Method)
	at java.lang.Class.getDeclaringClass(Class.java:1101)
```

**Comment by SethTisue** [comment]
closing backend tickets which are likely stale; comment and/or reopen if you have evidence this is still applicable

**Comment by lrytz** [comment]
Fixed, the 2.12 backend got an onvehaul of InnerClass attribute computation. Let's verify the result is correct and add a regression test to https://github.com/scala/scala/tree/v2.13.0-M3/test/files/jvm/innerClassAttribute

**Comment by adriaanm** [comment]
@lrytz did this end up getting verified as fixed?

**Comment by adriaanm** [comment]
It doesn't crash, at least. I'll leave it open in case `null` was not the expected result for the declaring class..
```
scala-2.12.7-bin-f2129b9/bin/scala ~/Library/Preferences/IdeaIC2018.2/scratches/scratch_7.scala
Main$$anon$1 - null
Main$$anon$1$$anon$2 - null
```

**Comment by jxnu-liguobin** [comment]
Empty seems wrong? I am ready to look at the issue, where are the relevant codes or files? thanks

**Comment by lrytz** [comment]
https://docs.oracle.com/en/java/javase/16/docs/api/java.base/java/lang/Class.html#getDeclaringClass() says

> If the class or interface represented by this Class object is a member of another class, returns the Class object representing the class in which it was declared

The two anonymous classes are both not "member" classes, so `null` is the correct value.

https://github.com/scala/scala/blob/8a2cf63ee5bad8c8c054f76464de0e10226516a0/src/compiler/scala/tools/nsc/backend/jvm/BTypes.scala#L352-L353

@jxnu-liguobin you could add a test case, that would be welcome.

Just tested with Java, it does the same:
```java
public class Test {
  public static void main(String[] args) {
    Object o = new MyTest() {
      Object i = new MyTest() { };
    };
  }
}

class MyTest {
  public MyTest() {
    System.out.println(this.getClass().getName());
    System.out.println(this.getClass().getDeclaringClass());
  }
}
```

```
Test$1
null
Test$1$1
null
```

**Comment by jxnu-liguobin** [comment]
ok, https://github.com/scala/scala/pull/9553/files, i have added scala test case
