### ISSUE TITLE
Bashisms prevent the scala scripts from running on HP-UX

### ISSUE THREAD

**Issue by scabug** [scala/bug#7998]
Reported by Ronald Steinhau on the mailing list: https://groups.google.com/forum/#!topic/scala-user/tndKwnHu3mo

The scala start script needs bash and (at least by default) bash is not available under HP-UX (and some admin's are not allowed to install
bash on it). Unfortunately the script contains bash only commands (e.g. declare) that are not POSIX compliant and are not trivial to replace. Maybe someone finds the time to rewrite the start script to be POSIX compliant. This would make life easier for such scenarios.

When you run the script with "ksh" (or just the sh, if it is not redirected to bash) you will get errors. The "declare" statement and the usage of indexed variables is the critical one. As "ksh" is available on HP-UX and many other environments it may be the one to test against.

**Comment by SethTisue** [comment]
while this was not actually fixed, I find it hard to imagine that in 2018 running on bash-less systems is still a concern?
