### ISSUE TITLE
ListBuffer relies upon deprecated Forwarder trait.

### ISSUE THREAD

**Issue by scabug** [scala/bug#8025]
Deprecating Forwarders has left ListBuffer relying upon deprecated functionality.  ListBuffer should be made independent of Forwarders.

**Comment by xuwei-k** [comment]
- https://github.com/scala/scala/commit/878e7d3e0d14633d19bac47dc9b532a54eab6379#diff-4858004d7457edde08b4ac6bfed91839
- https://github.com/scala/scala/blob/v2.13.0-M4/src/library/scala/collection/mutable/ListBuffer.scala#L31-L36

Forwarders removed since Scala 2.13.0-M4
