### ISSUE TITLE
Adopt Slick's ClosableIterator in scala.collection.JavaConversions

### ISSUE THREAD

**Issue by scabug** [scala/bug#8028]
I'm using com.googlecode.jcsv.reader.CSVReader<E> to read lines in from a text table. It works well, but I have to close things myself.

scala.collection.JavaConversions provides iterableAsScalaIterable, which is great, until it's time to close the iterator.

Slick has ClosableIterator, http://slick.typesafe.com/doc/0.11.0/api/index.html#scala.slick.util.CloseableIterator , which implements both Closable and Iterator.

Please adopt that, or add it to JavaConversions, maybe as closableIterableAsScalaIterable. 

I think this request fits into the larger automatic resource management puzzle. (I've been trying to get com.jsuereth's scala-arm_2.10 to work with the csv library without success.)

Thanks,

Dave

**Comment by NthPortal** [comment]
Is this resolved by scala/scala#6907?
