### ISSUE TITLE
Do not mutate List in Types.scala

### ISSUE THREAD

**Issue by scabug** [scala/bug#8061]
src/reflect/scala/reflect/internal/Types.scala  Mutates the tail of List.  This is not necessary and in the way of making List internally Immutable.

The main problem can best be described via:
https://gist.github.com/jrudolph/6552186

and
https://groups.google.com/forum/?fromgroups=#!topic/scala-internals/P7WNVkJQdHk

**Comment by SethTisue** [comment]
It's not clear to me whether some change to `Types.scala` might still be desirable.

Regardless, the whole `List`/`ListBuffer` mutability situation is considered resolved by scala/scala#6425, so I'm going to presumptively close this.
