### ISSUE TITLE
sanity checks for macro expansions

### ISSUE THREAD

**Issue by scabug** [scala/bug#8066]
There are some macro-induced compiler crashes in SuperAccessors, LambdaLift and GenICode (some of those documented at https://github.com/sbt/sbt/commit/3b213e59caafdc3b28bfbaf124e80a4584caf3aa) that we can easily avoid by providing a sanity-checking traverser for macro expansions. I will get to that this week.

**Comment by SethTisue** [comment]
closing since this never happened and it's far from clear that a change like this is likely ever to happen in the current macro system
