### ISSUE TITLE
Scaladoc generation can create invalid HTML.

### ISSUE THREAD

**Issue by scabug** [scala/bug#8073]
```
@implicitNotFound(
"""
some string
that spans multiple lines
>= 36 chars
"""
```

According to this: https://github.com/scala/scala/blob/v2.10.3/src/compiler/scala/tools/nsc/doc/html/page/Template.scala#L886-L889

a string thats >= 36 characters will be put into an attribute value, so on the Scaladoc the user can see the whole message when hovering over the implicitNotFound as opposed to having it crammed on the screen.

However, before this happens, it seems it translates any newline characters into `<br />`. So 

```
"""foo
bar"""
```

gets translated into `foo<br />bar`. The check for >= 36 characters happens after this, and so it is possible for the break line tag to appear in the tag attribute. I don't believe HTML allows for angle brackets in tag attributes.

**Comment by Philippus** [comment]
This seems to have been solved by @adriaanm in https://github.com/scala/scala/pull/6436
