### ISSUE TITLE
Unhelpful type mismatch error when parameter type does match but return type doesn't

### ISSUE THREAD

**Issue by scabug** [scala/bug#8074]
I tried to call the method "insert" on an "org.squeryl.Table[E]", but I got this compilation error:

[error]  found   : E
[error]  required: org.squeryl.Query[E]
[error]             underlyingTable.insert(newEntity)

The problem was not, in fact, this. In fact, a Query[E] is **not** required, because the insert method is overloaded to also take an E. The real problem, I think, was that the return type of the insert method that takes an E did not match the required return type inferred from the return type I had given the method. Once I added another line immediately after this one, the error disappeared.

**Comment by SethTisue** [comment]
I'm just going to close this since it doesn't include a proper repo (what version of squeryl?) but also because we tend not to keep individual open tickets on improvable error messages.

**Comment by som-snytt** [comment]
"Return type" does guide overload resolution because of applicability.

The lack of info makes it difficult to know what code was in use; the overload that takes a `Query` existed for a while but was never implemented? The minimization might be some permutation of the following.

Approximation for later:
```
import scala.language.implicitConversions

class Table[A] {
  def f(a: A): A = a
  //def f(q: Query[A]): Unit = ???
  def f(as: Iterable[A]): Unit = ()
}
class Query[A] // extends Iterable[A]

class C {
  implicit def cv[R](q: Query[R]): Iterable[R] = Nil

  val t: Table[String] = new Table[String]
  val q: Query[String] = new Query[String]

  def fail1(): Unit = t.f("")
  def ok() = t.f(q)
}

object Test extends App {
  val c = new C
  println(c.ok())
  println(c.fail1())
}
```
