### ISSUE TITLE
Creation of names prefixed with other names isn't straightforward in quasiquotes

### ISSUE THREAD

**Issue by scabug** [scala/bug#8078]
Let's say we want to create a bunch of definitions of vals v1...vN with values equal to N:
```scala
(1 to N).map { i => 
  val name = TermName(s"v$i")
  q"val $name = $i"
}
```
What I would like to write instead is:
```scala
(1 to N).map { i => q"val v$i = $i" }
```
Semantics of this is not clear though, especially considering non-name splices into names and requires some brainstorming.

**Comment by SethTisue** [comment]
closing all quasiquotes tickets; see #10755
