### ISSUE TITLE
Compiler error when creating runnable inside class constructor

### ISSUE THREAD

**Issue by scabug** [scala/bug#8162]
The following code fails to compile:
```
package bug

class Bug {	
	def this(param : Int) {
		this();
		val runnable = new Runnable() {
			override def run() {
				method();
			}
		};
	}
	
	def method() : Unit = {}
}
```
Compiles fine if invocation of method() is not attempted. 
Compiles fine if constructor is changed into simple method.

**Comment by SethTisue** [comment]
if something "fails to compile", please include the error message
