### ISSUE TITLE
Imprecise signature of InstanceMirror.reflectField

### ISSUE THREAD

**Issue by scabug** [scala/bug#8189]
Currently the aforementioned method takes TermSymbol, which isn't precise enough, as such a symbol can be whatever - a local variable, a method, a module. It would be nice to have the abstraction of FieldSymbol that would distinguish acceptable arguments of reflectField.

**Comment by SethTisue** [comment]
seems unlikely this is worth an API change at this point, but comment/reopen if you disagree
