### ISSUE TITLE
Assign is context-sensitive due to named arguments

### ISSUE THREAD

**Issue by scabug** [scala/bug#8206]
At the moment Assign is context sensitive due to the fact that it can't be distinguished from named argument:
```scala
def f(x: Any) = x 
var x = ...
f(x = 2) 
```
In order to minimize ambiguity we can force people who really want to have assign in that position should add extra parens or curly braces to disambiguate:
```scala
f(x = 2) // named arg
f((x = 2)) // assign
f { x = 2 } // assign
```
This would allow us to replace AssignOrNamedArg tree with just NamedArg.

**Comment by SethTisue** [comment]
@lrytz this is no longer applicable thanks to the ambiguity going away in 2.13, right?
