### ISSUE TITLE
Get rid of pervasive casts in the reflection API

### ISSUE THREAD

**Issue by scabug** [scala/bug#8220]
At the moment, reflection code is very often plagued by casts. Not those brutal and obvious asInstanceOf's, but rather the sneaky asXXX methods on symbols. 

Got a method from a list of members and want to figure out its return type - do a cast. Got a class from Type.typeSymbol and want to check out its type params - do a cast. And so on, and so forth.

This has to stop.

**Comment by SethTisue** [comment]
the Scala 2 reflection API is highly unlikely to undergo any sweeping changes
