### ISSUE TITLE
Better usability for reflective invocations

### ISSUE THREAD

**Issue by scabug** [scala/bug#8221]
In the current scheme of things, performing reflective invocations that are more or less simple in such languages/systems as Java and C# is quite convoluted.

When you want to reflectively call a method on a given object in Java, you figure out the object's class, then look up the corresponding `java.lang.reflect.Method` and finally simply call `Method.invoke`, passing the given object and the arguments.

In Scala this requires a significant amount of ceremony. First you have to obtain a runtime mirror, then you use it to reflect the object's class symbol, then you look up a method symbol in that class, then you need to obtain a method mirror using the calculated method symbol, and only then can you call apply on the resulting mirror.

**Comment by SethTisue** [comment]
chances of this ever getting addressed in Scala 2 seem slim
