### ISSUE TITLE
Unify metadata handling in reflection API

### ISSUE THREAD

**Issue by scabug** [scala/bug#8222]
It seems like it's high time to generalize and unify our approach to various pieces of metadata under annotations.

On the one hand, we have flags (#6267) and DocDefs (#7993) that can be represented as annotations. They can also be joined by visibility modifiers, associatedFile and maybe even attachments, giving us uniform way to store, query and update metadata on reflection artifacts.

On the other hand, it seems that we can drastically simplify our annotations by replacing them with plain trees. We have to decide on the exact shape of those trees (at the moment, I like Denys's idea of translating `@foo(bar, baz)` into a typechecked invocation of `foo(bar, baz)` where `foo` can be whatever's in scope rather than `new foo(bar, baz)` where `foo` can only be a subclass of Annotation like it's done now) and on Java compatibility policy, but once we do that, everything is going to become so much simpler: https://groups.google.com/forum/#!topic/scala-internals/8v2UL-LR9yY

**Comment by SethTisue** [comment]
reflection API in Scala 2 is pretty frozen these days
