### ISSUE TITLE
Specialization misses to override a method

### ISSUE THREAD

**Issue by scabug** [scala/bug#8242]
trait A[@specialized (Int) T] {
  def get: T
  def check(t: T): Boolean  
}

class Bug[@specialized (Int) T](val a: A[T]) {
  def aGet = a.get
  def getCheck() = a.check(a.get) 
}

In  Bug$mcI$sp class, aGet correctly receives aGet$mcI$sp method with calls to get$mcI$sp, but getCheck method isn't overridden - so ends up using check and get methods with boxing, instead of using check$mcI$sp and get$mcI$sp methods.
I.e. methods that call specialized methods, but don't have specializable argument/return type should be overridden in specialized classes.

**Comment by pabloazul** [comment]
It seems unlikely that this is going to progress in Scala 2 unless someone appears with a concrete proposal, so closing. If anyone has a proposal please feel welcome to reopen.
