### ISSUE TITLE
There is no easy way to extract types from nested trees in quasiquote

### ISSUE THREAD

**Issue by scabug** [scala/bug#8257]
```scala
scala> val q"..$_; $_($_: ${tpe: Type})" = 
     |   typecheck(q"""
     |     def id(i: Int) = i
     |     val a = 42
     |     id(a)
     |   """)
tpe: reflect.runtime.universe.Type = Int
```
i.e. piggyback on ascription syntax to extract tree.tpe in pattern matching.
Alternatively the same can be done through magic annotation as in #8250 but ascription looks more elegant for this purpose.

**Comment by SethTisue** [comment]
closing all quasiquotes tickets; see #10755
