### ISSUE TITLE
NoSuchMethodError at runtime when -Xmax-classfile-name 72 is used and when calling method whose return type has long class name

### ISSUE THREAD

**Issue by scabug** [scala/bug#8298]
I have some code which calls the following method in the following inner class in scalaz 6.0.4:

```
final class ApplicativeBuilder3[C](c: M[C]) {

  ...

  def |@|[D](d: M[D]) = new ApplicativeBuilder4[D](d)

    final class ApplicativeBuilder4[D](d: M[D]) {
      ...
    }
}
```

When running test or run in my Play application, I get the following error:

java.lang.NoSuchMethodError: scalaz.ApplicativeBuilder$ApplicativeBuilder3.$bar$at$bar(Ljava/lang/Object;)Lscalaz/ApplicativeBu$$$$fedb325b5cbd723ea8eb3a81591dc560$$$$ativeBuilder4;

javap shows:

```
 /usr/lib/jvm/jdk1.6.0_32/bin/javap -classpath /home/robin/.ivy2/cache/org.scalaz/scalaz-core_2.10/jars/scalaz-core_2.10-6.0.4.jar 'scalaz.ApplicativeBuilder$ApplicativeBuilder3'
Compiled from "ApplicativeBuilder.scala"
public final class scalaz.ApplicativeBuilder$ApplicativeBuilder3 extends java.lang.Object{
    public final java.lang.Object scalaz$ApplicativeBuilder$ApplicativeBuilder3$$c;                                                                                     
    public java.lang.Object apply(scala.Function3, scalaz.Functor, scalaz.Apply);                                                                                       
    public java.lang.Object tupled(scalaz.Functor, scalaz.Apply);                                                                                                       
    public scalaz.ApplicativeBuilder$ApplicativeBuilder3$ApplicativeBuilder4 $u229B(java.lang.Object);                                                                  
    public scalaz.ApplicativeBuilder$ApplicativeBuilder3$ApplicativeBuilder4 $bar$at$bar(java.lang.Object);
    public scalaz.ApplicativeBuilder scalaz$ApplicativeBuilder$ApplicativeBuilder3$$$outer();
    public scalaz.ApplicativeBuilder$ApplicativeBuilder3(scalaz.ApplicativeBuilder, java.lang.Object);
}
```

So it looks like scalac is regenerating the class name for the return type, when it should be using the existing return type verbatim, because this is a .class file dependency not a source dependency.

Here is a piece of code to reproduce the bug:

```
object MaxClassnameBug extends App { 

  import scalaz._
  import Scalaz._

  val s = "hi".success[String]
  s |@| s |@| s |@| s

}
```

I obviously cannot incorporate the scalaz code into this file otherwise the test case no longer be a test case - the fact that the dependency is a .class file is an essential part of this bug!

I compiled this as follows:

```
$ ~/opened/scala-2.10.2/bin/scalac -Xmax-classfile-name 72 -classpath /home/robin/opened/scala-2.10.2/lib/scala-library.jar:.:/home/robin/.ivy2/cache/org.scalaz/scalaz-core_2.10/jars/scalaz-core_2.10-6.0.4.jar MaxClassnameBug.scala
```

**Comment by SethTisue** [comment]
`-Xmax-classfile-name` is no longer supported: https://github.com/scala/scala/pull/7497

**Comment by som-snytt** [comment]
This is along the lines of https://github.com/scala/bug/issues/11277 (don't compactify Java names), to say don't compactify names from separately compiled classes which may have arbitrary flags set. (There is an effort to encode compiler settings in the class file.)

Instead of respecting separate compilation, the flag was removed in favor of a fixed maximum. (As noted above.)

It seems to me that the use case is better served by a post-processing step to prepare class files for the target environment.
