### ISSUE TITLE
REPL keybindings: ctrl-y should not kill session

### ISSUE THREAD

**Issue by scabug** [scala/bug#8307]
`scala`, like (I think all) other interactive intepreters (like Ruby's `irb`, Python, etc) support things like `C-r` for reverse command search, `C-a` & `C-e` for home/end, `C-k` for killing (cutting) a line to the end, `C-f` and `C-b` for moving, `C-d` for forward-delete-char, etc; however, a really annoying deviation from this is the lack of support for `C-y` (paste last killed item from kill ring) (and therefore probably `Alt-y` as well), and not only lack of support but unexpected behavior: `C-y` actually stops the interpreter just the same as `C-z`.

(using `C-` to mean `Ctrl-`)

**Comment by SethTisue** [comment]
> C-y actually stops the interpreter just the same as C-z

this is no longer the case (in 2.11.12 or 2.12.11 or 2.13.1 or 2.13.2)

> lack of support for C-y (paste last killed item from kill ring)

on this kind of thing, we take whatever JLine 3 gives us (JLine 3 is what we're using as of Scala 2.13.2; before that we were on JLine 2)

it works for me in both 2.13.1 and 2.13.2, not sure about older versions
