### ISSUE TITLE
Overloading Resolution + Vararg methods: example should be ambiguous

### ISSUE THREAD

**Issue by scabug** [scala/bug#8344]
Related to #4728. This compiles, the second alternative is chosen
```scala
object t {
  def f(x: Object) = 1
  def f(x: String*) = 2
}
t.f("") // returns 2, should be ambiguous.
```

According to #4728, it should be ambiguous. I assume the compiler thinks that `String*` conforms to `Object`. Maybe because it tests if `Seq[String]` conforms to `Object`, not sure.

**Comment by adriaanm** [comment]
Weird. You can't apply a `String*` to a method expecting an `Object`, but you can vice versa, so it should not be ambiguous, but it also shouldn't pick the `String*` overload... I think... 🤔

**Comment by adriaanm** [comment]
While deciding which one is more specific, you get the following calls to `isCompatibleArgs`:
```
isCompatibleArgs false List(Object) <:< List(String)
isCompatibleArgs true List(String*) <:< List(Object)
```

the second one should be false too
