### ISSUE TITLE
java.lang.IncompatibleClassChangeError when using Java-class, wich implements @interface

### ISSUE THREAD

**Issue by scabug** [scala/bug#8348]
When invoking method from instances of class, which implement interfaces, declared in Java as `public @interface SomeInterface` - then throws `java.lang.IncompatibleClassChangeError`. But if use that in Java classes - all works fine. Now to solve this problem used workaround which use static methods from Java-class with additional argument of this-object.
for example:

```java
// In Java
public @interface TableColumn {
	int width() default -1;
}
public class TableColumnImpl implements TableColumn {.......}
public class TableWorkAround { 
 public int width(TableColumnImpl column) { return column.width();}
}
```

```scala
// In Scala
...
val column: TableColumnImpl = getSomeFuncReturn_TableColumnImpl
val widthScala = column.width // throw IncompatibleClassChangeError
val widthJava = TableWorkAround.width(column) // works fine
```

when disassembly 
in scala call of method -> invokeinterface
in java call of method -> invokevirtual

Full bundle, which replicates this behaviour in bundle.zip, which attached

**Comment by hrhino** [comment]
This appears to have been fixed as a by-product of 7d51b3fd1569917cb804363bd418466a306f5c89.
