### ISSUE TITLE
Consider different syntax alternatives for quasiquotes

### ISSUE THREAD

**Issue by scabug** [scala/bug#8401]
Current string-interpolation based syntax has serious usability problems wrt nesting:
```scala
(stat: Tree, i: Int) => 
  q"""println(s"executing $${${stat.toString}}"); $stat"""
```
1. Any use of nested interpolators requires """ quotations even for small snippets
2. Unquoting into another interpolator requires lots of $$$$$$$ and { { { } } } that can be quite hard to read
3. Impossible to express nesting that is more than one level deep

I'm not sure if it's possible to fix those issues in string interpolation itself as it was not really designed for this purpose.

**Comment by SethTisue** [comment]
closing all quasiquotes tickets; see #10755
