### ISSUE TITLE
lexing of non-printable char literals diverges from spec

### ISSUE THREAD

**Issue by scabug** [scala/bug#8423]
according to the specification -> Lexical Syntax -> Character Literals and String Literals, non-printable characters are not valid literals. However, the literal '\u000A' as well as a literal newline character are accepted by the lexer (the spec explicitly mentions  '\u000A' as being illegal)

In strings, the lexer also accepts "\u000A" though it doesn't accept a literal newline character

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/6810 which amended the spec text.

I think the correction says that the character can't be a newline, but it can be a unicode newline or a normal escape char `\n`.
