### ISSUE TITLE
do not add all extension libraries to bootclasspath

### ISSUE THREAD

**Issue by scabug** [scala/bug#8472]
https://github.com/scala/scala/blob/v2.11.0-RC3/src/compiler/scala/tools/ant/templates/tool-unix.tmpl#L88

This will lead to difficulties with someone trying to use a different Akka version using the `scala` script, since akka-actor.jar will be used in the version that is shipped with the Scala distribution, not what is specified using the `-cp` option.

**Comment by SethTisue** [comment]
> scala-parser-combinators, scala-xml, and scala-swing remain affected

not anymore, these were all unbundled

it's not clear this is otherwise actionable or that anyone is still concerned. hence, closing
