### ISSUE TITLE
NumericRange[Double] take and drop are broken

### ISSUE THREAD

**Issue by scabug** [scala/bug#8518]
scala> val x = 0.0 to 1.0 by 0.1
x: scala.collection.immutable.NumericRange[Double] = NumericRange(0.0, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6, 0.7, 0.7999999999999999, 0.8999999999999999, 0.9999999999999999)

scala> x.take(3)
res1: scala.collection.immutable.NumericRange[Double] = NumericRange(0.0, 0.1, 0.2)

scala> x.drop(3)
res2: scala.collection.immutable.NumericRange[Double] = NumericRange(0.30000000000000004, 0.4, 0.5, 0.6, 0.7, 0.7999999999999999, 0.8999999999999999, 0.9999999999999999)

So far so good.

scala> x.drop(3).take(3)
res3: scala.collection.immutable.NumericRange[Double] = NumericRange(0.30000000000000004, 0.4)

Why only two values? Where's 0.5?

scala> x.drop(6)
res4: scala.collection.immutable.NumericRange[Double] = NumericRange(0.6000000000000001, 0.7000000000000001, 0.8, 0.9)

And where did the last value disappear now?

This is all due to floating point representation inaccuracies, but I don't think this is acceptable behavior. x.take(3) should not return a length 2 sequence when x is length 8.

I'll try to make a patch for this over the weekend.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6468
