### ISSUE TITLE
IMain interpret does not reset context classloader

### ISSUE THREAD

**Issue by scabug** [scala/bug#8521]
Calling `interpret` sets the current thread's context classloader, but fails to reset it to its previous state when returning from that method.

The following workaround illustrates the problem:

```scala
    val th = Thread.currentThread()
    val cl = th.getContextClassLoader
    try {
      imain.interpret(text)
    } finally {
      th.setContextClassLoader(cl)
    }
```

Jason Zaugg suggests that the following might be the regression: https://github.com/scala/scala/commit/3a30af1#diff-36a995091016ecd5cdb97e267764e05aL538

**Comment by som-snytt** [comment]
https://users.scala-lang.org/t/java-scriptengine-cannot-cast-to-scripted/1166

recaps the reproduction from two years ago.

**Comment by som-snytt** [comment]
Another mode of suffering

https://gitter.im/scala/scala?at=59b75be4177fb9fe7eacd7f1

where log4j loads script engines. And then everything breaks.

**Comment by Sciss** [comment]
I was just bitten by this again in 2.13.0-M5. Thought the issue was solved. I don't really understand [this merge](https://github.com/scala/scala/pull/5657). Is it only for Scala 2.12? In the meantime I will reinstall my patch in my IMain subclass like so

```scala
      // work-around for SI-8521 (Scala 2.11.0)
      override def interpret(line: String, synthetic: Boolean): Results.Result = {
        val th = Thread.currentThread()
        val cl = th.getContextClassLoader
        try {
          super.interpret(line, synthetic)
        } finally {
          th.setContextClassLoader(cl)
        }
      }
```

I think the issue should be re-opened and tagged 2.13.x?

**Comment by som-snytt** [comment]
@Sciss yes, it was never forward-ported over the scary REPL refactor. I'll refresh my memory and make a PR. One really does take forward-merging for granted.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/7544 for 2.13 (https://github.com/scala/scala/pull/5657 for 2.12)
