### ISSUE TITLE
explain interaction of typing application to named argument and implicit scope

### ISSUE THREAD

**Issue by scabug** [scala/bug#8571]
Let's make sure the spec adequately describes what should happen while  type checking (example by Alexander Podkhalyuzin), which is at the intersection of implicit search (argument types of expected method contribute to the implicit scope) and named arguments (need to type argument to populate said implicit scope). Not sure Dynamic is really relevant here.

```scala
class A extends Dynamic {
  def applyDynamicNamed(name: String)(v: (String, Any)) = "something"
}
val a = new A
var x = "text"
a.foo(x = "something")
```

For example we want to understand if x is named parameter or it's reference to "var x". To understand that it's named parameter we need to check a.foo reference. But 'a' doesn't contain method 'foo', so we need to go through all steps:
1. Implicit search.
2. Implicit search in extended scope (companion objects of type)
3. Dynamic type

If we use argument types for extended implicit search then we need to evaluate type of 'x = "something"', but it requires to understand if x is named or not. So we can't resolve x as named parameter and it would lead to compiler error.

**Comment by som-snytt** [comment]
Or, just stipulate that `f(x = "something")` only means named arg. That happened at some point, but not sure if it's represented in the spec.

**Comment by SethTisue** [comment]
> That happened at some point

deprecated https://github.com/scala/scala/pull/6089 (2.12), changed https://github.com/scala/scala/pull/6092 (2.13) — not sure if @lrytz (or any of us) evaluated whether a spec change was necessary (neither PR has one)

**Comment by lrytz** [comment]
It seems the spec is representing the current behavior

> an argument expression ´e_i´ is a named argument if it has the form ´x_i=e'_i´ and ´x_i´ is one of the parameter names ´p_1, \ldots, p_n´.

https://github.com/scala/scala/blob/v2.13.12/spec/06-expressions.md#function-applications
