### ISSUE TITLE
Odd Specialization Bug with Breeze

### ISSUE THREAD

**Issue by scabug** [scala/bug#8572]
I can't minimize this. I apologize in advance.

This bug: https://github.com/scalanlp/breeze/issues/65

Basically, sometimes breeze.linalg.DenseVector[Int]#apply(index: Int):Int will kill the compiler (with specialized turned on). Not always, but sometimes.  breeze.linalg.DenseVector[Double]#apply(index: Int):Double does not. 
(Note that DenseVector is specialized on both Double and Int.  )

Further note that if we use DenseVector[Int]#valueAt(i: Int):Int (which is literally just an alias for apply), everything is just fine. apply is defined in DenseVector's super-trait Vector, while valueAt is not. So, I suspect it's inheritance related. Vector is specialized on the same types as DenseVector

I've sometimes seen and worked around similar bugs in other places, always with Int.

**Comment by SethTisue** [comment]
closing (unless it can be minimized and confirmed to occur in current Scala)
