### ISSUE TITLE
Provide common function class for by-name thunks which are constants

### ISSUE THREAD

**Issue by scabug** [scala/bug#8600]
By-name thunks are often used for things like logging expressions, Option.fold(), and various other situations where an argument may well be completely ignored -- so as to avoid the extra computation. For instance:

```scala
def warn(s: => String) {
  println(s)
}
```

However, this always generates an anonymous function class, even when the expression is known by the compiler to be constant. Add enough of these (particularly debug logging), and an app can get pretty unwieldy in terms of anonymous class proliferation.

If the compiler is able to determine that the argument is indeed constant, or a variable that can be passed as-is without computation, it could collapse all such instances into a constant function helper class, for instance:

```scala
package scala.runtime
case class ConstantFunction0[T](apply: T) extends AbstractFunction0[T]
```

Then, rather than generate an anonymous function class consisting only of one load opcode for a constant field value, or a single final field, it could use the above class as-is.

**Comment by SethTisue** [comment]
> Once we flip to Java8 style closures (which might yet happen in 2.12),

It happened!
