### ISSUE TITLE
Future.retryable

### ISSUE THREAD

**Issue by scabug** [scala/bug#8615]
Proposed extension to `object Future` to provide an instantiator method which can automatically retry based on a `Throwable` predicate, without stacking on a `recoverWith` combinator for each retry:

```scala
  def retryable[T](shouldRetry: (Throwable) => Boolean)(body: => T)(implicit executor: ExecutionContext): Future[T] = {
    val promise = Promise[T]()

    def startFuture() {
      Future {
        body
      }.onComplete {
        case Failure(t) if shouldRetry(t) => startFuture()
        case x => promise.complete(x)
      }
    }

    startFuture()
    promise.future
  }
```

This could optionally be accompanied by a convenience method which counts an integer number of retries:

```scala
  def retryable[T](retries: Int)(body: => T)(implicit executor: ExecutionContext): Future[T] = {
    var retrynum = 0
    retryable { t =>
      retrynum += 1
      retrynum <= retries
    }(body)
  }
```

The retry loop will re-enqueue the original function body back onto the original `ExecutionContext` if the function results in a `Failure` and the `shouldRetry` predicate returns `true`. All the publicly exposed API goes through the instantiated `DefaultPromise`, shielding those calls from the underlying `Future` which may be replaced in case of a retry.

**Comment by SethTisue** [comment]
> Having thought about it for a while, I don't think it makes sense to add this specific feature to the stdlib

ok, closing
