### ISSUE TITLE
Floating point ranges don't work

### ISSUE THREAD

**Issue by scabug** [scala/bug#8620]
Floating point ranges don't work: precision issues, 0 to 0.3 by 0.1 fails, etc.  See more details at #4370 but closing that one because integral ranges DO work.

Getting floating-point ranges to work is a rat's nest.  Current best idea is to "fix" by deprecating them.

**Comment by eed3si9n** [comment]
I have a PR here - https://github.com/scala/collection-strawman/pull/489

```scala
scala> import strawman.collection.immutable.NumericRange
import strawman.collection.immutable.NumericRange

scala> val r1 = NumericRange(0.0, 0.3, 0.1)(scala.math.Numeric.DoubleAsIfIntegral)
r1: strawman.collection.immutable.NumericRange.Exclusive[Double] = NumericRange 0.0 until 0.3 by 0.1

scala> r1.toList
res0: strawman.collection.immutable.List[Double] = List(0.0, 0.1, 0.2)

scala> r1 foreach { scala.Predef.println }
0.0
0.1
0.2
```

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6468
