### ISSUE TITLE
Compiler hangs on aliased existential type with -Xexperimental

### ISSUE THREAD

**Issue by scabug** [scala/bug#8629]
The following code compiles fine with scalac with no arguments, but scalac -Xexperimental seems to hang:

object CompilerBug {
  trait EnumLike[T] {}
  type GenericEnumLike = (EnumLike[T] forSome { type T <: EnumLike[T] })
  implicitly[(EnumLike[T] forSome { type T <: EnumLike[T] }) =:= GenericEnumLike]
}

**Comment by magnolia-k** [comment]
The `-Xexperimental` option is no longer used in Scala 2.13, so this issue can be closed.

**Comment by som-snytt** [comment]
Also, doesn't hang.
