### ISSUE TITLE
can't infer type args for scalaz.Leibniz.symm ?

### ISSUE THREAD

**Issue by scabug** [scala/bug#8655]
code at http://scastie.org/5684

In a call to: 

{code}Leibniz.symm(G.leibniz){code}  where {code}G.A = A0{code}

I get this inference failure:

```scala
[error]  found   : scalaz.Leibniz.===[FA,G.M[G.A]]
[error]     (which expands to)  scalaz.Leibniz[Nothing,Any,FA,G.M[G.A]]
[error]  required: scalaz.Leibniz[L,Any,FA,G.M[G.A]]
[error]     Leibniz.symm(G.leibniz)
[error]                    ^
```

which seems silly.  `L` should be inferred as `Nothing` in this case.  

{code}Leibniz.symm[Nothing,Any,FA,G.M[G.A]](G.leibniz){code}

compiles fine, but is unnecessarily ugly.

**Comment by SethTisue** [comment]
needs minimization.

**Comment by joroKr21** [comment]
duplicates #1570 and #9453
