### ISSUE TITLE
Add scala.math.Ordering for scala.Symbol

### ISSUE THREAD

**Issue by scabug** [scala/bug#8664]
A default implicit Ordering seems to exist for all built-in types and some other classes (e.g. BigDecimal, Option[T]). I would think Symbol belongs in this distinguished category of types too, since it even has a literal syntax. But it has no Ordering:

scala> scala.collection.SortedSet('a, 'b)
<console>:18: error: No implicit Ordering defined for Symbol.
              scala.collection.SortedSet('a, 'b)

**Comment by NthPortal** [comment]
Should be trivial to add this to `scala.math.Ordering`. I can look into it tonight.
