### ISSUE TITLE
Concurrent Maps do not honor withDefaultValue with .get()

### ISSUE THREAD

**Issue by scabug** [scala/bug#8665]
`TrieMap.apply()` honors `withDefaultValue` but `TrieMap.get()` does not. This bug also affects java concurrent maps wrapped with `asScala`. Sorry about the formatting, can't figure out how to make it show up properly here. Please ignore the extra newlines before and after square braces.

```scala
scala>  val tm = TrieMap.empty[String, String].withDefaultValue("default")
tm: scala.collection.mutable.Map[String,String] = Map()

scala> tm.get("")
res35: Option\[String\] = None

scala> tm("")
res36: String = default

scala>  val chm = new java.util.concurrent.ConcurrentHashMap[String, String].asScala.withDefaultValue("default")
chm: scala.collection.mutable.Map[String,String] = Map()

scala> chm.get("")
res37: Option[String] = None

scala> chm("")
res38: String = default
```

**Comment by SethTisue** [comment]
there's also #8099, would someone like to look at both tickets and check the 2.13 behavior and see if both tickets should remain open?

**Comment by NthPortal** [comment]
at the very least, I think the tickets can be merged (perhaps with an updated title for one?). the issue does not appear to be specific to concurrent maps, but this ticket has more detail

**Comment by SethTisue** [comment]
okay, duplicate of #8099
