### ISSUE TITLE
Side effects incorrectly elided by Erasure's handling of Unit

### ISSUE THREAD

**Issue by scabug** [scala/bug#8666]
next code:
```scala
object A {
  val init = println("hello")
}

object Main {
  def main(args: Array[String]) {
      val a = A.init
  }
}
```

produces no output, but "hello" is expected.
This behaviour was observed when trying code described here http://stackoverflow.com/questions/24221601/scala-object-initialization

**Comment by SethTisue** [comment]
I added a reference from #5304 to here. closing
