### ISSUE TITLE
NumericRange[Double] contains does not stop at the right place

### ISSUE THREAD

**Issue by scabug** [scala/bug#8670]
(0d until 1051201d) by 350400.3333333333d gives  NumericRange(0.0, 350400.3333333333, 700800.6666666666, 1051201.0) in 2.10.3

 (0d until 1051201d) by 350400.3333333333d gives NumericRange(0.0, 350400.3333333333, 700800.6666666666) in 2.9.2

1d to 5d by 1.1d gives NumericRange(1.0, 2.1, 3.2) in 2.10.3

1d to 5d by 1.1d gives NumericRange(1.0, 2.1, 3.2, 4.300000000000001) in 2.9.2

The behaviour in 2.9.2 is definitely the correct behaviour.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6468
