### ISSUE TITLE
use logger in the scala presentation compiler

### ISSUE THREAD

**Issue by scabug** [scala/bug#8717]
Currently, the Global uses a bunch of boolean settings to decide whether to log messages... but it uses println which is a real pain when used by downstream libraries (e.g. scala-ide and ENSIME). We can't filter any of the messages or re-direct them except with a big on/off button. Also, there are a bunch of messages that just can't be turned off at all and it look really weird to our users when we are trying to capture the stdout for meaningful debugging information.

Please, please, consider using a logger (J2SE has the JUL, which can easily be redirected with SLF4J by downstream users like me) instead of println.... or at the very least take in a Writer for debug/verbose/whatever levels.

**Comment by SethTisue** [comment]
Scala IDE is dead and the old ENSIME is too, so I'm guessing there's probably no longer downstream appetite for this?
