### ISSUE TITLE
Bitwise operators on bytes

### ISSUE THREAD

**Issue by scabug** [scala/bug#8718]
First time reporting a bug, so if it's wrong please correct me.

I can't get this working:

scala> var a: Byte = 5 | 3
a: Byte = 7

scala> a |= 7
<console>:9: error: type mismatch;
 found   : Int
 required: Byte
              a |= 7
                ^

scala> a |= 7.toByte
<console>:9: error: type mismatch;
 found   : Int
 required: Byte
              a |= 7.toByte
                ^

scala> a |= 7
<console>:9: error: type mismatch;
 found   : Int
 required: Byte
              a |= 7
                ^

It seems like bit operators aren't working on bytes, is this a bug?

**Comment by SethTisue** [comment]
this is working as designed, for better or worse

**Comment by Ichoran** [comment]
For the record, one can get whatever behavior one wants with opaque types in Scala 3.  You could define `opaque type Bite = Byte` and define +, |, etc. to all be whatever you think is more sane.  There is a _little_ bit of syntactic overhead, but you can get it down to a `.b` or somesuch here and there.

I've done this with unsigned bytes, for instance.

**Comment by som-snytt** [comment]
Also to clarify for the record
```
scala> var x: Byte = 1
var x: Byte = 1

scala> val y: Byte = 2
val y: Byte = 2

scala> x + y
val res0: Int = 3

scala> x += y
         ^
       error: value += is not a member of Byte
         Expression does not convert to assignment because:
           type mismatch;
            found   : Int
            required: Byte
           expansion: x = x.+(y)

scala> implicit def cv(i: Int): Byte = i.toByte
                    ^
       warning: implicit conversion method cv should be enabled
       by making the implicit value scala.language.implicitConversions visible.
       This can be achieved by adding the import clause 'import scala.language.implicitConversions'
       or by setting the compiler option -language:implicitConversions.
       See the Scaladoc for value scala.language.implicitConversions for a discussion
       why the feature should be explicitly enabled.
def cv(i: Int): Byte

scala> x += y

scala> x
val res3: Byte = 3

```
