### ISSUE TITLE
Pattern matching fails if used directly in += operator

### ISSUE THREAD

**Issue by scabug** [scala/bug#8728]
```scala
object Bug {
	class A {};
	class B extends A{};
	class C extends A{};
}

class Bug {
	import Bug._
	
	def show : Unit = {
		var result = "";
		var base = new A();		
		
		//compiles
		val answer = base match {
			case b : B => "b";
			case c : C => "c";
			case _ => "";
		};
		
		result += answer;
		
		//does not compile		
		result += base match {
			case b : B => "b";
			case c : C => "c";
			case _ => "";
		};		 
	}
}
```

There are usually multiple incorrect error warnings on each case line, in the variant that does not compile. The common error warning goes like this: ??scrutinee is incompatible with pattern type; found : X required: Unit??

**Comment by SethTisue** [comment]
going with the last comment which says, not a bug. comment/reopen if you disagree.

**Comment by SethTisue** [comment]
note also at https://github.com/scala/scala-parallel-collections/pull/31#issuecomment-309045543 @szeiger said "probably" not a bug.

**Comment by som-snytt** [comment]
There could be a list of enhancements on the scala-dev "friendliness" ticket.
