### ISSUE TITLE
@inline failing without warning on nested function

### ISSUE THREAD

**Issue by scabug** [scala/bug#8789]
The inliner fails to inline a nested method marked with the `@inline` annotation, and fails to print a warning when `-Yinline-warnings` is passed to `scalac`.

The following MWE demonstrates the problem:

```scala
object Test {

  def m(x: Int) {
  	@inline def nested(y: Int) = y + x + 1
  	println(nested(x))
  }

}
```

Even if Scala does not support inlining nested methods (which would be a quite a shame in performance terms), at a *minimum* a **warning should be generated**.

Interestingly, the following is output by `scalac -Yinline-warnings Test.scala -print`:
```
package <empty> {
  object Test extends Object {
    def m(x: Int): Unit = scala.this.Predef.println(scala.Int.box(Test.this.nested$1(x, x)));
    @inline final private[this] def nested$1(y: Int, x$1: Int): Int = y.+(x$1).+(1);
    def <init>(): Test.type = {
      Test.super.<init>();
      ()
    }
  }
}
```

**Comment by SethTisue** [comment]
@lrytz still relevant?

**Comment by lrytz** [comment]
inlining works in 2.12
