### ISSUE TITLE
Ambiguities in Style Guide

### ISSUE THREAD

**Issue by scabug** [scala/bug#8840]
I apologize if at first the following seems a little pedantic, though I would argue correct style is not a small point in a team as conformity to a single style is important not to pollute commit logs with reformatting changes.

In http://docs.scala-lang.org/style/declarations.html it says

"function values ... The declaration itself should loosely follow the declaration style for methods, with the opening brace on the same line as the assignment or invocation, while the closing brace is on its own line immediately following the last line of the function."

it does not explicitly say that the body should itself be on a new line, nor does it say what to do in the case of partial functions, nor is it clear what "loosley" is supposed to mean. The only thing it is explicit about is that the closing brace is on its last line, therefore it seems any of the following is valid:

```
myMap.map { case (key, value) => key + value
}
```

Clearly the preferable way, but not explicit in the style guide

```
myMap.map {
  case (key, value) => key + value
}
```

Furthermore it's difficult to find any explicit mention in the style guide as to whether there should be a space ****before**** the curly brace, it does say there should be one after;

"Curly braces should be separated from the code within them by a one-space gap, to give the visually busy braces “breathing room”."

Therefore under the style guide the following seems correct, but is clearly hideous:

```
myMap.map{ case (key, value) => key + value
}
```

**Comment by SethTisue** [comment]
style guide tickets should go in https://github.com/scala/docs.scala-lang/issues
