### ISSUE TITLE
Treat java / scala deprecated annotations more uniformly

### ISSUE THREAD

**Issue by scabug** [scala/bug#8883]
There seem to be a some of inconsistencies in the way we deprecation annotations.

- Should the scala `@deprecated` add the Java annotation `@Deprecated`, or just the `ACC_DEPRECATED` flag?
- Adding Java's `@Deprecated` to a Scala class does not trigger any deprecation warnings (neither in scalac nor in javac)

etc.

**Comment by dwijnand** [comment]
https://github.com/scala/scala/pull/8781
