### ISSUE TITLE
NotImplementedError (aka ???) crashes jvm when assigned to Array of primitives

### ISSUE THREAD

**Issue by scabug** [scala/bug#8891]
The problem is that in this context the ??? does not throw the NotImplementedError. It tries of the ??? to the array and it is the jvm that catches the error when it sees that it received something that is not a java primitive value (int in this case). 

The problem seams to be the same with every primitive data types.

**Comment by som-snytt** [comment]
https://github.com/scala/scala/pull/5543 and related tickets.
