### ISSUE TITLE
incorporate support for type constructor polymorphism in Scala by Example

### ISSUE THREAD

**Issue by scabug** [scala/bug#89]
Tony rightfully points out that tcpoly should be better documented [http://blog.tmorris.net/type-safe-scala-sequence-comprehensions/] -- right now the docs say

  It would be attractive to enforce these types statically in the Scala compiler, for instance by requiring that any type supporting   for-comprehensions implements a standard trait with these methods 1 . The problem is that such a standard trait would have to   abstract over the identity of the class C, for instance by taking C as a type parameter. Note that this parameter would be a type   constructor, which gets applied to several different types in the signatures of methods map and flatMap. Unfortunately, the Scala  type system is too weak to express this construct, since it can handle only type parameters which are fully applied types.

Which ceased to be true with the introduction of type constructor polymorphism in 2.5

(I hope to have time to do this in October)

**Comment by SethTisue** [comment]
Scala by Example isn't maintained anymore, to my knowledge
