### ISSUE TITLE
imported function forgets varargness

### ISSUE THREAD

**Issue by scabug** [scala/bug#8923]
Why?

```scala
object Foo { def foo[A]: (A*) => A = as => as.head }
```

ok:
```scala
scala> Foo.foo(1,2,3)
res1: Int = 1
```

not ok:
```scala
scala> import Foo.foo; foo(1,2,3)
<console>:10: error: too many arguments for method apply: (v1: Seq[A])A in trait Function1
        foo(1,2,3)
           ^
```

**Comment by som-snytt** [comment]
Or unsubtle. There's an issue for a better way at scala/bug#6929

There was another issue with typing of accessors. Rather than ad-hoc conversions, it would be nice if the repeated param type could be computed differently depending on context.
