### ISSUE TITLE
Meta: Library Additions to consider for 2.13

### ISSUE THREAD

**Issue by scabug** [scala/bug#8958]
We cannot add to the standard library in 2.12 (source compatibility with 2.11).

This meta-ticket collects proposals that should be considered / discussed for 2.13.

Collections
- groupWhile (4065)
- https://github.com/jozic/scalax-collection (distinctBy, foldLeftWhile, others)
- groupInto (#5351)
- Map#mapEntries (#8594)
- JavaConversions.CloseableIterator (#8028)

Tuples
- append / prepend (#7305, http://stackoverflow.com/a/15349965/596816)

**Comment by SethTisue** [comment]
some of this should go to https://github.com/scala/collection-strawman, the rest to https://contributors.scala-lang.org. it's also possible to just directly open a pull request with an addition, (though you're liable to get asked to rally support on https://contributors.scala-lang.org even so)
