### ISSUE TITLE
`withFilter' method does not yet exist on scala.collection.parallel.immutable.ParSet

### ISSUE THREAD

**Issue by scabug** [scala/bug#8968]
Ack, so tired of this warning.  Can backport that implementation to 2.10.x?

```scala
/*scala>*/ for (i <- List(1,2,3,4).par if i % 2 == 0) yield i 
//<console>:8: warning: `withFilter' method does not yet exist on scala.collection.parallel.immutable.ParSeq[Int], using `filter' method instead
//              for (i <- List(1,2,3,4).par if i % 2 == 0) yield i 
//                                      ^
//res0: scala.collection.parallel.immutable.ParSeq[Int] = ParVector(2, 4)
```

**Comment by som-snytt** [comment]
2.10.6 or Obi-wan was the last hope.

On 2.11, amongst the removals: https://github.com/scala/scala/commit/aced32d05c97651534f468bc9a475ea5f6ae75b8

**Comment by SethTisue** [comment]
note that testing this in the 2.12 or 2.13 REPL is likely to run afoul of https://github.com/scala/scala-dev/issues/195

**Comment by som-snytt** [comment]
No fool I, `-Yrepl-class-based`.
