### ISSUE TITLE
REPL can't handle (A*) => A

### ISSUE THREAD

**Issue by scabug** [scala/bug#8971]
There is a compilation error (only in the REPL) in the following example, where none should be:
```scala
scala> val f: (Int*) => Int = _.size
<console>:5: error: type mismatch;
 found   : Int* => Int
 required: Seq[Int] => Int
  lazy val $result = f
                                          ^
```

**Comment by SethTisue** [comment]
these days this gives "error: repeated parameters are only allowed in method signatures; use Seq instead" (including in Ammonite)
