### ISSUE TITLE
Outdated copyright notices

### ISSUE THREAD

**Issue by scabug** [scala/bug#9026]
A lot of the copyright notices are still
(c) 2002-2013
or
2011-2013
or otherwise ending in 2013.

These should be updated to 2014 (even though 2015 is right around the corner).

**Comment by gourlaysama** [comment]
Duplicate of #10531. Or the other way around?

**Comment by SethTisue** [comment]
We're probably all confused about what the current situation here is. I'll do my best to summarize:

Historically, Adriaan has consistently discouraged sweeping PRs that reformat things or update things where doing so isn't actually important. It clutters up the history, clutters up diffs, etc.

There is no real need for every source file to always have the current year. So, no annual repo-wide year bump, please.

On the other hand, as Adriaan indicated at scala/scala#4184, if a source file has actually been modified , the copyright should have the year of most recent modification. We try to remember to do that manually but usually fail. Automation that updated the years to last-modified date would be good — retroactively, or as part of PR validation, either or both would be good IMO — would be a nice contribution.

**Comment by som-snytt** [comment]
As a reminder, the tool is https://github.com/scala/scala/pull/5201 but someone insisted on a different tool. I don't think one should be very picky about free tools if they sort of work. Someday I might upgrade it to scalafix integration.

**Comment by SethTisue** [comment]
the history on that is at https://github.com/scala/scala/pull/5145

**Comment by SethTisue** [comment]
behold! https://github.com/scala/scala/pull/7306
