### ISSUE TITLE
Compiler crash when using copy method + same named member def

### ISSUE THREAD

**Issue by scabug** [scala/bug#9035]
```scala
case class A(x: String)
case class B(a: A, y: String)
class C(var b: B) {
  def a = b.a;
  b.copy(a = a.copy())
}
```

See also:
http://stackoverflow.com/questions/27364287/how-can-i-find-the-source-file-that-causes-a-scalac-compiler-crash

**Comment by yoo-haemin** [comment]
I have a somewhat simpler example here: https://github.com/scala/bug/issues/10563

**Comment by hrhino** [comment]
fixed (by accident?) in https://github.com/scala/scala/pull/7147/commits/1d366a815713d6dbd88e00c7647b3ea3cf817587
