### ISSUE TITLE
Scalac phase typer hangs

### ISSUE THREAD

**Issue by scabug** [scala/bug#9055]
This is a regression, it used to work with 2.10.4 but now after upgrading to 2.11.4 scalac is hanging indefinitely in the phase typer. 

Unfortunately I haven't managed to pinpoint which code is causing the problem although it is hanging while processing my `RegexParsers` class.
I enabled -verbose but no error is reported whatsoever.

I just rolled back to 2.10.4 and the project compiles fine once again.

Since I don't know from where the problem is coming from, I have attached the source code of the project.

**Comment by SethTisue** [comment]
It's possible this remains broken. But closing anyway, provisionally at least, since it's old, since it's not minimized, and since the attached `src.zip` doesn't come with a build I could easily run.
