### ISSUE TITLE
Slicing IndexedSeqView repeatedly leads to StackOverflowError on access

### ISSUE THREAD

**Issue by scabug** [scala/bug#9069]
Taking slices of IndexedSeqView repeatedly leads to "stacking" Sliced instances up and that in turn leads to StackOverflowError when you sliced a view enough times, for example:

```scala
import scala.annotation.tailrec
import scala.collection.mutable

object ViewSliceBug extends App {
  val coll = Array.fill(12000)(0)

  def makeStackedSlice(coll: mutable.IndexedSeq[Int], count: Int) = {
    @tailrec
    def makeSlicesOfView(view: mutable.IndexedSeq[Int], noOfSlices: Int): Seq[Int] =
      if (noOfSlices == 0) view else makeSlicesOfView(view.tail, noOfSlices - 1)

    makeSlicesOfView(coll.view, count)
  }

  val slice = makeStackedSlice(coll, 10000)
  println(slice.head)
}
```

produces

```
java.lang.StackOverflowError
    at scala.collection.mutable.IndexedSeqView$$anon$2.from(IndexedSeqView.scala:81)
    at scala.collection.SeqViewLike$Sliced$class.apply(SeqViewLike.scala:58)
    at scala.collection.mutable.IndexedSeqView$$anon$2.apply(IndexedSeqView.scala:81)
    at scala.collection.SeqViewLike$Sliced$class.apply(SeqViewLike.scala:58)
    at scala.collection.mutable.IndexedSeqView$$anon$2.apply(IndexedSeqView.scala:81)
    at scala.collection.SeqViewLike$Sliced$class.apply(SeqViewLike.scala:58)
...
```

 In my humble opinion, slice applied to a view should do no more than indices translation, so I would expect this example to work regardless of how many times tail (or any slice) was taken (and with no performance degradation). Maybe Sliced trait should override the newSliced method to cut off transformation stacking. 
PS. Corresponding scala-internals discussion: [https://groups.google.com/d/msg/scala-internals/r1WnP5DfuNM/kyFtKG-sLfYJ]

**Comment by joshlemer** [comment]
I will try and work on this now

**Comment by NthPortal** [comment]
I agree that this in particular should be fixable, but I personally wouldn't consider it a huge problem. In general, excessive nesting with views (or other lazy types like `LazyList`) inevitably leads to overflowing the stack, and I don't think it's fixable in general.

**Comment by NthPortal** [comment]
@joshlemer I'm not against optimising them (though I do question a bit making them *too* complicated), but even if you fix the problem for `IndexedSeq#view`, it's still there for `Seq#view`

**Comment by joshlemer** [comment]
@NthPortal you can check out scala/scala#7048 to see how it turned out in the end, at least for `IndexedSeqView`

**Comment by som-snytt** [comment]
I did not follow the story beyond the closed PR, but I confirmed the example throws on 2.12.17 but not 2.13.0.

Apparently last year's tweak in this area was unrelated https://github.com/scala/bug/issues/12479

**Comment by som-snytt** [comment]
There is a creative test linked.
