### ISSUE TITLE
Lambda in REPL (using object-wrappers) + concurrency = deadlock

### ISSUE THREAD

**Issue by scabug** [scala/bug#9076]
The following code is a test of generating and using java.util.Spliterator to create a java.util.stream.Stream:

```scala
package xp

import java.util.Spliterator
import java.util.function.Consumer

class Aspi(a: Array[String], private val i0: Int, private var i1: Int) extends Spliterator[String] {
  private var i = i0
  def characteristics = Spliterator.SIZED | Spliterator.SUBSIZED | Spliterator.IMMUTABLE
  def estimateSize = i1-i
  override def getExactSizeIfKnown = i1-i
  def tryAdvance(f: Consumer[_ >: String]): Boolean = {
    println(s"Trying at $i [$i0, $i1)")
    if (i >= i1) false
    else { f.accept(a(i)); i += 1; true }
  }
  def trySplit(): Aspi = {
    if (i1-i < 4) {
      println(s"Could not split [$i $i1)")
      null
    }
    else {
      println(s"Splitting from [$i $i1)")
      val child = new Aspi(a, (i+i1+1)/2, i1)
      i1 = child.i0
      child
    }
  }
}

object Test { def main(args: Array[String]) {
  def nu = new xp.Aspi(Array("one", "two", "three", "four", "five"), 0, 5)
  val st = java.util.stream.StreamSupport.stream(nu, true)
  val c = new java.util.Comparator[String]{ def compare(s: String, t: String) = s compareTo t }
  println(st.map[String]((s: String) => s + s).max(c))
```

This compiles and runs successfully.  However, when the contents of `main` are entered in the REPL, the last line hangs.  Stack trace:

```
"ForkJoinPool.commonPool-worker-1" #14 daemon prio=5 os_prio=0 tid=0x00007f966855f800 nid=0x721f in Object.wait() [0x00007f964a18b000]
   java.lang.Thread.State: RUNNABLE
	at $line6.$read$$iw$$iw$$anonfun$1.apply(<console>:11)
	at $line6.$read$$iw$$iw$$anonfun$1.apply(<console>:11)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at xp.Aspi.tryAdvance(Test.scala:14)
	at java.util.Spliterator.forEachRemaining(Spliterator.java:326)
        ...
```

Explicitly creating the SAM like so:

```scala
println(st.map[String](new java.util.function.Function[String, String] {
  def apply(s: String) = s + s
}).max(c))
```

solves the issue.  (Note: I have not tried this on 2.11.5; I assumed 2.12.x was up to date in anything relevant.)

**Comment by adriaanm** [comment]
Probably a wontfix in 2.12, but should consider this as we improve the repl in 2.13 (where we'll standardize on some form of class-based wrapping).

**Comment by SethTisue** [comment]
should this still be on the 2.13.0-RC1 milestone, or shall we push it out to 2.13.x or 2.14?

**Comment by som-snytt** [comment]
Basically anything from 2015 onward has to be 2.13. Anything earlier is so intractable it must wait for the Scala 3 re-write, when all bets are off. Unless someone is betting on Scala 3? Sorry if I spoke out of turn.

**Comment by smarter** [comment]
It's indeed fixed in Dotty: https://github.com/scala/scala-dev/issues/195 :)

**Comment by adriaanm** [comment]
Re-scheduling for 2.13 in the context of https://github.com/scala/scala-dev/issues/325 and a commercial support request.

First we should finish the jline 3 upgrade, but then let's look into improving the encoding.

**Comment by adriaanm** [comment]
@retronym suggested a few alternative solutions -- one is to type check using the current object wrappers, and then have a repl phase that does the class-based encoding? This would avoid breaking anyone that relies on the current repl tree shapes during typer. Have to check how this affects serialization in Spark.
