### ISSUE TITLE
Replace scala.Cloneable/scala.Serializable types with type aliases to java.lang.Cloneable/java.io.Serializable

### ISSUE THREAD

**Issue by scabug** [scala/bug#9080]
Convert scala.Cloneable and scala.Serializable to simple type aliases for java.lang.Cloneable and java.io.Serializable.

The current state has caused confusion and a few issues, because the Scala types are subtypes of the Java types, but not the other way around.

To avoid breakage, the compiler should not fail when discovering the same parents iff those parents are Cloneable/Serializable. Instead a warning should be issued, suggesting that the superfluous parent should be dropped.

Jason mentioned another potential incompatibility with overloaded methods: Two methods could become identical after this change. Consensus seems to be that this scenario is highly unlikely – a dbuild run should make sure that such code doesn't exist in the wild.

**Comment by smarter** [comment]
For the record, there's a PR for that (https://github.com/scala/scala/pull/5288, and also https://github.com/scala/scala/pull/5520), but it's been abandoned, someone would have to pick it up.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6729 can be adapted and re-opened once M5 is the new STARR.
