### ISSUE TITLE
Avoid edge case in BigDecimal factory

### ISSUE THREAD

**Issue by scabug** [scala/bug#9143]
As reported on SO http://stackoverflow.com/q/28461403/1296806,

```scala
math.BigDecimal("0E+2147483648")
```
throws for reasons of Java backwards compatibility.

The consequence is that ScalaCheck generates BigDecimals that can't be reconstituted.

The Scala factory for BigDecimal could sidestep this problem.

**Comment by som-snytt** [comment]
There is a Java bug report for round-tripping

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8233760
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8132362
