### ISSUE TITLE
Mutable Queue only has expensive batch enqueue (elems: A*)

### ISSUE THREAD

**Issue by scabug** [scala/bug#9175]
Seems `mutable.Queue` only has batch enqueuing:

http://www.scala-lang.org/api/current/index.html#scala.collection.mutable.Queue@enqueue%28elems:A*%29:Unit

which tends to be slower than a combination of two enqueues, one for a single element and one for batches:

http://www.scala-lang.org/api/current/index.html#scala.collection.immutable.Queue@enqueue%5BB%3E:A%5D%28iter:scala.collection.immutable.Iterable%5BB%5D%29:scala.collection.immutable.Queue%5BB%5D

http://www.scala-lang.org/api/current/index.html#scala.collection.immutable.Queue@enqueue%5BB%3E:A%5D%28elem:B%29:scala.collection.immutable.Queue%5BB%5D

How do you feel about adding an enqueue to the mutable Queue?

**Comment by SethTisue** [comment]
@scala/collections what's the status on this one — should this stay open?

**Comment by NthPortal** [comment]
fixed in 2.13
