### ISSUE TITLE
implicit wrappers should NPE in same way as direct call

### ISSUE THREAD

**Issue by scabug** [scala/bug#9176]
Let's audit the wrappers we have in the std lib to make sure the behavior is consistent wrt a regular call on wrapped objects == null. Follow up for https://github.com/scala/scala/pull/4343

**Comment by SethTisue** [comment]
example: #8232, though I haven't checked the current behavior. `BigDecimal` and `null` are a popular pair to open tickets about (#6567, #12146, #6456)

**Comment by som-snytt** [comment]
@SethTisue let me know if there is a conversion of special concern

**Comment by SethTisue** [comment]
There isn't. Do you think we should close the issue, as it seems unlikely that a full audit will happen?

**Comment by som-snytt** [comment]
I tried to go through everything with `implicitConversions`. I could make a spreadsheet.

An audit might consist of verifying code coverage. Someone just asked in chat how can I list all my implicits to make sure they're "necessary". For conversions, we'd like to verify that there is a documenting test case for null. How would you go about that? they asked during the interview.

**Comment by som-snytt** [comment]
Audit:
```
scala> import scala.jdk.CollectionConverters._
import scala.jdk.CollectionConverters._

scala> val xs = null.asInstanceOf[java.util.List[Int]]
val xs: java.util.List[Int] = null

scala> xs.asScala
val res0: scala.collection.mutable.Buffer[Int] = null

```
