### ISSUE TITLE
API documentation should include a warning that Continuations plugin is unsupported

### ISSUE THREAD

**Issue by scabug** [scala/bug#9198]
The continuations plugin is unsupported, and apparently won't be included in Scala 2.12 - https://github.com/scala/scala-continuations

The relevant API documentation makes no mention of this, which could lead to people building on this plugin without realizing that it won't be included with Scala in the future:

http://www.scala-lang.org/api/2.10.1/index.html#scala.util.continuations.package

**Comment by SethTisue** [comment]
closing since only 2.10.x is affected and we aren't taking non-critical 2.10.x PRs anymore
