### ISSUE TITLE
Scala runner eats exclamation points on Windows!

### ISSUE THREAD

**Issue by scabug** [scala/bug#9204]
As reported at http://stackoverflow.com/q/28891832/1296806
```scala
C:\Users\you> scala greeting.script "hello^!"
hello!

C:\Users\you> set world= Bob

C:\Users\you> scala greeting.script "hello!world!"
hello Bob
```
where the script is `args foreach println`.

**Comment by GeorgOfenbeck** [comment]
Started working on this

**Comment by SethTisue** [comment]
@GeorgOfenbeck I've invited you to https://github.com/orgs/scala/teams/contributors ; after accepting, comment here and I'll assign the ticket to you.

**Comment by GeorgOfenbeck** [comment]
accepted - thanks for the invite and thanks for the welcome!
