### ISSUE TITLE
Repl :paste mode problem for 2.11.* versions has issues not seen with previous

### ISSUE THREAD

**Issue by scabug** [scala/bug#9221]
% ./scala
Welcome to Scala version 2.11.2 (OpenJDK 64-Bit Server VM, Java 1.7.0_75).
Type in expressions to have them evaluated.
Type :help for more information.

scala> :paste
// Entering paste mode (ctrl-D to finish)
var a = 3

----------------

Control-D does nothing to leave this environment.

No problems exist for 2.10.* nor 2.9.*

**Comment by som-snytt** [comment]
Closing as out of scope with a workaround.
