### ISSUE TITLE
REPL command mode

### ISSUE THREAD

**Issue by scabug** [scala/bug#9249]
As reported at https://github.com/scala/scala/issues/4392, not everyone appreciates REPL's colon-command syntax. Since JLine already supports vi mode line edits, one accommodation would be to recognize a colon while in escaped edit mode, erase the line, draw a colon and accept command text.

This improvement would delight that fraction of users who <3 vi and also use a lot of ::.  Probably under a flag.

This would make even more sense with line healing enabled.
```
scala> 42
res0: Int = 42

scala> :: Nil
res1: List[Int] = List(42)
```

**Comment by SethTisue** [comment]
@som-snytt I'm inclined to close this as I don't really see a problem here. maybe it's me. want to convince me to leave it open?

**Comment by som-snytt** [comment]
JLine 3 offers more and better options.
