### ISSUE TITLE
Intermittent assertion failure in genLoadIdent: temporary value created by patmat disappearing from scope

### ISSUE THREAD

**Issue by scabug** [scala/bug#9264]
From PR validation (https://github.com/scala/scala/pull/4376#issuecomment-90305927):

```
That assertion error is the same one that @gkossakowski's encountered while working on the SBT build. When we also saw it during PR validation, I added (https://github.com/scala/scala/pull/4397) an extended diagnostic error to the assertion in the hope we would see it again.

Now, to make sense of this:
```

```
[quick.compiler] error: symbol value x2#803320 does not exist in scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen.AdaptTypeError, which contains locals value x1#803317,value foundType#508052,value req#508050,value found#508049,value tree#508048
[quick.compiler] error: scala.reflect.internal.FatalError: symbol value x2#803320 does not exist in scala.tools.nsc.typechecker.ContextErrors$TyperContextErrors$TyperErrorGen.AdaptTypeError, which contains locals value x1#803317,value foundType#508052,value req#508050,value found#508049,value tree#508048
```

**Comment by dwijnand** [comment]
> we've worked around it in [scala/scala#5612](https://github.com/scala/scala/pull/5612), and it was never reported on 2.12 as far as I know.

🤞

**Comment by som-snytt** [comment]
This is one of my favorite threads, with all the drama, humor, twists and turns. Retronym's 3rd act reveal, only to turn to the audience and suggest diabolically, with cocked eyebrow, Or is it just a red herring?

Is there actually guidance in one of the release notes: Avoid local lazy vals? or a Scalafix? Lazy implementation has gone through a few design rounds, does that include local lazy?
