### ISSUE TITLE
Refactor duplicated code processing Scala signatures

### ISSUE THREAD

**Issue by scabug** [scala/bug#9296]
We have such a duplicated code in three places:
https://github.com/scala/scala/blob/v2.11.6/src/scalap/scala/tools/scalap/scalax/rules/scalasig/ScalaSig.scala#L20-L57
https://github.com/scala/scala/blob/v2.11.6/src/compiler/scala/tools/nsc/symtab/classfile/ClassfileParser.scala#L925-L971
https://github.com/scala/scala/blob/v2.11.6/src/reflect/scala/reflect/runtime/JavaMirrors.scala#L588-L639

The goal is to understand the existing code, look for intentional / accidental differences and similarities and extract the suitable abstraction.
Essentially scalap seems to duplicate a lot of a logic which already exists in some form in a compiler. In long term. if it's possible, it would be better to use some common code.

**Comment by SethTisue** [comment]
probably unlikely to happen at this point, and we don't normally keep speculative tickets like this open indefinitely

**Comment by som-snytt** [comment]
I just came here via the code comment.
