### ISSUE TITLE
Scala 2.12 needs packaging for Debian/Ubuntu in Ubuntu APT repos

### ISSUE THREAD

**Issue by scabug** [scala/bug#9299]
Ubuntu/Debian packages are required for Scala.
The build needs to produce binaries that are accepted by the Ubuntu committers. A new version of Ubuntu LTS will be released next year. It would be a major let down to the community building applications for the cloud if automatic package management is not provided.

See previous tickets:
https://issues.scala-lang.org/browse/INF-138
https://bugs.launchpad.net/ubuntu/+source/scala/+bug/1126035

**Comment by SethTisue** [comment]
just noticed that #10172 is a duplicate of this. there is some relevant discussion there

**Comment by SethTisue** [comment]
new thread about a new effort to tackle this: https://contributors.scala-lang.org/t/question-about-building-scala-and-sbt-proper/2811

**Comment by SethTisue** [comment]
Closing, as this isn't actionable within the scala/scala repo.

**Comment by SethTisue** [comment]
there's another new thread on this at https://contributors.scala-lang.org/t/bootstrapping-of-the-scala-compiler/6242
