### ISSUE TITLE
Optimizer leaves behind redundant (but illegal) anonymous classes

### ISSUE THREAD

**Issue by scabug** [scala/bug#9303]
Consider the following minimal example:

```scala
class MWE {

  private def anotherMethod(x: Int): Unit = {
    println(x)
  }

  def method(prop: Array[Int]): Unit = {
    for (i <- 0 until prop.length; j <- 0 until prop.length) {
      val lhs = prop(i)
      anotherMethod(lhs)
    }
  }

}
```

If you compile without the `-optimise` flag, then the compiler (2.11.x) will generate three class files:

```
MWE.class
MWE$$anonfun$method$1.class
MWE$$anonfun$method$1$$anonfun$apply$mcVI$sp$1.class
```

Decompiling `MWE$$anonfun$method$1$$anonfun$apply$mcVI$sp$1` with `scalap` shows that it is a class generated from the anonymous function and its constructor accepts an instance of `MWE$$anonfun$method$1`.

Now, instead compile the example with the `-optimise` flag and this time only *two* class files are generated:
```
MWE.class
MWE$$anonfun$method$1$$anonfun$apply$mcVI$sp$1.class
```
So far, so good.

But now decompiling with `scalap` shows that the constructor of `MWE$$anonfun$method$1$$anonfun$apply$mcVI$sp$1` still accepts an instance of `MWE$$anonfun$method$1`, **even though this class is no longer generated**.

(Note that decompiling `MWE` shows that this class does not construct an instance of, or in any way load, the class `MWE$$anonfun$method$1$$anonfun$apply$mcVI$sp$1`, so you will not get a problem at runtime.)

Thus, you do not have a problem at runtime, **but** if you use a tool to optimize, obfuscate or transform the bytecode generated by the compiler, and that tool verifies the bytecode of *every* class, then that tool will fail  with an error (and rightly so, since a class (i.e., `MWE$$anonfun$method$1$$anonfun$apply$mcVI$sp$1`) references a class that is not on the classpath (i.e., `MWE$$anonfun$method$1`)).

Note you must keep the `private` modifier for `anotherMethod` and the range for `j`, even those `j` is not used, in order to reproduce the bug.

I have tried this in 2.10.3, and the optimizer still allowed all three classes to be generated. Whilst you could argue that the behavior in 2.11.x is better (namely one of the two redundant classes is eliminated), I would argue that it is in fact worse, because of the issue of classes with references to non-existent classes being left behind.

**Comment by SethTisue** [comment]
from the discussion it sounds like this is no longer relevant in 2.12
