### ISSUE TITLE
requirement violation in BatchingExecutor

### ISSUE THREAD

**Issue by scabug** [scala/bug#9304]
The Play team found this flaw in Akka’s version of the BatchingExecutor, see https://github.com/akka/akka/pull/17390 and https://github.com/playframework/playframework/issues/4372.

**Comment by MihaiBogdanEugen** [comment]
Any news about this topic?

**Comment by SethTisue** [comment]
has anyone tried it in Scala 2.13.6?

**Comment by MihaiBogdanEugen** [comment]
To be fair, we did not. We're planning to upgrade to Scala 2.13.latest next month, but right now, we're facing this issue using Scala 2.12.12 and the latest Akka version.

**Comment by som-snytt** [comment]
I almost understand rkuhn's previous remark, that your `BatchingExecutor` must be able to delegate to an executor that will run jobs asynchronously. There is a `WARNING` in Akka. I submitted a PR on 2.12 but hadn't got around to looking at 2.13, so I don't know if backporting would make more sense.
