### ISSUE TITLE
Quasiquotes do not pattern match Java static method

### ISSUE THREAD

**Issue by scabug** [scala/bug#9404]
I am writing a Wart Remover plugin, and running Wart Remover as a Scala compiler plugin. I was not able to get the following quasiquote pattern match to match an actual call to `System.getProperty`:

```scala
tree match { 
  case q"java.lang.System.getProperty($_)" => ???
}
```

**Comment by SethTisue** [comment]
closing all quasiquotes tickets; see #10755
