### ISSUE TITLE
Misleading error when "implicitly" cannot find value when used without type arg

### ISSUE THREAD

**Issue by scabug** [scala/bug#9427]
I have noticed that the `implicitly` method gives a rather strange error message if it is used without arguments and the implicit value cannot be found:

```scala
scala> class Foo
defined class Foo

scala> val f: Foo = implicitly
<console>:8: error: ambiguous implicit values:
 both value StringCanBuildFrom in object Predef of type => scala.collection.generic.CanBuildFrom[String,Char,String]
 and method $conforms in object Predef of type [A]=> <:<[A,A]
 match expected type T
       val f: Foo = implicitly
                    ^
```

If you pass it an explicit type param, it gives a much more sensible error:

```scala
scala> val f = implicitly[Foo]
<console>:8: error: could not find implicit value for parameter e: Foo
       val f = implicitly[Foo]
                         ^
```

This looks to me like a minor compiler bug. 
I like using "implicitly" without type args when the type can be inferred, e.g.

```scala
myMethodWithLotsOfImplicits()(implicitly, implicitly, myExplicitOverride, implicitly, implicitly)
```

rather than, say:

```scala
myMethodWithLotsOfImplicits()(implicitly[Something], implicitly[SomethingElse], myExplicitOverride, implicitly[YetAnother], implicitly[EvenMore])
```

... but this does give very misleading errors if one of the implicits can't be found, as shown above.

## Minimised Repro case

```scala
scala> class Foo
defined class Foo

scala> val f: Foo = implicitly
```

## Expected result:

```scala
<console>:8: error: could not find implicit value for parameter e: Foo
       val f: Foo = implicitly
                         ^
```

## Observed result:

```scala
<console>:8: error: ambiguous implicit values:
 both value StringCanBuildFrom in object Predef of type => scala.collection.generic.CanBuildFrom[String,Char,String]
 and method $conforms in object Predef of type [A]=> <:<[A,A]
 match expected type T
       val f: Foo = implicitly
                    ^
```

## Related issues:

#5801 looks similar, but that's marked as fixed in 2.10
#8947 looks related, but marked fixed in 2.11.5

**Comment by SethTisue** [comment]
it's not clear here what a solution plan would even look like. adding special-case code for `implicitly` doesn't seem very satisfying.

Dotty is similar:

```
scala> implicitly 
1 |implicitly
  |          ^
  |ambiguous implicit arguments: both value charShow in object Show and value stringShow in object Show match type T of parameter ev of method implicitly in object DottyPredef
```

**Comment by smarter** [comment]
The issue is about using `implicitly` without a type parameter but with an expected type, and here Dotty does do better than scalac:
```scala
scala> val i: Int = implicitly 
1 |val i: Int = implicitly
  |                       ^
  |no implicit argument of type T was found for parameter ev of method implicitly in object DottyPredef
```

**Comment by jvican** [comment]
I stumbled upon this today. Isn't there a way we can improve the error message here? It seems baffling to me that the compiler doesn't infer that `implicitly` means `implicitly[Int]` because of the the type ascription of its lhs. What am I missing?

**Comment by Jasper-M** [comment]
If you have 
```
def foo[A]: A
val a: String = foo
```
then for some reason scalac is not convinced it should fix `A` to `String`, because it still wants to minimize `A`. If you force it to fix `A` to something, e.g. by asking for a `TypeTag[A]`, it will infer `A =:= Nothing`. I'm pretty sure it's because of some interplay with covariance.

**Comment by jvican** [comment]
@adriaanm Is what @Jasper-M says a well-known compiler misbehavior or is it intentional that scalac behaves this way here?

**Comment by smarter** [comment]
It's normal. The compiler will prefer solutions that give a more precise result type, this is usually what you want.

**Comment by joroKr21** [comment]
```scala
λ. scala

     ________ ___   / /  ___
    / __/ __// _ | / /  / _ |
  __\ \/ /__/ __ |/ /__/ __ |
 /____/\___/_/ |_/____/_/ | |
                          |/  version 2.13.1

scala> implicitly
res0: Nothing => Nothing = generalized constraint
```

**Comment by joroKr21** [comment]
@som-snytt why the adaptation warning?

**Comment by som-snytt** [comment]
Is there a warning? I think people should be adaptable, both to circumstances and to other people they may encounter. Not that I even approach that bar. I'm speaking hypothetically.

**Comment by joroKr21** [comment]
There's a warning in the REPL but not in the test :thinking:

**Comment by som-snytt** [comment]
REPL = Really Extraordinarily Psychotic Liar.

**Comment by som-snytt** [comment]
```
$ scala
Welcome to Scala 2.13.1 (OpenJDK 64-Bit Server VM, Java 1.8.0_222).
Type in expressions for evaluation. Or try :help.

scala> def f: Int = implicitly
                    ^
       error: type mismatch;
        found   : Nothing => Nothing
        required: Int

scala> def f = implicitly: Int
               ^
       error: type mismatch;
        found   : Nothing => Nothing
        required: Int
```
I was going to close this, as dotty crashes on the second formulation.
