### ISSUE TITLE
Error inferring correct type from java 8 class hierarchy

### ISSUE THREAD

**Issue by scabug** [scala/bug#9432]
Please take a look at the simple project attached, to reproduce the error run  

{code}mvn compile{code}

The same two-liner test is provided for Java (compiles) and for Scala (not compiling)

The sample makes uses of a Java interface `CacheSet` that has two similar methods going upwards in its hierarchy:

- stream() returning java.util.stream.Stream
- stream() returning a specialised sub-interface of java.util.stream.Stream, called CacheStream. This interface add extra methods to j.u.s.Stream, for example `disableRehashAware`

The compiler incorrectly infer the type of stream() to be j.u.s.Stream and thus cannot infer `stream().disableRehashAware()`

**Comment by SethTisue** [comment]
probably nobody ever looked at this since the reproduction isn't self-contained (it refers to `import org.infinispan.CacheSet`, which is defined elsewhere I guess)

**Comment by som-snytt** [comment]
This is the Scala 2 rule to prefer concrete to abstract member, which was discarded in Scala 3.

```
public interface CacheSet<E> extends CacheCollection<E>, CloseableIteratorSet<E> {
}

import java.util.stream.Stream;

public interface CacheStream<R> extends Stream<R> {
   CacheStream<R> disableRehashAware();
}

public interface CacheCollection<E> extends CloseableIteratorCollection<E> {
   @Override
   CacheStream<E> stream();
}

import java.util.Collection;
import java.util.stream.Stream;

public interface CloseableIteratorCollection<E> extends Collection<E> {
   /**
    * {@inheritDoc}
    * <p>
    * This stream should be explicitly closed after it has been used. Failure to do so could cause
    * resources to not be freed properly
    */
   @Override
   default Stream<E> stream() {
      return Collection.super.stream();
   }
}

```
and
```
scala> typeOf[CacheSet[AnyRef]]
val res2: $r.intp.global.Type = CacheSet[AnyRef]

scala> .baseClasses
val res3: List[$r.intp.global.Symbol] = List(trait CacheSet, trait CloseableIteratorSet, trait Set, trait CacheCollection, trait CloseableIteratorCollection, trait Collection, trait Iterable, class Object, class Any)
```
