### ISSUE TITLE
documented type signature for HashMap.foreach is wrong

### ISSUE THREAD

**Issue by scabug** [scala/bug#9444]
documentation says both mutable and immutable HashMap.foreach method takes (Key)=>Unit, while the source reveals it only takes ((Key, Value))=>Unit

**Comment by mghildiy** [comment]
This is where issue is:
https://www.scala-lang.org/api/current/scala/collection/immutable/HashMap.html.

def foreach(f: (A) ⇒ Unit): Unit

I guess HashMap.scala in scala/scala repo needs to be modified with correct scala doc.

**Comment by martijnhoekstra** [comment]
This is #6071 

However, this specific one could have the separate solution of just removing the usecase for foreach - it's just `[U]((A, B) => U)  => Unit`. not sure whether that would be an accepted solution

**Comment by mghildiy** [comment]
Does this ticket then depend on #6071?No action needed here?

**Comment by mghildiy** [comment]
BTW, how are docs created, like this one:

https://www.scala-lang.org/api/current/scala/collection/immutable/HashMap.html

**Comment by SethTisue** [comment]
> how are docs created

with Scaladoc, see https://docs.scala-lang.org/style/scaladoc.html and other things linked from https://github.com/scala/docs.scala-lang/issues/526

**Comment by SethTisue** [comment]
> Does this ticket then depend on #6071?No action needed here?

If Martijn's remark was unclear to you, it could be because you haven't encountered the concept of a "use case" in Scaladoc?

**Comment by grizio** [comment]
The documentation was corrected in 2.13-M5.

> `def foreach[U](f: ((K, V)) ⇒ U): Unit`
> Apply f to each element for its side effects Note: [U] parameter needed to help scalac's type inference. 

See https://scala-lang.org/files/archive/api/2.13.0-M5/scala/collection/immutable/HashMap.html

**Comment by julienrf** [comment]
Thanks @grizio!
