### ISSUE TITLE
Missing class hierarchy diagram on http://www.scala-lang.org/files/archive/spec/2.11/12-the-scala-standard-library.html

### ISSUE THREAD

**Issue by scabug** [scala/bug#9457]
http://www.scala-lang.org/files/archive/spec/2.11/12-the-scala-standard-library.html has a broken image: 

```scala
<img src="public/images/classhierarchy.pdf" alt="Class hierarchy of Scala">
```

The extension is .pdf. The resource is present and serves out in a new tab if requested directly,

    http://www.scala-lang.org/files/archive/spec/2.11/public/images/classhierarchy.pdf

but it does not display as an embedded image.

**Comment by SethTisue** [comment]
is this still broken?

**Comment by gourlaysama** [comment]
Yes, the problem is still there in [the 2.13 spec][1].

[1]: https://scala-lang.org/files/archive/spec/2.13/12-the-scala-standard-library.html

**Comment by tiarebalbi** [comment]
This issue can be fixed as the image is available. https://scala-lang.org/files/archive/spec/2.13/12-the-scala-standard-library.html#root-classes
