### ISSUE TITLE
Race condition may cause newly-created List to mutate.

### ISSUE THREAD

**Issue by scabug** [scala/bug#9462]
In a race condition, the lazy copy feature of ListBuffer may cause a newly-created immutable.List produced by the toList method to mutate after it's creation.

The mutator methods of ListBuffer first check if an export was performed, and copy the internal List object before performing a mutation. However, this sets up a potential race condition. Consider two threads, one performing updates, the other taking immutable.List snapshots of the contents of the ListBuffer. If the snapshot thread calls toList after the updating thread had checked for an export, but before performing it's update, the immutable list returned by toList will not be a copy, and will mutate when the updating thread performs it's update.

At least the documentation for toList should note this shortcoming so that it can be coded around.

**Comment by SethTisue** [comment]
was fixed for 2.13.0 by https://github.com/scala/scala/pull/6425
