### ISSUE TITLE
Don't constant fold `classOf` in the presentation compiler

### ISSUE THREAD

**Issue by scabug** [scala/bug#9476]
I'd like to merge https://github.com/retronym/scala/commit/689b6db, but we need to adapt the IDE first.

The first step was done here: https://github.com/scala-ide/scala-refactoring/pull/96

But extraction of the `throws` annotation in `ScalaStructureBuilder` needs to be modified to use the `.tpe` of the tree rather than pattern match on `Literal(Constant(tpe))`

https://github.com/scala-ide/scala-ide/blob/4.2.0-rc3/org.scala-ide.sdt.core/src/org/scalaide/core/internal/jdt/model/ScalaStructureBuilder.scala#L45

**Comment by som-snytt** [comment]
Superseded ten minutes later by https://github.com/scala/bug/issues/9477
