### ISSUE TITLE
bogus warning about usage of package-private types in method signatures

### ISSUE THREAD

**Issue by scabug** [scala/bug#9490]
```scala
package ws

private[ws] trait Foo
private[ws] object Test {
  class Bar {
    def apply(f: Foo) = ???
  }
}
```

This leads to: «method apply in class Bar references private[ws] trait Foo. Classes which cannot access Foo may be unable to override apply.» This is obviously a non-problem.

**Comment by som-snytt** [comment]
Linked ticket ("linket") shows sealed trait.

**Comment by SethTisue** [comment]
the warning is only produced under `-Xlint` and the problem still exists in 2.13.8.
