### ISSUE TITLE
Warn (or throw?) when a value class gets boxed

### ISSUE THREAD

**Issue by scabug** [scala/bug#9504]
Proposal: Add a compiler flag that makes it easier to know when an AnyVal allocation occurs. 

AnyVals can radically improve performance, but allocations can occur in surprising places (removing any performance gains). SIP-15 documents the conditions under which allocation occurs, but that can be hard to remember when browsing a complicated program. Compiler support for detecting allocations would help a lot.

A couple of possible flags are:

  * Warning - Generate a compiler warning when a use-site will require an AnyVal to be allocated. 
  * Throw on Allocate - Add a flag that causes an exception to be thrown when an AnyVal is allocated. The resulting stack trace should allow the programmer to track down the allocation easily.

**Comment by SethTisue** [comment]
@som-snytt did you do a thing like this under `-Wperformance`?

**Comment by som-snytt** [comment]
I see the linked (duplicating) ticket links to the `-Wperformance` PR which warns for `Ref` heapification which is not all boxing.

**Comment by som-snytt** [comment]
I'll let @SethTisue choose which ticket to close. It's nice to honor earlier reports, like being the first to name a species, but the other ticket has slightly more attention due its high-profile reporter.

**Comment by SethTisue** [comment]
consolidating at #12271
