### ISSUE TITLE
new keyword for implicit imports

### ISSUE THREAD

**Issue by scabug** [scala/bug#9510]
The readability of Scala code can be very bad, when implicits are used. The main reason, that the applicable implicits are not obvious from the source code because implicits can be imported from any import statement.
It could improve the readability if the implicit imports were supported through a different keyword and not with the standard `import` keyword.

**Comment by som-snytt** [comment]
`given`. Why didn't they just run with `implort`? Also my suggestion on the linked ticket for naming by type was realized.

This is out of scope for Scala 2.
