### ISSUE TITLE
[usecase] appears to label following text not preceding method signature

### ISSUE THREAD

**Issue by scabug** [scala/bug#9533]
The [use case] label is more likely to be interpreted as a header for the following text than an indication the method signature is a simplified version.

!scaladoc-usecase-misleading.png!

In this the **use case** could be taken to be *Multiples up the elements ...* .

Replacing [use case] with *Full Signature* would be a twofold improvement,

- Make it clear the signature above is probably not the full signature
- Avoid the confusingly named *use case*

If *use case* had to remain in some form then *simplified signature* would be an improvement.

|As a further illustration the problem is excerbated when the document block is collapsed|!scaladoc-usecase-misleading-collapsed.png!|

**Comment by SethTisue** [comment]
`@usecase` was deprecated in 2.13.0
