### ISSUE TITLE
Error:scalac: uncaught exception during compilation: java.lang.AssertionError

### ISSUE THREAD

**Issue by scabug** [scala/bug#9556]
I stumbled across this compilation error when trying to compile https://github.com/stratosphere/peel in IntelliJ 15. Can't seem to solve it and though it might be a bug in the compiler? Let me know if you need more info.

Error:Module 'peel-core' production: java.lang.AssertionError: assertion failed: 
     while compiling: /Users/Johannes/arbeit/systems/peel/peel/peel-core/src/main/scala/org/peelframework/core/util/shell.scala
        during phase: jvm
     library version: version 2.10.5
    compiler version: version 2.10.5
  reconstructed args: -nobootcp -javabootclasspath : -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/lib/tools.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Users/Johannes/arbeit/systems/peel/peel/peel-core/target/classes:/Users/Johannes/.m2/repository/com/h2database/h2/1.4.187/h2-1.4.187.jar:/Users/Johannes/.m2/repository/com/typesafe/play/anorm_2.10/2.4.0/anorm_2.10-2.4.0.jar:/Users/Johannes/.m2/repository/com/typesafe/play/anorm-tokenizer_2.10/2.4.0/anorm-tokenizer_2.10-2.4.0.jar:/Users/Johannes/.m2/repository/joda-time/joda-time/2.6/joda-time-2.6.jar:/Users/Johannes/.m2/repository/org/joda/joda-convert/1.7/joda-convert-1.7.jar:/Users/Johannes/.m2/repository/io/spray/spray-json_2.10/1.2.6/spray-json_2.10-1.2.6.jar:/Users/Johannes/.m2/repository/org/parboiled/parboiled-scala_2.10/1.1.6/parboiled-scala_2.10-1.1.6.jar:/Users/Johannes/.m2/repository/org/parboiled/parboiled-core/1.1.6/parboiled-core-1.1.6.jar:/Users/Johannes/.m2/repository/org/apache/commons/commons-compress/1.9/commons-compress-1.9.jar:/Users/Johannes/.m2/repository/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar:/Users/Johannes/.m2/repository/com/samskivert/jmustache/1.9/jmustache-1.9.jar:/Users/Johannes/.m2/repository/org/scala-lang/scala-library/2.10.5/scala-library-2.10.5.jar:/Users/Johannes/.m2/repository/org/scala-lang/scala-compiler/2.10.5/scala-compiler-2.10.5.jar:/Users/Johannes/.m2/repository/org/scala-lang/scala-reflect/2.10.5/scala-reflect-2.10.5.jar:/Users/Johannes/.m2/repository/org/springframework/spring-context/4.0.5.RELEASE/spring-context-4.0.5.RELEASE.jar:/Users/Johannes/.m2/repository/org/springframework/spring-aop/4.0.5.RELEASE/spring-aop-4.0.5.RELEASE.jar:/Users/Johannes/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar:/Users/Johannes/.m2/repository/org/springframework/spring-beans/4.0.5.RELEASE/spring-beans-4.0.5.RELEASE.jar:/Users/Johannes/.m2/repository/org/springframework/spring-core/4.0.5.RELEASE/spring-core-4.0.5.RELEASE.jar:/Users/Johannes/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/Johannes/.m2/repository/org/springframework/spring-expression/4.0.5.RELEASE/spring-expression-4.0.5.RELEASE.jar:/Users/Johannes/.m2/repository/com/typesafe/akka/akka-actor_2.10/2.3.12/akka-actor_2.10-2.3.12.jar:/Users/Johannes/.m2/repository/com/typesafe/akka/akka-slf4j_2.10/2.3.12/akka-slf4j_2.10-2.3.12.jar:/Users/Johannes/.m2/repository/com/jsuereth/scala-arm_2.10/1.4/scala-arm_2.10-1.4.jar:/Users/Johannes/.m2/repository/com/typesafe/config/1.2.1/config-1.2.1.jar:/Users/Johannes/.m2/repository/net/sourceforge/argparse4j/argparse4j/0.6.0/argparse4j-0.6.0.jar:/Users/Johannes/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/Users/Johannes/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar:/Users/Johannes/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar -deprecation -feature
  last tree to typer: Literal(Constant(java.nio.channels.WritableByteChannel))
              symbol: null
   symbol definition: null
                 tpe: Class(classOf[java.nio.channels.WritableByteChannel])
       symbol owners: 
      context owners: anonymous class anonfun$1 -> package util
== Enclosing template or block ==
Template( // val <local $anonfun>: <notype>, tree.tpe=org.peelframework.core.util.anonfun$1
  "scala.runtime.AbstractFunction0", "scala.Serializable" // parents
  ValDef(
    private
    "_"
    <tpt>
    <empty>
  )
  // 4 statements
  DefDef( // final def apply(): String
    <method> final <triedcooking>
    "apply"
    []
    List(Nil)
    <tpt> // tree.tpe=String
    Apply( // def s(args: Seq): String in class StringContext, tree.tpe=String
      new StringContext(scala.this.Predef.wrapRefArray(Array[String]{"# ", ""}.$asInstanceOf[Array[Object]]()))."s" // def s(args: Seq): String in class StringContext, tree.tpe=(args: Seq)String
      Apply( // implicit def genericWrapArray(xs: Object): collection.mutable.WrappedArray in class LowPriorityImplicits, tree.tpe=collection.mutable.WrappedArray
        scala.this."Predef"."genericWrapArray" // implicit def genericWrapArray(xs: Object): collection.mutable.WrappedArray in class LowPriorityImplicits, tree.tpe=(xs: Object)collection.mutable.WrappedArray
        ArrayValue( // tree.tpe=Array[Object]
          <tpt> // tree.tpe=Object
          List(
            Apply( // final def format(x$1: java.util.Date): String in class DateFormat, tree.tpe=String
              TimeStamps$$anonfun$1.this."dateFormat$1"."format" // final def format(x$1: java.util.Date): String in class DateFormat, tree.tpe=(x$1: java.util.Date)String
              Apply( // def <init>(): java.util.Date in class Date, tree.tpe=java.util.Date
                new java.util.Date."<init>" // def <init>(): java.util.Date in class Date, tree.tpe=()java.util.Date
                Nil
              )
            )
          )
        )
      )
    )
  )
  DefDef( // final def apply(): Object
    <method> final <bridge>
    "apply"
    []
    List(Nil)
    <tpt> // tree.tpe=Object
    Apply( // final def apply(): String, tree.tpe=String
      TimeStamps$$anonfun$1.this."apply" // final def apply(): String, tree.tpe=()String
      Nil
    )
  )
  ValDef( // private[this] val dateFormat$1: java.text.SimpleDateFormat
    private <local> <synthetic> <paramaccessor> <triedcooking>
    "dateFormat$1"
    <tpt> // tree.tpe=java.text.SimpleDateFormat
    <empty>
  )
  DefDef( // def <init>(arg$outer: org.peelframework.core.util.OutputStreamProcessLogger,dateFormat$1: java.text.SimpleDateFormat): org.peelframework.core.util.anonfun$1
    <method> <triedcooking>
    "<init>"
    []
    // 1 parameter list
    ValDef( // $outer: org.peelframework.core.util.OutputStreamProcessLogger
      <param>
      "$outer"
      <tpt> // tree.tpe=org.peelframework.core.util.OutputStreamProcessLogger
      <empty>
    )
    ValDef( // dateFormat$1: java.text.SimpleDateFormat
      <param> <synthetic> <triedcooking>
      "dateFormat$1"
      <tpt> // tree.tpe=java.text.SimpleDateFormat
      <empty>
    )
    <tpt> // tree.tpe=org.peelframework.core.util.anonfun$1
    Block( // tree.tpe=Unit
      // 2 statements
      Assign( // tree.tpe=Unit
        TimeStamps$$anonfun$1.this."dateFormat$1" // private[this] val dateFormat$1: java.text.SimpleDateFormat, tree.tpe=java.text.SimpleDateFormat
        "dateFormat$1" // dateFormat$1: java.text.SimpleDateFormat, tree.tpe=java.text.SimpleDateFormat
      )
      Apply( // def <init>(): scala.runtime.AbstractFunction0 in class AbstractFunction0, tree.tpe=scala.runtime.AbstractFunction0
        TimeStamps$$anonfun$1.super."<init>" // def <init>(): scala.runtime.AbstractFunction0 in class AbstractFunction0, tree.tpe=()scala.runtime.AbstractFunction0
        Nil
      )
      ()
    )
  )
)
== Expanded type of tree ==
ConstantType(value = Constant(java.nio.channels.WritableByteChannel))
how can getCommonSuperclass() do its job if different class symbols get the same bytecode-level internal name: org/peelframework/core/cli/command/rsync/package$FolderEntry

**Comment by SethTisue** [comment]
closing for lack of a standalone reproducer
