### ISSUE TITLE
Scaladoc has unnecessary dependencies on scala-parser-combinators and scala-xml

### ISSUE THREAD

**Issue by scabug** [scala/bug#9560]
- Scaladoc doesn't need to parse JSON, only generate it, and it's silly to depend on scala.util.parsing for that, especially since it only happens in one small place so the dependency would be easy to cut
- similarly for XML, except cutting the dependency is harder because we're generating HTML throughout the code. but but there's no truly fundamental difficulty

in both cases we could avoid replacing one Scala dependency with another Scala dependency by just using plain Scala and/or by adding a Java dependency.

main benefit is reduced complexity in the build.

see discussion at https://github.com/scala/slip/issues/24#issuecomment-157137761 and https://gitter.im/scala/slip?at=564a3a2e8b242470793e3035 (for HTML generation, Haoyi thought "vendoring a small 1000loc subset of scalatags" was plausible)

also I discussed this with retronym just now and:

- he doesn't recall there being any special reason that the parser-combinators dependency was left in place
- if they'd realized in advance how much work setting up the necessary "build gymnastics" for the circular dependencies would be, they might have considered other approaches, and just because those gymnastics now exist isn't a good reason to keep using them unless really needed
- he says there might be a place in a non-Scaladoc portion of the compiler where there's another not-really-needed dependency on scala-xml; if so, that could be taken care of at the same time

**Comment by ashawley** [comment]
> similarly for XML, except cutting the dependency is harder because we're generating HTML throughout the code.

So presumably the HTML bit is because of Scaladoc.

>there might be a place in a non-Scaladoc portion of the compiler where there's another not-really-needed dependency on scala-xml; if so, that could be taken care of at the same time

Is this talking about XML literals or is there a third situation?

**Comment by SethTisue** [comment]
> So presumably the HTML bit is because of Scaladoc

yup

> Is this talking about XML literals or is there a third situation?

I'm not sure what Jason was thinking when he said that. We can cross that bridge when we come to it, if there's even a river left to cross.

**Comment by SethTisue** [comment]
> scala-library-all resolves the dependencies to add them to the POM / ivy.xml

scala-library-all no longer exists in 2.13, so that's one less thing we need to worry about here

**Comment by ashawley** [comment]
It would seem the compiler could still be built without a scala-xml dependency and preserve XML literal support, but I suppose the issue is being able to rip out the dependency from the compiler test suite, which see scala/scala@5b532e9 is a commit from Adriaan from Nov-14 2013 that put back the tests for scala-xml back when the community module work was done.

It looks like the scala compiler junit test suite doesn't seem to need scala-xml as a dependency.  Presumably, this is because those junit tests were able to be moved to the scala-xml repo.

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/6436 has finished this off.
