### ISSUE TITLE
Allow scaladoc-diff to compare arbitrary tags

### ISSUE THREAD

**Issue by scabug** [scala/bug#9569]
`scaladoc-diff` currently compares HEAD with HEAD~1. While this is useful it would be more useful to be able to anchor the comparison to some ref, and additionally to allow ad-hoc comparisons between two refs.

## Suggested CLI

||Format||Consequence||
|scaladoc-diff|Compare HEAD and HEAD~1|
|scaladoc-diff ref|Compare HEAD and ref|
|scaladoc-diff ref1 ref2|Compare ref1 and ref2|

The second form will be particularly useful when accumulating a set of commits all related to Scaladoc changes.

**Comment by SethTisue** [comment]
while this might still be desirable, I don't think we need to keep the ticket open, scala/bug is focused on end-user things
