### ISSUE TITLE
package focus ineffective

### ISSUE THREAD

**Issue by scabug** [scala/bug#9598]
The focus text does little of value when clicked.

This shows the outcome after clicking it,

- Before clicking:
![scaladoc-focus-before](https://user-images.githubusercontent.com/28076058/33491829-6844d5ac-d689-11e7-9820-959b3422ddac.png)

- After clicking:
![scaladoc-focus-after](https://user-images.githubusercontent.com/28076058/33491838-703e4888-d689-11e7-9d2d-e3633b7e613c.png)

**Comment by SethTisue** [comment]
I don't think the "package focus" thing still exists in current Scaladoc? Let me know if I'm wrong.

The big redesign landed in 2.12.x sometime, so I'll tentatively mark as fixed in 2.12.0.
