### ISSUE TITLE
Document that /: and :\ aren't recommended for use (was: Deprecate /: and :\)

### ISSUE THREAD

**Issue by scabug** [scala/bug#9607]
See http://scala-lang.org/blog/2016/01/02/new-year-resolutions.html.

> Another example, where I have doubts if not regrets are the /: and :\ operators in scala.collections. They are cute synonyms for folds, and I am still fond of the analogy with falling dominoes they evoke. But in retrospect I think maybe they did give a bad example for others to go overboard with symbolic operators.

**Comment by SethTisue** [comment]
@eed3si9n yeah

**Comment by SethTisue** [comment]
separately, someone might add a Scalafix linting rule / rewrite for this.

**Comment by eed3si9n** [comment]
What do you mean by "document not recommended"? Like add English text in Scaladoc?
Isn't deprecation the ultimate form of documentation? Or are we concerned about the migration cost of all existing code vs new code that will be written?

**Comment by SethTisue** [comment]
yes, add English text in Scaladoc.

I wish we could just deprecate; I argued the point with the Scala team; I didn't convince them. see https://github.com/scala/bug/issues/9607#issuecomment-292439426

**Comment by som-snytt** [comment]
/:(

**Comment by Jasper-M** [comment]
I'd go with `:-\` and `/-:`

**Comment by SethTisue** [comment]
heh, well, I wonder who decided that, maybe @julienrf? anyway, yes, a big collections rewrite landing does seem like the time to do it

@longcao thanks for checking on it

**Comment by eshu** [comment]
:( They was so convenient...
