### ISSUE TITLE
Statistics gathering in compiler should be (can be) thread safe

### ISSUE THREAD

**Issue by scabug** [scala/bug#9613]
In cases where compiler is used in some sort of parallel compilation (e.g. sbt)  statistics (if enabled) are gathered in single place. Regardless of statistics being tempered (e.g. thread A and B wants to push/pop timer: A.push B.push, A.pop B.pop and we end in B -> A for A and  A ~~> B for B ~~ instead of tow medium times we got one long and one short time) it can also fails (e.g. match error on popTimer).

**Comment by SethTisue** [comment]
has anything happened with this in recent work on statistics? (@jvican?)

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6326

**Comment by jvican** [comment]
@SethTisue Nothing happened in this area because the use of statistics within the compiler didn't require thread safety. Now, with the introduction of the parallel genbcode, the use case has changed, so I'm happy to see progress on this area in the ticket that Lukas has linked to.

**Comment by romanowski** [comment]
@jvican what about gathering stats from IDE/sbt based compilations that run multiple compilations in parallel? IIRC the problem was that stats was stored in static maps that was shared across all compilations.

**Comment by jvican** [comment]
That was fixed in 2.12.4.
