### ISSUE TITLE
Compilation speed instrumentation per AST element / method / class

### ISSUE THREAD

**Issue by scabug** [scala/bug#9614]
Currently tracking bottle-necks in code compilation is pretty much impossible (especially for improving compilation time by reducing e.g. implicits or macros usage).

What we want is tool to tracking amount of time spend on compiling given node in AST (at best). We are aware that it can be almost impossible for multiple reason:
1. To much information to track - we can also live with method or even class level information
2. Impossible to assign time to given place in AST (e.g. cycle dependencies) - this time can be logged (if possible) as "other"

I know could not be accurate but this should be better then nothing. I think current counters/trimmers should be suitable for this.

**Comment by SethTisue** [comment]
stale ticket, and scala/bug is focused more on bugs than enhancements. but work in this vein is happening, someone want to provide links?
