### ISSUE TITLE
Deprecations from Java may be not taken into account in mixed projects

### ISSUE THREAD

**Issue by scabug** [scala/bug#9617]
There's a problem that deprecations from Java are not taken into account in Scala after parsing Java sources in mixed projects (when they are not yet compiled). I mean that warnings are not generated.

They would be generated only during the incremental compilation (Java files already compiled using javac). It's esp. problematic in case of -Xfatal-warnings as the CI build may pass but users will report problems in Scala IDE or IntelliJ.

The minimal reproduction:

1. Create two files.

J.java
```scala
public class J {
    @Deprecated
    public static void foo() {}
}
```

S.scala
```scala
class S {
  J.foo()
}
```

2. Make project (for the first time) or Rebuild Project. Everything is okay.

3. Now add some blank line in S.scala and start build:

Warning (or obviously Error in case of -Xfatal-warnings):scalac: there was one deprecation warning; re-run with -deprecation for details

4. Then Rebuild Project and, again, there are no warnings.

**Comment by dwijnand** [comment]
Fixed in https://github.com/scala/scala/pull/8781
