### ISSUE TITLE
Binary compatible case class evolution

### ISSUE THREAD

**Issue by scabug** [scala/bug#9627]
Case classes are currently hard to evolve in a binary compatible way. In akka and spray there's a pattern to transport settings in case classes and it would be nice if settings could be added in a binary compatible way. Otherwise, case classes cannot be used and intrusive changes are necessary (e.g. https://github.com/akka/akka/issues/19514).

Let's consider the specific case of adding case class parameters with default values in a binary compatible way.

The compatibility problems I see with this are (please comment if I'm missing something):
 * a new incompatible apply method is generated
 * a new incompatible copy method is generated
 * it isn't possible to create overloads resembling the old methods manually because multiple overloads with default parameters are not allowed

Here's a vague suggestion how it could be done:
 * the idea is to let the compiler generate the old versions of apply/copy automatically in a way that isn't considered for new invocations when the compiler chooses an overload
 * for this, a new parameter with a default value needs to be annotated with {code}@binaryCompatible(<version>){code}
 * in addition to the existing apply/copy methods, for each old version, new synthetic apply/copy method overloads are generated that represent the old version of the class
 * when a library maintainer releases a new binary incompatible version, all those annotations should be removed to prevent the generation of those then useless bridge methods

I guess this needs a SIP but I didn't find an existing issue that would describe the issue.

**Comment by SethTisue** [comment]
This is SIP territory. Closing since it's not immediately actionable, especially in Scala 2. An example of a recent discussion on the subject is https://contributors.scala-lang.org/t/pre-sip-structural-data-structures-that-can-evolve-in-a-binary-compatible-way/5684
