### ISSUE TITLE
Search for external documentation for class files outside of jars.

### ISSUE THREAD

**Issue by scabug** [scala/bug#9635]
When the classpath references a unpackaged (not a jar) directory, scaladoc does not generate links to the url provided via the -doc-external-doc flag.

Pretty sure this fixes it:
https://github.com/jgrean/scala/commit/becc3628086409d1a1f29663865d3227ec5fa2a9

But I need to figure out the testing+PR process, and verify I've used the canonical way to verify a class file is part of a classpath, before I'm ready to submit a PR.

Example Case:
We have two separate scala libraries we're building from source in the same sbt parent project, with nightly scaladoc builds. Currently it's a pain to link them without first packaging the dependency as a jar and referencing that in the dependent project instead of the sbt project.

**Comment by SethTisue** [comment]
hopefully https://github.com/scala/scala/pull/5799 fixed this? if not, speak up
