### ISSUE TITLE
timeout of executor.awaitTermination does not work for ForkJoinPool

### ISSUE THREAD

**Issue by scabug** [scala/bug#9641]
For the description from API for ForkJoinPoll, when we call shutdown method following the awaitTermination(long,TimeUnit), the main thread should not be blocked when the timeout occurs.
But using scala.concurrent.forkjoin.ForkJoinPool, it does not work.
The forkjoin package in Java Library does's occur that problem.

import scala.concurrent.forkjoin._
val exector = new ForkJoinPool()
  exector.execute( new Runnable {
    override def run(): Unit = {
      while(true){}
    }
  })
  exector.shutdown()
  exector.awaitTermination(3l, TimeUnit.SECONDS)

**Comment by NthPortal** [comment]
I think this is fixed by scala/scala#6319, which removes the `scala.concurrent.forkjoin` package.
