### ISSUE TITLE
New REPL doesn't work well in Cygwin

### ISSUE THREAD

**Issue by scabug** [scala/bug#9695]
A couple of things detected:

- No history with up/down arrows
- Semi-random cursor behavior, not easily test-case reproducable, but reproducable when encountered. E.g. typing a particular sequence of characters caused the cursor to jump to the start of the line. This happened every time with that particular string. (Yes, would be nice to have that string, but my console is now closed, and I can't get any history :-) )

**Comment by SethTisue** [comment]
believed fixed in 2.13.2. if not fixed for you, please open a new ticket and be maximally specific about the conditions for reproducing it
