### ISSUE TITLE
remove the use of Option from OpenHashMap

### ISSUE THREAD

**Issue by scabug** [scala/bug#9732]
By replacing the use of `Option` in `OpenHashMap` with a state code stored in an `Array[Byte]`, we can reduce memory usage by about 10%, with mixed effect on the execution time of operations but favoring larger maps.

**Comment by SethTisue** [comment]
closing because we don’t generally keep open tickets on every possible speculative performance improvement idea

regardless, perhaps the idea is valid? I don't know. fyi @scala/collections

**Comment by som-snytt** [comment]
At the linked effort, there is speculation about whether to improve or deprecate or change API in a future 2.13, but in historical 2.13, it was deprecated.

**Comment by SethTisue** [comment]
oh! I checked to see if it even still existed, but did not think to check if it was deprecated. 🙏
