### ISSUE TITLE
Scala Reflection typed Mirror.get

### ISSUE THREAD

**Issue by scabug** [scala/bug#9739]
Hey,

In [Mirrors](https://github.com/scala/scala/blob/2.12.x/src/reflect/scala/reflect/api/Mirrors.scala#L344) we have:
```scala
def get: Any
```
Would it be possible to have instead:
```scala
def get[T]: T
```
?

So that we don't have all the time to do a *.get.asInstanceOf[T]* ?

Maybe even better with a default to _Any_?

```scala
sealed class DefaultsToAny[A]

object DefaultsToAny {
  implicit def overrideDefault[A] = new DefaultsToAny[A]

  implicit def default = new DefaultsToAny[Any]
}
```
and
```scala
def get[T: DefaultToAny]: T
```

**Comment by som-snytt** [comment]
API tweaks are out of scope in Scala 2.
