### ISSUE TITLE
f-interpolator should not inject %s needlessly

### ISSUE THREAD

**Issue by scabug** [scala/bug#9784]
When the f-interpolator winds up just concatenating strings, it should just use StringBuilder instead of String.format. This makes a big difference on scala-js.

These should be equivalent:
```scala
f"My name is $name"
"My name is " + name
```

**Comment by som-snytt** [comment]
Bumping this, because now that s-interpolator is more reasonable, f-interpolator should translate normal interpolation (formatless) to string add. In particular, the semester project to bring f-interpolation to dotty should also do it.
