### ISSUE TITLE
scaladoc continues with bad option

### ISSUE THREAD

**Issue by scabug** [scala/bug#9793]
A bad cli option should hard exit. Instead the bad option is interpreted as a source file containing documentable content.

```scala
11:16 $ ./scaladoc -h
scaladoc error: bad option: '-h'
  scaladoc -help  gives more information
error: source file '-h' could not be found
model contains 1 documentable templates
two errors found
```

**Comment by som-snytt** [comment]
Since I also continue with bad options, I did not so much pick up the issue as it picked me up.
