### ISSUE TITLE
IndexOutOfBoundsException detail message

### ISSUE THREAD

**Issue by scabug** [scala/bug#9797]
Hi,

I've noticed that the IndexOutOfBoundsException only returns the size of the collection as detail message. I think it should be a more detailed message like "size is n, but m is expected".

The class where I found the unfavorable message was scala.collection.LinearSeqOptimized$class.apply

what do you mean, would it be a good idea to change the message?

**Comment by gourlaysama** [comment]
Fixed in scala/scala#7210.
