### ISSUE TITLE
Invalid bytecode signature emitted for field with value class type

### ISSUE THREAD

**Issue by scabug** [scala/bug#9810]
Given the following code, the compiler will create a class file with a signature attribute for the respective field with the field type signature "I". This is not valid byte code according to the JVM 8 Specification. (§4.7.9.1)

```scala
package demo
class PropertyKey[+P] ( final val id: Int) extends AnyVal
class Purity extends AnyRef
object Purity  {
    final val key: PropertyKey[Purity] = new PropertyKey(1)
}
```

Excerpt of the Java Bytecode:

// Compiled from CompilerBug.scala (version 1.6 : 50.0, super bit)
public final class demo.Purity$ {
  // Field descriptor #14 I
  {color:red}*// Signature: I*{color}
  private final int key;
  ...

**Comment by lrytz** [comment]
Check if related to https://github.com/scala/bug/issues/10351 (which has a fix PR)

**Comment by lrytz** [comment]
Fix in https://github.com/scala/scala/pull/5925
