### ISSUE TITLE
scalac should not report warnings for macro generated AST

### ISSUE THREAD

**Issue by scabug** [scala/bug#9852]
I create some macros that may generate some warnings: `a pure expression does nothing in statement position; you may be omitting necessary parentheses`. I hope scalac could stop reporting these warnings.

Warnings usually implies buggy hand-written code. Macro generated code does not fit that case at all.

**Comment by som-snytt** [comment]
How about I close this with the caveat that a handy reporter that makes it easy to suppress warnings would make my previous suggestion more refined? That could be done either globally or by the macro.

The `-Xlint:unused` warnings try to be sensitive as to whether linting before or after expansion is desired.

**Comment by SethTisue** [comment]
https://github.com/scala/scala/pull/8995 improves the situation w/r/t to "a pure expression does nothing in statement position" warnings in particular
