### ISSUE TITLE
A fruitless type test for scala.Singleton succeeds

### ISSUE THREAD

**Issue by scabug** [scala/bug#9867]
```scala
object Main extends App {
  class Baz {
    object Foo
  }

  println((new Baz).Foo.isInstanceOf[Singleton])
}
```
results in
```scala
[warn] /tmp/renderer4uPUlcG0ee/src/main/scala/test.scala:6: fruitless type test: a value of type Main.Baz#Foo.type cannot also be a Singleton
[warn]   println((new Baz).Foo.isInstanceOf[Singleton])
[warn]                                     ^
[warn] one warning found
[success] Total time: 9 s, completed Jul 23, 2016 6:11:33 AM
Now running...
[info] Running Main 
true
```
In fact, `"".isInstanceOf[Singleton]` is `true` as well...

Presumably the problem is that `Singleton` is erased to `Object`. Would it be reasonable to make `isInstanceOf[Singleton]` an error?

**Comment by milessabin** [comment]
We concluded in SIP-23 that since every value is a singleton _dynamically_ and `isInstanceOf` is a _dynamic_ test the behaviour being reported here is correct.

**Comment by hrhino** [comment]
Surely there's still a (smaller) bug in that the compiler warns inaccurately?
