### ISSUE TITLE
NumericRange[Double].contains() doesn't work due to rounding errors

### ISSUE THREAD

**Issue by scabug** [scala/bug#9874]
`NumericRange` is internally implemented by means of arithmetics - causing some trouble when working with doubles:

```scala
val r = 0.0 to 1.0 by 0.1
r.indexOf(r(3))  // => 3
r.contains(r(3)) // => false
```

Problem is that numeric range is a collection - really bad things can happen if someone passes NumericRange where Seq is expected and `contains()` method is used.

**Comment by eed3si9n** [comment]
Sent a PR to collection-strawman - https://github.com/scala/collection-strawman/pull/489

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/6468
