### ISSUE TITLE
List#tails and Stream#tails are extremely inefficient

### ISSUE THREAD

**Issue by scabug** [scala/bug#9892]
List#tails inherits its implementation from TraversableLike which creates lots of new Lists:

```scala
val ts = List(1,2,3).tails.toList
ts(0).tail eq ts(1) // false
```

**Comment by SethTisue** [comment]
note that in the abandoned PR, it came up that `Stream` has the same bug

**Comment by Ichoran** [comment]
Which probably means that `Queue` and `LinkedListMap` and so on are also all suspect.

**Comment by som-snytt** [comment]
`iterateUntilEmpty(_.tail)` is the story of my life. I couldn't find the t-shirt for that on the scala store.

**Comment by SethTisue** [comment]
scala/scala#5950 fixes it at the `LinearSeqOptimized` level rather than trying for the `TraversableLike` fix. this could be revisited in the 2.13 collections

**Comment by SethTisue** [comment]
scala/scala#5950 included tests, so I think it was just inadvertent that this ticket wasn't closed when that was merged

**Comment by SethTisue** [comment]
@hodga after accepting my invitation to https://github.com/orgs/scala/teams/contributors, comment here, and I'll assign this ticket to you

**Comment by hodga** [comment]
@SethTisue I accepted the invitation :)
