### ISSUE TITLE
scanLeft (and right) for TraversableViewLike is very ineffective

### ISSUE THREAD

**Issue by scabug** [scala/bug#9902]
Now implementation of scanLeft for TraversableViewLike is this

```java
override def scanLeft[B, That](z: B)(op: (B, A) => B)(implicit bf: CanBuildFrom[This, B, That]): That =
    newForced(thisSeq.scanLeft(z)(op)).asInstanceOf[That]
```

It goes to calculate all the collection when we call some method of the "view". But it is not the way, because we may want to take only a part of collection with "takeWhile" or "find" or "indexWhere". It should be implemented like "foldLeft" for "views"—using "foreach" call. But better potential implementations of many view's methods are with "iterator". And it should not be forced—it is a "view" after all. All the operations should be lazy. 

Now it is 100 times slower than it should be.

Probably, they are another view methods, these have non-lazy implementations.

**Comment by SethTisue** [comment]
closing since everything is changing in the 2.13 collections. someone with an interest in this ticket could verify whether it still exists in scala/collection-strawman now, or wait for Scala 2.13.0-M4 to land (when collection-strawman will be merged) and check it then.

**Comment by NthPortal** [comment]
This is fixed in strawman.

`Traversible` is deprecated in strawman, and `Iterable` should be used instead. `TraversibleViewLike` no longer exists; its closest replacement, `IterableOps.scanLeft`, is implemented lazily.
