### ISSUE TITLE
VectorBuilder should allow access to current element count

### ISSUE THREAD

**Issue by scabug** [scala/bug#9904]
Currently `VectorBuilder` doesn't allow access to the current element count which forces one to keep external counters in all cases where this information is important.

The proposal is to add these three methods to the `VectorBuilder` class:

```scala
    def size: Int = blockIndex + lo
    def isEmpty: Boolean = size == 0
    def nonEmpty: Boolean = size != 0
```

**Comment by eed3si9n** [comment]
https://github.com/scala/scala/pull/5489 was sent for this, and was closed:

> All collections stuff is likely to get overhauled as part of the https://github.com/scala/collection-strawman, so at the moment, I don't think it would make sense to accept this (or to leave it in the queue). We can always revisit/reopen later.

**Comment by SethTisue** [comment]
would someone like to look and see if this is already fixed in strawman or not...?

**Comment by NthPortal** [comment]
It is not yet fixed in strawman ([as of now](https://github.com/scala/collection-strawman/blob/a42fc3d03452ec52a76f10634cb17369376255e7/collections/src/main/scala/strawman/collection/immutable/Vector.scala#L620-L659)).

I can PR it if desired.
