### ISSUE TITLE
MatchError for Iterable not caught by compiler

### ISSUE THREAD

**Issue by scabug** [scala/bug#9905]
The following code snippet compiles just fine on 2.10.4 but causes a `MatchError` at runtime because the Iterable `m.keys` uses a `Set`, which does not have the `Cons` operator like lists.

```scala
val m = Map(0 -> false, 1 -> true)
m.keys match {
  case Nil => "oops"
  case x :: xs => "ok"
}
```

**Comment by SethTisue** [comment]
since 2.13.4, this gives an exhaustiveness warning under `-Xlint`
