### ISSUE TITLE
Emitting advice that compiles

### ISSUE THREAD

**Issue by scabug** [scala/bug#9908]
It would be nice if it were easy for the compiler to emit snippets that necessarily compiled.

```scala
[error] /** As seen from class string is option name, the missing signatures are as follows.
[error]  *  For convenience, these are usable as stub implementations.
[error]  */
[error]   def --?: Boolean = ???
```

Whatever the word is for the syntactic category of colon, the advice should compile.

**Comment by lrytz** [comment]
https://github.com/scala/scala/pull/8770
