### ISSUE TITLE
Incorrectly reported missing class error on Java nested static class

### ISSUE THREAD

**Issue by scabug** [scala/bug#9938]
I'm receiving this error:

```
[error] missing or invalid dependency detected while loading class file 'InternalTopic.class'.
[error] Could not access type TopicId in trait com.lightbend.lagom.javadsl.api.broker.Topic,
[error] because it (or its dependencies) are missing. Check your build definition for
[error] missing or conflicting dependencies. (Re-run with `-Ylog-classpath` to see the problematic classpath.)
[error] A full rebuild may help if 'InternalTopic.class' was compiled against an incompatible version of com.lightbend.lagom.javadsl.api.broker.Topic.
[error] one error found
```

For a class that exists.  The class in question is here:

https://github.com/lagom/lagom/blob/master/api/src/main/java/com/lightbend/lagom/javadsl/api/broker/Topic.java

You can see its a java interface with a nested class.  Then the InternalTopic.scala is here:

```
trait InternalTopic[Message] extends Topic[Message] {
  final override def topicId(): TopicId = throw new UnsupportedOperationException("Topic#topicId is not permitted in the service's topic implementation")

  final override def subscribe(): Subscriber[Message] =
    throw new UnsupportedOperationException("Topic#subscribe is not permitted in the service's topic implementation.")
}
```

(full source including imports here: https://github.com/jroper/lagom/blob/4579e11b9d794ff159cee65b6c220b72b0710568/api/src/main/scala/com/lightbend/lagom/internal/api/InternalTopicCall.scala#L50)

The issue can be fixed by replacing the TopicId reference with Topic.TopicId.

**Comment by som-snytt** [comment]
Duplicates https://github.com/scala/bug/issues/1409
