### ISSUE TITLE
"opchar" definition messed up? (like "x = not x")

### ISSUE THREAD

**Issue by scabug** [scala/bug#9947]
In the syntax summary chapter, non-terminal `opchar` is specified as:

```
opchar           ::= // printableChar not matched by (whiteSpace | upper | lower |
                     // letter | digit | paren | delim | opchar | Unicode_Sm | Unicode_So)
```

Note how `opchar` appears in that "... not matched by ..." list.  

As currently constructed, isn't that saying that `opchar` can produce only characters that are not characters produced by `opchar`?  That is, isn't that a contradiction (well, unless something else excluded all of `printableChar`)?

Shouldn't `opchar` be removed from that list?

Also, are the references to Unicode character categories in the wrong place?  (It's not fully clear whether the `opchar` definition means to include Sm and So characters or exclude them.)

**Comment by magnolia-k** [comment]
If printableChar can only take in the range from \u0020 to \u007F, then the specification to exclude Unicode_Sm and Unicode_So is not necessary in the first place, isn't it?

In other words, shouldn't we define it as follows

```
opchar           ::= printableChar not matched by (whiteSpace | upper | lower | letter | digit | paren | delim)
```

The syntax summary in Scala3 does not change anything here, but it may need to be changed as well.

At least opchar and Unicode_Sm need to be removed to be consistent with the actual behavior.

**Comment by som-snytt** [comment]
The improvement was https://github.com/scala/scala/pull/9243, perhaps there are other specifying improvements. Probably they should be lodged against Scala 3, where the implementation can be checked.
