### ISSUE TITLE
scala.sys.env should be case-insensitive on Windows

### ISSUE THREAD

**Issue by scabug** [scala/bug#9957]
`java.lang.System.getenv` is case-insensitive on Windows. Shall we follow its behavior?

**Comment by SethTisue** [comment]
currently `env` returns a `Map`. in order to make it case-insensitive, we'd have to add new API. in 2.13, `scala.sys` will become its own module, at which point this could be addressed if someone cares to.

closing since scala.sys issues will no longer be tracked here in scala/bug. I've made a "module:scala.sys" label so we can find relevant issues once the module has its own repo

**Comment by stefanobaghino** [comment]
@SethTisue Is this still the relevant place to talk about this? I've noticed the issue today by chance and I was thinking to use `System.getenv(String)` (which behaves correctly on Windows), doing something along these lines, so to not have to add a new API or introduce a breaking change (signature-wise, at least, I hope no one is relying on this behavior, which I believe can be anyhow considered incorrect):

```scala
  private object Env extends immutable.Map[String, String] {

    override def +[V1 >: String](kv: (String, V1)): Map[String, V1] =
      iterator.toMap + kv

    override def get(key: String): Option[String] =
      Option(System.getenv(key))

    override def iterator: Iterator[(String, String)] =
      JavaConverters.mapAsScalaMap(System.getenv()).iterator

    override def -(key: String): Map[String, String] =
      iterator.toMap - key

  }

  /** An immutable Map representing the current system environment.
   *
   *  @return   a Map containing the system environment variables.
   */
  val env: immutable.Map[String, String] = Env
```

I noticed that `env` is currently a `def`, so it may be desirable to turn `Env` in a `final class` and `env` back to a `def`, but the reason behind it is unclear to me (maybe something related to the behavior of the Java runtime but I'm not sure).

**Comment by stefanobaghino** [comment]
If this is not the right place to discuss about this I'd be very happy to move the discussion somewhere else. :wink:

**Comment by som-snytt** [comment]
There is a [code comment](https://github.com/scala/scala/blob/v2.13.1/src/library/scala/sys/package.scala#L57) suggesting they want to remove the related `SystemProperties` map in favor of a simple forwarder to `getProperty`.

I'd expect the same thinking to apply here, with the additional prejudice that the semantics for case-sensitivity are strange.

An updated map would lose its special get.

Interacting with process environment is via `processBuilder.environment` in java and scala.sys.process just lets you supply extra env mappings.

The proposed solution does have the virtue of not changing the API.

**Comment by Atry** [comment]
Shall we just add a `withDefault` to the original map?
https://github.com/scala/scala/pull/8508

**Comment by som-snytt** [comment]
I couldn't think of how it wouldn't be weird asymmetry, "`get` didn't return my `"shell"`."  "You have to use `apply`." "Oh, yeah."

**Comment by Atry** [comment]
Your argument applies to all usage of `withDefault`.

**Comment by Atry** [comment]
> I couldn't think of how it wouldn't be weird asymmetry, "get didn't return my "shell"." "You have to use apply." "Oh, yeah."

It's exact the same behavior as Java `System.getenv`

**Comment by som-snytt** [comment]
I agree with the previous comments, that conventionally you'd use `apply` for the special "platform-specific" behavior. I'm too lazy to exercise the behavior, as I am lying in bed with my Mac and not sitting out in the other room with the test bed windoze box.
