### ISSUE TITLE
Initialization order - calling `apply` method from `val` in case class companion object

### ISSUE THREAD

**Issue by scabug** [scala/bug#9971]
The following produces a stack-overflow:

```scala
object InitBug {
  def main(args: Array[String]): Unit = {
    object Foo {
      val bar = Foo()
    }
    case class Foo()
    
    Foo.bar
  }
}
```

**Comment by SethTisue** [comment]
these days Dotty gives `StackOverflowError`

**Comment by SethTisue** [comment]
Scala 3 ticket is https://github.com/lampepfl/dotty/issues/13162

**Comment by som-snytt** [comment]
There are suggestions on both scala and dotty tickets that the behavior is an implementation detail, but it is specified quite narrowly.

https://scala-lang.org/files/archive/spec/2.13/05-classes-and-objects.html#object-definitions

Note that the "lazy val" paradigm is paradigmatic, and top-level objects are the deviation.

This commit only fixes the bug mentioned above and elsewhere. I was mistaken that order of the companions makes a difference, or that behavior has improved, or maybe I was commenting only on the specification.
