### ISSUE TITLE
ambiguous implicit when constraint is of kind * -> *

### ISSUE THREAD

**Issue by scabug** [scala/bug#9991]
The following gist illustrates a problem I encountered recently: https://gist.github.com/julien-truffaut/d15e532443fa8174acc1d3c64194ffab

I can define instances for a typeclass with different constraints without the need to use low priority implicits if the constraint is based on type of kind * (here `Yo` with `Semigroup` / `Monoid` constraints). However, if the constraint is based on a kind * ->* (here `YoT` with `Functor` / `Applicative` constraints), I get an ambiguous implicit.

It would be nice if the behaviour were consistent and preferably not requiring low priority implicits.

Thanks

I tested the snippet using scala 2.11.8

**Comment by gourlaysama** [comment]
This was fixed in scala/scala#6122, though how the fix does that goes way above my head, there are no aliases here.

This can probably be closed...?

**Comment by SethTisue** [comment]
@julien-truffaut if you disagree, squawk
